// Shared helpers for the file-based library.
//
// Source of truth (edit these, one file per aesthetic — contributor friendly):
//   data/aesthetics/<slug>.json
//   data/relations.json
// Build output (generated by scripts/data/build.ts, deployed as static files):
//   public/data/*
import { mkdirSync, readdirSync, readFileSync, renameSync, unlinkSync, writeFileSync, existsSync } from 'node:fs'
import { createHash } from 'node:crypto'
import path from 'node:path'
import type { AestheticRecord, RelationRecord } from '../../src/lib/schema.ts'

export const ROOT = path.join(import.meta.dirname, '..', '..')
export const SRC_DIR = path.join(ROOT, 'data', 'aesthetics')
export const RELATIONS_JSON = path.join(ROOT, 'data', 'relations.json')
export const OUT_DIR = path.join(ROOT, 'public', 'data')
export const CACHE_DIR = path.join(ROOT, 'data', '.cache')

/** Stable key order for every record file (keeps git diffs readable). */
export const KEY_ORDER = [
  'slug', 'name', 'aliases', 'category', 'subcategory', 'establishment', 'status', 'confidence',
  'origin', 'geography', 'periodStart', 'periodEnd', 'startYear', 'endYear', 'era',
  'summary', 'description', 'culturalContext',
  'colors', 'paletteSource', 'visualDNA', 'typography', 'typePairing', 'materials', 'textures', 'lighting', 'photography',
  'architecture', 'fashion', 'objects', 'environment', 'graphicDesign', 'uiTranslation', 'recipe',
  'emotionProfile', 'dnaAxes', 'keyExamples', 'sounds', 'tags',
  'images', 'audio', 'sources', 'references', 'wikidata', 'wikipedia',
  'popularity', 'isNiche', 'dataQuality', 'verifiedAt', 'createdAt', 'updatedAt',
] as const

export function orderKeys<T extends Record<string, unknown>>(rec: T): T {
  const out: Record<string, unknown> = {}
  for (const k of KEY_ORDER) if (k in rec) out[k] = rec[k]
  for (const k of Object.keys(rec)) if (!(k in out)) out[k] = rec[k]
  return out as T
}

export function loadAesthetics(): AestheticRecord[] {
  return readdirSync(SRC_DIR)
    .filter((f) => f.endsWith('.json'))
    .sort()
    .map((f) => {
      const rec = JSON.parse(readFileSync(path.join(SRC_DIR, f), 'utf8'))
      ;(rec as { __file?: string }).__file = f
      return rec
    })
}

export function loadRelations(): RelationRecord[] {
  return JSON.parse(readFileSync(RELATIONS_JSON, 'utf8'))
}

export function loadLibrary() {
  return { aesthetics: loadAesthetics(), relations: loadRelations() }
}

function atomicWrite(file: string, text: string) {
  const tmp = `${file}.tmp`
  writeFileSync(tmp, text)
  // Windows: watchers/antivirus can briefly lock the target — retry, then fall back to a direct write.
  for (let i = 0; i < 8; i++) {
    try {
      renameSync(tmp, file)
      return
    } catch (e) {
      if ((e as NodeJS.ErrnoException).code !== 'EPERM' && (e as NodeJS.ErrnoException).code !== 'EBUSY') throw e
      Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, 50 * (i + 1))
    }
  }
  writeFileSync(file, text)
  unlinkSync(tmp)
}

/** Write one record to data/aesthetics/<slug>.json (renaming the file if the slug changed). */
export function saveAesthetic(rec: AestheticRecord) {
  mkdirSync(SRC_DIR, { recursive: true })
  const { __file, ...clean } = rec as AestheticRecord & { __file?: string }
  const file = `${clean.slug}.json`
  atomicWrite(path.join(SRC_DIR, file), JSON.stringify(orderKeys(clean), null, 2) + '\n')
  if (__file && __file !== file && existsSync(path.join(SRC_DIR, __file))) unlinkSync(path.join(SRC_DIR, __file))
  ;(rec as { __file?: string }).__file = file
}

export function saveRelations(relations: RelationRecord[]) {
  const sorted = [...relations].sort((a, b) =>
    a.from === b.from ? (a.to === b.to ? a.type.localeCompare(b.type) : a.to.localeCompare(b.to)) : a.from.localeCompare(b.from)
  )
  atomicWrite(RELATIONS_JSON, JSON.stringify(sorted, null, 1) + '\n')
}

export function saveLibrary(aesthetics: AestheticRecord[], relations?: RelationRecord[]) {
  for (const a of aesthetics) saveAesthetic(a)
  if (relations) saveRelations(relations)
}

export const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms))

export const USER_AGENT =
  'Aestheticpedia/1.0 (https://github.com/Sidmaz666/aestheticpedia; open aesthetics encyclopedia) node'
/** The Art Institute of Chicago serves its IIIF images only to clients that identify themselves
 *  with this header (https://api.artic.edu/docs/#introduction). Empty for every other host. */
export const aicHeaders = (url: string): Record<string, string> =>
  /^https:\/\/(www|api)\.artic\.edu\//.test(url) ? { 'AIC-User-Agent': 'Aestheticpedia (https://github.com/Sidmaz666/aestheticpedia)' } : {}

/** fetch JSON with retry/backoff on 429/5xx. */
export async function getJSON<T = any>(url: string, tries = 5, init: RequestInit = {}): Promise<T> {
  let wait = 1500
  for (let i = 0; ; i++) {
    try {
      const res = await fetch(url, {
        signal: AbortSignal.timeout(90_000),
        ...init,
        headers: { 'User-Agent': USER_AGENT, Accept: 'application/json', ...(init.headers ?? {}) },
      })
      if (res.ok) return (await res.json()) as T
      if ((res.status === 429 || res.status >= 500) && i < tries) {
        const ra = Number(res.headers.get('retry-after'))
        await sleep(ra ? ra * 1000 : wait)
        wait *= 2
        continue
      }
      throw new Error(`HTTP ${res.status} for ${url}`)
    } catch (e) {
      if (i >= tries || String(e).includes('HTTP 4')) throw e
      await sleep(wait)
      wait *= 2
    }
  }
}

/** Run async jobs with bounded concurrency. */
export async function pool<T>(items: T[], n: number, fn: (item: T, i: number) => Promise<void>) {
  let next = 0
  await Promise.all(
    Array.from({ length: Math.min(n, items.length) }, async () => {
      while (next < items.length) {
        const i = next++
        await fn(items[i], i)
      }
    })
  )
}

export function slugify(s: string): string {
  return s
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/&/g, ' and ')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

/** Simple JSON cache on disk for API responses (keeps re-runs cheap and polite). */
export function cache<T>(ns: string) {
  const dir = path.join(CACHE_DIR, ns)
  mkdirSync(dir, { recursive: true })
  const key = (k: string) => path.join(dir, createHash('sha1').update(k).digest('hex').slice(0, 20) + '.json')
  return {
    get(k: string): T | undefined {
      try {
        return JSON.parse(readFileSync(key(k), 'utf8'))
      } catch {
        return undefined
      }
    },
    set(k: string, v: T) {
      writeFileSync(key(k), JSON.stringify(v))
    },
  }
}
