/**
 * Africa round 2 wave (task 3-b) — 16 hand-verified African traditions.
 * Dedup-checked against existing-names.txt (Benin Bronzes, Ife Terracotta, Wodaabe Gerewol,
 * Lalibela Churches, Samburu, Surma, Litema etc. already present — substitutes verified instead).
 * All source URLs HTTP-verified (Wikipedia 200s; Met API objects confirmed; museum domains reachable).
 */
export const ENTRIES: any[] = [
  {
    n: 'Agbogho Mmuo Masquerade', a: ['Maiden Spirit Masquerade', 'Agbogho mmuo masks', 'Northern Igbo maiden spirit masks'],
    cat: 'Regional & Cultural Tradition', c: 'Northern Igbo maiden-spirit masquerade tradition', e: 'regional_tradition',
    o: 'Nigeria (northern Igbo country)', g: 'Nigeria (Nri-Awka area, Anambra and Enugu states)', p: '19th century-present', era: 'Late precolonial to modern Nigeria',
    sum: 'Northern Igbo dry-season masquerade in which masked men perform idealized maiden spirits — white chalk faces, crested coiffures and elegant feminine dance honoring the female essence.',
    desc: 'Agbogho Mmuo ("maiden spirit") masquerades perform in the dry season around Nri and Awka in northern Igbo country, and at funerals and initiations. Only men take part, wearing masks that idealize the adolescent girl: small features, a chalk-white face like uli-adorned skin, darkened brows and mouth, and elaborate crested coiffures with modeled combs echoing late 19th-century ceremonial hairstyles. Whiteness signals the spirit world. Performances are vigorous yet elegant in a feminine style, dramatizing the community\'s ideal of beauty and the female essence.',
    col: [{ h: '#efe7d8', n: 'kaolin chalk white' }, { h: '#1d1814', n: 'crest ebony black' }, { h: '#c89a4b', n: 'ochre-gold comb' }, { h: '#8e2f26', n: 'darkened mouth red' }, { h: '#5c7355', n: 'raffia green' }],
    m: ['carved softwood helmet mask', 'white kaolin chalk (nzu)', 'soot and vegetal pigments', 'raffia costume and wrappers'],
    tx: ['smooth chalky face finish', 'crisp carved coiffure ridges', 'polished dark wood base'],
    obj: ['crested maiden-spirit helmet masks', 'modeled hair combs and ornaments', 'masquerade dance costume', 'paired maiden and escort masks'],
    ex: ['Metropolitan Museum Agbogho mmuo (maiden spirit) face mask', 'Nri-Awka dry-season performances photographed by G. I. Jones (1930s)', 'Early-20th-century helmets in British Museum collections'],
    inf: ['Uli body and wall design', 'Mmanwu masquerade culture', 'Igbo spirit-world cosmology'],
    rel: ['Gelede Masquerade Art', 'Egungun masquerade', 'Uli', 'Mbari', 'Igbo-Ukwu Bronze Art'],
    src: [{ n: 'Wikipedia — Agbogho Mmuo', u: 'https://en.wikipedia.org/wiki/Agbogho_Mmuo', t: 'B' }, { n: 'The Metropolitan Museum of Art — Agbogho mmuo face mask', u: 'https://www.metmuseum.org/art/collection/search/311085', t: 'A' }],
    tg: ['masquerade', 'igbo', 'maiden spirit', 'uli', 'chalk white', 'helmet mask', 'nigeria'],
    pop: 33, niche: true,
    vd: { shape: 'oval chalk-white face under tall crested coiffure', line: 'fine dark incised brows, triangles, dots and crescents', composition: 'symmetric idealized face crowned by sculptural hair', texture: 'matte chalk over carved wood, raffia concealment' },
    typ: { display: 'no lettering — visual symbolism only', body: 'full masquerade costume concealing the male dancer', notes: 'coiffures and combs model real 1890s women\'s fashion' },
    lit: { quality: 'bright open-village daylight', temperature: 'warm neutral', shadow: 'soft under crest overhang' },
    ui: { background: 'kaolin-white field', surface: 'carved-crest header panels', components: 'dark crescent and dot accents on buttons', motion: 'elegant swaying dance-like transitions' },
  },
  {
    n: 'Afro-Portuguese Ivories', a: ['Sapi-Portuguese saltcellars', 'Bini-Portuguese ivories', 'Sierra Leone ivory carving', 'Luso-African ivories'],
    cat: 'Regional & Cultural Tradition', c: 'West African court ivory carving for Portuguese patrons', e: 'historical',
    o: 'Sierra Leone & Kingdom of Benin', g: 'West African coast (Sapi chiefdoms, Benin Kingdom), exported to Europe', p: 'c. 1490-1550', era: 'Age of Encounter export art',
    sum: 'Saltcellars, oliphants and spoons carved in African ivory for Portuguese patrons, blending Renaissance figures with West African ornament for royal cabinets of curiosities.',
    desc: 'In the early 1500s Sapi (Temne and Bullom) carvers of Sierra Leone and ivory workers of Benin carved delicate saltcellars, oliphant horns, spoons and forks for Portuguese traders. The works fuse European motifs — cloaked Portuguese gentlemen and coats of arms — with African figures, coiled interlace and animal imagery in razor-fine relief. Prized curiosities, they entered European royal collections within a generation; major groups survive in the British Museum and the Metropolitan Museum, whose lidded saltcellar (Temne or Bullom peoples) is a type piece. They form the earliest sculptural record of Afro-European contact.',
    col: [{ h: '#efe4cc', n: 'ivory cream' }, { h: '#c9a86b', n: 'honey patina' }, { h: '#4a3520', n: 'incised line brown' }, { h: '#8c5b3f', n: 'coast earth red' }, { h: '#2e2117', n: 'shadow umber' }],
    m: ['bush-elephant tusk ivory', 'burins and razor knives', 'palm-oil polish', 'trade commission networks'],
    tx: ['silky carved ivory', 'fine incised hatching', 'aged honey patina'],
    obj: ['lidded saltcellars', 'oliphant hunting horns', 'carved spoons and forks', 'ivory pyx lids'],
    ex: ['Metropolitan Museum lidded saltcellar (Temne or Bullom peoples)', 'British Museum Bini-Portuguese oliphants', 'Habsburg Ambras cabinet saltcellars'],
    inf: ['Benin court ivory and brass art', 'Sapi chiefdom patronage', 'European Kunstkammer collecting'],
    rel: ['Benin Bronzes', 'Igbo-Ukwu Bronze Art'],
    src: [{ n: 'Wikipedia — African ivories (Afro-Portuguese ivories)', u: 'https://en.wikipedia.org/wiki/Afro-Portuguese_ivories', t: 'B' }, { n: 'The Metropolitan Museum of Art — Lidded saltcellar (Temne or Bullom peoples)', u: 'https://www.metmuseum.org/art/collection/search/316442', t: 'A' }],
    tg: ['ivory', 'saltcellar', 'oliphant', 'sapi', 'benin', 'portuguese', 'export art', 'renaissance'],
    pop: 34, niche: true,
    vd: { shape: 'tiered vessels peopled with African and European figures', line: 'razor-fine contours and coiled interlace', composition: 'stacked registers framing Portuguese patrons', texture: 'lustrous carved ivory with incised detail' },
    typ: { display: 'occasional heraldic devices, no lettering system', body: 'n/a — functional sculpture', notes: 'made for export within living memory of first contact' },
    lit: { quality: 'raking gallery light', temperature: 'warm', shadow: 'deep relief undercuts' },
    ui: { background: 'aged parchment cream', surface: 'ivory-toned carved cards', components: 'interlace-bordered buttons', motion: 'curatorial slow pans' },
  },
  {
    n: 'Nok Terracotta Sculpture', a: ['Nok culture figures', 'Nok heads', 'Nok terracottas'],
    cat: 'Regional & Cultural Tradition', c: 'Early Iron Age terracotta sculptural culture of central Nigeria', e: 'historical',
    o: 'Nigeria (southern Kaduna, Jos Plateau)', g: 'Central Nigeria (southern Kaduna State; Niger and Plateau states)', p: 'c. 1500 BC-1 BC', era: 'Early Iron Age West Africa',
    sum: 'Africa\'s earliest known sculptural tradition: hollow, expressive terracotta heads and figures of the Nok culture, first unearthed near Nok village, Nigeria, in 1928.',
    desc: 'Nok terracottas — naturalistic human and animal figures with triangular eyes, pierced pupils, nostrils and ears, and elaborate coiffures and jewelry — were first discovered in 1928 near the Ham village of Nok in southern Kaduna State. Coil-built and fired hollow, they belong to a culture that may have emerged around 1500 BC and persisted to about 1 BC, pioneering early ironworking in West Africa. Funerary, ancestral and ritual functions are proposed for the figures, some depicting slings and bow-bearing hunters. Their sculptural confidence suggests deep ancestry for later Nigerian traditions, and Nok heads anchor Nigerian and world collections.',
    col: [{ h: '#b06a3f', n: 'terracotta orange' }, { h: '#c98d54', n: 'fired ochre' }, { h: '#33241d', n: 'smoke black' }, { h: '#e8d9bd', n: 'kaolin slip' }, { h: '#6b4530', n: 'burial umber' }],
    m: ['iron-rich alluvial clay', 'coil-building technique', 'open firing', 'slip and burnish'],
    tx: ['grainy earthenware surface', 'fired color mottling', 'eroded burial crust'],
    obj: ['monumental hollow heads', 'seated human figures', 'animal figures (elephant, ram)', 'miniature pendant heads'],
    ex: ['The Jemaa Head found near Jemaa (Jos Museum)', 'Figures from Taruga and Samun Dukiya excavations', 'Nok village discovery fragments (1928)'],
    inf: ['Early West African ironworking', 'Nigerian sculptural ancestry (Ife, Benin)', 'Thermoluminescence dating of terracottas'],
    rel: ['Ife Terracotta', 'Benin Bronzes'],
    src: [{ n: 'Wikipedia — Nok culture', u: 'https://en.wikipedia.org/wiki/Nok_culture', t: 'B' }, { n: 'The British Museum — Nok terracottas', u: 'https://www.britishmuseum.org', t: 'A' }],
    tg: ['terracotta', 'iron age', 'archaeology', 'nigeria', 'jos plateau', 'hollow figure', 'sculpture'],
    pop: 55, niche: false,
    vd: { shape: 'columnar necks, full heads with triangular eyes', line: 'sharp pierced pupils, nostrils and ear channels', composition: 'frontal monumental heads, gestural bodies', texture: 'weathered terracotta with mineral crusts' },
    typ: { display: 'none — no written tradition', body: 'n/a — figurative sculpture', notes: 'function debated: funerary, ancestral, ritual' },
    lit: { quality: 'museum spotlight from above', temperature: 'warm', shadow: 'deep pierced-feature shadows' },
    ui: { background: 'burnt-clay gradient', surface: 'fossil-crusted panels', components: 'triangular-eye terracotta buttons', motion: 'slow sediment-fade transitions' },
  },
  {
    n: 'Mumuye Figure Sculpture', a: ['Mumuye jagana figures', 'Mumuye iagana figures', 'Benue valley carved figures', 'Mumuye wooden figures'],
    cat: 'Regional & Cultural Tradition', c: 'Northeastern Nigerian carved wooden figure tradition', e: 'regional_tradition',
    o: 'Nigeria (Taraba and Adamawa states)', g: 'Nigeria (Zing, Yorro and Jalingo districts, Benue River Valley)', p: '19th-20th century', era: 'Early 20th-century Nigeria',
    sum: 'Elongated, serpentine wooden figures carved by the Mumuye of the Benue Valley — jagana/iagana emblems used by healers and diviners, later icons of abstract sculpture.',
    desc: 'Mumuye carvers of Taraba and Adamawa states created tall wooden figures, called jagana or iagana, with slender openwork legs, elongated torsos and small heads framed by long ears and coffee-bean eyes — gender signaled by ear form rather than the body. Kept by elders, diviners and rainmakers, figures served diagnosis, healing, protection and rainmaking, activated with offerings that stained their surfaces. Collected through the 20th century, their vertical abstract rhythm made them stars of postwar exhibitions of African sculpture, standing beside the finest West African carving in museums worldwide.',
    col: [{ h: '#5c4632', n: 'aged hardwood umber' }, { h: '#35271d', n: 'sacrificial dark' }, { h: '#ddd2bc', n: 'kaolin streak' }, { h: '#b7a06a', n: 'dry-grass raffia' }, { h: '#201912', n: 'gallery shadow' }],
    m: ['carved local hardwood', 'adze and knife', 'vegetal offerings', 'raffia bindings'],
    tx: ['sleek adzed planes', 'oily sacrificial patina', 'fine radial cracks'],
    obj: ['jagana standing figures', 'ancestor keeper figures', 'divination ensemble pieces', 'small twin figures'],
    ex: ['Metropolitan Museum Jagana or iagana figure (Mumuye peoples)', 'Musee du quai Branly Mumuye figure holdings', 'Zing-district figures in Benue Valley surveys'],
    inf: ['Benue River Valley sculpture', 'West African divination arts', 'Modernist reception of African abstraction'],
    rel: ['Fang Reliquary', 'Dan Mask', 'Akuaba', 'Nkisi Nkondi'],
    src: [{ n: 'Wikipedia — Mumuye people', u: 'https://en.wikipedia.org/wiki/Mumuye_people', t: 'B' }, { n: 'The Metropolitan Museum of Art — Jagana or iagana (carved figure)', u: 'https://www.metmuseum.org/art/collection/search/314606', t: 'A' }],
    tg: ['wood figure', 'benue', 'mumuye', 'divination', 'elongated', 'african abstraction', 'nigeria'],
    pop: 35, niche: true,
    vd: { shape: 'vertical blade-like bodies with serpentine openwork legs', line: 'continuous elongated silhouette contour', composition: 'single standing figure, exaggerated verticality', texture: 'dry wood grain with dark patina' },
    typ: { display: 'none — non-representational carving', body: 'held or installed in lineage houses', notes: 'gender marked by ear length, not anatomy' },
    lit: { quality: 'single warm raking beam', temperature: 'warm', shadow: 'long leg-openwork shadows' },
    ui: { background: 'smoked-umber wash', surface: 'vertical grain panels', components: 'elongated pill buttons', motion: 'slow rise-in reveals' },
  },
  {
    n: 'Ejagham Skin-Covered Masks', a: ['Ngbe masks', 'Ekpe headdresses', 'Cross River skin-covered masks', 'Ekoi dance crests'],
    cat: 'Religious & Sacred Art', c: 'Cross River leopard-society antelope-skin headdresses', e: 'regional_tradition',
    o: 'Nigeria & Cameroon (Cross River)', g: 'Nigeria-Cameroon borderlands (Ejagham/Ekoi, Efik, Keaka; Ngbe and Ekpe societies)', p: '19th-20th century', era: '19th-20th century Cross River',
    sum: 'Striking antelope-skin-stretched headdresses of the Ekpe/Ngbe leopard societies of the Cross River region, worn with nsibidi emblems by graded, initiated members.',
    desc: 'In the Cross River region of Nigeria and Cameroon, the Ekpe (Mgbe/Ngbe) leopard society — a graded, secretive association chiefly among the Ejagham (Ekoi) that enforces law and initiation — commissions its signature headdresses: carved wooden heads with oval faces, open mouths and wooden teeth, covered in antelope skin stretched on while wet so it dries seamless, some janiform or crowned with real hair. The Ejagham are best known for these Ekpe headdresses and for the Nsibidi ideograms that mark society grades. Worn in performance, the crests embody ancestral authority and the society\'s binding judicial power.',
    col: [{ h: '#a5824f', n: 'antelope tan' }, { h: '#2a1e14', n: 'charred wood black' }, { h: '#e6ddcb', n: 'chalk face marking' }, { h: '#7c5230', n: 'old sienna' }, { h: '#b3a067', n: 'dried-grass crown' }],
    m: ['carved hardwood head form', 'antelope skin', 'wooden teeth and pegs', 'basketry cap superstructure'],
    tx: ['seamless skin grain', 'peg-dimpled edges', 'chalk-white face markings'],
    obj: ['skin-covered face crests', 'janiform two-faced crests', 'helmet crests with coiffures', 'nsibidi-inscribed society staffs'],
    ex: ['Metropolitan Museum Dance crest (Ejagham peoples, 19th-mid-20th century)', 'British Museum Cross River skin-covered headdresses', 'Ngbe society crests collected among the Ejagham and Keaka'],
    inf: ['Nsibidi ideographic script', 'Ekpe graded society ritual', 'Cross River masquerade costume'],
    rel: ['Egungun masquerade', 'Gelede Masquerade Art', 'Asafo', 'Nkisi Nkondi'],
    src: [{ n: 'Wikipedia — Ekpe', u: 'https://en.wikipedia.org/wiki/Ekpe', t: 'B' }, { n: 'Wikipedia — Ekoi (Ejagham) people', u: 'https://en.wikipedia.org/wiki/Ejagham_people', t: 'B' }, { n: 'The Metropolitan Museum of Art — Dance crest (Ejagham peoples)', u: 'https://www.metmuseum.org/art/collection/search/312460', t: 'A' }],
    tg: ['ekpe', 'ngbe', 'skin mask', 'cross river', 'nsibidi', 'ejagham', 'leopard society'],
    pop: 34, niche: true,
    vd: { shape: 'oval skin faces under towering basketry crests', line: 'chalk face-marks in fine triangles and bands', composition: 'janiform pairs, frontal presentation', texture: 'taut hide over wood with hair-crest tufts' },
    typ: { display: 'nsibidi signs on staffs and society regalia', body: 'worn atop costume by graded initiates', notes: 'skin covering recalls earlier trophy-head emblems' },
    lit: { quality: 'dusk firelight of the society lodge', temperature: 'warm', shadow: 'deep eye-socket pockets' },
    ui: { background: 'river-tan hide tone', surface: 'crest-silhouette cards', components: 'chalk-triangle accents', motion: 'ceremonial slow pivots' },
  },
  {
    n: 'Yoruba Shrine Doorway Carving', a: ['Yoruba palace doors', 'Yoruba carved verandah posts', 'Olowe of Ise doors', 'oju-ona carving'],
    cat: 'Regional & Cultural Tradition', c: 'Yoruba deep-relief architectural wood carving', e: 'regional_tradition',
    o: 'Nigeria (Ekiti, Ondo and Ijesa country)', g: 'Nigeria (Ekiti and Ondo states; Ise, Ikere and other royal palaces)', p: 'late 19th century-present', era: 'Late precolonial to colonial Nigeria',
    sum: 'Deep-relief carved palace and shrine doors, verandah posts and royal bowls by Yoruba master carvers — court chronicles in wood with kings, warriors and mothers in tiers.',
    desc: 'Carved doorways of Yoruba palaces and shrines set stacked registers of court life — the king at center, warriors, drummers, mothers with children — projected in deep undercut relief against swirling oju-ona textured grounds. The style culminated with Olowe of Ise (c. 1873-c. 1938), a wood sculptor and master innovator of oju-ona design, whose doors and verandah posts for the palace of the Ogoga of Ikere and the Ise court entered the British Museum, the Art Institute of Chicago and other major collections. Layered relief depth makes the surfaces theatrical and kinetic, unequalled in African architectural carving.',
    col: [{ h: '#6e4a2c', n: 'palace iroko brown' }, { h: '#2e2013', n: 'deep undercut' }, { h: '#e3d7bd', n: 'kaolin wash' }, { h: '#b58a4a', n: 'iroko gold' }, { h: '#2f3f5c', n: 'indigo cloth' }],
    m: ['iroko hardwood panels', 'adze and v-chisels', 'razor-fine knives', 'palm-oil finish'],
    tx: ['deep undercut relief', 'scratched texture ground', 'smooth figure sheen'],
    obj: ['paired palace doors', 'verandah support posts', 'shrine door panels', 'carved kola bowls for royal wives'],
    ex: ['Doors of the Ogoga of Ikere palace by Olowe of Ise (British Museum)', 'Ise palace verandah post (Art Institute of Chicago)', 'Multi-figure royal bowls attributed to Olowe of Ise'],
    inf: ['Yoruba royal court culture', 'oju-ona surface design', 'early-20th-century collecting networks'],
    rel: ['Yoruba Beaded Crowns', 'Ere Ibeji', 'Gelede Masquerade Art', 'Adire Eleko'],
    src: [{ n: 'Wikipedia — Olowe of Ise', u: 'https://en.wikipedia.org/wiki/Olowe_of_Ise', t: 'B' }, { n: 'The British Museum — Yoruba carved doors', u: 'https://www.britishmuseum.org', t: 'A' }],
    tg: ['yoruba', 'palace door', 'olowe', 'relief carving', 'verandah post', 'ekiti', 'wood'],
    pop: 38, niche: true,
    vd: { shape: 'rectangular door panels stacked with figure registers', line: 'swirling oju-ona background strokes', composition: 'king central, courtiers flanking in tiers', texture: 'deep undercut shadow against smooth figures' },
    typ: { display: 'occasional dedicatory incisions', body: 'n/a — architectural carving', notes: 'doors read as court chronicles in wood' },
    lit: { quality: 'low verandah daylight', temperature: 'warm', shadow: 'strong relief shadows by design' },
    ui: { background: 'iroko brown field', surface: 'relief-register cards', components: 'undercut-edge buttons', motion: 'register-by-register slide reveals' },
  },
  {
    n: 'Senufo Firespitter Masks', a: ['Kponiugu helmet masks', 'Kporopianun firespitter', 'Firespitter helmet mask', 'Senufo Poro masks'],
    cat: 'Religious & Sacred Art', c: 'Poro-society composite helmet masks of the Senufo', e: 'regional_tradition',
    o: "Cote d'Ivoire, Mali & Burkina Faso", g: "Senufo country (Korhogo region, northern Cote d'Ivoire; adjacent Mali and Burkina Faso)", p: '19th-20th century', era: '19th-20th century West Africa',
    sum: 'Fearsome composite helmet masks — crocodile jaws, warthog tusks, antelope horns and hyena elements — danced by Poro society members to repel dangerous bush spirits.',
    desc: 'Among the Senufo of northern Cote d\'Ivoire and neighboring Mali and Burkina Faso, Poro society carvers compose the kponiugu or "firespitter" helmet: an aggressive crest mixing crocodile jaws, warthog tusks, antelope horns and predatory animal references. The Senufo are regionally famous for handicrafts charged with cultural and religious belief, and the firespitter is danced at funerals and honorific ceremonies to guard the community against malevolent bush spirits and forces of death. Its aggression is protective, clearing ritual space, and its sculptural brio helped make Senufo carving a touchstone of modern art.',
    col: [{ h: '#221a12', n: 'carved hardwood black' }, { h: '#e8dfcd', n: 'kaolin white' }, { h: '#9a5a33', n: 'rust ochre' }, { h: '#4f3823', n: 'libation brown' }, { h: '#a99757', n: 'savanna grass' }],
    m: ['dense carved hardwood', 'kaolin and earth pigments', 'raffia fiber costume', 'libation patina'],
    tx: ['polished libation sheen', 'hollowed horn volumes', 'fiber skirt sway'],
    obj: ['firespitter helmet masks', 'Poro society face masks', 'porpianong hornbill crests', 'rhythm pounder figures'],
    ex: ['Korhogo-region kponiugu helmets', 'Poro society funeral performances', 'Musee du quai Branly Senufo mask holdings'],
    inf: ['Poro society initiation', 'Senufo handicraft fame', 'Modernist reception of Senufo sculpture'],
    rel: ['Bamana Chi Wara', 'Dan Mask', 'Fang Reliquary', 'Mumuye Figure Sculpture'],
    src: [{ n: 'Wikipedia — Senufo people', u: 'https://en.wikipedia.org/wiki/Senufo_people', t: 'B' }, { n: 'Musee du quai Branly — Senufo collections', u: 'https://www.quaibranly.fr', t: 'A' }, { n: 'The British Museum — Senufo masks', u: 'https://www.britishmuseum.org', t: 'A' }],
    tg: ['senufo', 'poro', 'kponiugu', 'firespitter', 'helmet mask', 'funeral', 'cote divoire'],
    pop: 36, niche: true,
    vd: { shape: 'low-slung composite predator silhouette', line: 'curved horns meeting upturned jaws', composition: 'helm form, animal parts in dynamic tension', texture: 'dark libation-blackened wood, chalk accents' },
    typ: { display: 'none — symbolic anatomy only', body: 'worn horizontal atop the head with raffia costume', notes: 'aggressive form equals protective function' },
    lit: { quality: 'night ceremony firelight', temperature: 'warm', shadow: 'huge thrown shadows of horns' },
    ui: { background: 'charred-wood black', surface: 'horn-silhouette panels', components: 'kaolin-dot buttons', motion: 'lunging protective transitions' },
  },
  {
    n: 'Fulani Gold & Amber Jewelry', a: ['Fulani kwottenai earrings', 'Peul gold earrings', 'Fula bridal jewelry', 'Fulbe adornment'],
    cat: 'Fashion & Dress', c: 'Sahelian Fulani goldsmith and adornment tradition', e: 'regional_tradition',
    o: 'Mali & Senegal', g: 'West African Sahel (Mali, Senegal, Guinea, Burkina Faso, Niger)', p: '19th century-present', era: '19th-20th century Sahel',
    sum: 'Sahelian Fulani (Fulbe) women\'s gold-and-amber adornment — massive twisted gold earrings and coin-and-amber braids signaling married status and lineage wealth.',
    desc: 'Fulani women of the Sahel are celebrated for spectacular goldwork: great twisted kwottenai earrings worn by married women, forged by goldsmiths into wide fans and spirals, and braids hung with old silver coins, cowries and amber. Museum holdings such as the Metropolitan Museum\'s Fulani gold earrings record the tradition, while accounts describe Fulani women and girls attaching silver coins and amber to their five long braids. Adornment marks marital status, family wealth and trans-Saharan trade connections linking Sahelian gold to amber and coin routes. Sets pass from mother to daughter and are reworked rather than melted — a wearable family archive.',
    col: [{ h: '#d4a437', n: 'bullion gold' }, { h: '#b3671f', n: 'amber honey' }, { h: '#b9bec6', n: 'silver coin' }, { h: '#efe6d2', n: 'cowrie cream' }, { h: '#3a2c1c', n: 'dark leather' }],
    m: ['gold and gold alloy', 'amber beads', 'old silver coins', 'cowrie shells', 'leather and cord'],
    tx: ['burnished gold twist', 'translucent amber glow', 'worn coin relief'],
    obj: ['kwottenai twist earrings', 'amber braid pendants', 'coin necklaces', 'nose rings', 'bridal sets'],
    ex: ['Metropolitan Museum Earrings (African, Fulani)', 'Mali and Senegal bridal earring sets', 'Sahelian coin-and-amber braid ornaments'],
    inf: ['Sahelian goldsmithing', 'trans-Saharan amber and coin trade', 'Pastoralist wealth display'],
    rel: ['Tuareg Cross of Agadez', 'Asante Goldweights', 'Maasai Beadwork Aesthetic'],
    src: [{ n: 'Wikipedia — Fula people', u: 'https://en.wikipedia.org/wiki/Fula_people', t: 'B' }, { n: 'The Metropolitan Museum of Art — Earrings (African, Fulani)', u: 'https://www.metmuseum.org/art/collection/search/141748', t: 'A' }],
    tg: ['fulani', 'gold', 'amber', 'earrings', 'sahel', 'bridal', 'kwottenai', 'jewelry'],
    pop: 36, niche: true,
    vd: { shape: 'great flat twist-fans framing the face', line: 'spiral wire coils and coin discs', composition: 'mass symmetric around head and braids', texture: 'high-burnish gold against matte amber' },
    typ: { display: 'no lettering — value symbolism', body: 'worn at ears, braids, neck and nose', notes: 'old coins and amber pass through generations' },
    lit: { quality: 'hard Sahelian sun', temperature: 'warm', shadow: 'small glitter-cast sparkles' },
    ui: { background: 'amber gradient field', surface: 'gold-twist swatch cards', components: 'coin-disc buttons', motion: 'gentle shimmer oscillation' },
  },
  {
    n: 'Ethiopian Processional Crosses', a: ['Ethiopian crosses', 'Abyssinian crosses', 'Ethiopian-Eritrean crosses', 'hand blessing crosses'],
    cat: 'Religious & Sacred Art', c: 'Ethiopian Orthodox church cross-making tradition', e: 'regional_tradition',
    o: 'Ethiopia & Eritrea', g: 'Ethiopian Highlands (Amhara, Tigray; Ethiopian and Eritrean Orthodox churches)', p: '4th century-present', era: 'Aksumite to modern Ethiopia',
    sum: 'Latticed brass, bronze and wood crosses of the Ethiopian Orthodox Church — processional crosses on staffs and priests\' hand crosses whose intertwined lattice means everlasting life.',
    desc: 'Ethiopian crosses — also called Abyssinian or Ethiopian-Eritrean crosses — are distinguished by elaborate openwork latticework whose intertwined pattern represents everlasting life, and by the rule that no two crosses are identical: artisans exercise individual taste in shape and pattern. Processional types carry a socket at the base for mounting on a staff to be carried in church ceremonies; priests bless with smaller hand-held crosses. Cast, chased and incised in brass, bronze, iron and wood, they descend from Aksumite Christian metalwork; the celebrated Lalibela Cross is among the most famous, and crosses remain central to liturgy and Timkat festivals.',
    col: [{ h: '#b78b3a', n: 'brass gold' }, { h: '#5e6b52', n: 'aged bronze green' }, { h: '#241d14', n: 'incised black' }, { h: '#e9e2d0', n: 'parchment white' }, { h: '#8e2f26', n: 'timkat red' }],
    m: ['brass and bronze casting', 'chasing and incising tools', 'iron and carved wood', 'staff socket fittings'],
    tx: ['openwork lattice depth', 'incised line density', 'hand-worn polish'],
    obj: ['processional crosses with staff sockets', "priests' hand crosses", 'Lalibela-type crosses', 'cross-topped prayer sticks (mequamia)'],
    ex: ['Metropolitan Museum Processional Cross (Ethiopian)', 'Lalibela Cross, recovered in 1999 after theft', 'Northern Highlands processional crosses in museum collections'],
    inf: ['Aksumite Christian metalwork', 'Ethiopian Orthodox liturgy', 'Timkat festival ritual'],
    rel: ['Ethiopian Rock-Hewn Churches', 'Lalibela Churches', 'Ethiopian Border Embroidery', 'Ethiopian Illuminated Manuscripts'],
    src: [{ n: 'Wikipedia — Ethiopian cross', u: 'https://en.wikipedia.org/wiki/Ethiopian_cross', t: 'B' }, { n: 'The Metropolitan Museum of Art — Processional Cross (Ethiopian)', u: 'https://www.metmuseum.org/art/collection/search/479577', t: 'A' }, { n: 'The Metropolitan Museum of Art — Processional Cross (Northern Highlands)', u: 'https://www.metmuseum.org/art/collection/search/317877', t: 'A' }],
    tg: ['ethiopian orthodox', 'cross', 'lattice', 'processional', 'liturgy', 'brass', 'eritrea'],
    pop: 46, niche: false,
    vd: { shape: 'lozenge and diamond-armed crosses on staffs', line: 'endless interlaced lattice bands', composition: 'symmetric lozenge field fringed with arcs and bells', texture: 'cast relief with incised fill' },
    typ: { display: "occasional Ge'ez dedicatory inscriptions", body: 'carried aloft in procession; blessed in the hand', notes: 'no two crosses identical by tradition' },
    lit: { quality: 'church candle glow plus daylight', temperature: 'warm', shadow: 'lattice-patterned casts' },
    ui: { background: 'parchment-ivory field', surface: 'lattice-cross emblems', components: 'diamond-lattice buttons', motion: 'processional glide with gentle swing' },
  },
  {
    n: 'Aksum Stele Architecture', a: ['Axum obelisks', 'Aksum stelae', 'Stele Field of Aksum', 'hawelti of Aksum'],
    cat: 'Regional & Cultural Tradition', c: 'Monumental carved-stele architecture of the Kingdom of Aksum', e: 'historical',
    o: 'Ethiopia (Tigray, Aksum)', g: 'Kingdom of Aksum (northern Ethiopia, Eritrea, southern Arabia)', p: 'c. AD 100-700', era: 'Ancient Aksumite kingdom',
    sum: 'Giant phonolite stelae of Aksum — multi-storey towers with false doors and windows that turned palace architecture into royal tombstones, still standing in Ethiopia.',
    desc: 'In the capital of the Kingdom of Aksum, single quarried stones of phonolite were carved into multi-storey towers: the 4th-century CE Obelisk of Axum rises 24 meters and weighs 160 tonnes, ornamented with two false doors at the base and window-like decoration on all faces, ending in a semi-circular top once enclosed by metal frames. The even larger Great Stele fell, likely in antiquity, while King Ezana\'s stele still stands. Stelae marked royal burial complexes and translated palace facades into stone; the Obelisk, taken to Rome in 1937, was returned and re-erected at Aksum in 2008 within the UNESCO World Heritage site.',
    col: [{ h: '#7d7f7c', n: 'phonolite grey' }, { h: '#c2a675', n: 'desert ochre' }, { h: '#8a6b3a', n: 'bronze frame' }, { h: '#e5e2d6', n: 'sky-bleached white' }, { h: '#4c4a40', n: 'lichen shadow' }],
    m: ['phonolite monoliths', 'stone pounding and abrading tools', 'bronze cramps and metal frames', 'ramped erection works'],
    tx: ['false-door relief depth', 'storey-window jointing', 'desert-worn polish'],
    obj: ['Obelisk of Axum (24 m)', "King Ezana's standing stele", 'fallen Great Stele (33 m)', 'smaller tomb stelae'],
    ex: ['Obelisk of Axum, returned from Rome and re-erected 2008', "King Ezana's stele still standing", 'Great Stele fallen in the Northern Stelae Field'],
    inf: ['South Arabian monumental building', 'Ancient Egyptian obelisk forms', 'Aksumite inscriptions and coinage'],
    rel: ['Ethiopian Rock-Hewn Churches', 'Great Zimbabwe Architecture', 'Lalibela Churches'],
    src: [{ n: 'Wikipedia — Obelisk of Axum', u: 'https://en.wikipedia.org/wiki/Obelisk_of_Axum', t: 'B' }, { n: 'Wikipedia — Axum', u: 'https://en.wikipedia.org/wiki/Axum', t: 'B' }, { n: 'The British Museum — Aksum material', u: 'https://www.britishmuseum.org', t: 'A' }],
    tg: ['aksum', 'stele', 'obelisk', 'monolith', 'aksumite', 'ethiopia', 'unesco'],
    pop: 48, niche: false,
    vd: { shape: 'tapering storey-towers with curved tops', line: 'horizontal string-courses, vertical window strips', composition: 'false doors grounded, semicircular crown above', texture: 'banded phonolite, desert-worn' },
    typ: { display: 'inscribed Aksumite stones carry Ge\'ez, Greek and Sabaean', body: 'n/a — monumental architecture', notes: 'stelae marked subterranean royal tombs' },
    lit: { quality: 'hard highland sun', temperature: 'warm neutral', shadow: 'deep false-door recesses' },
    ui: { background: 'stone-grey gradient', surface: 'storey-relief header cards', components: 'false-door rectangle buttons', motion: 'monumental slow fades' },
  },
  {
    n: 'Ethiopian Illuminated Manuscripts', a: ['Garima Gospels', 'Gondarine manuscript painting', 'Ethiopian gospel books', "Ge'ez illuminated codices"],
    cat: 'Religious & Sacred Art', c: 'Ethiopian Orthodox illuminated manuscript tradition', e: 'regional_tradition',
    o: 'Ethiopian Highlands', g: 'Ethiopia (Tigray monasteries, Lake Tana islands, Gondar scriptoria)', p: 'c. 4th century-present', era: 'Aksumite to Gondarine Ethiopia',
    sum: 'Parchment gospel books of the Ethiopian Church — vivid broad-eyed saints in vermilion, yellow and blue — including the Garima Gospels, likely the earliest complete illuminated Christian manuscripts.',
    desc: 'Ethiopian monasteries have copied and painted Ge\'ez gospel codices on goatskin parchment for some 1,600 years. The Garima Gospels of Tigray — three manuscripts whose earliest radiocarbon dates run to c. 390-570 — include what is believed to be the earliest surviving complete illuminated Christian gospel book, its canon tables and portraits linked to late antique Coptic Egypt, Nubia and Himyar. Imperial Gondar, founded in 1636, fostered the Gondarine style: diptychs, triptychs, murals and illuminated manuscripts with religious motifs, patronized alongside 44 churches around Lake Tana. Monastic scriptoria bind hand-sewn wooden-board codices to this day.',
    col: [{ h: '#a63a26', n: 'vermilion red' }, { h: '#33518c', n: 'deep blue' }, { h: '#d9a334', n: 'saffron yellow' }, { h: '#e4d6b8', n: 'parchment buff' }, { h: '#26201a', n: 'ink black' }],
    m: ['goatskin parchment', 'mineral and organic pigments', 'carbon soot ink', 'wooden board bindings'],
    tx: ['burnished parchment ground', 'flat opaque color fields', 'bold black outline drawing'],
    obj: ['illuminated gospel codices', 'diptychs and triptychs', 'canon table pages', 'saint and Virgin portraits'],
    ex: ['Garima Gospels (Abba Garima Monastery, Tigray)', 'Gondarine-period gospel books of Lake Tana monasteries', 'Fasil Ghebbi-era royal commissions'],
    inf: ['Late antique Coptic and Nubian art', 'Gondarine imperial patronage', 'Ethiopian Orthodox liturgy'],
    rel: ['Ethiopian Rock-Hewn Churches', 'Ethiopian Processional Crosses', 'Ethiopian Border Embroidery'],
    src: [{ n: 'Wikipedia — Garima Gospels', u: 'https://en.wikipedia.org/wiki/Garima_Gospels', t: 'B' }, { n: 'Wikipedia — Gondarine period', u: 'https://en.wikipedia.org/wiki/Gondarine_period', t: 'B' }, { n: 'The Metropolitan Museum of Art — Ethiopian manuscript holdings', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['manuscript', 'geez', 'gondarine', 'garima', 'illumination', 'ethiopian orthodox', 'parchment'],
    pop: 42, niche: false,
    vd: { shape: 'frontal broad-eyed saints within painted frames', line: 'thick contour drawing, hatched drapery', composition: 'full-page portraits flanking canon tables', texture: 'matte pigment on burnished skin' },
    typ: { display: "Ge'ez script in two-column ink text", body: 'n/a — sacred codices', notes: 'colophons date and dedicate volumes' },
    lit: { quality: 'even monastic daylight', temperature: 'warm', shadow: 'flat, minimal' },
    ui: { background: 'aged parchment', surface: 'illuminated frame cards', components: 'red-and-yellow canon-table dividers', motion: 'page-turn reveal' },
  },
  {
    n: 'Swahili Carved Doors', a: ['Zanzibar carved doors', 'Zanzibari doors', 'Stone Town doors', 'Lamu doors'],
    cat: 'Regional & Cultural Tradition', c: 'Swahili coast architectural door carving', e: 'regional_tradition',
    o: 'Zanzibar & East African coast', g: 'Tanzania (Stone Town, Bagamoyo), Kenya (Lamu, Mombasa), Oman', p: '18th-20th century', era: 'Omani and colonial-era Zanzibar',
    sum: 'Monumental carved teak doorways of the Swahili coast — studded Indian-style portals and older Lamu-Omani types of Zanzibar and Lamu — announcing wealth in coral-stone streets.',
    desc: 'The coral-stone houses of Stone Town are fronted by monumental carved doors, a Swahili signature born of Arab, Persian, Indian, European and African traditions mixing. Two types dominate: the square-panelled door with brass studs associated with the Indian subcontinent, and the older coastal type with deep relief around a central carved post. Symbolic carving — lotus flowers, fish, date palms and hanging chains — carries wishes of fertility, abundance and security, while Arabic inscriptions bless the household. Carvers, many tracing to Gujarat, served Omani merchants; the Metropolitan Museum holds a Swahili carved door of the mid- to late 19th century.',
    col: [{ h: '#6a4526', n: 'teak oil brown' }, { h: '#b08d42', n: 'brass stud' }, { h: '#c49583', n: 'coral-stone pink' }, { h: '#2c1d10', n: 'deep carve shadow' }, { h: '#35506b', n: 'sea indigo' }],
    m: ['dense teak planks', 'gouges and straight chisels', 'brass bosses and studs', 'iron fittings'],
    tx: ['deep-relief rosette carving', 'polished stud gleam', 'weathered grain'],
    obj: ['studded merchant portals', 'Lamu-type paneled doors', 'carved doorposts and lintels', 'brass-studded lock plates'],
    ex: ['Metropolitan Museum Carved door (Swahili peoples, mid- to late-19th century)', 'Stone Town studded portals', 'Lamu old-town carved doorways'],
    inf: ['Gujarati carving workshops', 'Omani Zanzibar trade wealth', 'Swahili coral-stone architecture'],
    rel: ['Swahili Stone Town', 'Swahili Coastal Architecture', 'Zanzibar Architecture', 'Bukhara Wooden Doors'],
    src: [{ n: 'Wikipedia — Stone Town', u: 'https://en.wikipedia.org/wiki/Stone_Town', t: 'B' }, { n: 'Wikipedia — Swahili culture', u: 'https://en.wikipedia.org/wiki/Swahili_culture', t: 'B' }, { n: 'The Metropolitan Museum of Art — Carved door (Swahili peoples)', u: 'https://www.metmuseum.org/art/collection/search/930571', t: 'A' }],
    tg: ['swahili', 'zanzibar', 'carved door', 'lamu', 'teak', 'brass studs', 'stone town'],
    pop: 44, niche: false,
    vd: { shape: 'tall rectangular portals with square panels', line: 'deep vertical post and fringe carving', composition: 'symmetric leaves framing a carved central post', texture: 'hard teak relief with brass glints' },
    typ: { display: 'Arabic (and Gujarati) inscribed panels', body: 'n/a — architectural joinery', notes: 'motifs read as blessings on the household' },
    lit: { quality: 'narrow street sidelight', temperature: 'warm', shadow: 'deep gouged shade' },
    ui: { background: 'coral-pink stone tone', surface: 'door-panel cards', components: 'brass-boss round buttons', motion: 'hinged swing-in transitions' },
  },
  {
    n: 'Imigongo Wall Art', a: ['Rwandan cow-dung art', 'imigongo geometric murals', 'cow dung and ash painting'],
    cat: 'Regional & Cultural Tradition', c: 'Rwandan cow-dung geometric wall art', e: 'regional_tradition',
    o: 'Rwanda (Eastern Province)', g: 'Rwanda (Kibungo region, Kirehe and Nyarubuye; Kigali workshops)', p: '18th century-present', era: 'Precolonial Rwanda to present',
    sum: 'Rwanda\'s geometric art of cow dung and ash — black, white and red spirals and zigzags ridged on walls and panels, a women-led tradition revived by cooperatives after 1994.',
    desc: 'Imigongo is made by women who mix cow dung with ash — which kills bacteria and removes odor — and mold it on walls or boards into ridged spirals, zigzags and diamonds that harden before painting in organic colors: traditionally black, white, red, grey and beige-yellow. First found inside Kibungo hut walls in the 18th century as "magical" decoration, legend credits Prince Kakira of Gisaka with inventing it in the 1800s. The 1994 genocide nearly erased the skills; a women\'s cooperative on the road to Rusumo near Kirehe revived them, and artists now experiment with modern images of the Rwandan landscape alongside the classic geometry.',
    col: [{ h: '#1d1a16', n: 'soot black' }, { h: '#ece5d6', n: 'kaolin white' }, { h: '#a84a2c', n: 'ochre red' }, { h: '#8f8a80', n: 'grey ash' }, { h: '#d9c27e', n: 'beige-yellow' }],
    m: ['fresh cow dung', 'wood ash', 'natural organic pigments', 'wall or board ground'],
    tx: ['raised dung ridge', 'polished matte paint', 'crisp geometric edge'],
    obj: ['hut wall murals', 'framed square panels', 'decorated pottery', 'Kigali gallery boards'],
    ex: ['Kirehe-Rusumo women\'s cooperative panels', 'Nyarubuye imigongo tradition sites', 'Contemporary Kigali gallery imigongo'],
    inf: ['Rwandan court interior decoration', "Women's cooperative craft revival", 'Contemporary Rwandan design'],
    rel: ['Ndebele House Painting', 'Basotho Litema Murals', 'Ndebele Geometric Painting'],
    src: [{ n: 'Wikipedia — Imigongo', u: 'https://en.wikipedia.org/wiki/Imigongo', t: 'B' }, { n: 'Musee du quai Branly — African collections', u: 'https://www.quaibranly.fr', t: 'A' }],
    tg: ['imigongo', 'rwanda', 'cow dung', 'geometric', 'wall art', 'spiral', 'women cooperative'],
    pop: 40, niche: false,
    vd: { shape: 'interlocking spirals, diamonds and zigzag bands', line: 'raised ridges outline every color field', composition: 'all-over repeat filling a rectangular ground', texture: 'low-relief dung ridge under matte paint' },
    typ: { display: 'none — purely geometric vocabulary', body: 'wall surfaces and framed boards', notes: 'traditional palette limited to five earths' },
    lit: { quality: 'soft interior daylight', temperature: 'neutral warm', shadow: 'thin ridge shadow on each rise' },
    ui: { background: 'kaolin white', surface: 'ridge-textured geometric cards', components: 'black-diamond buttons', motion: 'spiral unwind transitions' },
  },
  {
    n: 'Tingatinga Painting', a: ['Tinga-tinga', 'Tinga Tinga', 'Dar es Salaam enamel painting', 'Tingatinga school'],
    cat: 'Regional & Cultural Tradition', c: 'East African enamel-on-masonite painting genre', e: 'regional_tradition',
    o: 'Tanzania (Dar es Salaam)', g: 'Tanzania, Kenya and neighboring countries (Dar es Salaam cooperatives)', p: '1968-present', era: 'Postcolonial East Africa',
    sum: 'East Africa\'s joyful painting genre founded by Edward Tingatinga in 1968 — bicycle-paint brilliance on masonite, naive animals and fantasy that became the region\'s signature art export.',
    desc: 'Tingatinga began when Tanzanian painter Edward Saidi Tingatinga painted small vivid panels in Dar es Salaam from 1968, working on masonite with several layers of bicycle paint that give brilliant, highly saturated color. The images are naive and caricatural, with humor and sarcasm often explicit; subjects — the Big Five and other wildlife, village life, invented spirits — were sized small and shaped square for the tourist market, leading some to call them "airport paintings". Spread by followers and the Tingatinga Arts Cooperative Society, the genre became the most widely represented painting style of Tanzania and Kenya, even inspiring the Tinga Tinga Tales animation.',
    col: [{ h: '#d43a26', n: 'enamel red' }, { h: '#f0b428', n: 'enamel yellow' }, { h: '#2b6cb5', n: 'enamel blue' }, { h: '#3d8f4f', n: 'enamel green' }, { h: '#16151a', n: 'gloss black' }],
    m: ['masonite hardboard', 'layers of bicycle enamel', 'household brushes'],
    tx: ['high-gloss enamel surface', 'layered color depth', 'clean naive contour'],
    obj: ['square wildlife panels', 'village life scenes', 'fantasy animal medallions', 'cooperative commissions'],
    ex: ['Edward Saidi Tingatinga originals (c. 1968-1972)', "Tingatinga Arts Cooperative Society members' work", "Simon Mpata's village scenes"],
    inf: ['Tourist-market art economies', 'East African sign-painting', 'Tinga Tinga Tales animation'],
    rel: ['Makonde Art', 'Swahili Stone Town'],
    src: [{ n: 'Wikipedia — Tingatinga (painting)', u: 'https://en.wikipedia.org/wiki/Tingatinga_(painting)', t: 'B' }, { n: 'Wikipedia — Tingatinga Arts Cooperative Society', u: 'https://en.wikipedia.org/wiki/Tingatinga_Arts_Cooperative_Society', t: 'B' }],
    tg: ['tingatinga', 'enamel paint', 'tanzania', 'naive art', 'wildlife', 'tourist art', 'dar es salaam'],
    pop: 46, niche: false,
    vd: { shape: 'flat monumental animals filling the square', line: 'simple confident outline, no shading', composition: 'centered subject on saturated ground', texture: 'glassy enamel layers' },
    typ: { display: 'signature in enamel paint', body: 'n/a — portable panel paintings', notes: 'square formats sized for luggage transport' },
    lit: { quality: 'flat even', temperature: 'warm', shadow: 'none — poster-flat' },
    ui: { background: 'saturated enamel field', surface: 'glossy animal-panel cards', components: 'round enamel-dot buttons', motion: 'bouncy pop-in animations' },
  },
  {
    n: 'Shona Stone Sculpture', a: ['Shona sculpture movement', 'Zimbabwean stone sculpture', 'Tengenenge carving community', 'first-generation Zimbabwean sculptors'],
    cat: 'Regional & Cultural Tradition', c: 'Zimbabwean modern stone-carving movement', e: 'regional_tradition',
    o: 'Zimbabwe', g: 'Zimbabwe (Harare, Nyanga, Tengenenge, Chapungu)', p: '1957-present', era: 'Late colonial to postcolonial Zimbabwe',
    sum: 'Zimbabwe\'s celebrated modern stone-carving movement — serpentine spirits, family groups and metamorphoses by first-generation masters like Mukomberanwa and Munyaradzi.',
    desc: 'Stone sculpture, and stone carving in particular, is the art for which Zimbabwe is known worldwide. From the late 1950s, pioneers such as Joram Mariga at Nyanga and communities like the Tengenenge sculptor village, encouraged by National Gallery director Frank McEwen, developed direct carving of local serpentine, springstone and soapstone — the term "Shona sculpture" was McEwen\'s, though artists of several peoples joined. First-generation masters including Nicholas Mukomberanwa, Henry Munyaradzi, Bernard Takawira and Colleen Madamombe carved spirits, mother-and-child groups and animal metamorphoses, exhibited internationally from the 1970s and renewing Great Zimbabwe\'s stone heritage in a modern personal voice.',
    col: [{ h: '#2a2723', n: 'springstone black' }, { h: '#9a8bb0', n: 'lepidolite lilac' }, { h: '#5c7355', n: 'serpentinite green' }, { h: '#d8cfc0', n: 'soapstone cream' }, { h: '#a89f8f', n: 'quarry dust' }],
    m: ['serpentinite and springstone', 'soapstone and lepidolite', 'hammers, chisels and rasps', 'wax and oil finish'],
    tx: ['polished stone sheen', 'raw chiseled passages', 'mineral speckling'],
    obj: ['tall spirit figures', 'mother-and-child groups', 'animal metamorphoses', 'large park monuments'],
    ex: ["Henry Munyaradzi's Great Spirit carvings", "Nicholas Mukomberanwa's family groups", 'Chapungu Sculpture Park collection, Harare'],
    inf: ['Great Zimbabwe stone heritage', 'Postcolonial workshop communities', 'International modernist collecting'],
    rel: ['Great Zimbabwe Architecture', 'Zimbabwean Dry Stone', 'Makonde Art'],
    src: [{ n: 'Wikipedia — Shona sculpture', u: 'https://en.wikipedia.org/wiki/Shona_sculpture', t: 'B' }, { n: 'Musee du quai Branly — Zimbabwean sculpture', u: 'https://www.quaibranly.fr', t: 'A' }, { n: 'The British Museum — Zimbabwean stone sculpture', u: 'https://www.britishmuseum.org', t: 'A' }],
    tg: ['shona', 'zimbabwe', 'stone sculpture', 'serpentine', 'springstone', 'mukomberanwa', 'carving'],
    pop: 45, niche: false,
    vd: { shape: 'organic totemic masses with smoothly fused figures', line: 'few edges — flowing carved volumes', composition: 'single hero stone with negative space around', texture: 'polished dark stone with raw zones' },
    typ: { display: 'occasional carved signatures', body: 'n/a — gallery and garden sculpture', notes: 'stone choice drives color and mood' },
    lit: { quality: 'strong raking sun', temperature: 'neutral', shadow: 'soft pooling on polished curves' },
    ui: { background: 'quarry-grey wash', surface: 'stone-gradient cards', components: 'pebble-rounded buttons', motion: 'slow orbit pans' },
  },
  {
    n: 'Xibelani Dance Skirt', a: ['Xibelani', 'Shibelani', 'Tinguvu dance skirt', 'Xibelane'],
    cat: 'Fashion & Dress', c: 'Tsonga women\'s dance and costume tradition', e: 'regional_tradition',
    o: 'South Africa & Mozambique', g: 'South Africa (Limpopo, Mpumalanga), Mozambique borderlands', p: '1400s-present', era: 'Precolonial to modern southern Africa',
    sum: 'The Tsonga xibelani — a shaking skirt worn to "hit the rhythm" in women\'s dance — with call-and-response song, xylophone and drum, from the Mozambique coast to Limpopo stages.',
    desc: 'Xibelani (also Shibelani) is the indigenous dance of Tsonga women of Limpopo and Mpumalanga; the name comes from Xitsonga and translates roughly as "hitting to the rhythm", while the skirt itself is the tinguvu. Its roots reach to early coastal southern Mozambique of the 1400s or earlier, where Chopi timbila orchestras — mbila xylophones and swigubu drums — accompanied women singing call-and-response between claps and whistles. Dancers shake the hips so the whole skirt rattles: old xibelani of fibers, wool, strings and grass, modern ones of strong pleated cloth. The dance remains central to Tsonga community celebration and identity.',
    col: [{ h: '#b23327', n: 'pleat scarlet' }, { h: '#f2c53d', n: 'rattle yellow' }, { h: '#2e6e4e', n: 'bead green' }, { h: '#efe2c8', n: 'cotton cream' }, { h: '#4a3324', n: 'drum leather' }],
    m: ['strong pleated cloth (tinguvu)', 'wool, string and grass fibers (traditional)', 'beadwork accessories', 'mbila xylophone and swigubu drum'],
    tx: ['crisp pleat rhythm', 'fiber-fringe rattle', 'bright cotton sheen'],
    obj: ['tinguvu shaking skirts', 'beaded dance accessories', 'matched performance wrappers', 'competition costumes'],
    ex: ['Limpopo xibelani competition costume sets', 'Mpumalanga Tsonga dance troupes', 'Xibelani performed with timbila orchestra accompaniment'],
    inf: ['Chopi timbila orchestral tradition', 'Tsonga call-and-response song', 'Southern African dance costume'],
    rel: ['isiNdebele Beadwork', 'Zulu Beadwork Love Letters', 'Basotho Blankets'],
    src: [{ n: 'Wikipedia — Xibelani dance', u: 'https://en.wikipedia.org/wiki/Xibelani_dance', t: 'B' }, { n: 'Wikipedia — Tsonga people', u: 'https://en.wikipedia.org/wiki/Tsonga_people', t: 'B' }],
    tg: ['xibelani', 'tsonga', 'dance skirt', 'timbila', 'limpopo', 'rhythm', 'south africa'],
    pop: 40, niche: false,
    vd: { shape: 'bell-shaped pleated skirt in motion', line: 'concentric fringe arcs', composition: 'dancer centered, orchestra flanking', texture: 'layered cloth and fiber movement blur' },
    typ: { display: 'none — kinetic costume', body: 'worn at the hips, shaken to percussion', notes: 'old skirts of grass and wool, modern of cloth' },
    lit: { quality: 'bright outdoor stage light', temperature: 'warm', shadow: 'quick pleat shadows in motion' },
    ui: { background: 'sunlit savanna cream', surface: 'pleat-stripe cards', components: 'fringe-edge buttons', motion: 'hip-shake oscillation loops' },
  },
]
