/**
 * Africa wave 3 — 12 hand-verified African traditions.
 * All names checked absent from existing-names.txt (no >=6-char overlaps).
 * Sources: stable Wikipedia articles + institutional museum URLs.
 */
export const ENTRIES: any[] = [
  {
    n: 'Nsibidi Ideographic Signs', a: ['Nsibidi script', 'Nsibidi symbol system'],
    cat: 'Religious & Sacred Art', c: 'Cross River ideographic sign tradition', e: 'regional_tradition',
    o: 'Nigeria & Cameroon (Cross River region)', g: 'Nigeria, Cameroon (Ejagham, Efik, Ekpe society sphere)', p: 'centuries-old-precolonial to present', era: 'precolonial Cross River to modern Nigeria',
    sum: 'Ancient ideographic sign system of the Ejagham, Efik and Cross River peoples, carried by the Ekpe leopard society for courtship, law, divination and secret communication.',
    desc: 'Nsibidi is one of Africa\'s oldest indigenous sign systems, developed among the Ejagham (Ekoi), Efik and neighbouring peoples of the Cross River region of Nigeria and Cameroon. Its glyphs range from simple pictograms to abstract marks covering love, war, law, dance and the sacred; public signs appear on bodies, walls, calabashes and ukara cloth, while deeper sets were reserved for Ekpe society initiates. Documented by colonial scholars such as J.K. Macgregor in 1909, nsibidi was transmitted through trained sign interpreters and remains a foundational reference for West African writing and graphic traditions.',
    col: [{ h: '#2b2b2b', n: 'nsibidi charcoal' }, { h: '#b5713a', n: 'ochre body paint' }, { h: '#efe6d8', n: 'kaolin white' }, { h: '#c9a24b', n: 'raffia gold' }, { h: '#26425c', n: 'Cross River indigo' }],
    m: ['calabash and wood sign panels', 'ukara Ekpe cloth', 'kaolin and charcoal pigments', 'incised body tattoo'],
    tx: ['cut-glyph incision', 'charcoal hand-drawn line', 'cloth-embossed patterning'],
    obj: ['ukara society cloth', 'sign-painted calabashes', 'body and wall signs', 'initiate handbooks and slates'],
    ex: ['Ukara Ekpe cloth covered in nsibidi glyphs', 'J.K. Macgregor\'s 1909 nsibidi sign records', 'Cross River wall and body sign panels'],
    inf: ['Ekpe leopard society', 'Ejagham mask and skin-covering arts', 'West African ideography'], rel: ['Ejagham Skin-Covered Masks', 'Uli Body & Wall Painting', 'Adinkra'],
    src: [{ n: 'Wikipedia — Nsibidi', u: 'https://en.wikipedia.org/wiki/Nsibidi', t: 'B' }, { n: 'The British Museum — Cross River collections', u: 'https://www.britishmuseum.org', t: 'A' }],
    tg: ['ideographic', 'script', 'cross river', 'ekpe', 'signs', 'nigeria'],
    pop: 46, niche: true,
    vd: { shape: 'angular glyphs balancing curves and notches', line: 'crisp cut and charcoal strokes', composition: 'sign registers read in ritual sequence', texture: 'incised calabash and rough cloth ground' },
    typ: { display: 'glyph panels and society-cloth borders', body: 'tattooed and painted body signs', notes: 'meaning stratified by initiation level' },
    lit: { quality: 'even archival light', temperature: 'neutral', shadow: 'soft incision shadows' },
    ui: { background: 'aged ukara indigo ground', surface: 'glyph-carved cards', components: 'charcoal-stroke buttons and dividers', motion: 'slow sign-reveal wipes' },
  },
  {
    n: 'Guro Mask Tradition', a: ['Guro masks', 'Zaouli mask dance'],
    cat: 'Regional & Cultural Tradition', c: 'Ivorian carved mask and masquerade art', e: 'regional_tradition',
    o: 'Côte d\'Ivoire', g: 'Côte d\'Ivoire (Baoulé-Guro frontier villages, Bouaké region)', p: '19th century-present', era: '19th-century Côte d\'Ivoire to present',
    sum: 'Polished, elegant carved masks of the Guro people of Côte d\'Ivoire, famed for the UNESCO-listed Zaouli dance mask, hybrid animal forms and refined, elongated faces.',
    desc: 'Guro masquerade centers on carved wooden masks with serene, oval, polished faces, elaborate crescent coiffures and superstructures of birds, antelope or human figures. Male and female mask pairs serve village entertainment masquerades and judicial assemblies, with the hybrid zamble and the celebrated Zaouli dance mask — inscribed on UNESCO\'s intangible heritage list in 2017 — performed to live orchestra for community honor. Guro carvers are renowned across the Ivory Coast for surface finish and balanced proportions, and their masks influenced twentieth-century European sculpture through the colonial collecting wave.',
    col: [{ h: '#2a211c', n: 'polished mask black' }, { h: '#a8332a', n: 'vermilion accent' }, { h: '#e8ddc8', n: 'kaolin white' }, { h: '#b5893a', n: 'brass gold' }, { h: '#3c6b52', n: 'leaf green' }],
    m: ['soft hardwood carving', 'kaolin white pigment', 'raffia fiber costume', 'cowrie and bead ornament'],
    tx: ['glass-smooth carved patina', 'fiber fringe movement', 'pigment-pocked age crust'],
    obj: ['Zaouli dance masks', 'zamble hybrid masks', 'gu female face masks', 'mask-and-costume ensembles', 'court assembly masks'],
    ex: ['UNESCO-inscribed Zaouli dance masks', 'Zamble buffalo-human hybrid masks', 'village entertainment masquerades of Bouaké region'],
    inf: ['Baoulé sculptural ideals', 'Dan mask conventions', 'French colonial collecting'], rel: ['Punu White-Face Masks', 'Senufo Firespitter Masks', 'Gelede Masquerade Art'],
    src: [{ n: 'Wikipedia — Guro people', u: 'https://en.wikipedia.org/wiki/Guro_people', t: 'B' }, { n: 'The Metropolitan Museum of Art — Guro masks', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['mask', 'masquerade', 'ivory coast', 'zaouli', 'carved wood'],
    pop: 44, niche: true,
    vd: { shape: 'elongated ovals with crescent crests', line: 'flowing profile contours', composition: 'single mask focal against deep field', texture: 'mirror-polished wood with fiber fringe' },
    typ: { display: 'dance mask centered in display', body: 'full raffia costume in motion', notes: 'mask pairs alternate male and female roles' },
    lit: { quality: 'directional warm spotlight', temperature: 'warm', shadow: 'deep carve shadows under brows' },
    ui: { background: 'smoky black-brown field', surface: 'polished wood-toned cards', components: 'kaolin-white outlined buttons', motion: 'swaying fiber-fringe transitions' },
  },
  {
    n: 'Wee-Guere Mask Tradition', a: ['Guere masks', 'We-Guere masks', 'Wè masks'],
    cat: 'Regional & Cultural Tradition', c: 'encrusted war and judgment masks of the We peoples', e: 'regional_tradition',
    o: 'Côte d\'Ivoire & Liberia', g: 'Côte d\'Ivoire, Liberia (Guéré and Wè village masquerades)', p: '19th century-present', era: '19th-century western Côte d\'Ivoire to present',
    sum: 'Fierce, heavily encrusted masks of the Wè (Guéré) peoples, blending human and animal violence — horned brows, gaping jaws and sacrificial patinas used for war, justice and protection.',
    desc: 'Wee-Guere masquerade among the Wè peoples of western Côte d\'Ivoire and Liberia produces some of Africa\'s most aggressive mask forms: domed heads under thorn-like superstructures, bared teeth, protruding tongues and multiple horn projections. Masks accumulate layers of kaolin, blood, nest material and offerings into thick sacrificial patina, marking each as an active judge and protector rather than decoration. Worn with massive fiber and bell costumes in Poro-society contexts, they adjudicate disputes, detect sorcery and enforce social order, and their raw expressive power made them prized holdings of early ethnographic museums.',
    col: [{ h: '#241b15', n: 'charred brown' }, { h: '#8c4a2b', n: 'rust red' }, { h: '#d9cbb2', n: 'kaolin white' }, { h: '#4a3428', n: 'dark wood' }, { h: '#6d6a5f', n: 'sacrificial ash gray' }],
    m: ['dense rainforest hardwood', 'encrusted kaolin and offerings', 'raffia and antelope-hide costume', 'iron bells and fiber ruffs'],
    tx: ['cracked sacrificial crust', 'impasto pigment layering', 'coarse fiber shag'],
    obj: ['glah war masks', 'judgment and sorcery-detecting masks', 'protector shrine masks', 'full bell-and-fiber ensembles'],
    ex: ['Glah institutional war masks', 'Poro-society judging masks of Guéré villages', 'encrusted Wè masks in early ethnographic collections'],
    inf: ['Liberian Poro society', 'Dan mask conventions', 'Kru coast exchange networks'], rel: ['Senufo Firespitter Masks', 'Punu White-Face Masks', 'Gelede Masquerade Art'],
    src: [{ n: 'Wikipedia — We people', u: 'https://en.wikipedia.org/wiki/We_people', t: 'B' }, { n: 'The Metropolitan Museum of Art — Wè/Guéré masks', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['mask', 'guere', 'we', 'war mask', 'encrusted patina', 'liberia'],
    pop: 40, niche: true,
    vd: { shape: 'domed heads bristling with horns and tusks', line: 'jagged, violent silhouette edges', composition: 'single confrontational mask, frontal power', texture: 'thick cracked crust over carved form' },
    typ: { display: 'frontal mask on dark plinth', body: 'towering fiber costume with bells', notes: 'patina thickness signals a mask\'s ritual career' },
    lit: { quality: 'low raking side light', temperature: 'warm-dark', shadow: 'deep pits within crust and fiber' },
    ui: { background: 'charred umber gradient', surface: 'rough crust-textured cards', components: 'kaolin-rimmed heavy buttons', motion: 'abrupt bell-shake reveals' },
  },
  {
    n: 'Pende Mask Traditions', a: ['Pende masks', 'Mbuya and Pwo masks'],
    cat: 'Regional & Cultural Tradition', c: 'Congolese masquerade repertory of the Pende peoples', e: 'regional_tradition',
    o: 'Democratic Republic of the Congo', g: 'DRC (Kwilu and Kasai Pende regions, Bandundu)', p: '19th century-present', era: 'precolonial Congo to present',
    sum: 'Richly stratified mask repertory of the Pende peoples — drooping-eyed mbuya character masks, the idealized female pwo, sickness masks and towering festival types.',
    desc: 'Pende masquerade divides into western (Kwilu) character masks and eastern (Kasai) festival traditions, unified by a signature drooping-lidded, upturned-nose face. The mbuya series caricatures social types — the chief, the diviner, the epileptic mbangu with its split black-and-white face, the wagging gitenga — while pwo, the beautiful woman mask with filed-teeth smile and braided coiffure, honors mothers and is danced with raffia costume by initiation graduates. Minganji and other fearsome types patrol circumcision festivals. Pende carving virtuosity made its masks a cornerstone of Central African museum holdings and modernist collecting.',
    col: [{ h: '#9c3d2e', n: 'camwood red' }, { h: '#efe7d6', n: 'kaolin white' }, { h: '#221c17', n: 'soot black' }, { h: '#b3813f', n: 'raffia gold' }, { h: '#5d4632', n: 'palm-oil brown' }],
    m: ['light hardwood masks', 'camwood red and kaolin pigments', 'raffia beards and fiber collars', 'pigment-saturated jute cloth'],
    tx: ['matte pigment wash', 'delicately striated coiffure', 'shaggy raffia fringe'],
    obj: ['mbuya character masks', 'pwo female masks', 'mbangu sickness masks', 'panya ngombe buffalo masks', 'minganji festival masks'],
    ex: ['Mbuya character masks of the Kwilu Pende', 'Pwo masks danced at initiation closings', 'Minganji masks of Kasai circumcision festivals'],
    inf: ['Lunda courtly inheritance', 'Pwo initiation practice', 'Belgian colonial collecting'], rel: ['Senufo Firespitter Masks', 'Punu White-Face Masks', 'Gelede Masquerade Art'],
    src: [{ n: 'Wikipedia — Pende people', u: 'https://en.wikipedia.org/wiki/Pende_people', t: 'B' }, { n: 'The Metropolitan Museum of Art — Pende masks', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['mask', 'pende', 'mbuya', 'pwo', 'congo', 'masquerade'],
    pop: 47, niche: true,
    vd: { shape: 'concave faces with drooping eyes and upturned nose', line: 'sinuous carved ridges, looping brows', composition: 'mask-type series arranged as character line-up', texture: 'soft matte pigment over fine wood grain' },
    typ: { display: 'mask type displayed with name and role', body: 'raffia costume with animated dance style', notes: 'face symmetry encodes beauty and health ideals' },
    lit: { quality: 'soft frontal museum light', temperature: 'warm', shadow: 'gentle hollows beneath lids and chin' },
    ui: { background: 'warm earth gradient', surface: 'pigment-washed cards', components: 'raffia-gold rounded buttons', motion: 'bobbing dance-step transitions' },
  },
  {
    n: 'Kota Reliquary Figures', a: ['Kota reliquaries', 'Mbulu ngulu figures'],
    cat: 'Religious & Sacred Art', c: 'brass-covered guardian figures of Gabonese reliquary cults', e: 'regional_tradition',
    o: 'Gabon & Equatorial Guinea', g: 'Gabon, Equatorial Guinea (Kota, Obamba, Mahongwe groups)', p: '18th-early 20th century', era: 'precolonial Gabon to early colonial era',
    sum: 'Abstract half-figure guardians in gleaming brass and copper sheet, mounted atop bark relic bundles that preserved the bones of Kota ancestors.',
    desc: 'Kota reliquary figures (mbulu ngulu) combine a carved hardwood body with faces sheathed in hammered brass and copper strips, their diamond, oval or hooded heads flashing above relic bundles of ancestral bone, medicine and iron. Placed on lineage reliquary baskets, they guarded against outsiders and channeled ancestral blessing, polished bright with sand and palm oil for ritual occasions. Regional variants range from the classic diamond-faced Obamba style to the deeply hooded Mahongwe type. Their radical abstraction transfixed European modernists, and removed figures are now icons of African sculpture in world collections.',
    col: [{ h: '#b08d3f', n: 'brass gold' }, { h: '#8c6b2f', n: 'aged copper' }, { h: '#2c241d', n: 'ebony wood' }, { h: '#d8c48a', n: 'polished flash' }, { h: '#5c4a2e', n: 'oxidized bronze' }],
    m: ['hardwood figure cores', 'brass and copper sheet overlay', 'iron and bone relic bundles', 'palm-oil polish'],
    tx: ['hammered metal striation', 'mirror metal flash', 'dark oiled wood base'],
    obj: ['mbulu ngulu reliquary figures', 'Mahongwe hooded heads', 'lineage relic baskets', 'guardian figure ensembles'],
    ex: ['Mbulu ngulu brass reliquary figures', 'Mahongwe hooded reliquary heads', 'Obamba diamond-faced guardian figures'],
    inf: ['Fang reliquary practice', 'Gabonese brass trade goods', 'European modernist collecting'], rel: ['Fang Reliquary Art', 'Nkisi Nkondi Power Figures', 'Benin Bronzes'],
    src: [{ n: 'Wikipedia — Kota people (Gabon)', u: 'https://en.wikipedia.org/wiki/Kota_people_(Gabon)', t: 'B' }, { n: 'The British Museum — Kota reliquary figures', u: 'https://www.britishmuseum.org', t: 'A' }],
    tg: ['reliquary', 'brass', 'kota', 'gabon', 'ancestor', 'mbulu ngulu'],
    pop: 49, niche: true,
    vd: { shape: 'asymmetric lozenge faces over tapering bodies', line: 'radiating repoussé ridges', composition: 'lone gleaming figure on dark ground', texture: 'hard metal sheen against matte wood' },
    typ: { display: 'figure atop its relic bundle', body: 'n/a — sacred guardian object', notes: 'metal brightness renewed for ceremonies' },
    lit: { quality: 'specular metal highlights', temperature: 'warm', shadow: 'sharp ridged shadows in repoussé' },
    ui: { background: 'deep charcoal field', surface: 'brass-toned reflective cards', components: 'hammered-metal rounded buttons', motion: 'glinting light-sweep reveals' },
  },
  {
    n: 'Mangbetu Courtly Elongation Aesthetics', a: ['Mangbetu court art', 'Lipombo elongation'],
    cat: 'Regional & Cultural Tradition', c: 'Northeast Congolese courtly arts and cranial elongation ideal', e: 'regional_tradition',
    o: 'Democratic Republic of the Congo', g: 'DRC (Bas-Uele, Mangbetu kingdom courts at Isiro and Nepoko)', p: '18th-early 20th century', era: 'Mangbetu kingdom zenith to colonial Congo',
    sum: 'Courtly aesthetic of the Mangbetu kingdom built on the elongated lipombo coiffure — royal portraiture, virtuoso harps, forged knives and gourd luxury arts.',
    desc: 'The Mangbetu kingdom of the northeastern Congo built a famously sophisticated court culture around the lipombo, cranial elongation bound in infancy and displayed through towering, architecture-like coiffures of oiled hair. Royal workshops produced figurative thrones and vessels, elongated-head harps and zithers of extraordinary finish, leaf-shaped trumbash throwing knives and gourd containers fitted with sculpted stoppers. Courtly portraiture fixed the elongated silhouette as an emblem of prestige, so that even colonial-era tourist carving adopted it. Mangbetu arts entered early museum collections through expeditions and remain emblems of Central African refinement.',
    col: [{ h: '#3b2a1e', n: 'dark carved wood' }, { h: '#a8865a', n: 'gourd tan' }, { h: '#5f4530', n: 'bark brown' }, { h: '#c9b28a', n: 'raffia cream' }, { h: '#7c3b2b', n: 'camwood red' }],
    m: ['hardwood figurative carving', 'gourd and calabash vessels', 'palm-oil dressed hair', 'forged iron and copper wire'],
    tx: ['silky hair dome sheen', 'polished gourd gloss', 'fine forge-hammered blade'],
    obj: ['elongated-coiffure court figures', 'Mangbetu harps and zithers', 'trumbash ceremonial knives', 'sculpted-stopper gourds', 'royal regalia and thrones'],
    ex: ['Court figures with elongated lipombo coiffures', 'Mangbetu harps in the Met and early expedition collections', 'Trumbash ceremonial knives'],
    inf: ['Mangbetu kingship and tribute economy', 'Azande courtly neighbours', 'expedition-era ethnographic collecting'], rel: ['Benin Royal Art', 'Kuba Shoowa', 'Fang Reliquary Art'],
    src: [{ n: 'Wikipedia — Mangbetu people', u: 'https://en.wikipedia.org/wiki/Mangbetu_people', t: 'B' }, { n: 'The Metropolitan Museum of Art — Mangbetu arts', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['court art', 'elongation', 'mangbetu', 'congo', 'regalia', 'harp'],
    pop: 41, niche: true,
    vd: { shape: 'towering elongated silhouettes and ovoid gourds', line: 'sleek vertical crown lines', composition: 'regal solitary figure with courtly props', texture: 'smooth oiled surfaces, fine forged steel' },
    typ: { display: 'court figure in full coiffure', body: 'bound head and tower hairstyle worn', notes: 'silhouette communicated rank at a glance' },
    lit: { quality: 'warm courtly lamplight', temperature: 'warm', shadow: 'long soft shadows off the crown' },
    ui: { background: 'umber royal gradient', surface: 'polished wood-tone cards', components: 'gourd-tan oval buttons', motion: 'stately slow pans' },
  },
  {
    n: 'Zaramo Mwana Hiti Figures', a: ['Mwana hiti dolls', 'Zaramo mwana hiti'],
    cat: 'Religious & Sacred Art', c: 'Tanzanian ancestral fertility doll tradition', e: 'regional_tradition',
    o: 'Tanzania', g: 'Tanzania (Dar es Salaam hinterland, Kariakoo to Coast Region)', p: '19th century-present', era: '19th-century Tanzania to present',
    sum: 'Cylindrical carved figures with cresting knife-blade hairdos — the mwana hiti "daughter of the throne" dolls mediating fertility, maturity and ancestral approval among the Zaramo.',
    desc: 'Mwana hiti figures of the Zaramo peoples near Dar es Salaam compress the human body into a slender column crowned by a thick, blade-shaped coiffure referencing chiefly thrones. Commissioned for girls at initiation and passed through matrilineal lines, the figures were fed, anointed and displayed so ancestral approval would grant fertility and safe childbirth; smaller versions served as ornaments, whistles and staff finials. Their radical reduction — face reduced to slit eyes, body to a smoothed cylinder — made them favorites of modernist collectors, while commissioned carving for the coastal trade sustained Zaramo workshops.',
    col: [{ h: '#6b4a33', n: 'carved dark brown' }, { h: '#d9cbb2', n: 'kaolin white' }, { h: '#8a6a3f', n: 'oiled wood tan' }, { h: '#a8332a', n: 'bead red' }, { h: '#2e4a5c', n: 'trade-cloth blue' }],
    m: ['soft carved wood', 'dark oiled patina', 'bead, string and cloth additions', 'kaolin body white'],
    tx: ['silky oiled carving', 'incised slit features', 'worn bead strung additions'],
    obj: ['mwana hiti initiation figures', 'miniature ornamental dolls', 'staff finials and whistles', 'naming-ceremony commissions'],
    ex: ['Mwana hiti ancestral pillar dolls', 'Mwali initiation headdress figures', 'coastal-trade commissioned Zaramo carvings'],
    inf: ['matrilineal ancestral veneration', 'Swahili coastal carving trade', 'Shirazi-influenced prestige styles'], rel: ['Akuaba Fertility Figures', 'Makonde Art', 'Kanga'],
    src: [{ n: 'Wikipedia — Zaramo people', u: 'https://en.wikipedia.org/wiki/Zaramo_people', t: 'B' }, { n: 'The Metropolitan Museum of Art — Mwana hiti figures', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['doll', 'fertility', 'zaramo', 'tanzania', 'mwana hiti', 'initiation'],
    pop: 38, niche: true,
    vd: { shape: 'slender columns with flat blade crests', line: 'one flowing carved profile, minimal facial marks', composition: 'single figure, vast negative space', texture: 'smooth oiled wood with subtle age crazing' },
    typ: { display: 'figure upright on cloth ground', body: 'held and fed by initiate owners', notes: 'anointing darkens and glosses the wood over years' },
    lit: { quality: 'soft window sidelight', temperature: 'warm', shadow: 'one clean long shadow' },
    ui: { background: 'sun-bleached tan wash', surface: 'smooth wood-grain cards', components: 'bead-red accent buttons', motion: 'quiet fade-in elevations' },
  },
  {
    n: 'Bamileke Kuosi Elephant Masks', a: ['Bamileke elephant masks', 'Kuosi society beadwork'],
    cat: 'Fashion & Dress', c: 'Cameroon Grassfields royal beadwork costume', e: 'regional_tradition',
    o: 'Cameroon', g: 'Cameroon (Grassfields fondoms — Bandjoun, Bafoussam, Baham)', p: '19th century-present', era: 'precolonial Grassfields kingdoms to present',
    sum: 'Two-panel beaded leopard-and-elephant costumes worn by Kuosi society dignitaries — red glass beads on black cloth with royal elephant masks, round hats and flywhisks.',
    desc: 'Among the Bamileke kingdoms of the Cameroon Grassfields, the Kuosi society — reserved for royalty, title-holders and their deputies — owns magnificent elephant mask costumes: two broad cloth panels shaped as elephant heads with broad flat ears and long trunks to the ground, completely beaded in red, white, black and polychrome glass beads with leopard motifs on the panels. Worn with feathered conical hats, blue tunic and flywhisk, the costume turns the dancer into a living emblem of kingly power — the elephant as royal wealth and the leopard as kingly beast. Palace workshops and court beadworkers continue the tradition at fondom festivals and royal funerals.',
    col: [{ h: '#8f2b23', n: 'bead red' }, { h: '#1c1714', n: 'cloth black' }, { h: '#d9a441', n: 'bead amber' }, { h: '#e9e2d2', n: 'bead white' }, { h: '#2f5c4a', n: 'bead green' }],
    m: ['glass trade beads', 'black cotton velour cloth', 'palm-rib armature frames', 'cowrie shells and brass bells'],
    tx: ['dense bead tessellation', 'napped cloth ground', 'swinging panel movement'],
    obj: ['elephant mask costumes (tse', 'kuosi society regalia', 'leopard beaded panels', 'royal conical hats', 'beaded palace stools and thrones'],
    ex: ['Kuosi elephant-mask costumes of Bandjoun', 'Leopard-themed dance panels at fondom festivals', 'Bamileke beaded thrones and stools'],
    inf: ['Grassfields kingship (fondom) hierarchy', 'trans-Saharan and coastal bead trade', 'German colonial era collecting'], rel: ['Yoruba Beaded Crowns', 'Gelede Masquerade Art', 'Benin Royal Art'],
    src: [{ n: 'Wikipedia — Elephant mask', u: 'https://en.wikipedia.org/wiki/Elephant_mask', t: 'B' }, { n: 'The Metropolitan Museum of Art — Cameroon Grassfields beadwork', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['beadwork', 'elephant mask', 'bamileke', 'grassfields', 'regalia', 'cameroon'],
    pop: 45, niche: true,
    vd: { shape: 'broad flat masks with hanging trunk panels', line: 'bead-row contours in tight spirals', composition: 'symmetrical two-panel frontality', texture: 'raised bead relief over black cloth' },
    typ: { display: 'costume displayed open like a coat', body: 'danced with hat, tunic and flywhisk', notes: 'leopard patterning marks royal prerogative' },
    lit: { quality: 'bright festival sun', temperature: 'warm', shadow: 'bead-glitter shading, crisp cloth folds' },
    ui: { background: 'black velour field', surface: 'beaded-pattern cards', components: 'red-bead circular buttons', motion: 'processional march-in reveals' },
  },
  {
    n: 'Malagasy Lamba Textiles', a: ['Lamba cloth', 'Lambamena shrouds'],
    cat: 'Textile & Craft', c: 'Malagasy woven cloth tradition', e: 'regional_tradition',
    o: 'Madagascar', g: 'Madagascar (Merina highlands, Ambatofinandrahana wild-silk centers)', p: 'precolonial-present', era: 'Merina kingdom era to modern Madagascar',
    sum: 'The lamba — Madagascar\'s defining cloth: silk and raffia wrappers, striped lamba akotofahana and lambamena burial shrouds binding the living to the ancestors.',
    desc: 'Lamba names the rectangular cloth central to Malagasy identity across every region, draped as wrappers, shoulder cloths and baby carriers and exchanged at every life passage. The highlands wove wild Landibe silk from Borocera moth cocoons into shimmering striped lamba akotofahana, while the lambamena — grand red silk burial shroud of the Merina — is essential to famadihana reburial rites, when families rewrap ancestors in fresh lamba. Raffia and cotton lambas served daily life and trade. Print patterns, natural dyes and strip-weave structure make lamba the visual signature of Madagascar from court portraits to the modern runway.',
    col: [{ h: '#e8dfd0', n: 'raw silk ivory' }, { h: '#b03526', n: 'lambamena red' }, { h: '#243a55', n: 'indigo stripe' }, { h: '#6d6a5f', n: 'wild-silk gray' }, { h: '#c9a24b', n: 'woven gold' }],
    m: ['wild landibe silk', 'raffia and cotton', 'natural mordant dyes', 'strip-weave seams'],
    tx: ['lustrous silk sheen', 'crisp striped ribbing', 'supple raffia stiffness'],
    obj: ['lambamena burial shrouds', 'lamba akotofahana ceremonial wrappers', 'raffia everyday lamba', 'baby-carrying and exchange cloths'],
    ex: ['Merina lambamena red silk shrouds for famadihana', 'lamba akotofahana wild-silk ceremonial wrappers', '19th-century royal lamba presented as gifts'],
    inf: ['Merina courtly dress codes', 'Austronesian weaving inheritance', 'famadihana ancestral rites'], rel: ['Kanga', 'Kente Weaving', 'Bogolanfini'],
    src: [{ n: 'Wikipedia — Lamba (clothing)', u: 'https://en.wikipedia.org/wiki/Lamba_(clothing)', t: 'B' }, { n: 'The British Museum — Malagasy textiles', u: 'https://www.britishmuseum.org', t: 'A' }],
    tg: ['silk', 'madagascar', 'lamba', 'shroud', 'strip weave', 'famadihana'],
    pop: 43, niche: true,
    vd: { shape: 'long rectangular drapes, banded stripes', line: 'warp-wise stripe rhythm', composition: 'wearer wrapped, one shoulder highlighted', texture: 'hand-loomed silk with soft sheen' },
    typ: { display: 'lamba hung full-length with drape folds', body: 'wrapped at shoulder and waist', notes: 'quality of cloth signals age, region and rank' },
    lit: { quality: 'highland daylight', temperature: 'cool-warm mix', shadow: 'soft fold shadows in drape' },
    ui: { background: 'ivory silk wash', surface: 'striped woven cards', components: 'indigo-stripe ribbon buttons', motion: 'draping slow-fall transitions' },
  },
  {
    n: 'Korhogo Cloth Painting', a: ['Korhogo cloth', 'Senufo painted cloth'],
    cat: 'Textile & Craft', c: 'Ivorian mud-painted cotton tradition', e: 'regional_tradition',
    o: 'Côte d\'Ivoire', g: 'Côte d\'Ivoire (Korhogo town, Senufo country, northern savanna)', p: 'mid-20th century-present', era: 'post-independence Côte d\'Ivoire to present',
    sum: 'Hand-painted cotton cloths from Korhogo in northern Côte d\'Ivoire — fermented mud figures of chameleons, birds, dancers and glyphs on unbleached strip-woven cloth.',
    desc: 'Korhogo cloth is produced around the northern Ivorian town of Korhogo by Senufo artists who paint fermented mud slurry, leaf decoctions and kaolin onto handwoven cotton strips, then sun-fix the designs into rust-brown, black and ochre. Panels fill with incised-looking motifs — chameleons, fish, birds, spiral glyphs, masked dancers and rhythm pestles — drawn freehand with twigs and combs in a controlled naiveté that became one of West Africa\'s most recognized contemporary craft exports. Rooted in Senufo graphic traditions and poro-society imagery, the cloth now spans fair-trade workshops, fashion and interior design worldwide.',
    col: [{ h: '#d8c9a8', n: 'unbleached cotton' }, { h: '#4a3527', n: 'mud ochre-brown' }, { h: '#8c6b45', n: 'fermented rust' }, { h: '#2e2620', n: 'charcoal figure' }, { h: '#b3a284', n: 'sun-bleached field' }],
    m: ['handwoven cotton strip cloth', 'fermented mud slurry pigment', 'kaolin and leaf decoctions', 'shea-butter finishing'],
    tx: ['chalky mud-paint matte', 'comb-drawn hatching', 'cotton slub ground'],
    obj: ['painted wall panels', 'Senufo graphic cloths', 'fair-trade workshop textiles', 'fashion and furnishing yardage'],
    ex: ['Hand-painted chameleon and bird motif panels', 'Senufo poro-society painted cloths', 'Korhogo workshop yardage for export fashion'],
    inf: ['Senufo poro society graphic arts', 'Bogolanfini mud-painting parallels', 'post-independence craft export schemes'], rel: ['Senufo Firespitter Masks', 'Bogolanfini', 'Adinkra'],
    src: [{ n: 'Wikipedia — Korhogo cloth', u: 'https://en.wikipedia.org/wiki/Korhogo_cloth', t: 'B' }, { n: 'The Metropolitan Museum of Art — African textiles', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['mud cloth', 'senufo', 'korhogo', 'painted textile', 'ivory coast'],
    pop: 48, niche: true,
    vd: { shape: 'totem-like animals and stacked glyph registers', line: 'thin twig-drawn contours with comb hatching', composition: 'border-to-border repeat of single motif rows', texture: 'gritty matte paint sinking into slub cotton' },
    typ: { display: 'motif panels hung as wall art', body: 'worn as wrappers and fashion cloth', notes: 'each panel hand-painted, no two repeats identical' },
    lit: { quality: 'bright even savanna daylight', temperature: 'warm', shadow: 'flat, minimal — graphic flatness' },
    ui: { background: 'sun-bleached cotton field', surface: 'mud-toned painted cards', components: 'ochre-line outline buttons', motion: 'gentle paint-soak fades' },
  },
  {
    n: 'Akwete Cloth Weaving', a: ['Akwete cloth', 'Akwaete wrapper weaving'],
    cat: 'Textile & Craft', c: 'Igbo women\'s broad-loom weaving tradition', e: 'regional_tradition',
    o: 'Nigeria', g: 'Nigeria (Akwete town, Ndoki Igbo, Abia State)', p: '19th century-present', era: '19th-century Igbo heartland to present',
    sum: 'Dense, ornate wrapper cloths woven by Igbo women of Akwete town — heavy cotton grounds inlaid with silk, velvet and bold motifs, once prestige export across the Niger Delta.',
    desc: 'Akwete cloth, woven by the women of Akwete in Ndoki country, Abia State, is Nigeria\'s classic broad-loom textile: panels up to a meter wide woven on upright looms in cotton, densely inlaid with bought silk, velvet, metallic threads and deep banding into heavy prestige wrappers. Motifs named after everyday things — combs, cocoyams, tortoise shells, even the 50-naira note — ride thick raised bands across the ground cloth. Historically bridal and title-holder dress and a major Niger Delta trade good, the craft passed mother-to-daughter through guild-like apprenticeship and remains a marker of Igbo female artistry and entrepreneurship.',
    col: [{ h: '#7c2d2d', n: 'madder red' }, { h: '#d9c9a8', n: 'cotton cream' }, { h: '#2f5c4a', n: 'indigo green' }, { h: '#c98a3d', n: 'silk gold' }, { h: '#3b3a55', n: 'trade purple' }],
    m: ['handspun cotton warp', 'silk and velvet inlay yarns', 'indigo and camwood dyes', 'upright broad looms'],
    tx: ['heavy inlaid bands', 'velvet pile patches', 'tightly beaten warp face'],
    obj: ['bridal wrapper cloths', 'title-holder prestige wrappers', 'tapestry-pattern hangings', 'Niger Delta trade cloth'],
    ex: ['Dense tapestry-pattern wrapper cloths of Akwete', 'Bridal and title-holder prestige wrappers', 'Ndoki trade cloth exported through the Niger Delta'],
    inf: ['Igbo women\'s weaving guilds', 'Niger Delta trade networks', 'Uli design vocabulary'], rel: ['Uli Body & Wall Painting', 'Adire Eleko', 'Aso Oke'],
    src: [{ n: 'Wikipedia — Akwete cloth', u: 'https://en.wikipedia.org/wiki/Akwete_cloth', t: 'B' }, { n: 'The British Museum — Akwete textiles', u: 'https://www.britishmuseum.org', t: 'A' }],
    tg: ['weaving', 'igbo', 'akwete', 'wrapper', 'nigeria', 'broad loom'],
    pop: 42, niche: true,
    vd: { shape: 'banded horizontal registers with named motifs', line: 'chunky inlaid band edges', composition: 'bold central band between plain selvages', texture: 'thick, weighty cloth with raised inlay' },
    typ: { display: 'wrapper draped to show band structure', body: 'worn full-length at weddings and titles', notes: 'motifs carry names remembered by weaving families' },
    lit: { quality: 'bright even workshop light', temperature: 'warm', shadow: 'soft pile shadows in velvet inlays' },
    ui: { background: 'cream cotton wash', surface: 'banded weave-pattern cards', components: 'silk-gold pill buttons', motion: 'shuttle-rap slide transitions' },
  },
  {
    n: 'Bwa Plank Masks', a: ['Bwa plank masks', 'Nwantantay masks'],
    cat: 'Regional & Cultural Tradition', c: 'Voltaic geometric plank mask tradition', e: 'regional_tradition',
    o: 'Burkina Faso', g: 'Burkina Faso (Bwa villages of Dossi, Boni, Houndé area)', p: '19th century-present', era: 'precolonial Volta region to present',
    sum: 'Towering geometric plank masks of the Bwa people — concentric faces, checkerboards and crescent horns — danced at harvest and initiation to embody wild nature spirits.',
    desc: 'Bwa plank masks (nwantantay) of Burkina Faso rise two meters or more: round concentric-circle faces under tall rectangular planks carved with checkerboards, triangles and zigzags in black, white and red ochre, topped by crescent horns and fiber beards that hide the dancer. Embodying su, wild bush spirits that protect the village, the masks leap and spin at harvest, initiation and mourning performances, their spinning fibers flashing as they charge spectators. Documented widely since the 1930s, Bwa masquerade — alongside neighbouring Gurunsi and Nuna carving — became the emblematic image of Voltaic geometric abstraction.',
    col: [{ h: '#1c1a17', n: 'carbon black' }, { h: '#e8ddc8', n: 'kaolin white' }, { h: '#a8332a', n: 'oxide red' }, { h: '#caa24d', n: 'ochre tan' }, { h: '#5d5a50', n: 'fiber gray' }],
    m: ['sese wood plank carving', 'kaolin, charcoal and red ochre', 'plant-fiber costumes', 'natural fiber cords'],
    tx: ['flat carved plane', 'crisp pigment edging', 'swinging fiber fringe'],
    obj: ['nwantantay plank masks', 'hawk and serpent horizontal masks', 'full fiber dance costumes', 'village spirit masks for harvest rites'],
    ex: ['Great hawk plank masks of Dossi festivals', 'Nwantantay masks at initiation performances', 'serpent and buffalo masks of Boni villages'],
    inf: ['Voltaic mask festivals', 'Bwa su bush-spirit cults', 'European modernist collecting'], rel: ['Senufo Firespitter Masks', 'Dogon Architecture', 'Gelede Masquerade Art'],
    src: [{ n: 'Wikipedia — Bwa people', u: 'https://en.wikipedia.org/wiki/Bwa_people', t: 'B' }, { n: 'The Metropolitan Museum of Art — Bwa plank masks', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['plank mask', 'bwa', 'burkina faso', 'masquerade', 'geometric', 'voltaic'],
    pop: 46, niche: true,
    vd: { shape: 'stacked rectangles, circles and crescents', line: 'hard-edge black-white-red divisions', composition: 'vertical totem pole masked figure centered', texture: 'flat matte pigment over plank wood' },
    typ: { display: 'mask shown full-height with fiber beard', body: 'danced with full raffia suit, leaping charges', notes: 'geometry encodes clan spirit identities' },
    lit: { quality: 'harsh Harmattan sun', temperature: 'warm', shadow: 'hard graphic shadows off plank edges' },
    ui: { background: 'red-earth savanna wash', surface: 'geometric pattern cards', components: 'checkerboard block buttons', motion: 'spin-and-charge quick cuts' },
  },
]
