/**
 * Wave 16 — Americas & Oceania: 16 hand-verified Indigenous and colonial traditions.
 * Duplicate-checked against existing-names.txt (skipped assigned names already covered:
 * Kinngait Printmaking, Inuit Soapstone Carving, Yupik Masks, Chilkat Weaving, Hamatsa,
 * Lakota Porcupine Quillwork, Huichol Yarn Painting, Shipibo Kené, Paracas Textiles,
 * Moche Fineline Pottery). Substitutes verified absent before inclusion.
 */
export const ENTRIES: any[] = [
  {
    n: 'Haida Argillite Carving', a: ['Haida argillite sculpture', 'Argillite carving', 'Haida slate carving', 'Argillite pipes'],
    cat: 'Material & Surface', c: 'Haida carved black-shale sculpture tradition', e: 'regional_tradition',
    o: 'Haida Gwaii, British Columbia, Canada', g: 'Canada (Haida Gwaii; 19th-century fur-trade and Victorian markets)', p: 'c. 1810-present', era: 'Fur-trade and colonial Northwest Coast',
    sum: 'Haida-carved black shale sculpture from a single Slatechuck quarry — tobacco pipes, model poles and dishware made for fur-trade and Victorian markets, still carved today.',
    desc: 'Haida carvers began shaping argillite — a black carbonaceous shale quarried only at Slatechuck Creek on Haida Gwaii — around 1810. The golden age (1840s-1870s) produced carved tobacco pipes, model totem poles, dishes and figural groups for sailors and Victorian collectors; masters like Charles Edenshaw bent formline design into the stone, often with abalone inlay. After the 1885 potlatch ban, model poles stood in for full-size ones. Haida artists still quarry and carve argillite today.',
    col: [{ h: '#1d1e22', n: 'charcoal black' }, { h: '#4a4d52', n: 'smoke gray' }, { h: '#2c3440', n: 'slate blue-gray sheen' }, { h: '#e8e2d2', n: 'ivory inlay' }, { h: '#7f9fa8', n: 'abalone flash' }],
    m: ['Slatechuck argillite shale', 'steel gravers and files', 'abalone and ivory inlay', 'oiled finish'],
    tx: ['sooty matte grain', 'incised formline groove', 'polished sheen bands'],
    obj: ['carved tobacco pipes', 'model totem poles', 'platters and servers', 'figural groups', 'engraved dishware'],
    ex: ['Charles Edenshaw argillite pipes (Canadian Museum of History)', 'mid-19th-century model poles (Pitt Rivers Museum)', 'contemporary Haida argillite (Bill Reid Gallery, Vancouver)'],
    inf: ['Haida formline design', 'Victorian collecting tastes', 'Northwest Coast monumental pole carving'], rel: ['Haida Formline Art', 'Edenshaw-era Silver Engraving', 'Northwest Coast Bentwood Boxes'],
    src: [{ n: 'Wikipedia — Haida people', u: 'https://en.wikipedia.org/wiki/Haida_people', t: 'B' }, { n: 'Smithsonian NMAI — Northwest Coast collections', u: 'https://americanindian.si.edu', t: 'A' }],
    tg: ['argillite', 'haida', 'northwest coast', 'black shale', 'trade art', 'formline'],
    pop: 34, niche: true,
    vd: { shape: 'compact pipes and scaled-down pole forms', line: 'incised formline contours in low relief', composition: 'stacked crest figures wrapping slender shafts', texture: 'sooty matte stone with polished raised crests' },
    typ: { display: 'incised maker and crest marks only', body: 'n/a', notes: 'model poles record crest rights during potlatch ban' },
    lit: { quality: 'soft directional light on relief', temperature: 'cool', shadow: 'shallow incised shadows' },
    ui: { background: 'near-black charcoal field', surface: 'carved dark-stone panels', components: 'slate-gray outlined buttons', motion: 'slow sheen fades' },
  },
  {
    n: 'Parfleche Painting', a: ['Parfleche bag', 'Parfleche envelope', 'Painted rawhide container', 'Parfleche case'],
    cat: 'Material & Surface', c: 'Painted rawhide container tradition of the Plains', e: 'regional_tradition',
    o: 'North American Great Plains', g: 'United States and Canada (Lakota, Crow, Comanche, Nez Perce and Plateau nations)', p: '18th century-present', era: 'Horse-era Plains to present',
    sum: 'Painted rawhide envelopes and cases of the Plains nations — stiff hides folded without stitching, mapped with bold geometric color systems distinct to each tribe.',
    desc: 'Parfleche is raw buffalo hide scraped pliable, folded into envelopes, cases and saddle bags, then painted by women with mineral and vegetal pigments. Designs are rigorously geometric — hourglasses, triangles, barred fields — and each nation keeps its own palette; Crow cases run to two colors, Lakota to layered blues, reds and greens. Made to carry dried meat and clothing on horse travels, parfleche remains a living women\'s tradition with contemporary makers at Plains communities.',
    col: [{ h: '#e5d9bd', n: 'rawhide cream' }, { h: '#c49a6c', n: 'buffalo tan' }, { h: '#8c3b2e', n: 'oxblood red' }, { h: '#274b6d', n: 'deep blue' }, { h: '#241f1a', n: 'black contour' }],
    m: ['raw buffalo and horse hide', 'vegetal and mineral pigments', 'sinew ties', 'bone flesher tools'],
    tx: ['stiff parchment grain', 'flat gouged pigment fields', 'inked black contours'],
    obj: ['folded envelope bags', 'flat storage cases', 'saddle-bag pairs', 'tepee bags', 'horse trappings'],
    ex: ['Lakota painted envelopes (Smithsonian NMAI)', 'Crow two-color cases (Plains Indian Museum, Cody)', 'Nez Perce folded saddle bags (Field Museum)'],
    inf: ['Plains pictographic hide painting', 'Horse nomad transport culture', 'Women\'s painting guilds of the Plains'], rel: ['Lakota Beadwork', 'Lakota Porcupine Quillwork', 'Plains Ledger Art'],
    src: [{ n: 'Wikipedia — Parfleche', u: 'https://en.wikipedia.org/wiki/Parfleche', t: 'B' }, { n: 'Smithsonian NMAI — Parfleche collections', u: 'https://americanindian.si.edu', t: 'A' }],
    tg: ['rawhide', 'plains', 'geometric', 'painted hide', 'lakota', 'envelope'],
    pop: 36, niche: true,
    vd: { shape: 'rectangular folded slabs with lashed flaps', line: 'hard-edged pigment bands and hourglass motifs', composition: 'symmetrical front-field panel with banded sides', texture: 'dry rawhide tooth under flat paint' },
    typ: { display: 'pictographic ownership marks only', body: 'n/a', notes: 'design color-codes identify nation and maker line' },
    lit: { quality: 'bright even daylight', temperature: 'warm', shadow: 'minimal, edge-only' },
    ui: { background: 'rawhide cream ground', surface: 'painted geometric cards', components: 'barred rectangle buttons', motion: 'crisp wipe reveals' },
  },
  {
    n: 'Haudenosaunee Wampum & Beadwork', a: ['Wampum belt', 'Wampum belts', 'Raised beadwork', 'Iroquois raised beadwork', 'Two Row Wampum'],
    cat: 'Textile & Craft', c: 'Shell-belt diplomacy and raised beadwork of the Six Nations', e: 'regional_tradition',
    o: 'Northeastern Woodlands (New York, Ontario, Quebec)', g: 'United States and Canada (Mohawk, Oneida, Onondaga, Cayuga, Seneca, Tuscarora)', p: 'c. 1600-present', era: 'Contact era to present',
    sum: 'Purple-and-white wampum shell belts recording covenants and law, alongside Haudenosaunee raised beadwork — dimensional floral moccasins, pincushions and whimseys.',
    desc: 'Wampum beads, cut from quahog clam and whelk shell in purple and white, were woven into belts that served Haudenosaunee diplomacy: the Two Row Wampum and Hiawatha Belt encode treaties and the Great Law, read aloud at council. A related women\'s art, raised beadwork, builds glass seed beads into stuffed three-dimensional florals on moccasins, caps and pincushions, famously sold through 19th-century Niagara Falls. Both remain living traditions in Six Nations communities.',
    col: [{ h: '#4d3a5e', n: 'quahog purple' }, { h: '#efe9dc', n: 'wampum white' }, { h: '#a3312f', n: 'bead crimson' }, { h: '#9db9c4', n: 'pale seed blue' }, { h: '#23211f', n: 'trade cloth black' }],
    m: ['quahog and whelk shell wampum', 'glass seed beads', 'dyed trade cloth', 'sinew and linen thread'],
    tx: ['polished shell cylinder sheen', 'padded dimensional bead loops', 'crisp belt weave'],
    obj: ['covenant belts (Two Row, Hiawatha)', 'condolence strings', 'raised floral pincushions', 'beaded moccasins and caps', 'picture-frame whimseys'],
    ex: ['Hiawatha Belt replica (Smithsonian NMAI)', 'Onondaga Nation wampum belts', '19th-century Niagara raised-beadwork whimseys (Rochester Museum)'],
    inf: ['Great League of Peace diplomacy', 'Dutch and British treaty protocol', 'Victorian souvenir markets'],
    rel: ['Lakota Floral Beadwork', 'Osage Ribbonwork', 'Seminole Patchwork'],
    src: [{ n: 'Wikipedia — Wampum', u: 'https://en.wikipedia.org/wiki/Wampum', t: 'B' }, { n: 'Smithsonian NMAI — wampum holdings', u: 'https://americanindian.si.edu', t: 'A' }],
    tg: ['wampum', 'shell beads', 'treaty belt', 'raised beadwork', 'iroquois', 'diplomacy'],
    pop: 45, niche: false,
    vd: { shape: 'wide belt rectangles with central glyph devices', line: 'purple figures held by white ground rows', composition: 'single emblem centered in belt bands', texture: 'glassy shell cylinders in flat weave' },
    typ: { display: 'no lettering — pictographic belt glyphs', body: 'n/a', notes: 'belts read aloud rather than inscribed' },
    lit: { quality: 'even gallery light', temperature: 'cool', shadow: 'low, bead-on-cloth crispness' },
    ui: { background: 'white shell ground', surface: 'purple emblem panels', components: 'woven-band buttons and dividers', motion: 'deliberate slide unveilings' },
  },
  {
    n: 'Seminole Patchwork', a: ['Seminole strip patchwork', 'Seminole piecing', 'Miccosukee patchwork', 'Seminole patchwork skirt'],
    cat: 'Textile & Craft', c: 'Strip-pattern cotton patchwork of the Florida Seminole and Miccosukee', e: 'regional_tradition',
    o: 'Florida, USA', g: 'United States (Seminole and Miccosukee communities; Big Cypress, Brighton, Hollywood)', p: 'late 1800s-present', era: 'Florida reservation era to present',
    sum: 'Machine-stitched strip patchwork of the Florida Seminole and Miccosukee — bands of dazzling geometric designs sewn into the long skirts that define tribal dress.',
    desc: 'With hand-crank sewing machines and bright trade cottons, Seminole women in the late 19th century invented a fast strip-piecing system: strips cut, reversed and re-stitched into rhythmic bands — windmills, crossed bars, arrow motifs — built into the long striped skirts and capes worn daily and at Green Corn Dance. Unlike Euro-American quilting, the patchwork bands are the garment itself. Miccosukee and Seminole seamstresses still sew the designs as markers of community identity.',
    col: [{ h: '#c8342c', n: 'band red' }, { h: '#f0b429', n: 'marigold yellow' }, { h: '#1f5fa8', n: 'band blue' }, { h: '#1e7a4e', n: 'band green' }, { h: '#f4ede0', n: 'cotton white' }],
    m: ['bright commercial cottons', 'hand-crank and treadle machines', 'cotton thread', 'paper templates'],
    tx: ['crisp pieced edges', 'registered stripe rhythm', 'mercerized sheen'],
    obj: ['long patchwork skirts', 'matching capes and jackets', 'men\'s big shirts', 'sashes and bandolier straps', 'patchwork doll dresses'],
    ex: ['Ah-Tah-Thi-Ki Museum patchwork collection', 'early 20th-century skirts (Smithsonian NMAI)', 'contemporary Miccosukee dress at Green Corn Dance'],
    inf: ['Euro-American strip quilting', 'post-war trade-cloth availability', 'Southeastern appliqué dress traditions'],
    rel: ['Osage Ribbonwork', 'Guna Mola Reverse Appliqué', 'Haudenosaunee Wampum & Beadwork'],
    src: [{ n: 'Wikipedia — Seminole', u: 'https://en.wikipedia.org/wiki/Seminole', t: 'B' }, { n: 'Smithsonian NMAI — Seminole textiles', u: 'https://americanindian.si.edu', t: 'A' }],
    tg: ['patchwork', 'strip piecing', 'seminole', 'miccosukee', 'florida', 'band sewing'],
    pop: 37, niche: true,
    vd: { shape: 'vertical skirt panels of stacked bands', line: 'zigzag and windmill pieced diagonals', composition: 'repeating band register down the garment', texture: 'flat pressed cotton with knife-crisp seams' },
    typ: { display: 'no lettering — bands carry identity', body: 'full garments are the tradition', notes: 'band designs named within communities' },
    lit: { quality: 'bright even light', temperature: 'warm', shadow: 'none — flat color' },
    ui: { background: 'white cotton field', surface: 'stacked band-pattern cards', components: 'zigzag-striped buttons', motion: 'quick band wipes' },
  },
  {
    n: 'Pomo Basketry', a: ['Pomo feathered basketry', 'Pomo treasure baskets', 'Feathered gift baskets'],
    cat: 'Textile & Craft', c: 'Feathered coiled baskets of Northern California', e: 'regional_tradition',
    o: 'Northern California, USA (Russian River, Clear Lake)', g: 'United States (Pomo, Wappo and Clear Lake weavers)', p: 'pre-contact-present', era: 'California Indian era to present',
    sum: 'World-famous California coiled baskets — some smaller than a dime — surfaced in feather mosaic of woodpecker, quail and mallard with shell-bead ornament.',
    desc: 'Pomo weavers coiled sedge root, willow and bulrush into watertight utility baskets; their treasure baskets became internationally renowned, encrusted in feather mosaic — acorn woodpecker reds, quail plumes, mallard curves — with clamshell and magnesite beads, given as ceremonial gifts or sold to museums from the 1890s. Weavers like Mabel McKay carried the knowledge into the 20th century, alongside record-holding thimble-scale miniatures. The tradition remains active and taught today.',
    col: [{ h: '#c9a26a', n: 'sedge root tan' }, { h: '#a3312f', n: 'woodpecker crimson' }, { h: '#6f6255', n: 'quail gray-brown' }, { h: '#f0ead9', n: 'clamshell white' }, { h: '#2a251f', n: 'bracken black' }],
    m: ['sedge root', 'willow shoots', 'feathers (acorn woodpecker, quail, mallard)', 'clamshell and magnesite beads'],
    tx: ['tight coil ridges', 'downy feather nap', 'shell-bead sparkle'],
    obj: ['feathered gift baskets', 'globular water baskets', 'seed beaters', 'miniature show baskets', 'dancing baskets'],
    ex: ['Mabel McKay feather baskets (Grace Hudson Museum)', 'Pomo treasure baskets (Phoebe A. Hearst Museum)', 'thimble-scale miniature baskets (Field Museum)'],
    inf: ['California acorn-processing economy', 'Ceremonial gift exchange', 'Late-19th-century museum collecting'],
    rel: ['Tohono O\'odham Basketry', 'Mexica Featherwork', 'Lakota Porcupine Quillwork'],
    src: [{ n: 'Wikipedia — Pomo', u: 'https://en.wikipedia.org/wiki/Pomo', t: 'B' }, { n: 'The Metropolitan Museum of Art — Native American baskets', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['basketry', 'coiling', 'feather mosaic', 'california', 'pomo', 'miniature'],
    pop: 33, niche: true,
    vd: { shape: 'rounded bowl volumes, flawless geometry', line: 'unbroken spiral coil lines', composition: 'feather bands and bead zones wrapping the curve', texture: 'velvety feathers over rigid coil armature' },
    typ: { display: 'no lettering — pattern and beads only', body: 'n/a', notes: 'finest show baskets never used functionally' },
    lit: { quality: 'warm raking light for nap and gloss', temperature: 'warm', shadow: 'soft coil shadow ripples' },
    ui: { background: 'sedge tan field', surface: 'feather-textured cards', components: 'shell-bead round buttons', motion: 'gentle feather-drift transitions' },
  },
  {
    n: 'Cuzco School Painting', a: ['Cusco School', 'Escuela Cuzqueña', 'Cusco School of painting', 'Andean Baroque painting'],
    cat: 'Religious & Sacred Art', c: 'Colonial Andean Catholic painting school', e: 'historical',
    o: 'Cusco, Peru', g: 'Viceroyalty of Peru (Cusco, Lake Titicaca, Upper Peru workshops)', p: 'c. 1570-1800', era: 'Colonial Peru (Viceroyalty)',
    sum: 'Colonial Andean school fusing European Baroque painting with Quechua and Inca taste — gold-brocaded Madonnas, flat luminous archangels with arquebuses, native patrons.',
    desc: 'Founded after the Italian Jesuit painter Bernardo Bitti arrived in 1575, the Cuzco School trained Indigenous and mestizo artists — Diego Quispe Tito, Basilio Santa Cruz, Marcos Zapata — who recast Counter-Reformation imagery in Andean terms: Madonnas in gold brocade, archangel arquebusiers, a cathedral Last Supper serving cuy and chicha. Workshops exported formula canvases across the Andes until the 1780 Túpac Amaru uprising closed its golden age; its canvases still line Cusco\'s churches.',
    col: [{ h: '#c9a227', n: 'brocade gold' }, { h: '#8c2b2b', n: 'deep carmine' }, { h: '#2e6b4f', n: 'Andean green' }, { h: '#3a2a20', n: 'shadow umber' }, { h: '#ece4d4', n: 'lead white' }],
    m: ['canvas and panel', 'oil and tempera', 'gold leaf (estofado)', 'mineral pigments'],
    tx: ['gilded brocade relief', 'hard enamel-like color', 'dark ground craquelure'],
    obj: ['brocaded Virgin Madonnas', 'archangel arquebusiers', 'cathedral Last Suppers', 'processional saint canvases', 'corpus series for parishes'],
    ex: ['Marcos Zapata Last Supper (Cusco Cathedral)', 'Diego Quispe Tito zodiac cycle (Cusco Cathedral)', 'Museo de Arte Religioso collections (Archbishop\'s Palace, Cusco)'],
    inf: ['Spanish Mannerism and Flemish prints', 'Counter-Reformation iconography', 'Inca royal textile aesthetics'],
    rel: ['Cusco Architecture', 'Ex-voto Retablo', 'Talavera Poblana'],
    src: [{ n: 'Wikipedia — Cusco School', u: 'https://en.wikipedia.org/wiki/Cusco_School', t: 'B' }, { n: 'The Metropolitan Museum of Art — colonial Andean painting', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['colonial', 'baroque', 'andean', 'cuzco', 'religious painting', 'viceroyalty'],
    pop: 52, niche: false,
    vd: { shape: 'elongated elegant figures, stacked saint rows', line: 'fine contour with hard highlight dashes', composition: 'centered icon beneath brocaded canopy zones', texture: 'smooth enamel paint over gilded relief cloth' },
    typ: { display: 'Latin inscriptions and donor marks', body: 'n/a', notes: 'signatures rare; workshops anonymous' },
    lit: { quality: 'candle-warm church light', temperature: 'warm', shadow: 'deep tenebrist pools' },
    ui: { background: 'carmine ground', surface: 'gold-brocade framed panels', components: 'gilt-outline buttons', motion: 'slow ceremonial fades' },
  },
  {
    n: 'Osage Ribbonwork', a: ['Osage ribbon work', 'Ribbonwork (Osage)', 'Osage ribbon dresses'],
    cat: 'Textile & Craft', c: 'Layered ribbon appliqué of the Osage Nation', e: 'regional_tradition',
    o: 'Oklahoma, USA (formerly Missouri and Arkansas homelands)', g: 'United States (Osage Nation, Oklahoma)', p: '1880s-present', era: 'Reservation era to present',
    sum: 'Precision-layered satin ribbonwork of the Osage — nested cut ribbon streamers and sunburst rosettes central to In-lon-schka dances and ceremonial dress.',
    desc: 'After removal to Indian Territory, Osage women turned commercial satin ribbon into one of Native America\'s most refined appliqué arts: ribbons folded, stacked and knife-cut into nested geometric and floral layers, sewn onto blankets, dresses and men\'s shirts. Oil wealth of the 1910s-20s funded spectacular In-lon-schka regalia, where ribbonwork remains required ceremonial dress. Osage seamstresses, often sewing for grandsons\' dances, keep the practice vigorous, designs passing family to family.',
    col: [{ h: '#b8232f', n: 'satin scarlet' }, { h: '#f0c02e', n: 'sunshine yellow' }, { h: '#1f7a6e', n: 'ribbon teal' }, { h: '#211e1c', n: 'broadcloth black' }, { h: '#f2ece0', n: 'iridescent white' }],
    m: ['silk and satin trade ribbons', 'black wool broadcloth', 'cotton thread', 'paper patterns and scissors'],
    tx: ['satin sheen bands', 'knife-sharp cut edges', 'layered relief stacking'],
    obj: ['ribbon dresses with matching blankets', 'men\'s ribbon shirts', 'stole and shawl streamers', 'sunburst rosette yokes', 'dance blankets'],
    ex: ['In-lon-schka dance regalia (Osage Nation, Oklahoma)', 'Osage ribbonwork dresses (Gilcrease Museum)', '19th-century blanket overlays (Smithsonian NMAI)'],
    inf: ['Eastern Woodlands ribbon-appliqué dress', 'post-removal trade-ribbon economy', 'Osage ceremonial dance cycle'],
    rel: ['Lakota Floral Beadwork', 'Seminole Patchwork', 'Haudenosaunee Wampum & Beadwork'],
    src: [{ n: 'Wikipedia — Osage Nation', u: 'https://en.wikipedia.org/wiki/Osage_Nation', t: 'B' }, { n: 'Smithsonian NMAI — Osage collections', u: 'https://americanindian.si.edu', t: 'A' }],
    tg: ['ribbonwork', 'appliqué', 'osage', 'oklahoma', 'dance regalia', 'satin'],
    pop: 31, niche: true,
    vd: { shape: 'nested streamers, stepped rosette medallions', line: 'radiating layered ribbon edges', composition: 'symmetrical stacked layers across garment centers', texture: 'glossy satin tiers over matte wool' },
    typ: { display: 'no lettering — layered pattern only', body: 'ceremonial garments are the tradition', notes: 'color sets signal family and dance society' },
    lit: { quality: 'bright specular ribbon sheen', temperature: 'warm', shadow: 'crisp tier shadows' },
    ui: { background: 'broadcloth black field', surface: 'layered satin-pattern cards', components: 'streamer-cut ribbon buttons', motion: 'layered peel-in reveals' },
  },
  {
    n: 'Plains Ledger Art', a: ['Ledger art', 'Ledger drawings', 'Plains pictographic drawing', 'Fort Marion art'],
    cat: 'Regional & Cultural Tradition', c: 'Narrative pictographic drawing on paper and ledger books', e: 'regional_tradition',
    o: 'Great Plains, USA (Fort Marion, Florida; reservation communities)', g: 'United States (Lakota, Cheyenne, Kiowa, Arapaho artists)', p: '1860s-present', era: 'Indian Wars era to present',
    sum: 'Pictographic autobiography drawn in pencil, ink and crayon on ruled ledger paper — horse raids, courting and prison memory, reborn as a contemporary fine art.',
    desc: 'As buffalo-hide painting declined, Plains men moved their flat, profile pictographic style to ruled ledger books, drawing battles, horse raids and name-glyph portraits. The best-known corpus comes from Cheyenne, Kiowa and Arapaho prisoners at Fort Marion, Florida (1875-78) — Howling Wolf, Zotom, Making Medicine — whose drawings sold to Eastern tourists. After the Kiowa Five carried the style into 20th-century easel painting, contemporary artists reclaimed ledger art for galleries and museums.',
    col: [{ h: '#9db9c4', n: 'ledger rule blue' }, { h: '#3c3c40', n: 'graphite' }, { h: '#b8474a', n: 'crayon red' }, { h: '#2b4a70', n: 'prussian crayon blue' }, { h: '#efe7d2', n: 'paper cream' }],
    m: ['ruled ledger paper', 'colored pencil and ink', 'crayon', 'commercial watercolor blocks'],
    tx: ['flat matte crayon fields', 'hairline ruled grids', 'graphite contour'],
    obj: ['ledger books of battle and courtship scenes', 'Fort Marion prisoner albums', 'muslin and hide drawings', 'contemporary gallery ledger paintings'],
    ex: ['Howling Wolf Fort Marion drawings (National Anthropological Archives)', 'Red Horse pictographic account of Little Bighorn (Smithsonian)', 'Kiowa Five portfolio "Kiowa Indian Art" (1929)'],
    inf: ['Winter Count hide chronicles', 'Fort Marion incarceration', 'Kiowa Five easel painting'],
    rel: ['Parfleche Painting', 'Lakota Beadwork', 'Osage Ribbonwork'],
    src: [{ n: 'Wikipedia — Ledger art', u: 'https://en.wikipedia.org/wiki/Ledger_art', t: 'B' }, { n: 'Smithsonian NMAI — ledger art collections', u: 'https://americanindian.si.edu', t: 'A' }],
    tg: ['ledger art', 'pictographic', 'plains', 'fort marion', 'prison drawing', 'narrative'],
    pop: 44, niche: false,
    vd: { shape: 'profile figures walking on single ground lines', line: 'clean contour with flat color fills', composition: 'narrative row scenes across ruled pages', texture: 'crayon tooth over ruled paper' },
    typ: { display: 'name glyphs identify every figure', body: 'n/a', notes: 'drawings read like sequenced annals' },
    lit: { quality: 'flat even daylight', temperature: 'warm', shadow: 'none — outline convention' },
    ui: { background: 'ruled ledger cream', surface: 'pictographic page cards', components: 'glyph-tag buttons', motion: 'page-turn reveals' },
  },
  {
    n: 'Hopi Katsina Doll Carving', a: ['Kachina doll carving', 'Katsina tihu', 'Hopi kachina dolls', 'Tihu'],
    cat: 'Religious & Sacred Art', c: 'Carved cottonwood spirit-figure dolls of the Hopi mesas', e: 'regional_tradition',
    o: 'Northeastern Arizona, USA (First, Second, Third Mesas)', g: 'United States (Hopi villages, Arizona)', p: '1800s-present', era: 'Pueblo ceremonial era to present',
    sum: 'Cottonwood-root tihu figures given to children at katsina ceremonies — from flat early broad-face forms to museum-grade naturalist portraits of spirit beings.',
    desc: 'In Hopi teaching, katsinam are spirit intermediaries who appear in masked ceremony; carved cottonwood-root dolls (tihu) are given to girls as teaching gifts, representing rather than embodying the spirits. Carving evolved from abbreviated flat 19th-century forms to action poses and naturalist portraiture by carvers like Wilson Tawaquaptewa and Otto Pentewa. A gallery art-doll market grew after the 1930s; Hopi artists keep ceremonial gifting and collector carving as distinct practices.',
    col: [{ h: '#e6dcc4', n: 'cottonwood cream' }, { h: '#2e8c86', n: 'turquoise' }, { h: '#f2ede2', n: 'kaolin white' }, { h: '#e3b23c', n: 'corn pollen gold' }, { h: '#26221e', n: 'face-line black' }],
    m: ['cottonwood root', 'mineral and commercial paints', 'wool and feather adornment', 'painted face plates'],
    tx: ['knifed wood facets', 'matte kaolin paint', 'wool fringe and rattle detail'],
    obj: ['broad-face 19th-century tihu', 'action-figure dance carvings', 'cradle katsina dolls', 'gallery sculptural katsinam'],
    ex: ['Wilson Tawaquaptewa carvings (Museum of Northern Arizona)', 'Otto Pentewa action dolls (Heard Museum)', 'broad-face tihu (Smithsonian NMAI)'],
    inf: ['Hopi ceremonial calendar', 'Rio Grande Pueblo doll carving', 'Anglo gallery and tourist markets'],
    rel: ['Pueblo weaving', 'Zuni inlay jewelry', 'Tohono O\'odham Basketry'],
    src: [{ n: 'Wikipedia — Kachina', u: 'https://en.wikipedia.org/wiki/Kachina', t: 'B' }, { n: 'Smithsonian NMAI — katsina doll collections', u: 'https://americanindian.si.edu', t: 'A' }],
    tg: ['katsina', 'kachina', 'cottonwood', 'hopi', 'carved doll', 'pueblo'],
    pop: 46, niche: false,
    vd: { shape: 'upright frontal figures with wide mask plates', line: 'faceted knife-cut edges, painted contours', composition: 'single standing spirit form, attribute-held', texture: 'matte paint on whittled cottonwood' },
    typ: { display: 'no lettering — mask and body paint identify each being', body: 'n/a', notes: 'carved tihu are gifts, not idolatrous effigies' },
    lit: { quality: 'even museum light', temperature: 'warm', shadow: 'soft pedestal shadows' },
    ui: { background: 'mesa-cream ground', surface: 'painted-figure cards', components: 'turquoise accent buttons', motion: 'slow reverent fades' },
  },
  {
    n: 'Tohono O\'odham Basketry', a: ['Papago basketry', 'O\'odham coiled baskets', 'Devilsclaw basketry', 'Friendship baskets'],
    cat: 'Textile & Craft', c: 'Coiled bear-grass and devilsclaw basketry of the Sonoran Desert', e: 'regional_tradition',
    o: 'Sonoran Desert (Arizona, USA and Sonora, Mexico)', g: 'United States and Mexico (Tohono O\'odham Nation; Akimel O\'odham)', p: 'pre-contact-present', era: 'Desert foraging era to present',
    sum: 'Tight-coiled desert baskets of beargrass, yucca and devilsclaw — from plain utility winnows to pictorial friendship baskets and the Man in the Maze motif.',
    desc: 'Tohono O\'odham weavers coil bundles of beargrass sewn with split soaptree yucca, adding devilsclaw for glossy black design lines: tight-packed, watertight work for winnowing, storing and carrying. Trading-post demand of 1900-1930 produced polychrome friendship baskets with pictorial figures, horses and the I\'itoi Man in the Maze emblem. A weavers\' revival from the 1980s through the Tohono O\'odham Basketweavers Organization sustains gathering and teaching today.',
    col: [{ h: '#e8dfc8', n: 'beargrass ivory' }, { h: '#cbb27a', n: 'yucca straw' }, { h: '#26211c', n: 'devilsclaw black' }, { h: '#8a4a2e', n: 'burnt sienna accent' }, { h: '#7a5c3d', n: 'desert brown' }],
    m: ['beargrass leaves', 'soaptree yucca root strands', 'devilsclaw (black design fiber)', 'steel awl'],
    tx: ['glass-tight coil packing', 'glossy devilsclaw inlay', 'arcuated spiral ridges'],
    obj: ['winnowing trays', 'olla-shaped storage baskets', 'pictorial friendship baskets', 'miniature figural horses', 'Man in the Maze baskets'],
    ex: ['Man in the Maze friendship baskets (Arizona State Museum)', '1900-1930 trading-post ollas (Heard Museum)', 'Basketweavers Organization revival show baskets'],
    inf: ['Sonoran Desert plant-gathering economy', 'Trading-post commercial demand', 'Late-20th-century basketry revival'],
    rel: ['Pomo Basketry', 'Pueblo weaving', 'Hopi Katsina Doll Carving'],
    src: [{ n: 'Wikipedia — Tohono O\'odham', u: 'https://en.wikipedia.org/wiki/Tohono_O%27odham', t: 'B' }, { n: 'Smithsonian NMAI — O\'odham basketry', u: 'https://americanindian.si.edu', t: 'A' }],
    tg: ['basketry', 'coiling', 'sonoran desert', 'tohono oodham', 'beargrass', 'devilsclaw'],
    pop: 32, niche: true,
    vd: { shape: 'bellied olla profiles and wide flat trays', line: 'concentric spiral coil courses', composition: 'pictorial figures set in spiral design fields', texture: 'smooth packed straw with lacquered black accents' },
    typ: { display: 'no lettering — pictorial motifs only', body: 'n/a', notes: 'finest friendship baskets made as gifts' },
    lit: { quality: 'bright desert daylight', temperature: 'warm', shadow: 'minimal coil shadow' },
    ui: { background: 'beargrass ivory field', surface: 'spiral coil-textured cards', components: 'oval straw buttons', motion: 'slow spiral transitions' },
  },
  {
    n: 'Taíno Zemi Carving', a: ['Cemí carving', 'Zemi carving', 'Taíno cemís', 'Trigonolito carving', 'Zemis'],
    cat: 'Religious & Sacred Art', c: 'Sacred carved idols of the Taíno Caribbean', e: 'historical',
    o: 'Greater Antilles (Dominican Republic, Puerto Rico, Cuba, Jamaica)', g: 'Taíno chiefdoms of the Greater Antilles and Bahamas', p: 'c. 900-1550 CE', era: 'Pre-colonial Caribbean (Chican Ostionoid)',
    sum: 'Polished stone, wood and cotton zemis — three-pointed cemís, duhos and cohoba stands embodying ancestors and forces, the sacred core of Taíno chiefdom art.',
    desc: 'Zemis (cemís) embody Taíno religion: spirits and deified ancestors carved in green serpentinite, wood, shell and cotton. Three-pointed trigonolito stones relate to the yuca spirit Yúcahu and the mother figure Atabey; chiefs kept wooden ancestor cemís with shell and guanín inlay, with duho seats and cohoba stands. Sacred objects were destroyed under Spanish conquest from the 1490s; survivors are treated today as ancestral patrimony in Caribbean museums and by Taíno descendant communities.',
    col: [{ h: '#4e6b52', n: 'serpentinite green' }, { h: '#23231f', n: 'polished charcoal' }, { h: '#ece3cf', n: 'shell ivory' }, { h: '#a8793c', n: 'guanín gold-bronze' }, { h: '#8c3b2e', n: 'red ochre' }],
    m: ['serpentinite and diorite', 'lignum vitae wood', 'cotton twine wrappings', 'shell and guanín inlay'],
    tx: ['stone-burnished sheen', 'sculptural volume polish', 'fiber-wrapped torso bands'],
    obj: ['three-pointed trigonolitos', 'cohoba ritual stands', 'duho ceremonial seats', 'wooden ancestor cemís', 'bone vomitive spatulae'],
    ex: ['Zemí collection (Museo del Hombre Dominicano, Santo Domingo)', 'Taíno duhos and cemís (El Museo del Barrio, New York)', 'British Museum Taíno holdings'],
    inf: ['Ostionoid and Chican ceramic lineage', 'Amazonian-Orinoco cosmology', 'Cohoba visionary ritual complex'],
    rel: ['Moche Fineline Pottery', 'Maya Codex Style', 'Mexica Featherwork'],
    src: [{ n: 'Wikipedia — Zemi', u: 'https://en.wikipedia.org/wiki/Zemi', t: 'B' }, { n: 'British Museum — Taíno collections', u: 'https://www.britishmuseum.org', t: 'A' }],
    tg: ['taino', 'zemi', 'caribbean', 'pre-columbian', 'sacred carving', 'greater antilles'],
    pop: 38, niche: true,
    vd: { shape: 'compact squat figures and three-pointed masses', line: 'deep eye channels and incised bands', composition: 'frontal hieratic poses, backs inscribed', texture: 'high-burnish stone gloss over carved volume' },
    typ: { display: 'incised cosmological back designs', body: 'n/a', notes: 'objects were inhabited by spirits during ritual' },
    lit: { quality: 'focused temple light', temperature: 'cool', shadow: 'deep carved-channel shadow' },
    ui: { background: 'serpentinite green wash', surface: 'polished stone panels', components: 'three-pointed emblem buttons', motion: 'slow contemplative dissolves' },
  },
  {
    n: 'Amate Bark Paper Painting', a: ['Amate painting', 'Bark paper painting', 'Amate paper art', 'Pintura en amate'],
    cat: 'Material & Surface', c: 'Painted figural amate paper of Guerrero and Puebla, Mexico', e: 'regional_tradition',
    o: 'Guerrero and Puebla, Mexico', g: 'Mexico (San Pablito, Puebla papermaking; Ameyaltepec, Oapan, Xalitla, Guerrero painting)', p: '1960s-present', era: 'Mesoamerican roots; Mexican modern folk revival',
    sum: 'Figure-dense paintings on beaten bark paper — Nahua painters of Guerrero filling brown amate sheets with carnival-bright scenes of village life, myth and protest.',
    desc: 'Amate paper, boiled and mallet-beaten from Ficus bark, carries roots to the pre-Hispanic codices; papermaking survived at San Pablito, Puebla, where Otomí shamans still cut ritual paper figures. In the 1960s Nahua painters of Ameyaltepec, Oapan and Xalitla, Guerrero, began covering the sheets in saturated gouache: village festivals, markets and political critique — dense flat figures. The sheets became Mexico\'s most recognized folk painting and remain a living, family-based trade.',
    col: [{ h: '#c9a678', n: 'amate tan' }, { h: '#b83280', n: 'fiesta magenta' }, { h: '#2e6db4', n: 'sheet blue' }, { h: '#f2b135', n: 'marigold yellow' }, { h: '#26211c', n: 'ink black' }],
    m: ['Ficus (jonote) bark', 'lime-ash boiling water', 'wooden beating mallets', 'gouache and acrylic paints'],
    tx: ['lumpy beaten-bark nap', 'flat gouache fields', 'dense pigment saturation'],
    obj: ['village-festival panels', 'agave-field scenes', 'Otomí ritual muñeco figures', 'political protest sheets', 'market-stand panels'],
    ex: ['Ameyaltepec and Oapan painted sheets (Museo Nacional de Antropología, Mexico)', 'San Pablito Otomí ritual paper figures', '1970s Guerrero amate panels (Museum of International Folk Art)'],
    inf: ['Pre-Hispanic codex painting', 'Otomí ritual paper use', 'Mexican folk-art tourist markets'],
    rel: ['Otomi Tenango Embroidery', 'Ofrenda de Día de Muertos', 'Maya Codex Style'],
    src: [{ n: 'Wikipedia — Amate', u: 'https://en.wikipedia.org/wiki/Amate', t: 'B' }, { n: 'British Museum — amate paper collections', u: 'https://www.britishmuseum.org', t: 'A' }],
    tg: ['amate', 'bark paper', 'mexican folk art', 'guerrero', 'nahua', 'gouache'],
    pop: 41, niche: false,
    vd: { shape: 'stacked rounded figures and patterned hills', line: 'bold black outline enclosing flat color', composition: 'edge-to-edge narrative with zero empty ground', texture: 'raw fibrous paper under matte paint' },
    typ: { display: 'hand-painted titles and village names', body: 'n/a', notes: 'protest sheets carry slogan text' },
    lit: { quality: 'bright even daylight', temperature: 'warm', shadow: 'none — flat folk depth' },
    ui: { background: 'amate tan field', surface: 'figural crowd-pattern cards', components: 'outlined folk buttons', motion: 'festival-bright pops' },
  },
  {
    n: 'Lapita Pottery', a: ['Lapita ware', 'Dentate-stamped pottery', 'Lapita ceramic tradition'],
    cat: 'Material & Surface', c: 'Dentate-stamped Oceanic ceramic complex', e: 'historical',
    o: 'Bismarck Archipelago to Fiji, Samoa and New Caledonia', g: 'Remote Oceania (Bismarcks, Solomons, Vanuatu, New Caledonia, Fiji, Tonga, Samoa)', p: 'c. 1600-500 BCE', era: 'Lapita cultural complex (first Remote Oceania settlement)',
    sum: 'Dentate-stamped red-slipped pottery of the first Pacific island settlers — repeated geometric faces and meanders combed with toothed stamps, ancestor of Polynesian design.',
    desc: 'Lapita names the Austronesian voyaging complex that settled Remote Oceania c. 1600-500 BCE, recognized by thin red-slipped earthenware with zoned friezes: repeated hatching, meanders and stylized faces pressed with toothed (dentate) combs before low open firing. Found from the Bismarck Archipelago to Samoa — Talepakemalai (Mussau), Teouma cemetery (Vanuatu) — the motifs anticipate later Polynesian patterning. Ceramics died out in Polynesia by about 500 BCE; Lapita survives in excavated sherds.',
    col: [{ h: '#a8502f', n: 'red slip ochre' }, { h: '#e3d3b4', n: 'fired cream' }, { h: '#2b241e', n: 'stamped black' }, { h: '#8b8579', n: 'fire-cloud gray' }, { h: '#c9743f', n: 'burnt orange' }],
    m: ['fine river-clay earthenware', 'red slip', 'carved dentate combs', 'open firing'],
    tx: ['toothed stamped drag marks', 'burnished slip sheen', 'repeated frieze registers'],
    obj: ['carinated dishes', 'shouldered water jars', 'flat-based bowls', 'jar burial vessels'],
    ex: ['Lapita type-site sherds (New Caledonia, excavated 1909)', 'Talepakemalai stamped vessels (Mussau, Papua New Guinea)', 'Teouma cemetery jar burials (Vanuatu)'],
    inf: ['Austronesian voyaging settlement', 'Ancestral Polynesian society', 'Melanesian pot-decoration lineages'],
    rel: ['Samoan siapo', 'Hawaiian kapa', 'Tongan ngatu'],
    src: [{ n: 'Wikipedia — Lapita culture', u: 'https://en.wikipedia.org/wiki/Lapita_culture', t: 'B' }, { n: 'British Museum — Lapita collections', u: 'https://www.britishmuseum.org', t: 'A' }],
    tg: ['lapita', 'dentate stamping', 'pottery', 'oceania', 'austronesian', 'archaeology'],
    pop: 37, niche: true,
    vd: { shape: 'carinated vessel profiles with angled shoulders', line: 'frieze bands of stamped repetition', composition: 'zoned registers from rim to base', texture: 'burnished slip toothed with comb drag' },
    typ: { display: 'no lettering — stamped motif grammar', body: 'n/a', notes: 'designs read as ancestral pattern language' },
    lit: { quality: 'raking archaeological light', temperature: 'warm', shadow: 'stamped groove micro-shadows' },
    ui: { background: 'red-slip ochre ground', surface: 'stamped frieze cards', components: 'toothed-band dividers', motion: 'pattern-register repeats' },
  },
  {
    n: 'Rapa Nui Moai Carving', a: ['Moai carving', 'Easter Island moai', 'Moai statues', 'Ahu moai'],
    cat: 'Material & Surface', c: 'Monolithic ancestor figures of Rapa Nui', e: 'historical',
    o: 'Rapa Nui (Easter Island), Chile', g: 'Rapa Nui (Easter Island), Chile (Polynesia)', p: 'c. 1250-1500 CE', era: 'Pre-contact Rapa Nui',
    sum: 'Nearly 900 monolithic ancestor statues — moai — quarried whole from Rano Raraku tuff and raised on ahu platforms, gazing inland over clan lands.',
    desc: 'From 1250-1500 CE, Rapa Nui carvers detached nearly 900 moai — averaging four meters and thirteen tonnes — from the Rano Raraku tuff quarry with basalt toki adzes, and stood them on ahu platforms facing inland villages. Red scoria pukao topknots crowned some; coral-and-obsidian eyes, surviving on Ahu Ko Te Riku, activated ancestral mana. Inter-clan warfare toppled most before European contact; re-erections restored the rows, and the British Museum\'s Hoa Hakananai\'a anchors global fame.',
    col: [{ h: '#7d8272', n: 'Raraku gray-green' }, { h: '#a5502f', n: 'red scoria' }, { h: '#eee8da', n: 'coral eye white' }, { h: '#1c1b19', n: 'obsidian black' }, { h: '#b0a05a', n: 'lichen gold' }],
    m: ['Rano Raraku tuff', 'red scoria (pukao)', 'basalt toki adzes', 'coral and obsidian eyes'],
    tx: ['tool-marked stone faces', 'wind-smoothed tuff', 'porous scoria crust'],
    obj: ['ahu-platform moai rows', 'pukao topknot cylinders', 'quarry figures left in situ', 'wooden moai kavakava figures'],
    ex: ['Hoa Hakananai\'a (British Museum, London)', 'Ahu Tongariki fifteen-moai row (re-erected 1990s)', 'Rano Raraku quarry figures (Rapa Nui National Park)'],
    inf: ['Polynesian ancestor veneration', 'Rapa Nui rongorongo tablet culture', 'Ahu platform engineering'],
    rel: ['Rongorongo', 'Lapita Pottery', 'Pounamu Greenstone Carving'],
    src: [{ n: 'Wikipedia — Moai', u: 'https://en.wikipedia.org/wiki/Moai', t: 'B' }, { n: 'British Museum — Hoa Hakananai\'a', u: 'https://www.britishmuseum.org', t: 'A' }],
    tg: ['moai', 'rapa nui', 'monolith', 'polynesia', 'ancestor figure', 'stone carving'],
    pop: 63, niche: false,
    vd: { shape: 'heavy-browed elongated heads on trapezoid bodies', line: 'brow ridge over inset eye sockets', composition: 'aligned rows on platforms, backs to sea', texture: 'weathered tuff with adze scoring' },
    typ: { display: 'no lettering — sculptural presence only', body: 'n/a', notes: 'eyes restored only on one ahu figure' },
    lit: { quality: 'high-contrast ocean light', temperature: 'warm', shadow: 'deep brow and jaw shadows' },
    ui: { background: 'tuff gray-green gradient', surface: 'monolith-textured panels', components: 'scoria-red accent buttons', motion: 'monumental slow pans' },
  },
  {
    n: 'Pounamu Greenstone Carving', a: ['Greenstone carving', 'Pounamu carving', 'Māori jade carving', 'Nephrite jade work'],
    cat: 'Material & Surface', c: 'Māori nephrite jade ornament and tool carving', e: 'regional_tradition',
    o: 'Te Waipounamu (South Island), Aotearoa New Zealand', g: 'New Zealand (West Coast, Otago; Māori iwi)', p: 'c. 1300-present', era: 'Māori settlement era to present',
    sum: 'Nephrite jade (pounamu) of the South Island rivers — hei-tiki pendants, mere clubs and hei matau hooks, taonga treasures passed down through generations.',
    desc: 'Pounamu — nephrite jade and bowenite from West Coast rivers like the Arahura — was prized by Māori above all other stone. Workers ground it with sandstone and quartz abrasives into hei-tiki pendants, mere pounamu clubs, hei matau hooks, toki adzes and kuru ear ornaments. As taonga, pieces inherited mana across lineages and were traded throughout Aotearoa. Gathering now follows Ngāi Tahu\'s 1997 pounamu regulations, and contemporary carvers continue the grind-and-polish lineage.',
    col: [{ h: '#1e5b45', n: 'kahurangi deep green' }, { h: '#cfd8cc', n: 'inanga pale' }, { h: '#2f7a4f', n: 'kawakawa green' }, { h: '#5c8f8a', n: 'tangiwai blue-green' }, { h: '#a3b18a', n: 'flower jade' }],
    m: ['nephrite pounamu (kahurangi, kawakawa, inanga)', 'bowenite tangiwai', 'quartz sand abrasives', 'diamond lapidary tools (modern)'],
    tx: ['oily stone gloss', 'bone-ground matte polish', 'translucent tangiwai glow'],
    obj: ['hei-tiki pendants', 'mere pounamu hand clubs', 'hei matau fish-hook pendants', 'toki adze blades', 'kuru ear ornaments'],
    ex: ['Hei-tiki (Museum of New Zealand Te Papa Tongarewa)', 'Chiefly mere pounamu (Auckland War Memorial Museum)', 'Arahura River pounamu gathering (Ngāi Tahu governance)'],
    inf: ['Māori whakapapa and taonga custodianship', 'East Polynesian adze technology', 'Early pākehā jade markets'],
    rel: ['Whakairo carving', 'Māori Ta Moko', 'Tukutuku Panels'],
    src: [{ n: 'Wikipedia — Pounamu', u: 'https://en.wikipedia.org/wiki/Pounamu', t: 'B' }, { n: 'Te Papa Tongarewa — pounamu', u: 'https://www.tepapa.govt.nz', t: 'A' }],
    tg: ['pounamu', 'greenstone', 'jade', 'maori', 'taonga', 'pendant'],
    pop: 42, niche: false,
    vd: { shape: 'simplified abstract figures with bulbous heads', line: 'soft ground contours, no hard edges', composition: 'single pendant form centered on cordage', texture: 'oily translucent jade depth' },
    typ: { display: 'no lettering — form and whakapapa carry meaning', body: 'n/a', notes: 'pieces accrue mana through inheritance' },
    lit: { quality: 'transmissive backlight glow', temperature: 'cool', shadow: 'internal stone depth shadows' },
    ui: { background: 'kahurangi green wash', surface: 'polished jade-sheen cards', components: 'corded pendant buttons', motion: 'slow luminous pulses' },
  },
  {
    n: 'Rongorongo', a: ['Rongo-rongo script', 'Rapa Nui rongorongo', 'Kohau rongorongo'],
    cat: 'Material & Surface', c: 'Undeciphered glyphic wood carving of Rapa Nui', e: 'historical',
    o: 'Rapa Nui (Easter Island), Chile', g: 'Rapa Nui (Easter Island), Chile', p: 'attested 1770s-1860s', era: 'Pre-contact to post-contact Rapa Nui',
    sum: 'Undeciphered pictographic glyphs incised in alternating rows on wooden tablets — human, bird and plant signs forming one of the Pacific\'s great unsolved scripts.',
    desc: 'Rongorongo is a system of some 600 distinct glyphs incised in reverse-boustrophedon rows — read bottom to top, rotating it per line — on wooden tablets and staffs such as the Mamari, Tahua and Santiago Staff. Nearly all surviving objects are 19th-century wood; reading knowledge collapsed after the 1860s slave raids and missionary suppression. Structural study — a genealogy on the Santiago Staff, the Mamari lunar calendar — has yielded partial readings, but the script remains undeciphered.',
    col: [{ h: '#5c4632', n: 'tablet umber' }, { h: '#26221e', n: 'incised charcoal' }, { h: '#c9b490', n: 'driftwood pale' }, { h: '#3f342a', n: 'oil patina' }, { h: '#a08a64', n: 'aged tan' }],
    m: ['Pacific hardwood and driftwood', 'obsidian flake engravers', 'charcoal rubbing pigment', 'shark oil finish'],
    tx: ['knife-scored glyph channels', 'dark rubbed patina', 'parallel row registers'],
    obj: ['Tahua and Mamari tablets', 'Santiago Staff', 'inscribed gourd vessel', 'rei miro crescent pectoral'],
    ex: ['Santiago Staff (Museo Nacional de Historia Natural, Chile)', 'Tahua tablet (Rome)', 'Rei Miro pectoral (Brussels)'],
    inf: ['Polynesian sign systems', 'Rapa Nui elite scribal houses', '1860s missionary printing primers'],
    rel: ['Rapa Nui Moai Carving', 'Lapita Pottery', 'Maya Codex Style'],
    src: [{ n: 'Wikipedia — Rongorongo', u: 'https://en.wikipedia.org/wiki/Rongorongo', t: 'B' }, { n: 'British Museum — Easter Island collections', u: 'https://www.britishmuseum.org', t: 'A' }],
    tg: ['rongorongo', 'undeciphered', 'glyphs', 'rapa nui', 'tablet', 'script'],
    pop: 39, niche: true,
    vd: { shape: 'crouching human, bird and plant glyph figures', line: 'shallow V-cut incisions in rows', composition: 'boustrophedon registers filling both faces', texture: 'oil-dark wood with crisp scored channels' },
    typ: { display: 'the glyphs themselves are the writing', body: 'n/a', notes: 'read bottom-left upward, tablet rotated per line' },
    lit: { quality: 'low raking light across incisions', temperature: 'warm', shadow: 'glyph-channel shadow lines' },
    ui: { background: 'tablet umber field', surface: 'incised glyph-row cards', components: 'glyph-etched buttons', motion: 'line-by-line trace reveals' },
  },
]
