/**
 * Ceramics wave (Task 1-a2) — 16 hand-verified ceramic & porcelain traditions.
 * All names are real, documented traditions; sources are stable institutional URLs.
 * Substitutes (Raku, Iznik, Mata Ortiz, Hispano-Moresque were already listed in existing-names.txt):
 * Shino Ware, Creamware, Salt-glazed Stoneware, Van Briggle Pottery.
 */
export const ENTRIES: any[] = [
  {
    n: 'Iga Ware', a: ['Iga-yaki', '伊賀焼', 'Iga stoneware'],
    cat: 'Regional & Cultural Tradition', c: 'Japanese wood-fired tea-ceremony stoneware from Iga', e: 'regional_tradition',
    o: 'Iga, Mie, Japan', g: 'Japan (Mie prefecture; Marubashira kilns near the Shigaraki border)', p: '16th century-present', era: 'Momoyama-Edo Japan to present',
    sum: 'Rugged wood-fired stoneware from Iga, Mie — coarse lakebed clay with feldspar bursts, molten fire color and glassy ash runs, beloved for irregular tea-ceremony water jars and flower vases.',
    desc: 'Iga ware (伊賀焼) comes from mountain kilns in Mie prefecture using coarse lakebed clay. Fired hard in long wood firings, its walls blister with feldspar bursts (ishi-hada, "stone skin") while pine ash fuses into glassy olive runs and flame scorches the surface to molten orange. Momoyama tea masters prized such distortions in mizusashi water jars and hanaire vases. Output faded in the Edo period, revived in the twentieth century, and Iga kilns still work beside Shigaraki.',
    col: [{ h: '#b05a2a', n: 'molten flame orange' }, { h: '#6f8f5e', n: 'ash-run olive' }, { h: '#e8e3d4', n: 'feldspar stone-skin white' }, { h: '#4a3527', n: 'charred brown' }, { h: '#8c8477', n: 'smoke gray' }],
    m: ['coarse lakebed stoneware clay', 'red pine firewood', 'anagama climbing kiln', 'natural feldspar inclusions'],
    tx: ['blistered feldspar pops', 'glassy ash drips', 'flame-scorched gradation'],
    obj: ['mizusashi water jars', 'hanaire flower vases', 'chawan tea bowls', 'tokkuri sake flasks', 'tsubo storage jars'],
    ex: ['Momoyama Iga mizusashi in major tea collections', 'Iga flower vases shaped to Furuta Oribe\'s taste', 'Marubashira revival works of the Onishi kiln lineage'],
    inf: ['Shigaraki kiln culture', 'Chanoyu tea aesthetics', 'Sue-ware stoneware'],
    rel: ['Shigaraki Ware', 'Bizen Ware', 'Wabi-sabi'],
    src: [{ n: 'Wikipedia — Iga ware', u: 'https://en.wikipedia.org/wiki/Iga_ware', t: 'B' }, { n: 'The Metropolitan Museum of Art — Japanese ceramics', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['stoneware', 'tea ceremony', 'wood-fired', 'feldspar', 'anagama', 'iga'],
    pop: 38, niche: true,
    vd: { shape: 'collapsed, distorted jar shoulders and tall flower vases', line: 'slack coil undulations left unfixed', composition: 'fire paints the focal interest — accidental bursts centered', texture: 'stone-skin blister over molten flame color' },
    typ: { display: 'n/a — applied object art', body: 'n/a', notes: 'no lettering tradition beyond potter marks' },
    lit: { quality: 'raking light across rough kiln surface', temperature: 'warm', shadow: 'deep pockets in blistered clay' },
    ui: { background: 'molten orange paper grain', surface: 'ash-run textured cards', components: 'olive-green rounded buttons', motion: 'slow ember-glow transitions' },
  },
  {
    n: 'Karatsu Ware', a: ['Karatsu-yaki', '唐津焼', 'Ko-Karatsu', 'Karatsu stoneware'],
    cat: 'Regional & Cultural Tradition', c: 'Korean-derived stoneware tradition of the Hizen kilns', e: 'regional_tradition',
    o: 'Karatsu, Saga, Japan', g: 'Japan (Saga and Nagasaki prefectures; former Hizen province)', p: 'late 16th century-present', era: 'Momoyama-Edo Japan to present',
    sum: 'Practical Korean-derived stoneware of Kyushu — earthy ash glazes, brushed iron painting and spotted madara ware whose quiet utility made "first Karatsu" the tea men\'s byword.',
    desc: 'Karatsu ware arose in Hizen (modern Saga and Nagasaki prefectures) after Korean potters brought the wheel, climbing kilns and ash glazes to Japan in the late sixteenth century. Old Ko-Karatsu types — e-karatsu with brushed iron painting, spotted madara glaze, kuro black and chōsen buff — made sturdy jars, plates and tea bowls ranked first by tea men ("first Karatsu, second Raku"). Domain kilns later supplied tableware across Kyushu; the workshops revived after decline and remain active today.',
    col: [{ h: '#8a6f4d', n: 'chōsen warm buff' }, { h: '#3d3a36', n: 'e-karatsu iron black' }, { h: '#5f7257', n: 'madara ash green' }, { h: '#a99c86', n: 'uncovered clay tan' }, { h: '#26221e', n: 'kiln-char black' }],
    m: ['iron-bearing Hizen stoneware clay', 'rice-straw ash glaze', 'iron-oxide brush pigment', 'wood-fired climbing kilns'],
    tx: ['soft ash pooling', 'iron-brown brush drag', 'paddled wheel rings'],
    obj: ['chawan tea bowls', 'tokkuri sake flasks', 'tsubo kitchen jars', 'dinner plates', 'flanged water jars'],
    ex: ['Momoyama Ko-Karatsu e-karatsu tea bowls', 'Karatsu wares recorded in Hizen domain kiln rosters', 'Nakazato Taroemon kiln lineage pieces'],
    inf: ['Joseon Korean kiln technology', 'Chanoyu tea aesthetics', 'Korean punch\'ong slip traditions'],
    rel: ['Hagi Ware', 'Shino Ware', 'Wabi-sabi'],
    src: [{ n: 'Wikipedia — Karatsu ware', u: 'https://en.wikipedia.org/wiki/Karatsu_ware', t: 'B' }, { n: 'Victoria & Albert Museum — Japanese stoneware', u: 'https://www.vam.ac.uk', t: 'A' }],
    tg: ['stoneware', 'korean influence', 'tea ceremony', 'ash glaze', 'kyushu', 'everyday ware'],
    pop: 41, niche: false,
    vd: { shape: 'full-shouldered bowls and jars of honest weight', line: 'loose brushed iron contours under glaze', composition: 'one motif per face, generous bare clay', texture: 'velvety ash over warm buff body' },
    typ: { display: 'n/a — applied object art', body: 'n/a', notes: 'kiln marks only; no surface lettering' },
    lit: { quality: 'soft daylight on matte glaze', temperature: 'warm', shadow: 'gentle pooling in glaze runs' },
    ui: { background: 'warm buff clay field', surface: 'ash-glazed matte cards', components: 'iron-painted outline buttons', motion: 'slow brush-in reveals' },
  },
  {
    n: 'Hagi Ware', a: ['Hagi-yaki', '萩焼', 'Hagi pottery'],
    cat: 'Regional & Cultural Tradition', c: 'Japanese tea stoneware of the Mōri domain kilns', e: 'regional_tradition',
    o: 'Hagi, Yamaguchi, Japan', g: 'Japan (Yamaguchi prefecture; Matsumoto and Sakakura kiln districts)', p: '1604-present', era: 'Edo period to present',
    sum: 'Pale pink-beige tea stoneware from Hagi, Yamaguchi — crackling loquat-toned glaze over soft clay that deepens with decades of use: the celebrated "seven changes of Hagi."',
    desc: 'Hagi ware was founded around 1604 when Korean potters brought their craft to the Mōri clan\'s castle town of Hagi in western Honshu. Its tea bowls use pale, iron-poor clay under a thin feldspathic glaze whose fine crackle stains amber through years of use — the nanakake, "seven changes of Hagi." Because body and glaze breathe, devotees treasure how each bowl ages. Domain kilns served tea and gift culture through the Edo period; workshops continued after Meiji and remain living traditions today.',
    col: [{ h: '#e3c9a8', n: 'loquat glaze cream' }, { h: '#d69f7a', n: 'tea-stained amber' }, { h: '#f0e6d2', n: 'chalky pink-white body' }, { h: '#a8806a', n: 'crackle rust line' }, { h: '#6b5847', n: 'foot-ring raw clay' }],
    m: ['pale iron-poor Hagi clay', 'Daido and Mitachi clay blends', 'thin feldspathic glaze', 'wood-fired noborigama kilns'],
    tx: ['fine crackle network', 'chalk-soft unglazed foot', 'tea-juice patina'],
    obj: ['chawan tea bowls', 'mizusashi water jars', 'hanaire flower vases', 'kōgō incense containers', 'sake vessels'],
    ex: ['Edo Hagi chawan of the Miwa lineage', 'Hagi water jars from Mōri family collections', 'Miwa Kyusetsu white-Hagi tea bowls'],
    inf: ['Joseon buncheong and white wares', 'Chanoyu tea aesthetics', 'Mōri domain patronage'],
    rel: ['Karatsu Ware', 'Wabi-sabi', 'Mingei'],
    src: [{ n: 'Wikipedia — Hagi ware', u: 'https://en.wikipedia.org/wiki/Hagi_ware', t: 'B' }, { n: 'The Metropolitan Museum of Art — Japanese tea ceramics', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['stoneware', 'tea bowl', 'crackle glaze', 'patina', 'yamaguchi', 'tea ceremony'],
    pop: 44, niche: false,
    vd: { shape: 'low wide tea bowls with quiet distorted rims', line: 'soft potter\'s-finger facets, no hard edges', composition: 'plain surface — time supplies the pattern', texture: 'crackling cream glaze warming with use' },
    typ: { display: 'n/a — applied object art', body: 'n/a', notes: 'potters\' seals on unglazed foot only' },
    lit: { quality: 'diffuse warm light', temperature: 'warm', shadow: 'soft, pooling at glaze pools' },
    ui: { background: 'loquat cream gradient', surface: 'crackle-textured cards', components: 'clay-toned rounded buttons', motion: 'slow patina-deepening fades' },
  },
  {
    n: 'Oribe Ware', a: ['Oribe-yaki', '織部焼', 'Oribe glaze', 'ao-Oribe'],
    cat: 'Material & Surface', c: 'Japanese copper-green glaze and bold-pattern design school', e: 'historical',
    o: 'Mino, Gifu, Japan', g: 'Japan (Mino kilns, Gifu; Kyoto-linked design circles)', p: 'c. 1600-1640s', era: 'Early Edo Japan',
    sum: 'Early Edo design school of the Mino kilns — copper-green Oribe glaze with white slip and brushed iron patterns on jaunty, deliberately distorted tea vessels, shaped by Furuta Oribe\'s taste.',
    desc: 'Oribe ware is the flamboyant branch of the Mino kilns named for tea master and design arbiter Furuta Oribe. Around 1600-1640 workshops made copper-green ao-Oribe with grid-panel painting, black-and-white kuro-Oribe with inlaid geometry, and slip-trailed, deliberately warped dishes that broke with restrained tea taste. Its asymmetry and bold vernacular geometry fed early Edo pattern books. Output lapsed by the mid-seventeenth century, though potters in Mino and Kyoto now revive Oribe glazes.',
    col: [{ h: '#4e7d4e', n: 'copper-green oribe' }, { h: '#1e1e1e', n: 'kuro-Oribe black' }, { h: '#efe9da', n: 'slip white' }, { h: '#8a4b2f', n: 'iron-brown paint' }, { h: '#c9a227', n: 'amber glaze edge' }],
    m: ['Mino stoneware clay', 'copper-oxide green glaze', 'white slip', 'iron-oxide brush pigment'],
    tx: ['glassy green pooling', 'inlaid slip crispness', 'brushed iron snap'],
    obj: ['warped serving dishes', 'grid-paneled tea bowls', 'slip-trailed plates', 'kuro-Oribe incense containers', 'tokkuri flasks'],
    ex: ['Ao-Oribe dishes with grid and fern designs', 'Kuro-Oribe inlaid tea bowls', 'Oribe dishes in early Edo export records'],
    inf: ['Furuta Oribe tea taste', 'Mino kiln slipware', 'early Edo pattern books'],
    rel: ['Shino Ware', 'Seto Ware', 'Iga Ware'],
    src: [{ n: 'Wikipedia — Oribe ware', u: 'https://en.wikipedia.org/wiki/Oribe_ware', t: 'B' }, { n: 'The Metropolitan Museum of Art — Mino ware', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['copper green', 'mino', 'tea taste', 'asymmetry', 'slipware', 'edo period'],
    pop: 42, niche: false,
    vd: { shape: 'leaning bowls and tipsy, trapezoidal dishes', line: 'thick black contour and painted grids', composition: 'deliberate lopsidedness; pattern on half the form', texture: 'glassy green over chalky slip' },
    typ: { display: 'n/a — applied object art', body: 'n/a', notes: 'no lettering; occasionally brush-marked counts' },
    lit: { quality: 'crisp directional light on gloss', temperature: 'cool', shadow: 'hard green reflections' },
    ui: { background: 'copper-green field', surface: 'grid-panel pattern cards', components: 'black-outline angular buttons', motion: 'playful tilted slide reveals' },
  },
  {
    n: 'Seto Ware', a: ['Seto-yaki', '瀬戸焼', 'Setomono', 'Seto mono'],
    cat: 'Regional & Cultural Tradition', c: 'Japan\'s most storied glazed-ceramic kiln city', e: 'regional_tradition',
    o: 'Seto, Aichi, Japan', g: 'Japan (Aichi prefecture; head of the six ancient kilns)', p: 'Kamakura period-present', era: 'Kamakura period to present',
    sum: 'Ceramics of Seto, Aichi — historically Japan\'s dominant source of glazed stoneware, so central that "setomono" became the generic Japanese word for ceramics.',
    desc: 'Seto ware leads Japan\'s "six ancient kilns." From the Kamakura period its workshops, credited to potter Kagemasa\'s study of Chinese glazes, supplied much of the country\'s glazed stoneware — iron-brown Koseto tea vessels, celadon-toned and ash-glazed jars. Edo-period Akazu kilns added overglaze enamels, and the nineteenth century brought blue-and-white sometsuke porcelain; by Meiji it was a mass-production city. "Setomono" long meant ceramics generally, and Akazu keeps them alive.',
    col: [{ h: '#7a5c3a', n: 'koseto iron brown' }, { h: '#9db294', n: 'ash-glaze celadon' }, { h: '#2b4c7e', n: 'sometsuke blue' }, { h: '#ece5d6', n: 'porcelain white' }, { h: '#57493a', n: 'clay brown' }],
    m: ['iron-rich Seto stoneware clay', 'natural ash glazes', 'iron and copper oxides', 'overglaze enamels (Akazu)'],
    tx: ['runny ash pooling', 'enamel sheen', 'wheel-turned ridges'],
    obj: ['chatsubo tea-leaf jars', 'Koseto tea bowls', 'Akazu overglaze plates', 'sometsuke dinnerware', 'suribachi mortars'],
    ex: ['Kamakura-Muromachi Koseto tea jars', 'Akazu kiln overglaze wares', 'Meiji sometsuke porcelain from Seto'],
    inf: ['Chinese Song glazed ceramics', 'Sue-ware stoneware', 'Kamakura tea culture'],
    rel: ['Shino Ware', 'Oribe Ware', 'Kutani Ware'],
    src: [{ n: 'Wikipedia — Seto ware', u: 'https://en.wikipedia.org/wiki/Seto_ware', t: 'B' }, { n: 'Victoria & Albert Museum — Japanese kilns', u: 'https://www.vam.ac.uk', t: 'A' }],
    tg: ['six ancient kilns', 'glazed stoneware', 'setomono', 'porcelain', 'akazu', 'mass production'],
    pop: 46, niche: false,
    vd: { shape: 'shouldered jars and practical table forms across eras', line: 'steady wheel rings, sober profiles', composition: 'restrained decoration; glaze as the event', texture: 'glassy ash and enamel over honest clay' },
    typ: { display: 'maker and kiln marks, Akazu shop stamps', body: 'n/a', notes: 'industrial backstamps on Meiji export wares' },
    lit: { quality: 'even gallery light', temperature: 'neutral', shadow: 'clean, minimal' },
    ui: { background: 'porcelain white field', surface: 'glaze-swatch cards', components: 'celadon-toned buttons', motion: 'steady, unhurried crossfades' },
  },
  {
    n: 'Shino Ware', a: ['Shino-yaki', '志野焼', 'Shino glaze'],
    cat: 'Material & Surface', c: 'Japanese white feldspathic-glaze stoneware of the Mino kilns', e: 'historical',
    o: 'Mino, Gifu, Japan', g: 'Japan (Mino kilns, Gifu prefecture)', p: 'c. 1570s-1640s; 20th-century revival', era: 'Momoyama-early Edo Japan',
    sum: 'Momoyama tea stoneware wearing thick milky feldspar glaze blushed red by fire — Japan\'s first white-glazed vessels, prized for soft iron painting under snow-like, crawling surfaces.',
    desc: 'Shino ware emerged at the Mino kilns around the 1570s as Japan\'s first white-glazed ceramic: a thick, slow-cooled feldspar glaze over iron-painted brushwork, fired so that pinholes, crawls and fire-red blushing (hi-shino) remain in the skin. Gray nezumi-shino, red-ground aka-shino and plain muji types made tea bowls, plates and water jars central to tea taste for rustic imperfection. Classical output faded early in the Edo period; Arakawa Toyozō reconstructed the firing in the twentieth century.',
    col: [{ h: '#f2ead8', n: 'shino milk white' }, { h: '#c96f4a', n: 'hi-shino fire blush' }, { h: '#a08768', n: 'nezumi gray-red' }, { h: '#6e4a32', n: 'iron-paint brown' }, { h: '#42352a', n: 'crawled clay shadow' }],
    m: ['Mino stoneware clay', 'coarse feldspar glaze slurry', 'iron-oxide pigment', 'wood-fired climbing kilns'],
    tx: ['crawled milky pinholes', 'iron brush bleeding', 'fire blush gradation'],
    obj: ['chawan tea bowls', 'aka-shino plates', 'mizusashi water jars', 'kōgō incense boxes', 'pine-motif dishes'],
    ex: ['Momoyama nezumi-shino tea bowls', 'Aka-shino plates with pine and fish designs', 'Arakawa Toyozō\'s reconstructed shino works'],
    inf: ['Seto kiln migrations', 'Chanoyu tea aesthetics', 'Furuta Oribe design taste'],
    rel: ['Oribe Ware', 'Seto Ware', 'Wabi-sabi'],
    src: [{ n: 'Wikipedia — Shino ware', u: 'https://en.wikipedia.org/wiki/Shino_ware', t: 'B' }, { n: 'The Metropolitan Museum of Art — Shino ware', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['feldspar glaze', 'white ware', 'mino', 'tea ceremony', 'iron painting', 'revival'],
    pop: 45, niche: false,
    vd: { shape: 'rounded tea bowls with soft, pinched presence', line: 'loose botanical iron strokes under milk', composition: 'single motif floating on whiteness', texture: 'crawled glaze skin over warm clay' },
    typ: { display: 'n/a — applied object art', body: 'n/a', notes: 'no lettering tradition beyond marks' },
    lit: { quality: 'warm even light, no hot spots', temperature: 'warm', shadow: 'blush shadows within glaze crawl' },
    ui: { background: 'milk-white field', surface: 'crawled-glaze texture cards', components: 'rust-accent rounded buttons', motion: 'slow snowfall-like fades' },
  },
  {
    n: 'Onggi', a: ['Onggi ware', '옹기', 'jangdok jars', 'Korean earthenware jars'],
    cat: 'Regional & Cultural Tradition', c: 'Korean earthenware jar tradition for ferment and storage', e: 'regional_tradition',
    o: 'Korea', g: 'Korea (whole peninsula; kiln towns across Gyeonggi, Jeolla, Gyeongsang)', p: 'Three Kingdoms period-present', era: 'Joseon Korea to present',
    sum: 'Korea\'s breathing brown-glazed earthenware — paddle-built fermentation and storage jars whose microporous walls season kimchi, soy sauce and pastes, a living folk craft of the jar terrace.',
    desc: 'Onggi are Korea\'s everyday earthenware: brown iron-glazed, coil- and paddle-built jars fired across the peninsula for fermenting kimchi, pastes and grain. Their walls stay slightly porous, letting vessels "breathe" — essential to Korean fermentation, kept on raised jangdokdae terraces by the kitchen. Makers shape onggi by quick paddle-and-anvil (ttakji) work rather than slow wheel turning. Village kilns declined with industrialization, but designated masters keep the craft alive.',
    col: [{ h: '#6b3f28', n: 'onggi brown glaze' }, { h: '#8a5a38', n: 'amber jar tone' }, { h: '#3f2a1c', n: 'dark-glaze shadow' }, { h: '#b59a76', n: 'unglazed rim tan' }, { h: '#57633f', n: 'moss-garden green' }],
    m: ['iron-rich earthenware clay', 'ferrous brown glaze slurry', 'wood-fired hill kilns', 'wooden paddles and anvils'],
    tx: ['paddle-faceted walls', 'glassy brown glaze streaks', 'porous breathing surface'],
    obj: ['jangdok fermentation jars', 'hangari water jars', 'grain jars', 'kimchi crocks', 'steamer pots'],
    ex: ['Joseon jangdok jar sets on jangdokdae terraces', 'village-kiln hangari water and grain jars', 'contemporary master onggi for fermentation restaurants'],
    inf: ['Silla earthenware traditions', 'Goryeo workshop methods', 'Korean fermentation cuisine'],
    rel: ['Buncheong Ware', 'Celadon', 'Mingei'],
    src: [{ n: 'Wikipedia — Onggi', u: 'https://en.wikipedia.org/wiki/Onggi', t: 'B' }, { n: 'The Metropolitan Museum of Art — Korean art', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['earthenware', 'fermentation', 'kimchi', 'jangdok', 'brown glaze', 'living craft'],
    pop: 36, niche: true,
    vd: { shape: 'full-bellied lidded jars in graded sizes', line: 'broad paddle facets, quick and rhythmic', composition: 'rows of jars composed on terrace steps', texture: 'wet-look brown glaze over breathing clay' },
    typ: { display: 'n/a — applied object art', body: 'n/a', notes: 'no lettering; occasional shop stamps' },
    lit: { quality: 'outdoor daylight, dappled courtyard', temperature: 'warm', shadow: 'terrace shade under jar bellies' },
    ui: { background: 'earth-brown courtyard field', surface: 'glazed-clay texture cards', components: 'jar-shaped rounded buttons', motion: 'gentle breathing-scale pulses' },
  },
  {
    n: 'Baekja', a: ['백자', 'Joseon white porcelain', 'Joseon baekja', 'Joseon porcelain'],
    cat: 'Regional & Cultural Tradition', c: 'Joseon Korean white porcelain of the royal and Bunwon kilns', e: 'historical',
    o: 'Korea (Gyeonggi and Jeolla kilns)', g: 'Korea', p: '15th century-1883', era: 'Joseon dynasty Korea',
    sum: 'The serene white porcelain of the Joseon court — moon jars, minimal forms and unpainted glazes praised as the ideal of quiet, Confucian restraint and wabi tea taste.',
    desc: 'Baekja is the plain white porcelain of Joseon Korea, made at royal kilns including the Bunwon works at Gwangju. Early wares show crisp Chinese-influenced forms; later kilns perfected the dalhangari moon jar — two hemispheres joined into a huge, leaning white sphere — beside slip-brushed wares. Unpainted restraint suited Confucian ideals of purity, and Japanese tea masters collected Joseon whites as wabi ideals. The official kilns closed in 1883; modern studios continue.',
    col: [{ h: '#f4f0e6', n: 'moon-jar white' }, { h: '#e4ddcd', n: 'warm ivory glaze' }, { h: '#c9c2b0', n: 'gray slip shadow' }, { h: '#9a9284', n: 'kiln-fleck gray' }, { h: '#5d574c', n: 'unglazed foot brown' }],
    m: ['white kaolinic porcelain clay', 'transparent feldspathic glaze', 'slip for brushed decoration', 'wood-fired royal kilns'],
    tx: ['eggshell-glaze sheen', 'slip-brush drag', 'subtle body undulation'],
    obj: ['dalhangari moon jars', 'white bottles and ewers', 'incised dragon jars', 'court tea bowls', 'water droppers'],
    ex: ['Eighteenth-century moon jars in Korean museum collections', 'Bunwon white ware with incised dragon design', 'slip-brushed white jars from Joseon court kilns'],
    inf: ['Goryeo celadon technology', 'Jingdezhen white porcelain', 'Joseon Confucian aesthetics'],
    rel: ['Buncheong Ware', 'Celadon', 'Onggi', 'Wabi-sabi'],
    src: [{ n: 'Wikipedia — Joseon white porcelain', u: 'https://en.wikipedia.org/wiki/Joseon_white_porcelain', t: 'B' }, { n: 'The Metropolitan Museum of Art — Korean ceramics', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['white porcelain', 'joseon', 'moon jar', 'confucian', 'minimal', 'korea'],
    pop: 39, niche: true,
    vd: { shape: 'great leaning spheres and tall-necked bottles', line: 'no contour — silhouette carried by glaze light', composition: 'emptiness as the design; nothing added', texture: 'soft ivory glow with fired flecks' },
    typ: { display: 'n/a — applied object art', body: 'n/a', notes: 'no lettering; rare incised court marks' },
    lit: { quality: 'soft north-light glow', temperature: 'cool-neutral', shadow: 'wraps softly around swelling forms' },
    ui: { background: 'moon-jar ivory field', surface: 'barely-there glaze cards', components: 'hairline-outline buttons', motion: 'breath-slow opacity shifts' },
  },
  {
    n: 'Meissen Porcelain', a: ['Meissen china', 'Meissner Porzellan', 'Meissen porcelain'],
    cat: 'Regional & Cultural Tradition', c: 'First European hard-paste porcelain manufactory', e: 'regional_tradition',
    o: 'Meissen, Saxony, Germany', g: 'Germany (Saxony; royal manufactory at Albrechtsburg, later Triebischtal)', p: '1710-present', era: 'Baroque Europe to present',
    sum: 'Europe\'s first true porcelain, decoded by Tschirnhaus and Böttger in 1708 — Baroque court wares, chinoiserie and Kakiemon painting, and rococo figures that set the continent\'s standard.',
    desc: 'Meissen solved hard-paste porcelain for Europe: Tschirnhaus and Böttger reached the formula by 1708, and Augustus the Strong founded the manufactory at Meissen in 1710. Underglaze blue, chinoiserie and Kakiemon-style painting, the Swan Service and Kaendler\'s rococo figures defined European taste; the crossed-swords mark remains the continent\'s oldest continuously used ceramic trademark. Formulas soon leaked abroad, but Meissen still produces today, byword for painted services and figurines.',
    col: [{ h: '#f7f4ec', n: 'porcelain white' }, { h: '#26468c', n: 'underglaze blue' }, { h: '#b23a2a', n: 'iron-red enamel' }, { h: '#c9a02c', n: 'gilded accent' }, { h: '#3d6b46', n: 'enamel green' }],
    m: ['hard-paste porcelain body (kaolin and petuntse)', 'cobalt underglaze', 'overglaze enamels', 'liquid gold gilding'],
    tx: ['glassy clear glaze', 'fine enamel stipple', 'raised gilt relief'],
    obj: ['Baroque tea and coffee services', 'rococo figure groups', 'chinoiserie-painted vases', 'Böttger red stoneware teapots', 'table garnitures'],
    ex: ['Böttger stoneware and early red porcelain', 'the Swan Service (1737-1741)', 'Kaendler\'s monkey band figurines'],
    inf: ['Chinese Kangxi porcelain', 'Japanese Kakiemon ware', 'Saxon alchemical science under Augustus the Strong'],
    rel: ['Sèvres Porcelain', 'Chinoiserie Panel Lacquer Painting', 'Bavarian Rococo'],
    src: [{ n: 'Wikipedia — Meissen porcelain', u: 'https://en.wikipedia.org/wiki/Meissen_porcelain', t: 'B' }, { n: 'Victoria & Albert Museum — Meissen collection', u: 'https://www.vam.ac.uk', t: 'A' }],
    tg: ['hard-paste porcelain', 'baroque', 'rococo', 'figurines', 'böttger', 'kakiemon'],
    pop: 63, niche: false,
    vd: { shape: 'asymmetric rococo moldings and lively figure silhouettes', line: 'fine enamel contour and gilt edging', composition: 'dense center vignettes inside reserved panels', texture: 'hard glass glaze with jeweled enamel dots' },
    typ: { display: 'crossed-swords mark in underglaze blue', body: 'n/a', notes: 'impressed model and painter numbers' },
    lit: { quality: 'bright specular highlights on glaze and gilt', temperature: 'neutral', shadow: 'crisp reflections under figures' },
    ui: { background: 'porcelain white field', surface: 'panel-reserved enamel cards', components: 'blue-outline gilded buttons', motion: 'precise, courtly fade steps' },
  },
  {
    n: 'Sèvres Porcelain', a: ['Manufacture de Sèvres', 'Vincennes-Sèvres porcelain', 'Sèvres porcelain'],
    cat: 'Regional & Cultural Tradition', c: 'French royal and national porcelain manufactory', e: 'regional_tradition',
    o: 'Sèvres, France', g: 'France (Vincennes 1740-1756; Sèvres from 1756; national manufactory since 1793)', p: '1740-present', era: 'Rococo France to present',
    sum: 'France\'s national porcelain manufactory — Vincennes soft-paste beginnings, Madame de Pompadour\'s rose, jeweled opaque grounds like bleu céleste, and virtuoso gilded services.',
    desc: 'Sèvres grew from the Vincennes manufactory (founded about 1740) into the French crown\'s porcelain works, moving to Sèvres in 1756 under Madame de Pompadour\'s patronage. Its soft-paste bodies of unmatched whiteness carried saturated opaque grounds — bleu céleste, bleu roi, rose Pompadour, reserved for the king — with virtuoso gilding and painters\' panels. It supplied court diplomacy, set Neoclassical taste after 1770, was nationalized in 1793 and adopted hard paste by 1804, still operating today.',
    col: [{ h: '#7f9fd1', n: 'bleu céleste' }, { h: '#2d4b8f', n: 'bleu roi' }, { h: '#d4708f', n: 'rose Pompadour' }, { h: '#d9b64a', n: 'heavy gilding' }, { h: '#f6f2e8', n: 'soft-paste white' }],
    m: ['soft-paste porcelain (from 1804 hard paste)', 'opaque colored ground enamels', 'overglaze panel pigments', 'matte and burnished gold'],
    tx: ['jeweled ground thickness', 'enameled painterly panels', 'chased gilt ridges'],
    obj: ['pot-pourri vases (vase Duplessis)', 'gilded dinner services', 'déjeuner tea sets', 'jeweled-ground urns', 'furniture-mounted porcelain plaques'],
    ex: ['Bleu céleste Duplessis pot-pourri vases', 'Catherine the Great\'s green Sèvres service', 'early hard-paste imperial services after 1804'],
    inf: ['Meissen porcelain', 'Rococo court taste', 'Saint-Cloud and Chantilly soft-paste experiments'],
    rel: ['Meissen Porcelain', 'Bavarian Rococo', 'Neoclassical', 'Empire Style'],
    src: [{ n: 'Wikipedia — Sèvres porcelain', u: 'https://en.wikipedia.org/wiki/Sèvres_porcelain', t: 'B' }, { n: 'Victoria & Albert Museum — Sèvres collection', u: 'https://www.vam.ac.uk', t: 'A' }],
    tg: ['soft paste', 'rococo', 'ground color', 'gilding', 'french court', 'neoclassical'],
    pop: 52, niche: false,
    vd: { shape: 'curvilinear rococo vases, later rectilinear Neoclassical urns', line: 'gilt cartouche framing painterly reserves', composition: 'dominant jeweled ground with centered panels', texture: 'thick enamel depth under burnished gold' },
    typ: { display: 'date letters, painter and gilder marks in ink or gilt', body: 'n/a', notes: 'royal cyphers on court commissions' },
    lit: { quality: 'candlelight-warm specular glow', temperature: 'warm', shadow: 'jeweled depths within ground color' },
    ui: { background: 'bleu céleste field', surface: 'gilt-framed panel cards', components: 'rose-gold outlined buttons', motion: 'stately curtain-like reveals' },
  },
  {
    n: 'Creamware', a: ['Queen\'s ware', 'cream-colored earthenware', 'Leeds creamware'],
    cat: 'Material & Surface', c: 'Cream-bodied lead-glazed English earthenware', e: 'historical',
    o: 'Staffordshire and Yorkshire, England', g: 'Britain, Europe, North America export markets', p: 'c. 1740-1820s', era: 'Georgian Britain',
    sum: 'Pale cream-bodied, lead-glazed earthenware perfected by Wedgwood and Leeds — the affordable Neoclassical tableware that displaced pewter and delft across the eighteenth-century world.',
    desc: 'Creamware is the pale-bodied, lead-glazed earthenware developed by Staffordshire potters from the 1740s and perfected by Josiah Wedgwood, who named it "Queen\'s ware" in 1765. White ball clay and flint blended into yellow clay under transparent lead glaze gave a warm cream ground ideal for Neoclassical molding, enameling and sprigging; Leeds Pottery made crisp pierced wares famous. Cheap, light and elegant, creamware displaced pewter and delft at British tables and dominated export markets.',
    col: [{ h: '#efe3c3', n: 'cream body' }, { h: '#d9c290', n: 'lead-glaze butter tint' }, { h: '#4b6455', n: 'enamel sprig green' }, { h: '#37507e', n: 'enamel sprig blue' }, { h: '#cfd6cf', n: 'pierced glaze sheen' }],
    m: ['white ball clay and flint', 'yellow-firing earthenware clay', 'transparent lead glaze', 'mild overglaze enamels'],
    tx: ['warm glaze pooling in molds', 'crisp molded edges', 'pierced-work light play'],
    obj: ['dinner plates and platters', 'pierced Leeds baskets', 'enameled teapots', 'sprigged jug forms', 'commemorative service pieces'],
    ex: ['Wedgwood Queen\'s ware of 1765', 'Leeds Pottery pierced baskets', 'the Frog Service for Catherine the Great (1773-74)'],
    inf: ['Staffordshire salt-glaze whiteness', 'tin-glaze tableware it displaced', 'Neoclassical pattern design'],
    rel: ['Neoclassical', 'Tin-Glazed Delft', 'Salt-glazed Stoneware', 'Empire Style'],
    src: [{ n: 'Wikipedia — Creamware', u: 'https://en.wikipedia.org/wiki/Creamware', t: 'B' }, { n: 'Victoria & Albert Museum — Creamware', u: 'https://www.vam.ac.uk', t: 'A' }],
    tg: ['earthenware', 'cream body', 'leeds', 'wedgwood', 'georgian', 'tableware'],
    pop: 44, niche: false,
    vd: { shape: 'thin, molded rimmed plates and gadrooned forms', line: 'engraved or enameled fine outline', composition: 'central bouquet or border repeat on cream void', texture: 'buttery glaze over light body' },
    typ: { display: 'impressed or printed maker marks on foot', body: 'n/a', notes: 'commemorative inscriptions on presentation wares' },
    lit: { quality: 'bright domestic daylight', temperature: 'warm', shadow: 'soft amber depth at moldings' },
    ui: { background: 'cream parchment field', surface: 'molded-edge cards', components: 'outline-etched buttons', motion: 'light, springy transitions' },
  },
  {
    n: 'Salt-glazed Stoneware', a: ['Salt glaze', 'Salzglasur', 'salt-glaze stoneware'],
    cat: 'Material & Surface', c: 'Sodium-vapor orange-peel stoneware glaze tradition', e: 'historical',
    o: 'Rhineland, Germany; Staffordshire, England', g: 'Germany, Britain, North America', p: '15th century-19th century', era: 'Late medieval to Victorian',
    sum: 'Stoneware sealed by salt thrown into the kiln fire — sodium fuses into a glassy, orange-peel-stippled skin on gray or buff bodies, from Rhenish Bartmann jugs to English white teapots.',
    desc: 'Salt glazing seals stoneware by volatilizing salt in the firebox: sodium bonds with body silica into a thin glassy coating with a distinctive orange-peel stipple. Rhenish centers — Siegburg, Raeren, the Westerwald — built export empires on gray salt-glazed jugs and bearded Bartmann bottles shipped worldwide. England adopted it for white-bodied teapots and press-molded plates; American makers developed crock traditions. Later industrial kilns ended most salt firing; studio potters preserve it.',
    col: [{ h: '#9aa0a6', n: 'Rhenish gray' }, { h: '#b8a98d', n: 'westerwald buff' }, { h: '#2f4d7a', n: 'cobalt sprig blue' }, { h: '#7b4a9e', n: 'manganese purple' }, { h: '#d7d2c6', n: 'orange-peel sheen' }],
    m: ['gray and buff stoneware clays', 'common salt (sodium chloride)', 'cobalt and manganese oxides', 'wood- and coal-fired kilns'],
    tx: ['orange-peel stipple', 'glassy pitted skin', 'sprigged relief crispness'],
    obj: ['Bartmann bearded jugs', 'Westerwald armorial mugs', 'white salt-glaze teapots', 'press-molded plates', 'ginger beer bottles'],
    ex: ['Rhenish Bartmann bellarmine jugs', 'Westerwald GR armorial mugs', 'Staffordshire white salt-glaze teapots'],
    inf: ['Rhenish stoneware tradition', 'Cologne export trade', 'Staffordshire press-molding'],
    rel: ['Creamware', 'Tin-Glazed Delft'],
    src: [{ n: 'Wikipedia — Salt-glazed stoneware', u: 'https://en.wikipedia.org/wiki/Salt-glazed_stoneware', t: 'B' }, { n: 'The British Museum — Rhineland stoneware', u: 'https://www.britishmuseum.org', t: 'A' }],
    tg: ['stoneware', 'salt glaze', 'orange peel', 'rhenish', 'bartmann', 'staffordshire'],
    pop: 40, niche: false,
    vd: { shape: 'bottle-bodied jugs and sturdy cylindrical crocks', line: 'sprigged and stamped relief borders', composition: 'armorial cartouche centered on jug belly', texture: 'pitted glassy stipple catching light' },
    typ: { display: 'incised or stamped capacity and maker marks', body: 'n/a', notes: 'GR cyphers and merchant seals on trade wares' },
    lit: { quality: 'hard sidelight emphasizing stipple', temperature: 'cool', shadow: 'micro-shadow in every salt pit' },
    ui: { background: 'stone-gray field', surface: 'stippled salt-skin cards', components: 'cobalt-sprig border buttons', motion: 'brisk utilitarian snaps' },
  },
  {
    n: 'Maiolica', a: ['Majolica', 'Istoriato ware', 'Italian tin-glazed earthenware'],
    cat: 'Material & Surface', c: 'Italian tin-glazed earthenware painting tradition', e: 'historical',
    o: 'Italy (Faenza, Deruta, Urbino, Venice)', g: 'Italy; exported across Europe', p: '14th-18th century', era: 'Italian Renaissance to Baroque',
    sum: 'Renaissance Italy\'s tin-glazed pottery — luminous white grounds for cobalt, green, yellow and ruby-luster painting, from apothecary albarellos to istoriato mythological show plates.',
    desc: 'Maiolica is Italian tin-glazed earthenware: an opaque white stanniferous glaze, a canvas for oxide painting — cobalt blue, greens, yellows, purples and ruby luster from Hispano-Moresque practice. Reaching Italy through Islamic Spain via Majorca ("maiolica"), it flourished by the fifteenth century at Faenza, Deruta, Urbino and Venice in apothecary jars, dowry plates and istoriato wares after Raphael-era prints. It declined under porcelain competition yet lived on at Gubbio and Faenza.',
    col: [{ h: '#f3eedd', n: 'tin-glaze white' }, { h: '#2c4f8a', n: 'maiolica cobalt' }, { h: '#c9971f', n: 'antimony yellow' }, { h: '#4f7d3f', n: 'copper green' }, { h: '#a75c33', n: 'ruby luster copper' }],
    m: ['buff earthenware clay', 'tin-opacified lead glaze', 'metallic-oxide pigments', 'copper-silver luster compounds'],
    tx: ['chalky white ground', 'fluid oxide brushwork', 'metallic luster shimmer'],
    obj: ['istoriato show plates', 'apothecary albarellos', 'dowry and birth wares', 'ewers and basins', 'inscribed drug jars'],
    ex: ['Urbino istoriato dishes from the Fontana workshop', 'Deruta ruby-luster wares', 'Faenza and Venetian apothecary albarellos'],
    inf: ['Hispano-Moresque lusterware', 'Islamic tin-glaze technology', 'Renaissance print and fresco design'],
    rel: ['Hispano-Moorish style', 'Faience', 'Tin-Glazed Delft', 'Talavera Poblana'],
    src: [{ n: 'Wikipedia — Maiolica', u: 'https://en.wikipedia.org/wiki/Maiolica', t: 'B' }, { n: 'The Metropolitan Museum of Art — Maiolica', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['tin glaze', 'istoriato', 'renaissance', 'luster', 'faenza', 'italy'],
    pop: 49, niche: false,
    vd: { shape: 'flat show plates as picture frames, albarello cylinders', line: 'assured ink-like contour on chalk white', composition: 'narrative field inside concentric borders', texture: 'matte-whitish glaze with glinting luster' },
    typ: { display: 'inscribed verses, dates and bottega marks', body: 'n/a', notes: 'apothecary jars carry drug names in bands' },
    lit: { quality: 'even museum light, gentle sheen', temperature: 'warm', shadow: 'flat; luster supplies its own glow' },
    ui: { background: 'tin-white field', surface: 'border-framed narrative cards', components: 'cobalt band buttons', motion: 'page-turn vignette transitions' },
  },
  {
    n: 'Rookwood Pottery', a: ['Rookwood Pottery Company', 'Rookwood art pottery'],
    cat: 'Material & Surface', c: 'Cincinnati art pottery of standard glaze lines', e: 'historical',
    o: 'Cincinnati, Ohio, USA', g: 'United States', p: '1880-1967', era: 'American Aesthetic and Arts & Crafts eras',
    sum: 'Cincinnati\'s celebrated art pottery — artist-signed wares in Standard, mat, Vellum and Sea Green glaze lines, each flame-marked, that anchored American art-pottery collecting.',
    desc: 'Rookwood was founded in Cincinnati in 1880 by Maria Longworth Nichols, an art pottery run to studio ideals with women decorators alongside male modelers. Its Standard glaze — deep amber-red over painted portraits and Japanese-inflected motifs — won international prizes; later came ivory mat glazes, translucent Vellum and Sea Green lines. Every piece carries the flame mark with date, shape number and artist initials. Tourist reliance deepened in the Depression, and the company closed in 1967.',
    col: [{ h: '#8c4a2b', n: 'standard glaze amber-red' }, { h: '#c98f4a', n: 'torch-lit gold brown' }, { h: '#e9e2d2', n: 'vellum ivory' }, { h: '#5c7d6b', n: 'sea green' }, { h: '#2f2a26', n: 'painted outline black' }],
    m: ['American earthenware and porcelain bodies', 'lead-free fritted glazes (mat and vellum)', 'underglaze mineral paints', 'plaster production molds'],
    tx: ['glassy standard-glow depth', 'matte velvet surface', 'painted stipple blending'],
    obj: ['Standard glaze portrait vases', 'Vellum iris vases', 'mat glaze garden urns', 'bookends and paperweights', 'architectural faience panels'],
    ex: ['Standard glaze vases painted by Kitaro Shirayamadani', 'Vellum glaze iris vases by Carl Schmidt', '1910s mat glaze garden urns'],
    inf: ['Aesthetic Movement Japonisme', 'Cincinnati pottery and carving circles', 'French matte glaze experiments'],
    rel: ['Grueby Faience', 'Van Briggle Pottery', 'Arts and Crafts Movement', 'Art Nouveau', 'Aesthetic Movement interior'],
    src: [{ n: 'Wikipedia — Rookwood Pottery Company', u: 'https://en.wikipedia.org/wiki/Rookwood_Pottery_Company', t: 'B' }, { n: 'The Metropolitan Museum of Art — Rookwood holdings', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['art pottery', 'standard glaze', 'vellum', 'cincinnati', 'american arts and crafts', 'flame mark'],
    pop: 54, niche: false,
    vd: { shape: 'balanced classical vases and low garden urns', line: 'fine painted contour under glowing glaze', composition: 'centered subject dissolving into glaze gradient', texture: 'amber glass depth or chalk-smooth mat' },
    typ: { display: 'flame mark with date, shape number, artist initials', body: 'n/a', notes: 'press defects and trial pieces marked accordingly' },
    lit: { quality: 'warm gallery spot on glossy depth', temperature: 'warm', shadow: 'glaze-darkened recesses like candlelight' },
    ui: { background: 'amber gradient field', surface: 'glow-depth cards', components: 'flame-mark seal buttons', motion: 'dusk-lit slow luminance shifts' },
  },
  {
    n: 'Grueby Faience', a: ['Grueby Faience Company', 'Grueby pottery'],
    cat: 'Material & Surface', c: 'Boston Arts & Crafts matte-glaze pottery', e: 'historical',
    o: 'Boston and Revere, Massachusetts, USA', g: 'United States', p: '1894-1911', era: 'American Arts & Crafts era',
    sum: 'Boston\'s Arts and Crafts pottery — thick, curdled matte glazes in cucumber green and butterscotch over simple carved-leaf vases, the archetypal American Craftsman vessel.',
    desc: 'Grueby Faience Company (1894-1911), founded by William Grueby in Boston, revived the thick matte glazes of French potters like Taxile Doat. Its signature: heavy, opaque matte surfaces — cucumber green, butterscotch yellow, rarely blue — over simple vases with carved leaves. Gustav Stickley\'s Craftsman circles paired Grueby vases with mission oak; its faience clad buildings like the 1901 Pan-American Exposition. Production ended in 1911; Grueby remains the definitive Arts and Crafts name.',
    col: [{ h: '#7c9a63', n: 'cucumber green matte' }, { h: '#d9b45f', n: 'butterscotch matte' }, { h: '#4c6b45', n: 'glaze-pool deep green' }, { h: '#c4b493', n: 'unglazed clay rim' }, { h: '#37543a', n: 'carved leaf shadow' }],
    m: ['American earthenware clay', 'heavy lead matte glazes', 'hand-carving tools', 'architectural faience tile bodies'],
    tx: ['curdled matte skin', 'glaze pooling in carvings', 'raw clay rim contrast'],
    obj: ['carved-leaf art vases', 'candlesticks', 'fireplace tiles', 'garden pots', 'lamp bases'],
    ex: ['cucumber-green vases with carved leaves', 'Grueby faience at the 1901 Pan-American Exposition', 'butterscotch vases sold through Gustav Stickley'],
    inf: ['French mat glazes (Taxile Doat)', 'Arts and Crafts movement', 'New England tile and faience traditions'],
    rel: ['Rookwood Pottery', 'Arts and Crafts Movement', 'American Craftsman', 'Mission Revival', 'Van Briggle Pottery'],
    src: [{ n: 'Wikipedia — Grueby Faience Company', u: 'https://en.wikipedia.org/wiki/Grueby_Faience_Company', t: 'B' }, { n: 'The Metropolitan Museum of Art — Grueby works', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['matte glaze', 'arts and crafts', 'boston', 'cucumber green', 'carved leaf', 'faience tile'],
    pop: 37, niche: true,
    vd: { shape: 'simple ovoid and shouldered vases, unforced asymmetry', line: 'carved leaf contours as the only drawing', composition: 'one leaf cluster, vast quiet glaze field', texture: 'frosted curdled matte absorbing light' },
    typ: { display: 'impressed Grueby mark with modeler initials', body: 'n/a', notes: 'no surface lettering tradition' },
    lit: { quality: 'soft absorbed daylight, no glare', temperature: 'cool-green warmth', shadow: 'deep matte shadows in leaf carvings' },
    ui: { background: 'cucumber-green matte field', surface: 'frosted clay cards', components: 'leaf-carve outline buttons', motion: 'grounded, craftsmanlike easing' },
  },
  {
    n: 'Van Briggle Pottery', a: ['Van Briggle Art Pottery', 'Van Briggle'],
    cat: 'Regional & Cultural Tradition', c: 'Colorado Arts & Crafts pottery, still in production', e: 'regional_tradition',
    o: 'Colorado Springs, Colorado, USA', g: 'United States', p: '1899-present', era: 'American Arts & Crafts era to present',
    sum: 'Colorado Springs art pottery founded by Artus Van Briggle — velvety matte glazes in signature yellow-greens and blues over curling Art Nouveau forms, continuously made since 1899.',
    desc: 'Van Briggle Pottery was founded in Colorado Springs in 1899 by Artus Van Briggle, a Rookwood-trained decorator who developed thick French-inspired matte glazes in blue-greens and roses. Anne Gregory Van Briggle designed curling, lilied Art Nouveau forms — the twin-tulip and Lorelei vases — that made the young firm a 1904 World\'s Fair sensation. After his early death Anne led the classic period; production continued through relocations, keeping the name among America\'s oldest working potteries.',
    col: [{ h: '#8ba68e', n: 'signature yellow-green matte' }, { h: '#5f7f95', n: 'ming blue matte' }, { h: '#b287a0', n: 'mulberry rose' }, { h: '#d9d3c0', n: 'ivory matte' }, { h: '#4a4a42', n: 'carved recess gray' }],
    m: ['Colorado and imported clay bodies', 'thick fritted matte glazes', 'Art Nouveau plaster molds', 'hand-carving and finishing tools'],
    tx: ['velvety mottled matte', 'faint glaze pooling in curls', 'modeled stem ridges'],
    obj: ['Lorelei and twin-tulip art vases', 'ovoid matte jars', 'curling botanical vases', 'bookends', 'architectural tile'],
    ex: ['the Lorelei vase of 1901', 'twin-tulip vases designed by Anne Van Briggle', 'Ming blue and yellow-green ovoid jars'],
    inf: ['Rookwood training', 'French matte glazes', 'Art Nouveau design'],
    rel: ['Rookwood Pottery', 'Art Nouveau', 'Grueby Faience', 'Arts and Crafts Movement'],
    src: [{ n: 'Wikipedia — Van Briggle Pottery', u: 'https://en.wikipedia.org/wiki/Van_Briggle_Pottery', t: 'B' }, { n: 'The Metropolitan Museum of Art — Van Briggle works', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['matte glaze', 'art nouveau', 'colorado springs', 'arts and crafts', 'yellow green', 'living pottery'],
    pop: 42, niche: false,
    vd: { shape: 'curling, whiplash botanical forms and soft ovoids', line: 'modeled stems and carved linear accents', composition: 'single flowering motive spiraling the body', texture: 'clouded matte like desert dusk' },
    typ: { display: 'impressed Van Briggle mark and date shape codes', body: 'n/a', notes: 'essayist marks varied by production era' },
    lit: { quality: 'soft outdoor light, matte diffusion', temperature: 'cool-warm mix', shadow: 'smoky pooling in carved curls' },
    ui: { background: 'dusk sage gradient', surface: 'velvet-matte cards', components: 'curl-stem outline buttons', motion: 'bloom-like slow unfolds' },
  },
]
