/**
 * Color & Light wave — 12 hand-verified color/light/illustration traditions.
 * Categories: 'Color & Light', 'Illustration & Comics', 'Painting Technique & School'.
 * Sources are stable Wikipedia exact-title URLs plus museum URLs; nothing fabricated.
 */
export const ENTRIES: any[] = [
  {
    n: 'Chiaroscuro', a: ['Clair-obscur', 'light-dark modeling'],
    cat: 'Painting Technique & School', c: 'Tonal painting technique of strong light-shade contrast', e: 'historical',
    o: 'Italy (Renaissance origins)', g: 'Europe — Italy, Flanders, Netherlands, Spain, France', p: 'c. 1500-present', era: 'Renaissance to Baroque Europe',
    sum: 'Strong tonal modeling of light and shade — bold dark-light contrast sculpting form, from Leonardo\'s soft gradation to Caravaggio\'s candlelit drama.',
    desc: 'Chiaroscuro (Italian "light-dark") models form through graded light and shadow rather than line or color. Leonardo codified soft graduated shading; Caravaggio pushed contrast to theatrical extremes with a single light source on a near-black ground; Rembrandt warmed it into glowing amber depth. Candlelit genre scenes, altarpieces and half-length portraits made it the Western canon of tonal painting, and it remains the root of photographic and cinematic lighting vocabulary.',
    col: [{ h: '#14100c', n: 'shadow umber black' }, { h: '#e8a33d', n: 'candlelight gold' }, { h: '#b57a4f', n: 'lit flesh ochre' }, { h: '#5b4632', n: 'half-tone umber' }, { h: '#7a1f22', n: 'crimson drape' }],
    m: ['oil on canvas', 'lead white impasto', 'warm umber glazes', 'single lamp or candle source'],
    tx: ['glazed shadow pooling', 'crisp highlight ridge'],
    obj: ['candlelit genre scenes', 'half-length portraits', 'altarpiece panels', 'vanitas still lifes'],
    ex: ["Caravaggio's The Calling of Saint Matthew (1599-1600)", "Rembrandt's The Night Watch (1642)", "Georges de La Tour's candlelight scenes"],
    inf: ['Leonardo\'s shadow modeling', 'Caravaggism', 'Dutch Golden Age tonal painting'], rel: ['Tenebrism', 'Sfumato', 'Rembrandt Lighting in Paint', 'Grisaille Underpainting'],
    src: [{ n: 'Wikipedia — Chiaroscuro', u: 'https://en.wikipedia.org/wiki/Chiaroscuro', t: 'B' }, { n: 'Wikipedia — Rembrandt', u: 'https://en.wikipedia.org/wiki/Rembrandt', t: 'B' }, { n: 'The Metropolitan Museum of Art — European paintings', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['light and shade', 'tonal', 'baroque', 'modeling', 'caravaggio', 'dramatic'],
    pop: 80, niche: false,
    vd: { shape: 'figures emerging from deep tonal voids', line: 'lost-and-found contours dissolving in shadow', composition: 'raking light pools on key subjects over dark ground', texture: 'glazed translucency under opaque highlights' },
    typ: { display: 'dramatic serif titling emerging from darkness', body: 'n/a — painterly tradition', notes: 'lettering treated as a lit object where present' },
    lit: { quality: 'single hard source with soft falloff', temperature: 'warm', shadow: 'dominant and enveloping' },
    ui: { background: 'near-black umber gradient', surface: 'warmly lit focal cards', components: 'gold-lit outlined buttons', motion: 'slow light-sweep reveals' },
  },
  {
    n: 'Tenebrism', a: ['Tenebroso', 'dark manner'],
    cat: 'Painting Technique & School', c: 'Baroque dramatic darkness with theatrical spotlight', e: 'historical',
    o: 'Rome and Naples, Italy', g: 'Italy, Spain, Spanish Netherlands (Utrecht)', p: 'c. 1590-1650s (echoes into 18th century)', era: 'Baroque Italy and Spain',
    sum: 'Baroque "dark manner" staging scenes in engulfing blackness pierced by one theatrical spotlight — Caravaggio\'s signature dramatic device.',
    desc: 'Tenebrism (Italian tenebroso, "dark") pushes chiaroscuro into drama: figures emerge from enveloping blackness struck by a single, often unseen light, so contrast itself narrates. Caravaggio established the manner in Rome around 1600; Artemisia Gentileschi, Jusepe de Ribera and the Spanish and Utrecht Caravaggists applied it to martyrdoms and nocturnal interiors. The device answered Counter-Reformation demands for visceral piety, and its spotlight-from-blackness logic survives in stage and film lighting.',
    col: [{ h: '#0d0b0e', n: 'tenebra black' }, { h: '#e6b35a', n: 'spotlight gold' }, { h: '#6e1b25', n: 'cardinal crimson' }, { h: '#3a3d2c', n: 'olive darkness' }, { h: '#ece5d8', n: 'struck highlight white' }],
    m: ['oil on canvas', 'dark umber underpainting', 'bitumen-rich shadow glazes', 'single hidden lamp'],
    tx: ['enveloping black field', 'hard single-source falloff'],
    obj: ['martyrdom scenes', 'half-length apostle portraits', 'nocturnal interrogations', 'denial-of-Christ night scenes'],
    ex: ["Caravaggio's The Taking of Christ (1602)", "Artemisia Gentileschi's Judith Slaying Holofernes (c.1620)", "Ribera's martyrdoms for Spanish viceroys"],
    inf: ['Caravaggism', 'Counter-Reformation piety', 'Utrecht Caravaggists'], rel: ['Chiaroscuro', 'Sfumato', 'Grisaille'],
    src: [{ n: 'Wikipedia — Tenebrism', u: 'https://en.wikipedia.org/wiki/Tenebrism', t: 'B' }, { n: 'Wikipedia — Caravaggio', u: 'https://en.wikipedia.org/wiki/Caravaggio', t: 'B' }, { n: 'The Metropolitan Museum of Art — Baroque painting', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['darkness', 'spotlight', 'caravaggio', 'baroque', 'drama', 'nocturnal'],
    pop: 62, niche: true,
    vd: { shape: 'halo-lit figures cut from a black void', line: 'edges lost in darkness, sharpened at highlights', composition: 'one spotlight cone from an off-canvas source', texture: 'glossy dark glaze with hot specular accents' },
    typ: { display: 'white-on-black titling lit like the subject', body: 'n/a — historical painting mode', notes: 'captions kept minimal to preserve darkness' },
    lit: { quality: 'single dramatic key light', temperature: 'warm against neutral dark', shadow: 'absolute, narrative' },
    ui: { background: 'true-black stage', surface: 'single illuminated panels', components: 'spotlit icon buttons on void', motion: 'hard cut-from-black transitions' },
  },
  {
    n: 'Sfumato', a: ['smoke technique', 'Leonardesque haze'],
    cat: 'Painting Technique & School', c: 'Leonardo\'s smoke-soft edgeless glazing', e: 'historical',
    o: 'Florence, Italy', g: 'Italian Renaissance courts (Florence, Milan, Rome)', p: 'c. 1490s-1520s; studied by copyists since', era: 'High Renaissance',
    sum: 'Leonardo da Vinci\'s "smoke" technique — dozens of translucent glazes dissolving contours into seamless tonal haze with no visible brushwork.',
    desc: 'Sfumato (Italian "smoke") is Leonardo da Vinci\'s technique of softening light-shadow transitions until contours vanish like smoke. He built it from many ultra-thin oil glazes, sometimes smoothed with a fingertip, in the Mona Lisa, the Virgin of the Rocks and St John the Baptist. His notebooks justify it optically: the edges of bodies are never hard lines. The living ambiguity made High Renaissance portraiture feel animated, and academies ranked flawless sfumato the summit of oil technique.',
    col: [{ h: '#2e2418', n: 'dark glaze umber' }, { h: '#6b5a44', n: 'sfumato haze' }, { h: '#c99e72', n: 'warm flesh' }, { h: '#8d8577', n: 'smoky gray' }, { h: '#efe6d2', n: 'luminous cream' }],
    m: ['walnut-oil glazes', 'fine soft brushes', 'slow-drying poppy-oil paint', 'primed poplar panel'],
    tx: ['seamless tonal haze', 'no visible brushstroke'],
    obj: ['portrait faces', 'veiled landscape backgrounds', 'Madonna and Child devotions', 'Leda and Baptist studies'],
    ex: ['Mona Lisa (Louvre, c.1503-1519)', 'Virgin of the Rocks (Louvre and London versions)', 'St John the Baptist (Louvre, c.1516)'],
    inf: ['Leonardo\'s optical notebooks', 'Netherlandish oil glazing', 'atmospheric perspective'], rel: ['Chiaroscuro', 'Tenebrism', 'Watercolor painting'],
    src: [{ n: 'Wikipedia — Sfumato', u: 'https://en.wikipedia.org/wiki/Sfumato', t: 'B' }, { n: 'Wikipedia — Mona Lisa', u: 'https://en.wikipedia.org/wiki/Mona_Lisa', t: 'B' }, { n: 'The Metropolitan Museum of Art — Leonardo studies', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['glaze', 'haze', 'leonardo', 'renaissance', 'soft edge', 'portrait'],
    pop: 70, niche: false,
    vd: { shape: 'ovoid faces dissolving into veiled darkness', line: 'no line — edges evaporate', composition: 'pyramidal half-figure before a twilight landscape', texture: 'fingerprint-smooth glaze bloom' },
    typ: { display: 'soft-shadowed serif with feathered edges', body: 'n/a — painting technique', notes: 'no lettering tradition within the style' },
    lit: { quality: 'luminous ambient glow without visible source', temperature: 'warm-neutral', shadow: 'gradated, never absolute' },
    ui: { background: 'sepia haze gradient', surface: 'velvet blur cards', components: 'feather-edged soft buttons', motion: 'slow focus-pull dissolves' },
  },
  {
    n: 'Contre-jour Lighting', a: ['backlighting', 'against-the-day shooting'],
    cat: 'Color & Light', c: 'Shooting into the light source for silhouettes and glow', e: 'commercial_style',
    o: 'Nineteenth-century European photography', g: 'International photography and cinematography', p: '1850s-present', era: 'Pictorialism to modern photography',
    sum: 'Shooting directly into the light so subjects become silhouettes rimmed with glow — haze, flare and luminous edge define the image.',
    desc: 'Contre-jour (French "against the day") points the camera at the light source, throwing foreground subjects into silhouette against a blazing background. Sun through mist, a window or low on the horizon yields luminous rim light, atmospheric haze veils and deliberate lens flare. Gustave Le Gray printed the sun into 1850s seascapes, pictorialists exploited backlit fog, and Bill Brandt built late nudes from window backlight. Cinematography borrows it for mystery and anonymity; silhouette photography remains its purest form.',
    col: [{ h: '#14161a', n: 'silhouette black' }, { h: '#f7f3e8', n: 'blown backlight white' }, { h: '#d9a441', n: 'rim gold' }, { h: '#9fb8c8', n: 'hazy sky blue' }, { h: '#cfd6d2', n: 'atmospheric veil' }],
    m: ['camera film or sensor', 'low sun or window source', 'telephoto compression', 'wide-aperture flare optics'],
    tx: ['glowing rim halo', 'haze-softened gradients', 'silhouette flatness'],
    obj: ['silhouette landscapes', 'backlit portraits', 'sunrise seascapes', 'window-lit interiors'],
    ex: ["Gustave Le Gray's The Great Wave, Sete (1857)", "Bill Brandt's backlit window nudes (1950s)", 'pictorialist backlit fog studies of the 1900s'],
    inf: ['silhouette portraiture', 'Pictorialism', 'Hollywood backlight glamour'], rel: ['Golden Hour Photography', 'Blue Hour Photography', 'Chiaroscuro'],
    src: [{ n: 'Wikipedia — Contre-jour', u: 'https://en.wikipedia.org/wiki/Contre-jour', t: 'B' }, { n: 'Wikipedia — Silhouette', u: 'https://en.wikipedia.org/wiki/Silhouette', t: 'B' }, { n: 'The Metropolitan Museum of Art — photography collection', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['backlight', 'silhouette', 'flare', 'rim light', 'haze', 'photography'],
    pop: 55, niche: true,
    vd: { shape: 'flat dark figure shapes on luminous ground', line: 'bright rim outlining every edge', composition: 'subject centered against the light source', texture: 'halation glow bleeding over contours' },
    typ: { display: 'oversized backlit white type with bloom', body: 'n/a — photographic lighting idiom', notes: 'text reversed out of dark silhouette areas' },
    lit: { quality: 'source-in-frame glare', temperature: 'warm at dawn and dusk, neutral at midday', shadow: 'shadow side faces the camera' },
    ui: { background: 'sun-washed white to black gradient', surface: 'glow-rimmed translucent panels', components: 'outlined ghost buttons', motion: 'flare-sweep transitions' },
  },
  {
    n: 'Golden Hour Photography', a: ['magic hour shooting', 'sunset light photography'],
    cat: 'Color & Light', c: 'Low-sun warm-light photographic practice', e: 'commercial_style',
    o: 'Hollywood and editorial photography practice', g: 'International', p: 'c. 1930s-present, codified late 20th century', era: 'Color film era to digital',
    sum: 'Photography scheduled to the hour after sunrise or before sunset, when low warm sunlight bathes scenes in amber and long soft shadows.',
    desc: 'Golden hour is the period just after sunrise or before sunset when low sunlight passes through more atmosphere, shifting warm while shadows grow long and soft. Hollywood "magic hour" scheduling, Kodachrome-era National Geographic assignments and modern wedding and lifestyle photography treat it as premium light: skin flatters, skies glow, contrast falls. It became standard photographic vocabulary, and golden-hour presets rank among the most-used looks in editing software.',
    col: [{ h: '#f2c14e', n: 'golden sunlight' }, { h: '#e8975a', n: 'amber wash' }, { h: '#f6d5b0', n: 'peach sky' }, { h: '#8a5a6b', n: 'long-shadow mauve' }, { h: '#4a5d78', n: 'cool sky complement' }],
    m: ['camera with warm white balance', 'low-angle sun', 'reflectors and fill', 'Kodachrome-era color film historically'],
    tx: ['long soft shadows', 'warm directional wash', 'subtle lens glow'],
    obj: ['wedding couple sessions', 'travel landscape essays', 'lifestyle advertising', 'seaside and skyline panoramas'],
    ex: ["Ernst Haas's Kodachrome color essays (1950s)", 'National Geographic golden-light reportage', 'contemporary wedding golden-hour sessions'],
    inf: ['Hollywood magic-hour scheduling', 'Kodachrome color film', 'Pictorialist warm tonality'], rel: ['Golden Hour Glow', 'Blue Hour Photography', 'Contre-jour Lighting'],
    src: [{ n: 'Wikipedia — Golden hour (photography)', u: 'https://en.wikipedia.org/wiki/Golden_hour_(photography)', t: 'B' }, { n: 'Wikipedia — Twilight', u: 'https://en.wikipedia.org/wiki/Twilight', t: 'B' }, { n: 'The Metropolitan Museum of Art — photography', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['golden hour', 'warm light', 'magic hour', 'sunrise', 'sunset', 'photography'],
    pop: 82, niche: false,
    vd: { shape: 'warm-edged organic frames with backlit glow', line: 'soft haloed contours', composition: 'low sun just out of frame, long shadows across the ground', texture: 'honeyed atmospheric wash' },
    typ: { display: 'rounded serif in warm gold tones', body: 'n/a — lighting practice', notes: 'warm white-balance bias noted in captions' },
    lit: { quality: 'low directional sun, near-horizontal', temperature: 'very warm', shadow: 'long, soft-edged, blue-cooled' },
    ui: { background: 'sunset gradient bands', surface: 'sun-flared photo cards', components: 'gold-tinted pill buttons', motion: 'warm light-bleed wipes' },
  },
  {
    n: 'Blue Hour Photography', a: ['twilight photography', 'civil twilight shooting'],
    cat: 'Color & Light', c: 'Deep-twilight cobalt-sky photographic practice', e: 'commercial_style',
    o: 'Night and architectural photography practice', g: 'International', p: 'early 20th century-present', era: 'Twentieth-century night photography to digital',
    sum: 'Shooting in the twilight band between sunset and night, when the clear sky glows cobalt and city lights balance with skylight.',
    desc: 'Blue hour is the twilight interval when the sun sits below the horizon yet the clear sky still glows deep cobalt. Artificial lights balance with the sky instead of fighting black, so cityscapes, bridges and building exteriors are shot in this window. Brassai prowled twilight Paris for Paris de Nuit (1933), and Michael Kenna\'s long-exposure dawn studies made the interval a fine-art idiom. Tripod long exposures smooth water and cloud into the serene tonal register the name describes.',
    col: [{ h: '#16213e', n: 'dusk navy' }, { h: '#2b3d63', n: 'blue hour cobalt' }, { h: '#3e5f8a', n: 'horizon steel' }, { h: '#8b8fa8', n: 'lavender twilight' }, { h: '#d99a7a', n: 'last-light peach' }],
    m: ['tripod-mounted camera', 'long exposure, seconds to minutes', 'neutral-density filtration', 'mixed ambient tungsten and skylight'],
    tx: ['smooth tonal gradient', 'low-contrast haze', 'cool even cast'],
    obj: ['city skylines at dusk', 'bridge and tower studies', 'long-exposure seascapes', 'building exteriors'],
    ex: ["Brassai's Paris de Nuit (1933)", "Michael Kenna's Hokkaido dawn studies", 'architectural firm twilight portfolio shots'],
    inf: ['astronomical twilight timing', 'Brassai night photography', 'long-exposure fine-art tradition'], rel: ['Golden Hour Photography', 'Contre-jour Lighting', 'Golden Hour Glow'],
    src: [{ n: 'Wikipedia — Blue hour', u: 'https://en.wikipedia.org/wiki/Blue_hour', t: 'B' }, { n: 'Wikipedia — Brassai', u: 'https://en.wikipedia.org/wiki/Brassa%C3%AF', t: 'B' }, { n: 'The Metropolitan Museum of Art — photography', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['blue hour', 'twilight', 'long exposure', 'cityscape', 'cobalt', 'photography'],
    pop: 68, niche: true,
    vd: { shape: 'clean geometric skylines under deep gradient domes', line: 'crisp light trails and edge glow', composition: 'horizon low, sky dominant', texture: 'silky long-exposure smoothness' },
    typ: { display: 'cool thin sans in ice blue', body: 'n/a — photographic timing idiom', notes: 'paired with warm-light accent thumbnails' },
    lit: { quality: 'even ambient skylight', temperature: 'cool', shadow: 'soft, barely present' },
    ui: { background: 'dusk cobalt gradient', surface: 'glassy dark photo cards', components: 'steel-blue outlined buttons', motion: 'gentle cross-fades with light trails' },
  },
  {
    n: 'Children\'s Book Golden Age Illustration', a: ['Golden Age picture books', 'Victorian toy books', 'Rackham-Greenaway manner'],
    cat: 'Illustration & Comics', c: 'Late Victorian and Edwardian picture-book illustration', e: 'historical',
    o: 'London, England', g: 'Britain, Europe, North America', p: 'c. 1870-1914 (peak 1880s-1910s)', era: 'Late Victorian and Edwardian',
    sum: 'The Golden Age of Illustration in children\'s publishing — Caldecott\'s motion, Greenaway\'s pastels, Rackham\'s ink-fairies in printed color.',
    desc: 'Between roughly 1870 and 1914, improved color printing — chromoxylography and three-color process — let publishers mass-produce fine picture books, launching the Golden Age of Illustration. Randolph Caldecott put comic motion into nursery rhymes, Kate Greenaway dressed childhood in Regency pastels, Walter Crane designed toy books like Arts and Crafts panels, and Arthur Rackham layered pen silhouettes with muted fairy washes. Gift-book annuals carried the manner worldwide into the twentieth century.',
    col: [{ h: '#f3ead6', n: 'cream book paper' }, { h: '#4a3728', n: 'pen-line brown' }, { h: '#d4a843', n: 'storybook gold' }, { h: '#b0503c', n: 'printed brick red' }, { h: '#8aa06a', n: 'pastel foliage green' }],
    m: ['pen and ink line', 'watercolor washes', 'three-color process plates', 'cream-coated paper'],
    tx: ['confident pen contour', 'flat transparent wash', 'visible process-print texture'],
    obj: ['picture-book spreads', 'toy books and gift annuals', 'nursery-rhyme collections', 'fairy-tale anthologies'],
    ex: ["Caldecott's The Diverting History of John Gilpin (1878)", "Greenaway's Under the Window (1878)", "Rackham's Peter Pan in Kensington Gardens (1906)"],
    inf: ['Arts and Crafts woodblock revival', 'chromoxylography printing', "Edmund Evans' color printing trade"], rel: ['Golden Age of Illustration', 'Art Nouveau', 'Watercolor painting', 'Japanese woodblock prints'],
    src: [{ n: 'Wikipedia — Arthur Rackham', u: 'https://en.wikipedia.org/wiki/Arthur_Rackham', t: 'B' }, { n: 'Wikipedia — Randolph Caldecott', u: 'https://en.wikipedia.org/wiki/Randolph_Caldecott', t: 'B' }, { n: 'The Metropolitan Museum of Art — book illustration', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['picture book', 'golden age', 'nursery', 'edwardian', 'fairy tale', 'pen and wash'],
    pop: 60, niche: false,
    vd: { shape: 'lively clustered figures with expressive gesture', line: 'jittery ink contour carrying the motion', composition: 'text below, image above, generous margins', texture: 'flat washes inside firm ink boundaries' },
    typ: { display: 'hand-drawn display lettering integrated with pictures', body: 'readable serifs set by the printer', notes: 'captions often hand-lettered by the illustrator' },
    lit: { quality: 'even daylight, gentle modeling', temperature: 'warm', shadow: 'light decorative shading' },
    ui: { background: 'cream paper field', surface: 'framed vignette cards', components: 'ink-outline buttons with wash fills', motion: 'page-turn reveals' },
  },
  {
    n: 'Botanical Illustration Tradition', a: ['botanical art', 'florilegium plates', 'scientific plant painting'],
    cat: 'Illustration & Comics', c: 'Scientific watercolor portraiture of plants', e: 'historical',
    o: 'European herbals and court gardens', g: 'Europe and colonial botanical networks; global practice today', p: '1st century (Dioscorides) to present; peak 1600s-1800s', era: 'Herbal age to Victorian science',
    sum: 'Scientific watercolor portraiture of plants — life-size, dissection-annotated plates on vellum or paper, from Besler and Merian to Redoute\'s roses.',
    desc: 'Botanical illustration serves plant science while pursuing beauty: life-size habit studies, enlarged dissections and ruled annotation identifying species for taxonomy and horticulture. The lineage runs from the Vienna Dioscorides (c.512) through Renaissance herbals to the great florilegia — Besler\'s Hortus Eystettensis (1613), Merian\'s insect-plant studies (1705), Redoute\'s roses for Empress Josephine. Stipple-engraved, hand-colored plates dominated reproduction until lithography, and institutions still commission watercolors today.',
    col: [{ h: '#4a6b3a', n: 'foliage green' }, { h: '#6f8f5a', n: 'young shoot green' }, { h: '#f0e8d4', n: 'vellum cream' }, { h: '#c46a7a', n: 'petal rose' }, { h: '#3d2f24', n: 'sepia ink brown' }],
    m: ['watercolor on vellum or rag paper', 'graphite underdrawing', 'gouache body color', 'camera-lucida aids historically'],
    tx: ['precise stippled shading', 'translucent layered wash', 'ruled annotation line'],
    obj: ['florilegium plates', 'herbarium folios', 'orchid and rose monographs', 'horticultural magazine plates'],
    ex: ["Besler's Hortus Eystettensis (1613)", "Merian's Metamorphosis insectorum Surinamensium (1705)", "Redoute's Les Liliacees (1802-1816)"],
    inf: ['Linnaean taxonomy', 'Renaissance herbals', 'voyages of natural history'], rel: ['Botanical illustration', 'Redouté Botanical Plates', 'Stippling & Engraving Tone', 'Watercolor painting'],
    src: [{ n: 'Wikipedia — Botanical illustration', u: 'https://en.wikipedia.org/wiki/Botanical_illustration', t: 'B' }, { n: 'Wikipedia — Pierre-Joseph Redoute', u: 'https://en.wikipedia.org/wiki/Pierre-Joseph_Redout%C3%A9', t: 'B' }, { n: 'The Metropolitan Museum of Art — drawings and prints', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['watercolor', 'botany', 'florilegium', 'plate', 'scientific', 'vellum'],
    pop: 58, niche: false,
    vd: { shape: 'single specimen centered with root, bloom and dissections', line: 'fine continuous contour with stipple shading', composition: 'specimen isolated on unprinted ground, numbers keyed to notes', texture: 'granular watercolor over laid paper' },
    typ: { display: 'engraved roman captions and numerals', body: 'n/a — plate tradition', notes: 'Latin binomials and dedications set in tiny italics' },
    lit: { quality: 'even north-light', temperature: 'neutral', shadow: 'faint drop shadow only' },
    ui: { background: 'vellum cream', surface: 'plate-framed specimen cards', components: 'keyed numeric markers and rules', motion: 'quiet zoom on plate details' },
  },
  {
    n: 'Anatomical Illustration', a: ['medical illustration (historical)', 'anatomy atlas plates'],
    cat: 'Illustration & Comics', c: 'Engraved and lithographed medical atlas tradition', e: 'historical',
    o: 'Padua and Venice printing houses', g: 'Europe; European medical schools worldwide', p: 'Renaissance to early 20th century (practice continues)', era: 'Scientific revival to Victorian medicine',
    sum: 'Engraved and lithographed medical atlases — ecorche muscle figures posed in landscapes, from Vesalius\' Fabrica (1543) to Gray\'s Anatomy (1858).',
    desc: 'Anatomical illustration renders dissected bodies for medical teaching, fusing artist, anatomist and print shop. Vesalius\' De humani corporis fabrica (1543), with woodcuts tied to Titian\'s studio, set the model — flayed figures posed in landscapes, layered from skeleton to muscle. William Hunter\'s gravid-uterus atlas (1774) and Carter\'s drawings for Gray\'s Anatomy (1858) refined accuracy and dignity, while engraving and lithography carried cross-hatched flesh tones and drapery conventions into every medical library.',
    col: [{ h: '#4d3826', n: 'sepia engraving ink' }, { h: '#e8dcc0', n: 'aged paper' }, { h: '#96402e', n: 'muscle red wash' }, { h: '#3a5a78', n: 'vein blue' }, { h: '#ddd2b8', n: 'bone ivory' }],
    m: ['woodcut and copperplate engraving', 'hand-coloring washes', 'lithographic stone (19th century)', 'rag printing paper'],
    tx: ['cross-contour hatching', 'plate tone on paper', 'pale hand-colored flesh'],
    obj: ['ecorche muscle plates', 'skeleton and osteology folios', 'obstetric atlases', 'surgical instrument manuals'],
    ex: ["Vesalius' De humani corporis fabrica (1543)", "Hunter's Anatomy of the Human Gravid Uterus (1774)", "Carter's plates for Gray's Anatomy (1858)"],
    inf: ['Vesalian anatomy', 'Renaissance printing', 'studio life-drawing training'], rel: ['Vesalian Anatomical Illustration', 'Andreas Vesalius engravings', 'Anatomical plates', 'Stippling & Engraving Tone', 'Hatching & Crosshatching'],
    src: [{ n: 'Wikipedia — Andreas Vesalius', u: 'https://en.wikipedia.org/wiki/Andreas_Vesalius', t: 'B' }, { n: 'Wikipedia — De humani corporis fabrica', u: 'https://en.wikipedia.org/wiki/De_humani_corporis_fabrica', t: 'B' }, { n: 'The Metropolitan Museum of Art — prints', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['anatomy', 'engraving', 'ecorche', 'medical', 'atlas', 'woodcut'],
    pop: 45, niche: true,
    vd: { shape: 'flayed figures in theatrical contrapposto', line: 'contour-following hatch modeling muscle', composition: 'figures arrayed across landscape backdrops, layered plates', texture: 'incised ink line over warm paper' },
    typ: { display: 'numbered key lettering tied to figures', body: 'n/a — atlas plates', notes: 'Latin terminology labels across plate surfaces' },
    lit: { quality: 'strong directional studio light', temperature: 'neutral-warm', shadow: 'hatched, explanatory' },
    ui: { background: 'aged parchment', surface: 'plate cards with keyed margins', components: 'numbered tab buttons', motion: 'layer-peel reveals' },
  },
  {
    n: 'Manga Screentone Aesthetics', a: ['screentone art', 'tone-film shading', 'Deleter tone look'],
    cat: 'Illustration & Comics', c: 'Adhesive dot-film gray system of manga production', e: 'commercial_style',
    o: 'Tokyo manga publishing (Letraton and Deleter supplies)', g: 'Japan; global manga-influenced comics', p: 'c. 1960s-present, tones widespread by 1970s', era: 'Postwar manga to digital tone',
    sum: 'Adhesive dot-pattern films pasted into inked manga pages — instant gray value, texture and sparkle that became the medium\'s signature.',
    desc: 'Screentone is pre-printed adhesive film carrying halftone dot patterns, cut with a scalpel and burnished onto inked line art to supply gray values that cheap magazine printing cannot hold. Manga studios adopted it through the 1960s-70s; in shōjo work of the Year 24 Group, layered tones carried atmosphere, emotion and fabric sparkle. Tone catalogs of dots, gradients and pattern flourishes became a language of their own, and digital tone libraries now reproduce the same grain worldwide.',
    col: [{ h: '#f8f8f6', n: 'manga page white' }, { h: '#1a1a1e', n: 'india ink black' }, { h: '#9a9aa2', n: '40 percent tone gray' }, { h: '#55555e', n: 'deep tone shadow' }, { h: '#e8a0b0', n: 'shojo accent pink' }],
    m: ['adhesive screentone sheets (Letraton, Deleter)', 'tonehera spatula', 'india ink and G-pens', 'manga magazine paper'],
    tx: ['uniform dot-pattern grain', 'high-contrast ink line', 'moire-prone overlay'],
    obj: ['shonen action spreads', 'shojo romance pages', 'manga cover artwork', 'doujinshi and fanzines'],
    ex: ["Moto Hagio's The Heart of Thomas (1974)", "Akira Toriyama's Dragon Ball pages (1984-1995)", "Naoko Takeuchi's Sailor Moon (1992-1997)"],
    inf: ['halftone printing process', 'photo-transfer Letraset culture', 'cheap web-offset magazine printing'], rel: ['Halftone Comic Book Printing', 'Comic halftone process', 'Four-color comic printing', 'Clear line', 'Anime Cel Aesthetics'],
    src: [{ n: 'Wikipedia — Screentone', u: 'https://en.wikipedia.org/wiki/Screentone', t: 'B' }, { n: 'Wikipedia — Manga', u: 'https://en.wikipedia.org/wiki/Manga', t: 'B' }, { n: 'The Metropolitan Museum of Art — Japanese illustration', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['screentone', 'halftone dots', 'manga', 'shojo', 'ink line', 'gray values'],
    pop: 65, niche: true,
    vd: { shape: 'angular speed-line panels with floating tone blooms', line: 'variable pen weight with white-out sparkles', composition: 'asymmetrical page grids, tone gradients between panels', texture: 'flat dot screen over unmodulated black' },
    typ: { display: 'furious hand-drawn onomatopoeia in tone', body: 'vertical kana typesetting in tone-banded boxes', notes: 'tone reserved behind dialogue to keep text legible' },
    lit: { quality: 'graphic — no modeled light', temperature: 'neutral', shadow: 'tone dots define cast shadows' },
    ui: { background: 'paper white with dot fields', surface: 'panel-grid cards', components: 'dot-texture buttons and speed-line dividers', motion: 'snappy panel-swap cuts' },
  },
  {
    n: 'Anime Cel Aesthetics', a: ['cel animation look', 'traditional anime shading', 'ink-and-paint style'],
    cat: 'Illustration & Comics', c: 'Hand-painted celluloid animation style of Japanese studios', e: 'commercial_style',
    o: 'Tokyo animation studios (Toei, Mushi Pro lineage)', g: 'Japan; global anime', p: 'c. 1960s-1990s cel era; style persists digitally', era: 'TV anime boom to cel-era peak',
    sum: 'Hand-painted celluloid animation look — flat color fills, hard two-step shadows, bold black outlines and luminous painted backgrounds.',
    desc: 'Anime cel aesthetics come from painting characters in gouache on transparent celluloid, photographed over painted backgrounds. Television economics enforced the look: limited frames per second, flat unblended fills, one hard shadow tone per color and thick uniform outlines that photograph cleanly. Studio Ghibli films, the Sailor Moon TV series and Akira (1988) mark the late cel peak before digital ink-and-paint spread from the mid-1990s. Crisp line, two-tone shading and saturated fills over soft painted backdrops remain anime\'s defining image.',
    col: [{ h: '#1c1c22', n: 'cel outline black' }, { h: '#f5d5b8', n: 'cel skin tone' }, { h: '#6aa8dc', n: 'anime sky blue' }, { h: '#45508a', n: 'cel shadow violet' }, { h: '#f4f4f2', n: 'paint highlight white' }],
    m: ['clear celluloid sheets', 'poster-color gouache cel paint', 'background paintings on board', 'rostrum animation camera'],
    tx: ['hard-edged shadow boundary', 'uniform flat fill', 'glossy acetate surface'],
    obj: ['TV episode cels', 'key animation genga', 'anime posters and VHS covers', 'production background paintings'],
    ex: ['Akira (1988) cel animation', "Studio Ghibli's My Neighbor Totoro (1988)", 'Sailor Moon TV cels (1992-1997)'],
    inf: ['Disney cel system', 'limited TV animation economics', 'Toei Doga training lineage'], rel: ['Manga Screentone Aesthetics', 'Clear line', 'Ukiyo-e', 'Four-color comic printing'],
    src: [{ n: 'Wikipedia — Traditional animation', u: 'https://en.wikipedia.org/wiki/Traditional_animation', t: 'B' }, { n: 'Wikipedia — Anime', u: 'https://en.wikipedia.org/wiki/Anime', t: 'B' }, { n: 'The Metropolitan Museum of Art — modern design', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['cel animation', 'anime', 'flat color', 'hard shadow', 'gouache', 'limited animation'],
    pop: 72, niche: false,
    vd: { shape: 'rounded stylized characters with oversized eyes', line: 'bold uniform black contour', composition: 'character plane over layered painted depth', texture: 'flat paint fields with hard shadow steps' },
    typ: { display: 'katakana-flavored logotypes with hard outline', body: 'n/a — animation idiom', notes: 'credit blocks in plain gothic sans' },
    lit: { quality: 'even, stepped rather than graded', temperature: 'varies by scene palette', shadow: 'single hard cel-shadow tone' },
    ui: { background: 'painted gradient sky wash', surface: 'flat saturated panels with shadow bands', components: 'outlined sticker buttons', motion: 'two-frame stepped animation loops' },
  },
  {
    n: 'Stippling & Engraving Tone', a: ['stipple engraving', 'engraved tonal manner', 'dot-tone intaglio'],
    cat: 'Illustration & Comics', c: 'Tone built from incised dots and lines in intaglio printmaking', e: 'historical',
    o: 'European print workshops (Rome, London, Paris)', g: 'Europe and North America', p: 'c. 1500-present; stipple peak 1770-1830', era: 'Renaissance engraving to banknote era',
    sum: 'Gray tone built from dots and incised lines — stipple engraving, mezzotint bloom and banknote intaglio — the print shop\'s answer to gradation.',
    desc: 'Before photographic halftones, printmakers built gray tone from repeated marks: engravers swelled and finelined hatch, stipplers tapped constellations of dots, and mezzotint rockers roughened plates to print velvet black. Francesco Bartolozzi\'s stipple manner dominated fashionable printmaking around 1770-1830, printing drawings as soft tonal flesh. The same dot-and-line logic ruled banknotes and postage stamps, where engine-turned engraving resisted forgery, and hand stippling survives in scientific illustration.',
    col: [{ h: '#1e1c1a', n: 'intaglio ink black' }, { h: '#8a8a8a', n: 'stipple mid gray' }, { h: '#efe8d8', n: 'laid paper cream' }, { h: '#6a6a6a', n: 'plate tone' }, { h: '#f7f2e6', n: 'paper highlight white' }],
    m: ['copper or steel plates', 'burin and etching needle', 'stipple roulettes and rockers', 'dampened rag paper'],
    tx: ['graduated dot density', 'incised line sheen', 'faint plate tone'],
    obj: ['stipple-engraved portraits', 'mezzotint reproductive prints', 'banknote and stamp plates', 'book frontispieces'],
    ex: ["Bartolozzi's stipple engravings after Cipriani (1770s-90s)", 'American Bank Note Company intaglio securities', 'Dore-era tone-block book engravings'],
    inf: ['copperplate line engraving', 'aquatint tonality', 'chalk-manner crayon engraving'], rel: ['Stippling', 'Hatching & Crosshatching', 'Contour Hatching', 'guilloché engraving', 'Pointillism in drawing'],
    src: [{ n: 'Wikipedia — Stippling', u: 'https://en.wikipedia.org/wiki/Stippling', t: 'B' }, { n: 'Wikipedia — Engraving', u: 'https://en.wikipedia.org/wiki/Engraving', t: 'B' }, { n: 'The Metropolitan Museum of Art — prints', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['stipple', 'engraving', 'intaglio', 'tone', 'banknote', 'mezzotint'],
    pop: 48, niche: true,
    vd: { shape: 'oval portrait frames with swelled tonal contours', line: 'dots and hatch swelling in mass', composition: 'tonal vignette on unprinted paper reserve', texture: 'paper pushed into incised ink ridges' },
    typ: { display: 'engraved roman capitals with shaded serifs', body: 'n/a — reproductive print tradition', notes: 'engraver and publisher credits beneath plate lines' },
    lit: { quality: 'raking light reveals incision', temperature: 'neutral', shadow: 'built from mark density, none natural' },
    ui: { background: 'laid paper cream', surface: 'intaglio-textured cards', components: 'dot-screen gray buttons', motion: 'tone-buildup fades' },
  },
]
