/**
 * Wave 16 — craft-techniques: 16 hand-verified decorative / metalwork / surface techniques.
 * Fills the 'textures & materials' domain. All names are real, documented techniques;
 * deduped against existing-names.txt (skipped: Kintsugi, cloisonné via Shippo Cloisonné,
 * Damascening via Pamor Damascene, urushi via Wajima Lacquer, Marquetry and Intarsia,
 * Pietra dura, Sgraffito, Terrazzo family). Wikipedia source URLs verified HTTP 200.
 */
export const ENTRIES: any[] = [
  {
    n: 'Verre Églomisé', a: ['Églomisé glass', 'verre églomisé', 'reverse-gilded glass', 'Glomy process'],
    cat: 'Material & Surface', c: 'Reverse gilding on glass', e: 'regional_tradition',
    o: 'France (technique of Roman/Levantine origin)', g: 'Roman Empire, Levant, France, England, Art Deco Europe and America', p: 'Hellenistic-Roman antiquity; revived 18th century-present', era: 'Rome to Art Deco',
    sum: 'Gilding on the reverse of a glass pane — gold or silver leaf fixed with size, engraved and backed with paint — giving flawless mirror-metal lettering and ornament.',
    desc: 'Verre églomisé gilds the reverse of a glass pane: gold or silver leaf is fixed with gelatine size, engraved or etched, then sealed with backing paint. Named for Jean-Baptiste Glomy, the 18th-century Parisian frame dealer who revived it, the process descends from Hellenistic and Roman gold glass. Viewed from the front the leaf reads as flawless mirror-metal — crisp monograms, rules and matte-versus-brilliant contrast — prized for Regency and Art Deco signs, mirrors and panels.',
    col: [{ h: '#c9a227', n: 'gold leaf' }, { h: '#cfd4da', n: 'mirror silver' }, { h: '#1a1a1c', n: 'backing black' }, { h: '#6e2430', n: 'oxblood backing' }, { h: '#2f5d50', n: 'viridian backing' }],
    m: ['annealed glass panes', 'gold and silver leaf', 'gelatine size', 'backing paint and foil'],
    tx: ['mirror-flat leaf', 'engraved-through outline', 'matte backing contrast'],
    obj: ['gilded shop and pub signs', 'mirrored overmantel panels', 'reverse-lettered door glass', 'frame inserts and mounts'],
    ex: ['Roman gold-glass medallions (3rd-4th c.) in the British Museum', 'Regency églomisé mirror-frames and signboards', 'Art Deco églomisé signage and shopfront panels'],
    inf: ['Roman gold glass', 'mirror-making', 'Art Deco interiors'], rel: ['Water Gilding', 'Chinoiserie Panel Lacquer Painting', 'Art Deco', 'Graining'],
    src: [{ n: 'Wikipedia — Verre églomisé', u: 'https://en.wikipedia.org/wiki/Verre_%C3%A9glomis%C3%A9', t: 'B' }, { n: 'The Metropolitan Museum of Art — glass and gilding collections', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['gilding', 'reverse glass', 'gold leaf', 'signage', 'art deco', 'mirror'],
    pop: 38, niche: true,
    vd: { shape: 'ruled panels, monogram roundels, border fillets', line: 'engraved-through contour, razor-clean on mirror metal', composition: 'reverse-reading layout planned mirrored on the glass', texture: 'flawless metallic sheen over deep backing color' },
    typ: { display: 'gilded monograms and shop lettering laid in reverse', body: 'n/a — decorative surface', notes: 'all lettering is drawn mirrored on the back of the pane' },
    lit: { quality: 'specular metal reflections with matte ground passages', temperature: 'cool with warm gold accents', shadow: 'painted on the reverse as hard drop shadows' },
    ui: { background: 'deep oxblood or black glass field', surface: 'gilded mirrored panels', components: 'gold-outline buttons and rules', motion: 'slow glint sweeps across leaf' },
  },
  {
    n: 'Guilloché', a: ['Guilloche engine turning', 'engine turning', 'rose-engine work', 'guilloché engraving'],
    cat: 'Texture & Material Study', c: 'Engine-turned metal engraving', e: 'regional_tradition',
    o: 'France & Switzerland (horology focus)', g: 'France, Switzerland, Russia, Germany, security printing worldwide', p: '17th century-present', era: 'Baroque to modern horology',
    sum: 'Repeating spirograph-like patterns cut into metal by hand-cranked rose engines — the signature ribbed shimmer of watch dials, Fabergé enamel and banknote grounds.',
    desc: 'Guilloché is engine-turned ornament: a hand-cranked rose engine or straight-line lathe cuts repeating geometric bands — waves, interlaced circles, sunburst ridges — into metal blanks. Breguet fitted guilloché dials from the late 18th century; Fabergé fused translucent enamel over machine-ribbed silver; security printers borrowed the mathematics for banknote backgrounds. Patterns are mathematically regular yet optically shimmering, catching light as fine ridged moiré.',
    col: [{ h: '#d8dde3', n: 'polished silver' }, { h: '#7fa8c9', n: 'guilloché enamel blue' }, { h: '#d19a7a', n: 'rose gold' }, { h: '#4a4e55', n: 'engine-cut shadow' }, { h: '#f2f4f7', n: 'burnished highlight' }],
    m: ['brass, silver and gold blanks', 'rose engine and straight-line lathe', 'hardened cutters', 'translucent enamel (Fabergé method)'],
    tx: ['ridged moiré shimmer', 'engine-line regularity', 'enamel-over-ribbing depth'],
    obj: ['watch dials and cases', 'cigarette cases and boxes', 'banknote ground patterns', 'Fabergé enamel minatures', 'locket and compact lids'],
    ex: ['Breguet guilloché watch dials (from c. 1790s)', 'Fabergé imperial eggs with enamel over guilloché silver', 'Guilloché rosette grounds of security banknote printing'],
    inf: ['Swiss horology', 'Fabergé enamel work', 'rose-engine turning', 'security printing'], rel: ['Viana Heart Filigree', 'Art Deco', 'Niello Inlay', 'Art Nouveau'],
    src: [{ n: 'Wikipedia — Guilloché', u: 'https://en.wikipedia.org/wiki/Guilloch%C3%A9', t: 'B' }, { n: 'Victoria & Albert Museum — metalwork collections', u: 'https://www.vam.ac.uk', t: 'A' }],
    tg: ['engine turning', 'rose engine', 'watch dial', 'faberge', 'enamel', 'moire'],
    pop: 44, niche: false,
    vd: { shape: 'precise overlapping circles, waves and sunbursts', line: 'machine-even engraved grooves', composition: 'all-over repeat banded by polished fields', texture: 'fine ridged metal catching moving light' },
    typ: { display: 'engraved names and numerals over engine-turned grounds', body: 'n/a — applied metalwork', notes: 'dial lettering engraved or enamel-filled, never printed' },
    lit: { quality: 'hard point highlights traveling across ridges', temperature: 'cool metallic', shadow: 'micro grooves self-shadow into moiré' },
    ui: { background: 'brushed silver field', surface: 'engine-ribbed cards and dials', components: 'guilloché-etched buttons and bezels', motion: 'rotating dial shimmer on scroll' },
  },
  {
    n: 'Champlevé Enamel', a: ['Champlevé', 'champlevé enamel on copper', 'Limoges champlevé'],
    cat: 'Material & Surface', c: 'Cell-carved enamel on copper', e: 'historical',
    o: 'Limoges, France (Mosan valley co-center)', g: 'Romanesque Western Europe', p: '11th-14th century apex; revivals to present', era: 'Romanesque medieval Europe',
    sum: 'Medieval enamel in which cells are hollowed from copper, filled with glass paste, fired and ground flush — gilt ridges framing deep Romanesque blues and greens.',
    desc: 'In champlevé enamel the metalworker chisels or etches hollow cells into a thick copper plate, fills them with crushed-glass enamel paste, fires until fused, then grinds and polishes the surface flush. The gilt ridges between cells frame deep saturated blues, greens and whites. Medieval Limoges made the technique famous across Romanesque Europe with reliquary chasses and altarpieces, while Byzantium preferred cloisonné. The flush, inlaid look anticipates hardstone marquetry.',
    col: [{ h: '#1e4d8c', n: 'limoges blue' }, { h: '#2e6b4f', n: 'medieval green' }, { h: '#d9a441', n: 'enamel yellow' }, { h: '#b08d3f', n: 'gilt copper ridge' }, { h: '#ece7dc', n: 'opaque white' }],
    m: ['hammered copper plates', 'crushed-glass enamel frit', 'kiln firing trays', 'gilding over raised ridges'],
    tx: ['glassy fired pools', 'flush polished cells', 'hard gilt contours'],
    obj: ['reliquary chasses and shrines', 'altar frontals', 'candlesticks and aquamaniles', 'book covers'],
    ex: ['Limoges Becket reliquary chasses (c. 1180-1220, V&A and British Museum)', 'Mosan champlevé work of Godefroid de Claire', 'Romanesque champlevé candlesticks in cathedral treasuries'],
    inf: ['Romanesque metalwork', 'cloisonné enamel', 'Byzantine goldsmithing', 'Limoges painted enamel'], rel: ['Shippo Cloisonné', 'Gothic Revival', 'Neoclassical', 'Plique-à-jour', 'Micromosaic'],
    src: [{ n: 'Wikipedia — Champlevé', u: 'https://en.wikipedia.org/wiki/Champlev%C3%A9', t: 'B' }, { n: 'Victoria & Albert Museum — medieval enamels', u: 'https://www.vam.ac.uk', t: 'A' }, { n: 'The British Museum — Limoges champlevé', u: 'https://www.britishmuseum.org', t: 'A' }],
    tg: ['enamel', 'limoges', 'romanesque', 'copper', 'reliquary', 'medieval'],
    pop: 40, niche: false,
    vd: { shape: 'bold figurative cells pressed to panel edges', line: 'thick gilt contours enclosing color', composition: 'hieratic rows of figures, dense narrative registers', texture: 'vitreous pool against warm gilt line' },
    typ: { display: 'inscribed Latin bands around reliquaries', body: 'n/a — applied object art', notes: 'donor names often chiseled into the copper ground' },
    lit: { quality: 'candle-glint on glass and gilt', temperature: 'warm', shadow: 'deep cells read as dark wells' },
    ui: { background: 'copper-brown field', surface: 'blue enamel tiles', components: 'gilt-outlined emblem buttons', motion: 'steady solemn fades' },
  },
  {
    n: 'Plique-à-jour', a: ['Plique a jour', 'plique-à-jour enamel', 'backless enamel', 'daylight enamel'],
    cat: 'Material & Surface', c: 'Backless translucent enamel', e: 'regional_tradition',
    o: 'France & Norway (Art Nouveau apex)', g: 'France, Norway, United States, Japan (Ando cloisonné)', p: '19th century revival-present (antique precedents)', era: 'Art Nouveau Europe',
    sum: 'Enamel without a backing: translucent paste fired in open cells glows like stained glass — the fragile signature of Art Nouveau jewelry by Lalique and Tiffany.',
    desc: 'Plique-à-jour ("letting in daylight") is enamel without a backing: translucent glass paste is fired in open cells — pierced from sheet, etched, or built of fine wire — so finished panels glow like stained glass. Revived by 19th-century French and Norwegian goldsmiths, it became Art Nouveau\'s signature: René Lalique\'s insect wings and orchid petals, Tiffany\'s enamel vessels. Fragile and laborious, it remains the most delicate enamel craft, glowing between gold wires like fixed watercolor.',
    col: [{ h: '#79b791', n: 'luminous green' }, { h: '#d9a441', n: 'window amber' }, { h: '#8e7cc3', n: 'translucent violet' }, { h: '#9ec5e8', n: 'sky cell blue' }, { h: '#c9a227', n: 'wire gold' }],
    m: ['gold or silver cell frameworks', 'translucent enamel frit', 'temporary mica or foil backing', 'fine jeweler\'s saws'],
    tx: ['stained-glass glow', 'pooled thin vitreous film', 'wire-suspended cell edge'],
    obj: ['insect-wing brooches and corsage ornaments', 'orchid and iris pendants', 'enamel vases', 'Norwegian silver brooches'],
    ex: ['René Lalique plique-à-jour jewels (Calouste Gulbenkian Museum, Lisbon)', 'Tiffany plique-à-jour enamel vases', 'Norwegian Tostrup and David-Andersen silver brooches'],
    inf: ['Art Nouveau jewelry', 'stained glass', 'cloisonné enamel', 'Norwegian silver revival'], rel: ['Art Nouveau', 'Shippo Cloisonné', 'Viana Heart Filigree', 'Champlevé Enamel'],
    src: [{ n: 'Wikipedia — Plique-à-jour', u: 'https://en.wikipedia.org/wiki/Plique-%C3%A0-jour', t: 'B' }, { n: 'The Metropolitan Museum of Art — Art Nouveau jewelry', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['enamel', 'translucent', 'art nouveau', 'lalique', 'jewelry', 'stained glass'],
    pop: 39, niche: true,
    vd: { shape: 'organic petal and wing cells, sinuous outlines', line: 'hair-fine wire contour', composition: 'whiplash asymmetry, single luminous motif', texture: 'glass glow between metal veins' },
    typ: { display: 'n/a — applied object art', body: 'n/a', notes: 'maker marks punched on wire frames only' },
    lit: { quality: 'transmitted light through thin glass', temperature: 'cool-warm mix per cell', shadow: 'none — the panel is its own light source' },
    ui: { background: 'ivory light field', surface: 'glowing translucent panels', components: 'wire-contour icon buttons', motion: 'breathing luminance pulses' },
  },
  {
    n: 'Bidri Ware', a: ['Bidriware', 'Bidri work', 'Bidar metalwork'],
    cat: 'Material & Surface', c: 'Silver-inlaid blackened alloy', e: 'regional_tradition',
    o: 'Bidar, Deccan, India', g: 'India (Bidar, Hyderabad, Lucknow, Purnia)', p: '14th century-present', era: 'Bahmani & Deccan sultanates to present',
    sum: 'Deccan craft of silver (sometimes gold or brass) inlaid into cast zinc-copper alloy, then blackened with a soil chemistry that leaves only the inlay luminous.',
    desc: 'Bidriware is cast from a dark zinc-copper alloy, engraved or inlaid with silver sheet and wire — sometimes brass — then painted with a paste of soil and ammonium chloride that blackens the base alloy while leaving the inlay bright silver. Developed at Bidar in the 14th-century Bahmani sultanate, it flourished under the Deccan sultanates on huqqa bases and pan boxes; Bidar workshops still practice the GI-tagged craft today. The look is stark: luminous silver arabesque on ink-black metal.',
    col: [{ h: '#26292e', n: 'bidri black' }, { h: '#c9ced6', n: 'inlaid silver' }, { h: '#b08d3f', n: 'brass accent' }, { h: '#4a4e55', n: 'cast zinc gray' }, { h: '#3a3540', n: 'oxidized violet cast' }],
    m: ['zinc-copper alloy ingots', 'silver sheet and wire', 'chisels and hammers for zarnishan inlay', 'bidar soil and ammonium chloride blackening paste'],
    tx: ['ink-black matte ground', 'raised silver line', 'burnished mixed-metal plane'],
    obj: ['huqqa (hookah) bases', 'paan-dan betel boxes', 'rosewater sprinklers', 'ashtrays and bowls', 'modern award trophies'],
    ex: ['Bidar huqqa bases with silver zarnishan inlay', 'Mughal-era paan boxes (Salar Jung Museum, Hyderabad)', 'GI-tagged Bidri craft of contemporary Bidar workshops'],
    inf: ['Deccan sultanate courts', 'Islamic metal inlay', 'Persian damascening'], rel: ['Pamor Damascene', 'Hutsul Wood and Metal Inlay', 'Islamic geometric patterns', 'Zuni inlay jewelry', 'Niello Inlay'],
    src: [{ n: 'Wikipedia — Bidriware', u: 'https://en.wikipedia.org/wiki/Bidriware', t: 'B' }, { n: 'The British Museum — Bidri collections', u: 'https://www.britishmuseum.org', t: 'A' }],
    tg: ['inlay', 'black metal', 'silver wire', 'deccan', 'islamic craft', 'india'],
    pop: 36, niche: true,
    vd: { shape: 'bulbous huqqa forms, low domed boxes', line: 'fine silver arabesque contour on black', composition: 'central medallion with scrolling field', texture: 'matte charcoal ground under bright metal line' },
    typ: { display: 'occasional Persian inscriptions in silver inlay', body: 'n/a — applied object art', notes: 'maker stamps impressed into the base alloy' },
    lit: { quality: 'single raking highlight on inlay', temperature: 'cool', shadow: 'black ground swallows all depth' },
    ui: { background: 'ink-black field', surface: 'silver-line ornament cards', components: 'wire-inlay outline buttons', motion: 'quiet line-draw reveals' },
  },
  {
    n: 'Niello Inlay', a: ['Niello', 'nielloware', 'niellated silver'],
    cat: 'Material & Surface', c: 'Black sulphide inlay on precious metal', e: 'historical',
    o: 'Mediterranean antiquity; Russia; Siam', g: 'Greece, Rome, Renaissance Italy, Russia, Thailand', p: 'Bronze Age-19th century; niche present practice', era: 'Antiquity to Renaissance',
    sum: 'Black fusible silver-lead-copper sulphide melted into engraved lines on silver or gold — drawing fixed in metal, from Mycenaean daggers to Thai nielloware.',
    desc: 'Niello is a black fusible alloy of silver, copper, lead and sulphur, melted into engraved lines on silver or gold and polished flush so the drawing reads as dark inlay. From Mycenaean dagger blades to Renaissance goldsmiths\' trial pieces and Russian and Thai nielloware, it gives metalwork the gravity of engraving with the permanence of inlay. Antonio Pollaiuolo\'s celebrated niello plates spread the style through Renaissance workshops. Today niello survives mainly in Thai jewelry and restoration.',
    col: [{ h: '#d9dde3', n: 'polished silver' }, { h: '#17181c', n: 'niello black' }, { h: '#22242c', n: 'blue-black line' }, { h: '#8b9097', n: 'warm gray tone' }, { h: '#c9a227', n: 'gold accent' }],
    m: ['silver or gold plate', 'silver-copper-lead sulphide niello', 'burins and gravers', 'planishing and polishing tools'],
    tx: ['flush black line in bright metal', 'soft engraved shadow', 'mirror-polish contrast'],
    obj: ['ceremonial dagger blades', 'silver boxes and covers', 'liturgical plate', 'Thai niello bowls and trays', 'Renaissance plaquettes'],
    ex: ['Mycenaean niello-inlaid daggers (National Archaeological Museum, Athens)', 'Antonio Pollaiuolo niello plates (Museo Nazionale del Bargello)', 'Russian and Thai niello silver boxes'],
    inf: ['Mycenaean arms decoration', 'Renaissance goldsmith drawing', 'Thai nielloware', 'Russian silverwork'], rel: ['Pamor Damascene', 'Hutsul metalwork', 'Granulation', 'Hopi silver overlay jewelry'],
    src: [{ n: 'Wikipedia — Niello', u: 'https://en.wikipedia.org/wiki/Niello', t: 'B' }, { n: 'The British Museum — niello metalwork', u: 'https://www.britishmuseum.org', t: 'A' }],
    tg: ['niello', 'silver', 'inlay', 'engraving', 'renaissance', 'siamese'],
    pop: 35, niche: true,
    vd: { shape: 'figure-drawing carried entirely in line', line: 'confident dark contour, engraver\'s hand visible', composition: 'central scene in a lined silver field', texture: 'hard bright metal against velvet black line' },
    typ: { display: 'n/a — applied object art', body: 'n/a', notes: 'occasional inscriptions engraved and filled black' },
    lit: { quality: 'specular silver with light-absorbing lines', temperature: 'cool', shadow: 'line-work itself is the shadow' },
    ui: { background: 'bright silver field', surface: 'black-line drawing panels', components: 'inset-line icon buttons', motion: 'etching-line draw-ins' },
  },
  {
    n: 'Granulation', a: ['Gold granulation', 'granulated goldwork'],
    cat: 'Material & Surface', c: 'Gold-sphere surface decoration', e: 'historical',
    o: 'Etruria & the ancient Near East', g: 'Sumer, Egypt, Greece, Etruria, Colchis; 19th-c. Rome revival', p: '3rd millennium BC-1st century AD; revived 19th century', era: 'Etruscan Orientalizing apex',
    sum: 'Ancient goldsmithing that fixes thousands of tiny gold spheres onto gold in cones, waves and rows — the lost caviar texture of Etruscan jewelry.',
    desc: 'Granulation decorates gold with thousands of tiny spheres, attached by colloidal or hard soldering in patterns of cones, waves and rows. Sumerian and Etruscan goldsmiths brought it to unsurpassed fineness — Etruscan bullae and fibulae of the 7th-6th centuries BC remain technical wonders — and the skill lapsed for centuries until 19th-century revivalists and the Castellani workshop reverse-engineered it. Its texture is unmistakable: the gold surface breaks into tactile, light-catching caviar.',
    col: [{ h: '#d4af37', n: 'high-karat gold' }, { h: '#9a7b1e', n: 'shadow gold' }, { h: '#c98f2e', n: 'reddish alloy gold' }, { h: '#e8e4da', n: 'electrum pale' }, { h: '#5c4632', n: 'buried patina' }],
    m: ['high-karat gold sheet and wire', 'gold granules drawn from wire droplets', 'colloidal solder (copper salts)', 'charcoal and jeweler\'s benches'],
    tx: ['caviar-sphere relief', 'soldered halo seams', 'row-on-row ripple'],
    obj: ['bullae and fibulae', 'earring pairs with pyramidal granulation', 'necklace spangles', 'archaeological-revival jewelry'],
    ex: ['Etruscan gold bullae and fibulae (Museo Nazionale Etrusco di Villa Giulia)', 'Sumerian granulated gold ornaments from the Royal Cemetery of Ur', 'Castellani archaeological-revival granulated jewelry (British Museum)'],
    inf: ['Etruscan goldwork', 'Orientalizing period', 'archaeological-revival jewelry'], rel: ['Mixtec Gold and Turquoise Mosaics', 'Filigree Lanterns', 'Egyptian Revival', 'Niello Inlay', 'Viana Heart Filigree'],
    src: [{ n: 'Wikipedia — Granulation (jewellery)', u: 'https://en.wikipedia.org/wiki/Granulation_(jewellery)', t: 'B' }, { n: 'The British Museum — ancient goldwork', u: 'https://www.britishmuseum.org', t: 'A' }],
    tg: ['gold', 'granules', 'etruscan', 'ancient jewelry', 'archaeological revival'],
    pop: 42, niche: false,
    vd: { shape: 'geometric registers built from spheres', line: 'rows of dots replacing drawn contour', composition: 'zoned bands of cones and waves on gold fields', texture: 'endless tactile micro-bumps' },
    typ: { display: 'n/a — applied object art', body: 'n/a', notes: 'no lettering tradition; owner marks rare' },
    lit: { quality: 'dense micro-highlights on every sphere', temperature: 'warm', shadow: 'halo shadows beneath each granule' },
    ui: { background: 'deep gold field', surface: 'granule-textured cards', components: 'stippled gold buttons', motion: 'sparkle scatter transitions' },
  },
  {
    n: 'Mokume-gane', a: ['Mokume', 'mokumegane', 'wood-grain metal', '木目金'],
    cat: 'Material & Surface', c: 'Laminated mixed-metal wood-grain', e: 'regional_tradition',
    o: 'Akita, Japan', g: 'Japan; worldwide studio metalsmithing after 1970', p: '17th century-present', era: 'Edo Japan to contemporary craft',
    sum: 'Laminated sheets of contrasting metals diffusion-bonded, then carved and forged so swirling burl-like strata surface — invented for Japanese sword fittings.',
    desc: 'Mokume-gane ("wood-grain metal") diffusion-bonds laminated sheets of contrasting non-ferrous metals — copper, silver, shakudo, shibuichi, gold — then carves, punches and forges the block so swirling, burl-like strata surface like a polished knot of timber. Sword-fitting master Denbei Shoami developed it in 17th-century Akita; Edo fittings exploited it, and the technique migrated to Western studio jewelry in the 1970s. Every billet is unrepeatable: marbled metal, no paint, dye or solder lines.',
    col: [{ h: '#b06a4a', n: 'copper stratum' }, { h: '#cfd4da', n: 'silver stratum' }, { h: '#26323e', n: 'shakudo stratum' }, { h: '#a89a8e', n: 'shibuichi stratum' }, { h: '#d4af37', n: 'gold stratum' }],
    m: ['stacked non-ferrous metal billets', 'further-clamp diffusion bonding forge', 'carving punches and files', 'patination baths'],
    tx: ['swirling layered strata', 'carved trench exposing underlayers', 'flux-seamless lamination'],
    obj: ['sword fittings (fuchi-kashira, kozuka)', 'contemporary wedding rings', 'brooches and pendants', 'vessel and holloware panels'],
    ex: ['Sword fittings of Shoami Denbei (Akita, 17th c.)', 'Edo-period fuchi-kashira with mokume plates', 'Pijanowski-era American studio-metalsmith mokume (1970s)'],
    inf: ['Japanese sword fittings', 'diffusion bonding', 'American studio craft movement'], rel: ['Shakudō & Irogane Patination', 'Kintsugi', 'Pamor Damascene', 'Maki-e'],
    src: [{ n: 'Wikipedia — Mokume-gane', u: 'https://en.wikipedia.org/wiki/Mokume-gane', t: 'B' }, { n: 'The Metropolitan Museum of Art — Japanese sword fittings', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['laminated metal', 'wood grain', 'sword fitting', 'eddo', 'alloy', 'marble metal'],
    pop: 46, niche: false,
    vd: { shape: 'organic burl swirls, no fixed motif', line: 'erupting strata contours, never repeated', composition: 'full-surface flow cut by carved windows', texture: 'polished marbled metal, warm-cold interleaved' },
    typ: { display: 'n/a — applied object art', body: 'n/a', notes: 'smith marks stamped on reverse of fittings' },
    lit: { quality: 'soft broad reflections across strata', temperature: 'mixed — copper warm, shakudo cool', shadow: 'layer edges self-shade like contour lines' },
    ui: { background: 'warm parchment neutral', surface: 'marbled metal gradient panels', components: 'strata-swirl pill buttons', motion: 'liquid metal morph transitions' },
  },
  {
    n: 'Shakudō & Irogane Patination', a: ['Shakudo', 'irogane patination', '赤銅', 'shakudo zogan'],
    cat: 'Material & Surface', c: 'Japanese patinated copper-gold alloy family', e: 'regional_tradition',
    o: 'Japan', g: 'Japan (Kyoto, Edo workshop traditions)', p: 'Nara-Edo apex; present practice', era: 'Edo sword-fitting culture',
    sum: 'Japanese copper-gold alloy that patinates to a blue-black sheen in plum-vinegar baths — the nocturne ground of Edo sword fittings and Meiji metalwork.',
    desc: 'Shakudo is a Japanese alloy of copper with a few percent gold that, after pickling in plum-vinegar baths (rakusho), develops a sumptuous blue-black patina; its sibling irogane metals — shibuichi, kuromido — patinate to graded grays, plums and browns. Edo-period sword-fitting masters inlaid gold and silver against these dark fields; Meiji workshops tuned the palette to a science for export metalwork. The aesthetic is nocturne: whisper-quiet metal whose color lives in oxidation, not pigment.',
    col: [{ h: '#232b36', n: 'shakudo blue-black' }, { h: '#3d2f3f', n: 'plum patina' }, { h: '#9aa0a6', n: 'shibuichi gray' }, { h: '#d4af37', n: 'inlaid gold' }, { h: '#a5643d', n: 'raw copper base' }],
    m: ['copper-gold shakudo alloy', 'shibuichi and kuromido irogane alloys', 'rakusho plum-vinegar patination bath', 'gold and silver inlay wire'],
    tx: ['velvety oxide skin', 'mirror-burnished patina', 'raised inlay against dark field'],
    obj: ['sword fittings (menuki, kozuka)', 'Meiji export boxes and plaques', 'contemporary patinated jewelry', 'knife and pen fittings'],
    ex: ['Edo kinko sword fittings with gold zogan on shakudo', 'Meiji export metalwork shown at world expositions', 'Contemporary irogane patinated knives and jewelry'],
    inf: ['irogane alloy science', 'zogan metal inlay', 'Meiji export crafts', 'sword-fitting kinko schools'], rel: ['Mokume-gane', 'Maki-e', 'Kintsugi'],
    src: [{ n: 'Wikipedia — Shakudō', u: 'https://en.wikipedia.org/wiki/Shakud%C5%8D', t: 'B' }, { n: 'Wikipedia — Irogane', u: 'https://en.wikipedia.org/wiki/Irogane', t: 'B' }, { n: 'The Metropolitan Museum of Art — Japanese metalwork', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['patina', 'alloy', 'blue black', 'sword fitting', 'zogan', 'eddo'],
    pop: 37, niche: true,
    vd: { shape: 'small-scale fittings as miniature canvases', line: 'gold contour lines floating on blackness', composition: 'isolated emblems in deep dark fields', texture: 'soft oxide depth with hard metal accents' },
    typ: { display: 'n/a — applied object art', body: 'n/a', notes: 'inscriptions in gold occur on kozuka hafts' },
    lit: { quality: 'low diffuse sheen, sparing specular points', temperature: 'cool', shadow: 'patina is itself living shadow' },
    ui: { background: 'blue-black gradient field', surface: 'patinated metal cards', components: 'gold-inlay outline buttons', motion: 'slow oxidize-shift color drifts' },
  },
  {
    n: 'Maki-e', a: ['Makie', 'gold-sprinkled lacquer', '蒔絵', 'hira/taka/togidashi maki-e'],
    cat: 'Material & Surface', c: 'Gold-powder lacquer decoration', e: 'regional_tradition',
    o: 'Japan', g: 'Japan (Kyoto, Edo/Tokyo, Wajima, Takamatsu)', p: 'Heian period-present', era: 'Heian to Edo Japan',
    sum: 'Gold and silver powder sprinkled onto wet urushi lacquer and polished into black depth — the pinnacle technique of Japanese lacquer decoration.',
    desc: 'Maki-e sprinkles gold and silver powder through bamboo tubes and funnels onto wet urushi lacquer, then re-coats and polishes until the design floats inside black depth. Flat hiramaki-e, raised takamaki-e and flush-ground togidashi maki-e grade the technique from whisper to relief. Court ateliers codified it in the Heian period; Rinpa masters Ogata Korin and Hon\'ami Koetsu made it painterly. Still practiced in Wajima and Kyoto, it remains the pinnacle of Japanese lacquer decoration.',
    col: [{ h: '#131313', n: 'urushi black' }, { h: '#d4af37', n: 'sprinkled gold' }, { h: '#b08d3f', n: 'muted gold' }, { h: '#b03a2e', n: 'vermilion accent' }, { h: '#c9ced6', n: 'silver powder' }],
    m: ['urushi (raw Japanese lacquer)', 'gold and silver powders (kinpaku, marubaku grades)', 'bamboo sprinkling tubes and funnels', 'polishing charcoal and deerhair brushes'],
    tx: ['powder-grain glitter field', 'buried-then-burnished flush image', 'raised relief rims'],
    obj: ['writing boxes (suzuribako)', 'tea caddies and inro', 'comb and kogai sets', 'modern fountain pens'],
    ex: ['Ogata Korin "Eight Bridges" maki-e writing box (National Treasure)', 'Heian-period maki-e sutra boxes and furnishings', 'Wajima and Kyoto maki-e of living workshops'],
    inf: ['urushi lacquer craft', 'Rinpa design', 'Kintsugi repair aesthetics', 'Heian court art'], rel: ['Wajima Lacquer', 'Kintsugi', 'Chinoiserie Panel Lacquer Painting', 'Chinese Style Lacquer', 'Shakudō & Irogane Patination'],
    src: [{ n: 'Wikipedia — Maki-e', u: 'https://en.wikipedia.org/wiki/Maki-e', t: 'B' }, { n: 'The Metropolitan Museum of Art — Japanese lacquer', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['lacquer', 'gold powder', 'urushi', 'rinpa', 'japan', 'writing box'],
    pop: 45, niche: false,
    vd: { shape: 'flowing Rimpa motifs — irises, waves, gourds', line: 'gold-dust contour dissolving into ground', composition: 'asymmetric corners, vast black margins', texture: 'granular gold rising from liquid-deep black' },
    typ: { display: 'calligraphic poems in gold dust on boxes', body: 'n/a', notes: 'poet-artist collaborations pair verse with imagery' },
    lit: { quality: 'pointillist gold glitter on deep black', temperature: 'warm gold over cool void', shadow: 'ground itself is infinite shadow' },
    ui: { background: 'lacquer black field', surface: 'gold-dust illustrated cards', components: 'gold-sprinkle buttons and inro-style tags', motion: 'dust-drift particle reveals' },
  },
  {
    n: 'Millefiori', a: ['Murrine', 'millefiori glass', 'mosaic glass', 'thousand-flowers glass'],
    cat: 'Texture & Material Study', c: 'Mosaic-cane glass', e: 'regional_tradition',
    o: 'Alexandria & Venice', g: 'Roman Mediterranean, Murano, French paperweight centers', p: '1st century BC-present', era: 'Roman antiquity to Murano revival',
    sum: 'Slices of multicolored glass canes — murrine with stars, flowers and faces running their length — fused into endless patterned fields of color.',
    desc: 'Millefiori ("a thousand flowers") fuses slices of mosaic glass canes — murrine — each extruded with a star, flower or face running its whole length, so cut cross-sections tile into endless patterned fields. Alexandrian and Roman glassmakers made mosaic bowls from the 1st century BC; Venice revived and renamed the craft, and 19th-century Murano houses and French paperweight makers brought canes to jewel-like precision. Murano furnaces still pull murrine canes today.',
    col: [{ h: '#c0392b', n: 'cane red' }, { h: '#1f4e8c', n: 'cane cobalt' }, { h: '#e8b62a', n: 'cane yellow' }, { h: '#2e8b57', n: 'cane green' }, { h: '#f5f1e6', n: 'casing white' }],
    m: ['colored glass canes (murrine)', 'glass furnace and punties', 'molds for fusing slices', 'clear gathering glass'],
    tx: ['glassy tile collage', 'cane cross-section rings', 'fused-slice seams'],
    obj: ['mosaic bowls and dishes', 'paperweights', 'beads for trade and jewelry', 'Venetian table glass'],
    ex: ['Roman mosaic-glass bowls (1st c. BC-1st c. AD)', 'Murano murrine vessels of the Moretti and Toso workshops', 'French millefiori paperweights (Baccarat, Clichy, St. Louis)'],
    inf: ['Roman glass industry', 'Venetian glass revival', 'paperweight craft'], rel: ['Islamic Glassware', 'Byzantine Revival', 'Micromosaic', 'Neo-Byzantine'],
    src: [{ n: 'Wikipedia — Millefiori', u: 'https://en.wikipedia.org/wiki/Millefiori', t: 'B' }, { n: 'The British Museum — Roman mosaic glass', u: 'https://www.britishmuseum.org', t: 'A' }],
    tg: ['glass', 'murrine', 'canes', 'murano', 'roman', 'paperweight'],
    pop: 48, niche: false,
    vd: { shape: 'roundels and star cells tiling edge to edge', line: 'cane-drawn inner contours, math-precise', composition: 'all-over repeat, no single focal point', texture: 'hard glossy color islands in clear glass' },
    typ: { display: 'n/a — applied object art', body: 'n/a', notes: 'occasional signature canes with lettering drawn in the glass' },
    lit: { quality: 'transmitted and refracted color', temperature: 'warm', shadow: 'internal cane shadows float in the mass' },
    ui: { background: 'clear glass tint', surface: 'murrine mosaic tile panels', components: 'cane-slice dot buttons', motion: 'kaleidoscope rotate reveals' },
  },
  {
    n: 'Scagliola', a: ['Scagliola art', 'scagliola marble work', 'plaster marbling'],
    cat: 'Texture & Material Study', c: 'Gypsum imitation marble', e: 'historical',
    o: 'Carpi & Tuscany, Italy', g: 'Italy, Britain, America', p: '17th century-early 20th century', era: 'Italian Baroque to Victorian',
    sum: 'Gypsum-plaster, glue and pigment worked into convincing imitation of breccia, porphyry and marbles — Baroque altars and Victorian columns at a fraction of the weight.',
    desc: 'Scagliola imitates precious marble with humble materials: selenite gypsum plaster mixed with hide glue and pigments, poured and figured into slabs, then ground and polished to a stone-deep luster. Italian friars and artisans perfected it in the 17th century for altar frontals and inlay that outdid quarried breccia and porphyry; Georgian and Victorian builders adopted it for columns and chimneypieces where real marble was too costly or heavy. American capitols carried it into the 1870s.',
    col: [{ h: '#e6dcc8', n: 'cream marble ground' }, { h: '#a05a3a', n: 'breccia sienna' }, { h: '#2e2a26', n: 'vein black' }, { h: '#7a8450', n: 'verde accent' }, { h: '#c78a8a', n: 'rose mottle' }],
    m: ['selenite gypsum plaster', 'hide glue binder', 'dry pigment powders', 'grinding and polishing stones'],
    tx: ['stone-deep polish', 'figured vein and mottle', 'inlaid contrasting patches'],
    obj: ['altar frontals and tabernacle surrounds', 'corridor and hall columns', 'chimneypieces', 'table and console tops'],
    ex: ['Baroque scagliola altar frontals of Carpi and Volterra (17th-18th c.)', 'Scagliola columns of the Michigan State Capitol (1870s)', 'Victorian scagliola chimneypieces in English country houses'],
    inf: ['Baroque church decoration', 'faux-marble painting', 'gypsum craft'], rel: ['Venetian plaster', 'Stucco veneziano', 'Marquetry and Intarsia', 'Graining', 'Neoclassical'],
    src: [{ n: 'Wikipedia — Scagliola', u: 'https://en.wikipedia.org/wiki/Scagliola', t: 'B' }, { n: 'Victoria & Albert Museum — scagliola and plasterwork', u: 'https://www.vam.ac.uk', t: 'A' }],
    tg: ['faux marble', 'plaster', 'baroque', 'imitation stone', 'victorian', 'columns'],
    pop: 34, niche: true,
    vd: { shape: 'slab rectangles and architectural orders', line: 'drawn veins wandering like geological line', composition: 'symmetric mirrored veining across columns', texture: 'cool polish hiding warm gypsum body' },
    typ: { display: 'occasional inscribed faux-stone cartouches', body: 'n/a — architectural surface', notes: 'dates and donors cut into imitation stone panels' },
    lit: { quality: 'soft even sheen, subsurface glow', temperature: 'warm', shadow: 'veins pool soft gray shadow' },
    ui: { background: 'cream marble wash', surface: 'veined slab panels', components: 'breccia-textured buttons', motion: 'slow vein-growth transitions' },
  },
  {
    n: 'Cosmatesque', a: ['Cosmati work', 'opus Alexandrinum', 'Cosmatesque pavement'],
    cat: 'Texture & Material Study', c: 'Marble mosaic pavement inlay', e: 'historical',
    o: 'Rome & Lazio', g: 'Central Italy; Westminster, England', p: '12th-14th century', era: 'Medieval Rome',
    sum: 'Medieval Roman marble mosaic slicing ancient porphyry and serpentine into discs and triangles set in quincunx geometry — imperial spolia as church pavement.',
    desc: 'Cosmatesque is the medieval Roman marble mosaic of floors, pulpits and cloisters: discs of porphyry and serpentine sliced from ancient columns, set with white marble triangles into quincunx and interlace geometry, edged by bands of glittering glass paste. Named for the Cosmati family of marble workers active in the 12th-13th centuries, it recycled imperial Rome into church pavement. Its greatest survival is the 1268 Westminster Abbey pavement before the high altar.',
    col: [{ h: '#6b2d4a', n: 'porphyry purple' }, { h: '#2f4f3a', n: 'serpentine green' }, { h: '#ece7dc', n: 'white marble' }, { h: '#d9a441', n: 'giallo antico' }, { h: '#b08d3f', n: 'glass paste gold' }],
    m: ['salvaged porphyry and serpentine columns', 'white Luna marble', 'colored glass paste tesserae', 'lime mortar beds'],
    tx: ['polished stone disc sheen', 'tight geometric joints', 'mosaic band sparkle'],
    obj: ['church pavements and thresholds', 'ambones (pulpits)', 'cloister walk floors', 'tomb slabs and episcopal thrones'],
    ex: ['Westminster Abbey Cosmati pavement (1268-69)', 'Cosmati cloister of San Giovanni in Laterano, Rome', 'Santa Maria in Cosmedin pavement, Rome'],
    inf: ['spolia reuse', 'Byzantine mosaic', 'Roman marble trade', 'medieval geometry'], rel: ['Pietra dura', 'Byzantine Revival', 'Neo-Byzantine', 'Romanesque Revival', 'Gothic architecture'],
    src: [{ n: 'Wikipedia — Cosmatesque', u: 'https://en.wikipedia.org/wiki/Cosmatesque', t: 'B' }, { n: 'Westminster Abbey — Cosmati pavement', u: 'https://www.westminster-abbey.org', t: 'A' }],
    tg: ['marble mosaic', 'spolia', 'porphyry', 'medieval rome', 'pavement', 'geometry'],
    pop: 33, niche: true,
    vd: { shape: 'circles, quincunx squares, interlaced bands', line: 'rigid geometry enclosing stone roundels', composition: 'bounded cosmological diagram spreading floor-wide', texture: 'cool polished stone against gritty matrix' },
    typ: { display: 'medieval Latin inscriptions in pavement bands', body: 'n/a — architectural surface', notes: 'Westminster pavement carries a dated Latin text on Henry III' },
    lit: { quality: 'overhead daylight brightening polished discs', temperature: 'cool', shadow: 'thin dark joints netting the floor' },
    ui: { background: 'pale limestone field', surface: 'quincunx geometric tiles', components: 'stone-roundel buttons', motion: 'orbiting concentric motifs' },
  },
  {
    n: 'Micromosaic', a: ['Micro-mosaic', 'Roman micromosaic', 'smalti filato work'],
    cat: 'Texture & Material Study', c: 'Micro-tessera glass picture mosaic', e: 'historical',
    o: 'Rome (Vatican workshops)', g: 'Italy, Grand Tour Europe, Russia', p: '18th-19th century apex', era: 'Neoclassical Grand Tour',
    sum: 'Pictures built from glass tesserae under a millimetre wide, pulled from colored rods — the Vatican craft behind Grand Tour snuffboxes, tables and jewels.',
    desc: 'Micromosaic draws pictures with thousands of glass tesserae under a millimetre wide, cut from slender colored rods (smalti filati) and packed into wax or cement on copper panels. The Vatican\'s St. Peter\'s workshop perfected the rods in the 18th century; Roman studios turned out Grand Tour snuffboxes, table tops and jewelry copying paintings and antiquities, and Giacomo Raffaelli\'s tables toured the courts of Europe. At close range the surfaces ripple like woven glass.',
    col: [{ h: '#1f3a93', n: 'smalti ultramarine' }, { h: '#7fb2d9', n: 'filato sky' }, { h: '#ece7dc', n: 'dove ivory' }, { h: '#b03a2e', n: 'tessera red' }, { h: '#b08d3f', n: 'gilt glass band' }],
    m: ['colored glass rods (smalti filati)', 'tweezers and micro-cutters', 'copper panels with wax or cement beds', 'Vatican kiln-drawn color blanks'],
    tx: ['woven-glass ripple', 'micro-tessera grid', 'enamel-rope contour lines'],
    obj: ['snuffbox lids and stamp boxes', 'table tops and plaques', 'brooches and parure jewelry', 'papal and view scenes'],
    ex: ['Giacomo Raffaelli micromosaic table with Pliny doves (Hermitage Museum)', 'St. Peter\'s Basilica altarpiece mosaics (Vatican Mosaic Studio)', 'Grand Tour micromosaic jewelry and snuffboxes (V&A)'],
    inf: ['Vatican mosaic studio', 'Grand Tour collecting', 'Byzantine mosaic', 'hardstone revival'], rel: ['Pietra dura', 'Millefiori', 'Neoclassical', 'Byzantine Revival'],
    src: [{ n: 'Wikipedia — Micromosaic', u: 'https://en.wikipedia.org/wiki/Micromosaic', t: 'B' }, { n: 'Victoria & Albert Museum — micromosaics', u: 'https://www.vam.ac.uk', t: 'A' }],
    tg: ['mosaic', 'smalti', 'grand tour', 'vatican', 'rome', 'jewelry'],
    pop: 40, niche: false,
    vd: { shape: 'framed picture vignettes, oval and rectangular', line: 'tessera rows tracing drawn contour', composition: 'central copy after a famous painting or view', texture: 'minute glass sparkle in dense grid' },
    typ: { display: 'view captions and titles in tiny tesserae', body: 'n/a — applied object art', notes: 'workshop marks stamped on copper reverses' },
    lit: { quality: 'close-view glass glitter under lamp light', temperature: 'mixed by subject', shadow: 'tessera depth speckles mid-tones' },
    ui: { background: 'deep ultramarine field', surface: 'mosaic picture cards', components: 'micro-tile bordered buttons', motion: 'pixel-assemble reveals' },
  },
  {
    n: 'Water Gilding', a: ['Water gilding', 'bole gilding', 'gesso-and-bole gilding', 'traditional water gilding'],
    cat: 'Material & Surface', c: 'Gesso-bole burnished gold leaf', e: 'regional_tradition',
    o: 'Italy & France (European tradition)', g: 'Europe, Byzantine sphere, Americas', p: 'Medieval-present', era: 'Medieval to contemporary gilding',
    sum: 'Gold leaf laid over gesso and red bole clay, wet, then burnished with agate until raised passages shine like mirrors — the deep luster of panel painting and frames.',
    desc: 'Water gilding lays gold leaf onto a slab of gesso covered with red bole clay, wetting each leaf so it clings, then burnishing with an agate stone until raised passages shine like mirrors while recessed bole keeps a matte, honeyed glow. It is the gilding of gold-ground Sienese and Florentine panel paintings, of carved Renaissance altarpieces, frames and Louis XIV furniture. The technique is alive in gilding and conservation workshops; nothing else gives gold so deep a luster on wood.',
    col: [{ h: '#d4af37', n: 'burnished leaf gold' }, { h: '#f0df9e', n: 'agate highlight' }, { h: '#8a3b2a', n: 'red bole clay' }, { h: '#ece7dc', n: 'gesso ground' }, { h: '#8c6d1f', n: 'matte shadow gold' }],
    m: ['rabbit-skin glue gesso', 'red Armenian bole clay', 'gold leaf books', 'agate burnishers and squirrel brushes'],
    tx: ['mirror burnish on raised zones', 'matte bole recesses', 'leaf-seam ghosting'],
    obj: ['gold-ground panel paintings', 'carved altar-pieces and frames', 'gilded boiserie and furniture', 'mirror and console frames'],
    ex: ['Gold-ground panels of Duccio and the Giotto-era Sienese school', 'Carved and gilded Renaissance altar frames', 'Gilded Louis XIV-XVI boiserie at Versailles'],
    inf: ['panel painting grounds', 'frame and furniture gilding', 'conservation craft', 'bole burnishing'], rel: ['Verre Églomisé', 'Egyptian Revival', 'Neoclassical', 'Aesthetic Movement interior', 'Gothic Revival'],
    src: [{ n: 'Wikipedia — Gilding', u: 'https://en.wikipedia.org/wiki/Gilding', t: 'B' }, { n: 'Victoria & Albert Museum — gilded furniture and frames', u: 'https://www.vam.ac.uk', t: 'A' }],
    tg: ['gold leaf', 'burnish', 'bole', 'frame', 'panel painting', 'gesso'],
    pop: 50, niche: false,
    vd: { shape: 'carved relief with punched ornament grounds', line: 'raised ridge catching burnish light', composition: 'halo and field gilding around painted centers', texture: 'mirror gold drifting into honeyed matte' },
    typ: { display: 'n/a — architectural and object surface', body: 'n/a', notes: 'inscriptions on gilded spines are blind-tooling, a parallel trade' },
    lit: { quality: 'two-state sheen — mirror highlights, matte fields', temperature: 'warm', shadow: 'recessed bole glows dull ember' },
    ui: { background: 'warm parchment field', surface: 'burnished gold trim cards', components: 'gold-leaf pill buttons', motion: 'sheen-sweep highlight transitions' },
  },
  {
    n: 'Graining', a: ['Faux bois graining', 'wood graining', 'grained joinery', 'feather graining'],
    cat: 'Texture & Material Study', c: 'Painted wood imitation', e: 'historical',
    o: 'Britain & America', g: 'Britain, Ireland, North America, Australia', p: '18th-early 20th century apex', era: 'Georgian & Victorian decorating trade',
    sum: 'Painted imitation of timber — combs, feathers and glazes turning cheap pine into oak, mahogany and rosewood — the Victorian decorating trade\'s master illusion.',
    desc: 'Graining is the painted imitation of timber: skilled decorators in oil glaze drag combs, feathers, rubber rollers and fitches over doors, wainscots and cheap pine to counterfeit oak, mahogany, rosewood and birds-eye maple, then harmonize and varnish. Victorian and Edwardian Britain grained everything from terrace-house doors to railway carriages, and the trade — with its tortoiseshell comb graining boxes — survived into conservation practice. It is honest joinery dressed in aristocratic clothes.',
    col: [{ h: '#8a6a42', n: 'grained oak' }, { h: '#4a2c24', n: 'imitation rosewood' }, { h: '#c9a875', n: 'stained pine' }, { h: '#5c4632', n: 'glaze umber' }, { h: '#b08d3f', n: 'varnish amber' }],
    m: ['oil color and japan glaze', 'rubber combs and rollers', 'feathers and fitch brushes', 'mastic varnish'],
    tx: ['dragged long grain', 'cathedral figure arching', 'comb-comb cross-band'],
    obj: ['terraced-house doors and staircase spindles', 'railway carriage panels', 'shopfitting and dado work', 'grained doors of public buildings'],
    ex: ['Victorian grained doors and staircases in British terraced housing', 'Grained woodwork in preserved Victorian railway carriages', 'Graining combs and trade tools in the V&A collections'],
    inf: ['faux painting', 'Scagliola', 'Victorian decorating trades', 'trompe-l\'œil'], rel: ['Scagliola', 'Venetian plaster', 'Victorian Polychrome', 'Georgian interior', 'Arts and Crafts Movement'],
    src: [{ n: 'Wikipedia — Graining', u: 'https://en.wikipedia.org/wiki/Graining', t: 'B' }, { n: 'Victoria & Albert Museum — decorating trades', u: 'https://www.vam.ac.uk', t: 'A' }],
    tg: ['faux wood', 'paint trade', 'victorian', 'glaze', 'illusion', 'interior'],
    pop: 32, niche: true,
    vd: { shape: 'board-true rectangles, grain running the length', line: 'combed striations and cathedral arches', composition: 'field-and-moulding logic of real joinery copied in paint', texture: 'glossy varnish over hand-dragged figure' },
    typ: { display: 'n/a — architectural surface', body: 'n/a', notes: 'maker and painter names occasionally inked on door edges' },
    lit: { quality: 'even daylight with varnish gloss points', temperature: 'warm', shadow: 'false grain self-shades like real relief' },
    ui: { background: 'warm pine tint', surface: 'grain-figure panel cards', components: 'wood-grain striped buttons', motion: 'brush-drag wipe reveals' },
  },
]
