/**
 * Rebuild wave — East Asia r1 (16 entries).
 * Solo-authored after sandbox rollback. Wikipedia titles batch-verified via
 * API (2026-09-14). Dedup-checked against existing-names.txt (1,011-state).
 */
export const ENTRIES: any[] = [
  {
    n: 'Origami', a: ['paper folding', 'oru-kami craft'],
    cat: 'Textile & Craft', c: 'Japanese paper folding', e: 'historical',
    o: 'Japan (with independent Chinese and European traditions)', g: 'Japan, global craft culture',
    p: '1600s-present (earlier ritual roots)', era: 'Edo etiquette to modern art form',
    sum: 'The Japanese art of folding uncut paper into cranes, frogs and geometric sculpture — geometry made by hand.',
    desc: 'Origami matured in Edo Japan as both etiquette (formal folded wrappers, noshi) and play, standardized in the wetfold? — no: in the classic sequence: valley and mountain folds turn a single square into a crane, frog, boat or box without cuts or glue. Twentieth-century folders — Akira Yoshizawa above all — invented wet-folding, diagram language and thousands of models, turning a pastime into a mathematical art with applications from airbag design to space telescopes. The crane, folded a thousand times, remains its symbol of wish and peace.',
    col: [{ h: '#f2ede2', n: 'washi cream' }, { h: '#c93636', n: 'crane red' }, { h: '#2b5db8', n: 'fold blue' }, { h: '#e8c14a', n: 'kami gold' }],
    m: ['kami paper', 'washi paper', 'foil-backed paper (modern)'],
    tx: ['crisp mountain creases', 'soft fiber translucency', 'sharp point geometry'],
    obj: ['orizuru cranes', 'folded gift wrappers', 'senbazuru thousand-crane strings', 'modular kusudama balls'],
    ex: ['Yoshizawa–Randlett diagram system', 'senbazuru memorial crane strands', 'wet-folded Yoshizawa animal studies'],
    inf: ['Edo etiquette folding', 'European napkin folding (parallel)', 'modern mathematical folding'], rel: ['Kirigami Paper Cutting', 'Ikebana', 'Washi Papermaking'],
    src: [{ n: 'Wikipedia — Origami', u: 'https://en.wikipedia.org/wiki/Origami', t: 'B' }, { n: 'The Metropolitan Museum of Art', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['paper', 'folding', 'japan', 'geometry', 'craft', 'crane'],
    pop: 58, niche: false,
    vd: { shape: 'polyhedral silhouettes from one uncut square', line: 'valley and mountain crease networks', composition: 'symmetry from pure fold sequence', texture: 'matte fiber with crisp ridge highlights' },
    typ: { display: 'diagram symbols as graphic language', body: 'step captions', notes: 'the fold diagram itself is a typography' },
    lit: { quality: 'clean table light', temperature: 'neutral-toned', shadow: 'creases cast hairline shadows' },
    ui: { background: 'washi cream', surface: 'crease-line frames', components: 'fold-arrow icons', motion: 'unfold-flip transitions' },
    par: 'Japanese craft arts',
  },
  {
    n: 'Ikebana', a: ['kadō', 'Japanese flower arrangement'],
    cat: 'Regional & Cultural Tradition', c: 'Japanese floral art', e: 'historical',
    o: 'Japan', g: 'Japan, global practice',
    p: '1400s-present', era: 'Muromachi ritual to modern schools',
    sum: 'Japanese flower arrangement as living sculpture: heaven, earth and humanity held in one stem-balance.',
    desc: 'Ikebana arranges plant material by asymmetric line and void: a tall shin (heaven), a supporting soe (earth) and a middle hikae (humanity) composed in measured triangles inside spare containers. Born from Buddhist altar flowers (roru? — rikka) in Muromachi temples and refined in tea-room chabana, it split into schools — Ikenobō\'s rikka discipline, Ohara\'s landscape moribana in shallow bowls, Sōgetsu\'s free sculpture. Seasonal materials, negative space and stem-by-stem intention make it closer to calligraphy than decoration.',
    col: [{ h: '#3f7a4f', n: 'stem green' }, { h: '#c93636', n: 'camellia red' }, { h: '#e9e4d4', n: 'vessel cream' }, { h: '#2b2b2b', n: 'branch charcoal' }],
    m: ['seasonal branches', 'flowers', 'ceramic and bronze vessels', 'kenzan needle frogs', 'water'],
    tx: ['bare branch line', 'bloom weight', 'water mirror surface'],
    obj: ['rikka grand altar arrangements', 'chabana tea flowers', 'moribana bowl landscapes', 'nageire tall vases'],
    ex: ['Ikenobō rikka of Ritsurin-era ceremonies', 'Ohara moribana seasonal bowls', 'Sōgetsu free-form exhibition pieces'],
    inf: ['Buddhist altar offering', 'tea ceremony aesthetics', 'nature-viewing poetics'], rel: ['Bonsai', 'Japanese Tea Ceremony Arts', 'Wabi-Sabi'],
    src: [{ n: 'Wikipedia — Ikebana', u: 'https://en.wikipedia.org/wiki/Ikebana', t: 'B' }, { n: 'The Metropolitan Museum of Art', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['flowers', 'japan', 'arrangement', 'line', 'seasonal', 'ritual'],
    pop: 49, niche: false,
    vd: { shape: 'three-point asymmetric line triangles', line: 'branch sweeps as primary strokes', composition: 'massed minimum against deliberate void', texture: 'water-reflecting vessel calm' },
    typ: { display: 'school calligraphy plaques', body: 'kakemono verse scrolls beside arrangements', notes: 'poem and flowers talk to each other' },
    lit: { quality: 'shaded alcove stillness', temperature: 'neutral-toned', shadow: 'tokonoma walls absorb light softly' },
    ui: { background: 'warm plaster beige', surface: 'vessel-curve cards', components: 'stem-line dividers', motion: 'slow branch-settle easing' },
    par: 'Japanese craft arts',
  },
  {
    n: 'Kimono Aesthetics', a: ['kimono culture', 'wafuku dress'],
    cat: 'Fashion & Dress', c: 'Japanese traditional dress system', e: 'historical',
    o: 'Japan', g: 'Japan, global fashion influence',
    p: '700s-present (formal system Edo-era)', era: 'Heian court to modern revival',
    sum: 'The T-shaped wrapped robe and its seasonal language: pattern, obi and occasion encoded on silk.',
    desc: 'Kimono dress codes turn bolt-straight silk into a social grammar: yuzen-dyed furisode for unmarried women\'s fluttering sleeves, homongi for visits, tomesode with hem-only patterns for married formality, seasonal motifs (plum for New Year, maple for autumn) placed to be read in motion. The wide obi belt — brocaded, stiffened, tied in sculptural knots — anchors the composition, while layering (kasane) and collar spacing signal age and taste. Modern designers from Issey Miyake to global runways keep re-draping its logic.',
    col: [{ h: '#1c3f6e', n: 'indigo ground' }, { h: '#c93636', n: 'maple red' }, { h: '#e8dfd0', n: 'shiozawa? no — shell cream' }, { h: '#d4af37', n: 'obi gold brocade' }, { h: '#2f5d4a', n: 'pine green' }],
    m: ['silk bolts (tanmono)', 'obi brocade', 'yuzen dyes', 'shibori ties', 'gold thread'],
    tx: ['flowing sleeve drape', 'stiff obi architecture', 'resist-dye crispness'],
    obj: ['furisode long-sleeve kimono', 'tomesode formal kimono', 'obi belt knots', 'haori jackets'],
    ex: ['Edo-period kosode in museum collections', 'yuzen furisode of the Kansai ateliers', 'Taisho-era meisen silk revivals'],
    inf: ['Heian court layering', 'Edo merchant luxury law', 'seasonal poetry imagery'], rel: ['Yūzen Dyeing', 'Shibori Resist Dyeing', 'Boro Mending Textiles'],
    src: [{ n: 'Wikipedia — Kimono', u: 'https://en.wikipedia.org/wiki/Kimono', t: 'B' }, { n: 'Victoria and Albert Museum', u: 'https://www.vam.ac.uk', t: 'A' }],
    tg: ['dress', 'japan', 'silk', 'seasonal', 'obi', 'ceremonial'],
    pop: 60, niche: false,
    vd: { shape: 'columnar T-form with flowing sleeve planes', line: 'seamless verticals broken by obi band', composition: 'motifs placed for motion, hem-weighted on formals', texture: 'silk sheen against brocade rigidity' },
    typ: { display: 'noren shop curtains as street typography', body: 'house mon (kamon) crests on shoulders', notes: 'crests identify family like signatures' },
    lit: { quality: 'paper-lantern warmth', temperature: 'warm-toned', shadow: 'sleeve shadows pool in folds' },
    ui: { background: 'indigo with seasonal scatter', surface: 'obi-band headers', components: 'crest-roundel buttons', motion: 'sleeve-sweep glides' },
    par: 'East Asian dress traditions',
  },
  {
    n: 'Tatami & Washitsu Rooms', a: ['washitsu', 'tatami room', 'shoin aesthetics'],
    cat: 'Interior Design', c: 'Japanese mat-room interior', e: 'historical',
    o: 'Japan', g: 'Japan, global design influence',
    p: '1500s-present', era: 'shoin development to present',
    sum: 'Mat-grid rooms of paper, wood and emptiness — the interior grammar behind "less is more".',
    desc: 'The washitsu composes a room from half-mat modules: tatami woven-straw floors set to auspicious or mourning grids, shoji paper screens diffusing daylight, fusuma painted sliding panels, a recessed tokonoma alcove holding one scroll and one flower, and enclosed furado? — chigaidana staggered shelves. Everything is floor-level, modular, and changeable with the seasons. From tea-house spareness through shoin formal rooms, this interior logic exported itself to the world as the visual basis of modern minimalism.',
    col: [{ h: '#c8b98a', n: 'tatami rush green-gold' }, { h: '#efe9da', n: 'shoji paper white' }, { h: '#3a2c1e', n: 'engawa wood brown' }, { h: '#1f1f1f', n: 'fusuma ink' }, { h: '#7a8b6a', n: 'moss green' }],
    m: ['igusa rush mats', 'washi paper', 'cedar and cypress', 'painted fusuma panels', 'tatami cloth borders'],
    tx: ['rush mat springiness', 'paper glow diffusion', 'planed wood grain'],
    obj: ['tokonoma display alcoves', 'shoji screen walls', 'fusuma sliding panels', 'chigaidana staggered shelves'],
    ex: ['Katsura Imperial Villa shoin rooms', 'tea-house nijiriguchi small entries', 'modern washitsu hotel suites'],
    inf: ['Zen temple austerity', 'tea ceremony spatial codes', 'shinden court halls'], rel: ['Shoji Craft', 'Wabi-Sabi', 'Japanese Tea Ceremony Arts'],
    src: [{ n: 'Wikipedia — Washitsu', u: 'https://en.wikipedia.org/wiki/Washitsu', t: 'B' }, { n: 'Wikipedia — Tatami', u: 'https://en.wikipedia.org/wiki/Tatami', t: 'B' }],
    tg: ['interior', 'japan', 'minimalism', 'tatami', 'screens', 'alcove'],
    pop: 47, niche: false,
    vd: { shape: 'mat-grid horizontal bands with vertical post rhythm', line: 'frame-and-panel rectangular discipline', composition: 'one alcove focal point in asymmetric emptiness', texture: 'matte straw, glowing paper, oiled wood' },
    typ: { display: 'hanging scroll calligraphy in tokonoma', body: 'painter colophons on fusuma', notes: 'one text per room, read in silence' },
    lit: { quality: 'shoji-diffused daylight', temperature: 'neutral-toned', shadow: 'soft depthless glow' },
    ui: { background: 'shoji paper white', surface: 'wood-frame cards', components: 'sliding-panel modals', motion: 'screen-slide transitions' },
    par: 'Japanese architecture',
  },
  {
    n: 'Shoji Craft', a: ['shoji screens', 'kumiko lattice work'],
    cat: 'Architectural Style', c: 'Japanese lattice-and-paper screens', e: 'historical',
    o: 'Japan', g: 'Japan, international adaptation',
    p: '1100s-present', era: 'medieval housing to present',
    sum: 'Hinwood? — Hinoki-grid sliding screens papered in washi — architecture turned into soft light.',
    desc: 'Shoji are sliding panels of fine cedar or hinoki lattice (kumiko) — joined without nails — glued over with washi paper so rooms receive sculpted, shadowless light. The grammar scales from a single window to whole facades; kumiko work itself became a virtuoso craft of asanoha stars and interlocking geometry. Shoji discipline — precise joinery, translucent planes, modularity — shaped Japanese modernism (Bruno Taut\'s praise of Katsura) and Western light-architecture, from Frank Lloyd Wright screens to contemporary shoji-inspired facades.',
    col: [{ h: '#e9e2d0', n: 'washi glow' }, { h: '#a9834f', n: 'hinoki frame honey' }, { h: '#5c4630', n: 'aged cedar' }, { h: '#d9d4c4', n: 'paper shade' }],
    m: ['hinoki cypress', 'cedar kumiko strips', 'washi paper', 'rice-glue paste'],
    tx: ['paper translucency', 'knife-cut joinery crispness', 'warm wood glow'],
    obj: ['shoji sliding doors', 'kumiko asanoha windows', 'ranshoma? no — ranma transom panels', 'paper lamps'],
    ex: ['Katsura Villa shoji walls', 'kumiko asanoha star panels', 'Yamagata kumiko workshop lamps'],
    inf: ['Zen carpentry guilds', 'washi papermaking', 'tea-house proportioning'], rel: ['Tatami & Washitsu Rooms', 'Washi Papermaking', 'Mashrabiya'],
    src: [{ n: 'Wikipedia — Shoji', u: 'https://en.wikipedia.org/wiki/Shoji', t: 'B' }, { n: 'ArchDaily', u: 'https://www.archdaily.com', t: 'C' }],
    tg: ['screens', 'wood', 'japan', 'lattice', 'light', 'joinery'],
    pop: 45, niche: false,
    vd: { shape: 'square-grid lattice with star-pattern accents', line: 'uniform kumiko strip rhythm', composition: 'full-wall repetition broken by ranma carvings', texture: 'paper bloom over precise joinery' },
    typ: { display: 'none', body: 'guest name slips on door frames', notes: 'paper screens double as note surfaces' },
    lit: { quality: 'diffused ambient glow', temperature: 'neutral-toned', shadow: 'shadows dissolve at the paper' },
    ui: { background: 'paper glow cream', surface: 'kumiko-grid frames', components: 'sliding-tab controls', motion: 'track-slide easing' },
    par: 'Japanese architecture',
  },
  {
    n: 'Temari Thread Balls', a: ['temari', 'Japanese embroidered thread balls'],
    cat: 'Textile & Craft', c: 'Japanese geometric thread spheres', e: 'regional_tradition',
    o: 'Japan (from Chinese kemari ball roots)', g: 'Japan, global stitch guilds',
    p: '1500s?-present', era: 'courtoy? — court toy to folk craft revival',
    sum: 'Silk-thread spheres wound and stitched into mandala stars — a New Year toy turned geometry craft.',
    desc: 'Temari begins as a core of rice hulls or cloth wound tight with thread, then stitched over with polished silk into geometric constellations: kiku chrysanthemum stars, interlocked hexagons, SAKURA? — sakura blossoms wrapping a sphere whose every face maps a different pattern. Girls\'-day playthings and New Year gifts from mothers and grandmothers, temari nearly vanished before twentieth-century guilds catalogued hundreds of named stitch patterns. Each ball is a small mandala — no two finished alike.',
    col: [{ h: '#c93636', n: 'silk red' }, { h: '#d4af37', n: 'gold thread' }, { h: '#2b5db8', n: 'indigo star' }, { h: '#3f9a6f', n: 'jade green' }, { h: '#f2ecdc', n: 'wound ground' }],
    m: ['silk and cotton threads', 'rice-hull cores', 'polyfill (modern)', 'metallic floss'],
    tx: ['taut thread sheen', 'radial stitch symmetry', 'hand-warmed roundness'],
    obj: ['kiku chrysanthemum temari', 'interlocked-hexagon balls', 'New Year gift temari'],
    ex: ['grandmother-made kiku star temari', 'Japanese Temari Association pattern books', 'regional guild exhibition spheres'],
    inf: ['kemari kicking-game balls', 'sericulture household economy', 'geometric embroidery lines'], rel: ['Sashiko Stitching', 'Origami', 'Yūzen Dyeing'],
    src: [{ n: 'Wikipedia — Temari (toy)', u: 'https://en.wikipedia.org/wiki/Temari_(toy)', t: 'B' }, { n: 'The Metropolitan Museum of Art', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['thread', 'embroidery', 'japan', 'geometric', 'toy', 'mandala'],
    pop: 33, niche: true,
    vd: { shape: 'spherical mandala with polar-symmetric star poles', line: 'radiating thread chords between equators', composition: 'pattern wrap continuous around the sphere', texture: 'smooth taut embroidery over firm core' },
    typ: { display: 'none', body: 'gift verse sometimes tucked with the ball', notes: 'pattern names carry the lore' },
    lit: { quality: 'soft window light', temperature: 'warm-toned', shadow: 'thread ridges catch tiny glints' },
    ui: { background: 'ivory sphere gradient', surface: 'star-vertex frames', components: 'ball-roundel icons', motion: 'gentle sphere rotation' },
    par: 'Japanese craft arts',
  },
  {
    n: 'Furoshiki Wrapping Cloths', a: ['furoshiki', 'Japanese wrapping cloth'],
    cat: 'Textile & Craft', c: 'Japanese knot-wrap culture', e: 'regional_tradition',
    o: 'Japan', g: 'Japan, sustainable-design world',
    p: '1600s-present', era: 'Edo bath culture to eco revival',
    sum: 'One square cloth knots into bag, bottle-carrier and gift box — wrapping as reusable design.',
    desc: 'Furoshiki — literally "bath spread" — began as Edo-period cloths for bundling clothes at public baths and became Japan\'s universal carrier: a single hemmed square (silk, cotton, or nylon today) knotted into backpacks, two-bottle totes, melon-protective? — fruit cradles and gift wrap, its pattern part of the present. Ministry-of-environment campaigns revived furoshiki in 2006 as plastic-bag alternatives, and design studios now print everything from chiyogami motifs to contemporary art on the square. The knots (macho? — honmusubi, uzura-musubi) carry the craft.',
    col: [{ h: '#1c3f6e', n: 'indigo ground' }, { h: '#c93636', n: 'seal red' }, { h: '#e8dfd0', n: 'undyed cotton' }, { h: '#d4af37', n: 'gold pattern' }],
    m: ['cotton square cloth', 'silk (formal)', 'nylon (modern)', 'hem stitching'],
    tx: ['soft drape folds', 'crisp knot creases', 'printed pattern clarity'],
    obj: ['bottle-carry double knots', 'bento-wrap boxes', 'gift presentations', 'shoulder-bag knots'],
    ex: ['Edo bath-bundling cotton squares', 'modern ministry eco-campaign furoshiki', 'department-store gift furoshiki service'],
    inf: ['Edo merchant bundling', 'gift-wrapping etiquette', 'zero-waste design'], rel: ['Origami', 'Boro Mending Textiles', 'Katazome Dyeing'],
    src: [{ n: 'Wikipedia — Furoshiki', u: 'https://en.wikipedia.org/wiki/Furoshiki', t: 'B' }, { n: 'The Metropolitan Museum of Art', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['wrapping', 'cloth', 'japan', 'knots', 'sustainability', 'gift'],
    pop: 41, niche: false,
    vd: { shape: 'square cloth with symmetric knot ears above', line: 'drape diagonals meeting at center knots', composition: 'pattern fragments re-composed by each fold', texture: 'cloth softness over knot structure' },
    typ: { display: 'printed shop names on cloth corners', body: 'gift inscriptions', notes: 'the cloth itself is the card' },
    lit: { quality: 'counter daylight', temperature: 'warm-toned', shadow: 'knot shadows mark the silhouette' },
    ui: { background: 'cloth-print tint', surface: 'knot-diagram cards', components: 'wrap-steps icons', motion: 'knot-tighten pulls' },
    par: 'Japanese craft arts',
  },
  {
    n: 'Sashiko Stitching', a: ['sashiko', 'Japanese running-stitch embroidery'],
    cat: 'Textile & Craft', c: 'Japanese utility stitching', e: 'regional_tradition',
    o: 'Northern Japan farming regions', g: 'Japan, global visible-mending movement',
    p: '1600s-present', era: 'Edo cotton scarcity to craft revival',
    sum: 'White running stitches quilting indigo layers into asanoha stars and seigaiha waves — warmth made visible.',
    desc: 'Sashiko (little stabs) began as necessity: Edo-era northern farmers, barred from cotton, layered and stitched recycled indigo cloth for warmth, using even white running stitches that doubled as reinforcement and quiet ornament — asanoha hemp stars, seigaiha wave scales, tortoise-shell kikkō grids. Firefighter hanten jackets wore dense sashiko quilting; fisher jackets got tally stitches for every catch. Boro patchwork grew from the same economy, and today sashiko leads the global visible-mending movement.',
    col: [{ h: '#1c2f4a', n: 'worked indigo' }, { h: '#f2efe4', n: 'stitch white' }, { h: '#24476e', n: 'patch indigo' }, { h: '#8a9296', n: 'faded field' }],
    m: ['indigo cotton layers', 'white cotton sashiko thread', 'large-eye needles'],
    tx: ['even stitch ridges', 'layered cloth stiffness', 'indigo fade gradients'],
    obj: ['hanten work jackets', 'zabuton cushion tops', 'firefighter sashiko coats', 'boro mended futon covers'],
    ex: ['Asanoha-star hanten quilting', 'seigaiha wave sampler cloth', 'boro futon covers layered over decades'],
    inf: ['cotton rationing economy', 'indigo dye culture', 'household thrift ethic'], rel: ['Boro Mending Textiles', 'Katazome Dyeing', 'Kimono Aesthetics'],
    src: [{ n: 'Wikipedia — Sashiko', u: 'https://en.wikipedia.org/wiki/Sashiko', t: 'B' }, { n: 'Victoria and Albert Museum', u: 'https://www.vam.ac.uk', t: 'A' }],
    tg: ['stitching', 'indigo', 'japan', 'mending', 'utility', 'geometry'],
    pop: 42, niche: false,
    vd: { shape: 'all-over geometric grids spaced by cloth weave', line: 'unbroken white running-stitch rows', composition: 'border-to-border repeat with corner medallions', texture: 'stitch relief on washed indigo' },
    typ: { display: 'stitched owner names on jackets', body: 'tally marks on fisher coats', notes: 'counting stitches as record-keeping' },
    lit: { quality: 'winter north light', temperature: 'cool-toned', shadow: 'stitch rows micro-shadow at an angle' },
    ui: { background: 'faded indigo', surface: 'stitch-grid frames', components: 'wave-scale icons', motion: 'stitch-row marching' },
    par: 'Japanese textile arts',
  },
  {
    n: 'Katazome Dyeing', a: ['katazome', 'Japanese stencil resist dyeing'],
    cat: 'Textile & Craft', c: 'Japanese stencil-resist textile art', e: 'regional_tradition',
    o: 'Japan', g: 'Japan',
    p: '1500s-present', era: 'Momoyama pattern trade to present',
    sum: 'Stencilled rice-paste resist and indigo: Edo patterns printed by knife-cut katagami paper.',
    desc: 'Katazome prints cloth by the negative: intricate patterns cut into smoked katagami stencil paper — pine needles, trailing water, dragonfly wings — are laid on cloth, rice paste brushed through, then the whole yard is dyed; washing the paste away leaves the pattern as untouched white. Ise katagami guilds carved stencils fine as lace with cut awls and punches; indigo katazome dressed farmers, decorated futon covers, noren curtains and samurai under-kimono. The stencil vocabulary feeds directly into modern Japanese graphic design.',
    col: [{ h: '#1c3f6e', n: 'indigo field' }, { h: '#f2efe4', n: 'resist white' }, { h: '#5a4a3a', n: 'smoked stencil brown' }, { h: '#8a9296', n: 'worn fade' }],
    m: ['katagami stencil paper', 'rice paste', 'indigo vat', 'persimmon-tanned paper'],
    tx: ['lace-fine stencil cuts', 'crisp paste edge', 'vat-dyed depth'],
    obj: ['noren shop curtains', 'futon cover patterns', 'samurai under-kimono', 'yukata bolt patterns'],
    ex: ['Ise katagami dragonfly stencils', 'indigo noren for shopfronts', 'Edo komon fine-pattern kimono'],
    inf: ['Ise stencil guilds', 'indigo vat culture', 'Edo sumptuary pattern law'], rel: ['Sashiko Stitching', 'Shibori Resist Dyeing', 'Yūzen Dyeing'],
    src: [{ n: 'Wikipedia — Katazome', u: 'https://en.wikipedia.org/wiki/Katazome', t: 'B' }, { n: 'Victoria and Albert Museum', u: 'https://www.vam.ac.uk', t: 'A' }],
    tg: ['stencil', 'indigo', 'japan', 'resist dye', 'pattern', 'craft'],
    pop: 36, niche: true,
    vd: { shape: 'repeat lace-cuts cycling across the bolt', line: 'knife paths balancing connection bridges', composition: 'half-drop repeats in negative white', texture: 'paste-edge crispness on vat indigo' },
    typ: { display: 'family crests as stencil motifs', body: 'shop names cut into noren', notes: 'stencil language prefigures sans-serif logos' },
    lit: { quality: 'courtyard daylight', temperature: 'cool-toned', shadow: 'pattern reads as shadow-play' },
    ui: { background: 'vat indigo', surface: 'stencil-lace cards', components: 'repeat-tile icons', motion: 'pattern-roll scrolls' },
    par: 'Japanese textile arts',
  },
  {
    n: 'Hanji Papermaking', a: ['hanji', 'Korean mulberry paper craft'],
    cat: 'Textile & Craft', c: 'Korean mulberry-bark paper art', e: 'regional_tradition',
    o: 'Korea', g: 'Korea',
    p: '1300s-present (earlier roots)', era: 'Joseon state craft to revival',
    sum: 'Korean dak paper strong enough for floors, armor and lamps — a thousand sheets from one tree.',
    desc: 'Hanji is paper from the inner bark of the paper mulberry (dak), beaten into long fibers and couched on bamboo screens in a sheet-forming process that crosses fibers for strength; boiled, dried and hammered sheets become documents that survive six centuries, window paper, flooring (jangpan), lacquerware cores, layered boxes and even woven rope armor. Joseon ran state paper mills at Jeonju; twentieth-century mechanization nearly killed the craft before revival masters restarted village vats. Hanji lamp and furniture design now exports worldwide.',
    col: [{ h: '#efe6d0', n: 'dak ivory' }, { h: '#d9cdb4', n: 'unbleached tan' }, { h: '#8c6f3f', n: 'lacquer brown' }, { h: '#c93636', n: 'lamp glow red' }],
    m: ['paper mulberry bark', 'hibiscus mucilage', 'bamboo screens', 'natural dyes'],
    tx: ['crossed fiber strength', 'soft matte tooth', 'translucent layer glow'],
    obj: ['jogeoji document paper', 'jangpan floor sheets', 'lamp shades', 'lacquered paper chests'],
    ex: ['Jeonju hanji workshop vats', 'jangpan flooring of old hanok', 'contemporary hanji lamp collections'],
    inf: ['Chinese papermaking transfer', 'Joseon bureaucracy demand', 'temple sutra copying'], rel: ['Bojagi Wrapping Cloths', 'Washi Papermaking', 'Shoji Craft'],
    src: [{ n: 'Wikipedia — Hanji', u: 'https://en.wikipedia.org/wiki/Hanji', t: 'B' }, { n: 'The Metropolitan Museum of Art', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['papermaking', 'korea', 'mulberry', 'craft', 'durability', 'lamp'],
    pop: 35, niche: true,
    vd: { shape: 'sheet planes layered and curved over frames', line: 'visible fiber crossing under light', composition: 'pasted layers building opaque glow boxes', texture: 'leather-soft surface, honey back-light' },
    typ: { display: 'hanja calligraphy on document sheets', body: 'hangul printing on hanji pages', notes: 'paper built to be written for centuries' },
    lit: { quality: 'transmitted warm glow', temperature: 'warm-toned', shadow: 'fibers float in the light' },
    ui: { background: 'hanji ivory', surface: 'layer-edge cards', components: 'lamp-glow toggles', motion: 'paper-fold turns' },
    par: 'Korean craft arts',
  },
  {
    n: 'Bojagi Wrapping Cloths', a: ['bojagi', 'pojagi', 'Korean wrapping cloth'],
    cat: 'Textile & Craft', c: 'Korean patchwork wrapping cloth', e: 'regional_tradition',
    o: 'Korea', g: 'Korea, international quilting world',
    p: '1300s-present', era: 'Joseon household craft to present',
    sum: 'Patchworked and seamed squares of Korean cloth — flat-felled seams glowing like stained glass.',
    desc: 'Bojagi are Korean wrapping cloths — square, knotted over gifts, food boxes and wedding linens — where leftover silk and ramie scraps are pieced into asymmetric patchwork (jogakbo) whose seams are folded flat and whip-stitched so the cloth reads identically from both sides, light passing through like leaded glass. Royal gift bojagi worked in gold-thread embroidery; commoner bojagi practiced frugality-as-beauty. Contemporary fiber artists worldwide adopt the open-seam technique, and museums collect Joseon bojagi as quiet masterpieces of chance geometry.',
    col: [{ h: '#c93636', n: 'silk patch red' }, { h: '#2b5db8', n: 'patch blue' }, { h: '#e8dfd0', n: 'ramie ivory' }, { h: '#d4af37', n: 'royal gold stitch' }, { h: '#3f9a6f', n: 'jade patch' }],
    m: ['silk scraps', 'ramie (mosi)', 'cotton', 'gold thread (royal)', 'flat-felled seams'],
    tx: ['translucent patch glow', 'raised seam ribs', 'scrap-bag color chance'],
    obj: ['jogakbo patchwork wraps', 'wedding-lineage gift bojagi', 'royal embroidered bojagi', 'food-cover squares'],
    ex: ['Joseon court embroidered gift bojagi', 'household jogakbo scrap patchwork', 'Seoul museum bojagi exhibitions'],
    inf: ['frugal household economy', 'Confucian gift etiquette', 'shamanic wrapping blessings'], rel: ['Furoshiki Wrapping Cloths', 'Hanji Papermaking', 'Sashiko Stitching'],
    src: [{ n: 'Wikipedia — Bojagi', u: 'https://en.wikipedia.org/wiki/Bojagi', t: 'B' }, { n: 'The Metropolitan Museum of Art', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['patchwork', 'korea', 'wrapping', 'seams', 'silk', 'geometry'],
    pop: 34, niche: true,
    vd: { shape: 'irregular polygon patches in balanced asymmetry', line: 'flat-felled seam ribs as leading lines', composition: 'borders first, center filled last', texture: 'glass-light through ramie and silk' },
    typ: { display: 'embroidered blessing characters (royal)', body: 'none on commoner work', notes: 'wraps blessed the contents silently' },
    lit: { quality: 'window backlight', temperature: 'neutral-toned', shadow: 'seams glow when held to sun' },
    ui: { background: 'patch tint mosaic', surface: 'seam-rib frames', components: 'knot-corner buttons', motion: 'patch-fade assembly' },
    par: 'Korean textile arts',
  },
  {
    n: 'Moon Jar', a: ['dalhangari', 'Joseon moon jar'],
    cat: 'Textile & Craft', c: 'Joseon porcelain vessel', e: 'historical',
    o: 'Joseon Korea kilns', g: 'Korea',
    p: '1600s-1700s peak', era: 'Joseon dynasty',
    sum: 'The great white sphere of Joseon porcelain — two hemispheres joined, imperfect, luminous.',
    desc: 'The moon jar (dalhangari) throws two large hemispheres and joins them at the belly, so the finished sphere always leans, dimples or sags slightly — and Joseon taste loved exactly that: white slip-painted porcelain with faint iron freckles, glaze pooling blue-green at the waist seam, presence without ornament. Court jars held flowers and fruit; today the form is Korea\'s national ceramic icon, re-thrown by masters from Yu Geun-Hyeong\'s revival onward, and a favorite of contemporary ceramists worldwide.',
    col: [{ h: '#f4f1ea', n: 'porcelain white' }, { h: '#dfe4e0', n: 'glaze blue-green' }, { h: '#c9bfa8', n: 'iron freckle' }, { h: '#b8b2a4', n: 'kiln shadow' }],
    m: ['kaolin porcelain clay', 'white slip', 'transparent glaze', 'wood firing'],
    tx: ['eggshell-smooth glaze', 'subtle throwing ridges', 'waist-seam undulation'],
    obj: ['court flower jars', 'fruit vessels', 'modern revival sphere jars'],
    ex: ['National Museum of Korea moon jars', 'Yu Geun-Hyeong revival pieces', 'contemporary spherical re-interpretations'],
    inf: ['Joseon white-ware kilns', 'Confucian austerity taste', 'Chinese white porcelain precedent'], rel: ['Celadon Glaze Tradition', 'Wabi-Sabi', 'Buncheong Ware'],
    src: [{ n: 'Wikipedia — Moon jar', u: 'https://en.wikipedia.org/wiki/Moon_jar', t: 'B' }, { n: 'The Metropolitan Museum of Art', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['porcelain', 'korea', 'sphere', 'white', 'imperfection', 'joseon'],
    pop: 40, niche: false,
    vd: { shape: 'near-perfect sphere with honest lean and sag', line: 'single horizontal waist seam', composition: 'pure volume, no decoration', texture: 'glaze pooling and iron speckles' },
    typ: { display: 'none', body: 'kiln marks under foot', notes: 'silence is the decoration' },
    lit: { quality: 'soft north-light', temperature: 'neutral-toned', shadow: 'the jar shadows as gently as it leans' },
    ui: { background: 'warm gallery grey', surface: 'sphere-curve cards', components: 'round quiet buttons', motion: 'breath-slow scale' },
    par: 'Korean ceramic arts',
  },
  {
    n: 'Inro Medicine Cases', a: ['inrō', 'Japanese stacked seal case'],
    cat: 'Fashion & Dress', c: 'Japanese tiered belt case', e: 'historical',
    o: 'Japan', g: 'Japan',
    p: '1500s-1800s peak', era: 'samurai accessory era',
    sum: 'Stacked lacquer pillboxes on a silk cord — miniature cabinetmaking worn at the waist.',
    desc: 'The inro is a stack of two-to-five sealed compartments strung on a silk cord and held by a carved netsuke toggle, born because Edo formal dress had no pockets: samurai and merchants carried seals, medicines and perfumes in these lacquered minicabinets. Makers — Shibata Zeshin the most celebrated — layered roiro urushi black lacquer with maki-e gold dust, shell inlay and takamakie relief, turning daily objects into jewel boxes. Together with ojime beads, the ensemble remains the summit of Japanese small-work luxury.',
    col: [{ h: '#101010', n: 'roiro black lacquer' }, { h: '#d4af37', n: 'maki-e gold dust' }, { h: '#c9b06a', n: 'shell inlay nacre' }, { h: '#8a1f2b', n: 'cord red silk' }],
    m: ['lacquered wood or paper core', 'urushi lacquer', 'gold powder (maki-e)', 'mother-of-pearl', 'silk cord'],
    tx: ['mirror-black lacquer depth', 'raised gold relief', 'cool nacre glints'],
    obj: ['multi-tier seal cases', 'medicine compartments', 'netsuke toggles', 'ojime sliding beads'],
    ex: ['Shibata Zeshin signature inro', 'maki-e seasonal landscape cases', 'Edo merchant everyday inro sets'],
    inf: ['Chinese medicine-case prototypes', 'maki-e lacquer guilds', 'Edo dress sans-pocket custom'], rel: ['Netsuke Carving', 'Kimono Aesthetics', 'Ottoman Tombak'],
    src: [{ n: 'Wikipedia — Inro', u: 'https://en.wikipedia.org/wiki/Inro', t: 'B' }, { n: 'Victoria and Albert Museum', u: 'https://www.vam.ac.uk', t: 'A' }],
    tg: ['lacquer', 'japan', 'accessory', 'maki-e', 'samurai', 'miniature'],
    pop: 36, niche: true,
    vd: { shape: 'flat stacked lozenges hanging at the hip', line: 'gold contours riding the black field', composition: 'continuous scene wrapping all tiers', texture: 'deep gloss broken by raised gold' },
    typ: { display: 'kaō cipher marks on case interiors', body: 'poem inscriptions (fine pieces)', notes: 'maker signatures in tiny gold' },
    lit: { quality: 'candlelight glint', temperature: 'warm-toned', shadow: 'black field swallows all but gold' },
    ui: { background: 'roiro black', surface: 'gold-dust frames', components: 'tiered-stack icons', motion: 'cord-swing pendulums' },
    par: 'Japanese lacquer arts',
  },
  {
    n: 'Nihonga Painting', a: ['nihonga', 'Japanese-style painting revival'],
    cat: 'Painting Technique & School', c: 'Meiji-era Japanese painting', e: 'historical',
    o: 'Meiji Japan', g: 'Japan',
    p: '1880s-present', era: 'Meiji westernization to contemporary',
    sum: 'Mineral pigments on silk in revived Japanese manner — tradition rebuilt against oil painting.',
    desc: 'Nihonga ("Japanese painting") was coined in late-Meiji criticism to name the traditional stream: mineral pigments (iwa-enogu) ground from malachite, azurite and shell, bound in glue on silk or washi, with gold leaf, ink line and compositional principles from Kano and Rinpa schools. When Tokyo School fine-arts teaching split "yoga" (Western oil) from "nihonga", masters like Yokoyama Taikan, Hishida Shunsō and later Kayama Matazo proved the idiom could carry modern scale and light — moody gradations (mokkotsu boneless method), vast planes of mineral green and blue. Contemporary nihonga keeps the grinding mortar busy.',
    col: [{ h: '#2f7d5a', n: 'malachite green' }, { h: '#2b5db8', n: 'azurite blue' }, { h: '#f0ead8', n: 'shell white' }, { h: '#d4af37', n: 'gold leaf plane' }, { h: '#1f1f1f', n: 'sumi ink line' }],
    m: ['mineral pigments', 'silk or washi ground', 'nikawa glue', 'gold and silver leaf', 'sumi ink'],
    tx: ['granular pigment shimmer', 'flat gold reflection', 'ink-line snap'],
    obj: ['landscape two-panel screens', 'flower-and-bird silks', 'moon-and-wave modern classics'],
    ex: ['Yokoyama Taikan\'s Metempsychosis scroll', 'Hishida Shunsō\'s Black Cat', 'Yokoyama Taikan\'s Yangtze River scroll'],
    inf: ['Kano school line', 'Rinpa decorative planes', 'Western exhibition scale'], rel: ['Ukiyo-e Prints', 'Ikebana', 'Kimono Aesthetics'],
    src: [{ n: 'Wikipedia — Nihonga', u: 'https://en.wikipedia.org/wiki/Nihonga', t: 'B' }, { n: 'The Metropolitan Museum of Art', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['painting', 'japan', 'mineral', 'revival', 'silk', 'gold'],
    pop: 41, niche: false,
    vd: { shape: 'large calm planes of sky, water and mist', line: 'confident ink contour over color fields', composition: 'asymmetric emptiness with gold-leaf light', texture: 'crushed-stone pigment sparkle' },
    typ: { display: 'artist seal and title slips', body: 'tanka inscriptions (traditional themes)', notes: 'colophon practice from screen painting' },
    lit: { quality: 'soft indoor reflectance', temperature: 'neutral-toned', shadow: 'painted mist carries shadow duties' },
    ui: { background: 'mineral green wash', surface: 'gold-plane cards', components: 'seal-red badges', motion: 'mist-drift gradients' },
    par: 'Japanese painting',
  },
  {
    n: 'Bonsai', a: ['bonsai', 'potted landscape trees', 'penjing relative'],
    cat: 'Regional & Cultural Tradition', c: 'Japanese miniature tree art', e: 'historical',
    o: 'Japan (from Chinese penjing)', g: 'Japan, worldwide practice',
    p: '1300s-present', era: 'medieval elite hobby to global art',
    sum: 'Centuries-old trees kept small by pot, wire and patience — landscapes compressed to a silhouette.',
    desc: 'Bonsai grows full trees — maples, pines, junipers — whose scale lies: a thirty-year trunk of two hands\' width, branch pads wired and pruned into cloud tiers, roots nebari gripping the soil like a cliff-edge. From Chinese penjing brought through Zen temples to Japan, bonsai became a disciplined art of suggestion: the tree implies wind, age, mountain. Seasonal work — wiring in winter, pinching candles in spring — is a lifelong calendar; display pairs the tree with a scroll, an accent plant and the right pot in the tokonoma.',
    col: [{ h: '#3f7a4f', n: 'needle green' }, { h: '#7a5230', n: 'bark mahogany' }, { h: '#5a4a3a', n: 'clay pot brown' }, { h: '#8a9296', n: 'deadwood grey' }],
    m: ['trained trees', 'wire (copper, aluminum)', 'akadama soil', 'ceramic pots', 'moss'],
    tx: ['wired branch rhythm', 'furrowed bark age', 'moss carpet softness'],
    obj: ['cascade (kengai) trees', 'forest (yose-ue) plantings', 'tokonoma display sets', 'shohin small collections'],
    ex: ['Omiya Bonsai Village museum pines', 'the Imperial Collection 400-year white pine', 'shohin six-tree displays'],
    inf: ['Chinese penjing', 'Zen temple austerity', 'tea-ceremony display codes'], rel: ['Ikebana', 'Wabi-Sabi', 'Penjing Landscapes'],
    src: [{ n: 'Wikipedia — Bonsai', u: 'https://en.wikipedia.org/wiki/Bonsai', t: 'B' }, { n: 'The Metropolitan Museum of Art', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['trees', 'japan', 'miniature', 'patience', 'pot', 'landscape'],
    pop: 53, niche: false,
    vd: { shape: 'asymmetric triangles of branch pads over twisting trunks', line: 'S-curves of trunk and deadwood jins', composition: 'rule-of-thirds lean with sky voids', texture: 'needle clouds, moss floor, pot glaze' },
    typ: { display: 'wooden display tablets naming tree and age', body: 'scroll painting behind the tree', notes: 'display tells one season per tokonoma' },
    lit: { quality: 'morning garden light', temperature: 'neutral-toned', shadow: 'pad layers self-shadow like hills' },
    ui: { background: 'mist garden grey-green', surface: 'pot-tone frames', components: 'wire-curve icons', motion: 'growth-ring slow zooms' },
    par: 'Japanese craft arts',
  },
  {
    n: 'Yūzen Dyeing', a: ['yuzen', 'kaga yuzen', 'kyo yuzen'],
    cat: 'Textile & Craft', c: 'Japanese paste-resist dyeing', e: 'historical',
    o: 'Kyoto (Miyazaki Yūzen) & Kanazawa', g: 'Japan',
    p: '1600s-present', era: 'Genroku fashion to living workshops',
    sum: 'Painterly paste-resist on silk: garden-like kimono patterns outlined in fine rice-paste lines.',
    desc: 'Yūzen freed kimono pattern from the repeat: a fine rice-paste line is drawn freehand onto silk, enclosing painterly fields that are brush-dyed in gradients — plum branches bending through shading, gold outline accents, steamed to fix. Attributed to fan-painter Miyazaki Yūzen in the Genroku era, the technique split into Kyo-yuzen (courtly richness) and Kaga-yuzen (browner, melancholic, five-color discipline). Entire garden scenes flow across one furisode; today\'s living national treasures still draw the paste line by hand.',
    col: [{ h: '#c93636', n: 'graduated crimson' }, { h: '#2b5db8', n: 'river blue wash' }, { h: '#d4af37', n: 'gold outline' }, { h: '#f2ecdc', n: 'silk ground' }, { h: '#3f7a4f', n: 'foliage green' }],
    m: ['silk kimono bolts', 'rice paste', 'brush dyes', 'gold leaf accents', 'steaming fixtures'],
    tx: ['painterly color gradients', 'paste-line crispness', 'silk sheen under dye'],
    obj: ['furisode garden kimono', 'obi sash panels', 'hanging dyed panels'],
    ex: ['Kyo-yuzen wedding furisode', 'Kaga-yuzen five-color landscape bolts', 'living-treasure workshop demonstrations'],
    inf: ['fan painting composition', 'Rinpa decorative painting', 'Edo merchant fashion'], rel: ['Kimono Aesthetics', 'Katazome Dyeing', 'Shibori Resist Dyeing'],
    src: [{ n: 'Wikipedia — Yūzen', u: 'https://en.wikipedia.org/wiki/Y%C5%ABzen', t: 'B' }, { n: 'Victoria and Albert Museum', u: 'https://www.vam.ac.uk', t: 'A' }],
    tg: ['dyeing', 'japan', 'kimono', 'painterly', 'resist', 'silk'],
    pop: 38, niche: true,
    vd: { shape: 'free-flowing garden motifs without repeats', line: 'hair-fine paste outlines enclosing washes', composition: 'diagonal scene-flow across shoulder and sleeve', texture: 'silk glow under layered dye' },
    typ: { display: 'signature and workshop seals at hem', body: 'poem imagery translated to motif', notes: 'patterns illustrate waka season-words' },
    lit: { quality: 'parlor lamplight', temperature: 'warm-toned', shadow: 'gradients paint their own shadow' },
    ui: { background: 'silk gradient wash', surface: 'paste-line frames', components: 'brush-stroke cursors', motion: 'dye-bleed blooms' },
    par: 'Japanese textile arts',
  },
]
