/**
 * Curated wave — East Asia II: Japan craft, ceramics, architecture,
 * gardens, dress and stage. Complements east-asia.ts (which holds the
 * textile resist-dye entries).
 */
export const WAVE_EA2: any[] = [
  {
    n: "Kintsugi repair", a: ["金継ぎ", "kintsukuroi", "golden joinery"],
    cat: "Textile & Craft", c: "Lacquer repair", e: "regional_tradition", o: "Japan", g: "Japan, global craft culture",
    p: "Muromachi era onward", era: "tea ceremony culture",
    sum: "Repairing broken ceramics with gold-dusted lacquer — fractures made into golden rivers, not hidden.",
    desc: "Kintsugi joins broken pottery with urushi lacquer, dusting the seams with gold or silver powder so cracks become bright veins across the vessel. Born in tea-ceremony culture (legend: a shogun's treasured bowl repaired with metal staples inspired lacquer craftsmen), it embodies wabi-sabi's ethics — damage is biography, repair is honor, nothing perfect is thrown away. Collectors prize kintsugi bowls above intact ones; the world's therapists and designers borrowed the metaphor. The look: dark seams turned luminous, mended glow.",
    col: [{ h: "#d4af37", n: "gold seam" }, { h: "#1a1a1a", n: "raku black" }, { h: "#f2ead9", n: "shino cream" }, { h: "#8b4513", n: "urushi brown" }],
    m: ["urushi lacquer", "gold powder (kinpaku)", "silver powder", "broken ceramics"],
    tx: ["luminous seam lines", "lacquer gloss", "vessel matte"],
    obj: ["repaired tea bowls", "gold-veined plates", "kintsugi vases"],
    ex: ["Tea-ceremony kintsugi bowls", "contemporary kintsugi studios", "museum repaired-ware displays"],
    inf: ["wabi-sabi philosophy", "urushi lacquer craft"], rel: ["Urushi lacquerware", "Tea ceremony aesthetics", "Bizen ware"],
    par: "", var: ["gold kintsugi", "silver kintsugi", "brass staple hybrid"], cf: ["wabi-sabi"],
    src: [{ n: "Wikipedia — Kintsugi", u: "https://en.wikipedia.org/wiki/Kintsugi", t: "B" }],
    tg: ["repair", "gold", "lacquer", "wabi-sabi", "japan"], pop: 56, niche: false,
    vd: { shape: "vessel silhouette + vein seams", line: "meandering gold cracks", composition: "fracture-as-pattern", texture: "gloss on matte", forms: "seams, rivers, joints" },
    typ: { display: "quiet mincho serif", body: "humanist sans", notes: "restraint + shine" },
    lit: { quality: "single warm lamp", direction: "raking", temperature: "warm", shadow: "seam glint" },
    ui: { background: "charcoal", surface: "gold-seam cards", components: "crack-line dividers", motion: "seam draw-on" },
    rec: { materials: "broken bowl, gold powder kit", lighting: "warm spot", objects: "mended bowl, tea things", music: "shakuhachi", scent: "urushi, tatami" },
    snd: ["shakuhachi breath", "ceramic chime"],
    dna: { mi: 65, og: 80, wc: 20, ns: 10, ad: 5, hf: 10, rr: 25, ps: 30, sh: 20, ql: 15, oc: 20, ds: 45, rs: 20, eu: 80, np: 50 },
    emo: { warm: 70, cold: 25, playful: 15, serious: 70, chaotic: 15, ordered: 80, nostalgic: 75, futuristic: 10, peaceful: 75, ominous: 10 },
  },
  {
    n: "Urushi lacquerware", a: ["漆", "japan lacquer", "Wajima-nuri"],
    cat: "Textile & Craft", c: "Lacquer craft", e: "regional_tradition", o: "Japan (Wajima, Takatsuki)", g: "Japan",
    p: "Jomon origins; medieval refinement", era: "living tradition",
    sum: "Sap-sapplied wooden vessels — dozens of lacquer layers cured in humidity, maki-e gold sprinkle at the summit.",
    desc: "Urushi is the art of the lacquer tree's sap: brushed in dozens of thin layers over wood, each cured in humid chambers, sanded between coats until the surface is harder than the wood it protects and warm to the touch. Decorative summits include maki-e (gold-sprinkle pictures), raden (mother-of-pearl inlay) and chinkin (carved gilt). Regional schools — Wajima-nuri's durability, Tsugaru-nuri's rainbow layered patterns — keep lineages; the tea ceremony treasured its depth of black. The look: liquid-dark gloss holding galaxies of gold.",
    col: [{ h: "#1a1a1a", n: "roiro black" }, { h: "#8b0000", n: "shu vermillion" }, { h: "#d4af37", n: "maki-e gold" }, { h: "#2a9d8f", n: "raden shell" }],
    m: ["urushi sap", "wood core (kiji)", "gold powder", "mother-of-pearl", "brushes of human hair"],
    tx: ["glass-deep gloss", "gold sprinkle shimmer", "layer depth"],
    obj: ["tea caddies (natsume)", "tiered boxes (jubako)", "bowls and trays", "maki-e writing boxes"],
    ex: ["Wajima-nuri workshops", "Kōdaiji maki-e", "Shōsōin treasury lacquers"],
    inf: ["Chinese lacquer tradition"], rel: ["Kintsugi repair", "Tea ceremony aesthetics", "Furisode"],
    par: "", var: ["Wajima-nuri", "Tsugaru-nuri", "maki-e", "chinkin"], cf: ["Kintsugi repair"],
    src: [{ n: "Wikipedia — Japanese lacquerware", u: "https://en.wikipedia.org/wiki/Japanese_lacquerware", t: "B" }],
    tg: ["lacquer", "japan", "gold", "craft", "maki-e"], pop: 34, niche: false,
    vd: { shape: "calm vessel geometry", line: "gold-sprinkle contours", composition: "centered motive fields", texture: "liquid gloss", forms: "clouds, cranes, pines" },
    typ: { display: "mincho serif", body: "humanist sans", notes: "brand-quiet" },
    lit: { quality: "single warm", direction: "raking", temperature: "warm", shadow: "gloss depth" },
    ui: { background: "black", surface: "gold-mist cards", components: "gloss buttons", motion: "gold dust drift" },
    rec: { materials: "lacquer bowls, gold accents", lighting: "single warm", objects: "bowls, boxes, chopsticks", music: "koto", scent: "urushi, wood" },
    snd: ["koto pluck", "brush on lacquer"],
    dna: { mi: 55, og: 70, wc: 20, ns: 10, ad: 5, hf: 10, rr: 15, ps: 25, sh: 25, ql: 15, oc: 10, ds: 55, rs: 20, eu: 90, np: 45 },
    emo: { warm: 65, cold: 30, playful: 15, serious: 80, chaotic: 5, ordered: 90, nostalgic: 75, futuristic: 10, peaceful: 65, ominous: 10 },
  },
  {
    n: "Edo Kiriko cut glass", a: ["江戸切子", "Edo cut crystal"],
    cat: "Textile & Craft", c: "Cut glass", e: "regional_tradition", o: "Edo (Tokyo)", g: "Japan",
    p: "1834 to present", era: "late Edo to present",
    sum: "Tokyo's cut crystal — nanako fish-roe grids, star-baskets and chrysanthemum facets in cobalt over clear.",
    desc: "Edo Kiriko began when Edo glassmasters learned European cutting: colored cased glass (cobalt, ruby over clear) carved with geometric fans — nanako fish-roe stipple, yasuri-bishi diamond lattice, kiku chrysanthemums — into prisms that fracture light. Meiji-era exports refined it; today's masters (National Living Treasures) hand-cut every facet on stone wheels. Sip sake from one and the rim shatters light. The look: jewel geometry, facet sparkle, deep color skin over clear core.",
    col: [{ h: "#1c5d99", n: "cased cobalt" }, { h: "#8e3b46", n: "cased ruby" }, { h: "#f2ead9", n: "clear core" }, { h: "#d4af37", n: "light gold glint" }],
    m: ["cased glass", "stone cutting wheels", "diamond paste"],
    tx: ["facet prisms", "fish-roe stipple", "color-over-clear"],
    obj: ["guinomi sake cups", "whiskey glasses", "star-cut decanters"],
    ex: ["Asakusa kiriko studios", "National Living Treasure masters", "Sumida Edo Kiriko Kan"],
    inf: ["European cut crystal"], rel: ["Rishtan ceramics", "Murano glass", "Bohemian crystal"],
    par: "", var: ["nanako", "kagome lattice", "chrysanthemum cut"], cf: ["Bohemian crystal"],
    src: [{ n: "Wikipedia — Edo Kiriko", u: "https://en.wikipedia.org/wiki/Edo_Kiriko", t: "B" }],
    tg: ["cut glass", "edo", "facets", "crystal", "tokyo"], pop: 24, niche: false,
    vd: { shape: "banded facet geometry", line: "wheel-cut precision", composition: "rim-to-base zones", texture: "prismatic sparkle", forms: "grids, stars, rosettes" },
    typ: { display: "mincho serif", body: "humanist sans", notes: "gift-box label" },
    lit: { quality: "refracted sparkle", direction: "multi", temperature: "neutral", shadow: "prism split" },
    ui: { background: "dark", surface: "facet-gloss cards", components: "crystal buttons", motion: "light fracture" },
    rec: { materials: "cut glass, dark cloth", lighting: "single beam", objects: "cups, decanters", music: "quiet koto", scent: "sake, glass" },
    snd: ["glass chime", "wheel whir"],
    dna: { mi: 55, og: 90, wc: 25, ns: 20, ad: 5, hf: 20, rr: 15, ps: 35, sh: 30, ql: 20, oc: 10, ds: 60, rs: 15, eu: 90, np: 35 },
    emo: { warm: 55, cold: 40, playful: 30, serious: 70, chaotic: 5, ordered: 95, nostalgic: 65, futuristic: 20, peaceful: 55, ominous: 5 },
  },
  {
    n: "Netsuke carving", a: ["根付", "netsuke toggles"],
    cat: "Textile & Craft", c: "Miniature carving", e: "historical", o: "Edo Japan", g: "Japan, world collections",
    p: "17th-19th century", era: "Edo period",
    sum: "Pocket-sized toggles — rats, masks, gourds and demons carved in ivory and wood, functional sculpture.",
    desc: "Netsuke anchored inro medicine cases to kimono sashes — and became Edo Japan's miniature sculpture: rats gnawing soybeans, gourds with frogs inside, thunder gods laughing, all in ivory, boxwood, stag antler, finished with himotoshi cord holes. Carvers signed the bases; subjects wove humor, superstition and literati taste into palm-size form. Meiji-era collectors (Gonse, Bing) exported thousands; auction houses still fight over masterpiece carvers (Miwa, Masanao). The look: worn-smooth miniature life, patina of touch.",
    col: [{ h: "#5c4033", n: "boxwood brown" }, { h: "#c49a6c", n: "aged ivory" }, { h: "#3d2b1f", n: "antler dark" }, { h: "#d4af37", n: "inlay gold" }],
    m: ["ivory (historic)", "boxwood", "stag antler", "mother-of-pearl inlay"],
    tx: ["hand-worn patina", "fine detail carving", "smooth miniature"],
    obj: ["animal toggles", "kagami-buta mirror lids", "signed masterpieces"],
    ex: ["Masanao school netsuke", "British Museum collections", "Auktion masterpiece sales"],
    inf: ["Edo craft culture"], rel: ["Urushi lacquerware", "Ashanti goldweights", "Netsuke carving"],
    par: "", var: ["katabori (3D)", "men-gashira (mask)", "sashi (long)"], cf: ["Ashanti goldweights"],
    src: [{ n: "Wikipedia — Netsuke", u: "https://en.wikipedia.org/wiki/Netsuke", t: "B" }],
    tg: ["miniature", "edo", "carving", "ivory", "toggle"], pop: 22, niche: false,
    vd: { shape: "palm-size figure knots", line: "fine chisel detail", composition: "single-object wit", texture: "worn patina", forms: "rats, masks, gourds" },
    typ: { display: "serif", body: "humanist sans", notes: "auction catalog" },
    lit: { quality: "case spot", direction: "raking", temperature: "warm", shadow: "miniature orbit" },
    ui: { background: "dark", surface: "figure-plinth cards", components: "round buttons", motion: "rotate toggle" },
    rec: { materials: "replica netsuke, silk cords", lighting: "spot", objects: "toggles, inro", music: "shamisen", scent: "wood, silk" },
    snd: ["shamisen", "soft cord slide"],
    dna: { mi: 50, og: 80, wc: 20, ns: 5, ad: 5, hf: 8, rr: 20, ps: 45, sh: 25, ql: 20, oc: 15, ds: 45, rs: 20, eu: 85, np: 40 },
    emo: { warm: 70, cold: 25, playful: 55, serious: 55, chaotic: 10, ordered: 85, nostalgic: 75, futuristic: 8, peaceful: 55, ominous: 10 },
  },
  {
    n: "Bizen ware", a: ["備前焼", "Bizen-yaki"],
    cat: "Textile & Craft", c: "Wood-fired stoneware", e: "regional_tradition", o: "Bizen, Okayama", g: "Japan",
    p: "medieval to present", era: "tea ceramics",
    sum: "Unglazed wood-fired stoneware — kiln ambushes of ash, rice-straw red and hidasuki scorch, each firing a lottery.",
    desc: "Bizen potters glaze nothing: clay from local paddies, fired 12 days in climbing kilns where falling ash, ember paths and rice-straw wraps ('hidasuki' red scorch) paint each pot by chance — goma sesame ash pools, sangiri smoky bands, hi-iro fire colors. Tea masters prized the tactile earthiness; no two firings repeat. The look: bark-rough earth skin, accidental beauty the kiln authors.",
    col: [{ h: "#8b5a2b", n: "clay amber" }, { h: "#3d2b1f", n: "smoke black" }, { h: "#a0522d", n: "hidasuki red" }, { h: "#c49a6c", n: "goma ash" }],
    m: ["iron-rich clay", "rice straw", "red pine fuel", "anagama kilns"],
    tx: ["ash-kissed crust", "straw scorch", "kiln randomness"],
    obj: ["tea bowls", "mizusashi jars", "vases", "hibachi"],
    ex: ["Bizen traditional kilns", "tea master favorite bowls", "Momoyama-era classics"],
    inf: ["Sue ware tradition"], rel: ["Shino ware", "Karatsu ware", "Kintsugi repair"],
    par: "", var: ["hidasuki", "goma", "sangiri", "hi-iro"], cf: ["Shino ware"],
    src: [{ n: "Wikipedia — Bizen ware", u: "https://en.wikipedia.org/wiki/Bizen_ware", t: "B" }],
    tg: ["pottery", "bizen", "woodfire", "unglazed", "wabi"], pop: 18, niche: true,
    vd: { shape: "muscular tea bowl curves", line: "accidental streaks", composition: "kiln-painted fields", texture: "stony roughness", forms: "scorch bands, ash pools" },
    typ: { display: "mincho serif", body: "humanist sans", notes: "exhibit label" },
    lit: { quality: "earthy warm", direction: "raking", temperature: "warm", shadow: "texture shadow" },
    ui: { background: "earth", surface: "clay-texture cards", components: "stone buttons", motion: "ember glow" },
    rec: { materials: "bizen bowls, wooden shelves", lighting: "warm", objects: "bowls, jars", music: "shakuhachi", scent: "smoke, clay" },
    snd: ["kiln crackle", "bowl tap"],
    dna: { mi: 55, og: 85, wc: 15, ns: 5, ad: 5, hf: 8, rr: 45, ps: 20, sh: 35, ql: 15, oc: 30, ds: 40, rs: 15, eu: 70, np: 35 },
    emo: { warm: 75, cold: 20, playful: 15, serious: 70, chaotic: 25, ordered: 70, nostalgic: 70, futuristic: 5, peaceful: 65, ominous: 10 },
  },
  {
    n: "Shino ware", a: ["志野焼", "Shino-yaki"],
    cat: "Textile & Craft", c: "Glazed stoneware", e: "historical", o: "Mino, Gifu", g: "Japan",
    p: "16th century Momoyama", era: "tea ceramics",
    sum: "Thick white feldspar glaze — milky skins scorching to orange fire-colors, tea bowl holy grail.",
    desc: "Shino's magic is its glaze: heavy feldspar slurry painted thick, fired slow, blooming into milky white that traps iron blushes — orange fire-edges (hi-iro), red brush figures under the glaze, pinholes and crawl that tea masters read as landscape. Momoyama kilns at Mino made the classics; 20th-century potters (Arakawa Toyozo) rediscovered the forgotten formula, re-igniting the style. The look: soft cream skin with living fire beneath.",
    col: [{ h: "#f2ead9", n: "shino white" }, { h: "#e07b39", n: "hi-iro orange" }, { h: "#8e3b46", n: "onitate red" }, { h: "#c49a6c", n: "warm rim" }],
    m: ["iron-bearing clay", "feldspar glaze", "wood kiln"],
    tx: ["milky glaze skin", "crawl and pinhole", "fire blush"],
    obj: ["tea bowls (chawan)", "mukozuke dishes", "vases"],
    ex: ["Kizaemon tea bowl", "Mino kiln classics", "Arakawa Toyozo revival"],
    inf: ["Seto ware tradition"], rel: ["Oribe ware", "Bizen ware", "Kintsugi repair"],
    par: "", var: ["white shino", "onitate red-figure", "aka shino"], cf: ["Oribe ware"],
    src: [{ n: "Wikipedia — Shino ware", u: "https://en.wikipedia.org/wiki/Shino_ware", t: "B" }],
    tg: ["pottery", "shino", "white glaze", "tea", "wabi"], pop: 16, niche: true,
    vd: { shape: "soft asymmetric bowls", line: "brush-red figures", composition: "glaze-led chance", texture: "milky skin", forms: "grasses, fire edges" },
    typ: { display: "mincho serif", body: "humanist sans", notes: "tea-label" },
    lit: { quality: "soft daylight", direction: "even", temperature: "warm", shadow: "crawl shadow" },
    ui: { background: "cream", surface: "glaze-texture cards", components: "round buttons", motion: "slow bloom" },
    rec: { materials: "shino bowls", lighting: "soft", objects: "bowls, grass arrangements", music: "shakuhachi", scent: "clay, tea" },
    snd: ["tea pour", "bowl set down"],
    dna: { mi: 60, og: 80, wc: 15, ns: 5, ad: 5, hf: 8, rr: 35, ps: 20, sh: 20, ql: 12, oc: 25, ds: 40, rs: 15, eu: 75, np: 35 },
    emo: { warm: 75, cold: 20, playful: 15, serious: 70, chaotic: 20, ordered: 75, nostalgic: 75, futuristic: 5, peaceful: 70, ominous: 5 },
  },
  {
    n: "Oribe ware", a: ["織部焼", "Oribe-yaki"],
    cat: "Textile & Craft", c: "Glazed stoneware", e: "historical", o: "Mino, Gifu", g: "Japan",
    p: "1600s", era: "early Edo",
    sum: "Green-copper glaze and playful geometry — warped dishes, grid-and-grass patterns from Furuta Oribe's taste.",
    desc: "Oribe ware carries tea master Furuta Oribe's taste: bold copper-green glaze splashed over white slip, painted grasses, checkered grids and fans on oddly warped dishes — asymmetry and wit over refinement. Kutsu-gata (shoe-shaped) bowls, black-and-white 'kuro-oribe' cousins, and over-the-edge compositions broke rules deliciously. The look: green pools, jazz-angled forms, pattern play.",
    col: [{ h: "#2a9d8f", n: "copper green" }, { h: "#f2ead9", n: "slip white" }, { h: "#1a1a1a", n: "iron black" }, { h: "#8b5a2b", n: "grass brown" }],
    m: ["iron clay", "copper glaze", "white slip", "wood kiln"],
    tx: ["glassy green pools", "brush pattern", "warped planes"],
    obj: ["kutsu-gata dishes", "green-glazed bowls", "pattern plates"],
    ex: ["Mino oribe kilns", "tea ceremony dish sets", "Edo museum corpora"],
    inf: ["Shino ware", "tea master aesthetics"], rel: ["Shino ware", "Bizen ware", "Kutani ware"],
    par: "", var: ["ao-oribe (green)", "kuro-oribe (black)"], cf: ["Shino ware"],
    src: [{ n: "Wikipedia — Oribe ware", u: "https://en.wikipedia.org/wiki/Oribe_ware", t: "B" }],
    tg: ["pottery", "oribe", "green glaze", "tea", "playful"], pop: 14, niche: true,
    vd: { shape: "warped dish planes", line: "bold grid + grass", composition: "asymmetric over-edge", texture: "green gloss", forms: "checks, fans, grasses" },
    typ: { display: "mincho serif", body: "humanist sans", notes: "tea-label" },
    lit: { quality: "bright", direction: "even", temperature: "neutral", shadow: "gloss sheen" },
    ui: { background: "white", surface: "green-pool cards", components: "grid buttons", motion: "glaze pour" },
    rec: { materials: "oribe dishes", lighting: "bright", objects: "dishes, grass ikebana", music: "koto", scent: "green tea" },
    snd: ["koto", "dish clink"],
    dna: { mi: 45, og: 75, wc: 20, ns: 10, ad: 5, hf: 10, rr: 30, ps: 50, sh: 25, ql: 30, oc: 30, ds: 55, rs: 20, eu: 70, np: 40 },
    emo: { warm: 65, cold: 30, playful: 60, serious: 40, chaotic: 25, ordered: 70, nostalgic: 65, futuristic: 10, peaceful: 55, ominous: 5 },
  },
  {
    n: "Kutani ware", a: ["九谷焼", "Kutani-yaki"],
    cat: "Textile & Craft", c: "Overglaze porcelain", e: "regional_tradition", o: "Kutani, Ishikawa", g: "Japan",
    p: "1655 to present", era: "Edo to present",
    sum: "Paint-everywhere porcelain — dense 'aka-e kinrante' red-gold crowds, green-blue-yellow-purple enamel at war.",
    desc: "Kutani fires porcelain then paints it over the glaze in enamel: the old 'ao-kutani' favored green, blue, yellow and purple garden landscapes; the later 'aka-e' style crowds dishes with red figures and vast gold ('kinrante') until nothing rests. Both extremes define it — maximalist Japanese enamel. Meiji exports conquered world expositions; modern kilns keep both modes. The look: porcelain gone operatic — color upon color, gold upon red.",
    col: [{ h: "#8e3b46", n: "aka-e red" }, { h: "#d4af37", n: "kinrante gold" }, { h: "#2d6a4f", n: "ao-kutani green" }, { h: "#1c5d99", n: "enamel blue" }, { h: "#ffd60a", n: "enamel yellow" }],
    m: ["porcelain body", "enamel overglaze", "gold paint", "muffle kiln"],
    tx: ["dense enamel field", "gold flood", "glossy finish"],
    obj: ["figure plates", "gold-storm chargers", "sake cups"],
    ex: ["Kutani classic kilns", "Meiji export wares", "modern Kutani yaki studios"],
    inf: ["Arita/Imari ware", "Chinese famille rose"], rel: ["Imari ware", "Oribe ware", "Famille rose"],
    par: "", var: ["ao-kutani", "aka-e", "yoshidaya style"], cf: ["Imari ware"],
    src: [{ n: "Wikipedia — Kutani ware", u: "https://en.wikipedia.org/wiki/Kutani_ware", t: "B" }],
    tg: ["porcelain", "kutani", "enamel", "gold", "maximal"], pop: 16, niche: true,
    vd: { shape: "crowded plate fields", line: "enamel fine brush", composition: "border-to-center flood", texture: "enamel sheen", forms: "figures, flowers, clouds" },
    typ: { display: "mincho serif", body: "humanist sans", notes: "gift label" },
    lit: { quality: "bright", direction: "even", temperature: "warm", shadow: "gloss" },
    ui: { background: "white", surface: "red-gold cards", components: "round buttons", motion: "color flood" },
    rec: { materials: "plates on stands", lighting: "bright", objects: "chargers, cups", music: "koto ensemble", scent: "tea" },
    snd: ["koto", "porcelain chime"],
    dna: { mi: 15, og: 65, wc: 15, ns: 15, ad: 5, hf: 10, rr: 15, ps: 55, sh: 30, ql: 55, oc: 25, ds: 90, rs: 20, eu: 80, np: 40 },
    emo: { warm: 75, cold: 20, playful: 55, serious: 50, chaotic: 25, ordered: 70, nostalgic: 70, futuristic: 10, peaceful: 40, ominous: 5 },
  },
  {
    n: "Imari ware", a: ["有田焼", "Arita ware", "Imari porcelain"],
    cat: "Textile & Craft", c: "Export porcelain", e: "historical", o: "Arita, Kyushu", g: "Japan, Europe (trade)",
    p: "1616 onward", era: "Edo export",
    sum: "Japan's porcelain capital — underglaze blue plus enamel red-gold, the 'Old Imari' that electrified Europe.",
    desc: "When Korean potter Yi Sam-pyeong found kaolin at Arita (1616), Japan gained porcelain: early underglaze blue was joined by vibrant overglaze red-and-gold ('aka-e') that Europe devoured as 'Imari' (shipped via Imari port) — VOC trade flooded Dutch still-lifes and palaces; Meissen stole the formula. Kakiemon's airy asymmetry and Ko-Imari's dense radial medallions are twin canons. The look: glowing red-gold-blue porcelains — Japan's first global design brand.",
    col: [{ h: "#1c5d99", n: "underglaze blue" }, { h: "#8e3b46", n: "enamel red" }, { h: "#d4af37", n: "gilding" }, { h: "#f5f0e6", n: "porcelain white" }],
    m: ["kaolin (Amakusa)", "cobalt underglaze", "enamel overglaze", "gold"],
    tx: ["porcelain gloss", "enamel relief", "gold shimmer"],
    obj: ["chargers", "figural bottles", "dinner services"],
    ex: ["Kakiemon kiln classics", "VOC-trade wares in Delft portraits", "Arita contemporary studios"],
    inf: ["Jingdezhen blue-and-white porcelain", "Korean potters"], rel: ["Kutani ware", "Delftware", "Jingdezhen blue-and-white porcelain"],
    par: "", var: ["Ko-Imari", "Kakiemon", "Nabeshima"], cf: ["Kutani ware"],
    src: [{ n: "Wikipedia — Imari ware", u: "https://en.wikipedia.org/wiki/Imari_ware", t: "B" }],
    tg: ["porcelain", "imari", "export", "red-gold", "arita"], pop: 24, niche: false,
    vd: { shape: "radial medallion plates", line: "enamel fine contour", composition: "dense border floods", texture: "porcelain gloss", forms: "peonies, phoenixes, chrysanthemums" },
    typ: { display: "mincho serif", body: "humanist sans", notes: "export label" },
    lit: { quality: "bright", direction: "even", temperature: "warm", shadow: "gloss" },
    ui: { background: "white", surface: "red-gold-blue cards", components: "round buttons", motion: "glaze sheen" },
    rec: { materials: "plates on stands", lighting: "bright", objects: "chargers, vases", music: "koto", scent: "tea" },
    snd: ["koto", "porcelain chime"],
    dna: { mi: 25, og: 70, wc: 15, ns: 15, ad: 5, hf: 10, rr: 15, ps: 50, sh: 30, ql: 50, oc: 20, ds: 85, rs: 20, eu: 80, np: 40 },
    emo: { warm: 75, cold: 20, playful: 45, serious: 55, chaotic: 20, ordered: 80, nostalgic: 70, futuristic: 10, peaceful: 45, ominous: 5 },
  },
  {
    n: "Sukiya-zukuri teahouse", a: ["数寄屋造り", "tea house architecture"],
    cat: "Architectural Style", c: "Tea architecture", e: "historical", o: "Japan", g: "Japan",
    p: "16th century onward", era: "Momoyama tea culture",
    sum: "Tea architecture as wabi — small, dark, irregular: clay walls, round windows, one perfect imperfection.",
    desc: "Sukiya-zukuri distills tea aesthetics into a few tatami mats: clay-and-bamboo walls, dark-polished pillars beside rough bark ones, shoji and round 'katto-mado' windows cropped like paintings, ceiling heights varied, a single nail-head left raw — refined rusticity (wabi) engineered with total control. Katsura Imperial Villa's shoin-teahouses canonized the type; Frank Lloyd Wright and modernists stole its lessons. The look: dim, quiet, asymmetric geometry — architecture of breath.",
    col: [{ h: "#5c4033", n: "dark pillar" }, { h: "#d9c7a7", n: "clay wall" }, { h: "#f2ead9", n: "shoji paper" }, { h: "#2d6a4f", n: "garden moss (view)" }],
    m: ["clay walls (tsuchikabe)", "cedar and bamboo", "shoji paper", "tatami"],
    tx: ["matte clay", "dark pillar sheen", "paper glow"],
    obj: ["nijiriguchi crawl doors", "round windows", "tokonoma alcoves", "roji garden paths"],
    ex: ["Katsura Imperial Villa", "Tai-an teahouse (Sen no Rikyū)", "Kyoto tea houses"],
    inf: ["shoin-zukuri architecture", "wabi-sabi philosophy"], rel: ["Shoin-zukuri", "Karesansui", "Tea ceremony aesthetics"],
    par: "", var: ["soan (grass hut)", "shoin-sukiya hybrid"], cf: ["Shoin-zukuri"],
    src: [{ n: "Wikipedia — Sukiya-zukuri", u: "https://en.wikipedia.org/wiki/Sukiya-zukuri", t: "B" }],
    tg: ["tea house", "wabi", "architecture", "japan", "quiet"], pop: 20, niche: false,
    vd: { shape: "small irregular boxes", line: "mixed rough-refined", composition: "framed garden views", texture: "clay + wood", forms: "windows, alcoves, paths" },
    typ: { display: "mincho serif", body: "humanist sans", notes: "calligraphy scroll" },
    lit: { quality: "dim, paper-diffused", direction: "low side", temperature: "warm", shadow: "deep quiet" },
    ui: { background: "paper cream", surface: "clay-texture cards", components: "thin-line buttons", motion: "breath-slow fade" },
    rec: { materials: "tatami, shoji, clay", lighting: "paper diffused", objects: "scroll, ikebana, kettle", music: "shakuhachi", scent: "tatami, charcoal" },
    snd: ["kettle simmer", "water scoop"],
    dna: { mi: 85, og: 70, wc: 20, ns: 5, ad: 5, hf: 5, rr: 35, ps: 15, sh: 15, ql: 8, oc: 20, ds: 20, rs: 10, eu: 85, np: 40 },
    emo: { warm: 60, cold: 30, playful: 10, serious: 75, chaotic: 10, ordered: 85, nostalgic: 70, futuristic: 5, peaceful: 90, ominous: 5 },
  },
  {
    n: "Shoin-zukuri", a: ["書院造", "study hall architecture"],
    cat: "Architectural Style", c: "Samurai residence", e: "historical", o: "Muromachi Japan", g: "Japan",
    p: "14th-16th century onward", era: "Muromachi to Edo",
    sum: "The samurai elite's hall plan — tokonoma alcoves, tatami grids and sliding panels that seeded all Japanese interiors.",
    desc: "Shoin-zukuri formalized elite interiors: irregular-but-ordered tatami layouts, the tokonoma display alcove with hanging scroll and ikebana, chigaidana staggered shelves, shoin study windows, and fusuma/sudare sliding layers — the blueprint for every later Japanese room including teahouses and modern tatami hotels. Ninomaru palace at Nijō and Katsura villa carry the canon. The look: disciplined emptiness where objects are chosen like poems.",
    col: [{ h: "#5c4033", n: "wood frame" }, { h: "#f2ead9", n: "shoji white" }, { h: "#2d6a4f", n: "fusuma green" }, { h: "#d9c7a7", n: "tatami" }],
    m: ["tatami", "fusuma panels", "tokonoma posts", "gold-leaf screens (elite)"],
    tx: ["paper softness", "smooth wood", "mat sliding"],
    obj: ["tokonoma alcoves", "chigaidana shelves", "fusuma screens", "engawa verandas"],
    ex: ["Nijō Castle Ninomaru", "Katsura Imperial Villa", "Kyoto temple shoin halls"],
    inf: ["Zen temple architecture"], rel: ["Sukiya-zukuri teahouse", "Karesansui", "Furisode"],
    par: "", var: ["honshoin", "chumon shoin"], cf: ["Sukiya-zukuri teahouse"],
    src: [{ n: "Wikipedia — Shoin-zukuri", u: "https://en.wikipedia.org/wiki/Shoin-zukuri", t: "B" }],
    tg: ["interior", "shoin", "tatami", "samurai", "japan"], pop: 16, niche: true,
    vd: { shape: "mat-grid rooms", line: "panel frame rhythm", composition: "alcove-anchored asymmetry", texture: "paper + wood", forms: "alcoves, screens, shelves" },
    typ: { display: "mincho serif", body: "humanist sans", notes: "scroll pairing" },
    lit: { quality: "soft paper-diffused", direction: "side", temperature: "warm", shadow: "gentle" },
    ui: { background: "paper", surface: "panel-grid cards", components: "thin-frame buttons", motion: "slide panel" },
    rec: { materials: "tatami, scroll, ikebana", lighting: "paper diffused", objects: "scrolls, screens, kettle", music: "koto", scent: "tatami, incense" },
    snd: ["koto", "sliding rail"],
    dna: { mi: 80, og: 65, wc: 20, ns: 5, ad: 5, hf: 5, rr: 25, ps: 15, sh: 12, ql: 8, oc: 12, ds: 20, rs: 10, eu: 88, np: 35 },
    emo: { warm: 60, cold: 30, playful: 10, serious: 75, chaotic: 5, ordered: 90, nostalgic: 70, futuristic: 5, peaceful: 85, ominous: 5 },
  },
  {
    n: "Gasshō-zukuri farmhouses", a: ["合掌造り", "Shirakawa-go minka"],
    cat: "Architectural Style", c: "Vernacular farmhouse", e: "regional_tradition", o: "Shirakawa-gō, Gifu", g: "Japan",
    p: "17th-19th century", era: "mountain vernacular",
    sum: "Prayer-hands thatched roofs — steep 60° gables of shirakawa-go, rebuilt by whole villages in a day.",
    desc: "Gasshō-zukuri ('prayer-hand construction') roofs pitch at 60° to shed heavy snow: massive A-frame gables of bundled susuki thatch, three or four stories tall, housing extended families and silkworm lofts under the ridge. Villages like Shirakawa-gō and Ainokura (UNESCO) cluster them along rivers; roof re-thatching is a whole-village ritual (yui). The look: towering thatch prayer-hands over snow, smoked-dark interiors, human-scale cathedrals.",
    col: [{ h: "#c49a6c", n: "thatch gold" }, { h: "#3d2b1f", n: "beam dark" }, { h: "#f5f0e6", n: "snow white" }, { h: "#2d6a4f", n: "valley green" }],
    m: ["susuki thatch", "cedar beams", "rope lashings", "smoked interior wood"],
    tx: ["thatch depth", "smoke-dark beams", "snow cap"],
    obj: ["steep gable roofs", "sericulture lofts", "sunken hearths (irori)"],
    ex: ["Shirakawa-gō (UNESCO)", "Ainokura village", "Wada House"],
    inf: ["minka vernacular tradition"], rel: ["Kyoto machiya", "Svaneti tower houses", "Karesansui"],
    par: "", var: ["Ogimachi type", "Ainokura type"], cf: ["alpine chalets"],
    src: [{ n: "Wikipedia — Gasshō-zukuri", u: "https://en.wikipedia.org/wiki/Gass%C5%8D-zukuri", t: "B" }],
    tg: ["vernacular", "thatch", "snow", "unesco", "japan"], pop: 24, niche: false,
    vd: { shape: "steep A-frame gables", line: "thatch layer rows", composition: "river-valley clusters", texture: "thatch grain", forms: "prayer-hands, lofts, hearths" },
    typ: { display: "humanist serif", body: "humanist sans", notes: "travel-postcard" },
    lit: { quality: "hearth flicker", direction: "center irori", temperature: "warm", shadow: "loft dark" },
    ui: { background: "snow", surface: "thatch-texture cards", components: "beam buttons", motion: "snow settle" },
    rec: { materials: "wood models, thatch prints", lighting: "irori warm", objects: "farmhouse stays, pickles", music: "shakuhachi", scent: "smoke, thatch" },
    snd: ["irori fire", "snow silence"],
    dna: { mi: 55, og: 75, wc: 30, ns: 5, ad: 5, hf: 5, rr: 40, ps: 25, sh: 35, ql: 15, oc: 25, ds: 35, rs: 10, eu: 70, np: 45 },
    emo: { warm: 80, cold: 25, playful: 20, serious: 60, chaotic: 15, ordered: 80, nostalgic: 80, futuristic: 5, peaceful: 75, ominous: 5 },
  },
  {
    n: "Kyoto machiya", a: ["町家", "Kyoto townhouse"],
    cat: "Architectural Style", c: "Merchant townhouse", e: "regional_tradition", o: "Kyoto", g: "Japan",
    p: "Edo to present", era: "living vernacular",
    sum: "Sleeping eel façades — narrow, deep wooden shops with lattice fronts, inner courts and hidden gardens.",
    desc: "Machiya are Kyoto's merchant houses: narrow street fronts (tax was once frontage-width), deep 'unagi no nedoko' eel-bed plans running back 20+ meters,degōshi wooden lattice fronts, mud-wall warehouses (kura) at the street, and sunken tsuboniwa courtyards breathing light and air through the spine. Renovation hotels and cafés recycle them; Kyoto city now subsidizes preservation. The look: dim lattice rhythm, wood-brine patina, courtyard green glow.",
    col: [{ h: "#5c4033", n: "aged wood" }, { h: "#3d2b1f", n: "lattice dark" }, { h: "#d9c7a7", n: "mud wall" }, { h: "#2d6a4f", n: "courtyard moss" }],
    m: ["cedar and cypress", "degoshi lattices", "mud walls", "tile roofs"],
    tx: ["lattice rhythm", "wood patina", "courtyard light shaft"],
    obj: ["degōshi lattice fronts", "tsuboniwa courtyards", "kura storehouses", "noren curtains"],
    ex: ["Nishiki district machiya", "renovated machiya stays", "Kyoto preservation programs"],
    inf: ["merchant urbanism"], rel: ["Gasshō-zukuri farmhouses", "Sukiya-zukuri teahouse", "Hadhrami architecture"],
    par: "", var: ["shop-front type", "oya-ya main house"], cf: ["shophouse (qilou)"],
    src: [{ n: "Wikipedia — Machiya", u: "https://en.wikipedia.org/wiki/Machiya", t: "B" }],
    tg: ["townhouse", "kyoto", "lattice", "courtyard", "japan"], pop: 22, niche: false,
    vd: { shape: "narrow-deep section", line: "lattice verticals", composition: "street-to-garden spine", texture: "wood + clay", forms: "lattices, courts, noren" },
    typ: { display: "mincho serif", body: "humanist sans", notes: "noren branding" },
    lit: { quality: "courtyard bounce", direction: "deep spine", temperature: "warm", shadow: "lattice stripes" },
    ui: { background: "cream", surface: "lattice-pattern cards", components: "slat buttons", motion: "curtain sway" },
    rec: { materials: "wood textures, noren", lighting: "courtyard", objects: "noren, tea, ceramics", music: "koto", scent: "wood, tea" },
    snd: ["bicycle bell", "rail slide"],
    dna: { mi: 65, og: 65, wc: 25, ns: 5, ad: 5, hf: 8, rr: 35, ps: 25, sh: 25, ql: 12, oc: 20, ds: 30, rs: 10, eu: 75, np: 45 },
    emo: { warm: 75, cold: 20, playful: 20, serious: 65, chaotic: 10, ordered: 85, nostalgic: 80, futuristic: 8, peaceful: 70, ominous: 5 },
  },
  {
    n: "Karesansui dry garden", a: ["枯山水", "Zen rock garden", "karesansui"],
    cat: "Architectural Style", c: "Garden & landscape", e: "historical", o: "Muromachi Kyoto", g: "Japan",
    p: "14th-16th century", era: "Zen culture",
    sum: "Raked gravel oceans and stone islands — abstraction as meditation at Ryōan-ji and Daisen-in.",
    desc: "Karesansui ('dry landscape') replaces water with suggestion: raked gravel patterns stand for rivers and seas, grouped stones for islands and mountains, clipped shrubs for hills — designed to be viewed from a veranda, not walked. Ryōan-ji's fifteen stones famously yield only fourteen views from any seat; Daisen-in's gravel river tells a life journey. Abbot-gardners (Musō Soseki lineage) composed them as Zen practice. The look: grey-white stillness, green cliffs of moss, space as substance.",
    col: [{ h: "#d9d2c5", n: "gravel grey" }, { h: "#2d6a4f", n: "moss green" }, { h: "#5c4033", n: "stone dark" }, { h: "#f2ead9", n: "wall white" }],
    m: ["raked gravel", "set stones", "moss", "clay walls"],
    tx: ["comb-line gravel", "stone mass", "moss velvet"],
    obj: ["stone triads", "raked wave patterns", "moss islands", "veranda viewing seats"],
    ex: ["Ryōan-ji", "Daisen-in", "Ginkaku-ji sand cone"],
    inf: ["Chinese Song ink painting", "Zen practice"], rel: ["Sukiya-zukuri teahouse", "Charbagh garden", "Tsubo-niwa courtyard garden"],
    par: "", var: ["flat stone type", "hill-and-pond derivative"], cf: ["Charbagh garden"],
    src: [{ n: "Wikipedia — Karesansui", u: "https://en.wikipedia.org/wiki/Japanese_dry_garden", t: "B" }],
    tg: ["zen", "garden", "gravel", "abstraction", "japan"], pop: 46, niche: false,
    vd: { shape: "island-stone masses", line: "raked water rhythms", composition: "asymmetric triads", texture: "gravel finesse", forms: "stones, moss, waves" },
    typ: { display: "mincho serif", body: "humanist sans", notes: "scroll captions" },
    lit: { quality: "morning side-light", direction: "low east", temperature: "neutral", shadow: "stone long" },
    ui: { background: "pale grey", surface: "stone-grid cards", components: "stone buttons", motion: "rake wave" },
    rec: { materials: "fine gravel, moss, stones", lighting: "morning", objects: "miniature gravel trays", music: "shakuhachi", scent: "moss, cedar" },
    snd: ["rake on gravel", "distant temple bell"],
    dna: { mi: 95, og: 70, wc: 30, ns: 5, ad: 5, hf: 5, rr: 30, ps: 10, sh: 10, ql: 5, oc: 15, ds: 15, rs: 15, eu: 90, np: 35 },
    emo: { warm: 50, cold: 40, playful: 5, serious: 80, chaotic: 5, ordered: 90, nostalgic: 60, futuristic: 5, peaceful: 95, ominous: 5 },
  },
  {
    n: "Tsubo-niwa courtyard garden", a: ["坪庭", "kyoto courtyard garden"],
    cat: "Architectural Style", c: "Micro garden", e: "regional_tradition", o: "Kyoto", g: "Japan",
    p: "Edo to present", era: "living tradition",
    sum: "Bottle-light micro gardens — a few square meters of stone, moss and lantern breathing through machiya spines.",
    desc: "Tsubo-niwa are courtyard gardens the size of a tatami or two, slotted into machiya depths for light and ventilation: one lantern, one stone group, moss, a maple or camellia, gravel raked or left — designed to be looked at from engawa and kitchen, not entered. Modern townhouses and even offices build them for biophilic breath. The look: compressed cosmos — all of karesansui's calm in a bottle of light.",
    col: [{ h: "#2d6a4f", n: "moss green" }, { h: "#5c4033", n: "stone grey" }, { h: "#d9d2c5", n: "gravel pale" }, { h: "#8a9a5b", n: "leaf green" }],
    m: ["stone lanterns", "moss and fern", "gravel", "single specimen tree"],
    tx: ["moss velvet", "gravel finesse", "light shaft"],
    obj: ["stone lanterns", "tsukubai basins", "stone groupings", "single maple"],
    ex: ["Kyoto machiya courtyards", "Daitoku-ji subtemple courts", "modern tsuboniwa offices"],
    inf: ["karesansui abstraction"], rel: ["Karesansui", "Kyoto machiya", "Sukiya-zukuri teahouse"],
    par: "", var: ["moss type", "water basin type"], cf: ["Karesansui"],
    src: [{ n: "Wikipedia — Tsubo-niwa", u: "https://en.wikipedia.org/wiki/Tsubo-niwa", t: "B" }],
    tg: ["courtyard", "moss", "micro garden", "kyoto", "quiet"], pop: 16, niche: true,
    vd: { shape: "square micro-fields", line: "few confident strokes", composition: "corner-weighted", texture: "moss + stone", forms: "lantern, basin, tree" },
    typ: { display: "mincho serif", body: "humanist sans", notes: "quiet label" },
    lit: { quality: "bottle light", direction: "above shaft", temperature: "warm", shadow: "stone soft" },
    ui: { background: "pale", surface: "moss-texture cards", components: "stone buttons", motion: "leaf drop" },
    rec: { materials: "moss tray, lantern", lighting: "morning shaft", objects: "basin, moss, stone", music: "shakuhachi", scent: "moss, rain" },
    snd: ["dripping basin", "bird single"],
    dna: { mi: 90, og: 75, wc: 25, ns: 5, ad: 5, hf: 5, rr: 30, ps: 10, sh: 10, ql: 5, oc: 15, ds: 15, rs: 10, eu: 90, np: 35 },
    emo: { warm: 60, cold: 35, playful: 8, serious: 75, chaotic: 5, ordered: 90, nostalgic: 70, futuristic: 5, peaceful: 95, ominous: 5 },
  },
  {
    n: "Ikebana flower arrangement", a: ["生け花", "kado", "ikebana"],
    cat: "Regional & Cultural Tradition", c: "Flower art", e: "regional_tradition", o: "Japan", g: "Japan, global practice",
    p: "6th c offering to 15th c art", era: "living tradition",
    sum: "Line-first flower art — heaven, earth, human in asymmetric three-branch structures, space as material.",
    desc: "Ikebana ('living flowers') composes with line and emptiness: three main stems mapping heaven-earth-human (shin-soe-hikae or taller schools' variations), asymmetry, and visible water surface; styles range from rikka's towering Buddhist cosmograms to chabana's single bloom to Sogetsu's free sculpture. Schools (Ikenobō 15th-c origin, Ohara, Sogetsu) teach in dojos worldwide. The look: stems as calligraphy, space as paper, seasons as ink.",
    col: [{ h: "#2d6a4f", n: "stem green" }, { h: "#f2ead9", n: "bloom white" }, { h: "#c0392b", n: "camellia red" }, { h: "#5c4033", n: "vessel bronze" }],
    m: ["seasonal branches and blooms", "kenzan needle frogs", "ceramic and bronze vessels", "hasami shears"],
    tx: ["bare stem line", "water mirror", "bloom mass"],
    obj: ["three-branch structures", "tokonoma arrangements", "chabana tea flowers"],
    ex: ["Ikenobō rikka tradition", "Sogetsu free style", "tea ceremony chabana"],
    inf: ["Buddhist flower offerings"], rel: ["Bonsai", "Karesansui", "Sukiya-zukuri teahouse"],
    par: "", var: ["rikka", "shoka", "chabana", "jiyuka (free)"], cf: ["Western flower arranging"],
    src: [{ n: "Wikipedia — Ikebana", u: "https://en.wikipedia.org/wiki/Ikebana", t: "B" }],
    tg: ["flowers", "ikebana", "line", "seasons", "japan"], pop: 40, niche: false,
    vd: { shape: "asymmetric stem triangles", line: "branch-led calligraphy", composition: "space-embracing", texture: "stem + petal", forms: "lines, masses, voids" },
    typ: { display: "mincho serif", body: "humanist sans", notes: "school certificate" },
    lit: { quality: "tokonoma soft", direction: "side", temperature: "warm", shadow: "stem long" },
    ui: { background: "paper", surface: "bloom-accent cards", components: "stem-line buttons", motion: "branch grow" },
    rec: { materials: "seasonal stems, kenzan", lighting: "soft side", objects: "vases, shears, branches", music: "koto", scent: "cut stems, incense" },
    snd: ["shear snip", "water fill"],
    dna: { mi: 85, og: 85, wc: 20, ns: 5, ad: 5, hf: 10, rr: 25, ps: 20, sh: 12, ql: 8, oc: 20, ds: 15, rs: 15, eu: 90, np: 40 },
    emo: { warm: 60, cold: 35, playful: 20, serious: 70, chaotic: 10, ordered: 85, nostalgic: 70, futuristic: 15, peaceful: 90, ominous: 5 },
  },
  {
    n: "Bonsai", a: ["盆栽", "bonsai cultivation"],
    cat: "Regional & Cultural Tradition", c: "Tree art", e: "regional_tradition", o: "China (penjing) → Japan", g: "Japan, world hobby",
    p: "Chinese penjing roots; Japanese codified", era: "living tradition",
    sum: "Century trees in shallow pots — pines aged to mountains, wired branch by branch, patience as medium.",
    desc: "Bonsai grows full mountain-ancient trees in pots: pines, maples, junipers trained over decades by wiring, pruning, repotting, their trunks twisted like lightning, canopies cloud-pruned — style categories (chokkan upright, kengai cascade, shakan slant) codify ideals of age and struggle. Kokufu-ten exhibitions and Omiya village anchor the craft; penjing (China) remains the poetic ancestor. The look: miniature wilderness, time made visible, pot as horizon.",
    col: [{ h: "#2d6a4f", n: "pine green" }, { h: "#5c4033", n: "bark trunk" }, { h: "#8b6f47", n: "un-glazed pot" }, { h: "#c9a227", n: "moss accent" }],
    m: ["specimen trees", "copper wire", "bonsai shears", "shallow pots", "akadama soil"],
    tx: ["bark furrow", "cloud foliage pads", "moss carpet"],
    obj: ["upright pines", "cascade junipers", "display tokonoma sets", "tool kits"],
    ex: ["Kokufu-ten bonsai exhibition", "Omiya Bonsai Village", "Imperial Collection trees"],
    inf: ["Chinese penjing"], rel: ["Ikebana flower arrangement", "Karesansui", "Sukiya-zukuri teahouse"],
    par: "", var: ["chokkan", "kengai", "shakan", "forest style"], cf: ["penjing"],
    src: [{ n: "Wikipedia — Bonsai", u: "https://en.wikipedia.org/wiki/Bonsai", t: "B" }],
    tg: ["trees", "bonsai", "patience", "miniature", "japan"], pop: 46, niche: false,
    vd: { shape: "aged miniature silhouettes", line: "wired branch flow", composition: "pot-horizon balance", texture: "bark + moss", forms: "trunks, pads, deadwood" },
    typ: { display: "mincho serif", body: "humanist sans", notes: "exhibit tag" },
    lit: { quality: "morning garden", direction: "even", temperature: "neutral", shadow: "canopy dapple" },
    ui: { background: "pale", surface: "tree-silhouette cards", components: "leaf buttons", motion: "branch sway" },
    rec: { materials: "starter trees, wire, shears", lighting: "bright indirect", objects: "pots, turntables, moss", music: "shakuhachi", scent: "soil, pine" },
    snd: ["shear snip", "wire twist"],
    dna: { mi: 70, og: 85, wc: 20, ns: 5, ad: 5, hf: 5, rr: 30, ps: 25, sh: 15, ql: 8, oc: 15, ds: 20, rs: 10, eu: 90, np: 30 },
    emo: { warm: 65, cold: 30, playful: 20, serious: 70, chaotic: 10, ordered: 90, nostalgic: 70, futuristic: 8, peaceful: 90, ominous: 5 },
  },
  {
    n: "Furisode", a: ["振袖", "swinging-sleeve kimono"],
    cat: "Fashion & Dress", c: "Ceremonial kimono", e: "regional_tradition", o: "Japan", g: "Japan",
    p: "Edo code onward", era: "living tradition",
    sum: "The unmarried woman's kimono — sleeves to the floor, yuzen gardens of color, worn at Coming of Age.",
    desc: "Furisode announces youth and availability: sleeves (furi = swinging) hang 90-114cm, silk grounds blooming with yūzen-dyed seasons — cranes over waves, peonies in mist — gold embroidery at hems. Worn at seijin-shiki Coming of Age, weddings and graduations with matching obi and zōri, they are the most formal women's kimono below bridal. Photography days make them spectacle; vintage furisode are collector treasures. The look: cascading color gardens in motion.",
    col: [{ h: "#c0392b", n: "crane red" }, { h: "#1c5d99", n: "wave blue" }, { h: "#d4af37", n: "gold embroidery" }, { h: "#f2ead9", n: "silk ground" }, { h: "#2a9d8f", n: "pine green" }],
    m: ["silk crepe (chirimen)", "yūzen dyes", "gold thread", "obi sash"],
    tx: ["crepe pebble", "dyed gradients", "gold relief"],
    obj: ["long-sleeved kimono", "fukuro obi", "zōri sandals", "kanzashi hairpins"],
    ex: ["Seijin-shiki furisode", "Taishō-era vintage furisode", "Kyoto rental studios"],
    inf: ["yūzen dyeing", "Edo court dress codes"], rel: ["Yūzen dyeing", "Tomesode", "Kutani ware"],
    par: "", var: ["ōfurisode (grand)", "chūfurisode", "kofurisode"], cf: ["Tomesode"],
    src: [{ n: "Wikipedia — Furisode", u: "https://en.wikipedia.org/wiki/Furisode", t: "B" }],
    tg: ["kimono", "ceremonial", "sleeves", "japan", "youth"], pop: 28, niche: false,
    vd: { shape: "T-silhouette + trailing sleeves", line: "yuzen contour resist", composition: "seasonal garden fields", texture: "crepe silk", forms: "cranes, waves, blossoms" },
    typ: { display: "mincho serif", body: "humanist sans", notes: "kimono-registry" },
    lit: { quality: "bright event", direction: "all", temperature: "warm", shadow: "silk sheen" },
    ui: { background: "cream", surface: "garden-pattern cards", components: "bloom buttons", motion: "sleeve swirl" },
    rec: { materials: "silk kimono, obi", lighting: "bright", objects: "kimono, obi, kanzashi", music: "koto", scent: "incense, silk" },
    snd: ["silk swish", "geta clack"],
    dna: { mi: 30, og: 75, wc: 15, ns: 5, ad: 5, hf: 10, rr: 15, ps: 55, sh: 20, ql: 45, oc: 20, ds: 85, rs: 20, eu: 85, np: 45 },
    emo: { warm: 80, cold: 15, playful: 60, serious: 50, chaotic: 15, ordered: 85, nostalgic: 75, futuristic: 10, peaceful: 55, ominous: 5 },
  },
  {
    n: "Tomesode", a: ["留袖", "married woman's formal kimono"],
    cat: "Fashion & Dress", c: "Ceremonial kimono", e: "regional_tradition", o: "Japan", g: "Japan",
    p: "Edo code onward", era: "living tradition",
    sum: "The married woman's black formal — short sleeves, hem-only gardens of cranes and pines, five crests.",
    desc: "Tomesode are the opposite of furisode: black (kurotomesode) or colored (irotomesode) silk with short sleeves, patterns kept to the hem — cranes over waves, pine, plum — and five family crests (kamon) on shoulders and back; the most formal married-women's dress for mothers of the bride etc. The design logic: authority speaks low, from the ground up. The look: midnight silk, hem gardens, crest geometry.",
    col: [{ h: "#1a1a1a", n: "kurotomesode black" }, { h: "#d4af37", n: "gold accent" }, { h: "#c0392b", n: "hem red" }, { h: "#f2ead9", n: "irotomesode cream" }],
    m: ["silk habutae", "yūzen dyes", "gold couching", "mon crest weaving"],
    tx: ["flat silk sheen", "hem garden detail", "crest precision"],
    obj: ["hem-pattern kimono", "five-crest sets", "fukuro obi"],
    ex: ["wedding-mother tomesode", "Edo-era court precedents", "formal-wear rental canons"],
    inf: ["Edo dress codes"], rel: ["Furisode", "Yūzen dyeing", "Mon (family crest)"],
    par: "", var: ["kurotomesode", "irotomesode"], cf: ["Furisode"],
    src: [{ n: "Wikipedia — Tomesode", u: "https://en.wikipedia.org/wiki/Tomesode", t: "B" }],
    tg: ["kimono", "formal", "black", "hem", "japan"], pop: 14, niche: true,
    vd: { shape: "ground-length T form", line: "hem-border imagery", composition: "bottom-weighted garden", texture: "smooth silk", forms: "cranes, waves, crests" },
    typ: { display: "mincho serif", body: "humanist sans", notes: "formal card" },
    lit: { quality: "even formal", direction: "frontal", temperature: "warm", shadow: "silk low" },
    ui: { background: "black", surface: "gold-accent cards", components: "crest buttons", motion: "slow formal fade" },
    rec: { materials: "silk kimono, obi", lighting: "even", objects: "kimono, obi", music: "koto", scent: "silk, incense" },
    snd: ["quiet silk", "koto"],
    dna: { mi: 45, og: 65, wc: 25, ns: 5, ad: 5, hf: 8, rr: 12, ps: 30, sh: 25, ql: 25, oc: 12, ds: 65, rs: 15, eu: 90, np: 40 },
    emo: { warm: 60, cold: 30, playful: 15, serious: 85, chaotic: 5, ordered: 90, nostalgic: 75, futuristic: 5, peaceful: 60, ominous: 10 },
  },
  {
    n: "Samurai armour (kacchū)", a: ["甲冑", "Japanese armor", "yoroi and kabuto"],
    cat: "Fashion & Dress", c: "War regalia", e: "historical", o: "Feudal Japan", g: "Japan",
    p: "Heian to Edo", era: "samurai culture",
    sum: "Lacquered lames and silk lacing — o-yoroi box armor, crested kabuto helmets, armor as heraldic art.",
    desc: "Samurai armor balanced function and theater: o-yoroi's great box torso of lacquered iron lames laced in colored silk (odoshi), shoulder shields (sode), and kabuto helmets crowned with clan crests and antler maedate; sengoku-era tosei-gusoku slimmed it for guns. Lacing colors identified clans; armorers (Myochin lineage) signed pieces. Museums (Tokyo National) display them like sculpture — because they are. The look: lacquer depth, silk rainbow lacing, crest silhouette.",
    col: [{ h: "#1a1a1a", n: "urushi black" }, { h: "#8e3b46", n: "lacing red" }, { h: "#d4af37", n: "crest gold" }, { h: "#1c5d99", n: "lacing blue" }, { h: "#f2ead9", n: "silk white" }],
    m: ["iron and leather lames", "urushi lacquer", "silk odoshi lacing", "bear fur (edging)"],
    tx: ["lame scales", "lacing bands", "lacquer gloss"],
    obj: ["kabuto helmets", "o-yoroi box armors", "sode shoulders", "menpō face masks"],
    ex: ["Tokyo National Museum armors", "Date Masamune's black-gold set", "Myochin school classics"],
    inf: ["Mongol-invasion lessons"], rel: ["Mon (family crest)", "Urushi lacquerware", "Kumadori makeup"],
    par: "", var: ["o-yoroi (great box)", "tosei-gusoku (modern)"], cf: ["European plate armor"],
    src: [{ n: "Wikipedia — Japanese armour", u: "https://en.wikipedia.org/wiki/Japanese_armour", t: "B" }],
    tg: ["armor", "samurai", "lacquer", "crest", "japan"], pop: 40, niche: false,
    vd: { shape: "lame-layered torso", line: "silk-lacing rows", composition: "frontal crest authority", texture: "lacquer + silk", forms: "helmets, crests, masks" },
    typ: { display: "mincho serif", body: "humanist sans", notes: "museum label" },
    lit: { quality: "case dramatic", direction: "top", temperature: "warm", shadow: "lame deep" },
    ui: { background: "black", surface: "lacquer-red cards", components: "crest buttons", motion: "armor clank" },
    rec: { materials: "armor replicas, silk cords", lighting: "dramatic", objects: "helmets, swords, stands", music: "taiko", scent: "lacquer, iron" },
    snd: ["taiko thunder", "armor creak"],
    dna: { mi: 40, og: 70, wc: 25, ns: 10, ad: 5, hf: 10, rr: 25, ps: 25, sh: 55, ql: 40, oc: 15, ds: 70, rs: 20, eu: 75, np: 35 },
    emo: { warm: 55, cold: 40, playful: 10, serious: 90, chaotic: 15, ordered: 85, nostalgic: 70, futuristic: 5, peaceful: 25, ominous: 45 },
  },
  {
    n: "Kumadori makeup", a: ["隈取", "kabuki makeup"],
    cat: "Music & Sonic Culture", c: "Stage makeup", e: "historical", o: "Kabuki theatre", g: "Japan",
    p: "Genroku era onward", era: "living stage tradition",
    sum: "Kabuki's painted faces — red stripes for heroes, blue for villains, brushwork as character x-ray.",
    desc: "Kumadori paints the soul on kabuki faces: bold pigment stripes laid over white base, red-brown (beni-guma) for justice and passion, indigo-blue for villains and demons, brown for ghosts — the brushstrokes follow muscle lines so expressions read from the last row. Danjūrō lineage codified suji-guma hero patterns; 'hikinuki' quick changes add magic. The look: face as dynamic mask, stripes like muscle-fires, red fury and blue ice.",
    col: [{ h: "#c0392b", n: "hero red" }, { h: "#1c5d99", n: "villain blue" }, { h: "#f2ead9", n: "base white" }, { h: "#3d2b1f", n: "ghost brown" }, { h: "#1a1a1a", n: "outline black" }],
    m: ["oil pigment cakes (hai)", "base wax", "brushes"],
    tx: ["stripe brushwork", "white ground", "stage sheen"],
    obj: ["suji-guma hero patterns", "kuma-guma demon stripes", "collection prints (yakusha-e)"],
    ex: ["Danjūrō line kabuki roles", "Yakusha-e print portraits", "kabuki-za stage nights"],
    inf: ["noh mask tradition"], rel: ["Noh mask and costume", "Samurai armour (kacchū)", "Shadow puppetry (piyingxi)"],
    par: "", var: ["suji-guma (hero)", "kuma-guma (demon)"], cf: ["Noh mask and costume"],
    src: [{ n: "Wikipedia — Kumadori", u: "https://en.wikipedia.org/wiki/Kumadori", t: "B" }],
    tg: ["kabuki", "makeup", "stripes", "stage", "japan"], pop: 28, niche: false,
    vd: { shape: "face-mapped stripe flows", line: "muscle-following brush", composition: "expression-coded zones", texture: "paint sheen", forms: "stripes, brows, mouths" },
    typ: { display: "edomoji serif", body: "humanist sans", notes: "program playbill" },
    lit: { quality: "stage spot", direction: "frontal hot", temperature: "warm", shadow: "face sculpted" },
    ui: { background: "black", surface: "stripe-accent cards", components: "stripe buttons", motion: "character snap" },
    rec: { materials: "face paints, brushes", lighting: "stage spot", objects: "prints, playbills", music: "nagauta shamisen", scent: "oil paint, stage dust" },
    snd: ["shamisen tsugaru", "hyoshigi clacks"],
    dna: { mi: 30, og: 70, wc: 15, ns: 10, ad: 5, hf: 10, rr: 30, ps: 60, sh: 55, ql: 70, oc: 30, ds: 65, rs: 40, eu: 55, np: 40 },
    emo: { warm: 75, cold: 20, playful: 55, serious: 60, chaotic: 35, ordered: 70, nostalgic: 70, futuristic: 10, peaceful: 20, ominous: 35 },
  },
  {
    n: "Noh mask and costume", a: ["能面", "nohmen", "noh shozoku"],
    cat: "Music & Sonic Culture", c: "Stage craft", e: "historical", o: "Japan", g: "Japan",
    p: "14th century onward", era: "living stage tradition",
    sum: "Carved masks that breathe — ko-omote's girl-smiles, hannya's jealous horns, and brocade shozoku robes.",
    desc: "Noh masks (nohmen) are carved hinoki wood, 20-30cm, painted with crushed shell; tilted up they smile, down they grieve — 'terasu' mechanics that actors master for years. Types span ko-omote (young woman), hannya (jealous demoness), okina (old man god), each category with sub-schools. Shozoku costumes drape heavy silk brocades in webs of gold over structured shoulders. The look: eerie neutrality made expressive by angle, silk-gold gravitas.",
    col: [{ h: "#f2ead9", n: "mask shell white" }, { h: "#8e3b46", n: "hannya red" }, { h: "#d4af37", n: "brocade gold" }, { h: "#3d2b1f", n: "carved wood" }, { h: "#1f3a5f", n: "robe blue" }],
    m: ["hinoki cypress", "shell-white pigment", "silk brocade", "gold thread"],
    tx: ["lacquered mask sheen", "brocade weave", "carved subtlety"],
    obj: ["ko-omote masks", "hannya masks", "karaori robes", "kagami-ita mirror boards"],
    ex: ["Kongo school mask collections", "Hōryū-ji oldest masks", "national treasure performances"],
    inf: ["sarugaku and dengaku theatre"], rel: ["Kumadori makeup", "Tea ceremony aesthetics", "Karagöz shadow theatre"],
    par: "", var: ["ko-omote", "hannya", "okina", "jo types"], cf: ["Kumadori makeup"],
    src: [{ n: "Wikipedia — Noh mask", u: "https://en.wikipedia.org/wiki/Noh_mask", t: "B" }],
    tg: ["noh", "mask", "theatre", "brocade", "japan"], pop: 26, niche: false,
    vd: { shape: "neutral-oval masks", line: "hairline carved brows", composition: "angle-driven expression", texture: "shell lacquer", forms: "smiles, horns, brocades" },
    typ: { display: "mincho serif", body: "humanist sans", notes: "program elegance" },
    lit: { quality: "candle stage", direction: "low frontal", temperature: "warm", shadow: "mask angle play" },
    ui: { background: "charcoal", surface: "gold-brocade cards", components: "mask buttons", motion: "mask tilt" },
    rec: { materials: "mask replicas, brocade", lighting: "candle low", objects: "masks, fans, robes", music: "nohayo flute and drums", scent: "incense, wood" },
    snd: ["nohkan flute", "kotsuzumi taps"],
    dna: { mi: 60, og: 70, wc: 25, ns: 5, ad: 5, hf: 5, rr: 20, ps: 20, sh: 45, ql: 20, oc: 15, ds: 55, rs: 35, eu: 85, np: 40 },
    emo: { warm: 55, cold: 40, playful: 10, serious: 90, chaotic: 10, ordered: 90, nostalgic: 75, futuristic: 5, peaceful: 40, ominous: 40 },
  },
  {
    n: "Mon (family crest)", a: ["家紋", "kamon", "Japanese family crest"],
    cat: "Graphic Design", c: "Heraldic emblem", e: "historical", o: "Heian court → samurai clans", g: "Japan",
    p: "Heian onward", era: "living tradition",
    sum: "Circular Japanese heraldry — paulownia, kiri, mokkō, and 20,000+ registered crests of elegance and clan pride.",
    desc: "Mon are Japan's heraldic emblems: single-motif circles — paulownia (Toyota's), tomoe whirls, mokkō rims, cherry blossoms, crossed sickles — drawn in precise black-and-white geometry, once painted on court carriages, sewn on kimono (five formal crests), carved on armor and gates. Over 20,000 designs are catalogued; families, companies and shrines own theirs. The look: perfect geometric balance, one motif per circle, quiet authority.",
    col: [{ h: "#1a1a1a", n: "ink black" }, { h: "#f2ead9", n: "ground white" }, { h: "#d4af37", n: "gold foil (formal)" }],
    m: ["ink and brush", "stencil cuts", "gold foil (ceremonial)", " embroidered thread"],
    tx: ["clean glyph strokes", "perfect circles", "fabric weave"],
    obj: ["kiri (paulownia) crests", "tomoe whirls", "mokkō rims", "five-crest formal sets"],
    ex: ["Toyotomi kiri crest", "Oda mokkō", "modern corporate kamon"],
    inf: ["Heian court carriage marks"], rel: ["Samurai armour (kacchū)", "Tomesode", "Tughra sultanic monogram"],
    par: "", var: ["kiri", "tomoe", "mokkō", "hanabishi"], cf: ["European heraldry"],
    src: [{ n: "Wikipedia — Mon (emblem)", u: "https://en.wikipedia.org/wiki/Mon_(emblem)", t: "B" }],
    tg: ["crest", "heraldry", "japan", "geometry", "family"], pop: 24, niche: false,
    vd: { shape: "circular emblem fields", line: "bold black strokes", composition: "single-motif centering", texture: "ink flat", forms: "flowers, whirls, rims" },
    typ: { display: "mincho serif", body: "humanist sans", notes: "crest + wordmark" },
    lit: { quality: "even graphic", direction: "frontal", temperature: "neutral", shadow: "none" },
    ui: { background: "white", surface: "crest-badge cards", components: "round badge buttons", motion: "crest stamp" },
    rec: { materials: "crest prints, black frames", lighting: "even", objects: "badges, kimono crests", music: "gagaku", scent: "ink" },
    snd: ["gagaku sho", "stamp press"],
    dna: { mi: 80, og: 85, wc: 30, ns: 10, ad: 10, hf: 20, rr: 10, ps: 25, sh: 20, ql: 15, oc: 5, ds: 35, rs: 10, eu: 90, np: 40 },
    emo: { warm: 55, cold: 40, playful: 15, serious: 85, chaotic: 5, ordered: 95, nostalgic: 70, futuristic: 20, peaceful: 60, ominous: 10 },
  },
  {
    n: "Katagami stencils", a: ["型紙", "ise katagami", "katazome stencils"],
    cat: "Textile & Craft", c: "Paper stencils", e: "historical", o: "Ise, Japan", g: "Japan",
    p: "Edo period peak", era: "craft culture",
    sum: "Mulberry-paper stencils of impossible finesse — hair-width bridges holding intricate pattern webs.",
    desc: "Katagami are the stencil heroes of katazome dyeing: mulberry paper laminated and smoked, cut freehand with knives and punches into pine needles, dragonflies, undulating waves — patterns held by hair-fine silk-thread bridges that vanish in dyeing. Ise (Suzuka) guilds made tens of thousands of designs; collectors (including French Art Nouveau masters) treasured them as abstract art. The look: black lace rectangles, geometric-perfect nature, bridges invisible until the light catches.",
    col: [{ h: "#3d2b1f", n: "smoked paper" }, { h: "#c49a6c", n: "paper tan" }, { h: "#1a2f5e", n: "dye indigo (context)" }],
    m: ["mulberry paper (kōzo)", "persimmon tannin", "smoke curing", "carving knives and punches"],
    tx: ["hair-bridge finesse", "punched dots", "smoke sheen"],
    obj: ["wave-pattern stencils", "dragonfly panels", "kyōkei geometric sets"],
    ex: ["Ise katagami guild stock", "Art Nouveau collector holdings", "Suzuka city collections"],
    inf: ["katazome dyeing craft"], rel: ["Katazome", "Jianzhi papercutting", "Mon (family crest)"],
    par: "", var: ["tsukibori (combed)", "doshaburi (rain)", "shima (stripes)"], cf: ["Jianzhi papercutting"],
    src: [{ n: "Wikipedia — Katagami", u: "https://en.wikipedia.org/wiki/Katagami", t: "B" }],
    tg: ["stencil", "japan", "pattern", "paper", "edo"], pop: 14, niche: true,
    vd: { shape: "rect pattern fields", line: "hair-bridge connections", composition: "all-over repeats", texture: "smoked paper", forms: "waves, dragonflies, dots" },
    typ: { display: "mincho serif", body: "humanist sans", notes: "archive caption" },
    lit: { quality: "backlit", direction: "through stencil", temperature: "warm", shadow: "lace shadow" },
    ui: { background: "tan", surface: "stencil-lace cards", components: "pattern buttons", motion: "stencil lift" },
    rec: { materials: "framed stencils, indigo cloth", lighting: "backlit", objects: "stencils, dye samples", music: "shakuhachi", scent: "smoke, paper" },
    snd: ["knife on paper", "quiet studio"],
    dna: { mi: 60, og: 80, wc: 25, ns: 5, ad: 5, hf: 10, rr: 25, ps: 35, sh: 20, ql: 15, oc: 15, ds: 75, rs: 15, eu: 80, np: 45 },
    emo: { warm: 65, cold: 30, playful: 30, serious: 65, chaotic: 10, ordered: 90, nostalgic: 75, futuristic: 10, peaceful: 65, ominous: 5 },
  },
  {
    n: "Nishiki-e prints", a: ["錦絵", "brocade pictures", "full-color woodblock prints"],
    cat: "Graphic Design", c: "Woodblock printmaking", e: "historical", o: "Edo (Tokyo)", g: "Japan, global art history",
    p: "1765 to Meiji", era: "Edo popular culture",
    sum: "Full-color ukiyo-e — Harunobu's twelve-tone brocades, Hokusai's waves, Hiroshige's rain, the woodblock summit.",
    desc: "Nishiki-e ('brocade pictures') arrived in 1765 when Harunobu coordinated publisher, carver, printer and pigment into full-color woodblock prints — kentō registration keys aligning up to a dozen blocks per sheet. Icons followed: Hokusai's Great Wave, Hiroshige's Sudden Shower, Utamaro's beauties, Kunisada's actors; van Gogh painted copies. Shorthand for ukiyo-e's summit, the technique shaped Art Nouveau and manga alike. The look: flat brilliant color fields, fearless cropping, populations of famous faces.",
    col: [{ h: "#1c5d99", n: "Prussian blue" }, { h: "#c0392b", n: "beni red" }, { h: "#f2ead9", n: "paper cream" }, { h: "#2a9d8f", n: "aizuri-e variant" }, { h: "#3d2b1f", n: "sumi black" }],
    m: ["cherry woodblocks", "Prussian blue (berorin-ai)", "safflower red", "hosho paper", "barens pads"],
    tx: ["flat ink fields", "woodgrain ghost", "color registration"],
    obj: ["landscape series", "actor portraits", "beauty sheets", "surimono deluxe"],
    ex: ["Hokusai Thirty-six Views", "Hiroshige Hundred Views of Edo", "Utamaro beauty portraits"],
    inf: ["sumizuri-e monochrome prints"], rel: ["Katagami stencils", "Katazome", "Divisionism"],
    par: "", var: ["landscape nishiki-e", "yakusha-e", "bijin-ga", "surimono"], cf: ["Wood engraving"],
    src: [{ n: "Wikipedia — Nishiki-e", u: "https://en.wikipedia.org/wiki/Nishiki-e", t: "B" }, { n: "Metropolitan Museum of Art", u: "https://www.metmuseum.org", t: "A" }],
    tg: ["woodblock", "ukiyoe", "edo", "color", "prints"], pop: 58, niche: false,
    vd: { shape: "cropped dynamic frames", line: "keyblock contour dominance", composition: "asymmetric boldness", texture: "flat color + grain", forms: "waves, faces, rain" },
    typ: { display: "edomoji calligraphic", body: "block-printed captions", notes: "signature cartouche" },
    lit: { quality: "even daylight", direction: "frontal", temperature: "warm", shadow: "flat" },
    ui: { background: "cream", surface: "bordered print cards", components: "cartouche buttons", motion: "block layer-in" },
    rec: { materials: "framed prints, indigo accents", lighting: "even", objects: "prints, fans, scrolls", music: "shamisen", scent: "paper, ink" },
    snd: ["baren rubbing", "shamisen"],
    dna: { mi: 40, og: 75, wc: 20, ns: 5, ad: 5, hf: 15, rr: 25, ps: 55, sh: 30, ql: 35, oc: 30, ds: 60, rs: 25, eu: 75, np: 40 },
    emo: { warm: 70, cold: 25, playful: 55, serious: 50, chaotic: 25, ordered: 75, nostalgic: 75, futuristic: 15, peaceful: 50, ominous: 10 },
  },
  {
    n: "Kamishibai story cards", a: ["紙芝居", "kamishibai theatre"],
    cat: "Music & Sonic Culture", c: "Street storytelling", e: "historical", o: "Showa Japan", g: "Japan",
    p: "1930s-1950s peak", era: "Showa street culture",
    sum: "Bicycle-mounted paper theatres — wooden stages, clacking hyoshigi, candy-selling storytellers of Showa streets.",
    desc: "Kamishibai ('paper drama') packed a wooden stage box on a bicycle: the gaitō kamishibai-ya pedaled neighborhoods selling candy, clacked hyōshigi sticks to gather kids, then slid illustrated card after card while voicing every character — serial adventures that TV killed (the first TV generation was called 'kamishibai orphans'). Original cards (Dachō hero series etc.) are collector relics; schools revived the form for education. The look: garish hand-painted cards, wooden stage, streetlight audience.",
    col: [{ h: "#e07b39", n: "card orange" }, { h: "#1c5d99", n: "hero blue" }, { h: "#c0392b", n: "drama red" }, { h: "#f2ead9", n: "card paper" }, { h: "#5c4033", n: "stage wood" }],
    m: ["illustrated card stock", "wooden stage box", "hyoshigi clappers", "bicycle"],
    tx: ["hand-painted gouache", "card edge wear", "stage shadow"],
    obj: ["card sets", "stage boxes", "candy trays"],
    ex: ["Golden Bat (Ōgon Batto) serials", "Showa street recordings", "modern classroom revivals"],
    inf: ["utation-era picture shows"], rel: ["Nishiki-e prints", "Karagöz shadow theatre", "Shadow puppetry (piyingxi)"],
    par: "", var: ["gaitō street type", "educational type"], cf: ["Shadow puppetry (piyingxi)"],
    src: [{ n: "Wikipedia — Kamishibai", u: "https://en.wikipedia.org/wiki/Kamishibai", t: "B" }],
    tg: ["storytelling", "showa", "cards", "street", "japan"], pop: 16, niche: true,
    vd: { shape: "landscape card frames", line: "bold gouache contour", composition: "slide-series drama", texture: "gouache matte", forms: "heroes, monsters, cities" },
    typ: { display: "showa poster serif", body: "humanist sans", notes: "playbill energy" },
    lit: { quality: "dusk streetlamp", direction: "frontal", temperature: "warm", shadow: "stage rim" },
    ui: { background: "dusk", surface: "card-slide cards", components: "card buttons", motion: "slide swap" },
    rec: { materials: "card sets, stage", lighting: "lamp", objects: "cards, clappers", music: "narration + clack", scent: "candy, dusk" },
    snd: ["hyoshigi clack", "child crowd"],
    dna: { mi: 25, og: 70, wc: 15, ns: 10, ad: 5, hf: 15, rr: 35, ps: 75, sh: 35, ql: 65, oc: 35, ds: 55, rs: 35, eu: 45, np: 50 },
    emo: { warm: 85, cold: 10, playful: 85, serious: 25, chaotic: 35, ordered: 60, nostalgic: 85, futuristic: 10, peaceful: 45, ominous: 15 },
  },
  {
    n: "Ger (yurt) felt dwelling", a: ["гэр", "mongolian yurt", "ger"],
    cat: "Architectural Style", c: "Nomad dwelling", e: "regional_tradition", o: "Mongolian steppe", g: "Mongolia, Central Asia",
    p: "centuries to present", era: "living nomad tradition",
    sum: "Felt-wall lattice homes — white domes of the steppe, stove-centered, door always facing the sun.",
    desc: "The ger assembles in an hour and houses generations: khana lattice walls, uni roof poles to the toono crown ring, felt layers blanketing all, painted doors facing south, stove (zuukh) at center connecting sky (toono) and hearth. Ornaments bless the frame — khadag silks on the crown, painted bands on doors; hospitality rules fix seating by honor. Ger camps ring Ulaanbaatar as they ring history. The look: white dome on green steppe, blue door, smoke straight up.",
    col: [{ h: "#f5f0e6", n: "felt white" }, { h: "#1c5d99", n: "door blue" }, { h: "#c49a6c", n: "lattice wood" }, { h: "#8a9a5b", n: "steppe green" }, { h: "#d4af37", n: "khadag gold" }],
    m: ["felt", "lattice wood (khana)", "roof poles (uni)", "horsehair ropes", "painted door"],
    tx: ["felt softness", "lattice rhythm", "smoke patina"],
    obj: ["toono crown rings", "painted doors", "stove centers", "khadag silks"],
    ex: ["Gobi ger camps", "Naadam festival gers", "Ulaanbaatar ger districts"],
    inf: ["steppe nomadism"], rel: ["Shyrdak felt rug", "Deel", "Sadu weaving"],
    par: "", var: ["five-wall ger", "eight-wall ger", "urts (western)"], cf: ["Deel"],
    src: [{ n: "Wikipedia — Yurt", u: "https://en.wikipedia.org/wiki/Yurt", t: "B" }],
    tg: ["yurt", "felt", "nomad", "steppe", "mongolia"], pop: 34, niche: false,
    vd: { shape: "low dome geometry", line: "lattice + pole radii", composition: "hearth-centered circle", texture: "felt + wood", forms: "doors, crowns, ropes" },
    typ: { display: "humanist sans", body: "humanist sans", notes: "ger-camp signage" },
    lit: { quality: "toono skylight", direction: "crown down", temperature: "warm", shadow: "felt soft" },
    ui: { background: "felt cream", surface: "lattice-pattern cards", components: "round buttons", motion: "dome rise" },
    rec: { materials: "felt, painted wood", lighting: "skylight", objects: "ger stays, saddles, bowls", music: "morin khuur", scent: "felt, milk tea" },
    snd: ["morin khuur", "wind on felt"],
    dna: { mi: 55, og: 70, wc: 20, ns: 5, ad: 5, hf: 8, rr: 35, ps: 35, sh: 30, ql: 20, oc: 20, ds: 40, rs: 10, eu: 60, np: 40 },
    emo: { warm: 80, cold: 20, playful: 30, serious: 60, chaotic: 15, ordered: 80, nostalgic: 75, futuristic: 8, peaceful: 70, ominous: 10 },
  },
  {
    n: "Deel", a: ["дээл", "Mongolian robe"],
    cat: "Fashion & Dress", c: "Nomad dress", e: "regional_tradition", o: "Mongolia", g: "Mongolia, Inner Mongolia",
    p: "centuries to present", era: "living tradition",
    sum: "The steppe's one-piece coat — silk-covered warmth, sash-tight, festival colors over everyday earth tones.",
    desc: "The deel is Mongolia's everything-coat: one rectangular body with folded flap front, high collar, sash (bus) at the waist, cut for riding wind; everyday versions wear sturdy cotton in dark tones, festival Naadam deels gleam in silk brocades of orange, turquoise, green with contrast trim and silver buttons. Winter deels layer sheepskin inside; hats, boots (gutal) complete. The look: belted silk architecture, color-blocked brights against steppe dust.",
    col: [{ h: "#e07b39", n: "festival orange" }, { h: "#1c5d99", n: "turquoise silk" }, { h: "#2d6a4f", n: "everyday green" }, { h: "#d4af37", n: "silver-gold button" }, { h: "#f2ead9", n: "contrast trim" }],
    m: ["silk and brocade (festival)", "cotton and wool (daily)", "sheepskin (winter)", "metal buttons"],
    tx: ["silk sheen", "trim contrast", "sash wrap"],
    obj: ["everyday deels", "Naadam festival deels", "bus sashes", "gutal boots"],
    ex: ["Naadam festival dress", "Ulaanbaatar street deels", "Gobi herder winter deels"],
    inf: ["steppe dress tradition"], rel: ["Ger (yurt) felt dwelling", "Sami gákti dress", "Sadu weaving"],
    par: "", var: ["khalsha day deel", "winter guchilgei"], cf: ["kaftan traditions"],
    src: [{ n: "Wikipedia — Deel", u: "https://en.wikipedia.org/wiki/Deel_(clothing)", t: "B" }],
    tg: ["robe", "mongolia", "nomad", "festival", "deel"], pop: 20, niche: false,
    vd: { shape: "rect body + flap front", line: "trim border lines", composition: "sash-waist geometry", texture: "silk over felt", forms: "collars, flaps, sashes" },
    typ: { display: "humanist sans", body: "humanist sans", notes: "festival poster" },
    lit: { quality: "steppe sun", direction: "high", temperature: "warm", shadow: "fold deep" },
    ui: { background: "steppe tan", surface: "color-block cards", components: "band buttons", motion: "sash tie" },
    rec: { materials: "deel coat, sash", lighting: "bright steppe", objects: "deels, boots, bowls", music: "morin khuur", scent: "wool, airag" },
    snd: ["long song (urtiin duu)", "hoof beats"],
    dna: { mi: 50, og: 60, wc: 15, ns: 10, ad: 5, hf: 10, rr: 30, ps: 45, sh: 30, ql: 40, oc: 20, ds: 55, rs: 10, eu: 60, np: 45 },
    emo: { warm: 80, cold: 15, playful: 40, serious: 55, chaotic: 15, ordered: 80, nostalgic: 70, futuristic: 10, peaceful: 55, ominous: 10 },
  },
];
