/**
 * Rebuild wave — Film, Comics, Color & Period styles r1 (20 entries).
 * Solo-authored after sandbox rollback. Wikipedia titles batch-verified via
 * API (2026-09-14). Dedup-checked against refreshed existing-names.txt.
 */
export const ENTRIES: any[] = [
  {
    n: 'Technicolor Musicals', a: ['three-strip technicolor', 'glorious technicolor', 'MGM musical color', 'golden-age technicolor'],
    cat: 'Film & Cinema', c: 'three-strip Technicolor film look', e: 'historical',
    o: 'Hollywood studios (1932-1955)', g: 'Hollywood, British & global studio films',
    p: '1932-1955', era: 'Becky Sharp to the dye-transfer shutdown',
    sum: 'Saturated three-strip color where every red is a costume decision.',
    desc: 'Three-strip Technicolor (1932-1955) is cinema\'s most committed color system: a beam-splitting camera shot three film records through filters, dyes were imbibition-printed in a dedicated lab, and studio color consultants (the Technicolor "color supervisor" role — Natalie Kalmus above all) forced art direction, costumes and even actor makeup to serve the dye gamut. Results: the poppy fields of The Wizard of Oz, the ink-lagoon of The Adventures of Robin Hood, MGM\'s chorus-line reds. Modern digital "technicolor" grades quote its healthy skin tones and deep primaries; the original dye-transfer prints remain collector icons of depth and stability.',
    col: [{ h: '#c93636', n: 'scarlet primary' }, { h: '#2f7d4f', n: 'emerald medium' }, { h: '#e8c14a', n: 'canary key light' }, { h: '#2979ff', n: 'dye blue' }, { h: '#f2d5a0', n: 'healthy skin warm' }],
    m: ['three-strip beam-splitter cameras', 'imbibition dye-transfer printing', 'Technicolor lab supervision', 'color-scripted sets'],
    tx: ['dye density richness', 'emulsion depth glow', 'matte painting blends'],
    obj: ['color-coded chorus costumes', 'painted scenic backdrops', 'technicolor camera rigs', 'consultant approval memos'],
    ex: ['The Wizard of Oz (1939) sepia-to-dorothy reveal', 'The Adventures of Robin Hood (1938)', 'Singin\' in the Rain (1952)'],
    inf: ['musical stage design', 'studio glamour portraiture', 'Walt Disney animation color experiments'], rel: ['Soviet Montage Cinema', 'French Nouvelle Vague', 'Pop Art Silkscreen'],
    src: [{ n: 'Wikipedia — Technicolor', u: 'https://en.wikipedia.org/wiki/Technicolor', t: 'B' }, { n: 'George Eastman Museum — Technicolor collection', u: 'https://www.eastman.org', t: 'A' }],
    tg: ['technicolor', 'film', 'color', 'musical', 'hollywood', '1930s'],
    pop: 52, niche: false,
    vd: { shape: 'theatrical blocking with costume-first framing', line: 'clean studio contour, no grain murk', composition: 'depth-staged musical tables', texture: 'dye-density glow, zero bleach' },
    typ: { display: 'golden-age studio title scripts', body: 'poster serif taglines', notes: 'color itself carries the melody' },
    lit: { quality: 'high-key studio glamour', temperature: 'warm-toned', shadow: 'soft glamour shadows, never black' },
    ui: { background: 'stage ruby', surface: 'curtain-swing cards', components: 'spotlight-dot icons', motion: 'musical-number choreography pans' },
    par: 'film look traditions',
  },
  {
    n: 'Spaghetti Western Visual Code', a: ['spaghetti western', 'eurowestern', 'Leone look', 'macaroni western'],
    cat: 'Film & Cinema', c: 'Italian-made western aesthetic', e: 'historical',
    o: 'Italian studios (Cinecittà & Almería, Spain)', g: 'Italy, Spain (Almería & Tabernas), global genre film',
    p: '1964-1978', era: 'A Fistful of Dollars to genre exhaustion',
    sum: 'Squinting close-ups, Spanish deserts, Morricone screams — the West rewritten as opera.',
    desc: 'The spaghetti western — launched internationally by Sergio Leone\'s A Fistful of Dollars (1964) — recoded the American western: amoral antiheroes in ponchos, extreme close-up squints intercut with wide Almería desert vistas, gallows humor, and Ennio Morricone\'s music (whips, coyote howls, chanted wah-wah) acting as on-screen color. Cinematographers like Tonino Delli Colli favored harsh sun, dust filters and unstylish sweat; production design turned Almería\'s Tabernas desert into a mythic Mexico. The style\'s grammar — the three-way standoff, the torture-of-the-hero, the dressed-down costume — spread through hundreds of Eurowesterns and redefined the genre\'s visual cruelty and cool.',
    col: [{ h: '#c98a3d', n: 'desert dust ochre' }, { h: '#8c1f1f', n: 'blood-and-poncho red' }, { h: '#3a3a3a', n: 'gunmetal grey' }, { h: '#e9e2d0', n: 'bone white' }, { h: '#5a4a3a', n: 'dried sweat brown' }],
    m: ['Almería/Tabernas locations', 'anamorphic Techniscope cameras', 'dust and sweat makeup', 'Morricone score sessions'],
    tx: ['harsh sun bleach', 'dust-on-lens haze', 'sweat-sheen close-ups'],
    obj: ['standoff triangle blocking', 'poncho-and-cigar costumes', 'ramshackle mission sets', 'whip-crack score stings'],
    ex: ['A Fistful of Dollars (1964)', 'The Good, the Bad and the Ugly (1966) cemetery finale', 'Once Upon a Time in the West (1968)'],
    inf: ['Kurosawa samurai structure (Yojimbo)', 'American B-westerns', 'Italian opera melodrama'], rel: ['Technicolor Musicals', 'Giallo Thriller', 'Soviet Montage Cinema'],
    src: [{ n: 'Wikipedia — Spaghetti Western', u: 'https://en.wikipedia.org/wiki/Spaghetti_Western', t: 'B' }, { n: 'BFI — Eurowestern essays', u: 'https://www.bfi.org.uk', t: 'A' }],
    tg: ['western', 'leone', 'italian', 'desert', 'morricone', 'film'],
    pop: 55, niche: false,
    vd: { shape: 'extreme-closeup eyes vs widescreen desert', line: 'sweat-and-dust silhouette edges', composition: 'standoff geometry, violent cuts', texture: 'dust, sweat, cheap fabric weave' },
    typ: { display: 'rough-hewn western title slabs', body: 'dubbed-dialogue neutral subtitles', notes: 'music cues as visual punctuation' },
    lit: { quality: 'noon desert cruelty', temperature: 'warm-toned', shadow: 'hat brims and eyes as shade traps' },
    ui: { background: 'dust ochre', surface: 'grit-textured cards', components: 'bullet-hole accents', motion: 'standoff zoom-in pulses' },
    par: 'film look traditions',
  },
  {
    n: 'Soviet Montage Cinema', a: ['soviet montage theory', 'montage school', 'kuleshov effect', 'Eisenstein montage'],
    cat: 'Film & Cinema', c: '1920s Soviet editing-driven film language', e: 'historical',
    o: 'Soviet film schools (Moscow, Lev Kuleshov\'s workshop)', g: 'USSR, world arthouse cinema',
    p: '1919-1935', era: 'revolution-era film experimentation to montage decree',
    sum: 'Meaning made in the cut: stone lions leaping, battleship guns, Kuleshov\'s hungry face.',
    desc: 'Soviet montage — Kuleshov, Eisenstein, Vertov, Pudovkin — built a film theory on the cut itself: the Kuleshov effect showed identical faces acquire meaning from adjacent shots; Eisenstein\'s "collision" montage (Battleship Potemkin\'s Odessa Steps, October\'s stone lions) created ideas no single frame contained; Vertov\'s Man with a Movie Camera made the camera and edit themselves the hero. Visually the school favored dynamic diagonals, rhythmic mass choreography, constructivist title cards and agit-prop poster acting. Its editing grammar infiltrated advertising, music video and every action climax; its theory remains the backbone of film-school editing pedagogy.',
    col: [{ h: '#141414', n: 'orthochromatic black' }, { h: '#e9e2d0', n: 'stock silver white' }, { h: '#8c1f1f', n: 'agitprop red ink' }, { h: '#b0b7bd', n: 'inter-title grey' }],
    m: ['orthochromatic film stock', 'hand-tinted and toned prints', 'constructivist title cards', 'rewriting-room editing tables'],
    tx: ['high-contrast ortho grain', 'jump-cut rhythm', 'constructivist type bite'],
    obj: ['Odessa Steps pram sequence', 'stone-lion triple montage', 'agitprop title cards', 'camera-as-eye sequences'],
    ex: ['Battleship Potemkin (1925) steps sequence', 'Man with a Movie Camera (1929)', 'Kuleshov Effect demonstration shorts'],
    inf: ['constructivist graphic design', 'Marxist dialectics', 'Griffith-era editing as raw material'], rel: ['Technicolor Musicals', 'Spaghetti Western Visual Code', 'Russian Constructivist Posters'],
    src: [{ n: 'Wikipedia — Soviet montage theory', u: 'https://en.wikipedia.org/wiki/Soviet_montage_theory', t: 'B' }, { n: 'British Film Institute — Eisenstein collections', u: 'https://www.bfi.org.uk', t: 'A' }],
    tg: ['montage', 'eisenstein', 'editing', 'soviet', 'silent film', 'theory'],
    pop: 44, niche: false,
    vd: { shape: 'diagonal masses and rhythmic crowd geometry', line: 'constructivist angle-cuts', composition: 'collision of shots as argument', texture: 'ortho grain, hand-toned tints' },
    typ: { display: 'constructivist inter-title slabs', body: 'newsreel caption lines', notes: 'typography as revolutionary declamation' },
    lit: { quality: 'hard daylight argument', temperature: 'cool-toned', shadow: 'stepped, poster-like shadow masses' },
    ui: { background: 'newsreel silver', surface: 'diagonal-slash cards', components: 'film-sprocket accents', motion: 'rapid montage cuts' },
    par: 'film look traditions',
  },
  {
    n: 'Dogme 95 Vow', a: ['dogme 95', 'dogme film', 'vow of chastity', 'von trier dogme'],
    cat: 'Film & Cinema', c: '1995 Danish filmmaking manifesto aesthetic', e: 'community_subculture',
    o: 'Cinema Oxygen workshop, Copenhagen (Lars von Trier, Thomas Vinterberg)', g: 'Denmark, global arthouse',
    p: '1995-2005', era: 'manifesto publication to certificate closure',
    sum: 'Handheld cameras, natural light, no props: cinema stripped by contract.',
    desc: 'Dogme 95 was a manifesto with teeth: von Trier and Vinterberg\'s 1995 "Vow of Chastity" banned artificial light, props, sets, genre music, optical filters and credit-list vanity — shooting only on location with handheld cameras and ambient sound. The Celebration (1998) and The Idiots (1998) proved the aesthetic: grainy, immediate, actor-forward films whose constraints manufactured emotional rawness. Thirty-plus certified Dogme films (Julien Donkey-Boy, Italian for Beginners) followed before the movement wound down in 2005. Its legacy is the normalized digital-naturalism of festival drama — handheld, available-light, imperfect — and a demonstration that constraint breeds style.',
    col: [{ h: '#5a4a3a', n: 'available-light beige' }, { h: '#141414', n: 'unfiltered black' }, { h: '#8a8378', n: 'fluorescent room grey' }, { h: '#7a8a8a', n: 'overcast window pale' }],
    m: ['handheld digital/beta cameras', 'available light only', 'on-location sound', 'prop-free set discipline'],
    tx: ['video grain shimmer', 'auto-focus hunt', 'unpolished skin texture'],
    obj: ['wedding speech long takes', 'corridor handheld chases', 'certificate-of-chastity documents'],
    ex: ['Festen / The Celebration (1998)', 'The Idiots (1998)', 'Julien Donkey-Boy (1999)'],
    inf: ['Danish film school culture', 'New Wave auteur manifestos', 'video-art immediacy'], rel: ['French Nouvelle Vague', 'PS1-Era Survival Horror', 'Cuban Rumba Dress & Drums'],
    src: [{ n: 'Wikipedia — Dogme 95', u: 'https://en.wikipedia.org/wiki/Dogme_95', t: 'B' }, { n: 'Danish Film Institute — Dogme archive', u: 'https://www.dfi.dk', t: 'A' }],
    tg: ['dogme', 'manifesto', 'handheld', 'danish', 'natural light', 'film'],
    pop: 32, niche: true,
    vd: { shape: 'handheld frame wander, faces first', line: 'no-contour video softness', composition: 'accidental blocking, real rooms', texture: 'beta grain, video smear' },
    typ: { display: 'plain credit sans', body: 'subtitle-neutral delivery', notes: 'director credit withheld on set' },
    lit: { quality: 'whatever the room gives', temperature: 'neutral-toned', shadow: 'un corrected, flat, honest' },
    ui: { background: 'room beige', surface: 'plain-border cards', components: 'no-frill buttons', motion: 'handheld micro-jitter' },
    par: 'film look traditions',
  },
  {
    n: 'French Nouvelle Vague', a: ['nouvelle vague', 'french new wave', 'truffaut style', 'left bank cinema'],
    cat: 'Film & Cinema', c: 'late-1950s French auteur cinema look', e: 'historical',
    o: 'Cahiers du cinéma critics turned directors (Paris)', g: 'France, world arthouse cinema',
    p: '1958-1968', era: 'The 400 Blows to May \'68 aftermath',
    sum: 'Jump cuts, street light, and the conviction that a camera is a pen.',
    desc: 'The Nouvelle Vague — Truffaut, Godard, Chabrol, Rohmer, Rivette, plus the Left Bank\'s Resnais and Varda — turned film criticism into film style: location Paris streets, natural light, direct address to camera, jump cuts (Breathless\'s famous elisions), long takes of conversation, and genre plots hijacked by cinephile reference. Low budgets and fast crews were the aesthetic: Godard shot Breathless with a wheelchair, a tripod and Chabrol\'s produce-check. The look — black-and-white grain, sunglasses-and-pipe chic, hand-lettered interludes — became the default image of cinematic modernism, and its "camera-stylo" freedom licenses every indie auteur since.',
    col: [{ h: '#141414', n: 'b&w silver black' }, { h: '#e9e2d0', n: 'ilford silver white' }, { h: '#8a8378', n: 'street café grey' }, { h: '#c93636', n: 'pierre-clément poster red' }],
    m: ['R Halina 16mm & 35mm stocks', 'portable Eclair cameras', 'street location permits', 'jump-cut editing'],
    tx: ['silver halide grain', 'location haze', 'printed-poster fold'],
    obj: ['café-terrace tracking shots', 'jump-cut city walks', 'cinephile poster tables', 'sunglasses-portrait frames'],
    ex: ['Breathless / À bout de souffle (1960)', 'The 400 Blows (1959)', 'Cléo from 5 to 7 (1962)'],
    inf: ['Cahiers auteur theory', 'Italian neorealism', 'American noir and musicals (remade freely)'], rel: ['Dogme 95 Vow', 'Soviet Montage Cinema', 'Film Noir'],
    src: [{ n: 'Wikipedia — French New Wave', u: 'https://en.wikipedia.org/wiki/French_New_Wave', t: 'B' }, { n: 'Cinémathèque française', u: 'https://www.cinematheque.fr', t: 'A' }],
    tg: ['newwave', 'godard', 'truffaut', 'paris', 'auteur', 'film'],
    pop: 54, niche: false,
    vd: { shape: 'street-frame immediacy, faces loitering', line: 'hand-held softness, jump-cut severances', composition: 'conversational long takes', texture: 'black-and-white grain, print silver' },
    typ: { display: 'hand-painted title cards', body: 'subtitle-styled dialogues', notes: 'michel Poiccard\'s posters are props' },
    lit: { quality: 'overcast Paris daylight', temperature: 'cool-toned', shadow: 'street-shadow casual falls' },
    ui: { background: 'café silver', surface: 'photo-border cards', components: 'jump-cut transitions', motion: 'walk-and-talk pacing' },
    par: 'film look traditions',
  },
  {
    n: 'Kirby Krackle', a: ['kirby krackle', 'kirby dots', 'energy dots', 'Jack Kirby power effects'],
    cat: 'Illustration & Comics', c: 'comic-book energy field dot device', e: 'historical',
    o: 'Jack Kirby (Marvel Comics, 1960s-70s)', g: 'US comics, global comic art',
    p: '1960s-present', era: 'Fourth World & Fantastic Four era to industry convention',
    sum: 'Black dots of pure power: the visual sound of cosmic energy in comics.',
    desc: 'The Kirby Krackle — clusters of black dots surrounding energy bursts, cosmic entities and dimensional rifts — is Jack Kirby\'s signature invention, standard from his 1960s-70s Marvel work (Fantastic Four, Fourth World, Eternals). Where other artists used white voids, Kirby packed negative space with crackling dot-masses that read as audible hum and raw force; combined with collage skies, square-fingered gestalt and out-of-panel bursts, the Krackle made machinery of magic. The device is now an industry-wide convention — named, taught in art schools, quoted in Manga (Bleach\'s release energy) and pixel games — and remains the fastest way to draw "power" in ink.',
    col: [{ h: '#141414', n: 'power-dot black' }, { h: '#f2efe4', n: 'panel paper white' }, { h: '#c93636', n: 'burst red' }, { h: '#e8c14a', n: 'cosmic gold' }],
    m: ['pen and brush ink', 'ben-day dot grids', 'four-color offset printing', 'collage photomontage (Kirby)'],
    tx: ['dot-cluster rhythm', 'ink brush weight', 'newsprint bite'],
    obj: ['energy-burst panels', 'cosmic entity auras', 'dimensional portals', 'collage-space spreads'],
    ex: ['Fantastic Four (Kirby 1961-70)', 'Fourth World saga (1970-72)', 'Eternals cosmic displays'],
    inf: ['pulp SF cover effects', 'Japanese monster film energy', 'photo-collage experiment'], rel: ['Manga Screentone', 'Golden Age Newsprint Comics', 'Pop Art Silkscreen'],
    src: [{ n: 'Wikipedia — Kirby Krackle', u: 'https://en.wikipedia.org/wiki/Kirby_krackle', t: 'B' }, { n: 'The Jack Kirby Museum', u: 'https://kirbymuseum.org', t: 'A' }],
    tg: ['kirby', 'comics', 'ink', 'energy', 'marvel', 'dots'],
    pop: 41, niche: true,
    vd: { shape: 'dot-cluster auras hugging force shapes', line: 'square-finger kinetic contour', composition: 'burst-center panel logic', texture: 'brushed ink, print dot gain' },
    typ: { display: 'Kirby-emphasis comic lettering', body: 'caption strip narration', notes: 'sound effects as figures' },
    lit: { quality: 'self-generated panel glow', temperature: 'warm-toned', shadow: 'dots ARE the shadow of power' },
    ui: { background: 'panel white', surface: 'dot-burst cards', components: 'krackle-load spinners', motion: 'power-hum pulse rings' },
    par: 'comic art devices',
  },
  {
    n: 'Manga Screentone', a: ['screentone', 'toning sheets', 'shonen gray tones', 'Manga shading film'],
    cat: 'Illustration & Comics', c: 'Japanese comic halftone-film craft', e: 'community_subculture',
    o: 'Japanese manga publishing (Osamu Tezuka era onward)', g: 'Japan, global manga & webtoon industry',
    p: '1960s-2010s (digital present)', era: 'tone-sheet craft era to digital tone libraries',
    sum: 'Adhesive gray made from dots: skies, blood-speed and blush by pre-printed film.',
    desc: 'Screentone is the craft glue of manga production: pre-printed adhesive sheets of halftone dots and patterns, cut with swivel knives and burnished onto inked pages to make skies, shadows, speed fields and texture — a physical collage process that turned black-and-white comics into richly graded worlds. Tone codes (Deleter, Letraset) became shared vocabulary; artists like Katsuhiro Otomo (Akira) and Tsutomu Nihei pushed tonal density to architectural extremes. Digital manga replaced knives with tone libraries, and the look — gradient dots, speed lines, ZIP-buyer marks — remains the visual fingerprint of the medium, even in webtoon rendering.',
    col: [{ h: '#141414', n: 'tone black' }, { h: '#f2efe4', n: 'page paper white' }, { h: '#8a8378', n: '50% gray tone' }, { h: '#c93636', n: 'cover accent red' }],
    m: ['Deleter & Letraset tone sheets', 'swivel knives', 'tonehera burnishers', 'digital tone libraries (CLIP STUDIO)'],
    tx: ['dot-gradient steps', 'tone-seam edges', 'burnish flat spots'],
    obj: ['sky-tone panels', 'speed-line bursts', 'shadow-side face tones', 'texture tones (steel, fur, rain)'],
    ex: ['Akira (Otomo) dense city toning', 'Knights of Sidonia (Nihei) architecture tone', 'Deleter Neukoeln tone catalog'],
    inf: ['photo-halftone print technology', 'Osamu Tezuka film-like framing', 'anime cel shading logic'], rel: ['Kirby Krackle', 'Cel-Shaded Game Art', 'Golden Age Newsprint Comics'],
    src: [{ n: 'Wikipedia — Screentone', u: 'https://en.wikipedia.org/wiki/Screentone', t: 'B' }, { n: 'Deleter — tone catalog', u: 'https://www.deleter-neoaldnoah.jp', t: 'C' }],
    tg: ['manga', 'screentone', 'halftone', 'ink', 'japan', 'comics'],
    pop: 49, niche: false,
    vd: { shape: 'panel grids with tone-washed depth', line: 'clean G-pen contours', composition: 'cinematic page flow, tone as light', texture: 'dot gradients, paper bite' },
    typ: { display: 'impact-logotype covers', body: 'vertical furigana-laced dialog', notes: 'sound effects drawn as art' },
    lit: { quality: 'tone-implied studio light', temperature: 'neutral-toned', shadow: 'dots are the shadow system' },
    ui: { background: 'paper white', surface: 'tone-panel cards', components: 'tone-chip swatches', motion: 'speed-line whoosh transitions' },
    par: 'comic art devices',
  },
  {
    n: 'High-Contrast Noir Comics', a: ['sin city style', 'noir comics', 'black-white-red comics', 'Frank Miller ink look'],
    cat: 'Illustration & Comics', c: 'posterized black-white crime comic style', e: 'community_subculture',
    o: 'US crime comics (Frank Miller\'s Sin City, 1991-)', g: 'US comics, global graphic novels',
    p: '1991-present', era: 'Sin City serialization to noir-comic mainstream',
    sum: 'Ink blots and bleach-white faces: crime comics reduced to pure light and dark.',
    desc: 'The high-contrast noir comic — canonized by Frank Miller\'s Sin City — draws with absence: massive black ink masses, few interior lines, spotlight-white faces and the occasional single accent color (the red dress, the yellow bastard). The tradition descends from Silver Streak horror and film-noir stills but was Miller\'s Sin City (1991) that made posterized chiaroscuro a working method: brush-drawn blacks as architecture, hatchless shadows, mood carried entirely by value structure. Eddie Campbell, Sean Phillips (Criminal) and Sean Murphy work the dialect; the style\'s digital descendant is the high-contrast webcomic frame, and its film adaptation (2005) moved the look to screen almost unchanged.',
    col: [{ h: '#141414', n: 'spot-black ink' }, { h: '#f2efe4', n: 'bleach-white paper' }, { h: '#c93636', n: 'single-accent red' }, { h: '#e8c14a', n: 'yellow bastard accent' }],
    m: ['brush and pen ink', 'posterized photo reference', 'single-accent spot color', 'matte paper stock'],
    tx: ['solid-black mass weight', 'white-knuckle negative space', 'accent-color pop'],
    obj: ['rain-slick street panels', 'white-face close-ups', 'silhouette-broken skylines', 'single-accent dress panels'],
    ex: ['Sin City: The Hard Goodbye (1991)', 'Criminal (Phillips & Brubaker)', 'Sin City (2005) film translation'],
    inf: ['film noir cinematography', 'Silver Age horror ink work', 'German expressionist woodcuts'], rel: ['Manga Screentone', 'Film Noir', 'Kirby Krackle'],
    src: [{ n: 'Wikipedia — Sin City', u: 'https://en.wikipedia.org/wiki/Sin_City', t: 'B' }, { n: 'Frank Miller — official Sin City materials', u: 'https://frankmillerink.com', t: 'C' }],
    tg: ['noir', 'comics', 'high contrast', 'frank miller', 'ink', 'crime'],
    pop: 46, niche: false,
    vd: { shape: 'posterized figure masses in deep ink', line: 'brush-edge white cuts', composition: 'spotlight-value storytelling', texture: 'brush drag, ink bleed' },
    typ: { display: 'hammered-noir title slabs', body: 'voiceover caption strips', notes: 'accent color = a character' },
    lit: { quality: 'streetlamp single-source', temperature: 'cool-toned', shadow: 'shadow does the drawing' },
    ui: { background: 'ink black', surface: 'white-cut cards', components: 'accent-dot buttons', motion: 'panel-to-panel hard cuts' },
    par: 'comic art devices',
  },
  {
    n: 'Bande Dessinée Album Style', a: ['bande dessinée', 'BD', 'franco-belgian album', 'ligne blanche album format'],
    cat: 'Illustration & Comics', c: 'Franco-Belgian hardback comic tradition', e: 'regional_tradition',
    o: 'Franco-Belgian publishers (Casterman, Dupuis, Dargaud)', g: 'France, Belgium, Switzerland, Quebec',
    p: '1930s-present', era: 'Tintin magazine era to contemporary album market',
    sum: '48-page hardbacks where every panel is a painting: the album as objet.',
    desc: 'Bande dessinée — the Franco-Belgian comic — built a distinct visual culture around the album format: 48-64 page hardbacks in rigid page grids, full-process color from the 1940s, and craft traditions from Hergé\'s ligne claire to André Franquin\'s elastic comedy to Moebius\'s sky-hatching and Bilal\'s grim airbrush. The album market treats comics as literary objects — critics review them, bookshops shelve them, festivals (Angoulême) award them — and its panel discipline (clean gutters, standardized page counts, painterly backgrounds) gave the world a vocabulary distinct from US action comics and Japanese tankobon. BD style still signals "European comics" at a glance: planche over splash, tableaux over speed.',
    col: [{ h: '#e9e2d0', n: 'album ivory stock' }, { h: '#1f4d8c', n: 'process blue' }, { h: '#c93636', n: 'tintin red' }, { h: '#e8c14a', n: 'children\'s sun yellow' }],
    m: ['album hardback format', 'four-color offset plates', 'planche grid layouts', 'gouache color guides'],
    tx: ['flat-process color fills', 'clean gutter discipline', 'glossy stock sheen'],
    obj: ['standard album spines', 'planche grid pages', 'festival poster artworks', 'collector edition slipcases'],
    ex: ['Tintin albums (Hergé)', 'Asterix page choreography (Uderzo)', 'Le Monde d\'Edena (Moebius)'],
    inf: ['Hergé ligne claire school', 'Franco-Belgian magazine serialization', 'European poster painting'], rel: ['Manga Screentone', 'Golden Age Newsprint Comics', 'High-Contrast Noir Comics'],
    src: [{ n: 'Wikipedia — Bande dessinée', u: 'https://en.wikipedia.org/wiki/Bande_dessin%C3%A9e', t: 'B' }, { n: 'Festival d\'Angoulême', u: 'https://www.festivalbdangouleme.com', t: 'A' }],
    tg: ['bd', 'franco-belgian', 'album', 'ligne claire', 'comics', 'europe'],
    pop: 43, niche: false,
    vd: { shape: 'planche grid of painterly tableaux', line: 'school-dependent: claire to textured', composition: 'page-as-composition discipline', texture: 'flat process color, album gloss' },
    typ: { display: 'series logotype consistency', body: 'classic bubble lettering', notes: 'album spine shelf-presence matters' },
    lit: { quality: 'clean daylight tableaux', temperature: 'varies by school', shadow: 'painterly, often absent' },
    ui: { background: 'album ivory', surface: 'planche-grid cards', components: 'bubble-frame dividers', motion: 'page-turn reveal' },
    par: 'comic art devices',
  },
  {
    n: 'Golden Age Newsprint Comics', a: ['golden age comics', 'newsprint comic art', 'four-color pulp comics', 'Action Comics era'],
    cat: 'Illustration & Comics', c: '1938-1956 US comic print culture', e: 'historical',
    o: 'US comic publishers (DC/National, Timely, Fawcett)', g: 'US newsstand culture',
    p: '1938-1956', era: 'Action Comics #1 to code-imposed decline',
    sum: 'Supermen on cheap paper: dot-bled primaries that decayed beautifully.',
    desc: 'The Golden Age of comics (1938-1956) is inseparable from its cheap physical medium: rough newsprint, four-color offset with heavy dot gain, registration drift and editorial reds that bled into hero capes. The look — saturated-but-murky primaries, hand-lettered captions, cover-dated yellowing — was forged by constraint and speed (Will Eisner\'s shop, Jack Kirby & Joe Simon\'s assembly lines), and the surviving artifacts (Action #1, Detective #27, Captain Marvel Adventures) are valued as much for their print decay as their art. Modern "newsprint" reprints and aged-paper digital filters deliberately reproduce the look: golden-age decay is now an aesthetic decision.',
    col: [{ h: '#c93636', n: 'newsprint bleed red' }, { h: '#2979ff', n: 'four-color blue' }, { h: '#e8c14a', n: 'aged yellow paper' }, { h: '#141414', n: 'print dot black' }, { h: '#d9c8a3', n: 'foxing tan' }],
    m: ['newsprint stock', 'four-color offset with dot gain', 'hand lettering', 'cover-dated bindings'],
    tx: ['dot-gain mush', 'registration misalign', 'foxing and edge yellowing'],
    obj: ['10¢ cover-dated issues', 'origin-story splash pages', 'hand-lettered caption boxes', 'newsstand spinner racks'],
    ex: ['Action Comics #1 (1938)', 'Captain Marvel Adventures covers (C.C. Beck)', 'Detective Comics #27 (1939)'],
    inf: ['pulp magazine production', 'newspaper strip printing', 'depression-era newsstand economics'], rel: ['Kirby Krackle', 'Bande Dessinée Album Style', 'Manga Screentone'],
    src: [{ n: 'Wikipedia — Golden Age of Comic Books', u: 'https://en.wikipedia.org/wiki/Golden_Age_of_Comic_Books', t: 'B' }, { n: 'Grand Comics Database', u: 'https://www.comics.org', t: 'C' }],
    tg: ['goldenage', 'newsprint', 'superhero', 'comics', 'print', '1940s'],
    pop: 48, niche: false,
    vd: { shape: 'chunky figure masses on coarse dot fields', line: 'print-rounded ink edges', composition: 'cover-first newsstand grab', texture: 'newsprint tooth, foxing age' },
    typ: { display: 'hand-lettered masthead logos', body: 'typewriter-style caption boxes', notes: '10¢ price corner as icon' },
    lit: { quality: 'flat print, no photographic light', temperature: 'warm-toned', shadow: 'dot-built shadow fields' },
    ui: { background: 'aged newsprint', surface: 'dot-gain cards', components: 'cover-date badges', motion: 'page-flip foxing fade' },
    par: 'comic art devices',
  },
  {
    n: 'International Klein Blue', a: ['IKB', 'Klein blue', 'Yves Klein blue', 'pure ultramarine'],
    cat: 'Color & Light', c: 'patented monochrome blue of Yves Klein', e: 'historical',
    o: 'Yves Klein, Paris (1960 registration)', g: 'global art & design culture',
    p: '1960-present', era: 'Nouveau Réalisme Paris to design-culture shorthand',
    sum: 'One blue, patented, total: a color as a finished artwork.',
    desc: 'International Klein Blue (IKB) is less a pigment than an artwork: the matte, velvet-deep ultramarine Yves Klein developed with chemist Edouard Adam (suspended in a synthetic resin binder that preserved raw pigment luminosity) and registered under a Soleau envelope in 1960. Klein showed it as monochrome canvases, sponges, and the living-brush "Anthropométries" — color stripped of composition until the hue itself carries the event. IKB escaped the gallery: design, fashion, album covers (Derek Jarman\'s Blue cinema), and every "Klein blue" sneaker quote it. The aesthetic lesson: total commitment to one color can be maximalism, not minimalism.',
    col: [{ h: '#002fa7', n: 'IKB ultramarine' }, { h: '#f2efe4', n: 'gallery white frame' }, { h: '#8a5230', n: 'sponge-bronze accent' }],
    m: ['ultramarine pigment (PB29)', 'synthetic resin binder (Médimix)', 'raw canvas & sponge supports', 'Soleau envelope registration'],
    tx: ['velvet matte depth', 'pigment particle grain', 'flat infinite field'],
    obj: ['monochrome IKB canvases', 'blue sponge sculptures', 'blue-period table installations', 'living-brush performance traces'],
    ex: ['IKB 191 (1962) canvas', 'Sponge Sculpture (1959)', 'Anthropométries performance paintings'],
    inf: ['Rosicrucian and judo-blue symbolism', 'Nouveau Réalisme Paris', 'monochrome painting lineage (Rodchenko)'], rel: ['Pop Art Silkscreen', 'Color Field Painting', 'Albers Color Interaction'],
    src: [{ n: 'Wikipedia — International Klein Blue', u: 'https://en.wikipedia.org/wiki/International_Klein_Blue', t: 'B' }, { n: 'Centre Pompidou — Klein collection', u: 'https://www.centrepompidou.fr', t: 'A' }],
    tg: ['klein blue', 'monochrome', 'color', 'art', 'ultramarine', 'ikb'],
    pop: 51, niche: false,
    vd: { shape: 'total flat field, edgeless', line: 'none — hue is the line', composition: 'color as sole subject', texture: 'matte pigment velvet' },
    typ: { display: 'gallery-label neutrality', body: 'none needed', notes: 'the blue speaks first' },
    lit: { quality: 'even museum wash', temperature: 'cool-toned', shadow: 'the field refuses shadow' },
    ui: { background: '#002fa7 field', surface: 'white-min cards', components: 'single-hue buttons', motion: 'immersion dissolve' },
    par: 'color systems',
  },
  {
    n: 'Pop Art Silkscreen', a: ['pop art', 'Warhol silkscreen', 'factory print art', 'screen-printed pop'],
    cat: 'Art Movement', c: '1960s screen-printed pop painting', e: 'historical',
    o: 'New York & London (Warhol Factory, Paolozzi & Blake)', g: 'US & UK art worlds, global design',
    p: '1950s-1970s', era: 'Independent Group to Factory production line',
    sum: 'Cans, stars and crashes printed flat: mass media adopted as painting.',
    desc: 'Pop art\'s silkscreen practice — Andy Warhol\'s Factory line above all — took mass-media imagery (soup cans, Marilyn stills, death-crash photos) and printed it with visible misregistration, repeating grids and flat commercial color. The silkscreen was the point: an industrial reproduction process inside fine art made originality itself the joke. Roy Lichtenstein\'s Benday-dot paintings, Richard Hamilton\'s collages and Paolozzi\'s print pop belong to the same logic; Warhol\'s variations (32 Campbells Soups, Marilyn diptychs) turned multiplication into portraiture. Its graphic legacy is everywhere: editorial flat color, brand-irony design, and the "pop filter" in every image editor.',
    col: [{ h: '#e8c14a', n: 'brillo yellow' }, { h: '#c93636', n: 'campbell red' }, { h: '#1f4d8c', n: 'process blue' }, { h: '#f2efe4', n: 'canvas white field' }, { h: '#141414', n: 'print key black' }],
    m: ['silkscreen frames & squeegees', 'photo-emulsion separations', 'acrylic paint (giclée-era later)', 'grid layouts'],
    tx: ['flat ink fields', 'misregistered edges', 'dot-grid texture'],
    obj: ['repeating celebrity grids', 'brillo-box sculpture stacks', 'crash-diptych newsprints', 'factory production tables'],
    ex: ['Campbell\'s Soup Cans (1962)', 'Marilyn Diptych (1962)', 'Just What Is It... (Hamilton, 1956)'],
    inf: ['commercial advertising art', 'comic and celebrity media', 'Duchampian appropriation logic'], rel: ['International Klein Blue', 'Kirby Krackle', 'Golden Age Newsprint Comics'],
    src: [{ n: 'Wikipedia — Pop art', u: 'https://en.wikipedia.org/wiki/Pop_art', t: 'B' }, { n: 'MoMA — Warhol collection', u: 'https://www.moma.org', t: 'A' }],
    tg: ['pop art', 'warhol', 'silkscreen', 'print', 'mass media', '1960s'],
    pop: 68, niche: false,
    vd: { shape: 'grid-multiplied product and portrait fields', line: 'hard ink separations', composition: 'repetition as composition', texture: 'flat print, squeegee drag' },
    typ: { display: 'commercial sans headline quoting', body: 'gallery-label flat text', notes: 'brand letterforms as art material' },
    lit: { quality: 'flat commercial evenness', temperature: 'varies — always loud', shadow: 'printed shadow, never natural' },
    ui: { background: 'gallery white', surface: 'grid-print cards', components: 'can-stack rows', motion: 'grid-repeat stutters' },
    par: 'modern art movements',
  },
  {
    n: 'Albers Color Interaction', a: ['interaction of color', 'josef albers', 'homage to the square', 'color perception study'],
    cat: 'Color & Light', c: 'relational color perception pedagogy', e: 'historical',
    o: 'Josef Albers (Bauhaus → Black Mountain → Yale)', g: 'US design education, global art schools',
    p: '1920s-1976', era: 'Bauhaus Vorkurs to Interaction of Color (1963) canon',
    sum: 'The same color, two ways: Albers proved color only exists in relation.',
    desc: 'Josef Albers built the 20th century\'s color pedagogy around one demonstration: identical colors look different depending on their neighbors. His color courses (Bauhaus, Black Mountain College, Yale) ran students through decades of cut-paper experiments — make one color look like two, make two look like one — and culminated in the 1963 Interaction of Color and the Homage to the Square series (1950-76), a thousand nested squares where inner "glow" is pure perceptual effect. The lessons — simultaneous contrast, vibrating boundaries, transparency illusions — are baked into every design curriculum and palette tool; "Albers exercise" remains a working verb among colorists.',
    col: [{ h: '#c98a3d', n: 'ochre illusion warm' }, { h: '#8a8378', n: 'identical grey pair' }, { h: '#c93636', n: 'boundary vibration red' }, { h: '#e9e2d0', n: 'perceptual white shift' }],
    m: ['cut-paper color experiments', 'gouache matched swatches', 'square-format oil sketches', 'course workbooks'],
    tx: ['flat matte fields', 'hard square boundaries', 'perceptual vibration at edges'],
    obj: ['Homage to the Square nesting', 'two-into-one illusion studies', 'student paper exercises', 'Interaction of Color plates'],
    ex: ['Homage to the Square: Apparition (1959)', 'Interaction of Color plate exercises', 'Black Mountain College course archives'],
    inf: ['Goethe color theory', 'Bauhaus Vorkurs pedagogy', 'simultaneous contrast science (Chevreul)'], rel: ['International Klein Blue', 'Bauhaus Design', 'Color Field Painting'],
    src: [{ n: 'Wikipedia — Josef Albers', u: 'https://en.wikipedia.org/wiki/Josef_Albers', t: 'B' }, { n: 'Josef & Anni Albers Foundation', u: 'https://www.albersfoundation.org', t: 'A' }],
    tg: ['color theory', 'albers', 'bauhaus', 'perception', 'pedagogy', 'interaction'],
    pop: 40, niche: true,
    vd: { shape: 'nested squares, centered upward bias', line: 'pure boundary, no stroke', composition: 'perception experiment as picture', texture: 'flat gouache matte' },
    typ: { display: 'workbook plate numbering', body: 'instructive exercise captions', notes: 'the exercise is the artwork' },
    lit: { quality: 'flat north-light studio', temperature: 'neutral-toned', shadow: 'no shadow — only contrast' },
    ui: { background: 'neutral grey 18%', surface: 'square-nest cards', components: 'color-swap toggles', motion: 'illusion-flip on hover' },
    par: 'color systems',
  },
  {
    n: 'Pantone Corporate Color', a: ['pantone', 'PMS colors', 'pantone guide', 'corporate color standard'],
    cat: 'Color & Light', c: 'proprietary color matching system aesthetic', e: 'commercial_style',
    o: 'Pantone Inc. (Lawrence Herbert, 1963)', g: 'global design & brand industry',
    p: '1963-present', era: 'print-chemistry solution to brand-culture icon',
    sum: 'The fan-deck as worldview: color standardized, licensed, and traded like stocks.',
    desc: 'Pantone built the 20th century\'s color infrastructure: Lawrence Herbert\'s 1963 ink-matching cards became the Pantone Matching System — numbered swatches (PMS 485 red, 286 blue, 448C "sepiatone") that printers, brands and fashion pipelines treat as legal truth. The fan-deck\'s matte-chip presentation became an aesthetic itself: brands defend trademarked Pantones (Tiffany 1837, UPS brown), the Color of the Year shapes retail seasons, and designers quote the chip-card layout as design shorthand for authority. Pantone\'s systemization also carried costs — standardized sameness debates — but as visual culture the numbered chip is as canonical as the hex code.',
    col: [{ h: '#e8c14a', n: 'guideband yellow' }, { h: '#141414', n: 'chip black bar' }, { h: '#c93636', n: 'PMS 485 red' }, { h: '#f2efe4', n: 'coated stock white' }],
    m: ['coated & uncoated chip cards', 'ink formulation tables', 'fan-deck bindings', 'digital hex bridges'],
    tx: ['matte chip ink evenness', 'coated-stock gloss strip', 'guide-edge wear'],
    obj: ['PMS fan decks', 'brand style-guide pages', 'Color of the Year campaigns', 'licensed chip merchandise'],
    ex: ['Pantone Color of the Year (annual)', 'Tiffany Blue PMS 1837 licensing', 'Pantone hotel and café pop-ups'],
    inf: ['Munsell color system', 'commercial print standardization', 'brand trademark law'], rel: ['Albers Color Interaction', 'Corporate Memphis', 'International Klein Blue'],
    src: [{ n: 'Wikipedia — Pantone', u: 'https://en.wikipedia.org/wiki/Pantone', t: 'B' }, { n: 'Pantone — official system site', u: 'https://www.pantone.com', t: 'A' }],
    tg: ['pantone', 'color', 'branding', 'print', 'pms', 'standard'],
    pop: 58, niche: false,
    vd: { shape: 'torn-edge chip cards in long fan rows', line: 'chip grid regularity', composition: 'authority through numbering', texture: 'matte ink, coated stock split' },
    typ: { display: 'guide-number tabular caps', body: 'spec-sheet neutral text', notes: 'the number is the name' },
    lit: { quality: 'D50 viewing-booth light', temperature: 'neutral-toned', shadow: 'chips are flat by law' },
    ui: { background: 'booth grey', surface: 'chip-tear cards', components: 'swatch-pick buttons', motion: 'chip-flick deck scroll' },
    par: 'color systems',
  },
  {
    n: 'Teal-and-Orange Grade', a: ['teal and orange', 'blockbuster color grade', 'Hollywood digital grade', 'skin-pop grading'],
    cat: 'Color & Light', c: 'complementary digital film grading look', e: 'commercial_style',
    o: 'digital intermediate suites (2000s Hollywood)', g: 'global cinema, TV, streaming and game trailers',
    p: '2000-present', era: 'digital intermediate era to meme-recognized default',
    sum: 'Cyan shadows, hot skin: the blockbuster grade so common it became a meme.',
    desc: 'The teal-and-orange grade is the digital-intermediate era\'s signature look: skin tones pushed warm-orange against shadows and skies crushed toward teal-cyan, exploiting maximal hue opposition while keeping faces luminous. Born when DI (digital intermediate) suites made per-channel grading trivial after O Brother, Where Art Thou? (2000) proved whole-film color control, the grade became blockbuster default — Transformers, Mad Max: Fury Road, every action key-art — and eventually a design meme ("everything is orange and teal"). Its power is real: complementary contrast plus protected skin reads well on dark screens. Its ubiquity made neutrality feel like rebellion.',
    col: [{ h: '#1f6b6b', n: 'shadow teal' }, { h: '#e8813a', n: 'skin orange' }, { h: '#2979ff', n: 'sky cyan push' }, { h: '#141414', n: 'crushed black' }, { h: '#f2d5a0', n: 'highlight warmth' }],
    m: ['digital intermediate suites', 'lift/gamma/gain per-channel tools', 'HSL qualifier masks', 'LUT look libraries'],
    tx: ['deep cyan shadow wash', 'hot specular skin', 'film-grain overlay (token)'],
    obj: ['blockbuster key art frames', 'trailer LUT stacks', 'game UI color scripts', 'streaming poster walls'],
    ex: ['O Brother, Where Art Thou? (2000) DI pioneer', 'Transformers (2007) trailer palette', 'Mad Max: Fury Road grade'],
    inf: ['complementary color theory', 'digital intermediate technology', 'trailer-marketing contrast logic'], rel: ['Technicolor Musicals', 'Pantone Corporate Color', 'VHS Tracking Glitch'],
    src: [{ n: 'Wikipedia — Color grading', u: 'https://en.wikipedia.org/wiki/Color_grading', t: 'B' }, { n: 'American Cinematographer — DI features', u: 'https://theasc.com', t: 'A' }],
    tg: ['color grading', 'teal orange', 'film', 'di', 'blockbuster', 'lut'],
    pop: 56, niche: false,
    vd: { shape: 'image split into warm subject vs cool world', line: 'none — grade is invisible structure', composition: 'faces always the warmest thing', texture: 'clean digital grain token' },
    typ: { display: 'trailer sans uppercase titles', body: 'legal-card neutral grey', notes: 'grade sells the genre at a glance' },
    lit: { quality: 'synthetic complementary split', temperature: 'split warm/cool', shadow: 'teal-cyan shadow push' },
    ui: { background: 'teal-shadow field', surface: 'orange-skin cards', components: 'LUT-preview toggles', motion: 'grade-slider wipe' },
    par: 'color systems',
  },
  {
    n: 'Haussmann Paris', a: ['haussmann renovation', 'paris boulevards', 'haussmannian architecture', 'second empire paris'],
    cat: 'Architectural Style', c: 'Napoleon III Paris rebuilding', e: 'historical',
    o: 'Paris under Baron Georges-Eugène Haussmann (1853-1870)', g: 'Paris, imitated worldwide',
    p: '1853-1870', era: 'Second Empire renovation program',
    sum: 'Limestone, zinc and straight lines: the Paris that photography loves.',
    desc: 'Haussmann\'s renovation of Paris under Napoleon III sliced medieval districts into the long boulevards and uniform facades that define the city: cream Lutetian limestone, height-limited buildings with rusticated ground floors, continuous wrought-iron balconies aligned by étage, and steep zinc mansard roofs. Beyond aesthetics the program served circulation, hygiene and counter-insurgency; displaced populations paid the human cost, and the "haussmannien" block became both civic icon and political battleground. Its visual legacy is total: every photograph of Paris rooftops, every "Parisian" interior trend (parquet, moulding, tall French windows), and every city-planning argument since.',
    col: [{ h: '#d9c8a3', n: 'lutetian limestone cream' }, { h: '#5a5a5a', n: 'zinc mansard grey' }, { h: '#141414', n: 'wrought iron black' }, { h: '#2f7d4f', n: 'boulevard garden green' }],
    m: ['Lutetian limestone ashlar', 'zinc roof sheets', 'wrought-iron balconies', 'cut-granite curbs'],
    tx: ['stone block jointing', 'zinc weather streaking', 'iron scrollwork lace'],
    obj: ['aligned étage balconies', 'mansard dormer rows', 'boulevard café terraces', 'civic fountain squares'],
    ex: ['Boulevard Saint-Michel cutting', 'Parc Monceau perimeter blocks', 'Opéra district avenues'],
    inf: ['Second Empire statecraft', 'sewer and water modernization', 'medieval quarter clearance politics'], rel: ['Gilded Age Interiors', 'Louis XIV Style', 'Beaux-Arts Architecture'],
    src: [{ n: "Wikipedia — Haussmann's renovation of Paris", u: 'https://en.wikipedia.org/wiki/Haussmann%27s_renovation_of_Paris', t: 'B' }, { n: 'Musée Carnavalet — Paris history', u: 'https://www.carnavalet.paris.fr', t: 'A' }],
    tg: ['paris', 'architecture', 'boulevard', 'limestone', 'second empire', 'planning'],
    pop: 62, niche: false,
    vd: { shape: 'continuous street-wall rhythm, horizon-cut roofs', line: 'balcony rail horizontal bands', composition: 'perspective avenues as composition', texture: 'stone jointing, zinc streaks' },
    typ: { display: 'street-name enamel plaques', body: 'café menu script', notes: 'facades align lettering heights' },
    lit: { quality: 'soft northern overcast', temperature: 'cool-toned', shadow: 'long avenue shade at dusk' },
    ui: { background: 'limestone cream', surface: 'ironwork-bordered cards', components: 'balcony-rail dividers', motion: 'avenue-perspective drift' },
    par: 'urban architecture traditions',
  },
  {
    n: 'Gilded Age Interiors', a: ['gilded age interior', 'american renaissance decor', 'vanderbilt mansion style', 'beaux arts interior'],
    cat: 'Interior Design', c: '1870s-1900s American mansion decoration', e: 'historical',
    o: 'New York & Newport mansions (The Breakers, Marble House)', g: 'US East Coast, Chicago Gold Coast',
    p: '1870-1900', era: 'post-Civil War fortune display era',
    sum: 'Marble halls, silk walls and imported everything — fortunes rendered as furniture.',
    desc: 'Gilded Age interiors converted industrial fortunes into continental display: Fifth Avenue and Newport mansions (Richard Morris Hunt\'s Breakers) filled with Italian marble, French silk wall panels, Japanese lacquer corners, oak galleries, and rooms purchased — sometimes entire ceilings — from European palaces. Decorators (the Herter Brothers, Ogden Codman with Edith Wharton\'s The Decoration of Houses) professionalized the field; every surface carried currency: parquet inlays, gilded mouldings, tapestry-lined halls, and the double-parlor social machine. The style\'s excess seeded both the American Renaissance and its reform backlash — and remains the visual grammar of "old money" costume drama.',
    col: [{ h: '#c9a227', n: 'gilt moulding gold' }, { h: '#7a4a2a', n: 'oak gallery brown' }, { h: '#8c1f1f', n: 'silk damask red' }, { h: '#f2efe4', n: 'carrara marble white' }, { h: '#1d3557', n: 'velvet drape blue' }],
    m: ['imported marble', 'silk damask panels', 'gilded plaster mouldings', 'inlaid parquet floors'],
    tx: ['marble veining', 'damask sheen', 'gilt relief sparkle'],
    obj: ['double parlors', 'oak library galleries', 'grand staircase halls', 'painted ceiling panels'],
    ex: ['The Breakers, Newport (1895)', 'Herter Brothers drawing rooms', 'Metropolitan Museum period rooms'],
    inf: ['French beaux-arts training', 'European grand tour collecting', 'industrial fortune competition'], rel: ['Haussmann Paris', 'Louis XIV Style', 'Adam Style'],
    src: [{ n: 'Wikipedia — Gilded Age', u: 'https://en.wikipedia.org/wiki/Gilded_Age', t: 'B' }, { n: 'Preservation Society of Newport County', u: 'https://www.newportmansions.org', t: 'A' }],
    tg: ['gilded age', 'interior', 'mansions', 'newport', 'beaux arts', 'opulence'],
    pop: 50, niche: false,
    vd: { shape: 'enfilade room sequences, ceiling-first entry', line: 'gilded moulding outlines', composition: 'axis-of-honor sightlines', texture: 'marble, silk, gilt relief' },
    typ: { display: 'family-crest heraldic panels', body: 'guest-book and menu scripts', notes: 'rooms read as genealogy' },
    lit: { quality: 'chandelier-laden evening', temperature: 'warm-toned', shadow: 'deep velvet corner shade' },
    ui: { background: 'damask crimson', surface: 'gilt-frame cards', components: 'crest-badge icons', motion: 'curtain-sweep reveals' },
    par: 'period interior traditions',
  },
  {
    n: 'Pennsylvania Dutch Fraktur', a: ['fraktur', 'PA dutch birth certificates', 'taufschein art', 'pennsylvania german illuminated records'],
    cat: 'Regional & Cultural Tradition', c: 'Pennsylvania German illuminated documents', e: 'historical',
    o: 'Pennsylvania German settlements (1750-1850 peak)', g: 'Pennsylvania, Ohio, Ontario Mennonite communities',
    p: '1740s-1900s', era: 'German-American folk illumination era',
    sum: 'Birth certificates as heaven: hearts, birds and fraktur letters inked by country hands.',
    desc: 'Fraktur are the illuminated manuscripts of the Pennsylvania Germans — printed and hand-drawn Taufscheine (birth and baptism certificates), hymn-book bookmarks and house blessings decorated with angels, tulips, unicorns, hearts and birds around Gothic fraktur lettering. Drawing on Rhineland models, scribes and schoolmasters (Scranton, the schoolmaster-artists of Montgomery County) personalized each piece with watercolor brightness that folk-art historians rank with the best American vernacular art. Collections (Free Library of Philadelphia\'s) hold thousands; the motifs — especially the distelfink and tulip — still seed Pennsylvania Dutch craft and quilt design.',
    col: [{ h: '#8c1f1f', n: 'watercolor crimson' }, { h: '#e8c14a', n: 'tulip gold' }, { h: '#2f7d4f', n: 'distelfink green' }, { h: '#1d3557', n: 'lettering ink blue-black' }, { h: '#f2efe4', n: 'laid paper ground' }],
    m: ['laid and wove paper', 'iron-gall ink', 'watercolor cakes', 'gothic fraktur type & hand lettering'],
    tx: ['watercolor wash bloom', 'pen-stroke swells', 'aged paper foxing'],
    obj: ['Taufschein birth certificates', 'Vorschrift writing samples', 'bookplate and hymn markers', 'house-blessing broadsheets'],
    ex: ['Free Library of Philadelphia fraktur collection', 'Schwenkfelder Library & Heritage Center', 'schoolmaster Johann Adam Eyer books'],
    inf: ['Rhineland manuscript models', 'Lutheran & Reformed church records', 'Moravian school culture'], rel: ['Chintz Printed Cotton', 'Dala Horse Painting', 'Glagolitic Liturgical Lettering'],
    src: [{ n: 'Wikipedia — Fraktur (folk art)', u: 'https://en.wikipedia.org/wiki/Fraktur_(folk_art)', t: 'B' }, { n: 'Free Library of Philadelphia — Fraktur collection', u: 'https://www.freelibrary.org', t: 'A' }],
    tg: ['fraktur', 'pennsylvania', 'folk art', 'manuscript', 'german', 'illumination'],
    pop: 30, niche: true,
    vd: { shape: 'arched certificate frames with bird-and-heart figures', line: 'gothic fraktur swells', composition: 'text center, garden border', texture: 'watercolor bloom on laid paper' },
    typ: { display: 'fraktur blackletter headings', body: 'scripted record details', notes: 'lettering is decoration and data' },
    lit: { quality: 'farmhouse window light', temperature: 'warm-toned', shadow: 'none — ink does the shading' },
    ui: { background: 'laid paper cream', surface: 'arched-frame cards', components: 'tulip-and-heart icons', motion: 'certificate-unroll reveal' },
    par: 'American folk arts',
  },
  {
    n: 'Louis XIV Baroque Style', a: ['louis quatorze style', 'versailles style', 'french classical baroque', 'le style louis xiv'],
    cat: 'Historical Period Style', c: 'Sun King court design', e: 'historical',
    o: 'Versailles & Paris (1661-1715)', g: 'France, European courts',
    p: '1661-1715', era: 'Versailles building campaigns to royal death',
    sum: 'Marble courtyards, sunface marquetry and mirror halls — absolutism as décor.',
    desc: 'The Louis XIV style is the visual language of absolutism: Versailles\' marble courtyards, the Hall of Mirrors\' arcade, Le Brun\'s painted apotheoses, Boulle marquetry (brass-and-tortoiseshell inlays), sun-face ornament (the king\'s emblem) and gardens where hedges obey geometry. Colbert\'s royal manufactories (Gobelins) industrialized luxury so French taste could be exported as policy; European courts copied the vocabulary for a century. The style\'s heaviness — massive commodes, gilt consoles, ceremonial ceilings — reads as power arithmetic: symmetry, axis, and the king everywhere implied.',
    col: [{ h: '#c9a227', n: 'boulle brass gold' }, { h: '#8c1f1f', n: 'velvet drape red' }, { h: '#d9c8a3', n: 'court marble cream' }, { h: '#141414', n: 'tortoiseshell dark' }, { h: '#2f7d4f', n: 'garden parterre green' }],
    m: ['boulle marquetry', 'italian marble', 'gilded carved wood', 'silk velvet upholstery'],
    tx: ['brass inlay sheen', 'carved gilt depth', 'parterre hedge precision'],
    obj: ['hall of mirrors arcades', 'sun-face commodes', 'ceremonial ceiling frescoes', 'grand canal perspectives'],
    ex: ['Hall of Mirrors, Versailles (1684)', 'Boulle armoires in the Louvre', 'André Le Nôtre parterre gardens'],
    inf: ['Italian baroque imports', 'royal manufactury policy', 'classical symmetry theory'], rel: ['Gilded Age Interiors', 'Haussmann Paris', 'Baroque Ornament'],
    src: [{ n: 'Wikipedia — Louis XIV style', u: 'https://en.wikipedia.org/wiki/Louis_XIV_style', t: 'B' }, { n: 'Château de Versailles', u: 'https://www.chateauversailles.fr', t: 'A' }],
    tg: ['versailles', 'baroque', 'louis xiv', 'french', 'court', 'baroque'],
    pop: 57, niche: false,
    vd: { shape: 'axial symmetry and garden compass geometry', line: 'gilt scroll and sun-ray outlines', composition: 'king-axis perspective everywhere', texture: 'marble, gilt, velvet, hedge' },
    typ: { display: 'engraved dedication cartouches', body: 'chancery document scripts', notes: 'royal ciphers repeat like logos' },
    lit: { quality: 'mirror-multiplied candlelight', temperature: 'warm-toned', shadow: 'controlled by candelabra and glass' },
    ui: { background: 'marble cream', surface: 'gilt-cartouche cards', components: 'sunface medallions', motion: 'hall-of-mirror parallax' },
    par: 'period interior traditions',
  },
  {
    n: 'Adam Style Neoclassicism', a: ['adam style', 'adamesque', 'robert adam neoclassical', 'brothers adam design'],
    cat: 'Historical Period Style', c: 'Robert Adam\'s light neoclassical manner', e: 'historical',
    o: 'Robert & James Adam, London & Edinburgh (1760s-1790s)', g: 'Britain, federal America',
    p: '1760-1800', era: 'Grand Tour antiquity fashion to Federal adoption',
    sum: 'Wedgwood colors and delicate urns: antiquity lightened for drawing rooms.',
    desc: 'The Adam style — architects Robert and James Adam — replaced Palladian heaviness with a light, painted neoclassicism: flat encaustic-color walls (pea green, salmon, Wedgwood blues), delicate stucco reliefs of urns, rams\' heads and vine scrolls drawn from Herculaneum and Diocletian\'s palace (Spalatro), elliptical rooms, and integrated door-to-ceiling compositions. Syon House, Kedleston Hall and Osterley Park are canons; American Federal builders (and the White House\'s early rooms) adopted the grammar. Its lesson — antiquity pastel and unified ornament instead of carved stone weight — made neoclassicism livable and feminine-coded in its era, an enduring interior-design template.',
    col: [{ h: '#7fb3a0', n: 'pea-green encaustic' }, { h: '#e8b4a0', n: 'salmon pink wall' }, { h: '#f2efe4', n: 'stucco relief white' }, { h: '#c9a227', n: 'gilt urn accent' }],
    m: ['painted encaustic walls', 'stucco composition reliefs', 'scagliola imitations', 'mahogany veneer furniture'],
    tx: ['flat wall color fields', 'low stucco relief shadow', 'satin wood sheen'],
    obj: ['elliptical drawing rooms', 'urn-and-vine relief panels', 'adam chimneypieces', 'painted seicento ceilings'],
    ex: ['Syon House gallery (1762-69)', 'Osterley Park Etruscan room', 'Harewood House state rooms'],
    inf: ['Grand Tour antiquarianism', 'Pompeii & Herculaneum excavations', 'Robert Adam Spalatro drawings'], rel: ['Gilded Age Interiors', 'Louis XIV Baroque Style', 'Haussmann Paris'],
    src: [{ n: 'Wikipedia — Adam style', u: 'https://en.wikipedia.org/wiki/Adam_style', t: 'B' }, { n: 'Sir John Soane\'s Museum', u: 'https://www.soane.org', t: 'A' }],
    tg: ['adam style', 'neoclassical', 'interior', 'georgian', 'robert adam', 'antiquity'],
    pop: 39, niche: true,
    vd: { shape: 'flat wall planes with framed relief panels', line: 'delicate scroll and urn contours', composition: 'integrated room-composition unity', texture: 'paint matte, stucco low relief' },
    typ: { display: 'antique-serif inscription panels', body: 'invitation copperplate script', notes: 'rooms as engraved plates' },
    lit: { quality: 'sash-window daylight', temperature: 'warm-toned', shadow: 'stucco casts shallow relief shade' },
    ui: { background: 'pea-green field', surface: 'relief-panel cards', components: 'urn-motif icons', motion: 'panel-frame soft reveals' },
    par: 'period interior traditions',
  },
]