/**
 * Rebuild wave — Games & Retrofuturism r1 (22 entries).
 * Solo-authored after sandbox rollback. Wikipedia titles batch-verified via
 * API (2026-09-14). Dedup-checked against refreshed existing-names.txt.
 */
export const ENTRIES: any[] = [
  {
    n: 'Demoscene', a: ['demo scene', 'demos', 'crackers demogroup', 'compo intro'],
    cat: 'Internet Aesthetic', c: 'realtime computer art underground', e: 'community_subculture',
    o: 'European home-computer scene (Amiga, C64, Atari ST)', g: 'Finland, Germany, Sweden, Hungary, Poland, worldwide',
    p: '1980s-present', era: 'cracker intros to Assembly demo party institution',
    sum: 'Coders, musicians and pixel artists push hardware to its bones — for glory, not money.',
    desc: 'The demoscene grew from 1980s software piracy credits: cracking groups signed disk copies with animated intros, then the intros became the point. Demos are realtime, machine-limited audiovisual artworks — procedural geometry, tracker music, shader sorcery — competed at parties like Assembly (Helsinki), Revision (Saarbrücken) and The Gathering in categorized compos. Categories (64k intro, 4k intro, wild) enforce ascetic constraints; scene fame is earned by pushing a C64 or a GPU further than it should go. UNESCO-recognized in Finland, Germany and other countries as living digital culture, the scene seeded today\'s GPU demoscene, procedural art and much of game-engine visual culture.',
    col: [{ h: '#141414', n: 'CRT room black' }, { h: '#7b2ff7', n: 'copper-bar purple' }, { h: '#00e676', n: 'vector green' }, { h: '#e8c14a', n: 'scroll-text yellow' }, { h: '#2979ff', n: 'plasma blue' }],
    m: ['Amiga & C64 hardware limits', 'tracker software', 'shader code', 'CRT phosphor displays'],
    tx: ['raster-bar smoothness', 'pixel-perfect sprite work', 'phosphor glow persistence'],
    obj: ['64k and 4k intros', 'scroll-text credit walls', 'compo big screens', 'demo party halls'],
    ex: ['Assembly demo party, Helsinki', 'Revision demoparty, Germany', 'Second Reality (Future Crew, 1993)'],
    inf: ['software cracker credit screens', 'home-computer chip capabilities', 'arcade and rail-shooter visuals'], rel: ['Tracker & Chiptune Scene', 'Commodore 64 Loading Screens', 'Amiga Bitmap Culture'],
    src: [{ n: 'Wikipedia — Demoscene', u: 'https://en.wikipedia.org/wiki/Demoscene', t: 'B' }, { n: 'Pouët.net demoscene archive', u: 'https://www.pouet.net', t: 'C' }],
    tg: ['demoscene', 'realtime', 'pixel', 'amiga', 'compo', 'code'],
    pop: 38, niche: true,
    vd: { shape: 'procedural geometry and scroll-text geometry', line: 'raster-bar horizon bands', composition: 'machine-timed choreography', texture: 'phosphor glow, checkerboard dithering' },
    typ: { display: 'chunky pixel logo lettering', body: 'scroll-text credits', notes: 'greet-lists as scene etiquette' },
    lit: { quality: 'dark hall + CRT bloom', temperature: 'cool-toned', shadow: 'phosphor trails replace shadow' },
    ui: { background: 'CRT black', surface: 'scanline-glass cards', components: 'raster-bar progress meters', motion: 'sine-wave scrolltext drift' },
    par: 'digital underground cultures',
  },
  {
    n: 'Voxel Art', a: ['voxel', 'volumetric pixel art', 'MagicaVoxel renders', 'cube sculpture'],
    cat: 'Internet Aesthetic', c: '3D cube-grid digital sculpting', e: 'experimental_hybrid',
    o: 'game engines & medical imaging culture', g: 'global indie games, renders, Minecraft-adjacent worlds',
    p: '1980s-present (boom 2010s)', era: 'Comanche voxel engines to MagicaVoxel indie renaissance',
    sum: 'Pixels with depth: whole worlds built from cubes, lit like dioramas.',
    desc: 'Voxel art treats the cube as the atomic brush: volumetric grids rendered in tools like MagicaVoxel, or driven in-engine from Ultima Underworld through Minecraft. The modern scene flourished after ephtriu\'s MagicaVoxel (2015) made 8-bit-shaded voxel dioramas one-click renderable — tiny cities, cyberpunk ramen stands, medieval keeps, all readable at a glance yet constructed cube by cube. Games (Resogun, Teardown, voxel roguelikes) use voxels for destructibility and charm; artists like Sir carma built followings on single-cube craftsmanship. The aesthetic is digital sculpture: isometric mass, hard-edge color steps, miniature-world storytelling.',
    col: [{ h: '#e8963a', n: 'warm voxel orange' }, { h: '#2f7d4f', n: 'cube grass green' }, { h: '#b0b7bd', n: 'stone grey' }, { h: '#e8c14a', n: 'light-bloom gold' }, { h: '#2979ff', n: 'water blue' }],
    m: ['voxel grid engines', 'MagicaVoxel palettes', 'isometric render cameras', 'ambient occlusion shading'],
    tx: ['hard cube-edge steps', 'chunky AO corner shading', 'flat color faces'],
    obj: ['voxel diorama scenes', 'destructible game environments', 'voxel character sprites', 'city block scenes'],
    ex: ['MagicaVoxel featured galleries', 'Teardown physics voxel destruction', 'Sir carma voxel diorama series'],
    inf: ['pixel art logic extended to 3D', 'LEGO modular building', 'Minecraft block culture'], rel: ['Pixel Art', 'Low Poly 3D', 'Demoscene'],
    src: [{ n: 'Wikipedia — Voxel', u: 'https://en.wikipedia.org/wiki/Voxel', t: 'B' }, { n: 'MagicaVoxel official gallery (ephtriu)', u: 'https://ephtracy.github.io', t: 'C' }],
    tg: ['voxel', '3d', 'cubes', 'isometric', 'render', 'games'],
    pop: 47, niche: false,
    vd: { shape: 'grid-aligned cube massing with readable silhouettes', line: 'cube-edge outlines only', composition: 'isometric diorama framing', texture: 'flat-shaded faces, banded AO' },
    typ: { display: 'none', body: 'none', notes: 'worlds tell without words' },
    lit: { quality: 'single strong key light', temperature: 'warm-toned', shadow: 'cube corners self-shadow softly' },
    ui: { background: 'studio grey', surface: 'cube-grid cards', components: 'voxel-block icons', motion: 'cube-build assemble-in' },
    par: 'game art styles',
  },
  {
    n: 'Low Poly 3D', a: ['low poly', 'polygon reduction aesthetic', 'faceted 3D', 'flat-shaded 3D'],
    cat: 'Internet Aesthetic', c: 'deliberately few-polygon 3D style', e: 'experimental_hybrid',
    o: 'early 3D game hardware limits (PS1/N64 era)', g: 'indie games, motion design, stock 3D',
    p: '1990s-present (revival 2010s)', era: 'hardware necessity to intentional flat-shaded art style',
    sum: 'Three colors per triangle and not one more facet than needed.',
    desc: 'Low poly began as hardware reality — PlayStation and Nintendo 64 budgets meant characters of a few hundred triangles — and became an aesthetic when Unity-era indie artists discovered that few polygons with flat shading, strong silhouettes and pastel gradient lighting reads as calm, modern and affordable. Platforms (Sketchfab, Itch.io) and mobile games standardized the look: faceted terrain, cone-trees, capsule people, isometric game boards. Motion designers (Gorilla, studio reels) adopted the style for explainer geometry; the low-poly landscape render became a stock-image genre of its own.',
    col: [{ h: '#e8963a', n: 'faceted peach' }, { h: '#2f7d4f', n: 'cone-tree green' }, { h: '#2979ff', n: 'gradient sky blue' }, { h: '#f2efe4', n: 'terrain cream' }, { h: '#e8813a', n: 'sunset coral' }],
    m: ['polygon budgets', 'flat shading normals', 'vertex color palettes', 'gradient environment lighting'],
    tx: ['hard triangle facets', 'flat color faces', 'smooth vertex-gradient skies'],
    obj: ['isometric game terrain', 'capsule characters', 'cone and sphere props', 'orbiting camera scenes'],
    ex: ['Monument Valley-inspired terrain sets', 'Sketchfab low-poly showcases', 'indie mobile game art bibles'],
    inf: ['PS1/N64 hardware limits', 'flat-shaded arcade 3D (Virtua Racing)', 'isometric board-game composition'], rel: ['Voxel Art', 'Cel-Shaded Game Art', 'PS1-Era Survival Horror'],
    src: [{ n: 'Wikipedia — Low poly', u: 'https://en.wikipedia.org/wiki/Low_poly', t: 'B' }, { n: 'Sketchfab — low poly category', u: 'https://sketchfab.com', t: 'C' }],
    tg: ['lowpoly', '3d', 'flat shading', 'indie', 'facets', 'render'],
    pop: 55, niche: false,
    vd: { shape: 'minimal triangle massing, readable at 10% zoom', line: 'faceted silhouette edges', composition: 'isometric or hero-orbit framing', texture: 'flat facets, banded gradient light' },
    typ: { display: 'geometric sans UI overlays', body: 'short game-caption strips', notes: 'style favored in UI-heavy games' },
    lit: { quality: 'two-point gradient sky rig', temperature: 'warm-toned', shadow: 'soft banded AO under facets' },
    ui: { background: 'gradient dawn sky', surface: 'facet-tilt cards', components: 'poly-edge icons', motion: 'slow hero-object orbit' },
    par: 'game art styles',
  },
  {
    n: 'Cel-Shaded Game Art', a: ['cel shading', 'toon shading', 'ink outlines 3D', 'cartoon render'],
    cat: 'Internet Aesthetic', c: '3D rendering styled as hand-inked animation', e: 'experimental_hybrid',
    o: 'game R&D (Jet Set Radio, 2000)', g: 'Japanese and global studios, anime-adjacent games',
    p: '2000-present', era: 'Dreamcast toon-shading era to anime-game standard',
    sum: 'Polygons pretending to be cels: flat color, black ink, animation confidence.',
    desc: 'Cel shading (toon shading) maps 3D geometry onto hand-drawn animation logic: two or three flat color bands per surface, hard terminator edges, and deliberately inked outlines that stay constant width on screen. Jet Set Radio (2000) and Zelda: The Wind Waker (2002) proved the style\'s legs; Dragon Ball Z, Guilty Gear Xrd and Genshin Impact carried it into anime-gaming mainstream. The craft is in the normals and edge detection — making 3D lie convincingly about being 2D — and its appeal is timelessness: cel-shaded games rarely date as hard as realistic renders.',
    col: [{ h: '#e8c14a', n: 'highlight yellow' }, { h: '#c93636', n: 'cel red' }, { h: '#141414', n: 'ink outline black' }, { h: '#2979ff', n: 'sky blue band' }, { h: '#f2efe4', n: 'paper white' }],
    m: ['toon shader ramps', 'outline pass (backface or edge detect)', 'hand-painted textures', 'color-band ramp maps'],
    tx: ['flat cel color bands', 'constant-width ink lines', 'posterized light steps'],
    obj: ['cel-shaded characters', 'painted-look environments', 'action-comic cutscenes', 'anime-style effects sprites'],
    ex: ['Jet Set Radio (2000) street-cel look', 'The Wind Waker sailing vistas', 'Guilty Gear Xrd anime-accurate models'],
    inf: ['hand-drawn cel animation', 'comic book ink logic', 'Japanese TV anime production'], rel: ['Low Poly 3D', 'Manga Screentone', 'Voxel Art'],
    src: [{ n: 'Wikipedia — Cel shading', u: 'https://en.wikipedia.org/wiki/Cel_shading', t: 'B' }, { n: 'Sega — Jet Set Radio press materials', u: 'https://www.sega.com', t: 'C' }],
    tg: ['celshading', 'toon', 'anime', 'rendering', 'outlines', 'games'],
    pop: 52, niche: false,
    vd: { shape: 'volume simplified to poster planes', line: 'constant ink contour', composition: 'anime-key-frame framing', texture: 'flat color, no surface noise' },
    typ: { display: 'anime display katakana/logos', body: 'sub-clean minimal UI text', notes: 'lettering mimics anime title cards' },
    lit: { quality: 'sunny key with posterized falloff', temperature: 'warm-toned', shadow: 'two-step shadow bands' },
    ui: { background: 'sky-band blue', surface: 'ink-border cards', components: 'cel-band buttons', motion: 'smear-frame squash on tap' },
    par: 'game art styles',
  },
  {
    n: 'Doom Clone Era (Boomer Shooter)', a: ['boomer shooter', 'doom clone', '90s FPS aesthetic', 'fast retro shooter'],
    cat: 'Internet Aesthetic', c: '90s first-person shooter visual language', e: 'historical',
    o: 'US and European studios (id Software, 3D Realms)', g: 'global gaming, indie revival',
    p: '1992-1999 (revival 2019-present)', era: 'DOOM/Quake golden age to Dusk/WWise revival',
    sum: 'Fast muzzle flashes, sprite demons and M16s — the shooter look the revival keeps choosing.',
    desc: 'The Doom clone era (retroactively "boomer shooter") defined shooter visuals: 2.5D levels of shifting-sector architecture, sprite enemies billboarded in fake 3D, brown-and-grey textures lit by muzzle flash, HUDs with grinning status faces, and heavy-metal MIDIs. Doom (1993), Build-engine games (Duke Nukem 3D, Blood) and Quake\'s true-3D upgrade composed a grammar of speed, gore, and readable level color-coding (red=keys). The 2019+ revival (Dusk, Ion Fury, Wrath, Selaco) rebuilt the look with modern engines, and its fans kept the HUDs, the wall textures and the joy of the strafe.',
    col: [{ h: '#5a4a3a', n: 'wall-texture brown' }, { h: '#8c1f1f', n: 'blood/health red' }, { h: '#b0b7bd', n: 'tech-panel grey' }, { h: '#e8c14a', n: 'muzzle flash gold' }, { h: '#141414', n: 'void black' }],
    m: ['sprite billboards', 'sector-based level geometry', 'texture-mapped walls', 'MIDI soundtracks'],
    tx: ['chunky texel grain', 'palette-clamped lighting', 'pixel sprite jaggies'],
    obj: ['grinning HUD faces', 'status-bar weapon strips', 'sprite monster hordes', 'keycard color logic'],
    ex: ['DOOM (1993) E1M1 iconography', 'Duke Nukem 3D city levels', 'Dusk (2018) revival campaign'],
    inf: ['Wolfenstein 3D grid logic', 'heavy metal album art', 'hacker BBS culture'], rel: ['PS1-Era Survival Horror', 'Demoscene', 'Pixel Art'],
    src: [{ n: 'Wikipedia — First-person shooter', u: 'https://en.wikipedia.org/wiki/First-person_shooter', t: 'B' }, { n: 'id Software — DOOM legacy materials', u: 'https://www.idsoftware.com', t: 'C' }],
    tg: ['fps', 'retro', 'doom', 'sprites', '90s', 'shooter'],
    pop: 50, niche: false,
    vd: { shape: 'corridor perspective to big sprite encounters', line: 'wall texture seams as sightlines', composition: 'speed-run spatial flow', texture: 'low-res texel, palette banding' },
    typ: { display: 'bevelled metal HUD numerals', body: 'all-caps pickup messages', notes: 'face reacts — the UI has a mood' },
    lit: { quality: 'fullbright flash zones', temperature: 'warm-toned', shadow: 'sector light levels step without gradient' },
    ui: { background: 'tech-brown panels', surface: 'bevel-frame cards', components: 'LED-red counters', motion: 'strafe-dash screen shake' },
    par: 'game art styles',
  },
  {
    n: 'PS1-Era Survival Horror', a: ['PS1 horror', 'low-poly dread', 'survival horror aesthetic', 'Spencer Mansion look'],
    cat: 'Internet Aesthetic', c: 'grainy low-poly horror game style', e: 'historical',
    o: 'Japanese studios (Capcom, Konami, Square)', g: 'global gaming, indie horror revival',
    p: '1996-2004 (revival 2020s)', era: 'Resident Evil/Silent Hill era to Signalis revival',
    sum: 'Dithered fog, fixed cameras, polygon faces — horror born of hardware limits.',
    desc: 'The PlayStation survival horror look — Resident Evil\'s Spencer Mansion, Silent Hill\'s fog-banked streets — was engineered by constraint: low-poly models, pre-rendered fixed-camera backgrounds, heavy dithering, and grain filters that hid polygon seams while adding analog dread. Fog in Silent Hill both masked draw distance and became the game\'s psychology; Resident Evil\'s static frames turned rooms into stage plays of reveal. The style\'s uncanny textures and limited animation read as wrongness, which is why 2020s indie horror (Signalis, Crow Country, Tormented Souls) deliberately resurrects the PS1 grain as a genre costume.',
    col: [{ h: '#141414', n: 'grain black' }, { h: '#5a4a3a', n: 'mansion wood brown' }, { h: '#7a8a8a', n: 'fog grey-green' }, { h: '#8c1f1f', n: 'blood dark red' }, { h: '#b0b7bd', n: 'corridor steel' }],
    m: ['low-poly character models', 'pre-rendered background plates', 'dither filters', 'CRT display grain'],
    tx: ['dithered gradient stair-steps', 'VHS-style grain', 'polygon joint warping'],
    obj: ['fixed-camera room compositions', 'item-box save points', 'document pickups with serif type', 'fog-banked streets'],
    ex: ['Resident Evil (1996) mansion layout', 'Silent Hill (1999) fog world', 'Signalis (2022) PS1-revival rendering'],
    inf: ['Italian giallo and B-horror film', 'jewel-case CD-ROM era', 'Japanese gothic literature imagery'], rel: ['Doom Clone Era (Boomer Shooter)', 'VHS Tracking Glitch', 'Film Noir'],
    src: [{ n: 'Wikipedia — Survival horror', u: 'https://en.wikipedia.org/wiki/Survival_horror', t: 'B' }, { n: 'Capcom — Resident Evil archive', u: 'https://www.capcom.com', t: 'C' }],
    tg: ['ps1', 'horror', 'grain', 'fog', 'fixed camera', 'retro games'],
    pop: 54, niche: false,
    vd: { shape: 'boxy rooms framed like theater sets', line: 'dither-edge soft silhouettes', composition: 'fixed-frame dread blocking', texture: 'VHS grain over low-res textures' },
    typ: { display: 'serif item/document lettering', body: 'typewriter file text', notes: 'ink-on-paper props carry lore' },
    lit: { quality: 'weak bulb pools in darkness', temperature: 'cold-toned', shadow: 'dithered darkness, fog eats distance' },
    ui: { background: 'grain black', surface: 'dither-panel cards', components: 'serif document frames', motion: 'door-open wipe transitions' },
    par: 'game art styles',
  },
  {
    n: 'Point-and-Click Adventure Art', a: ['point and click', 'LucasArts style', 'SCUMM backgrounds', 'adventure game backgrounds'],
    cat: 'Internet Aesthetic', c: 'illustrated adventure-game scene art', e: 'historical',
    o: 'Sierra & LucasArts studios (California)', g: 'global adventure gaming',
    p: '1984-2000s (revival present)', era: 'King\'s Quest pixel ages to Monkey Island hi-res era',
    sum: 'Painted rooms, walking characters, and verbs — the coziest genre of game art.',
    desc: 'Point-and-click adventure art is the illustrated background tradition of Sierra and LucasArts: every screen a painting (first 256-color, then hi-res) with strong foreground props, readable inventory items and characters composited in sprite or rotated-3D. The style ranges from King\'s Quest storybook watercolor to Monkey Island\'s stylized caricature and Full Throttle\'s film-noir shading; Tim Schafer-era backgrounds hold up as standalone illustration. Modern revivals (Thimbleweed Park, Return to Monkey Island, Broken Sword remasters) keep the grammar — hand-painted rooms, verb rows, elegant cursor puzzles — alive as comfort gaming\'s visual dialect.',
    col: [{ h: '#e8c14a', n: 'storybook yellow' }, { h: '#2f7d4f', n: 'island green' }, { h: '#1f4d8c', n: 'pirate coat blue' }, { h: '#8c1f1f', n: 'neon-sign red' }, { h: '#141414', n: 'ink line black' }],
    m: ['hand-painted background plates', 'sprite character cutouts', 'verb-row UI chrome', 'palette-swap systems'],
    tx: ['brushed plate texture', 'crisp sprite edges', 'UI bevel chrome'],
    obj: ['interactive hotspot props', 'inventory icon close-ups', 'verb-row interface bars', 'door-and-room stage sets'],
    ex: ['The Secret of Monkey Island backgrounds', 'Full Throttle biker-noir plates', 'Thimbleweed Park\'s period interiors'],
    inf: ['animated film background painting', 'comic panel storytelling', 'Disney parks audio-animatronic whimsy'], rel: ['PS1-Era Survival Horror', 'Pixel Art', 'Cel-Shaded Game Art'],
    src: [{ n: 'Wikipedia — Adventure game', u: 'https://en.wikipedia.org/wiki/Adventure_game', t: 'B' }, { n: 'Lucasfilm Games — Monkey Island archives', u: 'https://lucasfilmgames.com', t: 'C' }],
    tg: ['adventure', 'pointandclick', 'painted', 'backgrounds', 'lucasarts', 'retro games'],
    pop: 45, niche: false,
    vd: { shape: 'stage-set room depth with prop foregrounds', line: 'painted edge definition, sprite cutout', composition: 'every item reads as clickable', texture: 'brushed plate, chunky UI chrome' },
    typ: { display: 'genre logo hand-lettering', body: 'verb-row and dialog text', notes: 'cursor changes are punctuation' },
    lit: { quality: 'scene-lit painted mood', temperature: 'varies by plate — horror to comedy', shadow: 'painted shadow anchors props' },
    ui: { background: 'painted plate', surface: 'bevel-chrome cards', components: 'verb-row buttons', motion: 'cursor hotspot shimmer' },
    par: 'game art styles',
  },
  {
    n: 'Arcade Cabinet Culture', a: ['arcade cabinet', 'coin-op art', 'attract mode', 'upright arcade'],
    cat: 'Music & Sonic Culture', c: 'coin-operated game machine visual world', e: 'historical',
    o: 'Japanese and US arcade industry (Taito, Namco, Atari)', g: 'global arcade golden age',
    p: '1978-1990s (revival present)', era: 'Space Invaders boom to street-corner nostalgia',
    sum: 'Side-art missiles, backlit marquees and attract-mode loops — machines as billboards.',
    desc: 'The golden-age arcade cabinet was a three-dimensional advertisement: hand-painted side art (Galaga\'s red bug fleet, Street Fighter II\'s full-body fighters), backlit marquees, bezel art framing the CRT, and control panels labeled like cockpits. Inside, attract modes looped demo gameplay to pull quarters; outside, cabinets lined arcades in color ranks. Cabinet art mixed airbrushed sci-fi realism, Katsuya Terada-style brushwork and graffiti energy, and its icons — Pac-Man mazes, Invader rows — escaped into streetwear and print. Modern barcades and re-releases (Arcade1Up, cabinets by Taito/Namco museums) keep the physical format alive as design heritage.',
    col: [{ h: '#141414', n: 'cabinet black' }, { h: '#e8c14a', n: 'marquee backlight gold' }, { h: '#c93636', n: 'invader red' }, { h: '#00e676', n: 'vector green' }, { h: '#2979ff', n: 'side-art blue' }],
    m: ['silkscreened side panels', 'backlit marquee boxes', 'CRT bezel art', 'happ-style control panels'],
    tx: ['airbrush side-art sheen', 'marquee plastic glow', 'joystick-worn panel gloss'],
    obj: ['upright cabinet shells', 'marquee lightboxes', 'control panel overlays', 'attract-mode demo loops'],
    ex: ['Galaga & Ms. Pac-Man cabinet art', 'Street Fighter II side art', 'Arcade1Up home reproductions'],
    inf: ['airbrush van-art culture', 'Japanese robot anime posters', 'pachinko parlor display logic'], rel: ['Pinball Backglass Art', 'Demoscene', 'Doom Clone Era (Boomer Shooter)'],
    src: [{ n: 'Wikipedia — Arcade cabinet', u: 'https://en.wikipedia.org/wiki/Arcade_cabinet', t: 'B' }, { n: 'The International Arcade Museum', u: 'https://www.arcademuseum.org', t: 'A' }],
    tg: ['arcade', 'cabinet', 'coinop', 'marquee', 'retro games', '80s'],
    pop: 58, niche: false,
    vd: { shape: 'towering cabinet silhouettes in glowing rows', line: 'airbrushed action diagonals', composition: 'attract-loop spectacle per machine', texture: 'gloss laminate, CRT phosphor' },
    typ: { display: 'chrome-and-flame game logos', body: 'insert-coin instruction strips', notes: 'high-score tables as social text' },
    lit: { quality: 'dark arcade, self-lit cabinets', temperature: 'warm-toned', shadow: 'backlight makes marquee glow halos' },
    ui: { background: 'cabinet black', surface: 'marquee-glow cards', components: 'coin-slot accents', motion: 'attract-mode loop playback' },
    par: 'game hardware cultures',
  },
  {
    n: 'Pinball Backglass Art', a: ['pinball backglass', 'playfield art', 'pinball machine art', 'flasher-lit glass'],
    cat: 'Graphic Design', c: 'pinball machine illustration tradition', e: 'historical',
    o: 'Chicago pinball industry (Bally, Williams, Stern, Gottlieb)', g: 'US pinball golden age, collector market',
    p: '1930s-present', era: 'payout-machine era to solid-state theme machines',
    sum: 'Neon bombshells, chrome futures and monster mashes painted on glass behind flashing lights.',
    desc: 'Pinball\'s backglass and playfield art is a 90-year commercial illustration tradition: Airbrushed starlets, hot rods, devils, spacemen and, since the 1990s, licensed movie and band themes — painted by house artists like Gordon Morison, Dave Christensen (Firepower), Pat McMahon and Python Anghelo, with playfields adding ramps, plastics and pop bumpers as physical set-dressing. Machines like The Addams Family (1992) and medieval Madness merged theme, humor and layout into cult canon; collectors restore glasses under UV light, and modern Stern machines keep commissioning full illustrated packages. It is vernacular American illustration at arcade scale.',
    col: [{ h: '#e8c14a', n: 'flasher lamp gold' }, { h: '#c93636', n: 'bombshell red' }, { h: '#2979ff', n: 'chrome-sky blue' }, { h: '#141414', n: 'playfield black' }, { h: '#00e676', n: 'score display green' }],
    m: ['reverse-painted backglass', 'silk-screened playfields', 'UV-cured inks', 'flasher lamps and DOMES'],
    tx: ['glass-laminate gloss', 'airbrush neon edge', 'plastic ramp shine'],
    obj: ['themed backglasses', 'miniature playfield plastics', 'pop bumper caps', 'spinning targets'],
    ex: ['The Addams Family (Bally 1992)', 'Medieval Madness (Williams 1997)', 'Stern licensed band machines (Metallica)'],
    inf: ['movie-poster illustration', 'hot-rod pinstriping', 'Las Vegas signage logic'], rel: ['Arcade Cabinet Culture', 'Raygun Gothic', 'American Neon Signage'],
    src: [{ n: 'Wikipedia — Pinball', u: 'https://en.wikipedia.org/wiki/Pinball', t: 'B' }, { n: 'Internet Pinball Database', u: 'https://www.ipdb.org', t: 'C' }],
    tg: ['pinball', 'backglass', 'arcade', 'illustration', 'airbrush', 'games'],
    pop: 43, niche: true,
    vd: { shape: 'portrait-format glass scenes bursting past frame', line: 'airbrush highlight sweeps', composition: 'theme chaos organized by score display', texture: 'glass gloss, lamp flare, plastic shine' },
    typ: { display: 'theme-logo lettering machine-specific', body: 'rule and scoring text', notes: 'backglass is the poster' },
    lit: { quality: 'self-lit flasher storms', temperature: 'warm-toned', shadow: 'flasher pops erase shadow' },
    ui: { background: 'playfield black', surface: 'glass-gloss cards', components: 'bumper-cap icons', motion: 'multiplier flash pulses' },
    par: 'game hardware cultures',
  },
  {
    n: 'Amiga Bitmap Culture', a: ['amiga art', 'Workbench aesthetic', 'Amiga HAM mode', ' Deluxe Paint scene'],
    cat: 'Internet Aesthetic', c: 'Commodore Amiga creative computing style', e: 'historical',
    o: 'Commodore-Amiga user culture (1985-1994)', g: 'Europe, US, Australia demoscene & desktop scene',
    p: '1985-1994 (revival present)', era: 'home-computer multimedia flagship to cult classic',
    sum: '4096 colors, tracker modules and Workbench grey — the machine that taught Europe to paint on pixels.',
    desc: 'The Commodore Amiga defined a creative-computing visual culture: Deluxe Paint pixel illustration, HAM-mode 4096-color showpieces, Boing Ball demo physics, and Workbench\'s grey-and-blue desktop look. TV stations (like BBC\'s 1990s graphics departments) used Amigas for broadcast art; demoscene groups (Kefrens, Red Sector) pushed copper bars and dot pools; and tracked MOD music gave the machine a sound identity. The Amiga look — chunky fonts, saturated pixel gradients, cheerful gadget chrome — persists in retro-computing revivals, PiStorm-era hardware and A-EON continuations, and Deluxe Paint-era brushes seeded today\'s pixel-art tooling.',
    col: [{ h: '#141414', n: 'Workbench charcoal' }, { h: '#2979ff', n: 'Workbench blue' }, { h: '#e8c14a', n: 'copper-bar gold' }, { h: '#e8963a', n: 'HAM gradient orange' }, { h: '#00e676', n: 'sprite green' }],
    m: ['HAM-mode graphics chip', 'Deluxe Paint brushes', 'tracker MOD files', '3.5" floppy media'],
    tx: ['pixel gradient banding', 'copper-bar smoothness', 'floppy-neighborhood dithering'],
    obj: ['Deluxe Paint illustrations', 'Workbench desktop windows', 'Boing Ball icons', 'demo cracktro screens'],
    ex: ['Boing Ball demo (1984)', 'Kefrens "Desert Dream" demo', 'BBC TV Amiga graphics suites'],
    inf: ['C64 heritage', 'European computer club culture', 'broadcast graphics professionalization'], rel: ['Demoscene', 'Commodore 64 Loading Screens', 'Tracker & Chiptune Scene'],
    src: [{ n: 'Wikipedia — Amiga', u: 'https://en.wikipedia.org/wiki/Amiga', t: 'B' }, { n: 'Amiga Forever archive (Cloanto)', u: 'https://www.amigaforever.com', t: 'C' }],
    tg: ['amiga', 'pixel', 'retrocomputing', 'workbench', 'ham', 'demoscene'],
    pop: 37, niche: true,
    vd: { shape: 'pixel-precise desktop windows and art panels', line: 'copper-bar horizontal sweeps', composition: 'gadget-grid desktop logic', texture: 'deluxe paintbrush dithering' },
    typ: { display: 'Topaz bitmap font', body: 'Workbench icon labels', notes: 'fonts are the UI\'s face' },
    lit: { quality: 'bedroom-monitor glow', temperature: 'cool-toned', shadow: 'CRT bezel shadow frames the glow' },
    ui: { background: 'Workbench grey', surface: 'beveled window cards', components: 'Amiga gad-tool buttons', motion: 'copper-bar screen wipes' },
    par: 'retrocomputing cultures',
  },
  {
    n: 'Commodore 64 Loading Screens', a: ['C64 loader art', 'tape loading screens', 'multiload art', 'Commodore tape covers'],
    cat: 'Internet Aesthetic', c: 'C64 tape and disk loading visual culture', e: 'historical',
    o: 'UK & European C64 software houses', g: 'Europe (UK, Germany, Scandinavia), Australia',
    p: '1982-1993', era: 'cassetteSoftware era to cracktro heirlooms',
    sum: 'The picture you stared at for three minutes: borders, logos and hope.',
    desc: 'On the Commodore 64, the loading screen was half the product: while cassette tape hissed through loader bars, players stared at title pictures squeezed into the C64\'s attribute-grid — multicolor char-cell art with forced colors per 8x8 cell — produced by graphics houses like The Designers Republic precursors, Bob Wakelin and Oliver Frey for Zzap!64-adjacent studios. Ocean, Imagine and Hewson commissioned painted-to-pixel conversions that were often better than the games; cracktros later gave the same slots to demos. The grid-constrained look (two colors per cell, charset glyphs as texture) is a distinctive pixel-art dialect still imitated in modern indie covers.',
    col: [{ h: '#2979ff', n: 'loader border blue' }, { h: '#141414', n: 'char-cell black' }, { h: '#c93636', n: 'attribute red' }, { h: '#00e676', n: 'sprite green' }, { h: '#e8c14a', n: 'logo gold' }],
    m: ['C64 VIC-II attribute grid', 'charset glyph textures', 'cassette tape artwork', 'bitmap conversion software'],
    tx: ['8x8 cell color forcing', 'charset dithering', 'tape-noise patience'],
    obj: ['tape inlay covers', 'loading title screens', 'multiload disk art', 'Zzap!64 cover scans'],
    ex: ['Ocean Software multiload screens', 'Imagine Software tape covers', 'Turbo Tape loading bars'],
    inf: ['VHS cover painting', 'UK comics (Frey at RG)', 'spectrum color clash tradition'], rel: ['Amiga Bitmap Culture', 'Demoscene', 'Pixel Art'],
    src: [{ n: 'Wikipedia — Commodore 64', u: 'https://en.wikipedia.org/wiki/Commodore_64', t: 'B' }, { n: 'C64.com game archive', u: 'https://www.c64.com', t: 'C' }],
    tg: ['c64', 'loading screen', 'pixel', 'tape', 'retrocomputing', '8bit'],
    pop: 36, niche: true,
    vd: { shape: '8x8 attribute-grid pictures within border margins', line: 'forced-palette cell shading', composition: 'title logo top, scene below, border alive', texture: 'chunky charset grain' },
    typ: { display: 'charset-built game logos', body: 'PRESS PLAY ON TAPE prompts', notes: 'borders pulse during load' },
    lit: { quality: 'bedroom TV glow', temperature: 'cool-toned', shadow: 'cell-clamped two-tone shading' },
    ui: { background: 'C64 border blue', surface: 'char-cell cards', components: 'tape-progress bars', motion: 'striped border loading pulse' },
    par: 'retrocomputing cultures',
  },
  {
    n: 'Retrofuturism', a: ['retro futurism', 'yesterday\'s tomorrow', 'paleo-futurism', 'retrofuture'],
    cat: 'Technology & Retrofuturism', c: 'past visions of the future as aesthetic', e: 'community_subculture',
    o: 'Western pulp, world\'s fairs and industrial design', g: 'global design culture',
    p: '1940s-present (as look 1970s-present)', era: 'mid-century optimism to nostalgic design genre',
    sum: 'Tomorrow as imagined yesterday: fins, bubbles, chrome and unearned optimism.',
    desc: 'Retrofuturism is the retrospective enjoyment of past futures: ray-gun rocketships, household robots, monorails, dome cities and atomic-age optimism as seen from after their promised dates failed to arrive. The term covers a family of styles — Atompunk\'s tailfins, Dieselpunk\'s riveted machinery, Raygun Gothic\'s swooping pulp craft — and a criticism tradition (paleofuturism) that studies why futures were imagined as they were. Designers mine it for warmth without nostalgia irony; manga and games borrow its confident chrome. The core appeal: a future that believed in itself, now viewable as period charm.',
    col: [{ h: '#e8963a', n: 'atomic orange' }, { h: '#b0b7bd', n: 'chrome silver' }, { h: '#2979ff', n: 'sky-line blue' }, { h: '#e8c14a', n: 'starburst gold' }, { h: '#141414', n: 'outline ink' }],
    m: ['chrome plating', 'fiberglass shells', 'starburst clock forms', 'pulp-printed illustration'],
    tx: ['polished chrome streaks', 'molded plastic gloss', 'halftone pulp print'],
    obj: ['tailfin car dreams', 'monorail transit visions', 'dome-city cutaways', 'home-robot appliances'],
    ex: ['1939 & 1964 World\'s Fair visions', 'Popular Mechanics cover futures', 'Fallout series retrofuture set dressing'],
    inf: ['World\'s Fair modernism', 'Googie commercial architecture', 'pulp SF magazine covers'], rel: ['Futurama 1939 World\'s Fair', 'Atompunk', 'Raygun Gothic'],
    src: [{ n: 'Wikipedia — Retrofuturism', u: 'https://en.wikipedia.org/wiki/Retrofuturism', t: 'B' }, { n: 'Paleofuture (retrofuture archive blog)', u: 'https://paleofuture.com', t: 'C' }],
    tg: ['retrofuture', 'atomic', 'chrome', 'pulp', 'nostalgia', 'design'],
    pop: 60, niche: false,
    vd: { shape: 'swept fins, domes and rocket profiles', line: 'starburst and speed-line accents', composition: 'tomorrow-as-brochure framing', texture: 'chrome, plastic, halftone print' },
    typ: { display: 'speed-lettered futurescript', body: 'optimistic caption blocks', notes: 'exclamation marks unironic' },
    lit: { quality: 'studio-white optimism', temperature: 'warm-toned', shadow: 'chrome reflects instead of shading' },
    ui: { background: 'booth white', surface: 'chrome-trim cards', components: 'starburst toggles', motion: 'fin-sweep parallax' },
    par: 'retrofuturist family',
  },
  {
    n: 'Atompunk', a: ['atomicpunk', 'atomic age retrofuture', 'atomicpunk aesthetic', '1950s atom futurism'],
    cat: 'Technology & Retrofuturism', c: 'Atomic Age retrofuture style', e: 'community_subculture',
    o: 'US mid-century design culture', g: 'US-influenced global pop design',
    p: '1945-1965 (as -punk 1990s-present)', era: 'atomic optimism era to retro-genre label',
    sum: 'Fins, atoms and jello — the future when splitting the atom was daydreaming.',
    desc: 'Atompunk names the retrofuture of the atomic era: tailfins and chrome, starburst clocks, googie diners, bubble helmets, jello-and-casserole domestic futurism, and the general visual language from 1945-1965 when nuclear promise (not yet dread) powered optimism. The "-punk" suffix — applied by analogy to cyberpunk — formalized it as a design genre alongside dieselpunk and steampunk; games (Fallout), comics (Minutemen), TV (The Incredibles, Hello Tomorrow!) and collectors (orphan googie signage) sustain its aesthetics. Its signature motifs: atom orbit diagrams, blast-lamp silhouettes, and starbursts wherever ornament is wanted.',
    col: [{ h: '#e8963a', n: 'tailfin coral' }, { h: '#b0b7bd', n: 'diner chrome' }, { h: '#2979ff', n: 'starburst turquoise-blue' }, { h: '#e8c14a', n: 'atom gold' }, { h: '#f2efe4', n: 'formica white' }],
    m: ['chrome & formica', 'starburst metalwork', 'tailfin sheet metal', 'Pantone mid-century palette'],
    tx: ['polished chrome streaks', 'formica gloss', 'lettering with orbit-dot i\'s'],
    obj: ['atom-orbit clocks', 'tailfin fins-on-everything', 'bubble space helmets', 'googie signage boomerangs'],
    ex: ['Fallout (1997-) pip-boy futurism', 'The Incredibles title design', 'Seattle Space Needle era googie'],
    inf: ['atomic-age industrial design', 'Googie architecture', 'cold-war domestic futurism'], rel: ['Retrofuturism', 'Googie Architecture', 'Dieselpunk'],
    src: [{ n: 'Wikipedia — Cyberpunk derivatives', u: 'https://en.wikipedia.org/wiki/Cyberpunk_derivatives', t: 'B' }, { n: 'Smithsonian — Atomic Age design', u: 'https://www.si.edu', t: 'A' }],
    tg: ['atompunk', 'atomic', '1950s', 'tailfins', 'retrofuture', 'chrome'],
    pop: 48, niche: false,
    vd: { shape: 'swept, boosted, orbiting geometry', line: 'starburst and boomerang motifs', composition: 'drive-in optimism framing', texture: 'chrome over formica, halftone print' },
    typ: { display: 'atom-orbit and tailfin logotypes', body: 'clean mid-century sans captions', notes: 'future spelled with excitement' },
    lit: { quality: 'drive-in neon dusk', temperature: 'warm-toned', shadow: 'fins cast wing-like shade' },
    ui: { background: 'diner turquoise', surface: 'chrome-edge cards', components: 'starburst spinners', motion: 'fin-fin sweep transitions' },
    par: 'retrofuturist family',
  },
  {
    n: 'Dieselpunk', a: ['diesel punk', 'dieselpunk aesthetic', 'interwar retrofuture', 'wartime machinery futurism'],
    cat: 'Technology & Retrofuturism', c: 'interwar machinery retrofuture', e: 'community_subculture',
    o: 'interwar industrial design (1918-1939)', g: 'global genre culture, cosplay and game design',
    p: '1918-1939 (as -punk 2000s-present)', era: 'interwar machinery to retro-genre label',
    sum: 'Rivets, oil and dusk — the interwar machine future, armored and grainy.',
    desc: 'Dieselpunk is the retrofuture of the interwar years: riveted dreadnought geometry, airship hangars, testbed monoplanes, streamliner locomotives, art-deco radios and the somber industrial palette of oil, steel and smoke. The term — coined online in 2001 (Lewis Pollak & Dan LaSoura, for the RPG Children of the Sun) — sets the tone against steampunk\'s brass: diesel is grimmer, heavier, film-grainier. Games (Crimson Skies, Iron Harvest, Bioshock\'s rapture-era machines), cosplay and model-making sustain the aesthetic, and its art direction leans on Weimar posters, WPA murals and RKO serial menace.',
    col: [{ h: '#3a3a3a', n: 'armor gunmetal' }, { h: '#8a5230', n: 'rust oxide' }, { h: '#c9a227', n: 'deco brass' }, { h: '#141414', n: 'hangar black' }, { h: '#7a6a4f', n: 'canvas khaki' }],
    m: ['riveted steel plate', 'diesel engine blocks', 'canvas and doped fabric', 'deco brass trim'],
    tx: ['rivet-row rhythm', 'oil-stain patina', 'art-deco lacquer'],
    obj: ['airship hangar interiors', 'streamliner locomotive noses', 'deco radio cabinets', 'interwar recruiting posters'],
    ex: ['Crimson Skies aircraft line-ups', 'Bioshock\'s rapture industrial decor', 'Sky Captain and the World of Tomorrow'],
    inf: ['Weimar and WPA poster design', 'interwar aeronautics', 'art deco industrial styling'], rel: ['Decopunk', 'Retrofuturism', 'Streamline Moderne'],
    src: [{ n: 'Wikipedia — Dieselpunk', u: 'https://en.wikipedia.org/wiki/Dieselpunk', t: 'B' }, { n: 'Dieselpunks community archive', u: 'https://www.dieselpunks.org', t: 'C' }],
    tg: ['dieselpunk', 'interwar', 'rivets', 'artdeco', 'machinery', 'retrofuture'],
    pop: 42, niche: false,
    vd: { shape: 'heavy riveted masses, heroic verticals', line: 'deco step and speed-swoosh', composition: 'poster-drama diagonal staging', texture: 'gunmetal, rust, canvas grain' },
    typ: { display: 'deco condensed capitals', body: 'typewriter field reports', notes: 'propaganda-poster tone' },
    lit: { quality: 'smoky hangar shafts', temperature: 'cool-toned', shadow: 'dramatic noir side-light' },
    ui: { background: 'hangar grey', surface: 'rivet-frame cards', components: 'gauge-dial toggles', motion: 'engine-idle vibration' },
    par: 'retrofuturist family',
  },
  {
    n: 'Decopunk', a: ['deco punk', 'art deco futurism', 'deco retrofuture', 'Metropolis look'],
    cat: 'Technology & Retrofuturism', c: 'art-deco futurism variant of dieselpunk', e: 'community_subculture',
    o: 'art deco machine-age design (1920s-30s)', g: 'global genre culture',
    p: '1920s-1930s (as -punk 2000s-present)', era: 'deco machine-age to retro-genre label',
    sum: 'Dieselpunk\'s glamorous sibling: chrome ziggurats instead of rust and grease.',
    desc: 'Decopunk is the art-deco-leaning, cleaner-surfaced branch of the retrofuture family: ziggurat skyscrapers, sunburst grilles, lacquered chrome, illuminated theater marquees and the sort of gleaming metropolis Metropolis and the Chrysler Building promised. Where dieselpunk goes grimy and military, decopunk stays dressed for the premiere — polish, glamour, symmetry, stepped ornamentation. Its canon includes Bioshock Infinite\'s Columbia lighter modes, Batman: The Animated Series\' deco-noir, and The Rocketeer; collectors point to Coney Island\'s Parachute Jump and Radio City interiors as ground truth for the style\'s geometry.',
    col: [{ h: '#c9a227', n: 'deco gold' }, { h: '#141414', n: 'lacquer black' }, { h: '#f2efe4', n: 'marble white' }, { h: '#2979ff', n: 'marquee blue neon' }, { h: '#8c1f1f', n: 'premiere red' }],
    m: ['polished chrome & brass', 'black lacquer', 'marble & glass block', 'neon tubing'],
    tx: ['stepped-deco symmetry', 'lacquer deep gloss', 'neon tube glow'],
    obj: ['ziggurat towers', 'sunburst grille radios', 'theater marquees', 'deco elevator doors'],
    ex: ['Batman: The Animated Series city style', 'The Rocketeer aircraft & clubs', 'Bioshock Infinite Columbia interiors'],
    inf: ['art deco architecture', 'Metropolis (1927) film design', 'streamlined ocean liner interiors'], rel: ['Dieselpunk', 'Raygun Gothic', 'Retrofuturism'],
    src: [{ n: 'Wikipedia — Cyberpunk derivatives', u: 'https://en.wikipedia.org/wiki/Cyberpunk_derivatives', t: 'B' }, { n: 'Decopunk community wiki', u: 'https://deco-punk.fandom.com', t: 'C' }],
    tg: ['decopunk', 'artdeco', 'chrome', 'glamour', 'retrofuture', 'metropolis'],
    pop: 36, niche: true,
    vd: { shape: 'stepped ziggurat symmetry and sunbursts', line: 'parallel deco banding', composition: 'marquee-lit poster staging', texture: 'lacquer, chrome, marble' },
    typ: { display: 'tall deco capitals with stepped shadows', body: 'playbill-style serif lines', notes: 'symmetry above all' },
    lit: { quality: 'marquee neon against marble', temperature: 'warm-toned', shadow: 'hard geometric light steps' },
    ui: { background: 'lacquer black', surface: 'gold-stepped cards', components: 'sunburst spinners', motion: 'marquee chase lights' },
    par: 'retrofuturist family',
  },
  {
    n: 'Raygun Gothic', a: ['raygun gothic', 'retro rocket', 'pulp rocket aesthetic', 'Buck Rogers look'],
    cat: 'Technology & Retrofuturism', c: 'pulp-era rocket ship futurism', e: 'community_subculture',
    o: 'US pulp SF magazines (Amazing Stories, Planet Stories)', g: 'US pop design, global genre culture',
    p: '1926-1960 (as label 1980s-present)', era: 'pulp magazine era to design-historian label',
    sum: 'Fin-headed rocketships and zap-guns — the future drawn in bright pulp ink.',
    desc: 'Raygun Gothic is the term (coined by William Gibson in "The Gernsback Continuum") for the pulp-SF visual language of 1926-1950s: swooping finned rocketships, bubble canopies, needle-nosed zap guns, dials-and-bubbles control panels and underdome cities — the future as Amazing Stories cover art. Its designers borrowed from streamliners, deco and world\'s-fair futurism; its legacy runs through Forbidden Planet props, Tomorrowland, The Iron Giant, and every toy rocket that means "space age". The style is optimistic, drawn-curve smooth, and permanently associated with chrome and starlight.',
    col: [{ h: '#2979ff', n: 'pulp sky blue' }, { h: '#c9a227', n: 'rocket brass' }, { h: '#b0b7bd', n: 'hull chrome' }, { h: '#c93636', n: 'fin stripe red' }, { h: '#e8c14a', n: 'zap-flash gold' }],
    m: ['chrome and painted tin', 'die-cast rocket toys', 'pulp-print illustration', 'bubble acrylic domes'],
    tx: ['die-cast toy gloss', 'pulp halftone ink', 'swooping rivet lines'],
    obj: ['finned rocketships', 'ray gun props', 'bubble-helmet spacesuits', 'undersea-dome city cutaways'],
    ex: ['Forbidden Planet (1956) prop design', 'Amazing Stories cover gallery (Rogers, Ley)', 'Toy rocket die-cast golden age'],
    inf: ['Gernsback-era SF covers', 'streamline industrial design', 'world\'s fair futurama rides'], rel: ['Retrofuturism', 'Futurama 1939 World\'s Fair', 'Atompunk'],
    src: [{ n: 'Wikipedia — Raygun Gothic', u: 'https://en.wikipedia.org/wiki/Raygun_Gothic', t: 'B' }, { n: 'William Gibson — The Gernsback Continuum', u: 'https://www.williamgibsonbooks.com', t: 'C' }],
    tg: ['raygun', 'rocket', 'pulp', 'retrofuture', 'chrome', 'science fiction'],
    pop: 45, niche: false,
    vd: { shape: 'swooping rocket profiles with triple fins', line: 'speed-curve swept outlines', composition: 'cover-art dynamic diagonal', texture: 'chrome streaks over halftone sky' },
    typ: { display: 'tall condensed pulp mastheads', body: 'breathless caption columns', notes: 'titles shout in chrome' },
    lit: { quality: 'space-sunset gradient', temperature: 'warm-toned', shadow: 'rockets self-shadow in color bands' },
    ui: { background: 'pulp violet', surface: 'chrome-finned cards', components: 'zap-button accents', motion: 'rocket-launch lift-off' },
    par: 'retrofuturist family',
  },
  {
    n: 'Clockpunk', a: ['clock punk', 'renaissance tech', 'da vinci futurism', 'automaton age'],
    cat: 'Technology & Retrofuturism', c: 'Renaissance clockwork retrofuture', e: 'community_subculture',
    o: 'Renaissance Europe (Leonardo notebooks, automaton culture)', g: 'global genre culture',
    p: '1400s-1600s (as -punk 2000s-present)', era: 'renaissance engineering to retro-genre label',
    sum: 'Gears, springs and automata — the Renaissance\'s mechanical future.',
    desc: 'Clockpunk imagines the technological future built on Renaissance engineering: da Vinci-style flying machines, self-moving automata, cathedral-sized orreries, spring-driven arms and gear-punk weapons, all rendered in woodcut, sepia paper and polished brass. The term — a branch of the -punk family coined online in the 2000s — draws on Leonardo\'s notebooks, the mechanical curiosity cabinets of Rudolf II, and 16th-century automaton masterpieces. Games (Thief\'s Hammerite machines, Assassin\'s gear cities), novels and cosplayers use the aesthetic for a future that smells of wood shavings, hot metal and church incense instead of oil.',
    col: [{ h: '#c9a227', n: 'brass gear gold' }, { h: '#8a5230', n: 'walnut wood' }, { h: '#d9c8a3', n: 'parchment sepia' }, { h: '#141414', n: 'woodcut ink' }],
    m: ['brass clockwork', 'oak and walnut frames', 'parchment and iron-gall ink', 'coiled spring steel'],
    tx: ['gear-teeth precision', 'wood grain and turning', 'ink-on-paper hatching'],
    obj: ['da Vinci-style flying machines', 'automaton knights and monks', 'orrery planet models', 'gearwork crossbows'],
    ex: ['Leonardo da Vinci codex machines', 'Thief: The Dark Project Hammerite tech', 'Jesionowski automaton reproductions'],
    inf: ['Renaissance engineering notebooks', 'Habsburg kunstkammer automata', 'woodcut technical illustration'], rel: ['Steampunk', 'Silkpunk', 'Cabinet of Curiosities'],
    src: [{ n: 'Wikipedia — Cyberpunk derivatives', u: 'https://en.wikipedia.org/wiki/Cyberpunk_derivatives', t: 'B' }, { n: 'The Clockpunk genre archive', u: 'https://clockpunk.net', t: 'C' }],
    tg: ['clockpunk', 'renaissance', 'gears', 'automaton', 'da vinci', 'retrofuture'],
    pop: 33, niche: true,
    vd: { shape: 'gear-circle composition and flying-machine wings', line: 'woodcut hatch and inked contours', composition: 'notebook-diagram staging', texture: 'brass, walnut, parchment' },
    typ: { display: 'humanist italic notebooks', body: 'mirror-script annotations', notes: 'diagrams labeled in latin' },
    lit: { quality: 'workshop window shafts', temperature: 'warm-toned', shadow: 'gear spokes cast sundial shade' },
    ui: { background: 'parchment tan', surface: 'gear-rim cards', components: 'spring-coil toggles', motion: 'escapement tick rhythm' },
    par: 'retrofuturist family',
  },
  {
    n: 'Silkpunk', a: ['silk punk', 'ken liu silkpunk', 'bamboo-silk tech', 'dandelion dynasty aesthetic'],
    cat: 'Technology & Retrofuturism', c: 'East Asian fiber-and-bamboo retrofuture', e: 'experimental_hybrid',
    o: 'Ken Liu\'s Dandelion Dynasty (2015-)', g: 'global SF literature & illustration',
    p: '2015-present', era: 'coined in Dandelion Dynasty to genre adoption',
    sum: 'Airships of silk and bamboo, kites as engines — an East Asian grammar of the machine.',
    desc: 'Silkpunk is Ken Liu\'s term (The Grace of Kings, 2015) for a retrofuture built from East Asian materials and logic: bamboo, silk, paper and rope instead of iron and steam — airships that are octopus-kites, spring-driven carts, silk-string telegraphs, diving gears of lacquered hide. Where steampunk asks "what if steam won?", silkpunk asks "what if engineering followed silk and bamboo?" — yielding machines that bend, breathe and flutter. The aesthetic values tensile structure over rigidity, and its illustration tradition (Dandelion Dynasty covers, fan art) favors brushwork gradients and seagoing color. It has become a touchstone for non-Western futurism in fiction.',
    col: [{ h: '#c98a3d', n: 'bamboo tan' }, { h: '#e9e2d0', n: 'silk ivory' }, { h: '#8c1f1f', n: 'lacquer red' }, { h: '#1d3557', n: 'sea-ink blue' }],
    m: ['bamboo frames', 'woven silk membranes', 'paper and rope composites', 'lacquered hide'],
    tx: ['silk membrane sheen', 'bamboo node rhythm', 'brush-paint texture'],
    obj: ['kite-airship flotillas', 'silk-cord telegraphs', 'spring-driven carts', 'crane-wing diving suits'],
    ex: ['The Dandelion Dynasty airship battles', 'silkpunk concept illustration (covers)', 'fan-built bamboo kite models'],
    inf: ['Warring States engineering', 'kite and paper-craft traditions', 'East Asian naval architecture'], rel: ['Clockpunk', 'Steampunk', 'Koinobori Carp Streamers'],
    src: [{ n: 'Wikipedia — Silkpunk', u: 'https://en.wikipedia.org/wiki/Silkpunk', t: 'B' }, { n: 'Ken Liu — The Grace of Kings (author site)', u: 'https://kenliu.name', t: 'C' }],
    tg: ['silkpunk', 'bamboo', 'silk', 'east asian', 'retrofuture', 'fantasy'],
    pop: 28, niche: true,
    vd: { shape: 'tensile frames and membrane wings', line: 'brushwork flow lines', composition: 'literary-map and battle-diagram staging', texture: 'silk sheen, bamboo grain, lacquer' },
    typ: { display: 'brushed display hanzi/kana', body: 'classical annotation columns', notes: 'machines named like poetry' },
    lit: { quality: 'misty-sea morning', temperature: 'warm-toned', shadow: 'membrane light-through glow' },
    ui: { background: 'silk ivory', surface: 'bamboo-frame cards', components: 'knot-tie toggles', motion: 'membrane flutter in wind' },
    par: 'retrofuturist family',
  },
  {
    n: 'Used Future', a: ['used future', 'lived-in scifi', 'greasy spaceship', 'Star Wars grit'],
    cat: 'Technology & Retrofuturism', c: 'lived-in science fiction look', e: 'community_subculture',
    o: 'Star Wars production design (1977) & UK comics', g: 'global SF film and game design',
    p: '1977-present', era: 'post-2001: A Space Odyssey grit revolution',
    sum: 'Spaceships with mud on the tires: dents, grease, and cobbled panels.',
    desc: '"Used future" names the science-fiction look in which spaceships are work vehicles, not miracles: the Millennium Falcon\'s worn hull, Alien\'s Nostromo break-room, blade-runner drizzle — surfaces dented, duct-taped and grease-streaked, sets dressed like long-serving machinery. The look crystallized as a rebuke to gleaming-thryptic futures (2001, Star Trek bridge gloss): modelmakers (Industrial Light & Magic), production designers (Roger Christian\'s "used universe" brief for Star Wars) and art directors built grime into hero props. Games (Outer Wilds, Hardspace: Shipbreaker) and shows (The Expanse, Andor) inherit it: the future as blue-collar workplace.',
    col: [{ h: '#7a6a4f', n: 'hull khaki' }, { h: '#3a3a3a', n: 'engine soot' }, { h: '#b0b7bd', n: 'bare metal scrape' }, { h: '#8c1f1f', n: 'warning stripe red' }, { h: '#e8c14a', n: 'caution gold' }],
    m: ['weathered kit-bashed models', 'greeble panel detailing', 'oil-wash paint finishes', 'cobbled set dressing'],
    tx: ['oil-streak grime', 'panel seam rust', 'scrape-and-dent relief'],
    obj: ['patched hull plating', 'greasy engine bays', 'warning-label decals', 'break-room set corners'],
    ex: ['Millennium Falcon cockpit wear', 'Nostromo (Alien) interior dressing', 'The Expanse bootstrap-fleet interiors'],
    inf: ['trucker and merchant-navy film', 'model kit bashing culture', 'WWII movie production grit'], rel: ['Dieselpunk', 'Retrofuturism', 'Syd Mead Visionary Rendering'],
    src: [{ n: 'Wikipedia — Used future', u: 'https://en.wikipedia.org/wiki/Used_future', t: 'B' }, { n: 'IFC — "used universe" Star Wars interviews', u: 'https://www.ifc.com', t: 'C' }],
    tg: ['usedfuture', 'scifi', 'grit', 'star wars', 'production design', 'greeble'],
    pop: 49, niche: false,
    vd: { shape: 'panel-grid surfaces with asymmetric wear', line: 'greeble seam networks', composition: 'cockpit-workplace framing', texture: 'grease, dust, scrape metal' },
    typ: { display: 'stenciled hull registry numbers', body: 'worn safety-label plates', notes: 'every surface has a service record' },
    lit: { quality: 'work-lamp practicals', temperature: 'cool-toned', shadow: 'greeble shadows texture every plane' },
    ui: { background: 'soot charcoal', surface: 'panel-scrape cards', components: 'worn-sticker toggles', motion: 'dashboard-toggle clicks' },
    par: 'science fiction design',
  },
  {
    n: 'Syd Mead Visionary Rendering', a: ['Syd Mead style', 'visual futurism', 'Mead concept art', 'sentinel rendering'],
    cat: 'Technology & Retrofuturism', c: 'slick corporate future concept art', e: 'community_subculture',
    o: 'Syd Mead (US industrial designer, 1933-2019)', g: 'Hollywood, automotive industry, global concept art',
    p: '1960s-present', era: 'Ford/Philco design to Blade Runner and beyond',
    sum: 'Glossy, plausible tomorrows — the concept-art language behind Blade Runner\'s spinners.',
    desc: 'Syd Mead — "visual futurist", his own coinage — defined the slick end of retrofuture: airbrushed renderings of plausible machinery, from US Steel and Philips product futures to Blade Runner\'s spinner cars, Tron light-cycle roots, Aliens\' Sulaco, and Japan\'s Sony/Sharp concept commissions. Mead\'s grammar: strong single-light staging, believable wear on optimistic surfaces, people dwarfed by elegant hardware, and a rendering polish that made the impossible look like next year\'s brochure. Concept-art education still teaches from his books (Oblagon, Sentury), and "Mead-style" remains shorthand for corporate-future glamour with grit.',
    col: [{ h: '#2979ff', n: 'night-city cobalt' }, { h: '#e8963a', n: 'sodium amber' }, { h: '#b0b7bd', n: 'hull highlight silver' }, { h: '#141414', n: 'render shadow black' }, { h: '#c93663', n: 'neon accent magenta' }],
    m: ['airbrush and gouache', 'marker rendering', 'digital paint (late career)', 'automotive model references'],
    tx: ['airbrush gradient sheen', 'hard specular highlights', 'worn-metal believability'],
    obj: ['spinner vehicles', 'megastructure cutaways', 'product-future concepts', 'vehicle-chase storyboard frames'],
    ex: ['Blade Runner (1982) spinner & street concepts', 'US Steel "Steel Horizons" campaigns', 'Sentury and Oblagon art books'],
    inf: ['automotive design rendering', 'industrial-design consultancy culture', 'noir cinematography'], rel: ['Used Future', 'Retrofuturism', 'Cyberpunk'],
    src: [{ n: 'Wikipedia — Syd Mead', u: 'https://en.wikipedia.org/wiki/Syd_Mead', t: 'B' }, { n: 'Syd Mead Inc — official archive', u: 'https://sydmead.com', t: 'A' }],
    tg: ['sydmead', 'concept art', 'bladerunner', 'rendering', 'scifi', 'airbrush'],
    pop: 47, niche: false,
    vd: { shape: 'hero-hardware silhouettes with human scale cues', line: 'airbrush edge-light contours', composition: 'one-light cinematic staging', texture: 'gloss metal, believable wear' },
    typ: { display: 'clean automotive badge lettering', body: 'spec-annotation hand notes', notes: 'renders sell, annotations prove' },
    lit: { quality: 'single strong key with neon fill', temperature: 'cool-toned', shadow: 'deep render shadows with rim light' },
    ui: { background: 'cobalt dusk', surface: 'spec-gloss cards', components: 'annotation-line accents', motion: 'concept-turntable rotation' },
    par: 'science fiction design',
  },
  {
    n: 'Geodesic Dome Futurism', a: ['geodesic dome', 'bucky fuller dome', 'drop City dome', 'dome home futurism'],
    cat: 'Architectural Style', c: 'Buckminster Fuller-inspired dome architecture', e: 'historical',
    o: 'Black Mountain College & Fuller studios (1948-)', g: 'US counterculture, global expo architecture',
    p: '1948-1970s (revival present)', era: 'Fuller lectures to counterculture dome communes',
    sum: 'Triangles everywhere: shelter as solved geometry, the counterculture\'s favorite building.',
    desc: 'Buckminster Fuller\'s geodesic dome — a sphere built of triangulated struts, stronger and lighter as it grows — became the most influential architectural idea of postwar futurism: the 1954 Fuller dome at Milan Triennale, radar domes, Expo 67\'s US Pavilion, and counterculture builders like Drop City (Colorado, 1965) who zome-built domes from car tops and scrap. Fuller\'s rhetoric ("spaceship earth", synergetic geometry) made the dome an icon of rational optimism; off-grid builders, burning-man camps, and the Eden Project keep the geometry alive. The aesthetic: pure triangulated structure, visible engineering, futures drawn in great circles.',
    col: [{ h: '#b0b7bd', n: 'aluminum strut' }, { h: '#2979ff', n: 'panel acrylic blue' }, { h: '#f2efe4', n: 'membrane white' }, { h: '#2f7d4f', n: 'meadow green base' }],
    m: ['aluminum and steel struts', 'acrylic & fiberglass panels', 'membrane fabric covers', 'connector hub hardware'],
    tx: ['triangulated strut rhythm', 'panel seam glint', 'membrane daylight glow'],
    obj: ['expo pavilion domes', 'commune zome builds', 'radar & greenhouse domes', 'emergency shelter domes'],
    ex: ['Expo 67 US Pavilion (Montreal)', 'Drop City commune (1965-)', 'Eden Project biomes (2001)'],
    inf: ['Fuller synergetic geometry', 'counterculture communes', 'exposition architecture spectacle'], rel: ['Retrofuturism', 'Atompunk', 'Space Age Design'],
    src: [{ n: 'Wikipedia — Geodesic dome', u: 'https://en.wikipedia.org/wiki/Geodesic_dome', t: 'B' }, { n: 'Buckminster Fuller Institute', u: 'https://www.bfi.org', t: 'A' }],
    tg: ['geodesic', 'dome', 'fuller', 'commune', 'architecture', 'futurism'],
    pop: 41, niche: false,
    vd: { shape: 'triangulated sphere segments', line: 'great-circle strut paths', composition: 'geometry as total form', texture: 'strut metal, panel transparency' },
    typ: { display: 'diagrammatic strut labels', body: 'fullerian caption optimism', notes: 'blueprints are the poetry' },
    lit: { quality: 'interior glow through membrane', temperature: 'cool-toned', shadow: 'triangulated shade lattice' },
    ui: { background: 'panel white', surface: 'strut-grid cards', components: 'triangle-tile buttons', motion: 'dome-assembly tessellation' },
    par: 'futurist architecture',
  },
  {
    n: 'Futurama 1939 World\'s Fair', a: ['futurama', '1939 world\'s fair', 'world of tomorrow', 'GM futurama ride'],
    cat: 'Technology & Retrofuturism', c: 'Norman Bel Geddes\' 1939 fair futurama', e: 'historical',
    o: 'New York World\'s Fair, Flushing Meadows (1939)', g: 'US design culture',
    p: '1939-1940', era: 'depression-era optimism exhibit',
    sum: 'A ride through 1960 — highways, suburbs and the future as theme park.',
    desc: 'General Motors\' Futurama exhibit at the 1939 New York World\'s Fair — designed by Norman Bel Geddes — carried 26 million visitors on moving chairs over the world\'s largest animated model: a 35,000-square-foot miniature America of 1960, all fourteen-lane highways, cloverleaf interchanges and planned suburbs under unified light. It was propaganda for highway-building that largely came true, and it set the template for futurism-as-attraction: tomorrow as an amusement ride with scripted light and sound. Its sibling exhibits (Trylon & Perisphere, Democracity) fixed the fair\'s visual language — white geometry, upward arrows, unified night illumination — in American imagination.',
    col: [{ h: '#f2efe4', n: 'fair-plaster white' }, { h: '#2979ff', n: 'floodlight blue' }, { h: '#b0b7bd', n: 'highway model grey' }, { h: '#2f7d4f', n: 'model landscape green' }, { h: '#e8c14a', n: 'trylon spotlit gold' }],
    m: ['scale model landscapes', 'moving-chair ride systems', 'floodlight rigging', 'plaster and balsam miniatures'],
    tx: ['miniature model sheen', 'floodlit even glow', 'riding-rail metal hand'],
    obj: ['Trylon & Perisphere icons', 'Futurama ride chairs', 'cloverleaf model interchanges', 'democracity murals'],
    ex: ['GM Futurama ride (1939)', 'Democracity center show', 'World of Tomorrow Tomorrowland echoes'],
    inf: ['norman bel geddes stagecraft', 'US highway advocacy', 'depression-era consumer optimism'], rel: ['Retrofuturism', 'Atompunk', 'Geodesic Dome Futurism'],
    src: [{ n: "Wikipedia — Futurama (New York World's Fair)", u: 'https://en.wikipedia.org/wiki/Futurama_(New_York_World%27s_Fair)', t: 'B' }, { n: 'NYPL World\'s Fair archives', u: 'https://www.nypl.org', t: 'A' }],
    tg: ['worldsfair', 'futurama', '1939', 'highways', 'model', 'optimism'],
    pop: 35, niche: true,
    vd: { shape: 'aerial model-landscape grids', line: 'highway arrow flow-lines', composition: 'ride-the-future sightline', texture: 'plaster white, even floodlight' },
    typ: { display: 'fair masthead geometric caps', body: 'guidebook promise copy', notes: 'future with a ticket stub' },
    lit: { quality: 'even floodlit night', temperature: 'cool-toned', shadow: 'model buildings cast toy shadows' },
    ui: { background: 'fair white', surface: 'blueprint-line cards', components: 'arrow-flow dividers', motion: 'ride-chair glide scroll' },
    par: 'retrofuturist family',
  },
]