/**
 * Graphic Design wave — 12 real, documented graphic design movements & identities.
 * All names are real; sources are stable Wikipedia article URLs or institutional sites (moma.org etc.).
 */
export const ENTRIES: any[] = [
  {
    n: 'Psychedelic Poster Art', a: ['San Francisco psychedelic posters', 'Psychedelic music poster style'],
    cat: 'Graphic Design', c: '1960s counterculture concert-poster style', e: 'historical',
    o: 'San Francisco and Los Angeles, USA', g: 'United States, United Kingdom', p: '1965-1972', era: 'Late 1960s counterculture',
    sum: 'San Francisco concert-poster style of 1966-67: vibrating complementary colors, liquid Art Nouveau lettering and Op-Art distortion, deliberately pushing legibility to the edge.',
    desc: 'Psychedelic poster art flowered in San Francisco ballrooms — the Fillmore Auditorium and Avalon Ballroom — where promoters commissioned young artists to announce dances by the Grateful Dead, Jefferson Airplane and Big Brother. Wes Wilson, Victor Moscoso, Rick Griffin, Alton Kelley and Stanley Mouse fused Art Nouveau curves, Victorian lettering and Op-Art color vibration into posters meant to be experienced rather than merely read: melting letterforms, complementary reds against greens that flicker, and imagery drawn from mash-up collage. Moscoso\'s Neon Rose series and the Family Dog/Bill Graham numbered series (BG and FD) became the movement\'s core documents, printed in offset and silkscreen, collected as art from the start. MoMA and major museums now hold these posters as a defining chapter of 1960s graphic design.',
    col: [{ h: '#e6332a', n: 'electric vermilion' }, { h: '#7a2fa0', n: 'acid violet' }, { h: '#17a398', n: 'vibrating teal' }, { h: '#f2a41f', n: 'psych orange' }, { h: '#f2e9d8', n: 'cream paper' }],
    m: ['offset lithography', 'silkscreen inks', 'photographic plates for collage'],
    tx: ['flat opaque ink', 'vibrating color edge', 'melted letterform swell'],
    obj: ['Fillmore and Avalon concert posters', 'handbills and postcards', 'album covers', 'underground press advertisements', 'light-show flyers'],
    ex: ['Wes Wilson\'s Fillmore posters (1966-67)', 'Victor Moscoso\'s Neon Rose series', 'Rick Griffin\'s "Flying Eyeball" (BG-68, 1967)'],
    inf: ['Art Nouveau (Mucha line)', 'Op Art', 'Victorian display typography', 'Zap? comic collage'],
    rel: ['Psychedelic art', 'Art Nouveau', 'International Typographic Style'],
    src: [{ n: 'Wikipedia — Psychedelic art', u: 'https://en.wikipedia.org/wiki/Psychedelic_art', t: 'B' }, { n: 'Wikipedia — Wes Wilson', u: 'https://en.wikipedia.org/wiki/Wes_Wilson', t: 'B' }, { n: 'The Museum of Modern Art — collection', u: 'https://www.moma.org', t: 'A' }],
    tg: ['psychedelic', 'concert poster', 'fillmore', 'op art', 'counterculture', 'san francisco', 'nouveaurevival'],
    pop: 62, niche: false,
    vd: { shape: 'melting organic blobs and undulating contours', line: 'warped, fluid outlines swallowing letterforms', composition: 'layered central lettering, vibrating borders', texture: 'flat offset ink with near-fluorescent glow' },
    typ: { display: 'Cooper Black; hand-drawn liquid lettering (Wes Wilson, Moscoso)', body: 'Helvetica', notes: 'Victorian faces like French Clarendon quoted in 60s revivals' },
    lit: { quality: 'hot frontal glow', temperature: 'warm', shadow: 'flat, minimal — poster flatness' },
    ui: { background: 'deep violet wash', surface: 'iridescent gradient cards', components: 'wavy pill buttons and melt-edge dividers', motion: 'liquid ripple morphs' },
  },
  {
    n: 'Wiener Werkstätte Design', a: ['Vienna Workshops', 'Wiener Werkstätte style'],
    cat: 'Graphic Design', c: 'Viennese applied-arts workshop design program', e: 'historical',
    o: 'Vienna, Austria-Hungary', g: 'Austria-Hungary, Germany, Switzerland; brief New York branch (1922)', p: '1903-1932', era: 'Vienna Secession / fin-de-siècle to interwar',
    sum: 'Vienna\'s Hoffmann-Moser workshop fused Secession geometry with craftsman luxury: black-white-gold graphics, square grids, monograms and total designed environments.',
    desc: 'Founded in Vienna in 1903 by architects Josef Hoffmann and Koloman Moser with banker Fritz Waerndorfer, the Wiener Werkstätte ("Vienna Workshops") applied Arts and Crafts ideals to urban luxury: fashion, metalwork, textiles, furniture, postcards and above all graphic design. Its graphic identity favored geometric simplification — squares, checks, refined monograms — often restricted to black, white and gold, echoing the Secession Building\'s starkness. The Werkstätte produced exhibition catalogs, posters, ex libris, fashion plates and a landmark postcard series, with designers including Egon Schiele and Oskar Kokoschka contributing. Costly to run, it declined through the Depression and closed in 1932; Vienna\'s MAK museum holds its archive, and its square-grid graphics anticipate later modernist design.',
    col: [{ h: '#1a1712', n: 'secession black' }, { h: '#f2ecdc', n: 'ivory white' }, { h: '#c19a3d', n: 'workshop gold' }, { h: '#7d8a6a', n: 'muted willow green' }, { h: '#b04a3a', n: 'coral accent' }],
    m: ['fine paper and card stock', 'silver, brass and enamel metalwork', 'Backhausen woven silks'],
    tx: ['crisp geometric emboss', 'flat opaque ink', 'hammered metal sheen'],
    obj: ['exhibition posters and catalogs', 'monograms and logotypes', 'square-pattern textiles', 'postcard series', 'Hoffmann silver cutlery'],
    ex: ['Koloman Moser\'s Ver Sacrum-era designs', 'WW postcard series (1907-1920s)', 'Hoffmann\'s Fledermaus cabaret design (1907)'],
    inf: ['Vienna Secession', 'Arts and Crafts movement', 'Charles Rennie Mackintosh', 'Scottish Glasgow Style'],
    rel: ['Wiener Werkstätte', 'Art Nouveau', 'Bauhaus'],
    src: [{ n: 'Wikipedia — Wiener Werkstätte', u: 'https://en.wikipedia.org/wiki/Wiener_Werkst%C3%A4tte', t: 'B' }, { n: 'MAK — Museum für angewandte Kunst, Vienna', u: 'https://www.mak.at', t: 'A' }, { n: 'The Museum of Modern Art — collection', u: 'https://www.moma.org', t: 'A' }],
    tg: ['secession', 'geometric', 'vienna', 'workshop', 'monogram', 'total design', 'gold'],
    pop: 55, niche: true,
    vd: { shape: 'squares, checks and stark geometric emblems', line: 'fine black contour on white ground', composition: 'centered monogram architecture, airy margins', texture: 'flat ink with gilt and embossed accents' },
    typ: { display: 'Eckmann (Klingspor, 1900) and WW hand-drawn square lettering', body: 'Akzidenz-Grotesk', notes: 'monogram systems drawn by Moser and Hoffmann' },
    lit: { quality: 'even gallery light', temperature: 'neutral', shadow: 'minimal — graphic flatness' },
    ui: { background: 'ivory paper field', surface: 'black-line geometric cards', components: 'gold-outlined square buttons', motion: 'precise, stately crossfades' },
  },
  {
    n: 'Blue Note Record Covers', a: ['Blue Note album design', 'Reid Miles Blue Note covers'],
    cat: 'Graphic Design', c: 'Jazz record-label cover design program', e: 'commercial_style',
    o: 'New York City, USA', g: 'United States, international jazz market', p: '1939-present; iconic covers 1956-1967', era: 'Hard bop era, 1950s-60s America',
    sum: 'Reid Miles\' 1950s-60s Blue Note sleeves: duotone jazz photography cropped and tinted, off-kilter grotesque type and audacious color fields — hard bop\'s graphic signature.',
    desc: 'Blue Note, founded in 1939 by Alfred Lion and Francis Wolff, defined its look after hiring designer Reid Miles in 1956. Over roughly a decade Miles designed hundreds of 12-inch sleeves, usually building on Wolff\'s candid hard-bop session photographs: blowing them up into grainy duotones, tinting them cobalt, orange or yellow-green, cropping faces out entirely, and stacking slab-grotesque letterforms at angles across the frame — sometimes discarding the photo for pure typographic fields. Miles worked fast for low fees, borrowing from Swiss typography and contemporary advertising; his covers for Sonny Rollins, Art Blakey, Lee Morgan and Eric Dolphy ("Out to Lunch!") are among the most imitated record designs ever made. The blue-and-white label and pear-shaped logo completed an identity still used by the label today.',
    col: [{ h: '#111418', n: 'record black' }, { h: '#e8e4da', n: 'photo cream' }, { h: '#1d4e8f', n: 'blue note cobalt' }, { h: '#e0a520', n: 'mustard duotone' }, { h: '#4a9b8e', n: 'session teal' }],
    m: ['duotone photographic plates', 'offset lithography', 'LP cardboard sleeves'],
    tx: ['coarse halftone grain', 'flat color panel', 'crisp type knockouts'],
    obj: ['12-inch LP covers', 'label designs', 'inner sleeves', 'catalog and promo posters'],
    ex: ['Sonny Rollins "Vol. 2" (1957)', 'Art Blakey "Moanin\'" (1958)', 'Eric Dolphy "Out to Lunch!" (1964)'],
    inf: ['Swiss typography', 'Bauhaus composition', '1950s American advertising design'],
    rel: ['International Typographic Style', 'Swiss Style', 'Swiss International Style'],
    src: [{ n: 'Wikipedia — Blue Note Records', u: 'https://en.wikipedia.org/wiki/Blue_Note_Records', t: 'B' }, { n: 'Wikipedia — Reid Miles', u: 'https://en.wikipedia.org/wiki/Reid_Miles', t: 'B' }, { n: 'The Museum of Modern Art — collection', u: 'https://www.moma.org', t: 'A' }],
    tg: ['jazz', 'album cover', 'hard bop', 'duotone', 'typography', 'record sleeve', 'blue note'],
    pop: 66, niche: false,
    vd: { shape: 'full-bleed photo fields with cropped focal fragments', line: 'bold slab grotesque strokes at dynamic angles', composition: 'asymmetric type blocks anchoring photography', texture: 'grainy duotone over flat ink panels' },
    typ: { display: 'Alternate Gothic No. 2 and hand-set grotesques', body: 'Akzidenz-Grotesk', notes: 'type cropped, outlined, stacked and rotated by Reid Miles' },
    lit: { quality: 'hard side light on portrait photography', temperature: 'warm-neutral', shadow: 'deep stage shadows in the photos' },
    ui: { background: 'duotone photo wash', surface: 'flat color record cards', components: 'knockout grotesque buttons', motion: 'snappy jazz-cut transitions' },
  },
  {
    n: 'Penguin Paperback Covers', a: ['Penguin cover design', 'Penguin Books covers'],
    cat: 'Graphic Design', c: 'British paperback cover and series design tradition', e: 'commercial_style',
    o: 'Harmondsworth, Middlesex, England', g: 'United Kingdom, Commonwealth, export markets', p: '1935-present; classic covers 1935-1960s', era: 'Interwar Britain to postwar',
    sum: 'Allen Lane\'s 1935 Penguin grid — cream bands, Gill Sans lettering, color-coded series and the dancing penguin — that made the cheap paperback trustworthy.',
    desc: 'When Allen Lane launched Penguin Books in July 1935, Edward Young\'s cover design did as much as the sixpence price to revolutionize publishing: a clean horizontal grid of cream and color bands, title and author set in Eric Gill\'s Gill Sans, and Young\'s penguin colophon. Series were color-coded — orange for fiction, green for crime, blue for biography — turning bookshelves into branding systems. Jan Tschichold, arriving in 1947, imposed his "Penguin Composition Rules," harmonizing typography across hundreds of titles; in 1961 Romek Marber\'s grid restructured the crime and fiction covers around a small image panel. Restraint, legibility and system made Penguins an icon of democratic design, endlessly exhibited and collected.',
    col: [{ h: '#e8e2d0', n: 'penguin cream' }, { h: '#191614', n: 'ink black' }, { h: '#e07b2f', n: 'fiction orange' }, { h: '#2c6e63', n: 'crime green' }, { h: '#3d6b9e', n: 'biography blue' }],
    m: ['offset lithography', 'cream board covers', 'composition-line rule work'],
    tx: ['flat cream paper', 'clean banded edges', 'small duotone plate (Marber era)'],
    obj: ['Penguin fiction paperbacks', 'Penguin Crime covers', 'Pelican non-fiction', 'Penguin Classics', 'Penguin Shakespeare'],
    ex: ['Edward Young\'s original 1935 grid', 'Tschichold\'s Penguin Composition Rules (1947)', 'Romek Marber grid crime covers (1961)'],
    inf: ['Bauhaus functionalism', 'Tschichold\'s New Typography', 'Eric Gill\'s lettering reforms'],
    rel: ['Swiss International Style', 'International Typographic Style'],
    src: [{ n: 'Wikipedia — Penguin Books', u: 'https://en.wikipedia.org/wiki/Penguin_Books', t: 'B' }, { n: 'Wikipedia — Jan Tschichold', u: 'https://en.wikipedia.org/wiki/Jan_Tschichold', t: 'B' }, { n: 'Penguin Books UK', u: 'https://www.penguin.co.uk', t: 'A' }],
    tg: ['paperback', 'grid', 'gill sans', 'series design', 'publishing', 'british'],
    pop: 64, niche: false,
    vd: { shape: 'stacked horizontal bands, small framed image panel', line: 'ruled grid lines, roman caps', composition: 'strict modular grid, generous white cream fields', texture: 'flat matte paper' },
    typ: { display: 'Gill Sans (logotype and cover bands)', body: 'Times New Roman (post-1948 Penguin text)', notes: 'Marber grid fixed title, author and image positions' },
    lit: { quality: 'even, shadowless daylight', temperature: 'neutral', shadow: 'none — editorial flatness' },
    ui: { background: 'cream field with color band header', surface: 'grid-aligned book cards', components: 'band-topped list rows and small buttons', motion: 'tidy page-turn slides' },
  },
  {
    n: 'Mexico 68 Olympic Identity', a: ['Mexico 68', 'Lance Wyman Mexico 68 design'],
    cat: 'Graphic Design', c: 'Olympic Games visual identity and wayfinding system', e: 'historical',
    o: 'Mexico City, Mexico', g: 'Mexico, international print and broadcast', p: '1966-1968', era: 'Late 1960s Op-Art era',
    sum: 'Lance Wyman and Pedro Ramírez Vázquez\'s 1968 Olympic identity: radiating Op-Art stripes that turned the logotype, pictograms and city wayfinding into one vibrating system.',
    desc: 'For the 1968 Mexico City Games, architect Pedro Ramírez Vázquez directed a design program in which 29-year-old American Lance Wyman created the identity: the numerals 6-8 and MEXICO lettering built from parallel lines that radiate outward like Op-Art interference, inspired by pre-Hispanic huipil textile patterns and the era\'s kinetic art. Wyman and British designer Peter Murdoch drew a complete custom alphabet, pictogram sets for sports and services, and a city-scale wayfinding scheme — painted stripes on sidewalks, venue signage, stamp and sticker campaigns — so the whole capital read as one graphic field. Widely copied since, the system entered MoMA\'s collection and made Wyman\'s career; it remains a benchmark of environment-scale identity design.',
    col: [{ h: '#231f20', n: 'type black' }, { h: '#f4f1e6', n: 'paper white' }, { h: '#e83f8e', n: 'magenta pink' }, { h: '#f2c320', n: 'sun yellow' }, { h: '#2e9e6b', n: 'volcano green' }],
    m: ['silkscreen posters', 'offset printing', 'enamel and painted signage', 'pressure-sensitive stickers'],
    tx: ['flat opaque color', 'parallel-stripe vibration', 'crisp vector edge'],
    obj: ['Olympic logotype and posters', 'sports and service pictograms', 'venue wayfinding signage', 'street stripe markings', 'stamp and sticker series'],
    ex: ['Radiating "Mexico 68" logotype', 'venue pictogram boards (1968)', 'city-wide wayfinding stripe campaign'],
    inf: ['Op Art', 'Pre-Columbian huipil patterns', 'Swiss wayfinding design'],
    rel: ['International Typographic Style', 'Psychedelic art', 'Swiss Style'],
    src: [{ n: 'Wikipedia — 1968 Summer Olympics', u: 'https://en.wikipedia.org/wiki/1968_Summer_Olympics', t: 'B' }, { n: 'Wikipedia — Lance Wyman', u: 'https://en.wikipedia.org/wiki/Lance_Wyman', t: 'B' }, { n: 'The Museum of Modern Art — collection', u: 'https://www.moma.org', t: 'A' }],
    tg: ['olympic', 'op art', 'wayfinding', 'pictogram', 'lance wyman', 'mexico 68', 'stripes'],
    pop: 60, niche: false,
    vd: { shape: 'radiating parallel-line numerals and circles', line: 'consistent-width stripes that bend and pulse', composition: 'repeating stripe modules across print and streets', texture: 'flat enamel and ink, high vibration' },
    typ: { display: 'Mexico 68 typeface (Wyman and Peter Murdoch)', body: 'Helvetica', notes: 'numerals dissolve into Op-Art radiating stripes' },
    lit: { quality: 'harsh midday sun', temperature: 'warm', shadow: 'hard, short shadows outdoors' },
    ui: { background: 'white with magenta stripe header', surface: 'stripe-patterned cards', components: 'radiating-circle buttons and pictogram icons', motion: 'rolling stripe reveals' },
  },
  {
    n: 'Munich 1972 Olympic Design', a: ['Munich 72 design system', 'Otl Aicher Munich 1972'],
    cat: 'Graphic Design', c: 'Olympic design program directed by Otl Aicher', e: 'historical',
    o: 'Munich, West Germany', g: 'West Germany, international', p: '1967-1972', era: 'Postwar West German modernism',
    sum: 'Otl Aicher\'s 1972 Munich Olympics: spectral "ray" palette, Univers typography and neutral stick-figure pictograms that redefined institutional design systems.',
    desc: 'Otl Aicher directed the design of the 1972 Munich Olympic Games, the largest design program attempted to that point. Deliberately light and optimistic in response to Germany\'s dark Olympic past, Aicher\'s team built a system on a luminous light-blue ground, a rainbow "ray" spectrum motif, and Univers — set in many weights with disciplined grids — across posters, programs, tickets, credentials and staff wear. His greatest legacy was the pictogram set: geometric stick figures constructed on a modular grid, an evolution of the Tokyo 1964 icons whose logic fed directly into international public-symbol standards. The dachshund mascot Waldi, drafted by Elena Hoppe? (credited to the design team), and the cheerful "Wir wollen mehr" tone completed a program that still anchors textbooks on design systems.',
    col: [{ h: '#8fc4dd', n: 'munich light blue' }, { h: '#f4f2ea', n: 'paper white' }, { h: '#2c5545', n: 'olympic forest green' }, { h: '#e2a13a', n: 'ray gold' }, { h: '#c84b32', n: 'ray vermilion' }],
    m: ['offset lithography', 'phototype composition', 'enamel and painted signage', 'printed nylon banners'],
    tx: ['flat matte ink', 'sharp pictogram stencil edge', 'smooth spectral gradient'],
    obj: ['pictogram signage system', 'sports posters and programs', 'tickets and credentials', 'Waldi mascot merchandise', 'staff uniforms and badges'],
    ex: ['Athletics pictogram set (1972)', 'Rainbow ray poster series', 'Waldi dachshund mascot (1972)'],
    inf: ['Tokyo 1964 pictograms', 'Swiss International Style', 'Bauhaus', 'Ulm School of Design'],
    rel: ['International Typographic Style', 'Swiss International Style', 'Swiss Style', 'Bauhaus'],
    src: [{ n: 'Wikipedia — 1972 Summer Olympics', u: 'https://en.wikipedia.org/wiki/1972_Summer_Olympics', t: 'B' }, { n: 'Wikipedia — Otl Aicher', u: 'https://en.wikipedia.org/wiki/Otl_Aicher', t: 'B' }, { n: 'The Museum of Modern Art — collection', u: 'https://www.moma.org', t: 'A' }],
    tg: ['olympic', 'pictogram', 'univers', 'design system', 'otl aicher', 'munich 1972', 'rays'],
    pop: 61, niche: false,
    vd: { shape: 'modular stick-figure pictograms, radial ray bursts', line: 'uniform-width geometric strokes on grid', composition: 'grid-set typography under generous light-blue field', texture: 'flat, untextured modernist ink' },
    typ: { display: 'Univers (Frutiger) — Aicher\'s Munich 72 face', body: 'Univers 55', notes: 'pictograms built on a modular square grid' },
    lit: { quality: 'bright even daylight', temperature: 'cool-neutral', shadow: 'soft, minimized' },
    ui: { background: 'light blue field', surface: 'grid-ruled white cards', components: 'pictogram icon buttons, ray dividers', motion: 'clean modular slide-ins' },
  },
  {
    n: 'Chinese Propaganda Poster Art', a: ['PRC political posters', 'Mao-era propaganda posters'],
    cat: 'Graphic Design', c: 'State graphic propaganda tradition of the People\'s Republic of China', e: 'historical',
    o: 'People\'s Republic of China', g: 'PRC; circulated in socialist states and the West', p: '1949-1978 (peak 1950s-1970s)', era: 'Mao-era China',
    sum: 'Mass-printed Mao-era posters fusing Soviet socialist realism with Chinese folk palette — red suns, heroic workers and million-copy images of the Chairman.',
    desc: 'After 1949 the People\'s Republic built dedicated publishing houses — including the Shanghai People\'s Fine Arts Publishing House — to turn posters into instruments of mass mobilization, printing campaigns in editions of hundreds of thousands to millions. Early posters merged Soviet socialist realism with the nianhua New Year print tradition and the yuefenpai calendar-poster style; during the Cultural Revolution the visual language hardened into red suns, waves of little red books, model soldiers like Lei Feng, and vigorous worker-peasant-soldier figures under bold heiti slogans. Curated abroad by collectors — most prominently Stefan Landsberger\'s collection, now at the International Institute of Social History — these posters are a major document of twentieth-century political graphic design.',
    col: [{ h: '#d0312d', n: 'socialist red' }, { h: '#f2c320', n: 'golden sun yellow' }, { h: '#f4f0e6', n: 'paper cream' }, { h: '#2f7a4d', n: 'spring green' }, { h: '#23364f', n: 'deep backdrop blue' }],
    m: ['offset lithography', 'nianhua woodblock roots', 'glossy poster paper'],
    tx: ['flat poster ink', 'airbrushed hero glow', 'glossy field sheen'],
    obj: ['Cultural Revolution wall posters', 'Great Leap Forward campaign prints', 'model-worker and Lei Feng portraits', 'Chairman portraits', 'nianhua New Year prints'],
    ex: ['Lei Feng campaign posters', 'Shanghai People\'s Fine Arts Publishing House series', '"Chairman Mao is the red sun" portraits'],
    inf: ['Soviet socialist realism', 'yuefenpai calendar posters', 'nianhua folk prints', 'Lu Xun\'s woodcut movement'],
    rel: ['Chinese Socialist Realism', 'Socialist Modernism', 'Dazibao'],
    src: [{ n: 'Wikipedia — Quotations from Chairman Mao Tse-tung', u: 'https://en.wikipedia.org/wiki/Quotations_from_Chairman_Mao_Tse-tung', t: 'B' }, { n: 'International Institute of Social History — Landsberger poster collection', u: 'https://www.iisg.nl', t: 'A' }, { n: 'The Museum of Modern Art — collection', u: 'https://www.moma.org', t: 'A' }],
    tg: ['propaganda', 'mao era', 'socialist realism', 'cultural revolution', 'nianhua', 'red sun'],
    pop: 55, niche: true,
    vd: { shape: 'heroic rising diagonals, radiant suns and flags', line: 'bold drawing with airbrushed volume', composition: 'central Chairman or model figure, slogan beneath', texture: 'flat glossy litho ink' },
    typ: { display: 'bold heiti (黑体) slogan lettering', body: 'Songti (宋体) text blocks', notes: 'Mao\'s brush calligraphy used as an emblematic signature' },
    lit: { quality: 'radiant frontal glow', temperature: 'warm', shadow: 'minimal — heroic brightness' },
    ui: { background: 'red gradient sunrise', surface: 'glossy poster cards', components: 'gold-banner buttons', motion: 'triumphant slow zooms' },
  },
  {
    n: 'Wood Type & Letterpress Posters', a: ['Wood type posters', 'American show-bill printing'],
    cat: 'Graphic Design', c: 'Nineteenth-century wood-type poster printing', e: 'historical',
    o: 'United States (also Britain and France)', g: 'United States, Europe', p: '1828-1900s; revival ongoing', era: 'Antebellum to Gilded Age America',
    sum: 'Giant end-grain wooden letters — French Clarendon, Tuscan, condensed Gothics — steam-printed in loud colors to shout across nineteenth-century American streets.',
    desc: 'Darius Wells cut the first American wood type in 1828 at Lee, Massachusetts; by 1834 William Leavenworth had married it to the pantograph router, making display type cheap at any size. Because wooden letters were light and strong enough for the new steam-powered cylinder presses, printers could poster whole towns with circus bills, medicine-show broadsides and playbills set entirely from wood. Hamilton Manufacturing of Two Rivers, Wisconsin (founded 1880) grew into the world\'s largest wood-type maker, its specimen books defining the genre\'s faces — French Clarendon with its enormous slab serifs on a condensed body, branched Tuscans, fat and condensed Gothics — printed over ink-and-water color layers. The Hamilton Wood Type & Printing Museum keeps the tradition alive through working collections and revivals.',
    col: [{ h: '#f4ead2', n: 'unbleached poster stock' }, { h: '#c8322b', n: 'circus red' }, { h: '#1d4e8f', n: 'show blue' }, { h: '#e8b62a', n: 'chrome yellow' }, { h: '#171310', n: 'letterpress black' }],
    m: ['end-grain maple and poplar blocks', 'pantograph routers', 'letterpress proof and cylinder presses', 'oil-based display inks'],
    tx: ['slight wood-grain bite', 'ink squash at the edges', 'flat slab shadow layer'],
    obj: ['circus and menagerie posters', 'medicine-show broadsides', 'playbills', 'grocery and tobacco posters', 'railroad broadsides'],
    ex: ['Hamilton Manufacturing Co. specimen books', 'Nineteenth-century circus "steam" posters', 'Hamilton Wood Type & Printing Museum working collection'],
    inf: ['Victorian display typography', 'specimen-book culture', 'circus advertising'],
    rel: ['Letterpress Texture', 'Letterpress Relief', 'Letterpress Bite and Deboss', 'Victorian Color'],
    src: [{ n: 'Wikipedia — Wood type', u: 'https://en.wikipedia.org/wiki/Wood_type', t: 'B' }, { n: 'Wikipedia — Letterpress printing', u: 'https://en.wikipedia.org/wiki/Letterpress_printing', t: 'B' }, { n: 'Hamilton Wood Type & Printing Museum', u: 'https://woodtype.org', t: 'A' }],
    tg: ['wood type', 'letterpress', 'broadside', 'circus poster', 'victorian type', 'two rivers'],
    pop: 52, niche: true,
    vd: { shape: 'enormous condensed letters stacked in tiers', line: 'heavy slab serifs, hand-carved ornaments', composition: 'type fills every inch, color layers behind type', texture: 'ink bite on soft poster paper' },
    typ: { display: 'French Clarendon and Tuscan wood type', body: 'condensed Gothic wood type', notes: 'Hamilton specimen cuts; hand-carved flourishes and stars' },
    lit: { quality: 'bright street daylight', temperature: 'warm', shadow: 'flat layered color, no cast shadow' },
    ui: { background: 'cream stock with color washes', surface: 'slab-serif poster cards', components: 'letterpress-embossed buttons', motion: 'stamp-press thump reveals' },
  },
  {
    n: 'Victorian Advertising Trade Cards', a: ['Victorian trade cards', 'chromolithograph trade cards'],
    cat: 'Graphic Design', c: 'Chromolithographed advertising collectible cards', e: 'historical',
    o: 'United States and Britain', g: 'United States, Britain, France (chromo trade)', p: '1870s-1900', era: 'High Victorian era',
    sum: 'Free chromolithographed giveaway cards — bouquets, comic scenes, specialty borders — the first mass-market brand advertising and a Victorian collecting craze.',
    desc: 'In the 1870s-1890s, businesses gave away small chromolithographed cards that served as both advertisement and token: soap, coffee, sewing machines, patent medicines and department stores issued millions of them, often die-cut, embossed or gilded, with brand names set into ornamental cartouches. Chromolithography\'s layered stones produced bouquets, children, comic mishaps and butterfly-bordered wordmarks that hand-coloring could never have matched at scale; French "chromos" set the fashion and American printers industrialized it. Cards were traded, pasted into scrapbook albums and consciously collected — an early fan economy around advertising. The Smithsonian\'s Warshaw Collection of Business Americana preserves hundreds of thousands, making trade cards a key archive of Victorian consumer design and the birth of brand iconography.',
    col: [{ h: '#e8d9b0', n: 'cream card stock' }, { h: '#b03a3a', n: 'carmine chromo red' }, { h: '#2e6a4f', n: 'bottle green' }, { h: '#c98a2e', n: 'chrome ochre' }, { h: '#3b4d8f', n: 'litho blue' }],
    m: ['chromolithography (layered stones)', 'die-cut card stock', 'gold embossing'],
    tx: ['litho stipple texture', 'gilded emboss', 'flat spot color'],
    obj: ['soap and coffee giveaways (Arbuckle Brothers)', 'patent medicine cards', 'Singer sewing machine cards', 'scrapbook album pages', 'world\'s fair souvenir cards'],
    ex: ['Arbuckle Brothers coffee scene cards', 'Singer sewing machine advertising cards', 'Warshaw Collection of Business Americana (Smithsonian)'],
    inf: ['chromolithography', 'Victorian sentimental illustration', 'French chromo tradition', 'world\'s fair souvenir culture'],
    rel: ['Victorian Color', 'Victorian Polychrome', 'Victorian Style'],
    src: [{ n: 'Wikipedia — Trade card', u: 'https://en.wikipedia.org/wiki/Trade_card', t: 'B' }, { n: 'Smithsonian National Museum of American History', u: 'https://americanhistory.si.edu', t: 'A' }, { n: 'Victoria and Albert Museum', u: 'https://www.vam.ac.uk', t: 'A' }],
    tg: ['trade card', 'chromolithography', 'victorian advertising', 'die cut', 'brand origin', 'scrapbook'],
    pop: 45, niche: true,
    vd: { shape: 'die-cut silhouettes, ornamental cartouches and bouquets', line: 'delicate litho key-line over stipple color', composition: 'image dominant, brand name in flourish border', texture: 'stippled chromo tone, gilded edges' },
    typ: { display: 'Tuscan and French Clarendon ornamented faces', body: 'engraved script and roman jobbing type', notes: 'brand logotypes framed in botanical flourish cartouches' },
    lit: { quality: 'soft parlor light', temperature: 'warm', shadow: 'gentle vignetting, no hard cast' },
    ui: { background: 'cream stock texture', surface: 'die-cut keepsake cards', components: 'flourish-framed buttons', motion: 'scrapbook paste-and-peek reveals' },
  },
  {
    n: 'Push Pin Studio Style', a: ['Push Pin Studios', 'Push Pin Graphic style'],
    cat: 'Graphic Design', c: 'New York illustration-design studio style', e: 'commercial_style',
    o: 'New York City, USA', g: 'United States, international editorial market', p: '1954-1980s', era: 'Postwar American graphic design',
    sum: 'Milton Glaser, Seymour Chwast, Reynolds Ruffins and Edward Sorel\'s studio: eclectic historicist illustration and wry type that loosened Swiss modernism\'s grip on American design.',
    desc: 'Push Pin Studios was founded in New York in 1954 by four Cooper Union graduates; its house organ, The Push Pin Graphic (1957-1980), became an internationally imitated showcase. Rejecting both slick commercial realism and austere modernism, the studio mined Victorian engravings, Art Nouveau, woodcuts and comics, redrawing them with contemporary wit — an "eclectic revivalism" that paralleled Pop Art. Seymour Chwast designed influential display typefaces (Buffalo, Blippo), and Milton Glaser\'s 1966 Bob Dylan poster, with its silhouetted profile and psychedelic hair, became one of the most reproduced images of the century. Push Pin\'s illustration-led design reshaped American editorial graphics, record sleeves and posters for three decades.',
    col: [{ h: '#1a1a1a', n: 'pen-and-ink black' }, { h: '#e8b62a', n: 'push pin yellow' }, { h: '#c8532e', n: 'burnt orange' }, { h: '#4a7ba6', n: 'slate blue' }, { h: '#ece2c8', n: 'aged cream' }],
    m: ['pen-and-ink and gouache illustration', 'photo-mechanical paste-up', 'offset lithography'],
    tx: ['hand-drawn line texture', 'flat spot color', 'woodcut grain'],
    obj: ['Push Pin Graphic issues', 'record and book covers', 'magazine illustration', 'posters', 'advertising campaigns'],
    ex: ['Milton Glaser\'s Bob Dylan poster (1966)', 'Chwast\'s "Dante\'s Inferno" illustrations', 'Push Pin Graphic anti-war poster issue (1968)'],
    inf: ['Art Nouveau revival', 'Victorian illustration', 'American cartooning', 'German Expressionist woodcut'],
    rel: ['Psychedelic art', 'Art Nouveau', 'Victorian Color'],
    src: [{ n: 'Wikipedia — Push Pin Studios', u: 'https://en.wikipedia.org/wiki/Push_Pin_Studios', t: 'B' }, { n: 'Wikipedia — Milton Glaser', u: 'https://en.wikipedia.org/wiki/Milton_Glaser', t: 'B' }, { n: 'The Museum of Modern Art — collection', u: 'https://www.moma.org', t: 'A' }],
    tg: ['illustration', 'eclecticism', 'new york studio', 'chwast', 'milton glaser', 'editorial'],
    pop: 58, niche: false,
    vd: { shape: 'chunky drawn figures and organic poster shapes', line: 'confident ink contour, cartoon-born', composition: 'illustration dominant, type integrated as image', texture: 'hand-inked line over flat color' },
    typ: { display: 'Buffalo and Blippo (Seymour Chwast typefaces)', body: 'Clarendon revivals', notes: 'hand-lettered display often drawn per project' },
    lit: { quality: 'bright studio daylight', temperature: 'warm', shadow: 'graphic, drawn hatch-shadow' },
    ui: { background: 'aged cream with ink-line frames', surface: 'illustrated poster cards', components: 'chunky drawn buttons and badge icons', motion: 'playful spring-loaded pops' },
  },
  {
    n: 'Basel School Posters', a: ['Basel School of Design posters', 'Schule für Gestaltung Basel'],
    cat: 'Graphic Design', c: 'Swiss poster-design pedagogy and style', e: 'historical',
    o: 'Basel, Switzerland', g: 'Switzerland; international influence through alumni and summer courses', p: 'c. 1947-present; golden age 1950s-1970s', era: 'Postwar Swiss modernism',
    sum: 'Armin Hofmann and Emil Ruder\'s Basel poster school: objective photography, Akzidenz-Grotesk discipline and asymmetrical grids that codified Swiss typography.',
    desc: 'At Basel\'s Allgemeine Gewerbeschule (later Schule für Gestaltung), Emil Ruder\'s typography course and Armin Hofmann\'s poster class built the most systematic typographic pedagogy of the twentieth century. Ruder\'s "Typographie" (1967) and Hofmann\'s "Graphic Design Manual" (1965) codified the approach: Akzidenz-Grotesk set on rigorous grids, extreme scale contrast, objective photography, and a black-white-red restraint in which the poster\'s message became an exercise in order. Hofmann\'s own theater posters — the 1959 Giselle among them — are landmarks of the Swiss poster tradition, reducing imagery to typographic gesture. Through international summer courses and generations of alumni, the Basel School carried Swiss typography from regional poster walls into the world\'s design curricula.',
    col: [{ h: '#d8452c', n: 'basel poster red' }, { h: '#14120f', n: 'near-black type' }, { h: '#f2efe6', n: 'paper white' }, { h: '#3f5d7a', n: 'litho blue' }, { h: '#c8c2b4', n: 'neutral gray' }],
    m: ['letterpress and phototype setting', 'silkscreen posters', 'halftone photography', 'offset lithography'],
    tx: ['flat ink coverage', 'fine halftone grain', 'hard grid edge'],
    obj: ['theater and exhibition posters', 'typographic specimen studies', 'cultural event placards', 'student grid exercises'],
    ex: ['Armin Hofmann\'s Giselle poster (1959)', 'Emil Ruder\'s book "Typographie" (1967)', 'Hofmann\'s "Graphic Design Manual" (1965)'],
    inf: ['Swiss International Style', 'Tschichold\'s New Typography', 'Bauhaus'],
    rel: ['Swiss International Style', 'International Typographic Style', 'Swiss Style'],
    src: [{ n: 'Wikipedia — Armin Hofmann', u: 'https://en.wikipedia.org/wiki/Armin_Hofmann', t: 'B' }, { n: 'Wikipedia — Emil Ruder', u: 'https://en.wikipedia.org/wiki/Emil_Ruder', t: 'B' }, { n: 'Schule für Gestaltung Basel', u: 'https://sfgbasel.ch', t: 'A' }],
    tg: ['swiss typography', 'grid', 'akzidenz', 'poster school', 'ruder', 'hofmann', 'basel'],
    pop: 57, niche: true,
    vd: { shape: 'rectangular fields and cropped photographic planes', line: 'grotesque letterforms as pure structure', composition: 'asymmetric grid, extreme scale contrast', texture: 'flat ink, unbleached paper' },
    typ: { display: 'Akzidenz-Grotesk (Ruder and Hofmann\'s workhorse)', body: 'Akzidenz-Grotesk 55', notes: 'phototype scaling; type IS the image' },
    lit: { quality: 'neutral north light', temperature: 'cool-neutral', shadow: 'none — objective flatness' },
    ui: { background: 'paper white', surface: 'grid-locked typographic cards', components: 'grotesque buttons, hairline dividers', motion: 'exact, measured fades' },
  },
  {
    n: 'May 68 Paris Poster Art', a: ['Atelier Populaire posters', 'Paris May 1968 posters'],
    cat: 'Graphic Design', c: 'Occupied-art-school silkscreen poster movement', e: 'historical',
    o: 'Paris, France', g: 'France; international circulation', p: 'May-June 1968', era: 'France, May 1968',
    sum: 'Posters screen-printed overnight by the Atelier Populaire in the occupied École des Beaux-Arts — stenciled slogans that papered Paris during the May 68 uprising.',
    desc: 'When the French student revolt widened into a general strike in May 1968, students and artists occupied the École des Beaux-Arts and founded the Atelier Populaire (popular workshop) around 14-16 May. Working anonymously under the slogan "the posters are weapons in the struggle," the collective hand-cut stencils, pulled silkscreens around the clock and pasted thousands of sheets across Paris: the stark "CRS = SS" equating riot police with Nazis, "Sous les pavés, la plage," and "La beauté est dans la rue." Designs were debated collectively and signed by no one; police evacuated the Beaux-Arts on 27 June 1968, ending the workshop. Collections at the International Institute of Social History and major museums preserve the posters as a high point of agitprop graphic design.',
    col: [{ h: '#14120f', n: 'riot black' }, { h: '#e8e2d2', n: 'newsprint cream' }, { h: '#c8322b', n: 'revolt red' }, { h: '#2f5fa3', n: 'spray blue' }, { h: '#d9d2c0', n: 'aged kraft gray' }],
    m: ['hand-cut paper stencils', 'water-based silkscreen ink', 'kraft and newsprint stock', 'hand-pulled screens'],
    tx: ['grainy screen fill', 'rough stencil edge', 'flat protest ink'],
    obj: ['street protest posters', 'strike placards', 'union solidarity posters', 'commemorative poster books'],
    ex: ['"CRS = SS" (1968)', '"Sous les pavés, la plage" silkscreen', '"La beauté est dans la rue"'],
    inf: ['Russian Constructivist poster design', 'French revolutionary print tradition', 'Situationist détournement'],
    rel: ['Dazibao', 'Chinese Socialist Realism', 'Psychedelic art'],
    src: [{ n: 'Wikipedia — Atelier Populaire', u: 'https://en.wikipedia.org/wiki/Atelier_Populaire', t: 'B' }, { n: 'Wikipedia — May 68', u: 'https://en.wikipedia.org/wiki/May_68', t: 'B' }, { n: 'International Institute of Social History', u: 'https://www.iisg.nl', t: 'A' }],
    tg: ['may 68', 'atelier populaire', 'silkscreen', 'agitprop', 'paris', 'protest poster', 'stencil'],
    pop: 56, niche: true,
    vd: { shape: 'rough-cut symbols — fists, police helmets, barricades', line: 'jerky hand-cut stencil contours', composition: 'one image, one slogan, maximum street legibility', texture: 'grainy ink skips on cheap paper' },
    typ: { display: 'hand-cut stencil grotesque capitals', body: 'n/a — slogans carry the design', notes: 'anonymous lettering; Univers was the era\'s default grotesque' },
    lit: { quality: 'overcast Paris daylight on walls', temperature: 'cool', shadow: 'weathered paste shadows at sheet edges' },
    ui: { background: 'newsprint cream', surface: 'raw kraft poster cards', components: 'stencil-cut buttons, protest badges', motion: 'quick paste-up slaps' },
  },
]
