/**
 * Rebuild wave — Internet, Subculture & Web/UI r1 (24 entries).
 * Solo-authored after sandbox rollback. Wikipedia titles batch-verified via
 * API (2026-09-14). Dedup-checked against refreshed existing-names.txt.
 */
export const ENTRIES: any[] = [
  {
    n: 'Old Web GeoCities Era', a: ['GeoCities', 'geocities era', 'homepage culture', '90s personal web'],
    cat: 'Internet Aesthetic', c: '1990s amateur homepage culture', e: 'historical',
    o: 'GeoCities neighborhoods (Beverly Hills internet, 1994-2009)', g: 'angelfire, tripod, geocities worldwide',
    p: '1994-2009', era: 'personal homepage boom to Yahoo shutdown',
    sum: 'Under-construction GIFs, MIDI autoplay and guestbooks — the web when it was rooms.',
    desc: 'The GeoCities era (1994-2009) organized the amateur web as neighborhoods: personal homepages with tiled star backgrounds, animated GIF dividers, visitor counters, guestbooks, MIDI autoplays, "under construction" workers and webring navigation. Design was maximal, hand-coded and sincere — every page a bedroom; every hit counter, a heartbeat. Yahoo\'s 2009 shutdown triggered the Archive Team\'s emergency rip (now preserved by the GeoCities torrent and one terabyte of rooms), and the era\'s look now anchors "old web" nostalgia, neocities.org revivals, and yesterweb sentiment: the web as a place you live rather than a product you use.',
    col: [{ h: '#000080', n: 'default link navy' }, { h: '#c0c0c0', n: 'table border silver' }, { h: '#e8c14a', n: 'construction sign yellow' }, { h: '#008080', n: 'tiled teal bg' }, { h: '#ff00ff', n: 'star GIF magenta' }],
    m: ['HTML tables & font tags', 'animated GIF collections', 'MIDI soundtracks', 'guestbook CGI scripts'],
    tx: ['tiled background seams', 'beveled button chrome', 'scrolling marquee shimmer'],
    obj: ['visitor hit counters', 'under-construction GIFs', 'guestbook entries', 'webring nav bars'],
    ex: ['GeoCities "Area51" sci-fi neighborhood', 'Neocities revival homepages', '1TB GeoCities archive torrent'],
    inf: ['BBS and AOL culture', 'desktop publishing at home', 'fan-shrine hobby formats'], rel: ['88x31 Badges & Webrings', 'Web Brutalism', 'Commodore 64 Loading Screens'],
    src: [{ n: 'Wikipedia — GeoCities', u: 'https://en.wikipedia.org/wiki/Yahoo!_GeoCities', t: 'B' }, { n: 'Archive Team — GeoCities preservation', u: 'https://archiveteam.org', t: 'A' }],
    tg: ['old web', 'geocities', 'homepage', 'gif', 'nostalgia', 'internet'],
    pop: 55, niche: false,
    vd: { shape: 'centered 600px table layout', line: '3px bevel borders everywhere', composition: 'star-field bg, content table, guestbook footer', texture: 'tiled GIF seams, chrome bevels' },
    typ: { display: 'Impact or Comic Sans headers', body: 'Times New Roman body', notes: 'marquee text if you\'re brave' },
    lit: { quality: 'flat CRT phosphor', temperature: 'warm-toned', shadow: 'drop shadows in hard grey offsets' },
    ui: { background: 'tiled starfield', surface: 'bevel-table cards', components: '3D-embossed buttons', motion: 'marquee scroll loops' },
    par: 'old web cultures',
  },
  {
    n: 'Web Brutalism', a: ['web brutalism', 'brutalist websites', 'anti-design web', 'html default style'],
    cat: 'Internet Aesthetic', c: 'anti-polish raw HTML design stance', e: 'community_subculture',
    o: 'design discourse (Balenciaga site 2015, brutalistwebsites index)', g: 'fashion web, indie portfolios, design discourse',
    p: '2014-present', era: 'fashion-adopted raw web to ongoing counter-style',
    sum: 'Default blue links, system fonts, zero mercy: websites that refuse to be comfortable.',
    desc: 'Web brutalism applies architectural brutalism\'s honesty to the browser: raw HTML defaults, unstyled blue links, Times New Roman, clashing highlight colors, exposed markup and deliberate user-hostile composition. It emerged in mid-2010s design discourse as a reaction against template sameness (Squarespace gloss) and was adopted strategically — Balenciaga\'s 2015 site, Craigslist as accidental ancestor, indie portfolios, and the brutalistwebsites.com index documenting hundreds. The aesthetic\'s politics: content before decoration, structure visible, comfort refused. Its cousin "neubrutalism" (2021+) keeps the harsh borders but re-adds poster energy and playful color blocks.',
    col: [{ h: '#141414', n: 'text black' }, { h: '#f2efe4', n: 'bare background white' }, { h: '#0000ee', n: 'default link blue' }, { h: '#e8c14a', n: 'highlighter yellow' }],
    m: ['default browser stylesheets', 'system font stacks', 'raw HTML structure', 'no-framework discipline'],
    tx: ['unstyled link underline', 'system font metrics', 'hard 1px borders'],
    obj: ['unstyled-table layouts', 'monospace ASCII dividers', 'wall-of-links indexes', 'anti-landing pages'],
    ex: ['Balenciaga webstore (2015)', 'brutalistwebsites.com index', 'Craigslist as vernacular ancestor'],
    inf: ['architectural brutalism ethics', 'Bauhaus material honesty (misread)', 'early-90s corporate-web austerity'], rel: ['Neubrutalism Web Style', 'Old Web GeoCities Era', 'Bauhaus Design'],
    src: [{ n: 'Wikipedia — Brutalist web design', u: 'https://en.wikipedia.org/wiki/Brutalist_web_design', t: 'B' }, { n: 'Brutalist Websites index', u: 'https://brutalistwebsites.com', t: 'C' }],
    tg: ['brutalism', 'web', 'antidesign', 'raw html', 'minimal', 'internet'],
    pop: 46, niche: false,
    vd: { shape: 'document-flow rectangles, no curves', line: '1px default borders', composition: 'content-terms-first ordering', texture: 'none — that\'s the point' },
    typ: { display: 'Times New Roman bold caps', body: 'default system serif', notes: 'monospace if it wants respect' },
    lit: { quality: 'flat monitor emission', temperature: 'neutral-toned', shadow: 'none allowed' },
    ui: { background: 'document white', surface: 'border-only cards', components: 'unstyled form fields', motion: 'instant jumps, no easing' },
    par: 'web design stances',
  },
  {
    n: '88x31 Badges & Webrings', a: ['88x31 buttons', 'web badges', 'webring navigation', 'button wall'],
    cat: 'Internet Aesthetic', c: 'micro-banner linking culture', e: 'historical',
    o: 'personal web community standards (1995-2005)', g: 'GeoCities-era web, neocities revival',
    p: '1995-2005 (revival 2020s)', era: 'link-exchange etiquette to revival craft scene',
    sum: 'The 88×31 pixel button wall: identity at 2,728 pixels.',
    desc: 'The 88x31 pixel button is old web\'s unit of identity: tiny banners — "Made with Notepad", "Netscape Now!", "Best viewed at 800x600", site-specific pixel art — collected into button walls and stitched together by webrings, circular link exchanges that let strangers\' homepages reference each other like quotes in a guestbook. The format\'s constraints (two colors, 6-8px type, 1px bevel) produced a craft dialect of micro-design; the webring produced an etiquette of mutual visibility. The 2020s neocities/yesterweb revival rebuilt both: button-making tutorials, ring syndicates, and collectors documenting thousands of vintage badges as design history.',
    col: [{ h: '#000080', n: 'badge navy' }, { h: '#c0c0c0', n: 'bevel silver' }, { h: '#e8c14a', n: 'pixel highlight gold' }, { h: '#c93636', n: 'blink-text red' }],
    m: ['pixel-perfect GIF/PNG export', '1px bevel shading', 'animated frame delays', 'webring CGI rings'],
    tx: ['hard pixel edges', 'two-tone bevels', 'blink-frame flicker'],
    obj: ['button-wall footer grids', 'webring prev/next strips', 'anti-88x31 parody badges', '80x15 mini-buttons (later)'],
    ex: ['Netscape Now! official badges', 'Made on a Mac badge', 'neocities button collections'],
    inf: ['software "proudly built with" stickers', 'banner-exchange ad networks', 'zine sticker culture'], rel: ['Old Web GeoCities Era', 'Pixel Art', 'Web Brutalism'],
    src: [{ n: 'Wikipedia — Webring', u: 'https://en.wikipedia.org/wiki/Webring', t: 'B' }, { n: '88x31 badge archive (cambrian era)', u: 'https://cyber.dabamos.de/88x31', t: 'C' }],
    tg: ['badges', 'webring', 'old web', 'pixel', 'buttons', 'nostalgia'],
    pop: 34, niche: true,
    vd: { shape: 'strict 88x31 rectangles in wall grids', line: '1px bevel highlight/shadow pairs', composition: 'footer accumulation aesthetics', texture: '2-4 color pixel fills' },
    typ: { display: '6-7px pixel bitmap lettering', body: 'none — no room', notes: 'the badge IS the sentence' },
    lit: { quality: 'flat screen emission', temperature: 'cool-toned', shadow: 'bevel fakes depth' },
    ui: { background: 'desktop grey', surface: 'badge-wall cards', components: '88x31 collectible tiles', motion: 'blink-tag hover flicker' },
    par: 'old web cultures',
  },
  {
    n: 'Skeuomorphic UI Era', a: ['skeuomorphism', 'iOS 6 leather', 'rich UI era', 'real-object interface'],
    cat: 'Internet Aesthetic', c: 'real-material metaphor interface design', e: 'commercial_style',
    o: 'Apple design culture (macOS Aqua → iOS 6)', g: 'consumer software globally',
    p: '2001-2013', era: 'Aqua gloss to iOS 6 leather shutdown',
    sum: 'Stitched leather, felt card tables and glossy buttons — software as furniture.',
    desc: 'Skeuomorphism is interface design imitating physical material: Apple\'s iOS Game Center felt tables, Notes app legal pads with tear-off holes, Calendar\'s leather stitching, Find My Friends\' tanned hide, and Aqua\'s candy-gloss buttons before it. The era (2001-2013, peaking with iOS 4-6) argued that metaphor teaches — your phone as a desk of familiar objects — and produced the richest (and most ridiculed) ornament in software history: rendered shadows, glass reflections, velvet gradients. Jony Ive\'s iOS 7 (2013) flattened the world overnight, and skeuomorphism is now period style: quoted in "neo-skeuomorph" games, watch-face craft, and every design-history lecture about the metaphor debate.',
    col: [{ h: '#2f4f3a', n: 'game center felt' }, { h: '#8c1f1f', n: 'leather binding red' }, { h: '#c0c0c0', n: 'gloss button silver' }, { h: '#e8c14a', n: 'notepad yellow' }, { h: '#141414', n: 'shadow depth black' }],
    m: ['multi-stop gradients', 'rendered drop shadows', 'gloss highlight overlays', 'material texture photography'],
    tx: ['stitched leather grain', 'felt nap', 'candy-gloss speculars'],
    obj: ['leather-stitched app frames', 'felt game tables', 'glossy candy buttons', 'paper-leaf notepads'],
    ex: ['iOS Game Center (2010-13)', 'Apple Notes legal pad (pre-2013)', 'macOS Aqua buttons (2001)'],
    inf: ['physical product design metaphors', 'early GUI Xerox/Apple metaphor doctrine', 'luxury-material status cues'], rel: ['Aqua Interface', 'Glassmorphism', 'Metro Design Language'],
    src: [{ n: 'Wikipedia — Skeuomorph', u: 'https://en.wikipedia.org/wiki/Skeuomorph', t: 'B' }, { n: 'Ars Technica — iOS skeuomorphism retrospective', u: 'https://arstechnica.com', t: 'C' }],
    tg: ['skeuomorphism', 'ui', 'apple', 'leather', 'gloss', 'design'],
    pop: 57, niche: false,
    vd: { shape: 'object-shaped modules with material skins', line: 'bevel highlights and shadow rims', composition: 'desk-of-things spatial metaphor', texture: 'leather, felt, glass, paper' },
    typ: { display: 'embossed lettering on materials', body: 'system font with drop shadows', notes: 'labels stitched like patches' },
    lit: { quality: 'virtual studio product light', temperature: 'warm-toned', shadow: 'rendered realistic drop shadows' },
    ui: { background: 'textured material', surface: 'material-wrapped cards', components: 'gloss-3D buttons', motion: 'physical-object press depth' },
    par: 'web design stances',
  },
  {
    n: 'Neubrutalism Web Style', a: ['neubrutalism', 'neo-brutalism', 'hard shadow web', 'poster-web design'],
    cat: 'Internet Aesthetic', c: '2021+ hard-border playful web design', e: 'community_subculture',
    o: 'designer community (Figma community, Gumroad 2021)', g: 'indie web, agency sites, design-twitter',
    p: '2021-present', era: 'post-flat-design counter-movement',
    sum: 'Black borders, brutal shadows, clashing neons: the web\'s joyful rebellion.',
    desc: 'Neubrutalism (2021-) is web brutalism with energy drinks: thick 2-4px black borders, solid offset shadows (no blur), clashing candy colors (yellow on pink on lime), hover states that physically shove cards, and poster-scale type — a style that reads as hand-made print culture pasted onto screens. Gumroad\'s 2021 rebrand (built in-house) made it famous; Figma community kits, Framer templates and hundreds of agency sites spread the grammar. Where brutalism refuses comfort, neubrutalism plays with it: anti-corporate optics that still converts. It is the first web-native style generation to feel like a scene rather than a doctrine.',
    col: [{ h: '#e8c14a', n: 'block yellow' }, { h: '#c93663', n: 'poster pink' }, { h: '#141414', n: 'border black' }, { h: '#7fd45f', n: 'acid lime' }, { h: '#f2efe4', n: 'card cream' }],
    m: ['solid offset box-shadows', 'heavy border widths', 'sans-serif superfamily stacks', 'flat candy palettes'],
    tx: ['hard black outlines', 'shadow-block offset', 'flat color slabs'],
    obj: ['shadow-shoved cards', 'sticker-badge CTAs', 'marquee-strip headers', 'grid-tilted hero blocks'],
    ex: ['Gumroad rebrand (2021)', 'Figma community neubrutalism kits', 'neo-brutalist agency portfolio wave'],
    inf: ['memphis design energy', 'punk flyer layout', 'brutalist web ethics (softened)'], rel: ['Web Brutalism', 'Memphis Design', 'Old Web GeoCities Era'],
    src: [{ n: 'Wikipedia — Neubrutalism (design)', u: 'https://en.wikipedia.org/wiki/Neubrutalism_(design)', t: 'B' }, { n: 'Gumroad — 2021 redesign notes', u: 'https://gumroad.com', t: 'C' }],
    tg: ['neubrutalism', 'web', 'posters', 'shadows', 'design', '2020s'],
    pop: 53, niche: false,
    vd: { shape: 'tilted rectangles with hard black frames', line: '4px borders, zero radius', composition: 'poster-collage z-axis', texture: 'flat slabs, sticker gloss' },
    typ: { display: 'ultra-heavy grotesque headlines', body: 'workhorse sans with attitude', notes: 'type does the shouting' },
    lit: { quality: 'flat daylight, no gradient', temperature: 'warm-toned', shadow: 'solid offset, never blurred' },
    ui: { background: 'block yellow', surface: 'border-frame cards', components: 'shove-on-hover buttons', motion: 'physical kick interactions' },
    par: 'web design stances',
  },
  {
    n: 'Glassmorphism', a: ['glassmorphism', 'frosted glass ui', 'acrylic design', 'backdrop blur style'],
    cat: 'Internet Aesthetic', c: 'translucent blurred-layer interface style', e: 'commercial_style',
    o: 'Apple macOS Big Sur & Microsoft Fluent (2020)', g: 'consumer OS, fintech, web dashboards',
    p: '2013-present (boom 2020)', era: 'Vista Aero ancestry to Big Sur mainstream',
    sum: 'Frosted panes floating over color: UI as architectural glazing.',
    desc: 'Glassmorphism stacks interface cards as translucent frosted glass: background blur, 1px white rims, subtle inner highlights and layered depth — descends from Windows Vista Aero and iOS control centers, mainstreamed by macOS Big Sur (2020), Microsoft Fluent and the fintech boom (Revolut-era dashboards, every crypto app). The style sells premium software calm: content floats, color bleeds through panes, hierarchy reads as physical layering. Accessibility critiques (contrast collapse) keep it honest; variants persist in "liquid glass" OS updates and every dashboard template pack. Its material fantasy: software as architecture you can see through.',
    col: [{ h: '#b0c4de', n: 'frost pane blue-grey' }, { h: '#f2efe4', n: 'rim highlight white' }, { h: '#2979ff', n: 'backdrop gradient blue' }, { h: '#c93663', n: 'accent glow pink' }],
    m: ['backdrop-filter blur', 'semi-transparent fills', '1px light rims', 'gradient backdrop canvases'],
    tx: ['frosted diffusion', 'rim-light edge', 'inner-glow depth'],
    obj: ['floating glass cards', 'frosted nav bars', 'translucent widgets', 'depth-stacked modals'],
    ex: ['macOS Big Sur (2020) system UI', 'Microsoft Fluent acrylic layers', 'fintech dashboard template era'],
    inf: ['Vista Aero glass (2006)', 'physical architecture glazing', 'video-game HUD panels'], rel: ['Skeuomorphic UI Era', 'Aqua Interface', 'Metro Design Language'],
    src: [{ n: 'Wikipedia — Glassmorphism', u: 'https://en.wikipedia.org/wiki/Glassmorphism', t: 'B' }, { n: 'Apple HIG — materials guidance', u: 'https://developer.apple.com/design', t: 'A' }],
    tg: ['glassmorphism', 'ui', 'glass', 'blur', 'design', '2020s'],
    pop: 59, niche: false,
    vd: { shape: 'rounded translucent panes in z-stacks', line: '1px luminous rims', composition: 'layered depth over gradient worlds', texture: 'frosted diffusion, specular rims' },
    typ: { display: 'clean SF/Inter headings', body: 'system sans on glass', notes: 'contrast carefully rationed' },
    lit: { quality: 'backlit through frosted panes', temperature: 'cool-toned', shadow: 'soft ambient depth shadows' },
    ui: { background: 'gradient canvas', surface: 'frosted cards', components: 'translucent buttons', motion: 'pane-drift parallax' },
    par: 'web design stances',
  },
  {
    n: 'Metro Design Language', a: ['metro ui', 'windows phone style', 'modern ui', 'typography-first design'],
    cat: 'Internet Aesthetic', c: 'Microsoft typography-tile interface language', e: 'commercial_style',
    o: 'Microsoft (Windows Phone 7, 2010; Zune earlier)', g: 'Microsoft ecosystem, design pedagogy',
    p: '2010-2017', era: 'Zune/WP7 launch to Windows 8 backlash fade',
    sum: 'Flat tiles, giant type, motion that means it: software as Swiss signage.',
    desc: 'Metro — Microsoft\'s design language for Zune, Windows Phone 7 and Windows 8 — rebuilt UI around typography and motion: flat color tiles of live content, huge segmentation-lettered headers, no ornament, and animations with physical authority (slides that decelerate, pivots with weight). Its Swiss/International Typographic lineage was explicit (signage, transport graphics), and at its best (Windows Phone 7-8, Zune HD) it was the most distinctive consumer UI of its decade. Windows 8\'s desktop transplant failed publicly; Microsoft moved to Fluent, but Metro\'s typographic discipline — type as interface, chrome as nothing — remains foundational to flat design\'s best practice.',
    col: [{ h: '#00a2c7', n: 'wp tile cyan' }, { h: '#141414', n: 'ink black' }, { h: '#f2efe4', n: 'tile white' }, { h: '#c93636', n: 'live-tile red' }, { h: '#7fd45f', n: 'messaging green' }],
    m: ['flat color tiles', 'segoe UI family', 'pivot & pan motion systems', 'magnetic snap layouts'],
    tx: ['pure flat color fields', 'type-edge crispness', 'tile-motion trails'],
    obj: ['live-content tiles', 'panorama page strips', 'pivot header scopes', 'segment-letter hub headers'],
    ex: ['Windows Phone 7 start screen', 'Zune HD interface', 'Windows 8 start hub'],
    inf: ['International Typographic Style', 'transit signage systems', 'Microsoft brand modernization'], rel: ['Glassmorphism', 'Skeuomorphic UI Era', 'Bauhaus Design'],
    src: [{ n: 'Wikipedia — Metro (design language)', u: 'https://en.wikipedia.org/wiki/Metro_(design_language)', t: 'B' }, { n: 'Microsoft Design — Metro archive', u: 'https://www.microsoft.com/design', t: 'A' }],
    tg: ['metro', 'windows phone', 'tiles', 'typography', 'flat', 'design'],
    pop: 47, niche: false,
    vd: { shape: 'edge-to-edge tile fields', line: 'type-weight hierarchy only', composition: 'horizontal panorama flow', texture: 'flat, matte, nothing else' },
    typ: { display: 'Segoe Light at poster scale', body: 'Segoe regular compact', notes: 'typography IS the interface' },
    lit: { quality: 'flat even emission', temperature: 'cool-toned', shadow: 'none — depth is motion' },
    ui: { background: 'tile dark', surface: 'flat-color cards', components: 'live-tile modules', motion: 'weighted pivot slides' },
    par: 'web design stances',
  },
  {
    n: 'Aqua Interface', a: ['aqua ui', 'mac os x aqua', 'pinstripes', 'brushed metal era'],
    cat: 'Internet Aesthetic', c: 'Apple OS X 2000s interface design', e: 'commercial_style',
    o: 'Apple (Mac OS X, 2000-2014)', g: 'consumer software globally',
    p: '2000-2014', era: '10.0 Cheetah to Yosemite flattening',
    sum: 'Pinstripes, jelly buttons and brushed metal: the OS that made computers pretty.',
    desc: 'Aqua — Mac OS X\'s interface from 2000 — established the 2000s\' visual standard for software: candy-gloss gel buttons with real specular physics, pinstriped window backgrounds, brushed-metal panels, drop shadows like print, and motion (the genie effect, dock magnification) that made computing feel material. Its eras: early pinstripe/aqua (10.0-10.2), brushed metal decade (10.3-10.9) with iTunes\' and Safari\'s metal chrome, before Yosemite (2014) flattened everything. Aqua\'s influence is total — every "modern OS" of the 2000s (Vista glass, KDE Oxygen) answered it — and its buttons remain the most-imitated object in UI history.',
    col: [{ h: '#2979ff', n: 'aqua gel blue' }, { h: '#c0c0c0', n: 'brushed metal grey' }, { h: '#f2efe4', n: 'pinstripe white' }, { h: '#141414', n: 'window shadow black' }],
    m: ['gel-gradient buttons', 'pinstripe background patterns', 'brushed metal textures', 'quartz shadow compositing'],
    tx: ['gel speculars', 'brushed metal streak', 'pinstripe rhythm'],
    obj: ['candy jelly buttons', 'pinstriped list panes', 'brushed metal app windows', 'magnifying dock shelf'],
    ex: ['Mac OS X 10.0 Aqua debut', 'iTunes brushed metal era', 'genie effect window minimize'],
    inf: ['consumer product design gloss', 'NeXTSTEP engineering base', 'broadcast and print design polish'], rel: ['Skeuomorphic UI Era', 'Glassmorphism', 'Frutiger Aero'],
    src: [{ n: 'Wikipedia — Aqua (user interface)', u: 'https://en.wikipedia.org/wiki/Aqua_(user_interface)', t: 'B' }, { n: 'Apple — macOS human interface archives', u: 'https://developer.apple.com/design', t: 'A' }],
    tg: ['aqua', 'macos', 'ui', 'gel', 'brushed metal', 'design'],
    pop: 54, niche: false,
    vd: { shape: 'rounded gel capsules and metal sheets', line: 'specular highlight curves', composition: 'desktop-as-stage layering', texture: 'gel gloss, metal streak, pinstripe' },
    typ: { display: 'Lucida Grande era headings', body: 'system clean sans', notes: 'polish, never ornament past gloss' },
    lit: { quality: 'studio product photography light', temperature: 'cool-toned', shadow: 'print-quality soft drop shadows' },
    ui: { background: 'pinstripe grey', surface: 'gel-metal cards', components: 'jelly buttons', motion: 'genie-effect morphs' },
    par: 'web design stances',
  },
  {
    n: 'Cybergoth', a: ['cyber goth', 'graver fashion', 'cyber raver', 'industrial dance wear'],
    cat: 'Subculture Style', c: 'rave-industrial fashion subculture', e: 'community_subculture',
    o: 'UK & German rave/industrial scenes (late 1990s)', g: 'Europe, US club scenes, TikTok revival',
    p: '1997-present', era: 'happy hardcore & industrial club era to platform revival',
    sum: 'Goggles, dreadfalls and platform boots: the rave future made flesh.',
    desc: 'Cybergoth fused goth\'s darkness with rave\'s neon: UV-reactive mesh, PVC and doll-hair dreadfalls, gas-mask respirators, lab goggles, platform New Rocks, and cyberlox braids in acid green and hot pink — a costume engineered for strobe-lit warehouses playing aggrotech, EBM and happy hardcore. Born from late-1990s UK/German industrial club scenes (the "graver" portmanteau), the style spread through European festivals and US cyber clubs, dropped from mainstream view in the 2010s, and was resurrected by TikTok fashion cycles. Its visual logic: the body as techno-console — tubing, straps, screens, and neon filaments everywhere.',
    col: [{ h: '#00e676', n: 'UV acid green' }, { h: '#141414', n: 'PVC black' }, { h: '#ff00ff', n: 'dreadfall magenta' }, { h: '#2979ff', n: 'goggle lens blue' }],
    m: ['UV-reactive mesh', 'PVC & rubber trims', 'doll-hair dreadfalls', 'platform boots (New Rock)'],
    tx: ['neon glow-reactive brightness', 'vinyl shine', 'fiber-dread frizz'],
    obj: ['respirator gas masks', 'goggle stacks', 'cyberlox falls', 'platform boots'],
    ex: ['Infest (UK) goth festival cyber crowd', 'M\'era Luna cybergoth gatherings', 'TikTok #cybergoth revival (2020s)'],
    inf: ['industrial & EBM club culture', 'cyberpunk film costumes', 'Matrix-era fashion'], rel: ['Pastel Goth', 'Seapunk', 'Cyberpunk'],
    src: [{ n: 'Wikipedia — Cybergoth', u: 'https://en.wikipedia.org/wiki/Cybergoth', t: 'B' }, { n: 'Infest Festival — scene documentation', u: 'https://www.infestuk.com', t: 'C' }],
    tg: ['cybergoth', 'rave', 'neon', 'goth', 'clubwear', 'fashion'],
    pop: 44, niche: false,
    vd: { shape: 'spiked silhouettes with tubing arcs', line: 'UV glow-edge contours', composition: 'club-strobe freeze frames', texture: 'vinyl shine, fiber neon' },
    typ: { display: 'cyber-extended glitch lettering', body: 'flyer condensed caps', notes: 'goggle-lens glare in every photo' },
    lit: { quality: 'strobe and blacklight', temperature: 'cool-toned', shadow: 'UV makes shadows fluorescent' },
    ui: { background: 'blacklight void', surface: 'vinyl-shine cards', components: 'goggle-visor toggles', motion: 'strobe-pulse flashes' },
    par: 'club subcultures',
  },
  {
    n: 'Pastel Goth', a: ['pastel goth', 'creepy cute', 'kawaii goth', 'nu goth'],
    cat: 'Subculture Style', c: 'candy-dark hybrid fashion', e: 'community_subculture',
    o: 'Tumblr fashion community (2010)', g: 'Tumblr, Instagram, Harajuku street adoption',
    p: '2010-present', era: 'tumblr aesthetic blogs to global streetwear',
    sum: 'Skulls in lavender: spooky made sweet, dark made wearable.',
    desc: 'Pastel goth (nu-goth, creepy-cute) inverted goth\'s color law around 2010 on Tumblr: black platform base layers under mint, lavender and baby-pink candy colors, with skulls, bats, pentagrams and coffins rendered kawaii — bows on skeletons, glitter on gravestones. Drawing on Harajuku\'s fairy-kei softness and gothic lolita structure, the style spread through Lookbook and Instagram, entered mainstream fast fashion (Hot Topic to Shein), and survives as the default "spooky-cute" Halloween-ready dialect. Its thesis: horror and sweetness aren\'t opposites — pastel makes darkness gentle, and darkness makes pastel dangerous.',
    col: [{ h: '#c9a0dc', n: 'lavender candy' }, { h: '#a0d8ef', n: 'baby mint blue' }, { h: '#141414', n: 'platform black' }, { h: '#f5c6e0', n: 'skull bow pink' }],
    m: ['pastel hair dyes', 'kawaii skeleton prints', 'platform boots & creepers', 'glitter acrylic charms'],
    tx: ['soft pastel matte', 'glitter sparkle', 'cotton-candy fluff'],
    obj: ['skull-and-bow accessories', 'bat-print pastel tees', 'lavender creepers', 'coffin-shaped purses'],
    ex: ['Tumblr #pastelgoth peak (2012-14)', 'Iron Fist spooky-cute shoe lines', 'Harajuku pastel-goth street snaps'],
    inf: ['fairy kei sweetness', 'gothic lolita silhouettes', 'Halloween retail imagery'], rel: ['Cybergoth', 'Fairycore', 'Fairy Kei Fashion'],
    src: [{ n: 'Wikipedia — Goth subculture', u: 'https://en.wikipedia.org/wiki/Goth_subculture', t: 'B' }, { n: 'Tokyo Fashion — pastel goth street snaps', u: 'https://tokyofashion.com', t: 'C' }],
    tg: ['pastel goth', 'kawaii', 'creepy cute', 'tumblr', 'fashion', 'pastel'],
    pop: 50, niche: false,
    vd: { shape: 'layered platform silhouettes with candy accents', line: 'soft rounded spooky motifs', composition: 'sweet-dark balance framing', texture: 'pastel matte, glitter sparkle' },
    typ: { display: 'rounded kawaii-serif logotypes', body: 'bubble-script captions', notes: 'drip-spine letters optional' },
    lit: { quality: 'soft filtered daylight', temperature: 'pastel-warm', shadow: 'purple-tinted soft shade' },
    ui: { background: 'lavender gradient', surface: 'candy-frame cards', components: 'skull-bow icons', motion: 'bounce-with-glitter taps' },
    par: 'club subcultures',
  },
  {
    n: 'Fairycore', a: ['fairy core', 'fairygrunge', 'cottage fairy', 'pixie aesthetic'],
    cat: 'Internet Aesthetic', c: 'woodland-fantasy internet aesthetic', e: 'community_subculture',
    o: 'Tumblr & TikTok aesthetic community (2018-2021)', g: 'anglophone internet, cottagecore adjacency',
    p: '2018-present', era: 'pandemic-era nature dream boom',
    sum: 'Moth wings, moss and meadow light: the internet moves into the fairy wood.',
    desc: 'Fairycore is the woodland-fantasy branch of the pandemic-era nature aesthetics: dew-lit meadows, moth and butterfly wings, mushroom clusters, fairy-light glades, gossamer dresses and delicate jewelry — with fairygrunge adding dirt, twine and muted decay to the sweetness. It grew from Tumblr\'s cottagecore family via TikTok (2020-21 peak), feeding dress-up videos, nature-walk filming and wedding-inspo boards; cottagecore\'s domesticity becomes fairycore\'s wilderness. Its visual grammar: backlit fog, found-object altars, and the persistent sense that the camera wandered off the path and saw something it shouldn\'t have.',
    col: [{ h: '#a8d5a2', n: 'moss green' }, { h: '#f5e6c8', n: 'meadow light cream' }, { h: '#c9a0dc', n: 'wing violet' }, { h: '#7a6a4f', n: 'grunge twig brown' }],
    m: ['gossamer & tulle fabrics', 'pressed flowers & moss', 'delicate wire jewelry', 'moth and butterfly motifs'],
    tx: ['dew-drop glint', 'gossamer translucence', 'moss velvet nap'],
    obj: ['fairy-light glade scenes', 'mushroom-cluster macro shots', 'wing-veil costumes', 'found-object shrine tables'],
    ex: ['TikTok #fairycore costume reels (2020-21)', 'fairygrunge forest walk videos', 'fairy-themed weddings & photoshoots'],
    inf: ['Victorian fairy painting', 'cottagecore nature domesticity', 'renaissance faire costume culture'], rel: ['Cottagecore', 'Pastel Goth', 'Fairy Kei Fashion'],
    src: [{ n: 'Wikipedia — Cottagecore', u: 'https://en.wikipedia.org/wiki/Cottagecore', t: 'B' }, { n: 'Aesthetics Wiki — Fairycore', u: 'https://aesthetics.fandom.com', t: 'C' }],
    tg: ['fairycore', 'nature', 'forest', 'moss', 'fantasy', 'internet'],
    pop: 49, niche: false,
    vd: { shape: 'organic curlicue, wing-veil silhouettes', line: 'vine-and-filigree soft edges', composition: 'backlit glade depth', texture: 'moss, gossamer, dew glint' },
    typ: { display: 'delicate serif with leaf terminals', body: 'light handwritten script', notes: 'captions whispered' },
    lit: { quality: 'dappled forest backlight', temperature: 'warm-toned', shadow: 'tree-shade soft dapple' },
    ui: { background: 'meadow haze', surface: 'petal-froth cards', components: 'vine-scroll dividers', motion: 'wing-flutter hovers' },
    par: 'internet nature aesthetics',
  },
  {
    n: 'Mori Kei Forest Fashion', a: ['mori girl', 'mori kei', 'forest girl fashion', 'natural kei'],
    cat: 'Subculture Style', c: 'Japanese forest-layered fashion movement', e: 'community_subculture',
    o: 'Mixi community (Choco, 2007), Tokyo', g: 'Japan, global slow-fashion internet',
    p: '2007-2015 (revival present)', era: 'mixi community boom to slow-fashion afterlife',
    sum: 'Layered like a walk in the woods: the Japanese "forest girl" dress philosophy.',
    desc: 'Mori kei ("forest style") began in 2007 when Choco\'s mixi community defined the mori girl: layer upon layer of loose natural-fiber clothing — crocheted vests over smock dresses over skirts, warm browns, creams and forest greens, with scarves, brooches and vintage lace — dressing like a storybook wanderer rather than Harajuku\'s louder tribes. Peak media attention (mooks, Spoon. features) came 2009-2013; the community formalized rules (natural materials, A-line comfort, no glitter) that practitioners then happily broke. Its ethos — slow, handmade, seasonal, self-soothing — prefigured global cottagecore, and mori dressing survives in Japanese slow fashion and worldwide soft-grunge wardrobes.',
    col: [{ h: '#b0a58a', n: 'oatmeal cream' }, { h: '#7a6a4f', n: 'forest brown' }, { h: '#a8b0a0', n: 'sage green' }, { h: '#8c1f1f', n: 'brooch berry red' }],
    m: ['linen & gauze cotton layers', 'crocheted knitwear', 'vintage lace trims', 'wooden & brass brooches'],
    tx: ['gauze crinkle', 'crochet openness', 'layer-on-layer depth'],
    obj: ['smock-dress bases', 'layered vest stacks', 'scarf-and-brooch focal points', 'basket-bag accessories'],
    ex: ['Mori Girl Pattern Book (2010 mook)', 'mixi mori community lookbooks', 'Spoon. mori features'],
    inf: ['natural kei Japanese fashion', 'cottage living literature', 'vintage market culture'], rel: ['Fairycore', 'Cottagecore', 'Fairy Kei Fashion'],
    src: [{ n: 'Wikipedia — Mori girl', u: 'https://en.wikipedia.org/wiki/Mori_girl', t: 'B' }, { n: 'Tokyo Fashion — mori girl features', u: 'https://tokyofashion.com', t: 'C' }],
    tg: ['mori', 'forest', 'layers', 'japan', 'fashion', 'natural'],
    pop: 36, niche: true,
    vd: { shape: 'layered A-line silhouettes, draping tiers', line: 'crochet openwork edges', composition: 'texture-over-color composition', texture: 'gauze, crochet, wool, lace' },
    typ: { display: 'gentle serif with organic footnotes', body: 'diary-hand captions', notes: 'mooks type-set like notebooks' },
    lit: { quality: 'soft forest-filtered light', temperature: 'warm-toned', shadow: 'layer folds make gentle shade' },
    ui: { background: 'oatmeal linen', surface: 'layer-stack cards', components: 'brooch-pin accents', motion: 'layer-peek scrolls' },
    par: 'japanese street fashion',
  },
  {
    n: 'Seapunk', a: ['sea punk', 'webpunk ocean', 'vaporwave sibling', 'aquatic net art'],
    cat: 'Internet Aesthetic', c: 'ocean-nostalgia net art style', e: 'experimental_hybrid',
    o: 'Tumblr (2011,Albertine Osteria & Zombelle scenes)', g: 'tumblr, twitter, club music visuals',
    p: '2011-2014', era: 'tumblr art-music moment to vaporwave\'s shadow',
    sum: 'Dolphin GIFs over holographic seas: the ocean as club visual.',
    desc: 'Seapunk was a short, sharp net-art moment (2011-2014): Tumblr-centric visuals of CG dolphins, pixelated waves, wireframe shells and holographic gradients fused with club music (Zombelle, Ultrademon\'s "seapunk" tracks), seeded by artists around the Albertine Osteria blog and ignited when Twitter users spoofed its format into memes. Its palette — aquarium teal, hologram iridescence, sunbleached coral — and its dolphin Y2K nostalgia anticipated vaporwave\'s mass bloom; Rihanna\'s SNL appearance (2012) borrowed its graphics and caused scene controversy. As a style it belongs to the net-native family that treats the ocean as screen-saver sublime: water as CRT glow.',
    col: [{ h: '#1fd4c7', n: 'aquarium teal' }, { h: '#c93663', n: 'hologram pink' }, { h: '#2979ff', n: 'deep-sea blue' }, { h: '#f2d5a0', n: 'coral sand pale' }],
    m: ['CG dolphin renders', 'holographic foil textures', 'wireframe grids', 'club visual loops'],
    tx: ['hologram iridescence', 'wireframe depth', 'water-shimmer loop'],
    obj: ['dolphin GIF loops', 'pixel-wave backgrounds', 'shell-and-trident icons', 'sunburned-CD gradients'],
    ex: ['Albertine Osteria seapunk tumblr', 'Rihanna SNL seapunk visuals (2012)', 'Ultrademon seapunk releases'],
    inf: ['Y2K aquatic tech marketing', 'vaporwave\'s sibling palette', 'club-VJ culture'], rel: ['Vaporwave', 'Cybergoth', 'Y2K Cyber Aesthetic'],
    src: [{ n: 'Wikipedia — Seapunk', u: 'https://en.wikipedia.org/wiki/Seapunk', t: 'B' }, { n: 'Dazed — seapunk scene features', u: 'https://www.dazeddigital.com', t: 'C' }],
    tg: ['seapunk', 'ocean', 'netart', 'dolphin', 'club', 'internet'],
    pop: 33, niche: true,
    vd: { shape: 'wireframe waves with dolphin silhouettes', line: 'holographic gradient bands', composition: 'screensaver-sublime framing', texture: 'foil iridescence, pixel water' },
    typ: { display: 'chrome aquatic logotypes', body: 'lyric-caption holograms', notes: 'dolphin unicode as ornament' },
    lit: { quality: 'aquarium tank glow', temperature: 'cool-toned', shadow: 'hologram self-shadow' },
    ui: { background: 'deep-sea gradient', surface: 'foil-shimmer cards', components: 'shell-icons', motion: 'wave-loop parallax' },
    par: 'net art movements',
  },
  {
    n: 'McBling Era', a: ['mcbling', 'y2k bling', '2000s glam', 'trashy glam'],
    cat: 'Subculture Style', c: '2000s rhinestone consumer glam', e: 'community_subculture',
    o: 'US pop culture (2003-2008)', g: 'US celebrity culture, MySpace fashion',
    p: '2003-2008', era: 'post-Y2K pop maximalism',
    sum: 'Rhinestones, velour tracksuits and flip phones: the 2000s in one outfit.',
    desc: 'McBling (term coined by Tavi Gevinson-era writers, canonized by fashion historians like Liana Satenstein) names the 2003-2008 explosion of logo glam: Juicy velour tracksuits, rhinestone-studded everything, Von Dutch trucker hats, UGGs with miniskirts, flip phones with charms, and Paris-Hilton-era paparazzi flash. Descended from hip-hop bling and tabloid celebrity culture, it was maximal, expensive-looking and unashamed; MySpace glamor shots were its native format. The 2010s rejected it as "trashy", and the 2020s Y2K revival re-adopted it ironically-then-sincerely. Its visual signature: flash-photography gloss, brand-as-costume, sparkle against velour.',
    col: [{ h: '#f5c6e0', n: 'velour pink' }, { h: '#e8c14a', n: 'rhinestone gold' }, { h: '#c93663', n: 'logomania red' }, { h: '#f2efe4', n: 'UGG fleece cream' }],
    m: ['velour tracksuits', 'rhinestone appliqués', 'trucker hat foam', 'flip-phone charms'],
    tx: ['velour nap sheen', 'rhinestone sparkle points', 'paparazzi flash gloss'],
    obj: ['Juicy Couture tracksuits', 'Von Dutch trucker hats', 'bedazzled flip phones', 'monogram miniskirt sets'],
    ex: ['Paris & Nicole Simple Life era', 'MySpace glamor profile pics', 'Juicy Couture velour collections'],
    inf: ['hip-hop bling culture', 'tabloid celebrity system', 'mall-brand logomania'], rel: ['Y2K Cyber Aesthetic', 'Rockabilly Revival', 'Pop Art Silkscreen'],
    src: [{ n: 'Wikipedia — McBling', u: 'https://en.wikipedia.org/wiki/McBling', t: 'B' }, { n: 'i-D — McBling retrospective', u: 'https://i-d.vice.com', t: 'C' }],
    tg: ['mcbling', 'y2k', 'bling', '2000s', 'glam', 'fashion'],
    pop: 47, niche: false,
    vd: { shape: 'glam-pose silhouettes in velour softness', line: 'rhinestone sparkle points', composition: 'paparazzi-flash framing', texture: 'velour nap, crystal glitter' },
    typ: { display: 'rhinestone-script logotypes', body: 'MySpace glitter captions', notes: 'brand names as jewelry' },
    lit: { quality: 'direct flash photography', temperature: 'warm-toned', shadow: 'flash kills shadow, adds gloss' },
    ui: { background: 'velour pink', surface: 'sparkle-border cards', components: 'rhinestone-dot buttons', motion: 'glitter-shimmer hovers' },
    par: 'club subcultures',
  },
  {
    n: 'Afropunk Style', a: ['afropunk', 'afro-punk', 'black alternative fashion', 'punk of color'],
    cat: 'Subculture Style', c: 'Black alternative music & fashion culture', e: 'community_subculture',
    o: 'Brooklyn (Afropunk Festival, 2005)', g: 'US, South Africa, France, Brazil',
    p: '2005-present', era: 'festival founding to global Black-alternative platform',
    sum: 'Painted faces, pressed fros, and punk reclaimed: Black alternative in full color.',
    desc: 'Afropunk — the movement around the 2003 documentary and 2005 Brooklyn festival — is Black alternative culture\'s self-assertion: natural hair architecture (fros, locs, braids as sculpture), face paint and bold geometric pattern, thrifting culture, genre-mixing music (punk, soul, house, trap), and the "no rockists" refusal of white alternative gatekeeping. The festival became a global platform (Paris, Johannesburg, London) and a style engine: its face-paint-and-print look, natural-hair pride and DIY-to-couture range redefined what "punk" and "alternative" can wear. Its photography tradition — the festival crowd as style documentary — is one of the most-copied street-style genres of the 2010s-20s.',
    col: [{ h: '#8c1f1f', n: 'war-paint red' }, { h: '#e8c14a', n: 'pattern gold' }, { h: '#141414', n: 'afro crowning black' }, { h: '#2f7d4f', n: 'pan-african green' }],
    m: ['natural hair styling tools', 'face paint pigments', 'kente & ankara prints', 'DIY leather and studs'],
    tx: ['hair volume cloud', 'paint pigment matte', 'print-satin gleam'],
    obj: ['geometric face-paint masks', 'statement natural-hair styles', 'print-mixing festival wear', 'protest-signage accessories'],
    ex: ['Afropunk Brooklyn festival style (annual)', 'Afropunk Johannesburg editions', 'documentary AFROPUNK (2003)'],
    inf: ['Black punk lineage (Bad Brains, Fishbone)', 'African print fashion revivals', 'natural hair movement'], rel: ['Rockabilly Revival', 'McBling Era', 'Graffiti Writing Culture'],
    src: [{ n: 'Wikipedia — Afropunk', u: 'https://en.wikipedia.org/wiki/Afropunk', t: 'B' }, { n: 'AFROPUNK — official festival platform', u: 'https://afropunk.com', t: 'A' }],
    tg: ['afropunk', 'festival', 'black culture', 'punk', 'fashion', 'music'],
    pop: 48, niche: false,
    vd: { shape: 'crowned-hair silhouettes and painted faces', line: 'geometric paint boundaries', composition: 'documentary-crowd energy', texture: 'hair cloud, pigment matte, print weave' },
    typ: { display: 'protest-poster display caps', body: 'zine-cut body text', notes: 'lineup posters as canon' },
    lit: { quality: 'golden-hour festival light', temperature: 'warm-toned', shadow: 'crowd-shade rhythm' },
    ui: { background: 'print-collage field', surface: 'festival-poster cards', components: 'paint-stroke dividers', motion: 'crowd-wave energy loops' },
    par: 'club subcultures',
  },
  {
    n: 'Rockabilly Revival', a: ['rockabilly', 'psychobilly', 'greaser revival', '50s bad boy style'],
    cat: 'Subculture Style', c: '1950s Americana subculture revival', e: 'community_subculture',
    o: 'US roots revival (1980s Stray Cats era)', g: 'US, UK, Japan (psychobilly), global scenes',
    p: '1979-present', era: 'Stray Cats wave to global psychobilly scenes',
    sum: 'Pompadours, pegged jeans and upright bass slaps: the 1950s that never left.',
    desc: 'Rockabilly revival keeps 1950s Americana alive as living subculture: pompadour and duck-tail hair with actual pomade, cuffed selvedge denim, leather motorcycle jackets, swing dresses and victory rolls, the era\'s cars as totems, and its music lineage from Stray Cats (1979-) through psychobilly\'s horror-punk mutation (The Meteors, Nekromantix) to Japan\'s dedicated scene (Tokyo\'s Harajuku rockabillies since the 1980s). The culture is craft-heavy — pomade rituals, vintage sourcing, car-kustom kulture (pinstriping, lead sleds) — and visually cohesive enough to read instantly: the 1950s as defiant nostalgia with a danger curve.',
    col: [{ h: '#141414', n: 'leather black' }, { h: '#8c1f1f', n: 'bow-tie red' }, { h: '#e9e2d0', n: 'collar white tee' }, { h: '#3a5a8c', n: 'denim indigo' }, { h: '#e8963a', n: 'kustom flame orange' }],
    m: ['pomade & barber tools', 'selvedge denim', 'leather jackets', 'upright bass & vintage amps'],
    tx: ['pomade gloss waves', 'leather worn crease', 'denim fade whiskers'],
    obj: ['pompadour hairstyles', 'lead-sled kustom cars', 'victory-roll updos', 'slap-bass stage kits'],
    ex: ['Stray Cats revival wave (1979-81)', 'The Meteors & psychobilly scene', 'Harajuku rockabilly weekend gatherings'],
    inf: ['1950s Hollywood rebel imagery', 'hot rod kustom kulture', 'horror B-movie aesthetics'], rel: ['Afropunk Style', 'McBling Era', 'American Diner Culture'],
    src: [{ n: 'Wikipedia — Rockabilly', u: 'https://en.wikipedia.org/wiki/Rockabilly', t: 'B' }, { n: 'Viva Las Vegas Rockabilly Weekend', u: 'https://www.vivalasvegas.net', t: 'C' }],
    tg: ['rockabilly', '1950s', 'greaser', 'psychobilly', 'vintage', 'fashion'],
    pop: 45, niche: false,
    vd: { shape: 'sculpted hair volumes and slim silhouettes', line: 'pinstripe & flame kustom lines', composition: 'car-show photo staging', texture: 'pomade gloss, leather crease, denim fade' },
    typ: { display: 'hot-rod marquee lettering', body: 'record-sleeve script', notes: 'barber-shop signage logic' },
    lit: { quality: 'chrome-shop neon dusk', temperature: 'warm-toned', shadow: 'high-contrast noir side light' },
    ui: { background: 'denim indigo', surface: 'leather-stitch cards', components: 'flame-paint accents', motion: 'slap-bass pulse rhythm' },
    par: 'club subcultures',
  },
  {
    n: 'Rage Comic Era', a: ['rage comics', 'trollface era', 'FFFFUUUU', '2010 meme faces'],
    cat: 'Internet Aesthetic', c: 'MS Paint panel meme culture', e: 'community_subculture',
    o: '4chan & Reddit (2008-2014)', g: 'anglophone internet',
    p: '2008-2014', era: 'trollface to me-gusta boom and bust',
    sum: 'Derp faces tell daily failures: MS Paint panels as folk diaries.',
    desc: 'Rage comics (2008-2014) were the internet\'s folk-drawing age: four-to-eight-panel MS Paint strips using a shared cast — Trollface, FFFFUUUU Guy, Me Gusta, Forever Alone, Derp & Derpina — to narrate small humiliations and small victories of everyday internet life. The faces were reusable memes with standardized emotional payloads; the grammar (build-up, rage-quit panel, "le" epic narration) was community-enforced. Reddit\'s f7u12 and 4chan bred thousands daily before the format aged into cringe and then into nostalgia. Its legacy: proof that meme templates could function as a distributed comic language, and the direct ancestor of today\'s Wojak dialogue comics.',
    col: [{ h: '#141414', n: 'paint-line black' }, { h: '#f2efe4', n: 'canvas white' }, { h: '#c93636', n: 'rage red panel' }, { h: '#7fd45f', n: 'me-gusta green' }],
    m: ['MS Paint brush', 'copy-paste face templates', 'four-panel grid discipline', 'image-macro hosting culture'],
    tx: ['crude brush wobble', 'copy-artifact decay', 'flat fill fields'],
    obj: ['trollface origin panel', 'FFFFUUUU rage panels', 'derp-and-derpina romances', 'forever-alone endings'],
    ex: ['Trollface (Whynne, 2008)', 'r/fffffffuuuuuuuuuuuu subreddit', 'Me Gusta & Forever Alone canon'],
    inf: ['4chan rage thread culture', 'newspaper strip formats', 'AIM away-message humor'], rel: ['Wojak & Doomer Visuals', 'Imageboard Visual Language', 'Surreal Memes'],
    src: [{ n: 'Wikipedia — Rage comic', u: 'https://en.wikipedia.org/wiki/Rage_comic', t: 'B' }, { n: 'Know Your Meme — rage comics entry', u: 'https://knowyourmeme.com', t: 'C' }],
    tg: ['ragecomics', 'memes', 'trollface', 'mspaint', '2010s', 'internet'],
    pop: 51, niche: false,
    vd: { shape: 'four-panel grids with face-specific emotion', line: 'wobbly single-weight strokes', composition: 'setup-rage-punchline rhythm', texture: 'flat fills, brush wobble' },
    typ: { display: 'all-caps FFFFUUUU bursts', body: 'comic sans ironically-then-sincerely', notes: 'le-narration as dialect' },
    lit: { quality: 'flat screen emission', temperature: 'neutral-toned', shadow: 'none — faces are flat truth' },
    ui: { background: 'canvas white', surface: 'four-panel cards', components: 'face-picker meme chips', motion: 'rage-shake on fail' },
    par: 'internet folk cultures',
  },
  {
    n: 'Surreal Meme Culture', a: ['surreal memes', 'schrödinger memes', 'void memes', 'abstract meme art'],
    cat: 'Internet Aesthetic', c: 'absurdist dimension-bending meme genre', e: 'community_subculture',
    o: 'Tumblr & Reddit r/surrealmemes (2015-)', g: 'internet-native, anglophone + global',
    p: '2015-present', era: 'post-ironic meme abstraction wave',
    sum: 'Meme Man floats through non-Euclidean dread: humor after meaning broke.',
    desc: 'Surreal memes are the internet\'s absurdism proper: Meme Man (the smooth 3D head), geometric beings, impossible spaces, distorted typography ("stonks", "succ") and non-Euclidean dread rendered in bad-CGI and dream logic. Emerging mid-2010s from Tumblr and Reddit (r/surrealmemes, 2015+), the genre replaced relatable humor with dimensional wrongness — comedy for a generation fluent in post-irony. Its visual toolkit (bad renders, stock-corpse 3D objects, unicode mangling, cosmic voids) influenced glitch art, vaporwave\'s weirder cousins and the "weirdcore/dreamcore" family, while Meme Man became one of the internet\'s central mascots.',
    col: [{ h: '#141414', n: 'void black' }, { h: '#c9a0dc', n: 'wrong-purple' }, { h: '#e8c14a', n: 'stonks-chart gold' }, { h: '#f2efe4', n: 'render plastic white' }],
    m: ['low-poly 3D renders', 'photo-distortion tools', 'unicode typography abuse', 'cosmic void backgrounds'],
    tx: ['plastic render sheen', 'compression decay', 'dimension-warp stretch'],
    obj: ['meme man head renders', 'stonks chart panels', 'void-doorway scenes', 'uncanny stock-object collages'],
    ex: ['Meme Man Stonks format (2017-)', 'r/surrealmemes canon', 'Dimensional surrealist comic strips'],
    inf: [' Rene Magritte absurdism', 'early flash animation weirdness', 'heavypainting CG kit tradition'], rel: ['Weirdcore Visuals', 'Wojak & Doomer Visuals', 'Vaporwave'],
    src: [{ n: 'Wikipedia — Internet meme', u: 'https://en.wikipedia.org/wiki/Internet_meme', t: 'B' }, { n: 'r/surrealmemes community', u: 'https://www.reddit.com/r/surrealmemes', t: 'C' }],
    tg: ['surreal', 'memes', 'void', 'absurd', 'mememan', 'internet'],
    pop: 42, niche: false,
    vd: { shape: 'impossible geometry with floating heads', line: 'render-edge softness', composition: 'void-centered wrongness', texture: 'plastic 3D, compression mush' },
    typ: { display: 'mangled unicode headlines', body: 'broken-grammar captions', notes: 'misspelling as artform' },
    lit: { quality: 'flat void emission', temperature: 'neutral-toned', shadow: 'CG shadows that lie' },
    ui: { background: 'void gradient', surface: 'plastic-render cards', components: 'stonks-arrow meters', motion: 'dimension-glitch jumps' },
    par: 'internet folk cultures',
  },
  {
    n: 'Imageboard Visual Language', a: ['imageboard culture', 'greentext', '2channel style', 'anonymous posting art'],
    cat: 'Internet Aesthetic', c: 'anonymous forum text-and-image culture', e: 'community_subculture',
    o: '2channel Japan (1999), 4chan anglosphere (2003)', g: 'japan-derived global forums',
    p: '1999-present', era: '2channel ASCII era to 4chan visual canon',
    sum: 'Greentext, ASCII art and anonymity: the web\'s most influential subculture engine.',
    desc: 'Imageboard culture — 2channel\'s Japanese anonymous BBS tradition (1999) and 4chan\'s image-board adaptation (2003) — created the internet\'s most productive visual-language lab: greentext storytelling (">be me" narrative dialect), ASCII/Shift_JIS art (Mona), reaction-image repertoires, character memes (Pedobear, longcat, Pepe\'s origin), and anonymous collective authorship that spawns and kills memes in days. Its aesthetics — compressed JPEGs, saved-and-resaved decay, tripcodes, "[s4s]" meta-irony — are vernacular modernism of the anonymous web. 4chan alone birthed Anonymous, lolcats, rage comics and Wojak; the culture\'s dual legacy (creative engine + toxicity engine) makes it the internet\'s most studied folk space.',
    col: [{ h: '#7fd45f', n: 'greentext green' }, { h: '#f2efe4', n: 'yotsuba cream' }, { h: '#c93636', n: 'post-number red' }, { h: '#141414', n: 'anonymous black' }],
    m: ['greentext quoting systems', 'Shift_JIS ASCII fonts', 'thread reply-chains', 'image rehost pipelines'],
    tx: ['JPEG artifact decay', 'monospace rhythm', 'reply-nest depth'],
    obj: ['greentext story posts', 'ASCII art murals (Mona, giko)', 'reaction image libraries', 'get-thread celebrations'],
    ex: ['4chan /b/ meme factories', '2channel Mona ASCII canon', 'Pepe\'s /co/ origin (2008)'],
    inf: ['Japanese otaku BBS culture', 'usenet anonymous tradition', 'UNIX text aesthetics'], rel: ['Rage Comic Era', 'Wojak & Doomer Visuals', 'Old Web GeoCities Era'],
    src: [{ n: 'Wikipedia — Imageboard', u: 'https://en.wikipedia.org/wiki/Imageboard', t: 'B' }, { n: 'Know Your Meme — greentext', u: 'https://knowyourmeme.com', t: 'C' }],
    tg: ['imageboard', 'greentext', 'anonymous', '4chan', 'ascii', 'internet'],
    pop: 40, niche: true,
    vd: { shape: 'reply-chain text walls with inline art', line: 'monospace vertical rhythm', composition: 'thread-as-canvas accumulation', texture: 'JPEG mush, cream board tint' },
    typ: { display: 'greentext quote styling', body: 'monospace post text', notes: 'the > is a literary device' },
    lit: { quality: 'flat board emission', temperature: 'neutral-toned', shadow: 'none — text all the way down' },
    ui: { background: 'yotsuba cream', surface: 'thread-reply cards', components: 'greentext lines', motion: 'reply-nest indentation' },
    par: 'internet folk cultures',
  },
  {
    n: 'Tracker & Chiptune Scene', a: ['tracker music', 'chiptune scene', 'mod music', 'demoscene audio'],
    cat: 'Music & Sonic Culture', c: 'chip-sound tracker music culture', e: 'community_subculture',
    o: 'Amiga ProTracker culture (1987-)', g: 'Europe demoscene, global game audio',
    p: '1987-present', era: 'Amiga MOD era to chiptune revival',
    sum: 'Four channels and forever: music written as data, played by chips.',
    desc: 'Tracker music culture grew from ProTracker on the Amiga (1987): musicians composing as pattern data — 4 channels of samples, hex commands, no overdubs — traded freely as MOD/S3M/XM files through scene channels,FTP archives and demoparty competitions. The sound (chunky samples, arpeggiated leads, chip-fried drums) defined 8/16-bit game audio, demoscene soundtracks and the netmusic underground (ModArchive, Mik seri). The 2000s revival turned chiptune into performance culture (Chipzel, Sabrepulse, 8bitpeoples label, Blip Festival) with real Game Boys (LSDJ software) on stage; tracker grammar quietly persists inside DAWs and the demoscene\'s 64k soundtracks.',
    col: [{ h: '#00e676', n: 'tracker green waves' }, { h: '#141414', n: 'pattern editor black' }, { h: '#e8c14a', n: 'arp lead gold' }, { h: '#2979ff', n: 'sample blue' }],
    m: ['ProTracker / FastTracker software', 'Amiga & Game Boy hardware', 'sample pack trade culture', 'hex effect commands'],
    tx: ['square-wave grit', 'sample-loop grain', 'pattern-grid rhythm'],
    obj: ['pattern-editor screens', 'LSDJ game boy carts', 'modfile archives', 'blip-festival stage rigs'],
    ex: ['ProTracker module classics (Elwood, Jogeir)', 'Blip Festival NYC (2006-2012)', 'Chipzel Super Hexagon score'],
    inf: ['demoscene party competition', '8-bit console sound chips', 'net-artist file-sharing ethos'], rel: ['Demoscene', 'Amiga Bitmap Culture', 'Arcade Cabinet Culture'],
    src: [{ n: 'Wikipedia — Tracker (music software)', u: 'https://en.wikipedia.org/wiki/Tracker_(music_software)', t: 'B' }, { n: 'ModArchive — module archive', u: 'https://modarchive.org', t: 'C' }],
    tg: ['chiptune', 'tracker', 'amiga', '8bit', 'music', 'demoscene'],
    pop: 39, niche: true,
    vd: { shape: 'pattern-grid hex walls', line: 'channel-row striping', composition: 'tracker vertical timeline', texture: 'square-wave edge, sample grain' },
    typ: { display: 'module-file name caps', body: 'sample-list hex tables', notes: 'music you can read as text' },
    lit: { quality: 'CRT monitor glow', temperature: 'cool-toned', shadow: 'pattern-row highlight bands' },
    ui: { background: 'editor black', surface: 'pattern-grid cards', components: 'channel toggles', motion: 'row-cursor playback scan' },
    par: 'digital music cultures',
  },
  {
    n: 'Graffiti Writing Culture', a: ['graffiti', 'writing culture', 'throw-ups', 'street bombing'],
    cat: 'Regional & Cultural Tradition', c: 'aerosol name-writing subculture', e: 'community_subculture',
    o: 'Philadelphia & New York subway yards (late 1960s-70s)', g: 'global urban culture',
    p: '1967-present', era: 'TAKI 183 era to global gallery dual-career',
    sum: 'The name is the art: 50,000-year-old handstyles updated in aerosol.',
    desc: 'Graffiti writing — TAKI 183\'s 1971 New York Times fame canonized it — evolved from tag signatures to throw-ups to blockbuster whole-cars, inventing a complete technical culture: blackbooks, sketch exchanges, crew hierarchy, the crew-vs-crew "beef", and the ladder of fame (tags → throwies → pieces → productions). Its visual science: letter structure, color theory (3-color fade canons), wildstyle interlock, and the handstyle that graffiti writers consider the soul. Museums now collect what transit police sandblasted; Basquiat and Haring crossed over from the street; the culture\'s language (burner, king, toy, buff) spread worldwide while remaining earned-only — you can\'t buy your way in.',
    col: [{ h: '#e8c14a', n: 'fill yellow' }, { h: '#c93636', n: 'outline red' }, { h: '#141414', n: 'shadow black' }, { h: '#2979ff', n: 'bomb blue' }, { h: '#f2efe4', n: 'highlight white' }],
    m: ['aerosol caps (skinny-fat-wide)', 'mop markers & ink', 'blackbook sketchbooks', 'scaffolding courage'],
    tx: ['aerosol fade gradients', 'drip-edge honesty', 'steel-rail scuff patina'],
    obj: ['whole-car subway murals', 'handstyle tag runs', 'wildstyle interlocks', 'blackbook sketch trades'],
    ex: ['TAKI 183 NYT feature (1971)', 'Style Wars (1983) documentary', 'Bushwick Collective walls'],
    inf: ['gang territorial marking', 'Philadelphia cornbread era', 'hip-hop culture synthesis'], rel: ['Hip Hop Visual Culture', 'Afropunk Style', 'Neubrutalism Web Style'],
    src: [{ n: 'Wikipedia — Graffiti', u: 'https://en.wikipedia.org/wiki/Graffiti', t: 'B' }, { n: '149st crew — writing history archive', u: 'https://www.at149st.com', t: 'C' }],
    tg: ['graffiti', 'aerosol', 'street', 'hiphop', 'letters', 'urban'],
    pop: 66, niche: false,
    vd: { shape: 'letter-structure as architecture', line: 'outline-shadow-highlight triads', composition: 'piece-first, wall-as-frame', texture: 'aerosol fade, drip edges' },
    typ: { display: 'handstyle as signature calligraphy', body: 'throw-up bubble fills', notes: 'the tag is the artist' },
    lit: { quality: 'rail-yard sodium night', temperature: 'warm-toned', shadow: 'piece-shadow drop on brick' },
    ui: { background: 'concrete grey', surface: 'wall-piece cards', components: 'cap-swatch selectors', motion: 'tag-write stroke animation' },
    par: 'urban visual cultures',
  },
  {
    n: 'Hip Hop Visual Culture', a: ['hip hop aesthetics', 'b-boy style', 'album cover culture', 'golden era visuals'],
    cat: 'Music & Sonic Culture', c: 'hip hop\'s visual design tradition', e: 'community_subculture',
    o: 'Bronx block parties (1973-)', g: 'global music culture',
    p: '1973-present', era: 'DJ Kool Herc block era to global dominance',
    sum: 'Boom boxes, adidas laces and Pen & Pixel covers: the culture\'s 50-year visual archive.',
    desc: 'Hip hop\'s visual culture is as canonical as its music: 1970s Bronx foundations (adidas shell-toes with fat laces, Kangol, boombox-as-portrait), 80s graffiti-album synergies (Fab 5 Freddy, Blitz\'s Beastie graphics), golden-era photography (Ernie Paniccioli, Ricky Powell), 90s regional costume codes (West Coast Dickies-and-Cortez, Southern grill-and-Boot), and the extremities of Pen & Pixel\'s Houston airbrush covers — cars, diamonds, literally everything. Design lineage: flyer culture (Buddy Esquire), the Source-era typography, and today\'s merchandise-as-fashion houses. Every element — the cipher photo, the chain shot, the blockwide panorama — codified how youth culture photographs itself.',
    col: [{ h: '#141414', n: 'track-jacket black' }, { h: '#e8c14a', n: 'chain gold' }, { h: '#c93636', n: 'flyer red' }, { h: '#2f7d4f', n: 'shell-toe green accent' }],
    m: ['airbrush & chrome lettering', 'flyer paste-up boards', 'golden-era film photography', 'jewelry as portraiture'],
    tx: ['airbrush chrome sheen', 'film-grain portrait', 'diamond-point sparkle'],
    obj: ['boombox shoulder portraits', 'cipher circle photos', 'Pen & Pixel cover collages', 'shell-toe lace rituals'],
    ex: ['Pen & Pixel album covers (Houston)', 'Ernie Paniccioli hip-hop photography', 'Wild Style (1983) visual world'],
    inf: ['graffiti writing culture', 'prison uniform adaptation', 'brand entrepreneurship arc'], rel: ['Graffiti Writing Culture', 'Dancehall Poster Art', 'Afropunk Style'],
    src: [{ n: 'Wikipedia — Hip hop culture', u: 'https://en.wikipedia.org/wiki/Hip_hop_culture', t: 'B' }, { n: 'Cornell University — Hip Hop Collection', u: 'https://www.library.cornell.edu', t: 'A' }],
    tg: ['hiphop', 'album art', 'bronx', 'fashion', 'music', 'culture'],
    pop: 70, niche: false,
    vd: { shape: 'crew-cipher circles and low-angle heroes', line: 'chrome-outline lettering', composition: 'blockwide group portraits', texture: 'airbrush sheen, film grain, gold sparkle' },
    typ: { display: 'chrome-and-graffiti album logotypes', body: 'flyer condensed caps', notes: 'the cover is the mixtape promise' },
    lit: { quality: 'block-party floodlight', temperature: 'warm-toned', shadow: 'bounce-flash portrait shadow' },
    ui: { background: 'asphalt dusk', surface: 'gold-chain cards', components: 'boombox-icon players', motion: 'turntable-scratch glitches' },
    par: 'urban visual cultures',
  },
  {
    n: 'Zine Photocopy Aesthetic', a: ['zines', 'photocopy aesthetic', 'cut-and-paste', 'xerox art'],
    cat: 'Graphic Design', c: 'photocopied DIY publication culture', e: 'community_subculture',
    o: 'punk scenes (1976-, Sniffin\' Glue, Slash)', g: 'global DIY scenes, riot grrrl, perzines',
    p: '1976-present', era: 'punk first wave to riot grrrl to digital zine renaissance',
    sum: 'Photocopier as press: glue, toner noise and 40 copies of the truth.',
    desc: 'The zine — cut-and-paste punk\'s native press (Sniffin\' Glue 1976, Slash, Maximumrocknroll) — built a 50-year aesthetic from the photocopier\'s flaws: degraded contrast, margin loss, crooked pasted letters, correction-fluid strokes, screentone photo crashes and hand-numbered editions. Riot grrrl (Bikini Kill, 1990s) turned the form feminist-punk canon; perzines, queerzines and fanzines kept it personal. The look — xerox noise as texture, ransom-note typography, band photo halftones — is now a deliberate style (every "DIY" brand poster), while zine libraries (Barnard Zine Library, Salford Zine Library) archive the originals as material culture of pre-internet networks.',
    col: [{ h: '#141414', n: 'toner black' }, { h: '#f2efe4', n: 'xerox paper white' }, { h: '#8a8378', n: 'photocopy grey noise' }, { h: '#c93636', n: 'marker red' }],
    m: ['photocopier degradation', 'scissors & glue sticks', 'correction fluid', 'long-arm staplers'],
    tx: ['toner noise texture', 'contrast-crush darks', 'paste-up seam shadows'],
    obj: ['half-letter folded booklets', 'ransom-note headlines', 'hand-numbered covers', 'mail-trade envelope art'],
    ex: ['Sniffin\' Glue (1976-77)', 'Bikini Kill zine (riot grrrl canon)', 'Barnard Zine Library collections'],
    inf: ['punk anti-commerce ethics', 'mail-art network culture', 'amateur press associations (pre-punk)'], rel: ['Hip Hop Visual Culture', 'Imageboard Visual Language', 'Dancehall Poster Art'],
    src: [{ n: 'Wikipedia — Zine', u: 'https://en.wikipedia.org/wiki/Zine', t: 'B' }, { n: 'Barnard Zine Library', u: 'https://zines.barnard.edu', t: 'A' }],
    tg: ['zine', 'photocopy', 'diy', 'punk', 'print', 'riot grrrl'],
    pop: 43, niche: false,
    vd: { shape: 'half-letter folded page blocks', line: 'ransom-note cut edges', composition: 'dense two-column DIY chaos', texture: 'toner noise, paste seams' },
    typ: { display: 'ransom-note mixed cutouts', body: 'typewriter + handwriting mix', notes: 'illegibility is authenticity' },
    lit: { quality: 'copy-shop flatness', temperature: 'neutral-toned', shadow: 'photocopier eats shadows' },
    ui: { background: 'xerox grey', surface: 'folded-page cards', components: 'staple-mark accents', motion: 'page-croak flips' },
    par: 'DIY print cultures',
  },
  {
    n: 'Wojak & Doomer Visuals', a: ['wojak', 'feels guy', 'doomer', 'NPC meme'],
    cat: 'Internet Aesthetic', c: 'line-drawn emotional meme family', e: 'community_subculture',
    o: 'imageboards & Krautchan (2010)', g: 'global internet meme culture',
    p: '2010-present', era: 'feels guy to doomer-verse expansion',
    sum: 'One sad MS Paint face, ten thousand moods: the internet\'s emotional alphabet.',
    desc: 'Wojak ("feels guy", originated Krautchan 2010) became the internet\'s emotional shorthand: a bald line-drawn figure whose variants map entire worldviews — doomer (black hoodie, existential dread), bloomers (post-doomer hope), coomer, NPC (grey conformism), soyjak (excitable mockery), tradwife, zoomer — each a ready-made character for forum psychodrama. The doomer-verse extended into full comic genres (doomer girl romance arcs) and the "wojak compass" template where memes self-organize into ideological charts. As visual culture: a folk character system as expressive as theater masks, constantly recombined, occasionally poisoned by its political uses, and never done spawning variants.',
    col: [{ h: '#141414', n: 'line-drawn black' }, { h: '#f2efe4', n: 'canvas pale' }, { h: '#3a3a3a', n: 'doomer hoodie grey' }, { h: '#7fd45f', n: 'bloomer green' }],
    m: ['MS Paint line tools', 'variant-template sharing', 'compass-chart layouts', 'imageboard repost culture'],
    tx: ['wobbly line vulnerability', 'flat fill gloom', 'copy-generation decay'],
    obj: ['feels guy origin face', 'doomer hoodie portraits', 'NPC grey masks', 'wojak political compass charts'],
    ex: ['Krautchan feels guy origin (2010)', 'r/doomer & doomer wave (2019)', 'soyjak.party variant ecosystem'],
    inf: ['rage comic ancestry', 'imageboard character evolution', 'political compass chart format'], rel: ['Rage Comic Era', 'Imageboard Visual Language', 'Surreal Meme Culture'],
    src: [{ n: 'Wikipedia — Wojak', u: 'https://en.wikipedia.org/wiki/Wojak', t: 'B' }, { n: 'Know Your Meme — Wojak family', u: 'https://knowyourmeme.com', t: 'C' }],
    tg: ['wojak', 'doomer', 'memes', 'faces', 'internet', 'feelsguy'],
    pop: 55, niche: false,
    vd: { shape: 'minimal round-head figures with mood props', line: 'single-weight wobble contours', composition: 'character-chart panel staging', texture: 'flat fill, line wobble' },
    typ: { display: 'Impact meme captions', body: 'lowercase despair text', notes: 'the face carries, text confirms' },
    lit: { quality: 'flat screen emission', temperature: 'cool-toned', shadow: 'hatched cheek-shadow moods' },
    ui: { background: 'canvas pale', surface: 'face-variant cards', components: 'mood-picker chips', motion: 'subtle tremble idle loops' },
    par: 'internet folk cultures',
  },
]