/**
 * Interiors wave 12 — 12 real interior design styles for Aesthetic Atlas.
 * All names verified against existing-names.txt for collisions; Wikipedia source URLs checked live (HTTP 200).
 */
export const ENTRIES: any[] = [
  {
    n: 'Shoin-zukuri Interiors', a: ['Shoin style interiors', 'Shoin-zukuri', '書院造'],
    cat: 'Interior Design', c: 'Formal Japanese residential interior tradition', e: 'historical',
    o: 'Muromachi-period Japan', g: 'Japan (Zen monasteries to samurai residences, later homes nationwide)', p: '14th century-present', era: 'Muromachi & Momoyama Japan onward',
    sum: 'The formal Japanese zashiki interior: tiered tatami floors, tokonoma display alcoves, chigaidana staggered shelves and built-in shoin writing desks facing the garden.',
    desc: 'Shoin-zukuri (書院造) codified the Japanese residential interior from Muromachi-period Zen halls and samurai palaces. Its fixed grammar — tiered tatami seating by rank, the recessed tokonoma alcove for scrolls and flowers, staggered chigaidana shelves and built-in tsukeshoin writing desks — defined how rooms were composed and honoured. From it descend the tea room, the modern washitsu and the display niche in Japanese rooms.',
    col: [{ h: '#9aa66a', n: 'tatami rush green' }, { h: '#f3efe2', n: 'shoji paper white' }, { h: '#4a3320', n: 'dark paulownia brown' }, { h: '#2b2b2b', n: 'alcove charcoal' }, { h: '#a63a2a', n: 'seal vermilion accent' }],
    m: ['woven rush tatami mats', 'planed cypress (hinoki) joinery', 'paulownia shelving wood', 'papered shoji and fusuma panels'],
    tx: ['tight twill rush weave', 'satin hand-planed timber', 'backlit paper glow'],
    obj: ['tokonoma display alcoves', 'chigaidana staggered shelves', 'tsukeshoin writing desks', 'painted fusuma panels', 'ranma transom grilles'],
    ex: ['Ginkaku-ji Togudo with oldest extant tsukeshoin', 'Nijo Castle Ninomaru Palace rooms', 'Katsura Imperial Villa shoin interiors'],
    inf: ['Zen temple architecture', 'Chanoyu tea aesthetics', 'Chinese Song scholar studios'],
    rel: ['Wabi-sabi', 'Japandi', 'Wabi-cha'],
    src: [{ n: 'Wikipedia — Shoin-zukuri', u: 'https://en.wikipedia.org/wiki/Shoin-zukuri', t: 'B' }, { n: 'Kyoto National Museum', u: 'https://www.kyohaku.go.jp', t: 'A' }],
    tg: ['tatami', 'tokonoma', 'alcove', 'shoin', 'zen', 'japanese interior', 'samurai'],
    pop: 48, niche: true,
    vd: { shape: 'rectilinear bays with a deep vertical alcove accent', line: 'clean post-and-beam horizontals', composition: 'asymmetric alcove focal wall in an otherwise ordered grid', texture: 'rush mat grain against smooth planed wood' },
    typ: { display: 'hanging scroll and calligraphy in the tokonoma', body: 'vertical scroll inscriptions as room centerpiece', notes: 'the alcove composition itself is typographic in intent' },
    lit: { quality: 'soft diffused shoji daylight', temperature: 'neutral-warm', shadow: 'deep quiet alcove shadow, deliberate' },
    ui: { background: 'warm paper white', surface: 'tatami-toned cards with alcove accent blocks', components: 'thin-line framed buttons like kumiko grids', motion: 'slow sliding-panel transitions' },
  },
  {
    n: 'Maximalist Interior Styling', a: ['Maximalist decor', 'More-is-more styling'],
    cat: 'Interior Design', c: 'Deliberately abundant, layered interior styling', e: 'commercial_style',
    o: 'International (2010s design press)', g: 'Global urban markets', p: '1960s-80s roots; 2010s-present revival', era: 'Post-minimalism to present',
    sum: 'Interior styling that embraces abundance: saturated color, pattern-on-pattern, gallery walls, layered rugs and curated clutter against minimalist restraint.',
    desc: 'Maximalist interiors compose abundance deliberately: saturated palettes, pattern-on-pattern upholstery, gallery walls, layered rugs and collections shown en masse. Roots run through Victorian opulence, 1980s postmodernism and Memphis; the mid-2010s revival opposed spare Scandinavian minimalism. Unlike hoarding, it is curated excess — color stories, repetition and zoning hold the density together as personal, autobiographical display.',
    col: [{ h: '#1f6f54', n: 'emerald green' }, { h: '#4a2a52', n: 'aubergine' }, { h: '#c99a2e', n: 'mustard' }, { h: '#186a72', n: 'peacock teal' }, { h: '#9b2335', n: 'jewel ruby' }],
    m: ['velvet upholstery', 'patterned wallpaper', 'brass and colored glass', 'layered rugs and textiles'],
    tx: ['crushed velvet nap', 'high-gloss lacquer', 'fringed tassel'],
    obj: ['salon-style gallery walls', 'overfull display shelving', 'velvet sofas', 'color-drenched ceilings', 'plant clusters'],
    ex: ['Memphis-influenced 1980s interiors', '2010s maximalism features in design press', 'contemporary dark "moody maximalist" rooms'],
    inf: ['Victorian clutter traditions', 'Memphis Design', 'Chinoiserie collecting'],
    rel: ['Cluttercore', 'Cluttercore Aesthetic', 'Memphis Design'],
    src: [{ n: 'Wikipedia — Maximalism', u: 'https://en.wikipedia.org/wiki/Maximalism', t: 'B' }, { n: 'Victoria & Albert Museum', u: 'https://www.vam.ac.uk', t: 'A' }],
    tg: ['more is more', 'gallery wall', 'pattern mixing', 'color drenching', 'eclectic', 'collection'],
    pop: 74, niche: false,
    vd: { shape: 'full-bleed walls with no negative space', line: 'mixed contradictory contours', composition: 'layered density organized by color story', texture: 'plush, glossy and patterned stacked' },
    typ: { display: 'framed prints, posters and objects dense as type-blocks', body: 'book spines and posters as texture', notes: 'lettering lives in the collected objects' },
    lit: { quality: 'rich layered pools with accents', temperature: 'warm', shadow: 'deep corners embraced, not hidden' },
    ui: { background: 'saturated jewel gradient', surface: 'pattern-clash cards', components: 'brass-rimmed buttons with mixed shapes', motion: 'playful overlapping slides' },
  },
  {
    n: 'Hollywood Regency', a: ['Regency glamour style', 'Hollywood glam'],
    cat: 'Interior Design', c: 'Glamorous film-set revival interior style', e: 'historical',
    o: 'Hollywood, Los Angeles, USA', g: 'United States, later global', p: '1930s-1960s; 2000s revival', era: 'Golden Age Hollywood to present',
    sum: 'High-drama film-set glamour in interiors: mirrored furniture, chinoiserie motifs, lacquer, oversized chandeliers and gold-and-silver glitz staged like a movie set.',
    desc: 'Hollywood Regency grew from the 1930s-60s as decorators and ex-set designers — William Haines, Dorothy Draper, Tony Duquette — built theatrical homes for star clients: lacquer, faux bamboo, mirrored consoles, pagoda motifs and big chandeliers. It borrowed Regency silhouettes and chinoiserie but staged all for drama, mixing periods with set-design confidence. The 2000s glam revival led by Kelly Wearstler made it shorthand for high-contrast luxury.',
    col: [{ h: '#141414', n: 'lacquer black' }, { h: '#c9ccd1', n: 'mirror silver' }, { h: '#c9a227', n: 'gold leaf' }, { h: '#2e7d63', n: 'chinoiserie jade' }, { h: '#e8b7b0', n: 'blush satin' }],
    m: ['mirrored and chrome furniture', 'high-gloss lacquer surfaces', 'brass and gold leaf', 'satin and tufted velvet'],
    tx: ['mirror-polished flatness', 'piano-lacquer gloss', 'plush button tufting'],
    obj: ['mirrored console tables', 'faux-bamboo frames', 'oversized chandeliers', 'pagoda-motif cabinetry', 'shell and grotto seats'],
    ex: ['Dorothy Draper Greenbrier hotel interiors', 'William Haines homes for star clients', 'Tony Duquette stage-set rooms'],
    inf: ['Art Deco', 'Chinoiserie', 'Baroque Revival'],
    rel: ['Art Deco', 'Baroque Revival', 'Chinoiserie Panel Lacquer Painting'],
    src: [{ n: 'Wikipedia — Hollywood Regency', u: 'https://en.wikipedia.org/wiki/Hollywood_Regency', t: 'B' }, { n: 'Los Angeles County Museum of Art', u: 'https://www.lacma.org', t: 'A' }],
    tg: ['glam', 'lacquer', 'mirrored', 'draper', 'chinoiserie', 'golden age', 'theatrical'],
    pop: 66, niche: false,
    vd: { shape: 'swelling Regency curves with pagoda accents', line: 'sharp gilt contours on gloss', composition: 'symmetrical theatrical staging, one hero piece per wall', texture: 'hard shine over plush' },
    typ: { display: 'monograms and glamorous sans-serif labels in gilt', body: 'high-contrast script headlines', notes: 'ornament borrowed from film title cards' },
    lit: { quality: 'high specular sparkle and pools', temperature: 'warm', shadow: 'black lacquer shadows used as contrast' },
    ui: { background: 'black or blush lacquer field', surface: 'mirrored panel cards', components: 'gilt-outlined buttons, tufted dividers', motion: 'confident spotlight sweeps' },
  },
  {
    n: 'Shabby Chic', a: ['Shabby chic style', 'Rachel Ashwell style'],
    cat: 'Interior Design', c: 'Distressed-cottage comfort interior style', e: 'commercial_style',
    o: 'United Kingdom / United States', g: 'UK, USA, global retail', p: '1980s-present', era: 'Late 20th-century revival to present',
    sum: 'Romantic cottage interiors built from whitewashed, comfortably distressed furniture, faded florals, linen slipcovers and flea-market patina.',
    desc: 'Shabby Chic — trademarked by Rachel Ashwell in 1989 — turned aged, paint-worn country furniture into a marketable look: chipped finishes, linen slipcovers, faded rose florals and mismatched china. Rooted in English cottage thrift and French provincial style, it prized softness, imperfection and "beautiful use" over polish. Mass retail spread the whitewashed look in the 1990s-2000s, and its reuse-driven values feed today\'s cottagecore.',
    col: [{ h: '#f1ede2', n: 'chalk white' }, { h: '#dfb2b4', n: 'rose pink' }, { h: '#a8b092', n: 'faded sage' }, { h: '#d9cfb8', n: 'linen oatmeal' }, { h: '#9b968c', n: 'putty gray' }],
    m: ['whitewashed chippy-painted wood', 'washed linen slipcovers', 'rose-print cottons', 'vintage lace and linens'],
    tx: ['chipped paint edge', 'stonewashed softness', 'faded floral print'],
    obj: ['slipcovered sofas', 'painted farmhouse tables', 'vintage floral cushions', 'mismatched china displays', 'wired storage baskets'],
    ex: ['Rachel Ashwell Shabby Chic Couture stores', '1990s English cottage interiors', 'flea-market "finds" styling features'],
    inf: ['English cottage furnishing', 'French provincial furniture', 'flea-market reuse culture'],
    rel: ['Cottagecore', 'Cottage core', 'Modern Farmhouse'],
    src: [{ n: 'Wikipedia — Shabby chic', u: 'https://en.wikipedia.org/wiki/Shabby_chic', t: 'B' }, { n: 'Victoria & Albert Museum', u: 'https://www.vam.ac.uk', t: 'A' }],
    tg: ['whitewash', 'florals', 'cottage', 'distressed', 'ashwell', 'slipcover'],
    pop: 68, niche: false,
    vd: { shape: 'soft rounded country silhouettes', line: 'gentle faded edges, no hard rules', composition: 'airy layering with breathing room between groups', texture: 'worn paint over washed cloth' },
    typ: { display: 'handwritten price tags and script labels', body: 'soft serif or script typefaces', notes: 'lettering kept loose and romantic' },
    lit: { quality: 'hazy bright daylight', temperature: 'warm', shadow: 'soft, lifted, low contrast' },
    ui: { background: 'chalk white with rose tint', surface: 'washed linen-texture cards', components: 'rounded petal-toned buttons', motion: 'gentle cross-fades' },
  },
  {
    n: 'French Country Style', a: ['French provincial style', 'Provençal style', 'Campagne chic'],
    cat: 'Interior Design', c: 'Rural French provincial interior tradition', e: 'regional_tradition',
    o: 'Rural France (Provence, Normandy, Dordogne)', g: 'France; strong export to US and UK decorating', p: '17th century-present', era: 'Ancien Régime provinces to present',
    sum: 'Warm rural French interiors: terracotta floors, lime-washed walls, distressed painted armoires, toile de Jouy, hanging copper and lavender-olive palettes.',
    desc: 'French country style distills furnished provincial homes of France — Provençal farmhouses and Dordogne kitchens. Its ingredients are practical luxuries: terracotta floors, lime-washed walls, painted armoires, toile de Jouy cottons, ladder-back chairs and copper pots. Provincial cabinetmakers translated Louis XV curves into sturdier country forms, giving the style its rustic-elegant balance that 20th-century decorating books exported worldwide.',
    col: [{ h: '#9b8ec4', n: 'lavender' }, { h: '#c8912f', n: 'warm ochre' }, { h: '#7a8450', n: 'olive green' }, { h: '#b26a3f', n: 'terracotta' }, { h: '#ece3cd', n: 'aged cream' }],
    m: ['lime plaster and stone walls', 'terracotta floor tiles', 'painted oak and fruitwood', 'toile de Jouy and Provençal cottons'],
    tx: ['lime-wash chalkiness', 'worn terracotta polish', 'scratched paint patina'],
    obj: ['painted armoires', 'ladder-back rush chairs', 'hanging copper pots', 'faience pottery', 'toile curtains'],
    ex: ['Provençal farmhouse kitchens', 'Norman manor interiors', 'Louis XV-derived provincial case furniture'],
    inf: ['Louis XV provincial furniture', 'Mediterranean courtyard living', 'regional faience potteries'],
    rel: ['Modern Farmhouse', 'Tuscan Decor', 'Tuscan Kitchen Terracotta'],
    src: [{ n: 'Wikipedia — French Provincial architecture', u: 'https://en.wikipedia.org/wiki/French_Provincial_architecture', t: 'B' }, { n: 'The Metropolitan Museum of Art', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['toile', 'provence', 'terracotta', 'provincial', 'farmhouse', 'lime wash', 'copper'],
    pop: 63, niche: false,
    vd: { shape: 'cabriole curves softened by country weight', line: 'hand-drawn irregular contour', composition: 'centered hearth or dresser, symmetrical warmth', texture: 'chalky paint over aged wood and tile' },
    typ: { display: 'script bistro and menu lettering', body: 'old-style serif typefaces', notes: 'hand-painted shop and pantry labels' },
    lit: { quality: 'golden directional sun', temperature: 'warm', shadow: 'soft beam-shadow under beams' },
    ui: { background: 'aged cream paper', surface: 'ochre-washed cards with tile motifs', components: 'olive and terracotta rounded buttons', motion: 'unhurried fade-and-slide' },
  },
  {
    n: 'English Country House Style', a: ['The country house look', 'English house style'],
    cat: 'Interior Design', c: 'Layered aristocratic British interior tradition', e: 'regional_tradition',
    o: 'England', g: 'United Kingdom; strong influence in the US', p: '17th century-present', era: 'Georgian & Victorian country houses to present',
    sum: 'The layered English country-house look: ancestral portraits, glazed chintz, dark oil paintings, book overflow, fireside leather and furniture accumulated over generations.',
    desc: 'English country house style is less a formula than an accumulation: dark-panelled halls, ancestral portraits, chintz-covered chairs, giltwood mirrors, libraries and worn leather by the fire. Postwar decorators — John Fowler of Colefax and Fowler with Nancy Lancaster — codified its "shabby grandeur" as flower-filled, faded rooms. Its signal virtue is provenance: things inherited, mended and layered, the archetype heritage decorating borrows.',
    col: [{ h: '#8c3b2e', n: 'brick red' }, { h: '#5d6b48', n: 'chintz green' }, { h: '#5b4327', n: 'dark oak brown' }, { h: '#c2a14d', n: 'gilt gold' }, { h: '#e6dcc3', n: 'warm parchment' }],
    m: ['dark oak panelling', 'glazed chintz and damask', 'Turkey and Axminster carpets', 'leather and giltwood'],
    tx: ['worn leather nap', 'glazed chintz sheen', 'scumbled giltwood'],
    obj: ['ancestral portrait walls', 'chintz slipcovers', 'library shelves and steps', 'four-poster beds', 'fireside wing chairs'],
    ex: ['Colefax and Fowler drawing rooms', 'Nancy Lancaster\'s Mayfair office rooms', 'National Trust country house interiors'],
    inf: ['Georgian furnishing', 'Victorian collecting culture', 'chintz trade cottons'],
    rel: ['Aesthetic Movement interior', 'Victorian interior', 'Cottagecore'],
    src: [{ n: 'Wikipedia — English country house', u: 'https://en.wikipedia.org/wiki/English_country_house', t: 'B' }, { n: 'The National Trust', u: 'https://www.nationaltrust.org.uk', t: 'A' }],
    tg: ['chintz', 'country house', 'portraits', 'library', 'heritage', 'grandeur'],
    pop: 58, niche: false,
    vd: { shape: 'deep room volumes with dense wall hangings', line: 'dark moulding outlines', composition: 'layered accumulation around a fireplace axis', texture: 'aged gilt, glaze and leather' },
    typ: { display: 'family nameboards, bookplates and heraldry', body: 'engraved serif inscriptions', notes: 'lettering belongs to portraits and spines' },
    lit: { quality: 'low lamp and fire glow', temperature: 'warm', shadow: 'rich brown corner shadow' },
    ui: { background: 'parchment and oak tones', surface: 'chintz-pattern framed cards', components: 'gilt-line buttons, damask fills', motion: 'measured, curtain-drawn reveals' },
  },
  {
    n: 'British West Indies Style', a: ['West Indies style', 'West Indian interiors'],
    cat: 'Interior Design', c: 'Tropical island interior style of the British Caribbean', e: 'regional_tradition',
    o: 'British Caribbean', g: 'Jamaica, Barbados, Antigua; later US resort and beach-house influence', p: '18th century-present', era: 'Sugar-colony era to resort present',
    sum: 'Cool tropical island interiors from the British Caribbean: dark hardwoods and rattan, louvered shutters, ceiling fans, white walls and cane furniture in sea light.',
    desc: 'British West Indies interiors answer heat, humidity and hurricanes: high ceilings, louvered shutters, deep verandas, hardwood floors with cane matting, and furniture of mahogany and rattan — Georgian forms adapted to the tropics, plus planter\'s chairs and four-poster beds with mosquito nets. White walls, ceiling fans and tropical botanicals complete the register; resort designers carried it into American beach houses as polished tropical comfort.',
    col: [{ h: '#f2efe6', n: 'plantation white' }, { h: '#5e3a22', n: 'mahogany brown' }, { h: '#c8a878', n: 'rattan tan' }, { h: '#2e7f86', n: 'sea teal' }, { h: '#6f8f5a', n: 'fern green' }],
    m: ['mahogany and greenheart hardwoods', 'woven rattan and cane', 'louvered jalousie shutters', 'cotton mosquito netting'],
    tx: ['slatted louver rhythm', 'polished tropical hardwood', 'open-weave cane'],
    obj: ['louvered shutter walls', 'planter\'s chairs', 'hanging cane chairs', 'ceiling fans', 'four-poster net beds'],
    ex: ['Jamaican great-house interiors', 'Barbados chattel-house revivals', 'Caribbean resort veranda suites'],
    inf: ['Georgian furniture adapted to the tropics', 'Caribbean craft weaving', 'tropical resort design'],
    rel: ['Tropicalismo', 'Palm Springs Modern', 'Balinese Architecture'],
    src: [{ n: 'Wikipedia — British West Indies', u: 'https://en.wikipedia.org/wiki/British_West_Indies', t: 'B' }, { n: 'Caribbean Tourism Organization', u: 'https://www.onecaribbean.org', t: 'C' }],
    tg: ['tropical', 'louvered', 'rattan', 'caribbean', 'veranda', 'island', 'mahogany'],
    pop: 55, niche: true,
    vd: { shape: 'tall airy volumes with horizontal louver bands', line: 'crisp white trim against dark wood', composition: 'cross-ventilated symmetry opening to veranda', texture: 'hardwood sheen with open cane weave' },
    typ: { display: 'engraved estate and hotel signage', body: 'colonial-era serif inscriptions', notes: 'lettering on brass and painted signs' },
    lit: { quality: 'bright filtered tropical daylight', temperature: 'cool-warm mix', shadow: 'crisp louver shadow stripes' },
    ui: { background: 'plantation white', surface: 'cane-weave textured cards', components: 'teal and mahogany slatted buttons', motion: 'fan-blade rotation cues' },
  },
  {
    n: 'Gilded Age Interiors', a: ['Gilded Age decor', 'American Renaissance interiors'],
    cat: 'Interior Design', c: 'Opulent late-19th-century American mansion interior style', e: 'historical',
    o: 'New York and Newport, USA', g: 'United States', p: '1870-1900', era: 'American Gilded Age',
    sum: 'The marble, gilt, tapestry and oak over-abundance of America\'s 1870s-1890s mansions, staged by European-trained architects and decorators as new-world aristocracy.',
    desc: 'Gilded Age mansions translated European aristocratic display to American scale: marble halls, gilded boiserie, tapestry-hung salons and overmantels. Architects like Richard Morris Hunt and decorators such as Ogden Codman Jr., Wharton\'s co-author on The Decoration of Houses (1897), championed structural dignity over Victorian clutter while serving princely patrons; the Vanderbilt mansions set the tempo. House museums now preserve its interiors.',
    col: [{ h: '#c2a14d', n: 'water-gilt gold' }, { h: '#b58a6a', n: 'Siena marble' }, { h: '#4f3a26', n: 'oak brown' }, { h: '#7e2f38', n: 'tapestry crimson' }, { h: '#3d5245', n: 'brocade green' }],
    m: ['imported marble', 'gilded boiserie', 'carved oak panelling', 'Aubusson and Gobelin tapestries'],
    tx: ['polished veined marble', 'water-gilt sheen', 'deep carved oak relief'],
    obj: ['grand staircases', 'tapestry-hung salons', 'oak dining halls', 'marble mantels', 'overmantel mirrors'],
    ex: ['The Breakers, Newport', 'Biltmore Estate interiors', 'Vanderbilt Fifth Avenue mansions'],
    inf: ['French Beaux-Arts decoration', 'Italian Renaissance palazzi', 'English country house collecting'],
    rel: ['Victorian Style', 'Victorian interior', 'Baroque Revival'],
    src: [{ n: 'Wikipedia — Gilded Age', u: 'https://en.wikipedia.org/wiki/Gilded_Age', t: 'B' }, { n: 'The Metropolitan Museum of Art', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['mansion', 'gilt', 'newport', 'vanderbilt', 'beaux-arts', 'opulent', 'marble'],
    pop: 56, niche: true,
    vd: { shape: 'tall enfilade volumes with colossal frames', line: 'classical mouldings in gilded relief', composition: 'axial processional rooms, center-hall staging', texture: 'hard polished stone against woven gold' },
    typ: { display: 'carved family crests and engraved lintel inscriptions', body: 'engraved roman capitals', notes: 'lettering monumental and architectural' },
    lit: { quality: 'chandelier crystal scatter plus window shafts', temperature: 'warm', shadow: 'formal deep corners, dramatized' },
    ui: { background: 'deep crimson-brown field', surface: 'marble-textured cards with gilt rules', components: 'gold-line buttons, crest ornaments', motion: 'stately curtain-lift reveals' },
  },
  {
    n: 'Log Cabin Interiors', a: ['Log home style', 'Rustic cabin interiors'],
    cat: 'Interior Design', c: 'Rustic American log-home interior tradition', e: 'regional_tradition',
    o: 'American frontier (via Scandinavian settlers)', g: 'United States, Canada; Scandinavian roots', p: '17th century-present', era: 'Frontier America to rustic-lodge revival',
    sum: 'Interiors of exposed round-log walls: vaulted timber ceilings, stone fireplaces, hides, plaid, antler fittings and hand-hewn furniture in the frontier spirit.',
    desc: 'Log cabin interiors make structure and finish the same thing: walls of hand-hewn logs, stone hearths, and furnishings of hide, birch bark, antler and wool plaid. The tradition descends from log building brought by Scandinavian settlers to the Delaware colonies, later romanticized by wilderness lodges. Modern rooms range from frontier restorations to rustic-luxe lodges, unified by visible wood grain, animal textiles and firelight.',
    col: [{ h: '#a9743f', n: 'log amber' }, { h: '#7d7f7a', n: 'hearthstone gray' }, { h: '#e4d9c3', n: 'hide cream' }, { h: '#8e2f2a', n: 'plaid red' }, { h: '#3a5a40', n: 'pine green' }],
    m: ['hand-hewn log walls', 'fieldstone hearths', 'hide and antler', 'wool plaid and splint weaving'],
    tx: ['hewn timber grain', 'dry stone rubble', 'napped wool plaid'],
    obj: ['stone hearths', 'antler chandeliers', 'plaid throws and rugs', 'log-frame beds', 'birch-bark containers'],
    ex: ['frontier-era cabin restorations', 'national park lodge lobbies', 'Scandinavian-settler Delaware replicas'],
    inf: ['Scandinavian log-building technique', 'wilderness lodge architecture', 'frontier homesteading'],
    rel: ['American Craftsman', 'Craftsman Style', 'Turf-Roofed Farmhouse'],
    src: [{ n: 'Wikipedia — Log cabin', u: 'https://en.wikipedia.org/wiki/Log_cabin', t: 'B' }, { n: 'National Park Service', u: 'https://www.nps.gov', t: 'A' }],
    tg: ['log walls', 'hearth', 'rustic', 'frontier', 'plaid', 'timber', 'lodge'],
    pop: 52, niche: true,
    vd: { shape: 'round-log cylinders stacked as the room itself', line: 'horizontal log coursing', composition: 'hearth-centered radial gathering', texture: 'rough bark-adjacent wood with soft wool' },
    typ: { display: 'burned or carved brand marks and camp signs', body: 'hand-painted rustic signage', notes: 'lettering carved, stenciled or branded' },
    lit: { quality: 'firelight flicker over amber wood', temperature: 'warm', shadow: 'deep log-course shadow lines' },
    ui: { background: 'amber timber gradient', surface: 'grain-textured cards', components: 'stone-and-plaid chunky buttons', motion: 'ember-glow pulsing' },
  },
  {
    n: 'Hacienda Style Interiors', a: ['Hacienda style', 'Mexican hacienda decor'],
    cat: 'Interior Design', c: 'Spanish-Mexican ranch estate interior tradition', e: 'regional_tradition',
    o: 'Mexico and the Spanish Southwest', g: 'Mexico, US Southwest; Spanish roots', p: '16th century-present', era: 'Colonial Mexico to present revivals',
    sum: 'Thick-walled ranch interiors: white adobe, saltillo tile, dark viga beams, wrought iron, mesquite doors, Talavera tile and courtyard-facing coolness.',
    desc: 'Hacienda interiors grow from the estate houses of Spanish Mexico and the American Southwest: meter-thick white walls, terracotta floors, exposed viga beams, carved mesquite doors, wrought-iron grilles, Talavera tile wainscots, and dark carved furniture with tooled leather. Rooms open inward to courtyard gardens for shade and cross-ventilation, keeping heavy shadow and cool floors as comfort. revivals and desert resort design keep it alive today.',
    col: [{ h: '#f0e9da', n: 'adobe white' }, { h: '#b26a3f', n: 'saltillo terracotta' }, { h: '#5e4126', n: 'viga timber brown' }, { h: '#26241f', n: 'wrought iron black' }, { h: '#3b6ea5', n: 'Talavera blue' }],
    m: ['adobe and thick lime plaster', 'saltillo terracotta tile', 'rough viga ceiling beams', 'hand-forged wrought iron'],
    tx: ['chalky adobe wall', 'unsealed terracotta sheen', 'hammered iron scale'],
    obj: ['carved mesquite doors', 'Talavera tile wainscots', 'tooled-leather chairs', 'wrought-iron lanterns', 'courtyard portales'],
    ex: ['Sonoran estate houses', 'Santa Fe and Tucson revival homes', 'Mexican resort hacienda courtyards'],
    inf: ['Spanish-Moorish building arts', 'Talavera pottery', 'Mexican Baroque carving'],
    rel: ['Adobe Modern', 'Adobe construction', 'Mexican Baroque'],
    src: [{ n: 'Wikipedia — Hacienda', u: 'https://en.wikipedia.org/wiki/Hacienda', t: 'B' }, { n: 'Instituto Nacional de Antropología e Historia', u: 'https://www.inah.gob.mx', t: 'A' }],
    tg: ['adobe', 'saltillo', 'viga', 'talavera', 'wrought iron', 'courtyard', 'mesquite'],
    pop: 57, niche: false,
    vd: { shape: 'massive rectilinear walls pierced by arcs', line: 'rounded ironwork curves on hard edges', composition: 'inward-facing rooms around a courtyard', texture: 'plaster softness over hard tile and iron' },
    typ: { display: 'painted tile numerals and estate lettering', body: 'hand-painted Spanish-style type', notes: 'signs and dedications fired into tile or forged in iron' },
    lit: { quality: 'bright exterior against shaded interior', temperature: 'warm-cool contrast', shadow: 'deep window-reveal shadow, defining' },
    ui: { background: 'adobe white ground', surface: 'terracotta and tile-pattern cards', components: 'iron-scroll buttons, blue tile chips', motion: 'slow shutter-swing transitions' },
  },
  {
    n: 'Retro 70s Rec Room', a: ['1970s rec room', 'Seventies basement den', 'Wood paneling den'],
    cat: 'Interior Design', c: '1970s suburban basement leisure interior', e: 'commercial_style',
    o: 'North American suburbs', g: 'United States and Canada', p: '1965-1980; 2010s-present revival', era: '1970s North America',
    sum: 'The finished-basement den of the 1970s: knotty-pine paneling, shag carpet, sunken lounges, wood-trimmed bars, lava lamps and console televisions.',
    desc: 'The 1970s rec room turned the basement or den into family leisure architecture: knotty-pine paneling on every wall, shag carpet, sunken conversation pits, wet bars under swag lamps, beanbags, lava lamps, console TVs and hi-fi cabinets, plus game tables. Advertising and sitcoms made it the default image of suburban fun; decades of ridicule followed, before the 2010s kitsch revival reclaimed paneling and amber light as intentional retro warmth.',
    col: [{ h: '#b98a4e', n: 'knotty pine' }, { h: '#d69a2d', n: 'harvest gold' }, { h: '#7d8c46', n: 'avocado green' }, { h: '#c26a2e', n: 'shag orange' }, { h: '#5a3a22', n: 'walnut brown' }],
    m: ['knotty-pine wall paneling', 'shag nylon carpet', 'molded plastic lounge seating', 'amber glass and chrome'],
    tx: ['deep shag pile', 'V-groove paneling rhythm', 'fuzzy upholstery nap'],
    obj: ['wet bars with swag lamps', 'sunken conversation pits', 'lava lamps', 'console TV and hi-fi cabinets', 'beanbag chairs'],
    ex: ['1970s builder basement brochures', 'sitcom dens of the era', '2010s-2020s paneling-core revivals'],
    inf: ['mid-century family-room culture', 'kitsch revival collecting', 'teak-era Scandinavian retailing'],
    rel: ['Retrowave', 'Seventies airbrush style', 'Atomic Age retrofuturism'],
    src: [{ n: 'Wikipedia — Recreation room', u: 'https://en.wikipedia.org/wiki/Recreation_room', t: 'B' }, { n: 'Smithsonian National Museum of American History', u: 'https://americanhistory.si.edu', t: 'A' }],
    tg: ['shag carpet', 'paneling', 'harvest gold', 'basement bar', 'retro', 'seventies', 'den'],
    pop: 62, niche: false,
    vd: { shape: 'low-slung lounge geometry, sunken circles', line: 'vertical panel grooves everywhere', composition: 'wrap-around bar and pit anchoring one side', texture: 'fuzzy pile against flat wood veneer' },
    typ: { display: 'chunky rounded 70s type on bar and game signs', body: 'rounded groovy display faces', notes: 'lettering glows amber under swag lamps' },
    lit: { quality: 'warm pools from pendant swags', temperature: 'very warm', shadow: 'cozy amber half-dark' },
    ui: { background: 'harvest-gold gradient', surface: 'wood-grain cards with shag texture strips', components: 'pill-shaped avocado buttons', motion: 'lazy lava-lamp morphs' },
  },
  {
    n: 'Lagom Interior Philosophy', a: ['Lagom style', 'Swedish balance decor'],
    cat: 'Interior Design', c: 'Swedish "just enough" interior philosophy', e: 'regional_tradition',
    o: 'Sweden', g: 'Scandinavia; global lifestyle publishing', p: 'term centuries old; interiors wave 2010s-present', era: 'Contemporary Nordic lifestyle',
    sum: 'Swedish "not too much, not too little" applied to rooms: balanced palettes, functional comfort, natural light, honest modest materials and calm order.',
    desc: 'Lagom — a Swedish word meaning "just the right amount" — became an interiors philosophy in the mid-2010s as a middle way between austerity and abundance. Rooms are edited rather than emptied: muted naturals with one or two accents, honest materials like birch, wool and linen, daylight given priority, and concealed storage. Where hygge centers coziness, lagom centers balance — shorthand for sustainable, unostentatious Nordic decorating.',
    col: [{ h: '#e9e6df', n: 'birch white' }, { h: '#b9bcbe', n: 'muted gray' }, { h: '#8fa3b0', n: 'fog blue' }, { h: '#ddd3c0', n: 'natural linen' }, { h: '#7d8b74', n: 'spruce green' }],
    m: ['birch and pale pine', 'wool throws', 'washed linen', 'matte stoneware ceramics'],
    tx: ['brushed matte wood', 'napped wool', 'washed linen slub'],
    obj: ['concealed functional storage', 'daylight-maximizing mirrors', 'wool throws', 'simple ceramic tableware', 'potted greenery'],
    ex: ['Swedish apartment styling features', 'mid-2010s lagom book publishing wave', 'Nordic brand showroom interiors'],
    inf: ['Scandinavian functionalism', 'Swedish folk modesty', 'environmental minimalism'],
    rel: ['Hygge', 'Scandinavian design', 'Scandi style', 'Hygge interior design'],
    src: [{ n: 'Wikipedia — Lagom', u: 'https://en.wikipedia.org/wiki/Lagom', t: 'B' }, { n: 'Swedish Institute', u: 'https://si.se', t: 'A' }],
    tg: ['lagom', 'balance', 'nordic', 'swedish', 'restraint', 'sustainable', 'calm'],
    pop: 62, niche: false,
    vd: { shape: 'quiet rectangles with one soft curve', line: 'thin even strokes, no ornament', composition: 'generous margins, single accent per view', texture: 'flat matte with gentle fiber grain' },
    typ: { display: 'lowercase grotesque wordmarks', body: 'clean humanist sans with wide spacing', notes: 'whisper-level lettering, no shouting' },
    lit: { quality: 'even northern daylight', temperature: 'cool-neutral', shadow: 'soft, nearly eliminated' },
    ui: { background: 'birch white', surface: 'linen-textured neutral cards', components: 'fog-gray rounded buttons, single green accent', motion: 'subtle ease-in fades' },
  },
]
