/**
 * Latin America wave — 12 hand-verified craft, dress, festival & graphic traditions.
 * All names are real, documented traditions; sources are stable Wikipedia URLs.
 */
export const ENTRIES: any[] = [
  {
    n: 'Otomí Tenango Embroidery', a: ['Tenango embroidery', 'Tenango de Doria embroidery', 'Otomi embroidery', 'Bordado tenango'],
    cat: 'Textile & Craft', c: 'Mexican pictorial embroidery tradition', e: 'regional_tradition',
    o: 'Tenango de Doria, Hidalgo, Mexico', g: 'Mexico (Hidalgo Sierra Otomí; national craft markets)', p: 'c. 1960s-present (older Otomí roots)', era: 'Modern Mexican folk art',
    sum: 'Vivid pictorial crewelwork from the Sierra Otomí of Hidalgo: white cotton dense with multicolor blossoms, animals, comets and village scenes, stitched for the national folk-art market.',
    desc: 'Otomí embroidery crystallized in Tenango de Doria and neighboring Ñhähñu communities of Hidalgo, where women cover cotton with stitched blossoms, rabbits, deer, birds, comets and whole village scenes. Rooted in older Otomí needlework, the style bloomed commercially from the 1960s in dense satin and outline stitches of mercerized floss. Each panel reads as a teeming spirit-garden packed edge to edge — one of Mexico\'s most recognizable folk textiles.',
    col: [{ h: '#f4efe3', n: 'embroidery-ground cream' }, { h: '#c22a6e', n: 'fuchsia floss' }, { h: '#2e7d4f', n: 'parrot green' }, { h: '#e08a24', n: 'marigold orange' }, { h: '#2a6fa8', n: 'sky-animal blue' }],
    m: ['white cotton and muslin ground cloth', 'mercerized cotton embroidery floss', 'wool yarn (earlier pieces)', 'crewel needles and hoops'],
    tx: ['dense satin-stitch fill', 'outline stem-stitch contour', 'flat plain-weave ground'],
    obj: ['cushion covers', 'wall-hanging panels', 'table runners', 'embroidered dresses and blouses'],
    ex: ['Tenango de Doria workshop panels', 'Sierra Otomí cooperative textiles', 'museum holdings of Hidalgo embroidery'],
    inf: ['Pre-Hispanic Otomí stitching', 'Mexican folk-art market circuits', 'tourist craft economy'],
    rel: ['Amate Bark Paper Painting', 'Lotería Cards', 'Huichol Yarn Painting'],
    src: [{ n: 'Wikipedia — Otomi embroidery', u: 'https://en.wikipedia.org/wiki/Otomi_embroidery', t: 'B' }, { n: 'Wikipedia — Tenango de Doria', u: 'https://en.wikipedia.org/wiki/Tenango_de_Doria', t: 'C' }],
    tg: ['embroidery', 'otomi', 'tenango', 'hidalgo', 'folk textile', 'pictorial', 'mexican'],
    pop: 46, niche: true,
    vd: { shape: 'swelling flower and animal silhouettes packed edge to edge', line: 'snaking outline stitch enclosing satin fill', composition: 'all-over horror-vacui field, no empty ground', texture: 'raised floss sheen over flat cotton' },
    typ: { display: 'n/a — decorative textile', body: 'n/a', notes: 'occasional maker initials worked into the field' },
    lit: { quality: 'bright even daylight', temperature: 'warm', shadow: 'soft thread-cast micro-shadows' },
    ui: { background: 'warm cream ground', surface: 'dense pictorial stitch cards', components: 'flower-and-comet outlined buttons', motion: 'gentle bloom-in reveals' },
  },
  {
    n: 'Charrería Costume & Gear', a: ['Charreria', 'Charro costume', 'Traje de charro', 'Charrería gear'],
    cat: 'Regional & Cultural Tradition', c: 'Mexican rodeo dress and gear tradition', e: 'regional_tradition',
    o: 'Central Mexico (Hidalgo & Jalisco)', g: 'Mexico, Mexican-American rodeo communities', p: '16th century-present; codified 1930s-50s', era: 'Colonial Mexico to present',
    sum: 'Mexico\'s national sport and its visual code: silver-buttoned charro suits, wide sombreros, engraved saddles, braided rawhide and giant rowel spurs of the lienzo charro.',
    desc: 'Charrería grew from hacienda livestock work into Mexico\'s national sport, its suertes — coleadero, manganas, the paso de la muerte — codified by associations after the Revolution. Its visual code is the traje de charro: wide sombrero, chaqueta and calzoneras sewn with rows of silver botonería, engraved-silver saddle furniture and great rowel spurs. Women\'s escaramuza teams ride sidesaddle in ruffled adelita dresses. Charrería was inscribed on UNESCO\'s intangible heritage list in 2016.',
    col: [{ h: '#26262e', n: 'charro suit black' }, { h: '#c4c8cf', n: 'botonería silver' }, { h: '#8a6f47', n: 'gamuza suede tan' }, { h: '#6e1f2a', n: 'charro tie red' }, { h: '#caa64a', n: 'gold braid' }],
    m: ['fine wool and suede (gamuza)', 'silver and gold-thread button embroidery', 'hare-felt and palm sombrero straw', 'braided rawhide reata', 'hardwood and engraved-metal saddle fittings'],
    tx: ['closely set silver buttons', 'embossed leather tooling', 'silk braid piping', 'hand-braided rawhide twist'],
    obj: ['sombrero de charro', 'chaqueta and calzoneras suits', 'montura saddles with engraved fittings', 'espuelas rowel spurs', 'escaramuza adelita dresses'],
    ex: ['UNESCO-listed lienzo charro events', 'mariachi traje adaptations of charro dress', 'golden-age film charro wardrobes'],
    inf: ['Spanish vaquero horsemanship', 'hacienda livestock culture', 'mariachi costume'],
    rel: ['Charro Attire', 'Mexican Charro Suit', 'Gaucho Dress'],
    src: [{ n: 'Wikipedia — Charrería', u: 'https://en.wikipedia.org/wiki/Charrer%C3%ADa', t: 'B' }, { n: 'Wikipedia — Charro', u: 'https://en.wikipedia.org/wiki/Charro', t: 'B' }],
    tg: ['charro', 'rodeo', 'sombrero', 'silver buttons', 'escaramuza', 'mexican', 'costume'],
    pop: 48, niche: true,
    vd: { shape: 'fitted tailored silhouette under a wide spherical hat', line: 'rows of buttons and braid tracing seams', composition: 'symmetric front-fastening formality', texture: 'matte wool and suede against metal glint' },
    typ: { display: 'n/a — worn costume', body: 'n/a', notes: 'embroidered names and association crests on sombreros' },
    lit: { quality: 'harsh arena sun with metal sparkle', temperature: 'warm', shadow: 'hard hat-brim shadow on the face' },
    ui: { background: 'dust-tan arena gradient', surface: 'dark tailored panels with silver trim', components: 'button-row dividers and spur-shaped icons', motion: 'confident trot-step transitions' },
  },
  {
    n: 'Día de Muertos Visual Culture', a: ['Day of the Dead art', 'Día de los Muertos', 'Ofrenda visual culture', 'Dia de Muertos iconography'],
    cat: 'Festival & Folk Art', c: 'Mexican Day of the Dead folk visual culture', e: 'regional_tradition',
    o: 'Mexico (Oaxaca, Michoacán, Mexico City)', g: 'Mexico, Mexican-American communities, global festival adoption', p: 'pre-Hispanic roots; modern form 19th century-present', era: 'Syncretic colonial to modern Mexico',
    sum: 'The ofrenda world: cempasúchil marigold paths, papel picado, sugar skulls, pan de muerto and La Catrina — the dense visual language of Mexico\'s Day of the Dead.',
    desc: 'Mexico\'s Day of the Dead fuses pre-Hispanic death rites with Catholic All Souls in a dense visual culture: ofrenda altars with candles, copal smoke, portraits and pan de muerto; cempasúchil marigold petals scattered as soul-paths; perforated papel picado banners; grinning sugar skulls. José Guadalupe Posada\'s etched La Catrina, named by Diego Rivera, gave the feast its elegant skeleton icon. Its orange-and-magenta palette is now a global emblem of Mexican identity.',
    col: [{ h: '#e8862a', n: 'cempasúchil marigold' }, { h: '#b13c8c', n: 'colecção magenta' }, { h: '#f5f1e6', n: 'candle wax white' }, { h: '#5b3a8a', n: 'altar purple' }, { h: '#231f1c', n: 'skeleton soot black' }],
    m: ['cempasúchil marigold blooms', 'perforated tissue paper (papel picado)', 'sugar and alfeñique paste', 'beeswax candles', 'copal resin'],
    tx: ['fringed tissue-paper edge', 'granulated sugar frosting', 'wax-bloom glow', 'loose petal drifts'],
    obj: ['ofrenda altars', 'calaveras de azúcar', 'papel picado banners', 'pan de muerto', 'La Catrina figures'],
    ex: ['Oaxaca and Pátzcuaro public ofrendas', 'Posada\'s La Catrina zinc etching', 'Mexico City Día de Muertos parade (since 2016)'],
    inf: ['Posada print culture', 'pre-Hispanic death-goddess cult', 'Catholic All Souls\' Day'],
    rel: ['Ofrenda de Día de Muertos', 'La Catrina Iconography', 'Lotería Cards'],
    src: [{ n: 'Wikipedia — Day of the Dead', u: 'https://en.wikipedia.org/wiki/Day_of_the_Dead', t: 'B' }, { n: 'Wikipedia — La Catrina', u: 'https://en.wikipedia.org/wiki/La_Catrina', t: 'B' }],
    tg: ['day of the dead', 'ofrenda', 'sugar skull', 'marigold', 'catrina', 'mexican', 'festival'],
    pop: 64, niche: false,
    vd: { shape: 'tiered altar geometry and rounded skull ovals', line: 'cut-paper perforation lattice', composition: 'stacked levels dense with offerings', texture: 'petal drifts, sugar grit, wax sheen' },
    typ: { display: 'hand-lettered names and dates on sugar skulls', body: 'n/a', notes: 'inscriptions naming the honored dead' },
    lit: { quality: 'candlelight-dominated mixed lighting', temperature: 'warm', shadow: 'deep flickering altar shadows' },
    ui: { background: 'marigold-to-purple dusk gradient', surface: 'tissue-fringe bordered cards', components: 'skull and papel picado cutout buttons', motion: 'slow candle-flicker pulses' },
  },
  {
    n: 'Alebrije Wood Carving', a: ['Oaxacan alebrijes', 'Oaxacan wood carving', 'Alebrijes oaxaqueños'],
    cat: 'Folk Art & Sculpture', c: 'Oaxacan carved fantasy-creature folk sculpture', e: 'regional_tradition',
    o: 'Arrazola, San Martín Tilcajete & La Unión, Oaxaca, Mexico', g: 'Mexico (Oaxaca; international folk-art markets)', p: '1930s name origin; wood-carving 1960s-present', era: 'Postwar Mexican folk art',
    sum: 'Oaxacan copal-wood carvings of twisted beasts and nahuales, coated in pointillist dots, Zapotec frets and fluorescent florals — Mexico\'s signature folk sculpture.',
    desc: 'Pedro Linares\'s 1930s papier-mâché nightmare creatures gave Mexico the word alebrije; from the 1960s Manuel Jiménez of Arrazola carved the idea into copal wood, and the villages of San Martín Tilcajete and La Unión made it a trade. Knives coax nahuales, dragons, owls and rabbits from pale wood; surfaces explode in pointillist dots, Zapotec frets and fluorescent florals over black contour. Sold through the 1980s export boom, Oaxacan alebrijes became the country\'s signature folk sculpture.',
    col: [{ h: '#ff5f1f', n: 'fluorescent orange' }, { h: '#e91e8c', n: 'hot magenta' }, { h: '#19b8a6', n: 'turquoise' }, { h: '#c8e02e', n: 'acid lime' }, { h: '#1c1a1e', n: 'contour black' }],
    m: ['copal (Bursera) wood', 'machetes, hand knives and gouges', 'acrylic and aniline paints', 'fine pointillism brushes'],
    tx: ['dense dot-and-dash pointillism', 'fluorescent color fields', 'sanded pale copal grain'],
    obj: ['fantastical beast figurines', 'nahual spirit-animal carvings', 'owl and rabbit sculptures', 'large dragon composites'],
    ex: ['Pedro Linares papier-mâché alebrijes', 'Manuel Jiménez Arrazola carvings', 'Noche de Alebrijes parade, Mexico City (since 2007)'],
    inf: ['Pedro Linares cartonería alebrijes', 'Zapotec nahual beliefs', 'Oaxacan folk-art markets'],
    rel: ['Oaxacan Alebrijes', 'Alebrijes', 'Amate Bark Paper Painting'],
    src: [{ n: 'Wikipedia — Alebrije', u: 'https://en.wikipedia.org/wiki/Alebrije', t: 'B' }, { n: 'Wikipedia — Pedro Linares', u: 'https://en.wikipedia.org/wiki/Pedro_Linares', t: 'B' }],
    tg: ['alebrije', 'oaxaca', 'wood carving', 'folk sculpture', 'nahual', 'pointillism', 'mexican'],
    pop: 56, niche: false,
    vd: { shape: 'acrobatic twisted quadrupeds with exaggerated horns and wings', line: 'black contour enclosing fluorescent pattern', composition: 'single creature centered, pattern covering all', texture: 'smooth sealed wood under stippled paint' },
    typ: { display: 'n/a — applied object art', body: 'n/a', notes: 'village and maker signatures under base' },
    lit: { quality: 'bright studio highlights', temperature: 'warm', shadow: 'clean contact shadows under figures' },
    ui: { background: 'pale copal neutral', surface: 'fluorescent pattern tiles', components: 'dot-stipple buttons and fret dividers', motion: 'playful bounce-in scale reveals' },
  },
  {
    n: 'Barro Negro Pottery (Oaxaca)', a: ['Barro negro', 'Oaxacan black pottery', 'Doña Rosa pottery', 'Barro negro de San Bartolo Coyotepec'],
    cat: 'Material & Surface', c: 'Black burnished Oaxacan pottery tradition', e: 'regional_tradition',
    o: 'San Bartolo Coyotepec, Oaxaca, Mexico', g: 'Mexico (Oaxaca; national tourism routes)', p: 'pre-Hispanic to present; black burnish since 1952', era: 'Colonial Oaxaca to present',
    sum: 'Lustrous jet-black pottery from San Bartolo Coyotepec, Oaxaca — burnished with quartz before firing, its famous sheen invented by Doña Rosa Real in 1952.',
    desc: 'San Bartolo Coyotepec has shaped fine gray clay since Zapotec times, but its jet-black sheen dates to 1952, when Doña Rosa Real found that rubbing leather-hard paste with quartz before firing burns the surface to metallic luster. Burnished jars glow like obsidian; unburnished work stays matte smoke-gray. Cántaros, mezcal flasks, carved vases, whistling jars and animal figures made her family workshop famous and turned the town into a highlight on Oaxaca craft routes.',
    col: [{ h: '#141317', n: 'obsidian jet' }, { h: '#3d3d44', n: 'graphite sheen' }, { h: '#565a50', n: 'smoke gray-green' }, { h: '#7a5c44', n: 'unburnished clay brown' }, { h: '#b9bcc2', n: 'quartz shine' }],
    m: ['fine gray Oaxacan clay', 'quartz burnishing stones', 'wood-fuel updraft kilns'],
    tx: ['mirror-sheen burnish', 'carved floral relief', 'smoke-dark matte base'],
    obj: ['cántaro water jars', 'mezcal flasks and cups', 'carved flower vases', 'whistling jars', 'animal figurines'],
    ex: ['Doña Rosa Real\'s original burnished jars', 'family workshops of San Bartolo Coyotepec', 'MEAPO museum holdings, Oaxaca'],
    inf: ['Zapotec pottery', 'pre-Hispanic Coyotepec techniques', 'Mexican folk-art tourism'],
    rel: ['Barro Negro de Oaxaca', 'Talavera Pottery', 'Mata Ortiz Pottery'],
    src: [{ n: 'Wikipedia — Barro negro pottery', u: 'https://en.wikipedia.org/wiki/Barro_negro_pottery', t: 'B' }, { n: 'Wikipedia — San Bartolo Coyotepec', u: 'https://en.wikipedia.org/wiki/San_Bartolo_Coyotepec', t: 'C' }],
    tg: ['barro negro', 'black pottery', 'oaxaca', 'burnish', 'doña rosa', 'ceramics', 'mexican'],
    pop: 44, niche: true,
    vd: { shape: 'round-bellied jars and flasks, quiet useful silhouettes', line: 'carved curving bands where relief breaks the sheen', composition: 'one polished form, generous negative space', texture: 'liquid-metal gloss over smoke-dark clay' },
    typ: { display: 'incised maker marks only', body: 'n/a', notes: 'no lettering tradition beyond workshop marks' },
    lit: { quality: 'single specular highlight sweeping the burnish', temperature: 'cool-neutral', shadow: 'deep black self-shadow' },
    ui: { background: 'smoky charcoal gradient', surface: 'black gloss cards with carved bands', components: 'obsidian-tone rounded buttons', motion: 'slow sheen-slide transitions' },
  },
  {
    n: 'Marajoara Pottery', a: ['Marajoara ceramics', 'Marajó pottery', 'Marajoara style'],
    cat: 'Material & Surface', c: 'Pre-Columbian Amazonian painted ceramic style', e: 'historical',
    o: 'Marajó Island, Pará, Brazil', g: 'Brazil (Marajó island, Amazon estuary)', p: 'c. 400-1400 CE', era: 'Pre-Columbian Amazonia',
    sum: 'Elaborate painted and incised ceramics of Marajó Island chiefdoms: polychrome geometries, serpent and owl motifs, and great funerary urns of pre-Columbian Amazonia.',
    desc: 'On Marajó island, chiefdoms of the Marajoara phase (c. 400-1400 CE) raised earthen mounds and filled them with ceramics of rare refinement. Potters painted red, black and white on buff slips, cut excised patterns, and modeled rims into owls and serpents, building funerary urns for honored dead. Collected since Hartt\'s 1870s expeditions and canonized in Rio\'s National Museum, the style was revived into Brazilian design identity in the 20th century.',
    col: [{ h: '#c8926a', n: 'buff terracotta slip' }, { h: '#9c3524', n: 'hematite red' }, { h: '#2c2420', n: 'paint black' }, { h: '#efe6d2', n: 'kaolin white' }, { h: '#a8673f', n: 'fired clay orange' }],
    m: ['kaolin and cauixí sponge-spiker freshwater clay', 'burnishing pebbles', 'mineral polychrome pigments', 'open bonfire firing'],
    tx: ['incised and excised line', 'polychrome slip painting', 'modeled relief rims', 'smooth burnished slip'],
    obj: ['funerary urns', 'painted ritual bowls', 'effigy vessels', 'ceremonial pottery stools', 'spindle whorls'],
    ex: ['Museu Nacional Rio urns lost in the 2018 fire', 'Hartt expedition collections, 1870s', 'Museu Paraense Emílio Goeldi Marajó holdings'],
    inf: ['earlier Ananatuba and Formiga island phases', 'shamanic funerary practice', '20th-century Brazilian design revival'],
    rel: ['Maya Codex Art', 'Mata Ortiz Pottery'],
    src: [{ n: 'Wikipedia — Marajoara culture', u: 'https://en.wikipedia.org/wiki/Marajoara_culture', t: 'B' }, { n: 'Wikipedia — Marajó', u: 'https://en.wikipedia.org/wiki/Maraj%C3%B3', t: 'B' }],
    tg: ['marajoara', 'pre-columbian', 'amazon', 'funerary urn', 'polychrome', 'brazil', 'ceramics'],
    pop: 38, niche: true,
    vd: { shape: 'wide urns and bowls with modeled rim figures', line: 'interlocking scrolls, zigzags and stepped frets', composition: 'symmetric registers wrapping the vessel', texture: 'matte slip over burnished earthenware' },
    typ: { display: 'abstract iconography only', body: 'n/a', notes: 'no writing system; motifs read as symbolic code' },
    lit: { quality: 'soft diffuse museum light', temperature: 'warm', shadow: 'shallow relief shadows in incision' },
    ui: { background: 'buff terracotta field', surface: 'polychrome geometric pattern cards', components: 'scrollwork outline buttons', motion: 'steady register-slide transitions' },
  },
  {
    n: 'Chichicastenango Textile Tradition', a: ['Chichicastenango huipil', 'Chichi weaving', 'K\'iche\' brocaded huipiles'],
    cat: 'Textile & Craft', c: 'Highland Maya brocaded weaving tradition', e: 'regional_tradition',
    o: 'Chichicastenango, El Quiché, Guatemala', g: 'Guatemala (K\'iche\' highlands; export markets)', p: 'colonial era-present; market form 20th century', era: 'Colonial Guatemala to present',
    sum: 'K\'iche\' Maya backstrap-loom weaving of Chichicastenango: white huipiles brocaded with silk-floss double-headed eagles, birds, stars and flowers for market and cofradía.',
    desc: 'In the K\'iche\' Maya town of Chichicastenango, backstrap looms produce Guatemala\'s most festive huipiles: white grounds brocaded in silk-floss double-headed eagles, birds, stars and flowers, with ceremonial versions for cofradía officials. Supplementary-weft brocading lets each weaver improvise her figures, so no two match. Thursday and Sunday markets fill the plaza with these textiles, now central to Pan-Maya identity.',
    col: [{ h: '#f2ede2', n: 'brocade-ground white' }, { h: '#c22a6e', n: 'fuchsia silk floss' }, { h: '#2e7d4f', n: 'bird green' }, { h: '#d98e26', n: 'marigold gold' }, { h: '#28406e', n: 'indigo cobalt' }],
    m: ['backstrap loom (telar de cintura)', 'cotton thread', 'silk or synthetic floss for brocade', 'commercial dyes'],
    tx: ['supplementary-weft brocade floats', 'balanced plain-weave ground', 'satin floss sheen'],
    obj: ['brocaded huipiles', 'tzute headcloths', 'cofradía ceremonial textiles', 'market tablecloths'],
    ex: ['Chichicastenango Thursday and Sunday market stalls', 'Museo Ixchel documented huipiles', 'double-headed eagle ceremonial huipiles'],
    inf: ['postclassic Maya weaving', 'cofradía ritual dress', 'Pan-Maya weaving revival'],
    rel: ['Chichicastenango Textile', 'Huipil de San Antonio Aguas Calientes', 'Huipil de Zinacantan'],
    src: [{ n: 'Wikipedia — Chichicastenango', u: 'https://en.wikipedia.org/wiki/Chichicastenango', t: 'B' }, { n: 'Wikipedia — Huipil', u: 'https://en.wikipedia.org/wiki/Huipil', t: 'B' }],
    tg: ['huipil', 'maya', 'backstrap loom', 'brocade', 'guatemala', 'kiche', 'textile'],
    pop: 42, niche: true,
    vd: { shape: 'box-cut blouse panels with centered radial bird motifs', line: 'dotted brocade contours within weave grid', composition: 'symmetric front-and-back figure bands', texture: 'raised floss floats on crisp cotton' },
    typ: { display: 'n/a — decorative textile', body: 'n/a', notes: 'village identity readable through motif placement' },
    lit: { quality: 'highland even daylight', temperature: 'cool-neutral', shadow: 'minimal, thread-level only' },
    ui: { background: 'white cotton ground', surface: 'brocade figure cards', components: 'bird-and-star outlined buttons', motion: 'shuttle-paced slide reveals' },
  },
  {
    n: 'Wayuu Mochila Bags', a: ['Mochila wayuu', 'Wayuu crochet bag', 'Guajira mochila'],
    cat: 'Textile & Craft', c: 'Guajira tapestry-crochet bag tradition', e: 'regional_tradition',
    o: 'La Guajira peninsula, Colombia & Venezuela', g: 'Colombia & Venezuela, global craft retail', p: '20th century-present (older weaving roots)', era: '20th-century Guajira to present',
    sum: 'Dense spirally crocheted Wayuu bags from La Guajira — saturated kanaas geometric patterns worked in tapestry crochet, a single large bag taking up to a month.',
    desc: 'Among Wayuu weavers of the Guajira peninsula, the mochila is both daily gear and canvas: a circular bag crocheted upward in tight tapestry crochet, dense with kanaas — geometric designs named for spider myths and landscape. A large bag can occupy a woman for a month, worked in saturated acrylics and finished with braided straps. Traded across Colombia and Venezuela and exported worldwide, it is the most recognizable object of Wayuu culture.',
    col: [{ h: '#d81b74', n: 'guajira fuchsia' }, { h: '#00a8a8', n: 'caribbean turquoise' }, { h: '#f2a71b', n: 'desert marigold' }, { h: '#7cb342', n: 'cactus green' }, { h: '#211d21', n: 'contour black' }],
    m: ['acrylic and cotton yarn', 'crochet hooks', 'braided strap cord'],
    tx: ['tight tapestry-crochet texture', 'float-free colorwork', 'braided strap twist'],
    obj: ['mochila shoulder bags', 'miniature coin mochilas', 'braided straps and tassels', 'chinchorro hammocks (sister craft)'],
    ex: ['Uribía and Maicao craft markets', 'Wayuu weaving cooperatives', 'Bogotá and Caracas museum craft displays'],
    inf: ['Wayuu kanaas design language', 'Guajira trade economy', 'Colombian craft export programs'],
    rel: ['Guna Mola Reverse Appliqué', 'Huichol Yarn Painting'],
    src: [{ n: 'Wikipedia — Wayuu', u: 'https://en.wikipedia.org/wiki/Wayuu', t: 'B' }, { n: 'Wikipedia — Wayuu language', u: 'https://en.wikipedia.org/wiki/Wayuu_language', t: 'C' }],
    tg: ['wayuu', 'mochila', 'crochet', 'guajira', 'geometric', 'colombia', 'craft'],
    pop: 47, niche: true,
    vd: { shape: 'cylindrical bodies cinched at the drawstring mouth', line: 'stepped diagonal and zigzag kanaas bands', composition: 'continuous spiral registers base to rim', texture: 'stiff dense crochet stitch-wall' },
    typ: { display: 'n/a — decorative object', body: 'n/a', notes: 'patterns encode community and maker repertoires' },
    lit: { quality: 'bright desert daylight', temperature: 'warm', shadow: 'shallow interior-shadow at strap' },
    ui: { background: 'sandy neutral', surface: 'saturated geometric crochet tiles', components: 'zigzag-band buttons and tassel accents', motion: 'spiraling grow-around reveals' },
  },
  {
    n: 'Pollera Dress (Panama)', a: ['Panamanian pollera', 'Pollera panameña', 'Pollera de gala'],
    cat: 'Dress & Costume', c: 'Panamanian national dress and embroidery', e: 'regional_tradition',
    o: 'Azuero Peninsula, Panama', g: 'Panama, Panamanian diaspora celebrations', p: 'colonial roots; modern form 19th century-present', era: 'Colonial Panama to present',
    sum: 'Panama\'s national costume: a white cotton gown of layered embroidered ruffles over an enagua petticoat, crowned with peinetas and quivering pearl tembleque pins.',
    desc: 'Panama\'s national dress descends from Spanish colonial wear, refashioned on the Azuero peninsula into a white cotton gown: embroidered florals, lace ruffles tiered over an enagua petticoat, and a headdress of peinetas and quivering wire-and-pearl tembleques. Gold chains and filigree mosquetas cover the chest. Worn for mejorana festivals and the thousand-pollera parade in Las Tablas, the pollera embodies Panamanian identity.',
    col: [{ h: '#f7f4ec', n: 'pollera white' }, { h: '#caa64a', n: 'gold filigree' }, { h: '#b53a52', n: 'floral embroidery red' }, { h: '#4d6ea8', n: 'floral embroidery blue' }, { h: '#e8e0cf', n: 'lace ivory' }],
    m: ['fine white cotton cloth', 'embroidery floss', 'hand-made lace inserts', 'gold and pearl filigree jewelry', 'wire-and-pearl tembleque pins'],
    tx: ['dense floral embroidery', 'gathered lace ruffles', 'polished gold filigree', 'quivering pearl pins'],
    obj: ['pollera de gala gowns', 'enagua petticoats', 'tembleque hair ornaments', 'peineta combs', 'montuno men\'s shirts'],
    ex: ['Festival Nacional de la Pollera y el Mejorano, Las Tablas', 'Desfile de las Mil Polleras parades', 'Azuero embroidery workshops'],
    inf: ['Spanish colonial costume', 'Azuero folk Catholic festivals', 'mejorana music culture'],
    rel: ['Guna Mola Reverse Appliqué', 'Gaucho Dress', 'Maracatu Costumes'],
    src: [{ n: 'Wikipedia — Pollera', u: 'https://en.wikipedia.org/wiki/Pollera', t: 'B' }, { n: 'Wikipedia — Culture of Panama', u: 'https://en.wikipedia.org/wiki/Culture_of_Panama', t: 'C' }],
    tg: ['pollera', 'panama', 'national dress', 'embroidery', 'tembleques', 'azuero', 'costume'],
    pop: 40, niche: true,
    vd: { shape: 'full tiered bell skirt under a fitted ruffled bodice', line: 'concentric ruffle tiers traced by floral stitch', composition: 'head-to-hem vertical rhythm of white tiers', texture: 'soft cotton volume with lace breath' },
    typ: { display: 'n/a — worn costume', body: 'n/a', notes: 'jewelry layering follows fixed festival rules' },
    lit: { quality: 'bright festive daylight', temperature: 'warm', shadow: 'soft tier-to-tier shading' },
    ui: { background: 'ivory lace field', surface: 'tiered ruffle panels with floral stitch', components: 'gold filigree round buttons', motion: 'sway-and-turn parallax motion' },
  },
  {
    n: 'Literatura de Cordel Woodcuts', a: ['Cordel woodcuts', 'Xilogravura de cordel', 'Folheto covers', 'Cordel covers'],
    cat: 'Graphic & Print', c: 'Northeast Brazilian chapbook woodcut tradition', e: 'regional_tradition',
    o: 'Pernambuco, Paraíba & Ceará, Brazil', g: 'Brazil (Northeast; national book-fair culture)', p: 'late 19th century-present', era: 'Republic-era Brazil to present',
    sum: 'Northeast Brazil\'s chapbook verse sold hanging from strings at fairs, capped by bold xilogravura woodcut covers of cangaceiros, saints, beasts and droughts.',
    desc: 'Northeast Brazil\'s cordel literature — pamphlets of rhymed sextilha verse sold hanging from strings at fairs — has carried legends of cangaceiro bandits, droughts, saints and poet duels since the late 1800s. Its covers are cut as xilogravura woodcuts: bold black figures on cheap newsprint. J. Borges of Bezerros, Pernambuco raised the covers into fine art, and the woodcuts now stand beside the verse as Brazil\'s defining popular graphic tradition.',
    col: [{ h: '#171412', n: 'woodcut black' }, { h: '#efe6d0', n: 'newsprint cream' }, { h: '#b3341f', n: 'spot red' }, { h: '#2b5f9e', n: 'spot blue' }, { h: '#d9a520', n: 'spot yellow' }],
    m: ['regional hardwood blocks', 'carving gouges and knives', 'manual proof presses', 'cheap newsprint stock', 'black and spot-color inks'],
    tx: ['bold gouged black line', 'coarse woodgrain impression', 'newsprint absorbency'],
    obj: ['cordel pamphlet covers', 'stand-alone xilogravura prints', 'fair-stall string displays'],
    ex: ['J. Borges covers from Bezerros, Pernambuco', 'Lampião cangaceiro chapbooks', 'Academia Brasileira de Literatura de Cordel, Rio'],
    inf: ['Portuguese folheto tradition', 'feira chapbook commerce', 'Cangaço outlaw folklore'],
    rel: ['Xilogravura', 'Brazilian Woodcuts', 'Frevo Visual Culture'],
    src: [{ n: 'Wikipedia — Literatura de cordel', u: 'https://en.wikipedia.org/wiki/Literatura_de_cordel', t: 'B' }, { n: 'Wikipedia — Xilogravura', u: 'https://en.wikipedia.org/wiki/Xilogravura', t: 'B' }],
    tg: ['cordel', 'xilogravura', 'woodcut', 'chapbook', 'nordeste', 'brazil', 'folk print'],
    pop: 45, niche: true,
    vd: { shape: 'flat frontal figures and beasts framed in ruled borders', line: 'thick gouged contour with crosshatch tone', composition: 'title banner above, action scene below', texture: 'inky bite on fibrous newsprint' },
    typ: { display: 'hand-cut woodblock lettering in banner title', body: 'n/a', notes: 'verse printed letterpress inside pamphlet' },
    lit: { quality: 'flat even print light', temperature: 'warm', shadow: 'pure black shape shadow only' },
    ui: { background: 'newsprint cream', surface: 'black-cut print cards with spot color', components: 'banner-title headers and gouged-line dividers', motion: 'stamp-press snap reveals' },
  },
  {
    n: 'Frevo Umbrella Culture', a: ['Frevo sombrinha', 'Frevo parasol', 'Passista umbrella', 'Sombrinha de frevo'],
    cat: 'Festival & Folk Art', c: 'Recife carnival dance and parasol culture', e: 'regional_tradition',
    o: 'Recife, Pernambuco, Brazil', g: 'Brazil (Recife & Olinda carnival)', p: 'c. 1900-present', era: 'Belle-époque Brazil to present',
    sum: 'Recife\'s acrobatic carnival frevo and its chromatic mini-parasol — the sombrinha — spun by passistas in mirrored velvet suits behind blaring brass bands.',
    desc: 'Frevo — from ferver, to boil — boiled out of Recife\'s brass bands in the early 1900s, when capoeira-trained toughs spun small parasols to claim the street. The weapon became dance: passistas in mirrored velvet suits whirl the sombrinha through more than a hundred acrobatic passos, backed by blaring fanfarra bands. UNESCO-listed in 2012 and housed in Recife\'s Paço do Frevo, the spinning umbrella is Pernambuco\'s supreme carnival image.',
    col: [{ h: '#e91e63', n: 'hot pink taffeta' }, { h: '#aee62e', n: 'acid green' }, { h: '#f7c500', n: 'chrome yellow' }, { h: '#d9dde3', n: 'mirror sequin' }, { h: '#201a20', n: 'velvet black' }],
    m: ['lightweight steel ribs and shafts', 'taffeta parasol covers', 'velvet, satin and mirror-sequin suits', 'brass band instruments'],
    tx: ['spinning parasol blur', 'mirrored sequin flash', 'glazed taffeta shine'],
    obj: ['sombrinha mini-parasols', 'passista performance suits', 'fanfarra band uniforms'],
    ex: ['Galo da Madrugada parade, Recife', 'Paço do Frevo museum (2014)', 'UNESCO-listed frevo passista troupes'],
    inf: ['capoeira footwork', 'military brass band repertoire', 'maracatu pageantry'],
    rel: ['Frevo Dance Umbrellas', 'Maracatu Costumes', 'Capoeira Visual Culture'],
    src: [{ n: 'Wikipedia — Frevo', u: 'https://en.wikipedia.org/wiki/Frevo', t: 'B' }, { n: 'Wikipedia — Galo da Madrugada', u: 'https://en.wikipedia.org/wiki/Galo_da_Madrugada', t: 'B' }],
    tg: ['frevo', 'sombrinha', 'recife', 'carnival', 'passista', 'pernambuco', 'umbrella'],
    pop: 43, niche: true,
    vd: { shape: 'open half-dome parasol held aloft in mid-spin', line: 'rib spokes radiating from the ferrule', composition: 'diagonal leaping figure under spinning disc', texture: 'taffeta glare and sequin scatter' },
    typ: { display: 'n/a — performance object', body: 'n/a', notes: 'band names painted on parasol canopies' },
    lit: { quality: 'hard midday carnival sun', temperature: 'hot', shadow: 'sharp noon shadows on asphalt' },
    ui: { background: 'asphalt gray with color confetti', surface: 'taffeta-bright spinner cards', components: 'parasol-dome round buttons', motion: 'rapid spin-and-leap transitions' },
  },
  {
    n: 'Mexican Ex-Voto Retablo Painting', a: ['Mexican ex-votos', 'Laminitas', 'Retablo ex-voto painting', 'Votive tin paintings'],
    cat: 'Folk Art & Sculpture', c: 'Mexican votive painting on tinplate', e: 'historical',
    o: 'Bajío region, central Mexico', g: 'Mexico, US museum collections', p: 'c. 1800-1940 peak', era: '19th-century Mexico',
    sum: 'Painted tin miracle pictures: peril above, the saint descending on a cloud, and a written Milagro otorgado a... below — folk Catholicism\'s thank-you notes to the shrine wall.',
    desc: 'When crisis struck — accident, fever, lost love — Mexican Catholics commissioned small oil paintings on tinplate: the peril shown in earnest detail, the saint descending on a cloud, and below an inscription beginning Milagro otorgado a... naming the donor. These laminitas were nailed to shrine walls across the Bajío by the thousand. Frida Kahlo collected the panels and borrowed their naive candor and written testimony for her own work.',
    col: [{ h: '#cfc8b8', n: 'tin ground white' }, { h: '#a33b2e', n: 'brick red' }, { h: '#3f5e78', n: 'slate blue' }, { h: '#6b5a34', n: 'dust ochre' }, { h: '#2e2a26', n: 'soot black line' }],
    m: ['tin-plated iron sheets', 'oil-based commercial paints', 'fine bristle brushes'],
    tx: ['scrubbed tin sheen', 'brush-thinned oil wash', 'rust bloom at edges'],
    obj: ['miracle scene laminitas', 'shrine-wall votive clusters', 'donor portrait panels'],
    ex: ['Bajío shrine walls, Guanajuato and Querétaro', '19th-century railroad and mining accident votives', 'Frida Kahlo\'s collected ex-votos, Casa Azul'],
    inf: ['Spanish votive panel tradition', 'Catholic miracle doctrine', 'costumbrismo painting'],
    rel: ['Ex-voto Retablo', 'Lotería Cards', 'La Catrina Iconography'],
    src: [{ n: 'Wikipedia — Ex-voto', u: 'https://en.wikipedia.org/wiki/Ex-voto', t: 'B' }, { n: 'Wikipedia — Retablo', u: 'https://en.wikipedia.org/wiki/Retablo', t: 'B' }],
    tg: ['ex-voto', 'retablo', 'laminita', 'tin painting', 'devotional', 'mexican', 'folk art'],
    pop: 49, niche: true,
    vd: { shape: 'small landscape rectangles in gilt-line frames', line: 'naive firm outline, no perspective discipline', composition: 'peril upper field, saint on cloud, text band below', texture: 'thin oil on slick metal ground' },
    typ: { display: 'hand-lettered Milagro inscription as compositional base', body: 'n/a', notes: 'date, donor name and sometimes painter signature' },
    lit: { quality: 'flat even devotional light', temperature: 'warm', shadow: 'minimal, outlined rather than modeled' },
    ui: { background: 'tin-white neutral', surface: 'framed scene cards with text bands', components: 'gilt-frame outline buttons', motion: 'quiet pin-to-wall fades' },
  },
]
