/**
 * Rebuild wave — MENA & Central Asia r1 (16 entries).
 * Re-authored from scratch after sandbox rollback destroyed the Task 11 wave
 * files. All names real + dedup-checked against existing-names.txt; Wikipedia
 * titles batch-verified via API (2026-09-14): Sedefkari has no EN article —
 * cites Nacre + museums instead; Mamluk Sultanate (Cairo) canonical.
 * Format mirrors curated-seed.ts compact curated format.
 */
export const ENTRIES: any[] = [
  {
    n: 'Sedefkari', a: ['sedef work', 'mother-of-pearl inlay', 'sedefkârlık'],
    cat: 'Regional & Cultural Tradition', c: 'Ottoman nacre-inlay woodcraft', e: 'historical',
    o: 'Istanbul, Ottoman Empire', g: 'Turkey, former Ottoman lands',
    p: '1500s-1920', era: 'Ottoman classical to early Republican',
    sum: 'Ottoman art of inlaid patterns of iridescent mother-of-pearl set into dark walnut or ebony woodwork.',
    desc: 'Sedefkari is the Ottoman craft of cutting thin discs and splinters of mother-of-pearl (sedef) and inlaying them flush into dark woods — walnut, ebony, sometimes rosewood — often wired with brass or silver to form tulips, carnations, interlaced stars and calligraphic medallions. Istanbul and Edirne workshops fitted palace doors, Qur\'an cases, turban stands, writing boxes and the interiors of waterside yalı mansions. The craft survived the empire\'s end in small ateliers and remains a protected Turkish traditional handicraft today.',
    col: [{ h: '#e8e2d4', n: 'nacre white' }, { h: '#4a3627', n: 'walnut brown' }, { h: '#1f1a14', n: 'ebony black' }, { h: '#b08d57', n: 'brass wire gold' }, { h: '#8a9ba8', n: 'pearl grey-blue' }],
    m: ['mother-of-pearl', 'walnut', 'ebony', 'brass wire', 'bone'],
    tx: ['cool iridescent nacre', 'oily dark hardwood', 'fine metal fillets'],
    obj: ['Qur\'an case covers', 'turban stands', 'palace door leaves', 'writing boxes', 'yalı wall panelling'],
    ex: ['Topkapı Palace sedef doors', 'Ottoman Qur\'an cases', 'Istanbul yalı interior shutters'],
    inf: ['Ottoman court ateliers', 'Timurid woodworking', 'Islamic geometric ornament'], rel: ['Khatam Marquetry', 'Ottoman Tombak', 'Iznik Pottery'],
    src: [{ n: 'Wikipedia — Nacre', u: 'https://en.wikipedia.org/wiki/Nacre', t: 'B' }, { n: 'The Metropolitan Museum of Art', u: 'https://www.metmuseum.org', t: 'A' }, { n: 'Victoria and Albert Museum', u: 'https://www.vam.ac.uk', t: 'A' }],
    tg: ['inlay', 'mother-of-pearl', 'ottoman', 'woodwork', 'geometric', 'calligraphic'],
    pop: 32, niche: true,
    vd: { shape: 'star polygons, tulip and carnation sprays, pointed-arch medallions', line: 'brass fillets tracing silhouettes of each nacre piece', composition: 'central roundel with symmetrical quartered fields and narrow borders', texture: 'cool glassy nacre against warm matte hardwood' },
    typ: { display: 'celi sülüs calligraphy in raised gold or nacre', body: 'naskh manuscript hands on gilded borders', notes: 'panels frame inscriptions rather than carry running text' },
    lit: { quality: 'soft interior sheen', temperature: 'warm-toned', shadow: 'shallow relief shadows between inlay and field' },
    ui: { background: 'deep walnut brown with faint wood grain', surface: 'ivory cards with pearl-shimmer edges', components: 'octagonal buttons with brass keylines', motion: 'slow, measured crossfades' },
    par: 'Ottoman decorative arts',
  },
  {
    n: 'Qajar Painting', a: ['Qajar art', 'Qajar court painting'],
    cat: 'Painting Technique & School', c: 'Iranian court painting', e: 'historical',
    o: 'Tehran, Qajar Iran', g: 'Iran',
    p: '1789-1925', era: 'Qajar dynasty',
    sum: 'Florid Iranian court painting of the Qajar era: jewelled oil portraits, lacquerwork and illustrated books.',
    desc: 'Under the Qajar shahs, Iranian painting absorbed European oil technique while keeping Persian profile conventions: monumental portraits of Fath-Ali Shah with enormous black beard, jewelled crowns and brocaded robes; flattened figures set against spray-filled grounds; lacquer pen boxes and mirror cases painted with flowers and single figures. Mihr \'Ali\'s imperial portraits, Sani al-Mulk\'s illustrated One Thousand and One Nights and Kamal al-Molk\'s naturalistic turn mark its arc from court spectacle to academic realism.',
    col: [{ h: '#0f7d6c', n: 'Qajar turquoise' }, { h: '#c22f2f', n: 'lacquer red' }, { h: '#e8c56a', n: 'gold leaf' }, { h: '#2c2c34', n: 'beard black' }, { h: '#f0e6d2', n: 'marble ground' }],
    m: ['oil paint', 'lacquer', 'gold leaf', 'paper', 'mother-of-pearl frames'],
    tx: ['smooth enamel-like oil surface', 'gilded raised ornament', 'silky lacquer'],
    obj: ['imperial portraits', 'qalamdan pen boxes', 'lacquer mirror cases', 'palace wall paintings'],
    ex: ['Mihr \'Ali portraits of Fath-Ali Shah', 'Sani al-Mulk\'s One Thousand and One Nights plates', 'Kamal al-Molk\'s later realism'],
    inf: ['Safavid painting', 'European oil portraiture', 'Zand-era lacquer'], rel: ['Safavid Art', 'Persian Miniature'],
    src: [{ n: 'Wikipedia — Qajar art', u: 'https://en.wikipedia.org/wiki/Qajar_art', t: 'B' }, { n: 'The Metropolitan Museum of Art', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['court painting', 'persian', 'oil', 'lacquer', 'portrait', 'qajar'],
    pop: 41, niche: false,
    vd: { shape: 'frontal figures with wide shoulders and tiny waists', line: 'precise contour drawing over soft modelling', composition: 'central symmetric figure amid sprays of cast blossoms', texture: 'jewelled, enameled, gold-flecked surfaces' },
    typ: { display: 'nasta\'liq cartouche inscriptions', body: 'shikasta hands on documents', notes: 'paintings carry poetic captions in cartouches' },
    lit: { quality: 'flat even court lighting', temperature: 'warm-toned', shadow: 'minimal, decorative' },
    ui: { background: 'pale stone with painted blossom spray', surface: 'arched frames with turquoise and gold', components: 'oval medallion buttons', motion: 'stately, unhurried fades' },
    par: 'Persian painting',
  },
  {
    n: 'Mamluk Metalwork', a: ['Mamluk inlaid brass', 'damascened metalwork'],
    cat: 'Regional & Cultural Tradition', c: 'Cairo-Aleppo metalcraft', e: 'historical',
    o: 'Cairo & Aleppo, Mamluk Sultanate', g: 'Egypt, Syria',
    p: '1250-1517', era: 'Mamluk era',
    sum: 'Brass vessels of Mamluk Egypt and Syria crowded with silver-inlaid blazons, calligraphy and courtly scenes.',
    desc: 'Mamluk metalworkers in Cairo and Aleppo raised brass candlesticks, basins, ewers and mosque lamps, then chased and inlaid them with silver and gold: roundels of musicians, hunters and polo players alternating with bands of thuluth calligraphy and the armorial blazons of emirs — a cup, a sword, an eagle. The Baptistère de Saint-Louis in the Louvre, signed by Muhammad ibn al-Zayn, is the most celebrated example. After the Ottoman conquest the style simplified into export wares for Europe and the Ottoman court.',
    col: [{ h: '#8c6f3f', n: 'brass gold' }, { h: '#c0c0c8', n: 'silver inlay' }, { h: '#3a2f23', n: 'patina brown' }, { h: '#151312', n: 'niello black' }],
    m: ['brass', 'silver wire', 'gold leaf', 'copper'],
    tx: ['dully gleaming metal', 'fine chased detail', 'flush silver damascene'],
    obj: ['candlesticks', 'basins', 'ewers', 'mosque lamps', 'inkwells'],
    ex: ['Baptistère de Saint-Louis (Louvre)', 'blazoned candlesticks of the Sultan Hasan complex', 'Qaitbay-era basins'],
    inf: ['Seljuk metalwork', 'Ayyubid inlay traditions', 'Fatimid craftsmanship'], rel: ['Mamluk Enameled Glass', 'Mamluk Architecture', 'Ottoman Tombak'],
    src: [{ n: 'Wikipedia — Mamluk Sultanate', u: 'https://en.wikipedia.org/wiki/Mamluk_Sultanate', t: 'B' }, { n: 'Musée du Louvre', u: 'https://www.louvre.fr', t: 'A' }],
    tg: ['metalwork', 'brass', 'inlay', 'mamluk', 'calligraphy', 'blazon'],
    pop: 38, niche: true,
    vd: { shape: 'globular and hemispherical vessels on low feet', line: 'medallion roundels linked by trailing arabesque bands', composition: 'registered bands: calligraphy, figures, blazons', texture: 'dense silver-on-brass damascene glitter' },
    typ: { display: 'monumental thuluth on naskh ground bands', body: 'naskh benedictory inscriptions', notes: 'blazon emblems record patronage like makers\' marks' },
    lit: { quality: 'point highlights from candle flames', temperature: 'warm-toned', shadow: 'deep interior vessel shadows' },
    ui: { background: 'aged brass gradient', surface: 'engraved panels with silver keylines', components: 'medallion-shaped buttons', motion: 'glinting, lantern-like transitions' },
    par: 'Islamic metalwork',
  },
  {
    n: 'Mamluk Enameled Glass', a: ['mosque lamps', 'Mamluk gilded glass'],
    cat: 'Religious & Sacred Art', c: 'Syro-Egyptian glassware', e: 'historical',
    o: 'Damascus & Cairo', g: 'Egypt, Syria',
    p: '1250-1400', era: 'Mamluk era',
    sum: 'Free-blown mosque lamps and beakers enamel-painted in blue, red and green with gilded calligraphy.',
    desc: 'Between the thirteenth and fifteenth centuries, glasshouses of Damascus and Cairo produced the Islamic world\'s most prized painted glass: balloon-shaped mosque lamps hung by chains, their bodies enamel-painted with Light-verse inscriptions, emiral blazons and scrolling foliage in cobalt, ruby and white over gilt. The finest wares lit the sanctuaries of sultanic madrasas; smaller beakers and goblets travelled as luxury exports. Quality collapsed after about 1400, making surviving lamps the benchmarks of the craft.',
    col: [{ h: '#1d4e89', n: 'cobalt enamel' }, { h: '#a32638', n: 'ruby enamel' }, { h: '#d4af37', n: 'gilt scroll' }, { h: '#e9e4d8', n: 'clear glass' }, { h: '#5d6b52', n: 'olive green' }],
    m: ['clear glass', 'enamel', 'gold', 'chain mounts'],
    tx: ['smooth glassy body', 'raised enamel relief', 'burnished gold flecks'],
    obj: ['mosque lamps', 'goblets', 'beakers', 'bottles'],
    ex: ['Mosque lamp of the Sultan Hasan mosque', 'blazoned Damascus beakers', 'Ardabil shrine lamps (related Persian group)'],
    inf: ['Ayyubid glass', 'Byzantine glassmaking', 'Fatimid traditions'], rel: ['Mamluk Metalwork', 'Mamluk Architecture'],
    src: [{ n: 'Wikipedia — Islamic glass', u: 'https://en.wikipedia.org/wiki/Islamic_glass', t: 'B' }, { n: 'The Metropolitan Museum of Art', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['glass', 'enamel', 'gilded', 'mamluk', 'mosque lamp', 'calligraphy'],
    pop: 35, niche: true,
    vd: { shape: 'baluster lamps with flared foot and splayed neck', line: 'calligraphic bands swinging with the vessel curve', composition: 'three horizontal registers with pendant roundels', texture: 'glassy sheen under matte enamel' },
    typ: { display: 'white thuluth verses on blue panels', body: 'naskh benedictions to the donor', notes: 'Qur\'anic Light verse standard on lamps' },
    lit: { quality: 'transmitted glow when lit', temperature: 'warm-toned', shadow: 'amber pools under hanging lamps' },
    ui: { background: 'deep translucent blue', surface: 'gilded arabesque frames', components: 'lamp-shaped icons and badges', motion: 'flickering gentle pulses' },
    par: 'Islamic glass',
  },
  {
    n: 'Mashrabiya', a: ['shanasheel', 'mashrabiyya', 'musharabiye'],
    cat: 'Architectural Style', c: 'turned-wood lattice screens', e: 'historical',
    o: 'Egypt & the Levant', g: 'Middle East, North Africa',
    p: '1100s-1900s', era: 'medieval to modern Islamic world',
    sum: 'Projecting lattice-screened wooden bay windows filtering light, air and privacy across the Islamic city.',
    desc: 'The mashrabiya is a closed wooden oriel whose face is a lattice of hundreds of turned balusters, from coarse bottle shapes to mille-fieux fineness. Set over streets in Cairo, Damascus, Baghdad and beyond, it cooled interiors by drawing breezes across water jars, softened glare, granted household privacy while keeping street sightlines, and displayed status through lattice fineness. Modern architects revived the principle in kinetic and parametric sun-screens, from Jean Nouvel\'s Institut du Monde Arabe to contemporary Gulf facades.',
    col: [{ h: '#7a5c3e', n: 'aged cedar' }, { h: '#a9834f', n: 'honey wood' }, { h: '#d9c7a7', n: 'filtered light' }, { h: '#3f3123', n: 'deep shade' }],
    m: ['turned wood balusters', 'cedar', 'teak pegs', 'iron brackets'],
    tx: ['thousands of tiny turned beads', 'sun-bleached grain', 'lace-like shadow'],
    obj: ['street-facing oriel windows', 'room dividers', 'stairwell screens', 'rooftop enclosures'],
    ex: ['Bayt Al-Suhaymi, Cairo', 'Damascene houses with shanasheel', 'Institut du Monde Arabe diaphragm screens'],
    inf: ['Islamic privacy architecture', 'timber turning traditions', 'courtyard climate design'], rel: ['Ottoman Architecture', 'Arabesque'],
    src: [{ n: 'Wikipedia — Mashrabiya', u: 'https://en.wikipedia.org/wiki/Mashrabiya', t: 'B' }, { n: 'ArchDaily', u: 'https://www.archdaily.com', t: 'C' }],
    tg: ['lattice', 'wood', 'architecture', 'privacy', 'shade', 'islamic'],
    pop: 47, niche: false,
    vd: { shape: 'projecting polygonal bay of repeating geometric cells', line: 'vertical rhythm of turned balusters', composition: 'nested star-and-jar lattice in graded densities', texture: 'pierced light, dusty wood, silhouette lace' },
    typ: { display: 'painted shop signage behind grilles', body: 'hand-painted trade boards', notes: 'lettering through lattice reads as pattern' },
    lit: { quality: 'dappled, filtered', temperature: 'cool-toned', shadow: 'lattice lace across floors' },
    ui: { background: 'sun-cream with lattice shadow', surface: 'warm wood frames', components: 'turned-finial icons', motion: 'slow light-sweep pans' },
    par: 'Islamic architecture',
  },
  {
    n: 'Khatam Marquetry', a: ['khatam-kari', 'khatam', 'Persian micro-mosaic'],
    cat: 'Regional & Cultural Tradition', c: 'Persian micro-inlay', e: 'historical',
    o: 'Isfahan & Shiraz, Iran', g: 'Iran',
    p: '1500s-present', era: 'Safavid to present',
    sum: 'Persian micro-mosaic of star-patterned inlay built from hair-thin strips of wood, bone and wire.',
    desc: 'Khatam-kari builds geometric stars from glued bundles — maple, jujube, walnut, brass and silver wire, bone — sliced crosswise into thin tiles that tessellate into dense six- and eight-pointed star fields. Safavid workshops brought the technique to its height for doors, Qur\'an stands, mirror cases and boxes; Shiraz and Isfahan ateliers still cover jewelry cases, chessboards and gift objects. The best khatam reads as textile: a shimmering galaxy of pinpoint geometry under a glass-smooth surface.',
    col: [{ h: '#d9b98a', n: 'maple cream' }, { h: '#6b4423', n: 'jujube brown' }, { h: '#c9a227', n: 'brass star' }, { h: '#e9e2d0', n: 'bone white' }, { h: '#2f2a24', n: 'walnut ground' }],
    m: ['maple', 'jujube wood', 'brass wire', 'bone', 'walnut'],
    tx: ['glass-smooth oiled surface', 'pinpoint geometric grain', 'metal glints'],
    obj: ['pen boxes', 'jewelry caskets', 'Qur\'an stands', 'chessboards', 'picture frames'],
    ex: ['Safavid khatam doors of Isfahan', 'Shiraz khatam-atelier boxes', 'Golestan Palace fittings'],
    inf: ['Safavid court workshops', 'Islamic geometry', 'Timurid marquetry'], rel: ['Sedefkari', 'Qajar Painting'],
    src: [{ n: 'Wikipedia — Khatam', u: 'https://en.wikipedia.org/wiki/Khatam', t: 'B' }, { n: 'Victoria and Albert Museum', u: 'https://www.vam.ac.uk', t: 'A' }],
    tg: ['marquetry', 'inlay', 'persian', 'geometric', 'star pattern', 'woodwork'],
    pop: 40, niche: true,
    vd: { shape: 'continuous six- and eight-point star tessellation', line: 'hair-fine metal outlines around every tile', composition: 'central medallion dissolving into all-over micro-star field', texture: 'satin-smooth, dust-fine geometry' },
    typ: { display: 'inlaid nasta\'liq titles on lids', body: 'calligraphic gift inscriptions', notes: 'lettering rarely runs across the star field' },
    lit: { quality: 'even, cabinet-like', temperature: 'warm-toned', shadow: 'only from relief edges' },
    ui: { background: 'cream with faint star lattice', surface: 'wood-tone cards with brass hairlines', components: 'star-pointed buttons', motion: 'precise micro-shifts' },
    par: 'Islamic decorative arts',
  },
  {
    n: 'Termeh Weaving', a: ['Yazd termeh', 'Persian brocade'],
    cat: 'Textile & Craft', c: 'Persian brocade weaving', e: 'regional_tradition',
    o: 'Yazd, Iran', g: 'Iran',
    p: '1500s-present', era: 'Safavid to present',
    sum: 'Warp-faced Persian brocade of Yazd, dense with paisley boteh rows and gold-wrapped silk.',
    desc: 'Termeh is a luxurious handwoven cloth of Yazd: fine silk warps crossed by densely beaten wefts so the surface shimmers with rows of tiny boteh paisleys, cypress trees and arabesques, often with gold- or silver-wrapped thread. Traditionally cut into ceremonial cloths, trousseau pieces, sanctuary coverings and elite robes, the weave is slow — a day\'s work may advance centimetres. Machine competition thinned the workshops, but a handful of Yazd looms keep the craft alive as heritage textile.',
    col: [{ h: '#8c1f28', n: 'madder crimson' }, { h: '#1f5c4d', n: 'deep green' }, { h: '#d4af37', n: 'gilt thread' }, { h: '#27476e', n: 'indigo ground' }, { h: '#efe3c8', n: 'ivory silk' }],
    m: ['silk', 'gold-wrapped thread', 'cotton warp', 'wool weft'],
    tx: ['dense brocade sheen', 'raised weft ridges', 'metallic sparkle'],
    obj: ['ceremonial cloth rolls', 'cushion faces', 'table runners', 'sanctuary coverings'],
    ex: ['Yazd boteh termeh panels', 'Qajar-era termeh robes', 'present-day Yazd workshop weaves'],
    inf: ['Safavid brocade looms', 'paisley shawl trade', 'Persian garden symbolism'], rel: ['Paisley Pattern', 'Pateh Embroidery', 'Bukhara Embroidery'],
    src: [{ n: 'Wikipedia — Termeh', u: 'https://en.wikipedia.org/wiki/Termeh', t: 'B' }, { n: 'Victoria and Albert Museum', u: 'https://www.vam.ac.uk', t: 'A' }],
    tg: ['weaving', 'brocade', 'paisley', 'persian', 'silk', 'yazd'],
    pop: 34, niche: true,
    vd: { shape: 'endless diagonal rows of boteh and cypress repeats', line: 'warp-striped precision framing weft motifs', composition: 'bordered fields with flat-woven ends', texture: 'heavy drape with metallic flicker' },
    typ: { display: 'embroidered merchant labels', body: 'nasta\'liq gift inscriptions on selvedge', notes: 'text carries dedication rather than pattern' },
    lit: { quality: 'sheened directional glow', temperature: 'warm-toned', shadow: 'soft folds between boteh rows' },
    ui: { background: 'indigo with gold paisley scatter', surface: 'crimson ribbon trims', components: 'paisley-shaped toggles', motion: 'luxurious slow slides' },
    par: 'Persian textiles',
  },
  {
    n: 'Pateh Embroidery', a: ['pateh-duzi', 'Kerman pateh'],
    cat: 'Textile & Craft', c: 'Kermani crewel embroidery', e: 'regional_tradition',
    o: 'Kerman, Iran', g: 'Iran',
    p: '1700s-present', era: 'Zand to present',
    sum: 'Wide Kermani wool panels embroidered edge-to-edge with silk paisleys and tree-of-life scenes.',
    desc: 'Pateh is Kerman\'s grand textile: broad widths of hand-woven wool (ariz) completely covered by double-crewel silk stitches — no ground left bare — forming paisley boteh borders, central cypress trees and narrative scenes in deep madders, greens and blues. Traditionally made by women working collectively for dowries and ceremonial gift cloth, pateh absorbed carpet composition at fabric scale. Twentieth-century revivals turned famous panels into museum pieces; workshops in Kerman still teach the stitch.',
    col: [{ h: '#8e2a2a', n: 'Kerman red' }, { h: '#2e5d43', n: 'cypress green' }, { h: '#dcae5e', n: 'saffron' }, { h: '#243b57', n: 'indigo' }, { h: '#efe0c3', n: 'wool cream' }],
    m: ['wool ground cloth', 'silk thread', 'natural dyes'],
    tx: ['dense satin-stitch pile', 'velvety wool nap', 'silk sheen lines'],
    obj: ['ceremonial wall panels', 'dowry cloths', 'prayer spreads', 'gift tapestries'],
    ex: ['Kerman pateh with cypress-and-boteh field', 'large court-scene pateh panels', 'contemporary workshop replicas'],
    inf: ['Kerman carpet design', 'paisley shawl vocabulary', 'Zand court patronage'], rel: ['Termeh Weaving', 'Paisley Pattern', 'Persian Carpet Weaving'],
    src: [{ n: 'Wikipedia — Pateh', u: 'https://en.wikipedia.org/wiki/Pateh', t: 'B' }, { n: 'Victoria and Albert Museum', u: 'https://www.vam.ac.uk', t: 'A' }],
    tg: ['embroidery', 'paisley', 'kerman', 'wool', 'silk', 'persian'],
    pop: 30, niche: true,
    vd: { shape: 'carpet-style medallion with sweeping boteh borders', line: 'twisted silk threads laid flat in parallel', composition: 'fully covered ground, no negative space', texture: 'raised embroidery ridges over soft wool' },
    typ: { display: 'occasional woven dedication bands', body: 'poetic couplets in nasta\'liq', notes: 'inscriptions woven into the border ground' },
    lit: { quality: 'soft diffuse', temperature: 'warm-toned', shadow: 'gentle stitch shadows' },
    ui: { background: 'wool cream texture', surface: 'embroidered corner frames', components: 'boteh-shaped buttons', motion: 'stitch-like ticks' },
    par: 'Persian textiles',
  },
  {
    n: 'Kubachi Silver', a: ['Kubachi metalwork', 'Dagestan chasing'],
    cat: 'Regional & Cultural Tradition', c: 'Dagestani silversmithing', e: 'regional_tradition',
    o: 'Kubachi, Dagestan', g: 'Northeast Caucasus',
    p: '1300s-present', era: 'medieval to Soviet and post-Soviet',
    sum: 'Mountain-village silver of Dagestan: deeply chased, nielloed and gilded vessels, chains and arms.',
    desc: 'Kubachi, a clustered stone village in the Dagestan mountains, has produced smiths for centuries — first for Caucasian arms and harness, later for exhibition-grade silver: great water vessels (kumgans), trays, chains and dagger hilts covered in dense engraving, niello blackening, gilding and inset stones. Soviet power turned the workshops into an artel whose pieces toured exhibitions; hereditary families still pass designs from father to son. Museum collections from Moscow to the Met hold Kubachi masters\' work.',
    col: [{ h: '#b9bec4', n: 'silver grey' }, { h: '#141414', n: 'niello black' }, { h: '#c9a227', n: 'gilt accent' }, { h: '#5a2d2d', n: 'garnet stone' }, { h: '#3f4a3c', n: 'turquoise-set green' }],
    m: ['silver', 'niello', 'gold', 'garnets', 'turquoise'],
    tx: ['deep hand-chased relief', 'blackened line work', 'polished stone glints'],
    obj: ['kumgan water vessels', 'ceremonial chains', 'dagger hilts', 'trays and goblets'],
    ex: ['Kubachi kumgans in Russian museum collections', 'artel-era exhibition silver', 'hereditary-master dagger hilts'],
    inf: ['Caucasian arms decoration', 'Persian metalwork', 'Byzantine filigree heritage'], rel: ['Kaitag Embroidery', 'Caucasian Carpet Culture', 'Ottoman Tombak'],
    src: [{ n: 'Wikipedia — Kubachi', u: 'https://en.wikipedia.org/wiki/Kubachi', t: 'B' }, { n: 'The Metropolitan Museum of Art', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['silver', 'chasing', 'niello', 'caucasus', 'dagestan', 'metalwork'],
    pop: 31, niche: true,
    vd: { shape: 'bulbous vessels with tall necks and domed lids', line: 'engraved scrolling filled edge to edge', composition: 'horror vacui banding around central medallions', texture: 'bright silver against velvet niello' },
    typ: { display: 'Arabic benediction cartouches', body: 'engraved maker marks', notes: 'inscriptions merge with ornament fields' },
    lit: { quality: 'hard metallic glints', temperature: 'cool-toned', shadow: 'black niello pools in engraving' },
    ui: { background: 'slate with silver scrollwork', surface: 'embossed metal panels', components: 'gem-set round buttons', motion: 'bright snappy glints' },
    par: 'Caucasian decorative arts',
  },
  {
    n: 'Jewish Micrography', a: ['microcalligraphy', 'masoretic micrography', 'Mikrografie'],
    cat: 'Religious & Sacred Art', c: 'Hebrew micro-calligraphy', e: 'historical',
    o: 'Middle Eastern & Mediterranean scriptoria', g: 'Jewish diaspora worldwide',
    p: '900s-present', era: 'medieval to contemporary',
    sum: 'Tiny Hebrew script drawn into animal shapes and arabesques filling manuscript margins and modern prints.',
    desc: 'Jewish micrography writes the masorah — the scribal notes guarding biblical text accuracy — in letters smaller than a grain, then bends the lines into lions, birds, fish and towers filling the margins of Hebrew Bibles. Developed by Masoretes around the tenth century, it flourished in Spanish, French and Yemenite manuscript schools; legal tradition forbade figurative illustration, so letters themselves became the image. Modern Israeli artists revived the form in framed prints, ketubot and calligraphic panoramas.',
    col: [{ h: '#e7dfc8', n: 'vellum cream' }, { h: '#2b1d12', n: 'iron-gall brown-black' }, { h: '#8c2f2f', n: 'rubrication red' }, { h: '#445b74', n: 'blue accent' }],
    m: ['parchment', 'iron-gall ink', 'reed pen', 'paper (modern)'],
    tx: ['hairline ink webs', 'skin grain', 'crisp letter clusters'],
    obj: ['Hebrew Bible margins', 'masorah animal figures', 'wedding ketubot', 'framed calligraphic prints'],
    ex: ['Masoretic micrography of the Leningrad Codex', 'Spanish micrography Bible margins', 'contemporary Israeli microcalligraphy prints'],
    inf: ['Masoretic scribal practice', 'aniconic Jewish law', 'Islamic arabesque margins'], rel: ['Ketubah Illumination', 'Illuminated Manuscripts', 'Haggadah Illumination'],
    src: [{ n: 'Wikipedia — Micrography', u: 'https://en.wikipedia.org/wiki/Micrography', t: 'B' }, { n: 'The Jewish Museum', u: 'https://thejewishmuseum.org', t: 'A' }],
    tg: ['calligraphy', 'hebrew', 'manuscript', 'micrography', 'jewish', 'aniconic'],
    pop: 42, niche: false,
    vd: { shape: 'animal and architectural silhouettes formed entirely of text', line: 'single continuous hairline letters bent into contours', composition: 'text blocks framed by figurative letter-margins', texture: 'fine nib texture at near-invisible scale' },
    typ: { display: 'masoretic micro-script itself as image', body: 'square Hebrew book hand', notes: 'reading requires magnification — text as ornament' },
    lit: { quality: 'bright study lighting', temperature: 'neutral-toned', shadow: 'none — flat ink on skin' },
    ui: { background: 'vellum texture', surface: 'ruled manuscript frames', components: 'letterformed dividers', motion: 'zoom-reveal animations' },
    par: 'Jewish manuscript arts',
  },
  {
    n: 'Ketubah Illumination', a: ['illuminated ketubot', 'decorated marriage contracts'],
    cat: 'Religious & Sacred Art', c: 'Jewish marriage-contract art', e: 'historical',
    o: 'Italy, Netherlands & Mediterranean Jewish communities', g: 'Jewish diaspora',
    p: '1500s-present', era: 'Renaissance to contemporary',
    sum: 'Elaborately painted Jewish marriage contracts framing legal text with birds, zodiacs and architectural borders.',
    desc: 'The ketubah records a Jewish bridegroom\'s obligations in Aramaic legalese — and in many communities that document became a canvas. Italian Renaissance and Baroque ketubot from Venice, Florence and Ancona enclose the text in trompe-l\'oeil architecture, putti, birds and zodiac medallions; Sephardi and Mizrahi traditions favor papercut lacework and floral micro-architecture. Because the contract must remain legible, illumination always frames rather than fills, making law and ornament co-guarantors of the marriage.',
    col: [{ h: '#d9b23a', n: 'gold field' }, { h: '#8c2f2f', n: 'contract red' }, { h: '#3f6b4f', n: 'wreath green' }, { h: '#4a5f8a', n: 'putti blue' }, { h: '#f3ead2', n: 'contract parchment' }],
    m: ['parchment', 'gouache', 'gold paint', 'papercut layers', 'ink'],
    tx: ['smooth painted vellum', 'cut-paper lace edges', 'gilt highlights'],
    obj: ['framed marriage contracts', 'papercut ketubot', 'zodiac border plates', 'anniversary gifts'],
    ex: ['Venetian Baroque ketubot with trompe-l\'oeil columns', 'Livorno papercut ketubot', 'contemporary artist-made ketubot'],
    inf: ['Italian Renaissance ornament', 'Hebrew manuscript illumination', 'papercut folk art'], rel: ['Jewish Micrography', 'Mizrah Wall Plaques', 'Haggadah Illumination'],
    src: [{ n: 'Wikipedia — Ketubah', u: 'https://en.wikipedia.org/wiki/Ketubah', t: 'B' }, { n: 'The Jewish Museum', u: 'https://thejewishmuseum.org', t: 'A' }],
    tg: ['ketubah', 'jewish', 'illumination', 'papercut', 'marriage', 'manuscript'],
    pop: 38, niche: true,
    vd: { shape: 'text cartouche held by columns, birds and crowns', line: 'fine pen ruling around painted panels', composition: 'text center, ornament perimeter, zodiac corners', texture: 'glossy gouache on matte skin' },
    typ: { display: 'formal square Aramaic contract script', body: 'cursive Italian-Jewish additions', notes: 'two witness signatures anchor the design' },
    lit: { quality: 'even gallery light', temperature: 'warm-toned', shadow: 'subtle drop shadows of papercut layers' },
    ui: { background: 'parchment with corner wreaths', surface: 'gold-rule frames', components: 'crown-topped certificates', motion: 'unfolding scroll reveals' },
    par: 'Jewish manuscript arts',
  },
  {
    n: 'Mizrah Wall Plaques', a: ['mizrach plaques', 'east-wall tablets'],
    cat: 'Religious & Sacred Art', c: 'Jewish devotional wall art', e: 'regional_tradition',
    o: 'Central & Eastern Europe, Ottoman lands', g: 'Jewish diaspora',
    p: '1600s-1900s', era: 'early modern to modern',
    sum: 'Ornate tablets marking east — the direction of prayer — blending Hebrew verses with crowns and animals.',
    desc: 'A mizrah names the direction of Jerusalem toward which Jews pray; in diaspora homes the word became a wall fixture. Papercut plaques from Poland and Ukraine lace the letters of "mizrah" into deer, lions, birds and candelabra; painted and printed versions from Bohemia, Morocco and Iraq add Zodiacs, tomb imagery of righteous figures and household dedications. Placed on the eastern wall near the seat of the paterfamilias, the plaque made orientation devotional and decorative at once.',
    col: [{ h: '#c9a227', n: 'crown gold' }, { h: '#2f4f3e', n: 'deer green' }, { h: '#8c2f2f', n: 'plaque red' }, { h: '#f1e8d2', n: 'paper ground' }, { h: '#23364d', n: 'verse ink' }],
    m: ['paper', 'parchment', 'gouache', 'wood backing', 'silver (elite examples)'],
    tx: ['cut-paper lace', 'hand-painted panels', 'engraved printing plates'],
    obj: ['east-wall plaques', 'papercut mizrachs', 'printed holiday decorations', 'shiviti tables (related)'],
    ex: ['Polish papercut mizrachs with lions and deer', 'Bohemian painted Mizrah tablets', 'Moroccan mizrah tiles'],
    inf: ['Jewish papercut folk art', 'shiviti tablet tradition', 'local heraldic craft'], rel: ['Ketubah Illumination', 'Jewish Micrography', 'Papercutting'],
    src: [{ n: 'Wikipedia — Mizrah', u: 'https://en.wikipedia.org/wiki/Mizrah', t: 'B' }, { n: 'YIVO Encyclopedia', u: 'https://yivo.org', t: 'B' }],
    tg: ['jewish', 'papercut', 'wall art', 'folk', 'hebrew', 'devotional'],
    pop: 33, niche: true,
    vd: { shape: 'arched tablet flanked by animals and crown', line: 'lace-fine papercut filaments', composition: 'word MIZRAH central, verses ringing it', texture: 'airy cut paper over dark backing' },
    typ: { display: 'large ornamental MIZRAH letters', body: 'small psalm and blessing verses', notes: 'letterforms doubled as enclosures for imagery' },
    lit: { quality: 'soft domestic', temperature: 'warm-toned', shadow: 'paper lifts casting thread shadows' },
    ui: { background: 'cream lace-paper texture', surface: 'gold-crowned frames', components: 'arched plaques as cards', motion: 'delicate paper-fold transitions' },
    par: 'Jewish folk art',
  },
  {
    n: 'Bukhara Embroidery', a: ['Bukharan suzani', 'Bukhara silk embroidery'],
    cat: 'Textile & Craft', c: 'Uzbek court embroidery', e: 'regional_tradition',
    o: 'Emirate of Bukhara', g: 'Central Asia, Uzbekistan',
    p: '1700s-1900s', era: 'Manghit emirate',
    sum: 'Emirate-of-Bukhara silk embroideries: giant medallion hangings in brilliant greens, pinks and oranges.',
    desc: 'Under the Manghit emirs, Bukhara workshops embroidered colossal suzani-family hangings — palak, borchu and joynamaz — in silk so intense the palettes shift to acid greens, pinks and oranges unlike other Uzbek schools. Great rosette medallions, sprays of almond blossoms and fine black outlining cover guest-room walls, wedding alcoves and horse trappings of the emirate elite. Court ateliers mixed Persian floral refinement with Uzbek steppe boldness, and surviving pieces anchor Central Asian textile collections worldwide.',
    col: [{ h: '#b8336a', n: 'Bukhara pink' }, { h: '#4c9a2a', n: 'acid green' }, { h: '#e07b39', n: 'apricot orange' }, { h: '#1f1f1f', n: 'outline black' }, { h: '#f2e9d4', n: 'cotton ground' }],
    m: ['cotton ground cloth', 'silk floss', 'natural dyes'],
    tx: ['fine chain-stitch silk', 'firm even tension', 'saturated dye glow'],
    obj: ['palak wall hangings', 'borchu door curtains', 'prayer mats', 'horse covers'],
    ex: ['palak hangings with giant rosette medallions', 'emirate wedding alcove sets', 'collections of the Museum of Applied Arts, Tashkent'],
    inf: ['Persian floral embroidery', 'Uzbek nomad applique', 'court workshop organization'], rel: ['Suzani Embroidery', 'Kazakh felt traditions', 'Tush Kyiz'],
    src: [{ n: 'Wikipedia — Suzani (textile)', u: 'https://en.wikipedia.org/wiki/Suzani_(textile)', t: 'B' }, { n: 'Victoria and Albert Museum', u: 'https://www.vam.ac.uk', t: 'A' }],
    tg: ['embroidery', 'suzani', 'bukhara', 'uzbek', 'silk', 'medallion'],
    pop: 35, niche: true,
    vd: { shape: 'large rosette medallions with branching blossom sprays', line: 'fine black outlines defining every petal', composition: 'symmetrical field centered on one or three medallions', texture: 'glossy floss over matte cotton' },
    typ: { display: 'occasional woven owner marks', body: 'cursive dedication stitches', notes: 'text rare — ornament dominates' },
    lit: { quality: 'bright courtyard daylight', temperature: 'warm-toned', shadow: 'soft silks raise faint shadows' },
    ui: { background: 'cream cotton weave', surface: 'medallion-framed cards', components: 'blossom-dot buttons', motion: 'blooming radial reveals' },
    par: 'Central Asian embroidery',
  },
  {
    n: 'Kyrgyz Tush Kyiz', a: ['tush-kiiz', 'Kyrgyz wall hanging'],
    cat: 'Textile & Craft', c: 'Kyrgyz marriage embroidery', e: 'regional_tradition',
    o: 'Kyrgyzstan', g: 'Kyrgyzstan, Central Asia',
    p: '1800s-present', era: 'nomad household to national craft',
    sum: 'Large embroidered wall hangings stitched by Kyrgyz families to hang behind a bride in the yurt.',
    desc: 'A tush kyiz is a Kyrgyz family\'s most treasured textile: a broad cotton or velvet panel embroidered for a daughter\'s marriage and hung above her place in the yurt or home, often kept for decades and passed down. Designs burst with bright silk — blooming gardens, pomegranates, birds, mountain and stream motifs worked in chain and satin stitch over fringed borders — symbolizing wishes of fertility and abundance for the new household. Mothers, grandmothers and neighbours stitch together in the months before the wedding.',
    col: [{ h: '#c0284a', n: 'wedding red' }, { h: '#3a7d44', n: 'garden green' }, { h: '#e8b62c', n: 'sun gold' }, { h: '#2b4a8b', n: 'stream blue' }, { h: '#f5efe0', n: 'cotton white' }],
    m: ['cotton or velvet ground', 'silk and cotton floss', 'fringe cord'],
    tx: ['thick embroidered relief', 'fringed edges', 'dense color blocks'],
    obj: ['marriage wall hangings', 'fringed door textiles', 'yurt decor sets'],
    ex: ['multi-generation family tush kyiz', 'Bishkek craft-fair award panels', 'museum collections in Bishkek'],
    inf: ['nomad felt-decor tradition', 'Kyrgyz shyrdak color sense', 'Soviet folk-art exhibitions'], rel: ['Bukhara Embroidery', 'Shyrdak Felt Carpets', 'Suzani Embroidery'],
    src: [{ n: 'Wikipedia — Tush kyiz', u: 'https://en.wikipedia.org/wiki/Tush_kyiz', t: 'B' }, { n: 'UNESCO Intangible Heritage (Kyrgyz felt arts context)', u: 'https://ich.unesco.org', t: 'A' }],
    tg: ['embroidery', 'kyrgyz', 'yurt', 'marriage', 'wall hanging', 'central asia'],
    pop: 32, niche: true,
    vd: { shape: 'central garden burst with symmetric corner growths', line: 'bold chain-stitch contours', composition: 'top-heavy panel ending in long fringe', texture: 'plush floss ridges over flat cloth' },
    typ: { display: 'occasional embroidered family initials', body: 'no running text', notes: 'purely pictorial textile tradition' },
    lit: { quality: 'bright yurt crown-light', temperature: 'warm-toned', shadow: 'fringe shadows sway on walls' },
    ui: { background: 'white felt texture', surface: 'embroidered border frames', components: 'pomegranate-shaped icons', motion: 'fringe-sway transitions' },
    par: 'Central Asian embroidery',
  },
  {
    n: 'Ottoman Tombak', a: ['tombac ware', 'gilded copper vessels'],
    cat: 'Regional & Cultural Tradition', c: 'Ottoman gilt-copper craft', e: 'historical',
    o: 'Istanbul, Ottoman Empire', g: 'Turkey, Balkans, Arab provinces',
    p: '1500s-1800s', era: 'Ottoman classical to late',
    sum: 'Ottoman copper-alloy vessels gilded warm as gold, from palace ewers to dervish bowls.',
    desc: 'Tombak — the Ottoman copper-zinc alloy gilded to a soft gold glow — served wherever silver was barred or impractical: palace coffee sets, sherbet jugs, hand-washing ewers and basins, dervish kashkul bowls, mirror frames and mosque fittings. Topkapı workshops and provincial coppersmiths hammered, chased and inlaid the metal with elegant tulip and carnation handles, faceted bodies and calligraphic bands. The warm gilt sheen defined Ottoman table ceremony, and surviving pieces still anchor Turkish and European collections.',
    col: [{ h: '#c9963f', n: 'tombak gold' }, { h: '#8a5a2b', n: 'copper shadow' }, { h: '#e6d5ae', n: 'polish highlight' }, { h: '#4a3627', n: 'walnut table' }],
    m: ['copper-zinc alloy', 'gold amalgam gilding', 'silver inlay (fine pieces)'],
    tx: ['hammered facets', 'soft gilt glow', 'chased line detail'],
    obj: ['coffee pots and cups', 'ewer-and-basin sets', 'kashkul dervish bowls', 'mirror frames'],
    ex: ['Topkapı Palace tombak ewer sets', 'faceted sherbet jugs', 'engraved dervish kashkuls'],
    inf: ['Islamic metalwork tradition', 'Persian vessel forms', 'court ceremony protocol'], rel: ['Mamluk Metalwork', 'Sedefkari', 'Turkish Coffee Culture'],
    src: [{ n: 'Wikipedia — Tombac', u: 'https://en.wikipedia.org/wiki/Tombac', t: 'B' }, { n: 'Topkapı Palace Museum', u: 'https://www.topkapisaray.gov.tr', t: 'A' }],
    tg: ['metalwork', 'gilded', 'ottoman', 'copper', 'vessels', 'ceremony'],
    pop: 33, niche: true,
    vd: { shape: 'faceted globular bodies with tapering spouts and domed lids', line: 'chased arabesques following the profiles', composition: 'paired ewer-basin symmetry for ritual use', texture: 'warm satin gilt over hammer marks' },
    typ: { display: 'engraved founder inscriptions', body: 'calligraphic ownership bands', notes: 'inscriptions mark dedications to mosques' },
    lit: { quality: 'candlelight-focused glints', temperature: 'warm-toned', shadow: 'dark facet planes alternate with glow' },
    ui: { background: 'deep bronze gradient', surface: 'gilt-panel cards', components: 'faceted round buttons', motion: 'slow warm gleams' },
    par: 'Ottoman decorative arts',
  },
  {
    n: 'Coptic Iconography', a: ['Coptic wall painting', 'Coptic sacred art'],
    cat: 'Religious & Sacred Art', c: 'Egyptian Christian sacred painting', e: 'historical',
    o: 'Egypt', g: 'Egypt, Nubia, Monastic communities',
    p: '200s-1300s (revival 1800s)', era: 'Late Antique to medieval, modern revival',
    sum: 'Egyptian Christian painting of frontal wide-eyed saints, from encaustic portraits to monastery murals.',
    desc: 'Coptic iconography grows from Roman-Egyptian funerary portraits into one of Christianity\'s oldest continuous image traditions: wide, staring eyes; frontal flattened bodies; bold outline; and strong local color characterize saints, monks and Christ in monasteries like Saint Anthony\'s and Bawit, and in Nubian cathedral murals. Wood panels, textile fragments and wall paintings share the same expressive geometry. The style survived Arab rule in monastic isolation and was consciously revived in nineteenth- and twentieth-century Coptic church decoration, notably by Isaac Fanous.',
    col: [{ h: '#c9793a', n: 'terracotta skin' }, { h: '#2c2c2c', n: 'outline black' }, { h: '#8a3b2e', n: 'martyr red' }, { h: '#d9a441', n: 'halo ochre' }, { h: '#e9dcc3', n: 'plaster ground' }],
    m: ['encaustic wax (early)', 'tempera on wood', 'lime plaster', 'earthy pigments'],
    tx: ['matte fresco absorbency', 'linear wood-grain panels', 'textile-band weaving'],
    obj: ['saint panels', 'monastery apse murals', 'funerary portraits', 'tunic tapestry bands'],
    ex: ['Monastery of Saint Anthony wall paintings', 'Bawit monastery sculpture and murals', 'Isaac Fanous modern icons'],
    inf: ['Fayum funerary portraits', 'Byzantine icon convention', 'Pharaonic frontality'], rel: ['Byzantine Icon Painting', 'Ethiopian Manuscript Illumination', 'Fayum Mummy Portraits'],
    src: [{ n: 'Wikipedia — Coptic art', u: 'https://en.wikipedia.org/wiki/Coptic_art', t: 'B' }, { n: 'Wikipedia — Fayum mummy portraits', u: 'https://en.wikipedia.org/wiki/Fayum_mummy_portraits', t: 'B' }],
    tg: ['coptic', 'icon', 'egypt', 'fresco', 'monastic', 'christian'],
    pop: 45, niche: false,
    vd: { shape: 'frontal figures with oversized almond eyes', line: 'thick confident contour lines', composition: 'hieratic rows of saints on flat colored bands', texture: 'matte earth-pigment surfaces' },
    typ: { display: 'Greek and Coptic name inscriptions beside heads', body: 'Coptic liturgical script', notes: 'inscriptions identify; they never decorate' },
    lit: { quality: 'candle-warm deep shadows', temperature: 'warm-toned', shadow: 'halos glow against dark apses' },
    ui: { background: 'sand plaster texture', surface: 'ochre-framed panels', components: 'round halo icons', motion: 'reverent slow fades' },
    par: 'Christian icon traditions',
  },
]

