/**
 * MENA Round 2 Wave 12 — 12 verified-absent Middle Eastern & Central Asian traditions.
 * All names grepped against existing-names.txt; sources are stable institutional/Wikipedia URLs.
 */
export const ENTRIES: any[] = [
  {
    n: 'Kufic', a: ['Kufic script', 'Kufi'],
    cat: 'Religious & Sacred Art', c: 'Angular Arabic majuscule script of early Qur\'ans and monuments', e: 'historical',
    o: 'Kufa, Iraq (named); wider Arabia-Syria origins', g: 'Early Islamic world — Iraq, Syria, Egypt, Iran, North Africa, al-Andalus', p: 'late 7th century-12th century', era: 'Umayyad & Abbasid Islam',
    sum: 'The oldest codified calligraphic hand of Arabic — bold, angular, geometric script that carried the earliest Qur\'ans, mosque inscriptions, coins and architectural friezes across the early Islamic world.',
    desc: 'Kufic, named for the Iraqi garrison city of Kufa, is the earliest standardized Arabic script, developed as the young Islamic state needed a monumental vehicle for the Qur\'an. Its thick verticals, flat horizontals and sparing diacritics gave early mushaf copies a solemn rectilinear rhythm; on stone, stucco and coinage it stretched into elongated bands of text. Regional branches — Eastern Kufic with foliated terminals, Western Kufic of North Africa and al-Andalus, floriated and plaited variants — flourished through the twelfth century before rounded hands supplanted it for books. It survives in tile panels, tiraz textile bands and modernist Arabic typography.',
    col: [{ h: '#0e2a24', n: 'dark-green mushaf ground' }, { h: '#d9b24a', n: 'gold script' }, { h: '#f2ecdc', n: 'parchment cream' }, { h: '#2b2b2b', n: 'ink black' }, { h: '#8c2f2f', n: 'madder brown accent' }],
    m: ['reed qalam pen', 'carbon and soot ink', 'gold leaf for gilding', 'parchment and early paper'],
    tx: ['broad flat pen strokes', 'stone-carved relief bands', 'plaited interlace terminals'],
    obj: ['Qur\'an manuscripts', 'mosque foundation inscriptions', 'dirham and dinar coinage', 'ceramic frieze bands', 'tiraz textile inscriptions'],
    ex: ['7th-9th-century Qur\'an folios in early kufic hands', 'Samarra stucco inscription bands', 'Great Mosque of Kairouan panels'],
    inf: ['Pre-Islamic Nabataean and Syriac scripts', 'Tiraz textile inscriptions', 'Abbasid manuscript ateliers'], rel: ['Thuluth', 'Naskh', 'Square Kufic', 'Islamic calligraphy', 'Micrography'],
    src: [{ n: 'Wikipedia — Kufic', u: 'https://en.wikipedia.org/wiki/Kufic', t: 'B' }, { n: 'The Metropolitan Museum of Art — Islamic art collection', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['arabic script', 'quran', 'angular', 'monumental inscription', 'abbasid'],
    pop: 60, niche: false,
    vd: { shape: 'rectilinear block letters stretched into bands', line: 'thick uniform strokes with minimal contrast', composition: 'text as architecture — registers framing voids', texture: 'flat ink and carved stone crispness' },
    typ: { display: 'the script itself is the artwork', body: 'n/a', notes: 'monumental and manuscript variants differ in proportion' },
    lit: { quality: 'even raking light for carved inscriptions', temperature: 'warm', shadow: 'shallow relief shadows under strokes' },
    ui: { background: 'parchment cream', surface: 'gold-on-dark script panels', components: 'angular plaque buttons and rules', motion: 'steady horizontal slide' },
  },
  {
    n: 'Al-Qatt Al-Asiri', a: ['Al-Qatt', 'Asiri wall painting', 'qatt decoration'],
    cat: 'Regional & Cultural Tradition', c: 'Saudi women\'s geometric interior wall-painting tradition', e: 'regional_tradition',
    o: 'Asir region, southwest Saudi Arabia', g: 'Saudi Arabia (Asir highlands — Rijal Almaa, Abha area)', p: 'documented 20th century-present, older roots; UNESCO ICH 2017', era: 'Asir highland vernacular culture',
    sum: 'Vivid geometric wall and floor paintings drawn by Asir women on whitewashed mud-brick interiors — triangles, chevrons and rosettes symbolizing welcome, inscribed by UNESCO in 2017.',
    desc: 'Al-Qatt Al-Asiri is the female-led art of painting interior walls, ceilings and floors of Asir houses: a white gypsum ground divided by thumb-width bands into registers filled with triangles, diamond chains, sunbursts and cypress motifs in bright pigments — red ochre, green, cobalt, yellow and black. Women of the household mix and apply the colors, and the work marks hospitality, weddings and seasonal renewal; the painted village houses of Rijal Almaa are the emblematic ensemble. Inscribed on UNESCO\'s Representative List of Intangible Cultural Heritage in 2017, the tradition now informs Saudi public art and fashion prints while community workshops keep hereditary skills alive.',
    col: [{ h: '#e8e2d4', n: 'lime-wash white' }, { h: '#c0392b', n: 'Asiri red' }, { h: '#2e7d4f', n: 'warm green' }, { h: '#f2c438', n: 'ochre yellow' }, { h: '#2c4f8c', n: 'cobalt blue' }],
    m: ['mud plaster walls', 'gypsum lime wash', 'mineral and plant pigments', 'natural binders'],
    tx: ['brushed matte wall ground', 'crisp hand-ruled bands', 'slightly wobbly vernacular linework'],
    obj: ['painted majlis interior walls', 'decorated door lintels', 'painted floors', 'wedding-room murals', 'Rijal Almaa house facades'],
    ex: ['Rijal Almaa heritage village painted interiors', 'Asir seasonal qatt painting gatherings', 'Abha decorative wall programs'],
    inf: ['Pre-Islamic Arabian geometric ornament', 'Household hospitality customs', 'Female hereditary craft transmission'], rel: ['Egyptian Bedouin Dress', 'Sinai Bedouin Attire', 'Arabesque'],
    src: [{ n: 'Wikipedia — Al-Qatt Al-Asiri', u: 'https://en.wikipedia.org/wiki/Al-Qatt_Al-Asiri', t: 'B' }, { n: 'The Metropolitan Museum of Art — Arabian peninsula arts', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['wall painting', 'geometric', 'saudi', 'asir', 'unesco ich', 'women art'],
    pop: 46, niche: true,
    vd: { shape: 'triangle and chevron lattices in registers', line: 'confident hand-ruled banding', composition: 'banded fields covering whole rooms corner to corner', texture: 'matte chalky pigment on earth plaster' },
    typ: { display: 'benediction marks and praise poems sometimes included', body: 'n/a — architectural surface', notes: 'no formal lettering; symbolic motifs dominate' },
    lit: { quality: 'bright diffuse highland daylight', temperature: 'warm', shadow: 'minimal — flat painted planes' },
    ui: { background: 'lime white ground', surface: 'multicolored banded cards', components: 'triangle-motif buttons and dividers', motion: 'stepped band reveals' },
  },
  {
    n: 'Gulf Pearl Diving', a: ['Pearl diving of the Gulf', 'Ghauss diving culture', 'Bahrain pearling'],
    cat: 'Regional & Cultural Tradition', c: 'Pre-oil Gulf pearling economy and its material culture', e: 'historical',
    o: 'Arabian-Persian Gulf littoral — Bahrain, Qatar, UAE, Kuwait', g: 'Gulf states; major banks off Bahrain and Qatar', p: '18th century-1930s peak', era: 'Pre-oil Gulf maritime era',
    sum: 'Seasonal sea economy sending flotillas of dhows and freedivers down to pearl banks for months each summer — a complete material world of diving gear, fijiri songs, merchant markets and pearl jewelry.',
    desc: 'Before oil, Gulf pearl-bank dives defined the region: from late May to September, dhows crewed by freedivers (ghais) working up to thirty descents a day with nose clips (ftam), stone weights (hajar) and rope tenders harvested oysters from beds off Bahrain and Qatar. Divers lived on merchant advances in a debt system that the nahham\'s pearl-diving songs (fijiri) lamented. Natural pearls — graded jaynan, danah, basati — were sorted and priced in merchant majlises, supplying Bombay, Paris and Baghdad jewelers. Bahrain\'s Pearling Path is UNESCO World Heritage; the trade collapsed by the 1940s under cultured pearls and oil wealth, surviving in museums and maritime festivals.',
    col: [{ h: '#0f4c5c', n: 'gulf teal' }, { h: '#e9dfd0', n: 'pearl ivory' }, { h: '#c9b37e', n: 'champagne pearl' }, { h: '#3e6b8f', n: 'deep sea blue' }, { h: '#b8860b', n: 'brass weight gold' }],
    m: ['pearl oysters (Pinctada radiata)', 'cedar and teak dhows', 'nose clips (ftam) and diving stones', 'rope baskets (dajin)'],
    tx: ['nacreous luster', 'salt-crusted rope', 'weathered dhow wood'],
    obj: ['pearl merchant scales and strongboxes', 'diving dhows (jalibut)', 'fijiri song performances', 'pearl necklaces and bidariya jewelry', 'diving baskets'],
    ex: ['Bahrain Pearling Path UNESCO site, Muharraq', 'Qatar National Museum pearl galleries', 'Al Shindagha pearl-diving exhibits, Dubai'],
    inf: ['Indian Ocean dhow trade', 'Bombay pearl-market grading', 'Fijiri maritime musical tradition'], rel: ['Dhow Boat Decoration', 'Bedouin Thobe'],
    src: [{ n: 'Wikipedia — Pearl hunting', u: 'https://en.wikipedia.org/wiki/Pearl_hunting', t: 'B' }, { n: 'Wikipedia — Pearling, Testimony of an Island Economy', u: 'https://en.wikipedia.org/wiki/Pearling,_Testimony_of_an_Island_Economy', t: 'B' }],
    tg: ['pearls', 'maritime', 'bahrain', 'qatar', 'diving', 'pre-oil gulf'],
    pop: 55, niche: false,
    vd: { shape: 'hourglass dhow silhouettes, round pearl ovals', line: 'flowing rope and sail curves', composition: 'layered sea-to-market narrative registers', texture: 'nacre sheen over weathered timber' },
    typ: { display: 'pearl grade names and merchant marks', body: 'n/a', notes: 'fijiri lyrics documented in transcription exhibits' },
    lit: { quality: 'glittering specular over nacre', temperature: 'cool', shadow: 'rippling underwater caustics' },
    ui: { background: 'deep sea gradient', surface: 'pearl-sheen cards', components: 'oval nacre buttons', motion: 'slow dive-and-surface drift' },
  },
  {
    n: 'Talli Weaving', a: ['Talli', 'Emirati talli braid', 'Al Talli'],
    cat: 'Textile & Craft', c: 'Emirati hand-woven metallic braid trim', e: 'regional_tradition',
    o: 'United Arab Emirates (Trucial States)', g: 'UAE — Abu Dhabi, Dubai, Sharjah and northern emirates households', p: 'pre-20th century-present', era: 'Trucial Coast to modern UAE',
    sum: 'Fine hand-woven braids of silver and gold metallic thread with cotton or silk, sewn as glowing trim on Emirati women\'s kandurah dresses — a signature of Gulf bridal costume.',
    desc: 'Talli is the narrow loom-woven braid that edges Emirati women\'s kandurah dresses, running around the neckline, cuffs and hems in shimmering geometric bands. Teams of women work small domestic looms, shuttling dozens of bobbins (dabbous) so silver and gold metallic yarns cross colored cotton and silk in star, diamond and zigzag motifs; metallic thread was historically imported through Gulf ports. A bride\'s trousseau could carry many meters of talli, and skill with the loom was a marker of household pride. Production declined with imported ready-made trim in the mid-twentieth century, but heritage centers and Emirati designers have revived talli for National Day dress and bridal couture.',
    col: [{ h: '#1c1c1c', n: 'black ground' }, { h: '#b3122e', n: 'crimson silk' }, { h: '#c9a227', n: 'metallic gold' }, { h: '#2f6f4e', n: 'deep green' }, { h: '#d8d8d8', n: 'silver thread' }],
    m: ['metallic silver and gold threads', 'cotton and silk yarns', 'small domestic looms', 'wooden bobbins (dabbous)'],
    tx: ['glinting metallic wrap', 'dense flat braid ridges', 'tight geometric float work'],
    obj: ['kandurah dress neckline trims', 'bridal jalabiya edgings', 'sleeve and hem bands', 'National Day commemorative talli'],
    ex: ['Abu Dhabi Women\'s Handicraft Centre talli workshops', 'Heritage village talli demonstrations', 'Emirati bridal couture talli revival pieces'],
    inf: ['Indian zari metallic-thread trade', 'Bedouin dress ornament customs', 'Gulf merchant-household patronage'], rel: ['Bedouin Thobe', 'Egyptian Bedouin Dress', 'Turkish embroidered slippers'],
    src: [{ n: 'Wikipedia — Culture of the United Arab Emirates', u: 'https://en.wikipedia.org/wiki/Culture_of_the_United_Arab_Emirates', t: 'B' }, { n: 'Victoria & Albert Museum — Middle Eastern textiles', u: 'https://www.vam.ac.uk', t: 'A' }],
    tg: ['braid', 'metallic thread', 'emirati', 'dress trim', 'bridal', 'gulf'],
    pop: 40, niche: true,
    vd: { shape: 'narrow bands of star and zigzag motifs', line: 'glinting diagonal floats', composition: 'continuous ribbon logic of repeated units', texture: 'stiff metallic sheen over silk' },
    typ: { display: 'n/a — decorative trim', body: 'n/a', notes: 'motif families vary by emirate and household' },
    lit: { quality: 'point glints off metallic yarns', temperature: 'warm', shadow: 'soft cloth folds' },
    ui: { background: 'midnight black', surface: 'woven braid-stripe cards', components: 'gold-thread outline buttons', motion: 'shimmering band slides' },
  },
  {
    n: 'Al Sadu Weaving', a: ['Sadu', 'Bedouin sadu weaving', 'Al-Sadu'],
    cat: 'Textile & Craft', c: 'Bedouin flat-woven tent textiles of the Arabian Peninsula', e: 'regional_tradition',
    o: 'Arabian Peninsula Bedouin communities', g: 'Gulf and desert Bedouin — strongest documented in Kuwait, UAE and Saudi Arabia', p: 'centuries-old nomadic practice-21st century; UNESCO-listed 2011', era: 'Nomadic Arabia to modern Gulf',
    sum: 'Bedouin women\'s ground-loom flatweave — geometric black, white and madder-red tent dividers, rugs, cushions and camel trappings that turned desert migration into bold pattern.',
    desc: 'Al Sadu is the traditional weaving of Bedouin women, worked on a simple ground loom strung between pegs. Hand-spun sheep and camel wool becomes flatwoven textiles: the tent divider splitting men\'s and women\'s quarters, floor rugs, cushions (misnad), saddle bags and camel trappings. Patterns are geometric — triangles, stepped diamonds, eight-pointed stars — woven in black, natural cream and browns with dyed red-orange, and the motifs carry names drawn from desert life. Weaving encoded social identity and hospitality; after settlement, Kuwait\'s Al-Sadu Society spearheaded revival, UNESCO recognized the weaving skills in 2011, and sadu bands now brand Gulf design, from metro interiors to fashion.',
    col: [{ h: '#26221d', n: 'black sheep wool' }, { h: '#efe6d2', n: 'natural cream' }, { h: '#b3402a', n: 'madder red-orange' }, { h: '#8a6a45', n: 'camel-hair tan' }, { h: '#5b5148', n: 'smoke gray' }],
    m: ['hand-spun sheep wool', 'camel hair yarn', 'natural and imported dyes', 'ground tension loom'],
    tx: ['tightly beaten flatweave', 'raised pattern floats', 'hairy wool nap'],
    obj: ['tent dividers', 'floor rugs', 'cushions (misnad)', 'camel trappings and saddle bags', 'tent hanging bands'],
    ex: ['Kuwait Al-Sadu Society revival weaves', 'Sadu House weaving programs, Kuwait', 'Dubai metro sadu-pattern interiors'],
    inf: ['Nomadic tent architecture', 'Desert trade caravans', 'Natural wool dye traditions'], rel: ['Anatolian Kilims', 'Turkish Kilims', 'Hereke Kilim', 'Bedouin Thobe'],
    src: [{ n: 'Wikipedia — Sadu', u: 'https://en.wikipedia.org/wiki/Sadu', t: 'B' }, { n: 'Victoria & Albert Museum — Middle Eastern textiles', u: 'https://www.vam.ac.uk', t: 'A' }],
    tg: ['flatweave', 'bedouin', 'tent', 'wool', 'unesco ich', 'geometric'],
    pop: 52, niche: false,
    vd: { shape: 'long bands of stepped diamonds and triangles', line: 'sharp woven diagonals', composition: 'stacked horizontal registers with border strips', texture: 'dense wool flatweave ridging' },
    typ: { display: 'woven motif nomenclature, not lettering', body: 'n/a', notes: 'patterns named after desert objects and actions' },
    lit: { quality: 'hot desert sun diffusion', temperature: 'warm', shadow: 'weave shadow lines between floats' },
    ui: { background: 'desert cream', surface: 'banded geometric weave cards', components: 'diamond-motif buttons', motion: 'rhythmic loom-beat transitions' },
  },
  {
    n: 'Marsh Arab Reed Architecture', a: ['Mudhif', 'Marsh Arab reed houses', 'Ma\'dan reed building'],
    cat: 'Regional & Cultural Tradition', c: 'Traditional reed-built dwellings of the southern Iraqi Marshes', e: 'regional_tradition',
    o: 'Mesopotamian Marshes, southern Iraq', g: 'Iraq — Hawizeh, Central and Hammar marshes; Sumerian lineage', p: 'Sumerian antecedents (3rd millennium BCE)-20th-century vernacular survival', era: 'Mesopotamian marshland vernacular',
    sum: 'Cathedral-like vaulted guesthouses (mudhif) and family dwellings made entirely of bundled reeds and woven mats — a building tradition unbroken from Sumer to the modern Iraqi marshes.',
    desc: 'In the Mesopotamian Marshes, the Ma\'dan built without timber or brick: giant kamas reeds, up to seven meters tall, were bundled and arched in pairs into parabolic vaults, tied with twisted reed rope and clad in woven reed mats. The mudhif — a guesthouse vault up to thirty meters long — anchored tribal hospitality, while smaller family houses mixed reed arches with mat screens. Sumerian reed-vault buildings and seal depictions prefigure the form by five millennia, and the same punting buffalo-and-fish economy shaped daily life around them. Drainage schemes in the 1990s devastated the marshes; re-flooding after 2003 enabled partial reconstruction, making the reed vault an emblem of Iraqi heritage.',
    col: [{ h: '#a89a5f', n: 'sun-dried reed gold' }, { h: '#6f7a44', n: 'green reed' }, { h: '#4e4632', n: 'shadowed bundle brown' }, { h: '#d8cfae', n: 'woven mat straw' }, { h: '#33608a', n: 'marsh water blue' }],
    m: ['giant kamas reed bundles', 'woven reed mats', 'twisted reed rope ties', 'mud-plinth hearths'],
    tx: ['ribbed bundle rhythm', 'open-weave mat screens', 'sun-bleached fiber fuzz'],
    obj: ['mudhif guesthouse vaults', 'family reed houses', 'reed-mat partitions', 'reed buffalo byres', 'mashoof punt canoes (context)'],
    ex: ['Sumerian reed-vault depictions on cylinder seals', 'Wilfred Thesiger\'s 1950s marsh photography', 'Post-2003 Central Marsh mudhif reconstruction'],
    inf: ['Sumerian reed architecture', 'Tribal mudhif hospitality custom', 'Buffalo-herding marsh economy'], rel: ['Mashrabiya', 'Dhow Boat Decoration'],
    src: [{ n: 'Wikipedia — Marsh Arabs', u: 'https://en.wikipedia.org/wiki/Marsh_Arabs', t: 'B' }, { n: 'Wikipedia — Mesopotamian Marshes', u: 'https://en.wikipedia.org/wiki/Mesopotamian_Marshes', t: 'B' }],
    tg: ['vernacular architecture', 'reed', 'iraq', 'marsh', 'sumerian', 'mudhif'],
    pop: 48, niche: true,
    vd: { shape: 'parabolic reed-vault arches in series', line: 'vertical bundle ribs', composition: 'nave-like interior leading to the guest hearth', texture: 'sunlit golden fiber texture' },
    typ: { display: 'no lettering; tribal banners sometimes hung', body: 'n/a', notes: 'the architecture itself is the expressive medium' },
    lit: { quality: 'shafted light through mat walls', temperature: 'warm', shadow: 'deep golden interior shade' },
    ui: { background: 'reed-gold gradient', surface: 'ribbed vault-pattern cards', components: 'arch-line dividers', motion: 'slow light-through-reed pans' },
  },
  {
    n: 'Achaemenid Relief Sculpture', a: ['Persepolis reliefs', 'Achaemenid court reliefs', 'Persian imperial bas-relief'],
    cat: 'Material & Surface', c: 'Imperial stone-carving program of Achaemenid Persia', e: 'historical',
    o: 'Persia — Persepolis, Susa, Behistun, Pasargadae', g: 'Achaemenid Empire (550-330 BCE) across Iran and the Near East', p: 'c. 550-330 BCE', era: 'Achaemenid Persia',
    sum: 'Monumental low-relief carving — tribute bearers, guards, lion-bull combats — sheathing the stairways and gateways of Persepolis and the royal Achaemenid sites in immaculate processional stone.',
    desc: 'Achaemenid kings commissioned dense stone relief programs as imperial ideology made visible. At Persepolis, founded under Darius I around 518 BCE, stairway panels file hundreds of delegations — Medes, Elamites, Lydians, Indians, Ethiopians bearing gifts — toward the king, while gateways frame winged guardians and the winged disc hovers above royal figures. The carving is shallow, elegant and exact: sharp profile contours, polished limestone, rhythmically repeated rows of Immortal guards. Assyrian and Babylonian palace art supplied precedents, but Achaemenid reliefs replace conquest violence with ordered multitudes. The fire of 330 BCE buried rather than destroyed the terraces, preserving reliefs that remain touchstones of Iranian art and world archaeology.',
    col: [{ h: '#8d8579', n: 'limestone gray-beige' }, { h: '#3c3a36', n: 'carved shadow' }, { h: '#b23a2e', n: 'paint-trace red' }, { h: '#2e5979', n: 'lapis-blue pigment trace' }, { h: '#c9b26b', n: 'gilt halo trace' }],
    m: ['gray local limestone', 'iron chisels and abrasives', 'polychrome pigment traces', 'cedar roof-beam settings (context)'],
    tx: ['shallow crisp profile carving', 'polished stone planes', 'weathered flaking pigment'],
    obj: ['Apadana stairway reliefs', 'Gate of All Nations guardians', 'triptychon processional panels', 'Behistun royal relief', 'Naqsh-e Rostam tomb facades'],
    ex: ['Apadana eastern stairway tribute procession, Persepolis', 'Gate of All Nations winged guardians', 'Darius I relief at Behistun'],
    inf: ['Assyrian palace reliefs', 'Babylonian and Elamite monumental art', 'Median court iconography'], rel: ['Girih Patterns', 'Muqarnas vaulting', 'Arabesque'],
    src: [{ n: 'Wikipedia — Persepolis', u: 'https://en.wikipedia.org/wiki/Persepolis', t: 'B' }, { n: 'Wikipedia — Achaemenid Empire', u: 'https://en.wikipedia.org/wiki/Achaemenid_Empire', t: 'B' }],
    tg: ['stone relief', 'persepolis', 'achaemenid', 'monumental', 'procession', 'iran'],
    pop: 62, niche: false,
    vd: { shape: 'profile processions of repeated figures', line: 'incised contour around shallow planes', composition: 'register-based imperial procession toward the king', texture: 'smooth limestone with sharp edges' },
    typ: { display: 'cuneiform royal inscriptions framing reliefs', body: 'n/a', notes: 'trilingual inscriptions are part of the program' },
    lit: { quality: 'harsh high-desert raking sun', temperature: 'warm', shadow: 'crisp micro-shadows inside carving lines' },
    ui: { background: 'weathered limestone field', surface: 'relief-profile panels', components: 'chiseled contour buttons', motion: 'processional lateral scroll' },
  },
  {
    n: 'Tazhib', a: ['Tazhib gilding', 'Persian manuscript illumination', 'tazhib toranj'],
    cat: 'Religious & Sacred Art', c: 'Persian manuscript illumination and gilding art', e: 'regional_tradition',
    o: 'Persia (Iran) — Herat, Tabriz, Shiraz and Isfahan workshops', g: 'Greater Iran and Persianate courts — Ilkhanid, Timurid, Safavid, Qajar', p: '12th century-19th century (revivals to present)', era: 'Ilkhanid, Timurid & Safavid Iran',
    sum: 'Gold-ground illumination framing Persian Qur\'ans, Shahnamehs and album pages — lobed medallions, arabesque scrolls and khatai blossoms in lapis, gold and vermilion.',
    desc: 'Tazhib — from the Arabic for gilding — is the Persian art of illuminating manuscripts, in which folio borders and opening pages grow into minutely ruled fields of burnished gold and mineral color. Masters laid and burnished gold leaf, then drew khatai palmettes and islimi arabesque scrolls with hair-fine brushes, filling them with lapis ultramarine, vermilion, carmine and green. Signature forms include the shamsa sunburst that opens royal Qur\'ans, lobed toranj medallions, and cloud-band margins in Chinese-derived taste. Timurid Herat and Safavid Tabriz workshops set the classical standard, and their designs spread to Ottoman, Mughal and Uzbek ateliers. Iranian art academies still teach tazhib as a living discipline.',
    col: [{ h: '#1b2a6b', n: 'lapis ultramarine' }, { h: '#d4a72c', n: 'burnished gold' }, { h: '#a52a1f', n: 'vermilion' }, { h: '#f3ead0', n: 'ivory folio' }, { h: '#1e6b4f', n: 'emerald green' }],
    m: ['burnished gold leaf', 'lapis lazuli pigment', 'vermilion and orpiment', 'squirrel-hair brushes', 'sized burnished paper'],
    tx: ['glassy burnished gold', 'hair-fine ruling', 'velvet mineral bloom'],
    obj: ['Qur\'an openings and shamsas', 'Shahnameh frontispieces', 'muraqqa album borders', 'divan anthologies', 'calligraphy folio mounts'],
    ex: ['Timurid Herat Qur\'an shamsas, Baysunghur atelier', 'Shahnameh of Shah Tahmasp border programs', 'Safavid muraqqa album pages'],
    inf: ['Chinese cloud-band ornament', 'Timurid Herat ateliers', 'Qur\'an illumination conventions'], rel: ['Persian miniature', 'Mamluk Illumination', 'Mamluk Quran Illumination', 'Tezhip', 'Qajar Painting'],
    src: [{ n: 'Wikipedia — Tazhib', u: 'https://en.wikipedia.org/wiki/Tazhib', t: 'B' }, { n: 'The Metropolitan Museum of Art — Islamic manuscript illumination', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['illumination', 'gold', 'persian', 'manuscript', 'shamsa', 'timurid', 'safavid'],
    pop: 54, niche: false,
    vd: { shape: 'lobed medallions and radiating shamsas', line: 'hair-fine scrolling arabesque contours', composition: 'central medallion with guarded margins and corner units', texture: 'burnished gold over deep lapis' },
    typ: { display: 'opening benedictions integrated with ornament', body: 'n/a', notes: 'illumination frames calligraphy without competing' },
    lit: { quality: 'jewel-like even glow', temperature: 'warm', shadow: 'none — flat radiance' },
    ui: { background: 'lapis ground', surface: 'gold-scroll framed cards', components: 'medallion rosette buttons', motion: 'bloom-out medallion reveals' },
  },
  {
    n: 'Circassian Dress & Silver Traditions', a: ['Adyghe traditional dress', 'Circassian silverwork', 'Cherkeska costume'],
    cat: 'Textile & Craft', c: 'North Caucasus Circassian costume and silversmithing', e: 'regional_tradition',
    o: 'Northwest Caucasus — historical Circassia (Adygea, Kabardia)', g: 'Circassian communities and diaspora — Turkey, Jordan, Syria, Israel; homeland in Russia', p: 'pre-19th-century traditions-diaspora present', era: 'Circassian highland & diaspora culture',
    sum: 'The tailored cherkeska longcoat with gazyr cartridge pockets, gold-embroidered women\'s dress and celebrated niello-and-gilt silver belts, clasps and weapon mounts of Circassian makers.',
    desc: 'Circassian (Adyghe) material culture is prized for refined tailoring and metalwork. Men wore the fitted cherkeska coat with chest rows of gazyr cartridge tubes, while women\'s long dresses were fastened with hand-chased silver clasps and belts — heirloom sets engraved with niello scrollwork — beneath tall embroidered caps. Women termed "golden hands" worked gilt and silver thread into dense embroidery, and silversmiths furnished buckles, daggers and pistol mounts for a horseman culture. The end of the Russo-Circassian War and the 1864 exile carried these arts to Ottoman lands, where diaspora weddings still stage full traditional costume; museums in Adygea and Kabardino-Balkaria hold the classic ensembles.',
    col: [{ h: '#17181c', n: 'cherkeska black' }, { h: '#b02c2c', n: 'deep red bodice' }, { h: '#c9cdd2', n: 'hammered silver' }, { h: '#d9b64a', n: 'gilt thread' }, { h: '#f1ece2', n: 'cream wool felt' }],
    m: ['hammered silver and niello', 'gilt and silver thread', 'fine wool and felt', 'silk embroidery floss'],
    tx: ['chased niello line engraving', 'dense gold couching', 'firm tailored wool'],
    obj: ['cherkeska men\'s coats', 'silver belt sets and clasps', 'tall embroidered women\'s caps', 'gazyr cartridge pockets', 'dagger and pistol mounts'],
    ex: ['National Museum of the Republic of Adygea costume holdings', 'Kabardino-Balkarian museum silver belt sets', 'Diaspora wedding costume in Amman and Istanbul communities'],
    inf: ['Caucasian silversmithing schools', 'Ottoman elite dress culture', 'Highland horsemanship attire'], rel: ['Ottoman layered dress', 'Ottoman goldwork dress', 'Tekke Turkmen'],
    src: [{ n: 'Wikipedia — Circassians', u: 'https://en.wikipedia.org/wiki/Circassians', t: 'B' }, { n: 'The Metropolitan Museum of Art — Caucasian arms and dress', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['circassian', 'silver', 'costume', 'caucasus', 'niello', 'diaspora'],
    pop: 44, niche: true,
    vd: { shape: 'long tailored silhouettes, crescent-tipped caps', line: 'chased silver scroll borders', composition: 'centered silver clasp axis on dark wool', texture: 'matte wool against polished metal' },
    typ: { display: 'n/a — wearable tradition', body: 'n/a', notes: 'silver sets are heirloom dowry pieces' },
    lit: { quality: 'crisp gallery light', temperature: 'cool', shadow: 'soft wool-fold shading' },
    ui: { background: 'charcoal wool field', surface: 'silver-chased pattern cards', components: 'niello-outline buttons', motion: 'measured metallic glides' },
  },
  {
    n: 'Tughra', a: ['Tughra calligraphy', 'Ottoman sultanic monogram', 'Tugra'],
    cat: 'Religious & Sacred Art', c: 'Ottoman sultanic calligraphic emblems', e: 'historical',
    o: 'Ottoman court — Bursa, then Istanbul', g: 'Ottoman Empire — chancery, coinage, monuments and firmans', p: '14th century-early 20th century (abolished 1922)', era: 'Ottoman imperial era',
    sum: 'Interlaced calligraphic signatures of the Ottoman sultans — three vertical shafts looping into paired bowls and flying banners — drawn on firmans, stamped on coins and carved on gateways.',
    desc: 'The tughra fused the sultan\'s name, father\'s name and epithet ("ever-victorious") into a single emblem: vertical base strokes (tuğ) crowned by paired oval bowls (beyze), flying banners (sere), dagger strokes and comb-like zülfe. Drafted by the chancery and later by specialist tughra calligraphers, it authenticated decrees, endowment deeds and coinage as the visible sign of sovereignty, often set within illuminated gold-and-color cartouches. Each reign\'s tughra grew more elaborate — Süleyman the Magnificent\'s three-banner emblem is the celebrated type — and examples were carved on public buildings. Its interlace anticipates modern logotype thinking, and Turkish designers continue to revive the form.',
    col: [{ h: '#d7b45a', n: 'gold wash' }, { h: '#141414', n: 'ink black' }, { h: '#f0e7d3', n: 'burnished paper' }, { h: '#7a1f2b', n: 'illumination crimson' }, { h: '#1f4d7a', n: 'ultramarine accent' }],
    m: ['reed qalam pens', 'soot and oak-gall ink', 'gold wash on sized paper', 'illuminated scroll grounds'],
    tx: ['thick-thin qalam modulation', 'fluid loop interlace', 'gold-wash sheen'],
    obj: ['imperial firmans and berats', 'coin designs', 'carved gateway monograms', 'endowment deeds (vakfiye)', 'calligrapher practice panels'],
    ex: ['Tughra of Süleyman the Magnificent (The Metropolitan Museum of Art)', 'Tughra-bearing firmans in Ottoman archives', 'Sultanic tughra on late Ottoman coins'],
    inf: ['Mongol-Ilkhanid tamga seals', 'Ottoman chancery practice', 'Illuminated firman conventions'], rel: ['Tezhip', 'Thuluth', 'Naskh', 'Sedefkari', 'Micrography'],
    src: [{ n: 'Wikipedia — Tughra', u: 'https://en.wikipedia.org/wiki/Tughra', t: 'B' }, { n: 'The Metropolitan Museum of Art — Tughra of Süleyman the Magnificent', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['calligram', 'ottoman', 'monogram', 'imperial', 'calligraphy', 'seal'],
    pop: 50, niche: true,
    vd: { shape: 'tall vertical strokes igniting into looped bowls', line: 'qalam thick-thin flourish', composition: 'single emblem isolated on an illuminated ground', texture: 'gold wash glow over smooth paper' },
    typ: { display: 'the tughra is display lettering itself', body: 'n/a', notes: 'the sultan\'s titles are hidden in the interlace' },
    lit: { quality: 'soft directional manuscript light', temperature: 'warm', shadow: 'minimal; gold carries depth' },
    ui: { background: 'ivory manuscript tone', surface: 'gold-emblem medallion cards', components: 'loop-underline buttons', motion: 'draw-on signature animation' },
  },
  {
    n: 'Tatreez', a: ['Palestinian embroidery', 'fallahi stitch', 'Palestinian cross-stitch'],
    cat: 'Textile & Craft', c: 'Palestinian women\'s cross-stitch embroidery tradition', e: 'regional_tradition',
    o: 'Historic Palestine — villages of Ramallah, Hebron, Gaza and Galilee', g: 'Palestinian communities in Palestine and the diaspora', p: 'at least 19th century-present; UNESCO ICH 2021', era: 'Ottoman-era Palestine to present',
    sum: 'Dense crimson cross-stitch (fallahi) covering women\'s thobe dresses with village-specific motifs — cypresses, stars, combs, moons — inscribed by UNESCO in 2021 as stitched Palestinian identity.',
    desc: 'Tatreez is the counted cross-stitch embroidery Palestinian women worked onto hand-loomed linen dresses, veils and household textiles. The dominant fallahi stitch builds squared geometric motifs — cypress trees, moons and stars, combs, scissors — in silk dyed cochineal crimson, laid edge to edge so the pattern consumes the cloth. Each district carried recognizable panels: Ramallah\'s bold red chest panels are the classic type, while neighboring regions varied stitch density and motif sets. Embroidery marked life stages, from bridal trousseaus to mourning dress. After 1948 tatreez became a portable emblem of Palestinian identity, produced in refugee-camp cooperatives, and UNESCO inscribed the art on the Representative List in 2021.',
    col: [{ h: '#a31621', n: 'cochineal crimson' }, { h: '#efe8d8', n: 'undyed linen' }, { h: '#2c2c2c', n: 'mourning black' }, { h: '#4a6741', n: 'olive green' }, { h: '#c96a2e', n: 'orange madder' }],
    m: ['hand-woven linen', 'silk embroidery floss', 'cochineal and madder dyes', 'counted-thread cloth'],
    tx: ['raised X-stitch nap', 'dense full-coverage patterning', 'crisp geometric grid'],
    obj: ['women\'s thobe dresses', 'bridal trousseau panels', 'veils and head shawls', 'cushion covers', 'contemporary solidarity banners'],
    ex: ['Ramallah red bridal thobes in museum collections', 'Bethlehem couching wedding dresses (related technique)', 'Refugee-camp cooperative embroidery, e.g. Inaash'],
    inf: ['Regional bridal costume customs', 'Levantine trade silks', 'Post-1948 diaspora identity movements'], rel: ['Bukhara Embroidery', 'Egyptian Bedouin Dress', 'Bedouin Thobe', 'Bukharan suzani'],
    src: [{ n: 'Wikipedia — Palestinian embroidery', u: 'https://en.wikipedia.org/wiki/Palestinian_embroidery', t: 'B' }, { n: 'Victoria & Albert Museum — Palestinian dress collection', u: 'https://www.vam.ac.uk', t: 'A' }],
    tg: ['cross-stitch', 'embroidery', 'palestinian', 'thobe', 'unesco ich', 'identity'],
    pop: 56, niche: false,
    vd: { shape: 'squared motif blocks in grid registers', line: 'stepped diagonal stitch paths', composition: 'all-over field with a central qabbeh chest panel', texture: 'silk stitches lifted off linen' },
    typ: { display: 'occasional embroidered names and dates on panels', body: 'n/a', notes: 'village pattern vocabularies function as signatures' },
    lit: { quality: 'clear daylight', temperature: 'warm', shadow: 'light thread shadows on linen' },
    ui: { background: 'undyed linen field', surface: 'red-motif grid cards', components: 'stitch-square buttons', motion: 'cross-by-cross build-in' },
  },
  {
    n: 'Uzbek Silk Ikat', a: ['Atlas silk', 'Adras ikat', 'Khan-atlas', 'abrbandi'],
    cat: 'Textile & Craft', c: 'Central Asian resist-dyed silk weaving', e: 'regional_tradition',
    o: 'Bukhara, Samarkand and Margilan, Uzbekistan', g: 'Central Asian silk-road cities — Uzbekistan and adjoining Tajikistan, Turkmenistan, Kazakhstan', p: 'flourished 19th century-present (earlier roots)', era: 'Khanate-era Central Asia to present',
    sum: 'Blur-edged, jewel-colored silk ikat (atlas and adras) woven into shimmering zigzags, waves and toothed medallions — the legendary "khan-atlas" of Bukhara, Samarkand and Margilan.',
    desc: 'Uzbek ikat (abrbandi, "cloud-tying") binds warp threads into the pattern before each dye bath, so colors meet in the feathered abr cloud edge that defines the cloth. Workshop teams of masters, dyers and loom tenders produced silk atlas and silk-cotton adras in saturated yellows, greens, madders and indigo, arranged in bold zigzags, waves and serrated medallions that shimmer as the warp-aligned pattern flows. These silks dressed the courts of the Emirate of Bukhara and Khanate of Kokand, and ikat chapans ranked among the era\'s prized diplomatic gifts. Soviet collectivization dispersed the workshops; post-independence Margilan factories revived master dyeing, and atlas now stars in Uzbek national dress and contemporary fashion.',
    col: [{ h: '#e0b32a', n: 'atlas yellow' }, { h: '#2f7d4f', n: 'emerald green' }, { h: '#b03030', n: 'madder red' }, { h: '#1f3f7a', n: 'indigo' }, { h: '#f5efdd', n: 'silk ivory' }],
    m: ['silk and silk-cotton yarns', 'natural dyes — madder, indigo, walnut hulls', 'abrbandi warp bindings', 'treadle looms'],
    tx: ['feathered dye-bleed edges', 'high-twist silk sheen', 'crisp warp-faced pattern'],
    obj: ['chapan robes', 'bridal khan-atlas dresses', 'headwraps and veils', 'interior hangings', 'contemporary fashion textiles'],
    ex: ['Yodgorlik Silk Factory dye workshops, Margilan', '19th-century Bukharan ikat robes in museum collections', 'Samarkand and Tashkent atlas fashion houses'],
    inf: ['Silk Road dye trade', 'Persian textile patterning', 'Court robe-gifting diplomacy'], rel: ['Persian termeh brocade', 'Termeh', 'Bukhara Embroidery', 'Tekke Turkmen', 'Bukharan suzani'],
    src: [{ n: 'Wikipedia — Ikat', u: 'https://en.wikipedia.org/wiki/Ikat', t: 'B' }, { n: 'Victoria & Albert Museum — Central Asian ikat collection', u: 'https://www.vam.ac.uk', t: 'A' }],
    tg: ['ikat', 'silk', 'uzbekistan', 'atlas', 'resist dye', 'silk road'],
    pop: 57, niche: false,
    vd: { shape: 'zigzag and cloud-edge chevron bands', line: 'feathered abr dye boundaries', composition: 'warp-aligned vertical pattern flow', texture: 'liquid sheen with blur-edge color meetings' },
    typ: { display: 'n/a — patterned cloth', body: 'n/a', notes: 'colorways and scales signal region and workshop' },
    lit: { quality: 'luminous silk glow', temperature: 'warm', shadow: 'soft folds between color bands' },
    ui: { background: 'saffron silk wash', surface: 'ikat-chevron gradient cards', components: 'cloud-edge buttons', motion: 'warp-flow vertical sweeps' },
  },
]
