/**
 * North America wave — 16 hand-verified US/Canada/Mexico-borderlands traditions.
 * All names are real, documented traditions; Wikipedia URLs HTTP-verified (200).
 * Dedup-checked against existing-names.txt (fraktur, hex sign, Gee, Baltimore,
 * Amish, Métis, ceinture, hojalata, santero, adirondack, nantucket, decoy,
 * button blanket, moccasin all clear; Shaker Furniture and Hawaiian quilts
 * already existed and were substituted out for Hooked Rug Tradition and
 * Cowichan Knitting).
 */
export const ENTRIES: any[] = [
  {
    n: 'Pennsylvania Dutch Fraktur', a: ['Fraktur folk art', 'Pennsylvania German fraktur', 'Taufschein', 'Taufscheine', 'Fraktur drawings'],
    cat: 'Material & Surface', c: 'Pennsylvania German illuminated manuscript folk art', e: 'historical',
    o: 'Pennsylvania, USA', g: 'United States (Pennsylvania Dutch country; Ontario Mennonite settlements)', p: 'c. 1750-1900', era: 'Colonial & Victorian America',
    sum: 'Illuminated birth certificates and house blessings of the Pennsylvania Germans — blackletter script wreathed in watercolor tulips, hearts, birds and distlefinks on rag paper.',
    desc: 'Pennsylvania Dutch fraktur is the illuminated folk art of the Pennsylvania Germans: hand-lettered, hand-colored Taufscheine (birth and baptismal certificates), house blessings, bookplates and writing samples, their blackletter script wreathed in watercolor tulips, hearts, birds and distlefinks. Schoolmasters, scriveners and printers made them from the mid-1700s across Pennsylvania Dutch country and Ontario Mennonite settlements; the form faded as German-language printing declined after the Civil War. The Free Library of Philadelphia and Winterthur hold the great fraktur collections.',
    col: [{ h: '#1f1c18', n: 'iron-gall ink black' }, { h: '#a63a2b', n: 'madder red' }, { h: '#e8dcc0', n: 'aged rag paper' }, { h: '#d9a441', n: 'ochre yellow' }, { h: '#5c6e46', n: 'leaf green' }],
    m: ['laid rag paper', 'iron-gall and blackletter ink', 'watercolor and gum binder', 'hand-cut stencils (schoolmasters)'],
    tx: ['laid paper grain', 'feather-drawn hairline', 'watercolor bloom'],
    obj: ['taufschein birth and baptismal certificates', 'Haus-Segen house blessings', 'Vorschrift writing exercises', 'reward of merit cards', 'bookplates and family records'],
    ex: ['Bucks County schoolmaster drawings of Johann Adam Eyer', 'Bauman family printed-and-hand-colored taufscheine', 'Schwenkfelder Library fraktur collection'],
    inf: ['German blackletter calligraphy', 'Rhineland book illumination', 'Pennsylvania German parochial schooling'],
    rel: ['Hex Signs', 'Folk Tole Painting'],
    src: [{ n: 'Wikipedia — Fraktur (folk art)', u: 'https://en.wikipedia.org/wiki/Fraktur_(folk_art)', t: 'B' }, { n: 'Free Library of Philadelphia — Fraktur collection', u: 'https://www.freelibrary.org', t: 'A' }, { n: 'Winterthur Museum, Garden & Library', u: 'https://www.winterthur.org', t: 'A' }],
    tg: ['fraktur', 'blackletter', 'folk art', 'pennsylvania dutch', 'birth certificate', 'watercolor', 'illuminated'],
    pop: 38, niche: true,
    vd: { shape: 'symmetrical hearts, tulips and birds framing text bands', line: 'delicate quill outline beside fraktur blackletter', composition: 'centered certificate cartouche with corner sprays', texture: 'watercolor washes on laid rag paper' },
    typ: { display: 'blackletter fraktur lettering as the central element', body: 'n/a — document art', notes: 'every piece is titled and inscribed by hand' },
    lit: { quality: 'soft even daylight', temperature: 'warm', shadow: 'minimal, flat parchment' },
    ui: { background: 'aged parchment cream', surface: 'hand-tinted framed panels', components: 'blackletter-styled headings and rule lines', motion: 'gentle ink-in fades' },
  },
  {
    n: 'Hex Signs', a: ['Barn stars', 'Pennsylvania Dutch hex signs', 'Barn sign art', 'Distelfink hex', 'Fancy Dutch barn signs'],
    cat: 'Material & Surface', c: 'Pennsylvania Dutch barn decoration', e: 'regional_tradition',
    o: 'Pennsylvania, USA', g: 'United States (Berks, Lehigh, Lancaster counties; tourist trade nationwide)', p: 'c. 1850-present', era: '19th-century Pennsylvania to present',
    sum: 'Painted circular barn emblems of Pennsylvania Dutch country — stars, distelfinks, tulips and hearts — part folk ornament, part apotropaic legend, part roadside Americana.',
    desc: 'Hex signs are painted circular barn emblems of Pennsylvania Dutch country: eight-pointed stars, distelfinks, tulips, hearts and oak leaves in flat, bright color. Metal barn stars were set on gables from the mid-1800s; the painted "hex sign" form was popularized in the 1920s-40s — notably by Jacob Zook of Paradise — and sold widely to tourists as "fancy Dutch" decoration, while folklore attached meanings of luck, protection, fertility and welcome. They remain a signature roadside image of Berks, Lehigh and Lancaster county barns.',
    col: [{ h: '#f2ead8', n: 'white ground' }, { h: '#a32e2e', n: 'barn red' }, { h: '#d9a534', n: 'star gold' }, { h: '#2e6e6a', n: 'teal accent' }, { h: '#1e1a16', n: 'outline black' }],
    m: ['painted board and barn siding', 'oil and enamel paints', 'sheet-metal barn stars (companion tradition)'],
    tx: ['flat enamel face', 'weathered paint chalking', 'chained concentric rings'],
    obj: ['eight-pointed barn stars', 'distelfink hex signs', 'tulip-and-heart roundels', 'six-petal rosettes', 'painted barn gables'],
    ex: ['Jacob Zook printed hex signs (Paradise, PA)', 'Roadside barn stars of Berks and Lehigh counties', 'Kutztown Folk Festival hex sign displays'],
    inf: ['Pennsylvania German braucherei folk practice', 'Rhineland painted furniture ornament', 'Mid-century Americana tourism'],
    rel: ['Pennsylvania Dutch Fraktur', 'Folk Tole Painting', 'Hooked Rug Tradition'],
    src: [{ n: 'Wikipedia — Hex sign', u: 'https://en.wikipedia.org/wiki/Hex_sign', t: 'B' }, { n: 'Wikipedia — Barnstar', u: 'https://en.wikipedia.org/wiki/Barnstar', t: 'B' }, { n: 'Pennsylvania German Cultural Heritage Center, Kutztown University', u: 'https://www.kutztown.edu', t: 'A' }],
    tg: ['hex sign', 'barn star', 'folk art', 'pennsylvania dutch', 'apotropaic', 'americana'],
    pop: 45, niche: false,
    vd: { shape: 'concentric circular medallions, eight-point stars', line: 'bold flat outlines, radial symmetry', composition: 'centered disk scaled to the barn gable', texture: 'flat enamel on weathered board' },
    typ: { display: 'n/a — symbolic emblem with minimal lettering', body: 'n/a', notes: 'occasional painted dates or initials' },
    lit: { quality: 'bright exterior daylight', temperature: 'warm', shadow: 'cast under gable eaves only' },
    ui: { background: 'barn red field', surface: 'circular medallion badges', components: 'star-shaped buttons and rosette dividers', motion: 'slow radial spin accents' },
  },
  {
    n: 'Hooked Rug Tradition', a: ['Rug hooking', 'Hooked rugs', 'Grenfell mats', 'Hit-or-miss rugs', 'Chéticamp hooked rugs'],
    cat: 'Textile & Craft', c: 'North American rag-rug hooking craft', e: 'regional_tradition',
    o: 'Atlantic Canada & New England, Canada/USA', g: 'Canada and United States (Newfoundland, Nova Scotia, New England, Québec)', p: 'c. 1860-present', era: 'Victorian domestic craft to present',
    sum: 'Hand-pulled rag rugs of looped wool and silk — from frugal hit-or-miss floor mats to the pictorial Grenfell mats of Labrador and the cooperative tradition of Chéticamp.',
    desc: 'Hooked rugs are made by pulling wool and cotton rag strips through open-weave burlap with a hook, building dense looped pile in frugal "hit-or-miss" geometries. A household craft across New England and Atlantic Canada, it became a regional economy: from about 1916 the Grenfell Mission organized Labrador women to hook silk-sorted pictorial mats for southern markets, and Chéticamp, Nova Scotia, sustained a cooperative tradition. Maine\'s Waldoboro style sculpted flowers in relief. Shelburne Museum holds a major collection, and studio rug hooking thrives today.',
    col: [{ h: '#8a2f2b', n: 'hit-or-miss red' }, { h: '#31465e', n: 'workshirt navy' }, { h: '#d8c6a5', n: 'unbleached burlap' }, { h: '#5c6e46', n: 'wool green' }, { h: '#b5732e', n: 'plaid ochre' }],
    m: ['burlap and linen backing', 'wool and cotton rags', 'silk and stocking strips (Grenfell)', 'hand rug hook'],
    tx: ['dense looped pile', 'staggered loop rows', 'sheared pile unevenness'],
    obj: ['floor mats and hearth rugs', 'Grenfell pictorial mats', 'chair pads and footstool tops', 'wall-hung art rugs'],
    ex: ['Grenfell Mission silk-sorted mats of Labrador', 'Chéticamp pictorial hooked rugs', 'Shelburne Museum hooked rug collection'],
    inf: ['Newfoundland outport thrift culture', 'Grenfell Mission handicraft economy', 'Arts and Crafts homecraft revival'],
    rel: ['Gee\'s Bend Quilts', 'Shaker Furniture', 'Amish Quilts'],
    src: [{ n: 'Wikipedia — Rug hooking', u: 'https://en.wikipedia.org/wiki/Rug_hooking', t: 'B' }, { n: 'Wikipedia — Grenfell Mission', u: 'https://en.wikipedia.org/wiki/Grenfell_Mission', t: 'B' }, { n: 'Shelburne Museum', u: 'https://shelburnemuseum.org', t: 'A' }],
    tg: ['rug hooking', 'rag rug', 'grenfell', 'newfoundland', 'folk textile', 'burlap'],
    pop: 36, niche: true,
    vd: { shape: 'pictorial medallions or free geometric fills', line: 'pixel-like loop rows building contour', composition: 'centered motif with hit-or-miss borders', texture: 'looped wool pile, hand-shorn unevenness' },
    typ: { display: 'some Grenfell mats carry embroidered titles', body: 'n/a — floor and wall textile', notes: 'mission stamps and labels document mats' },
    lit: { quality: 'soft ambient interior light', temperature: 'warm', shadow: 'pile texture shadows' },
    ui: { background: 'burlap tan weave', surface: 'loop-textured tiles', components: 'hand-stitched pill buttons', motion: 'slow stitch-row reveals' },
  },
  {
    n: 'Gee\'s Bend Quilts', a: ['Quilts of Gee\'s Bend', 'Boykin quilts', 'Pettway quilts', 'Freedom Quilting Bee quilts', 'Housetop quilts'],
    cat: 'Textile & Craft', c: 'African American improvisational quilting tradition', e: 'regional_tradition',
    o: 'Gee\'s Bend, Alabama, USA', g: 'United States (Wilcox County, Alabama)', p: 'c. 1900-present', era: 'Jim Crow South to present',
    sum: 'Radically improvised geometric quilts from an isolated Black Alabama river community — corduroy coverlets, work-clothes patchwork and "my way" patterns of national art fame.',
    desc: 'In Gee\'s Bend (Boykin), Alabama — an isolated bend of the Alabama River settled around the Pettway plantation — women quilted from feed sacks, worn work clothes and leftover corduroy, improvising "housetop," strip and medallion compositions without written patterns. The Freedom Quilting Bee, founded in 1966, commercialized the work; the 2002-03 touring exhibition "The Quilts of Gee\'s Bend" (MFA Houston; Whitney Museum) brought makers such as Annie Mae Young, Mary Lee Bendolph and Loretta Pettway national recognition, their asymmetries often compared to modernist abstraction.',
    col: [{ h: '#2e3d54', n: 'work-denim blue' }, { h: '#8f3530', n: 'washed flannel red' }, { h: '#c9a15a', n: 'corduroy gold' }, { h: '#e6e0d2', n: 'feed-sack cream' }, { h: '#5b3a52', n: 'faded plum' }],
    m: ['feed and flour sack cotton', 'recycled work-clothes denim and corduroy', 'old quilts as batting', 'torn polyester double-knit'],
    tx: ['washed-cotton softness', 'corduroy wale', 'exposed seam ridges'],
    obj: ['housetop pattern quilts', 'corduroy scrap quilts', 'work-clothes memory quilts', 'strip and bricklayer quilts', 'gospel-patch bedcovers'],
    ex: ['Annie Mae Young work-clothes quilts (Whitney 2002)', 'Mary Lee Bendolph housetop quilts', 'Loretta Pettway corduroy "Housetop" quilts'],
    inf: ['African American improvisational craft', 'Sharecropper domestic economy', 'Modernist abstraction (reception)'],
    rel: ['Amish Quilts', 'Baltimore Album Quilts', 'Hooked Rug Tradition', 'Seminole Patchwork'],
    src: [{ n: 'Wikipedia — Quilts of Gee\'s Bend', u: 'https://en.wikipedia.org/wiki/Quilts_of_Gee%27s_Bend', t: 'B' }, { n: 'Museum of Fine Arts, Houston', u: 'https://www.mfah.org', t: 'A' }, { n: 'National Museum of African American History & Culture', u: 'https://nmaahc.si.edu', t: 'A' }],
    tg: ['quilt', 'improvisation', 'african american', 'alabama', 'housetop', 'corduroy', 'folk art'],
    pop: 58, niche: false,
    vd: { shape: 'asymmetrical stacked blocks, housetop squares', line: 'torn-strip seams, wobbly but confident', composition: 'edge-to-edge improvisation, borders optional', texture: 'washed worn cotton, corduroy ridges' },
    typ: { display: 'quilters often sign or title backs (contemporary)', body: 'n/a — bed and wall textile', notes: 'early quilts unsigned; provenance by family' },
    lit: { quality: 'warm gallery wash', temperature: 'warm', shadow: 'soft fold shadows' },
    ui: { background: 'washed denim blue-gray', surface: 'patch-grid mosaic cards', components: 'irregular stitched-edge buttons', motion: 'quilt-fold panel transitions' },
  },
  {
    n: 'Baltimore Album Quilts', a: ['Album quilts', 'Presentation quilts', 'Friendship album quilts', 'Baltimore appliqué quilts', 'Signed album blocks'],
    cat: 'Textile & Craft', c: 'Mid-19th-century appliqué album quilts of Baltimore', e: 'historical',
    o: 'Baltimore, Maryland, USA', g: 'United States (Baltimore; spread to Mid-Atlantic and Midwest)', p: 'c. 1840-1860', era: 'Antebellum America',
    sum: 'Antebellum Baltimore\'s signature appliqué quilts — each block a separate ink-signed, red-and-green bouquet, wreath or monument — presented as collective friendship documents.',
    desc: 'Between about 1840 and the Civil War, Baltimore quilters made album quilts of individual appliquéd blocks — red-and-green bouquets, wreaths, ships, monuments and lodge emblems — each inked with names, dates and sentiments. Many were presentation pieces built through church, temperance and Methodist school networks; Mary Evans\' pupils and the workshop of Achsah Goodwin Wilkins produced celebrated examples. The style spread nationally through periodicals but peaked in Baltimore. The Maryland Center for History and Culture and Shelburne Museum hold landmark collections.',
    col: [{ h: '#a32c2c', n: 'chintz red' }, { h: '#2e5e3a', n: 'turkey green' }, { h: '#d8b74a', n: 'gold chintz' }, { h: '#efe8da', n: 'muslin ground' }, { h: '#1e1c1a', n: 'iron-gall ink' }],
    m: ['white muslin ground', 'red and green printed calicos', 'ink for signatures', 'cotton batting'],
    tx: ['turned-edge appliqué ridge', 'fine feather-quilting', 'inked script'],
    obj: ['signed presentation album quilts', 'whig rose and wreath blocks', 'ship and memorial blocks', 'temperance and lodge presentation quilts'],
    ex: ['Mary Evans school presentation quilts (1840s-50s)', 'Achsah Goodwin Wilkins workshop appliqué quilts', 'Maryland Center for History and Culture album collection'],
    inf: ['Chintz appliqué (broderie perse)', 'Friendship album traditions', 'Methodist women\'s networks', 'Needlework periodical publishing'],
    rel: ['Gee\'s Bend Quilts', 'Amish Quilts', 'Hooked Rug Tradition'],
    src: [{ n: 'Wikipedia — Baltimore album quilt', u: 'https://en.wikipedia.org/wiki/Baltimore_album_quilt', t: 'B' }, { n: 'Maryland Center for History and Culture', u: 'https://www.mdhistory.org', t: 'A' }, { n: 'Winterthur Museum, Garden & Library', u: 'https://www.winterthur.org', t: 'A' }],
    tg: ['album quilt', 'appliqué', 'presentation', 'baltimore', 'antebellum', 'ink signatures'],
    pop: 38, niche: true,
    vd: { shape: 'square grid of independent pictorial blocks', line: 'fine turned-edge appliqué contour', composition: 'three-by-three or four-by-four block albums with sashing', texture: 'crisp muslin under layered calico' },
    typ: { display: 'inked names, dates and sentiments on every block', body: 'n/a — bed and presentation textile', notes: 'signatures are primary documentation' },
    lit: { quality: 'even museum daylight', temperature: 'warm', shadow: 'minimal, quilted dimples only' },
    ui: { background: 'muslin white field', surface: 'block-grid framed cards', components: 'wreath-outline buttons', motion: 'block-by-block staggered reveals' },
  },
  {
    n: 'Amish Quilts', a: ['Pennsylvania Amish quilts', 'Diamond-in-the-square quilts', 'Amish patchwork', 'Ohio Amish quilts', 'Sunshine and shadow log cabins'],
    cat: 'Textile & Craft', c: 'Plain-community geometric quilting', e: 'regional_tradition',
    o: 'Pennsylvania, Ohio & Indiana, USA', g: 'United States (Lancaster PA, Holmes County OH, Elkhart-LaGrange IN)', p: 'c. 1870s-present', era: 'Gilded Age to present',
    sum: 'Severe, radiant geometric quilts from Plain communities — solid-color diamonds, bars and log cabins whose restraint became an icon of American abstraction.',
    desc: 'Amish quilting emerged in the late 1800s as Plain communities took up quilting but rejected printed calicos, working in solid dress-fabric woolens: Lancaster County\'s "diamond in the square," Ohio "bars" and Indiana "sunshine and shadow" log cabins, all disciplined by dense hand-quilted grids. Color followed each community\'s dress code — charcoal, grape, bottle green, dove gray. Collected as abstraction after the 1971 Whitney exhibition "Abstract Design in American Quilts," Amish quilts became a canonical American minimalism made for beds, not walls.',
    col: [{ h: '#2f2a4a', n: 'deep grape' }, { h: '#8c2f3a', n: 'dress red' }, { h: '#20201e', n: 'charcoal black' }, { h: '#4a5d43', n: 'bottle green' }, { h: '#cfc9bd', n: 'dove gray' }],
    m: ['solid dress-fabric wools and cottons', 'black cotton grounds', 'cotton batting', 'hand-quilting thread'],
    tx: ['crisp pressed seams', 'dense stipple quilting', 'twill dress cloth'],
    obj: ['diamond-in-the-square quilts', 'sunshine and shadow log cabins', 'center diamond quilts', 'bars quilts', 'feather-quilted wholecloth borders'],
    ex: ['Lancaster County diamond-in-the-square quilts', 'Holmes County bars quilts', 'Esprit collection Amish quilts (San Francisco)'],
    inf: ['Plain dress discipline', 'American quilting exchange networks', 'Minimalist abstraction (reception)'],
    rel: ['Gee\'s Bend Quilts', 'Baltimore Album Quilts', 'Shaker Furniture', 'Hawaiian appliqué quilts'],
    src: [{ n: 'Wikipedia — Amish', u: 'https://en.wikipedia.org/wiki/Amish', t: 'B' }, { n: 'International Quilt Museum, University of Nebraska', u: 'https://www.internationalquiltmuseum.org', t: 'A' }, { n: 'Shelburne Museum', u: 'https://shelburnemuseum.org', t: 'A' }],
    tg: ['quilt', 'amish', 'plain', 'geometry', 'minimalist', 'lancaster', 'solid color'],
    pop: 55, niche: false,
    vd: { shape: 'single dominant geometric field, framed borders', line: 'ruled seam lines, even quilting grid', composition: 'radiating center with generous solid margins', texture: 'matte dress wool, subtle quilt dimple' },
    typ: { display: 'n/a — rarely signed; ownership marks only', body: 'n/a — bed textile', notes: 'palette tied to community dress codes' },
    lit: { quality: 'even gallery light', temperature: 'cool-neutral', shadow: 'minimal, shallow quilt dimples' },
    ui: { background: 'near-black field', surface: 'solid-color geometric tiles', components: 'border-framed buttons', motion: 'measured grid fades' },
  },
  {
    n: 'Cowichan Knitting', a: ['Cowichan sweater', 'Siwash sweater', 'Quw\'utsun\' knitting', 'Coast Salish hand knitting'],
    cat: 'Fashion & Dress', c: 'Coast Salish hand-knit heavy wool sweater tradition', e: 'regional_tradition',
    o: 'Vancouver Island, British Columbia, Canada', g: 'Canada (Cowichan Valley, BC; traded across North America)', p: 'c. 1900-present', era: 'Early 20th century to present',
    sum: 'Chunky pullovers hand-knit by Coast Salish makers from undyed lanolin-rich wool — thunderbird, eagle and whale motifs in natural cream and charcoal, built for West Coast rain.',
    desc: 'Cowichan sweaters are heavy pullovers hand-knit on southeastern Vancouver Island, mostly by Quw\'utsun\' (Cowichan Tribes) knitters, from thick single-ply unscoured wool in natural cream, charcoal and mixed grays. Taking up hand-spinning and knitting after sheep reached the island in the mid-1800s, Coast Salish knitters built a roadside trade from the 1920s on undyed fleece worked with thunderbird, eagle and whale motifs. Sold to loggers, fishermen and later Hollywood costume houses, the sweaters are regalia-grade craft with natural weatherproofing.',
    col: [{ h: '#ece4d3', n: 'natural cream fleece' }, { h: '#2b2724', n: 'charcoal fleece' }, { h: '#8b8378', n: 'salt-and-pepper gray' }, { h: '#7a5a3c', n: 'natural brown fleece' }, { h: '#c7b79b', n: 'oatmeal mix' }],
    m: ['undyed handspun lambswool with lanolin', 'single-ply thick yarn', 'heavy hand knitting needles'],
    tx: ['lofty yarn halo', 'nubby hand-knit gauge', 'intarsia motif junctions'],
    obj: ['thunderbird-motif pullovers', 'eagle and whale sweaters', 'buttoned cardigan jackets', 'toques and mittens'],
    ex: ['Quw\'utsun\' knitters\' roadside sweaters (Duncan, BC)', 'Cowichan sweaters in NMAI collections', 'Hollywood costume pieces, e.g. The Rocketeer (1991)'],
    inf: ['Coast Salish weaving and spindle-whorl traditions', 'Settler sheep and wool economy', 'West Coast logging workwear'],
    rel: ['Coast Salish Spindle Whorls', 'Tlingit Chilkat Weaving', 'Button Blankets', 'Moccasin Traditions'],
    src: [{ n: 'Wikipedia — Cowichan knitting', u: 'https://en.wikipedia.org/wiki/Cowichan_knitting', t: 'B' }, { n: 'National Museum of the American Indian', u: 'https://americanindian.si.edu', t: 'A' }],
    tg: ['knitting', 'cowichan', 'coast salish', 'wool', 'thunderbird', 'canada', 'workwear'],
    pop: 37, niche: true,
    vd: { shape: 'boxy drop-shoulder pullover silhouettes', line: 'bold intarsia motif contours', composition: 'large centered band motif between striped yokes', texture: 'thick lanolin-rich loop stitches' },
    typ: { display: 'rarely lettered; occasional knit initials', body: 'full garment coverage', notes: 'motifs read as family and crest imagery' },
    lit: { quality: 'soft outdoor overcast', temperature: 'cool', shadow: 'deep at motif edges' },
    ui: { background: 'cream wool field', surface: 'charcoal motif panels', components: 'chunky toggle buttons', motion: 'slow knit-gauge reveals' },
  },
  {
    n: 'Métis Beadwork', a: ['Flower beadwork people', 'Métis floral beadwork', 'Métis appliqué beadwork', 'Red River floral style'],
    cat: 'Textile & Craft', c: 'Métis floral bead and silk embroidery tradition', e: 'regional_tradition',
    o: 'Canadian Prairies & Upper Midwest, Canada/USA', g: 'Canada (Red River, Manitoba, Saskatchewan) and United States (North Dakota, Montana, Great Lakes)', p: 'c. 1815-present', era: 'Fur-trade era to present',
    sum: 'Sinuous floral beadwork in glass seed beads and silk floss on smoked hide — the "flower beadwork people" of the Red River, decorating firebags, coats and moccasins.',
    desc: 'Métis women of the Red River and fur-trade country fused European silk-embroidery training learned in convent schools with Anishinaabe and Cree floral traditions, working curling stems, hollyhocks and lilies in glass seed beads and silk floss on smoke-tanned hide. Neighboring Nations called them "the flower beadwork people"; the style radiated from Red River across the Plains and Upper Midwest, shaping regional beadwork as it traded. Firebags, moccasin vamps, coats and octopus bags carried the signature style, revived today at Métis festivals and in contemporary art.',
    col: [{ h: '#8e2f4f', n: 'bead rose' }, { h: '#3c6e46', n: 'leaf green' }, { h: '#e5c14d', n: 'gold center' }, { h: '#4e6e9c', n: 'sky blue bead' }, { h: '#3a2a20', n: 'smoke-tanned hide' }],
    m: ['smoke-tanned hide', 'glass seed beads', 'silk floss', 'linen thread'],
    tx: ['raised bead loops', 'satin-floss sheen', 'tensioned beaded edge'],
    obj: ['beaded hide coats and capotes', 'moccasin vamps and flaps', 'octopus bags', 'saddle bags and gun cases', 'firebags (pipe bags)'],
    ex: ['Red River Métis firebags (Manitoba Museum)', 'Octopus bags in NMAI collections', 'Back to Batoche festival beadwork competitions'],
    inf: ['Great Lakes floral quillwork and beadwork', 'Convent silk-embroidery training', 'Plains hide-decoration trade'],
    rel: ['Moccasin Traditions', 'Lakota Porcupine Quillwork', 'Osage Ribbonwork', 'Ceinture Fléchée'],
    src: [{ n: 'Wikipedia — Métis', u: 'https://en.wikipedia.org/wiki/M%C3%A9tis', t: 'B' }, { n: 'Gabriel Dumont Institute — Virtual Museum of Métis History', u: 'http://www.metismuseum.ca', t: 'A' }, { n: 'National Museum of the American Indian', u: 'https://americanindian.si.edu', t: 'A' }],
    tg: ['beadwork', 'metis', 'floral', 'red river', 'hide', 'fur trade'],
    pop: 41, niche: false,
    vd: { shape: 'asymmetrical curling floral sprays', line: 'sinuous outlined bead-row stems', composition: 'mirror-paired vamps, edge-emphasis borders', texture: 'glossy beads over suede nap' },
    typ: { display: 'n/a — occasional initials and dates in beads', body: 'garment trim at cuffs, hems and yokes', notes: 'continuous floral run distinguishes Métis work' },
    lit: { quality: 'soft raking light on bead gloss', temperature: 'warm', shadow: 'tiny bead casts' },
    ui: { background: 'smoke-tan hide tone', surface: 'beaded floral corner sprays', components: 'seed-bead dotted buttons', motion: 'stem-curl draw-on animations' },
  },
  {
    n: 'Ceinture Fléchée', a: ['Assomption sash', 'Arrow sash', 'Assumption sash', 'Métis sash', 'Fléché sash'],
    cat: 'Fashion & Dress', c: 'French-Canadian finger-woven wool sash', e: 'regional_tradition',
    o: 'Québec, Canada', g: 'Canada (Québec; Métis Prairies; Great Lakes fur trade)', p: 'late 18th century-present', era: 'Fur-trade era to present',
    sum: 'Finger-woven arrow-pattern sashes of Québec and the Métis — belt, tumpline and trade good rolled into one blazing chevron of red, blue, green and white wool.',
    desc: 'The ceinture fléchée — "arrowed sash" — is a wide finger-woven band of colored wool worked without a loom, its bold V-arrow columns and Assomption variants tied to workshops at L\'Assomption, Québec, from the late 1700s. Voyageurs cinched capotes with it, used it as tumpline, pack strap and emergency rope, and it traveled the canoe routes west, where the Métis adopted a red sash as a national emblem. Machine weaving ended commercial output in the late 1800s, but folklore revivals keep hand-woven arrow sashes central to Québec and Métis dress.',
    col: [{ h: '#a02c2c', n: 'voyageur red' }, { h: '#24457c', n: 'indigo blue' }, { h: '#2e6e46', n: 'spring green' }, { h: '#e8e2d2', n: 'white wool' }, { h: '#d9a534', n: 'flame yellow' }],
    m: ['two-ply worsted wool yarn', 'hemp or linen core threads (early)', 'finger-weaving (no loom)'],
    tx: ['diagonal weave ridges', 'flat herringbone hand', 'twisted fringe ends'],
    obj: ['voyageur belt sashes', 'Métis ceremonial sashes', 'tumplines (portage straps)', 'capote-coat ensembles'],
    ex: ['Assomption sashes in McCord Stewart Museum (Montréal)', 'Métis red sashes at Back to Batoche', 'Voyageur capote-and-sash recreations, Fort William Historical Park'],
    inf: ['French-Canadian voyageur culture', 'Eastern Woodlands finger-weaving', 'Métis national symbolism'],
    rel: ['Métis Beadwork', 'Moccasin Traditions', 'Haudenosaunee Wampum & Beadwork'],
    src: [{ n: 'Wikipedia — Ceinture fléchée', u: 'https://en.wikipedia.org/wiki/Ceinture_fl%C3%A9ch%C3%A9e', t: 'B' }, { n: 'Gabriel Dumont Institute — Virtual Museum of Métis History', u: 'http://www.metismuseum.ca', t: 'A' }],
    tg: ['sash', 'finger weaving', 'voyageur', 'metis', 'quebec', 'wool'],
    pop: 38, niche: true,
    vd: { shape: 'long rectangular band, V-arrow columns', line: 'stepped diagonal chevron edges', composition: 'symmetrical central motif field with fringed ends', texture: 'dense diagonal wool weave' },
    typ: { display: 'names and dates rarely woven in', body: 'worn at waist or across shoulder', notes: 'color sequences signal community identity' },
    lit: { quality: 'bright even daylight', temperature: 'warm', shadow: 'shallow weave grooves' },
    ui: { background: 'cream wool ground', surface: 'chevron stripe banners', components: 'arrow-striped buttons', motion: 'woven horizontal slides' },
  },
  {
    n: 'Mexican Tinwork (Hojalata)', a: ['Hojalata', 'Punched tin', 'Mexican punched tin', 'Tin nichos', 'Oaxacan tin art'],
    cat: 'Material & Surface', c: 'Mexican punched and painted tin folk art', e: 'regional_tradition',
    o: 'Central & Northern Mexico', g: 'Mexico (Oaxaca, San Miguel de Allende, Zacatecas; U.S. Southwest markets)', p: '19th century-present', era: 'Porfiriato to present',
    sum: 'Stamped, punched and painted tinplate — mirrors, nichos, ex-votos and festival ornaments — a "poor man\'s silver" folk art of Mexican homes, shrines and cantinas.',
    desc: 'Hojalata is Mexican folk art in tinplate: sheets cut, stamped, punched and repousséd into nichos (shadow-box shrines), mirror frames, lanterns, ex-votos and festival ornaments, then painted in bright lacquers or left scoured and bright. A "poor man\'s silver" for home altars and cantinas, it spread through central and northern Mexico in the 1800s, with Oaxaca and San Miguel de Allende famous workshop centers; borderlands markets carried it into the U.S. Southwest, where the Museum of International Folk Art holds major collections.',
    col: [{ h: '#b9bec4', n: 'punched tin silver' }, { h: '#c93a2e', n: 'lacquer red' }, { h: '#2e7ea8', n: 'painted blue' }, { h: '#e9b83c', n: 'marigold yellow' }, { h: '#3a7d4f', n: 'foliage green' }],
    m: ['tinplate sheet (hojalata)', 'punches, chisels and stamps', 'oil paints and clear lacquer'],
    tx: ['repoussé relief bumps', 'punched dot sparkle', 'lacquered oil gloss'],
    obj: ['nichos shrine boxes', 'mirrored frames and tin candelabra', 'Day of the Dead ornaments', 'painted tin ex-votos', 'cantina signs and lanterns'],
    ex: ['Oaxaca tin workshops\' nichos', 'San Miguel de Allende punched-tin mirrors', 'Museum of International Folk Art hojalata collection (Santa Fe)'],
    inf: ['Spanish colonial silverwork', 'Ex-voto retablo painting', 'Day of the Dead visual culture'],
    rel: ['Ex-voto Retablo', 'Santero Tradition'],
    src: [{ n: 'Wikipedia — Mexican handcrafts and folk art', u: 'https://en.wikipedia.org/wiki/Mexican_handcrafts_and_folk_art', t: 'B' }, { n: 'Wikipedia — Tin art', u: 'https://en.wikipedia.org/wiki/Tin_art', t: 'B' }, { n: 'Museum of International Folk Art, Santa Fe', u: 'https://www.internationalfolkart.org', t: 'A' }],
    tg: ['tin', 'hojalata', 'folk art', 'nichos', 'punched', 'oaxaca', 'day of the dead'],
    pop: 40, niche: false,
    vd: { shape: 'arched nichos, heart and cross plaques', line: 'chiseled borders, punched dotted contours', composition: 'symmetrical shrine niche with layered figures', texture: 'stamped bright tin catching light' },
    typ: { display: 'hand-painted banners and lettering on signs', body: 'n/a — decorative object art', notes: 'nichos frame prints and small statuettes' },
    lit: { quality: 'high sparkle speculars', temperature: 'warm', shadow: 'punched perforations cast pin-stars' },
    ui: { background: 'lacquered red ground', surface: 'stamped-tin accent cards', components: 'foil-bright icon buttons', motion: 'glinting highlight sweeps' },
  },
  {
    n: 'Santero Tradition', a: ['New Mexican santeros', 'Bulto carving', 'Santos of New Mexico', 'Hide retablos', 'Hispano religious art'],
    cat: 'Regional & Cultural Tradition', c: 'New Mexican Hispanic saint-carving and painting tradition', e: 'regional_tradition',
    o: 'New Mexico, USA', g: 'United States (Rio Grande valley villages; southern Colorado)', p: 'late 18th century-present', era: 'Spanish colonial New Mexico to present',
    sum: 'Hispano villages\' sacred art — carved and painted saints on pine panels and hide — born of colonial isolation in New Mexico and revived as a living heritage craft.',
    desc: 'When New Mexico\'s villages stood far from Mexican workshop art, Hispano santeros made their own: bultos (carved saint figures) from pine and cottonwood root, and painted retablos on pine panels, worked in gypsum-and-hide-glue gesso, earth pigments and piñon-sap varnish. Early masters such as José Aragón, Pedro Antonio Fresquis and the Laguna Santero set the idiom\'s frontal, hieratic style for home altars and village churches. The Spanish Colonial Arts Society (founded 1925) and Santa Fe\'s Spanish Market revived the tradition, which living santeros carry today.',
    col: [{ h: '#7a3b2e', n: 'red earth' }, { h: '#c9a441', n: 'yellow ochre' }, { h: '#4a5a3a', n: 'sap green' }, { h: '#e5dbc0', n: 'gesso cream' }, { h: '#241d16', n: 'pine brown' }],
    m: ['carved pine and cottonwood', 'gypsum-and-hide-glue gesso', 'natural earth pigments', 'piñon-sap varnish', 'tanned hide (early retablos)'],
    tx: ['hand-carved chisel facets', 'gesso brush drag', 'varnish ambering'],
    obj: ['bultos (freestanding saint figures)', 'retablos (painted panels)', 'cruz de ánimas processional crosses', 'home altar screens'],
    ex: ['José Aragón retablos in Smithsonian collections', 'Laguna Santero colonial altarscreens', 'Contemporary Spanish Market santeros, Santa Fe'],
    inf: ['European devotional prints', 'Pueblo pigment and gesso practice', 'Spanish Colonial Arts revival'],
    rel: ['Ex-voto Retablo', 'Mexican Tinwork (Hojalata)', 'Hopi Katsina Doll Carving'],
    src: [{ n: 'Wikipedia — Santo (art)', u: 'https://en.wikipedia.org/wiki/Santo_(art)', t: 'B' }, { n: 'Smithsonian American Art Museum — santero collection', u: 'https://americanart.si.edu', t: 'A' }, { n: 'Museum of International Folk Art, Santa Fe', u: 'https://www.internationalfolkart.org', t: 'A' }],
    tg: ['santero', 'santos', 'bulto', 'retablo', 'new mexico', 'colonial', 'devotional'],
    pop: 39, niche: true,
    vd: { shape: 'flat panel saints, frontal hieratic bultos', line: 'naive confident outline with hatched shading', composition: 'centered figure on plain ground, border arcs', texture: 'gesso tooth under thin pigment' },
    typ: { display: 'saint names and titles inscribed in gesso', body: 'n/a — devotional object art', notes: 'panels often titled in Spanish' },
    lit: { quality: 'candle-warm pools', temperature: 'warm', shadow: 'soft carve recesses' },
    ui: { background: 'gesso cream ground', surface: 'retablo panel cards', components: 'painted arc buttons', motion: 'slow pigment-wash fades' },
  },
  {
    n: 'Adirondack Rustic Furniture', a: ['Great Camp furnishings', 'Rustic twig furniture', 'Old Forge rustic', 'Burl and root furniture'],
    cat: 'Regional & Cultural Tradition', c: 'Adirondack camp furniture and interior craft', e: 'historical',
    o: 'Adirondacks, New York, USA', g: 'United States (Adirondack region; national lodge and park adaptations)', p: 'c. 1870-1940 (revival 1980s-present)', era: 'Gilded Age to interwar America',
    sum: 'Unpeeled-branch chairs, burl tables and root beds built for Gilded Age "Great Camps" — wilderness luxury where the forest itself furnished the room.',
    desc: 'As Gilded Age industrialists built the Adirondack Great Camps from the 1870s on, guides and estate carpenters furnished them in the region\'s own materials: unpeeled birch and cherry saplings bent into chairs, settees and beds, burl slabs as table tops, root and antler accents, joints lashed in rawhide or wire. The Old Forge workshops made the "rustic" a named trade, and camp interiors at Santanoni and Sagamore preserve the look — nature assembled indoors. A 1980s-90s revival brought rustic furniture back into the craft marketplace.',
    col: [{ h: '#5a4632', n: 'birch bark brown' }, { h: '#4a3b28', n: 'heartwood brown' }, { h: '#8c7a5c', n: 'peeled twig tan' }, { h: '#2e2618', n: 'log charcoal' }, { h: '#a68a5b', n: 'burl amber' }],
    m: ['unpeeled birch and cherry saplings', 'burl slabs', 'mountain-ash and willow twigs', 'rawhide lashings and wire', 'root and antler accents'],
    tx: ['bark-ridged members', 'burl swirl', 'lashed joints'],
    obj: ['rustic chairs and settees', 'burl-top tables', 'branch-frame beds', 'fern stands and magazine stands', 'lodge interiors with antler fittings'],
    ex: ['Great Camp furniture at Camp Santanoni and Sagamore', 'Adirondack Experience museum rustics', '1980s-90s Old Forge revival workshops'],
    inf: ['Gilded Age wilderness resorts', 'Arts and Crafts "back to nature"', 'Adirondack guide culture'],
    rel: ['Shaker Furniture', 'Nantucket Lightship Baskets', 'Hooked Rug Tradition'],
    src: [{ n: 'Wikipedia — Adirondack Architecture', u: 'https://en.wikipedia.org/wiki/Adirondack_Architecture', t: 'B' }, { n: 'Wikipedia — Great Camps', u: 'https://en.wikipedia.org/wiki/Great_Camps', t: 'B' }, { n: 'Adirondack Experience (Adirondack Museum)', u: 'https://www.theadkx.org', t: 'A' }],
    tg: ['rustic', 'adirondack', 'great camps', 'twig furniture', 'gilded age', 'lodge'],
    pop: 37, niche: true,
    vd: { shape: 'as-grown branch arches and forked legs', line: 'sinuous sapling curves', composition: 'whole-forest assemblage, burl focal slabs', texture: 'bark-on roughness, lashed nodes' },
    typ: { display: 'shop stamps and branded marks only', body: 'n/a — furniture', notes: 'bark left on as finish' },
    lit: { quality: 'dappled lodge light', temperature: 'warm', shadow: 'deep twig lattice shadows' },
    ui: { background: 'bark brown gradient', surface: 'branch-textured panels', components: 'node-knot buttons', motion: 'organic branch-draw reveals' },
  },
  {
    n: 'Nantucket Lightship Baskets', a: ['Lightship baskets', 'Nantucket baskets', 'Lightship purse baskets', 'Friendship baskets (Reyes)'],
    cat: 'Regional & Cultural Tradition', c: 'Nantucket wooden-stave basket craft', e: 'regional_tradition',
    o: 'Nantucket, Massachusetts, USA', g: 'United States (Nantucket; New England makers)', p: 'c. 1850-present', era: 'Whaling-era New England to present',
    sum: 'Fine round stave baskets woven on molds with rattan over hardwood bases — born aboard Nantucket lightships, now a signature New England luxury craft.',
    desc: 'Nantucket\'s lightship baskets were built aboard the island\'s South Shoal lightvessel from the 1850s: crews carved solid hardwood bases and staves, weaving rattan cane around wooden molds into fine, round, extremely sturdy baskets. Ashore, island makers adapted the form to covered purses with whale-ivory fittings; José Formoso Reyes\' "friendship basket" (1952) made the lightship purse an island icon. Maker-signed bases and molds document generations of Nantucket basketmakers, and the craft remains a living luxury tradition.',
    col: [{ h: '#8a5a34', n: 'hardwood base brown' }, { h: '#c9ae7d', n: 'rattan cane tan' }, { h: '#e8dcc2', n: 'whale ivory cream' }, { h: '#3a2e20', n: 'stave walnut' }, { h: '#6b4a2e', n: 'hickory gold-brown' }],
    m: ['solid hardwood bases and staves', 'rattan cane weavers', 'whale ivory and bone accents', 'wooden molds'],
    tx: ['tight parallel weave', 'stave gloss', 'ivory polish'],
    obj: ['round open baskets', 'friendship-basket purses', 'covered sewing baskets', 'scrimshaw-accented handbags'],
    ex: ['José Formoso Reyes friendship baskets (from 1952)', 'South Shoal lightship crew baskets', 'Nantucket Historical Association basket collection'],
    inf: ['Lightship station life', 'Whaling scrimshaw ivory trades', 'Shaker and New England basket forms'],
    rel: ['Shaker Furniture', 'Decoy Carving Traditions', 'Adirondack Rustic Furniture'],
    src: [{ n: 'Wikipedia — Nantucket basket', u: 'https://en.wikipedia.org/wiki/Nantucket_basket', t: 'B' }, { n: 'Nantucket Historical Association', u: 'https://www.nha.org', t: 'A' }],
    tg: ['basket', 'nantucket', 'lightship', 'rattan', 'purse', 'new england'],
    pop: 35, niche: true,
    vd: { shape: 'upright round stave cylinders, oval purse forms', line: 'vertical stave rhythm, horizontal weavers', composition: 'ivory clasp focal point on disciplined weave', texture: 'smooth rattan over glossy wood' },
    typ: { display: 'maker signatures on bases and tags', body: 'n/a — basket craft', notes: 'signed molds document lineage' },
    lit: { quality: 'bright maritime daylight', temperature: 'neutral-warm', shadow: 'fine weave striping' },
    ui: { background: 'cane tan ground', surface: 'stave-striped panels', components: 'ivory-cream toggles', motion: 'weave-build staggered reveals' },
  },
  {
    n: 'Decoy Carving Traditions', a: ['Waterfowl decoy carving', 'Chesapeake school decoys', 'Working decoys', 'Wildfowl carving'],
    cat: 'Material & Surface', c: 'North American hunting decoy carving', e: 'regional_tradition',
    o: 'US Atlantic coast & Great Lakes', g: 'United States and Canada (Chesapeake Bay, New Jersey shore, Great Lakes, Louisiana; St. Lawrence)', p: 'mid-19th century-present', era: 'Market-hunting era to present',
    sum: 'Carved and painted wooden waterfowl lures — from weathered Chesapeake canvasback rigs to folk sculpture now prized as signature American art.',
    desc: 'Mid-1800s market hunters and guides carved working waterfowl decoys by the rigful: hollow-bodied cedar canvasbacks on the Chesapeake, broadbill "sleepers" on the New Jersey shore, divers on the Illinois River and St. Lawrence. Regional schools show in silhouette, paint and wear. The Migratory Bird Treaty of 1918 ended market gunning, and folk-art collectors in the 1960s-70s — championed by Crisfield\'s Ward brothers, Lem and Steve — turned working decoys into prized American sculpture. The Ward Museum in Salisbury, Maryland, anchors the field.',
    col: [{ h: '#3a2e22', n: 'weathered cedar' }, { h: '#8c2f2e', n: 'canvasback red' }, { h: '#4a4e55', n: 'bluebill slate' }, { h: '#e0d6b8', n: 'bufflehead cream' }, { h: '#33382e', n: 'black duck brown' }],
    m: ['white cedar and pine blanks', 'oil paints', 'glass tack eyes', 'lead keel weights'],
    tx: ['hollow-body tap', 'chipped working wear', 'brushed feather paint'],
    obj: ['canvasback rig pairs', 'Canada goose standers', 'broadbill sleeper rigs', 'shorebird stick-ups', 'competition carvings'],
    ex: ['Lem and Steve Ward Chesapeake decoys', 'Shelburne Museum working decoy collection', 'Ward Museum championship carvings'],
    inf: ['Market-hunting culture', 'Migratory Bird Treaty Act of 1918', 'American folk art collecting'],
    rel: ['Nantucket Lightship Baskets', 'Adirondack Rustic Furniture'],
    src: [{ n: 'Wikipedia — Decoy', u: 'https://en.wikipedia.org/wiki/Decoy', t: 'B' }, { n: 'Ward Museum of Wildfowl Art, Salisbury University', u: 'https://www.wardmuseum.org', t: 'A' }, { n: 'Shelburne Museum', u: 'https://shelburnemuseum.org', t: 'A' }],
    tg: ['decoy', 'waterfowl', 'carving', 'chesapeake', 'folk art', 'hunting'],
    pop: 42, niche: false,
    vd: { shape: 'sleeping and swimming hull forms, simplified wings', line: 'few confident knife planes', composition: 'rig repetition across open water', texture: 'battered paint over cedar grain' },
    typ: { display: 'carved or branded maker initials', body: 'n/a — object art', notes: 'working wear read as provenance' },
    lit: { quality: 'low marsh light', temperature: 'cool-warm', shadow: 'breast highlight, keel shadow' },
    ui: { background: 'marsh drab green', surface: 'paint-worn swatch cards', components: 'round eye-dot buttons', motion: 'slow water-bob floats' },
  },
  {
    n: 'Button Blankets', a: ['Button robes', 'Kwakwaka\'wakw button blankets', 'Crest blankets', 'Tlingit button blankets', 'Dance blankets'],
    cat: 'Fashion & Dress', c: 'Northwest Coast ceremonial crest blankets', e: 'regional_tradition',
    o: 'Pacific Northwest Coast, Canada/USA', g: 'Canada (BC coast) and United States (southeast Alaska, Washington)', p: 'mid-19th century-present', era: 'Trade-cloth era to present',
    sum: 'Trade blankets transformed with felt clan crests edged in pearl buttons — the blaze of Northwest Coast potlatch, dance and identity from Alaska to Washington.',
    desc: 'From the mid-1800s, Nations up and down the Northwest Coast — Tlingit, Haida, Tsimshian, Kwakwaka\'wakw, Nuu-chah-nulth, Coast Salish — reinterpreted crest regalia in trade goods: navy or red wool blankets appliquéd with felt clan crests (eagle, raven, killer whale, frog) and outlined in rows of pearl buttons that blaze in firelight. Worn at potlatches, memorial dances and honouring ceremonies, button blankets carry inherited crest rights; their making resumed openly after the potlatch ban ended in 1951 and is now taught widely along the coast.',
    col: [{ h: '#1d2b4a', n: 'navy flannel' }, { h: '#9e2a2e', n: 'red flannel' }, { h: '#ece7dc', n: 'pearl button white' }, { h: '#1e1c1a', n: 'crest black felt' }, { h: '#c94f3e', n: 'appliqué red felt' }],
    m: ['commercial wool blankets', 'mother-of-pearl shell buttons', 'felt and flannel appliqué', 'family pattern boards'],
    tx: ['dense button rows', 'felt nap', 'flannel drape'],
    obj: ['crest dance blankets', 'potlatch robes', 'memorial blankets', 'graduation and honouring regalia'],
    ex: ['Kwakwaka\'wakw potlatch dance blankets (U\'mista Cultural Centre)', 'Tlingit clan crest blankets, Sealaska Heritage Institute', 'Haida crest robes in NMAI collections'],
    inf: ['Chilkat weaving crest traditions', 'Hudson\'s Bay blanket trade', 'Potlatch ban and revival (1885-1951)'],
    rel: ['Tlingit Chilkat Weaving', 'Haida Argillite Carving', 'Coast Salish Spindle Whorls', 'Moccasin Traditions'],
    src: [{ n: 'Wikipedia — Button blanket', u: 'https://en.wikipedia.org/wiki/Button_blanket', t: 'B' }, { n: 'U\'mista Cultural Centre', u: 'https://www.umista.ca', t: 'A' }, { n: 'Sealaska Heritage Institute', u: 'https://www.sealaskaheritage.org', t: 'A' }],
    tg: ['button blanket', 'crest', 'northwest coast', 'potlatch', 'regalia', 'clan'],
    pop: 38, niche: true,
    vd: { shape: 'rectangular robe, central crest panel', line: 'button-row contours outlining the crest', composition: 'bold centered heraldic figure, button frame borders', texture: 'button sparkle over wool matte' },
    typ: { display: 'n/a — crests over text', body: 'full ceremonial garment', notes: 'crest ownership follows family rights' },
    lit: { quality: 'firelight-friendly speculars', temperature: 'warm', shadow: 'felt relief casting' },
    ui: { background: 'navy wool field', surface: 'pearl-button bordered cards', components: 'button-row dividers', motion: 'dance-shimmer highlights' },
  },
  {
    n: 'Moccasin Traditions', a: ['Plains beaded moccasins', 'Woodlands hide moccasins', 'Beaded vamps', 'Native American moccasins'],
    cat: 'Fashion & Dress', c: 'North American Indigenous hide footwear craft', e: 'regional_tradition',
    o: 'North America-wide', g: 'United States and Canada (Plains, Woodlands, Subarctic, Southwest)', p: 'precontact-present', era: 'Fur trade to present',
    sum: 'The continent\'s Indigenous footwear — smoked-hide shoes stitched with sinew and crowned with beadwork, in regional dialects from Woodland florals to Plains geometry.',
    desc: 'Moccasin (from Ojibwe makizin) names the hide footwear of Turtle Island\'s Nations, and its regional dialects are unmistakable: Woodland puckered-toe and side-seam forms with floral beadwork, hard-sole Plains moccasins with geometric panels, Haudenosaunee over-flap gauntlets. Trade seed beads replaced quillwork through the 1800s, fixing signature palettes; sinew-stitched construction, ribbon-appliqué leggings and fully beaded vamps — the stuff of memorials like Walking With Our Sisters — keep the craft in daily and ceremonial use.',
    col: [{ h: '#6b4a30', n: 'smoked hide' }, { h: '#8e2f4f', n: 'bead rose' }, { h: '#2e4a7e', n: 'cobalt bead' }, { h: '#e8e2d2', n: 'white bead' }, { h: '#3a7d4f', n: 'leaf green bead' }],
    m: ['smoked and brain-tanned hide', 'sinew thread', 'glass seed beads', 'rawhide soles (Plains hard-sole)', 'silk ribbon (Woodlands)'],
    tx: ['raised bead texture', 'hide nap softness', 'flat two-needle appliqué'],
    obj: ['Plains beaded moccasins', 'Woodland pucker-toe moccasins', 'Haudenosaunee over-flap pairs', 'ribbon-appliqué leggings', 'memorial vamps (Walking With Our Sisters)'],
    ex: ['Plains fully beaded pairs in NMAI collections', 'Haudenosaunee over-flap moccasins, Bata Shoe Museum', 'Walking With Our Sisters memorial vamps (2013-19)'],
    inf: ['Porcupine quillwork techniques', 'Trade bead economy', 'Powwow regalia culture'],
    rel: ['Lakota Porcupine Quillwork', 'Métis Beadwork', 'Osage Ribbonwork', 'Haudenosaunee Wampum & Beadwork'],
    src: [{ n: 'Wikipedia — Moccasin', u: 'https://en.wikipedia.org/wiki/Moccasin', t: 'B' }, { n: 'Bata Shoe Museum, Toronto', u: 'https://www.batashoemuseum.ca', t: 'A' }, { n: 'National Museum of the American Indian', u: 'https://americanindian.si.edu', t: 'A' }],
    tg: ['moccasin', 'beadwork', 'plains', 'woodlands', 'vamps', 'footwear', 'regalia'],
    pop: 48, niche: false,
    vd: { shape: 'low hide slipper forms, soft upturn toe', line: 'beaded contour bands framing the instep', composition: 'symmetrical vamps, repeated panels at cuffs', texture: 'matte nap against glass-bead gloss' },
    typ: { display: 'n/a — occasional owner initials in beads', body: 'full footwear', notes: 'regional beadwork signals nation and era' },
    lit: { quality: 'soft directional daylight', temperature: 'warm', shadow: 'bead casts tiny shade sparks' },
    ui: { background: 'smoked hide tan', surface: 'beaded band panels', components: 'bead-row buttons', motion: 'step-synced pattern walks' },
  },
]
