/**
 * Wave 12 — historical period styles.
 * All names are real, documented period styles/art movements; sources are
 * stable institutional URLs (Wikipedia articles verified HTTP 200, plus museums).
 */
export const ENTRIES: any[] = [
  {
    n: 'Amarna Period Art', a: ['Amarna art', 'Tell el-Amarna style'],
    cat: 'Historical Period Style', c: 'Naturalistic art of Akhenaten\'s religious revolution', e: 'historical',
    o: 'Akhetaten (Amarna), Egypt', g: 'New Kingdom Egypt (18th Dynasty; influence across Nile Valley workshops)', p: 'c. 1353-1336 BC', era: 'New Kingdom, 18th Dynasty Egypt',
    sum: 'The revolutionary art style of Akhenaten\'s reign: fluid naturalism, tender royal family scenes and the radiant Aten disk set against Egypt\'s rigid millennia-old canon.',
    desc: 'Akhenaten\'s religious revolution produced Egypt\'s most distinctive art episode. At his capital Akhetaten the old canon relaxed: elongated skulls, soft bellies and tender royal family poses beneath the Aten disk whose rays end in tiny hands. Signature works include Thutmose\'s painted Nefertiti bust, lively talatat relief blocks, boundary stelae and household altars. After his death the style was suppressed and its monuments dismantled, but its naturalism echoes through Tutankhamun-era workshops and still makes Amarna the most human moment of ancient Egyptian art.',
    col: [{ h: '#e8dcc4', n: 'limestone cream' }, { h: '#2a4d8f', n: 'Egyptian blue' }, { h: '#c17434', n: 'ochre orange' }, { h: '#c9a227', n: 'gold leaf' }, { h: '#3b2f2f', n: 'kohl brown' }],
    m: ['talatat limestone blocks', 'painted gypsum plaster', 'faience inlay', 'polished calcite (Egyptian alabaster)'],
    tx: ['crisp sunk-relief edge', 'limewash matte paint', 'polished stone sheen'],
    obj: ['painted Nefertiti-style busts', 'talatat relief blocks', 'boundary stelae', 'household ancestor altars', 'Aten hymn cartouches'],
    ex: ['Bust of Nefertiti (Neues Museum, Berlin)', 'Amarna boundary stelae at Akhetaten', 'Tomb of Meryre II reliefs, Amarna'],
    inf: ['Traditional Theban canon', 'Atenist religious reform', 'Old Kingdom relief carving'], rel: ['Egyptian Revival', 'Egyptian Style'],
    src: [{ n: 'Wikipedia — Amarna art', u: 'https://en.wikipedia.org/wiki/Amarna_art', t: 'B' }, { n: 'The Metropolitan Museum of Art — Egyptian art collection', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['amarna', 'akhenaten', 'aten', 'new kingdom', 'naturalism', 'talatat', 'nefertiti', '18th dynasty'],
    pop: 38, niche: true,
    vd: { shape: 'elongated soft-bellied figures with drooping heads', line: 'flowing sunk-relief contour', composition: 'intimate family groups beneath the ray-handed Aten disk', texture: 'painted limestone with crisp sunk edges' },
    typ: { display: 'Papyrus', body: 'Optima', notes: 'Noto Sans Egyptian Hieroglyphs for glyph runs' },
    lit: { quality: 'hard desert sunlight', temperature: 'warm', shadow: 'high-contrast, edge-defined' },
    ui: { background: 'limestone cream parchment', surface: 'sunk-relief bordered panels', components: 'cartouche-shaped buttons and Aten-disk toggles', motion: 'slow sun-disk glow shifts' },
  },
  {
    n: 'Minoan Art', a: ['Minoan fresco tradition', 'Aegean Bronze Age Cretan art'],
    cat: 'Historical Period Style', c: 'Bronze Age Cretan palace art', e: 'historical',
    o: 'Crete, Aegean Sea', g: 'Aegean world (Crete, Thera, mainland trade outposts)', p: 'c. 3100-1100 BC (peak 2000-1450 BC)', era: 'Aegean Bronze Age',
    sum: 'Marine-and-motion art of Bronze Age Crete: bull-leaping and dolphin frescoes, Kamares polychrome pottery and sinuous nature imagery across palace walls.',
    desc: 'Minoan art is the palace culture of Bronze Age Crete — Knossos, Phaistos, Mallia — delighting in sea life, bulls and plants caught mid-motion. Wet frescoes of bull-leapers, dolphins and crocus gatherers fill court halls; Kamares ware swirls bright polychrome over black slip; Marine-style jars swim with painted octopi. Gold bee pendants, faience snake goddesses and carved stone rhyta round out the repertoire. After the Thera eruption and the Mycenaean takeover the palaces fell silent, yet this exuberant grace marks the first great European art.',
    col: [{ h: '#e6e2d3', n: 'lime plaster white' }, { h: '#c0392b', n: 'Cretan fresco red' }, { h: '#1f6f8b', n: 'marine blue' }, { h: '#e0a80d', n: 'saffron yellow' }, { h: '#3e2723', n: 'Kamares black' }],
    m: ['wet lime plaster', 'fine levigated clay slip', 'faience', 'steatite and gold'],
    tx: ['buoyant wet-fresco blur', 'eggshell-thin burnished slip', 'repousse gold ripple'],
    obj: ['bull-leaping frescoes', 'Kamares "eggshell" cups', 'Marine-style stirrup jars', 'snake goddess figurines', 'bull\'s-head rhyta'],
    ex: ['Bull-Leaping Fresco, Knossos Palace', 'Harvester Vase from Agia Triada', 'Spring Frescoes from Akrotiri, Thera'],
    inf: ['Egyptian wall painting technique', 'Cycladic figurine carving', 'Near Eastern goldsmithing'],
    rel: ['Egyptian Style', 'Pompeian Fourth Style Illusionism'],
    src: [{ n: 'Wikipedia — Minoan art', u: 'https://en.wikipedia.org/wiki/Minoan_art', t: 'B' }, { n: 'The Metropolitan Museum of Art — Aegean collection', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['minoan', 'crete', 'bronze age', 'fresco', 'kamares', 'knossos', 'bull-leaping', 'aegean'],
    pop: 45, niche: true,
    vd: { shape: 'sinuous octopus arms, flying-gallop poses, horned altars', line: 'curving confident outline', composition: 'frieze bands and floating figures over plain ground', texture: 'matte mineral pigment on smooth lime plaster' },
    typ: { display: 'Korinna', body: 'Palatino', notes: 'Linear B sign runs via Noto Sans Linear B' },
    lit: { quality: 'bright Aegean daylight', temperature: 'warm', shadow: 'minimal, flat color fields' },
    ui: { background: 'plaster white', surface: 'fresco frieze banners', components: 'rounded wave-arc buttons', motion: 'gentle undulating drifts' },
  },
  {
    n: 'Etruscan Art', a: ['Etruscan style', 'Art of ancient Etruria'],
    cat: 'Historical Period Style', c: 'Pre-Roman Italian art of the Etruscans', e: 'historical',
    o: 'Etruria (Tuscany, Lazio, Umbria), Italy', g: 'Central Italy with colonies in Campania and the Po Valley', p: 'c. 900-27 BC (peak 7th-5th century BC)', era: 'Iron Age Italy to Roman conquest',
    sum: 'Vivid pre-Roman Italian art: painted banquet tombs, smiling terracotta sarcophagi, black bucchero pottery and supreme bronzework absorbed into Roman art.',
    desc: 'Etruscan art flourished in the city-states of ancient Etruria before Roman absorption. Painted tombs at Tarquinia and Cerveteri brim with banquets, dancers and musicians; the terracotta Sarcophagus of the Spouses shows a couple reclining with Archaic smiles. Artisans excelled in black bucchero pottery, engraved bronze mirrors, votive bronzes and gold granulation, while Greek vases were imported and imitated. Native warmth produced lively funerary portraiture, and much of what survives as early Roman art was Etruscan in hand and spirit.',
    col: [{ h: '#b5651d', n: 'terracotta orange' }, { h: '#26221f', n: 'bucchero black' }, { h: '#8e2b25', n: 'tomb-painting red' }, { h: '#e3d9c0', n: 'fresco cream' }, { h: '#6d8a68', n: 'bronze patina' }],
    m: ['black bucchero clay', 'modelled terracotta', 'bronze and engraved mirrors', 'gold granulation'],
    tx: ['smoky burnished bucchero sheen', 'soft terracotta modeling', 'ruddy tomb-plaster matte'],
    obj: ['terracotta sarcophagi of couples', 'bucchero kantharoi', 'engraved bronze mirrors', 'canopic urns', 'votive bronze figures'],
    ex: ['Sarcophagus of the Spouses (Cerveteri, Louvre)', 'Chimera of Arezzo (Florence)', 'Tomb of the Leopards frescoes, Tarquinia'],
    inf: ['Greek Archaic sculpture', 'Villanovan metalwork', 'Phoenician goldsmithing'],
    rel: ['Pompeian Fourth Style Illusionism', 'Greek Revival'],
    src: [{ n: 'Wikipedia — Etruscan art', u: 'https://en.wikipedia.org/wiki/Etruscan_art', t: 'B' }, { n: 'The Metropolitan Museum of Art — Etruscan collection', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['etruscan', 'bucchero', 'tarquinia', 'sarcophagus', 'bronze', 'pre-roman italy', 'tomb painting'],
    pop: 40, niche: true,
    vd: { shape: 'reclining banqueters and wide-hipped figures', line: 'loose painted contour with Archaic smile curves', composition: 'banquet friezes ringing tomb walls', texture: 'matte earth pigments over rough plaster' },
    typ: { display: 'Cinzel', body: 'EB Garamond', notes: 'Old Italic letters via Noto Sans Old Italic' },
    lit: { quality: 'torch-lit interior warmth', temperature: 'warm', shadow: 'deep tomb vault shadows' },
    ui: { background: 'fresco cream', surface: 'terracotta framed cards', components: 'bronze-patina rounded buttons', motion: 'candle-flicker reveals' },
  },
  {
    n: 'Byzantine Aesthetics', a: ['Byzantine art', 'Byzantine style'],
    cat: 'Historical Period Style', c: 'Sacred art of the Eastern Roman Empire', e: 'historical',
    o: 'Constantinople (Byzantium)', g: 'Eastern Mediterranean, Balkans, Anatolia, Rus and the Orthodox world', p: '330-1453 AD', era: 'Eastern Roman (Byzantine) Empire',
    sum: 'The sacred visual order of the Eastern Roman Empire: gold-ground mosaics, frontal icons and domed light engineered to make heaven visible on earth.',
    desc: 'Byzantine aesthetics governed Orthodox art from Constantinople\'s founding to the fall of 1453. Gold-ground mosaics — Ravenna, Hagia Sophia, Daphni — suspend frontal, hieratic figures in timeless light; icons in encaustic and egg tempera serve as devotional windows; cloisonne enamel, carved ivories and illuminated psalters carry the style into objects, while domed architecture dissolves walls into light. After the Iconoclast controversy the canon hardened into flat grandeur and reverse perspective, shaping Orthodox worship from Greece to Russia and inspiring nineteenth-century revivals.',
    col: [{ h: '#d4af37', n: 'mosaic gold' }, { h: '#1b2a6b', n: 'lapis ground blue' }, { h: '#66023c', n: 'imperial purple' }, { h: '#1f7a4d', n: 'emerald tessera' }, { h: '#e9e2d0', n: 'marble white' }],
    m: ['glass and gold tesserae', 'egg tempera on wood panels', 'encaustic wax', 'cloisonne enamel on gold'],
    tx: ['shimmering tilted-tessera sparkle', 'sacred flatness of color', 'polished gold halo glow'],
    obj: ['apse mosaics', 'panel icons (Theotokos, Pantocrator)', 'cloisonne reliquaries', 'ivory diptychs', 'illuminated psalters'],
    ex: ['San Vitale mosaics, Ravenna', 'Christ Pantocrator icon, Mount Sinai (6th c.)', 'Vladimir Theotokos icon'],
    inf: ['Late Roman imperial art', 'Hellenistic naturalism', 'Early Christian funerary art'],
    rel: ['Byzantine Revival', 'Neo-Byzantine', 'Islamic geometric patterns', 'Moorish architecture'],
    src: [{ n: 'Wikipedia — Byzantine art', u: 'https://en.wikipedia.org/wiki/Byzantine_art', t: 'B' }, { n: 'The Metropolitan Museum of Art — Byzantine galleries', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['byzantine', 'mosaic', 'icon', 'gold ground', 'orthodox', 'hagia sophia', 'constantinople', 'encaustic'],
    pop: 52, niche: false,
    vd: { shape: 'elongated frontal figures on flat gold fields', line: 'stiff hieratic contour', composition: 'hierarchical symmetry around a central holy figure', texture: 'gold tessera shimmer over matte pigment' },
    typ: { display: 'GFS Didot', body: 'Palatino Linotype', notes: 'Greek uncial flavor via GFS Neohellenic' },
    lit: { quality: 'filtered dome light on gold', temperature: 'warm', shadow: 'suppressed — mystical flatness' },
    ui: { background: 'gold ground', surface: 'mosaic-pattern panels', components: 'gold-halo circular icons', motion: 'candle-flicker shimmer' },
  },
  {
    n: 'Adam Style', a: ['Adamesque', 'Style of Robert Adam'],
    cat: 'Architectural Style', c: 'Robert Adam\'s neoclassical architecture and interiors', e: 'historical',
    o: 'London, Great Britain', g: 'Britain and Ireland, with American Federal adaptations', p: 'c. 1760-1795', era: 'Georgian Britain',
    sum: 'Robert Adam\'s light, elegant neoclassicism: delicate antique ornament, Etruscan-painted rooms and unified design from facade to door handle — late-Georgian refinement.',
    desc: 'The Adam style is the neoclassical manner developed by Robert Adam and his brothers after his studies at Diocletian\'s Palace, Spalatro (1764). Reacting against heavy Palladianism, Adam composed rooms as unified ensembles in which walls, ceilings, carpets and even door fittings share one delicate scheme of flattened antique ornament — medallions, arabesques and scrolling rinceaux — painted in fresh Etruscan reds, pea greens and creams or cast in crisp stucco. Kedleston Hall, Syon House, Osterley Park and Harewood House are landmarks; in America the manner fed the Federal style.',
    col: [{ h: '#c46a4a', n: 'Etruscan red' }, { h: '#9caf88', n: 'pea green' }, { h: '#e8e0cf', n: 'cream stucco' }, { h: '#c8a951', n: 'gilded composition' }, { h: '#5f4b32', n: 'mahogany' }],
    m: ['lime stucco (compo)', 'painted distemper walls', 'mahogany and satinwood', 'gilt-brass mounts'],
    tx: ['crisp flat stucco relief', 'chalky distemper matte', 'fiddleback satinwood grain'],
    obj: ['medallion ceilings', 'Etruscan dressing rooms', 'Adam-style pier glasses', 'secretaire bookcases', 'stucco terrace frontages'],
    ex: ['Kedleston Hall state rooms', 'Syon House ante-room, London', 'Etruscan Dressing Room, Osterley Park'],
    inf: ['Diocletian\'s Palace studies', 'Pompeian and Herculaneum ornament', 'French neoclassicism'],
    rel: ['Georgian Style', 'Georgian interior', 'Neoclassical', 'Palladianism'],
    src: [{ n: 'Wikipedia — Adam style', u: 'https://en.wikipedia.org/wiki/Adam_style', t: 'B' }, { n: 'Victoria & Albert Museum — Robert Adam', u: 'https://www.vam.ac.uk', t: 'A' }],
    tg: ['adamesque', 'neoclassical', 'georgian', 'robert adam', 'stucco', 'etruscan room', 'england'],
    pop: 48, niche: true,
    vd: { shape: 'delicate medallions, sphinxes and rinceau borders', line: 'thin incised outline on flat fields', composition: 'unified room scheme with ceiling-to-carpet motif echoes', texture: 'flat pastel painting with crisp stucco relief' },
    typ: { display: 'Baskerville', body: 'Caslon', notes: 'period English foundry faces of the 1760s-90s' },
    lit: { quality: 'soft even daylight from tall sash windows', temperature: 'cool', shadow: 'light and decorative' },
    ui: { background: 'cream stucco field', surface: 'medallion-framed cards', components: 'gilt medallion buttons', motion: 'graceful scale-up fades' },
  },
  {
    n: 'Regency Style', a: ['English Regency', 'Regency taste'],
    cat: 'Historical Period Style', c: 'British design of the Regency era', e: 'historical',
    o: 'London, Great Britain', g: 'Britain and the Anglophone world', p: 'c. 1795-1830', era: 'British Regency (George IV era)',
    sum: 'Grecian-light British design of George IV\'s era: Nash\'s stucco terraces and Brighton Pavilion exotica, Thomas Hope\'s archaeology, caned and brass-inlaid furniture.',
    desc: 'Regency style names British design around George IV\'s regency and reign. John Nash gave it its public face: white stucco terraces around Regent\'s Park and the exotic domes and minarets of the Royal Pavilion, Brighton. Thomas Hope\'s Household Furniture (1807) set a severe, archaeologically minded Grecian taste — klismos chairs, scroll-end sofas, bronze-mounted rosewood. Interiors favored Pompeian reds and sage greens with brass inlay, caned seats, faux bamboo and japanned papier-mache. Elegant, eclectic and slightly theatrical, Regency taste bridged Georgian classicism and the Victorians.',
    col: [{ h: '#b04a3a', n: 'Pompeian red' }, { h: '#d8d3c5', n: 'white stucco' }, { h: '#3d5c52', n: 'sage green' }, { h: '#bfa046', n: 'brass gilt' }, { h: '#23272b', n: 'black marble' }],
    m: ['white lime stucco', 'brass inlay', 'rosewood and caning', 'japanned papier-mache'],
    tx: ['smooth stucco facing', 'polished brass strip', 'cane webbing weave'],
    obj: ['Grecian scroll-end sofas', 'klismos chairs', 'Brighton Pavilion interiors', 'stucco terrace frontages', 'lacquered tea trays'],
    ex: ['Royal Pavilion, Brighton (Nash, 1815-23)', 'Cumberland Terrace, Regent\'s Park', 'Thomas Hope\'s Duchess Street interiors'],
    inf: ['Pompeian excavations', 'French Empire style', 'Anglo-Indian exotica'],
    rel: ['Hollywood Regency', 'Regency Moderne', 'Georgian Style', 'Empire Style'],
    src: [{ n: 'Wikipedia — Regency architecture', u: 'https://en.wikipedia.org/wiki/Regency_architecture', t: 'B' }, { n: 'Royal Pavilion & Museums, Brighton', u: 'https://brightonmuseums.org.uk', t: 'A' }],
    tg: ['regency', 'john nash', 'brighton pavilion', 'klismos', 'grecian', 'stucco terrace', 'thomas hope'],
    pop: 55, niche: false,
    vd: { shape: 'lean klismos curves and shallow domes', line: 'thin brass inlay line on dark wood', composition: 'paired symmetry with decorative exotica accents', texture: 'smooth stucco and polished rosewood' },
    typ: { display: 'Didot', body: 'Bodoni', notes: 'modern-face types fashionable c. 1800' },
    lit: { quality: 'crisp morning light on pale stucco', temperature: 'cool-neutral', shadow: 'architectural and clean' },
    ui: { background: 'stucco white', surface: 'brass-inlaid panels', components: 'klismos-curved outlines and gilt buttons', motion: 'stately slide transitions' },
  },
  {
    n: 'Fin de Siecle', a: ['fin-de-siecle style', 'end-of-century mood'],
    cat: 'Historical Period Style', c: 'European turn-of-the-century aesthetic mood', e: 'historical',
    o: 'Paris, France (radiating across Europe)', g: 'France, Belgium, Austria, Germany, Britain', p: 'c. 1885-1914', era: 'Belle Epoque Europe',
    sum: 'The decadent, electric mood of Europe\'s turn of the century: poster art, Symbolist shadows, Art Nouveau whiplash lines and glittering expositions from 1885 to 1914.',
    desc: 'Fin de siecle ("end of century") names the aesthetic mood of Europe from the 1880s to 1914 — decadent, sensual and intoxicated by modernity. Paris held its center: Cheret and Toulouse-Lautrec turned boulevards into color-lithograph galleries; Le Chat Noir mingled cabaret and Symbolism; the 1889 and 1900 Expositions Universelles raised the Eiffel Tower and Art Nouveau metro gates. Whiplash ornament, peacock motifs, absinthe greens and dusk violets mixed with urban electricity and decadent literature, feeding Jugendstil, Vienna\'s Secession and early modernism before the war ended the mood.',
    col: [{ h: '#8a9a3b', n: 'absinthe green' }, { h: '#4b2e53', n: 'dusk violet' }, { h: '#141414', n: 'litho black' }, { h: '#6e2b1f', n: 'oxblood' }, { h: '#d9b45b', n: 'exposition gold' }],
    m: ['color lithography stones', 'gilded bronze and wrought iron', 'etched and cameo glass', 'silk and plush'],
    tx: ['flat litho tone with stipple', 'whiplash-line sheen', 'gaslight glow halos'],
    obj: ['boulevard posters', 'Guimard metro entrances', 'peacock-motif glassware', 'cabaret programs', 'exposition pavilions'],
    ex: ['Toulouse-Lautrec Moulin Rouge posters (1891)', 'Guimard Paris Metro entrances (1900)', 'Le Chat Noir shadow theatre programs'],
    inf: ['Symbolist painting', 'Japonisme', 'Arts and Crafts reform'],
    rel: ['Art Nouveau', 'Jugendstil', 'Symbolism', 'Belle Epoque Department Store'],
    src: [{ n: 'Wikipedia — Fin de siècle', u: 'https://en.wikipedia.org/wiki/Fin_de_si%C3%A8cle', t: 'B' }, { n: 'The Metropolitan Museum of Art — posters and prints', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['fin de siecle', 'belle epoque', 'poster', 'decadence', 'paris 1900', 'symbolism', 'whiplash line'],
    pop: 48, niche: true,
    vd: { shape: 'whiplash curves, peacock tails, cabaret silhouettes', line: 'sinuous continuous outline', composition: 'flat decorative panels with cropped figures', texture: 'lithographic stipple over flat tone' },
    typ: { display: 'Bocklin', body: 'Century Old Style', notes: 'Art Nouveau display face (1904); Century (1894) as period text face' },
    lit: { quality: 'gas and early electric glow', temperature: 'warm-dim', shadow: 'pooling cabaret darkness' },
    ui: { background: 'dusk violet gradient', surface: 'poster-framed panels', components: 'whiplash-line buttons and gilt rules', motion: 'slow gaslight flicker' },
  },
  {
    n: 'Weimar Culture', a: ['Weimar-era culture', 'Weimar Republic visual culture'],
    cat: 'Historical Period Style', c: 'Visual culture of Germany\'s Weimar Republic', e: 'historical',
    o: 'Weimar, Dessau and Berlin, Germany', g: 'Germany (influence across Europe and emigration worldwide)', p: '1918-1933', era: 'Weimar Republic',
    sum: 'The electric visual culture of Germany\'s first democracy: Bauhaus geometry, New Objectivity satire, expressionist film shadow and Berlin cabaret, 1918-1933.',
    desc: 'Weimar culture is the visual eruption of Germany\'s republic. The Bauhaus (Weimar 1919, Dessau 1925) fused craft, industry and typography into geometric functionalism; New Objectivity painters Otto Dix and George Grosz sharpened society into acid realism; expressionist cinema (The Cabinet of Dr. Caligari, Metropolis) built tilted worlds of light and shadow. Dada photomontage, jazz-age cabaret, tubular steel furniture and sans-serif type filled Berlin. Nazi suppression scattered its figures worldwide, making Weimar\'s synthesis of art, industry and media foundational to modern design and film.',
    col: [{ h: '#c23b22', n: 'Bauhaus red' }, { h: '#e8b71a', n: 'primary yellow' }, { h: '#2b5fad', n: 'primary blue' }, { h: '#3a3f44', n: 'zinc gray' }, { h: '#141414', n: 'print black' }],
    m: ['tubular steel', 'industrial glass', 'woodcut and litho ink', '35mm film stock'],
    tx: ['hard-edged machine smoothness', 'film-grain contrast', 'flat poster ink'],
    obj: ['Bauhaus Dessau building', 'Wagenfeld table lamp (1924)', 'Brandt ashtrays and teapots', 'Caligari film sets', 'satirical portfolio prints'],
    ex: ['Bauhaus Dessau (Gropius, 1926)', 'The Cabinet of Dr. Caligari (1920)', 'Otto Dix\'s Metropolis triptych (1927-28)'],
    inf: ['German Expressionism', 'Soviet Constructivism', 'De Stijl'],
    rel: ['Bauhaus', 'German Expressionism', 'Expressionist cinema', 'De Stijl', 'Art Deco'],
    src: [{ n: 'Wikipedia — Weimar culture', u: 'https://en.wikipedia.org/wiki/Weimar_culture', t: 'B' }, { n: 'Bauhaus Dessau Foundation', u: 'https://www.bauhaus-dessau.de', t: 'A' }],
    tg: ['weimar', 'bauhaus', 'neue sachlichkeit', 'berlin', 'expressionist film', 'cabaret', 'modernism'],
    pop: 58, niche: false,
    vd: { shape: 'primary-color geometry and tilted film sets', line: 'ruled sans-serif precision', composition: 'asymmetric grid with cinematic diagonals', texture: 'flat ink and industrial glass' },
    typ: { display: 'Futura', body: 'Akzidenz-Grotesk', notes: 'Futura (Paul Renner, 1927) is the era\'s own typeface' },
    lit: { quality: 'hard studio spots and projector beams', temperature: 'cool', shadow: 'expressionist dagger shadows' },
    ui: { background: 'zinc gray', surface: 'primary-color grid panels', components: 'circle-triangle-square toggles', motion: 'snappy mechanical cuts' },
  },
  {
    n: 'Roaring Twenties', a: ['Jazz Age', 'Annees folles'],
    cat: 'Historical Period Style', c: 'The 1920s jazz-age visual culture', e: 'historical',
    o: 'United States (echoing Paris and Berlin)', g: 'United States and Western Europe', p: 'c. 1920-1929', era: 'Interwar boom years',
    sum: 'The Jazz Age image bank: flapper fringe and cloches, Art Deco skyscraper setbacks, speakeasy glitter and radio-age speed — the decade that looked modern.',
    desc: 'The Roaring Twenties fused postwar release, Prohibition speakeasies, jazz and mass media into a distinctive look. Flappers bobbed hair, dropped waists and wore fringed hems; Art Deco towered in setback skyscrapers culminating in the Chrysler Building; Hollywood, radio and jazz records spread the image worldwide. The Harlem Renaissance gave Black modernity its stage in murals, music and nightclubs, while automobiles, ocean liners and movie palaces set the tempo of lacquer, chrome and sequins. The 1929 crash closed the party, but the decade\'s geometry and glamour remain the West\'s picture of modernity arriving.',
    col: [{ h: '#101418', n: 'midnight black' }, { h: '#d8b64a', n: 'champagne gold' }, { h: '#7a2230', n: 'cabaret red' }, { h: '#c9cdd2', n: 'pearl gray' }, { h: '#1f6f5e', n: 'peacock jade' }],
    m: ['lacquered wood and shagreen', 'sequins and bugle beads', 'chrome and colored glass', 'velvet'],
    tx: ['sequin sparkle', 'high piano-gloss lacquer', 'beaded fringe shimmer'],
    obj: ['setback skyscraper crowns', 'flapper dresses and cloche hats', 'jazz record sleeves', 'cocktail coupes and shakers', 'movie palace lobbies'],
    ex: ['Chrysler Building spire (1928-30)', 'Cotton Club Harlem revues', 'The Great Gatsby (Fitzgerald, 1925) imagery'],
    inf: ['Art Deco', 'Harlem Renaissance', 'Parisian haute couture'],
    rel: ['Art Deco', 'Harlem Renaissance', 'Streamline Moderne', 'Belle Epoque Department Store'],
    src: [{ n: 'Wikipedia — Roaring Twenties', u: 'https://en.wikipedia.org/wiki/Roaring_Twenties', t: 'B' }, { n: 'The Metropolitan Museum of Art — Art Deco collections', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['jazz age', 'flapper', 'art deco', 'speakeasy', 'harlem', '1920s', 'skyscraper', 'prohibition'],
    pop: 68, niche: false,
    vd: { shape: 'stepped ziggurats, arcs and sunburst fans', line: 'sleek deco pinstripes', composition: 'symmetrical setbacks framing centered glamour', texture: 'lacquer gloss with metallic sparkle' },
    typ: { display: 'Broadway', body: 'Kabel', notes: 'Broadway (ATF, 1927) is the marquee face of the decade' },
    lit: { quality: 'glittering chandelier and marquee light', temperature: 'warm', shadow: 'smoky club haze' },
    ui: { background: 'midnight black', surface: 'gold-deco framed panels', components: 'sunburst-fan buttons', motion: 'brassy swing-time reveals' },
  },
  {
    n: 'Modern Girl (Moga) Culture', a: ['Moga culture', 'modern girl aesthetics of Japan'],
    cat: 'Historical Period Style', c: 'Taisho-early Showa urban modernity in Japan', e: 'historical',
    o: 'Tokyo (Ginza, Asakusa), Japan', g: 'Urban Japan (Tokyo, Osaka, Kobe)', p: 'c. 1920-1933', era: 'Taisho to early Showa Japan',
    sum: 'The flapper-era "modern girl" of Ginza and Asakusa: bobbed hair, Western dresses, cafe culture and mass magazines — Japan\'s image of being modern between the wars.',
    desc: 'Moga (modan garu, "modern girl") named the bobbed-hair, Western-dressed woman of 1920s Tokyo and Osaka — cafe waitress, jazz fan, magazine reader. Ginza strolls, Asakusa revues and cafe culture supplied the stage; illustrated magazines, Hisui Sugiura posters and Shiseido advertising drew her in deco-tinged graphics fusing Japanese line with Western geometry. Celebrated in the 1927 film and song "Tokyo March" and policed by moralists, the moga and her mobo partner crystallized urban Japanese modernity until Depression and militarism closed the era. Her imagery remains the visual shorthand of Taisho romance.',
    col: [{ h: '#f2e8dc', n: 'silk cream' }, { h: '#c04a55', n: 'rouge red' }, { h: '#2c3e50', n: 'modern navy' }, { h: '#8f7ab5', n: 'lilac accent' }, { h: '#3b3b3b', n: 'bob-cut black' }],
    m: ['color offset and letterpress printing', 'rayon and silk crepe', 'celluloid accessories', 'magazine stock'],
    tx: ['glossy magazine halftone', 'smooth silk drape', 'lacquered celluloid shine'],
    obj: ['illustrated magazine covers', 'Shiseido advertising boards', 'cafe interiors', 'bobbed-hair fashion plates', 'cinema programs'],
    ex: ['Hisui Sugiura posters for Mitsukoshi', 'Shiseido Graph covers (1930s)', 'The 1927 film and song "Tokyo March"'],
    inf: ['Western Art Deco graphics', 'Taisho cafe culture', 'Asakusa revue spectacle'],
    rel: ['Taisho Roman Dress', 'Taishō to Shōwa', 'Art Deco', 'Mingei'],
    src: [{ n: 'Wikipedia — Modern girl', u: 'https://en.wikipedia.org/wiki/Modern_girl', t: 'B' }, { n: 'Tokyo National Museum — Taisho collections', u: 'https://www.tnm.jp', t: 'A' }],
    tg: ['moga', 'modern girl', 'taisho', 'ginza', 'cafe culture', 'japan 1920s', 'bobbed hair'],
    pop: 46, niche: true,
    vd: { shape: 'streamlined silhouettes with bob-line waves', line: 'clean deco contour with Japanese brush lift', composition: 'flat poster fields, cropped figures, bold title blocks', texture: 'halftone dots over flat color' },
    typ: { display: 'Ryumin', body: 'Noto Serif JP', notes: 'vertical tategaki setting with kaisho publisher seals' },
    lit: { quality: 'bright shop-window daylight', temperature: 'warm-neutral', shadow: 'graphic, minimal' },
    ui: { background: 'silk cream', surface: 'halftone-poster cards', components: 'deco-line buttons and vertical tabs', motion: 'quick Ginza-stroll slides' },
  },
  {
    n: 'Dutch Golden Age Painting', a: ['Dutch Golden Age art', '17th-century Dutch school'],
    cat: 'Historical Period Style', c: 'Painting of the independent Dutch Republic', e: 'historical',
    o: 'Dutch Republic (Holland)', g: 'Dutch Republic — Haarlem, Amsterdam, Delft, Utrecht, Leiden', p: 'c. 1588-1672', era: 'Dutch Golden Age',
    sum: 'The most intimate golden age of painting: Rembrandt\'s light, Vermeer\'s quiet rooms, Hals\' swagger and an open market of still lifes, seascapes and bourgeois scenes.',
    desc: 'After winning independence, the Protestant Dutch Republic built the first great open art market — pictures for homes, not altars. Haarlem\'s Frans Hals caught civic-guard swagger; Utrecht Caravaggists imported dramatic light; Rembrandt turned chiaroscuro into psychology; Vermeer fixed Delft interiors in pearly calm; Ruisdael painted vast skies and Heda the banquet still life. Tonal landscapes, church interiors, genre scenes and vanitas moralizing reflected Calvinist sobriety amid commercial wealth. The French invasion of 1672, the rampjaar, closed the era, leaving the benchmark for realism, light and domesticity.',
    col: [{ h: '#8a5a2b', n: 'amber umber' }, { h: '#3d3428', n: 'deep brown ground' }, { h: '#e2c25a', n: 'lead-tin yellow' }, { h: '#2e4a7d', n: 'ultramarine drapery' }, { h: '#dcd8cf', n: 'linen white' }],
    m: ['oil on oak panel and canvas', 'lead white and earth pigments', 'natural ultramarine and smalt', 'resin-varnish glazes'],
    tx: ['glazed shadow depth', 'impasto highlight ridges', 'fine oak panel grain'],
    obj: ['civic guard group portraits', 'domestic genre scenes', 'banquet and vanitas still lifes', 'canal and dune landscapes', 'church interiors'],
    ex: ['Rembrandt, The Night Watch (1642)', 'Vermeer, View of Delft (c. 1660-61)', 'Frans Hals\' Haarlem civic guard canvases'],
    inf: ['Utrecht Caravaggism', 'Flemish Renaissance painting', 'Calvinist domestic culture'],
    rel: ['Delftware', 'Rembrandt light', 'Baroque Français'],
    src: [{ n: 'Wikipedia — Dutch Golden Age painting', u: 'https://en.wikipedia.org/wiki/Dutch_Golden_Age_painting', t: 'B' }, { n: 'Rijksmuseum, Amsterdam', u: 'https://www.rijksmuseum.nl', t: 'A' }],
    tg: ['dutch golden age', 'rembrandt', 'vermeer', 'still life', 'genre painting', 'chiaroscuro', '17th century'],
    pop: 62, niche: false,
    vd: { shape: 'domestic rooms and horizon-low skies', line: 'soft lost-and-found contour', composition: 'window-lit interiors and balanced still-life pyramids', texture: 'layered oil glazes with impasto accents' },
    typ: { display: 'Janson', body: 'Van Dijck', notes: 'old-style faces after 17th-century Amsterdam punchcutters' },
    lit: { quality: 'single north-window shaft', temperature: 'warm-cool mix', shadow: 'deep glazed chiaroscuro' },
    ui: { background: 'aged umber paper', surface: 'framed canvas-texture panels', components: 'picture-frame buttons and gilt-oval badges', motion: 'slow curtain-dim transitions' },
  },
  {
    n: 'Quito School', a: ['Escuela Quiteña', 'Quito School of art'],
    cat: 'Art Movement', c: 'Colonial baroque art school of Quito', e: 'historical',
    o: 'Quito, Royal Audience of Quito (Ecuador)', g: 'Andean colonial South America (Ecuador, southern Colombia, Peru trade)', p: '16th-18th centuries (peak 17th-18th)', era: 'Spanish colonial Andes',
    sum: 'The Quito School: Spanish colonial baroque fused with Andean hands — gilded polychrome sculpture, Caspicara\'s Christs and gold-ground painting in the equatorial Andes.',
    desc: 'The Quito School (Escuela Quiteña) was the leading colonial art school of Spanish South America, centered in Quito. Indigenous and mestizo artists trained in Franciscan and Jesuit workshops translated Spanish baroque models with Andean sensibility: gold grounds and strong local faces in painting, and above all polychrome sculpture — Bernardo de Legarda\'s winged Virgins and Manuel Chili (Caspicara)\'s painstakingly detailed Christs. Churches such as the gilded Compania de Jesus blazed gold leaf over native ornament. The school supplied altars from Colombia to Bolivia and stands beside the Cusco School as the great Andean colonial style.',
    col: [{ h: '#d6a63e', n: 'gold-leaf ground' }, { h: '#7c2231', n: 'cochineal red' }, { h: '#33518f', n: 'colonial ultramarine' }, { h: '#5f8a68', n: 'brocade green' }, { h: '#4a2c1a', n: 'colonial wood brown' }],
    m: ['cedar and quishuar wood', 'gold leaf (pan de oro)', 'polychrome with estofado', 'maguey-fiber plaster'],
    tx: ['estofado reveal of painted pattern', 'burnished gold flicker', 'carved wood flesh-smoothness'],
    obj: ['winged Virgin sculptures', 'processional Christs', 'gold-ground colonial paintings', 'retablos (altar screens)', 'monstrances'],
    ex: ['Legarda\'s Virgen de Quito (Church of San Francisco)', 'Caspicara\'s Cristo de la Paciencia', 'Gilded interior of the Compania de Jesus, Quito'],
    inf: ['Sevillian Baroque sculpture', 'Andean indigenous ornament', 'Cusco School painting'],
    rel: ['Andean Baroque painting', 'Mexican Baroque', 'Ultra-Baroque', 'Churrigueresque', 'Spanish Colonial Architecture'],
    src: [{ n: 'Wikipedia — Quito School', u: 'https://en.wikipedia.org/wiki/Quito_School', t: 'B' }, { n: 'The Metropolitan Museum of Art — colonial Andes collection', u: 'https://www.metmuseum.org', t: 'A' }],
    tg: ['quito school', 'colonial baroque', 'escuela quiteña', 'polychrome', 'andes', 'retablo', 'gold ground'],
    pop: 41, niche: true,
    vd: { shape: 'serpentine baroque draperies and crowned virgins', line: 'deep carving channel-lines under gold', composition: 'vertical retablo tiers framing sculptural saints', texture: 'gilded flicker over matte pigment' },
    typ: { display: 'Cormorant', body: 'EB Garamond', notes: 'colonial imprints used garalde types imported via Spain' },
    lit: { quality: 'candle glow on gilded surfaces', temperature: 'warm', shadow: 'deep retablo recesses' },
    ui: { background: 'cochineal red ground', surface: 'gold-framed retablo panels', components: 'carved-column dividers', motion: 'candlelit slow shimmer' },
  },
]
