/**
 * Retrofuture wave 12 — 12 real retrofuturistic / sci-fi / design styles.
 * All names verified against existing-names.txt (no duplicates); all source URLs curl-verified (HTTP 200).
 */
export const ENTRIES: any[] = [
  {
    n: 'Raygun Gothic', a: ['raygun gothic sci-fi', 'pulp science fiction style'],
    cat: 'Science Fiction & Fantasy', c: 'Retroactive label for mid-century pulp science-fiction aesthetics', e: 'historical',
    o: 'United States (origin), global fandom', g: 'United States, United Kingdom, global science-fiction fandom', p: '1920s-1960s (named 1980s)', era: 'Pulp era to early Space Age',
    sum: 'Retroactive name for the ray-gun-and-rocket-ship look of golden-age pulp science fiction: chrome torpedoes, Bakerlite labs, bikini-metal spacesuits and L-5 bugeyes, named by Michael Moorcock in the 1980s.',
    desc: 'Raygun Gothic describes the visual world of American pulp-era science fiction as it ran from the 1920s Gernsback magazines through the 1950s B-movie: streamlined rocketships with tailfins, cities of cantilevered ramps, rayguns shaped like hairdryers, robots of drum-tight sheet metal and lab equipment of glass retorts and Bakelite. Writer Michael Moorcock coined the phrase in the late 1970s-80s as a companion to "Big Science" imagery, and critic usage fixed it as the label for that aesthetic. Its forms borrow equally from Streamline Moderne industrial design and WWII aviation, projecting them onto the future. The style survives as the default visual shorthand for "retro future" — the thing later punk genres and films like Sky Captain quote.',
    col: [{ h: '#c8cdd4', n: 'cast aluminum silver' }, { h: '#2e3d52', n: 'bugeye steel blue' }, { h: '#c33f2f', n: 'pulp cover red' }, { h: '#d9a441', n: 'raygun brass' }, { h: '#1d232b', n: 'vacuum-tube black' }],
    m: ['polished aluminum and chrome plate', 'Bakelite and early plastics', 'pulp pulpwood paper', 'glass retorts and neon'],
    tx: ['chrome specular streak', 'letterpress pulp halftone', 'machined ribbed housing'],
    obj: ['raygun prop replicas', 'finned rocketship models', 'bubble-domed space helmets', 'pulp magazine covers', 'robot toys'],
    ex: ['Amazing Stories and Planet Stories covers', 'Forbidden Planet (1956) props and C-57D ship', 'Moorcock\'s coining in the 1980s criticism'],
    inf: ['Hugo Gernsback\'s gadget fiction', 'Streamline Moderne industrial design', 'WWII aircraft and rocketry'], rel: ['Googie', 'Space Age design', 'Atomic Age design', 'Steampunk'],
    src: [{ n: 'Wikipedia — Raygun Gothic', u: 'https://en.wikipedia.org/wiki/Raygun_Gothic', t: 'B' }, { n: 'Wikipedia — Googie architecture', u: 'https://en.wikipedia.org/wiki/Googie_architecture', t: 'B' }],
    tg: ['pulp', 'rocketship', 'raygun', 'chrome', 'golden age sci-fi', 'retrofuture'],
    pop: 65, niche: false,
    vd: { shape: 'torpedoes, domes, tailfins — every silhouette streamlined', line: 'swooping speed-lines and riveted contours', composition: 'dynamic diagonals, machine at center under blast', texture: 'glossy enamel metal over flat pulp halftone' },
    typ: { display: 'Futura Bold all-caps with long crossbars', body: 'News Gothic', notes: 'pulp covers pair geometric caps with hand-lettered action titles' },
    lit: { quality: 'hard studio key light with chrome rim highlights', temperature: 'cool with warm neon accents', shadow: 'long theatrical shadows in lab scenes' },
    ui: { background: 'deep space navy with star fields', surface: 'brushed-aluminum control panels', components: 'chrome toggle switches, dial gauges, glass-tube indicators', motion: 'rocket-thrust slide-ins, radar-sweep transitions' },
  },
  {
    n: 'Dieselpunk', a: ['diesel-deco', 'interwar retrofuturism'],
    cat: 'Science Fiction & Fantasy', c: 'Retrofuturist genre style based on interwar diesel-era technology', e: 'community_subculture',
    o: 'Internet-rooted, drawing on US/Europe interwar imagery', g: 'North America, Europe, online fandom and gaming', p: 'coined 2001-present', era: 'imagines 1918-1945 technology extended',
    sum: 'Retrofuturist genre fusing 1920s-40s diesel technology, Art Deco and noir with speculative machinery — the oil-and-iron sibling of steampunk.',
    desc: 'Dieselpunk is a retrofuturist genre that asks what the future would look like if interwar diesel technology never ended: riveted battleships that fly, V8-powered cities, Art Deco skyscraper radios and propaganda posters in deco type. The term emerged online in 2001 (credited to Lewis Pollak\'s tabletop RPG Children of the Sun) and consolidated a fandom around gaming (Crimson Skies, Fallout\'s cousin aesthetics), cosplay and alternate-history art. Its palette runs from chrome-and-black-lacquer deco optimism to oil-stained, war-grim industrialism, usually divided by fans into "decopunk" (sleek) and darker diesel modes. It is now a standard branch of the -punk family tree alongside steampunk and atompunk, with documented conventions, art communities and small-press fiction.',
    col: [{ h: '#23262b', n: 'battleship iron' }, { h: '#8f7a3d', n: 'olive drab' }, { h: '#b8781f', n: 'engine brass' }, { h: '#a52922', n: 'propaganda red' }, { h: '#c9b98a', n: 'aged newsprint' }],
    m: ['riveted steel plate', 'cast iron engines', 'leather and canvas', 'enamel and chrome trim'],
    tx: ['riveted hull seams', 'oil-slick grime', 'lithographic poster flatness'],
    obj: ['dieselpunk airship models', 'deco radio receivers', 'flight-bomber jackets', 'propaganda-style posters', 'custom raygun-meets-mauser props'],
    ex: ['Crimson Skies (1998-) game universe', 'Sky Captain and the World of Tomorrow (2004)', 'The Rocketeer comics and film'],
    inf: ['Art Deco and Streamline Moderne', 'Weimar Neue Sachlichkeit poster art', 'pulp aviation adventure serials'], rel: ['Steampunk', 'Cyberpunk', 'Art Deco', 'Streamline Moderne'],
    src: [{ n: 'Wikipedia — Dieselpunk', u: 'https://en.wikipedia.org/wiki/Dieselpunk', t: 'B' }, { n: 'Wikipedia — Cyberpunk derivatives', u: 'https://en.wikipedia.org/wiki/Cyberpunk_derivatives', t: 'B' }],
    tg: ['diesel', 'art deco', 'dieselpunk', 'interwar', 'alternate history', 'dieselpunk fandom'],
    pop: 60, niche: false,
    vd: { shape: 'massive stepped ziggurats, airship ellipsoids, gear-and-grille geometry', line: 'hard deco outlines with rivet rows', composition: 'monumental low-angle hero shots', texture: 'worn enamel, soot, chrome scratches' },
    typ: { display: 'Peignot or deco inline caps', body: 'Franklin Gothic', notes: 'stenciled crate lettering and propaganda sans are core props' },
    lit: { quality: 'hard directional light, searchlight beams', temperature: 'neutral to cold with sodium-lamp warmth', shadow: 'noir chiaroscuro, venetian-blind slats' },
    ui: { background: 'smoke-black steel gradient', surface: 'riveted gauge panels', components: 'brass toggle switches, ivory dial plates, hazard-stripe buttons', motion: 'heavy mechanical clunk-and-slide transitions' },
  },
  {
    n: 'Atompunk', a: ['atomicpunk', 'Atomic Age retrofuturism'],
    cat: 'Science Fiction & Fantasy', c: 'Retrofuturist genre style based on Atomic Age technology and aesthetics', e: 'community_subculture',
    o: 'Internet-rooted, drawing on US/Soviet Atomic Age imagery', g: 'North America, Europe, online fandom and gaming', p: 'coined 1990s-2000s-present', era: 'imagines 1945-1965 technology extended',
    sum: 'Retrofuturist genre built on the Atomic Age of 1945-1965: atom-symbol logos, tailfin rockets, fallout shelters and starburst optimism, cousin of dieselpunk and steampunk.',
    desc: 'Atompunk is the -punk genre that extends the Atomic Age — roughly 1945 to 1965 — into an alternate future of fission-powered cars, orbiting cities and duck-and-cover civil defense. The term circulated in science-fiction fandom from the 1990s and was codified in listings of cyberpunk derivatives alongside dieselpunk and steampunk. Its imagery draws on Googie diners, the Ford Nucleon concept car, Test Film-era civil-defense graphics, Soviet space-propaganda and early NASA hardware, oscillating between chrome optimism and irradiated dread; the Fallout series is its most visible mass-culture expression. Fan communities sustain it through retro-scifi art, conventions and mods, making it the canonical "atomic utopia-gone-wrong" visual language.',
    col: [{ h: '#2aa198', n: 'starburst turquoise' }, { h: '#d8d5c5', n: 'Formica cream' }, { h: '#c93c2a', n: 'radiation red' }, { h: '#e8b62a', n: 'atom-chart yellow' }, { h: '#2c3440', n: 'fallout charcoal' }],
    m: ['porcelain-enamel steel', 'fiberglass and melamine laminates', 'chrome tube', 'silkscreen poster ink'],
    tx: ['glossy enamel chip', 'starburst laminate grain', 'halftone propaganda dot'],
    obj: ['tailfin concept-car models', 'civil-defense fallout posters', 'atom-symbol diner signage', 'bubble flight helmets', 'Geiger-counter props'],
    ex: ['Fallout game series (1997-)', 'Ford Nucleon concept car (1958)', 'Our Friend the Atom (1956) Disneyatom-era promotion'],
    inf: ['Googie commercial architecture', 'Atomic Age industrial design', 'early NASA and Soviet space graphics'], rel: ['Steampunk', 'Cyberpunk', 'Atomic Age design', 'Space Age design'],
    src: [{ n: 'Wikipedia — Cyberpunk derivatives', u: 'https://en.wikipedia.org/wiki/Cyberpunk_derivatives', t: 'B' }, { n: 'Wikipedia — Atomic Age', u: 'https://en.wikipedia.org/wiki/Atomic_Age', t: 'B' }],
    tg: ['atomic', 'nuclear', 'atompunk', 'starburst', 'fallout', 'cold war'],
    pop: 55, niche: true,
    vd: { shape: 'atom orbitals, boomerangs, starbursts, tailfins', line: 'clean product-illustration contour', composition: 'symmetrical optimism around a glowing core', texture: 'flat enamel color with print grain' },
    typ: { display: 'Handel Gothic (1965) rounded sci-fi caps', body: 'Univers', notes: 'atom-diagram labels and civil-defense stencil caps recur' },
    lit: { quality: 'bright even commercial light, glow accents', temperature: 'warm optimism, cold test-site flashes', shadow: 'minimal, poster-flat' },
    ui: { background: 'cream laminate field', surface: 'turquoise enamel cards with starburst badges', components: 'chrome-ringed push buttons, flip-chart tabs', motion: 'springy bounce-and-glow transitions' },
  },
  {
    n: 'Jet Age', a: ['jet age design', 'tailfin era'],
    cat: 'Historical Period Style', c: 'Postwar aviation-inspired design era of the 1950s-60s', e: 'historical',
    o: 'United States (origin), Western Europe', g: 'United States, Western Europe, Japan', p: '1949-1970', era: 'Postwar Jet Age, Cold War boom',
    sum: 'Design era when commercial jets and fighter aircraft reshaped consumer style: tailfins on cars, swept-wing lamps, flight-attendant futurism and airport optimism from 1949-1970.',
    desc: 'The Jet Age began when the de Havilland Comet (1949) and Boeing 707 (1954-58) made jet flight a mass promise, and industrial designers translated aerodynamics into everything else. American cars sprouted tailfins derived directly from the Lockheed P-38 and later fighter planes, reaching their excess in the 1959 Cadillac; household goods took swept-wing forms, traffic lights and radios echoed cockpit controls, and airport terminals like Eero Saarinen\'s TWA Flight Center (1962) staged flight as theater. Airlines became style brands — Braniff\'s colored planes, stewardess uniforms by Emilio Pucci — while Boeing 747 (1969) democratized long haul and closed the era\'s glamour phase. Jet Age styling is the aviation sibling of Googie and a core source of retrofuture imagery.',
    col: [{ h: '#9db8cc', n: 'altitude sky blue' }, { h: '#d5d8db', n: 'fuselage silver' }, { h: '#c33f2f', n: 'fin-tip red' }, { h: '#e8e3d5', n: 'cabin ivory' }, { h: '#2e3a45', n: 'cockpit slate' }],
    m: ['anodized aluminum', 'molded fiberglass', 'vinyl upholstery', 'polished chrome trim'],
    tx: ['brushed fuselage metal', 'tufted vinyl', 'swept-wing swoop'],
    obj: ['tailfin automobiles', 'winged hood ornaments', 'cockpit-style travel barware', 'flight-bag luggage', 'swivel airport lounges'],
    ex: ['1959 Cadillac Eldorado tailfins', 'Eero Saarinen TWA Flight Center (1962)', 'Boeing 747 launch livery (1969)'],
    inf: ['Commercial jet aviation', 'Streamline Moderne aerodynamics', 'Googie roadside architecture'], rel: ['Googie', 'Space Age design', 'Streamline Moderne', 'Mid-century modern'],
    src: [{ n: 'Wikipedia — Jet Age', u: 'https://en.wikipedia.org/wiki/Jet_Age', t: 'B' }, { n: 'Wikipedia — Googie architecture', u: 'https://en.wikipedia.org/wiki/Googie_architecture', t: 'B' }],
    tg: ['jet', 'tailfin', 'aviation', 'airline', 'postwar', 'chrome'],
    pop: 50, niche: true,
    vd: { shape: 'delta wings, tailfins, bullet noses', line: 'long speed-swoosh curves', composition: 'horizon-level hero vehicle with contrail diagonals', texture: 'polished metal with rivet rhythm' },
    typ: { display: 'Eurostile extended caps', body: 'Akzidenz-Grotesk', notes: 'airline timetable grids and route-map lettering as graphic devices' },
    lit: { quality: 'high-altitude crisp sunlight, glass-wall glow', temperature: 'cool', shadow: 'clean wing shadows on tarmac' },
    ui: { background: 'gradient sky with contrail streaks', surface: 'anodized panel cards', components: 'wing-shaped buttons, altitude-dial sliders', motion: 'takeoff-lift parallax ascents' },
  },
  {
    n: 'Novelty Architecture', a: ['programmatic architecture', 'duck architecture'],
    cat: 'Architectural Style', c: 'Buildings shaped as or adorned with giant everyday objects', e: 'historical',
    o: 'United States (origin), worldwide examples', g: 'United States roadside, Australia, Spain, worldwide', p: '1920s-present (peak 1925-1970)', era: 'Roadside America to postmodern revival',
    sum: 'Buildings shaped like giant ducks, donuts, teapots and baskets — programmatic roadside structures that turned commerce into sculpture along the American highway.',
    desc: 'Novelty architecture — also called programmatic or "duck" architecture after the Long Island Big Duck (1931) that literally coined the term — builds or dresses structures as the products and fantasies they sell: the Brown Derby hat, Teapot Dome gas station (1922), Randy\'s Donuts (1953), the Wigwam Motels, hot-dog stands and, lately, the Longaberger basket building (1997). Rooted in exuberant early-20th-century amusement parks and revived on the postwar highway strip, it overlaps with Googie signage culture and Las Vegas casino symbolism, and was canonized by Robert Venturi\'s Learning from Las Vegas (1972), which championed the decorated shed. Though often dismissed as kitsch, it is a documented American vernacular with preservation groups and a direct ancestor of theme-park and postmodern pop architecture.',
    col: [{ h: '#d98e4a', n: 'donut glaze tan' }, { h: '#f2e3c9', n: 'roadside cream' }, { h: '#e0473a', n: 'neon sign red' }, { h: '#3f7f6e', n: 'teapot jade' }, { h: '#5a4632', n: 'stucco brown' }],
    m: ['stucco and wire lath over frame', 'gunite spray concrete', 'painted sheet metal', 'neon tubing'],
    tx: ['sculpted stucco curve', 'hand-painted signage', 'weathered neon flicker'],
    obj: ['Big Duck-type programmatic buildings', 'donut and hot-dog stand roofs', 'wigwam and teepee motels', 'giant ice-cream and milk-bottle stands'],
    ex: ['Big Duck, Flanders, New York (1931)', 'Randy\'s Donuts, Inglewood (1953)', 'Longaberger Basket building, Newark, Ohio (1997)'],
    inf: ['Roadside amusement-park architecture', 'Googie sign culture', 'Postmodern decorated-shed theory'], rel: ['Googie', 'Tiki architecture', 'Art Deco'],
    src: [{ n: 'Wikipedia — Novelty architecture', u: 'https://en.wikipedia.org/wiki/Novelty_architecture', t: 'B' }, { n: 'Wikipedia — Googie architecture', u: 'https://en.wikipedia.org/wiki/Googie_architecture', t: 'B' }],
    tg: ['roadside', 'programmatic', 'duck', 'neon', 'kitsch', 'vernacular'],
    pop: 42, niche: true,
    vd: { shape: 'the building IS the object — literal oversize forms', line: 'contour of the product itself, no ornament hierarchy', composition: 'lone roadside monument against sky', texture: 'stucco, enamel paint, rusting neon' },
    typ: { display: 'Broadway deco caps on marquee signs', body: 'Cheltenham', notes: 'hand-painted menu boards and roof-mounted channel letters' },
    lit: { quality: 'harsh high-noon roadside sun; neon at dusk', temperature: 'warm', shadow: 'short hard shadows emphasizing bulk' },
    ui: { background: 'asphalt gray with horizon band', surface: 'stucco-curve cards with neon borders', components: 'marquee-lamp buttons, sign-shaped nav tabs', motion: 'chasing-bulb marquee animations' },
  },
  {
    n: 'Megastructure', a: ['megastructuralism', 'urban megastructure'],
    cat: 'Architectural Style', c: '1960s-70s visionary architecture of vast expandable frameworks', e: 'historical',
    o: 'Britain and Japan (main centers)', g: 'United Kingdom, Japan, Italy, United States', p: '1960-1976', era: 'Sixties radical architecture',
    sum: 'Visionary 1960s-70s concept of immense multi-purpose frameworks carrying changeable cells for living and work — Archigram\'s Plug-in City and Banham\'s named "megastructure" ideal.',
    desc: 'Megastructure names the 1960s ambition to build single colossal frameworks — serviced by cranes, filled with prefabricated interchangeable units — that could grow and reorganize like infrastructure. Reyner Banham fixed the term in his 1976 survey "Megastructure: Urban Futures of the Recent Past", reading it from projects such as Archigram\'s Plug-in City (1964), Yona Friedman\'s Ville Spatiale, Metabolism\'s Tokyo Bay schemes and Paolo Soleri\'s arcologies, with Le Corbusier\'s Marseille block as proto-type. Built partial realizations include the Brunswick Centre (1972) and Barbican (1976) in London and Japan\'s Nakagin Capsule Tower (1972). By the late 1970s the oil shock, maintenance failures and postmodern taste had ended the dream, but megastructure logic persists in arcology games, sci-fi cityscapes and capsule-housing research.',
    col: [{ h: '#8d9296', n: 'service tower gray' }, { h: '#c4c8ca', n: 'prefab panel white' }, { h: '#d97b29', n: 'crane safety orange' }, { h: '#3c4a54', n: 'framework steel blue' }, { h: '#6f7d5a', n: 'platform deck green' }],
    m: ['structural steel frames', 'prefabricated concrete modules', 'capsule pods', 'tower cranes'],
    tx: ['modular grid seam', 'board-formed concrete', 'capsule bolt-ring'],
    obj: ['plug-in city drawings', 'capsule tower buildings', 'exposition megaframeworks', 'stacked-housing schemes', 'arcology models'],
    ex: ['Archigram Plug-in City (1964)', 'Nakagin Capsule Tower, Tokyo (1972)', 'Brunswick Centre, London (1972)'],
    inf: ['Metabolism architecture', 'Team 10 urbanism debates', 'Buckminster Fuller\'s geodesic thinking'], rel: ['Metabolism', 'Brutalism', 'Space Age architecture'],
    src: [{ n: 'Wikipedia — Megastructure', u: 'https://en.wikipedia.org/wiki/Megastructure', t: 'B' }, { n: 'Wikipedia — Archigram', u: 'https://en.wikipedia.org/wiki/Archigram', t: 'B' }],
    tg: ['megastructure', 'archigram', 'plug-in', 'capsule', 'infrastructure', 'sixties utopia'],
    pop: 40, niche: true,
    vd: { shape: 'infinite grid frameworks with hangable cells', line: 'truss, gantry and crane-arm lines', composition: 'axonometric infinite extension off-frame', texture: 'exposed structure with stacked unit repetition' },
    typ: { display: 'Microgramma (1952) extended caps', body: 'Univers', notes: 'module numbers and zone codes as compositional elements' },
    lit: { quality: 'overcast even light, floodlight night zones', temperature: 'cool', shadow: 'deep structural shadow grids' },
    ui: { background: 'blueprint gray grid', surface: 'modular panel cards that visibly dock', components: 'socket-in modules, crane-slider controls', motion: 'units snap-and-dock into frames' },
  },
  {
    n: 'Atomic Ranch', a: ['atomic ranch house', 'mid-century ranch style'],
    cat: 'Historical Period Style', c: 'Postwar single-story ranch house style of 1945-1970 American suburbs', e: 'historical',
    o: 'United States', g: 'United States, Canada', p: '1945-1970 (revival 2004-present)', era: 'Postwar suburbia',
    sum: 'The low-slung postwar ranch house with wide eaves, carport, patio glass and atom-age openness — named "atomic ranch" by preservationists and the Atomic Ranch magazine revival.',
    desc: 'The atomic ranch is the tract-built single-story ranch house that absorbed Cliff May\'s California rancho prototypes, Frank Lloyd Wright\'s low horizontals and Case Study openness into 1950s-60s Levittown-scale suburbs. Its signature: long rooflines, wide overhanging eaves, attached carport, sliding glass to a back patio, integrated car culture, exposed brick or stone ends, and interiors with built-ins, bar walls and conversation pits. Postwar prosperity, FHA lending and the automobile made it America\'s dominant house type, and its casual indoor-outdoor modernism became the suburban face of the Atomic Age. The style\'s revival was sealed by Atomic Ranch magazine (founded 2004) and a robust preservation and remodeling community that documents period colors, cabinetwork and landscape.',
    col: [{ h: '#b98d5f', n: 'board-and-batten tan' }, { h: '#7c4a35', n: 'brick end wall' }, { h: '#5c7a6b', n: 'eucalyptus trim green' }, { h: '#e5ddca', n: 'privacy-fence cream' }, { h: '#37413a', n: 'shake roof charcoal' }],
    m: ['redwood and cedar clapboard', 'brick and stone wainscot', 'sliding aluminum glass walls', 'cedar shake roofing'],
    tx: ['horizontal board grain', 'flagstone patio rough', 'aged steel casement'],
    obj: ['ranch house facades with carports', 'patio sliders and bar walls', 'built-in credenzas', 'flagstone terraces', 'carport shade structures'],
    ex: ['Cliff May ranch prototypes, California (1930s-40s)', 'Levittown tract ranches (1947-51)', 'Atomic Ranch magazine restoration features (2004-)'],
    inf: ['Cliff May\'s rancho houses', 'Frank Lloyd Wright\'s Usonian horizontals', 'Case Study House program'], rel: ['Mid-century modern', 'Atomic Age design', 'Googie'],
    src: [{ n: 'Wikipedia — Ranch-style house', u: 'https://en.wikipedia.org/wiki/Ranch-style_house', t: 'B' }, { n: 'Atomic Ranch magazine', u: 'https://atomic-ranch.com', t: 'C' }],
    tg: ['ranch', 'suburb', 'postwar housing', 'mid-century', 'carport', 'patio'],
    pop: 46, niche: true,
    vd: { shape: 'long low rectangles, gable ends, deep eaves', line: 'strong horizontal board lines', composition: 'street-front horizontality, garden-side glass', texture: 'warm wood and stone against lawn flatness' },
    typ: { display: 'Compacta condensed caps on mailboxes and house numbers', body: 'Century Gothic', notes: 'period real-estate ads used perky geometric sans' },
    lit: { quality: 'low golden-hour western sun across the facade', temperature: 'warm', shadow: 'long eave shadows, dappled patio light' },
    ui: { background: 'warm cream plaster', surface: 'wood-slat cards with stone accents', components: 'brick-texture buttons, patio-slider panels', motion: 'sliding-glass door reveals' },
  },
  {
    n: 'Aeropittura', a: ['aeropainting', 'Aero-pittura'],
    cat: 'Technology & Retrofuturism', c: 'Italian Futurist aerial-painting movement of 1929-1940s', e: 'historical',
    o: 'Italy', g: 'Italy (with Argentine and Russian Futurist spillover)', p: '1929-1940s', era: 'Second Futurism, interwar Italy',
    sum: 'Second-era Futurist painting movement (1929) in which artists like Tato, Crali and Dottori painted from and about flight — spiraling aerial views, speed and machine-worship.',
    desc: 'Aeropittura ("aeropainting") was launched in 1929 when Futurist painters signed the "Manifesto of Aeropainting", extending Marinetti\'s movement into the age of aviation after Giacomo Balla and Fortunato Depero\'s 1915 reconstruction manifesto had already modernized its language. Artists including Tato (Guglielmo Sansoni), Tullio Crali (his 1939 "Tricolore Wings" / "Airspiraling" dives), Gerardo Dottori (Umbrian aerial landscapes) and Enrico Prampolini painted from cockpits and imagined flight: vertigo top-down landscapes, spiral dives, propeller vortices and luminous machine-mysticism. It became the dominant Italian avant-garde idiom of the interwar years, comfortably aligned with regime-era aeronautical propaganda yet formally radical — dynamic diagonals, complementary vibration, compressed aerial space. Collections from Rome to Rovereto hold its canonical works, and its spiral-and-speed vocabulary feeds retrofuture visual culture.',
    col: [{ h: '#1c3f8f', n: 'altitude ultramarine' }, { h: '#d9b23f', n: 'propeller gold' }, { h: '#c23b2e', n: 'dive-trail red' }, { h: '#e8e4da', n: 'cloud white' }, { h: '#25342c', n: 'ground-view green' }],
    m: ['oil and tempera on canvas', 'aerosemecca gloss enamels', 'glitter and metallic powder (Prampolini experiments)'],
    tx: ['spun spiral streak', 'high-glaze enamel flow', 'complementary color vibration'],
    obj: ['aerial-dive canvases', 'cockpit-view landscapes', 'propeller vortex studies', 'aero-glyptic stage designs'],
    ex: ['Tullio Crali "Tricolore Ali" (1939) and dive paintings', 'Gerardo Dottori\'s Perugia aerial views', 'Tato\'s "Aerial Spirals" series'],
    inf: ['F.T. Marinetti\'s Futurist manifestos', 'Balla-Depero dynamic reconstruction', 'early aviation spectacle and record flights'], rel: ['Futurist architecture', 'Art Deco', 'Streamline Moderne'],
    src: [{ n: 'Wikipedia — Aeropittura', u: 'https://en.wikipedia.org/wiki/Aeropittura', t: 'B' }, { n: 'Wikipedia — F.T. Marinetti', u: 'https://en.wikipedia.org/wiki/Filippo_Tommaso_Marinetti', t: 'B' }],
    tg: ['futurism', 'aeropainting', 'aviation', 'speed', 'spiral', 'italian avant-garde'],
    pop: 38, niche: true,
    vd: { shape: 'spirals, dive-cones, rotating propeller arcs', line: 'force-lines streaming from a moving viewpoint', composition: 'aerial vertigo — ground flattened below, sky activated', texture: 'smooth enamel glide with flickering complements' },
    typ: { display: 'Bifur (Cassandre, 1929) machine-cut caps', body: 'Bodoni', notes: 'manifesto broadsides mixed stuttering free-word layout with serif text' },
    lit: { quality: 'blinding sun glare with atmospheric haze', temperature: 'warm light over cool depths', shadow: 'dispersed — no grounded cast shadows' },
    ui: { background: 'high-altitude blue gradient', surface: 'spiral-streak panels', components: 'force-line dividers, afterburner glow buttons', motion: 'whip-dive zooms and orbital spins' },
  },
  {
    n: 'Kustom Kulture', a: ['custom car culture', 'kustom kustom art'],
    cat: 'Historical Period Style', c: 'Hot-rod and custom-car art subculture of postwar Southern California', e: 'community_subculture',
    o: 'Southern California, United States', g: 'United States, then worldwide rodding scenes', p: 'late 1950s-present', era: 'Postwar hot-rod era to revival',
    sum: 'Custom-car subculture aesthetic of pinstriping, monster mascots, scallop paint and airbrushed murals — Von Dutch, Ed "Big Daddy" Roth and the "Kustom Kulture" label.',
    desc: 'Kustom Kulture grew from 1950s-60s Southern California hot-rod and custom-car garages: lead-sled Mercs lowered and scallop-painted, lacquer pearl flakes, pinstriping masterwork by Von Dutch, and Ed "Big Daddy" Roth\'s airbrushed cars and monster T-shirt empire crowned by Rat Fink (1963), an anti-Mickey built for the car lot, not the cartoon studio. The name "Kustom Kulture" itself was popularized by Roth\'s circle and fixed by the 1990s revival, including the landmark "Kustom Kulture" exhibition at the Laguna Art Museum (1993) that placed the scene beside lowbrow art. Its graphic language — chrome, flames, panel murals, caricature mascots, hand-lettered shop windows — flowed into tattoo, skateboard and lowbrow art worlds and remains a living international scene with documented shows and archives.',
    col: [{ h: '#c1272d', n: 'candy scallop red' }, { h: '#1b3d8f', n: 'metalflake navy' }, { h: '#f2f2ef', n: 'pearl flake white' }, { h: '#f0a12b', n: 'flame orange' }, { h: '#232323', n: 'primer black' }],
    m: ['automotive lacquer and metalflake', 'one-shot enamel sign paint', 'airbrush dye', 'chrome plating'],
    tx: ['metalflake sparkle', 'hand-painted pinstripe snap', 'airbrush gradient smooth'],
    obj: ['customized lead-sled cars', 'pinstriped gas tanks', 'Rat Fink-style monster shirts', 'shop-window hand lettering', 'show-car trophy panels'],
    ex: ['Von Dutch pinstriping and Flying Eyeball (1950s)', 'Ed "Big Daddy" Roth\'s Rat Fink (1963)', 'Kustom Kulture exhibition, Laguna Art Museum (1993)'],
    inf: ['Hot-rod magazine art (Petersen titles)', 'Billboard and carnival sign painting', '1950s monster-movie merchandising'], rel: ['Googie', 'Mid-century modern', 'Tiki architecture'],
    src: [{ n: 'Wikipedia — Kustom Kulture', u: 'https://en.wikipedia.org/wiki/Kustom_Kulture', t: 'B' }, { n: 'Wikipedia — Googie architecture', u: 'https://en.wikipedia.org/wiki/Googie_architecture', t: 'B' }],
    tg: ['hot rod', 'pinstriping', 'rat fink', 'airbrush', 'lowbrow', 'custom car'],
    pop: 48, niche: true,
    vd: { shape: 'blob mascots, scallop panels, flame licks', line: 'elastic pinstripe contour drawing', composition: 'car as canvas — murals wrap the sheet metal', texture: 'candy lacquer depth with flake glitter' },
    typ: { display: 'Brush Script (1942) swinging caps', body: 'Cooper Black', notes: 'hand-lettered shop fronts and trophy-plaque gothic' },
    lit: { quality: 'show-floor spotlights, lacquer speculars', temperature: 'warm', shadow: 'glossy rolled reflections' },
    ui: { background: 'primer black', surface: 'candy-metalflake gradient cards', components: 'pinstripe-outlined buttons, chrome badges', motion: 'scallop wipe transitions, engine-rev haptics' },
  },
  {
    n: 'Palm Springs Modern', a: ['Desert Modernism', 'Palm Springs school'],
    cat: 'Architectural Style', c: 'Desert-adapted mid-century modernism of Palm Springs, California', e: 'commercial_style',
    o: 'Palm Springs, California, USA', g: 'Coachella Valley, spread to desert resorts worldwide', p: '1946-1972 (revival 1990s-present)', era: 'Postwar resort boom',
    sum: 'Desert Modernism of Palm Springs: steel-and-glass pavilions, breeze-block screens, dramatic rooflines and poolside leisure modernism by Richard Neutra, Albert Frey, Donald Wexler and E. Stewart Williams.',
    desc: 'Palm Springs Modern — often "Desert Modernism" — is the regional school of mid-century modern architecture developed for the Coachella Valley resort boom after WWII. Richard Neutra\'s Kaufmann House (1946) and Albert Frey\'s homes and tramway station fused International Style glass walls with desert strategy: deep roof overhangs, shaded courts, glazing to the San Jacinto mountains. Donald Wexler\'s steel houses (1961-62), Alexander Construction tracts by Palmer & Krisel with decorative breeze blocks, E. Stewart Williams\' airport and Williams/Krisel promontory banks defined a resort modernism of floating roofs, sunshades and pool-centered plans. Declined and later rediscovered, the style\'s preservation movement is institutionalized in Palm Springs\' Modernism Week (founded 2006 as an expanded event), making it the most tourist-visible mid-century enclave in America.',
    col: [{ h: '#e9e2d2', n: 'sun-bleached limestone' }, { h: '#7fb0a5', n: 'pool turquoise' }, { h: '#c9773a', n: 'breeze-block terra' }, { h: '#3f4c52', n: 'shadow slate' }, { h: '#d4b45a', n: 'desert gold' }],
    m: ['steel framing (Wexler system)', 'decorative concrete breeze block', 'floor-to-ceiling glazing', 'flagstone and aggregate paving'],
    tx: ['sun-warmed stone', 'brise-soleil shadow pattern', 'glass-mountain reflection'],
    obj: ['steel and glass pavilion houses', 'breeze-block screen walls', 'cantilevered carports', 'poolside cabanas', 'overhanging butterfly-roof banks'],
    ex: ['Kaufmann House by Richard Neutra (1946)', 'Wexler steel houses (1961-62)', 'Palm Springs airport by E. Stewart Williams (1965)'],
    inf: ['International Style glass pavilions', 'Case Study House program', 'desert resort leisure culture'], rel: ['Mid-century modern', 'Googie', 'Streamline Moderne'],
    src: [{ n: 'Wikipedia — Modernism Week', u: 'https://en.wikipedia.org/wiki/Modernism_Week', t: 'B' }, { n: 'Wikipedia — Googie architecture (regional modern context)', u: 'https://en.wikipedia.org/wiki/Googie_architecture', t: 'B' }],
    tg: ['desert modernism', 'palm springs', 'breeze block', 'mid-century', 'resort', 'glass wall'],
    pop: 58, niche: false,
    vd: { shape: 'flat and butterfly roofs floating over glass', line: 'deep horizontal eaves, slim mullions', composition: 'pavilion in landscape, mountains framed as backdrop', texture: 'smooth stucco, block perforation, water sparkle' },
    typ: { display: 'Neutraface (2002, after Richard Neutra\'s lettering)', body: 'Trade Gothic', notes: '1960s hotel stationery used wide-tracked geometric caps' },
    lit: { quality: 'intense desert sun with controlled shade', temperature: 'warm', shadow: 'graphic block-pattern shadows, blue pool bounce' },
    ui: { background: 'limestone white with heat haze', surface: 'glass-and-block pattern cards', components: 'sunshade-lined buttons, pool-gradient sliders', motion: 'breeze-block parallax reveals' },
  },
  {
    n: 'Tiki Culture', a: ['American tiki', 'Polynesian pop'],
    cat: 'Historical Period Style', c: 'Mid-century American Polynesian-themed bar, restaurant and design culture', e: 'community_subculture',
    o: 'United States (California origins)', g: 'United States, Canada, spread to resort world', p: '1934-1970s (revival 1990s-present)', era: 'Depression-era launch to 1960s peak',
    sum: 'Americana fantasy-Polynesia style launched by Don the Beachcomber (1934) and Trader Vic: carved gods, rattan and bamboo, rum cocktails and torch-light escapism, revived as a collector subculture.',
    desc: 'Tiki culture is America\'s invented Polynesia: a themed environment style begun when Donn Beach opened Don the Beachcomber in Hollywood (1934) and Victor Bergeron built Trader Vic\'s (1936), mixing South Seas imagery, bamboo-and-rattan rooms, tapa cloth, carved marquesan-style gods, torch lighting and strong rum drinks like the Zombie (1934) and Mai Tai (1944). The 1939 Golden Gate Exposition\'s Treasure Island and postwar Hawaii statehood enthusiasm, plus returning GIs and jet-tourism promises, made tiki a national interior-design fashion through the 1950s-60s — McMow glass, mugs shaped as heads, commercial "Polynesian pop" palaces like the Tonga Room and the Mai-Kai (1955). Critic Sven Kirsten\'s 2000 "Book of Tiki" named and archived the style, fueling the revivalist subculture of carvers, mug collectors and bars active today.',
    col: [{ h: '#2e5a4b', n: 'lagoon green' }, { h: '#8a4b2c', n: 'carved koa brown' }, { h: '#d9a441', n: 'torch flame gold' }, { h: '#7a2f28', n: 'rum punch red' }, { h: '#e4d6b8', n: 'tapa cloth tan' }],
    m: ['bamboo and rattan', 'carved wood and ceramic mugs', 'tapa-print upholstery', 'thatch and lava rock'],
    tx: ['carved grain relief', 'woven rattan weft', 'glazed mug gloss'],
    obj: ['tiki mugs and goblets', 'backbar waterfalls and torches', 'rattan lounge seating', 'carved god totems', 'menu covers and matchbooks'],
    ex: ['Don the Beachcomber, Hollywood (1934)', 'The Mai-Kai, Fort Lauderdale (1955)', 'Sven Kirsten\'s "Book of Tiki" (2000)'],
    inf: ['Trader Vic\'s and Donn Beach restaurant empires', 'Hollywood South Seas films', 'Postwar Hawaii tourism'], rel: ['Tiki architecture', 'Googie', 'Mid-century modern'],
    src: [{ n: 'Wikipedia — Tiki culture', u: 'https://en.wikipedia.org/wiki/Tiki_culture', t: 'B' }, { n: 'Wikipedia — Don the Beachcomber', u: 'https://en.wikipedia.org/wiki/Don_the_Beachcomber', t: 'B' }],
    tg: ['tiki', 'polynesian pop', 'rum cocktail', 'bamboo', 'escapism', 'mid-century bar'],
    pop: 57, niche: false,
    vd: { shape: 'stacked totem faces, volcano cones, outrigger curves', line: 'deep carved contour shadows', composition: 'layered foliage frames around a torch-lit altar bar', texture: 'thatch, bark cloth, ceramic glaze' },
    typ: { display: 'Cooper Black with carved-wood substitute forms', body: 'Kabel', notes: 'menus hand-lettered in beachcomber script with dropped-shadow extrusion' },
    lit: { quality: 'warm torch and aquarium-tank glow, low ambient', temperature: 'very warm', shadow: 'deep thatch shadow pockets, colored gel pools' },
    ui: { background: 'dusk lagoon gradient', surface: 'bamboo-frame cards, tapa-pattern fills', components: 'carved-mug buttons, torch-flame loaders', motion: 'lazy-hula sway, bubble risers' },
  },
  {
    n: 'World\'s Fair Futurism', a: ['world of tomorrow style', 'exposition futurism'],
    cat: 'Technology & Retrofuturism', c: 'Exposition-based future-city aesthetic of the 1939 and 1964 New York World\'s Fairs', e: 'historical',
    o: 'New York, USA (primary)', g: 'United States, international expositions', p: '1939-1965', era: 'Depression era to early Space Age',
    sum: 'The "world of tomorrow" look built by world\'s fairs — Trylon and Perisphere geometry, General Motors\' Futurama, monorail promises and corporate tomorrowlands of 1939 and 1964.',
    desc: 'World\'s Fair Futurism is the exposition-borne image of the future crystallized by the 1939 New York World\'s Fair, themed "Building the World of Tomorrow": Harrison and Fouilhoux\'s Trylon-and-Perisphere centerpiece, Norman Bel Geddes\'s General Motors Futurama ride forecasting 1960s motorways, and corporate pavilions staging streamlined cities, television and highways as consumer destiny. The 1964-65 fair reprised the formula in the Space Age — Unisphere globe, Disney\'s It\'s a Small World and GE\'s Progressland — translating atomic-age optimism into walkable spectacle. Design historians treat the fairs as the era\'s decisive popularization of planned-future imagery, linking Depression Modern styling to Space Age pageantry; their artifacts (guidebooks, souvenir graphics, model cities) are the master texts of retrofuture collecting.',
    col: [{ h: '#eef0f2', n: 'perisphere white' }, { h: '#2f6f9f', n: 'expo map blue' }, { h: '#c8c2b2', n: 'model-city beige' }, { h: '#b8352c', n: 'fair poster red' }, { h: '#2b3138', n: 'night fair navy' }],
    m: ['painted steel superstructures', 'plaster model dioramas', 'neon and floodlight arrays', 'printed souvenir ephemera'],
    tx: ['smooth plaster orb', 'moving-model highway gloss', 'floodlit halo glow'],
    obj: ['Trylon and Perisphere souvenirs', 'Futurama ride model highways', 'Unisphere-scale globes', 'monorail and pavilion models', 'guidebook graphics'],
    ex: ['Trylon and Perisphere, 1939 NY World\'s Fair', 'GM Futurama by Norman Bel Geddes (1939)', 'Unisphere, 1964-65 NY World\'s Fair'],
    inf: ['Streamline Moderne industrial design', 'Corporate exhibition design (GM, GE)', 'City-planning utopianism of the WPA era'], rel: ['Streamline Moderne', 'Art Deco', 'Space Age design', 'Googie'],
    src: [{ n: 'Wikipedia — 1939 New York World\'s Fair', u: 'https://en.wikipedia.org/wiki/1939_New_York_World%27s_Fair', t: 'B' }, { n: 'Wikipedia — 1964 New York World\'s Fair', u: 'https://en.wikipedia.org/wiki/1964_New_York_World%27s_Fair', t: 'B' }],
    tg: ['world of tomorrow', 'futurama', 'trylon', 'exposition', 'model city', 'corporate future'],
    pop: 44, niche: true,
    vd: { shape: 'spheres, spires, sweeping ramp spirals', line: 'orbiting ring lines around clean solids', composition: 'aerial model-city panorama with ordered circulation', texture: 'smooth white solids against night floodlight' },
    typ: { display: 'Futura (used at the 1939 fair) geometric caps', body: 'Metro (Dwiggins, 1930)', notes: 'guidebook captions in ruled modernist grids' },
    lit: { quality: 'night floodlighting, searchlight fans, glow halos', temperature: 'cool white with warm promenade accents', shadow: 'soft halo shadows on white geometry' },
    ui: { background: 'dusk navy with floodlit horizon', surface: 'white orb-and-spiral panels', components: 'ring-halo buttons, monorail progress bars', motion: 'slow orbital rotations, ramp-flythrough parallax' },
  },
]
