/**
 * Sci-fi & Fantasy wave 12 — 12 hand-verified genre visual styles.
 * All names are real, documented styles/traditions; sources are stable Wikipedia URLs.
 * Skipped 'Pixel Art Aesthetics' (overlap: 'Pixel Art Outlines'); slot 9 renamed.
 */
export const ENTRIES: any[] = [
  {
    n: 'Mecha Anime Aesthetics', a: ['Mecha design', 'Robot anime style', 'メカ'],
    cat: 'Science Fiction & Fantasy', c: 'Japanese giant-robot anime design tradition', e: 'commercial_style',
    o: 'Japan', g: 'Japan; global anime and hobby markets', p: '1972-present', era: 'Postwar anime era to global franchise culture',
    sum: 'Japanese giant-robot design tradition: layered armor, dense panel lines, hazard decals and transformation gimmicks, from super-robot manga to Gundam\'s real-robot school and Gunpla kit culture.',
    desc: 'Mecha design matured from Go Nagai\'s super-robot manga into Gundam\'s "real robot" school, where Kunio Okawara grounded giant robots in plausible military hardware. Layered armor plates, dense panel lines, hazard decals, transforming frames and cockpit launch sequences define the look, drawn in cel animation with hard shadow planes and spark highlights; Gunpla model-kit culture carried the aesthetic into worldwide hobby engineering and box-art design.',
    col: [{ h: '#f2f4f7', n: 'panel white' }, { h: '#d0342c', n: 'hero red' }, { h: '#2f6fb2', n: 'armor blue' }, { h: '#5a6472', n: 'gunmetal' }, { h: '#e8b830', n: 'caution yellow' }],
    m: ['cel animation paints', 'design markers and gouache concept art', 'injection-molded model kit plastics', 'dry-transfer decals'],
    tx: ['hard panel lines', 'mechanical decal marks', 'cel-shine sparkle highlights'],
    obj: ['giant robot hero units', 'cockpit hatch close-ups', 'launch catapult sequences', 'transformation gimmick frames', 'Gunpla box art'],
    ex: ['Mazinger Z (1972) super-robot origin', 'Mobile Suit Gundam (1979) real-robot school', 'Gunpla kit box-art line art'],
    inf: ['Super-robot manga (Go Nagai)', 'Real-robot design (Kunio Okawara)', 'Aircraft and military model kit culture', 'Star Wars miniature effects'],
    rel: ['Cassette Futurism', 'Tokusatsu Visual Culture', 'Raygun Gothic'],
    src: [{ n: 'Wikipedia — Mecha', u: 'https://en.wikipedia.org/wiki/Mecha', t: 'B' }, { n: 'Wikipedia — Mobile Suit Gundam', u: 'https://en.wikipedia.org/wiki/Mobile_Suit_Gundam', t: 'B' }, { n: 'Wikipedia — Gunpla', u: 'https://en.wikipedia.org/wiki/Gunpla', t: 'B' }],
    tg: ['giant robot', 'panel line', 'gundam', 'real robot', 'super robot', 'cel anime', 'katakana decals', 'gunpla'],
    pop: 62, niche: false,
    vd: { shape: 'blocky articulated silhouettes with layered armor', line: 'crisp inked contours with dense panel-line hatching', composition: 'low-angle hero shots, launch and transformation staging', texture: 'cel-shaded flat color with white sparkle shines' },
    typ: { display: 'Eurostile Extended', body: 'Morisawa Shin Go', notes: 'stenciled hull numbers, hazard stripes and katakana caution decals' },
    lit: { quality: 'hard key light with rim glow', temperature: 'cool', shadow: 'graphic cel-shadow planes' },
    ui: { background: 'hangar-gray gradient', surface: 'panel-line divided cards', components: 'angular chamfered buttons', motion: 'servo-snappy step transforms' },
  },
  {
    n: 'Tokusatsu Visual Culture', a: ['Tokusatsu', '特撮', 'suitmation'],
    cat: 'Science Fiction & Fantasy', c: 'Japanese practical-effects special filming tradition', e: 'commercial_style',
    o: 'Japan', g: 'Japan; global cult fandom', p: '1954-present', era: 'Postwar Japanese cinema to television franchise era',
    sum: 'Japan\'s practical-effects film tradition — rubber-suit heroes and monsters, miniature cities, matte paintings and optical compositing — codified by Godzilla, Ultraman and Kamen Rider.',
    desc: 'Tokusatsu ("special filming") names Japan\'s practical-effects tradition built by Eiji Tsuburaya: actors in rubber suits performing inside miniature cities, matte paintings, wire-work and squib explosions composited optically. From Godzilla (1954) through Ultraman (1966) and Kamen Rider (1971), fixed staging codes emerged — transformation poses, color-coded hero teams, weekly monster battles and reusable destruction footage — a template still powering superhero, monster and mecha franchises worldwide.',
    col: [{ h: '#c8352b', n: 'suit red' }, { h: '#2b6fc0', n: 'suit blue' }, { h: '#c0c6cc', n: 'suit silver' }, { h: '#e07b28', n: 'explosion orange' }, { h: '#1a1c20', n: 'stage black' }],
    m: ['latex and urethane monster suits', 'miniature city sets', 'squib pyrotechnics', 'optical compositor film passes'],
    tx: ['rubber suit sheen', 'miniature set grain', 'optical-printer halation'],
    obj: ['kaiju and hero suits', 'miniature cityscapes', 'henshin transformation poses', 'color-coded team helmets', 'stock-footage explosion shots'],
    ex: ['Godzilla (1954) Tsuburaya effects', 'Ultraman (1966) henshin-hero format', 'Kamen Rider (1971) masked-hero franchise'],
    inf: ['King Kong (1933) stop-motion lineage', 'American superhero serials', 'Kabuki-derived heroic posing', 'Postwar Japanese B cinema'],
    rel: ['Kaiju Film Aesthetics', 'Mecha Anime Aesthetics', 'Raygun Gothic'],
    src: [{ n: 'Wikipedia — Tokusatsu', u: 'https://en.wikipedia.org/wiki/Tokusatsu', t: 'B' }, { n: 'Wikipedia — Ultraman', u: 'https://en.wikipedia.org/wiki/Ultraman', t: 'B' }, { n: 'Wikipedia — Godzilla', u: 'https://en.wikipedia.org/wiki/Godzilla', t: 'B' }],
    tg: ['suitmation', 'tokusatsu', 'henshin', 'miniature effects', 'ultraman', 'kamen rider', 'rubber suit'],
    pop: 55, niche: true,
    vd: { shape: 'heroic human silhouettes against oversized suits and minis', line: 'bold poster contours', composition: 'matte-painted horizons, low hero angles, explosion-centered frames', texture: '35mm film grain with optical dissolve halos' },
    typ: { display: 'ITC Machine Bold', body: 'Hiragino Kaku Gothic', notes: 'chrome-beveled title logos and episode countdown supers' },
    lit: { quality: 'hard stage spots with colored gels', temperature: 'mixed warm blast / cool night', shadow: 'crisp suit-actor shadows on miniature streets' },
    ui: { background: 'black stage void', surface: 'chromed bevel panels', components: 'round henshin-glow buttons', motion: 'flash-frame transformation cuts' },
  },
  {
    n: 'Kaiju Film Aesthetics', a: ['Kaiju eiga', '怪獣映画', 'giant monster movie style'],
    cat: 'Science Fiction & Fantasy', c: 'Japanese giant-monster cinema visual grammar', e: 'commercial_style',
    o: 'Japan', g: 'Japan; worldwide genre cinema', p: '1954-present', era: 'Cold-war Japan to global franchise era',
    sum: 'Giant-monster cinema grammar born with Godzilla (1954): suited titans towering over miniature downtowns, searchlight grids, burning skylines and lurid theatrical poster spectacle.',
    desc: 'Kaiju eiga — giant monster cinema — began with Ishirō Honda and Eiji Tsuburaya\'s Godzilla (1954), staging national trauma as city-scale destruction. Its grammar: suited monsters towering over miniature downtowns, searchlight grids, burning skylines, military lines failing in waves, and poster art promising spectacle. Cold-war nuclear anxiety shaped the first cycle; revivals from Rodan (1956) to Shin Godzilla (2016) kept the miniature-and-suit poetry alive alongside CGI spectacle.',
    col: [{ h: '#3a4148', n: 'lithographic night gray' }, { h: '#e0651f', n: 'fire orange' }, { h: '#7c8794', n: 'smoke ash' }, { h: '#26424f', n: 'deep sea teal' }, { h: '#d9c9a3', n: 'searchlight cream' }],
    m: ['foam and latex kaiju suits', 'miniature building kits', 'matte paintings and rear projection', 'practical smoke and fire'],
    tx: ['scorched miniature charring', 'suit-scar monster texture', 'layered smoke haze'],
    obj: ['city-scale monster rampages', 'failing military lines', 'burning skyline silhouettes', 'evacuation warning posters', 'theatrical poster billboards'],
    ex: ['Godzilla (1954), Ishirō Honda', 'Rodan (1956)', 'Shin Godzilla (2016)'],
    inf: ['The Beast from 20,000 Fathoms (1953)', 'Hiroshima and firebombing memory', 'Nuclear test anxieties', 'Postwar poster lithography'],
    rel: ['Tokusatsu Visual Culture', 'Atomic Age design', 'Raygun Gothic'],
    src: [{ n: 'Wikipedia — Kaiju', u: 'https://en.wikipedia.org/wiki/Kaiju', t: 'B' }, { n: 'Wikipedia — Godzilla', u: 'https://en.wikipedia.org/wiki/Godzilla', t: 'B' }, { n: 'Wikipedia — Shin Godzilla', u: 'https://en.wikipedia.org/wiki/Shin_Godzilla', t: 'B' }],
    tg: ['kaiju', 'godzilla', 'monster movie', 'miniature', 'tokusatsu', 'atomic anxiety', 'poster art'],
    pop: 58, niche: false,
    vd: { shape: 'towering organic monster masses against grid city blocks', line: 'chunky poster silhouettes', composition: 'worm\'s-eye street views and wide destruction tableaus', texture: 'printed-poster flatness over film grain' },
    typ: { display: 'Franklin Gothic Condensed', body: 'Trade Gothic', notes: 'hand-painted Toho poster titles and stencil warning type' },
    lit: { quality: 'searchlight beams and fire glow', temperature: 'warm fire against cool night', shadow: 'long miniature shadows' },
    ui: { background: 'charred asphalt charcoal', surface: 'warning-poster cards', components: 'siren-amber alert buttons', motion: 'tremor shakes and smoke drift' },
  },
  {
    n: 'Sword & Sorcery Cover Art', a: ['S&S cover painting', 'sword-and-sorcery illustration'],
    cat: 'Science Fiction & Fantasy', c: 'Heroic fantasy paperback cover illustration', e: 'commercial_style',
    o: 'United States', g: 'US publishing; international genre art', p: '1930s-1980s (canonical era)', era: 'Pulp era to 1970s paperback boom',
    sum: 'Pulp-rooted heroic fantasy cover painting — Frazetta\'s barbarians, sorceresses and serpents under torchlight — that visually defined Conan-era fantasy paperbacks.',
    desc: 'Sword & sorcery cover painting codified the pulp tradition of Robert E. Howard\'s Conan for the 1960s-70s paperback boom. Frank Frazetta\'s oils — hulking barbarians, svelte sorceresses, serpents and ruined thrones under torchlight — set the genre template, followed by Boris Vallejo, Ken Kelly and the Lancer/Ace Conan editions. Diagonal hero compositions, chiaroscuro torchlight and gilded logo lettering made these covers the visual definition of heroic fantasy for two generations of readers.',
    col: [{ h: '#c96f2d', n: 'torchlit orange' }, { h: '#6d4a2f', n: 'leather brown' }, { h: '#3e4a2e', n: 'swamp green' }, { h: '#d8c8b0', n: 'parchment flesh' }, { h: '#26221f', n: 'cavern black' }],
    m: ['oil and acrylic on board', 'gouache', 'frisket masking', '1970s airbrush'],
    tx: ['licked oil blending', 'linen board tooth', 'varnished cover gloss'],
    obj: ['muscular barbarian heroes', 'sorceress and serpent motifs', 'ruined temples and thrones', 'damsel-and-dagger drama poses', 'jeweled greatswords'],
    ex: ['Frank Frazetta Conan covers (Lancer, 1966-70s)', 'Boris Vallejo and Ken Kelly Ace Conan covers', 'Weird Tales-era interior pulp art'],
    inf: ['Weird Tales pulp tradition', 'Howard Pyle illustration school', 'Maxfield Parrish mural painting', 'Bodybuilding physique culture'],
    rel: ['Pulp illustration', 'High Fantasy Illustration', 'Dark Fantasy Art'],
    src: [{ n: 'Wikipedia — Sword and sorcery', u: 'https://en.wikipedia.org/wiki/Sword_and_sorcery', t: 'B' }, { n: 'Wikipedia — Frank Frazetta', u: 'https://en.wikipedia.org/wiki/Frank_Frazetta', t: 'B' }, { n: 'Wikipedia — Weird Tales', u: 'https://en.wikipedia.org/wiki/Weird_Tales', t: 'B' }],
    tg: ['conan', 'frazetta', 'paperback', 'pulp fantasy', 'barbarian', 'cover art', 'torchlight'],
    pop: 56, niche: true,
    vd: { shape: 'diagonal figure triangles with exaggerated musculature', line: 'painterly contour with dramatic rim light', composition: 'single hero-centered tableau, monster encroaching from edges', texture: 'smooth oil gradients with hard-edge vignettes' },
    typ: { display: 'Albertus', body: 'Garamond', notes: 'gold-stamped title lettering on paperback spines' },
    lit: { quality: 'torchlight chiaroscuro', temperature: 'warm', shadow: 'deep pool blacks with colored bounce' },
    ui: { background: 'parchment smoke gradient', surface: 'gilded frame panels', components: 'sword-hilt dividers, rune-embossed buttons', motion: 'torch-flicker pulsing' },
  },
  {
    n: 'High Fantasy Illustration', a: ['Epic fantasy art', 'Tolkien illustration tradition'],
    cat: 'Science Fiction & Fantasy', c: 'Epic secondary-world fantasy illustration', e: 'commercial_style',
    o: 'United Kingdom and United States', g: 'Anglophone publishing; global genre art', p: '1954-present', era: 'Post-Tolkien publishing era',
    sum: 'Painterly medievalism of post-Tolkien epic publishing: questing companies in misty valleys and ruined towers, anchored by folded maps and golden-age illustration roots.',
    desc: 'Post-Tolkien epic fantasy publishing generated a coherent illustration tradition: small companies of questers dwarfed by misty valleys, ruined towers and ancient forests, with folded maps as essential paratext. Alan Lee and John Howe\'s watercolor-and-pencil Tolkien work, the Hildebrandt brothers\' 1970s calendars and Barbara Remington\'s Ballantine covers established a painterly medievalism drawing on Arthur Rackham, the Pre-Raphaelites and Arts & Crafts — the canonical look of high fantasy before digital painting.',
    col: [{ h: '#4a6741', n: 'elven green' }, { h: '#8f9aa8', n: 'mist gray-blue' }, { h: '#c9b47c', n: 'antique gold' }, { h: '#5d3f3a', n: 'quest-worn brown' }, { h: '#e8e4d8', n: 'vellum white' }],
    m: ['watercolor and gouache', 'oil glazing', 'pencil underdrawing', 'digital painting (contemporary)'],
    tx: ['atmospheric glaze veil', 'leaf-and-bark stipple', 'map-linework engraving'],
    obj: ['fellowship ensemble shots', 'ruined towers and hidden valleys', 'dragon confrontations', 'folded endpaper maps', 'rune-inscribed artifacts'],
    ex: ['Alan Lee and John Howe Tolkien illustrated editions', 'Brothers Hildebrandt 1970s Tolkien calendars', 'Barbara Remington Ballantine Tolkien covers'],
    inf: ['Arthur Rackham golden-age illustration', 'Pre-Raphaelite painting', 'Arts & Crafts medievalism', 'Norse saga and epic poetry'],
    rel: ['Pre-Raphaelites', 'Sword & Sorcery Cover Art', 'Dark Fantasy Art'],
    src: [{ n: 'Wikipedia — High fantasy', u: 'https://en.wikipedia.org/wiki/High_fantasy', t: 'B' }, { n: 'Wikipedia — Alan Lee (illustrator)', u: 'https://en.wikipedia.org/wiki/Alan_Lee_(illustrator)', t: 'B' }, { n: 'Wikipedia — Brothers Hildebrandt', u: 'https://en.wikipedia.org/wiki/Brothers_Hildebrandt', t: 'B' }],
    tg: ['tolkien', 'epic fantasy', 'quest', 'endpaper map', 'pre-raphaelite', 'illustration', 'medievalism'],
    pop: 60, niche: false,
    vd: { shape: 'rolling organic landscapes framing small figures', line: 'fine narrative contour drawing', composition: 'deep-stage vistas with architecture anchoring horizons', texture: 'watercolor wash grain over drawn detail' },
    typ: { display: 'Trajan Pro', body: 'Bembo', notes: 'runic display capitals and cartographic italics on maps' },
    lit: { quality: 'golden-hour diffuse', temperature: 'warm with cool mist', shadow: 'soft aerial-perspective haze' },
    ui: { background: 'vellum cream', surface: 'illuminated-border cards', components: 'laurel-arched buttons, compass markers', motion: 'slow mist reveals' },
  },
  {
    n: 'Dark Fantasy Art', a: ['Grimdark illustration', 'dark art community style'],
    cat: 'Science Fiction & Fantasy', c: 'Horror-inflected fantasy art current', e: 'community_subculture',
    o: 'US and European publishing; online art platforms', g: 'Global (DeviantArt, ArtStation, genre publishing)', p: '1980s-present', era: '1980s tabletop boom to online art-platform era',
    sum: 'Horror-fused fantasy imagery — undead knights, plague cathedrals, ritual sigils — carried from Warhammer-era art into a global online dark-art community.',
    desc: 'Dark fantasy art fuses horror and fantasy: undead knights, plague cathedrals, ritual sigils and demonic portraiture rendered in low-key, decaying palettes. Fed by 1980s Warhammer and D&D art, Beksiński\'s dark surrealism and grimdark fiction, it flourished as an online community style on DeviantArt and ArtStation, with artists like Wayne Barlowe, Brom and Adrian Smith defining its monumental corrupted-gothic imagery across games, album covers and trading-card art.',
    col: [{ h: '#241f26', n: 'bruise black' }, { h: '#5e2a33', n: 'blood maroon' }, { h: '#4c5b52', n: 'grave green' }, { h: '#b7a98e', n: 'bone parchment' }, { h: '#6f7c8a', n: 'corpse-pale blue' }],
    m: ['oil and acrylic', 'digital painting tablets', 'mixed-media texture plates', 'ink wash'],
    tx: ['decayed-armor rust', 'smoke-choked atmosphere', 'wet stone sheen'],
    obj: ['armored undead knights', 'cathedral ruins', 'ritual sigils and skulls', 'plague and coffin motifs', 'demon-portrait busts'],
    ex: ['Wayne Barlowe\'s Inferno paintings (1998)', 'Brom\'s Dark Sun and cover art', 'Adrian Smith\'s Warhammer Fantasy illustrations'],
    inf: ['Beksiński and Giger dark surrealism', 'Northern Renaissance death imagery', '1980s D&D and Warhammer art', 'Gothic literature'],
    rel: ['High Fantasy Illustration', 'Sword & Sorcery Cover Art'],
    src: [{ n: 'Wikipedia — Dark fantasy', u: 'https://en.wikipedia.org/wiki/Dark_fantasy', t: 'B' }, { n: 'Wikipedia — Grimdark', u: 'https://en.wikipedia.org/wiki/Grimdark', t: 'B' }, { n: 'Wikipedia — Zdzisław Beksiński', u: 'https://en.wikipedia.org/wiki/Zdzis%C5%82aw_Beksi%C5%84ski', t: 'B' }],
    tg: ['grimdark', 'horror fantasy', 'warhammer', 'undead', 'gothic', 'dark art', 'sigils'],
    pop: 57, niche: true,
    vd: { shape: 'hunched monumental figures and spiky silhouettes', line: 'scratchy broken contour', composition: 'claustrophobic frames with low-key vignetting', texture: 'mottled decay under chiaroscuro glazing' },
    typ: { display: 'Fette Fraktur', body: 'Baskerville', notes: 'distressed and scratched title plates' },
    lit: { quality: 'single-source candle or moonlight', temperature: 'cold with ember accents', shadow: 'devouring low-key blacks' },
    ui: { background: 'charcoal soot field', surface: 'cracked stone-slab cards', components: 'iron-filigree buttons', motion: 'candle-gutter flicker' },
  },
  {
    n: 'Space Opera Visual Traditions', a: ['Galactic adventure design', 'space opera production design'],
    cat: 'Science Fiction & Fantasy', c: 'Interstellar adventure design language', e: 'commercial_style',
    o: 'United States', g: 'Anglophone media; global franchises', p: '1928-present', era: 'Pulp era to modern franchise design',
    sum: 'Large-scale interstellar adventure design, from Doc Smith pulps and Flash Gordon to Star Wars\' used-future fleets, greebled hulls and dynastic court costume.',
    desc: 'Space opera\'s visual traditions run from E.E. "Doc" Smith\'s pulp serials and Flash Gordon cliffhanger serials to Star Wars\' used-future production design and Dune\'s dynastic ornament. The grammar: colossal starships dwarfing human figures, bridge viewscreens, greebled hull surfaces, planetary matte paintings, star charts and courtly costumes, all scored to mythic melodrama. Franchise concept departments standardized the idiom into a global design language of galactic conflict.',
    col: [{ h: '#101828', n: 'void navy' }, { h: '#d8dde3', n: 'hull white' }, { h: '#c23b2e', n: 'signal red' }, { h: '#3f7fbf', n: 'thrust blue' }, { h: '#e3c26b', n: 'star gold' }],
    m: ['matte paintings', 'motion-control miniatures', 'blue-screen compositing', 'concept design painting'],
    tx: ['hull panel weathering', 'starfield depth layering', 'optical lens-flare streaks'],
    obj: ['capital starship fleets', 'bridge viewscreens', 'planetary establishing mattes', 'alien court costumes', 'holographic star charts'],
    ex: ['Flash Gordon serials (1936)', 'Star Wars (1977) production design', 'Dune novel and film dynasty designs'],
    inf: ['Pulp magazine cover tradition', 'Flash Gordon serials', 'WWII naval and aerial combat film', 'Mythic epic melodrama'],
    rel: ['Raygun Gothic', 'Cassette Futurism', 'NASA Graphics Standards Era', 'Dime Novel & Pulp Cover Art'],
    src: [{ n: 'Wikipedia — Space opera', u: 'https://en.wikipedia.org/wiki/Space_opera', t: 'B' }, { n: 'Wikipedia — Star Wars', u: 'https://en.wikipedia.org/wiki/Star_Wars', t: 'B' }, { n: 'Wikipedia — Flash Gordon', u: 'https://en.wikipedia.org/wiki/Flash_Gordon', t: 'B' }],
    tg: ['space opera', 'starship', 'galactic empire', 'pulp', 'franchise', 'starfield', 'used future'],
    pop: 66, niche: false,
    vd: { shape: 'vast vertical ships and sweeping fleet formations', line: 'long cinematic perspective sweeps', composition: 'dwarfed human figures against colossal architecture', texture: 'greebled surface detail under atmospheric haze' },
    typ: { display: 'Microgramma', body: 'Univers', notes: 'custom franchise logotypes over star-field titles' },
    lit: { quality: 'hard single-sun keylight with fill bounce', temperature: 'cool space, warm interiors', shadow: 'deep two-tone contrast' },
    ui: { background: 'starfield void', surface: 'translucent console glass', components: 'backlit toggles and viewport frames', motion: 'hyperspace streak wipes' },
  },
  {
    n: 'NASA Graphics Standards Era', a: ['NASA worm logo era', '1976 NASA identity system', 'worm logotype design'],
    cat: 'Technology & Retrofuturism', c: '1976 NASA corporate identity system', e: 'commercial_style',
    o: 'United States', g: 'US federal space program; global design influence', p: '1976-1992 (official); revived 2020', era: '1970s American federal design modernism',
    sum: 'Danne & Blackburn\'s 1976 NASA identity: the continuous red "worm" logotype with a Helvetica grid system deployed on launch towers, orbiters, reports and press photography.',
    desc: 'In 1972-76, Danne & Blackburn\'s NASA Graphics Standards Manual replaced the official seal with the "worm" — a continuous red logotype — and a Helvetica-based system of grids, signage and vehicle decals. Deployed across launch towers, orbiters, technical reports and press photography, it embodied American federal modernism until the insignia\'s 1992 return; NASA revived the worm as a secondary identity in 2020, cementing its retrofuturist cult status among designers.',
    col: [{ h: '#ffffff', n: 'worm white' }, { h: '#0b3d91', n: 'NASA blue' }, { h: '#c2c7cc', n: 'vehicle gray' }, { h: '#e4002b', n: 'worm red' }, { h: '#101418', n: 'space black' }],
    m: ['printed standards manuals', 'silkscreen signage', 'vehicle vinyl decals', 'press-kit photography'],
    tx: ['flat ink on coated stock', 'clean vinyl sheen', 'grainy 1970s NASA photography'],
    obj: ['worm logotype signage', 'orbiter and launch-tower decals', 'standards manual spreads', 'technical report covers', 'mission control console graphics'],
    ex: ['NASA Graphics Standards Manual (Danne & Blackburn, 1976)', 'worm decals on Space Shuttle orbiters and towers', '2020 worm revival for crewed flight branding'],
    inf: ['Swiss International Typographic Style', '1970s Federal Design Improvement Program', 'Corporate identity practice (Lippincott & Margulies)', 'Modernist grid systems'],
    rel: ['Cassette Futurism', 'Atomic Age design', 'Space Opera Visual Traditions', 'Raygun Gothic'],
    src: [{ n: 'Wikipedia — NASA insignia', u: 'https://en.wikipedia.org/wiki/NASA_insignia', t: 'B' }, { n: 'Wikipedia — NASA', u: 'https://en.wikipedia.org/wiki/NASA', t: 'B' }, { n: 'Wikipedia — Space Shuttle', u: 'https://en.wikipedia.org/wiki/Space_Shuttle', t: 'B' }],
    tg: ['worm logo', 'nasa', 'identity system', 'helvetica', 'federal design', '1970s', 'grids', 'retrofuturism'],
    pop: 54, niche: true,
    vd: { shape: 'continuous rounded worm strokes and modular grids', line: 'uniform-weight Helvetica-era geometry', composition: 'generous white margins, left-aligned hierarchies', texture: 'flat ink with photographic grain accents' },
    typ: { display: 'custom worm logotype (Danne & Blackburn)', body: 'Helvetica', notes: 'all-caps technical captions and thin-rule data blocks' },
    lit: { quality: 'harsh Florida sunlight, engineering clarity', temperature: 'neutral-warm', shadow: 'clean functional photographic shadows' },
    ui: { background: 'paper white', surface: 'thin-rule grid panels', components: 'blue all-caps labels and underlined links', motion: 'plain crossfade slides' },
  },
  {
    n: 'Sprite & Tile Game Art', a: ['sprite art', 'sprite-based game graphics', 'tile-based game art'],
    cat: 'Game & Pixel Aesthetic', c: 'Tile-and-sprite console game graphics tradition', e: 'community_subculture',
    o: 'Japan and North America', g: 'Global game industry and pixel-art hobbyist scene', p: 'mid-1970s-present (canonical 1983-1995)', era: '8/16-bit console era to indie revival',
    sum: 'The craft of drawing characters and worlds from fixed hardware palettes into pixel grids — cluster shading, selective dithering and strict animation budgets of the console era.',
    desc: 'Sprite art is the craft of drawing characters and tiles from fixed hardware palettes into pixel grids. Born of arcade and console constraints (NES, Mega Drive, SNES), it developed cluster shading, selective dithering, anti-dither outlines and animation on strict frame budgets. Revival communities on Pixel Joint and itch.io, plus tools like Aseprite and fonts like Press Start 2P, keep the idiom central to indie games and retro-flavored graphic design.',
    col: [{ h: '#1a1c2c', n: 'sprite navy' }, { h: '#5d275d', n: 'master purple' }, { h: '#ef7d57', n: 'arcade orange' }, { h: '#38b764', n: 'CRT green' }, { h: '#f4f4f4', n: 'highlight white' }],
    m: ['character ROM and VRAM tiles', 'pixel editors (Aseprite, Deluxe Paint)', 'limited hardware palettes', 'CRT displays'],
    tx: ['1px hard-edge clusters', 'selective dithering', 'CRT phosphor bloom'],
    obj: ['walk-cycle character sprites', 'scrolling tile backgrounds', 'title-screen logos', 'boss battle sprite sheets', 'chiptune title jingle pairings'],
    ex: ['Super Mario Bros. (1985) NES sprites', 'Sonic the Hedgehog (1991) Mega Drive animation', 'Chrono Trigger (1995) SNES tile art'],
    inf: ['Arcade board hardware constraints', 'Home computer demoscene', 'Japanese character design', 'Amiga Deluxe Paint culture'],
    rel: ['8-Bit Palette Snapping', 'Low Poly 3D Aesthetics', 'JRPG Menu & UI Aesthetics'],
    src: [{ n: 'Wikipedia — Sprite (computer graphics)', u: 'https://en.wikipedia.org/wiki/Sprite_(computer_graphics)', t: 'B' }, { n: 'Wikipedia — Pixel art', u: 'https://en.wikipedia.org/wiki/Pixel_art', t: 'B' }, { n: 'Wikipedia — Super Mario Bros.', u: 'https://en.wikipedia.org/wiki/Super_Mario_Bros.', t: 'B' }],
    tg: ['sprite', 'tile', '8-bit', '16-bit', 'palette', 'dithering', 'nes', 'snes'],
    pop: 68, niche: false,
    vd: { shape: 'grid-locked tiles and modular character sprites', line: 'single-pixel contours with cluster shading', composition: 'side-scroll parallax bands and centered HUD', texture: 'hard-edged dither ramps with CRT bloom' },
    typ: { display: 'Press Start 2P', body: 'VT323', notes: '8×8 bitmap tiles and all-caps dialog boxes' },
    lit: { quality: 'emissive CRT glow', temperature: 'cool blue bias with warm sprite accents', shadow: 'stylized two-tone drop shadows' },
    ui: { background: 'black letterbox bars', surface: 'boxed window frames', components: 'chunky bordered buttons and cursor arrows', motion: '12/24fps frame-by-frame steps' },
  },
  {
    n: 'Low Poly 3D Aesthetics', a: ['Low-poly art', 'flat-shaded 3D', 'faceted 3D style'],
    cat: 'Game & Pixel Aesthetic', c: 'Minimal-polygon flat-shaded 3D style', e: 'commercial_style',
    o: 'Arcade and console industry; indie revival', g: 'Global game and motion design', p: '1990s; revival 2013-present', era: 'Early 3D console era to indie revival',
    sum: 'Minimal-triangle flat-shaded 3D — hard facets and vertex-light gradients — once a hardware limit, now a deliberate papercraft-clean indie style.',
    desc: 'Low poly 3D embraces minimal triangle counts with flat shading — hard facets, vertex-light gradients and simplified silhouettes. Originally a hardware necessity of Virtua Fighter-era arcade boards and PS1/N64 consoles, it was revived in the 2010s indie and mobile scene (Monument Valley, Superhot) as a deliberate style, spreading into isometric dioramas, explainer motion graphics and illustration for its clean, papercraft readability.',
    col: [{ h: '#8ecae6', n: 'sky cyan' }, { h: '#ffb703', n: 'pop yellow' }, { h: '#219ebc', n: 'facet teal' }, { h: '#e76f51', n: 'terracotta accent' }, { h: '#f8f9fa', n: 'clean white' }],
    m: ['triangle meshes', 'vertex colors and flat shading', 'affine texture maps (PS1 era)', 'Blender and 3ds Max toolchains'],
    tx: ['hard facet planes', 'vertex-lit gradients', 'pixelated texture warping'],
    obj: ['faceted terrain islands', 'low-poly vehicle sets', 'isometric dioramas', 'stylized character busts', 'mobile game environments'],
    ex: ['Virtua Fighter (1993) flat-shaded arcade 3D', 'Monument Valley (2014) isometric design', 'Superhot (2016) low-poly indie'],
    inf: ['Early hardware polygon budgets', 'Isometric illustration', 'Swiss flat design UI', 'PS1-era nostalgia'],
    rel: ['Sprite & Tile Game Art', 'JRPG Menu & UI Aesthetics'],
    src: [{ n: 'Wikipedia — Low poly', u: 'https://en.wikipedia.org/wiki/Low_poly', t: 'B' }, { n: 'Wikipedia — Virtua Fighter', u: 'https://en.wikipedia.org/wiki/Virtua_Fighter', t: 'B' }, { n: 'Wikipedia — Monument Valley (video game)', u: 'https://en.wikipedia.org/wiki/Monument_Valley_(video_game)', t: 'B' }],
    tg: ['low poly', 'flat shading', 'faceted', 'indie game', 'isometric', 'ps1', 'diorama'],
    pop: 64, niche: false,
    vd: { shape: 'simplified faceted geometry, crystal-like planes', line: 'hard triangle edges without smoothing', composition: 'isometric diorama framing, generous negative space', texture: 'flat color planes with subtle vertex gradients' },
    typ: { display: 'Montserrat', body: 'Open Sans', notes: 'geometric sans UI matching faceted visuals' },
    lit: { quality: 'single directional light, minimal fill', temperature: 'neutral', shadow: 'baked soft blob shadows or none' },
    ui: { background: 'flat pastel gradient', surface: 'rounded translucent cards', components: 'soft-shadow floating buttons', motion: 'ease-out object pops' },
  },
  {
    n: 'JRPG Menu & UI Aesthetics', a: ['JRPG interface style', 'command menu design', 'window UI'],
    cat: 'Game & Pixel Aesthetic', c: 'Japanese RPG interface design tradition', e: 'commercial_style',
    o: 'Japan', g: 'Japanese consoles; global fan emulation', p: '1986-present', era: 'Famicom golden age to modern homage',
    sum: 'Japanese RPG interface tradition: beveled blue-gradient "window" boxes, blinking triangle cursors, command lists and status screens codified by Dragon Quest and Final Fantasy.',
    desc: 'Japanese RPG interface design crystallized with Dragon Quest (1986): rounded-corner "window" boxes with beveled borders, blue-gradient fills, blinking triangle cursors and command lists (Attack/Item/Magic). Final Fantasy\'s ATB gauges, status screens and world-map menus standardized a readable iconography of tiny portraits, bars and counters. Modern titles like Persona 5 restyled the tradition with graphic maximalism, while indies emulate its bitmap-window nostalgia.',
    col: [{ h: '#1b3a8c', n: 'window blue' }, { h: '#dfe8ff', n: 'text white' }, { h: '#f2c14e', n: 'selection gold' }, { h: '#0d1b4b', n: 'border navy' }, { h: '#b03a48', n: 'HP-low red' }],
    m: ['tile-based UI window graphics', 'bitmap fonts', 'menu cursor sprites', 'jingle sting audio cues'],
    tx: ['gradient window dither', '1px bevel borders', 'blinking cursor pulse'],
    obj: ['command windows (Attack/Item/Magic)', 'status screens', 'ATB gauges', 'world-map cursor rings', 'battle-result stat panels'],
    ex: ['Dragon Quest (1986) window menu origin', 'Final Fantasy VI (1994) SNES menus', 'Persona 5 (2016) stylized UI evolution'],
    inf: ['PC-88/98 text adventure menus', 'Wizardry and Ultima ports', 'Japanese bitmap character fonts', 'Pachinko flash styling (Persona era)'],
    rel: ['Sprite & Tile Game Art', 'Low Poly 3D Aesthetics'],
    src: [{ n: 'Wikipedia — Dragon Quest', u: 'https://en.wikipedia.org/wiki/Dragon_Quest', t: 'B' }, { n: 'Wikipedia — Final Fantasy', u: 'https://en.wikipedia.org/wiki/Final_Fantasy', t: 'B' }, { n: 'Wikipedia — Role-playing video game', u: 'https://en.wikipedia.org/wiki/Role-playing_video_game', t: 'B' }],
    tg: ['jrpg', 'menu', 'command window', 'atb', 'status screen', 'cursor', 'bevel'],
    pop: 61, niche: true,
    vd: { shape: 'rounded rectangle windows with thick light/dark bevels', line: 'crisp 1-2px borders', composition: 'bottom-anchored command stacks, left portrait frames', texture: 'blue gradient dither fill' },
    typ: { display: 'PixelMplus12', body: 'MS Gothic', notes: 'kana/kanji bitmap dialog text; Famicom window tones' },
    lit: { quality: 'flat interface light, no scene lighting', temperature: 'cool blue', shadow: 'inner bevel shading only' },
    ui: { background: 'battle scene still', surface: 'blue gradient window stack', components: 'hand cursor selectors, blinking ► pointers', motion: 'cursor blink and window wipe-in' },
  },
  {
    n: 'Analog Horror Aesthetics', a: ['analog horror series style', 'VHS horror aesthetic'],
    cat: 'Technology & Retrofuturism', c: 'Internet-native found-broadcast horror genre', e: 'internet_aesthetic',
    o: 'YouTube, United States', g: 'Global internet communities', p: '2015-present', era: '2020s internet-native horror',
    sum: 'YouTube-native horror staged through obsolete media — VHS tracking errors, CRT scanlines, emergency-broadcast cards and public-information films gone wrong.',
    desc: 'Analog horror is an internet-native genre presenting dread through obsolete media: VHS tracking errors, CRT scanlines, emergency-broadcast cards and public-information films gone wrong. Kris Straub\'s Local 58 (2015-) established the format; Gemini Home Entertainment (2019) and Alex Kister\'s The Mandela Catalogue (2021) popularized the term and its codes — degraded broadcasts, uncanny entities, phone hotlines and viewer-participation lore distributed across YouTube.',
    col: [{ h: '#0d0f0d', n: 'CRT black' }, { h: '#b7bdb1', n: 'phosphor gray-green' }, { h: '#c8352b', n: 'EMERGENCY red' }, { h: '#d8d2c0', n: 'broadcast cream' }, { h: '#3d4a8c', n: 'PSA blue' }],
    m: ['VHS tape stock artifacts', 'CRT cameras and scanlines', 'linear video editing wipes', 'printed emergency broadcast cards'],
    tx: ['tracking distortion bands', 'chromatic bleed', 'tape hiss grain'],
    obj: ['emergency broadcast screens', 'public information film cards', 'corrupted entity faces', 'channel-ID and test-pattern slates', 'phone-in warning hotlines'],
    ex: ['Local 58 (Kris Straub, 2015-)', 'Gemini Home Entertainment (2019-)', 'The Mandela Catalogue (Alex Kister, 2021-)'],
    inf: ['1980s-90s public service announcements', 'Emergency Broadcast System culture', 'Found-footage horror', 'Creepypasta communities'],
    rel: ['Cassette Futurism', 'Vaporwave'],
    src: [{ n: 'Wikipedia — Analog horror', u: 'https://en.wikipedia.org/wiki/Analog_horror', t: 'B' }, { n: 'Wikipedia — Local 58', u: 'https://en.wikipedia.org/wiki/Local_58', t: 'B' }, { n: 'Wikipedia — The Mandela Catalogue', u: 'https://en.wikipedia.org/wiki/The_Mandela_Catalogue', t: 'B' }],
    tg: ['vhs', 'found footage', 'emergency broadcast', 'youtube horror', 'crt', 'creepypasta', 'test pattern'],
    pop: 62, niche: false,
    vd: { shape: '4:3 fullscreen frames with static-centered cards', line: 'low-res soft edges over scanline raster', composition: 'centered broadcast cards, sudden full-frame intrusions', texture: 'tape noise, dropouts and chroma bleed' },
    typ: { display: 'VCR OSD Mono', body: 'Times New Roman', notes: 'all-caps emergency cards and CC-style captions' },
    lit: { quality: 'harsh camera-attached light', temperature: 'cold fluorescent', shadow: 'crushed VHS blacks' },
    ui: { background: 'CRT black', surface: 'scanline overlay panels', components: 'OSD-style text boxes and ▶ cursors', motion: 'tracking jitters and hard-cut stingers' },
  },
]
