// WAVE_VIS - Visual Arts Techniques wave (task 2-h)
// Real, documented painting techniques, drawing/line-work methods, printmaking,
// photographic/optical effects, and color-and-light phenomena as aesthetic categories.
export const WAVE_VIS: any[] = [
  {
    "n": "Buon Fresco",
    "a": ["True fresco", "Affresco", "Fresco painting", "Frescante"],
    "cat": "Painting Technique & School",
    "c": "Wall & plaster",
    "e": "historical",
    "o": "Aegean antiquity (Knossos, Akrotiri), codified in Renaissance Italy",
    "g": "Mediterranean and Europe; 20th-century revivals in Mexico and the USA",
    "p": "c. 1650 BCE to present; Italian peak c. 1300-1560",
    "era": "Antiquity to Renaissance",
    "sum": "True fresco is wall painting brushed onto freshly laid damp lime plaster so pigments bond chemically into the wall as it cures. The image becomes part of the architecture rather than a layer sitting on it.",
    "desc": "Pigments ground in water are applied to intonaco, a smooth coat of wet lime plaster, and carbonatation locks them into the calcium carbonate skin as the wall dries, giving matte, breathable, unflakable color. Painters work in giornata - day-sized patches planned from sinopia underdrawings on the rough arriccio - so monumental cycles advance patch by patch with seam maps still visible under raking light. The lime permits only alkali-stable earth pigments (azurite is destroyed), and errors must be chiseled out and replastered. Giotto's Scrovegni Chapel, Michelangelo's Sistine ceiling and the instructively decaying Leonardo Last Supper made fresco the prestige medium of Italian public art.",
    "col": [{"h": "#F0EAD8", "n": "Lime plaster"}, {"h": "#A84448", "n": "Pompeian red"}, {"h": "#1034A6", "n": "Egyptian blue"}, {"h": "#C8A05A", "n": "Yellow ochre"}, {"h": "#6E7F4F", "n": "Green earth"}, {"h": "#4A3B2A", "n": "Raw umber"}],
    "m": ["Lime plaster (intonaco over arriccio)", "Water-ground pigment slurry", "Sinopia cartoon", "Mason trowel and float", "Bristle brushes", "Pounce bag and stylus"],
    "tx": ["Matte chalky wall", "Seam lines of giornate", "Soft powdery color", "Lime-efflorescence bloom"],
    "obj": ["Chapel fresco cycles", "Palace and villa walls", "Vaults and domes", "Garden loggias", "Cartoon transfer sheets", "Strappo-detached fragments"],
    "ex": ["Giotto, Scrovegni Chapel (Padua)", "Michelangelo, Sistine Chapel ceiling", "Pompeii Fourth Style wall paintings", "Diego Rivera, Detroit Industry murals"],
    "rel": ["Gouache illustration", "Trompe-l'œil", "Soviet Mosaics in Architecture", "Egg tempera panel painting"],
    "par": "",
    "var": ["Mezzo-fresco (on half-dried plaster)", "Fresco secco retouching on dry wall"],
    "cf": ["Fresco secco", "Tempera mural painting"],
    "src": [
      {"n": "Wikipedia: Fresco", "u": "https://en.wikipedia.org/wiki/Fresco", "t": "B"},
      {"n": "The J. Paul Getty Museum", "u": "https://www.getty.edu", "t": "A"}
    ],
    "tg": ["mural", "lime plaster", "monumental", "renaissance", "architecture-bound", "earthy"],
    "pop": 70,
    "niche": false,
    "vd": {"shape": "Grand architectural fields with figures scaled to walls and vaults", "line": "Confident contour set fast before the plaster bites", "composition": "Paced by giornata grids that break the cycle into breath-sized scenes", "texture": "Uniform matte tooth; color sits inside the surface rather than on it", "forms": "Volumes modeled in layered earth tones, never glossy glazes"},
    "typ": {"display": "Trajan Pro", "body": "Garamond", "notes": "Roman inscription capitals and humanist serifs match wall epigraphy and chapel labeling"},
    "lit": {"quality": "Soft raking daylight and candle glow kept diffuse by matte lime", "direction": "High clerestory side light", "temperature": "warm", "shadow": "Painted rather than cast; modeled through earth-tone modulation"},
    "env": {"places": "Chapels, council halls, cloisters, baptisteries, courtyard loggias", "weather": "Dry Mediterranean air that cures lime evenly"},
    "ui": {"background": "Plaster off-white with faint secco staining", "surface": "Troweled and subtly uneven", "components": "Cartouche panels, frieze bands, painted architectural borders", "motion": "None; slow parallax reveal imitates uncovering a scaffolded wall"},
    "rec": {"materials": "Lime putty, marble dust, raw natural pigments", "lighting": "North-facing window light with warm bounce", "objects": "Trowels, pigment cones, full-scale cartoons", "music": "Renaissance vocal polyphony", "scent": "Wet lime and clean mineral water"},
    "arc": {"forms": "Vaulted bays, arcades, domes", "examples": "Scrovegni Chapel, Sistine Chapel, Villa of the Mysteries"},
    "snd": ["Trowel scrape on wet plaster", "Chapel reverb", "Brush slur on mineral ground"],
    "dna": {"mi": 30, "og": 55, "wc": 60, "ns": 15, "ad": 5, "hf": 10, "rr": 55, "ps": 45, "sh": 35, "ql": 35, "oc": 40, "ds": 45, "rs": 55, "eu": 50, "np": 15},
    "emo": {"warm": 65, "cold": 35, "playful": 30, "serious": 70, "chaotic": 25, "ordered": 65, "nostalgic": 60, "futuristic": 20, "peaceful": 55, "ominous": 35}
  },
  {
    "n": "Egg Tempera Panel Painting",
    "a": ["Tempera", "Egg tempera", "Tempera on gesso panel", "Egg-and-gesso painting"],
    "cat": "Painting Technique & School",
    "c": "Panel painting",
    "e": "historical",
    "o": "Greco-Roman Egypt (Fayum), perfected by the Italian trecento and quattrocento",
    "g": "Mediterranean, Byzantine world, Italy; 20th-century revival in Britain and America",
    "p": "1st century CE to c. 1500, revived c. 1900",
    "era": "Medieval to Early Renaissance",
    "sum": "Egg tempera paints pigment bound with egg yolk onto a rigid gessoed panel, drying within seconds to a hard, luminous, water-resistant film. It is the crisp, jewel-toned medium of Byzantine icons and early Renaissance altarpieces.",
    "desc": "Artists layer many thin, hatch-built strokes of yolk-emulsion paint over white gesso ground, so light passes through each stratum and reflects off the chalk beneath, giving the characteristic glowing, satiny finish. Because the paint grabs almost instantly, shading is built from fine cross-hatching and repeated veils rather than broad blending, rewarding tiny brushes and surgical patience. Panels are prepared with linen and up to ten coats of gesso sanded to ivory; gold leaf may be burnished into haloes. Duccio's Maesta, Botticelli's Birth of Venus and Andrew Wyeth's Christina's World (a 20th-century revival) show its range from icon splendor to dry American realism.",
    "col": [{"h": "#EFE7D3", "n": "Gesso white"}, {"h": "#D4AF37", "n": "Burnished gold"}, {"h": "#E34234", "n": "Vermilion"}, {"h": "#120A8F", "n": "Ultramarine"}, {"h": "#3F7A5A", "n": "Malachite green"}, {"h": "#E7C9A9", "n": "Tempera flesh"}],
    "m": ["Egg yolk emulsion", "Distilled water", "Ground mineral pigments", "Gesso panel (chalk and rabbit-skin glue)", "Sable brushes", "Gold leaf and agate burnisher"],
    "tx": ["Satin eggshell sheen", "Fine hatched striations", "Hard polished panel", "Flecked gold ground"],
    "obj": ["Altarpieces", "Icons", "Devotional diptychs", "Portrait panels", "Predella scenes"],
    "ex": ["Duccio, Maesta (1308-11)", "Botticelli, The Birth of Venus", "Simone Martini, Annunciation (1333)", "Andrew Wyeth, Christina's World (1948)"],
    "rel": ["Buon Fresco", "Gongbi", "Nihonga", "Grisaille monochrome"],
    "par": "",
    "var": ["Tempera grassa (egg-oil emulsion)", "Icon-panel tempera with tooled gilded grounds"],
    "cf": ["Oil glazing", "Casein painting"],
    "src": [
      {"n": "Wikipedia: Tempera", "u": "https://en.wikipedia.org/wiki/Tempera", "t": "B"},
      {"n": "The Metropolitan Museum of Art", "u": "https://www.metmuseum.org", "t": "A"}
    ],
    "tg": ["panel painting", "gold ground", "icon", "renaissance", "crisp line", "luminous"],
    "pop": 58,
    "niche": false,
    "vd": {"shape": "Elongated figures and architectural compartments on rigid panels", "line": "Knife-sharp contour refined by hatched modeling", "composition": "Hieratic symmetry, often under tooled gold haloes", "texture": "Satin eggshell with visible fine striations", "forms": "Faceted drapery and luminous flesh built in translucent veils"},
    "typ": {"display": "Cinzel", "body": "EB Garamond", "notes": "Lapidary capitals and bookish serifs echo altar inscriptions and panel labels"},
    "lit": {"quality": "Even, high-key glow as if lit from the gesso itself", "direction": "Frontal, icon-like illumination", "temperature": "warm", "shadow": "Thin, warm, built in hatch layers rather than darkness"},
    "env": {"places": "Workshops of Siena and Florence, monastery studios", "weather": "Stable interior humidity for gesso panels"},
    "ui": {"background": "Warm ivory and gold field", "surface": "Sanded gesso smoothness", "components": "Gilded frames, tabernacle borders, incised haloes", "motion": "Slow crossfade; light that seems to rise from within panels"},
    "rec": {"materials": "Gesso slabs, pigment cones, fresh eggs", "lighting": "Soft frontal glow, candle-warm accents", "objects": "Agate burnishers, tiny sable brushes, reliquary frames", "music": "Byzantine chant, trecento ballate", "scent": "Rabbit-skin glue, egg, and frankincense"},
    "snd": ["Brush tick on gesso", "Burnisher ringing on gold", "Choir drone"],
    "dna": {"mi": 45, "og": 50, "wc": 55, "ns": 10, "ad": 5, "hf": 15, "rr": 40, "ps": 40, "sh": 30, "ql": 30, "oc": 60, "ds": 50, "rs": 45, "eu": 70, "np": 20},
    "emo": {"warm": 55, "cold": 45, "playful": 25, "serious": 80, "chaotic": 20, "ordered": 75, "nostalgic": 70, "futuristic": 15, "peaceful": 65, "ominous": 30}
  },
  {
    "n": "Encaustic Painting",
    "a": ["Wax painting", "Hot-wax painting", "Wax encaustic", "Punic wax technique"],
    "cat": "Painting Technique & School",
    "c": "Hot wax medium",
    "e": "historical",
    "o": "Ancient Greece and Hellenistic Egypt",
    "g": "Egypt (Fayum), Greece, Rome; mid-20th-century American revival",
    "p": "5th century BCE to 3rd century CE; revived from the 1950s",
    "era": "Antiquity; modern revival",
    "sum": "Encaustic binds pigment in hot beeswax that is applied molten and fused layer to layer with heat. It produced the hauntingly lifelike Fayum mummy portraits and was revived by Jasper Johns in 1950s America.",
    "desc": "Beeswax (often with damar resin) is melted with pigment and brushed or poured onto rigid supports; a heat gun, iron or tongs re-melt each layer so strata fuse into a single translucent body that can be carved, scraped and polished. The wax chills in seconds, allowing incised lines, collage and embedded objects, while the finished surface resists moisture and rarely yellows. Its ancient apex is the Fayum funerary portraits, whose encaustic flesh still looks freshly painted after eighteen centuries; the modern revival began with Jasper Johns' Flag, where collaged newspaper glows under waxy skin.",
    "col": [{"h": "#F5EDDC", "n": "Beeswax white"}, {"h": "#D9A441", "n": "Honey amber"}, {"h": "#C9A18E", "n": "Fayum flesh"}, {"h": "#6E4B3A", "n": "Mummy brown"}, {"h": "#7A2E2E", "n": "Oxblood"}, {"h": "#3E2F23", "n": "Deep umber"}],
    "m": ["Refined beeswax", "Damar resin", "Pigment sticks or dry pigment", "Heat gun, torch or tacking iron", "Rigid panel support", "Scraping and carving tools"],
    "tx": ["Translucent waxed depth", "Fused stratified ridges", "Carved incisions", "Polished satin bloom"],
    "obj": ["Fayum funerary portraits", "Contemporary abstract panels", "Mixed-media wax collages", "Sculptural wax reliefs"],
    "ex": ["Fayum mummy portraits (1st-3rd c. CE)", "Jasper Johns, Flag (1954-55)", "Jasper Johns, White Flag (1955)"],
    "inf": ["Egg tempera panel painting", "Ancient panel painting tradition"],
    "rel": ["Collage", "Abstract Expressionism", "Impasto"],
    "par": "",
    "var": ["Cold-wax medium worked at room temperature", "Wax-and-collage assemblage"],
    "cf": ["Oil glazing", "Resin varnishing"],
    "src": [
      {"n": "Wikipedia: Encaustic painting", "u": "https://en.wikipedia.org/wiki/Encaustic_painting", "t": "B"},
      {"n": "The J. Paul Getty Museum", "u": "https://www.getty.edu", "t": "A"}
    ],
    "tg": ["wax", "fayum", "antiquity", "mixed media", "translucent", "tactile"],
    "pop": 55,
    "niche": false,
    "vd": {"shape": "Firm contour with softly melted edges", "line": "Incised lines cut into cooled wax", "composition": "Layered fields; newspaper and fabric embedded under skin", "texture": "Stratified, translucent, faintly polished", "forms": "Flesh-like volumetric depth unusual for flat media"},
    "lit": {"quality": "Warm glow through translucent strata", "direction": "Frontal with warm lateral raking", "temperature": "warm", "shadow": "Brown wax shadows that never go black"},
    "ui": {"background": "Warm ivory wax field", "surface": "Satin, faintly matte", "components": "Embed, carve and polish tool icons", "motion": "Melt-and-fuse transitions between layers"},
    "rec": {"materials": "Beeswax blocks, heat tools, collage papers", "lighting": "Warm tungsten that stirs the wax glow", "objects": "Propane torches, tacking irons, hake brushes", "music": "Warm drones, tape loops", "scent": "Honeyed beeswax and pine resin"},
    "snd": ["Soft torch hiss", "Wax crackle on cooling", "Palette-knife scrape"],
    "dna": {"mi": 40, "og": 60, "wc": 70, "ns": 30, "ad": 5, "hf": 20, "rr": 60, "ps": 40, "sh": 40, "ql": 40, "oc": 40, "ds": 45, "rs": 50, "eu": 45, "np": 25},
    "emo": {"warm": 70, "cold": 30, "playful": 35, "serious": 65, "chaotic": 35, "ordered": 55, "nostalgic": 75, "futuristic": 25, "peaceful": 50, "ominous": 30}
  },
  {
    "n": "Grisaille Monochrome",
    "a": ["Grisaille painting", "En grisaille", "Gray monochrome", "Gray-tone painting"],
    "cat": "Painting Technique & School",
    "c": "Monochrome",
    "e": "historical",
    "o": "Northern Europe and Italy, 13th-15th centuries",
    "g": "Flanders, France, Italy, Netherlands",
    "p": "c. 1200 to present",
    "era": "Gothic to Modern",
    "sum": "Grisaille paints an entire image in shades of gray, either as a finished imitation of stone sculpture or as the tonal understructure beneath glazed color. Van Eyck's painted statues and countless underpaintings are its canonical forms.",
    "desc": "The painter works a single value family - lead white, ivory black and neutral grays - from highlights through halftones to deep shadow, so form reads entirely through lightness. As an independent picture it impersonates marble or bronze relief, as on the exterior shutters of the Ghent Altarpiece; as underpainting it establishes light logic that color glazes later enrich, the method of Flemish Primitives and academic training alike. Stained-glass grisaille shares the aesthetic of quiet luminous neutrality, and Picasso's Guernica proves gray can carry maximal drama.",
    "col": [{"h": "#F4F4F0", "n": "Lead white"}, {"h": "#C9C9C2", "n": "Light gray"}, {"h": "#9A9A93", "n": "Halftone gray"}, {"h": "#6B6B66", "n": "Shadow gray"}, {"h": "#3C3C38", "n": "Ivory black depth"}],
    "m": ["Lead white and ivory black", "Neutral gray mixes", "Lean oil medium", "Brushes in several sizes", "Toned panel or canvas"],
    "tx": ["Smooth enamel-like transitions", "Crisp relief highlights", "Matte stone-like surface"],
    "obj": ["Altarpiece shutters", "Sculpture-imitation panels", "Underpaintings for glazing", "Choir-stall designs", "Grisaille glass windows"],
    "ex": ["Van Eyck workshop, Ghent Altarpiece exterior (1432)", "Andrea Mantegna, grisaille monochromes", "Picasso, Guernica (1937)"],
    "rel": ["Sfumato", "Chiaroscuro", "Tenebrism", "Egg tempera panel painting"],
    "par": "",
    "var": ["Verdaccio green-brown underpainting", "Brunaille brown monochrome"],
    "cf": ["Stained-glass grisaille (same name, different craft)", "Pentimento underlayers"],
    "src": [
      {"n": "Wikipedia: Grisaille", "u": "https://en.wikipedia.org/wiki/Grisaille", "t": "B"},
      {"n": "The National Gallery, London", "u": "https://www.nationalgallery.org.uk", "t": "A"}
    ],
    "tg": ["monochrome", "underpainting", "value study", "sculptural", "flemish", "austere"],
    "pop": 48,
    "niche": false,
    "vd": {"shape": "Statuesque forms with relief-like edges", "line": "Contour subordinated to value transitions", "composition": "Quiet symmetry; color removed so structure shows", "texture": "Smooth, enamel-to-stone range", "forms": "Volumes built purely from light and shadow steps"},
    "typ": {"display": "Cormorant Garamond", "body": "Source Serif Pro", "notes": "Restrained classical serifs match monochrome austerity"},
    "lit": {"quality": "Cool even daylight, no color temperature shifts", "direction": "Soft top-left studio light", "temperature": "cool", "shadow": "Graded value steps, never muddy hue"},
    "ui": {"background": "Stone-neutral off-white", "surface": "Matte plaster gray", "components": "Relief-inspired buttons and incised dividers", "motion": "Fades between value steps only"},
    "rec": {"materials": "White and black pigment only", "lighting": "Diffuse north light", "objects": "Plaster casts, value scales, maulsticks", "music": "Renaissance polyphony, solo lute", "scent": "Cold chalk and linseed"},
    "snd": ["Dry brush whisper", "Stone room tone", "Single sustained organ note"],
    "dna": {"mi": 70, "og": 40, "wc": 35, "ns": 10, "ad": 5, "hf": 15, "rr": 35, "ps": 30, "sh": 45, "ql": 25, "oc": 70, "ds": 50, "rs": 40, "eu": 75, "np": 15},
    "emo": {"warm": 30, "cold": 70, "playful": 20, "serious": 85, "chaotic": 15, "ordered": 85, "nostalgic": 55, "futuristic": 25, "peaceful": 50, "ominous": 45}
  },
  {
    "n": "Sfumato",
    "a": ["Sfumatura", "Smoke-soft modeling", "Toneless gradation"],
    "cat": "Painting Technique & School",
    "c": "Edge & tone handling",
    "e": "historical",
    "o": "Florence and Milan, c. 1490, associated with Leonardo da Vinci",
    "g": "Lombardy, Florence; adopted across Italian Mannerism",
    "p": "c. 1490-1560",
    "era": "High Renaissance",
    "sum": "Sfumato dissolves contours into smoky gradations of tone so forms emerge and recede without hard edges, as in the Mona Lisa's face. Leonardo described blending 'without strokes or borders, in the manner of smoke'.",
    "desc": "Dozens of translucent glazes of increasingly transparent oil are laid one over another, each veil blurring the boundary between light and shadow until no perceivable line remains; technical studies of the Mona Lisa suggest as many as thirty micro-layers only a few microns thick. The method depends on slow-drying oil, soft brushes and the patience to let each film level before the next, producing skin that seems to breathe and eyes that hold ambiguous focus from any angle. Leonardo refined it from his chiaroscuro experiments, Correggio pushed it toward sweetness, and it remains the benchmark of atmospheric softness against which crisp techniques are contrasted.",
    "col": [{"h": "#1F1B16", "n": "Smoke black"}, {"h": "#4A3F30", "n": "Deep umber"}, {"h": "#7A6A50", "n": "Mid sienna"}, {"h": "#A98F6F", "n": "Warm halftone"}, {"h": "#6E7355", "n": "Olive glaze"}, {"h": "#D9C39A", "n": "Lit flesh"}],
    "m": ["Slow-drying walnut or linseed oil", "Transparent earth pigments", "Soft-hair brushes", "Fine glazing layers", "Poplar panel"],
    "tx": ["Smoke-soft gradients", "Micron-thin glaze strata", "Edgeless transitions"],
    "obj": ["Portraits", "Devotional paintings", "Landscape backgrounds", "Close-up facial studies"],
    "ex": ["Leonardo, Mona Lisa (c. 1503-19)", "Leonardo, Virgin of the Rocks", "Correggio, late devotional paintings"],
    "inf": ["Chiaroscuro", "Oil glazing tradition"],
    "rel": ["Chiaroscuro", "Impasto", "Grisaille monochrome"],
    "par": "",
    "var": [],
    "cf": ["Chiaroscuro (value contrast, not edge dissolution)", "Atmospheric perspective"],
    "src": [
      {"n": "Wikipedia: Sfumato", "u": "https://en.wikipedia.org/wiki/Sfumato", "t": "B"},
      {"n": "The Metropolitan Museum of Art", "u": "https://www.metmuseum.org", "t": "A"}
    ],
    "tg": ["glazing", "soft edge", "leonardo", "portrait", "atmospheric", "renaissance"],
    "pop": 78,
    "niche": false,
    "vd": {"shape": "Forms defined by tonal mass, not outline", "line": "Contour dissolved into smoke", "composition": "Figures emerging from atmospheric depth", "texture": "Silken, veil-on-veil smoothness", "forms": "Organic volume with ambiguous, breathing edges"},
    "typ": {"display": "Cormorant", "body": "EB Garamond", "notes": "High-contrast Renaissance serifs carry the smoky elegance"},
    "lit": {"quality": "Twilight diffusion; no point source", "direction": "Frontal enveloping light", "temperature": "warm", "shadow": "Warm, transparent, edgeless"},
    "ui": {"background": "Deep umber gradient", "surface": "Frosted glass blur", "components": "Soft-shadow cards, feathered dividers", "motion": "Slow opacity ramps and defocus pulls"},
    "rec": {"materials": "Walnut oil, ultra-fine pigment", "lighting": "North-window twilight ambience", "objects": "Soft brushes, veiling glazes, anatomical studies", "music": "Lira da braccio, slow madrigals", "scent": "Linseed and old resin"},
    "snd": ["Breath-soft room tone", "Glaze brush whisper", "Distant bell"],
    "dna": {"mi": 55, "og": 65, "wc": 65, "ns": 10, "ad": 5, "hf": 20, "rr": 25, "ps": 30, "sh": 20, "ql": 15, "oc": 55, "ds": 40, "rs": 45, "eu": 85, "np": 20},
    "emo": {"warm": 60, "cold": 40, "playful": 20, "serious": 75, "chaotic": 25, "ordered": 60, "nostalgic": 70, "futuristic": 30, "peaceful": 60, "ominous": 45}
  },
  {
    "n": "Impasto",
    "a": ["Impasto brushwork", "Thick-paint handling", "Relief painting"],
    "cat": "Painting Technique & School",
    "c": "Oil handling",
    "e": "historical",
    "o": "Venetian and Dutch painting; radicalized by 19th-century French art",
    "g": "Europe and North America",
    "p": "c. 1550 to present; peak 1870-1970",
    "era": "Baroque to Modern",
    "sum": "Impasto lays paint on thickly enough that brush and knife strokes stand up in relief, turning each mark into both image and physical record of gesture. Van Gogh's ridged skies and Rembrandt's encrusted highlights define the effect.",
    "desc": "Paint is loaded stiff - sometimes with added wax or sand - and dragged with hog bristle or palette knife so every stroke keeps its shape, catching real light on its ridges and casting micro-shadows that animate the surface as the viewer moves. Rembrandt built late self-portrait highlights into sculptural lumps, Van Gogh squeezed straight from the tube in The Starry Night, and Frank Auerbach rebuilt portrait heads in accumulation after accumulation until paint became terrain. Beyond drama, impasto declares material presence: the picture admits it is made of stuff.",
    "col": [{"h": "#F5F1E6", "n": "Lead white ridge"}, {"h": "#F2C649", "n": "Chrome yellow"}, {"h": "#0047AB", "n": "Cobalt blue"}, {"h": "#40826D", "n": "Viridian"}, {"h": "#E34234", "n": "Vermilion"}, {"h": "#003153", "n": "Prussian blue"}],
    "m": ["Stiff oil or acrylic paint", "Palette knives", "Hog-bristle brushes", "Beeswax or sand additives", "Coarse canvas or panel"],
    "tx": ["Sculptural paint ridges", "Brush-bristle grooves", "Knife-buttered slabs", "Cracked encrustation in extremes"],
    "obj": ["Expressionist portraits", "Landscapes with animated skies", "Late self-portraits", "Matter paintings"],
    "ex": ["Rembrandt, late self-portraits", "Van Gogh, The Starry Night (1889)", "Frank Auerbach, Head of E.O.W. series"],
    "rel": ["Alla prima", "Neo-Expressionism", "Art Informel", "Encaustic painting"],
    "par": "",
    "var": ["Broken impasto (juxtaposed dabs)", "Palette-knife impasto", "Cold-wax-reinforced buildup"],
    "cf": ["Impressionist broken color (thin, not thick)", "Gestural abstraction"],
    "src": [
      {"n": "Wikipedia: Impasto", "u": "https://en.wikipedia.org/wiki/Impasto", "t": "B"},
      {"n": "Van Gogh Museum", "u": "https://www.vangoghmuseum.nl", "t": "A"}
    ],
    "tg": ["thick paint", "gesture", "texture", "expressionism", "physical surface", "oil"],
    "pop": 74,
    "niche": false,
    "vd": {"shape": "Forms carried by directional stroke masses", "line": "The stroke itself is the line", "composition": "Turbulent, stroke-built fields", "texture": "Dominant; ridges catch actual light", "forms": "Shadows follow real paint topography"},
    "typ": {"display": "Archivo Black", "body": "Source Sans Pro", "notes": "Heavy grotesque display matches the weight of built-up paint"},
    "lit": {"quality": "Gallery spots that rake across ridges", "direction": "Side raking light essential", "temperature": "warm", "shadow": "Cast by real paint relief as much as painted"},
    "ui": {"background": "Deep neutral to let strokes pop", "surface": "Embossed, tactile-feeling panels", "components": "Chunky buttons with layered shadows", "motion": "Parallax over textured surfaces"},
    "rec": {"materials": "Heavy-body paint, wax additives", "lighting": "Directional raking spots", "objects": "Palettes of squeezed color, knives, jars of medium", "music": "Late Romantic strings, free jazz", "scent": "Linseed and pigment dust"},
    "snd": ["Squelch of loaded bristle", "Knife scrape on canvas", "Thick-paint slap"],
    "dna": {"mi": 35, "og": 60, "wc": 55, "ns": 15, "ad": 5, "hf": 15, "rr": 70, "ps": 40, "sh": 55, "ql": 60, "oc": 40, "ds": 40, "rs": 50, "eu": 35, "np": 25},
    "emo": {"warm": 60, "cold": 40, "playful": 40, "serious": 60, "chaotic": 60, "ordered": 40, "nostalgic": 45, "futuristic": 25, "peaceful": 30, "ominous": 45}
  },
  {
    "n": "Alla Prima",
    "a": ["Wet-on-wet", "Direct painting", "Au premier coup", "Premier coup"],
    "cat": "Painting Technique & School",
    "c": "Oil handling",
    "e": "historical",
    "o": "Venetian and Dutch 17th-century practice; 19th-century mainstream via paint tubes",
    "g": "Europe and North America",
    "p": "c. 1600 to present",
    "era": "Baroque to Modern",
    "sum": "Alla prima completes an oil painting in a single wet session, laying fresh color into still-wet paint without underpainting or glazes. Frans Hals' flicked portraits and Sargent's dashing likenesses are its high points.",
    "desc": "Working from thin darks to thick lights before anything dries, the painter must judge color, value and edge in one pass, which keeps hues clean and edges lively - mixing on the canvas itself rather than on the palette. Speed produces its signature look: unblended juxtaposed strokes, wet-into-wet smears where colors meet, and a surface that records a decisive hour of looking. Hals built laughing faces from slash-like strokes, the 1841 collapsible tin tube made the method portable, and Sargent or Anders Zorn turned it into society-portrait virtuosity; today it is the default language of oil sketching and portrait demonstrations.",
    "col": [{"h": "#F6F3EC", "n": "Titanium white"}, {"h": "#D94F30", "n": "Vermilion fresh"}, {"h": "#40826D", "n": "Viridian"}, {"h": "#C68E3F", "n": "Raw ochre"}, {"h": "#B85A6C", "n": "Rose madder"}, {"h": "#1C1C1C", "n": "Ivory black"}],
    "m": ["Fresh oil colors", "Collapsible paint tubes", "Bristle brushes", "Canvas or toned panel", "Palette knife", "Medium (linseed or oleopasto)"],
    "tx": ["Unblended juxtaposed strokes", "Wet-into-wet smears", "Lively edges", "Lean-to-fat single pass"],
    "obj": ["Portrait sketches", "One-session studies", "Society portraits", "Outdoor oil sketches", "Demonstration paintings"],
    "ex": ["Frans Hals, The Laughing Cavalier (1624)", "John Singer Sargent portraits", "Anders Zorn, portrait oils"],
    "rel": ["Plein air painting", "Impasto", "Tenebrism"],
    "par": "",
    "var": ["Wet-on-dry rework (contrary practice)", "Direct watercolor"],
    "cf": ["Glazing (layered, slow)", "Impressionist broken color"],
    "src": [
      {"n": "Wikipedia: Wet-on-wet", "u": "https://en.wikipedia.org/wiki/Wet-on-wet", "t": "B"},
      {"n": "Tate", "u": "https://www.tate.org.uk", "t": "A"}
    ],
    "tg": ["oil sketch", "one session", "direct painting", "portrait", "fresh color", "virtuoso"],
    "pop": 62,
    "niche": false,
    "vd": {"shape": "Forms stated in a few decisive shapes", "line": "Slash-like strokes double as contour", "composition": "Centered emphasis, backgrounds stated broadly", "texture": "Varied - thin translucent darks, thick opaque lights", "forms": "Volumetric but never over-finished"},
    "typ": {"display": "Libre Baskerville", "body": "PT Serif", "notes": "Confident book serifs suit the portrait-salon milieu"},
    "lit": {"quality": "North-light studio daylight, one steady session", "direction": "Consistent key light on sitter", "temperature": "warm", "shadow": "Transparent thin darks against impasto lights"},
    "ui": {"background": "Warm toned-canvas ground", "surface": "Brushy, lively", "components": "Sketch-like cards with visible stroke textures", "motion": "Quick, confident ease-ins; nothing over-polished"},
    "rec": {"materials": "Limited travel palette, easel, turpentine", "lighting": "Single north window or skylight", "objects": "Mahl stick, palette cups, sitter chair", "music": "Salon piano, chamber music", "scent": "Spirits of turpentine and fresh paint"},
    "snd": ["Rapid brush flicks", "Turpentine splash", "Studio clock tick"],
    "dna": {"mi": 45, "og": 55, "wc": 60, "ns": 15, "ad": 5, "hf": 15, "rr": 55, "ps": 45, "sh": 40, "ql": 45, "oc": 45, "ds": 45, "rs": 60, "eu": 60, "np": 25},
    "emo": {"warm": 65, "cold": 35, "playful": 45, "serious": 55, "chaotic": 40, "ordered": 60, "nostalgic": 50, "futuristic": 20, "peaceful": 45, "ominous": 25}
  },
  {
    "n": "Plein Air Painting",
    "a": ["En plein air", "Outdoor painting", "Painting on location", "Open-air painting"],
    "cat": "Painting Technique & School",
    "c": "Field painting",
    "e": "historical",
    "o": "Roman campagna sketches and the Barbizon School; consolidated 1840s-70s",
    "g": "Fontainebleau forest, Normandy coast, worldwide artist colonies",
    "p": "c. 1780s to present; canon 1841-1920",
    "era": "Romanticism to Impressionism",
    "sum": "Plein air painting means executing the picture outdoors, in front of the motif, chasing changing light with portable gear. It is the founding discipline of the Barbizon School and Impressionism, made possible by the 1841 paint tube.",
    "desc": "The painter sets up a box easel and limited palette directly before the subject, blocking in big value masses quickly because cloud and sun alter the scene within an hour or two; wet-into-wet handling and pre-tinted panels keep pace with the light. Corot's campagna oil studies, the Barbizon painters' Fontainebleau woods, Monet's serial haystacks and Rouen facades, and Winslow Homer's seaside turned direct observation into modernism's evidence base. The finish is characteristically fresh and generalized - accurate relationships of hue and temperature matter more than detail - and contemporary plein air events have revived the practice worldwide.",
    "col": [{"h": "#7FB2D9", "n": "Open sky"}, {"h": "#5F7F45", "n": "Foliage green"}, {"h": "#A0522D", "n": "Sienna earth"}, {"h": "#C79A4B", "n": "Yellow ochre"}, {"h": "#E9E4D4", "n": "Sunlit canvas tone"}, {"h": "#2E4A8F", "n": "Ultramarine shadow"}],
    "m": ["Portable box easel (pochade box)", "Field palette and limited colors", "Tinted panels or canvases", "Collapsible paint tubes", "Umbrella and sun hat", "Painting backpack"],
    "tx": ["Fresh broad strokes", "Generalized detail", "Atmospheric color temperature shifts"],
    "obj": ["Landscape oil studies", "Coastal seascapes", "Village street scenes", "Serial canvases of one motif", "Nocturne sketches"],
    "ex": ["Claude Monet, Haystacks series (1890-91)", "Barbizon School forest studies", "Winslow Homer marine paintings", "Camille Corot campagna oil sketches"],
    "inf": ["Alla prima", "Barbizon School", "Romanticism"],
    "rel": ["Impressionism", "Alla prima", "Hague School", "Norwich School"],
    "par": "",
    "var": ["Serial plein air (one motif, changing light)", "Pochade (small rapid study)"],
    "cf": ["Studio landscape painting", "Photography-based landscape"],
    "src": [
      {"n": "Wikipedia: En plein air", "u": "https://en.wikipedia.org/wiki/En_plein_air", "t": "B"},
      {"n": "The Metropolitan Museum of Art", "u": "https://www.metmuseum.org", "t": "A"}
    ],
    "tg": ["outdoor", "landscape", "impressionism", "natural light", "portable", "observation"],
    "pop": 66,
    "niche": false,
    "vd": {"shape": "Broad masses of land, sky, water", "line": "Minimal contour; edges are color meets color", "composition": "Strong value division, often low horizon", "texture": "Loose strokes sized to the motif", "forms": "Suggested rather than itemized"},
    "typ": {"display": "Playfair Display", "body": "Lora", "notes": "Nineteenth-century exhibition-catalogue flavor"},
    "lit": {"quality": "The subject itself - sun, haze, glitter", "direction": "Constantly moving overhead source", "temperature": "warm", "shadow": "Colored (violet-blue) rather than black"},
    "env": {"places": "Riverbanks, harvest fields, harbor quays, forest clearings", "weather": "Broken clouds, sea breeze, low golden sun"},
    "ui": {"background": "Sky-toned gradients", "surface": "Brushy canvas weave", "components": "Easel-inspired frames and tripods", "motion": "Light-angle sliders that repaint the scene"},
    "rec": {"materials": "Pochade box, stooled canvas carriers", "lighting": "Direct sun with white umbrella diffuser", "objects": "Tube caps, viewfinder, thermos", "music": "Debussy, pastoral folk", "scent": "Crushed grass, oil paint, river damp"},
    "snd": ["Wind in grass", "Brush scrubs on canvas", "Distant church bell"],
    "dna": {"mi": 50, "og": 70, "wc": 60, "ns": 20, "ad": 5, "hf": 15, "rr": 55, "ps": 45, "sh": 30, "ql": 30, "oc": 40, "ds": 55, "rs": 55, "eu": 45, "np": 25},
    "emo": {"warm": 70, "cold": 30, "playful": 45, "serious": 45, "chaotic": 30, "ordered": 55, "nostalgic": 60, "futuristic": 15, "peaceful": 75, "ominous": 15}
  },
  {
    "n": "Tenebrism",
    "a": ["Dramatic illumination", "Caravaggism lighting"],
    "cat": "Painting Technique & School",
    "c": "Dramatic lighting",
    "e": "historical",
    "o": "Rome, c. 1595-1610, around Caravaggio",
    "g": "Rome, Naples, Spain, Utrecht (Caravaggisti network)",
    "p": "c. 1595-1650",
    "era": "Baroque",
    "sum": "Tenebrism stages figures in a darkness that dominates the picture, pierced by theatrical spotlights acting like stage lighting on a bare black set. Caravaggio's Calling of Saint Matthew is the type specimen.",
    "desc": "Unlike mere strong shading, tenebrism makes darkness a compositional subject: forms are isolated in near-black fields and riveted by a single hot, often raking light that snags on hands, steel and faces. The drama carries Counter-Reformation content - conversion, martyrdom, revelation - by making the inexplicable light itself an actor, as in The Calling of Saint Matthew where the divine ray follows Christ's pointed hand. Artemisia Gentileschi, Ribera and the Utrecht Caravaggisti exported the idiom; Honthorst pushed it to single-candle night scenes, and its lighting logic still governs film noir and cinematic key-light practice.",
    "col": [{"h": "#0D0B08", "n": "Void black"}, {"h": "#1E1710", "n": "Near-black brown"}, {"h": "#C99A5B", "n": "Spotlit flesh"}, {"h": "#D9A84E", "n": "Candle gold"}, {"h": "#6E1D24", "n": "Deep crimson"}, {"h": "#EFE6D0", "n": "Highlight white"}],
    "m": ["Dark toned ground", "Impasto highlights", "Transparent shadow glazes", "Single-source studio setup", "Candle or lamp props"],
    "tx": ["Inky enveloping darkness", "Hot specular highlights", "Velvet shadow gradients"],
    "obj": ["Martyrdom scenes", "Conversion narratives", "Cardsharp and tavern pictures", "Single-candle interiors"],
    "ex": ["Caravaggio, The Calling of Saint Matthew (1599-1600)", "Artemisia Gentileschi, Judith Slaying Holofernes (c. 1620)", "Gerard van Honthorst candle scenes", "Jusepe de Ribera martyrdoms"],
    "inf": ["Chiaroscuro", "Venetian colorito tradition"],
    "rel": ["Chiaroscuro", "Film noir", "Baroque Revival", "Roman Baroque"],
    "par": "",
    "var": ["Candlelight tenebrism (Honthorst)", "Night-piece genre scenes"],
    "cf": ["Chiaroscuro (modeling without dominating darkness)"],
    "src": [
      {"n": "Wikipedia: Tenebrism", "u": "https://en.wikipedia.org/wiki/Tenebrism", "t": "B"},
      {"n": "Google Arts & Culture", "u": "https://artsandculture.google.com", "t": "A"}
    ],
    "tg": ["baroque", "spotlight", "caravaggio", "theatrical", "dark field", "counter-reformation"],
    "pop": 68,
    "niche": false,
    "vd": {"shape": "Figures emerging from an enveloping black field", "line": "Contour created purely by light boundary", "composition": "Diagonal light shafts and off-stage sources", "texture": "Glossy highlight against matte dark", "forms": "Sculptural, instantly readable silhouettes"},
    "typ": {"display": "Playfair Display", "body": "Source Serif Pro", "notes": "Dramatic serif contrast mirrors the light-dark theatre"},
    "lit": {"quality": "Hard single key light, theatrical", "direction": "Oblique high side or off-canvas source", "temperature": "warm", "shadow": "Total, swallowing, close-valued"},
    "ui": {"background": "Near-black #0D0B08", "surface": "Vignette-steeped panels", "components": "Spotlit focal cards, dark-mode chrome", "motion": "Light sweep reveals; iris-in transitions"},
    "rec": {"materials": "Deep red velvet, gilt frames", "lighting": "Single candle-equivalent key", "objects": "Pewter jugs, lutes, playing cards", "music": "Monteverdi, early Baroque toccatas", "scent": "Candle smoke and old wine"},
    "snd": ["Candle flutter", "Sub-bass room silence", "Dagger-sharp string pluck"],
    "dna": {"mi": 25, "og": 55, "wc": 70, "ns": 10, "ad": 5, "hf": 10, "rr": 45, "ps": 30, "sh": 65, "ql": 55, "oc": 35, "ds": 25, "rs": 55, "eu": 55, "np": 10},
    "emo": {"warm": 50, "cold": 50, "playful": 20, "serious": 90, "chaotic": 35, "ordered": 65, "nostalgic": 40, "futuristic": 15, "peaceful": 20, "ominous": 80}
  },
  {
    "n": "Chiaroscuro",
    "a": ["Clair-obscur", "Light-dark modeling", "Chiaroscuro woodcut (print branch)"],
    "cat": "Painting Technique & School",
    "c": "Light modeling",
    "e": "historical",
    "o": "Renaissance Italy, formalized by Leonardo's notebooks",
    "g": "Italy, Netherlands, France",
    "p": "c. 1490 to present",
    "era": "Renaissance to Baroque",
    "sum": "Chiaroscuro is the systematic modeling of form through contrasts of light and shade, giving painted figures the solidity of sculpture. It spans Leonardo's soft volumes, Rembrandt's glowing interiors and the chiaroscuro woodcut print.",
    "desc": "The painter plans a light logic - one dominant source, graded halftones, reflected lights in the shadows - so every form turns convincingly in space, from Leonardo's Virgin of the Rocks to Rembrandt's The Night Watch, where light picks a crowd into a narrative. Georges de La Tour compressed it into candlelit geometry, while in printmaking the chiaroscuro woodcut (Ugo da Carpi, Goltzius) achieved tonal effects with two or three inked blocks. As a principle rather than a single recipe, chiaroscuro underlies academic value study, cinematic lighting design and photographic low-key work.",
    "col": [{"h": "#F4EFE4", "n": "Lit white"}, {"h": "#C9B08A", "n": "Golden halftone"}, {"h": "#7A6248", "n": "Mid umber"}, {"h": "#46372A", "n": "Reflected shadow"}, {"h": "#20180F", "n": "Core dark"}],
    "m": ["Toned ground ( imprimatura)", "Transparent shadow glazes", "Opaque light passages", "Plaster-cast references", "Controlled single lamp"],
    "tx": ["Smooth value ramps", "Lost-and-found edges", "Glowing light pools"],
    "obj": ["History paintings", "Candlelit interiors", "Portrait studies", "Tonal woodcuts", "Cast drawings"],
    "ex": ["Leonardo, Virgin of the Rocks", "Rembrandt, The Night Watch (1642)", "Georges de La Tour, The Penitent Magdalene", "Ugo da Carpi, chiaroscuro woodcuts"],
    "rel": ["Sfumato", "Tenebrism", "Grisaille monochrome", "Wood engraving"],
    "par": "",
    "var": ["Candlelight chiaroscuro", "Chiaroscuro woodcut (color-block tonal print)"],
    "cf": ["Tenebrism (darkness dominates there)", "Sfumato (edge dissolution)"],
    "src": [
      {"n": "Wikipedia: Chiaroscuro", "u": "https://en.wikipedia.org/wiki/Chiaroscuro", "t": "B"},
      {"n": "The National Gallery, London", "u": "https://www.nationalgallery.org.uk", "t": "A"}
    ],
    "tg": ["light logic", "value", "modeling", "rembrandt", "tonal", "academic"],
    "pop": 88,
    "niche": false,
    "vd": {"shape": "Volumetric solids carved by light", "line": "Line subordinated to value mass", "composition": "Light planned as narrative structure", "texture": "Soft gloss-to-shadow continuum", "forms": "Fully dimensional, sculptural"},
    "typ": {"display": "Cormorant Garamond", "body": "Crimson Text", "notes": "Museum-catalogue serifs keep focus on tonal drama"},
    "lit": {"quality": "One graded source; everything else reflected", "direction": "Single dominant key, often upper side", "temperature": "warm", "shadow": "Transparent, warm, containing reflected light"},
    "ui": {"background": "Warm dark neutral", "surface": "Softly lit panels", "components": "Light-graded elevation steps", "motion": "Key-light pans across surfaces"},
    "rec": {"materials": "Plaster casts, value scales, lamps", "lighting": "Single warm key plus bounce", "objects": "Skull, books, brass lamp", "music": "Bach cello suites", "scent": "Beeswax and lamp oil"},
    "snd": ["Lamp hum", "Soft glaze strokes", "Deep room quiet"],
    "dna": {"mi": 40, "og": 55, "wc": 60, "ns": 10, "ad": 5, "hf": 15, "rr": 40, "ps": 35, "sh": 50, "ql": 35, "oc": 60, "ds": 35, "rs": 60, "eu": 65, "np": 15},
    "emo": {"warm": 60, "cold": 40, "playful": 25, "serious": 80, "chaotic": 25, "ordered": 70, "nostalgic": 55, "futuristic": 20, "peaceful": 45, "ominous": 55}
  },
  {
    "n": "Trompe-l'œil",
    "a": ["Trompe l'oeil", "Deceive-the-eye painting", "Illusionistic still life"],
    "cat": "Painting Technique & School",
    "c": "Optical illusion",
    "e": "historical",
    "o": "Greek anecdote (Zeuxis and Parrhasius); matured in 17th-century Netherlands",
    "g": "Netherlands, Italy, France, USA",
    "p": "Antiquity to present; peak 1650-1900",
    "era": "Baroque to Victorian",
    "sum": "Trompe-l'œil paints with such verisimilitude and true scale that flat objects appear physically present - a letter pinned to a board, a boy escaping a frame. Its test is the outstretched hand of the fooled viewer.",
    "desc": "Success requires actual-size objects, razor-sharp focus, exact cast shadows aligned to the room's real light, and shallow or zero perspective depth - unlike grand illusionistic ceilings, which use forced perspective from a fixed station point. Seventeenth-century Dutch painters like Samuel van Hoogstraten pinned letters, scissors and razors onto pale boards; Andrea Pozzo's Sant'Ignazio ceiling extended the idea into architecture (quadratura); Pere Borrell del Caso's Escaping Criticism shows a boy climbing out of his frame, and William Harnett fooled American jury-goers with painted dollar bills. The genre thrives today in street murals and decorative panels.",
    "col": [{"h": "#F2EEE6", "n": "Faux marble white"}, {"h": "#C7C2B4", "n": "Cool board gray"}, {"h": "#8A8577", "n": "Shadow gray"}, {"h": "#6B4F35", "n": "Wood tone"}, {"h": "#A6B6C8", "n": "Ceiling sky"}, {"h": "#57534A", "n": "Cast shadow"}],
    "m": ["Fine sables and miniaturist brushes", "Smooth gesso or mahogany support", "Exact shadow observation", "Mahl stick for detail", "Linear-perspective layout"],
    "tx": ["Impossible smoothness", "Painted cast shadows", "Faux wood and marble grain"],
    "obj": ["Letter-rack panels", "Escaping-figure canvases", "Illusionistic doors and niches", "Ceiling quadratura", "Street-wall murals"],
    "ex": ["Pere Borrell del Caso, Escaping Criticism (1874)", "Andrea Pozzo, Sant'Ignazio ceiling (1685-94)", "Samuel van Hoogstraten trompe-l'œil still lifes", "William Harnett, After the Hunt (1885)"],
    "inf": ["Chiaroscuro", "Linear perspective tradition", "Grisaille monochrome"],
    "rel": ["Trompe-l'œil Revival", "Anamorphosis", "Dutch Golden Age painting"],
    "par": "",
    "var": ["Quadratura (architectural ceiling illusion)", "Peep-box dioramas", "Faux-finish decorative painting"],
    "cf": ["Anamorphosis (distortion-based)", "Photorealism (camera-mediated rather than eye-true)"],
    "src": [
      {"n": "Wikipedia: Trompe-l'œil", "u": "https://en.wikipedia.org/wiki/Trompe-l%27%C5%93il", "t": "B"},
      {"n": "The Metropolitan Museum of Art", "u": "https://www.metmuseum.org", "t": "A"}
    ],
    "tg": ["illusion", "verisimilitude", "still life", "architecture", "trick", "hyperreal"],
    "pop": 60,
    "niche": false,
    "vd": {"shape": "Actual-size flat objects, edge-on to the viewer", "line": "No visible stroke; seamless finish", "composition": "Frontal, shallow, board-like fields", "texture": "Painted imitations of paper, metal, wood", "forms": "Objects that claim physical presence"},
    "typ": {"display": "Cormorant SC", "body": "EB Garamond", "notes": "Engraved-label lettering style matches painted documents and placards"},
    "lit": {"quality": "Single matched room light, consistent with real cast shadows", "direction": "Aligned with the installation site", "temperature": "warm", "shadow": "Painted cast shadows anchored to real ones"},
    "ui": {"background": "Pinstriped or wood-grain neutral", "surface": "Flat, hyper-crisp", "components": "Fake buttons and paper tabs that look graspable", "motion": "Peel and lift micro-interactions"},
    "rec": {"materials": "Mahogany panel, fine varnish", "lighting": "Site-matched, shadow-consistent", "objects": "Actual letters, combs and razors as reference props", "music": "Harpsichord wit, baroque capriccios", "scent": "Varnish and old paper"},
    "snd": ["Paper rustle", "Frame knock", "Stunned-room hush"],
    "dna": {"mi": 55, "og": 45, "wc": 55, "ns": 10, "ad": 5, "hf": 15, "rr": 30, "ps": 55, "sh": 35, "ql": 35, "oc": 70, "ds": 50, "rs": 70, "eu": 70, "np": 20},
    "emo": {"warm": 55, "cold": 45, "playful": 70, "serious": 45, "chaotic": 20, "ordered": 80, "nostalgic": 55, "futuristic": 20, "peaceful": 40, "ominous": 25}
  },
  {
    "n": "Gouache Illustration",
    "a": ["Body color", "Opaque watercolour", "Gouache painting", "Poster gouache"],
    "cat": "Painting Technique & School",
    "c": "Water-based media",
    "e": "historical",
    "o": "Renaissance manuscript augmentation; 19th-20th-century commercial and design studio",
    "g": "Europe, USA, Japan",
    "p": "16th century to present; golden age 1920-1970",
    "era": "Modern",
    "sum": "Gouache is opaque watercolor - pigment loaded with chalk or white - that dries fast to flat, velvety, light-reflecting films. It powered mid-century posters, animation backgrounds and Matisse's cut-outs.",
    "desc": "Because added white gives opacity, gouache covers mistakes, sits above underlying layers and blocks in solid shape without needing the white of paper to glow, which makes it ideal for design: hard edges, uniform fields, and reworkable passages. It was the studio workhorse of advertising art, theater design and film animation backgrounds, and Cassandre-style posters and mid-century children's books live on its matte flatness. Matisse cut his late compositions from paper he had painted in gouache (papiers decoupes), and contemporary flat-design illustration revives the look digitally. Its chalky matte body is instantly recognizable against glossy oils or transparent washes.",
    "col": [{"h": "#F6F2E7", "n": "Paper white"}, {"h": "#E8613C", "n": "Tomato red"}, {"h": "#F2C94C", "n": "Mustard yellow"}, {"h": "#4E7D7B", "n": "Muted teal"}, {"h": "#E9B44C", "n": "Naples gold"}, {"h": "#2B2B2B", "n": "Design ink"}],
    "m": ["Gouache tubes or cakes", "Chalk/whiting extenders", "Hot-pressed board", "Sable and synthetic rounds", "Ceramic mixing dishes", "Masking tape"],
    "tx": ["Flat velvety matte", "Chalky opacity", "Crisp cut-paper edges"],
    "obj": ["Poster art", "Animation backgrounds", "Children's book spreads", "Fashion and design croquis", "Cut-out paper collages"],
    "ex": ["Henri Matisse, The Snail (gouache cut-outs, 1953)", "Marc Chagall gouaches", "J.M.W. Turner gouache studies on tinted paper", "Mid-century film animation backgrounds"],
    "rel": ["Watercolor tradition", "Swiss International Style", "Corporate Memphis", "Polish poster school"],
    "par": "",
    "var": ["Gouache decoupee (painted-paper cut-out)", "Design-gouache marker rendering"],
    "cf": ["Transparent watercolor", "Tempera", "Poster paint"],
    "src": [
      {"n": "Wikipedia: Gouache", "u": "https://en.wikipedia.org/wiki/Gouache", "t": "B"},
      {"n": "Victoria and Albert Museum", "u": "https://www.vam.ac.uk", "t": "A"}
    ],
    "tg": ["opaque", "flat color", "design", "illustration", "matte", "mid-century"],
    "pop": 64,
    "niche": false,
    "vd": {"shape": "Solid, cleanly outlined color shapes", "line": "Contour either inked or left as edge", "composition": "Poster logic: hierarchy, negative space, flat depth", "texture": "Uniform matte with faint chalk drag", "forms": "Simplified, iconic, reworkable"},
    "fnt": {"display": "Futura", "body": "Georgia", "notes": "Futura is the canonical geometric face of the gouache poster era"},
    "lit": {"quality": "Even, shadowless key light", "direction": "Frontal", "temperature": "warm", "shadow": "Simplified graphic shapes"},
    "ui": {"background": "Warm paper cream", "surface": "Matte chalk finish", "components": "Flat-color buttons, offset hard shadows", "motion": "Cut-paper slide and snap transitions"},
    "rec": {"materials": "Gouache jars, sable rounds, layout board", "lighting": "Studio daylight flats", "objects": "Painting trays, T-squares, color-aid swatches", "music": "Jazz-age swing, bossa nova", "scent": "Chalky paint and fresh paper"},
    "snd": ["Wet brush drag", "Jar clink", "Ruler snap on board"],
    "dna": {"mi": 60, "og": 45, "wc": 55, "ns": 20, "ad": 25, "hf": 35, "rr": 40, "ps": 55, "sh": 30, "ql": 40, "oc": 55, "ds": 55, "rs": 45, "eu": 55, "np": 40},
    "emo": {"warm": 65, "cold": 35, "playful": 65, "serious": 35, "chaotic": 30, "ordered": 70, "nostalgic": 65, "futuristic": 35, "peaceful": 55, "ominous": 15}
  },
  {
    "n": "Gongbi",
    "a": ["Gong-bi", "Kung-pi", "Meticulous brush painting", "Fine-brush painting"],
    "cat": "Painting Technique & School",
    "c": "East Asian brush",
    "e": "regional_tradition",
    "o": "Imperial Chinese court painting, Tang-Song academies",
    "g": "China; Qing court and East Asian dissemination",
    "p": "c. 700 CE to present; Song dynasty apogee 960-1279",
    "era": "Imperial China",
    "sum": "Gongbi is Chinese meticulous brush painting: razor-fine ink outlines filled with graded mineral-pigment washes on silk. Emperor Huizong's parakeets and Qiu Ying's handscrolls exemplify its patient, jeweled precision.",
    "desc": "The painter first draws baimiao - hairline ink contours of a bird's feather rows or a flower's veins - with an upright, pressure-controlled brush, then floods even washes of malachite, azurite, cinnabar or gamboge between the lines, building dozens of layers over silk sized with alum. The result is exact to the point of taxonomy: Song bird-and-flower albums record species, plumage and petal count, yet stay lyrical through idealized spacing and breathing negative space. Huizong's Five-Colored Parakeet (1112) carries his瘦金-style inscription, Ming master Qiu Ying perfected the manner, and Jesuit court painter Giuseppe Castiglione (Lang Shining) fused it with European shading in the 18th century.",
    "col": [{"h": "#F1E9D7", "n": "Sized silk"}, {"h": "#1A1A1A", "n": "Ink line"}, {"h": "#B03A2E", "n": "Cinnabar"}, {"h": "#446CA3", "n": "Azurite"}, {"h": "#2F6B4F", "n": "Malachite"}, {"h": "#C9A227", "n": "Gamboge gold"}],
    "m": ["Alum-sized silk", "Ink stick and inkstone", "Fine wolf-hair detail brushes", "Mineral pigments (azurite, malachite, cinnabar)", "Bone-glue binder", "Bamboo brush rest"],
    "tx": ["Hairline ink contour", "Layered mineral wash", "Silk weave visible through thin color"],
    "obj": ["Bird-and-flower album leaves", "Court handscrolls", "Figure paintings", "Fan paintings", "Palace commissions"],
    "ex": ["Emperor Huizong, Five-Colored Parakeet (1112)", "Qiu Ying handscrolls (Ming)", "Giuseppe Castiglione (Lang Shining) court paintings"],
    "inf": ["Baimiao line drawing", "Calligraphic brush training", "Court academy practice"],
    "rel": ["Sumi-e ink wash painting", "Literati Painting", "Mughal Painting", "Nihonga"],
    "par": "East Asian brush painting",
    "var": ["Gongbi chongcai (heavy mineral color)", "Baimiao (unpainted line-only)"],
    "cf": ["Xieyi (freehand expressive brush)", "Ukiyo-e"],
    "src": [
      {"n": "Wikipedia: Gongbi", "u": "https://en.wikipedia.org/wiki/Gongbi", "t": "B"},
      {"n": "Google Arts & Culture", "u": "https://artsandculture.google.com", "t": "A"}
    ],
    "tg": ["silk", "meticulous", "court art", "chinese", "mineral pigment", "fine line"],
    "pop": 42,
    "niche": false,
    "vd": {"shape": "Species-exact silhouettes on open silk", "line": "Uniform hairline contour, pressure-graded", "composition": "Asymmetric balance with generous empty silk", "texture": "Glassy mineral layers over weave", "forms": "Feather-perfect detail, idealized posture"},
    "fnt": {"display": "Noto Serif SC", "body": "Noto Sans SC", "notes": "CJK serif honors inscription calligraphy alongside paintings"},
    "lit": {"quality": "Diffuse north-window light on silk", "direction": "Even, shadowless", "temperature": "cool", "shadow": "Minimal; internal ink gradations instead"},
    "env": {"places": "Court ateliers, garden studios, scholar studies", "weather": "Still indoor air to protect silk sizing"},
    "ui": {"background": "Silk cream", "surface": "Fine weave texture", "components": "Seal-red accents, vertical title strips", "motion": "Handscroll horizontal panning"},
    "rec": {"materials": "Silk, inkstone, pigment dishes", "lighting": "Soft daylight from the north", "objects": "Brush racks, seals, red paste", "music": "Guqin solo, Jiangnan sizhu", "scent": "Ink stick, sizing glue, osmanthus"},
    "snd": ["Fine brush tip tick", "Inkstone grinding", "Silk glide"],
    "dna": {"mi": 65, "og": 60, "wc": 50, "ns": 15, "ad": 5, "hf": 10, "rr": 30, "ps": 30, "sh": 25, "ql": 15, "oc": 75, "ds": 65, "rs": 50, "eu": 80, "np": 20},
    "emo": {"warm": 45, "cold": 55, "playful": 25, "serious": 75, "chaotic": 10, "ordered": 90, "nostalgic": 70, "futuristic": 15, "peaceful": 75, "ominous": 20}
  },
  {
    "n": "Ink Wash Painting",
    "a": ["Sumi-e", "Suibokuga", "Shuimohua", "Brush ink painting"],
    "cat": "Painting Technique & School",
    "c": "East Asian brush",
    "e": "regional_tradition",
    "o": "Tang dynasty China; transmitted to Zen Japan as sumi-e",
    "g": "China, Japan, Korea, Vietnam",
    "p": "8th century to present; Japanese peak 14th-16th centuries",
    "era": "Medieval East Asia",
    "sum": "Ink wash painting builds entire images from black sumi ink's five tonalities, using water-loaded brushwork on absorbent paper. Sesshu's splashed-ink landscapes and Tōhaku's pine screens distill the world into breath and stroke.",
    "desc": "Grinding an ink stick on a wet stone yields a ink whose dilution ladder - from dry burnt-black to pale mist - is called the five colors; the painter must place each stroke once, because absorbent paper forgives nothing. Composition privileges emptiness: a few angled branches, graded mountain masses dissolving into unworked paper, and the calligraphic body mechanics shared with writing. Zen monks carried the mode from Song China to Japan, where Sesshu Toyo's haboku (splashed-ink) landscapes and Hasegawa Tohaku's Pine Trees screens became national icons; Xu Beihong's galloping horses and Qi Baishi's shrimp show its 20th-century life.",
    "col": [{"h": "#F5F1E6", "n": "Washi paper"}, {"h": "#191713", "n": "Full-sumi black"}, {"h": "#55534E", "n": "Mid ink gray"}, {"h": "#8A877F", "n": "Pale wash"}, {"h": "#C8C4B8", "n": "Fog wash"}, {"h": "#B0312D", "n": "Seal vermilion"}],
    "m": ["Ink stick and grinding stone", "Bamboo brushes (various resilience)", "Absorbent xuan or washi paper", "Water dropper", "Felt blotting underlay", "Cinnabar seal paste"],
    "tx": ["Bleeding wet wash", "Flying-white dry brush", "Granulated ink pooling", "Empty-paper mist"],
    "obj": ["Hanging scrolls (kakemono)", "Handscrolls", "Folding screens", "Zen circle (enso) sheets", "Album leaves"],
    "ex": ["Sesshu Toyo, haboku landscape (1495)", "Hasegawa Tohaku, Pine Trees screen (16th c.)", "Xu Beihong galloping horses", "Qi Baishi shrimp studies"],
    "inf": ["Calligraphy", "Chan/Zen aesthetics", "Literati Painting"],
    "rel": ["Gongbi", "Wabi-sabi", "Nihonga", "New Ink Art"],
    "par": "East Asian brush painting",
    "var": ["Haboku (splashed ink)", "Hatsuboku (flung ink)", "Bokuseki-adjacent Zen brushwork"],
    "cf": ["Gongbi (meticulous, layered)", "Chinese calligraphy proper"],
    "src": [
      {"n": "Wikipedia: Ink wash painting", "u": "https://en.wikipedia.org/wiki/Ink_wash_painting", "t": "B"},
      {"n": "The Metropolitan Museum of Art", "u": "https://www.metmuseum.org", "t": "A"}
    ],
    "tg": ["sumi ink", "zen", "monochrome", "east asian", "gesture", "negative space"],
    "pop": 62,
    "niche": false,
    "vd": {"shape": "Reduced silhouettes inside large voids", "line": "Calligraphic stroke with pressure flare", "composition": "Emptiness as subject; one-corner asymmetry", "texture": "Feathered bleed and dry-brush skip", "forms": "Suggested atmospherics over explicit detail"},
    "fnt": {"display": "Yu Mincho", "body": "Noto Serif JP", "notes": "Mincho faces echo brush-derived CJK print typography"},
    "lit": {"quality": "Soft paper-diffused daylight", "direction": "Unspecified ambient", "temperature": "cool", "shadow": "Ink tonality replaces shadow"},
    "env": {"places": "Temple rooms, tea huts, mountain hermitages", "weather": "Mist, rain, snow - the painter's tonal allies"},
    "ui": {"background": "Warm paper white", "surface": "Fiber-grain texture", "components": "Ink-stroke dividers, seal-red markers", "motion": "Single-stroke draw-on animations"},
    "rec": {"materials": "Ink stone, washed brushes, rolled paper", "lighting": "Shoji-diffused daylight", "objects": "Scroll weights, seal, brush hanger", "music": "Shakuhachi honkyoku, guqin", "scent": "Pine-soot ink and tatami"},
    "snd": ["Single stroke exhale", "Water drop into suzuri", "Distant temple bell"],
    "dna": {"mi": 90, "og": 75, "wc": 45, "ns": 15, "ad": 5, "hf": 10, "rr": 45, "ps": 25, "sh": 25, "ql": 10, "oc": 35, "ds": 90, "rs": 55, "eu": 70, "np": 30},
    "emo": {"warm": 40, "cold": 60, "playful": 20, "serious": 65, "chaotic": 25, "ordered": 55, "nostalgic": 60, "futuristic": 20, "peaceful": 90, "ominous": 25}
  },
  {
    "n": "Divisionism",
    "a": ["Chromoluminarism", "Divisionist technique", "Neo-impressionist brushwork"],
    "cat": "Painting Technique & School",
    "c": "Optical color",
    "e": "historical",
    "o": "Paris, 1884-1886, by Georges Seurat and Paul Signac",
    "g": "France, Belgium, Italy",
    "p": "1884-1910",
    "era": "Late 19th century",
    "sum": "Divisionism applies pigment in small separated strokes of pure color intended to blend optically in the eye rather than on the palette, systematized from contemporary color science by Seurat and Signac.",
    "desc": "Grounded in Chevreul's simultaneous-contrast law and Ogden Rood's Modern Chromatics, the divisionist lays complementary and adjacent hues side by side - dot by measured dot in Seurat's pointille, comma-like strokes in Signac - so additive mixing in the retina yields luminosity impossible from stirred mud. A Sunday on La Grande Jatte took two years of studies and repainting to calibrate; Signac's Mediterranean sails, Henri-Edmond Cross's shimmering coastlines and Italian divisionists like Pellizza da Volpedo carried the method forward. Though often conflated with Pointillism (its dot-based branch), divisionism names the optical-mixing principle, with contrasts of hue, tone and line mapped almost musically.",
    "col": [{"h": "#F2E14C", "n": "Optical yellow"}, {"h": "#7FB2E5", "n": "Aerial blue"}, {"h": "#E86A4E", "n": "Complementary orange"}, {"h": "#7A4E8C", "n": "Cobalt violet"}, {"h": "#4C8C5A", "n": "Emerald green"}, {"h": "#F5E9D0", "n": "Sunlit ground"}],
    "m": ["Zinc and lead whites", "Pure spectrum pigments", "Small fine brushes", "Color wheel and Rood's Modern Chromatics", "Pre-mixed value strings"],
    "tx": ["Woven dot-fabric surface", "Shimmering optical vibration", "Uniform granular grain"],
    "obj": ["Monumental figure compositions", "Mediterranean seascapes", "Anarchist-labor canvases", "Color-theory studies"],
    "ex": ["Georges Seurat, A Sunday on La Grande Jatte (1884-86)", "Paul Signac, Mediterranean harbors", "Henri-Edmond Cross coastal paintings", "Giuseppe Pellizza da Volpedo, The Fourth Estate (1901)"],
    "inf": ["Impressionism", "Chevreul color science", "Contemporary optics (Ogden Rood)"],
    "rel": ["Pointillism", "Fauvism", "Impressionism", "Plein air painting"],
    "par": "",
    "var": ["Pointille dot application (Pointillism)", "Italian divisionism (Pellizza, Segantini)"],
    "cf": ["Pointillism (dot technique as distinct branch)", "Pixel art (digital, grid-locked)"],
    "src": [
      {"n": "Wikipedia: Divisionism", "u": "https://en.wikipedia.org/wiki/Divisionism", "t": "B"},
      {"n": "The Art Institute of Chicago", "u": "https://www.artic.edu", "t": "A"}
    ],
    "tg": ["optical mixing", "color science", "dots", "seurat", "luminous", "systematic"],
    "pop": 46,
    "niche": false,
    "vd": {"shape": "Forms woven from calibrated stroke textures", "line": "Directional stroke rhythms act as contour", "composition": "Renaissance-stable geometry under shimmering skin", "texture": "Uniform granular weave", "forms": "Solid yet atomized into light"},
    "typ": {"display": "Quicksand", "body": "Lora", "notes": "Friendly geometric display plus bookish serif bridges art and science framing"},
    "lit": {"quality": "High-sun sparkle; light modeled in hue pairs", "direction": "Open-air omnidirectional", "temperature": "warm", "shadow": "Violet-blue complements instead of black"},
    "ui": {"background": "Pale pointille cream", "surface": "Micro-dot texture", "components": "Complementary-pair gradient chips", "motion": "Dot-dissolve transitions"},
    "rec": {"materials": "Study panels, boxed pigment sets", "lighting": "Bright gallery daylight", "objects": "Scientific color charts, monocles, sketchbook studies", "music": "Debussy, early Messiaen color-chords", "scent": "Poplin canvas and turpentine"},
    "snd": ["Rapid dotting taps", "Seine-side ambience", "Park-band polka, far off"],
    "dna": {"mi": 55, "og": 40, "wc": 55, "ns": 15, "ad": 10, "hf": 25, "rr": 35, "ps": 45, "sh": 30, "ql": 30, "oc": 80, "ds": 45, "rs": 55, "eu": 65, "np": 35},
    "emo": {"warm": 65, "cold": 35, "playful": 50, "serious": 50, "chaotic": 20, "ordered": 85, "nostalgic": 55, "futuristic": 30, "peaceful": 65, "ominous": 15}
  },
  {
    "n": "Anamorphosis",
    "a": ["Anamorphic art", "Anamorphose", "Distorted perspective image", "Deceptive perspective"],
    "cat": "Painting Technique & School",
    "c": "Perspective illusion",
    "e": "historical",
    "o": "Renaissance Italy (Leonardo's Codex Atlanticus) and 16th-century Germany",
    "g": "Europe; cylinder anamorphosis spread to China and Japan",
    "p": "c. 1480 to present",
    "era": "Renaissance to Contemporary",
    "sum": "Anamorphosis distorts an image so it resolves only from one vantage point or in a curved mirror - most famously Holbein's stretched skull in The Ambassadors. It weaponizes perspective against casual seeing.",
    "desc": "The maker computes a projection grid - oblique, catoptric (mirror), or mathematical - then paints the subject through it, so from most angles the canvas shows abstract smear while the chosen viewpoint reconstructs the form. Holbein's Ambassadors (1533) floats a memento mori skull across its floor; Erhard Schön printed secret portraits for Reformation pamphlets; 17th-century cylinder anamorphoses needed polished cones to unscramble courtly puzzles. Modern heirs include Julian Beever and Edgar Mueller's pavement illusions, which realign a whole street's sidewalk perspective for a single camera position.",
    "col": [{"h": "#E8E2D2", "n": "Aged paper"}, {"h": "#7A6248", "n": "Brown wash"}, {"h": "#3B352C", "n": "Sepia ink"}, {"h": "#C9B88F", "n": "Ochre ground"}, {"h": "#9A9284", "n": "Smear gray"}],
    "m": ["Perspective grids and vantage templates", "Polished cylinder mirror (catoptric)", "Chalk and pastel for pavement work", "Ink and wash", "Fixed viewpoint scaffold"],
    "tx": ["Stretched smear at oblique angles", "Snapping clarity at the true viewpoint", "Grid-derived distortion"],
    "obj": ["Double-view portraits", "Secret courtly images", "Cylinder-mirror puzzles", "3D pavement art", "Signage and branding stunts"],
    "ex": ["Hans Holbein, The Ambassadors (1533)", "Erhard Schön anamorphic woodcuts", "Julian Beever and Edgar Mueller pavement illusions"],
    "inf": ["Linear perspective tradition", "Trompe-l'œil", "Optics and catoptrics"],
    "rel": ["Trompe-l'œil", "Camera obscura", "Glitch Art"],
    "par": "",
    "var": ["Oblique anamorphosis", "Mirror (catoptric) anamorphosis", "3D pavement anamorphosis"],
    "cf": ["Perspective painting proper", "Trompe-l'œil (no distortion required)"],
    "src": [
      {"n": "Wikipedia: Anamorphosis", "u": "https://en.wikipedia.org/wiki/Anamorphosis", "t": "B"},
      {"n": "The National Gallery, London", "u": "https://www.nationalgallery.org.uk", "t": "A"}
    ],
    "tg": ["perspective trick", "hidden image", "optical", "skull", "street art", "viewpoint"],
    "pop": 44,
    "niche": false,
    "vd": {"shape": "Twisting distortion resolved by stance", "line": "Grid-warped contours", "composition": "Two compositions in one surface", "texture": "Smooth so distortion stays legible", "forms": "Leap from abstraction to figure at one angle"},
    "typ": {"display": "Monoton", "body": "Inter", "notes": "Contemporary sans keeps focus on the perceptual game"},
    "lit": {"quality": "Flat, uniform; distortion is the star", "direction": "Ambient", "temperature": "cool", "shadow": "Aligned to the single correct viewpoint"},
    "ui": {"background": "Neutral field", "surface": "Grid overlay toggles", "components": "Viewpoint markers, lens-peg icons", "motion": "Camera-orbit reveals"},
    "rec": {"materials": "Chalk, tape, printed grids", "lighting": "Even overcast for pavement pieces", "objects": "Mirror cones, camera tripod at sweet spot", "music": "Minimal electronics, bell patterns", "scent": "Wet pavement chalk"},
    "snd": ["Lens focus seek", "Step-back gasp", "Chalk scratch"],
    "dna": {"mi": 55, "og": 45, "wc": 45, "ns": 15, "ad": 30, "hf": 40, "rr": 35, "ps": 65, "sh": 35, "ql": 45, "oc": 55, "ds": 45, "rs": 75, "eu": 55, "np": 50},
    "emo": {"warm": 45, "cold": 55, "playful": 75, "serious": 40, "chaotic": 45, "ordered": 60, "nostalgic": 35, "futuristic": 55, "peaceful": 35, "ominous": 45}
  },
  {
    "n": "Blind Contour Drawing",
    "a": ["Pure contour drawing", "Blind-line exercise", "No-look contour"],
    "cat": "Drawing & Line Work",
    "c": "Observational drawing",
    "e": "historical",
    "o": "American art pedagogy, 1920s-1940s",
    "g": "USA, then art schools worldwide",
    "p": "c. 1920s to present",
    "era": "Modern",
    "sum": "Blind contour drawing traces a subject's edges while watching only the subject, never the paper, training eye-hand sync and producing delightfully distorted, wiry lines. Kimon Nicolaides institutionalized it in The Natural Way to Draw.",
    "desc": "The artist fixes gaze on the model or object and moves the pen as though the point were touching the observed contour, climbing every bump at the speed of sight without lifting or checking; because the hand receives no visual correction, the result is a trembling, headless, often hilarious anatomy whose distortions record duration and attention rather than likeness. Nicolaides' 1941 textbook made it the first exercise of modern drawing pedagogy, Betty Edwards' Drawing on the Right Side of the Brain carried it to millions, and Egon Schiele-adjacent and contemporary illustrators deliberately exhibit blind-contour distortion as expressive style. It is a warm-up, a meditation, and an aesthetic in its own right.",
    "col": [{"h": "#F4EFE2", "n": "Sketch paper"}, {"h": "#14140F", "n": "Fountain ink"}, {"h": "#2B4A9B", "n": "Ballpoint blue"}, {"h": "#4A4A48", "n": "Graphite gray"}],
    "m": ["Fountain or ballpoint pen", "Cheap loose sketch paper", "Egg timer for timed sets", "Model or still life"],
    "tx": ["Wiry searching line", "Overlapping doubling", "Pressure wobble"],
    "obj": ["Sketchbook pages", "Timed exercise sheets", "Studio warm-ups", "Gallery-style blind portrait series"],
    "ex": ["Kimon Nicolaides, The Natural Way to Draw (1941)", "Betty Edwards, Drawing on the Right Side of the Brain (1979)", "Contemporary blind-contour portrait commissions"],
    "inf": ["Contour drawing", "Gesture drawing"],
    "rel": ["One-line drawing", "Continuous line drawing", "Sketchbook culture"],
    "par": "Observational drawing",
    "var": ["Modified blind contour (glancing checks)", "Timed blind gesture"],
    "cf": ["Contour drawing (looking allowed)", "Scribble drawing"],
    "src": [
      {"n": "Wikipedia: Blind contour drawing", "u": "https://en.wikipedia.org/wiki/Blind_contour_drawing", "t": "B"},
      {"n": "The Museum of Modern Art", "u": "https://www.moma.org", "t": "A"}
    ],
    "tg": ["exercise", "sketchbook", "line", "pedagogy", "distortion", "observational"],
    "pop": 45,
    "niche": false,
    "vd": {"shape": "Elastic distorted likenesses", "line": "Single unbroken searching thread", "composition": "Centered, loose, accidentally abstract", "texture": "Tremorous ink track", "forms": "Peculiar but structurally informed"},
    "typ": {"display": "Caveat", "body": "Karla", "notes": "Handwritten display fonts mirror the drawn-line identity"},
    "lit": {"quality": "Flat studio daylight", "direction": "Ambient", "temperature": "cool", "shadow": "None; line only"},
    "ui": {"background": "Paper white", "surface": "Faint tooth texture", "components": "Pen-path line animations", "motion": "Real-time stroke replay"},
    "rec": {"materials": "Stacks of copy paper, pens", "lighting": "Even desk lamp", "objects": "Timers, mirrors, potted plants as subjects", "music": "Lo-fi beats, quiet metronome", "scent": "Fresh ink"},
    "snd": ["Pen scratch cadence", "Timer ding", "Sketchbook flip"],
    "dna": {"mi": 75, "og": 70, "wc": 45, "ns": 15, "ad": 15, "hf": 30, "rr": 60, "ps": 65, "sh": 20, "ql": 25, "oc": 40, "ds": 55, "rs": 60, "eu": 30, "np": 45},
    "emo": {"warm": 55, "cold": 45, "playful": 75, "serious": 30, "chaotic": 55, "ordered": 35, "nostalgic": 40, "futuristic": 25, "peaceful": 60, "ominous": 15}
  },
  {
    "n": "One-Line Drawing",
    "a": ["Single line drawing", "One-line art", "Unbroken line drawing", "Monoline figure"],
    "cat": "Drawing & Line Work",
    "c": "Line economy",
    "e": "historical",
    "o": "Modernist Europe; popularized by Picasso's single-stroke works",
    "g": "France, worldwide design culture",
    "p": "c. 1907 to present",
    "era": "Modern",
    "sum": "One-line drawing reduces a subject to a single unbroken pencil or brush line that never lifts from the paper, finding the minimum path that still says horse, camel or face. Picasso's animal lithographs are the touchstones.",
    "desc": "Practitioners plan an economy of route - every edge does double duty as contour and feature - then commit in one confident pass, since erasure would betray the form; the best examples leave elegant overlaps where the path crosses itself, reading as both drawing and diagram. Picasso's late animal sketches (The Dog, the camel) distilled volumes into a dozen centimeters of continuous ink, Jean Cocteau's profile drawings decorated books and walls, and Alexander Calder translated the same economy into wire portraits that hang as line in space. The style's modern descendants span logos, tattoos and social-media illustration, all trading on its instant, self-assured elegance.",
    "col": [{"h": "#F6F1E4", "n": "Ivory paper"}, {"h": "#1A1A17", "n": "Sable ink"}, {"h": "#26489C", "n": "Ballpoint blue"}, {"h": "#C43A31", "n": "Fineliner red"}],
    "m": ["Ink pen or soft pencil", "Smooth bristol paper", "Preliminary thumbnails", "Optional brush and ink"],
    "tx": ["Continuous flowing stroke", "Confident pressure swell", "Clean overlap crossings"],
    "obj": ["Animal and face sketches", "Logo marks", "Tattoo stencils", "Wire line sculptures", "Editorial spot art"],
    "ex": ["Pablo Picasso, The Dog (Le chien)", "Jean Cocteau line drawings", "Alexander Calder single-line wire portraits"],
    "inf": ["Contour drawing", "Modernist reduction"],
    "rel": ["Blind Contour Drawing", "Ligne claire", "Wire sculpture"],
    "par": "Line-based drawing",
    "var": ["Continuous single-line portraits", "Closed-loop one-line logos"],
    "cf": ["Blind contour (accidental vs planned economy)"],
    "src": [
      {"n": "Wikipedia (search): one-line drawing", "u": "https://en.wikipedia.org/wiki/Special:Search?query=one-line+drawing", "t": "B"},
      {"n": "Musee Picasso Paris", "u": "https://www.museepicassoparis.fr", "t": "A"}
    ],
    "tg": ["minimal", "single stroke", "logo", "elegant", "modern", "line art"],
    "pop": 52,
    "niche": false,
    "vd": {"shape": "Silhouette reduced to one path", "line": "The entire identity; unbroken and fluid", "composition": "Centered, breathing white space", "texture": "Uniform ink body", "forms": "Iconic minimum with witty overlaps"},
    "typ": {"display": "Josefin Sans", "body": "Karla", "notes": "Light geometric sans parallels the thin continuous stroke"},
    "lit": {"quality": "Flat even light", "direction": "Ambient", "temperature": "cool", "shadow": "None"},
    "ui": {"background": "Off-white", "surface": "Ultra-clean", "components": "Stroke-draw icon set, one-accent color", "motion": "SVG line-draw on load"},
    "rec": {"materials": "Fineliners, bristol, light table", "lighting": "Even studio white", "objects": "Plan sheets, test pens, framing stock", "music": "Erik Satie, minimalist piano", "scent": "Paper and ink"},
    "snd": ["One long pen glide", "Page turn", "Quiet room"],
    "dna": {"mi": 90, "og": 60, "wc": 45, "ns": 15, "ad": 25, "hf": 45, "rr": 40, "ps": 55, "sh": 15, "ql": 15, "oc": 60, "ds": 70, "rs": 55, "eu": 80, "np": 45},
    "emo": {"warm": 50, "cold": 50, "playful": 60, "serious": 40, "chaotic": 20, "ordered": 70, "nostalgic": 35, "futuristic": 50, "peaceful": 70, "ominous": 10}
  },
  {
    "n": "Stippling",
    "a": ["Stipple drawing", "Dot work", "Stipple engraving (print branch)"],
    "cat": "Drawing & Line Work",
    "c": "Tone systems",
    "e": "historical",
    "o": "Copperplate printmaking (18th-century stipple engravers) and pen-and-ink practice",
    "g": "Europe, USA",
    "p": "c. 1750 to present",
    "era": "18th century to Contemporary",
    "sum": "Stippling builds tone entirely from dots whose density alone creates value, producing soft, granular, museum-grade shading without any line. Bartolozzi's stipple engravings and Seurat's conté drawings anchor the tradition.",
    "desc": "The artist probes thousands of individual touches - pen points, engraving needles or even curved rocker tools in printmaking - packing them tight for shadow and scattering them into paper-white breath for light; because no two dots connect, edges stay fuzzy and textures feel organic, which made the method beloved for botanical and scientific plates where hair, pollen and skin need gentle gradation. Francesco Bartolozzi's 18th-century stipple engravings spread chalky rouge-toned portraits across Europe, the engravers of Gustave Dore's Bible plates used white-line stipple to render smoke and night, and Seurat's conté crayon drawings are effectively giant stipple fields of luminous black.",
    "col": [{"h": "#FBF8F0", "n": "Plate paper"}, {"h": "#17150F", "n": "Ink black"}, {"h": "#4E4A40", "n": "Dense shade"}, {"h": "#8C877B", "n": "Halftone gray"}, {"h": "#B0413E", "n": "Stipple rouge (engraving accent)"}],
    "m": ["Technical pens (0.1-0.3 mm)", "Etching needle and rocker", "Smooth bristol or plate paper", "Magnifier lamp", "Conte crayon (drawing branch)"],
    "tx": ["Granular dot texture", "Soft fuzzed edges", "Tonal gradients without lines"],
    "obj": ["Botanical and anatomical plates", "Portrait stipple engravings", "Scientific illustration", "Editorial dot-and-line spot art"],
    "ex": ["Francesco Bartolozzi stipple engravings", "Gustave Dore Bible plate engravings", "Georges Seurat, conte crayon drawings"],
    "inf": ["Copperplate engraving", "Hatching tone systems"],
    "rel": ["Cross-hatching", "Pointillism", "Halftone printing"],
    "par": "Tone-based drawing",
    "var": ["Stipple engraving (copperplate)", "Micro-point scientific stippling"],
    "cf": ["Pointillism (colored paint, optical mix)", "Halftone (mechanical grid)"],
    "src": [
      {"n": "Wikipedia: Stippling", "u": "https://en.wikipedia.org/wiki/Stippling", "t": "B"},
      {"n": "Victoria and Albert Museum", "u": "https://www.vam.ac.uk", "t": "A"}
    ],
    "tg": ["dots", "tone", "patience", "scientific illustration", "engraving", "monochrome"],
    "pop": 55,
    "niche": false,
    "vd": {"shape": "Soft-edged tonal masses", "line": "Deliberately absent; value only", "composition": "Even, controlled, specimen-centered", "texture": "Fine granulation", "forms": "Gently dimensional, hair-accurate"},
    "typ": {"display": "Baskerville", "body": "Baskerville", "notes": "Baskerville's fine hairlines were born in the same 18th-century plate-printing world"},
    "lit": {"quality": "Neutral, shadow-free clarity", "direction": "Even studio light", "temperature": "cool", "shadow": "Rendered in dot density"},
    "ui": {"background": "Paper white", "surface": "Micro-dot pattern fills", "components": "Dot-density data visualizations", "motion": "Dot-field dissolve"},
    "rec": {"materials": "Pen sets, plate paper, loupe", "lighting": "Magnifier lamp", "objects": "Specimen trays, dot guides, erasers", "music": "Philip Glass minimalism, ticking clocks", "scent": "Ink and eraser dust"},
    "snd": ["Metronome pen taps", "Magnifier lamp hum", "Quiet focus"],
    "dna": {"mi": 70, "og": 55, "wc": 40, "ns": 10, "ad": 10, "hf": 30, "rr": 45, "ps": 40, "sh": 25, "ql": 15, "oc": 85, "ds": 55, "rs": 60, "eu": 70, "np": 30},
    "emo": {"warm": 40, "cold": 60, "playful": 30, "serious": 70, "chaotic": 15, "ordered": 90, "nostalgic": 55, "futuristic": 30, "peaceful": 60, "ominous": 25}
  },
  {
    "n": "Cross-Hatching",
    "a": ["Crosshatch", "Hatched shading", "Multi-direction hatching"],
    "cat": "Drawing & Line Work",
    "c": "Tone systems",
    "e": "historical",
    "o": "15th-century European engraving and drawing",
    "g": "Europe and worldwide print culture",
    "p": "c. 1430 to present",
    "era": "Renaissance to Contemporary",
    "sum": "Cross-hatching shades forms with layers of parallel lines set at crossing angles, letting line spacing and layer count encode value. It is the native language of engraving, etching and classical pen drawing.",
    "desc": "A first pass of parallel strokes sets the lightest tone; successive passes turn 30, 45, then 90 degrees across it, each added layer darkening the mesh until the deepest shadows almost weld into black, while following the form's direction makes surfaces feel turned in space. Durer's Melencolia I wrings every value from an engraving burin's disciplined hatch, Rembrandt's etchings loosen the network into expressive scribble-hatch, and Goya's Los Caprichos show how hatched chaos can carry satire. Because printing presses for centuries reproduced only black ink, hatching became the universal tone system of illustration, manga screentone logic and topographic shading all descend from it.",
    "col": [{"h": "#F7F3E8", "n": "Paper white"}, {"h": "#1B1912", "n": "Ink black"}, {"h": "#D9D2C0", "n": "First-pass tone"}, {"h": "#A69F8F", "n": "Mid hatch"}, {"h": "#6E695C", "n": "Deep mesh"}],
    "m": ["Pen and ink or burin", "Etching needle", "Smooth drawing paper", "Straightedge discipline", "Ruling pen for parallel sets"],
    "tx": ["Woven line mesh", "Directional grooves", "Angle-layered depth"],
    "obj": ["Engravings and etchings", "Pen-and-ink book illustration", "Anatomical and botanical plates", "Manga and comic shading", "Topographic hill-shading"],
    "ex": ["Albrecht Durer, Melencolia I (1514)", "Rembrandt etchings", "Goya, Los Caprichos (1799)"],
    "inf": ["Engraving craft", "Linear perspective value study"],
    "rel": ["Stippling", "Etching", "Wood engraving", "Ligne claire"],
    "par": "Tone-based drawing",
    "var": ["Single-direction hatching", "Scribble hatching", "Contour hatching (lines follow form)"],
    "cf": ["Cross-contour drawing (no value mesh)", "Screentone (mechanical transfer)"],
    "src": [
      {"n": "Wikipedia: Hatching", "u": "https://en.wikipedia.org/wiki/Hatching", "t": "B"},
      {"n": "The Metropolitan Museum of Art", "u": "https://www.metmuseum.org", "t": "A"}
    ],
    "tg": ["line network", "engraving", "value", "printmaking", "craft", "monochrome"],
    "pop": 66,
    "niche": false,
    "vd": {"shape": "Forms built from angled line families", "line": "Parallel discipline as structure", "composition": "Value balanced across mesh density", "texture": "Fabric-like woven tone", "forms": "Directional turning of surfaces"},
    "typ": {"display": "IM Fell English", "body": "Crimson Text", "notes": "Antique book faces suit the engraving-plate heritage"},
    "lit": {"quality": "Neutral clarity", "direction": "Consistent implied key", "temperature": "cool", "shadow": "Encoded in mesh density"},
    "ui": {"background": "Warm paper", "surface": "Fine line-grid texture", "components": "Hatched progress and shadow fills", "motion": "Line-draw layering animations"},
    "rec": {"materials": "Dip pens, burins, plate stock", "lighting": "Even north light", "objects": "Whetstones, hones, magnifier", "music": "Baroque keyboard fugues", "scent": "Ink, metal, resin"},
    "snd": ["Rhythmic pen strokes", "Burin push", "Press roller growl"],
    "dna": {"mi": 60, "og": 45, "wc": 40, "ns": 10, "ad": 10, "hf": 25, "rr": 50, "ps": 35, "sh": 40, "ql": 25, "oc": 80, "ds": 50, "rs": 55, "eu": 65, "np": 30},
    "emo": {"warm": 40, "cold": 60, "playful": 30, "serious": 70, "chaotic": 25, "ordered": 80, "nostalgic": 60, "futuristic": 25, "peaceful": 45, "ominous": 35}
  },
  {
    "n": "Silverpoint",
    "a": ["Metalpoint", "Silver point drawing", "Stylus drawing", "Leadpoint (variant)"],
    "cat": "Drawing & Line Work",
    "c": "Dry drawing media",
    "e": "historical",
    "o": "Medieval Europe; Renaissance workshop staple",
    "g": "Flanders, Italy, Germany; American revival",
    "p": "12th century to 16th century peak; revived 19th-20th centuries",
    "era": "Medieval to Renaissance",
    "sum": "Silverpoint draws with a silver wire on abrasive gessoed ground, leaving pale lines that tarnish over weeks into warm brown-gray. Leonardo's workshop studies and Durer's journey sketchbook are its classics.",
    "desc": "A stylus holding a silver point is stroked across white gesso or bone-dust ground; the metal sheds microscopic particles that read as delicate gray lines incapable of erasure, demanding absolute commitment and a build-up of hatch and crosshatch for tone. Fresh lines brighten, then oxidize to a luminous sepia that gives old sheets their mellow glow, and harder or softer alloys (goldpoint glows warm, leadpoint stays gray) tune the voice. Rogier van der Weyden's workshop portraits, Leonardo's silverpoint studies and Durer's 1520-21 Netherlands sketchbook define the pre-graphite era, while Otto Dix revived metalpoint for fiercely modern portraits.",
    "col": [{"h": "#EADFC6", "n": "Gesso ground"}, {"h": "#C0C3C7", "n": "Fresh silver line"}, {"h": "#84898E", "n": "Tarnished gray"}, {"h": "#F7F3E8", "n": "Highlight white"}, {"h": "#6E5F45", "n": "Aged sepia tarnish"}],
    "m": ["Silver wire in a stylus holder", "Gesso or bone-ash ground", "Prepared paper or panel", "Sandable abrasive underlayers", "Polishing cloth"],
    "tx": ["Hair-fine gray line", "Soft sheen", "Oxidized warm patina"],
    "obj": ["Portrait studies", "Workshop model drawings", "Travel sketchbooks", "Devotional sheets", "Contemporary metalpoint still lifes"],
    "ex": ["Leonardo da Vinci silverpoint studies", "Albrecht Durer, Netherlands journey sketchbook (1520-21)", "Otto Dix metalpoint portraits"],
    "inf": ["Metalpoint workshop training", "Egg tempera panel painting"],
    "rel": ["Cross-hatching", "Silverpoint revival drawing", "Egg Tempera Panel Painting"],
    "par": "Dry drawing media",
    "var": ["Goldpoint (warm tone)", "Leadpoint / black-chalk hybrid"],
    "cf": ["Graphite pencil (erasable, no tarnish)"],
    "src": [
      {"n": "Wikipedia: Metalpoint", "u": "https://en.wikipedia.org/wiki/Metalpoint", "t": "B"},
      {"n": "The National Gallery, London", "u": "https://www.nationalgallery.org.uk", "t": "A"}
    ],
    "tg": ["metalpoint", "renaissance", "delicate line", "tarnish", "gesso", "unerasable"],
    "pop": 40,
    "niche": false,
    "vd": {"shape": "Feather-weight contours on pale ground", "line": "Whisper-fine, cumulative hatching", "composition": "Centered studies, generous margins", "texture": "Gritty ground against smooth metal line", "forms": "Softly modeled, quiet"},
    "typ": {"display": "Cormorant Garamond", "body": "Alegreya", "notes": "Renaissance humanist serifs frame the archival mood"},
    "lit": {"quality": "Raking side light to catch sheen", "direction": "Oblique", "temperature": "cool", "shadow": "Hatch-built, pale"},
    "ui": {"background": "Warm gesso ivory", "surface": "Toothy paper feel", "components": "Hairline rules and tarnish-tone accents", "motion": "Slow oxidize color shifts"},
    "rec": {"materials": "Prepared sheets, styluses, abrasive powder", "lighting": "Soft raking window light", "objects": "Hone stones, wire spools, study casts", "music": "Renaissance lute, organum", "scent": "Chalk, bone ash, silver"},
    "snd": ["Faint metal whisper on tooth", "Stylus tap", "Archive-room silence"],
    "dna": {"mi": 70, "og": 55, "wc": 45, "ns": 10, "ad": 5, "hf": 15, "rr": 35, "ps": 25, "sh": 15, "ql": 10, "oc": 70, "ds": 55, "rs": 50, "eu": 80, "np": 25},
    "emo": {"warm": 50, "cold": 50, "playful": 15, "serious": 85, "chaotic": 10, "ordered": 85, "nostalgic": 70, "futuristic": 15, "peaceful": 65, "ominous": 25}
  },
  {
    "n": "Gyotaku",
    "a": ["Fish printing", "Fish rubbing", "Gyo-taku", "Fish impression print"],
    "cat": "Drawing & Line Work",
    "c": "Nature printing",
    "e": "regional_tradition",
    "o": "Edo-period Japan, c. 1800s, among anglers recording catches",
    "g": "Japan; global nature-print community",
    "p": "c. 1830 to present",
    "era": "Edo Japan",
    "sum": "Gyotaku is Japanese fish printing: sumi ink is brushed onto a real fish, and washi paper is rubbed against it to lift an exact monochrome record. Anglers used it as trophy evidence; museums hang it as art.",
    "desc": "The angler pins a fresh catch on a board, paints it with sumi in graded sweeps that honor scale and fin structure, then lays damp washi over the body and pats from center outward so every scale, gill plate and fin ray registers; peeling the sheet away leaves a mirrored, breathing record signed and often annotated with place, weight and date. Direct method (chokusetsu-ho) uses the cleaned fish itself, indirect method (kansetsu-ho) prints through a paper-thin mold, and the haiku poet Yosa Buson made early examples. Record prints (tairyo-batsu) still hang in fishing households, while contemporary artists extend the practice to crabs, leaves andInstallation-scale marine portraits.",
    "col": [{"h": "#F2EBD9", "n": "Washi sheet"}, {"h": "#191713", "n": "Sumi black"}, {"h": "#6B675E", "n": "Scale gray"}, {"h": "#A63D40", "n": "Seal red accent"}, {"h": "#CFC9BA", "n": "Pale wash gray"}],
    "m": ["Fresh fish specimen", "Sumi ink", "Handmade washi or rice paper", "Soft rubbing pads (tsubaki pads)", "Pins and board", "Artist seal and red paste"],
    "tx": ["Scale-by-scale stipple", "Fin-ray ridges", "Ink pooling in gill curves"],
    "obj": ["Angler record prints (tairyo-batsu)", "Marine species studies", "Gallery fish portraits", "Naturalist teaching sheets"],
    "ex": ["Yosa Buson fish prints (18th c.)", "Edo-period angler record prints", "Contemporary marine-specimen gyotaku exhibitions"],
    "inf": ["Ink wash painting", "Ukiyo-e", "Nature printing"],
    "rel": ["Sumi-e ink wash painting", "Sosaku-hanga", "Mingei"],
    "par": "Relief/nature printing",
    "var": ["Chokusetsu-ho (direct method)", "Kansetsu-ho (indirect mold method)"],
    "cf": ["Leaf-print nature printing", "Ukiyo-e (carved blocks, no specimen)"],
    "src": [
      {"n": "Wikipedia: Gyotaku", "u": "https://en.wikipedia.org/wiki/Gyotaku", "t": "B"},
      {"n": "Google Arts & Culture", "u": "https://artsandculture.google.com", "t": "A"}
    ],
    "tg": ["fish", "rubbing", "japan", "sumi", "naturalist", "trophy"],
    "pop": 46,
    "niche": false,
    "vd": {"shape": "Life-size mirrored specimen silhouette", "line": "Fin rays as drawn structure", "composition": "Single centered animal with calligraphic notes", "texture": "Scale-granular ink body", "forms": "Anatomically exact but softly inked"},
    "fnt": {"display": "Yu Mincho", "body": "Noto Serif JP", "notes": "Mincho matches vertical inscription and seal presentation"},
    "lit": {"quality": "Soft daylight, neutral", "direction": "Ambient studio", "temperature": "cool", "shadow": "None beyond ink gradation"},
    "env": {"places": "Fishing docks, kitchen workshops, print studios", "weather": "Cool air keeps the specimen fresh"},
    "ui": {"background": "Washi cream", "surface": "Fiber texture", "components": "Vertical caption strips, seal-red badges", "motion": "Print-press peel reveal"},
    "rec": {"materials": "Specimen trays, ink dishes, blotting felt", "lighting": "Bright work-table lamp", "objects": "Boards, pins, rubbing pads, measuring tape", "music": "Minyo folk, taiko pulse, distant surf", "scent": "Brine, sumi, kozo paper"},
    "snd": ["Patting rhythm on paper", "Paper peel", "Dock water lap"],
    "dna": {"mi": 60, "og": 80, "wc": 45, "ns": 20, "ad": 5, "hf": 15, "rr": 55, "ps": 45, "sh": 30, "ql": 30, "oc": 45, "ds": 50, "rs": 60, "eu": 55, "np": 30},
    "emo": {"warm": 45, "cold": 55, "playful": 50, "serious": 55, "chaotic": 30, "ordered": 60, "nostalgic": 55, "futuristic": 15, "peaceful": 55, "ominous": 25}
  },
];
