/**
 * Curated wave — Europe regional & folk, deep III (batch c, file 3/3):
 * Iberia, Alps/Carpathians, Balkans, Aegean, Baltic, Celtic fringes, Central Europe.
 * Hand-authored; all real, documented traditions. Companion to wave2-europe-2.ts.
 */
export const WAVE_EUF3: any[] = [
  {
    n: "Catalan castells", a: ["casteller human towers", "colla castellera", "Catalan human towers"],
    cat: "Regional & Cultural Tradition", c: "human tower building", e: "regional_tradition",
    o: "Camp de Tarragona, Catalonia, Spain", g: "Catalonia and Valencia, above all Valls, Tarragona, Vilafranca del Penedès, Terrassa and Barcelona",
    p: "recorded 1712, golden age 1780s-1850s, revival from 1981", era: "early modern to living tradition",
    sum: "Catalan castells are human towers built by competing teams (colles), a fiesta tradition from Camp de Tarragona inscribed by UNESCO in 2010.",
    desc: "Castell literally means castle: hundreds of castellers in coloured shirts, wide black sashes and white trousers assemble tiered human towers crowned by a light child, the enxaneta, who raises four fingers in the senyal. The dense crowd-base, the pinya, cushions falls and braces the tower, while folre, manilles and agulla add upper storeys to famous structures such as the quatre de nou. A tower counts only when dismantled without collapsing — descarregat. First recorded in 1712 and codified by rival Valls teams in the 19th century, the art declined before the post-Franco revival of the 1980s. Gralla shawms and timbal drums drive each attempt, the Concurs de castells at Tarragona draws rival colles, and UNESCO inscribed castells on the Representative List in 2010.",
    col: [{ h: "#1c7c43", n: "colla green shirt" }, { h: "#a02c2c", n: "team crimson" }, { h: "#111111", n: "faixa sash black" }, { h: "#d9c9a8", n: "plaza limestone" }, { h: "#efe6d4", n: "climber white trousers" }],
    m: ["woven faixa sash cloth", "cotton team shirts", "hemispheric safety helmets", "gralla wood shawm"],
    tx: ["tensioned human plait", "sweat-damp cotton", "worn stone flags", "sunlit gravel plaza"],
    obj: ["pinya base ring", "enxaneta topping-out child", "black faixa sashes", "colla banner and pennant", "gralla and timbal band"],
    ex: ["Concurs de castells, Tarraco Arena Plaça, Tarragona", "Diada castellera at Plaça de Sant Jaume during La Mercè, Barcelona", "Castellers de Vilafranca's quatre de deu at the 2015 diada"],
    inf: ["Valencian muixeranga ritual towers", "18th-century dance figures ending in human pyramids"],
    rel: ["Valencian muixeranga", "Catalan sardana circle dance", "correfoc fire runs"],
    par: "Catalan festivity culture", var: ["quatre de nou", "dos de vuit", "torre de vuit", "pilar caminat walking pillar"], cf: ["muixeranga", "Chinese human-pyramid acrobatics"],
    src: [
      { n: "Wikipedia — Castell", u: "https://en.wikipedia.org/wiki/Castell", t: "B" },
      { n: "UNESCO — Castells", u: "https://ich.unesco.org/en/RL/castells-00934", t: "A" },
    ],
    tg: ["catalonia", "human tower", "castellers", "tarragona", "festival"],
    pop: 44, niche: false,
    vd: { shape: "vertically stacked human mass narrowing to a child", line: "plaited diagonal arm-frames", composition: "ring of pinya grounding a slender column", texture: "shirts, sashes and skin in compression", forms: "pyramid, arch of linked arms, topped circle" },
    typ: { display: "condensed poster sans", body: "workhorse grotesque", notes: "fiesta-banner typography with bold numerals for tower grades" },
    fnt: { display: "Anton", body: "Inter", notes: "condensed impact type echoes painted colla banners" },
    lit: { quality: "hard high-contrast Mediterranean", direction: "overhead noon and evening raking side light", temperature: "hot", shadow: "short and sharp under the tower" },
    pho: { approach: "long-lens compression of tower mass against plaza crowds", grade: "warm high-saturation reportage" },
    fash: { silhouettes: "athletic, compressed, uniform", garments: "white trousers, colla-coloured shirts, wide black faixa", acc: "hemispheric helmets for the youngest climbers" },
    env: { places: "gravelled plazas, festes majors, arena plaça", weather: "late-summer heat, dust and sweat" },
    gd: { layout: "vertical poster spine with crowd base", icon: "four-fingered senyal hand" },
    ui: { background: "#d9c9a8", surface: "woven sash texture bands", components: "colla colour swatches and tower-score counters", motion: "rise-and-top-out vertical transitions" },
    rec: { materials: "hemp sash, cotton, limestone", lighting: "hard midday sun filtered by dust", objects: "gralla, timbal drum, colla banner", music: "gralla shawms and pounding timbals", scent: "sweat, dust and festival street food" },
    snd: ["gralla shawm", "timbal drum", "the hushed roar as a tower tops out"],
    dna: { mi: 20, og: 55, wc: 25, ns: 30, ad: 10, hf: 12, rr: 40, ps: 55, sh: 45, ql: 60, oc: 25, ds: 80, rs: 30, eu: 40, np: 45 },
    emo: { warm: 75, cold: 15, playful: 70, serious: 60, chaotic: 45, ordered: 70, nostalgic: 55, futuristic: 20, peaceful: 35, ominous: 25 },
  },
  {
    n: "Sardinian Mamuthones masks", a: ["Mamuthones of Mamoiada", "issohadores ritual pair", "Mamoiada carnival masks"],
    cat: "Regional & Cultural Tradition", c: "ritual carnival masquerade", e: "regional_tradition",
    o: "Mamoiada, Barbagia, central Sardinia", g: "Mamoiada and Sardinian carnival villages such as Ottana and Oristano",
    p: "documented 18th century; roots likely in older pastoral rites", era: "pre-modern folk continuum",
    sum: "In Mamoiada, Sardinia, black-clad Mamuthones weighted with rows of cowbells tread a slow hypnotic step, herded by red-sashed issohadores swinging ropes.",
    desc: "The Mamuthones wear black sheepskins, dark wooden masks with white-ringed eyes, and is carras — saddles of some thirty cowbells whose clanging replaces speech as they shuffle in file with slow, jerking steps. Governing them are the issohadores, in white dress with red sashes, who twirl braided ropes (sa attza) and lightly lasso onlookers in a gesture of capture or protection. Processions come out for Sant'Antonio Abate on 16-17 January and through carnival, ending in communal feasts. Folklorists read the pairing as an agro-pastoral rite: a flock driven by shepherds, or winter bound and led away by spring. Neighbouring Barbagia villages keep kindred masks such as Ottana's boes and merdules, and the Museo delle Maschere Mediterranee in Mamoiada documents the wider Mediterranean mask belt.",
    col: [{ h: "#14100d", n: "hide black" }, { h: "#5b4531", n: "calfskin brown" }, { h: "#a8802f", n: "bell brass" }, { h: "#8d2a24", n: "issohadore red" }, { h: "#ece4d2", n: "linen white" }],
    m: ["black calfskin hides", "lacquered wooden masks", "cast-bronze cowbells", "braided attza rope"],
    tx: ["shaggy hide fringe", "polished bell brass", "dark painted mask wood", "heavy rope braid"],
    obj: ["rows of is carras bells", "dark eye-ringed masks", "red issohadore sashes", "braided ropes and lassos", "sheepskin mantles"],
    ex: ["Mamoiada processions of 16-17 January and carnival Sundays", "Museo delle Maschere Mediterranee, Mamoiada", "Ottana's boes and merdules carnival dance"],
    inf: ["agro-pastoral fertility rites", "Mediterranean chain-mask traditions"],
    rel: ["Sartiglia of Oristano", "Sardinian launeddas music", "Alpine Perchten mask runs"],
    par: "Sardinian carnival", var: ["Issohadores", "boes and merdules of Ottana"], cf: ["Thurpos of Orotelli", "Basque joaldunak bell-wearers"],
    src: [
      { n: "Wikipedia — Mamuthones", u: "https://en.wikipedia.org/wiki/Mamuthones", t: "B" },
      { n: "Wikipedia — Barbagia", u: "https://en.wikipedia.org/wiki/Barbagia", t: "B" },
    ],
    tg: ["sardinia", "mamuthones", "carnival", "mask", "cowbell"],
    pop: 37, niche: false,
    vd: { shape: "slow black file of bell-weighted figures", line: "vertical hide fringes over stepping bodies", composition: "dark mass herded by two white-and-red shepherds", texture: "shaggy hide, brass, lacquer", forms: "mask, bell saddle, rope loop" },
    typ: { display: "archaic inscriptional serif", body: "quiet humanist serif", notes: "museum-label sobriety suits the ritual gravity" },
    fnt: { display: "Cormorant Garamond", body: "Crimson Pro", notes: "old-style serif keeps an ethnographic register" },
    lit: { quality: "low winter sun, smoke-dimmed", direction: "side light raking through hide fringes", temperature: "cold with warm bell brass", shadow: "deep and black-dominant" },
    pho: { approach: "slow-shutter processional studies and frontal portraiture", grade: "desaturated charcoal with brass warmth" },
    fash: { silhouettes: "heavy, layered, animal", garments: "black sheepskins over white shepherd dress", acc: "lacquered masks, bell saddles, red sashes" },
    env: { places: "granite village lanes, Sant'Antonio bonfire squares", weather: "January cold, woodsmoke haze" },
    gd: { layout: "horizontal frieze procession", icon: "eye-ringed mask silhouette" },
    ui: { background: "#14100d", surface: "rope braid and hide textures", components: "brass bell medallions", motion: "slow rhythmic sways on a bell-pulse" },
    rec: { materials: "calfskin, bronze, oak, hemp", lighting: "bonfire glow against winter dusk", objects: "cowbells, masks, ritual ropes", music: "polyphonic cantu a tenore", scent: "woodsmoke, wool and animal hide" },
    snd: ["thirty cascading cowbells", "muffled shuffling steps", "cantu a tenore voices"],
    dna: { mi: 25, og: 75, wc: 15, ns: 35, ad: 5, hf: 10, rr: 35, ps: 30, sh: 60, ql: 55, oc: 20, ds: 75, rs: 30, eu: 35, np: 40 },
    emo: { warm: 35, cold: 60, playful: 30, serious: 75, chaotic: 30, ordered: 60, nostalgic: 60, futuristic: 5, peaceful: 30, ominous: 60 },
  },
  {
    n: "Walser alpine settlements", a: ["Walser villages", "Walserhaus architecture", "Upper Valais colonization villages"],
    cat: "Architectural Style", c: "high-altitude vernacular settlement", e: "regional_tradition",
    o: "Upper Valais, Switzerland", g: "high valleys of Valais, Grisons, Vorarlberg, Ticino and the Italian Monte Rosa side: Alagna Valsesia, Gressoney, Macugnaga",
    p: "migration from the 11th century; building type persists today", era: "medieval colonization to living vernacular",
    sum: "Walser settlers colonized high Alpine passes from Upper Valais from the eleventh century, raising larch-and-stone hamlets whose houses, granaries and terraces survive above 1,300 metres.",
    desc: "The Walser are Alemannic-speakers who pushed out of the Upper Valais over glaciers and passes from about 1050, clearing and draining high valley floors others found hostile. Their Walserhaus pairs a dry-stone ground floor with larch-timber storeys above, deep eaves, long balconies for drying, and roofs of hand-split stone slabs or larch shingles heavy enough to shrug off mountain snow. Settlements hug avalanche-safe alluvial fans on the sunny side, with terraced rye plots, hay barns, stone bread ovens and stilted granaries detached to starve fire and rats. Isolation preserved Walser German dialects, including the Gressoney and Issime varieties of the Italian valleys, now endangered. Protected ensembles at Alagna Valsesia, Gressoney and Bosco Gurin anchor a living cross-border Walser identity and an ecomuseum economy.",
    col: [{ h: "#8f857a", n: "silvered larch" }, { h: "#5d5a55", n: "stone-slab roof" }, { h: "#5f7a44", n: "hay meadow green" }, { h: "#e8eef0", n: "glacier white" }, { h: "#6e4f35", n: "pine interior brown" }],
    m: ["larch timber", "hand-split stone slabs", "dry-laid gneiss", "hay and rye straw"],
    tx: ["silvered larch grain", "slate-slab scale roofing", "rough gneiss masonry", "worn threshold wood"],
    obj: ["Walserhaus with drying balcony", "stone-slab roof", "stilted granary", "terraced rye plots", "stone bread oven"],
    ex: ["Alagna Valsesia Walser hamlets and ecomuseum", "Gressoney-Saint-Jean Walserhaus ensembles", "Bosco Gurin, Ticino's highest village"],
    inf: ["Alemannic timber building", "medieval high-colonization movement"],
    rel: ["Alpine chalet", "Tyrolean farm vernacular", "hórreo raised granary"],
    par: "Alpine vernacular architecture", var: ["Gressoney Walserhaus", "Formazza Walser houses", "raccard granary"], cf: ["generic Alpine chalet", "Grisons stone house"],
    src: [
      { n: "Wikipedia — Walser", u: "https://en.wikipedia.org/wiki/Walser", t: "B" },
      { n: "Wikipedia — Walser German", u: "https://en.wikipedia.org/wiki/Walser_German", t: "B" },
    ],
    tg: ["walser", "alps", "larch", "valais", "vernacular"],
    pop: 30, niche: true,
    vd: { shape: "clustered gabled hamlet on an alluvial fan", line: "long horizontal balconies under heavy roofs", composition: "houses stacked up the slope with detached barns", texture: "silvered larch over stone", forms: "Walserhaus, stilted granary, oven block" },
    typ: { display: "woodcut-flavoured slab serif", body: "calm sans", notes: "heritage-trail signage tone" },
    fnt: { display: "Bitter", body: "Source Sans Pro", notes: "slab warmth suits timber vernacular" },
    lit: { quality: "thin, brilliant high-altitude light", direction: "morning sun off glacier faces", temperature: "crisp", shadow: "violet and deep in gable shade" },
    pho: { approach: "wides that stack village against glacier backdrop", grade: "cool alpine clarity, low saturation" },
    fash: { silhouettes: "layered, woollen, compact", garments: "loden jackets, linen workwear", acc: "wool shawls, carved wooden combs" },
    env: { places: "stony high lanes, hay meadows, glacier torrents", weather: "foehn wind, sudden mountain storms" },
    gd: { layout: "terraced slope map as hero graphic", icon: "stone-slab roof gable mark" },
    ui: { background: "#e8eef0", surface: "silvered larch panels", components: "slab-roof shingle cards", motion: "slow parallax along the valley axis" },
    rec: { materials: "larch, gneiss, slate, hemp rope", lighting: "high thin sun with lifted blue shadows", objects: "milking pails, bell collars, carved spoons", music: "yodelled jüüzli of the Upper Valais", scent: "hay, resin and cold stone" },
    snd: ["glacier stream", "cowbells on the alp", "wind in the larches"],
    dna: { mi: 45, og: 80, wc: 20, ns: 40, ad: 15, hf: 20, rr: 45, ps: 40, sh: 65, ql: 60, oc: 50, ds: 70, rs: 35, eu: 65, np: 50 },
    emo: { warm: 45, cold: 55, playful: 20, serious: 55, chaotic: 15, ordered: 75, nostalgic: 70, futuristic: 10, peaceful: 75, ominous: 20 },
  },
  {
    n: "Zakopane style", a: ["styl zakopiański", "Witkiewicz style", "Polish highlander style"],
    cat: "Architectural Style", c: "national-romantic timber architecture", e: "historical",
    o: "Zakopane, Podhale, Polish Tatra foothills", g: "Zakopane and Podhale, with echoes across interwar Poland",
    p: "1890s-1910s, revivals into the 1930s", era: "fin-de-siècle national romanticism",
    sum: "The Zakopane style was Stanisław Witkiewicz's 1890s codification of Podhale highlander carpentry into a national Polish architecture, furniture and ornament.",
    desc: "Rejecting imported historicism, painter-architect Stanisław Witkiewicz argued that a nation needs its own style and found it in góral highlander building: steep shingled roofs, deep porches on carved brackets, sun-cross rozety in gables and dense geometric linework. Villa Koliba (1892-94) launched the style and now houses the Museum of Zakopane Style; villa Pod Jedlami refined it; the Sacred Heart chapel at Jaszczurówka (1904-08) translated it into sacred timber. Witkiewicz also designed highland chairs, furniture and interiors, exhibited in Warsaw and Vienna and taken up by Young Poland designers. The style fed interwar Polish applied arts, shaped how the Tatra resort presents itself, and its carved sun-clocks, brackets and swags remain the signature of Zakopane's protected villas today.",
    col: [{ h: "#6b4a2f", n: "adzed wood brown" }, { h: "#7a7268", n: "roof shingle grey" }, { h: "#e9dfc8", n: "cream plaster" }, { h: "#9c3324", n: "highland red" }, { h: "#33566b", n: "Tatra sky blue" }],
    m: ["spruce and larch timber", "wood shingles", "wrought-iron hinges", "hand-carved rosettes"],
    tx: ["hand-adzed planks", "shingle scale", "carved geometric relief", "wrought-iron scrollwork"],
    obj: ["gable rozeta sun-cross", "carved porch brackets", "Witkiewicz highland chair", "shingled tent-roof tower", "embroidered highlander textiles"],
    ex: ["Villa Koliba, now the Museum of Zakopane Style", "Villa Pod Jedlami on Kościeliska Street", "Sacred Heart chapel at Jaszczurówka (1904-08)"],
    inf: ["Podhale highlander carpentry", "Arts and Crafts national-romantic currents"],
    rel: ["Swiss chalet style", "Hungarian Secession folk architecture", "Arts and Crafts movement"],
    par: "National Romantic architecture", var: ["Witkiewicz furniture", "Tatra chapel variant", "interwar highlander revival"], cf: ["generic Alpine chalet", "Polish manor style"],
    src: [
      { n: "Wikipedia — Zakopane Style", u: "https://en.wikipedia.org/wiki/Zakopane_Style", t: "B" },
      { n: "Wikipedia — Stanisław Witkiewicz", u: "https://en.wikipedia.org/wiki/Stanis%C5%82aw_Witkiewicz", t: "B" },
    ],
    tg: ["zakopane", "podhale", "witkiewicz", "timber", "tatras"],
    pop: 36, niche: false,
    vd: { shape: "steep-shingled gables with tent roofs", line: "dense geometric carving bands", composition: "asymmetric villa masses under huge roofs", texture: "adzed wood and shingle scale", forms: "sun-cross rozeta, bracket porch, highland chair" },
    typ: { display: "carved-log display serif", body: "humanist sans", notes: "museum guidebook register" },
    fnt: { display: "Marcellus", body: "Lato", notes: "lapidary display echoes carved lettering" },
    lit: { quality: "crisp mountain light", direction: "low winter sun across gables", temperature: "cold-bright", shadow: "long and blue on snow" },
    pho: { approach: "gable portraits and timber detail studies", grade: "sepia-leaning heritage grade" },
    fash: { silhouettes: "tailored highlander wool", garments: "ciamparka jackets, embroidered waistcoats", acc: "ciupaga shepherd's axes and felt hats" },
    env: { places: "snowy villa lanes, Tatra foothill meadows", weather: "deep snow, mountain sun" },
    gd: { layout: "centered villa elevation on a patterned border", icon: "rozeta sun-cross" },
    ui: { background: "#e9dfc8", surface: "carved plank headers", components: "rosette icon chips", motion: "sliding shingle panels" },
    rec: { materials: "spruce, shingle, iron", lighting: "hearth fire against blue window dusk", objects: "ciupaga axes, carved spoons, wool hangings", music: "Podhale bagpipes and violins", scent: "resin, smoke and cold air" },
    snd: ["highland bagpipes", "gęśle fiddle", "cracking firewood"],
    dna: { mi: 30, og: 70, wc: 20, ns: 35, ad: 15, hf: 15, rr: 50, ps: 45, sh: 55, ql: 60, oc: 45, ds: 70, rs: 35, eu: 60, np: 45 },
    emo: { warm: 60, cold: 40, playful: 35, serious: 55, chaotic: 20, ordered: 65, nostalgic: 75, futuristic: 15, peaceful: 55, ominous: 20 },
  },
  {
    n: "Kalotaszeg embroidery", a: ["kalotaszegi hímzés", "Transylvanian Hungarian embroidery", "írásos stitching"],
    cat: "Textile & Craft", c: "two-colour chain-stitch embroidery", e: "regional_tradition",
    o: "Kalotaszeg region west of Cluj, Transylvania", g: "villages around Huedin — Magyarvista, Sâncraiu, Călățele — in Cluj county, Romania",
    p: "flourished 18th-19th century; continuous practice and revival", era: "late baroque folk to living craft",
    sum: "Kalotaszeg embroidery covers Transylvanian Hungarian linen in bold two-colour chain-stitched flowers, tulips and birds, balancing red against blue with rare discipline.",
    desc: "In Kalotaszeg, a cluster of Transylvanian Hungarian villages west of Cluj, linen pillowcases, aprons, altar cloths and dress panels are worked with richly curved flowers — tulips, pinks, carnations, roses and small birds — outlined in chain stitch and filled in satin stitch. The palette is famously disciplined: strong red against strong blue, later softened with greens and golds, always on bleached homespun. Variants range from free-flowing piecework to the counted írások style, and 19th-century dowry inventories trace its spread as wedding wealth. The craft survived collectivisation and exile, kept alive by village embroiderers, Hungarian folk-art revivalists and museum collections in Cluj and Budapest. Today it dresses Pentecost processions, decorates Calvinist and Catholic interiors alike, and supplies a heritage market of reconstructed folk costume.",
    col: [{ h: "#b3232a", n: "embroidery red" }, { h: "#2b4a7d", n: "indigo blue" }, { h: "#f2ead6", n: "linen cream" }, { h: "#5d7a4c", n: "muted green" }, { h: "#c9a24b", n: "gold accent" }],
    m: ["bleached homespun linen", "wool embroidery thread", "silk chain-stitch floss", "tassel cords"],
    tx: ["raised chain loops", "satin-stitch fill", "hemstitched edges", "soft washed linen"],
    obj: ["tulip-and-bird pillowcases", "kötő aprons", "altar cloths", "wedding cushions", "embroidered blouse yokes"],
    ex: ["Museum of Ethnography, Budapest — Kalotaszeg collections", "Pentecost costume processions at Sâncraiu", "Transylvanian folk-art workshops of Cluj-Napoca"],
    inf: ["Baroque floral silks", "Transylvanian oriental-trade textiles"],
    rel: ["Matyó embroidery", "Hungarian Kalocsa embroidery", "Transylvanian rug weaving"],
    par: "Hungarian folk embroidery", var: ["írásos counted style", "kötött stitch variant", "church altar work"], cf: ["Kalocsa embroidery", "Matyó roses"],
    src: [
      { n: "Wikipedia — Kalotaszeg", u: "https://en.wikipedia.org/wiki/Kalotaszeg", t: "B" },
      { n: "Wikipedia — Transylvania", u: "https://en.wikipedia.org/wiki/Transylvania", t: "B" },
    ],
    tg: ["kalotaszeg", "embroidery", "transylvania", "hungarian", "linen"],
    pop: 30, niche: true,
    vd: { shape: "symmetrical floral medallions on square cloth", line: "curling chain-stitch stems", composition: "corner-to-corner spreading bouquets", texture: "raised loops on flat linen", forms: "tulip, carnation, bird, heart" },
    typ: { display: "folk display serif", body: "book serif", notes: "embroidery-chart spacing" },
    fnt: { display: "Lora", body: "Source Sans Pro", notes: "warm serif suits floral craft" },
    lit: { quality: "soft window light", direction: "north-light evenness for colour truth", temperature: "neutral-warm", shadow: "minimal, cloth-cradled" },
    pho: { approach: "flat-lay textiles and maker hands in sequence", grade: "gentle warm film" },
    fash: { silhouettes: "waisted folk dress", garments: "embroidered blouses, pleated aprons, vests", acc: "red coral beads, headscarves" },
    env: { places: "whitewashed village rooms, garden fences", weather: "gentle four-season highland climate" },
    gd: { layout: "framed medallion grid", icon: "two-bird tulip crest" },
    ui: { background: "#f2ead6", surface: "linen weave texture", components: "stitched-border buttons", motion: "stitch-by-stitch line drawing" },
    rec: { materials: "linen, wool thread, coral", lighting: "soft daylight through lace curtains", objects: "embroidery hoops, scissors, hope chests", music: "Kalotaszeg string trio with kontra viola", scent: "linen soap and beeswax" },
    snd: ["folk violin trio", "gentle village chatter", "church bells"],
    dna: { mi: 35, og: 75, wc: 15, ns: 30, ad: 10, hf: 12, rr: 50, ps: 40, sh: 50, ql: 70, oc: 55, ds: 65, rs: 30, eu: 55, np: 45 },
    emo: { warm: 75, cold: 25, playful: 45, serious: 45, chaotic: 20, ordered: 70, nostalgic: 80, futuristic: 10, peaceful: 70, ominous: 10 },
  },
  {
    n: "Transylvanian Saxon painted furniture", a: ["Saxon dowry chests", "Transylvanian Kasten", "Engelsherz painted ware"],
    cat: "Furniture & Product Design", c: "rural painted furniture", e: "historical",
    o: "Transylvanian Saxon villages, southern Transylvania", g: "Sibiu, Brașov and Sighișoara regions; Saxon villages such as Viscri and Mălâncrav",
    p: "18th-19th century peak", era: "Baroque-to-Biedermeier folk craft",
    sum: "Transylvanian Saxon joiners painted dowry chests and cupboards with tulips, angels' hearts and marble effects, sealing a vanished ethnic culture into folk furniture.",
    desc: "The Transylvanian Saxons, colonists settled from the twelfth century, furnished their houses with chest-built Kasten dowry chests, cupboards, cradles and benches painted by village workshops that peaked in the 1800s. Motifs blend late Baroque flowers — tulips, pinks, acanthus — with the community's emblem, the Engelsherz or angels' heart, plus inscription panels, marbleising and grained borders in blue-greens, red-browns and ochres. Pieces marked betrothals and household rank, travelled with brides, and were periodically repainted by itinerant masters. The twentieth-century exodus of nearly all Saxons emptied the villages, so painted furniture now survives largely in museums and restored house ensembles, above all Sibiu's ASTRA complex and the furnished Saxon rooms of villages like Viscri, where guesthouses keep chests in daily use.",
    col: [{ h: "#2e6b66", n: "blue-green ground" }, { h: "#7c3327", n: "red-brown flower" }, { h: "#c99a3f", n: "ochre border" }, { h: "#d8b25c", n: "angels'-heart gold" }, { h: "#3f3226", n: "dark pine back" }],
    m: ["pine and fir chest timber", "mineral and oil paints", "linseed varnish", "wrought-iron strap hinges"],
    tx: ["brush-figured marbleising", "grained wood borders", "chipped patina", "smooth varnished panels"],
    obj: ["Kasten dowry chest", "Engelsherz crest panels", "painted cradles", "inscription cartouches", "corner cupboards"],
    ex: ["ASTRA Museum of Traditional Folk Civilization, Sibiu", "Furnished Saxon rooms of Viscri village houses", "Mălâncrav manor and village house interiors"],
    inf: ["Austrian Baroque folk painting", "Swabian workshop traditions"],
    rel: ["Transylvanian fortified churches", "Austrian peasant furniture", "Bavarian dresser painting"],
    par: "European painted folk furniture", var: ["Engelsherz chests", "marbleised cupboards", "inscribed cradles"], cf: ["Transylvanian Hungarian furniture", "Alpine dresser painting"],
    src: [
      { n: "Wikipedia — Transylvanian Saxons", u: "https://en.wikipedia.org/wiki/Transylvanian_Saxons", t: "B" },
      { n: "UNESCO — Villages with Fortified Churches in Transylvania", u: "https://whc.unesco.org/en/list/596", t: "A" },
    ],
    tg: ["transylvania", "saxon", "furniture", "engelsherz", "dowry chest"],
    pop: 31, niche: true,
    vd: { shape: "blocky chest volumes with panelled fronts", line: "painted scroll and vine borders", composition: "central crest over drawer friezes", texture: "marbleised and grained paint film", forms: "tulip, angels' heart, cartouche" },
    typ: { display: "blackletter-flavoured display", body: "book serif", notes: "inscription-panel lettering" },
    fnt: { display: "UnifrakturMaguntia", body: "PT Serif", notes: "blackletter display echoes painted inscriptions" },
    lit: { quality: "museum even light", direction: "soft frontal", temperature: "warm", shadow: "gentle under-frame" },
    pho: { approach: "chest-front portraiture with detail crops of motifs", grade: "muted heritage colour" },
    fash: { silhouettes: "sturdy settler dress", garments: "linen shirts, wool skirts, black bodices", acc: "silk head kerchiefs, silver pins" },
    env: { places: "village house rooms, museum courts", weather: "dry continental seasons" },
    gd: { layout: "catalogue plate symmetry", icon: "angels' heart crest" },
    ui: { background: "#2e6b66", surface: "painted panel tiles", components: "cartouche buttons", motion: "drawer-slide reveals" },
    rec: { materials: "pine, mineral pigment, varnish", lighting: "window light across chest tops", objects: "painted chests, ceramics, psalm books", music: "Transylvanian Saxon chorales", scent: "beeswax, pine resin, old paint" },
    snd: ["creaking chest lids", "church bells", "organ chorale"],
    dna: { mi: 35, og: 70, wc: 15, ns: 30, ad: 8, hf: 10, rr: 55, ps: 45, sh: 55, ql: 65, oc: 55, ds: 70, rs: 30, eu: 55, np: 40 },
    emo: { warm: 60, cold: 35, playful: 30, serious: 55, chaotic: 15, ordered: 70, nostalgic: 85, futuristic: 5, peaceful: 55, ominous: 15 },
  },
  {
    n: "Cypriot lefkaritika lace", a: ["Lefkara lace", "lefkaritiko", "white embroidery of Lefkara"],
    cat: "Textile & Craft", c: "drawn-thread embroidery and needlelace", e: "regional_tradition",
    o: "Lefkara, Larnaca district, Cyprus", g: "Lefkara village and Cypriot diaspora lace markets",
    p: "Venetian era onward; UNESCO inscription 2009", era: "late medieval to living craft",
    sum: "Lefkaritika is Lefkara's white-on-white lacework, a Venetian-era blend of drawn-thread embroidery and needlelace that Leonardo's 1481 visit made legendary.",
    desc: "In Lefkara's cobbled lanes women work lefkaritika: tablecloths, napkins and altar linen patterned by cutting and drawing out threads, then darning and overcasting the remainder, and finished with sprays of floral needlelace — the ploumisto style — all strictly white or ivory. Venetian trade carried the work to aristocratic Europe, and village tradition credits Leonardo da Vinci with buying an altar cloth for Milan Cathedral during a 1481 visit. Mass tourism and migration thinned the ranks of embroiderers, prompting UNESCO's 2009 inscription of Lefkara laces (Lefkaritika) on the Representative List. A village women's cooperative and the Cyprus Handicraft Service now train new generations, certify authentic pieces with sewn labels, and keep the summer-doorway stool-and-hoop image of the village alive for visitors.",
    col: [{ h: "#f4efe2", n: "ivory linen" }, { h: "#cfc4ab", n: "ecru shadow" }, { h: "#b9a98c", n: "stone lane" }, { h: "#6f7a4f", n: "olive leaf" }, { h: "#4a3d2c", n: "doorway shadow brown" }],
    m: ["fine linen cloth", "linen thread", "steel embroidery needles", "olive-wood hoop and stool"],
    tx: ["counted thread grids", "raised needlelace sprays", "hemstitched hems", "crisp laundered cloth"],
    obj: ["ploumisto floral tablecloths", "altar cloths", "wedding pillowcases", "needlelace edge trims", "heirloom trousseau chests"],
    ex: ["Lefkara Women's Cooperative showroom", "Legend of Leonardo's 1481 altar cloth", "Cyprus Handicraft Service, Nicosia"],
    inf: ["Venetian reticella and punto in aria", "Greek island white embroidery"],
    rel: ["Venetian needle lace", "Greek island folk dress", "Aegean white embroidery"],
    par: "Mediterranean white needlelace", var: ["ploumisto floral type", "geometric cut-work type", "mixed panel type"], cf: ["Venetian needle lace", "Madeira embroidery"],
    src: [
      { n: "Wikipedia — Lefkara", u: "https://en.wikipedia.org/wiki/Lefkara", t: "B" },
      { n: "UNESCO — Lefkara Laces (Lefkaritika)", u: "https://ich.unesco.org/en/RL/lefkara-laces-lefkaritika-00266", t: "A" },
    ],
    tg: ["cyprus", "lefkaritika", "lace", "venetian", "needlework"],
    pop: 33, niche: true,
    vd: { shape: "square cloth fields of counted geometry", line: "fine pulled-thread diagonals", composition: "central medallion with corner sprays", texture: "openwork whitework", forms: "diamond grid, flower spray, hem band" },
    typ: { display: "delicate high-contrast serif", body: "light serif", notes: "white-catalogue elegance" },
    fnt: { display: "Cormorant", body: "EB Garamond", notes: "fine old-style suits lace fragility" },
    lit: { quality: "bright Aegean", direction: "raking light to reveal thread relief", temperature: "warm-neutral", shadow: "soft blue-grey in the weave" },
    pho: { approach: "macro lace studies with hands at the doorway stool", grade: "ivory-forward clean grade" },
    fash: { silhouettes: "modest Mediterranean layers", garments: "black village dresses with white headscarves", acc: "gold chains, prayer beads" },
    env: { places: "cobbled Lefkara lanes, stone doorways", weather: "dry island sun" },
    gd: { layout: "openwork grid layout", icon: "drawn-thread diamond motif" },
    ui: { background: "#f4efe2", surface: "linen texture cards", components: "stitched-outline buttons", motion: "thread-pull dissolve transitions" },
    rec: { materials: "linen, steel needles, olive wood", lighting: "doorway light on lap work", objects: "hoops, heirloom cloths, coffee cups", music: "Cypriot violin and laouto tunes", scent: "linen starch and jasmine" },
    snd: ["quiet needlework", "village bells", "cicadas"],
    dna: { mi: 60, og: 60, wc: 25, ns: 35, ad: 20, hf: 15, rr: 55, ps: 45, sh: 40, ql: 75, oc: 65, ds: 60, rs: 35, eu: 60, np: 50 },
    emo: { warm: 60, cold: 30, playful: 25, serious: 50, chaotic: 10, ordered: 80, nostalgic: 75, futuristic: 15, peaceful: 70, ominous: 10 },
  },
  {
    n: "Greek island folk dress", a: ["Aegean island costume", "Amalia dress tradition", "island Greek traditional dress"],
    cat: "Fashion & Dress", c: "regional costume", e: "regional_tradition",
    o: "Aegean islands and post-1836 court fashion", g: "Cyclades, Dodecanese (Karpathos, Olympos), Crete, Hydra and Spetses",
    p: "19th century codification; living festal use", era: "romantic nationalism to living tradition",
    sum: "Greek island folk dress layers silk chemises, short embroidered jackets and heavy silver into regionally coded ensembles, crowned by the Amalia dress myth of 1836.",
    desc: "Island costume encoded marriage status, island and wealth in layers: a white silk chemise, the short wool sigouni jacket trimmed with gold braid, the dark kavadi coat, and silver chest chains and brooches. Karpathos' mountain village Olympos keeps the most exuberant dress, with multicoloured aprons and gold-stitched panels worn at weddings and panigyria. Men wore vraka breeches — Cretan dark wool versions with a tucked knife, sailor variants on Hydra. Queen Amalia's 1836 court dress, a blue-silk gown with loose jacket and tasselled cap, fused Bavarian and island elements into a promoted national dress spread by illustrated press. The Lykeion ton Ellinidon, founded in 1911, records and stages authentic costumes, which now anchor festivals, weddings and the great costume collections of Athens museums.",
    col: [{ h: "#2b3f8c", n: "royal blue silk" }, { h: "#c8a03c", n: "gold braid" }, { h: "#f5f1e6", n: "chemise white" }, { h: "#26242a", n: "Cretan black wool" }, { h: "#a52833", n: "apron red" }],
    m: ["island silk and wool", "gold metallic braid", "silver filigree jewellery", "hand-loomed apron cloth"],
    tx: ["shot silk sheen", "metal-thread embroidery", "heavy silver repoussé", "fulled wool"],
    obj: ["sigouni jackets", "kavadi coats", "vraka breeches", "tasselled Amalia caps", "silver chest chains"],
    ex: ["Olympos, Karpathos wedding dress at panigyria", "Lykeion ton Ellinidon archive, Athens", "Cretan vraka dress of Anogia festas"],
    inf: ["Bavarian court fashion of the 1830s", "Ottoman-era island tailoring"],
    rel: ["Cypriot lefkaritika lace", "Faroese wool culture", "Breton bigouden headdress"],
    par: "Greek folk culture", var: ["Amalia dress", "Cretan vraka", "Karpathian bridal dress", "Hydra sailor costume"], cf: ["fustanella mainland dress", "Ottoman urban dress"],
    src: [
      { n: "Wikipedia — Amalia of Oldenburg", u: "https://en.wikipedia.org/wiki/Amalia_of_Oldenburg", t: "B" },
      { n: "Wikipedia — Fustanella", u: "https://en.wikipedia.org/wiki/Fustanella", t: "B" },
    ],
    tg: ["greece", "aegean", "costume", "amalia", "karpathos"],
    pop: 37, niche: false,
    vd: { shape: "layered vertical drape with dark jacket", line: "gold braid trim arcs", composition: "white chemise against black vest", texture: "silk sheen, metal thread", forms: "jacket, apron, cap, chains" },
    typ: { display: "Greek Didot display", body: "clean sans", notes: "island formality with authentic Greek support" },
    fnt: { display: "GFS Didot", body: "Noto Sans", notes: "Greek Font Society Didot suits costume plates" },
    lit: { quality: "whitewashed glare softened by dusk", direction: "side light across braided seams", temperature: "hot with cooling blues", shadow: "short and dense" },
    pho: { approach: "processional and portrait work at panigyria", grade: "saturated blue-gold postcard grade" },
    fash: { silhouettes: "layered, waisted, jewelled", garments: "sigouni jackets, kavadi coats, vraka breeches", acc: "silver chest ornaments, kerchiefs, gold-stitched caps" },
    env: { places: "marble island lanes, village squares, chapels", weather: "meltemi wind and island heat" },
    gd: { layout: "costume-plate symmetry with island map", icon: "sigouni jacket silhouette" },
    ui: { background: "#f5f1e6", surface: "silk sheen panels", components: "gold-braid rule lines", motion: "veil-fade transitions" },
    rec: { materials: "silk, wool, silver", lighting: "candle and votive glow at festivals", objects: "jewellery boxes, embroidery, wedding crowns", music: "island lyra and laouto tunes", scent: "sea salt, basil and incense" },
    snd: ["island lyra", "festival violins", "church bells over water"],
    dna: { mi: 40, og: 60, wc: 20, ns: 30, ad: 15, hf: 15, rr: 50, ps: 50, sh: 50, ql: 65, oc: 50, ds: 65, rs: 35, eu: 60, np: 45 },
    emo: { warm: 70, cold: 25, playful: 45, serious: 50, chaotic: 25, ordered: 65, nostalgic: 75, futuristic: 10, peaceful: 55, ominous: 15 },
  },
  {
    n: "Faroese wool culture", a: ["Faroese knitting", "Føroyar wool traditions", "Faroese national dress wool"],
    cat: "Textile & Craft", c: "wool economy and knitting", e: "regional_tradition",
    o: "Faroe Islands, North Atlantic", g: "all eighteen Faroese islands, notably Tórshavn and the outports",
    p: "medieval wool export to living national dress", era: "Norse settlement to living tradition",
    sum: "On the Faroes, where sheep long outnumber people, wool runs through everything from everyday knitwear to the silver-buckled national dress worn at Ólavsøka.",
    desc: "Sheep gave the Faroes both name (Færeyjar, sheep islands) and subsistence: home-grown wool was carded, spun and knitted in every household into jumpers, caps and the famous patterned shawls whose winged shoulders grip the wearer. Exported sweaters with bird, flower and wave motifs carried the islands' knitting worldwide in the mid-twentieth century, later amplified by design houses such as Guðrun & Guðrun. Wool also dresses the nation: the national costume pairs hand-knit stockings and waistcoats with silver buttons and, for women, silver-trimmed headdresses and shawls, worn en masse at Ólavsøka on 29 July. Spinning wheels, dye pots and wool stores remain common sights, and knitwear cooperatives keep the chain local from clip to jumper in a place where weather makes wool a necessity, not a nostalgia.",
    col: [{ h: "#7a5a48", n: "moorit brown" }, { h: "#eceae2", n: "foam white" }, { h: "#5c6772", n: "storm slate" }, { h: "#45604e", n: "seaweed green" }, { h: "#9b3a3d", n: "berry red knit" }],
    m: ["Faroese breed wool", "plant dye materials", "silver costume buttons", "bone knitting needles"],
    tx: ["grippy knit gauge", "hairy two-ply yarn", "woven wool twill", "polished silver"],
    obj: ["winged Faroese shawls", "bird-pattern jumpers", "national-dress stockings", "silver-studded belts", "yarn hanks drying by the stove"],
    ex: ["Ólavsøka national dress processions, Tórshavn, 29 July", "Guðrun & Guðrun knitwear studio", "patterned shawls with eagle-wing shoulders"],
    inf: ["Norse settler wool economy", "mid-century Nordic knitwear design"],
    rel: ["Nordic knitwear traditions", "Faroese chain dance", "Harris Tweed weaving"],
    par: "North Atlantic wool cultures", var: ["winged shawls", "national dress knitwear", "patterned jumpers"], cf: ["Icelandic lopapeysa", "Shetland knitting"],
    src: [
      { n: "Wikipedia — Culture of the Faroe Islands", u: "https://en.wikipedia.org/wiki/Culture_of_the_Faroe_Islands", t: "B" },
      { n: "Wikipedia — Faroe Islands", u: "https://en.wikipedia.org/wiki/Faroe_Islands", t: "B" },
    ],
    tg: ["faroe", "wool", "knitting", "olavsoka", "north atlantic"],
    pop: 34, niche: false,
    vd: { shape: "rounded shoulder-hugging knit volumes", line: "checker and bird chart bands", composition: "solid ground with pattern yokes", texture: "hairy lofted wool", forms: "shawl wing, jumper yoke, stocking" },
    typ: { display: "chunky rounded slab", body: "friendly sans", notes: "cozy wool-shop register" },
    fnt: { display: "Fraunces", body: "Karla", notes: "warm retro serif suits heritage knitwear" },
    lit: { quality: "flat, damp, luminous North Atlantic light", direction: "omnidirectional overcast", temperature: "cool", shadow: "barely there, soft" },
    pho: { approach: "interior wool vignettes and coastal knit portraits", grade: "muted, slightly cool film" },
    fash: { silhouettes: "bulky, layered, hand-made", garments: "patterned jumpers, shawls, wool skirts", acc: "silver national-dress buttons and headdresses" },
    env: { places: "grass-roofed harbours, grassy slopes, knit-filled homes", weather: "horizontal rain, sudden clearance" },
    gd: { layout: "cozy grid with knit-swatch tiles", icon: "winged shawl mark" },
    ui: { background: "#eceae2", surface: "knit-stitch texture panels", components: "button-stud toggles", motion: "soft wool-blur fades" },
    rec: { materials: "wool, silver, driftwood", lighting: "overcast window glow", objects: "spinning wheels, yarn baskets, costume chests", music: "Faroese chain-dance ballads", scent: "wet wool, peat smoke, sea" },
    snd: ["chain-dance singing", "rain on roofs", "seabirds"],
    dna: { mi: 45, og: 75, wc: 15, ns: 35, ad: 20, hf: 15, rr: 55, ps: 45, sh: 55, ql: 65, oc: 50, ds: 60, rs: 35, eu: 60, np: 50 },
    emo: { warm: 65, cold: 40, playful: 40, serious: 45, chaotic: 15, ordered: 60, nostalgic: 70, futuristic: 20, peaceful: 65, ominous: 15 },
  },
  {
    n: "Latvian folk symbols and midsummer", a: ["Jāņi festival", "Līgo night", "Latvian sign motifs"],
    cat: "Regional & Cultural Tradition", c: "calendar festival and sign system", e: "regional_tradition",
    o: "Latvia, Baltic agrarian culture", g: "Latvia and the Latvian diaspora worldwide",
    p: "pre-Christian roots; folk revival documented since the 19th century", era: "pagan-continuum to national tradition",
    sum: "Latvia's Jāņi midsummer pairs bonfires, wreaths and caraway cheese with an ancient sign vocabulary — Māra's cross, Jumis, Auseklis — woven into belts, mittens and song.",
    desc: "At Jāņi (23-24 June) Latvians wear oak-leaf and flower wreaths, brew beer, bake Jāņu siers caraway cheese and sing līgo refrains through the shortest night around bonfires, floating wreaths downstream. The festival carries a geometric sign language: Māra's cross guarding hearth and house, Jumis' doubled spike for fertility, Auseklis the morning star, sun discs and stars, worked into woven josta belts, mittens and sashes. Krišjānis Barons' Dainu skapis — a cabinet of over 217,000 archived folk-song texts, itself on UNESCO's Memory of the World register — codified the repertoire these signs travel with. Soviet bans only deepened the songs' political charge, and the restored Song and Dance Festival now stages the whole sign-and-song system at national scale in Riga.",
    col: [{ h: "#d9a441", n: "amber" }, { h: "#6f4a2a", n: "rye brown" }, { h: "#a83232", n: "mitten red" }, { h: "#efe6d0", n: "flax cream" }, { h: "#c56b2f", n: "bonfire orange" }],
    m: ["hand-woven wool belts", "flax linen", "oak leaves", "muslin cheese cloth"],
    tx: ["warp-float belt weaving", "plush knit mitten pile", "woven sash striping", "charred bonfire wood"],
    obj: ["Jāņu siers caraway cheese", "oak-leaf wreaths", "Māra's cross belts", "patterned mittens", "Jumis grain charms"],
    ex: ["Jāņi bonfires and wreath-floating, 23-24 June", "Krišjānis Barons' Dainu skapis, UNESCO Memory of the World", "Latvian Song and Dance Festival, Riga"],
    inf: ["Baltic pre-Christian cosmology", "19th-century folk-song collection movement"],
    rel: ["Estonian knitting traditions", "Sorbian egg decorating", "Seto culture"],
    par: "Baltic folk tradition", var: ["Līgo songs", "Jāņu siers", "woven sign belts"], cf: ["Lithuanian Joninės", "Estonian Jaanipäev"],
    src: [
      { n: "Wikipedia — Jāņi", u: "https://en.wikipedia.org/wiki/J%C4%81%C5%86i", t: "B" },
      { n: "Wikipedia — Latvian mythology", u: "https://en.wikipedia.org/wiki/Latvian_mythology", t: "B" },
    ],
    tg: ["latvia", "jani", "midsummer", "folk symbols", "bonfire"],
    pop: 40, niche: false,
    vd: { shape: "geometric star and cross signs in strips", line: "warp-float diagonal bands", composition: "symmetrical belt repetition", texture: "wool weft on flax warp", forms: "Māra cross, Jumis, Auseklis star, sun disc" },
    typ: { display: "geometric display serif", body: "clean sans", notes: "sign-chart clarity" },
    fnt: { display: "Zilla Slab", body: "Fira Sans", notes: "slab warmth with geometric crispness" },
    lit: { quality: "low golden midnight sun", direction: "firelight radiance against dusk", temperature: "warm", shadow: "flickering and amber" },
    pho: { approach: "fire-lit festival reportage and textile flat-lays", grade: "warm high-contrast night grade" },
    fash: { silhouettes: "white folk blouse and wreath", garments: "woven belts, patterned mittens, linen shirts", acc: "flower and oak-leaf crowns" },
    env: { places: "farmsteads, birch groves, riverbanks", weather: "white nights, warm storms" },
    gd: { layout: "belt-like horizontal sign bands", icon: "Auseklis eight-point star" },
    ui: { background: "#efe6d0", surface: "woven wool texture", components: "sign-charm toggles", motion: "bonfire flicker loops" },
    rec: { materials: "wool, flax, oak, beeswax", lighting: "bonfire and candle glow", objects: "cheese moulds, wreaths, songbooks", music: "daina drone singing and kokle zither", scent: "smoke, caraway and cut grass" },
    snd: ["kokle zither", "līgo song refrains", "crackling bonfire"],
    dna: { mi: 40, og: 70, wc: 20, ns: 35, ad: 15, hf: 15, rr: 55, ps: 50, sh: 55, ql: 60, oc: 60, ds: 65, rs: 35, eu: 60, np: 45 },
    emo: { warm: 80, cold: 20, playful: 55, serious: 45, chaotic: 30, ordered: 60, nostalgic: 80, futuristic: 15, peaceful: 60, ominous: 15 },
  },
  {
    n: "Seto culture", a: ["Setomaa", "Seto leelo", "Setos of Estonia"],
    cat: "Regional & Cultural Tradition", c: "Finno-Ugric borderland ethnic culture", e: "regional_tradition",
    o: "Setomaa on the Estonia-Russia border", g: "south-eastern Estonia (Võru county) and Pechory district, Russia",
    p: "medieval Orthodox mission onward; UNESCO listing 2009", era: "borderland medieval to endangered living culture",
    sum: "The Setos, an Orthodox Finno-Ugric people of borderland Setomaa, keep leelo polyphony, tsässon chapels and towering silver jewellery in a culture UNESCO lists as urgently safeguarded.",
    desc: "Straddling the Estonia-Russia frontier, the Setos joined a Finnic language to Orthodox faith from medieval times, building wooden tsässon village chapels and keeping a calendar of Orthodox-folk feasts. Their leelo — led by an improvising sõnoline soloist over a drone — is a polyphony UNESCO inscribed on the Urgent Safeguarding List in 2009. Costume is unmistakable: linen shirts under wool, crowned by massive silver sõlg brooches with dangling chains that announced family wealth, worn at their most abundant by brides. Since the 1990s the community has re-crowned a symbolic Seto Kingdom at Obinitsa each August, complete with king and suur sõlg. Border changes after 1991 split families and villages, making leelo choirs, language camps and museum work matters of cultural survival.",
    col: [{ h: "#2f3f66", n: "indigo wool" }, { h: "#c6c8cc", n: "chased silver" }, { h: "#7c6a4f", n: "tsässon pine" }, { h: "#8c4a33", n: "trim red" }, { h: "#6b7c4f", n: "birch green" }],
    m: ["wool cloth", "hammered silver brooches", "pine chapel logs", "linen shirts"],
    tx: ["heavy wool twill", "chased silver relief", "log-cut chapel wall", "red linen stitchwork"],
    obj: ["suur sõlg silver brooches", "tsässon chapels", "leelo choirs", "crown of the Seto King", "embroidered shirts"],
    ex: ["Seto Kingdom celebration, Obinitsa, August", "Seto leelo choirs of Värska and Obinitsa", "tsässon chapels across Setomaa"],
    inf: ["Orthodox mission culture", "Baltic-Finnic runo-song tradition"],
    rel: ["Latvian folk symbols and midsummer", "Estonian knitting traditions", "Kihnu island culture"],
    par: "Finno-Ugric folk cultures", var: ["leelo polyphony", "tsässon keeping", "Seto Kingdom feast"], cf: ["Võro culture", "Veps culture"],
    src: [
      { n: "Wikipedia — Setos", u: "https://en.wikipedia.org/wiki/Setos", t: "B" },
      { n: "UNESCO — Seto Leelo, Seto Polyphonic Singing Tradition", u: "https://ich.unesco.org/en/USL/seto-leelo-seto-polyphonic-singing-tradition-00338", t: "A" },
    ],
    tg: ["seto", "setomaa", "leelo", "estonia", "singing"],
    pop: 29, niche: true,
    vd: { shape: "upright choir rows under silver glare", line: "embroidered straight borders", composition: "white-and-indigo fields with metal flashes", texture: "wool, chased silver, log wood", forms: "sõlg brooch, tsässon gable, shawl" },
    typ: { display: "sturdy humanist serif", body: "quiet sans", notes: "museum-ethnography register" },
    fnt: { display: "Bitter", body: "PT Sans", notes: "slab serif with Cyrillic-capable body" },
    lit: { quality: "cool northern summer light", direction: "low silver sun", temperature: "cold-neutral", shadow: "long and thin" },
    pho: { approach: "choir portraits and chapel interiors", grade: "desaturated silver-blue" },
    fash: { silhouettes: "heavy layered wool with metal crown", garments: "wool skirts, linen shirts, big shawls", acc: "sõlg brooches, chains, headcloths" },
    env: { places: "village chapels, border forests, feast tables", weather: "short summers, long snows" },
    gd: { layout: "framed ethnographic plates", icon: "sõlg brooch rosette" },
    ui: { background: "#2f3f66", surface: "wool weave panels", components: "silver stud buttons", motion: "slow drone-like loops" },
    rec: { materials: "wool, silver, pine", lighting: "candlelight in tsässons", objects: "brooches, song sheets, icon lamps", music: "leelo drone polyphony", scent: "pine resin, wax, rye bread" },
    snd: ["leelo female choir drone", "forest wind", "chapel bells"],
    dna: { mi: 40, og: 70, wc: 15, ns: 30, ad: 10, hf: 12, rr: 55, ps: 40, sh: 60, ql: 60, oc: 50, ds: 65, rs: 35, eu: 50, np: 45 },
    emo: { warm: 50, cold: 55, playful: 30, serious: 65, chaotic: 20, ordered: 60, nostalgic: 75, futuristic: 10, peaceful: 55, ominous: 30 },
  },
  {
    n: "Cornish engine houses", a: ["Cornish mine engine houses", "beam engine houses", "Cornish mining landscape ruins"],
    cat: "Architectural Style", c: "industrial vernacular", e: "historical",
    o: "Cornwall and west Devon, United Kingdom", g: "Cornish mining districts: Redruth, Camborne, St Agnes, Botallack, Levant, Tavistock fringe",
    p: "1712-1930s, mostly 19th century", era: "Industrial Revolution",
    sum: "Cornish engine houses are the granite-and-brick shells built to hold beam engines that kept Cornish tin and copper mines dry, now ruins strung along a UNESCO-listed landscape.",
    desc: "Every deep Cornish mine needed a beam engine to lift water, and each engine got a tapered granite house with brick arches, a bob-wall aperture over the shaft and a tall slim stack, often stepped into cliff or moor. Built chiefly in the 1800s to house ever-larger high-pressure Cornish engines — the most efficient steam engines of their day — the houses hardened into a standard pattern repeated across the mining districts. When copper collapsed and tin slumped, the pumps stilled and the houses were left as landmarks; the Cornwall and West Devon Mining Landscape won World Heritage status in 2006 across ten areas. Emigrant Cousin Jacks rebuilt the type in Mexico, Australia, South Africa and Michigan, and the cliff-top ruins at Botallack and Wheal Coates keep the style famous on screen and page.",
    col: [{ h: "#9a968c", n: "granite grey" }, { h: "#8d4a32", n: "brick arch red" }, { h: "#a9c3bd", n: "sea foam" }, { h: "#7a4a2a", n: "rust iron" }, { h: "#6d7a4a", n: "moor grass green" }],
    m: ["dressed granite", "engineering brick", "cast-iron beam remnants", "oak beam timbers"],
    tx: ["coursed granite rubble", "weathered brick voussoirs", "pitted ironwork", "salt-scoured stone"],
    obj: ["tapered chimney stacks", "bob-wall arches", "cylinder platform openings", "inscribed granite lintels", "shaft collar masonry"],
    ex: ["The Crowns engine houses, Botallack", "Levant Beam Engine, Pendeen", "Wheal Coates above St Agnes"],
    inf: ["Cornish high-pressure beam-engine design", "mining-settlement vernacular building"],
    rel: ["Welsh slate quarry landscapes", "Industrial Revolution iron architecture", "post-industrial ruin aesthetic"],
    par: "Industrial Revolution architecture", var: ["pumping engine houses", "winding houses", "count houses"], cf: ["winding house ruins", "mill architecture"],
    src: [
      { n: "Wikipedia — Cornish Engine", u: "https://en.wikipedia.org/wiki/Cornish_engine", t: "B" },
      { n: "UNESCO — Cornwall and West Devon Mining Landscape", u: "https://whc.unesco.org/en/list/970", t: "A" },
    ],
    tg: ["cornwall", "mining", "engine house", "granite", "unesco"],
    pop: 38, niche: false,
    vd: { shape: "boxy granite houses with tapering stacks", line: "tall round chimneys against skyline", composition: "ruin row along cliff or moor", texture: "coursed granite, rust, salt", forms: "bob wall, chimney, arch, shaft collar" },
    typ: { display: "bold industrial grotesque", body: "utility sans", notes: "heritage-board tone" },
    fnt: { display: "Archivo Black", body: "Work Sans", notes: "heavy grotesque reads at ruin distances" },
    lit: { quality: "silver Atlantic weather light", direction: "sea-facing cross light", temperature: "cool with warm stone", shadow: "hard in squalls, soft in fog" },
    pho: { approach: "cliffside silhouette studies and interior shaft frames", grade: "cool slate grade with rust accents" },
    fash: { silhouettes: "hard-wearing Victorian workwear", garments: "drill jackets, moleskin trousers", acc: "tin hats and lamp buckets" },
    env: { places: "cliff ruins, moorland shafts, tramway paths", weather: "gales, sea mist, sudden sun" },
    gd: { layout: "industrial elevation plates with site maps", icon: "engine house chimney glyph" },
    ui: { background: "#9a968c", surface: "granite texture blocks", components: "rivet and bolt details", motion: "steam-smoke drifts" },
    rec: { materials: "granite, brick, iron", lighting: "low Atlantic sun through engine arches", objects: "beam engine remains, ore carts, mine plans", music: "Cornish brass bands and shanties", scent: "salt, gorse, cold stone" },
    snd: ["Atlantic gale", "gull cries", "reconstructed beam-engine clack"],
    dna: { mi: 50, og: 45, wc: 25, ns: 40, ad: 20, hf: 25, rr: 40, ps: 55, sh: 50, ql: 65, oc: 55, ds: 75, rs: 40, eu: 55, np: 50 },
    emo: { warm: 35, cold: 60, playful: 20, serious: 70, chaotic: 25, ordered: 55, nostalgic: 70, futuristic: 15, peaceful: 50, ominous: 45 },
  },
  {
    n: "Celtic Revival", a: ["Archibald Knox design", "Cymric and Tudric ware", "Irish Celtic Revival"],
    cat: "Art Movement", c: "Celtic Revival decorative design", e: "historical",
    o: "British Isles, 1880s-1910s", g: "London design houses (Liberty & Co.), Dublin workshops, Isle of Man",
    p: "1880s-1910s peak", era: "late Victorian to Edwardian",
    sum: "The Celtic Revival reworked Insular knotwork and stone-cross carving into modern design, most elegantly in Archibald Knox's Cymric silver and Tudric pewter for Liberty & Co.",
    desc: "Fired by antiquarian study of illuminated gospels, high crosses and brooches, designers across Britain and Ireland translated interlace, spirals and engraved zoomorphs into contemporary wares. The decisive figure was Manx-born Archibald Knox (1864-1933), who from 1899 designed Liberty & Co.'s Cymric silver and Tudric pewter: clean rectilinear forms skinned with fine knotwork and often left partly unornamented, bridging Arts and Crafts restraint and Art Nouveau line. In Dublin the Dun Emer and Cuala presses and allied metalwork shops gave the revival an Irish-national cast, while Knox's manuscript-style lettering albums seeded Manx design identity. The movement fed early twentieth-century jewellery, book covers and stained glass, and its museum-friendly canon endures in reproductions, wedding bands and heritage branding across the Celtic countries.",
    col: [{ h: "#8c8f94", n: "pewter grey" }, { h: "#c9ccd1", n: "worked silver" }, { h: "#3f6b52", n: "Celtic enamel green" }, { h: "#c39a4e", n: "manuscript ochre" }, { h: "#efe8d4", n: "vellum cream" }],
    m: ["Tudric pewter", "Cymric silver", "plique enamel", "vellum and ink"],
    tx: ["polished pewter softness", "fine incised knotwork", "chased silver relief", "aged vellum"],
    obj: ["Cymric silver tea services", "Tudric pewter clocks", "interlace inkwells", "knotwork buckles and brooches", "manuscript-style title pages"],
    ex: ["Liberty & Co. Cymric ware from 1899", "Manx Museum Knox collections, Douglas", "Cuala Press Celtic Revival book design"],
    inf: ["Insular manuscript interlace", "Arts and Crafts reform design"],
    rel: ["Irish Celtic metalwork", "Insular manuscript illumination", "Arts and Crafts movement"],
    par: "Arts and Crafts movement", var: ["Cymric silver ware", "Tudric pewter", "Knox Manx lettering"], cf: ["Art Nouveau", "Gothic Revival ornament"],
    src: [
      { n: "Wikipedia — Celtic Revival", u: "https://en.wikipedia.org/wiki/Celtic_Revival", t: "B" },
      { n: "Wikipedia — Archibald Knox", u: "https://en.wikipedia.org/wiki/Archibald_Knox", t: "B" },
    ],
    tg: ["celtic revival", "archibald knox", "liberty", "knotwork", "manx"],
    pop: 36, niche: false,
    vd: { shape: "rectilinear wares wrapped in knotwork panels", line: "endless interlace cords", composition: "controlled panels with breathing space", texture: "polished metal with incised line", forms: "knot, spiral, zoomorph, cross-carpet band" },
    typ: { display: "insular-style decorative caps", body: "warm serif", notes: "decorative caps with restrained body" },
    fnt: { display: "Cinzel Decorative", body: "Alegreya", notes: "decorative caps nod to carved lettering" },
    lit: { quality: "soft showroom daylight", direction: "even top light for metal sheen", temperature: "neutral", shadow: "controlled studio soft" },
    pho: { approach: "object studio stills with knotwork macro crops", grade: "silver-grey elegance" },
    fash: { silhouettes: "tailored Edwardian", garments: "high-collar blouses, Liberty silks", acc: "Celtic silver brooches and buckles" },
    env: { places: "design showrooms, manuscript libraries", weather: "mild temperate interiors" },
    gd: { layout: "panelled symmetry with interlace borders", icon: "endless knot medallion" },
    ui: { background: "#efe8d4", surface: "pewter panels", components: "knot-border buttons", motion: "interlace line-draw loops" },
    rec: { materials: "pewter, silver, enamel", lighting: "soft north light on metal", objects: "clocks, inkwells, gospel facsimiles", music: "Irish harp airs", scent: "ink, beeswax, heather" },
    snd: ["Celtic harp", "uilleann pipes", "stylus on pewter"],
    dna: { mi: 55, og: 55, wc: 20, ns: 35, ad: 25, hf: 20, rr: 55, ps: 45, sh: 55, ql: 70, oc: 60, ds: 60, rs: 35, eu: 60, np: 45 },
    emo: { warm: 50, cold: 45, playful: 35, serious: 55, chaotic: 15, ordered: 70, nostalgic: 70, futuristic: 20, peaceful: 60, ominous: 15 },
  },
  {
    n: "Irish Celtic metalwork", a: ["Ardagh chalice tradition", "Tara brooch craft", "Insular ecclesiastical metalwork"],
    cat: "Religious & Sacred Art", c: "Insular ecclesiastical goldsmithing", e: "historical",
    o: "early medieval Ireland", g: "Ireland; National Museum of Ireland, Dublin",
    p: "7th-9th century golden age, decline after 12th-century church reform", era: "early medieval",
    sum: "Early Irish monasteries produced Europe's most sophisticated metalwork — the Ardagh Chalice, Tara Brooch and Derrynaflan hoard — fusing gold filigree, enamel and amber into Insular splendour.",
    desc: "Between the seventh and ninth centuries Irish monastic workshops raised goldsmithing to unmatched heights. The Ardagh Chalice (early eighth century), found in 1868 at Reerasta, joins beaten silver with gilt-bronze bands, filigree interlace panels, enamels, amber and glass studs — hundreds of individual fittings hiding under a serene curve. The Tara Brooch (c. 700), ploughed up at Bettystown in 1850, packs a pseudo-penannular form with gold filigree, amber and millefiori. The 1980 Derrynaflan find — chalice, paten and sieve — confirmed a whole school. Techniques included drawn-wire filigree, chip-carving, cloisonné and gilding, serving church ritual and elite display alike. After the twelfth-century church reform the school faded, leaving objects now centred in the National Museum of Ireland and endlessly reinterpreted by the Celtic Revival.",
    col: [{ h: "#b9bec4", n: "beaten silver" }, { h: "#c8a13f", n: "gilt gold" }, { h: "#8f2f2a", n: "enamel red" }, { h: "#cf8a2e", n: "amber" }, { h: "#3d5a4a", n: "patina green" }],
    m: ["beaten silver", "gold wire filigree", "cloisonné enamel", "amber and millefiori glass"],
    tx: ["drawn gold-wire coils", "glass-smooth enamel", "hammered silver sheen", "dark bronze patina"],
    obj: ["Ardagh Chalice", "Tara Brooch", "Derrynaflan chalice and paten", "Moylough belt shrine", "cumdach book shrines"],
    ex: ["Ardagh Chalice, National Museum of Ireland", "Tara Brooch, found 1850 at Bettystown", "Derrynaflan Hoard, discovered 1980"],
    inf: ["late Roman goldsmith technique", "Anglo-Saxon metalwork exchange"],
    rel: ["Insular manuscript illumination", "Celtic Revival", "Celtic knotwork"],
    par: "Insular art", var: ["pseudo-penannular brooches", "chalice and paten sets", "cumdach book shrines"], cf: ["Anglo-Saxon metalwork", "Pictish silverware"],
    src: [
      { n: "Wikipedia — Ardagh Chalice", u: "https://en.wikipedia.org/wiki/Ardagh_Chalice", t: "B" },
      { n: "Wikipedia — Tara Brooch", u: "https://en.wikipedia.org/wiki/Tara_Brooch", t: "B" },
    ],
    tg: ["ireland", "metalwork", "ardagh", "insular", "chalice"],
    pop: 42, niche: false,
    vd: { shape: "balanced chalice silhouettes and disc brooches", line: "swirling filigree interlace", composition: "gilt bands on silver fields", texture: "granulated gold, glass studs", forms: "brooch, chalice, crozier, shrine" },
    typ: { display: "lapidary carved caps", body: "scholarly serif", notes: "museum-catalogue register" },
    fnt: { display: "Cinzel", body: "Gentium Book Plus", notes: "lapidary caps with broad script support" },
    lit: { quality: "museum key-light drama", direction: "spotlight grazing relief", temperature: "neutral-gold", shadow: "black velvet surrounds" },
    pho: { approach: "macro filigree studies on black", grade: "gold-and-silver jewel grade" },
    fash: { silhouettes: "romantic medievalist", garments: "wool cloaks fastened at the shoulder", acc: "penannular brooch reproductions" },
    env: { places: "monastic sites, museum vitrines", weather: "Atlantic drizzle beyond glass" },
    gd: { layout: "object-on-black vitrine layout", icon: "pseudo-penannular brooch glyph" },
    ui: { background: "#101314", surface: "dark stone panels", components: "gold hairline rules", motion: "slow orbit reveals" },
    rec: { materials: "silver, gold, amber", lighting: "single-source vitrine spots", objects: "chalice replicas, brooches, manuscripts", music: "plainchant and harp", scent: "beeswax candle, cold stone" },
    snd: ["Celtic harp", "monastic chant", "silver ring on stone"],
    dna: { mi: 50, og: 50, wc: 15, ns: 30, ad: 20, hf: 15, rr: 60, ps: 55, sh: 50, ql: 75, oc: 65, ds: 65, rs: 35, eu: 55, np: 45 },
    emo: { warm: 45, cold: 50, playful: 20, serious: 75, chaotic: 10, ordered: 70, nostalgic: 60, futuristic: 10, peaceful: 45, ominous: 25 },
  },
  {
    n: "Insular manuscript illumination", a: ["Hiberno-Saxon gospel art", "Book of Kells style", "Lindisfarne style painting"],
    cat: "Religious & Sacred Art", c: "Insular gospel-book illumination", e: "historical",
    o: "Irish and Northumbrian monasteries", g: "Iona, Kells, Lindisfarne, Durrow; Trinity College Dublin and British Library collections",
    p: "7th-9th centuries", era: "early medieval",
    sum: "Insular manuscript illumination turned gospel books into labyrinths of interlace, carpet pages and exploding initials, culminating in the Book of Kells around 800.",
    desc: "Monasteries of Ireland and Northumbria developed a gospel-book art unlike any contemporary: full pages of pure pattern — carpet pages of spirals, knots and stepped crosses — and initials that detonate into men, beasts and endless cords, as on Kells' Chi-Rho page. The Lindisfarne Gospels (c. 698), written and painted by Eadfrith, the Book of Durrow and the Book of Kells (c. 800) set the canon, with blues, yellows and reds laid flat on calfskin vellum. Scribes mixed La Tène-derived ornament with Mediterranean book design, creating a style carried by missionaries across Europe that influenced continental illumination. After Viking raids dispersed the communities, the great books survived as relics — Kells now in Trinity College Dublin, Lindisfarne in the British Library — among the most visited artworks of the British Isles.",
    col: [{ h: "#e8dcb8", n: "vellum ochre" }, { h: "#3a4f8c", n: "woad blue" }, { h: "#d9a832", n: "orpiment yellow" }, { h: "#a83232", n: "red lead" }, { h: "#2e2620", n: "oak-gall ink" }],
    m: ["calfskin vellum", "mineral and plant pigments", "goose quills", "oak-gall ink"],
    tx: ["fine interlace hairlines", "flat opaque colour fields", "vellum tooth", "burnished ink"],
    obj: ["carpet pages", "Chi-Rho initials", "evangelist portraits", "cross-carpet spirals", "marginal beasts"],
    ex: ["Book of Kells Chi-Rho page, Trinity College Dublin", "Lindisfarne Gospels carpet page, British Library", "Book of Durrow, Trinity College Dublin"],
    inf: ["La Tène curvilinear ornament", "late antique gospel layout"],
    rel: ["Irish Celtic metalwork", "Celtic Revival", "Celtic knotwork"],
    par: "Insular art", var: ["carpet page type", "initial-page type", "evangelist portrait type"], cf: ["Carolingian manuscript painting", "Coptic manuscript illumination"],
    src: [
      { n: "Wikipedia — Insular Art", u: "https://en.wikipedia.org/wiki/Insular_art", t: "B" },
      { n: "Wikipedia — Book of Kells", u: "https://en.wikipedia.org/wiki/Book_of_Kells", t: "B" },
    ],
    tg: ["insular", "kells", "manuscript", "lindisfarne", "interlace"],
    pop: 45, niche: false,
    vd: { shape: "full-page geometric labyrinths", line: "endless double-line interlace", composition: "frame, field and exploding initial", texture: "fine hairline knots on vellum", forms: "knot, spiral, zoomorph, stepped cross" },
    typ: { display: "uncial display", body: "old-style serif", notes: "insular-style caps with legible body" },
    fnt: { display: "Uncial Antiqua", body: "EB Garamond", notes: "half-uncial display evokes the scriptorium" },
    lit: { quality: "cool library daylight", direction: "raking light to lift vellum relief", temperature: "neutral", shadow: "minimal and controlled" },
    pho: { approach: "codex spreads and macro detail pairs", grade: "true-to-parchment neutral" },
    fash: { silhouettes: "monastic robe simplicity", garments: "wool habits, cowls", acc: "leather book satchels" },
    env: { places: "scriptorium cells, stone churches", weather: "Atlantic mist beyond the cloister" },
    gd: { layout: "carpet-page full-bleed fronts", icon: "interlace initial capital" },
    ui: { background: "#e8dcb8", surface: "vellum texture", components: "knotwork dividers", motion: "slow page-turn transitions" },
    rec: { materials: "vellum, quill, pigment", lighting: "soft overcast window light", objects: "gospel books, inkhorns, wax tablets", music: "plainchant", scent: "vellum, oak-gall ink, candle" },
    snd: ["quill scratch", "chant from the church", "parchment rustle"],
    dna: { mi: 45, og: 55, wc: 20, ns: 30, ad: 25, hf: 15, rr: 60, ps: 55, sh: 55, ql: 75, oc: 65, ds: 60, rs: 35, eu: 55, np: 45 },
    emo: { warm: 40, cold: 45, playful: 25, serious: 75, chaotic: 15, ordered: 75, nostalgic: 60, futuristic: 10, peaceful: 55, ominous: 20 },
  },
  {
    n: "Hutsul Carpathian folk culture", a: ["Hutsulshchyna", "Hutsul crafts", "Carpathian Hutsuls"],
    cat: "Regional & Cultural Tradition", c: "Carpathian highland culture", e: "regional_tradition",
    o: "Carpathian mountains of western Ukraine and adjacent Romania", g: "Ivano-Frankivsk and Zakarpattia oblasts, Bukovina, and Suceava county, Romania",
    p: "documented from the 18th century; living tradition", era: "early modern to living tradition",
    sum: "Hutsul highlanders of the Carpathians built a culture of inlaid wood, painted ceramics, trembita horns and keptar vests celebrated across Ukraine.",
    desc: "Hutsuls — sheepherding highlanders of the eastern Carpathians — turned mountain materials into signature crafts: chests, powder horns and small topirky axes carved and inlaid with contrasting woods, beads and metal; Kosiv's painted ceramic tiles and plates with horses, roosters and garden trees, inscribed by UNESCO in 2019; and Hutsul pysanky Easter eggs in dense red-black writing. Shepherd life gave the trembita, an alpine horn up to three metres long that once carried signals between valleys, plus the keptar vest, felt hats and embroidered shirts worn with wide leather belts. Kolomyia's National Museum of Hutsulshchyna and Pokuttya Folk Art holds the canon, Hutsul fiddle-and-drymba music fills festivals, and the culture now drives Carpathian tourism, film and craft revival on both sides of the border.",
    col: [{ h: "#5d4327", n: "walnut brown" }, { h: "#9a3b26", n: "Kosiv red-brown" }, { h: "#a92c22", n: "egg red" }, { h: "#b08d3e", n: "brass inlay" }, { h: "#3e5a3c", n: "spruce green" }],
    m: ["Carpathian hardwoods", "coloured clays", "sheep wool", "brass inlay"],
    tx: ["deep chip-carving", "glazed tile gloss", "felted wool", "steam-bent wood"],
    obj: ["trembita horns", "Kosiv painted tiles", "keptar vests", "inlaid wooden chests", "topirets hand-axes"],
    ex: ["Kosiv painted ceramics, UNESCO ICH since 2019", "trembita signals of Carpathian shepherds", "National Museum of Hutsulshchyna and Pokuttya Folk Art, Kolomyia"],
    inf: ["Carpathian pastoral transhumance", "Hutsul church carpentry"],
    rel: ["Slovak fujara", "Sorbian egg decorating", "Alpine alphorn"],
    par: "Carpathian folk cultures", var: ["Kosiv ceramics", "Hutsul pysanky", "inlaid woodcraft"], cf: ["Boyko culture", "Lemko culture"],
    src: [
      { n: "Wikipedia — Hutsuls", u: "https://en.wikipedia.org/wiki/Hutsuls", t: "B" },
      { n: "Wikipedia — Trembita", u: "https://en.wikipedia.org/wiki/Trembita", t: "B" },
    ],
    tg: ["hutsul", "carpathians", "trembita", "kosiv", "ukraine"],
    pop: 37, niche: false,
    vd: { shape: "chip-carved geometric panels over useful forms", line: "solar and wave carving bands", composition: "dense ornament with mountain backdrop", texture: "gleaming inlay, glazed clay, felt", forms: "chest, tile, horn, vest, egg" },
    typ: { display: "carved-wood display serif", body: "sturdy sans", notes: "craft-market warmth" },
    fnt: { display: "Philosopher", body: "PT Sans", notes: "Cyrillic-friendly pairing" },
    lit: { quality: "mountain sun through pine", direction: "dappled side light", temperature: "warm days, cold nights", shadow: "deep forest shade" },
    pho: { approach: "craftsperson portraits and mountain-valley landscapes", grade: "earthy saturated film" },
    fash: { silhouettes: "fitted embroidered shirts with wide belts", garments: "keptar vests, wide leather belts, felt hats", acc: "topirky axes, beads, tassels" },
    env: { places: "polonyna sheep runs, timber churches, market streets", weather: "mountain storms and clear cold nights" },
    gd: { layout: "carved-border frames", icon: "solar rosette chip-carving" },
    ui: { background: "#5d4327", surface: "inlaid wood tiles", components: "rosette icon chips", motion: "trembita-swell transitions" },
    rec: { materials: "wood, clay, wool, brass", lighting: "open-hearth glow", objects: "chests, tiles, pysanky, horns", music: "trembita calls and Hutsul fiddle", scent: "pine smoke, sheep wool, beeswax" },
    snd: ["trembita long calls", "drymba jaw harp", "mountain wind"],
    dna: { mi: 30, og: 80, wc: 20, ns: 35, ad: 10, hf: 12, rr: 50, ps: 45, sh: 55, ql: 60, oc: 45, ds: 70, rs: 35, eu: 45, np: 45 },
    emo: { warm: 70, cold: 35, playful: 50, serious: 50, chaotic: 30, ordered: 55, nostalgic: 70, futuristic: 15, peaceful: 55, ominous: 25 },
  },
  {
    n: "Lithuanian cross crafting", a: ["kryždirbystė", "stogastulpis shrine poles", "Lithuanian wayside crosses"],
    cat: "Religious & Sacred Art", c: "wayside cross and shrine carving", e: "regional_tradition",
    o: "Lithuania", g: "Lithuania, especially Dzūkija, Aukštaitija and Samogitia; Hill of Crosses near Šiauliai",
    p: "centuries-old practice; UNESCO listing 2008", era: "living folk sacral craft",
    sum: "Kryždirbystė — Lithuanian cross-crafting — fills roadsides, crossroads and graveyards with carved oak crosses and roofed shrine poles, a symbolism UNESCO inscribed in 2008.",
    desc: "Across Lithuania, self-taught master cross-crafters (kryždirbiai) raise oak crosses and stogastulpiai — poles roofed with little shingled chapels — at roadsides, crossroads, farms and graves, to keep vows, honour the dead, seek healing or guard travellers. Forms stack pagan solar, plant and bird ornament onto Christian crosses, each piece distinct and often painted or gilded. The self-taught itinerant Vincas Svirskis (1835-1916) became legendary for double-sided crosses that pivot on their posts. Craft knowledge passed informally from master to apprentice, and UNESCO inscribed Cross-crafting and its Symbolism in Lithuania on the Representative List in 2008. The Hill of Crosses near Šiauliai, packed with tens of thousands of offerings, is the tradition's most famous emblem, while Rumšiškės open-air museum preserves carved shrines and gates.",
    col: [{ h: "#a97b42", n: "honey oak" }, { h: "#6d675e", n: "roof shingle grey" }, { h: "#5f7f9e", n: "painted sky blue" }, { h: "#c8a44a", n: "gold leaf" }, { h: "#ede7d8", n: "limewash white" }],
    m: ["oak timber", "shingle laths", "oil paints and gilding", "forged iron details"],
    tx: ["deep-relief carving", "weathered silvered oak", "brush-painted figures", "shingle scale"],
    obj: ["monumental oak crosses", "stogastulpis roofed poles", "roofed chapel niches", "solar and bird carvings", "double-sided Svirskis crosses"],
    ex: ["Hill of Crosses near Šiauliai", "Vincas Svirskis' double-sided crosses of the Ukmergė region", "Rumšiškės Open-Air Museum shrine collection"],
    inf: ["pagan Balt solar symbolism", "Catholic devotional woodcarving"],
    rel: ["Khachkar cross-stone", "Ethiopian processional crosses", "Breton calvary sculpture"],
    par: "European devotional folk art", var: ["stogastulpiai", "koplytstulpiai shrine posts", "Rūpintojėlis pensive Christ"], cf: ["Galician cruceiros", "Alpine wayside shrines"],
    src: [
      { n: "Wikipedia — Lithuanian Cross Crafting", u: "https://en.wikipedia.org/wiki/Lithuanian_cross_crafting", t: "B" },
      { n: "UNESCO — Cross-crafting and its Symbolism in Lithuania", u: "https://ich.unesco.org/en/RL/cross-crafting-and-its-symbolism-in-lithuania-01098", t: "A" },
    ],
    tg: ["lithuania", "kryzdirbyste", "cross", "oak", "unesco"],
    pop: 34, niche: true,
    vd: { shape: "tall vertical crosses with little roofs", line: "gable-topped pole silhouettes", composition: "single marker against sky or dense hill clusters", texture: "carved oak, gilding, paint", forms: "cross, roofed niche, sun, bird" },
    typ: { display: "woodcut display serif", body: "humanist sans", notes: "field-guide tone" },
    fnt: { display: "Marcellus", body: "Source Sans Pro", notes: "lapidary display echoes carved lettering" },
    lit: { quality: "quiet Baltic overcast with silver breaks", direction: "low side light across relief", temperature: "cool-neutral", shadow: "soft and atmospheric" },
    pho: { approach: "lone-cross studies and dense cross-field compositions", grade: "muted silver-green grade" },
    fash: { silhouettes: "plain rural dress", garments: "wool coats, headscarves", acc: "rosaries and amber beads" },
    env: { places: "crossroads, churchyards, hill fields", weather: "changeable Baltic skies" },
    gd: { layout: "vertical marker centred in whitespace", icon: "roofed cross glyph" },
    ui: { background: "#ede7d8", surface: "oak texture panels", components: "gable-top cards", motion: "slow wind-sway loops" },
    rec: { materials: "oak, shingle, gilding", lighting: "candle and votive light", objects: "carving gouges, votive flowers, rosaries", music: "Lithuanian sutartinės songs", scent: "cut oak, rain, incense" },
    snd: ["sutartinė polyphony", "wind through carved eaves", "distant church bells"],
    dna: { mi: 45, og: 65, wc: 15, ns: 30, ad: 12, hf: 12, rr: 55, ps: 45, sh: 60, ql: 60, oc: 50, ds: 65, rs: 35, eu: 50, np: 45 },
    emo: { warm: 55, cold: 45, playful: 20, serious: 70, chaotic: 15, ordered: 60, nostalgic: 75, futuristic: 5, peaceful: 65, ominous: 30 },
  },
  {
    n: "Sorbian egg decorating", a: ["Sorbian Easter eggs", "wósmorske jajka", "Lusatian wax-resist eggs"],
    cat: "Textile & Craft", c: "wax-resist egg decoration", e: "regional_tradition",
    o: "Lusatia (Saxony and Brandenburg), Germany", g: "Upper and Lower Lusatia around Bautzen, Cottbus, Schleife and Hoyerswerda",
    p: "centuries-old, documented from the 18th century", era: "living folk craft",
    sum: "Sorbian craftswomen of Lusatia turn Easter eggs into lace-fine wax-resist and scratched artworks in red, black and green.",
    desc: "In Sorbian villages between Bautzen and Cottbus, decorating eggs is a community art passed down in families and clubs. Several techniques coexist: wax batik drawn with pin-heads and goose quills, engraving scratched through dyed colour, and etching. Motifs — suns, roosters, flowers, waves and geometric crosses — belong to a shared West Slavic sign vocabulary, worked in reds, blacks and greens over natural brown or blown white shells, the finest pieces rivalling lace. Eggs are exchanged at Easter, entered at village competitions and Easter markets, and collected by institutions such as the Sorbian Museum in Bautzen. Around the craft lives the wider Sorbian Easter, including the Osterreiter, Easter-morning riders who process between villages carrying the news of the resurrection.",
    col: [{ h: "#a02622", n: "wax red" }, { h: "#221d19", n: "black ink" }, { h: "#4c7a3f", n: "leaf green" }, { h: "#b08a5a", n: "shell brown" }, { h: "#f0e9d8", n: "blown shell cream" }],
    m: ["hen and goose eggshells", "beeswax", "egg dyes", "goose quills and pins"],
    tx: ["raised wax lines", "layered dye depth", "incised scratch lines", "delicate shell sheen"],
    obj: ["wax-resist eggs", "engraved eggs", "pin-stylus wax pens", "Easter market displays", "Osterreiter processions"],
    ex: ["Sorbian Museum, Bautzen — egg collections", "Easter egg markets of Upper Lusatian villages", "Osterreiter Easter-morning processions"],
    inf: ["West Slavic wax-resist egg traditions", "Christian Easter symbolism"],
    rel: ["Latvian folk symbols and midsummer", "Hutsul Carpathian folk culture", "Seto culture"],
    par: "West Slavic Easter customs", var: ["wax batik technique", "engraved technique", "etched technique"], cf: ["Ukrainian pysanka", "Polish pisanki"],
    src: [
      { n: "Wikipedia — Sorbs", u: "https://en.wikipedia.org/wiki/Sorbs", t: "B" },
      { n: "Wikipedia — Easter Egg", u: "https://en.wikipedia.org/wiki/Easter_egg", t: "B" },
    ],
    tg: ["sorbian", "lusatia", "easter egg", "wax resist", "craft"],
    pop: 29, niche: true,
    vd: { shape: "oval fields of radial and border motifs", line: "hairline wax ridges", composition: "star and band zones divided by meanders", texture: "waxy raised lines over dye", forms: "sun, rooster, tulip, wave, cross" },
    typ: { display: "hand-drawn display", body: "friendly sans", notes: "folk-workshop charm" },
    fnt: { display: "Amatic SC", body: "Mulish", notes: "condensed hand strokes echo quill lines" },
    lit: { quality: "bright spring window light", direction: "soft top light for shell sheen", temperature: "warm-neutral", shadow: "tiny, shell-cradled" },
    pho: { approach: "macro egg portraits and maker hand sequences", grade: "clean pastel spring grade" },
    fash: { silhouettes: "traditional Sorbian dress", garments: "embroidered blouses, dark skirts", acc: "ribbon bonnets and bead necklaces" },
    env: { places: "kitchen tables, village halls, Easter churchyards", weather: "early spring chill and sun" },
    gd: { layout: "egg-grid showcase", icon: "sun-and-wave egg motif" },
    ui: { background: "#f0e9d8", surface: "shell texture cards", components: "wax-line dividers", motion: "dye-bloom reveals" },
    rec: { materials: "shell, beeswax, dye", lighting: "morning kitchen window light", objects: "quill styluses, dye cups, baskets", music: "Sorbian choral and fiddle music", scent: "beeswax, dye vinegar, spring flowers" },
    snd: ["Sorbian choir songs", "gentle kitchen clatter", "Easter bells"],
    dna: { mi: 40, og: 75, wc: 15, ns: 35, ad: 10, hf: 10, rr: 55, ps: 45, sh: 50, ql: 70, oc: 60, ds: 60, rs: 30, eu: 45, np: 45 },
    emo: { warm: 75, cold: 25, playful: 60, serious: 45, chaotic: 15, ordered: 70, nostalgic: 80, futuristic: 5, peaceful: 70, ominous: 5 },
  },
  {
    n: "Czech puppetry", a: ["Czech marionettes", "Czech puppet theatre", "Spejbl and Hurvínek tradition"],
    cat: "Regional & Cultural Tradition", c: "marionette theatre", e: "regional_tradition",
    o: "Bohemia, Habsburg lands", g: "Czechia, notably Prague and Plzeň and the touring family stages between",
    p: "18th century onward; UNESCO listing 2016", era: "baroque to living tradition",
    sum: "Czech puppetry runs from itinerant Baroque marionettists through Spejbl and Hurvínek to Prague's puppet Don Giovanni, a tradition UNESCO inscribed with Slovakia in 2016.",
    desc: "Marionette theatre took root in Bohemia in the eighteenth century with itinerant dynasties like the Kopecký family, playing folk-cast operas and comedies in village barns and inns — and, under a German-language theatre monopoly, giving Czech its own stage voice. Carved linden marionettes with jointed, expressive faces became the craft's signature. The twentieth century added Josef Skupa's comic schoolmaster Spejbl (1920) and rascal Hurvínek (1926), radio and film stars whose Prague theatre still tours. The National Marionette Theatre in Prague has staged Mozart's Don Giovanni with marionettes since 1991, Plzeň keeps a dedicated puppet museum, and UNESCO inscribed Puppet Theatre in Slovakia and Czechia on the Representative List in 2016. Carving workshops now supply both heritage stages and a global collector market.",
    col: [{ h: "#b78d5e", n: "linden wood" }, { h: "#8e2f2f", n: "stage crimson" }, { h: "#ece5d5", n: "greasepaint white" }, { h: "#c39a4e", n: "proscenium gold" }, { h: "#2e3a5c", n: "velvet navy" }],
    m: ["linden wood", "painter's colours", "wire joints and strings", "velvet curtain cloth"],
    tx: ["carved wood grain", "varnished painted faces", "worn velvet", "brass fittings"],
    obj: ["carved marionettes", "Spejbl and Hurvínek figures", "toy prosceniums", "wooden control crosses", "travelling puppet booths"],
    ex: ["National Marionette Theatre's Don Giovanni, Prague", "Spejbl and Hurvínek Theatre, Prague", "Puppet Museum, Plzeň"],
    inf: ["Jesuit school drama", "Habsburg popular theatre"],
    rel: ["Sicilian opera dei pupi", "French Guignol puppetry", "Kasperle theatre"],
    par: "European puppet theatre", var: ["marionette opera", "Spejbl and Hurvínek revue", "Kašpárek hand-puppet plays"], cf: ["Kasperle hand puppets", "opera dei pupi"],
    src: [
      { n: "UNESCO — Puppet Theatre in Slovakia and Czechia", u: "https://ich.unesco.org/en/RL/puppet-theatre-in-slovakia-and-czechia-00999", t: "A" },
      { n: "Wikipedia — Spejbl and Hurvínek", u: "https://en.wikipedia.org/wiki/Spejbl_and_Hurv%C3%ADnek", t: "B" },
    ],
    tg: ["czech", "puppetry", "marionette", "prague", "unesco"],
    pop: 43, niche: false,
    vd: { shape: "jointed figure silhouettes on tiny stages", line: "articulated strings and carved arcs", composition: "toy proscenium framing", texture: "painted wood, velvet, string", forms: "marionette, booth, control cross, curtain" },
    typ: { display: "playbill display serif", body: "friendly sans", notes: "vintage theatre-playbill charm" },
    fnt: { display: "Bree Serif", body: "Nunito Sans", notes: "rounded warmth suits toy theatre" },
    lit: { quality: "warm footlit stage glow", direction: "low front light from the booth", temperature: "warm", shadow: "big and theatrical behind figures" },
    pho: { approach: "stage portraits and workshop carving scenes", grade: "amber theatre grade" },
    fash: { silhouettes: "playful period costume on figures", garments: "folk waistcoats, comic tails and caps", acc: "tiny props, strings and control bars" },
    env: { places: "village barns, inn stages, small theatres", weather: "indoor warmth against winter touring" },
    gd: { layout: "proscenium-framed hero areas", icon: "crossed control-bar glyph" },
    ui: { background: "#2e3a5c", surface: "velvet texture panels", components: "curtain-swipe components", motion: "curtain rises and string-bounce motions" },
    rec: { materials: "linden wood, paint, velvet", lighting: "footlights and booth lamps", objects: "marionettes, booths, playbills", music: "Mozart overtures and folk tunes", scent: "wood shavings, greasepaint, old velvet" },
    snd: ["creaking control bars", "children's laughter", "toy-trumpet overtures"],
    dna: { mi: 35, og: 70, wc: 25, ns: 35, ad: 20, hf: 15, rr: 50, ps: 55, sh: 55, ql: 65, oc: 40, ds: 65, rs: 35, eu: 55, np: 45 },
    emo: { warm: 75, cold: 25, playful: 85, serious: 35, chaotic: 35, ordered: 55, nostalgic: 80, futuristic: 20, peaceful: 50, ominous: 20 },
  },
  {
    n: "Slovak fujara", a: ["fujara flute", "Podpoľanie overtone flute", "shepherd's fujara"],
    cat: "Music & Sonic Culture", c: "overtone bass flute", e: "regional_tradition",
    o: "Podpoľanie region, central Slovakia", g: "Podpoľanie around Detva and Očová; Slovak folk festivals nationwide",
    p: "documented from the 18th century; UNESCO listing 2008", era: "shepherd tradition to national symbol",
    sum: "The fujara, an up-to-two-metre overtone bass flute from Podpoľanie, turns Slovak shepherd solitude into UNESCO-listed music.",
    desc: "The fujara is a contrabass duct flute of 160-200 cm, played upright with a small parallel mouth tube feeding the main elder-wood bore, its three finger-holes coaxing deep, breathy overtones. Born among Podpoľanie shepherds around Detva and Očová who guarded dispersed flocks on the poľana hills, it was the lone herdsman's instrument for signals and long improvised meditations — typically a slow solemn prelude, a rippling middle and a calm close. Players decorate the wood with carved and painted folk ornament. UNESCO proclaimed fujara music a Masterpiece in 2005 and inscribed Fujara Flute and its Music on the Representative List in 2008; the fujara now stars at the Východná and Detva folk festivals and in world-music ensembles, its relative the koncovka keeping the overtone tradition alive in miniature.",
    col: [{ h: "#b58a4e", n: "elder wood honey" }, { h: "#4a3524", n: "carved soot brown" }, { h: "#647a45", n: "pasture green" }, { h: "#4f6b86", n: "storm blue" }, { h: "#efe8d8", n: "sheep fleece cream" }],
    m: ["elder-wood body", "hemp cords", "carved geometric ornament", "beeswax finish"],
    tx: ["long bored grain", "chip-carved bands", "waxed sheen", "breath-worn mouthpiece"],
    obj: ["fujara bass flute", "side mouthpiece tube", "carved ornament bands", "three finger holes", "shepherd's felt cloak"],
    ex: ["fujara players of Detva, Podpoľanie", "Východná folk festival performances", "UNESCO inscription Fujara Flute and its Music, 2008"],
    inf: ["Carpathian overtone flute practice", "Podpoľanie ornament carving"],
    rel: ["Alpine alphorn", "Hutsul Carpathian folk culture", "willow flute traditions"],
    par: "Carpathian pastoral music", var: ["koncovka overtone flute", "festival fujara variants", "Detva ornament school"], cf: ["koncovka flute", "trembita horn"],
    src: [
      { n: "Wikipedia — Fujara", u: "https://en.wikipedia.org/wiki/Fujara", t: "B" },
      { n: "UNESCO — Fujara Flute and its Music", u: "https://ich.unesco.org/en/RL/fujara-flute-and-its-music-00090", t: "A" },
    ],
    tg: ["slovakia", "fujara", "flute", "podpolanie", "shepherd"],
    pop: 33, niche: true,
    vd: { shape: "towering vertical flute against a hill line", line: "carved horizontal ornament bands", composition: "lone player in a big landscape", texture: "waxed wood, wool, wind", forms: "tube, mouthpiece tube, carving, cloak" },
    typ: { display: "rustic display serif", body: "clean sans", notes: "festival-poster tone" },
    fnt: { display: "Fjalla One", body: "Spectral", notes: "condensed display with warm book body" },
    lit: { quality: "soft upland daylight", direction: "backlight through breath and dust", temperature: "cool-warm mixed", shadow: "long pastoral shadows" },
    pho: { approach: "player-against-landscape portraits", grade: "natural documentary grade" },
    fash: { silhouettes: "loose shepherd layers", garments: "embroidered vests, wide leather belts, hats", acc: "valaška staffs, hat feathers" },
    env: { places: "poľana hill pastures, festival stages", weather: "mountain wind and summer storms" },
    gd: { layout: "tall vertical instrument hero", icon: "carved-band flute glyph" },
    ui: { background: "#efe8d8", surface: "wood grain panels", components: "carved-band headers", motion: "breath-swell loops" },
    rec: { materials: "elder wood, wax, wool", lighting: "late golden pasture light", objects: "fujara, shepherd crooks, bells", music: "solo fujara meditations", scent: "hay, wood smoke, rain on grass" },
    snd: ["deep fujara overtones", "pasture cowbells", "mountain wind"],
    dna: { mi: 55, og: 75, wc: 15, ns: 35, ad: 15, hf: 12, rr: 55, ps: 50, sh: 55, ql: 65, oc: 40, ds: 60, rs: 35, eu: 50, np: 50 },
    emo: { warm: 60, cold: 35, playful: 30, serious: 50, chaotic: 15, ordered: 55, nostalgic: 75, futuristic: 10, peaceful: 80, ominous: 15 },
  },
];
