/**
 * Curated wave — Africa III (part 2 of 2): Horn & East Africa, Southern Africa,
 * Indian Ocean creole, Sahel/Chad Basin, Congo-adjacent leftovers. Hand-authored,
 * real documented traditions. Complements africa.ts and wave2-africa-2.ts.
 */
export const WAVE_AFR3: any[] = [
  {
    n: "Ethiopian healing scrolls", a: ["Ethiopian magic scrolls", "talismanic scrolls", "Ge'ez healing scrolls"],
    cat: "Religious & Sacred Art", c: "talismanic manuscript scrolls", e: "historical", o: "Ethiopian Highlands (Amhara, Tigray)", g: "Ethiopia, Eritrea, diaspora museum collections",
    p: "18th century–early 20th century", era: "Solomonic-era manuscript culture",
    sum: "Parchment talismanic scrolls in Ge'ez script, written and drawn by dabtara clerics with prayers, magic seals and a staring face at the head, commissioned to heal and protect.",
    desc: "In the Ethiopian Highlands, church-trained dabtara clerics prepare talismanic scrolls on parchment for clients seeking healing or protection from illness, misfortune and the evil eye. Written in Ge'ez with prayers, divine names and grids of magic seals, the scrolls are crowned by a striking round face ringed by staring eyes — the 'eyes of the scroll' — a demon-binding image, sometimes with sewn medicine pouches still attached. Scrolls were traditionally cut to the height of the person they protect, carried on the body, hung at home or kept beside the bed, and commissioned anew rather than inherited. Collected since the eighteenth century, Ethiopian healing scrolls now hang in the Met, the British Library and the Musée du quai Branly as one of Africa's most distinctive manuscript arts.",
    col: [{ h: "#d9b982", n: "parchment tan" }, { h: "#1e1a14", n: "iron-gall black" }, { h: "#a5342a", n: "seal vermilion" }, { h: "#2c3a55", n: "indigo marginalia" }, { h: "#8c6f4a", n: "aged leather" }],
    m: ["vellum parchment", "iron-gall ink", "red ochre pigment", "sewn medicine pouches"],
    tx: ["hairline script bands", "seal-grid lattices", "radiating eye lines", "worn parchment scuffs"],
    obj: ["rolled healing scrolls", "eye-face medallions", "magic seal lattices", "dabtara ink pots", "leather talisman cases"],
    ex: ["Ethiopian healing scrolls in The Met collection", "British Library Ge'ez magic-scroll collections", "dabtara-commissioned scrolls of Lasta and Tigray"],
    inf: ["Ge'ez liturgical book arts", "Semitic talisman traditions"], rel: ["Ethiopian church murals", "Ethiopian processional crosses", "Timbuktu manuscripts"],
    par: "Ethiopian Orthodox manuscript tradition", var: ["long full-body scrolls", "short home-scrolls"], cf: ["Ethiopian church murals"],
    src: [{ n: "Wikipedia — Magic scroll", u: "https://en.wikipedia.org/wiki/Magic_scroll", t: "B" }, { n: "The Metropolitan Museum of Art", u: "https://www.metmuseum.org", t: "A" }],
    tg: ["ethiopia", "scroll", "talisman", "ge'ez", "manuscript"], pop: 26, niche: true,
    vd: { shape: "long vertical roll", line: "flowing Ge'ez ductus", composition: "text bands crowned by a face medallion", texture: "parchment grain with iron-gall bite", forms: "eyes, seal lattices, stars, bound demons" },
    typ: { display: "quiet serif", body: "humanist sans", notes: "museum-caption restraint with liturgical gravity" },
    fnt: { display: "Cormorant Garamond", body: "IBM Plex Sans", notes: "archival serif suits Ge'ez-adjacent manuscript setting" },
    lit: { quality: "single warm spot", direction: "raking", temperature: "warm", shadow: "ink bite on parchment" },
    pho: { approach: "manuscript photography on neutral ground", grade: "warm low-key, ochre lift" },
    fash: { silhouettes: "robed clerical column", garments: "white shemma tunics", acc: "leather talisman cases, crosses" },
    env: { places: "highland church courtyards, scribe sheds", weather: "cool highland light" },
    gd: { layout: "single-column scroll band", icon: "eye-face medallion" },
    ui: { background: "#d9b982", surface: "parchment-tone cards", components: "seal-grid dividers", motion: "ink-write reveal" },
    rec: { materials: "parchment, ink, red ochre", lighting: "candle-warm raking", objects: "scroll, ink pot, herbs", music: "Ge'ez chant (zema)", scent: "incense, vellum" },
    snd: ["Ge'ez chant drone", "kebero drum", "page rustle"],
    dna: { mi: 20, og: 70, wc: 10, ns: 15, ad: 10, hf: 5, rr: 55, ps: 30, sh: 40, ql: 20, oc: 65, ds: 55, rs: 45, eu: 75, np: 35 },
    emo: { warm: 55, cold: 35, playful: 15, serious: 80, chaotic: 25, ordered: 70, nostalgic: 70, futuristic: 10, peaceful: 45, ominous: 45 },
  },
  {
    n: "Habesha kemis dress", a: ["habesha kemis", "Ethiopian tibeb dress", "shemma cotton dress"],
    cat: "Fashion & Dress", c: "border-woven national dress", e: "regional_tradition", o: "Ethiopian and Eritrean Highlands", g: "Ethiopia, Eritrea, diaspora communities",
    p: "19th century–present", era: "modern national dress",
    sum: "Ivory handwoven cotton dresses edged in brilliant tibeb border bands — Ethiopia and Eritrea's national dress for holidays, weddings and church feasts.",
    desc: "Habesha kemis is the white or ivory cotton dress worn by Ethiopian and Eritrean women at holidays, weddings and church feasts, cut long and often smocked with fine pleats at the bodice. Its signature is the tibeb — bands of patterned weaving in gold, red, green and purple — laid along hem, cuffs and neckline, running for meters on bridal versions. The cloth is shemma, woven in narrow strips on pit looms and joined edge-to-edge, traditionally by male weavers; women pair the dress with the netela shawl or the heavier kaba velvet cape. After decades of plain imported styles, habesha fashion houses in Addis Ababa and diaspora designers have made tibeb a booming identity marker, now a fixture of Ethiopian runways, music videos and Timkat street style.",
    col: [{ h: "#f4efe2", n: "ivory kemis" }, { h: "#c99a2e", n: "tibeb gold" }, { h: "#a83b2a", n: "tibeb red" }, { h: "#3f6b46", n: "tibeb green" }, { h: "#6a3d6e", n: "tibeb purple" }],
    m: ["handwoven shemma cotton", "tibeb border bands", "netela shawl weave", "velvet kaba"],
    tx: ["smocked bodice pleats", "strip-joined weave lines", "dense border patterning", "airy plain weave"],
    obj: ["kemis dresses", "netela shawls", "kaba velvet capes", "pit looms", "bridal tibeb panels"],
    ex: ["Timkat and Meskel street dress in Addis Ababa", "habesha wedding sets with meter-long tibeb", "Addis Ababa fashion-house tibeb collections"],
    inf: ["Ethiopian Orthodox feast calendar", "highland handloom guilds"], rel: ["Kente cloth", "Aso oke weaving", "Adire indigo dyeing"],
    par: "Highland Ethiopian dress", var: ["zuria", "bridal tibeb dress"], cf: ["Kanga cloth"],
    src: [{ n: "Wikipedia — Habesha kemis", u: "https://en.wikipedia.org/wiki/Habesha_kemis", t: "B" }, { n: "Google Arts & Culture", u: "https://artsandculture.google.com", t: "A" }],
    tg: ["ethiopia", "eritrea", "tibeb", "cotton", "national dress"], pop: 42, niche: false,
    vd: { shape: "long flowing column with border bands", line: "crisp pleat lines", composition: "white field against dense hem borders", texture: "crisp handloom cotton", forms: "cross motifs, diamond bands, foliate tibeb" },
    typ: { display: "elegant serif", body: "humanist sans", notes: "bridal-editorial warmth" },
    fnt: { display: "Playfair Display", body: "Karla", notes: "high-contrast serif echoes pleat and border elegance" },
    lit: { quality: "highland bright", direction: "frontal", temperature: "warm", shadow: "soft pleat shadow" },
    pho: { approach: "outdoor fashion editorial", grade: "airy warm whites" },
    fash: { silhouettes: "floor-length A-line", garments: "kemis, netela, kaba", acc: "albaso braids, silver crosses" },
    env: { places: "Timkat processions, Entoto hills", weather: "dry-season highland sun" },
    gd: { layout: "full-length portrait bands", icon: "tibeb border stripes" },
    ui: { background: "#f4efe2", surface: "ivory cards with tibeb rules", components: "border-ribbon buttons", motion: "fabric sway parallax" },
    rec: { materials: "handloom cotton, velvet, gold thread", lighting: "soft daylight", objects: "dress form, shawl, coffee set", music: "Ethio-jazz, masinko", scent: "frankincense, coffee" },
    snd: ["masinko fiddle", "washint flute", "kebero drum"],
    dna: { mi: 35, og: 60, wc: 20, ns: 20, ad: 15, hf: 45, rr: 40, ps: 55, sh: 45, ql: 35, oc: 50, ds: 60, rs: 35, eu: 60, np: 50 },
    emo: { warm: 75, cold: 25, playful: 45, serious: 50, chaotic: 20, ordered: 70, nostalgic: 70, futuristic: 35, peaceful: 60, ominous: 10 },
  },
  {
    n: "Somali alindi weaving", a: ["alindi cloth", "Somali handwoven stripes", "guntiino cloth"],
    cat: "Textile & Craft", c: "strip-woven handloom cloth", e: "regional_tradition", o: "Somalia (Benadir and riverine towns)", g: "Somalia, Djibouti, Somali Region of Ethiopia",
    p: "pre-colonial–present", era: "Indian Ocean trade era",
    sum: "Strip-woven handloom cloth with bold multicolor bands, woven in Somalia and tailored into the guntiino wrap and circulated as bridal gift and trade textile.",
    desc: "Alindi is Somalia's traditional handwoven cloth, produced in narrow strips on pit-treadle looms and sewn selvedge-to-selvedge into wraps and garments. Its look is instantly recognizable: saturated horizontal bands — indigo, coral, gold, black and white — punctuated by fine accent lines, with weaver households keeping signature stripe orders. Alindi is tailored above all into the guntiino, the women's wrap draped over one shoulder and fastened with paired clasps, and it circulates as bridal gift, dowry textile and long-distance trade cloth alongside imported Indian cottons. Woven in Mogadishu and riverine market towns, the cloth survives through small workshops and heritage labels reviving its stripe palettes for contemporary dirac and abaya styles.",
    col: [{ h: "#26355c", n: "band indigo" }, { h: "#c4503a", n: "band coral" }, { h: "#d3a03c", n: "band gold" }, { h: "#17171a", n: "band black" }, { h: "#efe8d8", n: "chalk white" }],
    m: ["pit-treadle looms", "cotton yarn", "indigo and alizarin dyes", "imported metallic thread"],
    tx: ["flat banded stripes", "selvedge joins", "fine pinstripe rhythm", "soft worn cotton"],
    obj: ["alindi cloth rolls", "guntiino wraps", "loom benches", "trade bales", "bridal stripe panels"],
    ex: ["guntiino wraps of Mogadishu households", "alindi bridal gifts in riverine towns", "heritage-label alindi stripe revivals"],
    inf: ["Indian Ocean cotton trade", "Somali weaver lineages"], rel: ["Kanga cloth", "Aso oke weaving", "Atlas silk Uzbek ikat"],
    par: "Somali textile tradition", var: ["guntiino stripes", "bridal alindi"], cf: ["Kanga cloth"],
    src: [{ n: "Wikipedia — Culture of Somalia", u: "https://en.wikipedia.org/wiki/Culture_of_Somalia", t: "B" }, { n: "Google Arts & Culture", u: "https://artsandculture.google.com", t: "A" }],
    tg: ["somalia", "weaving", "stripes", "guntiino", "indian ocean"], pop: 22, niche: true,
    vd: { shape: "long rectangular wrap", line: "strict horizontal banding", composition: "rhythmic stripe color order", texture: "soft handloom slub", forms: "bands, pinstripes, selvedge lines" },
    typ: { display: "grotesque display", body: "geometric sans", notes: "stripe-derived modular type" },
    fnt: { display: "Archivo", body: "Manrope", notes: "banded grotesque mirrors stripe rhythm" },
    lit: { quality: "even bright", direction: "frontal", temperature: "warm-neutral", shadow: "minimal" },
    pho: { approach: "textile flat-lay and draped mannequin", grade: "clean neutral with saturated bands" },
    fash: { silhouettes: "one-shoulder draped wrap", garments: "guntiino, dirac", acc: "silver clasps, beaded neck pouch" },
    env: { places: "Mogadishu markets, riverine weaving towns", weather: "hot coastal light" },
    gd: { layout: "banded stripe grid", icon: "stripe motifs" },
    ui: { background: "#26355c", surface: "stripe-banded cards", components: "tab banding", motion: "stripe slide" },
    rec: { materials: "cotton, dyes, loom wood", lighting: "bright even", objects: "loom, bales, clasp pair", music: "heello poetry with oud", scent: "indigo, gum arabic" },
    snd: ["heello verse", "loom treadle rhythm", "coastal wind"],
    dna: { mi: 30, og: 55, wc: 10, ns: 10, ad: 10, hf: 20, rr: 45, ps: 35, sh: 40, ql: 20, oc: 60, ds: 65, rs: 40, eu: 55, np: 40 },
    emo: { warm: 60, cold: 30, playful: 40, serious: 50, chaotic: 20, ordered: 75, nostalgic: 65, futuristic: 25, peaceful: 50, ominous: 10 },
  },
  {
    n: "Turkana adornment", a: ["Turkana beadwork", "Turkana dress", "ekicholong headrest culture"],
    cat: "Fashion & Dress", c: "beaded body ornament", e: "regional_tradition", o: "Turkana County, northwestern Kenya", g: "Lake Turkana basin, Kenya–Uganda borderlands",
    p: "19th century–present", era: "living pastoral tradition",
    sum: "Beaded collars, brass coils and ochre-patina hair ornament the Turkana pastoralists of Lake Turkana's arid country.",
    desc: "The Turkana are semi-nomadic herders of the arid lands west of Lake Turkana, and their dress is built for desert color and cattle wealth. Women wear wide flat collars and disk necklaces of layered glass beads strung on leather, brass and aluminum wire bangles, long pierced earlobes loaded with coils, and leather skirts trimmed with ostrich eggshell and metal; hair is worked up with ochre and animal fat into glossy sculptural forms. Men carry the ekicholong — a carved wooden headrest that doubles as a stool and protects elaborate hairstyles — along with wrist knives and finger knives worn as tools and status. Bead color, quantity and material encode age-set, wealth and clan standing, and Turkana ensembles anchor the Lake Turkana Cultural Festival alongside neighboring Samburu and Pokot dress.",
    col: [{ h: "#9c4a26", n: "ochre rust" }, { h: "#274a7a", n: "bead blue" }, { h: "#c2c5c9", n: "aluminum grey" }, { h: "#7a5c34", n: "leather tan" }, { h: "#1f1a16", n: "hide black-brown" }],
    m: ["glass beads on wire", "brass and aluminum wire", "leather hides", "ostrich eggshell"],
    tx: ["tight bead rows", "coiled wire rings", "fat-glossed ochre", "scarred leather"],
    obj: ["layered bead collars", "ekicholong headrests", "wrist knives", "finger knives", "brass ear coils"],
    ex: ["Turkana beadwork in National Museums of Kenya collections", "ekicholong headrests in East African ethnography collections", "Lake Turkana Cultural Festival dress"],
    inf: ["Karamojong-cluster bead language", "cattle-wealth exchange"], rel: ["Samburu beadwork", "Zulu beadwork", "Plains beadwork"],
    par: "Nilotic pastoral adornment", var: ["women's disk collars", "men's headrest dress"], cf: ["Samburu beadwork"],
    src: [{ n: "Wikipedia — Turkana people", u: "https://en.wikipedia.org/wiki/Turkana_people", t: "B" }, { n: "National Museums of Kenya", u: "https://www.museums.or.ke", t: "A" }],
    tg: ["turkana", "kenya", "beadwork", "pastoral", "ochre"], pop: 34, niche: false,
    vd: { shape: "torus collars and stacked disks", line: "concentric bead rings", composition: "body as vertical totem", texture: "ochre matte against metal shine", forms: "disks, coils, spikes, shells" },
    typ: { display: "heavy condensed sans", body: "rounded sans", notes: "sun-hard poster energy" },
    fnt: { display: "Anton", body: "Rubik", notes: "compressed display matches stacked collar mass" },
    lit: { quality: "harsh equatorial sun", direction: "raking", temperature: "hot", shadow: "deep hard edge" },
    pho: { approach: "environmental portraiture", grade: "saturated earth tones" },
    fash: { silhouettes: "stacked collar torso", garments: "beaded leather skirts", acc: "wrist knife, ear coils, headrest" },
    env: { places: "Lake Turkana shores, acacia drylands", weather: "dust, 40°C heat" },
    gd: { layout: "portrait column stack", icon: "concentric circles" },
    ui: { background: "#6f2f18", surface: "leather-tone cards", components: "ring toggles", motion: "bead shift" },
    rec: { materials: "beads, brass, hide", lighting: "hard sun", objects: "headrest, knife, collars", music: "call-and-response herding songs", scent: "dust, ghee, woodsmoke" },
    snd: ["herding song calls", "cattle bells", "dry wind"],
    dna: { mi: 30, og: 60, wc: 5, ns: 5, ad: 5, hf: 10, rr: 60, ps: 30, sh: 45, ql: 20, oc: 40, ds: 65, rs: 50, eu: 60, np: 45 },
    emo: { warm: 65, cold: 25, playful: 35, serious: 60, chaotic: 30, ordered: 55, nostalgic: 60, futuristic: 20, peaceful: 45, ominous: 25 },
  },
  {
    n: "Samburu beadwork", a: ["Samburu collars", "moran beadwork", "Samburu body ornament"],
    cat: "Textile & Craft", c: "beaded collar tradition", e: "regional_tradition", o: "Samburu County, north-central Kenya", g: "Samburu lowlands, Kenya",
    p: "19th century–present", era: "living Maa tradition",
    sum: "Layered disk collars, coiled beaded bands and ochre braids — Samburu 'butterfly people' ornament of north-central Kenya.",
    desc: "The Samburu, Maa-speaking pastoralists of Kenya's Samburu County, keep one of East Africa's most elaborate bead vocabularies. Married women stack great flat collars of layered colored disks — red, white, blue, green, orange — over coiled beaded necklaces and beaded headbands; unmarried moran warriors braid their hair into long ochre-clay plaits and wear beaded belts, earrings and banded wristlets. Colors and pattern orders carry messages about clan, age-set, marriage and cattle wealth, and beaded pieces are made, gifted and re-gifted at every social transition. Since the 1990s Samburu and Maasai beadwork has also become a design export through women's cooperatives, whose collars now hang on global runways and hotel walls and fund village economies.",
    col: [{ h: "#b03a2e", n: "maa red" }, { h: "#f0e8d8", n: "milk white" }, { h: "#24568c", n: "bead cobalt" }, { h: "#3c7a44", n: "bead green" }, { h: "#d9822b", n: "bead amber" }],
    m: ["glass seed beads", "leather backings", "red ochre and animal fat", "wire"],
    tx: ["layered disk edges", "tight spiral coiling", "ochre-plaited hair", "fringe swing"],
    obj: ["layered marriage collars", "coiled beaded necklaces", "moran belts and ear hoops", "beaded headbands", "ochre gourds"],
    ex: ["Samburu marriage collars in Kenyan museum collections", "moran warrior dress at Samburu ceremonies", "beadwork cooperative collars in global fashion shoots"],
    inf: ["Maa age-set system", "cooperative craft economies"], rel: ["Turkana adornment", "Zulu beadwork", "Plains beadwork"],
    par: "Maa pastoral ornament", var: ["married women's disk collars", "moran braid dress"], cf: ["Maasai beadwork", "Turkana adornment"],
    src: [{ n: "Wikipedia — Samburu people", u: "https://en.wikipedia.org/wiki/Samburu_people", t: "B" }, { n: "Google Arts & Culture", u: "https://artsandculture.google.com", t: "A" }],
    tg: ["samburu", "kenya", "beadwork", "moran", "collars"], pop: 36, niche: false,
    vd: { shape: "stacked disk strata", line: "concentric color rings", composition: "neck and shoulders as stage", texture: "bead glint against ochre matte", forms: "disks, spirals, plaits, fringes" },
    typ: { display: "warm serif", body: "rounded sans", notes: "ceremonial-warm pairing" },
    fnt: { display: "Crimson Pro", body: "Nunito Sans", notes: "gentle serif suits layered collar softness" },
    lit: { quality: "morning side light", direction: "frontal", temperature: "warm", shadow: "crisp short shadow" },
    pho: { approach: "ceremonial portraiture", grade: "high-saturation earth" },
    fash: { silhouettes: "shoulder-wide collar stack", garments: "beaded leather capes and skirts", acc: "beaded headbands, ochre braids, cowries" },
    env: { places: "Samburu lowlands, acacia riverbeds", weather: "dry heat, red dust" },
    gd: { layout: "radial collar motifs", icon: "disk rings, plait lines" },
    ui: { background: "#8c2f1f", surface: "bead-plate cards", components: "ring buttons", motion: "collar stack hover" },
    rec: { materials: "beads, leather, ochre", lighting: "warm side sun", objects: "collars, gourd, staff", music: "Samburu herding songs and ululations", scent: "ochre, milk, smoke" },
    snd: ["call-and-response songs", "rattle anklets", "cattle lowing"],
    dna: { mi: 25, og: 65, wc: 5, ns: 5, ad: 5, hf: 25, rr: 50, ps: 40, sh: 50, ql: 25, oc: 45, ds: 75, rs: 45, eu: 60, np: 45 },
    emo: { warm: 70, cold: 20, playful: 45, serious: 55, chaotic: 30, ordered: 60, nostalgic: 55, futuristic: 25, peaceful: 50, ominous: 20 },
  },
  {
    n: "Pokot beadwork", a: ["Pökot ornament", "Pokot brass jewelry", "sapana dress"],
    cat: "Textile & Craft", c: "beaded ornament and age-set dress", e: "regional_tradition", o: "West Pokot, Kenya and Karamoja edge, Uganda", g: "Kerio Valley escarpments, Kenya–Uganda border",
    p: "19th century–present", era: "living Kalenjin tradition",
    sum: "Brass wire, cowries and seed beads assembled into Pokot women's collars and men's age-set dress across West Pokot's escarpments.",
    desc: "The Pokot (Pökot) of Kenya's West Pokot County and the Karamoja edge of Uganda are Kalenjin-speaking herders and cultivators whose ornament is among the most distinctive in East Africa. Women build tall collars and chest panels of glass seed beads over leather, wind brass and iron wire into spirals worn in stretched earlobes, and pile cowries, beads and wire into layered bangles, with bead color and quantity reading household wealth. Young men pass through the sapana initiation into named age-sets, adopting ostrich-feather and fur headdresses, hide armbands and beaded bandoliers for dances where lineages display daughters and herds. Pokot ornament appears in Kenyan national collections and at the Lake Turkana Cultural Festival alongside neighboring Turkana and Samburu ensembles.",
    col: [{ h: "#b58a3a", n: "brass burnish" }, { h: "#a63a2e", n: "seed red" }, { h: "#ece4d2", n: "seed white" }, { h: "#2b2b2e", n: "iron black" }, { h: "#8a6a44", n: "hide tan" }],
    m: ["glass seed beads", "brass and iron wire", "cowrie shells", "leather"],
    tx: ["wire coil spirals", "dense bead panels", "cowrie dome rows", "fur fringe"],
    obj: ["beaded collars", "brass ear coils", "sapana feather headdresses", "banded armlets", "beaded bandoliers"],
    ex: ["West Pokot women's collars in Kenyan museum collections", "sapana initiation dress at age-set dances", "Pokot ensembles at the Lake Turkana Cultural Festival"],
    inf: ["Kalenjin age-set institutions", "Karamoja-cluster exchange"], rel: ["Turkana adornment", "Samburu beadwork", "Zulu beadwork"],
    par: "Kalenjin-Karamoja ornament", var: ["women's collars", "sapana headdress"], cf: ["Samburu beadwork"],
    src: [{ n: "Wikipedia — Pokot people", u: "https://en.wikipedia.org/wiki/Pokot_people", t: "B" }, { n: "National Museums of Kenya", u: "https://www.museums.or.ke", t: "A" }],
    tg: ["pokot", "kenya", "brass", "beadwork", "initiation"], pop: 20, niche: true,
    vd: { shape: "tall collar columns", line: "coil spirals", composition: "wealth read as ornament density", texture: "brass burnish, bead matte", forms: "spirals, bands, feather fans" },
    typ: { display: "geometric display", body: "neutral sans", notes: "structural field-documentary tone" },
    fnt: { display: "Sora", body: "Barlow", notes: "constructed display echoes wire coil geometry" },
    lit: { quality: "escarpment sun", direction: "raking", temperature: "warm", shadow: "hard edge" },
    pho: { approach: "age-set dance documentation", grade: "warm documentary" },
    fash: { silhouettes: "chest-high collar mass", garments: "hide skirts and capes", acc: "ear coils, feathers, bandoliers" },
    env: { places: "West Pokot escarpments, Kerio Valley", weather: "hot days, cool nights" },
    gd: { layout: "vertical collar bands", icon: "coil spiral" },
    ui: { background: "#3a2c18", surface: "brass-toned cards", components: "coil ring icons", motion: "spiral wind-in" },
    rec: { materials: "beads, wire, hide", lighting: "hard side sun", objects: "collar, coils, headdress", music: "Pokot dance songs", scent: "ghee, brass, dust" },
    snd: ["dance chorus", "ankle rattles", "cattle bells"],
    dna: { mi: 25, og: 62, wc: 5, ns: 5, ad: 5, hf: 8, rr: 62, ps: 30, sh: 45, ql: 18, oc: 42, ds: 68, rs: 55, eu: 55, np: 40 },
    emo: { warm: 62, cold: 28, playful: 40, serious: 58, chaotic: 32, ordered: 55, nostalgic: 58, futuristic: 18, peaceful: 45, ominous: 25 },
  },
];
