/**
 * Curated wave — Europe regional & folk, deep II (batch c, file 2/2):
 * Italy, Central Europe, Balkans/Adriatic, Iberia, France & Celtic fringes.
 * Hand-authored; all real, documented traditions. Companion to wave2-europe-3.ts.
 */
export const WAVE_EUF2: any[] = [
  {
    n: "Sicilian Baroque", a: ["Val di Noto Baroque", "Barocco Siciliano", "Noto Baroque"],
    cat: "Architectural Style", c: "Earthquake-rebuilt late Baroque", e: "historical",
    o: "southeastern Sicily", g: "Val di Noto: Noto, Ragusa Ibla, Modica, Catania, Caltagirone, Militello, Scicli, Palazzolo",
    p: "1693-1760s peak", era: "late Baroque",
    sum: "The theatrical honey-limestone Baroque of southeastern Sicily, rebuilt after the 1693 earthquake into grinning masks, voluted balconies and stage-set facades.",
    desc: "After the catastrophic 1693 earthquake levelled southeastern Sicily, nobles and the church rebuilt eight towns almost from scratch, staging a flamboyant regional Baroque in warm honey limestone. Local architects such as Rosario Gagliardi, Andrea Palma and Giovanni Battista Vaccarini composed facades like theatre scenery: broken pediments, bunched columns, and balconies carried on volute corbels carved with grinning masks, putti and grotesques. Earthquake logic favoured broad, low, buttressed masses, while Spanish and Roman ornamental currents pushed the carving ever wilder. Modica's San Giorgio and Noto's cathedral stair-scenography became style icons, and the late start let the style bloom into almost Rococo exuberance. UNESCO inscribed the Late Baroque Towns of the Val di Noto in 2002, and the towns now anchor a film-location and restoration economy.",
    col: [{ h: "#d4b483", n: "honey limestone" }, { h: "#8a6d3b", n: "carved umber shadow" }, { h: "#b05a3a", n: "terracotta roof" }, { h: "#2b2b2b", n: "wrought iron" }, { h: "#f1e3c8", n: "sunlit cream" }],
    m: ["Comiso limestone", "wrought iron", "terracotta roof tile", "gilded stucco"],
    tx: ["sun-weathered stone", "deep carved volutes", "facade chiaroscuro relief", "polished balustrades"],
    obj: ["grinning mask corbels", "concave balconies", "scrolled pediments", "saint niches", "scenographic stairways"],
    ex: ["San Giorgio, Modica — Rosario Gagliardi tiered facade", "Noto cathedral and San Domenico stair-scenography", "Ragusa Ibla Duomo di San Giorgio"],
    inf: ["Roman Baroque scenography", "Spanish Plateresque ornament"], rel: ["Roman Baroque", "Sicilian carretto painted cart", "Bavarian Rococo"],
    par: "Italian Baroque", var: ["Noto school", "Catania school", "Modica school"], cf: ["Churrigueresque", "Roman Baroque"],
    src: [
      { n: "Wikipedia — Sicilian Baroque", u: "https://en.wikipedia.org/wiki/Sicilian_Baroque", t: "B" },
      { n: "UNESCO — Late Baroque Towns of the Val di Noto", u: "https://whc.unesco.org/en/list/1024", t: "A" },
    ],
    tg: ["sicily", "baroque", "limestone", "theatrical", "un"],
    pop: 42, niche: false,
    vd: { shape: "scenographic facade masses", line: "broken pediments and volutes", composition: "tower against low town grid", texture: "honey limestone chiaroscuro", forms: "masks, putti, balconies" },
    typ: { display: "serif with strong contrast", body: "old-style serif", notes: "engraved town-guide feel" },
    fnt: { display: "Playfair Display", body: "Source Sans Pro", notes: "dramatic Didone display suits volute drama" },
    lit: { quality: "molten late afternoon", direction: "raking southern sun", temperature: "hot", shadow: "deep and carved" },
    pho: { approach: "wide-angle facade studies at golden hour", grade: "warm amber film" },
    fash: { silhouettes: "voluminous ceremonial", garments: "linen suits, vestments", acc: "gold filigree" },
    env: { places: "balconied baroque streets, duomo squares", weather: "dazzling sun, siesta stillness" },
    gd: { layout: "centered symmetry like an altarpiece", icon: "grinning mask crest" },
    ui: { background: "#f1e3c8", surface: "carved stone panels", components: "voluted buttons", motion: "curtain-reveal sweeps" },
    rec: { materials: "limestone, iron, stucco", lighting: "low sun through shuttered windows", objects: "majolica, crib figures", music: "mandolin serenades", scent: "orange blossom and hot stone" },
    snd: ["church bells", "mandolin", "cicadas"],
    dna: { mi: 15, og: 40, wc: 18, ns: 25, ad: 5, hf: 8, rr: 30, ps: 35, sh: 35, ql: 70, oc: 30, ds: 85, rs: 25, eu: 45, np: 40 },
    emo: { warm: 70, cold: 20, playful: 45, serious: 60, chaotic: 30, ordered: 65, nostalgic: 65, futuristic: 10, peaceful: 45, ominous: 30 },
  },
  {
    n: "Burano lace", a: ["merletto di Burano", "Venetian needle lace", "Burano merletto"],
    cat: "Textile & Craft", c: "Needle lace island craft", e: "regional_tradition",
    o: "Burano, Venetian Lagoon", g: "Venice lagoon; collectors across Europe",
    p: "16th century peak; 1872 revival", era: "early modern craft",
    sum: "Needle-built lace from a painted fishing island — punto in aria stitches, school-revived traditions and whitework that once rivalled currency.",
    desc: "On Burano, lacemakers stitched lace purely with needle and thread, evolving punto in aria — stitch-in-air — that freed lace from fabric grounds. Venetian needle lace became a state treasure under the Republic, so valuable that lacemakers were forbidden to leave with patterns. After an 18th-century collapse, Countess Andriana Marcello founded the Burano lace school in 1872, standardising the dense floral and geometric grounds still worked today with pillow and needle. The Museo del Merletto in the island's old lace school displays wedding veils and collars in ivory thread. The craft's setting is inseparable: fishermen's houses painted in saturated yellow, green, orange and blue, said to help boats find home in fog.",
    col: [{ h: "#f5f0e1", n: "ivory thread" }, { h: "#e8b93c", n: "house yellow" }, { h: "#3b7a57", n: "lagoon green" }, { h: "#d96c2c", n: "house orange" }, { h: "#2b6ca3", n: "fishing blue" }],
    m: ["linen thread", "needle and pillow", "flax grounds", "dye-rich house paint"],
    tx: ["dense floral netting", "raised relief stitches", "gauze-fine openwork", "weathered stucco"],
    obj: ["wedding veils", "ruff collars", "lacemaking bobbins", "painted facades", "stitch samplers"],
    ex: ["Museo del Merletto, Burano", "Scuola dei Merletti revival (1872)", "Venetian punto in aria collars in civic collections"],
    inf: ["Renaissance needlework patternbooks", "Venetian mercantile luxury"], rel: ["Vologda lace", "Alençon needle lace", "Murano glass"],
    par: "Venetian lace craft", var: ["rose point", "point de Venise a reseau", "soprammobillo"], cf: ["Chantilly bobbin lace"],
    src: [
      { n: "Wikipedia — Burano", u: "https://en.wikipedia.org/wiki/Burano", t: "B" },
      { n: "Fondazione Musei Civici di Venezia — Museo del Merletto", u: "https://visitmuve.it", t: "A" },
    ],
    tg: ["lace", "venice", "needlework", "island", "ivory"],
    pop: 34, niche: false,
    vd: { shape: "floral medallions on net", line: "continuously built cord", composition: "medallion repeats with open ground", texture: "stiff ivory relief", forms: "veils, collars, flounces" },
    typ: { display: "high-contrast serif", body: "humanist sans", notes: "museum-label elegance" },
    fnt: { display: "Cormorant Garamond", body: "Work Sans", notes: "delicate Renaissance-flavoured pairing" },
    lit: { quality: "lagoon glare", direction: "soft diffuse", temperature: "warm", shadow: "minimal" },
    pho: { approach: "macro shots of thread against painted walls", grade: "clean warm neutral" },
    fash: { silhouettes: "fitted 17th-century", garments: "lace collars, veils", acc: "pearl and coral" },
    env: { places: "canals, leaning campanile, lace shops", weather: "salt haze and flat light" },
    gd: { layout: "oval medallion framing", icon: "stitched floral roundel" },
    ui: { background: "#f5f0e1", surface: "net-textured cards", components: "thread-line borders", motion: "stitch-by-stitch draws" },
    rec: { materials: "lace, painted wood, fishing rope", lighting: "bright diffuse lagoon light", objects: "bobbins, veils, masks", music: "lagoon rowing songs", scent: "salt, linen, paint" },
    snd: ["lapping water", "bobbin clicks", "seagulls"],
    dna: { mi: 35, og: 60, wc: 25, ns: 5, ad: 5, hf: 12, rr: 15, ps: 40, sh: 15, ql: 25, oc: 20, ds: 75, rs: 20, eu: 60, np: 40 },
    emo: { warm: 65, cold: 25, playful: 40, serious: 55, chaotic: 15, ordered: 80, nostalgic: 85, futuristic: 10, peaceful: 70, ominous: 5 },
  },
  {
    n: "Neapolitan presepe", a: ["presepe napoletano", "Neapolitan nativity scene", "San Gregorio Armeno cribs"],
    cat: "Religious & Sacred Art", c: "Baroque nativity craft", e: "regional_tradition",
    o: "Naples", g: "Naples; exported to European collections",
    p: "18th-century golden age; living craft", era: "late Baroque folk sacred",
    sum: "Naples' theatrical nativity craft — terracotta shepherds, silk-robed Magi and whole comic villages around the Holy Family on San Gregorio Armeno.",
    desc: "Naples turned the nativity into total theatre during the 18th century: craggy cork landscapes, ruined temples, and hundreds of figures where Holy Family mingle with taverns, fishwives and bandits, collapsing sacred and everyday time. Master modellers worked terracotta heads with glass eyes, silver-gilt trappings and silk costumes stiffened with wire — Giuseppe Sanmartino's era produced shepherds of uncanny realism. The great Cuciniello nativity at the Certosa di San Martino assembles over 600 pieces. The street of San Gregorio Armeno still concentrates workshop after workshop making figures year-round, from cardinals to footballers. The presepe is Naples' self-portrait: chaotic, devout, humane, and endlessly added to.",
    col: [{ h: "#a56b46", n: "terracotta flesh" }, { h: "#7d5a3c", n: "cork grotto" }, { h: "#c9a227", n: "gilt trim" }, { h: "#5e7d5a", n: "faded silk green" }, { h: "#3f3f5f", n: "twilight blue" }],
    m: ["terracotta", "cork and moss", "silk and wire", "glass eyes", "silver-gilt accents"],
    tx: ["crackled painted clay", "fuzzy moss rockwork", "stiff brocade folds", "wire-armature pose"],
    obj: ["shepherd figures", "cork ruins", "silk-robed Magi", "tavern scenes", "angels on wires"],
    ex: ["Cuciniello nativity, Certosa di San Martino, Naples", "San Gregorio Armeno workshop street", "18th-century presepi in the Museo di San Martino"],
    inf: ["Neapolitan Baroque sculpture", "opera scenography"], rel: ["Provençal santons", "Kraków szopka", "Roman Baroque"],
    par: "Christian nativity craft", var: ["aristocratic presepe", "street-workshop figures", "tableau presepi"], cf: ["Provençal santons"],
    src: [
      { n: "Wikipedia — Nativity scene", u: "https://en.wikipedia.org/wiki/Nativity_scene", t: "B" },
      { n: "Wikipedia — San Gregorio Armeno", u: "https://en.wikipedia.org/wiki/San_Gregorio_Armeno", t: "B" },
      { n: "Ministry of Culture — Polo Museale Campania", u: "https://www.cultura.gov.it", t: "A" },
    ],
    tg: ["naples", "nativity", "terracotta", "baroque", "craft"],
    pop: 32, niche: true,
    vd: { shape: "rugged theatrical diorama", line: "gestural clay folds", composition: "sacred centre, comic margins", texture: "cork, moss, silk, clay", forms: "shepherds, angels, ruins" },
    typ: { display: "swash serif", body: "humanist sans", notes: "baroque-playbill mood" },
    fnt: { display: "Alegreya", body: "Open Sans", notes: "warm calligraphic serif display" },
    lit: { quality: "candlelit grotto", direction: "low warm pools", temperature: "warm", shadow: "rich, tinted" },
    pho: { approach: "tabletop macro dioramas", grade: "warm amber with deep shadows" },
    fash: { silhouettes: "18th-century folk", garments: "silk gowns, shepherd smocks", acc: "gilt trappings" },
    env: { places: "workshop lanes, dark palazzo rooms", weather: "warm humid night air" },
    gd: { layout: "diorama assemblage", icon: "star over cork ruins" },
    ui: { background: "#3f3f5f", surface: "cork-textured panels", components: "terracotta buttons", motion: "gentle figure pops" },
    rec: { materials: "terracotta, cork, moss, silk", lighting: "candle and tiny lamps", objects: "shepherds, angels, tavern props", music: "neapolitan canzonetta", scent: "moss, clay, incense" },
    snd: ["workshop chatter", "hand-bells", "mandolin"],
    dna: { mi: 10, og: 70, wc: 15, ns: 10, ad: 5, hf: 10, rr: 35, ps: 60, sh: 30, ql: 45, oc: 45, ds: 90, rs: 35, eu: 55, np: 45 },
    emo: { warm: 85, cold: 15, playful: 65, serious: 45, chaotic: 55, ordered: 35, nostalgic: 85, futuristic: 5, peaceful: 45, ominous: 15 },
  },
  {
    n: "Nuragic stone architecture", a: ["nuraghe towers", "Su Nuraxi style", "Sardinian Bronze Age towers"],
    cat: "Architectural Style", c: "Bronze Age corbelled towers", e: "historical",
    o: "Sardinia", g: "island-wide Sardinia",
    p: "c. 1800-238 BC", era: "Bronze and Iron Age",
    sum: "Sardinia's prehistoric civilization of corbelled basalt towers — thousands of truncated cones with inner tholos chambers, crowned by Su Nuraxi of Barumini.",
    desc: "The nuragic people built some 7,000 surviving nuraghi: truncated-cone towers of dry-laid basalt blocks rising inward by corbelling to close a domed tholos chamber, often compounded into multi-tower fortresses with ramparts and village huts. Su Nuraxi at Barumini, the type-site excavated by Giovanni Lilliu, shows a central tower wrapped by four, then a seven-lobed bastion — UNESCO inscribed it in 1997. Around the towers stand giants' tombs with carved stele, assembly huts and sacred wells with precise masonry. No written language survives; their aesthetic is mass, geometry and corbelled void, echoed in the bronzetti votive figurines that preserve warriors and mothers with child. The towers remain Sardinia's emblem, stamped on everything from bread to banners.",
    col: [{ h: "#6e6a63", n: "basalt grey" }, { h: "#8c8377", n: "dust-warm stone" }, { h: "#4f5d4a", n: "macchia green" }, { h: "#b8a887", n: "dry grass" }, { h: "#3a4a5a", n: "deep slate" }],
    m: ["basalt blocks", "trachyte", "corbelled dry stone", "bronze (figurines)"],
    tx: ["stepped corbelling", "lava-rough masonry", "sun-bleached rock", "narrow passage shadow"],
    obj: ["truncated cone towers", "tholos chambers", "giants' tombs", "bronzetti figurines", "sacred well temples"],
    ex: ["Su Nuraxi di Barumini (UNESCO 1997)", "Nuraghe Santu Antine, Torralba", "Well temple of Santa Cristina, Paulilatino"],
    inf: ["Mediterranean corbel-vaulting know-how", "indigenous island cults"], rel: ["Svaneti tower houses", "Great Zimbabwe Architecture", "Inca Ashlar Masonry"],
    par: "prehistoric Mediterranean architecture", var: ["single-tower pylon", "tetrilobate complex", "sacred wells"], cf: ["Sardinian shepherds' stone huts"],
    src: [
      { n: "Wikipedia — Nuraghe", u: "https://en.wikipedia.org/wiki/Nuraghe", t: "B" },
      { n: "Wikipedia — Su Nuraxi (Barumini)", u: "https://en.wikipedia.org/wiki/Su_Nuraxi_(Barumini)", t: "B" },
      { n: "UNESCO World Heritage Centre", u: "https://whc.unesco.org", t: "A" },
    ],
    tg: ["sardinia", "prehistoric", "stonework", "towers", "unesco"],
    pop: 30, niche: true,
    vd: { shape: "truncated cones and lobed bastions", line: "stepped corbel courses", composition: "tower against skyline", texture: "dry basalt rubble", forms: "domed voids, narrow portals" },
    typ: { display: "sturdy geometric sans", body: "humanist sans", notes: "archaeological-plate tone" },
    fnt: { display: "Marcellus", body: "Inter", notes: "lapidary display caps" },
    lit: { quality: "hard island sun", direction: "high vertical", temperature: "hot", shadow: "black, knife-edged" },
    pho: { approach: "monumental low-angle shots", grade: "desaturated stone and sky" },
    fash: { silhouettes: "shepherd utilitarian", garments: "wool tunics, leather vests", acc: "bronze fibulae" },
    env: { places: "basalt plateaux, cork oak groves", weather: "mistral wind, scorched summers" },
    gd: { layout: "radial fortress plan", icon: "nuraghe silhouette mark" },
    ui: { background: "#8c8377", surface: "stone-block cards", components: "chunky stone buttons", motion: "block-by-block builds" },
    rec: { materials: "basalt, cork, bronze", lighting: "torchlight in tholos chambers", objects: "bronzetti, bread stamps, tower models", music: "launeddas drones", scent: "hot stone, wild herbs" },
    snd: ["wind over ruins", "launeddas", "distant sheep bells"],
    dna: { mi: 45, og: 65, wc: 35, ns: 5, ad: 5, hf: 5, rr: 55, ps: 20, sh: 80, ql: 25, oc: 25, ds: 40, rs: 20, eu: 75, np: 25 },
    emo: { warm: 35, cold: 55, playful: 15, serious: 85, chaotic: 20, ordered: 70, nostalgic: 60, futuristic: 5, peaceful: 50, ominous: 45 },
  },
  {
    n: "Caltagirone ceramics", a: ["maiolica di Caltagirone", "Sicilian maiolica", "ceramiche siciliane"],
    cat: "Material & Surface", c: "Sicilian tin-glazed ceramics", e: "regional_tradition",
    o: "Caltagirone, Sicily", g: "Sicily; export and revival across Italy",
    p: "10th century onward; 20th-century revival", era: "Islamic-era to modern craft",
    sum: "Sicily's ceramic capital — Arab-rooted maiolica of green and manganese, Teste di Moro vases and the great tiled staircase of Santa Maria del Monte.",
    desc: "Caltagirone has fired maiolica since Arab potters worked Sicily in the tenth century, developing a bold palette of copper green, manganese purple and ochre over white tin glaze. Its signature objects run from baroque pharmacy jars to Teste di Moro — sculpted Moor-head vases sprouting citrus and basil — and the painted panels that dressed Sicilian carts. The 142-step Scalinata di Santa Maria del Monte (1608), tiling its risers with patterned maiolica in the 1950s, turns the whole town into a ceramic object, lit by paper lanterns during the Luminaria festival. Workshops still throw, tin-glaze and hand-paint with transmission through family botteghe. The look: confident brushwork, dense borders, fruit, acanthus and finial forms scaled for church doors and kitchen shelves alike.",
    col: [{ h: "#2e7d5b", n: "copper green" }, { h: "#4a3653", n: "manganese purple" }, { h: "#e3d9b8", n: "tin-glaze white" }, { h: "#c86a2f", n: "sicilian ochre orange" }, { h: "#b8952f", n: "citron yellow" }],
    m: ["clay", "tin glaze", "mineral pigments", "kilns"],
    tx: ["glossy tin surface", "confident brush strokes", "crazed antique glaze", "scalloped tile edges"],
    obj: ["Teste di Moro vases", "apothecary jars", "tiled stair risers", "pomegranate finials", "carretto panels"],
    ex: ["Scalinata di Santa Maria del Monte, 142 tiled steps", "Luminaria festival of San Giacomo", "Regional Ceramic Museum of Caltagirone"],
    inf: ["Islamic-Sicilian maiolica", "Spanish Valencian ware"], rel: ["Sicilian carretto painted cart", "Talavera Poblana ceramics", "Delftware"],
    par: "Mediterranean maiolica", var: ["Teste di Moro", "farmacia jars", "geometric Islamic-revival bands"], cf: ["Talavera Poblana ceramics"],
    src: [
      { n: "Wikipedia — Caltagirone", u: "https://en.wikipedia.org/wiki/Caltagirone", t: "B" },
      { n: "Wikipedia — Maiolica", u: "https://en.wikipedia.org/wiki/Maiolica", t: "B" },
      { n: "Victoria and Albert Museum", u: "https://www.vam.ac.uk", t: "A" },
    ],
    tg: ["sicily", "ceramics", "maiolica", "tiles", "craft"],
    pop: 28, niche: true,
    vd: { shape: "globular vases, scalloped rims", line: "bold outline-and-fill brushwork", composition: "medallion and band repeats", texture: "glassy tin glaze", forms: "Moor heads, jars, tiles" },
    typ: { display: "rounded folk serif", body: "humanist sans", notes: "ceramic-label warmth" },
    fnt: { display: "Lora", body: "Open Sans", notes: "friendly brush-contrast serif" },
    lit: { quality: "bright workshop", direction: "even top light", temperature: "warm", shadow: "soft" },
    pho: { approach: "still-life on stone sills", grade: "saturated warm colour" },
    fash: { silhouettes: "mediterranean summer", garments: "linen, terracotta tones", acc: "ceramic jewellery" },
    env: { places: "tiled stairways, pottery courtyards", weather: "high sun, dry heat" },
    gd: { layout: "tile-grid repeats", icon: "Moor head silhouette" },
    ui: { background: "#e3d9b8", surface: "glazed tile cards", components: "green-framed buttons", motion: "tile-flip transitions" },
    rec: { materials: "glazed pots, tiled steps", lighting: "strong sun with bounce", objects: "Moor heads, jars, carretto wheels", music: "sicilian folk guitar", scent: "citrus, clay dust" },
    snd: ["wheel hum", "kiln crackle", "market calls"],
    dna: { mi: 25, og: 55, wc: 12, ns: 15, ad: 5, hf: 15, rr: 30, ps: 55, sh: 30, ql: 45, oc: 30, ds: 80, rs: 25, eu: 60, np: 45 },
    emo: { warm: 80, cold: 20, playful: 60, serious: 40, chaotic: 30, ordered: 65, nostalgic: 75, futuristic: 10, peaceful: 60, ominous: 5 },
  },
  {
    n: "Scagliola", a: ["scagliola art", "selenite marbling", "Tuscan scagliola"],
    cat: "Material & Surface", c: "Faux-marble plaster craft", e: "historical",
    o: "Tuscany and Emilia, Italy", g: "Italy; exported to Britain and Central Europe",
    p: "17th-18th century peak", era: "Baroque craft",
    sum: "The alchemical craft of selenite plaster polished into false marble — pictorial panels that rivaled Florentine pietre dura at a fraction of the cost.",
    desc: "Scagliola binds ground selenite (gypsum crystal) with animal glue and pigments into a dough that is trowelled, engraved, filled with coloured mixes and polished to a vitreous marble sheen. Florentine friars and craftsmen such as Enrico Hugford elevated it to a pictorial art in the 18th century, making altarpieces, panelled walls and kneeling-steps that imitated — and sometimes out-charmed — pietre dura inlay. The Emilian town of Carpi kept a celebrated workshop tradition of trompe-l'oeil landscapes and crests. Because it could fake rare marbles cheaply, scagliola travelled: Georgian Britain sheathed columns and hearths with it, and Central European palaces lined stair halls. Its surface holds tiny cracks and a warm depth that distinguish it from stone at arm's length.",
    col: [{ h: "#b49a6c", n: "sienna scagliola" }, { h: "#5a3a2e", n: "engraved umber" }, { h: "#8f2f28", n: "false porphyry red" }, { h: "#d9cbb0", n: "cream marble ground" }, { h: "#2f2f2f", n: "polish charcoal" }],
    m: ["selenite gypsum", "animal glue", "earth pigments", "wax polish"],
    tx: ["vitreous polished sheen", "hairline crackle", "feathered marbling", "engraved line fills"],
    obj: ["altar frontals", "false-marble columns", "panelled walls", "crest plaques", "pictorial panels"],
    ex: ["Corsini Chapel, Santa Maria del Carmine, Florence", "Scagliola workshop tradition of Carpi", "Georgian scagliola columns in British country houses"],
    inf: ["pietre dura inlay", "faux-marble painting"], rel: ["Pietra dura", "Venetian plaster", "Trompe-l'œil"],
    par: "Italian decorative plastercraft", var: ["pictorial Florentine scagliola", "architectural block scagliola"], cf: ["Trompe-l'œil", "Pietra dura"],
    src: [
      { n: "Wikipedia — Scagliola", u: "https://en.wikipedia.org/wiki/Scagliola", t: "B" },
      { n: "Victoria and Albert Museum", u: "https://www.vam.ac.uk", t: "A" },
    ],
    tg: ["plaster", "faux marble", "tuscany", "baroque", "craft"],
    pop: 20, niche: true,
    vd: { shape: "book-matched panels", line: "engraved then filled outlines", composition: "architectural framing, pictorial centres", texture: "glassy mineral sheen", forms: "marble veining, crests, landscapes" },
    typ: { display: "engraved-feel serif", body: "serif", notes: "cabinet-and-cornice mood" },
    fnt: { display: "EB Garamond", body: "EB Garamond", notes: "single-family engraved-book pairing" },
    lit: { quality: "candle-polish glow", direction: "raking to reveal sheen", temperature: "warm", shadow: "soft sepia" },
    pho: { approach: "angled close-ups catching sheen", grade: "warm sepia highlights" },
    fash: { silhouettes: "classic tailored", garments: "velvet, wool broadcloth", acc: "cameos" },
    env: { places: "chapel interiors, stair halls", weather: "still indoor air" },
    gd: { layout: "panel-and-border framing", icon: "marble-swatch roundel" },
    ui: { background: "#d9cbb0", surface: "polished stone cards", components: "inlaid line buttons", motion: "polish-glint sweeps" },
    rec: { materials: "plaster samples, wax, marble offcuts", lighting: "low raking light", objects: "panels, columns, plaques", music: "baroque harpsichord", scent: "hide glue, beeswax" },
    snd: ["trowel scrape", "polishing cloth", "chapel quiet"],
    dna: { mi: 40, og: 45, wc: 20, ns: 20, ad: 5, hf: 10, rr: 20, ps: 25, sh: 35, ql: 20, oc: 20, ds: 65, rs: 15, eu: 55, np: 25 },
    emo: { warm: 60, cold: 35, playful: 25, serious: 70, chaotic: 10, ordered: 85, nostalgic: 75, futuristic: 10, peaceful: 60, ominous: 15 },
  },
  {
    n: "Czech Cubism", a: ["Bohemian Cubism", "cubist architecture of Prague", "Pražský kubismus"],
    cat: "Art Movement", c: "Cubism as national style", e: "historical",
    o: "Prague", g: "Bohemia, Czechoslovakia",
    p: "1911-1919; Rondo-Cubism after 1918", era: "pre-war modernism",
    sum: "The world's only Cubist architecture — Prague's faceted crystal facades, prism-philosophy theory and angular furniture of Gočár, Chochol and Janák.",
    desc: "Between 1911 and the First World War, a circle of Czech architects and painters did what no other nation attempted: turned Analytical Cubism into a built national style. Pavel Janák theorised angularity as the Czech spirit against soft Secession curves, while Josef Gočár built the House of the Black Madonna (1912) with faceted bay windows and a famous cubist lamppost, and Josef Chochol composed villa facades like fractured crystal. Painter Emil Filla and sculptor Otto Gutfreund carried the idiom into canvas and relief. Interiors kept cubist furniture, chandeliers and even doorknobs, so the style read as total design. After 1918 the movement softened into rounded Rondo-Cubism for the new republic, but Prague's faceted corners remain unique evidence of a painted avant-garde leaping into masonry.",
    col: [{ h: "#8a8578", n: "Prague sandstone" }, { h: "#3d4a52", n: "slate blue-grey" }, { h: "#b0413e", n: "poster red" }, { h: "#d8cfc0", n: "facade cream" }, { h: "#22242a", n: "faceted shadow" }],
    m: ["plaster over masonry", "wrought iron", "stained glass", "lacquered wood (furniture)"],
    tx: ["sharp planar facets", "chiselled corners", "stepped rhythms", "matte painted render"],
    obj: ["faceted bay windows", "cubist lampposts", "angular doorways", "fractured balconies", "crystal-form chairs"],
    ex: ["House of the Black Madonna, Ovocný trh (Gočár, 1912)", "Villa Kovařovic, Libeň (Chochol, 1913)", "Czech Cubism permanent gallery, Museum of Decorative Arts Prague"],
    inf: ["Analytic Cubism", "Czech national revival"], rel: ["Analytic Cubism", "Prague Group", "Art Deco"],
    par: "Cubism", var: ["Rondo-Cubism", "cubist applied design"], cf: ["Art Deco"],
    src: [
      { n: "Wikipedia — Czech Cubism", u: "https://en.wikipedia.org/wiki/Czech_Cubism", t: "B" },
      { n: "Google Arts & Culture", u: "https://artsandculture.google.com", t: "A" },
    ],
    tg: ["prague", "cubism", "architecture", "modernism", "faceted"],
    pop: 30, niche: true,
    vd: { shape: "prismatic crystalline masses", line: "chiselled diagonal folds", composition: "vertical bay rhythm", texture: "planar matte render", forms: "faceted windows, pyramidal caps" },
    typ: { display: "angular geometric sans", body: "grotesque sans", notes: "avant-garde poster energy" },
    fnt: { display: "Josefin Sans", body: "Work Sans", notes: "period geometric with Czech modernist roots" },
    lit: { quality: "overcast silver", direction: "cross light on facets", temperature: "cold", shadow: "hard-edged" },
    pho: { approach: "steep upward angles emphasising facets", grade: "cool duotone" },
    fash: { silhouettes: "sharp-shouldered modern", garments: "wool suits, high collars", acc: "angular brooches" },
    env: { places: "narrow old-town streets, cafe interiors", weather: "grey Bohemian drizzle" },
    gd: { layout: "diagonal dynamic grid", icon: "shard triangle mark" },
    ui: { background: "#d8cfc0", surface: "angled panel cards", components: "faceted buttons", motion: "planar slide cuts" },
    rec: { materials: "render, iron, glass", lighting: "single window shaft", objects: "cubist chairs, lamps, posters", music: "interwar cabaret piano", scent: "coffee, plaster" },
    snd: ["tram bells", "typewriter", "cafe murmur"],
    dna: { mi: 40, og: 15, wc: 45, ns: 45, ad: 25, hf: 35, rr: 35, ps: 30, sh: 55, ql: 50, oc: 35, ds: 45, rs: 30, eu: 40, np: 55 },
    emo: { warm: 30, cold: 65, playful: 35, serious: 70, chaotic: 40, ordered: 60, nostalgic: 55, futuristic: 45, peaceful: 30, ominous: 30 },
  },
  {
    n: "Meissen porcelain", a: ["Meissen ware", "crossed-swords porcelain", "Böttger porcelain"],
    cat: "Furniture & Product Design", c: "European hard-paste porcelain", e: "historical",
    o: "Meissen, Saxony", g: "European courts and export markets",
    p: "1708 onward", era: "early modern luxury",
    sum: "Europe's first true porcelain — alchemically cracked at Meissen in 1708, then painted with Höroldt chinoiserie and modelled by Kaendler's lively figures.",
    desc: "Johann Friedrich Böttger, an imprisoned alchemist, and Ehrenfried Tschirnhaus cracked the hard-paste porcelain recipe in 1708 for Augustus the Strong, and the Meissen manufactory opened at Albrechtsburg in 1710 as a state secret. Johann Gregor Höroldt perfected on-glaze enamels for radiant chinoiserie scenes, while Johann Joachim Kändler modelled figurines — commedia players, shepherdesses, the monumental Swan Service — with a liveliness that defined European rococo taste. The blue crossed-swords mark became the first great porcelain signature. As recipes leaked to Vienna and Sèvres, Meissen answered with ever finer modelling and painting; the manufactory still produces by hand today. Its look: brilliant white paste, jewel enamels, gilt edges, and figures caught mid-gesture.",
    col: [{ h: "#f6f3ec", n: "porcelain white" }, { h: "#26479c", n: "crossed-swords blue" }, { h: "#c8a02c", n: "rim gilt" }, { h: "#b5432f", n: "enamel red" }, { h: "#3f7a4e", n: "enamel green" }],
    m: ["kaolin paste", "cobalt underglaze", "on-glaze enamels", "gilding"],
    tx: ["glassy glaze", "sculptural folds", "fine enamel stipple", "raised gilt borders"],
    obj: ["figurines", "Swan Service", "chinoiserie teapots", "monkey orchestra", "crossed-swords mark"],
    ex: ["Swan Service (Kändler, 1737-41)", "Kaendler commedia figurines", "Meissen manufactory, Albrechtsburg"],
    inf: ["Chinese Kangxi porcelain", "rococo taste"], rel: ["Herend porcelain", "Imari ware", "Famille rose"],
    par: "European court porcelain", var: ["Böttger red stoneware", "Höroldt chinoiserie", "Kändler figures"], cf: ["Sèvres porcelain"],
    src: [
      { n: "Wikipedia — Meissen porcelain", u: "https://en.wikipedia.org/wiki/Meissen_porcelain", t: "B" },
      { n: "Staatliche Porzellan-Manufaktur Meissen", u: "https://www.meissen.com", t: "A" },
      { n: "Victoria and Albert Museum", u: "https://www.vam.ac.uk", t: "A" },
    ],
    tg: ["porcelain", "saxony", "rococo", "court", "luxury"],
    pop: 34, niche: false,
    vd: { shape: "sculptural rocaille vessels", line: "asymmetric C-scroll enamelling", composition: "centred figure scenes", texture: "high-gloss glaze", forms: "figures, tea services, swans" },
    typ: { display: "rococo script-flavoured serif", body: "serif", notes: "court-catalogue refinement" },
    fnt: { display: "Petit Formal Script", body: "Crimson Pro", notes: "rococo label script plus book serif" },
    lit: { quality: "candlelustre", direction: "soft key with glints", temperature: "warm", shadow: "silver-grey" },
    pho: { approach: "single-figure museum lighting", grade: "clean bright with gilt sparkle" },
    fash: { silhouettes: "rococo courtly", garments: "silk coats, pannier gowns", acc: "porcelain-brooch bijoux" },
    env: { places: "porcelain cabinets, treaty salons", weather: "candlelit evenings" },
    gd: { layout: "centered vignette on white", icon: "crossed swords cartouche" },
    ui: { background: "#f6f3ec", surface: "white with gilt hairlines", components: "scalloped buttons", motion: "graceful figure pirouettes" },
    rec: { materials: "porcelain, velvet, giltwood", lighting: "chandelier pools", objects: "figures, teacups, mirrors", music: "court flute", scent: "orange pekoe, beeswax" },
    snd: ["delicate chimes", "saucer clinks", "harpsichord"],
    dna: { mi: 30, og: 35, wc: 20, ns: 30, ad: 5, hf: 12, rr: 10, ps: 45, sh: 15, ql: 20, oc: 15, ds: 70, rs: 20, eu: 50, np: 30 },
    emo: { warm: 55, cold: 40, playful: 55, serious: 50, chaotic: 15, ordered: 80, nostalgic: 80, futuristic: 10, peaceful: 60, ominous: 5 },
  },
  {
    n: "Erzgebirge wooden folk art", a: ["Erzgebirgische Volkskunst", "Seiffen toys", "Ore Mountain woodcraft"],
    cat: "Furniture & Product Design", c: "Mining-region toy craft", e: "regional_tradition",
    o: "Erzgebirge, Saxony-Bohemia border", g: "Saxony; Christmas markets worldwide",
    p: "17th century onward; Christmas canon by 19th century", era: "industrial-era folk",
    sum: "Ore Mountain woodcraft born of dying mines — nutcrackers, smoking men, candle arches and turning Christmas pyramids in turned and chip-carved pine.",
    desc: "When the Ore Mountains' silver and tin mines declined, miner families turned to wood: Seiffen's turners invented Reifendrehen, slicing figures from a turned ring, and whole villages made toys for Leipzig fairs. The canon grew from mining life — nutcracker kings and gendarmes, Räuchermännchen figures that puff incense smoke, the Schwibbogen candle arch echoing a mine-tunnel cross-section, and carousel-like Christmas pyramids whose fan-blades rise over hearth heat. Palettes are frank: wax-reds, forest greens, cream paint over pale wood, with white-flocked snow textures. Trade catalogues and German emigration carried the craft worldwide, and workshops in Seiffen still hand-carve and turn. It is mining cosmology domesticated: the pit, the watchman and the light, miniaturised for the parlour.",
    col: [{ h: "#b23a2e", n: "wax red" }, { h: "#2f5d3a", n: "forest green" }, { h: "#f0e6cf", n: "cream paint" }, { h: "#d9b98a", n: "pale pine" }, { h: "#3a3a3a", n: "miner black" }],
    m: ["pine and spruce", "water-based paints", "candle wax", "brass (pyramid fans)"],
    tx: ["lathe-smooth turnings", "chip-carved facets", "flocked snow", "flat gouache paint"],
    obj: ["nutcracker soldiers", "Räuchermännchen smokers", "Schwibbogen arches", "Christmas pyramids", "miner and angel pairs"],
    ex: ["Seiffen turners' Reifendrehen ring figures", "Erzgebirgisches Spielzeugmuseum, Seiffen", "Schwibbogen candle arches on winter windowsills"],
    inf: ["mining guild traditions", "Protestant candle piety"], rel: ["Dala horse", "Kraków szopka", "Scandinavian Hygge"],
    par: "German toy-making", var: ["Seiffen turning", "chip-carved flat figures", "arch and pyramid types"], cf: ["Dala horse"],
    src: [
      { n: "Wikipedia — Erzgebirgische Volkskunst", u: "https://en.wikipedia.org/wiki/Erzgebirgische_Volkskunst", t: "B" },
      { n: "Germanisches Nationalmuseum", u: "https://www.gnm.de", t: "A" },
    ],
    tg: ["toys", "saxony", "christmas", "woodcraft", "mining"],
    pop: 28, niche: true,
    vd: { shape: "blunt heraldic figurines", line: "chip-carve knife facets", composition: "paired figures and arch scenes", texture: "painted pine, flock snow", forms: "miners, angels, arches, pyramids" },
    typ: { display: "friendly rounded serif", body: "humanist sans", notes: "storybook-catalogue tone" },
    fnt: { display: "Amatic SC", body: "Nunito", notes: "hand-cut caps for toy labels" },
    lit: { quality: "candle-warm parlour", direction: "window sidelight", temperature: "warm", shadow: "soft amber" },
    pho: { approach: "parlour-sill still lifes", grade: "warm nostalgic film" },
    fash: { silhouettes: "alpine domestic", garments: "knit cardigans, wool skirts", acc: "wooden jewellery" },
    env: { places: "attic workshops, snow-set windows", weather: "dark snowy afternoons" },
    gd: { layout: "arch-framed symmetry", icon: "candle arch silhouette" },
    ui: { background: "#f0e6cf", surface: "painted-wood cards", components: "peg buttons", motion: "pyramid fan rotation" },
    rec: { materials: "pine, wax, incense cones", lighting: "candle and string lights", objects: "nutcrackers, pyramids, smokers", music: "german christmas carols", scent: "incense, pine resin" },
    snd: ["candle flicker", "carousel tinkle", "snow hush"],
    dna: { mi: 35, og: 70, wc: 12, ns: 10, ad: 5, hf: 12, rr: 25, ps: 70, sh: 20, ql: 25, oc: 20, ds: 45, rs: 15, eu: 70, np: 40 },
    emo: { warm: 90, cold: 15, playful: 80, serious: 30, chaotic: 15, ordered: 75, nostalgic: 90, futuristic: 10, peaceful: 75, ominous: 5 },
  },
  {
    n: "Kraków szopka", a: ["szopka krakowska", "Kraków Christmas crib", "Polish Christmas crèche"],
    cat: "Regional & Cultural Tradition", c: "Folk architectural puppet crib", e: "regional_tradition",
    o: "Kraków, Poland", g: "Kraków; national symbol of Polish craft",
    p: "19th century onward; competition since 1937", era: "modern folk craft",
    sum: "Kraków's fantasy Christmas cribs stacking St Mary's spires and Wawel towers in coloured foil — an annual competition that turned street cribs into national art.",
    desc: "Kraków szopki are miniature castles of Christmas: slender Gothic spires modelled on St Mary's Basilica, Wawel's courtyard arcade, domes and clock tiers, all sheathed in shiny coloured foil and populated by puppet carollers, folk devils, Turks and dragons. Born in the 19th century as portable street cribs for carollers earning coins, they were rescued from decline when an annual competition was launched in 1937, a tradition now run by the Historical Museum of Kraków. Building is a family craft transmitted across generations, with symmetry, spire count and moving figures judged each December on the Main Square. UNESCO inscribed the tradition in 2018. The aesthetic is gleaming, vertical, symmetric and gleefully over-stuffed — folklore and cathedral condensed into a shoebox skyline.",
    col: [{ h: "#2b6ca3", n: "foil blue" }, { h: "#c8a02c", n: "foil gold" }, { h: "#b23a2e", n: "foil red" }, { h: "#3f7a4e", n: "foil green" }, { h: "#f2ead9", n: "pearl foil" }],
    m: ["plywood frame", "coloured foil", "papier-mâché", "beads and tinsel"],
    tx: ["crinkled reflective foil", "pierced fretwork", "puppet-jointed limbs", "glitter scatter"],
    obj: ["St Mary's twin spires", "Wawel arcade tiers", "puppet carollers", "Lajkonik figures", "clock tiers"],
    ex: ["Annual szopka competition on the Main Square", "Historical Museum of Kraków szopka collection", "UNESCO intangible listing (2018)"],
    inf: ["Kraków Gothic architecture", "puppet theatre craft"], rel: ["Wycinanki papercuts", "Neapolitan presepe", "Pisanki egg decoration"],
    par: "Polish Christmas folk craft", var: ["cathedral type", "palace type", "moving-figure theatrical type"], cf: ["Neapolitan presepe"],
    src: [
      { n: "Wikipedia — Kraków szopka", u: "https://en.wikipedia.org/wiki/Krak%C3%B3w_szopka", t: "B" },
      { n: "UNESCO Intangible Cultural Heritage", u: "https://ich.unesco.org", t: "A" },
    ],
    tg: ["krakow", "christmas", "folk craft", "foil", "puppets"],
    pop: 26, niche: true,
    vd: { shape: "vertical symmetric fantasy skyline", line: "Gothic pinnacles and foil creases", composition: "tiered cathedral elevation", texture: "crinkle-foil glitter", forms: "spires, arches, puppets" },
    typ: { display: "slender display serif", body: "humanist sans", notes: "museum-competition label" },
    fnt: { display: "Marcellus", body: "Nunito", notes: "gothic-caps display with soft body" },
    lit: { quality: "tinsel sparkle", direction: "frontal flash", temperature: "cool-warm mix", shadow: "hard little points" },
    pho: { approach: "square-on museum shots", grade: "high saturation sparkle" },
    fash: { silhouettes: "folk festive", garments: "embroidered vests, capes", acc: "foil crowns" },
    env: { places: "market square, museum vitrines", weather: "frosty december air" },
    gd: { layout: "symmetric elevation like a facade", icon: "twin spire crest" },
    ui: { background: "#f2ead9", surface: "foil-creased cards", components: "gold-tinsel buttons", motion: "curtain-up reveals" },
    rec: { materials: "foil, wood, beads", lighting: "sparkle points on dark", objects: "cribs, puppets, carol books", music: "polish carols", scent: "pine, glue, candle" },
    snd: ["carol singing", "jingle bells", "crowd oohs"],
    dna: { mi: 15, og: 45, wc: 25, ns: 35, ad: 10, hf: 15, rr: 40, ps: 75, sh: 25, ql: 60, oc: 40, ds: 90, rs: 35, eu: 55, np: 55 },
    emo: { warm: 75, cold: 25, playful: 85, serious: 30, chaotic: 45, ordered: 60, nostalgic: 85, futuristic: 10, peaceful: 55, ominous: 10 },
  },
  {
    n: "Transylvanian fortified churches", a: ["Saxon fortified churches", "kirchenburgen", "burgrural churches"],
    cat: "Architectural Style", c: "Defensive village churches", e: "historical",
    o: "Transylvania (Saxon settlement zone)", g: "southern and central Transylvania villages",
    p: "13th-16th centuries", era: "medieval frontier",
    sum: "Saxon colonists' churches walled into village fortresses — onion-buttressed rings, storage chambers and watchtowers above apricot-orchard villages.",
    desc: "Transylvanian Saxons, colonists invited from the 12th century, rebuilt their village churches as fortresses against raids: concentric curtain walls, massive ring walls with grain chambers, and towers where each guild kept a floor. Prejmer's walls could shelter whole villages, while Biertan's triple ring and its celebrated multi-tumbler sacristy lock made it the see of the Saxon bishops. The aesthetic is stern mineral harmony: ochre and white plaster, dark shingle roofs, catwalks under tiled slopes, all over green hill orchards. After Saxon emigration in the 1990s many villages emptied, and trusts led by patrons including King Charles III now restore roofs and murals. UNESCO lists seven village ensembles, with Viscri and Saschiz among the best known.",
    col: [{ h: "#c8b083", n: "ochre plaster" }, { h: "#8a4a2f", n: "tile rust" }, { h: "#5c5f52", n: "watchtower grey" }, { h: "#7a8f5a", n: "orchard green" }, { h: "#f0e6d2", n: "lime white" }],
    m: ["stone and brick", "oak beam rings", "clay tile and shingle", "lime plaster"],
    tx: ["buttressed wall planes", "catwalk timber", "shingle shadow rows", "plaster crackle"],
    obj: ["storehouse ring chambers", "guild towers", "sacristy lock doors", "catwalk galleries", "crescent-shaped buttresses"],
    ex: ["Biertan fortified church, triple ring and bishop's seat", "Prejmer church, largest fortress church in southeastern Europe", "Viscri village restoration by the Mihai Eminescu Trust"],
    inf: ["Saxon military architecture", "Byzantine-influenced local craft"], rel: ["Trullo", "Svaneti tower houses", "Maramureș wooden churches"],
    par: "medieval Saxon church building", var: ["hall church with wall ring", "basilica type", "peasant citadel type"], cf: ["Svaneti tower houses"],
    src: [
      { n: "Wikipedia — Fortified church", u: "https://en.wikipedia.org/wiki/Fortified_church", t: "B" },
      { n: "Wikipedia — Biertan", u: "https://en.wikipedia.org/wiki/Biertan", t: "B" },
      { n: "UNESCO World Heritage Centre", u: "https://whc.unesco.org", t: "A" },
    ],
    tg: ["transylvania", "saxon", "fortress", "village", "unesco"],
    pop: 24, niche: true,
    vd: { shape: "concentric wall rings around nave", line: "buttress rhythm", composition: "church as castle centre", texture: "plaster and shingle", forms: "towers, granary chambers, catwalks" },
    typ: { display: "sturdy transitional serif", body: "humanist sans", notes: "heritage-sign tone" },
    fnt: { display: "Spectral", body: "Source Sans Pro", notes: "quiet scholarly pairing" },
    lit: { quality: "high plateau light", direction: "long morning rays", temperature: "neutral", shadow: "soft violet-grey" },
    pho: { approach: "aerial village-with-church shots", grade: "muted earthy film" },
    fash: { silhouettes: "rural practical", garments: "linen shirts, wool vests", acc: "copper buttons" },
    env: { places: "hilltop churches, orchard lanes", weather: "storm-light over the plateau" },
    gd: { layout: "concentric defensive plan", icon: "tower-and-ring mark" },
    ui: { background: "#f0e6d2", surface: "plaster cards", components: "buttress-framed panels", motion: "gate-swing reveals" },
    rec: { materials: "plaster, shingle, oak", lighting: "low church windows", objects: "granary pegs, locks, candle stands", music: "transylvanian brass bands", scent: "hay, lime wash, smoke" },
    snd: ["organ drone", "swifts", "bells across valley"],
    dna: { mi: 40, og: 60, wc: 30, ns: 8, ad: 5, hf: 10, rr: 45, ps: 25, sh: 60, ql: 25, oc: 25, ds: 45, rs: 20, eu: 70, np: 20 },
    emo: { warm: 50, cold: 45, playful: 15, serious: 80, chaotic: 15, ordered: 75, nostalgic: 80, futuristic: 5, peaceful: 70, ominous: 30 },
  },
  {
    n: "Kukeri", a: ["kukeri ritual", "Surva masquerade", "Bulgarian mumming"],
    cat: "Regional & Cultural Tradition", c: "Winter ritual masking", e: "regional_tradition",
    o: "Bulgaria", g: "Bulgaria; Balkan analogues",
    p: "pre-Christian roots; living tradition", era: "winter carnival",
    sum: "Bulgaria's furred and belled winter mummers — horned wooden masks, goatskin suits and huge copper chan bells dancing evil out of the village.",
    desc: "Kukeri are masked men who, between Christmas and Lent, clothe themselves in shaggy goatskin and sheep-fleece suits, wear carved wooden masks with horns, beaks and painted sun-discs, and strap belts of giant copper chan bells that announce them a kilometre away. Dancing in deep, sweeping lunges to shake the earth awake and frighten evil spirits, they echo Thracian Dionysian rites recorded on antiquity's reliefs. Regional styles differ: Shiroka Laka's Rhodope masks run to feathers and painted ribbons, while Pernik's Surva festival — held since 1966 — gathers thousands of masked performers from across the Balkans in competitive boulevards of fur and bronze sound. Costumes are made by families and local clubs, maintained for decades. The aesthetic is overwhelming: black wool pile, rawhide, ochre-red painted wood, and thunder as ornament.",
    col: [{ h: "#2b2320", n: "fleece black" }, { h: "#8a3b2a", n: "mask ochre red" }, { h: "#a97e3f", n: "bell bronze" }, { h: "#d9c7a0", n: "sheep fleece" }, { h: "#5a4632", n: "rawhide brown" }],
    m: ["sheep fleece and goatskin", "carved linden masks", "copper bells", "wool rope and ribbons"],
    tx: ["long shaggy pile", "carved horn relief", "hammered metal", "braided tassels"],
    obj: ["horned wooden masks", "chan bell belts", "kuker clubs", "feathered Rhodope masks", "sun-disc cheeks"],
    ex: ["International Festival of Masquerade Games Surva, Pernik", "Kukeri games of Shiroka Laka, Rhodopes", "New Year kukeri rounds in the Razlog region"],
    inf: ["Thracian Dionysian ritual", "Balkan carnival masking"], rel: ["Gelede masquerade", "Karagöz shadow theatre", "Georgian polyphonic singing"],
    par: "Balkan winter mumming", var: ["Rhodope feathered type", "Thracian bell type", "Pernik Surva type"], cf: ["Talchum mask dance"],
    src: [
      { n: "Wikipedia — Kukeri", u: "https://en.wikipedia.org/wiki/Kukeri", t: "B" },
      { n: "Encyclopedia Britannica — Bulgaria", u: "https://www.britannica.com/place/Bulgaria", t: "B" },
    ],
    tg: ["bulgaria", "masks", "ritual", "bells", "carnival"],
    pop: 24, niche: true,
    vd: { shape: "shaggy mountain silhouette", line: "heavy arc-and-stamp dance paths", composition: "processional mass", texture: "fleece, hide, hammered bronze", forms: "masks, bells, clubs" },
    typ: { display: "rugged block serif", body: "sans", notes: "festival-poster weight" },
    fnt: { display: "Bebas Neue", body: "Open Sans", notes: "poster-impact caps" },
    lit: { quality: "cold winter blaze", direction: "low sun through fur", temperature: "cold", shadow: "deep bronze" },
    pho: { approach: "high-shutter action portraits", grade: "contrasty winter colour" },
    fash: { silhouettes: "shaggy monumental", garments: "fleece suits, sashes", acc: "giant bells, masks" },
    env: { places: "village squares, mountain roads", weather: "january frost, breath clouds" },
    gd: { layout: "processional banner strips", icon: "horned sun-disc mask" },
    ui: { background: "#2b2320", surface: "hide-textured cards", components: "bronze bell buttons", motion: "stamp-and-shake pulses" },
    rec: { materials: "fleece, wood, copper", lighting: "torch and low sun", objects: "masks, bells, ritual bread", music: "bagpipe (gaida) and drum", scent: "wool tallow, woodsmoke" },
    snd: ["chan bells thunder", "gaida drone", "ritual shouts"],
    dna: { mi: 10, og: 75, wc: 25, ns: 10, ad: 5, hf: 15, rr: 75, ps: 55, sh: 65, ql: 85, oc: 55, ds: 80, rs: 55, eu: 65, np: 45 },
    emo: { warm: 45, cold: 60, playful: 55, serious: 65, chaotic: 65, ordered: 35, nostalgic: 70, futuristic: 10, peaceful: 25, ominous: 55 },
  },
  {
    n: "Dalmatian dry-stone walling", a: ["gromače", "suhozid", "Adriatic dry stone craft"],
    cat: "Architectural Style", c: "Dry stone landscape craft", e: "regional_tradition",
    o: "Dalmatian coast and islands, Croatia", g: "Adriatic; wider Mediterranean dry-stone belt",
    p: "ancient to living tradition", era: "vernacular continuity",
    sum: "Karst field-clearing made visible — miles of stacked gromače walls, shepherds' bunja shelters and terraced olive gardens of the Dalmatian islands.",
    desc: "Dalmatia's limestone karst yielded nothing until farmers moved the stone: clearing fields produced gromače — dry-stacked walls a metre or more high — running in grid and terrace across Hvar, Brač and the mainland, no mortar in any joint. Shepherds roofed the leftover technique into bunja and kažun shelters, beehive huts with corbelled domes, while hillside terraces held olives and vines against wind and runoff. On Hvar, the Stari Grad Plain still shows Greek parcellation walled in this fashion since the fourth century BC, and Brač's quarries fed Diocletian's Palace with the same white stone. UNESCO inscribed the Art of Dry Stone Walling (Croatia among eight states) in 2018, and volunteer camps now rebuild collapsed stretches. The look is silver-grey geometry: wall and shadow, terraced light, sea beyond.",
    col: [{ h: "#c9c4b4", n: "limestone silver" }, { h: "#8e8874", n: "dry shadow grey" }, { h: "#6d7b4f", n: "olive garden green" }, { h: "#a3b8c9", n: "adriatic haze" }, { h: "#5a4f3d", n: "karst earth" }],
    m: ["limestone fieldstone", "corbelled slab roofing", "olive wood", "sheep-pressed terraces"],
    tx: ["stacked rubble courses", "lichen-washed stone", "thistle-tufted joints", "sun-bleached caps"],
    obj: ["gromače field walls", "bunja beehive huts", "olive terraces", "sheep pens", "stone gate-posts"],
    ex: ["Stari Grad Plain, Hvar (UNESCO 2008)", "Bunja shelters of the Dalmatian hinterland", "Pučišća quarries of Brač"],
    inf: ["Greek colonial land division", "Mediterranean pastoralism"], rel: ["Trullo", "Hórreo", "Svaneti tower houses"],
    par: "Mediterranean dry stone culture", var: ["terrace walls", "beehive shelters", "sheepfold compounds"], cf: ["Trullo"],
    src: [
      { n: "Wikipedia — Dry stone", u: "https://en.wikipedia.org/wiki/Dry_stone", t: "B" },
      { n: "UNESCO Intangible Cultural Heritage", u: "https://ich.unesco.org", t: "A" },
    ],
    tg: ["dalmatia", "dry stone", "karst", "landscape", "unesco"],
    pop: 22, niche: true,
    vd: { shape: "grid and terrace line-work", line: "stacked horizontal courses", composition: "wall-ruled landscape", texture: "lichen silver on stone", forms: "walls, domes, pens" },
    typ: { display: "clean editorial serif", body: "humanist sans", notes: "landscape-essay mood" },
    fnt: { display: "Newsreader", body: "Inter", notes: "quiet text-forward pairing" },
    lit: { quality: "white karst glare", direction: "overhead summer", temperature: "hot", shadow: "blue-grey, dense" },
    pho: { approach: "drone grids and texture details", grade: "sun-bleached high clarity" },
    fash: { silhouettes: "workmanlike", garments: "linen, canvas caps", acc: "none — tools only" },
    env: { places: "walled fields, hill shelters", weather: "bura wind, drought" },
    gd: { layout: "map-like wall grid", icon: "stacked-stone glyph" },
    ui: { background: "#c9c4b4", surface: "rubble-textured cards", components: "stone-cap buttons", motion: "course-by-course stacks" },
    rec: { materials: "stone, olive wood, thyme", lighting: "harsh noon bounce", objects: "walls, huts, sickles", music: "klapa a cappella", scent: "sun-hot stone, rosemary" },
    snd: ["klapa voices", "cicadas", "bura gusts"],
    dna: { mi: 55, og: 70, wc: 40, ns: 5, ad: 5, hf: 15, rr: 60, ps: 20, sh: 70, ql: 20, oc: 25, ds: 45, rs: 25, eu: 80, np: 15 },
    emo: { warm: 55, cold: 40, playful: 15, serious: 70, chaotic: 20, ordered: 75, nostalgic: 70, futuristic: 5, peaceful: 70, ominous: 15 },
  },
  {
    n: "Maltese luzzu", a: ["luzzu boats", "Eyes of Osiris boats", "Marsaxlokk luzzu"],
    cat: "Regional & Cultural Tradition", c: "Fishing boat culture", e: "regional_tradition",
    o: "Malta", g: "Maltese harbours, chiefly Marsaxlokk",
    p: "Phoenician-derived hulls; living fleet", era: "maritime folk",
    sum: "Malta's double-ended fishing boats, painted in candy primaries with the protective Eye of Osiris on the prow — Phoenician apotropaion afloat.",
    desc: "The luzzu is a robust double-ended fishing boat whose lineage is often traced to Phoenician hull forms, most visibly in the pair of painted eyes — the Eye of Osiris or Horus — fixed on the high prow to guard the crew, a symbol continuous with ancient Mediterranean practice. Hulls blaze in red, yellow, blue and green with picked-out gunwales and names in letters between gilded curls; each boat's owners keep the paint as a matter of family pride. Marsaxlokk's Sunday fish market rows them bow-on in the harbour like a floating bazaar, while the smaller kajjik and the passenger dghajsa share the family traits. Storms and engine change have thinned the wooden fleet, and restoration workshops now matter to Malta's heritage scene. The aesthetic: sun-saturated primaries, curling scrollwork, and watchful eyes on blue water.",
    col: [{ h: "#d93a2b", n: "hull red" }, { h: "#e8b93c", n: "gunwale yellow" }, { h: "#1f6fb2", n: "mediterranean blue" }, { h: "#f5efdd", n: "sail white" }, { h: "#2f7d4f", n: "trim green" }],
    m: ["carved hull timber", "marine enamels", "gilded scrollwork", "canvas"],
    tx: ["lapstrake-smooth hull paint", "high-gloss enamel", "curled gold leaf", "salt-chalked trim"],
    obj: ["Eyes of Osiris prows", "twin rudders", "painted name boards", "fish boxes", "harbour awnings"],
    ex: ["Marsaxlokk Sunday fish market fleet", "Malta Maritime Museum, Birgu (Heritage Malta)", "Luzzu races at village festas"],
    inf: ["Phoenician apotropaic iconography", "Sicilian boat decoration"], rel: ["Venetian Carnevale mask", "Terracotta tile", "Calçada Portuguesa"],
    par: "central Mediterranean boatbuilding", var: ["kajjik", "dghajsa passenger boat"], cf: ["gondola"],
    src: [
      { n: "Wikipedia — Luzzu", u: "https://en.wikipedia.org/wiki/Luzzu", t: "B" },
      { n: "Heritage Malta", u: "https://heritage.org.mt", t: "A" },
    ],
    tg: ["malta", "boats", "harbour", "folk", "phoenician"],
    pop: 24, niche: true,
    vd: { shape: "high-prowed double ender", line: "scrolling painted gunwales", composition: "bow-on fleet rows", texture: "glossy enamel on wood", forms: "eyes, curls, name boards" },
    typ: { display: "chip-carved nautical serif", body: "sans", notes: "boat-transom lettering" },
    fnt: { display: "Alfa Slab One", body: "Work Sans", notes: "transom-bold display" },
    lit: { quality: "harbour sparkle", direction: "high mediterranean", temperature: "hot", shadow: "brief and blue" },
    pho: { approach: "bow-on harbour rows at market", grade: "vivid tourist-poster colour" },
    fash: { silhouettes: "fisherman working", garments: "canvas aprons, caps", acc: "none" },
    env: { places: "marsaxlokk quay, fish stalls", weather: "bright wind, glittering chop" },
    gd: { layout: "symmetric eye-centred crest", icon: "osiris eye" },
    ui: { background: "#1f6fb2", surface: "painted hull panels", components: "curl-framed buttons", motion: "gentle rocking" },
    rec: { materials: "timber, enamel, rope", lighting: "morning market glare", objects: "boats, crates, nets", music: "maltese guitar folk", scent: "salt, fish, paint" },
    snd: ["halyard clink", "market calls", "gulls"],
    dna: { mi: 30, og: 60, wc: 15, ns: 25, ad: 10, hf: 15, rr: 40, ps: 60, sh: 35, ql: 55, oc: 35, ds: 60, rs: 30, eu: 65, np: 40 },
    emo: { warm: 80, cold: 20, playful: 65, serious: 40, chaotic: 40, ordered: 50, nostalgic: 75, futuristic: 10, peaceful: 60, ominous: 10 },
  },
  {
    n: "Calçada Portuguesa", a: ["Portuguese pavement", "calcada", "pedra portuguesa"],
    cat: "Material & Surface", c: "Hand-laid stone paving art", e: "regional_tradition",
    o: "Lisbon, Portugal", g: "Portugal and former empire (Macau, Brazil)",
    p: "1840s onward", era: "modern urban craft",
    sum: "Lisbon's hand-cut limestone pavements — black and white waves, ships and gulls laid shard by shard by calceteiros since the Rossio set the canon.",
    desc: "Calçada Portuguesa turns the sidewalk into intarsia: irregular shards of white limestone and black basalt are hand-laid by calceteiros into waves, armillary spheres, ships and fish. The canon was set in the 1840s when the Rossio square was paved with its rolling mar-largo wave pattern, and Lisbon's guilds have trained apprentices ever since, sketching with chalk outlines directly on screed. The craft spread across the Portuguese empire — Macau's wavy hillsides and Rio's Copacabana boardwalk carry it. Its vices are real: marble-hard, slippery in rain, and costly to maintain, prompting debates about replacing it, while the municipality defends it as intangible heritage and the city's signature. Up close it is a mosaic of thousands ofhammered facets; from a window it is drawing on the ground.",
    col: [{ h: "#f2efe6", n: "limestone white" }, { h: "#26262a", n: "basalt black" }, { h: "#8d9db0", n: "rain sheen" }, { h: "#c9b48a", n: "worn cream" }, { h: "#5a7d9a", n: "tile azulejo blue" }],
    m: ["white limestone", "black basalt", "screed bed", "rubber mallets"],
    tx: ["hammered stone facets", "irregular tight joints", "polished wear paths", "wet gloss"],
    obj: ["mar-largo waves", "armillary sphere motifs", "ship and gull scenes", "sidewalk medallions", "chalk patterns"],
    ex: ["Rossio square wave paving, Lisbon (1849)", "Copacabana promenade, Rio de Janeiro", "Macau's calçada waves"],
    inf: ["Roman opus tessellatum paving", "Azulejo pattern culture"], rel: ["Portuguese azulejo tiles", "Terrazzo", "Encaustic cement tile"],
    par: "Iberian stone craft", var: ["mar-largo wave", "figurative scenes", "geometric borders"], cf: ["Terrazzo"],
    src: [
      { n: "Wikipedia — Calçada Portuguesa", u: "https://en.wikipedia.org/wiki/Cal%C3%A7ada_Portuguesa", t: "B" },
      { n: "Câmara Municipal de Lisboa", u: "https://www.lisboa.pt", t: "A" },
    ],
    tg: ["lisbon", "paving", "stone", "urban", "craft"],
    pop: 34, niche: false,
    vd: { shape: "flowing wave field", line: "black-outline drawing in stone", composition: "figure-ground reversal tricks", texture: "facet-glitter mosaic", forms: "waves, ships, gulls, knots" },
    typ: { display: "condensed grotesque", body: "humanist sans", notes: "municipal-sign clarity" },
    fnt: { display: "Oswald", body: "Inter", notes: "street-signage pairing" },
    lit: { quality: "atlantic glare", direction: "low winter sun raking facets", temperature: "neutral", shadow: "glittering points" },
    pho: { approach: "top-down graphic abstraction", grade: "high-contrast monochrome-plus" },
    fash: { silhouettes: "urban smart-casual", garments: "suede shoes beware, trench coats", acc: "leather" },
    env: { places: "hillside streets, tram 28 climbs", weather: "rain-slick evenings" },
    gd: { layout: "continuous ground pattern", icon: "wave-swatch chip" },
    ui: { background: "#f2efe6", surface: "stone-mosaic cards", components: "pebble buttons", motion: "wave-crest flows" },
    rec: { materials: "stone shards, screed", lighting: "after-rain reflection", objects: "mallets, chalk, knee pads", music: "fado guitar", scent: "wet limestone, grilled sardines" },
    snd: ["mallet tapping", "fado", "tram bells"],
    dna: { mi: 45, og: 40, wc: 35, ns: 20, ad: 10, hf: 25, rr: 45, ps: 40, sh: 55, ql: 35, oc: 30, ds: 80, rs: 30, eu: 60, np: 30 },
    emo: { warm: 55, cold: 40, playful: 45, serious: 55, chaotic: 25, ordered: 70, nostalgic: 75, futuristic: 20, peaceful: 50, ominous: 10 },
  },
  {
    n: "Hórreo", a: ["hórreos", "espigueiro", "raised granary"],
    cat: "Architectural Style", c: "Elevated vernacular granary", e: "regional_tradition",
    o: "Galicia and Asturias, northern Iberia", g: "Galicia, Asturias, northern Portugal",
    p: "medieval to 20th century; living landscape", era: "vernacular agrarian",
    sum: "Galicia's ventilated granaries on mushroom-topped stone legs — cross-ventilated, rodent-proof, cross-topped and scattered like shrines across wet green fields.",
    desc: "The hórreo is a raised granary engineered for Atlantic damp: a granite or chestnut chamber slatted for airflow, set on stone pegollos crowned with mushroom-shaped discs that defeat rats, roofed in thatch or tile, and finished with crosses or stars that bless the harvest. Maize arriving from the Americas in the 16th-17th centuries made granaries essential, and Galicia's bocarones — ventilation slits — became the region's architectural signature. Villages like Soajo and Lindoso in Portugal's Peneda-Gerês gather dozens of espigueiros in granary squares still in use each autumn. Carved dates, ships and solar symbols personalize family units, which are built to the measure of the household's land. The aesthetic is compact, dry-stone precision against mist-green meadows — farm rationality raised to talisman.",
    col: [{ h: "#9a9a8f", n: "granite grey" }, { h: "#6f7d4a", n: "rain green" }, { h: "#b7ad93", n: "chestnut tan" }, { h: "#cfd6d8", n: "galician mist" }, { h: "#4a4438", n: "thatch umber" }],
    m: ["granite block", "chestnut timber", "slat ventilation", "thatch or clay tile"],
    tx: ["slotted air-slit walls", "moss-soft stone caps", "grain-worn wood", "wet slate sheen"],
    obj: ["mushroom-capped pegollos", "bocarones slits", "cross finials", "grain doors", "carved harvest dates"],
    ex: ["Espigueiros of Soajo and Lindoso, Peneda-Gerês", "Combarro's shoreline hórreo row, Galicia", "Asturian hórreo with carved pegollos"],
    inf: ["pre-Roman granary types", "Columbian maize economy"], rel: ["Dalmatian dry-stone walling", "Transylvanian fortified churches", "Palladianism"],
    par: "Atlantic vernacular architecture", var: ["galician square type", "asturian rectangular type", "portuguese espigueiro"], cf: ["staddle-stone granaries"],
    src: [
      { n: "Wikipedia — Hórreo", u: "https://en.wikipedia.org/wiki/H%C3%B3rreo", t: "B" },
      { n: "Xunta de Galicia", u: "https://www.xunta.gal", t: "A" },
    ],
    tg: ["galicia", "granary", "vernacular", "granite", "agrarian"],
    pop: 26, niche: true,
    vd: { shape: "slatted box on stilts", line: "horizontal slit rhythm", composition: "lone object in green field", texture: "wet granite and thatch", forms: "mushroom caps, crosses, slits" },
    typ: { display: "earthy humanist serif", body: "humanist sans", notes: "ethnographic-note tone" },
    fnt: { display: "Alegreya", body: "Source Sans Pro", notes: "bookish-rural pairing" },
    lit: { quality: "overcast silver-green", direction: "even wet light", temperature: "cool", shadow: "soft moss-green" },
    pho: { approach: "mist-field wide shots", grade: "desaturated green-grey" },
    fash: { silhouettes: "atlantic rural", garments: "wool capes, rubber boots", acc: "none" },
    env: { places: "maize fields, granary squares", weather: "drizzle and mist" },
    gd: { layout: "scattered field composition", icon: "slatted-box glyph" },
    ui: { background: "#cfd6d8", surface: "stone-slat cards", components: "peg-leg buttons", motion: "gentle wind sway" },
    rec: { materials: "granite, chestnut, thatch", lighting: "diffuse grey daylight", objects: "corn cobs, sacks, crosses", music: "galician gaita", scent: "maize, wet stone, hay" },
    snd: ["rain on thatch", "gaita pipes", "distant cowbells"],
    dna: { mi: 50, og: 75, wc: 30, ns: 5, ad: 5, hf: 15, rr: 55, ps: 25, sh: 55, ql: 20, oc: 20, ds: 25, rs: 25, eu: 85, np: 15 },
    emo: { warm: 45, cold: 55, playful: 20, serious: 65, chaotic: 15, ordered: 75, nostalgic: 80, futuristic: 5, peaceful: 75, ominous: 15 },
  },
  {
    n: "Falles", a: ["Fallas festival", "ninot sculptures", "Valencia fire festival"],
    cat: "Regional & Cultural Tradition", c: "Satirical fire effigies", e: "regional_tradition",
    o: "Valencia, Spain", g: "Valencia region; imitators worldwide",
    p: "18th century roots; UNESCO 2016", era: "modern carnival",
    sum: "Valencia's March inferno of art — towering satirical ninot sculptures that joke through the streets for days, then burn whole in la Cremà.",
    desc: "Falles are enormous figurative sculptures — ninots — built by neighbourhood casal communities from wood, papier-mâché and polystyrene, satirising politicians and fads with a carpenter's cruel accuracy, raised on street corners for the festival of St Joseph. For five days the city runs on gunpowder mascletà barrages, street bands and lights, until la Cremà on 19 March ignites every falla at once, streets turning to a canyon of controlled fire. Each year one ninot is pardoned by public vote — the ninot indultat — and enters the Falles Museum with decades of saved figures. UNESCO inscribed the festival in 2016, and artists' guilds train fallero sculptors through apprenticeships. The aesthetic is saturated pop-baroque: neon spray, flesh-pink modelling, gutter caricature and firelight.",
    col: [{ h: "#e0532f", n: "flame orange" }, { h: "#f6c445", n: "fire yellow" }, { h: "#2f2f6e", n: "night street blue" }, { h: "#d9728f", n: "flesh-pink model" }, { h: "#59c1c9", n: "spray turquoise" }],
    m: ["papier-mâché", "polystyrene", "wood armature", "spray paint", "pyrotechnics"],
    tx: ["carved foam relief", "airbrushed gradients", "charred edges", "tinsel and light"],
    obj: ["ninot figures", "fallera dresses", "mascletà rockets", "pardoned ninots", "street light arches"],
    ex: ["La Cremà, 19 March, Valencia", "Museu Faller with saved ninots", "UNESCO intangible inscription (2016)"],
    inf: ["carpenter's guild effigy burning", "baroque street festival culture"], rel: ["Kukeri", "Kraków szopka", "Día de Muertos ofrenda culture"],
    par: "Iberian street festival", var: ["big falla mayor", "children's falla infantil", "pardoned ninot"], cf: ["Carnival effigy burning"],
    src: [
      { n: "Wikipedia — Falles", u: "https://en.wikipedia.org/wiki/Falles", t: "B" },
      { n: "UNESCO Intangible Cultural Heritage", u: "https://ich.unesco.org", t: "A" },
    ],
    tg: ["valencia", "festival", "fire", "satire", "sculpture"],
    pop: 38, niche: false,
    vd: { shape: "towering figure groups", line: "caricature exaggeration", composition: "street-corner stage sets", texture: "foam, spray, char", forms: "satirical bodies, flowers, crowns" },
    typ: { display: "loud display sans", body: "sans", notes: "fiesta-poster voice" },
    fnt: { display: "Archivo Black", body: "Open Sans", notes: "poster impact with clean body" },
    lit: { quality: "firestorm", direction: "360-degree ember glow", temperature: "hot", shadow: "orange-black" },
    pho: { approach: "long exposure over flames and crowds", grade: "hot high-saturation" },
    fash: { silhouettes: "18th-century fallera dress", garments: "silk fallera gowns with sashes", acc: "gold combs and jewellery" },
    env: { places: "valencia intersections, street altars", weather: "march warm nights" },
    gd: { layout: "poster stack, fire at base", icon: "flaming ninot glyph" },
    ui: { background: "#2f2f6e", surface: "spray-textured cards", components: "ember-glow buttons", motion: "burn-away reveals" },
    rec: { materials: "papier-mâché, foam, fireworks", lighting: "street firelight", objects: "ninots, paella pans, sashes", music: "dolçaina and tabalet bands", scent: "gunpowder, burnt wood, orange blossom" },
    snd: ["mascletà thunder", "brass bands", "crowd roar"],
    dna: { mi: 10, og: 45, wc: 15, ns: 35, ad: 15, hf: 30, rr: 55, ps: 75, sh: 45, ql: 90, oc: 60, ds: 85, rs: 55, eu: 35, np: 55 },
    emo: { warm: 70, cold: 30, playful: 80, serious: 40, chaotic: 80, ordered: 30, nostalgic: 55, futuristic: 30, peaceful: 15, ominous: 40 },
  },
  {
    n: "Basque pelota", a: ["jai alai", "fronton culture", "cesta punta"],
    cat: "Regional & Cultural Tradition", c: "Wall-court ball culture", e: "regional_tradition",
    o: "Basque Country", g: "Basque Country, France and Spain; export to Florida, Latin America, Philippines",
    p: "folk roots; codified 19th century", era: "modern sport-folk",
    sum: "The Basque wall game cosmos — bare-hand pelota, cesta-punta whirls at 200 km/h, and the fronton court anchoring every village square.",
    desc: "Pelota basque is less one sport than a family of wall games played against the fronton — one-, two- or three-walled courts built into church squares and town halls across the Basque Country. Modalities range from bare-hand pelota, where palm meets goatskin ball with a slap like a gunshot, to cesta punta or jai alai, where a long curved wicker cesta slings the ball at speeds ranked among the fastest of any ball sport. The fronton itself is village architecture: painted angle walls with sponsor murals, seating steps facing the play wall, kids practising between matches. The game exported early — Miami jai alai frontons and Manila courts spread the vocabulary. Its aesthetic is stark and kinetic: chalk-white walls, ochre clay, green shirts, black helmets, and the blur of the pelotari's leap.",
    col: [{ h: "#e8e4d8", n: "chalk wall" }, { h: "#b5652f", n: "court clay" }, { h: "#a33524", n: "pelota red" }, { h: "#2f5d3a", n: "shirt green" }, { h: "#d9c7a0", n: "cesta wicker" }],
    m: ["goatskin ball", "wicker cesta", "stone and plaster walls", "lime lines"],
    tx: ["plaster-scuffed walls", "woven cesta basketry", "chalk dust haze", "clay-court grain"],
    obj: ["fronton angle walls", "cesta baskets", "hand slaps", "murals on walls", "stair-step stands"],
    ex: ["Jai alai frontons of Miami and Manila", "Village frontons of the Basque interior", "Cesta punta matches at Gernika"],
    inf: ["village square architecture", "handball traditions"], rel: ["Castells", "Georgian polyphonic singing", "Kukeri"],
    par: "Iberian wall-ball games", var: ["mano (bare hand)", "cesta punta / jai alai", "paleta rubber paddle", "frontenis"], cf: ["Valencian pilota"],
    src: [
      { n: "Wikipedia — Basque pelota", u: "https://en.wikipedia.org/wiki/Basque_pelota", t: "B" },
      { n: "Encyclopedia Britannica — Jai alai", u: "https://www.britannica.com/sports/jai-alai", t: "B" },
    ],
    tg: ["basque", "sport", "fronton", "ball", "village"],
    pop: 28, niche: true,
    vd: { shape: "long open rectangle", line: "diagonal chase trajectories", composition: "wall as opponent", texture: "plaster, wicker, leather", forms: "court, baskets, murals" },
    typ: { display: "heavy athletic sans", body: "sans", notes: "scoreboard immediacy" },
    fnt: { display: "Anton", body: "Inter", notes: "fronton-mural lettering" },
    lit: { quality: "sharp iberian", direction: "raking across court", temperature: "hot", shadow: "hard graphic" },
    pho: { approach: "1/2000s freeze of the leap", grade: "punchy documentary" },
    fash: { silhouettes: "athletic minimal", garments: "white trousers, coloured shirts, beret off-duty", acc: "txapela beret" },
    env: { places: "village squares, covered frontons", weather: "heat and dry wind" },
    gd: { layout: "scoreboard grid", icon: "ball-and-wall mark" },
    ui: { background: "#e8e4d8", surface: "plaster cards", components: "score-strip buttons", motion: "ball-bounce physics" },
    rec: { materials: "wicker, leather, plaster", lighting: "late afternoon slant", objects: "cestas, balls, murals", music: "txistu flute and drum", scent: "dust, leather, sun" },
    snd: ["ball crack", "crowd ohs", "txalaparta clatter"],
    dna: { mi: 55, og: 50, wc: 30, ns: 20, ad: 10, hf: 25, rr: 50, ps: 55, sh: 55, ql: 70, oc: 25, ds: 30, rs: 45, eu: 50, np: 25 },
    emo: { warm: 60, cold: 35, playful: 65, serious: 50, chaotic: 45, ordered: 55, nostalgic: 55, futuristic: 20, peaceful: 30, ominous: 10 },
  },
  {
    n: "Breton parish closes", a: ["enclos paroissiaux", "Breton calvaries", "parish close enclosures"],
    cat: "Religious & Sacred Art", c: "Architectural sacred precincts", e: "historical",
    o: "Finistère and central Brittany", g: "Brittany, France (Léon and Cornouaille)",
    p: "16th-17th centuries", era: "Counter-Reformation folk baroque",
    sum: "Brittany's walled sacred compounds — triumphal arch gate, ossuary and narrative calvaries where granite and painted saints crowd the whole Passion.",
    desc: "In western Brittany, proud rural parishes rebuilt their churches within enclosed compounds — the enclos paroissiaux — entered through a triumphal Roman arch and containing an ossuary, a funeral charniers' porch, and above all a calvary: a granite tree crowded with carved Passion scenes, from Guimiliau's 1580s masterpiece with its narrative crowds and lampooned rich man in hell, to Saint-Thégonnec's staged multi-figure version. Beaumanoir-family masons set Renaissance detail against late-Gothic bones, while local painters layered saints' statues in gilded polychrome inside. The closes express a peculiar Breton theology: communal, tactile, unafraid of death's furniture, funded by linen trade wealth. Over seventy survive, and their grey granite glows under Atlantic rain. They remain among Europe's most distinctive sacred landscapes.",
    col: [{ h: "#8b8b83", n: "granite grey" }, { h: "#4f6650", n: "rain moss green" }, { h: "#b0a27a", n: "lichen gold" }, { h: "#5a4a3a", n: "oak dark" }, { h: "#c9c4bb", n: "pale sky stone" }],
    m: ["granite", "oak (porches)", "polychrome and gilding", "slate"],
    tx: ["knuckle-dense carving", "rain-darkened stone", "gilded saint robes", "slate shadow courses"],
    obj: ["triumphal entry arches", "narrative calvaries", "ossuary chapels", "polychrome saints", "enclosure walls"],
    ex: ["Guimiliau calvary (1581-88)", "Saint-Thégonnec parish close", "Pleyben calvary and ossuary"],
    inf: ["Counter-Reformation imagery", "Breton linen wealth"], rel: ["Irish high crosses", "Religious & Sacred Art", "English Perpendicular"],
    par: "late Gothic parish church", var: ["calvary types", "ossuary-and-arch type"], cf: ["Irish high crosses"],
    src: [
      { n: "Wikipedia — Parish close", u: "https://en.wikipedia.org/wiki/Parish_close", t: "B" },
      { n: "Ministère de la Culture", u: "https://www.culture.gouv.fr", t: "A" },
    ],
    tg: ["brittany", "calvary", "granite", "sacred", "gothic"],
    pop: 20, niche: true,
    vd: { shape: "walled precinct composition", line: "stacked narrative friezes", composition: "gate-ossuary-calvary axis", texture: "granite grain, gilt accents", forms: "crosses, figures, arches" },
    typ: { display: " inscriptional serif", body: "serif", notes: "gravestone dignity" },
    fnt: { display: "Cinzel", body: "Lora", notes: "carved-caps display" },
    lit: { quality: "atlantic silver", direction: "low rain-washed sun", temperature: "cool", shadow: "soft grey-green" },
    pho: { approach: "raking light on carved friezes", grade: "muted stone tones" },
    fash: { silhouettes: "breton rural", garments: "coiffes and black bodices (historic)", acc: "gilded headdress bands" },
    env: { places: "walled closes, yew shade", weather: "four seasons in an hour" },
    gd: { layout: "processional axis through gate", icon: "granite calvary tree" },
    ui: { background: "#c9c4bb", surface: "granite-textured cards", components: "arch-framed panels", motion: "gate-opening wipes" },
    rec: { materials: "granite, oak, gilt", lighting: "candle plus skylight", objects: "calvaries, ossuaries, banners", music: "biniou and bombarde", scent: "damp stone, beeswax, yew" },
    snd: ["bombarde drone", "bells", "rain on slate"],
    dna: { mi: 25, og: 55, wc: 30, ns: 10, ad: 5, hf: 8, rr: 40, ps: 25, sh: 60, ql: 30, oc: 25, ds: 75, rs: 20, eu: 60, np: 30 },
    emo: { warm: 35, cold: 60, playful: 15, serious: 85, chaotic: 20, ordered: 70, nostalgic: 75, futuristic: 5, peaceful: 60, ominous: 40 },
  },
  {
    n: "Provençal santons", a: ["santons de Provence", "little saints", "crèche figurines"],
    cat: "Religious & Sacred Art", c: "Folk crèche figurines", e: "regional_tradition",
    o: "Marseille and Provence", g: "Provence; exported collections",
    p: "1790s onward", era: "post-Revolution folk sacred",
    sum: "Provence's clay little saints — the ravi, the blind man and the whole village crowding the crèche since the Revolution closed the churches.",
    desc: "When Revolutionary law emptied the churches, Marseillais Louis Lagnel began moulding small clay figures around 1797 so families could stage nativity plays at home — and santons, little saints, became Provence's own folk art. The canon fills the crèche with the whole Midi: the ravi (the delighted one), the blind man regaining sight, the miller, the Arlésienne, the tambourinaire with his galoubet, shepherds and hens in pale Provençal colours. Fired in molds from Aubagne and Marseille clay, then hand-painted, santons gained their own annual fair on Marseille's Canebière from 1803, still running each December. Museums in Marseille and workshops in Aubagne keep the canon and the painters' styles distinct. It is folk theology as village portrait: everyone earns a place at the stable.",
    col: [{ h: "#c9a96b", n: "provençal ochre" }, { h: "#7a9e7e", n: "santon green" }, { h: "#a8574e", n: "vest red" }, { h: "#d8cbb2", n: "clay body" }, { h: "#4f6d7a", n: "midi blue" }],
    m: ["Aubagne clay", "plaster molds", "gouache paints", "moss and bark props"],
    tx: ["mold-soft surfaces", "fine hand-painted features", "matte chalky colour", "folded drapery"],
    obj: ["the ravi figure", "blind man", "Arlésienne", "tambourinaire", "provençal crèche props"],
    ex: ["Marseille santon fair since 1803", "Aubagne santon workshops", "Musée des Santons, Marseille"],
    inf: ["crèche tradition", "provençal costume culture"], rel: ["Neapolitan presepe", "Quimper faience", "Falles"],
    par: "Christian nativity craft", var: ["petit santons", "grand santons (custom)", "santons by vocation sets"], cf: ["Neapolitan presepe"],
    src: [
      { n: "Wikipedia — Santon (figurine)", u: "https://en.wikipedia.org/wiki/Santon_(figurine)", t: "B" },
      { n: "Ministère de la Culture", u: "https://www.culture.gouv.fr", t: "A" },
    ],
    tg: ["provence", "nativity", "clay", "folk", "christmas"],
    pop: 26, niche: true,
    vd: { shape: "stiff front-facing villagers", line: "soft mold folds", composition: "crowded village tableau", texture: "matte painted clay", forms: "peasants, animals, props" },
    typ: { display: "warm rounded serif", body: "humanist sans", notes: "fair-stand charm" },
    fnt: { display: "Courgette", body: "Open Sans", notes: "hand-painted sign accent" },
    lit: { quality: "December window light", direction: "warm sidelight", temperature: "warm", shadow: "soft ochre" },
    pho: { approach: "tableau flat-lays with moss", grade: "gentle warm film" },
    fash: { silhouettes: "provençal folk dress", garments: "calénque skirts, brimmed hats", acc: "ribboned coiffes" },
    env: { places: "christmas fairs, farmhouse mantels", weather: "mistral-cold bright days" },
    gd: { layout: "village-in-a-circle layout", icon: "ravi roundel" },
    ui: { background: "#d8cbb2", surface: "clay-textured cards", components: "painted-fig buttons", motion: "tableau slide-ins" },
    rec: { materials: "clay, moss, bark", lighting: "candle warm", objects: "santons, crèche moss, olive sprigs", music: "provencal carols (pastorales)", scent: "cypress, candle wax, clay" },
    snd: ["galoubet-tambourin", "fair chatter", "church bells"],
    dna: { mi: 30, og: 70, wc: 12, ns: 10, ad: 5, hf: 10, rr: 30, ps: 60, sh: 25, ql: 30, oc: 30, ds: 70, rs: 30, eu: 70, np: 35 },
    emo: { warm: 85, cold: 15, playful: 65, serious: 40, chaotic: 25, ordered: 65, nostalgic: 90, futuristic: 5, peaceful: 70, ominous: 5 },
  },
  {
    n: "Limoges champlevé enamel", a: ["Opus Lemovicense", "Limoges enamel", "champlevé reliquaries"],
    cat: "Religious & Sacred Art", c: "Medieval enamel school", e: "historical",
    o: "Limoges, France", g: "churches and treasuries across medieval Europe",
    p: "12th-15th centuries (champlevé); painted enamel after 1470", era: "Gothic craft",
    sum: "Medieval Europe's enamel factory — copper chasses and Becket caskets with jewel-blue grounds and gilt figures, exported by the thousand from Limoges.",
    desc: "From the twelfth century, Limoges workshops carved troughs into copper sheets, filled them with powdered glass, fired, polished and gilded, producing champlevé reliquary chasses, altar crosses and book covers that shipped across Latin Christendom. Their aesthetic is instantly legible: intense cobalt and turquoise grounds against gilt figures with punched stipple halos, flat hieratic bodies, and wheel-cut leaf scrolls. Dozens of caskets depicting the murder of Thomas Becket survive from a single commercial canon — medieval Europe's mass-market devotional art. In the late fifteenth century the city pivoted to painted enamels, with court portraitists like Léonard Limosin working in grisaille and jewel tones on plaques. The V&A and British Museum hold the great collections, and Limoges kept enamel as a living trade.",
    col: [{ h: "#1f4e9c", n: "enamel cobalt" }, { h: "#3aa6a0", n: "turquoise cell" }, { h: "#c8a02c", n: "gilt figure" }, { h: "#7a3b8f", n: "purple enamel" }, { h: "#b87333", n: "copper ground" }],
    m: ["copper plates", "powdered glass frit", "gilding", "fire (kiln)"],
    tx: ["glass-gloss cells", "raised gilt lines", "punched stipple", "kiln-smooth surfaces"],
    obj: ["reliquary chasses", "Becket caskets", "altar crosses", "book covers", "portrait plaques"],
    ex: ["Thomas Becket caskets in the British Museum and V&A", "Léonard Limosin painted enamel portraits", "Limoges enamel collections, Victoria and Albert Museum"],
    inf: ["Byzantine enamel technique", "Gothic goldsmithery"], rel: ["Georgian cloisonné enamel", "Cloisonné enamel", "Religious & Sacred Art"],
    par: "medieval metalwork-enamel", var: ["champlevé", "opus lemovicense", "painted enamel (16th c)"], cf: ["Cloisonné enamel"],
    src: [
      { n: "Wikipedia — Limoges enamel", u: "https://en.wikipedia.org/wiki/Limoges_enamel", t: "B" },
      { n: "Victoria and Albert Museum", u: "https://www.vam.ac.uk", t: "A" },
    ],
    tg: ["enamel", "medieval", "limoges", "relics", "gilt"],
    pop: 22, niche: true,
    vd: { shape: "gabled casket architecture", line: "gilt outline cells", composition: "hieratic register rows", texture: "glassy jewel surface", forms: "chasses, figures, scrolls" },
    typ: { display: "blackletter-adjacent serif", body: "serif", notes: "treasury-inventory tone" },
    fnt: { display: "MedievalSharp", body: "Crimson Pro", notes: "manuscript-flavoured caps" },
    lit: { quality: "candle on gold", direction: "point glints", temperature: "warm", shadow: "deep jewel" },
    pho: { approach: "treasury-case macro with glints", grade: "rich jewelled colour" },
    fash: { silhouettes: "romanesque ceremonial", garments: "coped vestments", acc: "enamel mounts" },
    env: { places: "treasury rooms, crypt light", weather: "still dry air" },
    gd: { layout: "register-row panels", icon: "gabled shrine glyph" },
    ui: { background: "#1f4e9c", surface: "enamel-cell cards", components: "gilt-line buttons", motion: "jewel glint pulses" },
    rec: { materials: "copper, glass, gold leaf", lighting: "candle sparkle", objects: "chasses, caskets, crosses", music: "medieval chant", scent: "incense, beeswax, metal" },
    snd: ["chant", "bell taps", "cases unlocking"],
    dna: { mi: 30, og: 40, wc: 20, ns: 20, ad: 5, hf: 8, rr: 25, ps: 20, sh: 35, ql: 25, oc: 20, ds: 80, rs: 15, eu: 55, np: 30 },
    emo: { warm: 50, cold: 45, playful: 20, serious: 80, chaotic: 15, ordered: 80, nostalgic: 70, futuristic: 5, peaceful: 55, ominous: 25 },
  },
  {
    n: "Aubusson tapestry", a: ["Aubusson-Felletin tapestry", "basse-lice weaving", "Creuse verdure tapestries"],
    cat: "Textile & Craft", c: "Low-warp workshop tapestry", e: "regional_tradition",
    o: "Aubusson and Felletin, Creuse valley", g: "France; palace and bourgeois interiors Europe-wide",
    p: "14th century roots; 1665 manufacture royale; UNESCO 2009", era: "early modern to modern craft",
    sum: "The Creuse valley's flat-woven tapestry tradition — forest verdures, grotesques and Lurçat's modern revival woven on low-warp looms in workshops on both banks.",
    desc: "In the valley of the Creuse, dyers and weavers built Aubusson and Felletin into France's great provincial tapestry centre: low-warp looms weaving upside-down from behind, wool weft over linen warp, producing large flat-woven room-size hangings. Sixteenth-century verdures — dense forests where nobles hunted among monogrammed trees — set a taste that persisted into millefleur borders and later pastoral and exotic scenes; in 1665 royal letters patent gave the town manufacture status. Mid-twentieth-century Jean Lurçat's angular, boldly coloured designs revived the workshops for modern interiors, and cartoon-based weaving continues under the Cité internationale de la tapisserie. UNESCO inscribed the craft in 2009 as living heritage. The look: vegetable-dye greens and madder reds, woven shadow, and edges where forest, cloud and thread meet.",
    col: [{ h: "#3f5d3a", n: "verdure green" }, { h: "#8a3b2a", n: "madder red" }, { h: "#c9b072", n: "gold ochre" }, { h: "#2f4a6b", n: "woad blue" }, { h: "#d9c7a0", n: "linen ground" }],
    m: ["wool weft", "linen warp", "vegetable dyes", "low-warp looms"],
    tx: ["flat woven surface", "weft-line texture", "vegetable-dye depth", "fringe edges"],
    obj: ["verdure forests", "millefleur borders", "grotesque foliage", "cartoon sheets", "loom bobbins"],
    ex: ["Sixteenth-century verdures in the Cité internationale de la tapisserie, Aubusson", "Jean Lurçat modern designs woven in Aubusson", "UNESCO intangible inscription (2009)"],
    inf: ["Flemish tapestry models", "royal manufacture policy"], rel: ["Gobelins tapestry manufactory", "Finnish ryijy rug", "Persian carpet"],
    par: "European tapestry weaving", var: ["verdure", "grotesque style", "pastoral scenes", "modern revival"], cf: ["Gobelins tapestry manufactory"],
    src: [
      { n: "Wikipedia — Aubusson tapestry", u: "https://en.wikipedia.org/wiki/Aubusson_tapestry", t: "B" },
      { n: "UNESCO Intangible Cultural Heritage", u: "https://ich.unesco.org", t: "A" },
    ],
    tg: ["tapestry", "france", "weaving", "verdure", "unesco"],
    pop: 26, niche: true,
    vd: { shape: "wall-filling landscape fields", line: "woven contour shifts", composition: "layered forest depth", texture: "flat weft matte", forms: "trees, beasts, clouds, borders" },
    typ: { display: "old-style serif", body: "serif", notes: "inventory-book tone" },
    fnt: { display: "EB Garamond", body: "Source Serif Pro", notes: "château-label restraint" },
    lit: { quality: "castle-hall dim", direction: "window shafts", temperature: "neutral-cool", shadow: "woven greens" },
    pho: { approach: "flat-on wall documentation", grade: "muted heritage colour" },
    fash: { silhouettes: "aristocratic drapery", garments: "velvet doublets", acc: "tassel trims" },
    env: { places: "chimneypiece walls, workshop lofts", weather: "creuse river mist" },
    gd: { layout: "bordered field with cartouche", icon: "loom-swatch square" },
    ui: { background: "#d9c7a0", surface: "weave-textured cards", components: "bordered buttons", motion: "weft-shuttle sweeps" },
    rec: { materials: "wool, linen, dye vats", lighting: "north workshop light", objects: "looms, cartoons, bobbin racks", music: "baroque viol consort", scent: "wool, river damp, madder" },
    snd: ["loom clack", "river flow", "workshop voices"],
    dna: { mi: 25, og: 65, wc: 30, ns: 8, ad: 5, hf: 15, rr: 30, ps: 25, sh: 35, ql: 20, oc: 25, ds: 85, rs: 25, eu: 65, np: 30 },
    emo: { warm: 50, cold: 45, playful: 25, serious: 70, chaotic: 15, ordered: 80, nostalgic: 85, futuristic: 15, peaceful: 65, ominous: 20 },
  },
];
