/**
 * Curated wave — Wave 2 batch d: Americas deep coverage II.
 * Indigenous and Afro-Atlantic traditions of North America, Mesoamerica,
 * South America and the Caribbean. All entries real and documented.
 */
export const WAVE_AMO2: any[] = [
  {
    n: "Plains tipi painting and parfleche", a: ["painted tipis", "parfleche painting", "buffalo-hide pictorial art"],
    cat: "Textile & Craft", c: "painted hide craft", e: "regional_tradition", o: "Great Plains nations", g: "US and Canadian Plains",
    p: "18th-19th c buffalo era onward", era: "hide-painting classic",
    sum: "Painted tipi liners and rawhide parfleche envelopes — war deeds, thunder beings and bold geometry drawn on hide.",
    desc: "On the buffalo-hunting Plains, hide was the canvas: men's war deeds and Thunderbird visions covered ceremonial tipis and interior liners, while women painted parfleche — folded rawhide envelopes and boxes — with bold black-red-green geometries that outlined every camp. Tipi painting required rights earned through dreams or purchase; each design had an owner and a story. Parfleche cut simple rectilinear fields, tri-color chevrons and hourglasses that prefigured hard-edge abstraction. Buffalo gave way to cowhide and canvas, but painted-liner revivals (Crow, Blackfoot, Lakota) raise painted lodges at encampments today, and museum corpora (National Museum of the American Indian, Fenimore) keep the 19th-century masterpieces visible. The look: sun-warmed hide, crisp pigment contours, narrative bands around a shelter's base.",
    col: [{ h: "#d9b382", n: "buffalo tan" }, { h: "#a63a2b", n: "earth red" }, { h: "#241d18", n: "charcoal black" }, { h: "#d9a441", n: "ochre yellow" }, { h: "#3a5d7a", n: "lake blue" }],
    m: ["buffalo and cow hide", "rawhide (parfleche)", "mineral and plant pigments", "sinew"],
    tx: ["suede nap", "hard rawhide sheen", "brushed pigment fields", "fringed edges"],
    obj: ["painted tipi liners", "parfleche envelopes", "ceremonial tipi exteriors", "shield covers", "drum cases"],
    ex: ["Blackfoot ceremonial lodges at Browning", "Crow tipi backers in NMAI collections", "Lakota parfleche envelope suites"],
    inf: ["rock-art pictorial conventions", "trade-cloth color economy"], rel: ["Plains beadwork", "Navajo weaving", "Haudenosaunee wampum belts"],
    par: "", var: ["painted tipi liner", "parfleche envelope", "shield painting"], cf: ["Plains beadwork"],
    src: [{ n: "Wikipedia — Tipi", u: "https://en.wikipedia.org/wiki/Tipi", t: "B" }, { n: "Wikipedia — Parfleche", u: "https://en.wikipedia.org/wiki/Parfleche", t: "B" }, { n: "National Museum of the American Indian", u: "https://americanindian.si.edu", t: "A" }],
    tg: ["tipi", "parfleche", "hide painting", "plains", "pictographic"], pop: 38, niche: false,
    vd: { shape: "rectilinear envelope fields", line: "crisp pigment contour", composition: "banded narrative ring", texture: "hide nap under pigment", forms: "thunderbirds, warriors, hourglasses" },
    typ: { display: "humanist serif", body: "humanist sans", notes: "museum label" },
    fnt: { display: "Cormorant Garamond", body: "Source Sans 3", notes: "field-guide serif over plain sans" },
    lit: { quality: "high-plain daylight", direction: "raking", temperature: "warm", shadow: "hide texture" },
    pho: { approach: "documentary of lodges and flat-laid parfleche", grade: "warm earthy film" },
    fash: { silhouettes: "wrap robes, straight-cut shirts", garments: "quilled or painted robes", acc: "painted shields, parfleche saddle bags" },
    env: { places: "tipi encampments, prairie rivers", weather: "big-sky wind" },
    gd: { layout: "banded rows with central medallion", icon: "hourglass and chevron motif" },
    ui: { background: "hide tan", surface: "parchment cards", components: "chevron buttons", motion: "envelope fold" },
    rec: { materials: "rawhide, framed hides on log walls", lighting: "warm raking", objects: "parfleche, shields, tipi models", music: "plains drum songs", scent: "sage, hide, grass" },
    snd: ["plains drum", "wind across grass"],
    dna: { mi: 40, og: 60, wc: 25, ns: 5, ad: 5, hf: 10, rr: 30, ps: 35, sh: 35, ql: 30, oc: 30, ds: 60, rs: 30, eu: 80, np: 40 },
    emo: { warm: 70, cold: 30, playful: 30, serious: 65, chaotic: 25, ordered: 75, nostalgic: 75, futuristic: 5, peaceful: 50, ominous: 25 },
  },
  {
    n: "Osage ribbonwork", a: ["Osage ribbon appliqué", "ribbon shirts and dresses", "Wazhazhe ribbonwork"],
    cat: "Fashion & Dress", c: "silk ribbon appliqué", e: "regional_tradition", o: "Osage Nation, Oklahoma", g: "Oklahoma, Southern Plains",
    p: "late 19th c to present", era: "early 20th c flowering",
    sum: "Layered silk ribbons cut into stepped and fan patterns — the regalia that crowned Osage oil-era pride.",
    desc: "Osage women transformed trade silk ribbons into an appliqué art without rival: up to five layered colors, cut in concentric stepped diamonds, fans and half-moons, whipstitched onto blankets and dresses so each layer peeks beneath the next. The women's blanket dress with ribbon yoke and the men's ribbon shirt became core regalia for the Inlonshka dances that accompanied the oil-rich 1920s (and remain central today). Ribbonwork replaced older quilled and painted decoration, absorbing trade-cloth geometry into a distinctly Osage signature, family-sewn and passed down. Museums (NMAI, Gilcrease) collect the 1900s-1930s masterworks; dance grounds around Pawhuska and Hominy keep the style in live motion. The look: radiating silk steps in candy-bright hues over dark wool.",
    col: [{ h: "#c0392b", n: "silk red" }, { h: "#f2c14e", n: "silk gold" }, { h: "#2e6f6a", n: "silk teal" }, { h: "#7a3b8f", n: "silk purple" }, { h: "#2b2b2b", n: "broadcloth ground" }],
    m: ["commercial silk ribbon", "broadcloth", "cotton lining", "thread whipstitch"],
    tx: ["layered ribbon relief", "scissor-cut edges", "flat wool ground", "satin sheen bands"],
    obj: ["blanket dresses", "ribbon shirts", "yoke panels", "dance shawls", "legging strips"],
    ex: ["Inlonshka dance regalia at Gray Horse", "NMAI ribbonwork corpora", "1920s oil-era photograph dress"],
    inf: ["Great Lakes ribbon-appliqué relatives", "millinery ribbon-trade abundance"], rel: ["Seminole patchwork", "Plains beadwork", "Osage Nation dances"],
    par: "", var: ["blanket dress", "ribbon shirt", "straight dance suit"], cf: ["Great Lakes ribbonwork", "Seminole patchwork"],
    src: [{ n: "Wikipedia — Osage Nation", u: "https://en.wikipedia.org/wiki/Osage_Nation", t: "B" }, { n: "National Museum of the American Indian", u: "https://americanindian.si.edu", t: "A" }],
    tg: ["ribbonwork", "osage", "applique", "regalia", "oklahoma"], pop: 24, niche: true,
    vd: { shape: "stepped diamond stacks", line: "concentric cut edges", composition: "yoke-centered panels", texture: "silk layers", forms: "fans, half-moons, steps" },
    typ: { display: "humanist serif", body: "humanist sans", notes: "exhibit caption" },
    fnt: { display: "Fraunces", body: "Work Sans", notes: "warm display serif, plain body" },
    lit: { quality: "dance-ground sun", direction: "frontal", temperature: "warm", shadow: "ribbon layers" },
    pho: { approach: "dancer portraits mid-step", grade: "vivid warm slide film" },
    fash: { silhouettes: "blanket-drape dress, tucked shirt", garments: "ribbon yoke dresses, ribbon shirts", acc: "beaded belts, silver brooches" },
    env: { places: "arbor dance grounds, tallgrass prairie", weather: "summer heat shimmer" },
    gd: { layout: "stepped-border frames", icon: "layered diamond" },
    ui: { background: "deep wool", surface: "silk-step cards", components: "layered buttons", motion: "ribbon unfold" },
    rec: { materials: "ribbon panels, dark cloth", lighting: "warm spot", objects: "dresses, photographs, brooches", music: "Inlonshka songs", scent: "silk, cut grass" },
    snd: ["southern plains drum", "women's back-up songs"],
    dna: { mi: 45, og: 55, wc: 20, ns: 15, ad: 10, hf: 15, rr: 25, ps: 45, sh: 30, ql: 35, oc: 25, ds: 65, rs: 25, eu: 65, np: 35 },
    emo: { warm: 80, cold: 15, playful: 45, serious: 55, chaotic: 15, ordered: 85, nostalgic: 80, futuristic: 15, peaceful: 55, ominous: 10 },
  },
  {
    n: "Seminole patchwork", a: ["Seminole strip patchwork", "Seminole stripcloth", "Florida Seminole clothing"],
    cat: "Textile & Craft", c: "strip patchwork", e: "regional_tradition", o: "Seminole Tribe of Florida", g: "Florida, Oklahoma",
    p: "late 19th c to present", era: "living tradition",
    sum: "Treadle-machine strip patchwork — bands of tiny geometric cut-and-turn blocks that became Seminole identity cloth.",
    desc: "Around the turn of the 20th century Seminole women, sewing on treadle machines in camp, invented a patchwork revolution: long bands ('strips') built by cutting commercial cotton into tiny pieces and reassembling them into sawtooths, checkers, and flashing rainburst blocks, then seamed into skirts, capes and big shirts. Machine-speed geometry let patterns grow ever more complex — some bands carry dozens of color changes per inch. Patchwork clothing announced Seminole survival after the wars, dressed women at Green Corn Dance, and anchored the tourist economy of the Tamiami Trail mid-century. Ah-Tah-Thi-Ki Museum preserves the classic era; today's seamstresses keep flagship bands alive for medicine society and pageant wear. The look: incandescent micro-geometry, strip after strip, hard edges, hot palettes.",
    col: [{ h: "#e63946", n: "cotton red" }, { h: "#f4d35e", n: "cotton yellow" }, { h: "#1d6fa5", n: "cotton blue" }, { h: "#f1faee", n: "cotton white" }, { h: "#2b2118", n: "cotton black" }],
    m: ["commercial cotton", "treadle sewing machine", "thread", "commercial trim"],
    tx: ["seamed micro-blocks", "crisp strip bands", "flat machine stitch", "pressed flat seams"],
    obj: ["patchwork skirts", "grandmother capes", "big shirts", "patchwork bands", "doll clothing"],
    ex: ["Green Corn Dance dress", "Tamiami Trail tourist-era ensembles", "Ah-Tah-Thi-Ki Museum collections"],
    inf: ["trade-cloth economy", "mission-school sewing education"], rel: ["Osage ribbonwork", "Guna mola panels", "Quilting and trapunto"],
    par: "", var: ["big shirt", "cape and skirt set", "contemporary band revival"], cf: ["Osage ribbonwork", "mola"],
    src: [{ n: "Wikipedia — Seminole", u: "https://en.wikipedia.org/wiki/Seminole", t: "B" }, { n: "Ah-Tah-Thi-Ki Museum", u: "https://www.ahtahthiki.com", t: "A" }],
    tg: ["patchwork", "seminole", "stripcloth", "florida", "sewing"], pop: 30, niche: true,
    vd: { shape: "sawtooth and checker bands", line: "seam-as-line", composition: "horizontal strip stack", texture: "pressed cotton", forms: "rainbursts, checkers, diamonds" },
    typ: { display: "geometric sans", body: "humanist sans", notes: "trading-post tag" },
    fnt: { display: "Space Grotesk", body: "DM Sans", notes: "crisp geometry echoes the strips" },
    lit: { quality: "bright swamp light", direction: "even", temperature: "warm", shadow: "seam ridges" },
    pho: { approach: "flat-lay band studies, dress portraits", grade: "saturated, high-key" },
    fash: { silhouettes: "full skirt, cape-shouldered top", garments: "patchwork skirts and capes", acc: "bead necklaces, silver coins" },
    env: { places: "cypress camps, Tamiami Trail chickees", weather: "humid subtropical glare" },
    gd: { layout: "strip-band header rules", icon: "sawtooth block" },
    ui: { background: "cream cotton", surface: "patch-band cards", components: "striped buttons", motion: "band slide" },
    rec: { materials: "folded bands, vintage machine", lighting: "bright even", objects: "skirts, capes, thread chests", music: "Seminole stomp dance", scent: "cotton, starch, pond" },
    snd: ["stomp-dance shell shaker", "treadle rhythm"],
    dna: { mi: 40, og: 35, wc: 15, ns: 25, ad: 15, hf: 15, rr: 25, ps: 50, sh: 30, ql: 35, oc: 20, ds: 70, rs: 20, eu: 55, np: 35 },
    emo: { warm: 75, cold: 20, playful: 55, serious: 50, chaotic: 15, ordered: 85, nostalgic: 70, futuristic: 20, peaceful: 55, ominous: 10 },
  },
  {
    n: "Cherokee rivercane basketry", a: ["Cherokee double-weave baskets", "rivercane baskets", "Tsalagi basketry"],
    cat: "Textile & Craft", c: "double-weave basketry", e: "regional_tradition", o: "Cherokee Nation and Eastern Band", g: "North Carolina, Oklahoma, Georgia",
    p: "pre-contact to present", era: "living tradition",
    sum: "Split rivercane woven into double-walled baskets — inside-out sculpture with diagonal mountain-night patterns.",
    desc: "Cherokee weavers split rivercane (Arundinaria gigantea) into supple slats and weave them into a signature double-walled form: one basket born inside another, the first turned like a glove and interwoven so walls lock without glue. Diagonal spoke-and-twill patterning reads as mountains, night skies and river marks, in natural cane tan, black walnut dye and bloodroot red. Basketry carried seed, food and story before contact, survived removal, and was revived at Qualla Boundary by weavers such as Lottie Stamper and Eva Wolfe (National Heritage Fellowship), whose families and Qualla Arts cooperative continue today. Cane stands have shrunk, making large old baskets rare museum treasures (Museum of the Cherokee Indian, NMAI). The look: glossy golden weave, tight as cloth, sculptural double walls.",
    col: [{ h: "#c9a227", n: "cane gold" }, { h: "#4a3728", n: "walnut black" }, { h: "#8a3324", n: "bloodroot red" }, { h: "#e8dcc0", n: "pale cane" }, { h: "#5c6b3c", n: "riverbank green" }],
    m: ["rivercane slats", "walnut dye", "bloodroot dye", "cutting knives"],
    tx: ["tight twill weave", "glossy slat sheen", "double-wall relief", "rattling dry clack"],
    obj: ["double-weave storage baskets", "carrying baskets", "market baskets", "wedding baskets", "miniatures"],
    ex: ["Eva Wolfe award baskets", "Qualla Arts and Crafts cooperative sales", "Museum of the Cherokee Indian corpora"],
    inf: ["woodland cane-lodge weaving", "Appalachian white-oak basketry"], rel: ["Pomo basketry", "Chilkat weaving (Tlingit)", "Birchbark biting (Ojibwe)"],
    par: "", var: ["double-weave", "single-wall twill", "mat and sifter forms"], cf: ["Pomo basketry"],
    src: [{ n: "Wikipedia — Cherokee", u: "https://en.wikipedia.org/wiki/Cherokee", t: "B" }, { n: "National Museum of the American Indian", u: "https://americanindian.si.edu", t: "A" }],
    tg: ["basketry", "cherokee", "rivercane", "double-weave", "appalachia"], pop: 28, niche: true,
    vd: { shape: "flaring double walls", line: "diagonal twill flow", composition: "interlocked shell-in-shell", texture: "slat gloss", forms: "mountains, night patterns, river chevrons" },
    typ: { display: "humanist serif", body: "humanist sans", notes: "gallery label" },
    fnt: { display: "Marcellus", body: "Lora", notes: "quiet classical pairing" },
    lit: { quality: "porch daylight", direction: "angled", temperature: "warm", shadow: "weave ridges" },
    pho: { approach: "still-life on wood, hands-at-work", grade: "natural warm" },
    fash: { silhouettes: "tear dresses, hunting shirt", garments: "cotton and ribbon-trim dress", acc: "basket shoulder straps, bead belts" },
    env: { places: "canebrakes, Qualla craft shops", weather: "Blue Ridge mist" },
    gd: { layout: "diagonal weave grid", icon: "mountain chevron" },
    ui: { background: "cane cream", surface: "weave-texture cards", components: "woven buttons", motion: "over-under weave" },
    rec: { materials: "baskets on shelves, cane bundles", lighting: "soft warm", objects: "baskets, dye pots, photos", music: "Cherokee hymns and flute", scent: "cane, walnut husk" },
    snd: ["river water", "cane slicing"],
    dna: { mi: 55, og: 75, wc: 20, ns: 5, ad: 5, hf: 10, rr: 30, ps: 40, sh: 30, ql: 25, oc: 20, ds: 55, rs: 20, eu: 80, np: 30 },
    emo: { warm: 75, cold: 20, playful: 35, serious: 60, chaotic: 10, ordered: 85, nostalgic: 75, futuristic: 10, peaceful: 65, ominous: 10 },
  },
  {
    n: "Pomo basketry", a: ["Pomo baskets", "California Indian basketry", "feathered show baskets"],
    cat: "Textile & Craft", c: "fine-stitch coiling", e: "regional_tradition", o: "Pomo peoples, Northern California", g: "Clear Lake and Russian River country, California",
    p: "pre-contact to present", era: "late 19th c masterpiece era",
    sum: "Among the world's finest baskets — sixty stitches to the inch, feathered showpieces and shell-studded gifts.",
    desc: "Pomo weavers coiled sedge root, willow and redbud with a precision that set a world standard: stitch counts approaching sixty per inch, walls thin as parchment, forms from water-tight cooking baskets to gem-like miniatures. Finest of all are the gift baskets ('show baskets') feathered with valley quail and woodpecker crest, banded with olive shell discs and abalone pendants — wealth objects made for ceremonies and world's-fair display, where 1890s Pomos won medals. Basketry braided economy, medicine and cosmology; bundles of feathers record trades across language lines. The 20th-century collapse of gathering grounds nearly ended it, but families such as the Bensons and weavers like Susan Billy rebuilt teaching lines; Grace Hudson Museum holds the classic corpus. The look: jewel-dense surface, color from feather and shell, not dye.",
    col: [{ h: "#b78b4e", n: "sedge root" }, { h: "#7c3f2c", n: "redbud shoot" }, { h: "#2e4a3a", n: "quail green sheen" }, { h: "#d94f3d", n: "woodpecker red" }, { h: "#e9e2d0", n: "shell white" }],
    m: ["sedge root", "willow", "redbud shoots", "feathers and shells"],
    tx: ["extremely fine coil", "feather pile", "shell disc relief", "parchment-thin walls"],
    obj: ["show baskets", "cooking baskets", "miniature gift baskets", "feathered trays", "shell-studded rims"],
    ex: ["World's Fair prize baskets (1890s)", "Grace Hudson Museum holdings", "Susan Billy teaching-line baskets"],
    inf: ["Californian acorn-economy basketry", "World's Fair collecting era"], rel: ["Cherokee rivercane basketry", "Tlingit Chilkat weaving", "Pueblo pottery"],
    par: "", var: ["show basket", "cooking basket", "miniature"], cf: ["Cherokee rivercane basketry"],
    src: [{ n: "Wikipedia — Pomo", u: "https://en.wikipedia.org/wiki/Pomo", t: "B" }, { n: "Grace Hudson Museum", u: "https://www.gracehudsonmuseum.org", t: "A" }],
    tg: ["basketry", "pomo", "california", "coiling", "feathers"], pop: 26, niche: true,
    vd: { shape: "dome and jar profiles", line: "concentric coil rings", composition: "medallion-centered spiral", texture: "feather pile over weave", forms: "shell medallions, feather bands" },
    typ: { display: "humanist serif", body: "humanist sans", notes: "museum label" },
    fnt: { display: "Cormorant Garamond", body: "Inter", notes: "delicate serif for delicate craft" },
    lit: { quality: "museum spot", direction: "top raking", temperature: "warm", shadow: "coil depth" },
    pho: { approach: "macro texture studies", grade: "warm archival" },
    fash: { silhouettes: "wrap skirts, buckskin dresses", garments: "ceremonial shell dresses", acc: "shell necklaces, feather pins" },
    env: { places: " tule marshes, oak savanna", weather: "lake-morning fog" },
    gd: { layout: "spiral medallion motif", icon: "coil ring" },
    ui: { background: "shell white", surface: "feather-texture cards", components: "disc buttons", motion: "coil spin" },
    rec: { materials: "glassed baskets, willow rods", lighting: "soft spot", objects: "baskets, shells, feathers", music: "Pomo hand-game songs", scent: "sedge, lake reed" },
    snd: ["clapperstick rhythm", "marsh birds"],
    dna: { mi: 60, og: 80, wc: 25, ns: 5, ad: 5, hf: 10, rr: 20, ps: 40, sh: 25, ql: 20, oc: 20, ds: 60, rs: 25, eu: 85, np: 30 },
    emo: { warm: 70, cold: 25, playful: 40, serious: 60, chaotic: 10, ordered: 90, nostalgic: 70, futuristic: 10, peaceful: 65, ominous: 10 },
  },
  {
    n: "Haudenosaunee wampum belts", a: ["wampum belts", "wampum", "Guswenta (Two Row belt)"],
    cat: "Textile & Craft", c: "shell-bead diplomacy", e: "regional_tradition", o: "Haudenosaunee Confederacy", g: "Northeastern Woodlands",
    p: "17th-19th c classical era, revived", era: "diplomatic classic",
    sum: "Purple-and-white quahog bead belts that 'speak' — treaties, laws and grief woven in shell.",
    desc: "Wampum belts weave cylindrical quahog-clam and whelk beads into purple-on-white pictograms: the Hiawatha belt's five linked symbols of the Confederacy, the Two Row's parallel lines of ship and canoe ('we travel this river together'), Covenant Chain, Condolence belts that wipe tears at succession. Belts were laid on councils and 'read' aloud — legal documents in shell, cared for by appointed keepers. Made on bow-string looms from hundreds of thousands of drilled beads, they anchored Northeast diplomacy with Dutch, English and colonial powers. Colonists debased wampum as currency, but the belts themselves remained Haudenosaunee; repatriations returned historic belts to nations, and new belts record modern agreements. The look: deep purple figures on white ground, rows straight as law.",
    col: [{ h: "#2e1f4f", n: "quahog purple" }, { h: "#efe8d8", n: "whelk white" }, { h: "#5b4a78", n: "faded purple" }, { h: "#c9bfa4", n: "hemp cord" }, { h: "#1a1a1a", n: "ground dark" }],
    m: ["quahog shell", "whelk shell", "hemp or sinew warp", "leather backing"],
    tx: ["cylinder-bead rows", "slight bead shimmer", "soft belt drape", "purple grain depth"],
    obj: ["Hiawatha belt", "Two Row (Guswenta) belt", "Covenant Chain belt", "Condolence belts", "strand necklaces"],
    ex: ["Repatriated Confederacy belts (New York State Museum)", "Ganondagan interpretive belts", "contemporary treaty-anniversary belts"],
    inf: ["shell-bead exchange networks", "colonial treaty diplomacy"], rel: ["Haudenosaunee raised beadwork", "Birchbark biting (Ojibwe)", "Zulu beadwork"],
    par: "", var: ["treaty belts", "condolence strings", "personal strands"], cf: ["Haudenosaunee raised beadwork"],
    src: [{ n: "Wikipedia — Wampum", u: "https://en.wikipedia.org/wiki/Wampum", t: "B" }, { n: "Ganondagan State Historic Site", u: "https://ganondagan.org", t: "A" }],
    tg: ["wampum", "haudenosaunee", "treaty", "shell beads", "diplomacy"], pop: 34, niche: false,
    vd: { shape: "rectangular belt fields", line: "row-built pictograms", composition: "central figure bands", texture: "bead cylinder gloss", forms: "figures, parallel lines, linked squares" },
    typ: { display: "humanist serif caps", body: "humanist sans", notes: "treaty panel label" },
    fnt: { display: "Spectral", body: "Inter", notes: "sober document-like pairing" },
    lit: { quality: "longhouse even", direction: "frontal", temperature: "cool", shadow: "bead relief" },
    pho: { approach: "flat-lay documentation, council-hall context", grade: "neutral archival" },
    fash: { silhouettes: "garment and blanket drape", garments: "ribbon-trimmed leggings, broadcloth", acc: "wampum strands, silver brooches" },
    env: { places: "longhouse interiors, treaty sites", weather: "woodland overcast" },
    gd: { layout: "banded horizontal composition", icon: "two parallel rows" },
    ui: { background: "parchment", surface: "bead-row cards", components: "pill buttons", motion: "row slide" },
    rec: { materials: "belts in cases, cordage", lighting: "even cool", objects: "belts, strings, documents", music: "water drum songs", scent: "cedar, river shell" },
    snd: ["water drum", "horn rattle"],
    dna: { mi: 55, og: 60, wc: 15, ns: 5, ad: 5, hf: 15, rr: 25, ps: 30, sh: 30, ql: 20, oc: 10, ds: 50, rs: 15, eu: 70, np: 20 },
    emo: { warm: 60, cold: 35, playful: 20, serious: 80, chaotic: 10, ordered: 90, nostalgic: 70, futuristic: 15, peaceful: 60, ominous: 15 },
  },
  {
    n: "Yup'ik masks", a: ["Yupik ceremonial masks", "Yup'ik dance masks", "Agayuliyararput collection"],
    cat: "Religious & Sacred Art", c: "ceremonial dance masks", e: "regional_tradition", o: "Yup'ik villages, Yukon-Kuskokwim Delta", g: "Southwest Alaska",
    p: "19th c ceremonial era, revived", era: "surrealist-coveted classic",
    sum: "Swinging driftwood dream-masks — white faces, red lines and feather fans that made visions dance.",
    desc: "Yup'ik carved driftwood masks are dream-engineering: shaman-visions made visible for winter ceremonies, with swinging appendages, hoops and feather fans that made stories move as dancers swayed — each mask narrating its origin in performance. Worn with finger-masks by women dancers, they served Bladder Festival and Kelek rites honoring animals who 'give themselves' to hunters. Mission-era suppression and the great early-1900s collections (Sheldon Jackson; the 1905 Agayuliyararput assemblage) emptied villages, scattering masks to Paris, New York and Berlin — where their pop-eyed transformations helped feed Surrealist taste for the visionary. Carving revived in the 1960s and community shows now re-teach the forms. The look: white-faced, red-lined beings, ringed with feathers, half animal half weather.",
    col: [{ h: "#e8ded0", n: "chalk white" }, { h: "#b03a2e", n: "ceremonial red" }, { h: "#22303c", n: "tattoo dark" }, { h: "#7d90a0", n: "driftwood grey" }, { h: "#e5d8a8", n: "feather straw" }],
    m: ["driftwood", "feathers", "sinew cordage", "mineral paint"],
    tx: ["carved shallow relief", "feather fringe motion", "paint crackle", "seal-oil sheen"],
    obj: ["dream masks", "finger masks", "hoop-and-plume appendages", "bladder-festival masks", "story masks"],
    ex: ["1905 Agayuliyararput masks in world museums", "Anchorage Museum rotating Yup'ik exhibits", "contemporary village carving revivals"],
    inf: ["hunter cosmology of animal persons", "shamanic dream practice"], rel: ["Kwakwaka'wakw Hamat'sa regalia", "Hopi kachina doll carving", "Inuit printmaking"],
    par: "", var: ["festival masks", "story masks", "finger masks"], cf: ["Kwakwaka'wakw masks", "kachina dolls"],
    src: [{ n: "Wikipedia — Yup'ik masks", u: "https://en.wikipedia.org/wiki/Yup%27ik_masks", t: "B" }, { n: "Anchorage Museum", u: "https://www.anchoragemuseum.org", t: "A" }],
    tg: ["masks", "yupik", "alaska", "ceremony", "driftwood"], pop: 28, niche: true,
    vd: { shape: "face-plus-ring appendage forms", line: "red contour lines", composition: "centered face with orbiting fans", texture: "painted driftwood", forms: "animal-persons, weather faces, seal spirits" },
    typ: { display: "humanist sans", body: "humanist sans", notes: "exhibit caption" },
    fnt: { display: "Space Grotesk", body: "Newsreader", notes: "modern sans over storybook serif" },
    lit: { quality: "qasgiq firelight", direction: "flickering side", temperature: "warm", shadow: "feather swing" },
    pho: { approach: "museum macro plus archival dance photos", grade: "cool-neutral with warm highlights" },
    fash: { silhouettes: "fur parkas, dance tunics", garments: "ground-squirrel parkas", acc: "finger masks, walrus ivory" },
    env: { places: "qasgiq community houses, frozen delta", weather: "blizzard to blue ice" },
    gd: { layout: "centered mask with orbiting elements", icon: "hoop-and-plume" },
    ui: { background: "ice grey", surface: "mask-plinth cards", components: "ring buttons", motion: "feather sway" },
    rec: { materials: "masks on plinths, fur", lighting: "warm low", objects: "masks, parkas, drums", music: "Yup'ik dance songs", scent: "woodsmoke, tundra" },
    snd: ["cauyaq drum", "crow calls"],
    dna: { mi: 45, og: 75, wc: 20, ns: 5, ad: 5, hf: 15, rr: 30, ps: 45, sh: 35, ql: 40, oc: 30, ds: 55, rs: 45, eu: 70, np: 40 },
    emo: { warm: 55, cold: 45, playful: 45, serious: 65, chaotic: 30, ordered: 65, nostalgic: 60, futuristic: 15, peaceful: 40, ominous: 35 },
  },
  {
    n: "Kwakwaka'wakw Hamat'sa regalia", a: ["Hamatsa dance regalia", "cannibal dance costume", "Kwakiutl winter dance regalia"],
    cat: "Religious & Sacred Art", c: "winter-dance regalia", e: "regional_tradition", o: "Kwakwaka'wakw, northern Vancouver Island", g: "British Columbia coast",
    p: "19th c documented to present", era: "living tradition",
    sum: "Red-cedar-bark regalia for the Hamat'sa — the wild one tamed by dance, ringed in shredded bark and transformation.",
    desc: "The Hamat'sa ('cannibal dance') dramatizes a youth seized by Man-Eater-at-North-End-of-World and slowly tamed through ceremonial dances at a potlatch. His regalia is deliberately feral: shredded red cedar-bark head ring and waist loops that explode with motion, hemlock-branch props, bird whistles answered from the rafters, and carved regalia — raven rattles, transformation masks snapping from one being to another on concealed levers. Field photographs of 1914-1930s winter dances document the iconic look. Canada's potlatch ban (1885-1951) jailed dancers and confiscated regalia; the repatriated treasures anchor the U'mista Cultural Centre in Alert Bay, where the dance is performed again. The look: crimson bark storm around a black-painted body, feathers and masks in ferocious orbit.",
    col: [{ h: "#a02c22", n: "cedar-bark red" }, { h: "#1a1a1a", n: "body black" }, { h: "#c46a4a", n: "bark copper" }, { h: "#f2ead9", n: "mask white" }, { h: "#22303c", n: "design navy" }],
    m: ["red cedar bark", "hemlock boughs", "carved wood masks", "raven rattle"],
    tx: ["shredded bark fringe", "deep mask relief", "paint on skin", "copper gleam"],
    obj: ["bark head rings", "waist and ankle loops", "transformation masks", "raven rattles", "ceremonial whistles"],
    ex: ["U'mista Cultural Centre repatriated regalia", "Alert Bay big house winter dances", "Edward Curtis winter-dance photographs"],
    inf: ["cannibal-dance myth cycle", "Northwest Coast potlatch law"], rel: ["Haida formline art", "Pacific Northwest totem pole carving", "Yup'ik masks"],
    par: "", var: ["tamed-stage dances", "transformation mask sequences", "red-cedar-bark dancer"], cf: ["totem pole carving", "Yup'ik masks"],
    src: [{ n: "Wikipedia — Hamatsa", u: "https://en.wikipedia.org/wiki/Hamatsa", t: "B" }, { n: "U'mista Cultural Centre", u: "https://www.umista.ca", t: "A" }],
    tg: ["hamatsa", "kwakwakawakw", "potlatch", "regalia", "cedar bark"], pop: 30, niche: false,
    vd: { shape: "orb of bark around figure", line: "formline painted joints", composition: "fire-centered dance ring", texture: "shredded bark halo", forms: "raven, man-eater, transformation faces" },
    typ: { display: "humanist sans caps", body: "humanist sans", notes: "big-house signage" },
    fnt: { display: "Sora", body: "Inter", notes: "sturdy sans for big-house gravity" },
    lit: { quality: "big-house fire", direction: "circular flicker", temperature: "warm", shadow: "bark-storm shadow play" },
    pho: { approach: "longhouse stage documentation", grade: "high-contrast warm" },
    fash: { silhouettes: "blanket-wrapped, bark-fringed", garments: "cedar-bark ceremonial dress", acc: "raven rattles, copper shields" },
    env: { places: "Alert Bay big house, beaches", weather: "coastal drizzle" },
    gd: { layout: "radial fire-centered poster", icon: "split-U thunderbird" },
    ui: { background: "deep black", surface: "bark-red cards", components: "ovoid buttons", motion: "mask transform" },
    rec: { materials: "bark regalia, drum skins", lighting: "firelight", objects: "masks, rattles, coppers", music: "winter dance songs", scent: "cedar bark, smoke, sea" },
    snd: ["box drum", "hawk whistles"],
    dna: { mi: 40, og: 80, wc: 20, ns: 5, ad: 5, hf: 15, rr: 30, ps: 30, sh: 45, ql: 45, oc: 25, ds: 65, rs: 30, eu: 65, np: 30 },
    emo: { warm: 60, cold: 30, playful: 20, serious: 80, chaotic: 35, ordered: 70, nostalgic: 55, futuristic: 10, peaceful: 25, ominous: 50 },
  },
  {
    n: "Bonampak murals", a: ["Bonampak paintings", "Temple of the Murals", "Structure 1 fresco cycle"],
    cat: "Painting Technique & School", c: "Maya mural painting", e: "historical", o: "Bonampak, Chiapas, Mexico", g: "Maya lowlands",
    p: "c. AD 790", era: "Late Classic Maya",
    sum: "Three rooms of 8th-century fresco — royal presentation, war and torture, and a triumph dance in full color.",
    desc: "Bonampak's Structure 1 preserves the most complete Maya mural cycle known: three vaulted rooms painted around AD 790 under lord Chan Muwan, chronicling his court — the presentation of an heir among elaborately robed nobles; the storming of a village, captives bleeding before the throne; and a final dance in feathered regalia with musicians and masked performers. Painters on lime stucco handled wet and dry pigment in mineral reds, blues (Maya blue), yellows and blacks with astonishing life — eyebrows, teeth, textiles, glyphs naming every figure. Lost to jungle and found in 1946 (guided by Lacandon Maya), the murals exploded the 'peaceful Maya' myth, showing courtly politics and violence in HD. INAH's reproductions and digital scans keep the fragile originals sheltered. The look: deep-walled fresco theater, oxblood and teal, glyph-tagged drama.",
    col: [{ h: "#9e2b25", n: "fresco red" }, { h: "#2b6a8a", n: "Maya blue" }, { h: "#d4a017", n: "ochre gold" }, { h: "#1a1a1a", n: "outline black" }, { h: "#e8dcc0", n: "lime ground" }],
    m: ["lime stucco", "mineral pigments", "Maya blue (indigo-palygorskite)", "brush and quill"],
    tx: ["polished stucco ground", "wet-outline strokes", "salt-freted surface", "lampblack depth"],
    obj: ["presentation-of-heir scene", "battle and captive panels", "triumph dance frieze", "glyph captions", "musicians and masked dancers"],
    ex: ["Room 2 captive torture scene", "Room 1 heir presentation", "INAH full-scale reproduction"],
    inf: ["Maya court ceremonial cycle", "regional Maya wall-painting workshops"], rel: ["Maya codices", "Mixtec codices", "Ethiopian church murals"],
    par: "Maya painting tradition", var: ["three-room narrative cycle", "glyph-tagged portraiture"], cf: ["Teotihuacan murals", "Maya codices"],
    src: [{ n: "Wikipedia — Bonampak", u: "https://en.wikipedia.org/wiki/Bonampak", t: "B" }, { n: "Instituto Nacional de Antropología e Historia", u: "https://www.inah.gob.mx", t: "A" }],
    tg: ["maya", "mural", "fresco", "bonampak", "classic"], pop: 32, niche: false,
    vd: { shape: "procession-stacked figures", line: "calligraphic contour", composition: "register bands up vaulted walls", texture: "stucco grain", forms: "nobles, captives, musicians, glyphs" },
    typ: { display: "humanist serif", body: "humanist sans", notes: "archaeology label" },
    fnt: { display: "Cinzel", body: "Inter", notes: "lapidary caps echo glyph panels" },
    lit: { quality: "torch-warm chamber", direction: "low side raking", temperature: "warm", shadow: "vault shade" },
    pho: { approach: "segment scans, raking-light texture", grade: "warm, high detail" },
    fash: { silhouettes: "wrapped loincloths, capes", garments: "jaguar pelts, feathered capes", acc: "jade earspools, shell plaques" },
    env: { places: "jungle temples, Usumacinta valley", weather: "green canopy heat" },
    gd: { layout: "register-band scroll", icon: "glyph cartouche" },
    ui: { background: "lime cream", surface: "fresco-texture cards", components: "glyph buttons", motion: "panel pan" },
    rec: { materials: "stucco textures, reproductions", lighting: "torch-warm", objects: "casts, drawings, codex facsimiles", music: "Maya drum and conch", scent: "limestone, wet jungle" },
    snd: ["conch horn", "jungle cicadas"],
    dna: { mi: 40, og: 65, wc: 20, ns: 5, ad: 5, hf: 5, rr: 35, ps: 35, sh: 35, ql: 35, oc: 25, ds: 70, rs: 30, eu: 75, np: 30 },
    emo: { warm: 65, cold: 30, playful: 25, serious: 80, chaotic: 40, ordered: 70, nostalgic: 55, futuristic: 10, peaceful: 30, ominous: 45 },
  },
  {
    n: "Maya codices", a: ["Dresden Codex", "screenfold books", "Madrid and Paris codices"],
    cat: "Religious & Sacred Art", c: "screenfold almanacs", e: "historical", o: "Maya lowlands (Yucatán, Petén)", g: "Maya region; Dresden, Madrid, Paris libraries",
    p: "extant books c. AD 1200-1500", era: "Postclassic",
    sum: "Four surviving bark-paper screenfolds — Venus tables, rain almanacs and gods painted in red-black calligraphy.",
    desc: "Maya scribes (aj tz'ib) folded lime-coated bark paper (huun) into accordion screenfolds, painting gods, rituals and astronomical tables with reed brushes in a red-black outline style dense with glyphs. The Dresden Codex's Venus tables and eclipse almanacs track the morning star to uncanny accuracy; the Madrid Book is a household-ritual compendium; Paris holds the katun-prophecy pages; the Grolier — re-authenticated as the Maya Codex of Mexico in 2018 — is the oldest known book in the Americas. Bishop Diego de Landa's 1562 burning of 'books of the devil' left only these four, making them the last voices of a vast scribal culture; their figures and color scheme still define Maya visual identity. The look: red-cased gods in black ink, columned almanacs, numerical dots and bars.",
    col: [{ h: "#b03a2e", n: "scribe red" }, { h: "#1c1c1c", n: "ink black" }, { h: "#e8dcc0", n: "lime paper" }, { h: "#c88f3c", n: "wash ochre" }, { h: "#2b6a8a", n: "accidental blue" }],
    m: ["lime-coated bark paper", "mineral red", "carbon black", "reed brush"],
    tx: ["smooth gessoed fold", "fine brush line", "fold-crease shadow", "red wash pools"],
    obj: ["Venus tables", "eclipse almanacs", "god portraits", "day-sign columns", "numerical bars and dots"],
    ex: ["Dresden Codex Venus pages", "Madrid Codex beekeeping almanacs", "Maya Codex of Mexico (Grolier)"],
    inf: ["Postclassic scribal workshops", "Mesoamerican screenfold technology"], rel: ["Mixtec codices", "Bonampak murals", "Tibetan sand mandala"],
    par: "Maya scribal tradition", var: ["Dresden", "Madrid", "Paris", "Maya Codex of Mexico"], cf: ["Mixtec codices", "Aztec codices"],
    src: [{ n: "Wikipedia — Maya codices", u: "https://en.wikipedia.org/wiki/Maya_codices", t: "B" }, { n: "The Metropolitan Museum of Art", u: "https://www.metmuseum.org", t: "A" }],
    tg: ["codex", "maya", "screenfold", "astronomy", "glyphs"], pop: 34, niche: false,
    vd: { shape: "columned almanac grids", line: "red-outlined black figures", composition: "frame-within-frame pages", texture: "lime paper", forms: "gods, demons, serpents, day signs" },
    typ: { display: "humanist serif", body: "humanist sans", notes: "facsimile edition" },
    fnt: { display: "EB Garamond", body: "Inter", notes: "book-historical serif" },
    lit: { quality: "library even", direction: "frontal flat", temperature: "warm", shadow: "fold valleys" },
    pho: { approach: "page-by-page facsimile photography", grade: "neutral archival" },
    fash: { silhouettes: "woven wrap, cotton tunic", garments: "painted priestly dress", acc: "jade earspools, shell inkpots" },
    env: { places: "temple scriptoria, monastic libraries", weather: "still dry-season air" },
    gd: { layout: "accordion page spread", icon: "day-sign cartouche" },
    ui: { background: "lime paper", surface: "almanac cards", components: "column toggles", motion: "fold flip" },
    rec: { materials: "facsimile books, brushes", lighting: "even library", objects: "codices, ink pots, obsidian blades", music: "conch and turtle drum", scent: "bark paper, copal" },
    snd: ["page fold", "low chant"],
    dna: { mi: 50, og: 60, wc: 15, ns: 5, ad: 5, hf: 10, rr: 25, ps: 35, sh: 25, ql: 15, oc: 15, ds: 65, rs: 20, eu: 75, np: 30 },
    emo: { warm: 55, cold: 40, playful: 30, serious: 80, chaotic: 20, ordered: 85, nostalgic: 65, futuristic: 15, peaceful: 45, ominous: 30 },
  },
  {
    n: "Mixtec codices", a: ["Codex Zouche-Nuttall", "Codex Vindobonensis", "Mixteca-Puebla painting"],
    cat: "Painting Technique & School", c: "screenfold history painting", e: "historical", o: "Ñuu Dzaui (Mixtec), Oaxaca-Puebla", g: "Oaxaca; European museum libraries",
    p: "14th-16th c", era: "Postclassic-Early Colonial",
    sum: "Deer-hide screenfolds painting genealogies and conquests — Eight Deer Jaguar Claw's world in red-line graphics.",
    desc: "Mixtec painted histories record eight centuries of Ñuu Dzaui royalty: genealogies, marriages and wars of rulers like Eight Deer Jaguar Claw (Codex Zouche-Nuttall), creation at Apoala (Vindobonensis), and tribute lands (Colombino). Deerskin screenfolds, gessoed to a hard white ground, carry flat figures drawn in fine red outlines with black and color fills; people are named by day-sign and numeral glyphs so each noble is a walking date. The crisp 'Mixteca-Puebla' style became the international idiom of late Postclassic Mesoamerica, shaping Aztec imperial art, and its linearity fascinates modern designers. Held at the British Museum, Vienna and Mexico's national library, the books are read today in Mixtec communities' revived literacy projects. The look: banded place-glyphs, profile nobles, red-line precision on warm hide.",
    col: [{ h: "#b03a2e", n: "outline red" }, { h: "#d9a441", n: "hide gold" }, { h: "#1c1c1c", n: "line black" }, { h: "#2e6f6a", n: "turquoise green" }, { h: "#f2ead9", n: "gesso white" }],
    m: ["deer hide", "gesso ground", "mineral pigments", "fine brush"],
    tx: ["polished hide sheen", "red-line hatching", "lacquer-like surface", "pigment set-off rub"],
    obj: ["day-sign name glyphs", "place-glyph scrolls", "ruler portraits", "marriage scenes", "year bundles"],
    ex: ["Codex Zouche-Nuttall (British Museum)", "Codex Vindobonensis (Vienna)", "Eight Deer biography pages"],
    inf: ["Mixteca-Puebla international style", "Borgia-group manuscript workshops"], rel: ["Maya codices", "Aztec turquoise mosaic", "Bonampak murals"],
    par: "Ñuu Dzaui scribal tradition", var: ["historical-genealogical books", "tribute registers", "ritual books"], cf: ["Maya codices", "Aztec codices"],
    src: [{ n: "Wikipedia — Codex Zouche-Nuttall", u: "https://en.wikipedia.org/wiki/Codex_Zouche-Nuttall", t: "B" }, { n: "The British Museum", u: "https://www.britishmuseum.org", t: "A" }],
    tg: ["mixtec", "codex", "genealogy", "screenfold", "oaxaca"], pop: 26, niche: true,
    vd: { shape: "banded page registers", line: "fine red contour", composition: "glyph-driven sequences", texture: "hide gloss", forms: "nobles, place glyphs, day signs" },
    typ: { display: "humanist serif", body: "humanist sans", notes: "facsimile commentary" },
    fnt: { display: "Sorts Mill Goudy", body: "Inter", notes: "historical serif, quiet body" },
    lit: { quality: "case even", direction: "flat frontal", temperature: "warm", shadow: "minimal" },
    pho: { approach: "full-page facsimile and macro detail", grade: "warm neutral" },
    fash: { silhouettes: "knotted capes, loincloth wrap", garments: "cotton mantles", acc: "turquoise, gold discs" },
    env: { places: "hilltop palaces, cloud forest", weather: "Oaxaca dry shimmer" },
    gd: { layout: "register band with glyph headers", icon: "day-sign medallion" },
    ui: { background: "hide tan", surface: "red-line cards", components: "glyph buttons", motion: "band scroll" },
    rec: { materials: "facsimiles, hide panels", lighting: "even", objects: "codices, jade, gold", music: "conch and huehuetl", scent: "hide, copal" },
    snd: ["conch shell", "rattle cadence"],
    dna: { mi: 45, og: 55, wc: 20, ns: 5, ad: 5, hf: 10, rr: 25, ps: 35, sh: 25, ql: 20, oc: 15, ds: 70, rs: 20, eu: 75, np: 30 },
    emo: { warm: 60, cold: 35, playful: 30, serious: 75, chaotic: 20, ordered: 85, nostalgic: 65, futuristic: 10, peaceful: 45, ominous: 30 },
  },
  {
    n: "Aztec turquoise mosaic", a: ["Mexica turquoise mosaic", "Xiuhtecuhtli masks", "double-headed serpent mosaic"],
    cat: "Material & Surface", c: "ceremonial stone mosaic", e: "historical", o: "Mexica (Aztec) empire, Central Mexico", g: "Central Mexico; European museums",
    p: "15th-16th c", era: "Late Postclassic",
    sum: "Faces of gods in thousands of turquoise tesserae — serpent bodies, skull eyes, resin-set precision.",
    desc: "Mexica artists set thousands of hand-cut turquoise tesserae over carved cedar faces and figures, following every curve with resin adhesive so a god's face ripples with mineral blue-green light. Masterpieces carried to Europe in the 1520s and now icon-class: the Double-headed Serpent, the turquoise Mask of Xiuhtecuhtli (god of fire and year) and Tezcatlipoca's skull-face mask, mostly in the British Museum. Tesserae came from trade routes reaching far north of the empire; shells, pyrite and mother-of-pearl flash accents; red Spondylus-shell eyes bite from some masks. Fewer than a dozen mosaics survive — sacrificial and diplomatic regalia burned or melted in conquest — making each an unmatched window into Mexica taste. The look: dense blue-green shingle, polished stone glow, eerie symmetry.",
    col: [{ h: "#2a9d8f", n: "turquoise" }, { h: "#1f7a6d", n: "deep teal" }, { h: "#c0392b", n: "spondylus red" }, { h: "#e8e3d3", n: "shell white" }, { h: "#3d3a30", n: "cedar dark" }],
    m: ["turquoise tesserae", "carved cedar wood", "pine resin adhesive", "shell and pyrite accents"],
    tx: ["stone shingle mosaic", "polished mineral gloss", "carved under-form", "resin amber glints"],
    obj: ["god masks", "double-headed serpent", "mosaic shields", "ceremonial knives", "skull masks"],
    ex: ["Double-headed Serpent (British Museum)", "Mask of Xiuhtecuhtli", "Tezcatlipoca skull mask"],
    inf: ["Mesoamerican turquoise exchange", "amanteca featherworker precision culture"], rel: ["Mixtec codices", "Smalti glass mosaic", "Aztec Tenochtitlan Style"],
    par: "Mexica lapidary tradition", var: ["god masks", "serpent pectorals", "shields"], cf: ["Greek mosaic work", "Huichol yarn painting"],
    src: [{ n: "Wikipedia — Double-headed serpent", u: "https://en.wikipedia.org/wiki/Double-headed_serpent", t: "B" }, { n: "The British Museum", u: "https://www.britishmuseum.org", t: "A" }],
    tg: ["turquoise", "mosaic", "aztec", "mexica", "mask"], pop: 30, niche: false,
    vd: { shape: "symmetric god fronts", line: "tessera courses follow form", composition: "centered mask symmetry", texture: "stone shingle", forms: "serpents, skulls, fire gods" },
    typ: { display: "humanist serif", body: "humanist sans", notes: "museum label" },
    fnt: { display: "Bodoni Moda", body: "Inter", notes: "high-contrast display for jewel tones" },
    lit: { quality: "case spot", direction: "frontal", temperature: "cool", shadow: "tessera relief" },
    pho: { approach: "macro mosaic raking, frontal mask portrait", grade: "cool, high clarity" },
    fash: { silhouettes: "regalia-fronted body", garments: "feathered cloaks", acc: "turquoise masks, shell pendants" },
    env: { places: "templo precincts, museum vitrines", weather: "valley-of-Mexico haze" },
    gd: { layout: "centered symmetric emblem", icon: "serpent double-head" },
    ui: { background: "obsidian black", surface: "turquoise-shingle cards", components: "tile buttons", motion: "tessera shimmer" },
    rec: { materials: "mosaic casts, velvet cases", lighting: "cool spot", objects: "masks, serpents, shells", music: "huehuetl and conch", scent: "cedar, resin" },
    snd: ["conch horn", "rattle hiss"],
    dna: { mi: 50, og: 45, wc: 10, ns: 5, ad: 5, hf: 10, rr: 20, ps: 30, sh: 40, ql: 30, oc: 15, ds: 75, rs: 15, eu: 70, np: 30 },
    emo: { warm: 45, cold: 55, playful: 25, serious: 80, chaotic: 15, ordered: 85, nostalgic: 60, futuristic: 15, peaceful: 35, ominous: 50 },
  },
  {
    n: "Purépecha copperwork", a: ["Tarascan metalwork", "Purépecha coppersmithing", "Michoacán copper"],
    cat: "Material & Surface", c: "indigenous copper metallurgy", e: "regional_tradition", o: "Purépecha Empire, Michoacán", g: "Michoacán, Mexico",
    p: "c. 1200-1521 to present", era: "Postclassic to living craft",
    sum: "Mesoamerica's only true copper state — smelted axes and bells, now hammered vases of Santa Clara del Cobre.",
    desc: "The Purépecha (Tarascan) Empire was Mesoamerica's metallurgical exception: the only state that smelted and cast copper on an industrial scale, producing cold-hammered axes, needles, awls and cast tinkler bells from ore roasted in open furnaces. Copper tools and bells were tribute, war material and ritual sound; the Relación de Michoacán documents the craft's status. After conquest the skill survived — Santa Clara del Cobre's smiths retooled for colonial trade and today hammer world-famous vases and single-piece cauldrons, some over a meter wide, from reclaimed copper, a tradition crowned each year at the Feria del Cobre, where master smiths compete to raise single-piece vases. The look: fire-crimson copper settling into deep warm patina, hammer-bloomed surfaces.",
    col: [{ h: "#b87333", n: "hammered copper" }, { h: "#8a4b24", n: "heat red" }, { h: "#6e4a2e", n: "patina brown" }, { h: "#5d7d6b", n: "lake patina green" }, { h: "#e8dcc0", n: "ash white" }],
    m: ["copper ore", "charcoal furnaces", "hammer and anvil", "reclaimed copper sheet"],
    tx: ["hammer bloom facets", "fire scale", "soft burnish", "high-sheen planishing"],
    obj: ["axe blades", "tinkler bells", "single-piece cauldrons", "hammered vases", "copper vessels"],
    ex: ["Santa Clara del Cobre smithies", "Feria del Cobre prize vases", "Relación de Michoacán copper tribute lists"],
    inf: ["Postclassic long-distance ore trade", "colonial-era market retooling"], rel: ["Aztec turquoise mosaic", "Tuareg silver and leatherwork", "Granulation (goldsmithing)"],
    par: "", var: ["Prehispanic cast bells", "colonial-era implements", "art-hammered vases"], cf: ["Damascening (metal inlay)"],
    src: [{ n: "Wikipedia — Purépecha", u: "https://en.wikipedia.org/wiki/Pur%C3%A9pecha", t: "B" }, { n: "Wikipedia — Tarascan state", u: "https://en.wikipedia.org/wiki/Tarascan_state", t: "B" }, { n: "Smithsonian Institution", u: "https://www.si.edu", t: "A" }],
    tg: ["copper", "purepecha", "michoacan", "metallurgy", "smithing"], pop: 20, niche: true,
    vd: { shape: "swelling vessel curves", line: "faceted hammer paths", composition: "single-piece forming", texture: "hammer bloom", forms: "vases, cauldrons, bells" },
    typ: { display: "humanist serif", body: "humanist sans", notes: "craft fair placard" },
    fnt: { display: "Alegreya", body: "Inter", notes: "warm literary serif" },
    lit: { quality: "forge glow", direction: "underside warm bounce", temperature: "hot-warm", shadow: "hammer facets" },
    pho: { approach: "sparks-and-hammer action shots, vessel portraits", grade: "warm high contrast" },
    fash: { silhouettes: "apron-and-sleeve workwear", garments: "linen work shirts", acc: "copper jewelry, apron tools" },
    env: { places: "Pátzcuaro lake towns, forge yards", weather: "highland pine cool" },
    gd: { layout: "centered vessel portrait", icon: "bell and axe motif" },
    ui: { background: "charred wood", surface: "copper-sheen cards", components: "rivet buttons", motion: "hammer strike" },
    rec: { materials: "copper vessels, soot-black rafters", lighting: "forge warm", objects: "vases, cauldrons, ore", music: "pirekua song", scent: "charcoal, hot metal" },
    snd: ["hammer on copper", "forge roar"],
    dna: { mi: 55, og: 55, wc: 10, ns: 10, ad: 10, hf: 15, rr: 35, ps: 35, sh: 45, ql: 35, oc: 20, ds: 45, rs: 25, eu: 75, np: 30 },
    emo: { warm: 75, cold: 20, playful: 30, serious: 65, chaotic: 25, ordered: 75, nostalgic: 70, futuristic: 15, peaceful: 45, ominous: 20 },
  },
  {
    n: "Danza de los Voladores", a: ["Voladores de Papantla", "pole-flying ritual", "volador ceremony"],
    cat: "Regional & Cultural Tradition", c: "aerial ritual performance", e: "regional_tradition", o: "Totonac people, Papantla, Veracruz", g: "Veracruz and across Mexico",
    p: "pre-Hispanic origin to present", era: "living tradition (UNESCO 2009)",
    sum: "Four flyers descend spinning from a 30-meter pole while a caporal plays flute and drum above — 52 revolutions of prayer.",
    desc: "Five Totonac men climb a lashed 30-meter pole: atop, the caporal stands playing reed flute and small drum without tether, while the four voladores bind ropes around the pole and launch into the void, spinning down in widening circles — thirteen turns each, four flyers, fifty-two revolutions for the calendar round. The rite petitions for rain and fertility, remembered in Totonac myth as an answer to drought, and was historically performed from trees. UNESCO inscribed the Ritual Ceremony of the Voladores in 2009; beside authentic Papantla performances, tourist versions (Xochimilco, airports) raise heritage-and-commodification debates. Painted flyers in red-and-white suits and ribboned headdresses climb in solemn order. The look: red-and-white figures spiraling against sky, drum-flute circling overhead.",
    col: [{ h: "#c0392b", n: "flyer red" }, { h: "#f2ead9", n: "suit white" }, { h: "#8b5a2b", n: "pole wood" }, { h: "#d4a017", n: "ribbon gold" }, { h: "#2d6a4f", n: "verde ribbon" }],
    m: ["straight pine pole", "hemp rope", "reed flute", "small drum"],
    tx: ["lashed pole texture", "rope-wrapped column", "silk ribbon flutter", "body-rope friction sheen"],
    obj: ["thirty-meter pole", "caporal's flute-drum", "rope loops", "ribboned headdresses", "ceremonial flyers' suits"],
    ex: ["Voladores of Papantla, Veracruz", "UNESCO 2009 inscription performances", "Xochimilco and tourist-pole adaptations"],
    inf: ["Totonac rain-fertility cosmology", "post-conquest plaza adaptation"], rel: ["Papel picado", "Día de Muertos ofrenda culture", "Tibetan sand mandala"],
    par: "", var: ["Papantla Totonac rite", "Nahua variants (Puebla)", "tourist adaptations"], cf: ["circus pole acts"],
    src: [{ n: "Wikipedia — Danza de los Voladores", u: "https://en.wikipedia.org/wiki/Danza_de_los_Voladores", t: "B" }, { n: "UNESCO Intangible Cultural Heritage", u: "https://ich.unesco.org", t: "A" }],
    tg: ["voladores", "totonac", "ritual", "veracruz", "unesco"], pop: 38, niche: false,
    vd: { shape: "descending spiral cone", line: "rope helix", composition: "pole-centered radial choreography", texture: "rope and bark", forms: "four flyers, caporal, sun burst" },
    typ: { display: "humanist serif", body: "humanist sans", notes: "heritage placard" },
    fnt: { display: "Playfair Display", body: "Inter", notes: "festival-poster serif" },
    lit: { quality: "tropical noon", direction: "overhead sun", temperature: "hot", shadow: "long pole shadow sweep" },
    pho: { approach: "verticals and slow-shutter spirals", grade: "saturated warm" },
    fash: { silhouettes: "banded tunic and trousers", garments: "embroidered flyer suits", acc: "ribboned headdress, sash" },
    env: { places: "town plazas, Papantla square", weather: "humid gulf heat" },
    gd: { layout: "radial drop-away graphic", icon: "spiral rope" },
    ui: { background: "sky wash", surface: "pole-vertical cards", components: "ribbon buttons", motion: "spiral descend" },
    rec: { materials: "pole, ropes, ribbons", lighting: "noon overhead", objects: "pole, flute, drum", music: "flute and tiny drum loop", scent: "wood, rope, vanilla fields" },
    snd: ["reed flute", "small drum pulse"],
    dna: { mi: 40, og: 65, wc: 20, ns: 5, ad: 5, hf: 20, rr: 30, ps: 40, sh: 35, ql: 40, oc: 25, ds: 35, rs: 35, eu: 65, np: 30 },
    emo: { warm: 70, cold: 25, playful: 40, serious: 65, chaotic: 25, ordered: 75, nostalgic: 65, futuristic: 15, peaceful: 50, ominous: 35 },
  },
  {
    n: "Nazca lines", a: ["Nasca lines", "Nazca geoglyphs", "Líneas de Nazca"],
    cat: "Regional & Cultural Tradition", c: "desert geoglyphs", e: "historical", o: "Nazca culture, south coast Peru", g: "Nazca-Palpa desert, Peru",
    p: "c. 500 BC - AD 500", era: "Early Intermediate",
    sum: "Hummingbirds, monkeys and spiders scraped into desert pavement — hundreds of figures readable only from the air.",
    desc: "Across the Peruvian pampa, Nazca makers removed dark iron-oxide pebbles to expose pale ground beneath, drawing hundreds of geoglyphs: the hummingbird's long beak, spiral-tailed monkey, spider, condor, whale and tree, plus thousands of straight lines and trapezoids marching to the horizon. Surveying was done with stakes and cords by coordinated crews; the dry, windless desert preserved them for two millennia. Purposes argued — water rituals tied to aquifer-fed springs, pilgrimage processions along the lines, offering images to mountain and sky deities — remain debated, with drone surveys still finding new figures (the 2019-2020 'cat' and AI-found hillside glyphs). Maria Reiche's fifty-year guardianship and UNESCO listing (1994) fixed their fame; flights over the pampa are now the classic viewing rite. The look: single-stroke animal calligraphy on rust-red earth.",
    col: [{ h: "#b06a3b", n: "desert rust" }, { h: "#d8c39a", n: "paved pale ground" }, { h: "#8a4a2b", n: "oxidized stone" }, { h: "#c99e6a", n: "dust gold" }, { h: "#5f7d8c", n: "sky over pampa" }],
    m: ["desert pavement", "removed dark pebbles", "survey stakes and cords", "pale subsoil"],
    tx: ["pebble-strewn grain", "scraped pale troughs", "wind micro-ridges", "iron-oxide dust bloom"],
    obj: ["hummingbird", "spider", "monkey", "condor", "trapezoid lines"],
    ex: ["Hummingbird figure overflights", "Maria Reiche's observation tower", "2020 drone-found cat geoglyph"],
    inf: ["Paracas-era geoglyph precursors", "Andean desert ritual walking"], rel: ["Paracas textiles", "Chan Chan adobe reliefs", "Land Art"],
    par: "", var: ["biomorph figures", "line networks", "Palpa hillside reliefs"], cf: ["Land Art", "crop circles"],
    src: [{ n: "Wikipedia — Nazca Lines", u: "https://en.wikipedia.org/wiki/Nazca_Lines", t: "B" }, { n: "UNESCO World Heritage Centre", u: "https://whc.unesco.org/en/list/700", t: "A" }],
    tg: ["geoglyph", "nazca", "peru", "desert", "aerial"], pop: 55, niche: false,
    vd: { shape: "single-contour animal glyphs", line: "one continuous edge", composition: "huge scale, aerial legibility", texture: "pebble pavement", forms: "birds, monkey, spider, trapezoids" },
    typ: { display: "geometric sans", body: "humanist sans", notes: "archaeology placard" },
    fnt: { display: "Space Grotesk", body: "Work Sans", notes: "clean survey-document pairing" },
    lit: { quality: "altiplano glare", direction: "overhead", temperature: "hot", shadow: "pebble micro-shadow" },
    pho: { approach: "aerial and oblique morning flights", grade: "high clarity, warm dust" },
    fash: { silhouettes: "wrapped poncho", garments: "embroidered tunics", acc: "feather mantles" },
    env: { places: "pampa miradores, desert aquifer springs", weather: "cloudless, windless" },
    gd: { layout: "single-line emblem on field", icon: "hummingbird contour" },
    ui: { background: "desert rust", surface: "line-trace cards", components: "outline buttons", motion: "path draw" },
    rec: { materials: "aerial charts, pebbles", lighting: "harsh clear", objects: "maps, drone footage, models", music: "Andean panpipes", scent: "dry dust, creosote" },
    snd: ["desert wind", "distant propeller"],
    dna: { mi: 80, og: 60, wc: 20, ns: 5, ad: 10, hf: 15, rr: 30, ps: 35, sh: 35, ql: 25, oc: 15, ds: 25, rs: 30, eu: 85, np: 30 },
    emo: { warm: 60, cold: 30, playful: 30, serious: 70, chaotic: 15, ordered: 80, nostalgic: 55, futuristic: 30, peaceful: 60, ominous: 30 },
  },
  {
    n: "Moche portrait vessels", a: ["Moche huacos retrato", "portrait head jars", "stirrup-spout portrait bottles"],
    cat: "Textile & Craft", c: "portrait ceramic sculpture", e: "historical", o: "Moche culture, north coast Peru", g: "Moche and Chicama valleys, Peru",
    p: "AD 100-800", era: "Moche IV-V flowering",
    sum: "Stirrup-spout bottles modeling individual faces — age, scar and sneer captured in fired clay.",
    desc: "Moche potters made the pre-Columbian Americas' great gallery of faces: stirrup-spout bottles whose chambers are modeled and painted portraits — old men with furrowed cheeks, warriors with face paint, scarred veterans and composed dignitaries — some individualized enough to suggest specific named lords. Built from coils and molds then reworked by hand, painted in cream-and-red slips, they likely portrayed elite individuals for court and burial; royal tombs like the Lord of Sipán confirm the portrait world's real-world cast. Rafael Larco Hoyle amassed thousands of 'huacos retrato,' now the core of the Larco Museum in Lima; the finer examples rival any ancient portrait tradition in psychological presence. The look: calm burnished faces under loop-and-spout handles, red-on-cream reserve painting.",
    col: [{ h: "#c65d3b", n: "slip red" }, { h: "#e8dcc0", n: "cream ground" }, { h: "#7a4a2f", n: "fired brown" }, { h: "#1c1c1c", n: "painted black" }, { h: "#a98a5b", n: "burnish tan" }],
    m: ["fine clay", "red and cream slips", "molds and hand modeling", "burnishing stone"],
    tx: ["burnished surface", "mold seam traces", "painted reserve fields", "fine incised detail"],
    obj: ["portrait head jars", "stirrup spouts", "warrior figures", "narrative roll-out scenes", "mythic and erotic vessels"],
    ex: ["Larco Museum portrait vessel galleries", "Lord of Sipán tomb context", "Moche V decline-phase vessels"],
    inf: ["Cupisnique stirrup-spout tradition", "Moche state iconography"], rel: ["Paracas textiles", "Nazca lines", "Marajoara ceramics"],
    par: "North-coast ceramic tradition", var: ["portrait vessels", "narrative vessels", "late abstract phase"], cf: ["Greek portrait busts", "Mata Ortiz pottery"],
    src: [{ n: "Wikipedia — Moche culture", u: "https://en.wikipedia.org/wiki/Moche_culture", t: "B" }, { n: "Museo Larco", u: "https://www.museolarco.org", t: "A" }],
    tg: ["moche", "portrait", "ceramics", "peru", "stirrup spout"], pop: 40, niche: false,
    vd: { shape: "head-jar volume with spout loop", line: "painted slip contours", composition: "face-centered sculptural front", texture: "burnished slip", forms: "elders, warriors, lords" },
    typ: { display: "humanist serif", body: "humanist sans", notes: "museum label" },
    fnt: { display: "Newsreader", body: "Inter", notes: "portrait-plate serif" },
    lit: { quality: "case spot", direction: "three-quarter", temperature: "warm", shadow: "sculptural relief" },
    pho: { approach: "museum portraiture of objects, three-quarter light", grade: "warm archival" },
    fash: { silhouettes: "loincloth and earplug regalia", garments: "woven tunics", acc: "earspools, headcloth" },
    env: { places: "adobe platforms, valley museums", weather: "coastal desert haze" },
    gd: { layout: "vessel-centered plate", icon: "stirrup-spout silhouette" },
    ui: { background: "cream slip", surface: "vessel cards", components: "loop buttons", motion: "spout arc" },
    rec: { materials: "ceramic casts, tan walls", lighting: "warm spot", objects: "vessels, textiles, gold", music: "Andean antara flutes", scent: "clay, dust" },
    snd: ["clay tap", "desert wind"],
    dna: { mi: 55, og: 70, wc: 20, ns: 5, ad: 5, hf: 10, rr: 25, ps: 35, sh: 40, ql: 25, oc: 20, ds: 50, rs: 25, eu: 75, np: 30 },
    emo: { warm: 65, cold: 30, playful: 30, serious: 70, chaotic: 15, ordered: 80, nostalgic: 65, futuristic: 10, peaceful: 50, ominous: 30 },
  },
  {
    n: "Paracas textiles", a: ["Paracas mantles", "Necropolis embroidery", "Paracas burial cloths"],
    cat: "Textile & Craft", c: "embroidered burial textiles", e: "historical", o: "Paracas culture, Ica, Peru", g: "Paracas Peninsula, Peru",
    p: "c. 500-200 BC", era: "Early Horizon (Necropolis phase)",
    sum: "Mantles embroidered with flying shamans and severed heads — up to 190 yarn colors in desert burial bundles.",
    desc: "In the Paracas Necropolis's mummy bundles, Julio C. Tello's 1927 excavation found textiles of impossible richness: wool-on-cotton mantles whose borders swarm with embroidered 'Oculate Beings' — masked flying shamans, felines and condors clutching severed heads, each figure a variant on the last. Spinners and embroiderers, almost certainly women specialists, worked dyed camelid yarn in a chromatic range often tallied near 190 shades, from shrimp pink to deep indigo, using stem-stitch at near-microscopic density. The garments layered over elite dead across generations before final burial, making cemeteries archives of color. Conserved in Lima (MNAAHP) and Gothenburg — whose collection's 2014 repatriation controversy made headlines — Paracas embroidery anchors Andean textile history. The look: polychrome flying figures, border-to-border, glowing against desert dust.",
    col: [{ h: "#c94f7c", n: "shrimp pink" }, { h: "#2b5f8a", n: "yarn indigo" }, { h: "#d4a017", n: "saffron yarn" }, { h: "#7a3b5e", n: "plum dye" }, { h: "#e8dcc0", n: "cotton ground" }],
    m: ["camelid wool yarn", "cotton ground cloth", "cochineal and plant dyes", "embroidery needle"],
    tx: ["dense stem stitch", "yarn pile halo", "plainweave ground", "fringed mantle edges"],
    obj: ["Oculate Being figures", "severed-head trophies", "border mantle bands", "flying shaman lineups", "mummy bundle wraps"],
    ex: ["Necropolis mantles (MNAAHP Lima)", "Paracas Textile (Brooklyn Museum)", "Gothenburg repatriated bundles"],
    inf: ["Chavín iconographic base", "camelid-herding wool economy"], rel: ["Nazca lines", "Moche portrait vessels", "Fon appliqué"],
    par: "", var: ["block-color mantles", "linear-embroidery cloths", "Necropolis vs Cavernas phases"], cf: ["Nazca textiles", "fon appliqué"],
    src: [{ n: "Wikipedia — Paracas culture", u: "https://en.wikipedia.org/wiki/Paracas_culture", t: "B" }, { n: "Google Arts & Culture", u: "https://artsandculture.google.com", t: "A" }],
    tg: ["paracas", "textile", "embroidery", "peru", "mantle"], pop: 36, niche: false,
    vd: { shape: "border-swarm figure rows", line: "outline-stitch contour", composition: "central field plus narrative borders", texture: "yarn pile", forms: "flying shamans, felines, heads" },
    typ: { display: "humanist serif", body: "humanist sans", notes: "exhibit label" },
    fnt: { display: "Vollkorn", body: "Inter", notes: "textile-warm serif" },
    lit: { quality: "conservation even", direction: "flat frontal", temperature: "warm", shadow: "embroidery relief" },
    pho: { approach: "conservation flat-lay, border macros", grade: "neutral, high fidelity" },
    fash: { silhouettes: "mantle drape over shoulder", garments: "embroidered mantles, tunics", acc: "feather fans, gold ornaments" },
    env: { places: "desert necropolis, conservation labs", weather: "rainless coast fog" },
    gd: { layout: "border-ruled spread", icon: "Oculate Being" },
    ui: { background: "cotton cream", surface: "embroidery-texture cards", components: "border buttons", motion: "figure procession" },
    rec: { materials: "textile fragments, color chips", lighting: "even museum", objects: "mantles, dye pots, spindles", music: "Andean quena flute", scent: "camelid wool, desert salt" },
    snd: ["spindle whir", "quena breath"],
    dna: { mi: 40, og: 70, wc: 20, ns: 5, ad: 5, hf: 5, rr: 25, ps: 40, sh: 30, ql: 25, oc: 20, ds: 80, rs: 30, eu: 70, np: 35 },
    emo: { warm: 65, cold: 30, playful: 35, serious: 70, chaotic: 25, ordered: 80, nostalgic: 70, futuristic: 10, peaceful: 45, ominous: 35 },
  },
  {
    n: "Chan Chan adobe reliefs", a: ["Chimú adobe friezes", "Ciudad de Chan Chan", "Chimor capital walls"],
    cat: "Architectural Style", c: "adobe relief architecture", e: "historical", o: "Chimú Empire (Chimor), Trujillo", g: "North coast Peru",
    p: "c. AD 900-1470", era: "Late Intermediate",
    sum: "The world's largest mud-brick city — kilometre walls carved with fishnets, birds and otter processions.",
    desc: "Chan Chan, capital of Chimor and the largest adobe city on earth (some 20 km²), is architecture-as-frieze: ten royal ciudadelas enclosed by nine-meter walls whose interior corridors carry continuous low-relief carving — fishnet lattice dense with fish, bird processions, otters and squirrels, wave forms and geometric 'audiencia' panels, some once painted in mineral pigments over earth plaster. Mud brick and puddled adobe made a soft, soaring, monochrome architecture where shadow carves the ornament; storerooms, sunken plazas and burial platforms organized each walled royal compound, built by one king and sealed at his death. Inca conquest (c. 1470) and El Niño rains softened the city; UNESCO listing (1986) flags its fragility, and conservation shelters now roof the finest friezes. The look: golden-brown clay light, lace-precise relief, endless corridor perspective.",
    col: [{ h: "#c9a06a", n: "adobe gold" }, { h: "#8a6a45", n: "shadow clay" }, { h: "#5d4a33", n: "relief depth brown" }, { h: "#e3d3b3", n: "plaster pale" }, { h: "#3f6f7a", n: "painted teal traces" }],
    m: ["molded adobe brick", "puddled mud wall core", "earth plaster", "mineral paint (traces)"],
    tx: ["carved low relief", "wind-eroded clay", "corridor shadow bands", "pale limewash patches"],
    obj: ["fishnet lattice walls", "bird processions", "audiencia niches", "sunken courtyards", "burial platforms"],
    ex: ["Nik An (Tschudi) ciudadelas", "UNESCO-sheltered frieze corridors", "nearby Huaca Esmeralda and Huaca del Arco Iris"],
    inf: ["earlier north-coast mural traditions", "Chimor urban planning"], rel: ["Sahelian Mud Architecture", "Nazca lines", "Moche portrait vessels"],
    par: "North-coast Andean urbanism", var: ["ciudadelas", "smaller elite compounds", "huaca-relief temples"], cf: ["Sahelian mud architecture", "Tiwanaku stonework"],
    src: [{ n: "Wikipedia — Chan Chan", u: "https://en.wikipedia.org/wiki/Chan_Chan", t: "B" }, { n: "UNESCO World Heritage Centre", u: "https://whc.unesco.org/en/list/366", t: "A" }],
    tg: ["adobe", "chimu", "chan chan", "relief", "peru"], pop: 35, niche: false,
    vd: { shape: "continuous wall friezes", line: "clay-carve contour", composition: "corridor perspective repetition", texture: "eroded adobe", forms: "fishnets, birds, otters, waves" },
    typ: { display: "humanist serif", body: "humanist sans", notes: "site signage" },
    fnt: { display: "Marcellus", body: "Work Sans", notes: "monumental calm caps" },
    lit: { quality: "coastal desert glare", direction: "low raking sun", temperature: "hot-warm", shadow: "deep relief shadow" },
    pho: { approach: "corridor one-point perspective, relief raking light", grade: "warm dusty" },
    fash: { silhouettes: "cotton wrap robes", garments: "plain weave loincloths", acc: "gold ear ornaments" },
    env: { places: "walled ciudadelas, Trujillo outskirts", weather: "garúa fog to blazing sun" },
    gd: { layout: "repeating band header", icon: "fishnet lattice" },
    ui: { background: "adobe gold", surface: "relief-texture cards", components: "lattice buttons", motion: "corridor scroll" },
    rec: { materials: "adobe textures, shelters", lighting: "raking golden", objects: "models, ceramics, frieze casts", music: "Andean quena", scent: "dry clay, sea salt" },
    snd: ["wind through corridors", "distant sea"],
    dna: { mi: 50, og: 55, wc: 15, ns: 5, ad: 5, hf: 10, rr: 30, ps: 30, sh: 35, ql: 25, oc: 20, ds: 60, rs: 20, eu: 80, np: 25 },
    emo: { warm: 65, cold: 30, playful: 20, serious: 75, chaotic: 15, ordered: 85, nostalgic: 65, futuristic: 10, peaceful: 45, ominous: 35 },
  },
  {
    n: "Mapuche silver and kultrun", a: ["Mapuche silverwork", "platería mapuche", "kultrun shaman drum"],
    cat: "Fashion & Dress", c: "silver regalia and sacred drum", e: "regional_tradition", o: "Mapuche, Araucanía", g: "Chile and Argentina",
    p: "18th-19th c flourishing to present", era: "living tradition",
    sum: "Coin-silver headbands, pins and pectorals worn in shining abundance — and the machi's quartered cosmos drum.",
    desc: "After 18th-century peace parlamentos flooded Araucanía with silver coins, Mapuche smiths (plateros) melted and re-forged them into a dazzling female regalia: tupu shawl pins, trapelacucha pectorals, trariwe headbands, chaway earrings and silver-studded belts, chased and engraved in symmetric plant-and-star repoussé, worn layered at ngillatun ceremonies so a woman glittered like lineage itself. Alongside, the machi (healer) paints the kultrun drum's head with the four quarters of the Mapuche cosmos (meli witran mapu) and its stepped crosses, drumming it to travel and heal; the drum is both instrument and cosmological chart. Missionization and Chilean assimilation nearly stilled both arts; the late 20th-century Mapuche renaissance revived platería workshops and machi practice. The look: coin-bright silver on indigo cloth, painted drum thunder.",
    col: [{ h: "#d9d9d9", n: "coin silver" }, { h: "#2b3a67", n: "indigo cloth" }, { h: "#8a3324", n: "drum paint red" }, { h: "#1c1c1c", n: "drum black" }, { h: "#5d7d6b", n: "patina green" }],
    m: ["coin silver", "hide drum head", "hardwood shell", "engraving tools"],
    tx: ["repoussé relief", "engraved line work", "painted rawhide", "coin-silver mirror polish"],
    obj: ["trariwe headbands", "tupu pins", "trapelacucha pectorals", "chaway earrings", "kultrun drums"],
    ex: ["platería at ngillatun ceremonies", "Museo Chileno de Arte Precolombino collections", "contemporary machi kultrun painting"],
    inf: ["colonial coin economy", "Andean quartered cosmology"], rel: ["Yemeni silverwork", "Tuareg silver and leatherwork", "Filigree wirework"],
    par: "", var: ["platería sets", "kultrun cosmology styles", "contemporary silver revival"], cf: ["Yemeni silverwork", "Tuareg silver"],
    src: [{ n: "Wikipedia — Mapuche", u: "https://en.wikipedia.org/wiki/Mapuche", t: "B" }, { n: "Museo Chileno de Arte Precolombino", u: "https://www.precolombino.cl", t: "A" }],
    tg: ["mapuche", "silver", "kultrun", "arauco", "chile"], pop: 30, niche: true,
    vd: { shape: "lobed and starred silver plates", line: "engraved vegetal curves", composition: "layered body symmetry", texture: "raised repoussé", forms: "stars, plants, stepped cross, drum quarters" },
    typ: { display: "humanist serif", body: "humanist sans", notes: "exhibit label" },
    fnt: { display: "Alegreya", body: "Inter", notes: "regional-literary tone" },
    lit: { quality: "cordillera clear", direction: "frontal", temperature: "cool-warm", shadow: "silver relief glint" },
    pho: { approach: "ceremony documentary, silver macro", grade: "cool neutral with silver highlights" },
    fash: { silhouettes: "heavy wrapped shawl over dress", garments: "dark woven-wool dresses", acc: "headbands, pectorals, pins, earrings" },
    env: { places: "ruca clearings, ngillatun fields", weather: "Araucanía rain and volcanoes" },
    gd: { layout: "symmetric medal frame", icon: "stepped cosmological cross" },
    ui: { background: "indigo", surface: "silver-relief cards", components: "medallion buttons", motion: "drum pulse" },
    rec: { materials: "silver sets, hide drums", lighting: "overcast soft", objects: "jewelry, drums, textiles", music: "kultrun and trance chant", scent: "woodsmoke, wet wool" },
    snd: ["kultrun drum", "throat-forward chant"],
    dna: { mi: 45, og: 65, wc: 15, ns: 10, ad: 5, hf: 15, rr: 30, ps: 30, sh: 35, ql: 35, oc: 25, ds: 60, rs: 25, eu: 70, np: 30 },
    emo: { warm: 60, cold: 35, playful: 25, serious: 75, chaotic: 25, ordered: 70, nostalgic: 70, futuristic: 20, peaceful: 45, ominous: 30 },
  },
  {
    n: "Cuban rumba", a: ["rumba cubana", "guaguancó", "yambú and columbia"],
    cat: "Music & Sonic Culture", c: "Afro-Cuban music and dance", e: "community_subculture", o: "Afro-Cuban solares, Matanzas and Havana", g: "Cuba and international scenes",
    p: "late 19th c to present", era: "living tradition (UNESCO 2016)",
    sum: "Street-corner congas and voices — yambú, guaguancó and columbia turning courtyards into ritual theater.",
    desc: "Rumba grew in the solares and waterfront patios of Havana and Matanzas, where freed and enslaved-descended Cubans built ensemble art from conga drums, wooden cajón boxes, claves and call-and-response chorus. Its three faces: yambú, the slow 'dance of the old people'; guaguancó, the flirtatious pursuit sealed by the vacunao gesture; and columbia, the virtuoso solo male challenge balancing on genius footwork and drum dialogue. Long policed and racialized as low culture, rumba rose to national emblem through ensembles like Los Muñequitos de Matanzas and is UNESCO-listed (2016) as heritage of musicianship, dance and improvised verse. Open-air ruedas still erupt on Sunday afternoons in working-class barrios and at Callejón de Hamel; the visual world is sunlit street, bright dresses, drums on crates. The look: sweat-shine courtyard theater, drum circles, flying skirts.",
    col: [{ h: "#d94f3d", n: "guaguancó red" }, { h: "#e8b23c", n: "patio gold" }, { h: "#2b7a78", n: "shuffle teal" }, { h: "#f2ead9", n: "sun white" }, { h: "#3d2b1f", n: "drum skin brown" }],
    m: ["conga drums (tumbadoras)", "cajón boxes", "claves", "catá sticks"],
    tx: ["worn drum skins", "sun-bleached walls", "rust and paint patina", "flaking paint layers"],
    obj: ["tumbadora trio", "clave sticks", "cajón ensembles", "ruffled dresses", "patio drum circles"],
    ex: ["Los Muñequitos de Matanzas performances", "Sunday solar ruedas in Santos Suárez", "Callejón de Hamel gatherings"],
    inf: ["Congo and Lucumí drum languages", "coro-pregón verse tradition"], rel: ["Lucumí eleke and batá", "Ballroom culture", "Afro-Brazilian samba schools"],
    par: "", var: ["yambú", "guaguancó", "columbia"], cf: ["ballroom 'rhumba'", "salsa"],
    src: [{ n: "Wikipedia — Rumba", u: "https://en.wikipedia.org/wiki/Rumba", t: "B" }, { n: "UNESCO Intangible Cultural Heritage", u: "https://ich.unesco.org", t: "A" }],
    tg: ["rumba", "cuba", "congas", "guaguancó", "afro-cuban"], pop: 36, niche: false,
    vd: { shape: "circling courtship duet", line: "clave-spined rhythm", composition: "drum semicircle, open center", texture: "street sun", forms: "drums, skirts, hats, hands" },
    typ: { display: "poster display serif", body: "humanist sans", notes: "concert bill" },
    fnt: { display: "Playfair Display", body: "Inter", notes: "hand-bill energy" },
    lit: { quality: "tropical afternoon", direction: "hard top light", temperature: "hot", shadow: "hard short shadows" },
    pho: { approach: "action documentary, motion blur dancers", grade: "saturated, sun-hot" },
    fash: { silhouettes: "ruffled skirt flare, slim trousers", garments: "polka-dot dresses, guayaberas", acc: "hats, bangles, claves" },
    env: { places: "solares, callejones, Malecón edges", weather: "Caribbean heat, sudden rain" },
    gd: { layout: "poster stack with big type", icon: "drum-and-clave mark" },
    ui: { background: "patio gold", surface: "sun-fade cards", components: "round drum buttons", motion: "clave sync pulse" },
    rec: { materials: "drums on crates, peeling paint", lighting: "harsh joyful", objects: "drums, dresses, bottles of rum", music: "guaguancó ensembles", scent: "cigar, ocean, fried plantain" },
    snd: ["tumbadora talk", "clave wood click"],
    dna: { mi: 35, og: 70, wc: 10, ns: 10, ad: 5, hf: 20, rr: 40, ps: 45, sh: 30, ql: 70, oc: 35, ds: 55, rs: 60, eu: 60, np: 40 },
    emo: { warm: 90, cold: 10, playful: 75, serious: 40, chaotic: 45, ordered: 55, nostalgic: 70, futuristic: 20, peaceful: 50, ominous: 15 },
  },
  {
    n: "Puerto Rican vejigante masks", a: ["vejigantes", "carnival de Ponce masks", "coconut-shell vejigante"],
    cat: "Regional & Cultural Tradition", c: "carnival masking", e: "regional_tradition", o: "Puerto Rico (Ponce and Loíza)", g: "Puerto Rico and diaspora",
    p: "18th c festival roots to present", era: "living tradition",
    sum: "Horned, bat-winged tricksters in papier-mâché or coconut shell — carnival's comic-devil exorcism.",
    desc: "The vejigante — a horned, many-eyed comic devil with bat-wing capes and a cow-bladder noisemaker (the vejiga) — erupts through Puerto Rico's Fiestas de Santiago Apóstol in Loíza and the February Carnival of Ponce. Two craft schools define the look: Ponce's papier-mâché masks, exaggerated into dozens of horns and 'eyes' in candy colors, and Loíza's carved coconut-shell masks (from the Afro-Puerto Rican lineages of that town) with sharp teeth and domed crowns, both painted in high-saturation point-and-swirl patterns. African, Iberian and Taíno threads braid in the figure's genealogy; master mask-making families pass the trade down, and the mask now doubles as national art emblem in galleries and NMAI collections. The look: grinning horns, confetti paint, wings mid-lunge.",
    col: [{ h: "#e63946", n: "carnival red" }, { h: "#f4d35e", n: "paper yellow" }, { h: "#1d6fa5", n: "paint blue" }, { h: "#2d6a4f", n: "horn green" }, { h: "#3d2b1f", n: "coconut brown" }],
    m: ["coconut shell (Loíza)", "papier-mâché (Ponce)", "oil and enamel paint", "cloth capes"],
    tx: ["carved shell grain", "lumpy paper build", "glossy dot painting", "cape satin flutter"],
    obj: ["multi-horned masks", "bat-wing capes", "cow-bladder noisemakers", "trickster suits", "procession banners"],
    ex: ["Fiestas de Santiago Apóstol, Loíza", "Carnaval de Ponce mask workshops", "vejigante masks in NMAI holdings"],
    inf: ["Iberian festival devil figures", "Afro-Caribbean masking lineages"], rel: ["Cuban rumba", "Venetian Carnevale mask", "Egungun masquerade"],
    par: "", var: ["Ponce papier-mâché style", "Loíza coconut style", "miniature craft masks"], cf: ["Venetian Carnevale mask", "Egungun masquerade"],
    src: [{ n: "Wikipedia — Vejigante", u: "https://en.wikipedia.org/wiki/Vejigante", t: "B" }, { n: "National Museum of the American Indian", u: "https://americanindian.si.edu", t: "A" }],
    tg: ["vejigante", "carnival", "puerto rico", "mask", "loiza"], pop: 28, niche: true,
    vd: { shape: "horn-burst mask fronts", line: "dot-and-swirl paint rhythm", composition: "figure-in-motion parade", texture: "shell and paper lump", forms: "horns, teeth, wings, eyes" },
    typ: { display: "carnival display sans", body: "humanist sans", notes: "festival poster" },
    fnt: { display: "Syne", body: "Inter", notes: "wry grotesque display" },
    lit: { quality: "tropical carnival noon", direction: "hard frontal", temperature: "hot", shadow: "hard masks' shadows" },
    pho: { approach: "parade action, mask close-ups", grade: "high-saturation joy" },
    fash: { silhouettes: "billowing cape over suit", garments: "bright satins and ruffles", acc: "masks, bladders, bells" },
    env: { places: "Loíza streets, Ponce plazas", weather: "steamy July sun" },
    gd: { layout: "poster burst with radial horns", icon: "horned grin" },
    ui: { background: "carnival red", surface: "confetti-dot cards", components: "horn buttons", motion: "cape whoosh" },
    rec: { materials: "masks drying on lines, paint pots", lighting: "noon hard", objects: "masks, capes, drums", music: "plena and bomba", scent: "oil paint, ocean, fried food" },
    snd: ["bomba barrel drums", "cowbell clatter"],
    dna: { mi: 30, og: 65, wc: 10, ns: 15, ad: 5, hf: 15, rr: 45, ps: 65, sh: 30, ql: 70, oc: 40, ds: 55, rs: 65, eu: 55, np: 40 },
    emo: { warm: 85, cold: 10, playful: 85, serious: 30, chaotic: 55, ordered: 45, nostalgic: 65, futuristic: 20, peaceful: 40, ominous: 30 },
  },
  {
    n: "Lucumí eleke and batá", a: ["Santería bead necklaces", "ileke", "consecrated batá drums"],
    cat: "Religious & Sacred Art", c: "initiatory beadwork and sacred drums", e: "regional_tradition", o: "Lucumí (Regla de Ocha), Cuba", g: "Cuba, US, Latin America, Nigeria links",
    p: "19th c Cuba onward", era: "living tradition",
    sum: "Oricha-colored consecrated beads and Añá-filled batá drums — the orishas' colors and voices made wearable.",
    desc: "In Lucumí (Santería/Regla de Ocha) practice, eleke — necklaces of glass and stone beads — are consecrated by padrinos in oricha colors: Elegguá's red-and-black, Obatalá's all white, Yemayá's translucent blue, Changó's red-and-white — worn as protection and covenant, each collar a material oath. Beside them stand the batá drums (iyá, itótele, okónkolo), two-headed drums 'born' through the Añá consecration that installs the oricha of the drum itself; bembé toques call orichas with praise songs and 'talking' drum patterns from Yoruba Nigeria. Cowrie-shell diloggún divination boards, sopera lidded vessels and white sanctuary cloths complete a domestic-temple aesthetic of gleaming color under white light. Post-1959 exile carried the tradition to New York and Miami temple rooms; museums now collect both as diaspora sacred art. The look: bead-bright color codes, thunder of consecrated drums.",
    col: [{ h: "#c0392b", n: "Changó red" }, { h: "#f2ead9", n: "Obatalá white" }, { h: "#2b6f8a", n: "Yemayá blue" }, { h: "#e8b23c", n: "Ochún gold" }, { h: "#1c1c1c", n: "Elegguá black" }],
    m: ["glass and stone beads", "cowrie shells", "goatskin drum heads", "hardwood batá shells"],
    tx: ["tight bead luster", "drum skin tautness", "white cloth sheen", "wood drum polish"],
    obj: ["eleke necklaces", "batá drum trio", "diloggún cowrie sets", "sopera vessels", "beaded drum skirts"],
    ex: ["Añá-consecrated batá at bembé toques", "eleke consecrations in ilé ocha rooms", "Smithsonian Folkways batá recordings"],
    inf: ["Yoruba bead and drum traditions", "Catholic saint syncretism"], rel: ["Cuban rumba", "Yoruba beaded crowns", "Puerto Rican vejigante masks"],
    par: "", var: ["eleke sets by oricha", "fundamento batá sets", "trono throne displays"], cf: ["Candomblé beadwork", "Haitian vodou flags"],
    src: [{ n: "Wikipedia — Santería", u: "https://en.wikipedia.org/wiki/Santer%C3%ADa", t: "B" }, { n: "Wikipedia — Batá drum", u: "https://en.wikipedia.org/wiki/Bat%C3%A1_drum", t: "B" }, { n: "Smithsonian Folkways", u: "https://folkways.si.edu", t: "A" }],
    tg: ["santeria", "eleke", "bata", "oricha", "diaspora"], pop: 24, niche: true,
    vd: { shape: "looped bead strands", line: "color-code bands", composition: "altar-centered symmetry", texture: "bead luster on cloth", forms: "collars, drums, crowns, shells" },
    typ: { display: "humanist serif", body: "humanist sans", notes: "quiet respectful caption" },
    fnt: { display: "Cormorant Garamond", body: "Inter", notes: "reverent serif, plain body" },
    lit: { quality: "altar candle", direction: "warm low", temperature: "warm", shadow: "bead sparkle points" },
    pho: { approach: "respectful detail photography, drums in situ", grade: "warm, soft highlight" },
    fash: { silhouettes: "all-white garment drape", garments: "white cotton ceremonial dress", acc: "eleke, ide bracelets, cowries" },
    env: { places: "ilé ocha rooms, thrones of cloth", weather: "still night air" },
    gd: { layout: "centered altar band", icon: "bead-strand arc" },
    ui: { background: "sanctuary white", surface: "bead-code cards", components: "strand buttons", motion: "drum pulse" },
    rec: { materials: "drums, bead trays, white cloth", lighting: "candle warm", objects: "eleke, batá, soperas", music: "bembé batá cycle", scent: "cocoa butter, omiero herbs" },
    snd: ["batá conversation", "call-and-response chant"],
    dna: { mi: 45, og: 60, wc: 15, ns: 10, ad: 5, hf: 15, rr: 30, ps: 35, sh: 30, ql: 45, oc: 25, ds: 55, rs: 35, eu: 60, np: 35 },
    emo: { warm: 75, cold: 20, playful: 35, serious: 75, chaotic: 30, ordered: 70, nostalgic: 60, futuristic: 15, peaceful: 45, ominous: 35 },
  },
];
