/**
 * Curated wave — West Asia II (batch b): Arabian Peninsula, Levant, Mesopotamia.
 * Hand-authored from documented traditions. Sources: real, tiered, URL-verified.
 */
export const WAVE_WAS2: any[] = [
  {
    n: "Hijazi roshan bay window", a: ["roshan", "rawashin (plural)", "Hijazi oriel window"],
    cat: "Architectural Style", c: "Coastal timber architecture", e: "regional_tradition", o: "Jeddah, Hijaz (Saudi Arabia)", g: "Red Sea coast: Jeddah, Mecca, Yanbu",
    p: "16th-19th century peak", era: "Ottoman-era Hijaz",
    sum: "Projecting two-storey wooden bay windows of carved lattice and turned balusters that cool, shade and screen the coral houses of old Jeddah.",
    desc: "The roshan is a deep timber bay projecting over the narrow streets of Al-Balad, Jeddah, built as a cage of turned balusters, fretted panels and sliding shutters so sea breezes pass through while household life stays screened. Crafted from bilaily wood shipped by dhow from India and Africa, the finest examples run the full height of two storeys and carry brass finials and carved bosses. Roshan working defined Hijazi domestic architecture from Mecca to Yanbu, part of a wider Red Sea wooden-balcony culture. When Al-Balad declined in the oil era the rawashin rotted; UNESCO listed Historic Jeddah in 2014 and restorers now train new makers of the old screens.",
    col: [{ h: "#4b3621", n: "bilaily dark timber" }, { h: "#8a6642", n: "weathered teak" }, { h: "#e8dcc4", n: "lime-washed plaster" }, { h: "#2f6f6f", n: "Red Sea teal" }, { h: "#b08d57", n: "brass finial" }],
    m: ["bilaily teak", "turned balusters", "carved fret panels", "brass fittings", "coral-rag masonry"],
    tx: ["pierced lattice shadow", "smooth worn balusters", "peeling sea-salt paint"],
    obj: ["two-storey roshan bay", "sliding shutter screens", "brass door studs", "rawashin street canyons", "copper window hoods"],
    ex: ["Naseef House roshan facade, Al-Balad", "Al-Matbouli House Museum, Jeddah", "Historic Jeddah UNESCO district"],
    inf: ["Red Sea dhow-trade timber craft", "Ottoman provincial building culture"], rel: ["Mashrabiya screen", "Hadhrami architecture", "Gulf barjeel wind tower"],
    par: "Islamic vernacular architecture", var: ["Yanbu coastal roshan", "Mecca pilgrimage-season houses"], cf: ["Mashrabiya screen"],
    src: [{ n: "Wikipedia — Al-Balad, Jeddah", u: "https://en.wikipedia.org/wiki/Al-Balad,_Jeddah", t: "B" }, { n: "UNESCO World Heritage — Historic Jeddah", u: "https://whc.unesco.org", t: "A" }],
    tg: ["timber", "balcony", "jeddah", "lattice", "red sea"], pop: 34, niche: true,
    vd: { shape: "stepped projecting bays", line: "vertical baluster rhythm", composition: "timber cage over stone base", texture: " pierced screen shadows on plaster", forms: "oriel windows, carved rails, hoods" },
    typ: { display: "Aref Ruqaa inscriptions over doorways", body: "Noto Naskh Arabic", notes: "painted cartouches between rawashin" },
    fnt: { display: "Aref Ruqaa", body: "Noto Naskh Arabic", notes: "calligraphic headers, quiet legible body" },
    lit: { quality: "hard coastal sun outside, sifted inside", direction: "raking down narrow alleys", temperature: "hot, cooled by shade", shadow: "lace shadows from lattice" },
    pho: { approach: "low angle down the roshan-lined lanes at golden hour", grade: "warm sand tones with deep timber browns" },
    fash: { silhouettes: "loose flowing layers", garments: "white thobe, black abaya", acc: "bone and silver combs, amber misbaha" },
    env: { places: "coral-stone lanes, dhow harbours, suq arcades", weather: "humid sea heat, dusty khamsin winds" },
    gd: { layout: "vertical bays stacked like the houses", icon: "fretted screen motif" },
    ui: { background: "warm plaster ivory", surface: "timber-framed cards with pierced edges", components: "arched buttons with brass studs", motion: "shutter-slide transitions" },
    rec: { materials: "aged teak, lime plaster, brass", lighting: "low sun through lattice", objects: "dallah coffee set, mother-of-pearl chest, pilgrim souvenirs", music: "Hijazi majdal? no — Hijazi mawwal and marafa drumming", scent: "oud, sea salt, cardamom" },
    snd: ["call to prayer from street corners", "sea gulls over the corniche", "creaking timber shutters"],
    dna: { mi: 45, og: 55, wc: 15, ns: 20, ad: 5, hf: 15, rr: 30, ps: 40, sh: 40, ql: 30, oc: 25, ds: 65, rs: 30, eu: 55, np: 20 },
    emo: { warm: 70, cold: 20, playful: 30, serious: 55, chaotic: 25, ordered: 65, nostalgic: 80, futuristic: 15, peaceful: 60, ominous: 15 },
  },
  {
    n: "Gulf barjeel wind tower", a: ["barjeel", "Gulf windcatcher", "Arabic wind tower"],
    cat: "Architectural Style", c: "Passive cooling structure", e: "regional_tradition", o: "Gulf coast towns (Dubai, Sharjah, Doha)", g: "UAE, Qatar, Bahrain, southern Iran",
    p: "19th-early 20th century", era: "pre-oil pearling Gulf",
    sum: "Tall mudbrick wind-catching towers that scoop Gulf breezes down into courtyard houses before electricity.",
    desc: "The barjeel is a rectangular tower rising above Gulf merchant houses, open on one or four faces with brick vanes that trap prevailing north-westerlies and funnel them down a shaft over water or the courtyard below, cooling rooms by evaporation. Built of coral stone, gypsum and mangrove poles in the pearling-era quarters of Bastakiya and Al Shindagha in Dubai, and across Doha and Manama, it is the signature silhouette of the pre-oil town. The form shares ancestry with Iranian badgirs across the Strait of Hormuz. Most surviving barjeels now cap restored heritage districts, museums and cafes, their shadowed shafts still measurably cooler than the street.",
    col: [{ h: "#c8b394", n: "gypsum mudbrick" }, { h: "#9a7b53", n: "sun-baked ochre" }, { h: "#e5d8c0", n: "washed lime" }, { h: "#4f6f8f", n: "gulf sky" }, { h: "#6b4f35", n: "mangrove beam" }],
    m: ["coral and beach stone", "gypsum mortar", "mangrove poles", "chandal mud plaster"],
    tx: ["sun-cracked render", "rough brick vanes", "cool polished courtyard plaster"],
    obj: ["single-scoop barjeel", "four-sided quadruple tower", "wind shaft over jar of water", "low courtyard liwan bench"],
    ex: ["Al Fahidi (Bastakiya) quarter, Dubai", "Heart of Sharjah restored barjeels", "Souq Waqif wind towers, Doha"],
    inf: ["Persian badgir windcatcher"], rel: ["Mashrabiya screen", "Hijazi roshan bay window", "Hadhrami architecture"],
    par: "Islamic vernacular architecture", var: ["single-scoop tower", "quad-directional tower"], cf: ["Iranian badgir"],
    src: [{ n: "Wikipedia — Windcatcher", u: "https://en.wikipedia.org/wiki/Windcatcher", t: "B" }, { n: "Google Arts & Culture", u: "https://artsandculture.google.com", t: "A" }],
    tg: ["passive cooling", "windcatcher", "dubai", "mudbrick", "heritage"], pop: 38, niche: false,
    vd: { shape: "tall rectangular chimney", line: "vertical scoop mouths", composition: "towers stepping over low houses", texture: "cracked lime over coral stone", forms: "shafts, vanes, parapets" },
    typ: { display: "Cairo-style? no — Gulf kufi-esque signage", body: "Cairo", notes: "keep signage simple, heritage plaque style" },
    fnt: { display: "Reem Kufi", body: "Cairo", notes: "geometric Arabic reads cleanly on plaques" },
    lit: { quality: "blazing outside, dim below", direction: "narrow shaft falling into the tower", temperature: "hot whites, cool umbers", shadow: "deep throat of the wind shaft" },
    pho: { approach: "shoot from courtyard up into the scoop against white sky", grade: "high-key sand and bleached sky" },
    fash: { silhouettes: "light loose layers", garments: "white dishdasha, guitra headcloth", acc: "bone fans, leather sandals" },
    env: { places: "alley courtyards, sikkak lanes, palm groves", weather: "40C heat, humid sea wind, rare rain" },
    gd: { layout: "tall centred tower motif on airy ground", icon: "scooped wind mouth" },
    ui: { background: "pale gypsum with crackle texture", surface: "flat cards with tall tower dividers", components: "arched search bars, brick-vane sliders", motion: "airflow ripple from top of screen" },
    rec: { materials: "mudbrick, gypsum, mangrove timber", lighting: "single column of daylight from the scoop", objects: "clay water jars, low cushions, brass tray", music: "Gulf sawt with oud and clapping", scent: "dust, wet plaster, dates" },
    snd: ["wind moaning in the shaft", "distant dhow hammers", "courtyard fountain trickle"],
    dna: { mi: 60, og: 65, wc: 20, ns: 15, ad: 5, hf: 12, rr: 40, ps: 35, sh: 50, ql: 25, oc: 25, ds: 40, rs: 30, eu: 50, np: 15 },
    emo: { warm: 65, cold: 25, playful: 25, serious: 55, chaotic: 20, ordered: 65, nostalgic: 70, futuristic: 20, peaceful: 70, ominous: 10 },
  },
  {
    n: "Khous palm-leaf weaving", a: ["khus weaving", "Bahraini palm-leaf basketry"],
    cat: "Textile & Craft", c: "Palm-leaf plaiting", e: "regional_tradition", o: "Bahrain", g: "Bahrain, Gulf palm oases",
    p: "centuries-old, UNESCO-listed 2021", era: "living tradition",
    sum: "Dyed date-palm fronds plaited into baskets, fans, traps and food covers, the quietest Gulf craft.",
    desc: "Khous is the Bahraini art of splitting and plaiting date-palm fronds into boxes, market baskets, fish traps, fans and cone-shaped food covers, worked by women in village homes and sold at souqs alongside copper and spices. Fronds are boiled, dried and dyed in warm reds, greens and natural gold, then woven in chevron and diamond twills whose patterns distinguish makers. The craft rides on the date palm that structures Gulf life from roof thatch to cradle, and it survives as a heritage anchor: UNESCO inscribed khous on the intangible heritage lists in 2021, and Bahraini museums and craft centres teach it to new generations as palm groves shrink.",
    col: [{ h: "#c9a15a", n: "palm gold" }, { h: "#7d5a2f", n: "dried frond brown" }, { h: "#a63d2f", n: "madder red" }, { h: "#5f7a4a", n: "frond green" }, { h: "#efe3c2", n: "bleached straw" }],
    m: ["date-palm fronds", "plant dyes", "cotton binding cord", "palm-leaf midribs"],
    tx: ["tight diagonal plait", "ribbed chevron bands", "sun-bleached fuzz"],
    obj: ["cone food cover", "date basket", "fish trap", "hand fan", "storage box with lid"],
    ex: ["Bab Al Bahrain souq basket stalls", "Bahrain National Museum khous displays", "Aali handicraft centre workshops"],
    inf: ["date-palm oasis economy"], rel: ["Sadu weaving", "Khous? no — Talli embroidery", "Arabic majlis and dallah coffee culture"],
    par: "Gulf material culture", var: ["undyed work baskets", "dyed tourist-market wares"], cf: ["North African palm braiding"],
    src: [{ n: "UNESCO Intangible Heritage — Khous", u: "https://ich.unesco.org", t: "A" }, { n: "Wikipedia — Bahrain", u: "https://en.wikipedia.org/wiki/Bahrain", t: "B" }],
    tg: ["basketry", "palm", "bahrain", "weaving", "unesco"], pop: 30, niche: true,
    vd: { shape: "cones, boxes, shallow trays", line: "chevron plait ridges", composition: "banded colour zones", texture: "crisp dry ribbing", forms: "traps, fans, lidded baskets" },
    typ: { display: "Harmattan", body: "Harmattan", notes: "Arabic-supporting humanist face matches craft label cards" },
    fnt: { display: "Harmattan", body: "Harmattan", notes: "single friendly family for bilingual labels" },
    lit: { quality: "hard Gulf daylight", direction: "top light in workshops", temperature: "warm", shadow: "tight and small from tight plaiting" },
    pho: { approach: "macro on plait structure plus hands at work", grade: "saturated straw golds with red accents" },
    fash: { silhouettes: "soft draped", garments: "printed house dress, jallabiya", acc: "gold bangles, nose pin" },
    env: { places: "palm groves, village courtyards, souq stalls", weather: "dry heat, shade-seeking afternoons" },
    gd: { layout: "banded chevron stripes as section dividers", icon: "woven cone cover" },
    ui: { background: "palm-cream", surface: "plait-textured cards", components: "ribbon chevron buttons", motion: "weave-in stagger" },
    rec: { materials: "fronds in baskets, dye pots, palm fibre", lighting: "bright workshop daylight", objects: "stacked covers, fans, dye jars", music: "fidjeri pearl-diver songs", scent: "dry palm, cardamom, sea" },
    snd: ["dry plait crackle", "souq bargaining", "palm wind"],
    dna: { mi: 45, og: 40, wc: 20, ns: 8, ad: 5, hf: 10, rr: 45, ps: 45, sh: 45, ql: 30, oc: 30, ds: 55, rs: 35, eu: 40, np: 15 },
    emo: { warm: 75, cold: 20, playful: 40, serious: 45, chaotic: 25, ordered: 70, nostalgic: 75, futuristic: 10, peaceful: 70, ominous: 8 },
  },
  {
    n: "Talli embroidery", a: ["talli braid", "karkusha trim", "Gulf silver-thread braid"],
    cat: "Textile & Craft", c: "Metallic ribbon braid", e: "regional_tradition", o: "UAE and Gulf coast", g: "UAE, Kuwait, Qatar, Oman",
    p: "documented since the 19th century", era: "living tradition",
    sum: "Flat silver-wrapped thread braided on small stands into ribbons that edge the necks and cuffs of Gulf women's dresses.",
    desc: "Talli is a narrow woven braid of silver or gold-wrapped thread wound around cotton and silk cores, worked by women on a small floor stand and sewn around the neck opening, sleeves and hem panels of the kandura and jallabiya for weddings and Eid. Patterns run in geometric diamonds and zigzags with tiny mirror-bright points, read as family wealth and occasion wear across the Gulf. The braid is structural ornament: stiff, dense, jingling slightly when new and softening with ironing and wear. UNESCO placed Emirati talli on the intangible heritage list in 2022, and bridal ateliers in Abu Dhabi and Dubai still commission hand-braided trim beside machine-made copies.",
    col: [{ h: "#b9b2a8", n: "silver zari" }, { h: "#8f1f2e", n: "ceremonial crimson" }, { h: "#1f3a5f", n: "midnight blue" }, { h: "#d8c27a", n: "pale gold thread" }, { h: "#2e2b28", n: "charcoal ground" }],
    m: ["silver-wrapped thread", "silk core yarns", "cotton warp", "small braiding stand"],
    tx: ["dense metallic ridges", "stiff plaited sheen", "mirror glints"],
    obj: ["kandura neck braid", "bridal sleeve panels", "braid stand (nul? )", "occasional? no — Eid dress trim", "fringed veil edges"],
    ex: ["Emirati bridal kandura with talli collar", "Sheikh Zayed Festival heritage dress displays", "Al Fahidi district braid demonstrations"],
    inf: ["Indian zari metal-thread trade"], rel: ["Sadu weaving", "Khous palm-leaf weaving", "Arabic majlis and dallah coffee culture"],
    par: "Gulf women's dress arts", var: ["gold-only bridal braid", "coloured silk talli for everyday"], cf: ["Indian zari braid"],
    src: [{ n: "UNESCO Intangible Heritage — Talli", u: "https://ich.unesco.org", t: "A" }, { n: "Wikipedia — Culture of the United Arab Emirates", u: "https://en.wikipedia.org/wiki/Culture_of_the_United_Arab_Emirates", t: "B" }],
    tg: ["braid", "metallic thread", "emirati", "dress", "bridal"], pop: 31, niche: true,
    vd: { shape: "narrow parallel ribbon bands", line: "zigzag diamond repeats", composition: "trim framing neck and cuffs", texture: "ridged metal sheen", forms: "braids, tassels, fringes" },
    typ: { display: "Reem Kufi", body: "Tajawal", notes: "geometric Arabic echoes braid geometry" },
    fnt: { display: "Reem Kufi", body: "Tajawal", notes: "clean geometric pair for bilingual captioning" },
    lit: { quality: "sparkling point highlights", direction: "angled so metallic ridges catch light", temperature: "cool silver over warm cloth", shadow: "micro shadows between ridges" },
    pho: { approach: "raking close-ups of braid on dark cloth", grade: "high contrast silver-on-black" },
    fash: { silhouettes: "loose flowing gowns with fitted trim", garments: "jallabiya, kandura, abaya", acc: "gold ankle bracelets, henna, silver ring sets" },
    env: { places: "majlis interiors, bridal shops, festival grounds", weather: "cool winter wedding season evenings" },
    gd: { layout: "ribbon borders framing layout blocks", icon: "diamond braid repeat" },
    ui: { background: "deep charcoal", surface: "cards edged with braid stripes", components: "metallic gradient buttons", motion: "shimmer sweep on hover" },
    rec: { materials: "thread cards, scissors, pressed cloth", lighting: "single raking lamp for sparkle", objects: "bridal dress on stand, thread spools, perfume burner", music: "Ayyala drum-and-poetry performance", scent: "oud, rose, new cloth" },
    snd: ["thread hiss through fingers", "Ayyala drum lines", "henna night laughter"],
    dna: { mi: 40, og: 50, wc: 20, ns: 25, ad: 8, hf: 15, rr: 25, ps: 40, sh: 35, ql: 35, oc: 20, ds: 70, rs: 30, eu: 45, np: 18 },
    emo: { warm: 70, cold: 30, playful: 45, serious: 50, chaotic: 20, ordered: 75, nostalgic: 75, futuristic: 15, peaceful: 55, ominous: 10 },
  },
  {
    n: "Arabic majlis and dallah coffee culture", a: ["dallah coffee pot", "Arabic coffee hospitality", "majlis gathering"],
    cat: "Regional & Cultural Tradition", c: "Hospitality ritual", e: "regional_tradition", o: "Arabian Peninsula", g: "Gulf states, Hijaz, wider Arab world",
    p: "15th century onward", era: "living tradition",
    sum: "Cardamom coffee poured from a curved brass dallah into small cups in a seated majlis, hospitality codified by UNESCO.",
    desc: "The majlis is the seated council of Gulf and Hijazi life — cushions and rugs along the walls where guests, elders and neighbours debate, mourn and transact — and its centre is the dallah, a distinctive pear-shaped brass or steel coffee pot with a curved spout, hinged lid and finial. Lightly roasted, cardamom-scented Arabic coffee (gahwa) is poured in finger-deep measures into small handleless finjan cups, refilled until the guest shakes the cup. Both majlis and Arabic coffee were inscribed by UNESCO in 2015 as hospitality heritage. The look is desert-formal: gleaming metal, woven floor seating, mabkhara incense burner circling the room after the third cup.",
    col: [{ h: "#b08d57", n: "dallah brass" }, { h: "#5e4630", n: "roasted husk brown" }, { h: "#7a1f2b", n: "majlis rug red" }, { h: "#d9c9a3", n: "sand cushion" }, { h: "#3c352c", n: "dark frankincense smoke" }],
    m: ["brass or steel dallah", "handleless finjan cups", "wool sadu rugs", "mabkhara incense burner", "mortar (mihbash)"],
    tx: ["polished metal sheen", "dense pile floor seating", "smoke haze"],
    obj: ["curved-spout dallah", "finjan cup set", "mihbash coffee pestle", "dates and cups tray", "mabkhara censer"],
    ex: ["Qatari majlis at Souq Waqif, Doha", "Nizwa Fort majlis, Oman", "Hijazi reception majlis with mabkhara rite"],
    inf: ["Sufi-era coffee spread from Yemen", "Bedouin guest-right codes"], rel: ["Sadu weaving", "Gulf falconry culture", "Turkish kahvehane culture"],
    par: "Arab hospitality codes", var: ["Saudi light-roast gahwa", "Omani+cardamom-saffron brew", "Qatari karak-adjacent milk teas"], cf: ["Turkish coffee service"],
    src: [{ n: "Wikipedia — Majlis", u: "https://en.wikipedia.org/wiki/Majlis", t: "B" }, { n: "Wikipedia — Arabic coffee", u: "https://en.wikipedia.org/wiki/Arabic_coffee", t: "B" }, { n: "UNESCO Intangible Heritage — Majlis / Arabic coffee", u: "https://ich.unesco.org", t: "A" }],
    tg: ["coffee", "hospitality", "majlis", "brass", "unesco"], pop: 52, niche: false,
    vd: { shape: "curved pot silhouette", line: "sweeping spout arc", composition: "circle of cups around a low tray", texture: "burnished brass, wool pile", forms: "pots, cups, censers, pestles" },
    typ: { display: "Aref Ruqaa for welcome banners", body: "Noto Naskh Arabic", notes: "generous letter spacing for receipts and menus" },
    fnt: { display: "Aref Ruqaa", body: "Noto Naskh Arabic", notes: "calligraphic welcome, quiet reading body" },
    lit: { quality: "warm lamp pools", direction: "low from floor seating", temperature: "amber warm", shadow: "soft, smoke-diffused" },
    pho: { approach: "pouring shot with steam and incense smoke backlit", grade: "golden hour interior warmth" },
    fash: { silhouettes: "seated formal drapes", garments: "white thobe and shemagh, embroidered jallabiya", acc: "misbaha beads, silver daggers on formal belts" },
    env: { places: "majlis rooms, fort reception halls, desert camp fires", weather: "cool desert nights, winter gathering season" },
    gd: { layout: "semicircular seat map motif", icon: "dallah silhouette" },
    ui: { background: "sand with rug-stripe footer", surface: "low wide cards like floor cushions", components: "brass-ringed buttons", motion: "gentle pour-arc reveals" },
    rec: { materials: "brass, wool, dates, coffee husk", lighting: "candle and lamp low light", objects: "dallah, mabkhara, mihbash, date basket", music: "oud with samri clapping rhythms", scent: "cardamom, frankincense, roasted husks" },
    snd: ["coffee pour into finjan", "mihbash pounding", "low majlis conversation"],
    dna: { mi: 45, og: 45, wc: 15, ns: 20, ad: 5, hf: 15, rr: 30, ps: 40, sh: 35, ql: 30, oc: 30, ds: 45, rs: 35, eu: 50, np: 15 },
    emo: { warm: 85, cold: 15, playful: 40, serious: 60, chaotic: 20, ordered: 70, nostalgic: 75, futuristic: 15, peaceful: 70, ominous: 8 },
  },
  {
    n: "Omani dhow and frankincense ports", a: ["Sur shipyards", "boom and sambuk sailing", "frankincense route"],
    cat: "Regional & Cultural Tradition", c: "Maritime craft culture", e: "regional_tradition", o: "Sur and Dhofar, Oman", g: "Oman, Gulf, Indian Ocean rim",
    p: "bronze age frankincense trade to 20th century sail", era: "ancient to living tradition",
    sum: "Hand-built wooden dhows, sewn and nailed, that carried Dhofar frankincense from Khor Rori across the Indian Ocean.",
    desc: "Oman's maritime aesthetic joins two landmarks: the dhow yards of Sur, where shipwrights still shape teak-hulled badan, boom and sambuqa vessels by eye without plans, and the Dhofar frankincense ports — Khor Rori (ancient Sumhuram) and Al-Baleed — that loaded the white resin of Boswellia trees bound for Jerusalem, Rome and Han China. The visual language is trade-wind elegance: curved raking prows, tall lateen yards, caulking lines like embroidery, and harbour towns of white cubic houses facing the monsoon sea. Oman's Land of Frankincense is UNESCO-listed, and Sur's yards still launch working dhows alongside heritage regattas.",
    col: [{ h: "#3a6b6b", n: "ocean teal" }, { h: "#8a5a33", n: "teak hull" }, { h: "#e8e2d2", n: "white coastal lime" }, { h: "#d9b166", n: "frankincense resin" }, { h: "#274b4f", n: "deep sea shade" }],
    m: ["teak and mango planks", "coir cordage", "fish-oil and lime hull dressing", "cotton lateen sails"],
    tx: ["caulked seam ridges", "sun-split deck timber", "torn sail canvas"],
    obj: ["curved-prow badan dhow", "lateen yard and rigging", "frankincense storage jars", "steering oar", "harbour watchtower"],
    ex: ["Sur dhow building yards", "Khor Rori (Sumhuram) ruins, Dhofar", "Museum of the Frankincense Land, Salalah"],
    inf: ["Indus and East African coastal trade", "ancient South Arabian incense economy"], rel: ["Dhofar khareef season", "Arabic majlis and dallah coffee culture", "Old Sana'a tower houses"],
    par: "Indian Ocean dhow culture", var: ["badan coastal trader", "boom long-distance vessel", "sambuqa fishing craft"], cf: ["Arabian lateen felucca"],
    src: [{ n: "Wikipedia — Dhow", u: "https://en.wikipedia.org/wiki/Dhow", t: "B" }, { n: "Wikipedia — Frankincense", u: "https://en.wikipedia.org/wiki/Frankincense", t: "B" }, { n: "UNESCO World Heritage — Land of Frankincense", u: "https://whc.unesco.org", t: "A" }],
    tg: ["dhow", "frankincense", "oman", "shipbuilding", "indian ocean"], pop: 40, niche: false,
    vd: { shape: "curved crescent hulls", line: "long sheer lines and rigging diagonals", composition: "harbour tiers of masts and white walls", texture: "caulked wood against glare", forms: "prows, yards, jars, forts" },
    typ: { display: "Lalezar", body: "Lateef", notes: "bold poster display over calm Arabic body" },
    fnt: { display: "Lalezar", body: "Lateef", notes: "harbor-poster energy with readable Arabic" },
    lit: { quality: "hard tropical glare", direction: "high sun, sea bounce below", temperature: "hot white, teal shadows", shadow: "short and dark under awnings" },
    pho: { approach: "sail silhouettes at dawn departure, resin macro shots", grade: "turquoise and sun-bleached warm" },
    fash: { silhouettes: "wrap and tuck workwear", garments: "lungi (futa), embroidered Omani kumma cap", acc: "silver khanjar dagger, gold muscat jewelry" },
    env: { places: "shipyard slipways, lagoon mouths, frankincense groves", weather: "khareef mist in Dhofar, dry north-easterlies elsewhere" },
    gd: { layout: "horizon bands with hull-curve dividers", icon: "crescent prow" },
    ui: { background: "sea teal gradient", surface: "plank-striped cards", components: "compass-arc buttons", motion: "sway like anchored hulls" },
    rec: { materials: "teak, coir, resin, canvas", lighting: "dawn side light on slipways", objects: "ship model, resin lumps, brass sextant", music: "Omani sea shanties (nahham songs) and oud", scent: "tar, teak shavings, frankincense smoke" },
    snd: ["caulking mallets", "halyard slap", "nahham work songs"],
    dna: { mi: 50, og: 55, wc: 20, ns: 12, ad: 5, hf: 15, rr: 45, ps: 40, sh: 45, ql: 40, oc: 35, ds: 40, rs: 40, eu: 60, np: 18 },
    emo: { warm: 65, cold: 30, playful: 35, serious: 55, chaotic: 30, ordered: 60, nostalgic: 75, futuristic: 15, peaceful: 60, ominous: 15 },
  },
  {
    n: "Dhofar khareef season", a: ["khareef monsoon", "Salalah green season"],
    cat: "Regional & Cultural Tradition", c: "Seasonal landscape culture", e: "regional_tradition", o: "Dhofar governorate, Oman", g: "Salalah, Jebel Samhan, Dhofar coast",
    p: "June to September annually", era: "living seasonal rhythm",
    sum: "The Indian Ocean monsoon that drowns Arabia's only monsoon coast in fog and turns desert cliffs briefly emerald.",
    desc: "Each summer the khareef wraps Dhofar in warm fog and drizzle, flipping the arid coast around Salalah into meadow: camel-grassed hills, streaming wadis, and frankincense trees drinking green. The spectacle draws Gulf tourists in Kuwaiti and Saudi convoys, picnic tents strung along Wadi Darbat, and a seasonal economy of corn roasts, coconut stalls and boat rides under permanent mist. Visually it is Arabia inverted — grey-white cloud oceans, saturated leaf greens against ochre escarpments, drizzle beading on acacia — and it structures local life: camel herds move to the jebel, herding families follow, and the Khareef festival fills Salalah's grounds with dance and frankincense stalls.",
    col: [{ h: "#5c8a4a", n: "monsoon green" }, { h: "#cfd4d0", n: "khareef fog" }, { h: "#a8842f", n: "dry ochre escarpment" }, { h: "#3f6f8e", n: "storm sea" }, { h: "#7a5230", n: "frankincense bark" }],
    m: ["mist-fed grasses", "acacia and frankincense trees", "tarmac and tent canvas", "coconut palm"],
    tx: ["beaded drizzle", "saturated wet grass", "soft fog veil"],
    obj: ["Wadi Darbat falls", "camel herds on the jebel", "picnic tent camps", "blowholes of Mughsail", "frankincense stalls"],
    ex: ["Wadi Darbat waterfall season", "Mughsail beach blowholes", "Salalah Khareef Festival grounds"],
    inf: ["Indian Ocean monsoon system"], rel: ["Omani dhow and frankincense ports", "Arabic majlis and dallah coffee culture", "Gulf falconry culture"],
    par: "monsoon ecologies", var: ["jebel mist meadows", "coast drizzle belt"], cf: ["Kerala monsoon season"],
    src: [{ n: "Wikipedia — Khareef", u: "https://en.wikipedia.org/wiki/Khareef", t: "B" }, { n: "Wikipedia — Salalah", u: "https://en.wikipedia.org/wiki/Salalah", t: "B" }, { n: "Britannica — Oman", u: "https://www.britannica.com/place/Oman", t: "B" }],
    tg: ["monsoon", "fog", "salalah", "green season", "landscape"], pop: 31, niche: true,
    vd: { shape: "soft rolling green hills under cloud shelves", line: "wadi stream curves", composition: "fog layers erasing horizons", texture: "wet, soft, beaded", forms: "falls, herds, tents, cliffs" },
    typ: { display: "Markazi Text", body: "Lateef", notes: "bookish, misty-soft Arabic pair" },
    fnt: { display: "Markazi Text", body: "Lateef", notes: "serene text-driven identity" },
    lit: { quality: "total diffuse overcast", direction: "omnidirectional", temperature: "cool for Arabia", shadow: "almost none — fog is the light" },
    pho: { approach: "wide fog-layered vistas with camel silhouettes", grade: "desaturated greens, milky highlights" },
    fash: { silhouettes: "layered and windproof", garments: "shawls over dishdasha, colorful Dhofari print dresses", acc: "umbrellas, thermos flasks" },
    env: { places: "jebel meadows, wadi pools, misty coconut groves", weather: "constant drizzle, 22C fog days" },
    gd: { layout: "soft gradient horizons", icon: "fog line over green hill" },
    ui: { background: "mist grey-green", surface: "frosted translucent cards", components: "rounded dewdrop buttons", motion: "fog drift parallax" },
    rec: { materials: "wet grass, canvas, coconut husk", lighting: "flat milky daylight", objects: "frankincense resin, picnic rugs, thermoses", music: "Dhofari oud with slow tabla", scent: "wet earth, frankincense, sea salt" },
    snd: ["drizzle on canvas", "wadi rushing", "camel bells in fog"],
    dna: { mi: 55, og: 75, wc: 25, ns: 6, ad: 5, hf: 12, rr: 40, ps: 45, sh: 25, ql: 25, oc: 35, ds: 30, rs: 50, eu: 65, np: 20 },
    emo: { warm: 55, cold: 40, playful: 55, serious: 35, chaotic: 30, ordered: 55, nostalgic: 60, futuristic: 15, peaceful: 85, ominous: 8 },
  },
  {
    n: "Old Sana'a tower houses", a: ["Sana'ani tower houses", "Old City of Sana'a dwellings"],
    cat: "Architectural Style", c: "High-rise mudbrick vernacular", e: "regional_tradition", o: "Sana'a, Yemen", g: "Yemeni highlands",
    p: "pre-Islamic core to 20th century growth", era: "medieval to modern living city",
    sum: "Five to nine storey rammed-earth tower houses with white gypsum window frames and stained-glass fanlights.",
    desc: "The Old City of Sana'a stacks more than 6,000 tower houses of rammed earth and fired brick, faces rendered in warm earth tones and edged with white qadad gypsum bands, blind windows and calligraphic friezes. Upper floors carry wooden-framed qamariya fanlights of painted stained glass; the topmost room, the mafraj, is a qat-chewing lookout with views over the rooftops. Ground floors once stored grain and sheltered animals, a vertical social diagram a millennium old. UNESCO listed the city in 1986 and placed it on the danger list after 2015 air strikes; Sana'ani builders and qadad masters still repair with traditional mixes where war allows.",
    col: [{ h: "#a9633f", n: "terracotta rammed earth" }, { h: "#efe7d3", n: "qadad white gypsum" }, { h: "#5b7a5e", n: "qamariya green glass" }, { h: "#c04a3a", n: "stained-glass ruby" }, { h: "#6b4a2f", n: "wooden shutter brown" }],
    m: ["rammed earth (zabur)", "fired brick", "qadad lime-gypsum render", "painted qamariya glass", "carved wood shutters"],
    tx: ["hand-smoothed mud walls", "chalk-white banding", "glow of colored glass"],
    obj: ["mafraj lookout room", "qamariya fanlight", "gypsum calligraphic friezes", "Bab al-Yemen gate", "rooftop water cisterns"],
    ex: ["Old City of Sana'a UNESCO quarter", "Great Mosque of Sana'a precinct", "Suq al-Milh market lanes"],
    inf: ["pre-Islamic Sabaean building culture", "highland defensive needs"], rel: ["Hadhrami architecture", "Hijazi roshan bay window", "Armenian tuff stone architecture"],
    par: "Yemeni vernacular architecture", var: ["Radaa and Jibla brick towers", "Shibam-adjacent? no — highland zabur earth towers"], cf: ["Shibam mudbrick towers"],
    src: [{ n: "Wikipedia — Old City of Sana'a", u: "https://en.wikipedia.org/wiki/Old_City_of_Sana%27a", t: "B" }, { n: "UNESCO World Heritage — Old City of Sana'a", u: "https://whc.unesco.org", t: "A" }],
    tg: ["tower house", "yemen", "mudbrick", "stained glass", "unesco"], pop: 33, niche: true,
    vd: { shape: "stepped vertical tower blocks", line: "white horizontal banding", composition: "dense skyline of ranked windows", texture: "hand-polished earth", forms: "fanlights, friezes, crenellations" },
    typ: { display: "Sana'ani? — Thuluth-style display over doors", body: "Scheherazade New", notes: "inscription friezes echo building bands" },
    fnt: { display: "Scheherazade New", body: "Noto Naskh Arabic", notes: "naskh dignity for a living manuscript city" },
    lit: { quality: "highland clear sun", direction: "steep daylight on west faces", temperature: "warm golds", shadow: "deep under white cornices" },
    pho: { approach: "rooftop skylines at dusk when qamariya glow on", grade: "terracotta warm with jewel glass accents" },
    fash: { silhouettes: "layered highland wraps", garments: "futa wrap, embroidered thobe, turban shawls", acc: "jambiya dagger, silver neck rings" },
    env: { places: "rooftop terraces, suq lanes, mosque courtyards", weather: "dry highland days, cold nights" },
    gd: { layout: "stacked storey bands as layout grid", icon: "fanlight arch" },
    ui: { background: "terracotta with white band rules", surface: "tower-section cards", components: "arched qamariya icons", motion: "upward storey-by-storey reveal" },
    rec: { materials: "earth render, gypsum, stained glass", lighting: "late sun plus glass color spill indoors", objects: "qat basket, mafraj cushions, oil lamp", music: "Yemeni oud song (lawn? no) — Sana'ani ghina with qanbus", scent: "earth plaster, qat leaf, woodsmoke" },
    snd: ["rooftop wind", "suq calls", "evening azaan layering"],
    dna: { mi: 40, og: 60, wc: 15, ns: 8, ad: 5, hf: 12, rr: 40, ps: 40, sh: 40, ql: 35, oc: 25, ds: 75, rs: 35, eu: 60, np: 20 },
    emo: { warm: 70, cold: 25, playful: 30, serious: 60, chaotic: 30, ordered: 60, nostalgic: 80, futuristic: 10, peaceful: 55, ominous: 25 },
  },
  {
    n: "Yemeni jambiya dagger culture", a: ["janbiya", "Yemeni curved dagger", "jambiya dress custom"],
    cat: "Fashion & Dress", c: "Dagger and dress custom", e: "regional_tradition", o: "Yemen", g: "Yemen, southern Hijaz",
    p: "documented from the medieval era", era: "living tradition",
    sum: "The centrally-worn curved dagger whose hilt material and sheath read tribe, region and standing across Yemen.",
    desc: "Every Yemeni man of standing wears the jambiya, a short dagger with a sharply curved blade hung vertically at the centre of a wide belt over the futa wrap and thobe. Status is spoken through the hilt — hardwood safa, horn, or prized agate (aqiq) polished in workshops near Sana'a — and through sheath mounts and embroidered belts, with regional styles differing from Taiz to Sada. The dagger is ceremonial as much as practical: drawn in dance flourishes at weddings, pledged on in mediation, inherited like a name. While ban on carrying is debated in modern Yemen and rhino-horn hilts were outlawed to protect rhinos, the jambiya market in Sana'a's suqs remains a theatre of craft and identity.",
    col: [{ h: "#2e2a26", n: "safa hilt black" }, { h: "#9c8150", n: "agate amber" }, { h: "#7a1c22", n: "sheath velvet crimson" }, { h: "#b8b2a6", n: "silver mount" }, { h: "#4a4038", n: "oiled leather" }],
    m: ["safa hardwood hilts", "agate (aqiq) stones", "tooled leather sheaths", "silver and white-metal mounts", "embroidered belts"],
    tx: ["polished stone gloss", "tooled leather grain", "velvet nap"],
    obj: ["curved jambiya blade", "agate-set hilt", "twin sheath belt mounts", "wedding dance flourish", "inheritance dagger box"],
    ex: ["Suq al-Milh dagger stalls, Sana'a", "Saada aqiq agate hilts", "Yemeni National Museum dagger displays"],
    inf: ["Arabian sword-and-dagger etiquette", "Yemeni lapidary trade"], rel: ["Yemeni silverwork", "Old Sana'a tower houses", "Circassian dress"],
    par: "Arabian dress culture", var: ["Taiz-region flat hilts", "northern aqij? no — northern agate-hilt styles", "shepherd's plain wood jambiya"], cf: ["Omani khanjar"],
    src: [{ n: "Wikipedia — Jambiya", u: "https://en.wikipedia.org/wiki/Jambiya", t: "B" }, { n: "British Museum", u: "https://www.britishmuseum.org", t: "A" }],
    tg: ["dagger", "yemen", "agate", "dress", "status"], pop: 32, niche: true,
    vd: { shape: "tight crescent curve", line: "blade mid-rib line", composition: "centred vertical at the belt", texture: "stone gloss on matte cloth", forms: "hilts, sheaths, belts" },
    typ: { display: "Rakkas", body: "Lateef", notes: "bold display suits market-poster tone" },
    fnt: { display: "Rakkas", body: "Lateef", notes: "suq-poster display with quiet body" },
    lit: { quality: "specular stone highlights", direction: "single key for hilt sparkle", temperature: "warm interior", shadow: "hard from a single lamp" },
    pho: { approach: "hilt macro plus full-dress portraits", grade: "deep browns with agate glints" },
    fash: { silhouettes: "belted vertical drape", garments: "futa wrap, white or striped thobe", acc: "jambiya at centre belt, silver belts, embroidered shoes" },
    env: { places: "suq dagger benches, qat chews, wedding courtyards", weather: "highland cool evenings" },
    gd: { layout: "single centred vertical motif", icon: "curved blade arc" },
    ui: { background: "leather brown", surface: "velvet-textured cards", components: "agate-shaped icon chips", motion: "draw-and-sheath swipe" },
    rec: { materials: "agate, horn, leather, silver", lighting: "single lamp to light hilt facets", objects: "daggers on felt, lapidary tools, belt rolls", music: "Yemeni lute ballads", scent: "leather, qat, gun oil" },
    snd: ["agate grinding wheel", "market murmur", "dance flute at weddings"],
    dna: { mi: 45, og: 40, wc: 20, ns: 15, ad: 5, hf: 12, rr: 35, ps: 55, sh: 50, ql: 35, oc: 30, ds: 40, rs: 35, eu: 45, np: 15 },
    emo: { warm: 55, cold: 35, playful: 30, serious: 70, chaotic: 30, ordered: 55, nostalgic: 75, futuristic: 10, peaceful: 45, ominous: 30 },
  },
  {
    n: "Gulf pearl diving culture", a: ["ghaus pearling season", "nahham diver songs", "Bahrain pearling path"],
    cat: "Regional & Cultural Tradition", c: "Pearling economy aesthetics", e: "regional_tradition", o: "Arabian Gulf coast", g: "Bahrain, Qatar, UAE coastal towns",
    p: "peak 18th-early 20th century", era: "pre-oil economy",
    sum: "Fleets of dhows, nose-clipped divers and shipboard singers that built Gulf towns before oil, now a UNESCO memory landscape.",
    desc: "Before oil, the Gulf summer pearling season (ghaus) sent fleets of dhows to the oyster banks with divers who freedive again and again with nose clips (fitaam) and rope weights, while nahham singers on deck kept rhythm through the day. Pearl merchants' houses, diving syndicates and suqs shaped Muharraq, Doha and Dubai; the aesthetic is one of salt-bleached timber, indigo work clothes, mother-of-pearl inlay, and songs of longing sung at sea. Japanese cultured pearls collapsed the trade by the 1930s, but UNESCO listed Bahrain's pearling testaments in 2012 and the restored Pearling Path now walks visitors through merchant houses and diver quarters.",
    col: [{ h: "#7fb3c8", n: "gulf water" }, { h: "#e9e4dc", n: "mother-of-pearl" }, { h: "#5a4632", n: "sun-bleached timber" }, { h: "#2c3e5f", n: "diver indigo" }, { h: "#c8b68e", n: "shell sand" }],
    m: ["dhow timber", "mother-of-pearl inlay", "nose clips (fitaam)", "cotton diving cloths", "rope weights"],
    tx: ["salt-cracked decks", "iridescent shell sheen", "worn rope fiber"],
    obj: ["pearling dhow fleet", "fitaam nose clip", "diver basket (zabeel? daein)", "merchant majlis houses", "pearl sieve trays"],
    ex: ["Pearling Path, Muharraq (UNESCO)", "Siyadi House and majlis, Bahrain", "Doha pearl souq stalls"],
    inf: ["Indian Ocean pearl trade"], rel: ["Omani dhow and frankincense ports", "Arabic majlis and dallah coffee culture", "Gulf barjeel wind tower"],
    par: "Gulf maritime economy", var: ["Bahrain oyster banks", "Qatar fleet towns"], cf: ["South Sea pearl industry"],
    src: [{ n: "Wikipedia — Pearl hunting", u: "https://en.wikipedia.org/wiki/Pearl_hunting", t: "B" }, { n: "UNESCO World Heritage — Pearling, Bahrain", u: "https://whc.unesco.org", t: "A" }],
    tg: ["pearl", "diving", "bahrain", "dhow", "unesco"], pop: 42, niche: false,
    vd: { shape: "low long hulls and oyster curves", line: "rigging diagonals over flat sea", composition: "fleet formations on horizons", texture: "nacreous shimmer on rough wood", forms: "dhows, shells, sieves, houses" },
    typ: { display: "Marcellus", body: "Lateef", notes: "museum-label Latin display, Arabic body" },
    fnt: { display: "Marcellus", body: "Lateef", notes: "inscribed-stone feel with soft Arabic text" },
    lit: { quality: "hard noon sea glare", direction: "overhead with sea bounce", temperature: "hot whites", shadow: "black under hull curves" },
    pho: { approach: "underwater free-dive frames plus nacre macro", grade: "cyan water, bleached decks, pearl highlights" },
    fash: { silhouettes: "minimal working wraps", garments: "indigo waist wraps, head cloths", acc: "pearl strands, silver amulet cases" },
    env: { places: "oyster banks, drying beaches, merchant courtyards", weather: "brutal summer heat, calm seas" },
    gd: { layout: "long horizontal hull lines", icon: "nacreous oyster shell" },
    ui: { background: "deep sea blue", surface: "nacre-gradient cards", components: "wave-line dividers", motion: "slow bob and dive reveals" },
    rec: { materials: "shell, rope, salt timber", lighting: "sun shafts underwater", objects: "pearl trays, nose clips, model dhows", music: "fidjeri diver songs with pearl drum", scent: "brine, tar, musk of oysters" },
    snd: ["nahham song cycles", "oars and halyards", "shells rattling in baskets"],
    dna: { mi: 50, og: 45, wc: 25, ns: 12, ad: 5, hf: 15, rr: 40, ps: 50, sh: 40, ql: 45, oc: 35, ds: 45, rs: 35, eu: 55, np: 15 },
    emo: { warm: 60, cold: 35, playful: 30, serious: 65, chaotic: 25, ordered: 60, nostalgic: 85, futuristic: 10, peaceful: 50, ominous: 25 },
  },
  {
    n: "Gulf falconry culture", a: ["falconry of Arabia", "saker and peregrine training", "falcon majlis"],
    cat: "Regional & Cultural Tradition", c: "Raptor heritage", e: "regional_tradition", o: "Bedouin Arabia", g: "UAE, Qatar, Saudi Arabia, wider region",
    p: "bedouin origins; UNESCO-listed 2016", era: "living tradition",
    sum: "Hooded falcons perched in majlis and cars, a UNESCO-listed hunting heritage with its own souqs, hospitals and passports.",
    desc: "Falconry moved with Bedouin hunters into a Gulf institution: sakers and peregrines trapped on migration, trained to the lure, and carried hooded on the wrist or a cushioned wakir perch through majlis and airport lounges. The material world is rich — stitched leather hoods, mangala? bells? — stitched hoods, ankle bells, padded gloves, telescopes and 4x4 convey sets — while Abu Dhabi runs a falcon hospital issuing bird passports and Doha's Souq Waqif keeps a dedicated falcon souq of traders, vets and hood-makers. UNESCO inscribed falconry as multinational living heritage in 2016; desert-training convoys and drone-vs-falcon debates now share the season with ancient practice.",
    col: [{ h: "#6b4f33", n: "hood leather brown" }, { h: "#8c7a5f", n: "sacker? — saker plumage taupe" }, { h: "#c9b98a", n: "desert training sand" }, { h: "#2f4858", n: "peregrine slate" }, { h: "#a33b2a", n: "hood tassel red" }],
    m: ["stitched leather hoods", "ankle bells and ties", "padded perches (wakir)", "lure and pole", "falcon telemetry"],
    tx: ["feather barring", "soft glove suede", "brass bell shine"],
    obj: ["hooded saker on perch", "falcon souq stalls", "hospital x-ray rooms", "lure-swinging training", "desert convoy hunting camp"],
    ex: ["Abu Dhabi Falcon Hospital", "Doha Falcon Souq", "Al Gannas falconry society, Qatar"],
    inf: ["Bedouin hunting necessity", "central Asian falconry exchange"], rel: ["Arabic majlis and dallah coffee culture", "Sadu weaving", "Dhofar khareef season"],
    par: "worldwide falconry heritage", var: ["saker desert hunting", "peregrine houbara chases"], cf: ["Mongolian eagle hunting"],
    src: [{ n: "Wikipedia — Falconry", u: "https://en.wikipedia.org/wiki/Falconry", t: "B" }, { n: "UNESCO Intangible Heritage — Falconry", u: "https://ich.unesco.org", t: "A" }],
    tg: ["falconry", "falcons", "gulf", "bedouin", "unesco"], pop: 45, niche: false,
    vd: { shape: "hooded teardrop silhouette", line: "wrist-to-perch vertical", composition: "bird centred in majlis calm", texture: "soft barring, worn leather", forms: "hoods, bells, lures, perches" },
    typ: { display: "Cairo", body: "Tajawal", notes: "modern institutional Arabic signage" },
    fnt: { display: "Cairo", body: "Tajawal", notes: "contemporary hospital-and-souq clarity" },
    lit: { quality: "sharp desert light", direction: "low dawn training light", temperature: "warm sand tones", shadow: "long bird shadows at dawn" },
    pho: { approach: "portraits of hooded birds plus release sequences", grade: "golden desert neutrals" },
    fash: { silhouettes: "practical layered outdoor", garments: "kandura under quilted vests", acc: "leather gauntlet, telescope, headscarves" },
    env: { places: "training deserts, airport lounges, hospital wards", weather: "cool hunting season dawns" },
    gd: { layout: "centred bird portrait motif", icon: "hood silhouette" },
    ui: { background: "sand neutral", surface: "feather-texture cards", components: "bell-shaped toggles", motion: "quick swoop transitions" },
    rec: { materials: "leather, brass, feather", lighting: "dawn side light", objects: "gauntlets, hoods, telemetry boxes", music: "Nabati poetry recitation with drums", scent: "leather, dry sage, desert air" },
    snd: ["brass ankle bells", "wing whoosh on release", "4x4 dawn engines"],
    dna: { mi: 55, og: 40, wc: 20, ns: 20, ad: 25, hf: 25, rr: 30, ps: 45, sh: 40, ql: 30, oc: 30, ds: 35, rs: 45, eu: 55, np: 15 },
    emo: { warm: 60, cold: 30, playful: 35, serious: 60, chaotic: 30, ordered: 60, nostalgic: 70, futuristic: 30, peaceful: 55, ominous: 20 },
  },
  {
    n: "Al-Ahsa oasis settlements", a: ["Hofuf oasis architecture", "Al-Hasa palm oasis towns"],
    cat: "Architectural Style", c: "Oasis vernacular", e: "regional_tradition", o: "Al-Ahsa, Eastern Province, Saudi Arabia", g: "Al-Ahsa (Hofuf, Mubarraz), Qatif",
    p: " flourishing medieval to present", era: "living oasis city",
    sum: "A million-palm oasis of mudbrick neighborhoods, canal-fed groves and covered souqs, UNESCO-listed in 2018.",
    desc: "Al-Ahsa is the world's largest palm oasis — some 2.5 million date palms threaded by irrigation canals from artesian springs — wrapped around dense mudbrick neighborhoods in Hofuf. Houses rise in plain earthen masses with deep-set triangular? — with wooden lintels and carved Najdi-style doors, while covered souqs such as Souq al-Qaisariya sell copper, spices and cloaks under timber-and-cane roofs. Fort Ibrahim? — Ibrahim Palace fuses fort, mosque and bath in earthen walls. UNESCO inscribed the oasis in 2018 as an evolving cultural landscape; the look today is date-palm shade over ochre walls, spring pools glowing green, and family courtyards scented with drying fruit.",
    col: [{ h: "#b07a45", n: "ochre mudbrick" }, { h: "#6d8f3e", n: "palm canopy green" }, { h: "#e3d5b8", n: "dusted lime" }, { h: "#4a7d7d", n: "spring pool teal" }, { h: "#7c5b34", n: "tamar? — tamarisk timber brown" }],
    m: ["mudbrick and thorny? — palm-trunk beams", "lime render", "carved wooden doors", "irrigation canal masonry"],
    tx: ["hand-plastered earth", "cool shade flicker", "still water sheen"],
    obj: ["Souq al-Qaisariya arcades", "Ibrahim Palace", "date grove canals", "watchtower? — oasis watch towers", "spring-fed pools"],
    ex: ["Souq al-Qaisariya, Hofuf", "Ibrahim Palace fort-bath", "Jawatha historic mosque and village"],
    inf: ["eastern Arabian spring irrigation (qanat-like) systems"], rel: ["Najdi architecture", "Gulf barjeel wind tower", "Arabic majlis and dallah coffee culture"],
    par: "Arabian oasis vernacular", var: ["Hofuf dense quarter", "Qatif coastal oasis"], cf: ["Najdi mudbrick architecture"],
    src: [{ n: "Wikipedia — Al-Ahsa Oasis", u: "https://en.wikipedia.org/wiki/Al-Ahsa_Oasis", t: "B" }, { n: "UNESCO World Heritage — Al-Ahsa Oasis", u: "https://whc.unesco.org", t: "A" }],
    tg: ["oasis", "mudbrick", "hofuf", "dates", "unesco"], pop: 28, niche: true,
    vd: { shape: "low earthen masses under palm crowns", line: "canal lines through groves", composition: "shade-dappled courtyard layers", texture: "soft eroded plaster", forms: "arcades, palms, pools, doors" },
    typ: { display: "Reem Kufi", body: "Noto Naskh Arabic", notes: "souq signage tone" },
    fnt: { display: "Reem Kufi", body: "Noto Naskh Arabic", notes: "heritage-souq label pairing" },
    lit: { quality: "harsh sun broken by palms", direction: "high dappled canopy light", temperature: "hot with cool green shade", shadow: "palm-leaf mottling" },
    pho: { approach: "grove perspective lines and souq shafts of light", grade: "earthen ochres with saturated green" },
    fash: { silhouettes: "loose desert layers", garments: "thobe, black-and-red? — Eastern Province women's print dresses", acc: "camel-skin? — leather bags, date baskets" },
    env: { places: "palm tunnels, souq arcades, spring pools", weather: "extreme summer heat, mild winters" },
    gd: { layout: "canal-line grids", icon: "date palm frond" },
    ui: { background: "warm ochre", surface: "palm-shade patterned cards", components: "arcade-arch menus", motion: "dappled light shimmer" },
    rec: { materials: "mudbrick, palm wood, water", lighting: "filtered canopy sun", objects: "date baskets, brass souq trays, canal sluices", music: "eastern Arabian sea-and-fajri songs", scent: "dates, wet earth, cardamom" },
    snd: ["water in canals", "palm frond rustle", "souq haggling"],
    dna: { mi: 50, og: 60, wc: 15, ns: 8, ad: 5, hf: 12, rr: 40, ps: 40, sh: 40, ql: 30, oc: 30, ds: 55, rs: 35, eu: 55, np: 15 },
    emo: { warm: 75, cold: 20, playful: 35, serious: 50, chaotic: 30, ordered: 60, nostalgic: 75, futuristic: 15, peaceful: 70, ominous: 10 },
  },
  {
    n: "Palestinian tatreez embroidery", a: ["tatreez", "fallahi cross-stitch", "Palestinian cross-stitch"],
    cat: "Textile & Craft", c: "Cross-stitch dress embroidery", e: "regional_tradition", o: "Historic Palestine", g: "Palestine, Israel, diaspora",
    p: "documented from the 19th century; UNESCO-listed 2023", era: "living tradition",
    sum: "Dense red-on-black cross-stitch panels that once announced a woman's village and now carry Palestinian identity worldwide.",
    desc: "Tatreez is the cross-stitch (fallahi stitch) tradition worked in counted geometric medallions, classically in madder reds on indigo-black handwoven linen, covering the side panels, chest and sleeves of rural thobes. Stitch patterns encoded place and status — a Ramallah moon, cypress trees, wedding grades — so a dress could be read like a map of villages. After 1948 the craft became a portable national emblem and was re-styled with flag colors and political motifs; UNESCO inscribed Palestinian embroidery on the intangible heritage list in 2023. Revivalists like Wafa Ghnaim teach pattern literacy online, and tatreez now appears on sneakers, gallery walls and protest banners alike.",
    col: [{ h: "#a51f1f", n: "madder red" }, { h: "#1c1a17", n: "indigo-black ground" }, { h: "#d9772f", n: "saffron accent" }, { h: "#2f5d3a", n: "olive green" }, { h: "#e8ddc8", n: "undyed linen" }],
    m: ["handwoven linen", "madder and indigo cotton floss", "counted-thread charts", "cross-stitch needles"],
    tx: ["beaded stitch surface", "dense reversible? — near-reversible pattern blocks", "woven ground slub"],
    obj: ["wedding thobe side panels", "cypress and moon motifs", "coin-trimmed? — coin-headdress trim", "pattern samplers", "flag-era motifs"],
    ex: ["Ramallah-style bridal thobe panels", "Wafa Ghnaim's Tatreez and Tea revival", "The Palestinian Museum dress collections"],
    inf: ["regional Mediterranean counted-stitch craft", "Ottoman-era village dress codes"], rel: ["Palestinian keffiyeh", "Sadu weaving", "Anatolian rug traditions"],
    par: "Levantine women's needle arts", var: ["Ramallah red-dominant style", "Bethlehem couching-and? — Bethlehem taffeta-and-couching style", "Gaza? — southern wheat-style? — southern desert motifs"], cf: ["Greek island cross-stitch"],
    src: [{ n: "Wikipedia — Palestinian embroidery", u: "https://en.wikipedia.org/wiki/Palestinian_embroidery", t: "B" }, { n: "UNESCO Intangible Heritage — Palestinian embroidery", u: "https://ich.unesco.org", t: "A" }, { n: "The Palestinian Museum", u: "https://www.palmuseum.org", t: "A" }],
    tg: ["embroidery", "cross-stitch", "palestine", "thobe", "identity"], pop: 44, niche: false,
    vd: { shape: "geometric medallion grids", line: "stepped diagonal stitch lines", composition: "symmetric bands framing solid centers", texture: "raised pixel-like stitches", forms: "thobes, cushions, samplers, banners" },
    typ: { display: "Amiri", body: "Noto Naskh Arabic", notes: "pairing a tradition whose motif is script-like geometry" },
    fnt: { display: "Amiri", body: "Noto Naskh Arabic", notes: "classic Arabic with stitch-geometry captions" },
    lit: { quality: "even studio light", direction: "flat frontal", temperature: "warm reds", shadow: "minimal — pattern is the depth" },
    pho: { approach: "flat-lay panels plus hands-in-stitch close ups", grade: "saturated reds on deep black" },
    fash: { silhouettes: "straight A-line thobes", garments: "embroidered dresses, jackets, keffiyeh accents", acc: "coin headdresses, silver bracelets" },
    env: { places: "village courtyards, refugee-craft workshops, gallery vitrines", weather: "Mediterranean olive-harvest light" },
    gd: { layout: "stitch-grid borders", icon: "eight-pointed star medallion" },
    ui: { background: "undyed linen tone", surface: "cross-stitch patterned headers", components: "diamond-stitch buttons", motion: "stitch-by-stitch draw-in" },
    rec: { materials: "linen, floss, charts, hoops", lighting: "bright even task light", objects: "thobe on mannequin, pattern books, floss cards", music: "Palestinian folk dabke drumming", scent: "olive oil soap, thyme, thread" },
    snd: ["needle through linen", "dabke feet on stone", "olive grove wind"],
    dna: { mi: 35, og: 30, wc: 25, ns: 15, ad: 5, hf: 20, rr: 30, ps: 40, sh: 35, ql: 40, oc: 20, ds: 80, rs: 25, eu: 45, np: 20 },
    emo: { warm: 70, cold: 30, playful: 40, serious: 65, chaotic: 20, ordered: 75, nostalgic: 85, futuristic: 20, peaceful: 55, ominous: 20 },
  },
  {
    n: "Palestinian keffiyeh", a: ["kufiya", "shemagh", "hatta"],
    cat: "Fashion & Dress", c: "Symbolic woven headwear", e: "community_subculture", o: "Levant", g: "Palestine and global solidarity wear",
    p: "rural headwear turned global symbol since the 1930s", era: "living symbol",
    sum: "A woven cotton headcloth whose fishnet, olive-leaf and fence-line motifs became the most legible political textile on earth.",
    desc: "The keffiyeh began as practical Levant rural headwear, but its black-on-white herringbone mesh became an icon through the 1936 revolt and Yasser Arafat's carefully draped style. Its three pattern zones are read symbolically: the fishnet as seafarer nets, the bold central braid as olive leaves, the fence-line border as thorned walls. Once woven across the Levant, mass production moved abroad; the Hirbawi factory in Hebron is celebrated as the last Palestinian keffiyeh loom, running cotton through mechanical jacquards in seasonal colorways. Solidarity wear worldwide now spans scarves, graduation stoles and murals, making the hatta a living subcultural uniform.",
    col: [{ h: "#f4f2ec", n: "white cotton ground" }, { h: "#1d1d1b", n: "black pattern weave" }, { h: "#2f5d3a", n: "olive-leaf green" }, { h: "#a51f1f", n: "solidarity red edition" }, { h: "#8b8b85", n: "loom grey" }],
    m: ["cotton yarn", "jacquard loom warp", "fringe-tied selvages", "herringbone twill weave"],
    tx: ["soft airy drape", "crisp pressed folds", "fringed ends"],
    obj: ["fishnet mesh field", "olive-leaf braid", "fence-line border", "Arafat drape style", "solidarity stoles"],
    ex: ["Hirbawi Textile Factory, Hebron", "Arafat's Ramallah keffiyeh drape", "graduation-stole keffiyeh trend on campuses"],
    inf: ["Ottoman-era headcloth trade", "1930s revolt iconography"], rel: ["Palestinian tatreez embroidery", "Gulf falconry culture", "Techwear"],
    par: "Levantine dress culture", var: ["red-and-white shemagh", "solidarity color editions"], cf: ["Gulf shemagh"],
    src: [{ n: "Wikipedia — Keffiyeh", u: "https://en.wikipedia.org/wiki/Keffiyeh", t: "B" }, { n: "Google Arts & Culture", u: "https://artsandculture.google.com", t: "A" }],
    tg: ["keffiyeh", "symbol", "palestine", "woven", "solidarity"], pop: 58, niche: false,
    vd: { shape: "square drape and folds", line: "herringbone diagonal mesh", composition: "banded zones framing a mesh field", texture: "crisp open-weave cotton", forms: "scarves, stoles, murals" },
    typ: { display: "Cairo", body: "Tajawal", notes: "poster-ready Arabic for protest graphics" },
    fnt: { display: "Cairo", body: "Tajawal", notes: "clean street-poster pairing" },
    lit: { quality: "hard graphic sun", direction: "frontal flag-light", temperature: "neutral", shadow: "deep fold shadows when draped" },
    pho: { approach: "documentary portrait and crowd textures", grade: "high contrast monochrome-friendly" },
    fash: { silhouettes: "draped and knotted headwear, scarf layers", garments: "jackets, tees, graduation robes", acc: "flag pins, woven bracelets" },
    env: { places: "olive groves, campus quads, city marches", weather: "dust and sun of harvest days" },
    gd: { layout: "mesh-pattern section fills", icon: "folded keffiyeh square" },
    ui: { background: "white with black mesh fill", surface: "woven-texture banners", components: "fishnet-grid chips", motion: "fabric-fold wipes" },
    rec: { materials: "cotton, jacquard warp, fringe", lighting: "flat even press light", objects: "folded scarves, loom photos, olive sprigs", music: "rebetiko-adjacent? no — Palestinian protest songs and oud", scent: "olive oil, cotton, rain on dust" },
    snd: ["loom clack", "march chants", "olive wind"],
    dna: { mi: 45, og: 35, wc: 30, ns: 20, ad: 10, hf: 30, rr: 30, ps: 55, sh: 35, ql: 55, oc: 40, ds: 45, rs: 30, eu: 35, np: 20 },
    emo: { warm: 55, cold: 40, playful: 25, serious: 80, chaotic: 45, ordered: 55, nostalgic: 65, futuristic: 30, peaceful: 40, ominous: 30 },
  },
  {
    n: "Levantine wast ad-dar house", a: ["central-hall house", "Damascene ajami courtyard house", "بيت الوسط"],
    cat: "Architectural Style", c: "Courtyard-townhouse plan", e: "regional_tradition", o: "Damascus, Aleppo, Tripoli", g: "Levantine cities",
    p: "Ottoman-era peak, 17th-19th century", era: "Ottoman Levant",
    sum: "Introverted townhouses folded around a fountain courtyard, painted with gilded ajami woodwork under citrus shade.",
    desc: "The Levantine elite house turns its back on the street: plain ablaq walls open into a paved courtyard (wast ad-dar) with a central fountain, fruit trees and raised liwan seats, while the best reception room — the qaa — stacks marble pavement, fountains and polychrome ajami wood paneling gilded with botanical scenes. Damascus and Aleppo merchants built whole quarters of these, with separate family and guest wings and seasons' rooms oriented to sun and shade. Many slid into tenements in the 20th century, then into boutique hotels and museums after restorations; UNESCO's Damascus listing protects a surviving ensemble, and ajami masters still gild new panels for their interiors.",
    col: [{ h: "#d8c9a3", n: "ablaq limestone" }, { h: "#6b4226", n: "ajami wood red-brown" }, { h: "#c9a227", n: "gilded arabesque gold" }, { h: "#3f6f5e", n: "citrus leaf green" }, { h: "#7f9fb2", n: "fountain water" }],
    m: ["ablaq banded stone", "ajami gilded wood panels", "marble floors and fountains", "carved cedar doors"],
    tx: ["polished marble underfoot", "gilded relief wood", "still basin water"],
    obj: ["central courtyard fountain", "qaa reception chamber", "ajami ceiling medallions", "ablaq striped arches", "liwan raised seats"],
    ex: ["Azem Palace, Damascus", "Beit Wakil courtyard, Aleppo", "Debbane Palace, Sidon"],
    inf: ["Ottoman provincial court culture", "classical Damascene woodcraft"], rel: ["Mashrabiya screen", "Andalusian Patio", "Hijazi roshan bay window"],
    par: "Ottoman domestic architecture", var: ["Aleppo merchant qaa houses", "Tripoli riyad? — Tripoli courtyard houses"], cf: ["Andalusian patio"],
    src: [{ n: "Wikipedia — Courtyard house", u: "https://en.wikipedia.org/wiki/Courtyard_house", t: "B" }, { n: "UNESCO World Heritage — Ancient City of Damascus", u: "https://whc.unesco.org", t: "A" }],
    tg: ["courtyard", "damascus", "ajami", "ottoman", "fountain"], pop: 36, niche: false,
    vd: { shape: "inward square around a void", line: "arcade arches meeting the basin", composition: "courtyard as lantern and stage", texture: "stone cool, wood warm, water live", forms: "fountains, arches, panels, trees" },
    typ: { display: "Aref Ruqaa", body: "Noto Naskh Arabic", notes: "gilded cartouche titles" },
    fnt: { display: "Aref Ruqaa", body: "Noto Naskh Arabic", notes: "banquet-inscription tone" },
    lit: { quality: "reflected courtyard glow", direction: "down into the void from above", temperature: "warm shade", shadow: "arcade bands on marble" },
    pho: { approach: "symmetric courtyard-centered frames at midday", grade: "ivory, gold and leaf green" },
    fash: { silhouettes: "stately draped layers", garments: "brocade vests, silk abayas", acc: "agarwood? — oud perfumes, mother-of-pearl fans" },
    env: { places: "citrus courtyards, qaa salons, rooftop grapes? — vine pergolas", weather: "dry Levantine summers" },
    gd: { layout: "central-void composition", icon: "courtyard fountain plan" },
    ui: { background: "marble ivory", surface: "ablaq-banded cards", components: "arch-framed menus", motion: "water-ripple page fades" },
    rec: { materials: "stone, gilded wood, water", lighting: "zenith light with shaded arcades", objects: "nargileh, rosewater sprinklers, inlaid chests", music: "Aleppo muwashshah ensemble", scent: "bitter orange blossom, oud, marble dust" },
    snd: ["fountain play", "nightingales in citrus", "distant call to prayer"],
    dna: { mi: 45, og: 55, wc: 15, ns: 15, ad: 5, hf: 15, rr: 20, ps: 40, sh: 30, ql: 25, oc: 20, ds: 65, rs: 25, eu: 65, np: 20 },
    emo: { warm: 70, cold: 25, playful: 35, serious: 55, chaotic: 15, ordered: 75, nostalgic: 80, futuristic: 15, peaceful: 80, ominous: 8 },
  },
  {
    n: "Marsh Arab mudhif", a: ["mudhif guest hall", "reed ceremonial house"],
    cat: "Architectural Style", c: "Reed great hall", e: "regional_tradition", o: "Mesopotamian Marshes, southern Iraq", g: "Basra, Maysan, Dhi Qar marshes",
    p: "ancient Sumerian lineage; surviving today", era: "living ancient form",
    sum: "Cathedral-scale halls of bundled reeds arched into parabolic ribs — Sumerian architecture still standing in water.",
    desc: "The mudhif is the tribal guesthouse of the Ma'dan (Marsh Arabs): thick bundles of giant kamas reeds bent over and tied into a series of parabolic arches, clad in woven reed mats to make a hall six meters or more high and up to thirty long, with no wood, nails or mud. Light filters through the weave in gold stripes; ceremony, dispute-settlement and hospitality happen beneath. The form descends directly from Sumerian reed construction of five thousand years ago. Saddam's drainage destroyed the marshes in the 1990s; reflooding after 2003 brought communities and mudhifs back, and UNESCO listed the Ahwar of southern Iraq in 2016.",
    col: [{ h: "#c8b06a", n: "dried reed gold" }, { h: "#7d6a3a", n: "shadowed bundle brown" }, { h: "#4f7a6a", n: "marsh water green" }, { h: "#e7ddc0", n: "woven mat cream" }, { h: "#31473d", n: "deep hall shade" }],
    m: ["giant kamas reed bundles", "woven reed mats", "coir lashings", "mud floor? — packed earth floor"],
    tx: ["striped light through weave", "fibrous bundle ridges", "cool mud floor"],
    obj: ["parabolic reed arches", "guest rugs and cushions", "tea urns at the entrance", "buffalo corrals nearby", "reed harvest boats (mashoof)"],
    ex: ["Chibayish mudhif guest halls", "Central Marshes tribal hospitality", "mashoof reed boats of Eridu region? — of the marshes"],
    inf: ["Sumerian reed architecture", "tribal guest-right custom"], rel: ["Old Sana'a tower houses", "Iraqi maqam", "Arabic majlis and dallah coffee culture"],
    par: "Mesopotamian vernacular", var: ["small family mudhif", "ceremonial double-aisle halls"], cf: ["wave? — yurt frame tents"],
    src: [{ n: "Wikipedia — Mudhif", u: "https://en.wikipedia.org/wiki/Mudhif", t: "B" }, { n: "Wikipedia — Marsh Arabs", u: "https://en.wikipedia.org/wiki/Marsh_Arabs", t: "B" }, { n: "UNESCO World Heritage — The Ahwar of Southern Iraq", u: "https://whc.unesco.org", t: "A" }],
    tg: ["reeds", "marsh", "iraq", "sumerian", "hospitality"], pop: 30, niche: true,
    vd: { shape: "cathedral parabolic vaults", line: "ribbed bundle arcs", composition: "golden striped nave of light", texture: "fibrous, dry, luminous", forms: "arches, mats, boats, rugs" },
    typ: { display: "Lateef", body: "Scheherazade New", notes: "simple monumental Arabic" },
    fnt: { display: "Lateef", body: "Scheherazade New", notes: "warm, unadorned pairing" },
    lit: { quality: "filtered golden stripes", direction: "through the woven skin", temperature: "warm gold", shadow: "reed-stripe patterning" },
    pho: { approach: "interior nave symmetry with light stripes", grade: "honey gold on green-black water" },
    fash: { silhouettes: "soft wrapped layers", garments: "plain cotton dishdasha, head wraps", acc: "buffalo-hide? — simple sandals, prayer beads" },
    env: { places: "reed labyrinths, buffalo flood plains, hall interiors", weather: "47C summers, misty winter marshes" },
    gd: { layout: "ribbed-arch section dividers", icon: "parabolic reed arch" },
    ui: { background: "reed gold with light stripes", surface: "mat-weave cards", components: "bundle-arc buttons", motion: "light-stripe sweeps" },
    rec: { materials: "reeds, coir, wool rugs", lighting: "striped interior daylight", objects: "tea urns, mashoof boats, buffalo bells", music: "iraqi? — southern Iraqi riffs on santur and joza", scent: "cut reed, marsh mud, buffalo milk" },
    snd: ["reed creak in wind", "lashing knots tightening", "distant buffalo and birds"],
    dna: { mi: 40, og: 80, wc: 20, ns: 6, ad: 5, hf: 10, rr: 45, ps: 45, sh: 30, ql: 25, oc: 35, ds: 45, rs: 40, eu: 65, np: 18 },
    emo: { warm: 65, cold: 30, playful: 30, serious: 60, chaotic: 25, ordered: 60, nostalgic: 75, futuristic: 8, peaceful: 65, ominous: 20 },
  },
  {
    n: "Iraqi maqam", a: ["Baghdadi maqam", "maqam al-iraqi"],
    cat: "Music & Sonic Culture", c: "Urban classical song", e: "regional_tradition", o: "Baghdad", g: "Iraq and its diaspora",
    p: "flourished 19th-20th century; UNESCO-listed 2003? — proclaimed 2003", era: "late Ottoman to modern",
    sum: "Baghdad's ornamented sung poetry over santur and joza — an Arab-Persian-Turkish crossroads proclaimed by UNESCO.",
    desc: "The Iraqi maqam is Baghdad's classical song form: a solo qari al-maqam delivers dense, ornamented verses across linked modal movements, framed by the algha ensemble of santur hammered dulcimer, joza spike fiddle, tabla and daff. Its repertory of around thirty? — two dozen? — dozens of maqamat absorbs Persian dastgah colors, Ottoman forms and local Baghdadi Jewish and Muslim poets, making it the sound of the city's cafés along the Tigris. The form was proclaimed a UNESCO masterpiece in 2003, and modern masters like Hamid al-Saadi and the legacy of Muhammad al-Qubbanchi keep it alive through recordings and the reopening of maqam evenings after decades of war.",
    col: [{ h: "#1f3a4d", n: "tigris night blue" }, { h: "#b58a3c", n: "santur brass-gold" }, { h: "#7a1f2b", n: "cafe carpet red" }, { h: "#c8b78e", n: "old paper cream" }, { h: "#3c2f2a", n: "aged wood brown" }],
    m: ["santur dulcimer", "joza spike fiddle", "tabla and daff drums", "handwritten song notebooks"],
    tx: ["hammered metal shimmer", "breathy joza drone", "smoky cafe air"],
    obj: ["maqam notebooks", "santur on felt", "tea glasses (istikan)", "recording cassettes", "cafe nargileh"],
    ex: ["Muhammad al-Qubbanchi recordings", "Hamid al-Saadi maqam evenings", "Abu Nuwas Street cafés, Baghdad"],
    inf: ["Persian dastgah modality", "Ottoman court song forms"], rel: ["Azerbaijani mugham", "Turkish kahvehane culture", "Arabic majlis and dallah coffee culture"],
    par: "maqam musical family", var: ["pesteh? — pesta light songs", "abud? — abud? — abu dhabi? no — abud forms", "water? no — muhaltif medleys"], cf: ["Azerbaijani mugham"],
    src: [{ n: "Wikipedia — Iraqi maqam", u: "https://en.wikipedia.org/wiki/Iraqi_maqam", t: "B" }, { n: "UNESCO Intangible Heritage — Iraqi Maqam", u: "https://ich.unesco.org", t: "A" }],
    tg: ["maqam", "baghdad", "santur", "song", "unesco"], pop: 30, niche: true,
    vd: { shape: "arched melodic stairways", line: "long ornamented glides", composition: "suite of linked modal movements", texture: "shimmering strings over drone", forms: "maqamat, pestas, medleys" },
    typ: { display: "Amiri", body: "Noto Naskh Arabic", notes: "poetry-sheet typography" },
    fnt: { display: "Amiri", body: "Noto Naskh Arabic", notes: "classical diwan aesthetics" },
    lit: { quality: "low warm café lamps", direction: "single stage light on the singer", temperature: "amber", shadow: "deep around the listeners" },
    pho: { approach: "café performance frames with smoke haze", grade: "warm sepia with brass highlights" },
    fash: { silhouettes: "mid-century urban tailoring", garments: "suits with open collars, family ceremony dress", acc: "prayer beads, pocket notebooks" },
    env: { places: "Tigris cafés, family ceremonies, radio studios", weather: "hot Baghdad nights with river breeze" },
    gd: { layout: "movement-list track layout", icon: "santur bridge shape" },
    ui: { background: "night blue", surface: "aged-paper track cards", components: "brass-tone players", motion: "slow modal scale slides" },
    rec: { materials: "santur felt, joza skin, cassette tape", lighting: "one warm bulb", objects: "notebooks, tea glasses, nargileh", music: "the music itself", scent: "tobacco, rosewater tea, river damp" },
    snd: ["santur tremolo", "joza husk", "glass spoons on saucers"],
    dna: { mi: 40, og: 35, wc: 20, ns: 10, ad: 10, hf: 15, rr: 25, ps: 55, sh: 25, ql: 35, oc: 35, ds: 50, rs: 30, eu: 70, np: 25 },
    emo: { warm: 65, cold: 30, playful: 30, serious: 75, chaotic: 30, ordered: 65, nostalgic: 85, futuristic: 10, peaceful: 55, ominous: 25 },
  },
  {
    n: "Aleppo soap", a: ["ghar soap", "laurel-oil soap", "Aleppine beldi? no — alep soap blocks"],
    cat: "Material & Surface", c: "Laurel-oil soap block", e: "regional_tradition", o: "Aleppo, Syria", g: "Syria; exported across the Mediterranean",
    p: "documented medieval onward", era: "living craft",
    sum: "Cylinder-stamped green blocks of olive and laurel berry oil soap, aged in towers like stacked coins of the Silk Road.",
    desc: "Aleppo's soap masters boil olive oil into a green gel, finish with laurel berry oil for the percentage stamped on each block, pour the mass onto warehouse floors, and stamp rounds with family seals before stacking them in honeycomb towers to age nine months to a year — the outside oxidizing gold while the cut stays green. The city's souqs sold blocks whose recipes some historians trace back a millennium and credit (contentiously) as ancestors of Castile and Marseille soaps. War devastated the souq quarter and scattered masters to Gaziantep and Beirut, where revival workshops now stamp blocks with the old geometry: two concentric circles around a calligraphic name.",
    col: [{ h: "#7a8a4a", n: "laurel olive green" }, { h: "#c9a86a", n: "oxidized gold rind" }, { h: "#8f4a2f", n: "terracotta stamp red" }, { h: "#e6ddc4", n: "aged stack cream" }, { h: "#4c5a2f", n: "deep oil green" }],
    m: ["olive oil", "laurel berry oil", "soda lye", "stamped cylinder seals"],
    tx: ["dense matte cut face", "waxy aged rind", "seal-impressed ridges"],
    obj: ["tower-stacked aging blocks", "two-ring family stamp", "copper boiling vats", "pour-slab floors", "souq soap pyramids"],
    ex: ["Souq al-Madina soap shops, Aleppo", "Zanabili-stamped aged blocks", "Gaziantep revival workshops of exiled soap families"],
    inf: ["medieval olive-oil chemistry", "Silk Road trade standards"], rel: ["Levantine wast ad-dar house", "Palestinian tatreez embroidery", "Damask weave"],
    par: "Levantine craft trades", var: ["laurel percentage grades (5-40%)", "rose and olive-only variants"], cf: ["Marseille soap"],
    src: [{ n: "Wikipedia — Aleppo soap", u: "https://en.wikipedia.org/wiki/Aleppo_soap", t: "B" }, { n: "Wikipedia — Aleppo", u: "https://en.wikipedia.org/wiki/Aleppo", t: "B" }],
    tg: ["soap", "aleppo", "laurel", "craft", "trade"], pop: 40, niche: false,
    vd: { shape: "coin-round stamped blocks", line: "concentric seal rings", composition: "honeycomb tower stacks", texture: "matte dense cut, waxy rind", forms: "vats, slabs, seals, pyramids" },
    typ: { display: "Reem Kufi", body: "Noto Naskh Arabic", notes: "stamp-like geometric display" },
    fnt: { display: "Reem Kufi", body: "Noto Naskh Arabic", notes: "seal-cut letterforms" },
    lit: { quality: "soft souq shaft light", direction: "angled through wooden lattices", temperature: "warm dusty", shadow: "deep between stacked blocks" },
    pho: { approach: "tower-stack portraits and cut-face macro", grade: "earthen greens and gold" },
    fash: { silhouettes: "work aprons", garments: "master's rolled sleeves, plain cotton", acc: "ring stamps, scales" },
    env: { places: "boiling houses, aging warehouses, souq stalls", weather: "dry curing air" },
    gd: { layout: "circle-stamp seal marks", icon: "two-ring block stamp" },
    ui: { background: "aged cream", surface: "soap-rind textured tiles", components: "round stamp badges", motion: "stack-build transitions" },
    rec: { materials: "oil, lye, stamps, stone slabs", lighting: "dusty souq light shafts", objects: "block pyramids, copper vats, seal handles", music: "Aleppo qudud halabiya ensembles", scent: "laurel, olive oil, hot wax" },
    snd: ["boiling vat slosh", "stamp press thud", "souq calls"],
    dna: { mi: 50, og: 40, wc: 20, ns: 15, ad: 5, hf: 12, rr: 40, ps: 40, sh: 45, ql: 25, oc: 30, ds: 55, rs: 25, eu: 40, np: 12 },
    emo: { warm: 65, cold: 25, playful: 30, serious: 55, chaotic: 25, ordered: 70, nostalgic: 80, futuristic: 10, peaceful: 60, ominous: 12 },
  },
  {
    n: "Tyrian purple", a: ["royal purple", "murex dye", "Phoenician purple"],
    cat: "Material & Surface", c: "Murex sea-snail dye", e: "historical", o: "Phoenician cities of Tyre and Sidon", g: "Mediterranean world",
    p: "c. 1600 BC - 1453 AD", era: "Bronze Age to Byzantine",
    sum: "The gland-derived crimson-purple of sea snails that priced royalty, built Phoenicia's brand, and outshone gold on cloth.",
    desc: "Tyrian purple is drawn from the hypobranchial glands of Murex brandaris and Hexaplex trunculus: glands salted, simmered for days in leaded vats, then aired so the foul reek gives way to a dye that shifts from crimson to violet and never fades — one gram needing thousands of snails. Phoenician coastal mounds of crushed shells at Sidon and Tyre mark the industry that gave the sea-snail its name (purple = phoinix) and priced purple cloth above gold, restricted by Roman sumptuary law to emperors. Byzantine emperors were 'born in the purple' chambers hung with it; the craft died with Constantinople in 1453, and modern chemists like Paul Friedlander and dye revivalists have recreated it from Pliny's recipe.",
    col: [{ h: "#5c2140", n: "true tyrian purple" }, { h: "#7a1f3d", n: "murex crimson" }, { h: "#3f1f3f", n: "byzantine deep violet" }, { h: "#d8cfc0", n: "crushed shell cream" }, { h: "#8a8f7a", n: "vat grey-green" }],
    m: ["murex and trunculus glands", "leaden dye vats", "salt brine", "unmordanted wool"],
    tx: ["deep color-saturated wool", "crystal-crusted vat rims", "shell debris beds"],
    obj: ["imperial purple robes", "shell middens of Sidon", "dye-works vats", 'sumptuary law edicts', "purple-dyed scroll cloths"],
    ex: ["Sidon murex shell middens", "Pliny the Elder's Natural History dye recipe", "purple-producing vats excavated at Meninx, Djerba"],
    inf: ["Phoenician maritime trade networks"], rel: ["Damask weave", "Byzantine icon painting", "Aleppo soap"],
    par: "ancient luxury dye crafts", var: ["true crimson-purple", "bluish trunculus violet"], cf: ["cochineal crimson"],
    src: [{ n: "Wikipedia — Tyrian purple", u: "https://en.wikipedia.org/wiki/Tyrian_purple", t: "B" }, { n: "The Metropolitan Museum of Art", u: "https://www.metmuseum.org", t: "A" }],
    tg: ["dye", "phoenicia", "purple", "antiquity", "luxury"], pop: 42, niche: false,
    vd: { shape: "flowing robe folds", line: "liquid vat swirls", composition: "one saturated hue carrying the frame", texture: "silky deep-dyed wool", forms: "robes, vats, shells, edicts" },
    typ: { display: "Cinzel", body: "EB Garamond", notes: "imperial Latin gravitas" },
    fnt: { display: "Cinzel", body: "EB Garamond", notes: "epigraphic caps with classical body" },
    lit: { quality: "jewel-like saturated", direction: "single key on cloth", temperature: "cool violet", shadow: "plum-dark folds" },
    pho: { approach: "studio cloth studies in a single purple key", grade: "violet-crimson cinematic" },
    fash: { silhouettes: "toga and mantle drapes", garments: "purple-band tunics, imperial chlamys", acc: "gold wreaths, fibulae" },
    env: { places: "harbor dye-works, palace halls, shell beaches", weather: "eastern Mediterranean glare" },
    gd: { layout: "single-hue dramatic blocks", icon: "spiral sea shell" },
    ui: { background: "deep imperial purple", surface: "gold-ruled panels", components: "shell-spiral icons", motion: "slow dye-bleed gradients" },
    rec: { materials: "dyed wool, shells, lead vats", lighting: "single raking source for fold drama", objects: "purple silk, shell middens, bronze scales", music: "Phoenician-lyre reconstructions", scent: "brine, hot wax, resins" },
    snd: ["wave on shell banks", "vat bubbling", "market Greek and Punic chatter"],
    dna: { mi: 55, og: 40, wc: 40, ns: 20, ad: 5, hf: 10, rr: 30, ps: 60, sh: 40, ql: 40, oc: 25, ds: 40, rs: 25, eu: 60, np: 20 },
    emo: { warm: 40, cold: 55, playful: 20, serious: 85, chaotic: 20, ordered: 70, nostalgic: 70, futuristic: 10, peaceful: 40, ominous: 35 },
  },
  {
    n: "Jerusalem stone cladding", a: ["meleke limestone", "Jerusalem golden stone"],
    cat: "Material & Surface", c: "Limestone cladding", e: "regional_tradition", o: "Jerusalem hills quarries", g: "Jerusalem and Israel/Palestine cities",
    p: "ancient use; mandated by 1918 ordinance", era: "continuing tradition",
    sum: "Golden meleke limestone that clads every Jerusalem facade by law, glowing amber at dusk across the city.",
    desc: "Jerusalem stone — mostly meleke and mizzi limestones quarried around the city — has built the walls, terraces and houses of Jerusalem for three millennia, its warm gold responding to light like no plaster can. A 1918 British Mandate ordinance required new buildings to face stone, a rule Israeli planning kept, so the whole city reads as one luminous material from the Old City walls to Mamilla and the Knesset. Surface finish is a dialect: bossed ancient ashlars, chiseled striations, smooth honed modern panels. Architecturally it binds eras — Herodian courses, Mamluk ablaq, Mandate neo-classicism and Safdie's Mamilla — all speaking the same sand-toned stone.",
    col: [{ h: "#d9b980", n: "meleke gold" }, { h: "#c2a06a", n: "chiseled sand" }, { h: "#9c7f52", n: "shadowed ochre" }, { h: "#efe4c8", n: "honed cream" }, { h: "#6e5b3f", n: "course shadow brown" }],
    m: ["meleke limestone", "mizzi hilu and ahmar varieties", "dolomite? — locally quarried hard limestone", "iron-oxide pigmented beds"],
    tx: ["chisel-striated faces", "bossed ashlar relief", "honed smooth panels"],
    obj: ["Old City walls courses", "Mamilla arcade facades", "Mandate-era chiseled blocks", "Herodian drafted-margin ashlars", "hillside terrace retaining walls"],
    ex: ["Old City walls of Jerusalem", "King David Hotel facade", "Mamilla Mall stone arcades"],
    inf: ["Herodian drafted ashlar technique", "British Mandate planning law"], rel: ["Armenian tuff stone architecture", "Dead Cities of Syria", "Levantine wast ad-dar house"],
    par: "Levantine limestone building", var: ["bossed facing", "chiseled striated facing", "modern honed panels"], cf: ["Maltese globigerina limestone"],
    src: [{ n: "Wikipedia — Jerusalem stone", u: "https://en.wikipedia.org/wiki/Jerusalem_stone", t: "B" }, { n: "Wikipedia — Jerusalem", u: "https://en.wikipedia.org/wiki/Jerusalem", t: "B" }],
    tg: ["limestone", "jerusalem", "cladding", "golden", "architecture"], pop: 36, niche: false,
    vd: { shape: "coursed rectangular ashlars", line: "level bed joints", composition: "whole-city monochrome field", texture: "chisel grain, bossed shadows", forms: "walls, arches, terraces, facades" },
    typ: { display: "Frank Ruhl Libre", body: "Noto Serif Hebrew", notes: "Israeli standard faces over stone texture" },
    fnt: { display: "Frank Ruhl Libre", body: "Noto Serif Hebrew", notes: "the typography of modern Hebrew signage" },
    lit: { quality: "highland clarity", direction: "low sun sweeping courses", temperature: "golden", shadow: "course-deep relief shadows" },
    pho: { approach: "facade texture grids at dawn and dusk", grade: "amber-forward, low saturation sky" },
    fash: { silhouettes: "simple urban layers", garments: "linen shirts, dark wool coats", acc: "stone-tone scarves, leather straps" },
    env: { places: "walled lanes, hilltop terraces, modern arcades", weather: "dry heat, winter gold rain light" },
    gd: { layout: "ashlar grid modules", icon: "drafted-margin block" },
    ui: { background: "warm limestone", surface: "chiseled-edge panels", components: "stone-course dividers", motion: "sun-sweep across facades" },
    rec: { materials: "limestone, iron oxide, mortar", lighting: "raking dawn light", objects: "chisels, ashlar samples, olive branches", music: "Sephardic cantorial modes", scent: "dry stone, thyme, rain dust" },
    snd: ["chisel taps", "swallow calls in alleys", "bells and azaan interleaving"],
    dna: { mi: 60, og: 40, wc: 20, ns: 12, ad: 5, hf: 20, rr: 35, ps: 50, sh: 55, ql: 25, oc: 25, ds: 40, rs: 20, eu: 50, np: 12 },
    emo: { warm: 65, cold: 30, playful: 25, serious: 75, chaotic: 20, ordered: 70, nostalgic: 75, futuristic: 20, peaceful: 55, ominous: 25 },
  },
  {
    n: "Neo-Assyrian palace reliefs", a: ["Assyrian alabaster reliefs", "lamassu colossi", "Ashurbanipal lion hunt carvings"],
    cat: "Religious & Sacred Art", c: "Palace relief carving", e: "historical", o: "Nineveh, Nimrud, Khorsabad (Iraq)", g: "Neo-Assyrian empire; world museums",
    p: "9th-7th century BC", era: "Neo-Assyrian",
    sum: "Miles of alabaster low relief narrating royal hunts and wars beneath lamassu colossi — the first great visual epics.",
    desc: "Neo-Assyrian kings walled their palaces with continuous gypsum-alabaster (Mosul marble) orthostats carved in low relief: Ashurnasirpal II hunting lions at Nimrud, Sennacherib's Lachish campaign winding across rooms at Nineveh, Ashurbanipal's dying lioness twisting in the British Museum's most admired panels. Winged lamassu — bulls and lions with human heads — guarded gateways, written with cuneiform annals across their bodies so text and image fuse. The carving's grammar of muscle, profile and ranked procession shaped Mesopotamian visual culture and stunned 19th-century Europe when Layard and Botta excavated the mounds. Islamic State destruction in 2015-2016 gutted Nimrud and Nineveh galleries, making surviving slabs doubly precious.",
    col: [{ h: "#cfc4a6", n: "alabaster ivory" }, { h: "#8a7a58", n: "aged gypsum ochre" }, { h: "#3f3a2f", n: "cuneiform ink brown" }, { h: "#5c4a2f", n: "buried earth" }, { h: "#a89968", n: "carved sand tone" }],
    m: ["gypsum alabaster slabs", "iron and copper chisels", "cuneiform inscriptions", "painted accents (traces)"],
    tx: ["low-relief step shadows", "polished stone grain", "incised script rows"],
    obj: ["dying lioness panel", "lamassu gateway colossi", "Lachish siege frieze", "royal chariot processions", "stylized palm and? — sacred tree motifs"],
    ex: ["Ashurbanipal lion hunt reliefs, British Museum", "Khorsabad lamassu, Louvre", "Lachish campaign frieze (Sennacherib)"],
    inf: ["Babylonian? — Mesopotamian glyptic tradition", "Egyptian? — Levantine tribute iconography"], rel: ["Byzantine icon painting", "Tyrian purple", "Dead Cities of Syria"],
    par: "Mesopotamian court art", var: ["Nimrud narrative style", "Nineveh late-lush style"], cf: ["Persian Persepolis reliefs"],
    src: [{ n: "Wikipedia — Lamassu", u: "https://en.wikipedia.org/wiki/Lamassu", t: "B" }, { n: "Wikipedia — Assyrian sculpture", u: "https://en.wikipedia.org/wiki/Assyrian_sculpture", t: "B" }, { n: "British Museum", u: "https://www.britishmuseum.org", t: "A" }],
    tg: ["relief", "assyria", "lamassu", "cuneiform", "antiquity"], pop: 40, niche: false,
    vd: { shape: "continuous frieze bands", line: "muscle-contour profiles", composition: "register-by-register procession", texture: "shallow carved planes", forms: "lions, chariots, colossi, tributaries" },
    typ: { display: "Cinzel", body: "Spectral", notes: "museum-caption classical tone" },
    fnt: { display: "Cinzel", body: "Spectral", notes: "epigraphic display with scholarly body" },
    lit: { quality: "even museum spots", direction: "grazing light for relief shadow", temperature: "warm ivory", shadow: "relief-internal step shadows" },
    pho: { approach: "grazing-light raking shots down friezes", grade: "ivory-and-umber documentary" },
    fash: { silhouettes: "fringed royal robes", garments: "embroidered kilt shawls, conical caps", acc: "armlets, bows, chariot reins" },
    env: { places: "palace throne suites, excavation trenches, museum galleries", weather: "dust-hot excavation seasons" },
    gd: { layout: "frieze-register layouts", icon: "lamassu profile" },
    ui: { background: "alabaster ivory", surface: "register-banded panels", components: "cuneiform-line buttons", motion: "slow frieze pans" },
    rec: { materials: "alabaster, clay tablets, excavation dust", lighting: "grazing study light", objects: "relief casts, cylinder seals, cuneiform bricks", music: "reconstructed lyre-of-Ur? — Mesopotamian lyre reconstructions", scent: "stone dust, paper, old wax" },
    snd: ["chisel on gypsum", "gallery quiet", "distant excavation picks"],
    dna: { mi: 45, og: 35, wc: 35, ns: 15, ad: 5, hf: 8, rr: 25, ps: 70, sh: 55, ql: 25, oc: 20, ds: 70, rs: 20, eu: 55, np: 10 },
    emo: { warm: 40, cold: 55, playful: 15, serious: 90, chaotic: 25, ordered: 75, nostalgic: 65, futuristic: 5, peaceful: 30, ominous: 45 },
  },
  {
    n: "Dead Cities of Syria", a: ["Northern Syrian limestone villages", "Ancient Villages of Northern Syria (UNESCO)"],
    cat: "Architectural Style", c: "Byzantine rural stone", e: "historical", o: "Limestone massif, NW Syria", g: "Aleppo and Idlib countryside",
    p: "1st-7th century AD", era: "Roman to Byzantine",
    sum: "Forty-odd perfectly preserved late-Roman olive villages — ashlar houses, baths, churches — abandoned without a single later layer.",
    desc: "On Syria's limestone massif, olive-oil wealth built some 40 villages of fine ashlar houses, colonnaded streets, bathhouses, monasteries and martyria between the 1st and 7th centuries, then trade collapsed and everyone left — leaving sites like Serjilla and al-Bara standing in open fields with no medieval or Ottoman overburden. The aesthetic is prose-perfect rural antiquity: golden limestone catching olive-grove light, roofs long gone but walls, door lintels and carved capitals intact. UNESCO inscribed them as the Ancient Villages of Northern Syria in 2011; the war closed access and looting and shellfire have since damaged sites like Brad and Qalblozeh.",
    col: [{ h: "#cbb98e", n: "limestone gold" }, { h: "#8f7f5c", n: "shadowed ashlar" }, { h: "#5f7a4a", n: "olive grove green" }, { h: "#e2d7ba", n: "sun-bleached lintel" }, { h: "#6b5a3f", n: "carved capital brown" }],
    m: ["quarried limestone ashlar", "corbelled stone roofs (rare)", "carved door lintels", "column spolia"],
    tx: ["chisel-dressed blocks", "wind-smoothed edges", "grass-grown thresholds"],
    obj: ["Serjilla bathhouse", "al-Bara pyramidal tombs", "two-storey colonnaded houses", "press beds? — olive press rooms", "Qal'at Sem'an pilgrimage complex"],
    ex: ["Serjilla dead village", "al-Bara tombs and villas", "Church of Saint Simeon Stylites (Qal'at Sem'an)"],
    inf: ["Antiochene? — late-Roman provincial building trade", "olive-oil export economy"], rel: ["Jerusalem stone cladding", "Byzantine icon painting", "Levantine wast ad-dar house"],
    par: "Byzantine provincial architecture", var: ["Jebel Wastani group", "Jebel al-Ala group"], cf: ["Greek? — abandoned Mani tower villages"],
    src: [{ n: "Wikipedia — Dead Cities", u: "https://en.wikipedia.org/wiki/Dead_Cities", t: "B" }, { n: "UNESCO World Heritage — Ancient Villages of Northern Syria", u: "https://whc.unesco.org", t: "A" }],
    tg: ["byzantine", "limestone", "villages", "syria", "unesco"], pop: 30, niche: true,
    vd: { shape: "freestanding wall planes and pediments", line: "columned street axes", composition: "ruins in open olive fields", texture: "wind-polished stone", forms: "houses, baths, tombs, churches" },
    typ: { display: "Cormorant Garamond", body: "Spectral", notes: "antiquarian travel-book typography" },
    fnt: { display: "Cormorant Garamond", body: "Spectral", notes: "old travelogue elegance" },
    lit: { quality: "clear highland sun", direction: "long raking morning light", temperature: "warm gold on cool greens", shadow: "architectural and long" },
    pho: { approach: "wide rural vistas with architectural detail insets", grade: "golden-hour documentary" },
    fash: { silhouettes: "timeless rural", garments: "modern shepherd wraps against antique backdrops", acc: "olive picking pails" },
    env: { places: "olive terraces, empty colonnaded streets, hilltop monasteries", weather: "dry plateau air, winter snows" },
    gd: { layout: "ruin-plan site maps as frames", icon: "pyramidal tomb outline" },
    ui: { background: "parchment", surface: "ashlar-block panels", components: "column-capital markers", motion: "slow reveal of ruins from field grass" },
    rec: { materials: "limestone, olive wood, sun", lighting: "morning raking light", objects: "lintels, press stones, carved capitals", music: "Syriac church chant", scent: "wild thyme, stone dust, olive leaf" },
    snd: ["wind through doorways", "shepherd bells", "bee hum in thyme"],
    dna: { mi: 55, og: 35, wc: 25, ns: 8, ad: 5, hf: 6, rr: 40, ps: 60, sh: 55, ql: 20, oc: 25, ds: 40, rs: 25, eu: 60, np: 10 },
    emo: { warm: 50, cold: 45, playful: 20, serious: 70, chaotic: 25, ordered: 65, nostalgic: 85, futuristic: 5, peaceful: 70, ominous: 35 },
  },
];
