/**
 * Curated wave — West Asia III (batch b part 2): Anatolia, Caucasus, ritual & feast cultures.
 * Hand-authored from documented traditions. Sources: real, tiered, URL-verified.
 * Companion to wave2-west-asia-2.ts — no name/alias overlap with existing-names.txt.
 */
export const WAVE_WAS3: any[] = [
  {
    n: "Ta'ziyeh passion play", a: ["Ta'zieh", "Shia passion drama", "Karbala mourning theatre"],
    cat: "Religious & Sacred Art", c: "Ritual theatre scenography", e: "regional_tradition", o: "Safavid and Qajar Iran", g: "Iran (Varamin, Kashan, Tehran), Iraqi shrine cities, diaspora",
    p: "Safavid roots; golden age 19th century", era: "Qajar Iran",
    sum: "Shia ritual drama re-enacting the martyrdom of Imam Husayn at Karbala, staged in circular tekyeh courtyards with saint-red and villain-green costuming.",
    desc: "Ta'ziyeh is a sung passion play performed during Muharram that re-enacts the battle of Karbala and the martyrdom of Imam Husayn, with actors chanting sung marsiya and noha elegy verses while the audience itself becomes a mourner. Performance spaces are circular open-air tekyeh courtyards so the procession of horsemen can circle the stage; scenery is minimal, with a sand stage strip, a few banners and props like a cradle or a water-skin carrying the story. Costuming encodes theology: holy figures wear green and white with faces veiled, villains wear red and strut in mock-grandeur, a convention unique among world theatre. Qajar patronage built vast tekyeh such as Tekyeh Dowlat in Tehran; the form was suppressed under the Pahlavis, revived after 1979, and UNESCO inscribed Ta'ziyeh ritual performance in 2010. Directors from Peter Brook to Robert Wilson have admired its ritual power.",
    col: [{ h: "#8f1d1d", n: "martyr crimson" }, { h: "#1c1c22", n: "mourning black" }, { h: "#2e7d4f", n: "saint green" }, { h: "#c9a227", n: "halo gold" }, { h: "#d9cbb2", n: "arena dust" }],
    m: ["painted canvas flats", "green and red silk robes", "brass alam standards", "horse trappings", "sand stage strip"],
    tx: ["rough arena dust", "gleaming ceremonial metal", "embroidered velvet banner"],
    obj: ["circular tekyeh courtyard", "veiled saint mask", "green turban and kaffan shroud", "red-clad villain robe", "Karbala banner pole"],
    ex: ["Tekyeh Moaven al-Molk, Kerman", "Ta'ziyeh performances at Varamin", "UNESCO ICH listing 2010 (Ta'zieh ritual performance)"],
    inf: ["Shia Muharram mourning ritual", "Qajar court theatre patronage"], rel: ["Muharram alam processional standards", "Karbala narrative painting", "Medieval mystery play"],
    par: "Islamic ritual performance", var: ["Varamin village ta'ziyeh", "Tehran tekyeh court spectacles"], cf: ["Medieval European passion play"],
    src: [{ n: "Wikipedia — Ta'zieh", u: "https://en.wikipedia.org/wiki/Ta%27zieh", t: "B" }, { n: "UNESCO ICH — Ta'zieh ritual performance", u: "https://ich.unesco.org/en/RL/ta-zieh-ritual-performance-00377", t: "A" }],
    tg: ["passion play", "muharram", "karbala", "tekyeh", "ritual theatre"], pop: 33, niche: true,
    vd: { shape: "circle of horsemen around empty centre", line: "banner poles and standards cutting vertical", composition: "audience surrounds the arena of martyrdom", texture: "dust, velvet, hammered metal", forms: "robes, standards, cradle props" },
    typ: { display: "Lalezar for loudly painted title boards", body: "Vazirmatn", notes: "painted placards announce each scene" },
    fnt: { display: "Lalezar", body: "Vazirmatn", notes: "Persian poster energy, legible ritual text" },
    lit: { quality: "harsh daylight or torchlight, never neutral", direction: "overhead onto the sand ring", temperature: "hot reds against cold blacks", shadow: "long horse-and-rider shadows circling" },
    pho: { approach: "shoot from inside the crowd ring with banners against sky", grade: "high-contrast crimson and umber" },
    fash: { silhouettes: "long robes and wrapped turbans", garments: "green saint robe, red villain coat, black women's chador", acc: "brass alam standards, green headbands" },
    env: { places: "tekyeh courtyards, husseiniyeh halls, dusty village squares", weather: "dry summer heat, drums and dust" },
    gd: { layout: "radial composition with empty martyr centre", icon: "green-and-red split emblem" },
    ui: { background: "sand parchment", surface: "deep red panels with gold rules", components: "banner-ribbon tabs, circular progress rings", motion: "circling processional pan" },
    rec: { materials: "velvet, brass, canvas, sand", lighting: "low sun or torch rings", objects: "cradle prop, water-skin, mourning banners", music: "nefil drum, cymbal and sung martiyeh", scent: "rosewater, dust, incense" },
    snd: ["sorrowful noh-chant of the singers", "horse hooves on packed earth", "chest-beating pulse of the crowd"],
    dna: { mi: 40, og: 80, wc: 10, ns: 25, ad: 10, hf: 10, rr: 70, ps: 55, sh: 60, ql: 30, oc: 35, ds: 75, rs: 20, eu: 40, np: 15 },
    emo: { warm: 45, cold: 40, playful: 10, serious: 95, chaotic: 45, ordered: 60, nostalgic: 55, futuristic: 5, peaceful: 20, ominous: 70 },
  },
  {
    n: "Muharram alam processional standards", a: ["alam standard", "Muharram standards", "panja finial standards"],
    cat: "Religious & Sacred Art", c: "Processional metalwork", e: "regional_tradition", o: "Deccan India and Iran", g: "India (Hyderabad, Lucknow), Iran, Iraq, Pakistan",
    p: "17th-20th century", era: "Qutb Shahi and Asaf Jahi Deccan",
    sum: "Tall brass and steel processional standards topped with the panja hand or pirs, carried in Muharram mourning processions as portable shrines of Karbala.",
    desc: "The alam is a freestanding metal standard, often two metres tall, carried at the head of Muharram processions in place of the standards of Imam Husayn's army. Its finial is typically the panja, a stylized open right hand, or a composition of crowns, fishes, tulips and calligraphic medallions hammered in brass, steel or gold-washed copper, sometimes inlaid with silver. Deccani workshops in Hyderabad and Bidri-influenced Lucknow produced the richest alams, many kept year-round in imambaras and ashurkhanas as objects of votive devotion, touched and crowned with cloth. On Ashura they are borne aloft through crowds beating chests to drumbeat, glinting above black flags. Museum collections from the V&A to the Salar Jung hold fine examples, and the craft of alam-making continues in hereditary family workshops.",
    col: [{ h: "#8c6d2f", n: "brass gold" }, { h: "#3d4450", n: "gunmetal steel" }, { h: "#7a1f1f", n: "drape red" }, { h: "#14161a", n: "mourning black" }, { h: "#d8cbb0", n: "sandalwood cream" }],
    m: ["brass sheet and wire", "steel armature", "gold-wash (tarkashi)", "silver inlay", "velvet drapery"],
    tx: ["repoussé calligraphy", "cool polished steel", "frayed ceremonial cloth"],
    obj: ["panja hand finial", "fish-and-tulip openwork alam", "imambara alcove stand", "chained mourning drape", "calligraphic medallion"],
    ex: ["Ashurkhana alams of Hyderabad old city", "Lucknow imambara Muharram processions", "V&A and Salar Jung Museum alam collections"],
    inf: ["Bidri metalcraft", "Shia votive material culture"], rel: ["Ta'ziyeh passion play", "Hijazi roshan bay window", "Ottoman mehter band"],
    par: "Islamic metalwork", var: ["panja alam", "Bidri inlaid alam", "crowned fish alam"], cf: ["Khanda sword emblem"],
    src: [{ n: "Wikipedia — Mourning of Muharram", u: "https://en.wikipedia.org/wiki/Mourning_of_Muharram", t: "B" }, { n: "Victoria and Albert Museum", u: "https://www.vam.ac.uk", t: "A" }],
    tg: ["alam", "panja", "muharram", "metalwork", "imambara"], pop: 30, niche: true,
    vd: { shape: "vertical spire of symmetric metalwork", line: "flame and calligraphy contours", composition: "dark procession under one glinting standard", texture: "hammered gold on black velvet", forms: "hands, crowns, tulips, fishes" },
    typ: { display: "Aref Ruqaa for calligraphic cartouches", body: "Amiri", notes: "metal-cut kufi accents on headers" },
    fnt: { display: "Aref Ruqaa", body: "Amiri", notes: "devotional Arabic hierarchy" },
    lit: { quality: "single hard glints in deep shade", direction: "low side sun catching brass", temperature: "warm metal on cold night", shadow: "standards casting spear shadows" },
    pho: { approach: "low angle up the alam silhouette against night sky", grade: "gold highlights crushed into black" },
    fash: { silhouettes: "black flowing layers", garments: "black kurta and chadar", acc: "red armbands, steel chains" },
    env: { places: "imambara courtyards, old-city lanes, river ghats of procession", weather: "monsoon humidity, torch and sodium light" },
    gd: { layout: "tall centred spire on black field", icon: "panja hand emblem" },
    ui: { background: "near-black charcoal", surface: "brass-edged cards", components: "medallion badges, chain dividers", motion: "slow standard-rise reveal" },
    rec: { materials: "brass, steel, velvet, rose petals", lighting: "torchlight and single spotlight", objects: "crowned alam, attar bottles, offerings", music: "mournful noha chants with dhol", scent: "attar, sandalwood, rain on stone" },
    snd: ["rhythmic chest-beating and drum", "clink of chains and finial", "collective lament chant"],
    dna: { mi: 35, og: 85, wc: 5, ns: 20, ad: 10, hf: 10, rr: 65, ps: 60, sh: 70, ql: 35, oc: 30, ds: 70, rs: 20, eu: 35, np: 15 },
    emo: { warm: 40, cold: 45, playful: 5, serious: 95, chaotic: 40, ordered: 65, nostalgic: 60, futuristic: 5, peaceful: 25, ominous: 65 },
  },
  {
    n: "Turkish kahvehane", a: ["Ottoman coffee house", "kıraathane", "Turkish kiraathane"],
    cat: "Interior Design", c: "Social coffeehouse interior", e: "regional_tradition", o: "Ottoman Istanbul (mid-16th century)", g: "Türkiye, Balkans, Levant, Caucasus",
    p: "1550s to present", era: "Ottoman and Republican Türkiye",
    sum: "The neighbourhood Ottoman coffeehouse of low stools, copper cezve and backgammon boards that organised male social life for four centuries.",
    desc: "Kahvehane appeared in Istanbul in the 1550s, quickly spreading through the empire as the first space where commoners could gather over a stimulant drink, prompting repeated Ottoman bans before it became institutional. Interiors are long shallow rooms facing the street: banquettes and low stools, marble-topped tables, nargile pipes, shelves of glasses of tea, and walls of framed pictures from football teams to Mevlana. Coffee is brewed in copper cezve on hot sand, tea served in tulip glasses, and time measured by backgammon, okey tiles and conversation rather than transactions. The kahvehane carried meddah storytellers and shadow-play bookings, seeded the European coffeehouse through Venice and Vienna, and survives as the kıraathane alongside new-wave specialty cafés. UNESCO inscribed Turkish coffee culture in 2013.",
    col: [{ h: "#7a4a2b", n: "coffee ochre" }, { h: "#d9c6a5", n: "tea-glass amber tint" }, { h: "#3f5a52", n: "tile green" }, { h: "#241c14", n: "smoked ceiling brown" }, { h: "#b5763a", n: "copper cezve" }],
    m: ["marble table tops", "bentwood chairs", "copper cezve", "patterned tile wainscot", "nargile glass"],
    tx: ["sand-brewed coffee grind", "worn wooden banquette", "steam-fogged windows"],
    obj: ["tulip tea glass and saucer", "backgammon board", "copper cezve on hot sand", "nargile hose coil", "low wooden stools"],
    ex: ["Pierre Loti Café hillside, Eyüp, Istanbul", "Çorlulu Ali Paşa Medresesi tea garden", "UNESCO ICH listing 2013 (Turkish coffee culture)"],
    inf: ["Ottoman guild street culture", "Viennese and Parisian café lineage"], rel: ["Georgian supra feast", "Viennese Coffeehouse", "Arabic majlis and dallah coffee culture"],
    par: "Café culture", var: ["kıraathane (reading-room style)", "tea garden (çay bahçesi)", "nargile lounge"], cf: ["Arabic majlis and dallah coffee culture"],
    src: [{ n: "Wikipedia — Coffeehouse", u: "https://en.wikipedia.org/wiki/Coffeehouse", t: "B" }, { n: "UNESCO ICH — Turkish coffee culture and tradition", u: "https://ich.unesco.org/en/RL/turkish-coffee-culture-and-tradition-00645", t: "A" }],
    tg: ["coffeehouse", "cezve", "backgammon", "istanbul", "tea"], pop: 46, niche: false,
    vd: { shape: "long shallow street-front room", line: "row of small round tables", composition: "men in profile over boards and glasses", texture: "steam, smoke, marble sheen", forms: "tulip glasses, cezve, low stools" },
    typ: { display: "Fraunces for hand-painted shop signs", body: "Noto Serif", notes: "signwriter caps with tilde flourishes" },
    fnt: { display: "Fraunces", body: "Noto Serif", notes: "vernacular signage meets bookish calm" },
    lit: { quality: "smoky warm tungsten glow", direction: "low lamps along the wall", temperature: "amber heat", shadow: "steam shadows on fogged glass" },
    pho: { approach: "reportage at table height across the room, wide lens", grade: "warm amber with tobacco softness" },
    fash: { silhouettes: "relaxed everyday tailoring", garments: "shirtsleeves, flat caps, cardigans", acc: "prayer beads, caps on hooks" },
    env: { places: "narrow old-town streets, ferry quays, bazaar edges", weather: "Bosphorus damp, winter steam" },
    gd: { layout: "wide table rows with drink close-ups", icon: "cezve and tulip glass pair" },
    ui: { background: "cream with faint tile print", surface: "marble-textured panels", components: "rounded copper buttons, checkered game motifs", motion: "coffee-cream swirl loaders" },
    rec: { materials: "copper, marble, dark wood", lighting: "warm low bulbs over tables", objects: "cezve set, okey tiles, framed posters", music: "arabesk and classical Turkish fasil", scent: "roasted coffee, apple tobacco, tea" },
    snd: ["dice rattling in the backgammon cup", "spoon against glass saucer", "low TV football commentary"],
    dna: { mi: 50, og: 70, wc: 20, ns: 30, ad: 15, hf: 15, rr: 50, ps: 65, sh: 45, ql: 35, oc: 30, ds: 60, rs: 35, eu: 50, np: 30 },
    emo: { warm: 85, cold: 15, playful: 55, serious: 40, chaotic: 35, ordered: 55, nostalgic: 85, futuristic: 15, peaceful: 65, ominous: 10 },
  },
  {
    n: "Turkish hammam", a: ["hammam bath", "Ottoman bathhouse", "göbek taşı bath"],
    cat: "Architectural Style", c: "Ottoman bath architecture", e: "regional_tradition", o: "Anatolia and Ottoman Istanbul", g: "Türkiye, Balkans, Levant, North Africa",
    p: "14th-20th century", era: "Ottoman classical period",
    sum: "Dome-lit steam bathhouses sequenced from cold room to hot marble slab, where scrubbing, foam and social ritual renew body and neighbourhood.",
    desc: "The Ottoman hammam refined Roman-Byzantine bathing into a triple sequence: the camekân changing hall under a central dome, the warm sogukluk, and the hot hararet crowned by pierced glass domes and eyvan alcoves around a raised central göbek taşı slab. Sunlight falls through bullseye glass domes in shifting spots across the marble while steam softens bathers for the tellak's kese scrub and foam massage, followed by cold pours and lounging on the camekân divans with sherbet or tea. Classical architects including Sinan built landmark baths such as the Haseki Hürrem Sultan Hamamı beside Hagia Sophia, and gendered double or sequential timetables made the hammam a centre of neighbourhood and bridal ritual life. Many historic hammams now operate as restored spas, museums of light and steam.",
    col: [{ h: "#e8ded0", n: "warm marble white" }, { h: "#c9b28f", n: "honey stone" }, { h: "#7fa3a1", n: "dome glass teal" }, { h: "#9a6b45", n: "steam shadow umber" }, { h: "#b23a2e", n: "pestemal red" }],
    m: ["veined marble slabs", "cut-stone vaulting", "bullseye glass domes", "brass taps and bowls", "woven pestemal cloth"],
    tx: ["wet slick marble sheen", "steam condensation", "dome-light spots on stone"],
    obj: ["central göbek taşı slab", "pierced dome skylights", "copper bath bowls", "marble basin niches", "foam scrub mitts"],
    ex: ["Haseki Hürrem Sultan Hamamı, Istanbul", "Çemberlitaş Hamamı (Sinan, 1584)", "Bey Hamam, Thessaloniki"],
    inf: ["Roman-Byzantine bath lineage", "Sinan's classical dome engineering"], rel: ["Turkish kahvehane", "Armenian tuff vernacular", "Gulf barjeel wind tower"],
    par: "Islamic architecture", var: ["double-bath (çifte hamam)", "single neighbourhood hamam", "palace bath"], cf: ["Roman thermae", "Moroccan hammam"],
    src: [{ n: "Wikipedia — Hammam", u: "https://en.wikipedia.org/wiki/Hammam", t: "B" }, { n: "Google Arts & Culture", u: "https://artsandculture.google.com", t: "A" }],
    tg: ["hammam", "steam", "marble", "dome", "bathhouse"], pop: 44, niche: false,
    vd: { shape: "cluster of squat domes with glass eyes", line: "arcaded niches around the hot room", composition: "light shafts converging on the central slab", texture: "steamed marble sheen", forms: "domes, eyvan alcoves, basins" },
    typ: { display: "Cormorant Garamond for spa-style headings", body: "Noto Naskh Arabic", notes: "quiet inscriptions over doorways" },
    fnt: { display: "Cormorant Garamond", body: "Noto Naskh Arabic", notes: "soft classical serif with Arabic body" },
    lit: { quality: "diffused silver light through dome eyes", direction: "top-down spots that drift with the sun", temperature: "white steam over warm stone", shadow: "soft pooled shadows in niches" },
    pho: { approach: "long exposure of dome light spots and steam", grade: "pale marble whites with honey warmth" },
    fash: { silhouettes: "wrapped cloth", garments: "pestemal wraps, wooden clogs (takunya)", acc: "brass bowls, kese mitts" },
    env: { places: "bath domes behind bazaar streets, fountains, neighbourhood squares", weather: "dense warm steam, tiled coolness" },
    gd: { layout: "domed plan diagram as skeleton", icon: "pierced dome eye" },
    ui: { background: "steamed ivory", surface: "marble cards with dome-cut corners", components: "circular dome buttons, steam-fade toggles", motion: "condensation dissolve" },
    rec: { materials: "marble, brass, glass dome", lighting: "star-spots of daylight in steam", objects: "bath bowl, pestemal, sherbet glasses", music: "soft ney and water trickle", scent: "olive soap, steam, rose" },
    snd: ["water poured from copper bowls", "echoed voices under domes", "soft scrub rasp on marble"],
    dna: { mi: 55, og: 65, wc: 20, ns: 30, ad: 20, hf: 20, rr: 45, ps: 55, sh: 40, ql: 40, oc: 30, ds: 55, rs: 40, eu: 55, np: 30 },
    emo: { warm: 80, cold: 20, playful: 30, serious: 45, chaotic: 15, ordered: 70, nostalgic: 70, futuristic: 15, peaceful: 85, ominous: 5 },
  },
  {
    n: "Nowruz haft-sin table", a: ["haft seen", "haft-sīn spread", "Nowruz sofreh"],
    cat: "Regional & Cultural Tradition", c: "New Year table setting", e: "regional_tradition", o: "Iran (pre-Islamic roots)", g: "Iran, Afghanistan, Tajikistan, Kurdish and diaspora communities",
    p: "ancient roots; codified by medieval era", era: "Safavid to contemporary Iran",
    sum: "The Nowruz spread of seven 's' items — sabzeh sprouts, senjed, sir, samanu, sumac, seer-flavoured vinegar and painted eggs, goldfish and hyacinth — that stages the Persian new year at the spring equinox.",
    desc: "Haft-sin is the ceremonial sofreh laid for Nowruz, the new year at the vernal equinox, arranged from seven symbolic items each beginning with the letter sin: sabzeh lentil or wheat sprouts for rebirth, samanu wheat pudding for affluence, senjed lotus fruit for love, sir garlic, seeb apples, somaq sumac and serkeh vinegar. Around them gather painted eggs, a mirror and candles, a bowl with goldfish, hyacinth (sonbol), a book of Hafez or the Quran, and coins. Families dress in new clothes, sit before the sofreh at the exact moment of the equinox, exchange gifts and segue into thirteen days of visits, ending with Sizdah Bedar picnics where the sabzeh is cast into running water. The table is the single most recognizable material expression of Persian domestic culture and travels intact through every diaspora kitchen.",
    col: [{ h: "#4f7d3a", n: "sabzeh green" }, { h: "#d4af37", n: "samanu gold" }, { h: "#c1272d", n: "egg dye red" }, { h: "#e9e2d0", n: "sofreh white cloth" }, { h: "#b257a1", n: "hyacinth violet" }],
    m: ["sprouted wheat greens", "mirror and candles", "painted eggs", "crystal sweet bowls", "patterned sofreh cloth"],
    tx: ["glossy sprout blades", "mirror glare", "silk cloth weave"],
    obj: ["seven sin dishes", "goldfish bowl", "candle-mirror pair", "Hafez poetry book", "hyacinth vase"],
    ex: ["Family haft-sin spreads at Tehran Nowruz", "Sizdah Bedar park picnics, 13 Farvardin", "UNESCO ICH multination Nowruz listing (2016)"],
    inf: ["Zoroastrian spring festival", "Safavid court Nowruz ceremonial"], rel: ["Kurdish Newroz fire festival", "Georgian supra feast", "Ta'ziyeh passion play"],
    par: "Nowruz new year tradition", var: ["haft-shin (Kurdish variant)", "haft-mewa (Afghan seven fruits)"], cf: ["Kurdish Newroz fire festival"],
    src: [{ n: "Wikipedia — Haft-sin", u: "https://en.wikipedia.org/wiki/Haft-sin", t: "B" }, { n: "UNESCO ICH — Nowruz", u: "https://ich.unesco.org/en/RL/nowruz-00282", t: "A" }],
    tg: ["nowruz", "haft-sin", "spring", "sofreh", "new year"], pop: 47, niche: false,
    vd: { shape: "symmetric flat spread facing the sitter", line: "arc of dishes around the mirror", composition: "green centre, sweets flanks, eggs scattered", texture: "fresh sprouts, gold glints, dyed shells", forms: "bowls, candles, sprout beds" },
    typ: { display: "Lalezar for Nowruz greeting cards", body: "Vazirmatn", notes: "floral border frames around type" },
    fnt: { display: "Lalezar", body: "Vazirmatn", notes: "festive Persian display with clean body" },
    lit: { quality: "bright even spring daylight", direction: "window light across the cloth", temperature: "clear fresh neutral-warm", shadow: "soft candle accents only" },
    pho: { approach: "top-down flat lay of the full sofreh, then candle-level detail", grade: "luminous pastels on white" },
    fash: { silhouettes: "new festive clothes", garments: "colourful women's dresses, tailored suits", acc: "gold coins, eglantine and hyacinth corsages" },
    env: { places: "carpeted living rooms, blooming gardens, Sizdah Bedar riverbanks", weather: "mild equinox sun, budding trees" },
    gd: { layout: "radial menu around mirror centrepiece", icon: "sprout-and-fish emblem" },
    ui: { background: "soft white with green sprout motifs", surface: "glass bowls as card containers", components: "candle pill buttons, egg-dot checkboxes", motion: "sprout growth progress bars" },
    rec: { materials: "wheatgrass, crystal, gold leaf", lighting: "candle-and-window mix", objects: "painted eggs, sweet dishes, poetry book", music: "setar and daf Nowruz songs", scent: "hyacinth, fresh wheat, vinegar and sweets" },
    snd: ["goldfish stirring water", "spoons struck for the equinox moment", "family chatter and doorbells of visitors"],
    dna: { mi: 55, og: 75, wc: 25, ns: 35, ad: 20, hf: 25, rr: 55, ps: 60, sh: 35, ql: 45, oc: 30, ds: 65, rs: 45, eu: 60, np: 35 },
    emo: { warm: 90, cold: 10, playful: 60, serious: 35, chaotic: 25, ordered: 70, nostalgic: 85, futuristic: 25, peaceful: 80, ominous: 5 },
  },
  {
    n: "Kurdish Newroz fire festival", a: ["Newroz", "Kurdish new year", "Kawa the blacksmith legend"],
    cat: "Regional & Cultural Tradition", c: "Spring fire festival", e: "regional_tradition", o: "Zagros and Taurus mountain Kurdistan", g: "Kurdish regions of Türkiye, Iraq, Iran, Syria; diaspora",
    p: "ancient roots; politicised 20th century", era: "20th-21st century Kurdistan",
    sum: "Kurdish spring new year celebrated by leaping bonfires on ridgelines, wearing red-green-yellow dress and retelling the blacksmith Kawa's defeat of the tyrant Zahhak.",
    desc: "Newroz, the Kurdish celebration of the spring equinox on 21 March, centres on bonfires lit at dusk on hillsides and jumped over for purification and luck. The founding story is the legend of Kawa the blacksmith, who slew the serpent-tyrant Zahhak and fired a beacon from the mountain to announce freedom — so the flame reads as liberation, and in modern times Newroz gatherings have carried strong political meaning, from Akre's torch-lit displays in Iraqi Kurdistan to mass celebrations in Amed (Diyarbakır). Dress is vivid: embroidered Kurdish vests and headscarves in red, green and yellow, with govend circle dances, zirne horns and def drums. Tables hold saffron rice, dolma and coloured eggs; kilim weavers mark Newroz motifs in flatweave. The festival is now widely institutionalised as a public holiday across Kurdish regions.",
    col: [{ h: "#c8321f", n: "bonfire red" }, { h: "#e8a020", n: "flame orange" }, { h: "#2f6d3f", n: "mountain green" }, { h: "#f2d13d", n: "sun yellow" }, { h: "#3a3f4a", n: "ridge slate" }],
    m: ["dried brush and pyre wood", "embroidered festival vests", "def frame drums", "flatweave kilim banners"],
    tx: ["spark-filled night air", "coarse embroidery threads", "heat shimmer over wool"],
    obj: ["hilltop bonfire ring", "Kawa hammer emblem", "red-green-yellow flags", "dance line of linked hands", "coloured egg baskets"],
    ex: ["Newroz fire celebrations in Akre, Iraqi Kurdistan", "Mass Newroz gathering in Amed (Diyarbakır)", "Newroz as public holiday across Iraqi Kurdistan"],
    inf: ["Zoroastrian fire symbolism", "20th-century Kurdish national movement"], rel: ["Nowruz haft-sin table", "Circassian dress tradition", "Mevlevi sema whirling ceremony"],
    par: "Nowruz new year tradition", var: ["Akre torch parade", "Amed mass gathering", "village bonfire night"], cf: ["Persian Nowruz"],
    src: [{ n: "Wikipedia — Newroz as celebrated by Kurds", u: "https://en.wikipedia.org/wiki/Newroz_as_celebrated_by_Kurds", t: "B" }, { n: "Encyclopædia Britannica — Nowruz", u: "https://www.britannica.com/topic/Nowruz", t: "A" }],
    tg: ["newroz", "bonfire", "kurdish", "spring", "dance"], pop: 43, niche: false,
    vd: { shape: "circle of leaping figures against flame", line: "sparks rising along ridgelines", composition: "fire as central sun of the night scene", texture: "heat glow, wool texture, smoke", forms: "flames, flags, dance arcs" },
    typ: { display: "Reem Kufi for festival posters", body: "Noto Sans Arabic", notes: "Latin support for bilingual posters" },
    fnt: { display: "Reem Kufi", body: "Noto Sans Arabic", notes: "geometric warmth for bilingual text" },
    lit: { quality: "single-source firelight at night", direction: "radial from the pyre", temperature: "hot oranges over cold blue night", shadow: "long dancing shadows down the slope" },
    pho: { approach: "silhouette dancers against full flame, slow shutter for sparks", grade: "high-contrast ember palette" },
    fash: { silhouettes: "fitted embroidered vests over full skirts", garments: "Kurdish festival dress, headscarves, cummerbund sashes", acc: "coin jewellery, flower crowns" },
    env: { places: "mountain ridges, village squares, stadium gatherings", weather: "cold clear March night, thaw wind" },
    gd: { layout: "flame-centred poster grid", icon: "spark and hammer motif" },
    ui: { background: "night blue with ember particles", surface: "warm gradient panels", components: "flame-shaped buttons, flag-stripe accents", motion: "spark drift upward" },
    rec: { materials: "wool, ember wood, iron", lighting: "bonfire glow and torches", objects: "hammers, drums, embroidered banners", music: "zirne horns, def drums, dance lines", scent: "woodsmoke, mountain thyme, roasting meat" },
    snd: ["crack and rush of bonfires", "zirne and def dance rhythm", "crowd cheers echoing off ridges"],
    dna: { mi: 45, og: 80, wc: 15, ns: 30, ad: 20, hf: 20, rr: 60, ps: 60, sh: 55, ql: 35, oc: 35, ds: 70, rs: 40, eu: 45, np: 25 },
    emo: { warm: 90, cold: 25, playful: 70, serious: 50, chaotic: 55, ordered: 45, nostalgic: 70, futuristic: 30, peaceful: 55, ominous: 20 },
  },
  {
    n: "Mevlevi sema whirling ceremony", a: ["Sufi whirling", "whirling dervishes", "Mevlevi ayin"],
    cat: "Music & Sonic Culture", c: "Sufi ritual music and dance", e: "regional_tradition", o: "Konya, Anatolia (13th century)", g: "Türkiye (Konya, Istanbul), Balkans, Syria",
    p: "founded 13th century; banned 1925; revived 1950s", era: "Seljuk Anatolia to Republican Türkiye",
    sum: "The Mevlevi Sufi ceremony in which semazens whirl in white flared skirts to ney flute, reed and drum as a moving meditation on union with the divine.",
    desc: "The sema is the Mevlevi order's whirling liturgy, founded by followers of the mystic poet Rumi in Konya, whose mausoleum remains the ceremony's heart. Semazens in white full-skirted tanbur-cloaks and tall felt sikke hats whirl in a choreographed circuit — arms open right palm up to receive, left palm down to bestow — while a flute, kudüm drum and rebab play the ayin suite and singers chant verses of Rumi. The ceremony proceeds through a greeting, the removal of the black cloak as burial shroud, four salams or whirl phases, and closing prayers, all under the sheikh's circulation around the hall. Banned with the dervish lodges in 1925, the sema survived as heritage and was proclaimed a UNESCO Masterpiece in 2005; Konya's December Seb-i Arus festival draws thousands to watch hundreds whirl.",
    col: [{ h: "#efe9dc", n: "whirling skirt white" }, { h: "#2b2620", n: "cloak black" }, { h: "#9c7b4d", n: "felt camel" }, { h: "#4b6b45", n: "reed green" }, { h: "#b89a5a", n: "lamp gold" }],
    m: ["wool sikke felt hats", "full camlet skirts", "ney reed flute", "kudüm drums", "red sheepskin post"]
    ,
    tx: ["motion-blurred skirt hem", "soft felt nap", "candlelit wood floor"],
    obj: ["flared white skirt in spin", "tall sikke hat", "ney flute", "red post medallion", "black cloak (hırka) fold"],
    ex: ["Seb-i Arus ceremonies, Konya (December)", "Galata Mevlevi Lodge Museum, Istanbul", "UNESCO 2005 proclamation of the Mevlevi Sema Ceremony"],
    inf: ["Rumi's mystical poetry", "Ottoman lodge (tekke) music"], rel: ["Ottoman mehter band", "Azerbaijani mugham", "Armenian duduk music"],
    par: "Sufi devotional practice", var: ["Konya lodge sema", "Istanbul Galata sema", "staged folkloric whirling"], cf: ["Sufi dhikr circles"],
    src: [{ n: "Wikipedia — Sufi whirling", u: "https://en.wikipedia.org/wiki/Sufi_whirling", t: "B" }, { n: "UNESCO ICH — Mevlevi Sema Ceremony", u: "https://ich.unesco.org/en/RL/mevlevi-sema-ceremony-00114", t: "A" }],
    tg: ["sema", "whirling", "rumi", "ney", "konya"], pop: 45, niche: false,
    vd: { shape: "cone of spinning white cloth", line: "circular trajectories of the dance floor", composition: "single whirl centre with seated musicians arc", texture: "flowing cloth blur, polished floor", forms: "skirts, hats, reed flute" },
    typ: { display: "Amiri for Rumi verse excerpts", body: "Noto Naskh Arabic", notes: "italic Latin for transliteration" },
    fnt: { display: "Amiri", body: "Noto Naskh Arabic", notes: "poetic calligraphic display, serene body" },
    lit: { quality: "dim lodge light with warm pools", direction: "overhead onto the circling floor", temperature: "candle warm, contemplative", shadow: "rotating skirt shadows" },
    pho: { approach: "slow shutter to keep faces sharp and skirts blurred", grade: "sepia-warm minimalism" },
    fash: { silhouettes: "flared ceremonial", garments: "white henna-skirt, black cloak, camel tennure", acc: "felt sikke, red post" },
    env: { places: "wood-floored tekke halls, marble dervish cells, Konya shrine courts", weather: "still candle-warmed air" },
    gd: { layout: "single centred whirl on calm field", icon: "spiral and reed motif" },
    ui: { background: "warm off-white", surface: "cream cards with spiral corners", components: "circular spin loaders, felt-texture chips", motion: "easing rotation as primary transition" },
    rec: { materials: "felt, wool, reed, rose petals", lighting: "candle circles in a dim hall", objects: "ney, kudüm, opened cloak", music: "ayin suite with ney, kudüm, chant", scent: "rose attar, wool, candle wax" },
    snd: ["breathy ney melody", "deep kudüm pulse", "soft swish of spinning wool"],
    dna: { mi: 60, og: 75, wc: 15, ns: 30, ad: 15, hf: 20, rr: 50, ps: 50, sh: 45, ql: 45, oc: 25, ds: 60, rs: 45, eu: 55, np: 30 },
    emo: { warm: 65, cold: 25, playful: 15, serious: 80, chaotic: 10, ordered: 85, nostalgic: 65, futuristic: 20, peaceful: 90, ominous: 10 },
  },
  {
    n: "Ottoman mehter band", a: ["mehteran", "Janissary band", "mehter music"],
    cat: "Music & Sonic Culture", c: "Military processional music", e: "historical", o: "Ottoman Anatolia (14th century)", g: "Ottoman Empire; revived in Istanbul, Türkiye",
    p: "14th century-1826; revival 1914-present", era: "Ottoman classical period",
    sum: "The world's oldest military band tradition — zurna shriek, kös giant drums and crescent standard-bearers marching the Ottoman army and terrifying European composers into imitation.",
    desc: "The mehterhâne was the Ottoman army's martial band, playing zurna shawms, boru trumpets, kös kettle-drums, davul, cymbals and triangles while halberd-bearing çavuşes marched with banners and the crescent alem standard, performing the gezik coordination step of striking right foot, knee and elbow. Its function was psychological as much as musical: thunderous tuning collisions and slow majestic peşrev marches announced siege lines and sultans, while European observers copied the sound into 'Turkish' style — Mozart's Rondo alla Turca and Beethoven's Turkish march descend from mehter's battery. Abolished with the Janissaries in 1826, the tradition was revived in 1914 and now performs in historical costume at the Istanbul Military Museum and state ceremonies, maintaining a repertoire of peşrev and mars form with unison singing in octaves.",
    col: [{ h: "#a01f24", n: "janissary red" }, { h: "#caa53d", n: "standard gold" }, { h: "#2d4a3a", n: "robe green" }, { h: "#e6d8bd", n: "turban white" }, { h: "#4a4a52", n: "halberd steel" }],
    m: ["brass zurna shawms", "calfskin kös drums", "crescent alem standards", "felt caps with sleeve", "cymbal bronze"],
    tx: ["blazing brass bell mouths", "drum skin tension", "gold thread on wool robes"],
    obj: ["giant kös kettle drum", "crescent-tipped alem", "zurna and boru horns", "twin cymbals raised", "horse-drawn drum cart"],
    ex: ["Mehter troupe at Istanbul Military Museum daily shows", "Mehteran performance at state ceremonies, Ankara", "Recorded peşrev repertoire by the Istanbul Historical Music ensemble"],
    inf: ["Central Asian military music", "European 'Turkish style' in classical music"], rel: ["Mevlevi sema whirling ceremony", "Muharram alam processional standards", "Georgian supra feast"],
    par: "Ottoman military culture", var: ["campaign mehterhâne", "ceremonial modern mehter"], cf: ["Austrian Turkish Style marches"],
    src: [{ n: "Wikipedia — Ottoman military band", u: "https://en.wikipedia.org/wiki/Ottoman_military_band", t: "B" }, { n: "Encyclopædia Britannica — Janissary music", u: "https://www.britannica.com/art/Janissary-music", t: "A" }],
    tg: ["mehter", "janissary", "military band", "zurna", "ottoman"], pop: 38, niche: false,
    vd: { shape: "phalanx of musicians and standards", line: "diagonal march of banners", composition: "drums at the rear, horns forward", texture: "brass glare, drum skin, gold thread", forms: "horns, drums, crescent poles" },
    typ: { display: "Reem Kufi for mars title calligraphy", body: "Cairo", notes: "tughra-inspired flourishes sparingly" },
    fnt: { display: "Reem Kufi", body: "Cairo", notes: "imperial geometric display" },
    lit: { quality: "outdoor blaze with dust", direction: "low sun behind marching column", temperature: "hot brass gold", shadow: "long spears and standards" },
    pho: { approach: "track alongside the column at drum-cart height", grade: "saturated red-gold parade tones" },
    fash: { silhouettes: "robed uniform", garments: "börk felt caps with hanging sleeve, kaftans, boots", acc: "halberds, mustachioed moustache combs" },
    env: { places: "parade grounds, museum courtyards, fortress walls", weather: "dry steppe wind, dust" },
    gd: { layout: "march-diagonal with drum anchors", icon: "crescent alem emblem" },
    ui: { background: "deep parade red", surface: "gold-ruled panels", components: "banner ribbons, drum-skin toggles", motion: "march-step slide" },
    rec: { materials: "brass, calfskin, wool, steel", lighting: "hard sun with dust haze", objects: "kös drums, alem standard, halberd", music: "mehter peşrev with octave chant", scent: "leather, horse, gun oil" },
    snd: ["zurna octave shriek", "deep kös boom", "cymbal crashes in slow majesty"],
    dna: { mi: 45, og: 85, wc: 10, ns: 20, ad: 15, hf: 15, rr: 65, ps: 65, sh: 60, ql: 30, oc: 30, ds: 70, rs: 25, eu: 50, np: 20 },
    emo: { warm: 60, cold: 30, playful: 20, serious: 85, chaotic: 30, ordered: 80, nostalgic: 70, futuristic: 15, peaceful: 25, ominous: 45 },
  },
  {
    n: "Çanakkale ceramics", a: ["Canakkale pottery", "Çanakkale ware", "folk ceramics of the Dardanelles"],
    cat: "Textile & Craft", c: "Ottoman folk ceramics", e: "regional_tradition", o: "Çanakkale, Dardanelles coast (18th century)", g: "Çanakkale, Türkiye; collections worldwide",
    p: "18th-early 20th century", era: "late Ottoman era",
    sum: "Ottoman folk pottery from the Dardanelles famous for Slip-decorated mosque lamps, polychrome ships, temples and floral panels on cream ground.",
    desc: "Çanakkale ware was the last great Ottoman folk ceramic, produced in workshops by the Dardanelles from the eighteenth century until the 1920s population exchange. Made on a fast wheel and covered in white slip, pieces were painted in runny polychrome — green, rust, cobalt and ochre — with naive subjects rare in Islamic ceramics: sailing ships, mosques with domes and minarets, temples, horsemen, and even the Hagia Sophia, alongside tulip and carnation borders. The signature forms are mosque lamps with pierced necks, wall plaques, huge flowerpots, sugar bowls with animal finials and ewers, and the iconic double-handled testi. Neither court İznik refinement nor European porcelain, its charm is deliberate folk eccentricity; today the Sadberk Hanım and Benaki museums hold major collections and the style anchors Çanakkale's souvenir identity.",
    col: [{ h: "#efe4cd", n: "cream slip ground" }, { h: "#3f6d4e", n: "copper green" }, { h: "#9c3b25", n: "rust red" }, { h: "#33528c", n: "cobalt blue" }, { h: "#d09a3c", n: "ochre ochre" }],
    m: ["red earthenware clay", "white slip coat", "lead glaze", "brush pigments"],
    tx: ["runny slip edges", "glaze crackle", "naive brush wobble"],
    obj: ["pierced mosque lamp", "ship-decorated plaque", "animal-finial sugar bowl", "double-handled testi jug", "giant mosque flowerpot"],
    ex: ["Sadberk Hanım Museum Çanakkale collection, Istanbul", "Benaki Museum Islamic ceramics, Athens", "Çanakkale city folk pottery displays"],
    inf: ["İznik court ceramics", "Aegean port trade imagery"], rel: ["Çini tiles", "Azerbaijani shebeke lattice", "Armenian tuff vernacular"],
    par: "Ottoman decorative arts", var: ["mosque lamps", "wall plaques", "temple ware"], cf: ["İznik pottery"],
    src: [{ n: "Wikipedia — Çanakkale", u: "https://en.wikipedia.org/wiki/%C3%87anakkale", t: "B" }, { n: "Sadberk Hanım Museum", u: "https://www.sadberkhanimmuzesi.org.tr", t: "A" }],
    tg: ["folk pottery", "slipware", "ottoman", "dardanelles", "mosque lamp"], pop: 28, niche: true,
    vd: { shape: "bulbous pots with naive painted panels", line: "wobbly hand-drawn borders", composition: "single proud subject centred on cream", texture: "glaze crackle over slip", forms: "lamps, jugs, plaques" },
    typ: { display: "Lalezar for hand-lettered labels", body: "Noto Serif", notes: "museum-caption simplicity" },
    fnt: { display: "Lalezar", body: "Noto Serif", notes: "folk poster energy, quiet captions" },
    lit: { quality: "soft museum spotlights", direction: "gentle top light", temperature: "warm neutral", shadow: "tight pot shadows on plinth" },
    pho: { approach: "single object on linen with raking side light", grade: "warm ceramic neutrals" },
    fash: { silhouettes: "workaday aprons", garments: "potter's apron, rolled sleeves", acc: "clay-stained hands, simple headscarves" },
    env: { places: "wheel workshops, portside kiln yards, museum vitrines", weather: "Aegean sea wind, kiln heat" },
    gd: { layout: "object-catalogue grid on cream", icon: "ship and tulip border" },
    ui: { background: "cream slip tone", surface: "crackle-glaze cards", components: "brush-stroke buttons, plaque frames", motion: "slip-pour wipe" },
    rec: { materials: "clay, slip, glaze", lighting: "raking window light on glaze", objects: "wheel, sponge brushes, drying lamps", music: "thrum of the wheel, market chatter", scent: "wet clay, woodsmoke, sea salt" },
    snd: ["wheel hum and water slap", "brush on biscuit ware", "gulls over the harbour kilns"],
    dna: { mi: 50, og: 70, wc: 20, ns: 35, ad: 15, hf: 15, rr: 55, ps: 55, sh: 40, ql: 40, oc: 30, ds: 65, rs: 40, eu: 55, np: 25 },
    emo: { warm: 75, cold: 15, playful: 65, serious: 30, chaotic: 35, ordered: 55, nostalgic: 85, futuristic: 10, peaceful: 65, ominous: 5 },
  },
  {
    n: "Cappadocia rock-cut settlements", a: ["Göreme cave dwellings", "fairy chimney troglodyte towns", "Cappadocia cave architecture"],
    cat: "Architectural Style", c: "Troglodyte rock-cut architecture", e: "regional_tradition", o: "Byzantine Cappadocia (Anatolia)", g: "Nevşehir and Kayseri provinces, Türkiye",
    p: "4th century-20th century", era: "Byzantine to Ottoman Anatolia",
    sum: "Whole towns carved into volcanic tuff — dwellings, dovecotes, pigeon lofts and painted churches hollowed from Cappadocia's fairy chimneys and valleys.",
    desc: "In Cappadocia the soft volcanic tuff of eroded 'fairy chimney' cones could be cut with hand tools faster than it could be built with, so communities hollowed houses, stables, dovecotes, monasteries and entire underground refuges directly into the rock. Byzantine monastic communities carved rock churches in the Göreme valley whose vaults carry some of the finest 10th-12th century fresco cycles, including the Karanlık (Dark) Church; defensive multi-level refuges like Derinkuyu held thousands of people with ventilation shafts, wells and rolling stone doors. Vernacular dwellings continued the technique into the 20th century, dovetailing carved rooms with courtyards and pigeon houses whose droppings fertilised vineyards. UNESCO inscribed Göreme National Park and the Rock Sites of Cappadocia in 1985, and cave hotels now inhabit the same volumes.",
    col: [{ h: "#d8c3a0", n: "pale tuff cream" }, { h: "#b98d5f", n: "sunlit cone ochre" }, { h: "#8a5a3c", n: "cave interior brown" }, { h: "#7f9bb3", n: "highland sky" }, { h: "#c46a4a", n: "fresco terracotta" }],
    m: ["volcanic tuff", "hand-carved vaults", "plaster and fresco secco", "dovecote niches"],
    tx: ["wind-eroded cone surface", "chisel scallops in vaults", "dust-softened fresco pigment"],
    obj: ["fairy chimney dwelling", "rock-cut church nave", "rolling stone door", "pigeon loft facade", "underground ventilation shaft"],
    ex: ["Karanlık (Dark) Church frescoes, Göreme Open Air Museum", "Derinkuyu underground city", "Uçhisar rock-cut castle dwellings"],
    inf: ["Byzantine monasticism", "volcanic tuff building culture"], rel: ["Armenian tuff vernacular", "Safranbolu Ottoman timber houses", "Georgian qvevri winemaking"],
    par: "Troglodyte architecture", var: ["Göreme monastery complexes", "Derinkuyu-type underground cities", "village pigeon-house valleys"], cf: ["Armenian tuff vernacular"],
    src: [{ n: "Wikipedia — Cappadocia", u: "https://en.wikipedia.org/wiki/Cappadocia", t: "B" }, { n: "UNESCO — Göreme National Park and the Rock Sites of Cappadocia", u: "https://whc.unesco.org/en/list/357", t: "A" }],
    tg: ["cave city", "tuff", "byzantine", "frescoes", "fairy chimneys"], pop: 49, niche: false,
    vd: { shape: "clusters of eroded cones with punched openings", line: "organic contour lines of valleys", composition: "horizon of chimneys, carved cross-sections revealed", texture: "gritty tuff, soot-dark interiors", forms: "arches, niches, dovecote grids" },
    typ: { display: "Cormorant Garamond for site titles", body: "Noto Sans", notes: "archaeological caption clarity" },
    fnt: { display: "Cormorant Garamond", body: "Noto Sans", notes: "classical serif over dust tones" },
    lit: { quality: "raking golden-hour light on cones", direction: "low across valley walls", temperature: "hot outside, cool cave dusk", shadow: "deep chimney undercuts" },
    pho: { approach: "balloon-height or ridge panoramas at dawn, interior flash for churches", grade: "rosy tuff with deep shadow detail" },
    fash: { silhouettes: "rural practical layers", garments: "shawls, waistcoats, work boots", acc: "copper pots, woven satchels" },
    env: { places: "valley trails, cave courtyards, pigeon-loft cliffs", weather: "harsh steppe sun, cold nights, dust" },
    gd: { layout: "valley cross-section storyboard", icon: "chimney-with-door motif" },
    ui: { background: "tuff cream", surface: "carved-arch card frames", components: "niche slots, stone-roll toggles", motion: "cave-mouth fade inward" },
    rec: { materials: "tuff, plaster, pigeon-guano patina", lighting: "dawn raking light, candle interiors", objects: "clay amphorae, oil lamps, loom fragments", music: "ney drone and valley wind", scent: "dry dust, candle soot, wild herbs" },
    snd: ["pigeon wings in the lofts", "wind over chimney mouths", "distant call to prayer across valleys"],
    dna: { mi: 55, og: 90, wc: 10, ns: 25, ad: 20, hf: 20, rr: 60, ps: 60, sh: 50, ql: 35, oc: 35, ds: 75, rs: 30, eu: 50, np: 25 },
    emo: { warm: 70, cold: 25, playful: 35, serious: 60, chaotic: 20, ordered: 60, nostalgic: 75, futuristic: 20, peaceful: 70, ominous: 30 },
  },
  {
    n: "Safranbolu Ottoman timber houses", a: ["Safranbolu konak", "Ottoman townhouse", "Safranbolu historic houses"],
    cat: "Architectural Style", c: "Ottoman timber townhouse", e: "regional_tradition", o: "Safranbolu, Anatolia", g: "Safranbolu, Karabük Province, Türkiye",
    p: "17th-19th century", era: "Ottoman caravan-trade era",
    sum: "Three-storey timber-frame mansions with jettied cumbas, tiled hipped roofs and hidden inner courtyards, preserved whole in a caravan-stop Ottoman town.",
    desc: "Safranbolu prospered as a caravan station on the saffron and coffee route between Istanbul and the Black Sea, and its merchant families raised hundreds of timber-framed konak houses that survive as an intact Ottoman townscape. Houses rise over stone bases into jettied upper floors with projecting cumbas enclosed in lattice sashes, hipped roofs of Turkish tile, and plans divided into the winter harem and summer selamlık wings around inner courts with cisterns and ivy. Interiors show built-in cupboards, ceilings of painted timber and iplik sofas; plumbing brought water to rooms, a luxury of the era. The town's guild bazaar, caravansaray, hamam and 200-odd monuments round out the fabric, and UNESCO inscribed the City of Safranbolu in 1994 as a benchmark of Ottoman domestic architecture, with conservation rules still binding the streets.",
    col: [{ h: "#8a5a38", n: "timber frame brown" }, { h: "#e9dcc3", n: "bagdadi plaster white" }, { h: "#a8412f", n: "tile roof red" }, { h: "#5c6b53", n: "ivy courtyard green" }, { h: "#3f3a33", n: "shutter charcoal" }],
    m: ["timber frame (hımış)", "bagdadi lath plaster", "Turkish roof tiles", "lattice sash windows", "cut stone base"],
    tx: ["sun-bleached plaster", "grain-worn wood sills", "cool dim courtyard air"],
    obj: ["jettying cumba bay", "lattice shuttered sash", "inner courtyard cistern", "painted timber ceiling", "stone-paved street runnel"],
    ex: ["Kaymakamlar House Museum, Safranbolu", "Cinci Han caravansaray", "UNESCO 1994 inscription of Safranbolu"],
    inf: ["Ottoman guild-town planning", "Anatolian timber framing"], rel: ["Turkish hammam", "Tbilisi carved wooden balconies", "Hijazi roshan bay window"],
    par: "Ottoman domestic architecture", var: ["merchant konak", "ashraf (summer) houses", "Black Sea variant"], cf: ["Tbilisi carved wooden balconies"],
    src: [{ n: "Wikipedia — Safranbolu", u: "https://en.wikipedia.org/wiki/Safranbolu", t: "B" }, { n: "UNESCO — City of Safranbolu", u: "https://whc.unesco.org/en/list/614", t: "A" }],
    tg: ["ottoman houses", "timber frame", "konak", "safranbolu", "heritage town"], pop: 37, niche: false,
    vd: { shape: "tall jettied boxes stepping over cobbles", line: "horizontal eaves against vertical lattices", composition: "canyon street of overhanging bays", texture: "plaster flatness with timber grid", forms: "cumbas, hipped roofs, courtyards" },
    typ: { display: "Playfair Display for house-museum plaques", body: "Noto Serif", notes: "museum-plate restraint" },
    fnt: { display: "Playfair Display", body: "Noto Serif", notes: "gentle heritage serif pairing" },
    lit: { quality: "soft mountain light", direction: "bounce between overhanging storeys", temperature: "cool shade with warm patches", shadow: "cumba shadows striping the cobbles" },
    pho: { approach: "walk the streets at dusk when shutters glow", grade: "muted timber and plaster pastels" },
    fash: { silhouettes: "settled bourgeois layers", garments: "vested suits, headscarves, house slippers", acc: "copper trays, rosaries" },
    env: { places: "cobbled lanes, ivy courtyards, bazaar arasta", weather: "misted Black Sea foothills, four seasons" },
    gd: { layout: "street-canyon perspective grid", icon: "jettied bay outline" },
    ui: { background: "plaster cream", surface: "timber-grid framed cards", components: "lattice sliders, tile-red accents", motion: "shutter fold reveals" },
    rec: { materials: "timber, plaster, tile", lighting: "warm interior lamps at twilight", objects: "coffee Sets, iplik sofa cushions, cistern bucket", music: "kemençe and soft ney", scent: "saffron, damp wood, rose water" },
    snd: ["wooden stair creaks", "runnel water over stone", "evening swifts under eaves"],
    dna: { mi: 50, og: 75, wc: 15, ns: 30, ad: 15, hf: 15, rr: 55, ps: 55, sh: 45, ql: 40, oc: 30, ds: 60, rs: 40, eu: 55, np: 30 },
    emo: { warm: 75, cold: 20, playful: 25, serious: 50, chaotic: 15, ordered: 75, nostalgic: 85, futuristic: 10, peaceful: 75, ominous: 10 },
  },
  {
    n: "Armenian tuff vernacular", a: ["tuff stone architecture", "Armenian pink tufa building", "Gyumri tuff houses"],
    cat: "Architectural Style", c: "Volcanic stone building culture", e: "regional_tradition", o: "Armenian Highland", g: "Armenia (Gyumri, Yerevan, Shirak), historic Western Armenia",
    p: "medieval to 20th century", era: "medieval kingdom to Soviet Armenia",
    sum: "A building culture in feather-light volcanic tuff whose rose, apricot and black shades give Armenian towns their monochrome glow and their seismic resilience.",
    desc: "The Armenian highland is sheathed in layers of volcanic tuff, a stone light enough to float yet weatherproof and easy to cut, and virtually all Armenian building — from medieval monasteries to 19th-century merchant houses — is made of it. Quarries yield different colours by region: the famous pink and apricot tufa of Yerevan and Artik, the black tuff of Gyumri, making whole districts monochrome in a single mineral tone. Masons laid precisely dressed ashlar in arch-and-vault systems long proven against earthquakes, carving cornices, rope-mouldings and khachkar-like ornament directly into the stone. Gyumri's Kumayri district preserves the largest historic quarter, its black-and-ochre houses with iron balconies built by the amira merchant class after the 1853 quake; Soviet-era Yerevan clad its monumental centre in pink tufa, earning the 'pink city' reputation.",
    col: [{ h: "#d9a08a", n: "pink tufa rose" }, { h: "#e3b795", n: "apricot Artik tuff" }, { h: "#4a4547", n: "Gyumri black tuff" }, { h: "#8f8578", n: "weathered ashlar grey" }, { h: "#5f7d5a", n: "orchard green" }],
    m: ["dressed tuff ashlar", "lime mortar", "wrought-iron balconies", "volcanic basalt bases"],
    tx: ["fine-grained stone face", "blackened quake cracks", "sun-bleached moulding edges"],
    obj: ["tuff ashlar facade", "carved rope-moulding cornice", "iron balcony grid", "bell-cast tile roof", "vaulted cellar door"],
    ex: ["Kumayri historic district, Gyumri", "Yerevan's pink tuff Republic Square buildings", "Artik tufa quarries and churches"],
    inf: ["Armenian mason guilds", "post-earthquake rebuilding codes"], rel: ["Cappadocia rock-cut settlements", "Tbilisi carved wooden balconies", "Khachkar cross-stone"],
    par: "Armenian architecture", var: ["Gyumri black tuff houses", "Yerevan pink monumental", "Shirak village ashlar"], cf: ["Cappadocia rock-cut settlements"],
    src: [{ n: "Wikipedia — Armenian architecture", u: "https://en.wikipedia.org/wiki/Armenian_architecture", t: "B" }, { n: "UNESCO — Cathedral and Churches of Echmiatsin and Zvartnots", u: "https://whc.unesco.org/en/list/1011", t: "A" }],
    tg: ["tuff", "gyumri", "ashlar", "armenia", "stone town"], pop: 32, niche: true,
    vd: { shape: "squat stone blocks under wide eaves", line: "string-course horizontals", composition: "monochrome streetscapes of one mineral", texture: "fine tuff grain, iron rust", forms: "arches, cornices, balconies" },
    typ: { display: "Noto Serif Armenian", body: "Noto Sans Armenian", notes: "full Armenian script support" },
    fnt: { display: "Noto Serif Armenian", body: "Noto Sans Armenian", notes: "dual Armenian + Latin pairing" },
    lit: { quality: "high-altitude crisp sun", direction: "strong southern light across facades", temperature: "sharp mornings, warm stone afternoons", shadow: "crisp cornice shadows" },
    pho: { approach: "facade studies in single-colour streets, overcast for texture", grade: "desaturated rose and charcoal" },
    fash: { silhouettes: "layered highland wool", garments: "taraz-style vests, long coats", acc: "silver belt clasps, pomegranate motifs" },
    env: { places: "stone quarters, quarry scarps, orchard edges", weather: "severe winters, dust-white summers" },
    gd: { layout: "facade tile grid keyed to stone tones", icon: "arch-and-rope-moulding motif" },
    ui: { background: "rose-tuff tint", surface: "stone-cut card edges", components: "ironwork dividers, ashlar buttons", motion: "stone-slide horizontal pan" },
    rec: { materials: "tuff, iron, tile", lighting: "low winter sun", objects: "pomegranate bowls, duduk case, stone lintels", music: "duduk over komuz strings", scent: "cold stone, lavash bread, river dust" },
    snd: ["chisel tapping in the workshop", "wind down empty stone lanes", "distant church bell"],
    dna: { mi: 45, og: 80, wc: 15, ns: 25, ad: 15, hf: 15, rr: 60, ps: 55, sh: 50, ql: 35, oc: 30, ds: 70, rs: 30, eu: 50, np: 20 },
    emo: { warm: 65, cold: 35, playful: 20, serious: 70, chaotic: 15, ordered: 75, nostalgic: 80, futuristic: 15, peaceful: 60, ominous: 20 },
  },
  {
    n: "Tbilisi carved wooden balconies", a: ["Tbilisi balcony facades", "Georgian lace balconies", "Tbilisi old town verandas"],
    cat: "Architectural Style", c: "19th-century urban timberwork", e: "regional_tradition", o: "Tbilisi, Georgia", g: "Tbilisi old town, Kutaisi, Signagi, Georgia",
    p: "19th-early 20th century", era: "Russian imperial Tiflis",
    sum: "Fretted deep-veranda balconies in wild colour that wrap Tbilisi's older houses, mixing Georgian, Persian and neoclassical taste into a single signature facade.",
    desc: "The wooden balcony is the emblem of Tbilisi's historic architecture, built mostly in the 19th century when Russian imperial Tiflis grew with merchant houses on Sololaki, Betlemi and Abanotubani streets. Carpenters assembled deep verandas of turned posts, carved brackets, sunburst tympana and fine fretwork lattices, often glazed in later decades, then painted them in saturated colours — duck-egg blue, pistachio, oxblood — against plaster walls tinted ochre, rose or cream. The vocabulary braids Georgian carving, Persian timberwork and Italianate stucco order, with ironwork gates and shop awnings below. Decay in the 1990s led conservationists and programmes to restore hundreds of balconies; today they front guesthouses, embassies and the city's identity, and Kutaisi and Signagi carry related regional variants.",
    col: [{ h: "#7fb3a6", n: "duck-egg balcony teal" }, { h: "#e8d8b8", n: "plaster sand" }, { h: "#a13b2c", n: "oxblood trim" }, { h: "#c56a4b", n: "terracotta wall" }, { h: "#4c5a44", n: "shutter green" }],
    m: ["carved pine posts", "fretwork lattice panels", "turned balusters", "iron tie-rods", "coloured mineral plaster"],
    tx: ["flaking pastel paint", "sun-split fretwork", "cool shaded veranda boards"],
    obj: ["deep glazed veranda", "carved sunburst tympanum", "turned post row", "corner fretwork spandrel", "iron gate under archway"],
    ex: ["Sololaki and Betlemi street facades, Tbilisi", "Abanotubani balcony crescent", "Kutaisi old town balconies"],
    inf: ["Persian carpentry vocabulary", "Italianate Tiflis eclecticism"], rel: ["Safranbolu Ottoman timber houses", "Hijazi roshan bay window", "Georgian supra feast"],
    par: "Georgian vernacular architecture", var: ["glazed veranda type", "open fretwork type", "Kutaisi provincial variant"], cf: ["Safranbolu Ottoman timber houses"],
    src: [{ n: "Wikipedia — Tbilisi", u: "https://en.wikipedia.org/wiki/Tbilisi", t: "B" }, { n: "Google Arts & Culture", u: "https://artsandculture.google.com", t: "A" }],
    tg: ["balcony", "tbilisi", "fretwork", "facade", "georgia"], pop: 40, niche: false,
    vd: { shape: "projecting lace boxes on plaster walls", line: "repeating post and bracket rhythm", composition: "colour-blocked facade with timber overlay", texture: "peeling paint over carved wood", forms: "verandas, tympana, brackets" },
    typ: { display: "Noto Serif Georgian", body: "Noto Sans Georgian", notes: "Georgian Mkhedruli script support" },
    fnt: { display: "Noto Serif Georgian", body: "Noto Sans Georgian", notes: "elegant Mkhedruli display, clean body" },
    lit: { quality: "soft southern light, filtered on verandas", direction: "afternoon raking across fretwork", temperature: "warm plaster, cool timber shade", shadow: "fretwork lace shadows on walls" },
    pho: { approach: "straight-on facade documentation plus balcony interior frames", grade: "saturated pastel colour blocking" },
    fash: { silhouettes: "urban late-imperial layers", garments: "light summer dresses, waistcoats", acc: "wine-glass props, felt hats" },
    env: { places: "narrow lane stairways, courtyard wells, sulphur bath quarter", weather: "hot dry summer, grey wet winter" },
    gd: { layout: "facade grid with balcony close-up insets", icon: "fretwork bracket motif" },
    ui: { background: "tinted plaster cream", surface: "veranda cards with carved corners", components: "lattice toggles, bracket dividers", motion: "awning-shade wipe" },
    rec: { materials: "painted timber, plaster, iron", lighting: "lantern-lit verandas at night", objects: "samovar, wine carafe, carved stools", music: "panduri strings and city buskers", scent: "lime blossom, khinkali steam, rain on wood" },
    snd: ["chairs scraping on balcony boards", "grapevine leaves in wind", "sparring swifts between eaves"],
    dna: { mi: 55, og: 70, wc: 20, ns: 35, ad: 20, hf: 20, rr: 50, ps: 60, sh: 40, ql: 40, oc: 30, ds: 65, rs: 40, eu: 60, np: 35 },
    emo: { warm: 80, cold: 20, playful: 55, serious: 35, chaotic: 30, ordered: 60, nostalgic: 85, futuristic: 15, peaceful: 70, ominous: 10 },
  },
  {
    n: "Georgian supra feast", a: ["supra table", "Georgian feast ritual", "tamada toast tradition"],
    cat: "Regional & Cultural Tradition", c: "Ritual banquet culture", e: "regional_tradition", o: "Georgia (Caucasus)", g: "Georgia and Georgian diaspora",
    p: "centuries-old; codified in 19th-20th century", era: "imperial and Soviet Georgia",
    sum: "The Georgian ritual feast presided over by a tamada toastmaster, where long toasts, polyphonic table songs and mountains of food turn a meal into a social institution.",
    desc: "A supra is the Georgian feast table: a spread of khachapuri cheese bread, mtsvadi grilled meat, pkhali walnut pastes, qvriviani herbs and clay-jar wine, presided over by a tamada or toastmaster who orders the evening through themed toasts — to ancestors, Georgia, women, friendship, the departed — each requiring a horn or glass emptied at length. Between toasts the table answers with polyphonic songs like Mravalzhamier, so the feast doubles as a concert, and tamadoba, the art of toastmaking, is judged as oratory. The supra runs from birthdays to funerals (a kelekhi mourning feast), making it the spine of Georgian social life across empires and Soviet decades. Ethnographers treat it as a living institution where hospitality, hierarchy and song are negotiated, and every Georgian film from Mimino to modern feasts stages its rules.",
    col: [{ h: "#7a1f2b", n: "saperavi wine red" }, { h: "#e6ddca", n: "linen table cream" }, { h: "#3d6b35", n: "herb pkhali green" }, { h: "#c78f3d", n: "bread crust gold" }, { h: "#5b4632", n: "clay jug brown" }],
    m: ["clay qvevri wine jugs", "woven tablecloths", "drinking horns", "long banquet tables", "grilled skewer iron"],
    tx: ["greasy bread crust sheen", "wine-stained linen", "steam over platters"],
    obj: ["tamada's horn", "khachapuri wheel", "mtsvadi skewers", "pitcher of saperavi", "long toast-chain of glasses"],
    ex: ["Tamada toasts at Tbilisi family supras", "Polyphonic table songs at village kelekhi feasts", "Supra scenes in Georgian films (Mimino, And Then We Danced)"],
    inf: ["Georgian polyphonic singing", "qvevri wine culture"], rel: ["Georgian qvevri winemaking", "Turkish kahvehane", "Nowruz haft-sin table"],
    par: "feast culture", var: ["kelekhi mourning feast", "wedding supra", "Soviet-era kitchen supra"], cf: ["Armenian kef feast"],
    src: [{ n: "Wikipedia — Supra (feast)", u: "https://en.wikipedia.org/wiki/Supra_(feast)", t: "B" }, { n: "Encyclopædia Britannica — Georgia", u: "https://www.britannica.com/place/Georgia", t: "A" }],
    tg: ["supra", "tamada", "toast", "feast", "wine"], pop: 39, niche: false,
    vd: { shape: "long loaded horizontal table", line: "rows of glasses and platters", composition: "tamada at head, arms raised mid-toast", texture: "linen, steam, wine gloss", forms: "horns, jugs, bread wheels" },
    typ: { display: "Noto Serif Georgian", body: "Noto Sans Georgian", notes: "toast list as typographic column" },
    fnt: { display: "Noto Serif Georgian", body: "Noto Sans Georgian", notes: "banquet-programme formality" },
    lit: { quality: "warm interior glow, long exposure", direction: "candle and chandelier down the table", temperature: "deep amber evening", shadow: "glass shadows along the linen" },
    pho: { approach: "down-table long view with raised glass mid-toast", grade: "warm amber with wine-dark accents" },
    fash: { silhouettes: "dressed-up comfort", garments: "dark tailored suits, chokha nods, bright headscarves", acc: "drinking horns, wine glass chains" },
    env: { places: "village long-houses, Tbilisi restaurant vaults, vineyard maranis", weather: "cool mountain nights, warm hearth" },
    gd: { layout: "horizontal banquet timeline of toasts", icon: "horn and vine emblem" },
    ui: { background: "linen warm white", surface: "wine-red header bands", components: "glass-raise buttons, song-card rows", motion: "toast cascade ripple" },
    rec: { materials: "clay, horn, linen, oak", lighting: "candle runs down the table", objects: "qvevri jug, horn, skewer set", music: "polyphonic table songs between toasts", scent: "grilled meat, tarragon, wine and bread" },
    snd: ["glass clinks down the table", "three-voice song swelling mid-feast", "laughter and chair scrapes"],
    dna: { mi: 60, og: 80, wc: 15, ns: 30, ad: 20, hf: 20, rr: 60, ps: 70, sh: 50, ql: 40, oc: 30, ds: 70, rs: 40, eu: 55, np: 30 },
    emo: { warm: 95, cold: 10, playful: 60, serious: 55, chaotic: 40, ordered: 65, nostalgic: 80, futuristic: 15, peaceful: 60, ominous: 15 },
  },
  {
    n: "Azerbaijani shebeke lattice", a: ["shebeke window", "shabaka lattice", "Azerbaijani wooden screens"],
    cat: "Textile & Craft", c: "Lattice woodwork", e: "regional_tradition", o: "Azerbaijan (Shaki and Karabakh workshops)", g: "Azerbaijan, Iran, Dagestan",
    p: "18th-19th century peak", era: "khanate-era Azerbaijan",
    sum: "Assembled-without-nails wooden window lattices of Shaki khanate palaces, filling glassless openings with geometric star patterns that cool and dim the light.",
    desc: "Shebeke is the Azerbaijani art of window lattices assembled from hundreds of small wooden elements — walnut, oak or poplar — joined by wooden pins and mortise-and-tenon alone, without glue or nails, a technique hereditary masters still guard. Openings were traditionally left unglazed: the lattice breaks wind and sun, dims harsh light into pattern, and lets rooms breathe in summer heat, while rich khans ordered screens inset with coloured glass and stained panes. The masterpiece is the Khan's Palace of Shaki (1797), whose hall windows run floor-to-ceiling in stained-glass-set shebeke that lights the mirrored interior in jewel tones. Craftsmen compute the star-and-rosette geometry by hand; UNESCO inscribed the Historic Centre of Sheki with the Khan's Palace in 2019, and shebeke restoration remains a living guild profession.",
    col: [{ h: "#6b4a2f", n: "walnut lattice brown" }, { h: "#e5d3ae", n: "strong light amber" }, { h: "#2f5d8a", n: "stained glass cobalt" }, { h: "#b8452f", n: "glass garnet" }, { h: "#d8c07a", n: "honey sunlight" }],
    m: ["walnut and oak strips", "wooden pins (no nails)", "coloured glass insets", "chalk-and-ink layout lines"],
    tx: ["razor-clean joinery edges", "glass jewel glow", "dust in light shafts"],
    obj: ["floor-to-ceiling palace window", "eight-point star rosette panel", "coloured glass medallion", "restorer's peg box", "summer hall divan"],
    ex: ["Khan's Palace of Shaki stained-glass shebeke (1797)", "Shaki shebeke master workshops", "UNESCO 2019 listing of Historic Centre of Sheki"],
    inf: ["Persian orsi stained-glass lattices", "khanate court craft patronage"], rel: ["Mashrabiya screen", "Tbilisi carved wooden balconies", "Kubachi silver engraving"],
    par: "Islamic ornamental woodwork", var: ["glass-inset shebeke", "open summer screen", "door and cabinet panels"], cf: ["Mashrabiya screen"],
    src: [{ n: "Wikipedia — Khan's Palace of Shaki", u: "https://en.wikipedia.org/wiki/Khan%27s_Palace_of_Shaki", t: "B" }, { n: "UNESCO — Historic Centre of Sheki with the Khan's Palace", u: "https://whc.unesco.org/en/list/1669", t: "A" }],
    tg: ["shebeke", "lattice", "shaki", "woodwork", "stained glass"], pop: 29, niche: true,
    vd: { shape: "gridded star-polygon fields", line: "hair-fine walnut ribs", composition: "glow wall with geometric order", texture: "crisp timber edges, glass gleam", forms: "rosettes, stars, hexagon fills" },
    typ: { display: "Marcellus for museum captions", body: "Noto Sans", notes: "Latin transliteration of Azerbaijani terms" },
    fnt: { display: "Marcellus", body: "Noto Sans", notes: "inscription-style display, neutral body" },
    lit: { quality: "outside glare tamed into jewels", direction: "sun straight through the screen", temperature: "hot amber with cool blue glass", shadow: "star shadows falling across divans" },
    pho: { approach: "shoot through the lattice toward the sun for star flare", grade: "amber-cobalt jewel contrast" },
    fash: { silhouettes: "khanate court layers", garments: "silk kelaghai headscarves, chapkan coats", acc: "silver-gilt filigree buttons" },
    env: { places: "palace summer halls, courtyard workshops, plane-tree lanes", weather: "dry hot summers, snowy Caucasus winters" },
    gd: { layout: "star-grid modular tiles", icon: "eight-point rosette" },
    ui: { background: "parchment light", surface: "lattice-divided panels", components: "rosette buttons, glass-chip toggles", motion: "light-mosaic shimmer" },
    rec: { materials: "walnut, coloured glass, ox-horn pins", lighting: "projected lattice shadows", objects: "master's layout compass, peg chest, glass offcuts", music: "tar and kamancha mugham modal phrases", scent: "fresh walnut shavings, rose tea" },
    snd: ["tap of the master's mallet", "fine saw through walnut", "leaves of plane trees outside"],
    dna: { mi: 50, og: 85, wc: 10, ns: 25, ad: 15, hf: 15, rr: 65, ps: 65, sh: 55, ql: 40, oc: 25, ds: 75, rs: 25, eu: 50, np: 20 },
    emo: { warm: 70, cold: 25, playful: 25, serious: 60, chaotic: 10, ordered: 90, nostalgic: 75, futuristic: 20, peaceful: 75, ominous: 10 },
  },
  {
    n: "Azerbaijani mugham", a: ["mugham modal music", "Mugham trio", "Azeri dastgah"],
    cat: "Music & Sonic Culture", c: "Modal art music", e: "regional_tradition", o: "Azerbaijan (Baku, Karabakh, Shusha)", g: "Azerbaijan, Iranian Azerbaijan, Iraq borderlands",
    p: "medieval roots; canonised 19th-20th century", era: "khanate to Soviet Azerbaijan",
    sum: "A modal art music of tar, kamancha and daf where the singer navigates improvised ascents through dastgah modes, paralleling Persian dastgah and Arab maqam systems.",
    desc: "Mugham is Azerbaijan's classical modal music, built on dastgah modes such as Rast, Shur and Segah, performed by a trio of tar (plucked lute), kamancha (bowed spike fiddle) and daf frame drum supporting a khanende vocalist. A performance is an improvised ascent: the singer departs from a base section and travels through related modal sections, each demanding precise intonation and melodic knowledge, before returning — a journey often compared to the structure of Persian dastgah and Arabic maqam, its close relatives. Shusha in Karabakh produced legendary singers including Jabbar Garyaghdioglu and Bülbül, and Baku's mugham opera tradition fused the modes with staged drama. Soviet-era institutions preserved and codified mugham, and UNESCO proclaimed Azerbaijani Mugham a Masterpiece in 2003; the Baku Mugham Centre now stages international competitions.",
    col: [{ h: "#1f2a3a", n: "concert indigo" }, { h: "#c9a35c", n: "tar varnish gold" }, { h: "#8c2f2f", n: "curtain crimson" }, { h: "#d8cdb4", n: "programme cream" }, { h: "#4c6b52", n: "daf skin green-grey" }],
    m: ["tar eleven-string lute", "kamancha spike fiddle", "daf frame drum", "rosewood fingerboards"],
    tx: ["varnished mulberry sheen", "pizzicato string shimmer", "smoky hall air"],
    obj: ["tar with bone inlay", "kamancha's round bridge", "daf ring of jingles", "khanende's open score book", "mugham trio stage arc"],
    ex: ["Jabbar Garyaghdioglu's recorded bayatis-shiraz", "Mugham opera 'Leyli and Majus' by Uzeyir Hajibeyov (1908)", "Baku Mugham Centre competitions"],
    inf: ["Persian dastgah system", "medieval Islamic music theory"], rel: ["Iraqi maqam", "Armenian duduk music", "Azerbaijani shebeke lattice"],
    par: "maqam-dastgah music family", var: ["mugham opera", "zarbi-mugham (rhythmic)", "instrumental mugham"], cf: ["Iraqi maqam", "Persian dastgah"],
    src: [{ n: "Wikipedia — Mugham", u: "https://en.wikipedia.org/wiki/Mugham", t: "B" }, { n: "UNESCO ICH — Azerbaijani Mugham", u: "https://ich.unesco.org/en/RL/azerbaijani-mugham-00071", t: "A" }],
    tg: ["mugham", "tar", "kamancha", "modal music", "baku"], pop: 36, niche: false,
    vd: { shape: "arc of seated trio", line: "phrase curves ascending through modes", composition: "listener-focused dim stage", texture: "string sheen, breath tone", forms: "lutes, fiddle, drum ring" },
    typ: { display: "Aref Ruqaa for mode names", body: "Noto Naskh Arabic", notes: "Latin transliteration beside Arabic script" },
    fnt: { display: "Aref Ruqaa", body: "Noto Naskh Arabic", notes: "calligraphic titles, discreet body" },
    lit: { quality: "single warm stage pool", direction: "front low onto the trio", temperature: "dim amber hush", shadow: "instrument silhouettes on backcloth" },
    pho: { approach: "close on the khanende's hands and throat mid-phrase", grade: "low-key amber with deep blacks" },
    fash: { silhouettes: "formal evening dress", garments: "dark suits, kelaghai silk", acc: "chokha-style waistcoats in folk ensembles" },
    env: { places: "Baku concert vaults, Caravanserai courtyard sessions, Shusha memorials", weather: "hot still Caspian evenings" },
    gd: { layout: "mode-map diagram as hero graphic", icon: "tar silhouette" },
    ui: { background: "deep indigo", surface: "cream modal-chapter cards", components: "waveform scrubbers, mode chips", motion: "slow phrase-rise animation" },
    rec: { materials: "mulberry wood, gut strings, skin", lighting: "one lamp over the trio", objects: "tar, kamancha, tea glasses", music: "improvised mugham ascent itself", scent: "rose oil, cardamom tea, varnish" },
    snd: ["vocal melisma over tar tremolo", "daf jingle shimmer", "hall echo tail"],
    dna: { mi: 55, og: 85, wc: 10, ns: 25, ad: 15, hf: 15, rr: 60, ps: 60, sh: 50, ql: 40, oc: 25, ds: 70, rs: 35, eu: 45, np: 20 },
    emo: { warm: 65, cold: 30, playful: 20, serious: 85, chaotic: 30, ordered: 70, nostalgic: 80, futuristic: 20, peaceful: 60, ominous: 25 },
  },
  {
    n: "Kubachi silver engraving", a: ["Kubachi metalwork", "Dagestani chasing", "Kubachi master households"],
    cat: "Textile & Craft", c: "Silver chasing and engraving", e: "regional_tradition", o: "Kubachi village, Dagestan", g: "Mountain Dagestan, North Caucasus; Russian museum collections",
    p: "medieval origins; 19th-20th century fame", era: "Caucasian khanate to Soviet era",
    sum: "A single Dagestani mountain village whose hereditary workshops filled museum vaults with densely engraved silver jugs, belts, daggers and fire-gilt niello work.",
    desc: "Kubachi, a stone village in mountain Dagestan, has practised metalwork for at least a thousand years; Persian chronicles praised Zirihgeran, 'the armour-makers', its medieval ancestor. Hereditary households divided tasks — one line for engraving, one for chasing, one for casting — and produced parade armour, chain mail, water vessels (kumgans), belts, pistol butts and kindjal scabbards in deep-relief chased silver, often gilded and blackened with niello, covered edge to edge in scrolling Arabic-style ornament and bird medallions. In the 19th century Kubachi work won Paris and Istanbul exhibition medals and entered the Hermitage and Kremlin Armoury collections; Soviet reorganisation made the village a state artel working through the 20th century. The craft survives in family workshops, and Kubachi ornament remains a Caucasian shorthand for dense hand-engraved silver.",
    col: [{ h: "#b9bec4", n: "chased silver grey" }, { h: "#c69c46", n: "fire gilding gold" }, { h: "#2a2a2e", n: "niello black" }, { h: "#6e4a2c", n: "walnut handle brown" }, { h: "#8e3b2e", n: "garnet inlay red" }],
    m: ["silver sheet and ingot", "niello compound", "fire gilding", "walnut and horn grips"],
    tx: ["mirror-tool polish", "dark niello recesses", "hammered field dimples"],
    obj: ["chased kumgan jug", "engraved kindjal scabbard", "narrow master's belt", "gilded drinking horn tip", "bird-medallion plaque"],
    ex: ["Hermitage Museum Kubachi silver collection", "Kremlin Armoury Caucasian pieces", "Kubachi family workshops today"],
    inf: ["medieval Zirihgeran armour school", "Caucasian court gift exchange"], rel: ["Azerbaijani shebeke lattice", "Circassian dress tradition", "Damascening (metal inlay)"],
    par: "Caucasian metalcraft", var: ["niello-ware", "gilt parade vessels", "engraved pistol butts"], cf: ["Damascening (metal inlay)"],
    src: [{ n: "Wikipedia — Kubachi", u: "https://en.wikipedia.org/wiki/Kubachi", t: "B" }, { n: "State Hermitage Museum", u: "https://www.hermitagemuseum.org", t: "A" }],
    tg: ["kubachi", "silver", "engraving", "dagestan", "niello"], pop: 27, niche: true,
    vd: { shape: "covered vessels bulging with ornament", line: "dense scroll and tendril engraving", composition: "object as total ornament field", texture: "chase relief against black niello", forms: "jugs, belts, scabbards" },
    typ: { display: "Aref Ruqaa for ornament panel headings", body: "Cairo", notes: "engraved-cartouche frame motifs" },
    fnt: { display: "Aref Ruqaa", body: "Cairo", notes: "metal-cut calligraphic feel" },
    lit: { quality: "hard studio sparkles on relief", direction: "cross light to pop the chasing", temperature: "cold silver with warm gilt", shadow: "black niello depth" },
    pho: { approach: "macro raking light across engraving depth", grade: "silver-gold duotone" },
    fash: { silhouettes: "highland ceremonial", garments: "chokha with gazyr cartridges, papakha hat", acc: "engraved belt and kindjal set" },
    env: { places: "stone-village workshops, aul terraces, museum vaults", weather: "thin mountain air, snow glare" },
    gd: { layout: "ornament-field border around captions", icon: "scrolling tendril vignette" },
    ui: { background: "slate dark", surface: "silver-bevel cards", components: "chased-metal buttons, niello dividers", motion: "engraving-tool draw-on lines" },
    rec: { materials: "silver, niello, walnut", lighting: "one hard lamp for relief", objects: "burin set, unfinished jug, master's belt", music: "Caucasian lezginka drum patterns", scent: "metal polish, mountain juniper smoke" },
    snd: ["burin scratch in silence", "tap of chasing hammer", "stream below the aul"],
    dna: { mi: 45, og: 90, wc: 5, ns: 20, ad: 10, hf: 10, rr: 70, ps: 55, sh: 65, ql: 30, oc: 30, ds: 75, rs: 20, eu: 40, np: 15 },
    emo: { warm: 45, cold: 50, playful: 15, serious: 80, chaotic: 15, ordered: 85, nostalgic: 75, futuristic: 10, peaceful: 40, ominous: 25 },
  },
  {
    n: "Circassian dress tradition", a: ["Adyghe costume", "cherkeska coat", "gazyr cartridge dress"],
    cat: "Fashion & Dress", c: "Caucasian national dress", e: "regional_tradition", o: "Northwest Caucasus (Circassia)", g: "Adygea, Kabardino-Balkaria, diaspora in Türkiye, Jordan, Israel",
    p: "documented 16th-19th century; revival present", era: "pre-exile Circassia",
    sum: "The fitted cherkeska and long gazyr-chested men's costume and the high-waisted sa'i women's dress that became emblems of Circassian identity through exile and diaspora.",
    desc: "Circassian male dress centres on the cherkeska, a tight-bodiced, long-skirted coat with sewn-on gazyr cartridge tubes across the chest, worn over a beshmet, with a narrow leather belt bearing silver fittings, soft kokej boots, a bashlyk hood and the tall wool papakha; the kindjal dagger hangs at the front in plain sight. Women wore the sa'i — a long dress with a high silver-buckled belt and a distinctive tall cap (dyshche paʼo) with veil, described by Ottoman and European travellers as graceful and courtly. After the 1860s genocide and mass exile to the Ottoman Empire, dress became a portable nation: diaspora troupes in Türkiye, Jordan and Israel kept the silhouette alive through dance costumes, while Soviet republics codified 'Caucasian' stage versions. The gazyr chest in particular became a pan-Caucasian icon copied by neighbouring peoples.",
    col: [{ h: "#2a2622", n: "cherkeska black" }, { h: "#8d1f1f", n: "papakha deep red" }, { h: "#d8d2c4", n: "beshmet cream" }, { h: "#b6b0a2", n: "wool felt grey" }, { h: "#a8863c", n: "silver-gilt buckle" }],
    m: ["wool broadcloth", "gazyr wooden tubes", "silver belt fittings", "astrakhan papakha wool", "kid leather boots"],
    tx: ["felted wool nap", "cold silver clasp", "long skirt drape"],
    obj: ["gazyr cartridge chest", "silver belt and dagger", "tall dyshche paʼo cap", "bashlyk hood", "long-skirted cherkeska"],
    ex: ["Nart dance ensemble costumes, Nalchik", "Circassian wedding dress in Amman diaspora", "Museum of Adyghe costume, Maykop"],
    inf: ["Caucasian equestrian culture", "Ottoman-era exile memory"], rel: ["Kubachi silver engraving", "Kurdish Newroz fire festival", "Georgian supra feast"],
    par: "Caucasian dress culture", var: ["Kabardian courtly variant", "black mourning cherkeska", "stage folk-dance costume"], cf: ["Georgian chokha"],
    src: [{ n: "Wikipedia — Circassians", u: "https://en.wikipedia.org/wiki/Circassians", t: "B" }, { n: "Encyclopædia Britannica — Circassian", u: "https://www.britannica.com/topic/Circassian", t: "A" }],
    tg: ["cherkeska", "gazyr", "caucasus", "costume", "adyghe"], pop: 31, niche: true,
    vd: { shape: "tall vertical silhouette with flared skirt", line: "cartridge rows as chest pinstripes", composition: "silver accents on black field", texture: "wool nap, silver gleam", forms: "coats, caps, belts" },
    typ: { display: "Cormorant Garamond for captions", body: "Spectral", notes: "Latin transliteration with Adyghe notes" },
    fnt: { display: "Cormorant Garamond", body: "Spectral", notes: "ethnographic-plate elegance" },
    lit: { quality: "soft even studio light", direction: "three-quarter frontal", temperature: "neutral with silver highlights", shadow: "clean drop shadows" },
    pho: { approach: "full-length plate photos against plain backdrop, detail crops of gazyr", grade: "silvered monochrome plus red accent" },
    fash: { silhouettes: "nipped waist, long skirt, tall hat", garments: "cherkeska, beshmet, sa'i dress", acc: "silver belt, dagger, papakha" },
    env: { places: "mountain auls, dance stages, diaspora wedding halls", weather: "alpine wind, warm hall lights" },
    gd: { layout: "fashion-plate column with annotation lines", icon: "gazyr tube row" },
    ui: { background: "bone white", surface: "tailored card lapels", components: "cartridge-row list items, silver toggles", motion: "cape-swish page turn" },
    rec: { materials: "wool, silver, leather", lighting: "crisp north-window light", objects: "dagger, belt, papakha", music: "shichepshin fiddle and clapping dance", scent: "wool, leather, mountain grass" },
    snd: ["leather boots striking dance floor", "silver belt chime", "flute (kamyl) melody"],
    dna: { mi: 45, og: 85, wc: 10, ns: 20, ad: 10, hf: 10, rr: 65, ps: 55, sh: 60, ql: 30, oc: 30, ds: 70, rs: 25, eu: 45, np: 20 },
    emo: { warm: 55, cold: 40, playful: 25, serious: 80, chaotic: 15, ordered: 80, nostalgic: 85, futuristic: 10, peaceful: 45, ominous: 20 },
  },
  {
    n: "Armenian duduk music", a: ["duduk and its music", "tsiranapogh", "apricot wood pipe"],
    cat: "Music & Sonic Culture", c: "Double-reed pastoral music", e: "regional_tradition", o: "Armenian Highland", g: "Armenia and worldwide Armenian diaspora",
    p: "documented for centuries; UNESCO 2005", era: "living medieval tradition",
    sum: "The apricot-wood double-reed duduk whose breathy, mournful tone carries Armenian weddings, funerals and film scores, played in two-part drone-and-melody pairs.",
    desc: "The duduk is a short cylindrical pipe of apricot wood (tsiran, the Armenian tree) with a wide soft double reed, producing a warm, reedy, deeply mournful voice unlike any sharper oboe family instrument. It is played in pairs: one musician sustains the continuous drone (dam) while the duduk player improvises a melody in Armenian modal khaz notation heritage, ornamented with slides, trills and breath inflections. The repertoire spans dance tunes, love songs and laments — the funeral elegy krunk being the most famous — and the instrument accompanies both weddings and wakes, its timbre considered the sound of Armenian memory itself. Master Djivan Gasparyan carried it to global audiences and film soundtracks (Gladiator, Syriana), and UNESCO proclaimed 'Duduk and its Music' a Masterpiece of Intangible Heritage in 2005.",
    col: [{ h: "#c98a4b", n: "apricot wood amber" }, { h: "#7a4a2a", n: "aged pipe brown" }, { h: "#3a3f36", n: "drone green-grey" }, { h: "#d9cba8", n: "reed pale gold" }, { h: "#5a2f2f", n: "velvet case red" }],
    m: ["apricot wood body", "cane double reed (ghamish)", "leather case", "beeswax reed seating"],
    tx: ["silky worn wood grain", "wet reed sheen", "breath fog in cold air"],
    obj: ["paired duduk and dam drone", "wide flat reed", "tuning band ring", "embroidered instrument sleeve", "apricot orchard grove"],
    ex: ["Djivan Gasparyan's 'Ask the Wind' recordings", "Gladiator soundtrack duduk themes", "UNESCO 2005 proclamation 'Duduk and its Music'"],
    inf: ["Armenian khaz modal system", "oral ashugh song culture"], rel: ["Azerbaijani mugham", "Armenian tuff vernacular", "Mevlevi sema whirling ceremony"],
    par: "Caucasian wind instrument traditions", var: ["dance duduk repertoire", "lament (krunk) style", "orchestral film arrangement"], cf: ["Turkish mey", "Georgian salamuri"],
    src: [{ n: "Wikipedia — Duduk", u: "https://en.wikipedia.org/wiki/Duduk", t: "B" }, { n: "UNESCO ICH — Duduk and its Music", u: "https://ich.unesco.org/en/RL/duduk-and-its-music-00085", t: "A" }],
    tg: ["duduk", "armenia", "reed", "lament", "gasparyan"], pop: 34, niche: true,
    vd: { shape: "two seated players, pipe and drone", line: "breath-phrase arcs", composition: "close duet intimacy", texture: "wood grain, breath haze", forms: "pipes, reeds, rings" },
    typ: { display: "Noto Serif Armenian", body: "Noto Sans Armenian", notes: "Armenian script first, Latin second" },
    fnt: { display: "Noto Serif Armenian", body: "Noto Sans Armenian", notes: "bilingual Armenian/Latin pairing" },
    lit: { quality: "low warm side light", direction: "window light on the player's cheek", temperature: "candle dusk", shadow: "long soft room shadows" },
    pho: { approach: "intimate portrait with reed and breath visible, orchard context", grade: "warm umber film look" },
    fash: { silhouettes: "simple highland layers", garments: "wool vests, flat caps", acc: "silver pendants, worn instrument cases" },
    env: { places: "apricot orchards, stone village rooms, church steps", weather: "dry mountain wind, golden dusk" },
    gd: { layout: "two-voice staff graphic (melody + drone)", icon: "pipe-and-arc motif" },
    ui: { background: "apricot-cream gradient", surface: "wood-grain panels", components: "breath-level meters, reed toggles", motion: "slow vibrato wobble" },
    rec: { materials: "apricot wood, cane, leather", lighting: "single warm practical", objects: "pipe pair, reed tin, orchard fruit", music: "paired duduk improvisation itself", scent: "apricot blossom, tobacco, warm wood" },
    snd: ["airy double-reed moan", "steady drone breath", "village dog and wind underneath"],
    dna: { mi: 60, og: 85, wc: 10, ns: 25, ad: 15, hf: 15, rr: 60, ps: 55, sh: 40, ql: 45, oc: 25, ds: 65, rs: 40, eu: 50, np: 25 },
    emo: { warm: 75, cold: 30, playful: 20, serious: 80, chaotic: 15, ordered: 60, nostalgic: 90, futuristic: 20, peaceful: 75, ominous: 25 },
  },
  {
    n: "Georgian qvevri winemaking", a: ["qvevri clay amphora", "kvevri wine", "Georgian amber wine"],
    cat: "Regional & Cultural Tradition", c: "Clay-vessel fermentation culture", e: "regional_tradition", o: "Kakheti, Georgia", g: "Georgia (Kakheti, Imereti), revived worldwide natural-wine cellars",
    p: "8000 years of lineage; UNESCO 2013", era: "Bronze Age to living present",
    sum: "Wine fermented and aged underground in enormous beeswax-lined clay qvevri, the oldest continuously practised winemaking method and source of Georgia's amber wines.",
    desc: "Qvevri are egg-shaped clay vessels up to two metres tall, lined inside with hot beeswax, buried to the neck in cellar earth so the surrounding soil keeps fermentation at steady temperature. Crushed grapes with skins, seeds and stalks go in whole, ferment on the skins through autumn and winter, and the wine draws amber colour, intense tannin and flavour from the long contact — the technique behind Georgia's distinctive amber (orange) wines from rkatsiteli and other varieties. Archaeology at sites like Gadachrili Gora traces the lineage back some 8,000 years to the earliest known winemaking, and every Kakhetian village still keeps marani cellars of buried qvevri tended by hereditary makers. Soviet industrialisation sidelined the method, but post-1990s revival made it the flag of Georgian identity and natural wine; UNESCO inscribed the tradition in 2013.",
    col: [{ h: "#a35c2e", n: "fired clay terracotta" }, { h: "#c98f2e", n: "amber wine gold" }, { h: "#4f3a28", n: "cellar earth brown" }, { h: "#d9b23c", n: "beeswax honey" }, { h: "#39503a", n: "vine leaf green" }],
    m: ["coiled river clay", "beeswax inner lining", "lime-earth cellar packing", "cane cleaning brushes"],
    tx: ["waxy clay sheen", "damp cellar coolness", "wine-stained rim glaze"],
    obj: ["buried egg-shaped qvevri", "neck-level stone lid", "amber wine in bowl glass", "grape-skin cap (chacha foam)", "marani cellar row"],
    ex: ["Kakheti village marani cellar rows", "Gadachrili Gora Neolithic wine residue finds", "UNESCO 2013 inscription of qvevri method"],
    inf: ["Neolithic Caucasus wine origins", "natural-wine movement"], rel: ["Georgian supra feast", "Cappadocia rock-cut settlements", "Çanakkale ceramics"],
    par: "traditional winemaking", var: ["Imereti white-method qvevri", "chacha distillation by-product", "export natural-wine qvevri"], cf: ["Roman amphora winemaking"],
    src: [{ n: "Wikipedia — Qvevri", u: "https://en.wikipedia.org/wiki/Qvevri", t: "B" }, { n: "UNESCO ICH — Qvevri wine-making method", u: "https://ich.unesco.org/en/RL/ancient-georgian-traditional-qvevri-wine-making-method-00870", t: "A" }],
    tg: ["qvevri", "amber wine", "kakheti", "clay vessel", "winemaking"], pop: 41, niche: false,
    vd: { shape: "buried egg forms in a row", line: "cellar arch over vessel necks", composition: "cross-section of earth, clay, wine", texture: "wax-glossed clay, gritty soil", forms: "amphorae, lids, ladles" },
    typ: { display: "Noto Serif Georgian", body: "Noto Sans Georgian", notes: "vintage-label Mkhedruli headers" },
    fnt: { display: "Noto Serif Georgian", body: "Noto Sans Georgian", notes: "wine-label elegance with modern body" },
    lit: { quality: "single hanging bulb in cellar dark", direction: "down onto vessel necks", temperature: "cool earth, warm wine glow", shadow: "egg shadows rising from floor" },
    pho: { approach: "cellar row at neck height, wax-lined interior macro", grade: "terracotta and amber warmth" },
    fash: { silhouettes: "vintner practical", garments: "boots, aprons, light summer shirts", acc: "cane brushes, horn ladles" },
    env: { places: "village marani cellars, grape-treading yards, church vineyards", weather: "harvest heat, cellar cool, autumn rain" },
    gd: { layout: "vessel cross-section as diagram spine", icon: "egg-amphora outline" },
    ui: { background: "cellar stone dark", surface: "terracotta cards", components: "vessel-shaped progress vessels, wax-gold accents", motion: "slow ferment bubbling" },
    rec: { materials: "clay, beeswax, oak, earth", lighting: "bulb and candle in cellar dark", objects: "qvevri, ladle, grape basket", music: "polyphonic vintage work songs", scent: "wet earth, wine must, beeswax" },
    snd: ["fermentation fizz at the neck", "ladle scrape on wax", "songs above ground at harvest"],
    dna: { mi: 55, og: 95, wc: 5, ns: 30, ad: 20, hf: 25, rr: 60, ps: 60, sh: 40, ql: 40, oc: 30, ds: 70, rs: 45, eu: 55, np: 35 },
    emo: { warm: 80, cold: 20, playful: 40, serious: 55, chaotic: 25, ordered: 65, nostalgic: 85, futuristic: 30, peaceful: 70, ominous: 10 },
  },
];
