/**
 * Curated wave — Wave 3 batch b: Film & Cinema, Music & Sonic Culture.
 * Real film movements and record/subculture visual cultures. All topics
 * documented and referenceable; dedup-checked against existing-names.txt
 * (Film noir, Giallo, City pop, Synthwave, Visual Kei, Punk fashion skipped).
 */
export const WAVE_FAM: any[] = [
  {
    n: "Italian Neorealism", a: ["neorealismo", "postwar Italian realist cinema"],
    cat: "Film & Cinema", c: "postwar realist film movement", e: "historical", o: "anti-fascist screenwriters and directors centred on Rome's film culture",
    g: "Italy — Rome, the war-damaged North, the rural South", p: "c. 1943-1952", era: "post-WWII reconstruction",
    sum: "Postwar Italian cinema of rubble, trams and unemployed men — real streets, real faces, real time, filmed amid the wreckage of fascism.",
    desc: "Born from pre-Liberation film debates and ignited by the end of the war, Italian neorealism took cameras out of Cinecitta into streets stripped by bombing. Rossellini's Rome, Open City (1945) and De Sica's Bicycle Thieves (1948) mixed non-professional actors, location sound and loose episodic plots with working-class protagonists for whom poverty, not romance, drives the story. Screenwriter Cesare Zavattini pushed the doctrine that a film should need nothing invented, while Visconti's La Terra Trema shot an entire Sicilian fishing village in dialect. Stock shortages, black markets and censors shaped the look as much as ideology did. By the early 1950s the box office pulled production back to spectacle, yet the style became the century's template for realist cinema from Satyajit Ray to the Dardennes.",
    col: [{ h: "#8a8578", n: "rubble grey" }, { h: "#cfc4ab", n: "travertine dust" }, { h: "#b07a4a", n: "faded plaster ochre" }, { h: "#2b2b2e", n: "bicycle-steel black" }, { h: "#5a6e78", n: "Po valley slate" }],
    m: ["short-end film stock scrounged from studios", "location streets and tenement interiors", "non-professional performers", "post-synced dialect sound"],
    tx: ["grainy monochrome emulsion", "soot-washed plaster", "worn wool and mended cloth", "handheld horizon drift"],
    obj: ["stolen bicycles", "open-top army trucks", "tenement stairwells", "ration queues", "burnt-out apartment blocks"],
    ex: ["Rome, Open City (Roberto Rossellini, 1945)", "Bicycle Thieves (Vittorio De Sica, 1948)", "La Terra Trema (Luchino Visconti, 1948)"],
    inf: ["the French New Wave's street-cinema ethics", "Satyajit Ray's Apu realism"], rel: ["French New Wave", "Free Cinema", "cinema verite documentary"],
    par: "European art cinema", var: ["Rossellini war trilogy", "Visconti lyric realism", "pink neorealism comedies"], cf: ["cinema verite documentary", "Free Cinema"],
    src: [{ n: "Wikipedia — Italian neorealism", u: "https://en.wikipedia.org/wiki/Italian_neorealism", t: "B" }, { n: "The Criterion Collection", u: "https://www.criterion.com", t: "A" }],
    tg: ["italian neorealism", "postwar cinema", "location shooting", "de sica", "rossellini"], pop: 52, niche: false,
    vd: { shape: "documentary full-frame streetscapes", line: "contour-less natural edges", composition: "deep-staged crowds with one small figure", texture: "coarse silver grain", forms: "bicycles, rubble, laundry lines, trams" },
    typ: { display: "condensed grotesque", body: "plain humanist sans", notes: "festival programme reportage tone" },
    fnt: { display: "Archivo Narrow", body: "Source Sans 3", notes: "newsprint-adjacent pairing" },
    lit: { quality: "flat overcast daylight", direction: "omnidirectional street light", temperature: "neutral-cool", shadow: "soft, low-contrast" },
    pho: { approach: "candid deep-focus street reportage", grade: "desaturated silver with warm plaster highlights" },
    fash: { silhouettes: "short cropped 1940s jackets", garments: "wool suits worn shiny, headscarves, mended skirts", acc: "flat caps, wire-frame glasses, canvas satchels" },
    env: { places: "bombed plazas, tram depots, tenement courtyards", weather: "damp Roman winter haze" },
    gd: { layout: "text-ruled broadsheet column", icon: "bicycle wheel emblem" },
    ui: { background: "warm grey", surface: "paper card with hard shadow", components: "rule-line dividers", motion: "plain cuts, no easing" },
    rec: { materials: "plaster, iron, straw seats", lighting: "north window light in bare rooms", objects: "bicycle, ewer, folding chairs", music: "street accordion, part songs", scent: "coal smoke, wet stone, espresso" },
    snd: ["streetcar bell", "children shouting in courtyard", "measured dialogue in dialect"],
    dna: { mi: 65, og: 80, wc: 15, ns: 12, ad: 10, hf: 15, rr: 30, ps: 55, sh: 45, ql: 70, oc: 55, ds: 60, rs: 25, eu: 85, np: 60 },
    emo: { warm: 55, cold: 55, playful: 20, serious: 90, chaotic: 40, ordered: 45, nostalgic: 60, futuristic: 8, peaceful: 30, ominous: 45 },
  },
  {
    n: "French New Wave", a: ["Nouvelle Vague", "Nouvelle Vague cinema", "Cahiers du cinema auteur wave"],
    cat: "Film & Cinema", c: "auteur film movement", e: "historical", o: "critics of Cahiers du cinema turning directors — Truffaut, Godard, Chabrol, Rohmer, Rivette — with Left Bank neighbours Varda and Resnais",
    g: "France, chiefly Paris", p: "1958-1968", era: "late 1950s-1960s",
    sum: "Critics-turned-filmmakers who shot on Paris streets with pocket money, jump cuts and all, making the director an author.",
    desc: "A generation of cinephile critics mounted the auteur policy — the director as author — and then proved it with cheap, fast, personal films. Truffaut's The 400 Blows (1959) and Godard's Breathless (1960) abandoned studio polish for handheld location shooting, direct sound, jump cuts and open endings, quoting American genre movies with ironic tenderness. The Left Bank strand — Agnes Varda's Cleo from 5 to 7 (1962), Resnais's Hiroshima mon amour — braided essay, memory and documentary. Budgets were tiny, crews skeletal, and self-reference part of the grammar. The wave remade world financing and festival culture, scattered into May 68 politics, and remains the default image of what it means to make a personal film.",
    col: [{ h: "#d8d6cf", n: "silver screen grey" }, { h: "#1a1a1c", n: "ink black" }, { h: "#e6dcc3", n: "cafe cream" }, { h: "#6b7d8a", n: "Seine grey-blue" }, { h: "#b3342c", n: "newspaper red" }],
    m: ["Eclair Cameflex cameras", "Paris sidewalks and studios-with-windows", "fast natural-light emulsions", "portable tape sound"],
    tx: ["high-contrast black-and-white grain", "sun-scorched boulevard asphalt", "cigarette smoke in shafts", "jump-cut spatial jumps"],
    obj: ["Cahiers du cinema magazines", "cinematheque tickets", "kiosk newspapers", "petrol-station mirrors", "folded Ray-Ban wayfarers"],
    ex: ["The 400 Blows (Francois Truffaut, 1959)", "Breathless (Jean-Luc Godard, 1960)", "Cleo from 5 to 7 (Agnes Varda, 1962)"],
    inf: ["self-referential indie filmmaking worldwide", "walk-and-talk location coverage"], rel: ["Italian Neorealism", "New Hollywood", "Slow cinema"],
    par: "European art cinema", var: ["Cahiers wave", "Left Bank group", "Rive Gauche essay film"], cf: ["Italian Neorealism", "French poetic realism"],
    src: [{ n: "Wikipedia — French New Wave", u: "https://en.wikipedia.org/wiki/French_New_Wave", t: "B" }, { n: "The Criterion Collection", u: "https://www.criterion.com", t: "A" }],
    tg: ["nouvelle vague", "french new wave", "auteur cinema", "godard", "varda"], pop: 58, niche: false,
    vd: { shape: "cropped faces and long street horizontals", line: "restless handheld jitter", composition: "off-centre portraits, eyeline breaks", texture: "silver halide grain", forms: "sunglasses, newspapers, café tables, posters" },
    typ: { display: "literary serif with strong italic", body: "grotesque sans", notes: "Cahiers page feel" },
    fnt: { display: "Playfair Display", body: "Work Sans", notes: "magazine-critique pairing" },
    lit: { quality: "hard Paris spring sun", direction: "side and backlit walks", temperature: "neutral", shadow: "snappy, hand-shadowed" },
    pho: { approach: "follow-shot street portraits", grade: "bright silver monochrome" },
    fash: { silhouettes: "slim cropped trousers", garments: "beatnik rollnecks, tobacco trench coats, striped tees", acc: "wayfarers, short bangs, gitane cigarettes" },
    env: { places: "Champs-Elysees kiosks, latin quarter cafes, tiny hotel rooms", weather: "bright windy spring" },
    gd: { layout: "asymmetric magazine spread", icon: "film-sprocket underline" },
    ui: { background: "café cream", surface: "silver-grey panels", components: "underline links like pen strokes", motion: "abrupt jump cuts" },
    rec: { materials: "formica, chrome, newsprint", lighting: "window-side table light", objects: "espresso cups, paperbacks, typewriter", music: "michel legrand-style piano turns", scent: "gauloises smoke, coffee, wet gutter" },
    snd: ["typewriter clatter", "café fork-on-saucer", "breathless overlapping dialogue"],
    dna: { mi: 70, og: 90, wc: 25, ns: 30, ad: 20, hf: 30, rr: 45, ps: 65, sh: 55, ql: 75, oc: 60, ds: 55, rs: 40, eu: 90, np: 50 },
    emo: { warm: 55, cold: 45, playful: 65, serious: 45, chaotic: 60, ordered: 35, nostalgic: 70, futuristic: 45, peaceful: 35, ominous: 25 },
  },
  {
    n: "Soviet Montage", a: ["montage theory", "Soviet montage school", "Eisensteinian montage"],
    cat: "Film & Cinema", c: "revolutionary editing movement", e: "historical", o: "Lev Kuleshov's Moscow workshop; Eisenstein, Vertov, Pudovkin within the young Soviet film industry",
    g: "Soviet Russia — Moscow and Leningrad", p: "1924-1930", era: "1920s avant-garde",
    sum: "A school that discovered meaning lives between shots — the Kuleshov effect, Odessa Steps, and a city made to dance for the camera.",
    desc: "With film stock scarce after the revolution, the Kuleshov workshop re-edited existing footage and proved that meaning is manufactured in the join: the same neutral face read as grief or appetite beside different images. Eisenstein theorised montage as collision — intellectual, rhythmic, tonal — and staged the Odessa Steps massacre in Battleship Potemkin (1925) as a machine of shock cuts. Vertov's Man with a Movie Camera (1929) turned editing itself into the hero, exposing splices, cranks and city symphony rhythms. Designers from the constructivist wing supplied aggressive diagonals and photomontage graphics. The school was formally retired by the 1934 socialist realism decree, but its grammar passed into advertising, propaganda and every film school curriculum.",
    col: [{ h: "#c22a1e", n: "constructivist red" }, { h: "#1c1a19", n: "newsprint black" }, { h: "#e8e2d0", n: "newsprint cream" }, { h: "#4a5359", n: "gunmetal" }, { h: "#7d8b94", n: "neva frost" }],
    m: ["scarce raw stock and re-edited prints", "propped city locations", "experimental optical printers", "hand-cut title cards"],
    tx: ["hammered silver grain", "photomontage hard edges", "printed constructivist type", "flicker of hand-cranked frames"],
    obj: ["battleship gun turrets", "odessa stone steps", "hand-cranked cameras", "agitational trains", "montage tables with trims"],
    ex: ["Battleship Potemkin (Sergei Eisenstein, 1925)", "Man with a Movie Camera (Dziga Vertov, 1929)", "Strike (Sergei Eisenstein, 1925)"],
    inf: ["advertising and trailer cutting rhythms", "suspense cross-cutting worldwide"], rel: ["Constructivist Sculpture", "German Expressionism", "French New Wave"],
    par: "European avant-garde film", var: ["intellectual montage", "kino-eye vertovian observation", "linkage montage (pudovkin)"], cf: ["German Expressionism", "classical continuity editing"],
    src: [{ n: "Wikipedia — Soviet montage theory", u: "https://en.wikipedia.org/wiki/Soviet_montage_theory", t: "B" }, { n: "MoMA — The Collection", u: "https://www.moma.org", t: "A" }],
    tg: ["soviet montage", "eisenstein", "kuleshov effect", "dziga vertov", "1920s avant-garde"], pop: 40, niche: false,
    vd: { shape: "diagonal wedges and shock rectangles", line: "vectorised constructivist slash", composition: "collided fragments, no single focal point", texture: "photomontage print grain", forms: "gears, crowds, prams, gun barrels, type blocks" },
    typ: { display: "heavy condensed slab caps", body: "grotesque sans", notes: "agitprop poster hierarchy" },
    fnt: { display: "Anton", body: "IBM Plex Sans", notes: "poster-caps over engineer's sans" },
    lit: { quality: "high-contrast studio arcs", direction: "low raking key light", temperature: "cold-neutral", shadow: "blacked-out with blazing figures" },
    pho: { approach: "dutch-angle crowd choreography", grade: "stark silver with crushed blacks" },
    fash: { silhouettes: "worker rectangle tunics", garments: "peasant blouses, sailor collars, leather director coats", acc: "cloth caps, berets, armbands" },
    env: { places: "granite quays, factory halls, cutting rooms", weather: "white river frost" },
    gd: { layout: "diagonal agitprop grid", icon: "lightning-cut film strip" },
    ui: { background: "newsprint cream", surface: "red-blocked panels", components: "angled banner buttons", motion: "hard slash transitions" },
    rec: { materials: "iron, enamel, paper trims", lighting: "arc-lamp silhouettes", objects: "cutting benches, film tins", music: "industrial percussion overtures", scent: "celluloid, machine oil, print ink" },
    snd: ["projector rattle", "crowd roar cut mid-breath", "brass fanfare stabs"],
    dna: { mi: 80, og: 88, wc: 20, ns: 10, ad: 12, hf: 18, rr: 40, ps: 70, sh: 50, ql: 72, oc: 65, ds: 75, rs: 35, eu: 80, np: 55 },
    emo: { warm: 30, cold: 65, playful: 25, serious: 85, chaotic: 55, ordered: 65, nostalgic: 35, futuristic: 70, peaceful: 15, ominous: 50 },
  },
  {
    n: "Japanese New Wave", a: ["Nuberu bagu", "Japanese New Wave cinema", "Shochiku new wave"],
    cat: "Film & Cinema", c: "studio-rebel film movement", e: "historical", o: "young assistant directors in revolt at Shochiku Ofuna and Nikkatsu, led by Oshima Nagisa; Art Theatre Guild support",
    g: "Japan", p: "late 1950s-early 1970s", era: "postwar Japan",
    sum: "Oshima, Suzuki and peers torched studio decorum with bright-brutal films about youth, sex, crime and the emperor system.",
    desc: "A cluster of young studio rebels — Nagisa Oshima, Yoshishige Yoshida, Masahiro Shinoda at Shochiku, Seijun Suzuki at Nikkatsu — gave Japanese cinema its own New Wave, the Nuberu bagu. Cruel Story of Youth (1960) and The Sun's Burial mapped postwar delinquency onto a country bursting from prosperity into rage; Suzuki's Branded to Kill (1967) flattened the yakuza picture into pop-art anarchy until the studio fired him and students protested. Films interrogated the emperor system, Korean diaspora and student left, favouring wipe cuts, frontal staging, saturated color and black comedy. The Art Theatre Guild gave the movement a second, freer home, and Toshio Matsumoto's Funeral Parade of Roses (1969) fed straight into global counterculture before the movement dissolved into independents around 1972.",
    col: [{ h: "#14121a", n: "night ink" }, { h: "#b02218", n: "sun-burial crimson" }, { h: "#d9c9a3", n: "paper-lantern cream" }, { h: "#3f5a4f", n: "tatami green" }, { h: "#e2e0d8", n: "studio white" }],
    m: ["studio sound stages turned feral", "handheld and whip-pan camera work", "poster-paint pop colour design", "jazz-scored montage sequences"],
    tx: ["high-gloss lacquer surfaces", "neon-bright poster inks", "gritty night-street grain", "graphic wipe transitions"],
    obj: ["tsure-comi motorcycle jackets", "pachinko parlour signs", "iron pipe weapons", "kabuki-style frontal close-ups", "ATG programme booklets"],
    ex: ["Cruel Story of Youth (Nagisa Oshima, 1960)", "Branded to Kill (Seijun Suzuki, 1967)", "Funeral Parade of Roses (Toshio Matsumoto, 1969)"],
    inf: ["Wong Kar-wai and John Woo's stylised rebellions", "queer and punk cinema staging"], rel: ["French New Wave", "Hong Kong action cinema", "Taiwan New Cinema"],
    par: "Japanese studio cinema", var: ["shochiku Ofuna rebellion", "nikkatsu action pop", "ATG independent strand"], cf: ["French New Wave", "Japanese classical (golden age) studio style"],
    src: [{ n: "Wikipedia — Nuberu bagu", u: "https://en.wikipedia.org/wiki/Nuberu_bagu", t: "B" }, { n: "The Criterion Collection", u: "https://www.criterion.com", t: "A" }],
    tg: ["nuberu bagu", "japanese new wave", "oshima nagisa", "seijun suzuki", "atg cinema"], pop: 34, niche: true,
    vd: { shape: "frontal kabuki-framed figures", line: "whip-pan smear lines", composition: "flat pop-art staging, hard graphic wipes", texture: "lacquer gloss vs night grit", forms: "motorbikes, neon signs, paper lanterns, bar mirrors" },
    typ: { display: "brutalist gothic with vertical option", body: "clean gothic sans", notes: "bilingual japanese-latin lockups" },
    fnt: { display: "Zen Kaku Gothic New", body: "Noto Sans JP", notes: "poster-brutal over plain gothic" },
    lit: { quality: "hard bar spots in darkness", direction: "single ruthless key", temperature: "mixed neon-cool and tungsten-hot", shadow: "cut-out noir pools" },
    pho: { approach: "frontal icon portraits against flat colour", grade: "saturated primaries over inky blacks" },
    fash: { silhouettes: "sharp narrow suits", garments: "leather riders, school uniforms as rebellion, yukata twisted glam", acc: "dark glasses, cigarette on lip, berets" },
    env: { places: "all-night coffee houses (junkissa), portside alleys, studio backlots", weather: "humid neon night" },
    gd: { layout: "collaged poster grid with kabuki accents", icon: "slashed circle motif" },
    ui: { background: "night ink", surface: "lantern cream cards", components: "wipe-transition panels", motion: "speed-ramp snap" },
    rec: { materials: "lacquer, chrome, paper screens", lighting: "bare bulb over table", objects: "beer bottles, transistor radio, film stills", music: "hard bop quintet with surf stabs", scent: "kerosene heater, tobacco, tatami" },
    snd: ["rockabilly guitar echo", "studio megaphone bark", "jazz drum roll into silence"],
    dna: { mi: 55, og: 92, wc: 30, ns: 25, ad: 20, hf: 25, rr: 60, ps: 60, sh: 65, ql: 70, oc: 70, ds: 60, rs: 45, eu: 65, np: 45 },
    emo: { warm: 40, cold: 60, playful: 50, serious: 65, chaotic: 70, ordered: 30, nostalgic: 45, futuristic: 55, peaceful: 15, ominous: 65 },
  },
  {
    n: "New Hollywood", a: ["American New Wave", "Hollywood Renaissance", "movie brat era"],
    cat: "Film & Cinema", c: "director-led studio film era", e: "historical", o: "television-trained and film-school directors breaking the old studio packet system (BBS Productions, Warner Bros)",
    g: "United States — Los Angeles and location America", p: "1967-1980", era: "late 1960s-1970s",
    sum: "Between Bonnie and Clyde and Heaven's Gate, young American directors turned the studio film gritty, personal and ambiguous.",
    desc: "As the Production Code collapsed and the old audience defected to television, a new generation seized the means: Bonnie and Clyde (1967), Easy Rider (1969) and MASH (1970) proved outsiders could hit big on location with ambiguous heroes and rock soundtracks. Through the decade Coppola, Scorsese, Altman, Bogdanovich, Friedkin and Malick worked loose, grainy realism — zoom lenses, available dark, offhand profanity, downbeat endings like Chinatown (1974). Personal production companies and presold soundtracks reshaped the business, until Jaws (1975) and Star Wars (1977) built the blockbuster machine and the era closed with the costly failures of 1980. Its look — Kodak amber, dirty skylines, antiheroes in hats — still defines the idea of serious American film.",
    col: [{ h: "#c99a3f", n: "kodak amber" }, { h: "#4a5f6e", n: "steel canyon blue" }, { h: "#d8cbb2", n: "desert khaki" }, { h: "#26221d", n: "asphalt black" }, { h: "#a33c2b", n: "brake-light red" }],
    m: ["zoom lenses and diffused stock", "real Los Angeles locations", "Nagra-synced street sound", "personal-company production logs"],
    tx: ["soft-halation grain", "smog-filtered skylines", "pool-table felt greens", "sun-faded interior plastics"],
    obj: ["lake-hollywood road signs", "payphones", "tailfin sedans", "production office corkboards", "soundtrack LP gatefolds"],
    ex: ["Easy Rider (Dennis Hopper, 1969)", "Chinatown (Roman Polanski, 1974)", "Mean Streets (Martin Scorsese, 1973)"],
    inf: ["indie film financing via presold elements", "prestige-TV moral grey zones"], rel: ["French New Wave", "Film noir", "Spaghetti Western"],
    par: "American studio cinema", var: ["bbs outsider films", "movie brat auteurism", "paranoid-thriller strand"], cf: ["Film noir", "French New Wave"],
    src: [{ n: "Wikipedia — New Hollywood", u: "https://en.wikipedia.org/wiki/New_Hollywood", t: "B" }, { n: "BFI", u: "https://www.bfi.org.uk", t: "A" }],
    tg: ["new hollywood", "hollywood renaissance", "70s cinema", "movie brats", "antihero"], pop: 50, niche: false,
    vd: { shape: "wide dusty horizontals and car-window frames", line: "loose zoom-in emphasis", composition: "characters off-balance in empty thirds", texture: "warm grain with halation", forms: "sedans, diners, venetian blinds, billboards" },
    typ: { display: "condensed poster sans", body: "neutral grotesque", notes: "70s one-sheet energy" },
    fnt: { display: "Fjalla One", body: "Libre Franklin", notes: "billboard condensed over news serif-sans" },
    lit: { quality: "late tungsten and sodium street light", direction: "warm side key through blinds", temperature: "warm amber", shadow: "long, smoky, practical-sourced" },
    pho: { approach: "environmental portraits in available dark", grade: "amber push-processed warmth" },
    fash: { silhouettes: "wide lapels, flared trousers", garments: "corduroy, suede jackets, shirt-dresses", acc: "cowboy hats, aviators, cigarette lighters" },
    env: { places: "strip corridors, canyon houses, parking garages", weather: "smog-golden afternoons" },
    gd: { layout: "painted one-sheet with credits block", icon: "highway route arrow" },
    ui: { background: "asphalt black", surface: "khaki paper cards", components: "ticket-stub buttons", motion: "lazy zoom" },
    rec: { materials: "corduroy, chrome trim, shag", lighting: "piano-bar practicals", objects: "cassette deck, ashtray, call sheet", music: "laurel canyon demos", scent: "leather, gasoline, espresso from craft services" },
    snd: ["car radio drifting between stations", "screen door spring", "understated big-band needle drop"],
    dna: { mi: 45, og: 78, wc: 35, ns: 25, ad: 18, hf: 22, rr: 55, ps: 60, sh: 55, ql: 72, oc: 55, ds: 50, rs: 45, eu: 55, np: 40 },
    emo: { warm: 60, cold: 50, playful: 40, serious: 70, chaotic: 55, ordered: 35, nostalgic: 65, futuristic: 35, peaceful: 25, ominous: 55 },
  },
  {
    n: "Dogme 95", a: ["Dogme collective", "Dogme film movement", "vow of chastity cinema"],
    cat: "Film & Cinema", c: "purist filmmaking manifesto movement", e: "historical", o: "Lars von Trier and Thomas Vinterberg, proclaimed at a Paris cinema conclave in 1995",
    g: "Denmark — Copenhagen; adopted internationally", p: "1995-2005", era: "1990s-2000s",
    sum: "A ten-rule 'Vow of Chastity' that banned lights, props and gimmicks — and accidentally birthed the handheld lo-fi revolution.",
    desc: "Announced in Paris in 1995 with red prospectuses, the Dogme 95 manifesto by Lars von Trier and Thomas Vinterberg demanded location shooting, no imported props, no artificial light, no filters, no superficial action, no genre trappings and no on-screen credits, signed as a Vow of Chastity. Vinterberg's Festen (1998) and von Trier's The Idiots (1998) proved the rules could detonate melodrama; 35 numbered certificates followed, from Italian for Beginners (2000) to 2005, with confessing directors trading rule-breaks in secret annexes. The washed video-grain look read as truth in an era of CGI overload and seeded found-footage and smartphone-native realism. The collective disbanded quietly, but its certificate system remains cinema's most famous aesthetic contract.",
    col: [{ h: "#c9c2ad", n: "video-transfer beige" }, { h: "#9aa0a0", n: "fluorescent grey" }, { h: "#b9786a", n: "skin flush red" }, { h: "#5e6b5d", n: "corridor green" }, { h: "#2e2a24", n: "dim room brown" }],
    m: ["available light only", "handheld cameras with on-camera sound", "real locations and found furnishings", "compact 35mm or video transfer"],
    tx: ["flat fluorescent falloff", "camera-noise grain", "crease of real upholstery", "blown window highlights"],
    obj: ["red manifesto prospectuses", "dogme certificates with numbers", "birthday party tables", "airport corridors", "boom-box party sound"],
    ex: ["Festen / The Celebration (Thomas Vinterberg, 1998)", "The Idiots (Lars von Trier, 1998)", "Italian for Beginners (Lone Scherfig, 2000)"],
    inf: ["found-footage believability conventions", "smartphone-native filmmaking norms"], rel: ["Slow cinema", "cinema verite documentary", "Mumblecore"],
    par: "European art cinema", var: ["dogme certificate films", "annex-confessed rule-breaks", "lo-fi danish realist strand"], cf: ["cinema verite documentary", "found footage horror"],
    src: [{ n: "Wikipedia — Dogme 95", u: "https://en.wikipedia.org/wiki/Dogme_95", t: "B" }, { n: "BFI", u: "https://www.bfi.org.uk", t: "A" }],
    tg: ["dogme 95", "vow of chastity", "lo-fi cinema", "danish film", "von trier"], pop: 30, niche: true,
    vd: { shape: "unsteady close crops", line: "no visible authorship lines", composition: "subjects pushed against the lens", texture: "video noise and skin blotch", forms: "doorways, banquet tables, hands, corridors" },
    typ: { display: "typewriter mono", body: "mono sans", notes: "manifesto certificate tone" },
    fnt: { display: "Special Elite", body: "IBM Plex Mono", notes: "typed contract over clinical mono" },
    lit: { quality: "soulless interior fluorescents", direction: "top-down flat", temperature: "cold green-tinged", shadow: "none where lights can't reach" },
    pho: { approach: "claustrophobic handheld pursuit", grade: "washed beige with green cast" },
    fash: { silhouettes: "ordinary daily cuts", garments: "office shirts, knit cardigans, hospital linens", acc: "wristwatches, eyeglasses, nothing styled" },
    env: { places: "family houses, institutional halls, airports", weather: "flat northern drizzle" },
    gd: { layout: "typed manifesto page", icon: "red seal stamp" },
    ui: { background: "beige paper", surface: "grey form fields", components: "checkbox list", motion: "document flicker" },
    rec: { materials: "laminate, polyester, party balloons", lighting: "ceiling bulbs unshielded", objects: "cassette recorder, wine glasses, dogme booklet", music: "diegetic only — singing, radio, footsteps", scent: "cold coffee, upholstery, rain on coats" },
    snd: ["camera motor whir", "off-mic mumbling", "sheet rain on windows"],
    dna: { mi: 40, og: 82, wc: 10, ns: 8, ad: 8, hf: 10, rr: 35, ps: 65, sh: 40, ql: 55, oc: 50, ds: 65, rs: 20, eu: 80, np: 50 },
    emo: { warm: 45, cold: 60, playful: 25, serious: 80, chaotic: 55, ordered: 55, nostalgic: 25, futuristic: 30, peaceful: 25, ominous: 60 },
  },
  {
    n: "Spaghetti Western", a: ["Euro western", "Italo-Western", "macaroni western"],
    cat: "Film & Cinema", c: "European genre film wave", e: "historical", o: "Italian producers shooting cheap westerns for world markets; Sergio Leone's partnership with Ennio Morricone",
    g: "Italy (Cinecitta, Lazio quarries) and Spain (Almeria)", p: "1964-1976 (peak)", era: "1960s",
    sum: "Sun-flayed faces, $50,000 budgets and Morricone whistling — the Italian western that turned the genre cruel, ironic and operatic.",
    desc: "When A Fistful of Dollars (1964) recycled a Kurosawa plot through an American TV actor in Spanish stone deserts, Italian producers found a genre factory: several hundred Eurowesterns followed within a decade. Sergio Leone choreographed seconds into minutes — eyes, gun barrels, flies — while Ennio Morricone's scores used whips, coyote howls, wordless wails and jew's harps as narrative. Characters were amoral bounty men in dust-caked ponchos, dubbed in post because crews were multilingual, shot in wide Academy-framed closeups under blistering sun. Corbucci's Django (1966) dragged a coffin behind him; the wave turned revisionist, political and gruesome before dying out around 1976. Leone's grammar colonised action cinema, music videos and Tarantino outright.",
    col: [{ h: "#d9b878", n: "sun-bleached sand" }, { h: "#c2743a", n: "dust orange" }, { h: "#3a2418", n: "shadow brown" }, { h: "#8e2418", n: "dried blood red" }, { h: "#b98a3a", n: "ammo brass" }],
    m: ["anamorphic widescreen lenses", "almerian badlands and quarry sets", "post-production dubbing loops", "morricone orchestration with found percussion"],
    tx: ["heat-shimmer haze", "sun-scoured adobe texture", "sweat-stiffened canvas", "scratched print grain"],
    obj: ["cigarillos", "coffin sidecars", "poncho serapes", "trembling closeup eyes", "gold-wagon payrolls"],
    ex: ["A Fistful of Dollars (Sergio Leone, 1964)", "The Good, the Bad and the Ugly (Sergio Leone, 1966)", "Django (Sergio Corbucci, 1966)"],
    inf: ["modern action scoring built on voices and drones", "revisionist antihero westerns"], rel: ["New Hollywood", "Film noir", "Giallo"],
    par: "European genre cinema", var: ["leone dollars trilogy", "corbucci macaroni brutality", "comic django-sartana imitators"], cf: ["American classical western", "Giallo"],
    src: [{ n: "Wikipedia — Spaghetti Western", u: "https://en.wikipedia.org/wiki/Spaghetti_Western", t: "B" }, { n: "The Criterion Collection", u: "https://www.criterion.com", t: "A" }],
    tg: ["spaghetti western", "sergio leone", "ennio morricone", "eurowestern", "almeria"], pop: 55, niche: false,
    vd: { shape: "extreme closeups against vast flats", line: "hard sun edge on skin", composition: "three-way standoff symmetries", texture: "dust bloom and sweat speculars", forms: "hats, gun grips, rope, ribs of wind-worn rock" },
    typ: { display: "slab western poster caps", body: "rustic serif", notes: "wanted-poster energy" },
    fnt: { display: "Rye", body: "Bitter", notes: "ornamented western over sturdy slab" },
    lit: { quality: "merciless noon sun", direction: "vertical top light, eyes kept in shadow", temperature: "hot", shadow: "black under hat brims" },
    pho: { approach: "blink-less face standoff inserts", grade: "bleached amber with burning highlights" },
    fash: { silhouettes: "draped poncho over long duster", garments: "dust-caked waistcoats, shotgun sleeves", acc: "cigarillos, bandoliers, wide-brim hats" },
    env: { places: "almerian dry riverbeds, adobe pueblos, mission ruins", weather: "white heat and dust wind" },
    gd: { layout: "stacked wanted-poster panels", icon: "crossed revolver mark" },
    ui: { background: "sand tan", surface: "parchment cards", components: "rope-line dividers", motion: "slow burn-in" },
    rec: { materials: "adobe, sun-bleached wood, canvas", lighting: "single lantern at night", objects: "revolvers, watches, mescal bottles", music: "whistled theme over brushed guitar", scent: "dust, gun oil, horse sweat" },
    snd: ["whip crack", "coyote howl", "spurs on stone"],
    dna: { mi: 30, og: 85, wc: 40, ns: 20, ad: 15, hf: 20, rr: 60, ps: 55, sh: 65, ql: 68, oc: 60, ds: 55, rs: 40, eu: 70, np: 45 },
    emo: { warm: 70, cold: 40, playful: 30, serious: 65, chaotic: 50, ordered: 45, nostalgic: 50, futuristic: 15, peaceful: 15, ominous: 70 },
  },
  {
    n: "Technicolor musicals", a: ["MGM Freed Unit musicals", "Golden Age movie musical", "three-strip Technicolor song films"],
    cat: "Film & Cinema", c: "studio musical film style", e: "historical", o: "Arthur Freed's production unit at MGM, carrying Busby Berkeley's spectacle into integrated narrative song",
    g: "Hollywood, USA", p: "c. 1939-1958", era: "Golden Age Hollywood",
    sum: "Candy-saturated three-strip dream factories — Kelly splashing through rain, Minnelli's neon ballets — the musical at maximum color.",
    desc: "From the late 1930s three-strip Technicolor let studios build whole worlds out of dye-imbibed primaries, and MGM's Arthur Freed Unit perfected the genre film that sings. Meet Me in St. Louis (1944), An American in Paris (1951) and Singin' in the Rain (1952) integrated songs into plot, choreographed by Gene Kelly and Stanley Donen in single-take tracking flourishes, while Vincente Minnelli designed sets as palette-saturated abstract paintings. Costume designers from Adrian to Cecil Beaton treated gowns as light sources; production designers matched walls, lampshades and umbrellas to them. The form faded as television flattened budgets and widescreen experiment replaced the backlot, but its candy-box color science and camera-dance choreography still govern movie-musical craft and music-video staging.",
    col: [{ h: "#e0444a", n: "poppy red" }, { h: "#f2c14e", n: "marigold" }, { h: "#3f7d64", n: "emerald raincoat" }, { h: "#7a5fa0", n: "lilac stage wash" }, { h: "#f5efe0", n: "arcade ivory" }],
    m: ["three-strip Technicolor camera work", "studio backlot street sets", "hundred-gown costume inventories", "pre-recorded playback vocal tracks"],
    tx: ["hyper-saturated dye clouds", "glossy lacquered floors", "tulle and satin sheen", "soft theatrical vignette"],
    obj: ["lampposts in rain", "showgirl headdresses", "piano-key keyboards", "sheet-music title cards", "revolving stage wagons"],
    ex: ["Singin' in the Rain (Kelly & Donen, 1952)", "An American in Paris (Vincente Minnelli, 1951)", "Meet Me in St. Louis (Vincente Minnelli, 1944)"],
    inf: ["modern movie-musical color design", "music-video choreography staging"], rel: ["Art Deco", "New Hollywood", "classic Broadway revue"],
    par: "American studio cinema", var: ["freed-unit integrated musical", "minnelli fantasy ballets", "berkeley geometric spectacle"], cf: ["classic Broadway revue", "backstage melodrama films"],
    src: [{ n: "Wikipedia — Musical film", u: "https://en.wikipedia.org/wiki/Musical_film", t: "B" }, { n: "BFI", u: "https://www.bfi.org.uk", t: "A" }],
    tg: ["technicolor", "mgm musical", "freed unit", "gene kelly", "golden age"], pop: 38, niche: false,
    vd: { shape: "symmetrical proscenium arches", line: "ribboning choreography trails", composition: "centered star with synchronized chorus", texture: "dyed-satin glow", forms: "umbrellas, top hats, garlands, carousels" },
    typ: { display: "art-deco marquee caps", body: "rounded geometric sans", notes: "marquee billing order" },
    fnt: { display: "Limelight", body: "Jost", notes: "deco marquee over geometric sans" },
    lit: { quality: "even glamour key with fill everywhere", direction: "butterfly top-front light", temperature: "warm", shadow: "sculpted, never dirty" },
    pho: { approach: "choreographed tableau capture", grade: "full-saturation candy primaries" },
    fash: { silhouettes: "nipped-waist gowns and white-tie tails", garments: "tulle skirts, satin gowns, straw boaters", acc: "feather fans, gloves, two-tone brogues" },
    env: { places: "backlot main streets, sound-stage ballrooms", weather: "stage-made rain and confetti" },
    gd: { layout: "centered billing marquee", icon: "art-deco sunburst" },
    ui: { background: "arcade ivory", surface: "candy-red cards", components: "marquee-bulb borders", motion: "curtain-wipe reveal" },
    rec: { materials: "satin, lacquer, brass", lighting: "piano-bar warmth with stage wash", objects: "upright piano, sheet music, top hats", music: "overture into tap break", scent: "greasepaint, rose water, rain on hot pavement" },
    snd: ["tap-shoe rolls", "orchestra swell", "stage-wind before curtain"],
    dna: { mi: 50, og: 72, wc: 30, ns: 15, ad: 15, hf: 25, rr: 45, ps: 70, sh: 60, ql: 80, oc: 70, ds: 40, rs: 35, eu: 55, np: 35 },
    emo: { warm: 80, cold: 20, playful: 85, serious: 30, chaotic: 30, ordered: 70, nostalgic: 85, futuristic: 25, peaceful: 45, ominous: 5 },
  },
  {
    n: "Iranian New Wave", a: ["Iranian New Wave cinema", "Persian New Wave film"],
    cat: "Film & Cinema", c: "poetic-realist film movement", e: "historical", o: "Forugh Farrokhzad's documentary work, Dariush Mehrjui's The Cow; second wave led by Kiarostami and Makhmalbaf",
    g: "Iran — Tehran, the Koker villages of Gilan", p: "1969-1990s (two waves)", era: "pre- and post-revolution",
    sum: "Two movements of Iranian cinema that turned censorship and simplicity into elliptical, deeply humane masterworks.",
    desc: "The first Iranian New Wave arrived in 1969 when Mehrjui's The Cow — a peasant who becomes his dead animal — and Kimiai's Qeysar forged a national modernism; it was cut short by the 1979 revolution. The second wave rebuilt under strict codes as the cinema of children and village paths: Kiarostami's Koker trilogy, from Where Is the Friend's House? (1987), used non-professional actors, long perspectival roads and unresolved questions, then folded fiction and documentary in Close-Up (1990). Makhmalbaf, his daughter Samira and Jafar Panahi turned constraint into ellipsis — offscreen violence, symbolic doubling, fable logic. By the mid-1990s the movement had become festival cinema's moral centre and its minimalism reshaped world film's idea of what a story could withhold.",
    col: [{ h: "#c98d6b", n: "dust-rose plain" }, { h: "#7a7d4a", n: "olive field" }, { h: "#efe7d6", n: "whitewash" }, { h: "#8a5c3c", n: "mud-brick brown" }, { h: "#1c1a19", n: "chador ink" }],
    m: ["wind-up location silence and direct sound", "schoolroom and hillside found sets", "non-professional village performers", "16mm-derived poetic minimalism"],
    tx: ["sun-bleached earth texture", "grain of schoolroom chalk", "wind tremor in fields", "patient static frames"],
    obj: ["zigzag hillside paths", "exercise notebooks", "broken flowerpots", "school gates", "doorway shadows"],
    ex: ["The Cow (Dariush Mehrjui, 1969)", "Where Is the Friend's House? (Abbas Kiarostami, 1987)", "Close-Up (Abbas Kiarostami, 1990)"],
    inf: ["world-cinema minimalism and festival realism", "docufiction hybrid methods"], rel: ["Slow cinema", "Italian Neorealism", "Dogme 95"],
    par: "world art cinema", var: ["koker realist strand", "makhmalbaf house fable style", "pre-revolution social melodrama"], cf: ["Slow cinema", "Italian Neorealism"],
    src: [{ n: "Wikipedia — Iranian New Wave", u: "https://en.wikipedia.org/wiki/Iranian_New_Wave", t: "B" }, { n: "The Criterion Collection", u: "https://www.criterion.com", t: "A" }],
    tg: ["iranian new wave", "kiarostami", "koker trilogy", "iranian cinema", "makhmalbaf"], pop: 31, niche: true,
    vd: { shape: "long receding zigzag lines to a single figure", line: "contour of dirt paths", composition: "off-centre child in vast frame", texture: "dust, chalk, plaster", forms: "doors, notebooks, olive shrubs, shadow ellipses" },
    typ: { display: "elegant naskh-derived face", body: "quiet humanist sans", notes: "bilingual Persian-Latin setting" },
    fnt: { display: "Vazirmatn", body: "Noto Naskh Arabic", notes: "native Persian rendering, airy weights" },
    lit: { quality: "high mountain-plain sun", direction: "overhead, then long dusk raking", temperature: "warm-dry", shadow: "single doorway cut of dark" },
    pho: { approach: "patient deep-focus landscape with small figures", grade: "dusty warm neutrals" },
    fash: { silhouettes: "simple geometric drapes", garments: "school smocks, headscarves, woolen tassel cloaks", acc: "plastic sandals, notebooks, keys on string" },
    env: { places: "koker hill paths, tehran peripheries, village classrooms", weather: "dry wind, high thin sun" },
    gd: { layout: "single-line path diagram", icon: "zigzag road glyph" },
    ui: { background: "whitewash", surface: "dust-rose cards", components: "thin underline nav", motion: "slow fade hold" },
    rec: { materials: "mud brick, jute, tin", lighting: "one high window", objects: "chalk, watering can, film canisters", music: "setar phrase, then ambient village hum", scent: "dust, rain on dry earth, school paste" },
    snd: ["distant rooster", "children reciting in unison", "wind through olive scrub"],
    dna: { mi: 55, og: 85, wc: 12, ns: 10, ad: 10, hf: 12, rr: 45, ps: 60, sh: 50, ql: 75, oc: 60, ds: 60, rs: 25, eu: 65, np: 55 },
    emo: { warm: 65, cold: 40, playful: 45, serious: 75, chaotic: 25, ordered: 55, nostalgic: 65, futuristic: 15, peaceful: 60, ominous: 40 },
  },
  {
    n: "Hong Kong action cinema", a: ["HK action film", "heroic bloodshed cinema", "kung fu golden age film culture"],
    cat: "Film & Cinema", c: "action genre tradition", e: "historical", o: "Shaw Brothers studio system and the kung fu revival; John Woo's 1980s heroic bloodshed",
    g: "Hong Kong", p: "1960s-1990s (golden age 1985-1994)", era: "studio era to handover era",
    sum: "Balletic kung fu, gun-fu melodrama and stuntmen flying through plate glass — the most influential action grammar ever built.",
    desc: "Hong Kong industrialised screen violence: Shaw Brothers' swordplay epics like The One-Armed Swordsman (1967) trained a stunt ecosystem, the kung fu boom of the early 70s globalised it, and Jackie Chan's Police Story (1985) fused slapstick with real, insured-by-nobody falls. John Woo's heroic bloodshed — A Better Tomorrow (1986), The Killer, Hard Boiled — remade the gangster film as gun-melodrama with doves, trench coats and two-fisted loyalty codes, cut with the island's famous speed: shoot first, pre-plan everything, and let the cameraman be a stuntman. Tsui Hark's wirework fantasy and category-III grit filled out the scene until the 1997 handover drained talent to Hollywood, where The Matrix openly bought the grammar whole.",
    col: [{ h: "#1d2733", n: "midnight blue" }, { h: "#e0a13c", n: "sodium orange" }, { h: "#b3342c", n: "temple red" }, { h: "#e8e3d5", n: "nightclub white" }, { h: "#2e6e5a", n: "jade green" }],
    m: ["wire-rigging harnesses", "breakaway glass and squibs", "multi-camera live-recorded fight takes", "neon-drenched practical locations"],
    tx: ["sweat-slick skin speculars", "muzzle-flash strobe", "shattered glass confetti", "molasses-slow bullet time before the term"],
    obj: ["twin Berettas", "bamboo scaffolding", "mahjong parlour tables", "chopstick-through-palm set pieces", "neon sign canyons"],
    ex: ["A Better Tomorrow (John Woo, 1986)", "Police Story (Jackie Chan, 1985)", "Hard Boiled (John Woo, 1992)"],
    inf: ["bullet-time and pre-viz action design worldwide", "stunt-team choreography as spectacle"], rel: ["New Hollywood", "Spaghetti Western", "wuxia swordplay tradition"],
    par: "Asian genre cinema", var: ["shaw brothers swordplay", "kung fu comedy", "heroic bloodshed gun melodrama"], cf: ["wuxia swordplay tradition", "Japanese chambara"],
    src: [{ n: "Wikipedia — Hong Kong action cinema", u: "https://en.wikipedia.org/wiki/Hong_Kong_action_cinema", t: "B" }, { n: "The Criterion Collection", u: "https://www.criterion.com", t: "A" }],
    tg: ["hong kong action", "heroic bloodshed", "john woo", "jackie chan", "kung fu"], pop: 48, niche: false,
    vd: { shape: "diagonal action vectors and glass-shard bursts", line: "speed-blurred tracking arcs", composition: "staggered multi-plane depth in narrow streets", texture: "wet asphalt neon reflections", forms: "revolvers, doves, trench coats, neon kanji signs" },
    typ: { display: "brush-weight display face", body: "compact grotesque", notes: "bilingual HK poster lockups" },
    fnt: { display: "Bebas Neue", body: "Noto Sans HK", notes: "poster impact with CJK fallback" },
    lit: { quality: "neon-pierced night air", direction: "hard single source in blackness", temperature: "cool with hot flashes", shadow: "gunmetal deep-field" },
    pho: { approach: "kinetic low-angle mayhem coverage", grade: "cyan shadow, orange practical" },
    fash: { silhouettes: "long-trench dramatics vs bare-torso agility", garments: "dusters, mandarin-collar jackets, school-inspired leathers", acc: "toothpicks, sunglasses at night, amulets" },
    env: { places: "kowloon markets, container docks, rooftop hairpin roads", weather: "steaming monsoon night" },
    gd: { layout: "collaged action-poster burst", icon: "lightning gun glyph" },
    ui: { background: "midnight blue", surface: "jade glass cards", components: "shard-cut buttons", motion: "whip-pan slide" },
    rec: { materials: "chrome, bamboo, cracked plaster", lighting: "sign-spill neon", objects: "milk bottles, shotguns, folded newspapers", music: "synth-brass themes over rock guitar", scent: "char siu smoke, rain, cordite" },
    snd: ["glass sheet detonation", "shell casing rain", "saxophone over gunfight"],
    dna: { mi: 40, og: 88, wc: 35, ns: 25, ad: 20, hf: 20, rr: 65, ps: 65, sh: 70, ql: 65, oc: 60, ds: 55, rs: 50, eu: 55, np: 40 },
    emo: { warm: 60, cold: 45, playful: 55, serious: 55, chaotic: 75, ordered: 35, nostalgic: 55, futuristic: 50, peaceful: 10, ominous: 60 },
  },
  {
    n: "Slow cinema", a: ["contemplative cinema", "minimalist festival cinema"],
    cat: "Film & Cinema", c: "contemplative festival film movement", e: "historical", o: "festival circuit descended from Tarr Bela, Tsai Ming-liang and Apichatpong; term popularised by critics around 2010",
    g: "Hungary, Taiwan, Mexico, Philippines — the global festival circuit", p: "late 1980s-present; named in the 2010s", era: "contemporary",
    sum: "Long takes, real duration, weather as plot — cinema that refuses the cut and asks the viewer to simply stay.",
    desc: "Slow cinema names a strain of festival film that privileges duration over event: static or glacially moving long takes, ambient sound, non-professional actors and real-time passages in which weather, labour or a single corridor is the action. Bela Tarr's Satantango (1994) ran seven hours in thirty-nine takes; Tsai Ming-liang, Lav Diaz, Pedro Costa and Apichatpong Weerasethakul built comparable vocabularies of duration, ruin and sleep. Critics around 2010 — and academics like Song Hwee Lim — codified the label, debating it as resistance to attention economies rather than a genre. Projected in festivals and galleries, often financed by European co-production funds, it remains the contemporary benchmark for what film duration can still risk.",
    col: [{ h: "#cfc4a5", n: "wheat haze" }, { h: "#7d8b8a", n: "well-water grey" }, { h: "#23211f", n: "coal smoke" }, { h: "#a9c2b2", n: "hospital mint" }, { h: "#c98d4a", n: "tungsten amber" }],
    m: ["locked-off tripod or slow dolly", "available weather light", "non-professional ensemble", "direct ambient sound recording"],
    tx: ["deep-focus stillness", "breath of rain in air", "wall damp and rust bloom", "long silences with grain"],
    obj: ["empty roads", "coal stoves", "hospital corridors", "moored boats", "single hanging bulbs"],
    ex: ["Satantango (Bela Tarr, 1994)", "Uncle Boonmee Who Can Recall His Past Lives (Apichatpong, 2010)", "Vitalina Varela (Pedro Costa, 2019)"],
    inf: ["gallery moving-image duration norms", "essay-film and slow-TV formats"], rel: ["Iranian New Wave", "Italian Neorealism", "Dogme 95"],
    par: "world art cinema", var: ["tarr elemental duration", "diaz epic daylong form", "costa cape verdean portrait style"], cf: ["meditation on documentary", "Iranian New Wave"],
    src: [{ n: "Wikipedia — Slow cinema", u: "https://en.wikipedia.org/wiki/Slow_cinema", t: "B" }, { n: "BFI", u: "https://www.bfi.org.uk", t: "A" }],
    tg: ["slow cinema", "contemplative film", "bela tarr", "long take", "festival cinema"], pop: 30, niche: true,
    vd: { shape: "long horizontal stillness", line: "minimal horizon rule", composition: "figure absorbed into environment depth", texture: "weather grain over frame", forms: "roads, fog, steam, doorway light, water" },
    typ: { display: "quiet literata serif", body: "airy grotesque sans", notes: "programme-note restraint" },
    fnt: { display: "Spectral", body: "Karla", notes: "contemplative serif, low-contrast sans" },
    lit: { quality: "overcast natural suffusion", direction: "soft environmental fill", temperature: "cool-neutral with ember exceptions", shadow: "long ambient dusk" },
    pho: { approach: "fixed-camera duration portraits", grade: "muted naturalism, lifted blacks" },
    fash: { silhouettes: "working drape and layers", garments: "heavy coats, rubber boots, house dresses", acc: "scarves, thermos flasks, reading glasses" },
    env: { places: "ruined tenements, steppe roads, riverbanks", weather: "fog, drizzle, thaw" },
    gd: { layout: "single image, vast margin", icon: "thin horizon line" },
    ui: { background: "well-water grey", surface: "paper with no shadow", components: "text-only nav", motion: "one slow crossfade per session" },
    rec: { materials: "raw concrete, coal, wet wood", lighting: "one bare bulb in a large dark", objects: "kettle, oil lamp, wristwatch", music: "ambient room tone only", scent: "coal smoke, wet wool, old plaster" },
    snd: ["wind across waste ground", "dripping pipe", "distant train"],
    dna: { mi: 60, og: 78, wc: 12, ns: 10, ad: 8, hf: 10, rr: 40, ps: 55, sh: 45, ql: 80, oc: 65, ds: 55, rs: 20, eu: 70, np: 60 },
    emo: { warm: 40, cold: 60, playful: 10, serious: 80, chaotic: 10, ordered: 70, nostalgic: 60, futuristic: 20, peaceful: 75, ominous: 35 },
  },
  {
    n: "Shoegaze", a: ["shoegazing", "the scene that celebrates itself", "shoegazer"],
    cat: "Music & Sonic Culture", c: "guitar-effects subculture", e: "community_subculture", o: "British indie scene around My Bloody Valentine, Ride, Slowdive and Lush, press-named by the NME",
    g: "UK — Oxford, Reading, Thames Valley, London", p: "1988-1994 (revival from 2010s)", era: "late 1980s-1990s",
    sum: "Guitarists staring down at pedalboards while walls of tremolo and fuzz bury the voice — the loudest dream pop ever staged.",
    desc: "The British weekly press coined 'shoegazing' in 1990 to mock bands who gazed at effects pedals instead of the crowd, and the sneer named a sound: layer upon layer of tremolo, fuzz and reversed reverb with vocals mixed as another instrument. My Bloody Valentine's Loveless (1991) — famously expensive and built on glide-guitar tremolo bars — became the genre's monolith, flanked by Ride's Nowhere (1990) and Slowdive's Souvlaki (1993). Scene politics were acrimonious: journalists framed it against the ladish Madchester scene as 'the scene that celebrates itself'. Britpop's swagger and label consolidation buried the wave by 1994, but the 2010s revival — Slowdive's reunion, DIIV, blackgaze offshoots — turned it into a durable global template for immersive, effects-driven guitar music.",
    col: [{ h: "#c98d94", n: "blush rose" }, { h: "#7a6b9a", n: "reverb violet" }, { h: "#2a2f4a", n: "fuzz navy" }, { h: "#c9ccd4", n: "starmap silver" }, { h: "#a13a3a", n: "bleed red" }],
    m: ["tremolo-arm Fender Jaguars and Jazzmasters", "wall-of-pedal boards (fuzz, reverb, delay)", "vinyl LPs and CD longboxes", "four-track demo cassettes"],
    tx: ["harsh pedal-fuzz blur", "velvet curtain depth", "analogue tape warble", "smoke-machine stage haze"],
    obj: ["pedalboards dense with knobs", "downcast stares under spotlights", "faded band tees from Creation Records", "vinyl pressings of Loveless", "smoke-filled student unions"],
    ex: ["Loveless (My Bloody Valentine, 1991)", "Nowhere (Ride, 1990)", "Souvlaki (Slowdive, 1993)"],
    inf: ["blackgaze and post-metal atmospherics", "bedroom dream-pop production"], rel: ["Madchester", "C86 indie pop", "dream pop"],
    par: "indie guitar culture", var: ["early creation records noise-pop", "slowdive melodic strand", "blackgaze fusion"], cf: ["dream pop", "Madchester"],
    src: [{ n: "Wikipedia — Shoegaze", u: "https://en.wikipedia.org/wiki/Shoegaze", t: "B" }, { n: "Pitchfork", u: "https://pitchfork.com", t: "B" }],
    tg: ["shoegaze", "my bloody valentine", "noise pop", "creation records", "dream pop"], pop: 45, niche: false,
    vd: { shape: "soft-focus concentric blooms", line: "no hard edges — bleed everywhere", composition: "band obscured by haze and backlight", texture: "overexposed velvet", forms: "pedals, smoke, closed eyes, starfields" },
    typ: { display: "low-contrast elegant serif", body: "rounded humanist sans", notes: "fanzine whisper tone" },
    fnt: { display: "Fraunces", body: "Space Grotesk", notes: "hazy serif over modern sans" },
    lit: { quality: "blinded backlights through smoke", direction: "rear wash, faces erased", temperature: "cool violet", shadow: "dissolved edges" },
    pho: { approach: "motion-smeared stage haze photography", grade: "lifted blacks, rose-violet cast" },
    fash: { silhouettes: "shapeless layered drape", garments: "oversized jumpers, floral sundresses under leather, corduroy", acc: "bowl cuts, canvas sneakers (the gaze), fender straps" },
    env: { places: "student unions, riverside rehearsal rooms", weather: "grey english drizzle" },
    gd: { layout: "blurred centre-vortex poster", icon: "concentric ripple ring" },
    ui: { background: "fuzz navy", surface: "rose-mist cards", components: "soft glow buttons", motion: "slow fade-blur transitions" },
    rec: { materials: "velour, smoke, chrome pedal shells", lighting: "single backlight in fog", objects: "pedals, earplugs, setlists", music: "the actual wall of sound, vocals underwater", scent: "incense, cold rain, hot valve dust" },
    snd: ["tremolo dive-bomb", "high-frequency feedback bloom", "whispered double-tracked vocal"],
    dna: { mi: 50, og: 85, wc: 30, ns: 30, ad: 15, hf: 25, rr: 55, ps: 65, sh: 60, ql: 70, oc: 65, ds: 45, rs: 40, eu: 75, np: 45 },
    emo: { warm: 45, cold: 55, playful: 30, serious: 45, chaotic: 50, ordered: 35, nostalgic: 75, futuristic: 55, peaceful: 55, ominous: 35 },
  },
  {
    n: "Witch house", a: ["drag (microgenre)", "screwgaze", "occult electronic microgenre"],
    cat: "Music & Sonic Culture", c: "dark electronic microgenre", e: "community_subculture", o: "Salem, Pictureplane, oOoOO and the Triangle scene, distributed via blogs and Tumblr",
    g: "US internet culture (Providence, Portland) with global blog scenes", p: "2009-2013", era: "blog-house era",
    sum: "Chopped-and-screwed hip-hop slowed into occult fog, branded with triangles, Unicode and MySpace-era black magic.",
    desc: "Witch house was a 2009-2013 internet microgenre that pitched slowed, chopped-and-screwed hip-hop behind haze-drenched synths and screamed-through-reverb vocals, distributed as MP3s across Tumblr, SoundCloud and Last.fm rather than labels. Salem's King Night (2010) and Pictureplane's Dark Rift (2009) anchored the canon while oOoOO, White Ring and Ritualz spread the fog; fans and artists coded the look with triangles, crosses, inverted symbols and Unicode names like ▲. The alias 'drag' and 'screwgaze' circulated alongside; critics doubted its coherence and the scene flamed out by 2013. Its true legacy was method: net-native aesthetic tribalism, slowed tempos as mood, and typography-as-brand — all inherited by vaporwave and the dark-synth diaspora.",
    col: [{ h: "#0e0d12", n: "void black" }, { h: "#6b3fa0", n: "UV violet" }, { h: "#e8e6e2", n: "chalk white" }, { h: "#b0182a", n: "ritual red" }, { h: "#3aa09a", n: "witch teal" }],
    m: ["cracked software and DAW presets", "MP3 blog distribution", "chopped-and-screwed vinyl technique", "tumblr GIF and glitch art"],
    tx: ["low-bit digital smear", "purpled haze gradient", "vhs tracking noise", "occult symbol overlay"],
    obj: ["triangle glyphs", "inverted crosses", "screwed-pitch mixtape covers", "blacklight posters", "unicode type as sigil"],
    ex: ["King Night (Salem, 2010)", "Dark Rift (Pictureplane, 2009)", "oOoOO self-titled EP (Tri Angle, 2010)"],
    inf: ["vaporwave's net-native typography", "slowed-and-reverb playlist culture"], rel: ["Vaporwave", "chopped and screwed Houston culture", "Chillwave"],
    par: "internet microgenres", var: ["salem fog-rap strand", "tri angle ethereal wing", "euro occult techno branch"], cf: ["Vaporwave", "industrial goth culture"],
    src: [{ n: "Wikipedia — Witch house", u: "https://en.wikipedia.org/wiki/Witch_house", t: "B" }, { n: "Pitchfork", u: "https://pitchfork.com", t: "B" }],
    tg: ["witch house", "salem", "screwgaze", "triangle gang", "blog era"], pop: 26, niche: true,
    vd: { shape: "hard triangles in soft fog", line: "1px white sigil strokes", composition: "central occult sigil over gradient void", texture: "digital grain and tracking error", forms: "triangles, crosses, warped faces, static fields" },
    typ: { display: "occult display or glitched pixel face", body: "narrow techno sans", notes: "unicode symbols as decoration" },
    fnt: { display: "Metal Mania", body: "VT323", notes: "blackletter-aggression over terminal pixel" },
    lit: { quality: "blacklight UV only", direction: "under-glow from screens", temperature: "cold violet", shadow: "absolute black" },
    pho: { approach: "flash-lit night ritual snapshots", grade: "purple-black with sodium pockets" },
    fash: { silhouettes: "all-black draped streetwear", garments: "hooded sweatshirts, mesh tops, Docs boots", acc: "triangle pendants, face paint, snapbacks" },
    env: { places: "bedroom studios, warehouse corners, myspace pages", weather: "screen-glow midnight" },
    gd: { layout: "sigil-centred dark grid", icon: "triangle within triangle" },
    ui: { background: "void black", surface: "violet glass", components: "glitch-hover buttons", motion: "frame-skip stutter" },
    rec: { materials: "latex, cracked leather, printed vinyl", lighting: "UV tube in darkness", objects: "candles beside laptops, tarot decks, hard drives", music: "screwed 808s under choir pads", scent: "incense, ozone from old CRTs" },
    snd: ["screwed vocal moan", "tape-stop pitch fall", "hi-hat smoke hiss"],
    dna: { mi: 35, og: 80, wc: 25, ns: 20, ad: 12, hf: 15, rr: 70, ps: 60, sh: 75, ql: 45, oc: 70, ds: 65, rs: 55, eu: 40, np: 65 },
    emo: { warm: 15, cold: 85, playful: 35, serious: 55, chaotic: 65, ordered: 40, nostalgic: 45, futuristic: 60, peaceful: 15, ominous: 90 },
  },
  {
    n: "Chillwave", a: ["glo-fi", "hypnagogic pop"],
    cat: "Music & Sonic Culture", c: "lo-fi synth-pop microgenre", e: "community_subculture", o: "Washed Out's Ernest Greene, Toro y Moi and Memory Tapes, blog-named in 2009",
    g: "US Southeast (Georgia, South Carolina) and the music-blogosphere", p: "2009-2012", era: "late blog era",
    sum: "Sun-bleached synths and hissed vocals about remembered summers — the first genre made, named and killed by the blogosphere.",
    desc: "Chillwave arrived in mid-2009 when blogs — notably Hipster Runoff, which coined the name — and writers like Simon Reynolds (offering 'hypnagogic pop') tried to classify a wave of bedroom producers using hazy vintage synths, filtered vocals, drum-machine softshoes and VHS-warm nostalgia. Washed Out's 'Feel It All Around' (2009) became the sound's face as the Portlandia theme; Toro y Moi's Causers of This (2010) and Washed Out's Within and Without (2011) filled the small canon. Everything was lo-fi by design: tape hiss, detuned Junos, beach-poster color. Journalists declared the genre dead by 2012, but its methods seeded synth-pop revivalism, vaporwave's warmth and the lo-fi beats playlists of the streaming decade.",
    col: [{ h: "#e8b08a", n: "VHS peach" }, { h: "#5aa8a0", n: "pool teal" }, { h: "#e8cf7a", n: "sun haze yellow" }, { h: "#8aa0b2", n: "bleach denim" }, { h: "#a07a8a", n: "dusk mauve" }],
    m: ["vintage analog synths (Juno, DX7 patches)", "cassette four-tracks and tape hiss", "CD-R and Bandcamp distribution", "VHS-sourced video loops"],
    tx: ["tape saturation bloom", "sunset gradient scanlines", "soft-focus pool water shimmer", "hissed vocal veil"],
    obj: ["beach-poster sunsets", "analog synth woodsides", "palm-tree silhouettes", "washed band logos", "ceiling fan spinners"],
    ex: ["Feel It All Around (Washed Out, 2009)", "Causers of This (Toro y Moi, 2010)", "Within and Without (Washed Out, 2011)"],
    inf: ["lo-fi beats study playlists", "vaporwave warmth and nostalgia"], rel: ["Synthwave", "Vaporwave", "Shoegaze"],
    par: "internet microgenres", var: ["washed out ambient-leaning strand", "toro y moi funk-leaning strand", "hypnagogic pop cousin"], cf: ["Synthwave", "Vaporwave"],
    src: [{ n: "Wikipedia — Chillwave", u: "https://en.wikipedia.org/wiki/Chillwave", t: "B" }, { n: "Pitchfork", u: "https://pitchfork.com", t: "B" }],
    tg: ["chillwave", "glo-fi", "washed out", "hypnagogic pop", "blog era"], pop: 38, niche: false,
    vd: { shape: "soft horizontal sun bands", line: "no outlines — gradient only", composition: "centered horizon with lens flare", texture: "VHS grain over satin", forms: "sun, pool ripples, palms, sunglasses" },
    typ: { display: "soft geometric display", body: "rounded sans", notes: "late-night-poster ease" },
    fnt: { display: "Comfortaa", body: "DM Sans", notes: "rounded warmth over clean sans" },
    lit: { quality: "sunset diffusion with flare", direction: "front-glow backlight", temperature: "warm", shadow: "none — everything lifts" },
    pho: { approach: "memory-haze snapshot with leak", grade: "peach-teal cross-processed" },
    fash: { silhouettes: "breezy relaxed drape", garments: "linen shirts, screen-printed tees, pastel shorts", acc: "round sunglasses, cassette players, flip-flops" },
    env: { places: "backyard pools, suburban porches, empty night freeways", weather: "humid golden hour" },
    gd: { layout: "centered gradient hero", icon: "sun-disc motif" },
    ui: { background: "VHS peach gradient", surface: "frosted teal cards", components: "soft-pill buttons", motion: "slow cross-dissolve" },
    rec: { materials: "wicker, terry cloth, plastic radios", lighting: "string lights at dusk", objects: "cassettes, sunglasses, coconut lotion", music: "the genre itself on a porch radio", scent: "suntan oil, cut grass, warm vinyl" },
    snd: ["tape hiss swell", "detuned pad shimmer", "filtered vocal loop"],
    dna: { mi: 40, og: 68, wc: 45, ns: 25, ad: 15, hf: 30, rr: 50, ps: 60, sh: 55, ql: 55, oc: 55, ds: 40, rs: 45, eu: 45, np: 50 },
    emo: { warm: 80, cold: 20, playful: 55, serious: 25, chaotic: 25, ordered: 45, nostalgic: 90, futuristic: 40, peaceful: 75, ominous: 10 },
  },
  {
    n: "Blue Note record design", a: ["Blue Note album covers", "Reid Miles sleeve design", "hard bop record graphics"],
    cat: "Music & Sonic Culture", c: "jazz record sleeve design culture", e: "community_subculture", o: "Blue Note Records' art direction — Reid Miles layouts over Francis Wolff photography, for Alfred Lion's label",
    g: "New York City, USA", p: "1956-1967 (classic Miles era)", era: "hard bop era",
    sum: "Two-colour modernist sleeves with cropped smoke-lit session photos — the most imitated record design system in jazz.",
    desc: "From 1956 freelance designer Reid Miles turned Blue Note covers into a modernist system: Wolff's warm session photographs cropped radically, headlines set in trade-gothic caps, one or two flat Pantone colors chosen partly because two-plate printing was cheap — thrift that hardened into signature. Miles reportedly didn't listen to the music (he preferred Shostakovich) yet matched mood after mood, from the cobalt-and-amber Blue Train (1957) to knock-out type on Moanin' (1958). Francis Wolff's photographs, taken through rehearsal smoke at sessions he attended since the label's 1939 founding, supplied the human grain. The roughly 400-cover corpus became the default reference for independent-label art direction, endlessly reissued, exhibited and remixed, and still shorthand for jazz's cool.",
    col: [{ h: "#1f3a93", n: "cobalt ink" }, { h: "#e0782a", n: "tangerine" }, { h: "#f2efe6", n: "acetate white" }, { h: "#1a1a1c", n: "smoke black" }, { h: "#d9a52a", n: "mustard spot" }],
    m: ["two-plate Pantone offset printing", "francis wolff session photography", "trade gothic and derived wood type", "10-inch and 12-inch vinyl gloss laminate"],
    tx: ["flat uncoated stock matte", "halftone photo crop", "knock-out reversed type", "off-register accent slabs"],
    obj: ["cropped musician portraits", "blue note logos in bold white", "rehearsal-room session smoke", "limelight piano keys", "liner notes with Lion's editorial voice"],
    ex: ["Blue Train (John Coltrane, 1957)", "Moanin' (Art Blakey & the Jazz Messengers, 1958)", "Somethin' Else (Cannonball Adderley, 1958)"],
    inf: ["independent label art direction systems", "swiss-modernist record graphics"], rel: ["Salsa record covers", "swiss modernist typography", "hard bop culture"],
    par: "record sleeve design", var: ["miles two-colour system", "wolff photo-crop school", "60s abstract-expressionist sleeves"], cf: ["impulse! gatefold era", "prestige cover minimalism"],
    src: [{ n: "Wikipedia — Blue Note Records", u: "https://en.wikipedia.org/wiki/Blue_Note_Records", t: "B" }, { n: "Blue Note Records (official)", u: "https://www.bluenote.com", t: "A" }],
    tg: ["blue note", "reid miles", "jazz covers", "francis wolff", "hard bop"], pop: 42, niche: false,
    vd: { shape: "asymmetric photo-crop rectangles", line: "single rule or none", composition: "type locked to photo bleed edge", texture: "flat ink on uncoated board", forms: "horns, cigarette smoke, hands, caps, piano lids" },
    typ: { display: "condensed gothic caps", body: "small grotesque caps for credits", notes: "billing-card hierarchy" },
    fnt: { display: "Oswald", body: "Archivo", notes: "trade-gothic homage pairing" },
    lit: { quality: "single-source session lamp warmth", direction: "side vignette around the soloist", temperature: "warm amber on smoke", shadow: "rich but readable" },
    pho: { approach: "environmental jazz session reportage", grade: "warm monochrome with one flat spot colour" },
    fash: { silhouettes: "sharp 50s tailoring", garments: "narrow-lapel suits, rollneck sweaters, shirt sleeves at work", acc: "porkpie hats, horn cases, wristwatches" },
    env: { places: "englewood clipping studios, basement studios, 50s NY jazz clubs", weather: "steam-heated new york winter night" },
    gd: { layout: "photo-crop with locked type edge", icon: "bold white music-note mark" },
    ui: { background: "acetate white", surface: "cobalt panels", components: "flat two-tone buttons", motion: "one clean cut" },
    rec: { materials: "uncoated board, brass, shellac dust", lighting: "photo-lamp over turntable", objects: "LP sleeves, horn mouthpieces, coffee cups", music: "hard bop quintet in full swing", scent: "cigarette smoke, printing ink, vinyl" },
    snd: ["brushed snare patter", "upright bass walk", "needle drop crackle"],
    dna: { mi: 85, og: 82, wc: 25, ns: 20, ad: 18, hf: 20, rr: 55, ps: 72, sh: 50, ql: 85, oc: 70, ds: 60, rs: 45, eu: 70, np: 45 },
    emo: { warm: 70, cold: 35, playful: 45, serious: 60, chaotic: 30, ordered: 75, nostalgic: 80, futuristic: 35, peaceful: 50, ominous: 20 },
  },
  {
    n: "Reggae sound-system culture", a: ["Jamaican sound system", "dancehall session culture", "toasting and clash culture"],
    cat: "Music & Sonic Culture", c: "outdoor bass dance culture", e: "community_subculture", o: "Kingston street dances built around portable PA rigs; carried to Britain by Windrush-era migration",
    g: "Jamaica (Kingston) and the UK (Notting Hill, Birmingham, Leicester)", p: "1950s-present", era: "independence era to digital",
    sum: "Hand-built speaker stacks, exclusive dubplates and MC clashes — the street-bass institution that became reggae's beating heart.",
    desc: "When radios were scarce, Kingston's poorer districts danced to the first sound systems — carts of hand-built speaker boxes run by operators like Coxsone Dodd's Downbeat and Duke Reid the Trojan, later refined by King Tubby's bass innovations. The system made the music: exclusive dubplates cut for one crew, selectors controlling the night, and toasting DJs chatting over rhythms — the seedbed of rap and of dancehall itself. Migrating to Britain, the culture took root at Notting Hill Carnival and in Midlands clubs, with outfits like Saxon Studio International producing stars from Smiley Culture onward. Clash etiquette, vertical bass feel, box-spray gold lettering and bass-bin physics remain a living lineage running through jungle, dubstep, grime and every festival stage with a wall of scoops.",
    col: [{ h: "#17140f", n: "bass-bin black" }, { h: "#c9a53a", n: "glitter gold" }, { h: "#b0182a", n: "session crimson" }, { h: "#2a7d4f", n: "bottle green" }, { h: "#e8e2d2", n: "curtain cream" }],
    m: ["hand-built plywood scoop bins", "valve amps rewired for bass", "dubplate acetates", "gold and red spray-lettered banners"],
    tx: ["sawdust-rough plywood grain", "spray-drip lettering", "hot valve glow", "woven speaker cloth"],
    obj: ["stacked scoop speaker walls", "dj toasting microphones", "acetate dubplates", "selector control towers", "velvet dancehall curtains"],
    ex: ["Coxsone Dodd's Downbeat vs Duke Reid clashes, Kingston", "Saxon Studio International's UK sound, 1980s", "Notting Hill Carnival static sound systems"],
    inf: ["UK bass lineage: jungle, dubstep, grime", "hip-hop MCing and remix culture"], rel: ["Dancehall poster culture", "UK carnival culture", "Jamaican dub production"],
    par: "Caribbean music culture", var: ["kingston clash sound", "uk carnival static sound", "roots reggae dance strand"], cf: ["dancehall recording industry", "American block-party DJ culture"],
    src: [{ n: "Wikipedia — Sound system (Jamaican)", u: "https://en.wikipedia.org/wiki/Sound_system_(Jamaican)", t: "B" }, { n: "British Library — Sound Archive", u: "https://www.bl.uk", t: "A" }],
    tg: ["sound system", "reggae", "dubplate", "notting hill carnival", "toasting"], pop: 44, niche: false,
    vd: { shape: "vertical stacked-block monoliths", line: "hand-spray outline strokes", composition: "stage as cathedral of boxes", texture: "carpeted ply, gold glitter lettering", forms: "scoop bins, horns, mics, curtains, crowns" },
    typ: { display: "bold rounded poster face with glitter fill", body: "plain grotesque", notes: "hand-lettered session bill tone" },
    fnt: { display: "Shrikhand", body: "Karla", notes: "juicy display over workhorse sans" },
    lit: { quality: "blue-and-red stage floods in open air", direction: "front wash from the rig", temperature: "hot", shadow: "bass-shaking silhouettes" },
    pho: { approach: "night-dance reportage around the rig", grade: "saturated warm with deep shadows" },
    fash: { silhouettes: "crisp pressed streetwear", garments: "clarkes wallabees, pressed khaki, mesh vests, church-crisp dresses", acc: "gold chains, bamboo earrings, tall tees, khaki caps" },
    env: { places: "kingston yards, notting hill side streets, midland blues parties", weather: "caribbean heat, english drizzle under tarpaulins" },
    gd: { layout: "stacked event-bill hierarchy", icon: "speaker-box crown" },
    ui: { background: "bass-bin black", surface: "crimson panels", components: "gold-outline buttons", motion: "bass-pulse scale" },
    rec: { materials: "plywood, carpet, chrome grilles", lighting: "rig floods in darkness", objects: "dubplate crates, power strips, rum cups", music: "riddim through 18-inch cones", scent: "weed smoke, frying fish, hot electronics" },
    snd: ["sub-bass pull", "dj toast over riddim", "generator hum"],
    dna: { mi: 30, og: 85, wc: 45, ns: 20, ad: 15, hf: 20, rr: 70, ps: 60, sh: 70, ql: 60, oc: 55, ds: 60, rs: 45, eu: 45, np: 55 },
    emo: { warm: 85, cold: 25, playful: 65, serious: 50, chaotic: 55, ordered: 45, nostalgic: 65, futuristic: 40, peaceful: 40, ominous: 35 },
  },
  {
    n: "Dancehall poster culture", a: ["dancehall session posters", "Jamaican street flyer art", "bashment poster vernacular"],
    cat: "Music & Sonic Culture", c: "hand-lettered event poster vernacular", e: "community_subculture", o: "Kingston promoters, sign painters and photocopy shops advertising sessions and clashes",
    g: "Jamaica — Kingston, Spanish Town", p: "1980s-2000s", era: "digital riddim era",
    sum: "Glitter-marker gradients, exploding letterforms and zinc-fence banners — the street graphics that advertised every Jamaican session.",
    desc: "Every Jamaican dance — from yard sessions to Boxing Day's Sting spectacular — needed walls of graphics, and a vernacular industry of sign painters, photocopy flyers and screen-printed banners supplied them. Names ballooned in outlined marker with glitter and metallic gradients; sound systems, selectors and promoters stacked in descending scale; stars, flashes and hand-drawn DJ caricatures burst from zinc fences and lamp posts. Photographers and documenters like Beth Lesser, who shot and wrote on the Kingston scene through the 80s, preserved the graphic ecology alongside the music. The style's exaggeration logic — maximum star power per square inch — migrated to UK and US reggae promotion and into digital riddim-era Photoshop flyers, where its DNA survives in today's bashment promos.",
    col: [{ h: "#f2c53d", n: "glitter gold" }, { h: "#d43a2f", n: "banner red" }, { h: "#2a9d5c", n: "marker green" }, { h: "#2b2530", n: "zinc-fence dusk" }, { h: "#f5f0e0", n: "photocopy white" }],
    m: ["photocopy flyers on bond paper", "sign-painter enamel and one-shot lettering", "metallic glitter markers", "screen-printed cloth banners"],
    tx: ["marker gradient fills", "photocopy drop-out contrast", "zinc corrugation behind paste-ups", "spray-drip edges"],
    obj: ["hand-drawn DJ caricatures", "starburst 'tonight!' flashes", "clash line-up bills", "zinc-fence paste walls", "selector cartoon logos"],
    ex: ["Beth Lesser's 1980s Kingston session photography and flyers", "Hand-painted banners for Sting at Jamworld, Portmore", "Passa Passa weekly street-dance flyers, Kingston"],
    inf: ["UK rave and bashment flyer design", "digital-era dance promo templates"], rel: ["Reggae sound-system culture", "Golden-era hip-hop visual culture", "Nollywood poster art"],
    par: "Caribbean music culture", var: ["sign-painter banner school", "photocopy flyer wave", "photoshop riddim era"], cf: ["Nollywood poster art", "UK rave flyer design"],
    src: [{ n: "Wikipedia — Dancehall", u: "https://en.wikipedia.org/wiki/Dancehall", t: "B" }, { n: "British Library", u: "https://www.bl.uk", t: "A" }],
    tg: ["dancehall posters", "jamaica", "session flyers", "bashment", "sign painting"], pop: 28, niche: true,
    vd: { shape: "exploding starburst silhouettes", line: "chunky marker double-outlines", composition: "name hierarchy stacked to shouting point", texture: "glitter grain on paper", forms: "microphones, crowns, stars, sound-boxes, flags" },
    typ: { display: "fat outlined script-and-block mix", body: "condensed sans", notes: "every line shouts louder than the last" },
    fnt: { display: "Bowlby One SC", body: "Catamaran", notes: "marker-bold display over legible sans" },
    lit: { quality: "midday tropical hard sun", direction: "flat frontal, poster-legible", temperature: "hot", shadow: "hard-edged and short" },
    pho: { approach: "documentary shots of pasted walls", grade: "punchy saturated pop" },
    fash: { silhouettes: "stage-ready flashy cuts", garments: "white-on-white dance outfits, baggy tees for selectors", acc: "gold-fronted smiles, chains, bandanas, tall tees" },
    env: { places: "half-way-tree walls, zinc-fence yards, bus shelters", weather: "wet-season downpour past flyers" },
    gd: { layout: "shouting stacked bill", icon: "star flash burst" },
    ui: { background: "photocopy white", surface: "gold card accents", components: "outlined badge buttons", motion: "flash-blink" },
    rec: { materials: "corrugated zinc, enamel paint, kraft paper", lighting: "bare stall bulbs", objects: "marker trays, paste buckets, flyers", music: "clash rewinds on portable speakers", scent: "spray paint, fried dumplings, rain" },
    snd: ["whistle of hype man", "rewind pull-up clap", "street preacher and tivoli bass overlap"],
    dna: { mi: 25, og: 90, wc: 55, ns: 20, ad: 12, hf: 15, rr: 75, ps: 65, sh: 80, ql: 45, oc: 45, ds: 70, rs: 40, eu: 35, np: 70 },
    emo: { warm: 85, cold: 20, playful: 80, serious: 35, chaotic: 75, ordered: 30, nostalgic: 55, futuristic: 35, peaceful: 30, ominous: 30 },
  },
  {
    n: "Golden-era hip-hop visual culture", a: ["golden age hip-hop graphics", "boom bap era visual culture"],
    cat: "Music & Sonic Culture", c: "hip-hop graphic vernacular", e: "community_subculture", o: "New York street scenes crossing graffiti writing, flyer art and label design at Def Jam, Cold Chillin' and Pop Art Records",
    g: "New York City, spreading to Los Angeles and Philadelphia", p: "1984-1994", era: "golden age",
    sum: "Party flyers, airbrushed logos and hard-cropped portraits — the graphic system boom-bap built before Photoshop.",
    desc: "Between the genre's commercial birth and its CD-era consolidation, a network of Bronx and Brooklyn artists gave golden-age hip-hop its visual voice: Buddy Esquire's hand-drawn party flyers welded Art Deco flourishes to graffiti lettering; Eric Haze's logos and sleeves branded the Def Jam generation; Cey Adams carried the studio aesthetic forward; photographers like Janette Beckman caught rappers as hard-lit street aristocrats. Covers alternated minimalist confidence — Run-DMC's hats-and-stripes abstraction — with riotous collage, Public Enemy's militarist iconography, and Yo! MTV Raps' broadcast energy. The system's tools were marker, airbrush, photostat and Letraset, which is why its grids still read as hand-work. Its legacy saturates streetwear, mixtape-cover economies and every era's nostalgia for crate-dug graphics.",
    col: [{ h: "#d92419", n: "marker red" }, { h: "#1c1c1e", n: "rooftop black" }, { h: "#f2b705", n: "taxi yellow" }, { h: "#2a6fd6", n: "airbrush blue" }, { h: "#efe9da", n: "photostat cream" }],
    m: ["photostat and PMT camera repro", "Letraset and marker comps", "airbrush on CS10 board", "12-inch vinyl and promo flat posters"],
    tx: ["crisp halftone dots", "airbrush fade gradients", "marker bleed edges", "black-and-white photo crop"],
    obj: ["hand-drawn party flyers", "Kangol hats and Cazals", "boomboxes on subway platforms", "def jam logo lockups", "records crates as pedestals"],
    ex: ["Buddy Esquire's Bronx party flyers, 1979-1985", "Eric Haze's Def Jam-era logos and covers", "Janette Beckman's rap portrait photography, 1980s"],
    inf: ["streetwear branding systems", "mixtape-cover and promo economies"], rel: ["Reggae sound-system culture", "graffiti writing culture", "UK rave flyer design"],
    par: "hip-hop culture", var: ["flyer lettering school", "def jam minimalist covers", "airbrush glory era"], cf: ["graffiti writing culture", "post-disco club flyers"],
    src: [{ n: "Wikipedia — Golden age hip hop", u: "https://en.wikipedia.org/wiki/Golden_age_hip_hop", t: "B" }, { n: "MoMA — The Collection", u: "https://www.moma.org", t: "A" }],
    tg: ["golden age hip hop", "boom bap", "party flyers", "buddy esquire", "def jam"], pop: 46, niche: false,
    vd: { shape: "stacked arcade-block letterforms", line: "marker outline with airbrush shadow", composition: "artist as monument, low angle", texture: "photostat grit", forms: "kangols, chains, boomboxes, subway cars, dookie ropes" },
    typ: { display: "wildstyle-adjacent display block", body: "bold grotesque", notes: "flyer billing hierarchy" },
    fnt: { display: "Rubik Wet Paint", body: "Chivo", notes: "graffiti flavor display over sturdy sans" },
    lit: { quality: "hard flash in dark club voids", direction: "direct flash, subject front-on", temperature: "neutral-hot", shadow: "halo behind subject" },
    pho: { approach: "direct-flash environmental portraits", grade: "punchy primaries, slight yellow push" },
    fash: { silhouettes: "boxy authoritative volume", garments: "leather bomber jackets, laced-adidas tracksuits, dookie rope chains", acc: "kangol hats, cazal glasses, four-finger rings" },
    env: { places: "rooftop parties, record shops, 125th street", weather: "fire-hydrant summer" },
    gd: { layout: "flyer grid with headline shout", icon: "boombox glyph" },
    ui: { background: "photostat cream", surface: "red-blocked panels", components: "sticker-style badges", motion: "pop-in bounce" },
    rec: { materials: "vinyl, cardboard record jackets, chrome", lighting: "flash-cube contrast", objects: "turntables, mics on stands, fly posters", music: "breakbeats cut on two decks", scent: "magic marker, asphalt, Jamaican patty foil" },
    snd: ["double-time scratch chirp", "airhorn", "crowd call-and-response"],
    dna: { mi: 35, og: 88, wc: 55, ns: 25, ad: 15, hf: 20, rr: 75, ps: 65, sh: 85, ql: 60, oc: 55, ds: 65, rs: 50, eu: 40, np: 60 },
    emo: { warm: 75, cold: 30, playful: 70, serious: 55, chaotic: 60, ordered: 45, nostalgic: 80, futuristic: 55, peaceful: 30, ominous: 30 },
  },
  {
    n: "Gabber visual culture", a: ["Rotterdam gabber culture", "hardcore house aesthetic", "gabbers"],
    cat: "Music & Sonic Culture", c: "hardcore rave subculture style", e: "community_subculture", o: "Rotterdam docklands youth around the Parkzicht club and labels like Rotterdam Records",
    g: "Netherlands (Rotterdam, The Hague), spreading to Flanders, Germany and northern Italy", p: "1991-2000s", era: "1990s hardcore",
    sum: "Shaved heads, Australian tracksuits and 200 BPM distortion — Rotterdam's working-class answer to Amsterdam's smiley house.",
    desc: "Gabber — Amsterdam slang for 'mate' — hardened into a full subculture in early-90s Rotterdam, where dockland youth built identity on the fastest, most distorted techno in Europe. The uniform was instantly readable: shaved heads for all genders, Nike Air Max, and the tracksuits of Australian, a sportswear brand adopted wholesale by the scene. The hakkuh dance pumped arms over kicking feet at 150-200 BPM; flyer and cassette art answered with chrome skulls, distorted Rotterdam Records logos and tram-stop typography. Mega-raves under ID&T's Thunderdome banner scaled it into stadiums while media panic and the genre's own extremity burned it out around the millennium. Its stubby afterlife lives in hardstyle, festival hardcore and Dutch pop's ironic affection for its own toughest decade.",
    col: [{ h: "#1f2a4a", n: "tracksuit navy" }, { h: "#d9a52a", n: "australian gold" }, { h: "#eef0f2", n: "strobe white" }, { h: "#8a8f96", n: "sweat grey" }, { h: "#a01818", n: "thunderdome red" }],
    m: ["Australian-brand tracksuit velour", "stamped hardcore vinyl EPs", "chrome-and-sword flyer airbrush", "warehouse concrete and chain-link"],
    tx: ["distorted-to-death logo edges", "high-shine velour", "strobe freeze-frames", "industrial scuffed concrete"],
    obj: ["shaved heads under strobes", "air max sneakers as uniform", "thunderdome compilation CDs", "skull-and-lightning flyers", "kicking hakkuh stance"],
    ex: ["Rotterdam Records' distorted-logo hardcore EPs", "Parkzicht club raves, Rotterdam, early 1990s", "Thunderdome arena events by ID&T, from 1992"],
    inf: ["hardstyle and festival hardcore branding", "football-casual style crossover into rave"], rel: ["Acid house", "football casual culture", "happy hardcore scene"],
    par: "electronic rave cultures", var: ["rotterdam gabber hardcore", "happy hardcore offshoot", "early hardstyle evolution"], cf: ["Acid house", "skinhead revival fashion"],
    src: [{ n: "Wikipedia — Gabber", u: "https://en.wikipedia.org/wiki/Gabber", t: "B" }, { n: "Discogs", u: "https://www.discogs.com", t: "B" }],
    tg: ["gabber", "hardcore techno", "rotterdam", "thunderdome", "australian tracksuit"], pop: 32, niche: true,
    vd: { shape: "angular chrome slabs and skulls", line: "beveled metal outlines", composition: "logo-first, crowd as texture", texture: "brushed chrome and velour", forms: "skulls, lightning bolts, chains, sneakers, fists" },
    typ: { display: "distorted stencil-caps", body: "condensed industrial sans", notes: "flyer legibility at 200 bpm" },
    fnt: { display: "Rubik Glitch", body: "Barlow Condensed", notes: "corrupted display over tight sans" },
    lit: { quality: "strobe-white machine hall light", direction: "overhead bars, no nuance", temperature: "cold with sweat steam", shadow: "hard drop under rig" },
    pho: { approach: "documentary crowd shots in strobe", grade: "blue-grey industrial with gold accents" },
    fash: { silhouettes: "track-cut athletic blocks", garments: "australian tracksuits, bomber jackets, timberland boots", acc: "air maxes, shaved heads, small gold earrings" },
    env: { places: "rotterdam warehouse halls, scooter parks, tram shelters", weather: "north sea drizzle" },
    gd: { layout: "central logo + billing strip", icon: "skull with lightning" },
    ui: { background: "concrete grey", surface: "navy chrome cards", components: "stamped metal buttons", motion: "kick-drum pulse" },
    rec: { materials: "concrete, chain-link, velour", lighting: "white strobe grids", objects: "water pistols, earplugs, compacts and lipgloss", music: "distorted kicks at 180 bpm", scent: "sweat, fireworks smoke, frites fat" },
    snd: ["distorted kick thud", "hoover stab", "mc bark in dutch"],
    dna: { mi: 30, og: 70, wc: 60, ns: 15, ad: 10, hf: 12, rr: 65, ps: 50, sh: 65, ql: 45, oc: 50, ds: 75, rs: 55, eu: 70, np: 65 },
    emo: { warm: 45, cold: 60, playful: 55, serious: 50, chaotic: 75, ordered: 40, nostalgic: 55, futuristic: 60, peaceful: 15, ominous: 65 },
  },
  {
    n: "Reggaeton perreo visual culture", a: ["perreo flyer culture", "reggaeton club graphics"],
    cat: "Music & Sonic Culture", c: "club promo graphic vernacular", e: "community_subculture", o: "San Juan underground sessions — DJ Playero mixtapes, The Noise compilations — and the club economy around them",
    g: "Puerto Rico (San Juan, Carolina), with Panamanian roots", p: "1990s-present", era: "underground to streaming era",
    sum: "Cassette covers, wet-look flyers and club-bling graphics — the vernacular visual economy of reggaeton's perreo nights.",
    desc: "Before reggaeton had a global industry it had a flyer-and-cassette economy: San Juan's underground spread through DJ Playero's Playero mixtapes and The Noise compilations, copied to cassette and advertised on photocopied flyers whose wet-look gradients, sparkled logos and posed-crew photography set the template. Perreo — the dance and the night itself — supplied the visual logic: maximum energy, bodies front and centre, gold and neon over photocopy blue. As the 2000s boom hit, Luny Tunes' Mas Flow (2003) era branded the sound with glossy urban-latin graphics, diamond type and video-vixen glamour, which today's urbano superstars retool through streaming cover art and Instagram promo. The vernacular remains proudly low-fi at street level even as its centre goes platinum.",
    col: [{ h: "#101c2e", n: "photocopy blue night" }, { h: "#f2b705", n: "bling gold" }, { h: "#e0348a", n: "neon perreo pink" }, { h: "#3fae6a", n: "chrome mint" }, { h: "#f5efe4", n: "flyer white" }],
    m: ["dubbed cassette J-cards", "photocopy and neon-paper flyers", "photoshop bevel-and-glow era files", "CD-R club promos"],
    tx: ["beveled chrome letterforms", "wet gradient sheen", "photocopy grain", "sparkle burst overlays"],
    obj: ["crew photo line-ups", "sparkled artist logos", "J-card cassettes", "club bottle-service tables", "perreo crowd wall shots"],
    ex: ["DJ Playero's Playero 37 underground cassette", "The Noise compilation series, 1990s", "Luny Tunes' Mas Flow (2003)"],
    inf: ["Latin trap and urbano cover art", "streaming-era playlist branding"], rel: ["Reggae sound-system culture", "Dancehall poster culture", "Golden-era hip-hop visual culture"],
    par: "Latin music cultures", var: ["underground cassette era", "glossy 2000s boom era", "streaming urbano era"], cf: ["Dancehall poster culture", "Golden-era hip-hop visual culture"],
    src: [{ n: "Wikipedia — Reggaeton", u: "https://en.wikipedia.org/wiki/Reggaeton", t: "B" }, { n: "British Library", u: "https://www.bl.uk", t: "A" }],
    tg: ["reggaeton", "perreo", "playero", "the noise", "urbano"], pop: 43, niche: false,
    vd: { shape: "beveled chrome name-slabs", line: "glow-outline strokes", composition: "crew stacked over club glow", texture: "sparkle grain on gradient", forms: "crowds, gold chains, car grilles, bottle light, palms" },
    typ: { display: "beveled chrome script or block", body: "clean geometric sans", notes: "logo-first promo hierarchy" },
    fnt: { display: "Righteous", body: "Manrope", notes: "display glow over modern sans" },
    lit: { quality: "club wash and phone flash", direction: "front flash in dark club", temperature: "mixed hot pink and gold", shadow: "crowd silhouettes" },
    pho: { approach: "posed crew line-ups and crowd energy", grade: "high-saturation neon with gold bloom" },
    fash: { silhouettes: "body-defining street glamour", garments: "baggy tees to tight dresses, denim cutoffs, sheer layers", acc: "gold ropes, hoop earrings, bandanas, shades at night" },
    env: { places: "caserio courtyards, san juan clubs, car parks turned venues", weather: "caribbean night steam" },
    gd: { layout: "artist-logo hero + date grid", icon: "cassette with wings" },
    ui: { background: "photocopy blue", surface: "gold-gradient cards", components: "chrome-stroke buttons", motion: "shimmer sweep" },
    rec: { materials: "chrome, neon acrylic, printed vinyl", lighting: "led strip colour cycling", objects: "cassettes, coup glasses, phone flashes", music: "dembow riddim at perreo volume", scent: "money-spray sugarcane, sunscreen, gasoline" },
    snd: ["dembow kick-snare loop", "air-horn rewinds", "crowd chant of artist names"],
    dna: { mi: 35, og: 72, wc: 50, ns: 20, ad: 15, hf: 20, rr: 70, ps: 60, sh: 80, ql: 50, oc: 55, ds: 60, rs: 55, eu: 40, np: 55 },
    emo: { warm: 80, cold: 30, playful: 75, serious: 40, chaotic: 65, ordered: 40, nostalgic: 60, futuristic: 50, peaceful: 25, ominous: 35 },
  },
  {
    n: "Salsa record covers", a: ["Fania sleeve art", "salsa album design", "NY latin record graphics"],
    cat: "Music & Sonic Culture", c: "latin record sleeve design culture", e: "community_subculture", o: "Fania Records and New York latin labels (Alegre, Tico, Vaya), with Izzy Sanabria's graphic direction",
    g: "New York City — Spanish Harlem, the Bronx, midtown studios", p: "1964-1980", era: "Fania era",
    sum: "Crime-scene melodrama, Palladium ballroom flash and bold latin modernism — the sleeve art of Nueva York's hottest rhythm.",
    desc: "Fania Records turned salsa into a brand, and its covers taught the world how the music looked: Willie Colon's early albums posed the teenage bandleader as mobster beside Hector Lavoe — El Malo (1967) launched the crime-scene idiom, continued through Cosa Nuestra's vintage car and autopsy-table imagery. Izzy Sanabria, who designed for Fania and published Latin New York magazine, pushed bold lettering, poster-like illustration and stage-photo spreads that unified the scene's look from record sleeve to club flyer. The Fania All-Stars' Live at the Cheetah (1972) and the Siembra (1978) collaboration of Blades and Colon supplied the canon's peak images: baroque, urban, proud and sometimes violent. The corpus now anchors latin-design collecting and the salsa dura revival's branding.",
    col: [{ h: "#8e1b1b", n: "crimson bolero" }, { h: "#d9a52a", n: "brass bandleader gold" }, { h: "#20242c", n: "downtown night navy" }, { h: "#e8ddc4", n: "ticket cream" }, { h: "#3f6e54", n: "mojito green" }],
    m: ["glossy laminated LP jackets", "photo-collage and airbrush illustration", "bold latin-poster lettering", "latin new york magazine newsprint"],
    tx: ["airbrush drama gradients", "halftone stage-photo grain", "gloss jacket glare", "hand-lettered title flourishes"],
    obj: ["tresillo-bandoneon horn sections", "vintage gangster cars", "cheetah ballroom stage shots", "guayabera-and-tailor hybrids", "congas under spotlight"],
    ex: ["El Malo (Willie Colon, 1967)", "Siembra (Ruben Blades & Willie Colon, 1978)", "Live at the Cheetah Vol. 1 (Fania All-Stars, 1972)"],
    inf: ["salsa dura revival branding", "latin boogaloo graphic nostalgia"], rel: ["Blue Note record design", "Reggaeton perreo visual culture", "mambo Palladium ballroom culture"],
    par: "record sleeve design", var: ["colon-lavoe crime-scene school", "sanabria poster lettering", "cheetah live-photo spreads"], cf: ["Blue Note record design", "mambo-era dance posters"],
    src: [{ n: "Wikipedia — Salsa music", u: "https://en.wikipedia.org/wiki/Salsa_music", t: "B" }, { n: "Fania Records (official)", u: "https://www.fania.com", t: "A" }],
    tg: ["salsa", "fania", "willie colon", "hector lavoe", "record covers"], pop: 36, niche: false,
    vd: { shape: "poster-steeped portrait blocks", line: "swash-lettered title underlines", composition: "bandleader as antihero centerpiece", texture: "gloss laminate over halftone", forms: "horns, congas, fedoras, ruffled cuffs, dominoes" },
    typ: { display: "bold swash display serif", body: "grotesque sans", notes: "ballroom billing energy" },
    fnt: { display: "Alfa Slab One", body: "Mulish", notes: "poster slab over friendly sans" },
    lit: { quality: "ballroom spot and crime-flash hybrid", direction: "low-angle hero key", temperature: "hot amber", shadow: "noir pools behind swagger" },
    pho: { approach: "staged melodrama tableaux", grade: "warm saturated with noir edges" },
    fash: { silhouettes: "sharp 70s flare tailoring", garments: "three-piece suits in rust and cream, silk ruffle shirts", acc: "wide brims, domino pendants, conga-calloused hands" },
    env: { places: "cheetah and palladium ballrooms, spanish harlem stoops, recording lofts", weather: "sticky new york july" },
    gd: { layout: "poster-steeped cover grid", icon: "swash note clef" },
    ui: { background: "ticket cream", surface: "crimson panels", components: "brass-line dividers", motion: "spotlight fade" },
    rec: { materials: "laminated board, brass, velvet rope", lighting: "stage spots through haze", objects: "LPs, congas, harmonicas, dominoes", music: "brass montage into coro-pregon call", scent: "cigars, sweat, photocopy toner" },
    snd: ["bongocero bell pattern", "trombone layering", "sonero improvised call"],
    dna: { mi: 45, og: 78, wc: 45, ns: 20, ad: 15, hf: 20, rr: 60, ps: 65, sh: 60, ql: 68, oc: 60, ds: 55, rs: 50, eu: 45, np: 55 },
    emo: { warm: 85, cold: 30, playful: 60, serious: 55, chaotic: 50, ordered: 55, nostalgic: 80, futuristic: 25, peaceful: 35, ominous: 40 },
  },
  {
    n: "Afrobeat album art", a: ["Afrobeat cover painting", "Lemi Ghariokwu sleeves", "Fela album covers"],
    cat: "Music & Sonic Culture", c: "protest record sleeve painting", e: "community_subculture", o: "Lagos scene of Fela Kuti's Afrika Shrine and Kalakuta Republic; painter Lemi Ghariokwu's partnership with Fela from the mid-1970s",
    g: "Nigeria — Lagos", p: "1970s-1990s", era: "afrobeat seventies-eighties",
    sum: "Hand-painted Fela covers that were political cartoons — grotesque generals, Pidgin slogans and riotous color against military rule.",
    desc: "Afrobeat's albums were arguments, and their covers were painted arguments: from Alagbon Close (1974) onward, self-taught painter Lemi Ghariokwu created 26 sleeves for Fela Kuti, working from the music and from long conversations at Kalakuta Republic. Zombie (1976) caricatured soldiers as vacant clockwork; Beasts of No Nation (1989) turned UN bigwigs into snarling monsters, captioned in English, Pidgin and Yoruba lettering that functioned as on-record protest under censorship. Ghariokwu's grotesque airbrush-and-acrylic style — bulging eyes, banner text, checkerboard satire — made each LP a pamphlet you could play, and Lagos studios, printers and fans turned the covers into street-level political education. The tradition's lineage runs through Nigerian modern design collecting and today's Afrobeats sleeve revivals quoting his hand outright.",
    col: [{ h: "#c98e2a", n: "ochre market gold" }, { h: "#2c6e3f", n: "kalakuta green" }, { h: "#b3261e", n: "protest red" }, { h: "#1c1a18", n: "shrine ink" }, { h: "#f2e3c2", n: "harmattan cream" }],
    m: ["acrylic and airbrush on board", "hand-lettered English/Pidgin/Yoruba banners", "LP presses of Lagos and EMI Nigeria", "photocopy protest duplicates"],
    tx: ["grotesque airbrush modelling", "banner stroke lettering", "checkerboard satire fields", "matte print grain"],
    obj: ["caricatured military generals", "slogan banner scrolls", "saxophone-toting central figures", "prison bars as frame devices", "yabbis — the loose trouser suits of the shrine crowd"],
    ex: ["Zombie (Fela Kuti & Africa 70, 1976)", "Beasts of No Nation (Fela Kuti, 1989)", "Lemi Ghariokwu's Kalakuta-era sleeve paintings, 1974-1993"],
    inf: ["Nigerian album-art collecting and revival", "protest poster design in Afrobeats"], rel: ["Highlife music culture", "Reggae sound-system culture", "Salsa record covers"],
    par: "record sleeve design", var: ["ghariokwu grotesque airbrush school", "shrine handbill lettering", "80s collage-diptych era"], cf: ["highlife poster graphics", "caribbean dub sleeve culture"],
    src: [{ n: "Wikipedia — Lemi Ghariokwu", u: "https://en.wikipedia.org/wiki/Lemi_Ghariokwu", t: "B" }, { n: "Wikipedia — Fela Kuti", u: "https://en.wikipedia.org/wiki/Fela_Kuti", t: "B" }],
    tg: ["afrobeat", "fela kuti", "lemi ghariokwu", "album art", "lagos"], pop: 36, niche: false,
    vd: { shape: "central grotesque figure in banner frame", line: "wobbly confident brush contour", composition: "poster-cartoon hierarchy with slogan rails", texture: "acrylic stroke and airbrush puff", forms: "generals, saxophones, chains, dollar eyes, crowds" },
    typ: { display: "hand-lettered banner caps", body: "plain grotesque", notes: "slogans integral, never separate" },
    fnt: { display: "Shantell Sans", body: "Sora", notes: "hand-feel display over modern sans" },
    lit: { quality: "hot stage light of the afrika shrine", direction: "uplight on performer, flat elsewhere", temperature: "hot", shadow: "caricature-absorbing flat black" },
    pho: { approach: "sleeve-as-tableau reproduction", grade: "saturated primary gouache warmth" },
    fash: { silhouettes: "shrine stage flamboyance", garments: "fela's yabbis and printed pant-suits, agbada robes", acc: "multi-necklace beadwork, face paint, 70s aviators" },
    env: { places: "afrika shrine stage, kalakuta compound, lagos printing rows", weather: "harmattan haze and rain-season downpours" },
    gd: { layout: "banner-framed poster cover", icon: "raised fist star" },
    ui: { background: "harmattan cream", surface: "shrine-ink panels", components: "slogan-sticker buttons", motion: "stamp slam" },
    rec: { materials: "acrylic board, newsprint, vinyl", lighting: "bare bulb over worktable", objects: "brushes, logo stencils, dub cassettes", music: "afrobeat grooves at rehearsal volume", scent: "turpentine, pepper soup, joss sticks" },
    snd: ["baritone sax honk", "chanting choruses", "maracas shaker pattern"],
    dna: { mi: 35, og: 90, wc: 55, ns: 20, ad: 12, hf: 15, rr: 80, ps: 70, sh: 85, ql: 55, oc: 55, ds: 60, rs: 45, eu: 35, np: 65 },
    emo: { warm: 75, cold: 35, playful: 55, serious: 70, chaotic: 60, ordered: 45, nostalgic: 65, futuristic: 35, peaceful: 30, ominous: 55 },
  },
];
