/**
 * Curated wave — Wave 3: Subculture, Fashion, Retrofuturism & SciFi-Fantasy.
 * Music-scene visual cultures, working-class British street styles, retail
 * fashion trends, retrofuture design languages and fantasy/horror genre imagery.
 * All entries real and documented. Sensitive subcultures (skinhead style) are
 * handled factually and neutrally, distinguishing the original style from later
 * racist appropriation.
 */
export const WAVE_SUB: any[] = [
  {
    n: "Black metal visual culture", a: ["corpse paint look", "trve kvlt graphics", "second wave black metal art"],
    cat: "Subculture Style", c: "extreme metal visual culture", e: "community_subculture",
    o: "Second wave black metal scene, early 1990s", g: "Norway first; global extreme metal underground",
    p: "c. 1990–present", era: "underground cassette and CD era",
    sum: "The visual language of black metal: corpse paint, illegibly spiked logos and wintry lo-fi imagery built on cold, loathing and mystique.",
    desc: "Black metal developed a visual culture as extreme as its sound. Roots run through first-wave shock rock and bands like Venom and Bathory, but the codified look came with Norway's second wave (Mayhem, Darkthrone, Emperor): corpse paint — black-and-white face paint traced to theatrical precursors like Alice Cooper and Kiss — spiked gauntlets, and logos lettered into near-illegible tangles of branches and thorns. Album covers favoured grainy monochrome photographs, snowbound forests, crypts and lake piers, often reused from older sources, while demo culture ran on xeroxed J-cards and letterzines. The imagery deliberately courts misanthropy, anti-modernity and Nordic winter. Scenes worldwide localised the grammar (France, Greece, USBM), and the look now reads through documentary photography, festival stagecraft and endless meme-era parody.",
    col: [{ h: "#0d0d0d", n: "void black" }, { h: "#f2f0eb", n: "bone white" }, { h: "#5b6770", n: "slate grey" }, { h: "#7a1f1f", n: "dried blood red" }, { h: "#3c4a3e", n: "pine green" }],
    m: ["xeroxed zine pages", "grainy gig photography", "hand-drawn logo lettering", "cassette J-cards"],
    tx: ["high-contrast photocopy grain", "scratchy pen-spike linework", "snow static", "smoke blur"],
    obj: ["spiked bracers", "upside-down crosses", "snowbound pine forests", "candle-lit crypts", "fogged lake piers"],
    ex: ["Darkthrone's Transilvanian Hunger (1994) cover", "Emperor's In the Nightside Eclipse (1994) artwork", "Mayhem's corpse-paint stage imagery"],
    inf: ["theatrical shock rock (Alice Cooper, Kiss)", "Caspar David Friedrich's Romantic landscape painting"], rel: ["Goth subculture", "Punk fashion", "Cosmic horror"],
    par: "extreme metal underground", var: ["atmospheric black metal landscape art", "DSBM cover art", "war metal graphics"], cf: ["death metal art (gory cartoon versus stark monochrome)"],
    src: [{ n: "Wikipedia — Black metal", u: "https://en.wikipedia.org/wiki/Black_metal", t: "B" }, { n: "Wikipedia — Corpse paint", u: "https://en.wikipedia.org/wiki/Corpse_paint", t: "B" }],
    tg: ["black metal", "corpse paint", "trve kvlt", "norwegian black metal", "extreme metal"], pop: 42, niche: false,
    vd: { shape: "spiky fractal contours and stark horizon photos", line: "branching thorn linework, near-illegible", composition: "band logo over single bleak landscape", texture: "photocopy grain, snow noise", forms: "crosses, trees, corpses, candles, mountains" },
    typ: { display: "hand-drawn organic thorn lettering", body: "weathered serif or xerox caps", notes: "illegibility is the point; body text stays austere" },
    fnt: { display: "Metal Mania", body: "EB Garamond", notes: "spiked display caps over austere old-style serif body" },
    lit: { quality: "weak overcast winter light", direction: "backlit silhouettes", temperature: "cold", shadow: "crushed blacks, fog-shredded" },
    pho: { approach: "lo-fi analog gig and landscape photography", grade: "high-contrast monochrome, crushed blacks" },
    fash: { silhouettes: "leather, denim and spikes; gauntlet sleeves", garments: "battle jackets, corpse-paint blackcloth", acc: "spiked wristbands, inverted crosses" },
    env: { places: "Nordic forests, frozen lakes, stone churches", weather: "snow, fog, moonless winter" },
    gd: { layout: "logo-dominant cover with bleak photo field", icon: "thorned sigil or inverted cross" },
    ui: { background: "#0d0d0d", surface: "charcoal panels with white bone text", components: "xerox-textured cards, thin rule lines", motion: "slow fog drift, flicker" },
    rec: { materials: "charred wood, pewter, fur, frost", lighting: "candlelight in cold darkness", objects: "cassettes, daggers, snow globes of ruins", music: "tremolo-picked guitar washes, shrieked vocals", scent: "cold pine, incense smoke, damp stone" },
    snd: ["tremolo guitar wall", "church bell in fog", "wind over ice"],
    dna: { mi: 45, og: 30, wc: 85, ns: 55, ad: 15, hf: 25, rr: 85, ps: 85, sh: 90, ql: 65, oc: 70, ds: 45, rs: 55, eu: 75, np: 55 },
    emo: { warm: 10, cold: 90, playful: 5, serious: 90, chaotic: 55, ordered: 40, nostalgic: 45, futuristic: 15, peaceful: 15, ominous: 95 },
  },
  {
    n: "NWOBHM album art", a: ["new wave of British heavy metal art", "Eddie the Head art"],
    cat: "Subculture Style", c: "late-70s/80s metal cover art", e: "community_subculture",
    o: "UK heavy metal renewal, c. 1979", g: "United Kingdom; influence worldwide",
    p: "c. 1979–mid-1980s", era: "vinyl and cassette era of independent metal labels",
    sum: "Galloping skeletons, chrome and hellfire: the cover art and mascots of Britain's New Wave of Heavy Metal.",
    desc: "The New Wave of British Heavy Metal (NWOBHM) — Iron Maiden, Saxon, Diamond Head, Motörhead at the heavier edge — built a recognisable cover-art world on small independent labels like Bronze, Neat and Ebony. Its vocabulary: airbrushed chrome and stage lighting, motorcycles, skeletal ghouls, devils and battlefield hordes, often painted fast for tight budgets. Iron Maiden's mascot Eddie, designed by Derek Riggs from 1980, became the movement's most durable image, mutating across sleeves and T-shirts. The style fused 1950s EC horror-comic ghoulishness, science-fiction paperback painting and biker-magazine bravado, and it fed directly into American power and speed metal artwork, dungeon-metal illustration and the sword-and-skull iconography still used across heavy metal today.",
    col: [{ h: "#1a1c2c", n: "midnight navy" }, { h: "#d6231f", n: "battle red" }, { h: "#e8c25a", n: "chrome gold" }, { h: "#cfd4d8", n: "steel grey" }, { h: "#0c0c0c", n: "ink black" }],
    m: ["airbrush on board", "gouache horror illustration", "glossy laminate sleeves", "photocopied gig posters"],
    tx: ["smooth airbrush gradients", "hard chrome highlights", "electric stage-light glow", "halftone print grain"],
    obj: ["mascot ghoul (Eddie)", "motorcycles and chains", "flying-V guitars", "devils and skeletons", "battlefield hordes"],
    ex: ["Iron Maiden's Eddie artwork by Derek Riggs (from 1980)", "Saxon's Wheels of Steel (1980)", "Diamond Head's Lightning to the Nations (1980)"],
    inf: ["1950s EC horror comics", "science-fiction paperback cover painting"], rel: ["Black metal visual culture", "Sword & sorcery", "Punk fashion"],
    par: "heavy metal album art", var: ["speed metal covers", "dungeon metal illustration"], cf: ["US power metal art"],
    src: [{ n: "Wikipedia — New wave of British heavy metal", u: "https://en.wikipedia.org/wiki/New_wave_of_British_heavy_metal", t: "B" }, { n: "Wikipedia — Iron Maiden", u: "https://en.wikipedia.org/wiki/Iron_Maiden", t: "B" }],
    tg: ["nwobhm", "iron maiden", "eddie the head", "album art", "heavy metal"], pop: 30, niche: true,
    vd: { shape: "dynamic diagonal action poses", line: "bold outline with airbrush fill", composition: "mascot looming over band logo", texture: "chrome sheen on matte board", forms: "ghouls, bikes, axes, lightning, hordes" },
    typ: { display: "spiked metal logotype", body: "condensed grotesque caps", notes: "dripping or bevelled display, utilitarian track lists" },
    fnt: { display: "Pirata One", body: "Oswald", notes: "blackletter-leaning metal display with condensed sans body" },
    lit: { quality: "stage spotlight glow", direction: "underlight and rim light", temperature: "hot highlights, cold grounds", shadow: "hard theatrical shadows" },
    pho: { approach: "painted and airbrushed fantasy illustration", grade: "saturated primaries on black" },
    fash: { silhouettes: "denim-and-leather uniform", garments: "cut-off battle vests, drainpipe jeans", acc: "studded belts, patches, bandana" },
    env: { places: "rehearsal rooms, transit vans, festival stages", weather: "dry-ice smoke and strobes" },
    gd: { layout: "central mascot, arc band logo, tracklist strip", icon: "horned skull with lightning bolt" },
    ui: { background: "#1a1c2c", surface: "steel-grey cards with gold rules", components: "embossed metal-look buttons", motion: "gallop rhythm marquees" },
    rec: { materials: "polished steel, black denim, laminate", lighting: "amps and spotlights in dark rooms", objects: "vinyl sleeves, patch sew-ons, ticket stubs", music: "twin-guitar gallops, wailing tops", scent: "spilled beer, leather, smoke machine" },
    snd: ["galloping twin guitars", "stadium crowd roar", "hi-hat machine rhythm"],
    dna: { mi: 40, og: 45, wc: 55, ns: 65, ad: 10, hf: 30, rr: 60, ps: 65, sh: 60, ql: 70, oc: 50, ds: 55, rs: 45, eu: 40, np: 75 },
    emo: { warm: 45, cold: 40, playful: 60, serious: 45, chaotic: 50, ordered: 40, nostalgic: 85, futuristic: 40, peaceful: 15, ominous: 60 },
  },
  {
    n: "Teddy Boys", a: ["teds", "Edwardian drape revival"],
    cat: "Subculture Style", c: "1950s British youth style", e: "community_subculture",
    o: "London working-class youth, early 1950s", g: "Britain; later revivals across the UK",
    p: "c. 1950–1960s; revivals since the 1970s", era: "post-war austerity into the rock'n'roll era",
    sum: "Britain's first youth subculture: Edwardian drape jackets, drainpipe trousers, quiffs and brothel creepers worn to rock'n'roll.",
    desc: "Teddy Boys — 'teds' — emerged in working-class London around 1950 when Savile Row tailors revived Edwardian dress and young men bought into it. The uniform: long drape jackets with velvet collars, drainpipe trousers, high-necked shirts and bootlace ties, thick-soled brothel creeper shoes, and heavily greased quiffs. They took up rock'n'roll from 1954-55, becoming the template for every later British youth tribe. The history is double-edged: the same scene's fringes were involved in the 1958 Notting Hill race riots, and the style has at times been claimed by far-right revivals, which historians of the subculture note without it defining the whole. Chris Steele-Perkins' photobook The Teds (1979) fixed the revival-era image; drape tailoring and creepers remain collectable and still surface in modern rockabilly and pub-rock scenes.",
    col: [{ h: "#2b2b33", n: "charcoal drape" }, { h: "#7f1d2b", n: "velvet maroon" }, { h: "#d9cfae", n: "fawn waistcoat" }, { h: "#1c1c22", n: "boot black" }, { h: "#b39a5d", n: "bootlace tan" }],
    m: ["wool drape cloth", "velvet collars", "thick crepe soles", "greased pomade"],
    tx: ["heavy tailored drape", "soft velvet sheen", "crepe-sole depth", "high-shine pompadour"],
    obj: ["drape jacket with velvet collar", "brothel creepers", "bootlace tie", "drainpipe trousers", "greased quiff"],
    ex: ["Chris Steele-Perkins' photobook The Teds (1979)", "V&A collections of Edwardian-revival drape tailoring", "Brothel creeper shoes popularised in the 1950s"],
    inf: ["Edwardian menswear", "1950s rock'n'roll iconography"], rel: ["Rockabilly", "Mod subculture", "Punk fashion"],
    par: "British working-class youth culture", var: ["1970s Ted revival", "rock'n'roll ted hybrid"], cf: ["Rockabilly greaser style"],
    src: [{ n: "Wikipedia — Teddy Boy", u: "https://en.wikipedia.org/wiki/Teddy_Boy", t: "B" }, { n: "Wikipedia — Brothel creeper", u: "https://en.wikipedia.org/wiki/Brothel_creeper", t: "B" }],
    tg: ["teddy boys", "teds", "drape jacket", "brothel creepers", "1950s britain"], pop: 34, niche: true,
    vd: { shape: "long tailored drape over narrow drainpipes", line: "crisp Edwardian tailoring lines", composition: "posed pair or crew outside dancehalls", texture: "wool, velvet, crepe", forms: "jackets, quiffs, ties, creepers, jukeboxes" },
    typ: { display: "Edwardian-influenced high-contrast serif", body: "bookish serif", notes: "dancehall poster rules and flourishes" },
    fnt: { display: "Playfair Display", body: "Lora", notes: "Victorian-editorial contrast with quiet book body" },
    lit: { quality: "flash-lit night streets", direction: "frontal press flash", temperature: "warm tungsten indoors", shadow: "hard flash falloff" },
    pho: { approach: "documentary social photography, posed crews", grade: "slightly warm silver-halide neutrals" },
    fash: { silhouettes: "long drape, slim leg, padded shoulder", garments: "drape jackets, bootlace ties, brocade waistcoats", acc: "bootlace ties, creepers, pocket watch chains" },
    env: { places: "dance halls, milk bars, London terraces", weather: "drizzle and lamplit night" },
    gd: { layout: "centre-posed figure with ticket-stub borders", icon: "drape jacket silhouette" },
    ui: { background: "#2b2b33", surface: "fawn paper panels", components: "letterpress-style buttons", motion: "stiff, formal transitions" },
    rec: { materials: "wool, velvet, crepe rubber", lighting: "warm pub tungsten", objects: "jukeboxes, pocket combs, gramophones", music: "skiffle into early rock'n'roll", scent: "pomade, pipe smoke, wet wool" },
    snd: ["slap-bass rock'n'roll", "vinyl crackle", "echoing dancehall feet"],
    dna: { mi: 40, og: 55, wc: 45, ns: 40, ad: 80, hf: 15, rr: 45, ps: 50, sh: 40, ql: 45, oc: 45, ds: 50, rs: 60, eu: 55, np: 90 },
    emo: { warm: 55, cold: 35, playful: 50, serious: 45, chaotic: 35, ordered: 55, nostalgic: 95, futuristic: 10, peaceful: 40, ominous: 35 },
  },
  {
    n: "Rockabilly", a: ["50s rock'n'roll style", "greaser look"],
    cat: "Subculture Style", c: "rock'n'roll dress and imagery", e: "community_subculture",
    o: "early 1950s American South", g: "US South first; worldwide revival scenes",
    p: "c. 1953–present; major revivals 1970s–2000s", era: "rock'n'roll era and its nostalgia revivals",
    sum: "Pompadours, circle skirts, leopard print and hot rods: the 1950s rockabilly look and its living revival culture.",
    desc: "Rockabilly fused hillbilly country with rhythm and blues — Elvis Presley's Sun Records sessions (1954-55) are the mythic origin — and carried a total visual package. Men: greased pompadours or ducktails, rolled tee sleeves, cuffed jeans or greaser leather; women: swing dresses, full petticoats, polka dots, bullet bras, red lips and pin curls. Hot rods, drive-ins and pin-up illustration supply the backdrop, and revival scenes from the Stray Cats era (1979 onward) through today's weekenders like Viva Las Vegas keep it alive, braided with kustom kulture pinstriping and Sailor Jerry-style tattooing. The psychobilly offshoot pushed the imagery toward horror kitsch. The style is now a global retro subculture with its own contests, shops and car shows, nostalgic by definition yet continuously re-performed.",
    col: [{ h: "#8c1f28", n: "cherry red" }, { h: "#16161a", n: "leather black" }, { h: "#e9e2d0", n: "diner cream" }, { h: "#d4a24e", n: "leopard gold" }, { h: "#4e6e8a", n: "denim blue" }],
    m: ["leather and denim", "swing-dress cotton", "chrome hot-rod plating", "tattoo-ink linework"],
    tx: ["polished chrome sparkle", "soft cotton swing", "greased hair sheen", "weathered leather crease"],
    obj: ["pompadour quiff", "hot rods and fins", "petticoat circle skirts", "saddle shoes", "spinning vinyl 45s"],
    ex: ["Elvis Presley's Sun Records era look (1954–56)", "Stray Cats' 1980s revival", "Viva Las Vegas rockabilly weekender"],
    inf: ["1950s advertising illustration", "Sailor Jerry tattoo flash"], rel: ["Teddy Boys", "Kustom kulture", "Lowrider culture"],
    par: "1950s American youth style", var: ["psychobilly", "rockabella styling", "kustom kulture"], cf: ["1950s suburban Americana"],
    src: [{ n: "Wikipedia — Rockabilly", u: "https://en.wikipedia.org/wiki/Rockabilly", t: "B" }, { n: "Wikipedia — Greaser (subculture)", u: "https://en.wikipedia.org/wiki/Greaser_(subculture)", t: "B" }],
    tg: ["rockabilly", "greaser", "50s style", "pompadour", "hot rod"], pop: 46, niche: false,
    vd: { shape: "cinched waists, full skirts, sculpted hair volumes", line: "swash script and rounded chrome curves", composition: "couple or car centre-stage, sunburst backdrop", texture: "glossy print and cotton swing", forms: "fins, bows, records, cherries, dice" },
    typ: { display: "brush script with swash tails", body: "condensed sans caps", notes: "diner-menu and 45-label conventions" },
    fnt: { display: "Yellowtail", body: "Oswald", notes: "1950s sign-painter script over utilitarian condensed sans" },
    lit: { quality: "bright high-noon sun or neon diner glow", direction: "frontal and warm", temperature: "warm", shadow: "crisp, minimal" },
    pho: { approach: "vivid pin-up and car-show photography", grade: "Kodachrome-saturated warm" },
    fash: { silhouettes: "hourglass swing or lean jean-and-jacket", garments: "swing dresses, cuffed denim, leather biker", acc: "bandanas, saddle shoes, cherry jewellery" },
    env: { places: "drive-ins, diners, drag strips, car shows", weather: "dry summer evening" },
    gd: { layout: "arc script headline over central car or couple", icon: "fleur pinstripe or spinning record" },
    ui: { background: "#e9e2d0", surface: "diner-red panels with chrome trim", components: "jukebox-style buttons", motion: "bouncy swing transitions" },
    rec: { materials: "chrome, vinyl upholstery, cotton", lighting: "neon diner at dusk", objects: "45 rpm records, dashboard hula girls, combs", music: "slap bass and twangy guitar", scent: "bourbon vanilla, gasoline, hairspray" },
    snd: ["slap bass and twang", "car engine rev", "malt-shop jukebox hum"],
    dna: { mi: 45, og: 60, wc: 70, ns: 45, ad: 85, hf: 15, rr: 50, ps: 65, sh: 35, ql: 55, oc: 45, ds: 55, rs: 65, eu: 50, np: 95 },
    emo: { warm: 75, cold: 25, playful: 65, serious: 35, chaotic: 35, ordered: 55, nostalgic: 95, futuristic: 10, peaceful: 50, ominous: 20 },
  },
  {
    n: "Traditional skinhead style", a: ["trad skin style", "boots and braces look"],
    cat: "Subculture Style", c: "1969 British working-class street style", e: "community_subculture",
    o: "British working-class youth, 1969", g: "UK; later multiracial international scenes",
    p: "1969–1973 first wave; revivals since", era: "post-mod working-class Britain",
    sum: "The 1969 working-class style of cropped hair, boots, braces and checked shirts, born on reggae records and later contested by racist appropriation.",
    desc: "Traditional skinheads emerged in Britain in 1969, evolving from hard mods: cropped hair, Dr. Martens boots, Levi's jeans, braces, checked Ben Sherman shirts, MA-1 flight jackets and donkey jackets. Crucially, the first-wave scene was multiracial and musically devoted to Jamaican music — skinhead reggae via Trojan Records artists like Symarip and Desmond Dekker — with rude boy styling a clear influence. From the mid-1970s the look was appropriated by far-right gangs, a poisonous association the wider style never fully escaped: anti-racist skinheads organised explicitly in response, most visibly SHARP (Skinheads Against Racial Prejudice, founded 1987 in New York), and 2 Tone bands kept the original multiracial identity visible. Today 'trad skin' denotes the apolitical dress code and its reggae roots, distinct from the racist appropriation documented separately.",
    col: [{ h: "#1d1d1f", n: "boot black" }, { h: "#b03a2e", n: "braces red" }, { h: "#c8b98a", n: "tartan beige" }, { h: "#2e3b2f", n: "MA-1 olive" }, { h: "#e6e6e2", n: "shirt white" }],
    m: ["polished boot leather", "checked cotton shirting", "military nylon", "heavy denim"],
    tx: ["mirror boot shine", "herringbone weave", "denim whisker fade", "stiff pressed placket"],
    obj: ["Dr. Martens boots", "braces (suspenders)", "checked button-down shirts", "MA-1 flight jacket", "sheepskin coat"],
    ex: ["Trojan Records skinhead reggae compilations", "SHARP (Skinheads Against Racial Prejudice, founded 1987)", "2 Tone bands' skinhead-influenced style (The Specials)"],
    inf: ["Jamaican rude boy style", "British working-class menswear"], rel: ["Mod subculture", "Punk fashion", "Rockabilly"],
    par: "British working-class youth culture", var: ["hard mod", "Oi! era skinhead style", "SHARP anti-racist skinhead style"], cf: ["far-right skinhead appropriation (a racist gang identity, not the original style)"],
    src: [{ n: "Wikipedia — Skinhead", u: "https://en.wikipedia.org/wiki/Skinhead", t: "B" }, { n: "Wikipedia — Skinheads Against Racial Prejudice", u: "https://en.wikipedia.org/wiki/Skinheads_Against_Racial_Prejudice", t: "B" }],
    tg: ["skinhead", "trad skin", "boots and braces", "skinhead reggae", "trojan records"], pop: 30, niche: true,
    vd: { shape: "square, cropped, utilitarian blocks", line: "straight seams and pressed creases", composition: "crew shoulder-to-shoulder on street corners", texture: "leather shine against matte cotton", forms: "boots, braces, checks, jackets, dos" },
    typ: { display: "bold grotesque caps", body: "plain workhorse sans", notes: "record-label simplicity, no ornament" },
    fnt: { display: "Archivo Black", body: "Work Sans", notes: "heavy label caps with plain utilitarian body" },
    lit: { quality: "flat overcast daylight", direction: "frontal, even", temperature: "neutral cool", shadow: "short and functional" },
    pho: { approach: "straight documentary street photography", grade: "honest neutral tones" },
    fash: { silhouettes: "short cropped, snug shirts, heavy boots", garments: "checked shirts, jeans with turned-up cuffs, flight jackets", acc: "braces, boot laces, pork pie hats" },
    env: { places: "council estates, football terraces, record shops", weather: "grey drizzle" },
    gd: { layout: "label-style grid, central record disc", icon: "boot or braces cross" },
    ui: { background: "#e6e6e2", surface: "flat grey panels", components: "stamped-look buttons", motion: "none, utilitarian" },
    rec: { materials: "leather, cotton, steel toe", lighting: "flat estate daylight", objects: "7-inch singles, boot polish, braces and combs", music: "skinhead reggae organ skanks", scent: "boot polish, chip shops, rain" },
    snd: ["reggae organ bubble", "boot heel stomp", "pub chatter"],
    dna: { mi: 55, og: 40, wc: 40, ns: 55, ad: 70, hf: 15, rr: 75, ps: 55, sh: 60, ql: 55, oc: 55, ds: 45, rs: 75, eu: 85, np: 70 },
    emo: { warm: 45, cold: 45, playful: 30, serious: 70, chaotic: 40, ordered: 65, nostalgic: 75, futuristic: 10, peaceful: 35, ominous: 45 },
  },
  {
    n: "Cybergoth", a: ["graver", "cyber goth"],
    cat: "Subculture Style", c: "goth-rave-industrial club style", e: "community_subculture",
    o: "late 1990s European club culture", g: "Germany, UK and Netherlands club scenes; global spread",
    p: "c. 1998–present", era: "industrial-dance and rave crossover era",
    sum: "UV dreadfalls, goggles, PVC and platform boots: goth fused with rave and industrial club culture.",
    desc: "Cybergoth codified in late-1990s Europe as goth met rave and industrial dance music, and it answers traditional goth's black-only palette with neon UV accents. The kit: cyberlox and brightly coloured dreadfalls, goggles and respirator masks, PVC and fishnet layers, platform New Rock boots, and ultraviolet-reactive details made for blacklit clubs. The soundtrack is EBM and futurepop — VNV Nation, Covenant, Combichrist — with its own bounce-driven club dance. Camden Market's Cyberdog store became the style's flagship retailer, and the look was documented by the Consumer Aesthetics Research Institute as a distinct consumer aesthetic. In the 2010s the 'cybergoth dance' video meme spread the silhouette worldwide; today the style persists in industrial club nights and as a nostalgic fashion reference within 2000s revivals.",
    col: [{ h: "#0a0a0f", n: "void black" }, { h: "#39ff14", n: "UV green" }, { h: "#ff2bd1", n: "hot magenta" }, { h: "#00e5ff", n: "electric cyan" }, { h: "#b7b7c4", n: "PVC grey" }],
    m: ["PVC and latex", "synthetic dreadfalls", "fishnet", "reflective plastics"],
    tx: ["glossy UV-reactive surface", "coiled synthetic dread", "stretched mesh", "chrome buckles"],
    obj: ["goggles and respirators", "neon dreadfalls", "platform boots", "circuit motifs", "UV club lighting"],
    ex: ["Cyberdog store, Camden Market", "VNV Nation's futurepop club anthems", "Cybergoth dance videos of the 2010s"],
    inf: ["acid house rave fashion", "industrial music clubwear"], rel: ["Goth subculture", "Rave fashion", "Mall goth"],
    par: "goth subculture offshoot", var: ["graver (goth plus raver)", "cyber industrial"], cf: ["rivethead industrial style"],
    src: [{ n: "Consumer Aesthetics Research Institute", u: "https://cari.institute/aesthetics/cybergoth", t: "A" }, { n: "Aesthetics Wiki — Cybergoth", u: "https://aesthetics.fandom.com/wiki/Cybergoth", t: "B" }],
    tg: ["cybergoth", "graver", "cyberlox", "industrial club", "futurepop"], pop: 32, niche: true,
    vd: { shape: "vertical dread columns over club silhouettes", line: "hard neon strips and circuit traces", composition: "blacklit figures in dark rooms", texture: "wet PVC gloss", forms: "goggles, dreads, platforms, masks, glowsticks" },
    typ: { display: "techno square sans with stencil cuts", body: "angular techno sans", notes: "readout-style spacing, ALL CAPS labels" },
    fnt: { display: "Orbitron", body: "Chakra Petch", notes: "rave-flyer geometric display with techno body" },
    lit: { quality: "blacklight fluorescence", direction: "strobe crossfire", temperature: "cold with neon pops", shadow: "deep club darkness" },
    pho: { approach: "long-exposure club photography, strobe blur", grade: "high saturation, blown neon highlights" },
    fash: { silhouettes: "layered tube tops, kilts, platform lift", garments: "PVC coats, mesh inserts, cyberkilts", acc: "goggles, respirators, faux-fur trim" },
    env: { places: "industrial clubs, warehouse raves, Camden alleys", weather: "interior darkness, fog machines" },
    gd: { layout: "angled flyer type over blacklit photo", icon: "goggle lens or biohazard glyph" },
    ui: { background: "#0a0a0f", surface: "PVC-dark cards with neon edges", components: "glowing pill buttons", motion: "strobe flickers, glitch hops" },
    rec: { materials: "PVC, mesh, acrylic", lighting: "UV blacklight bars", objects: "glowsticks, gas masks, platform boots", music: "EBM basslines, futurepop leads", scent: "smoke machine, rubber, energy drink" },
    snd: ["hard EBM kick", "futurepop arpeggio", "strobe circuit buzz"],
    dna: { mi: 40, og: 20, wc: 40, ns: 90, ad: 80, hf: 75, rr: 60, ps: 55, sh: 55, ql: 75, oc: 55, ds: 50, rs: 45, eu: 60, np: 45 },
    emo: { warm: 35, cold: 65, playful: 60, serious: 35, chaotic: 60, ordered: 35, nostalgic: 40, futuristic: 85, peaceful: 25, ominous: 50 },
  },
  {
    n: "Mall goth", a: ["2000s Hot Topic goth", "mall gothic"],
    cat: "Subculture Style", c: "retail goth teen style", e: "community_subculture",
    o: "US suburban malls, late 1990s", g: "North America",
    p: "c. 1997–2009; nostalgia revivals since", era: "Hot Topic and mall culture era",
    sum: "Tripp pants, band tees and rubber bracelets: suburban teens assembling goth identity from the mall.",
    desc: "Mall goth describes the teenage goth vernacular of late-1990s and 2000s North America, assembled not through obscure clubs but through mall retailers — above all Hot Topic, plus Spencer's — and carried across MySpace profiles. The uniform: Tripp NYC and Lip Service wide-leg pants with straps and chains, Slipknot, Marilyn Manson and Nine Inch Nails tees, black-and-white striped armwarmers, rubber bracelets stacked to the elbow, skull-and-cross motifs, heavy eyeliner and unnaturally black dyed hair. Older goth scenes often gatekept it as fashion without substance, but it functioned as a genuine entry point and identity for a generation; the Consumer Aesthetics Research Institute documents it as a coherent aesthetic. The phrase has been revived in the 2020s as a nostalgic label for that era's look, sold back through the same channels.",
    col: [{ h: "#101013", n: "pitch black" }, { h: "#7d0f0f", n: "bloodstripe red" }, { h: "#c9c9d1", n: "chain grey" }, { h: "#3d2b4f", n: "plaid purple" }, { h: "#f0eded", n: "skeleton white" }],
    m: ["nylon utility straps", "screen-printed cotton tees", "gel wristbands", "chain hardware"],
    tx: ["matte polyester shine", "band-tee screenprint crack", "rubber bracelet matte", "chain-link glint"],
    obj: ["Tripp wide-leg pants", "skull motifs", "stacked rubber bracelets", "striped armwarmers", "Hot Topic storefront"],
    ex: ["Hot Topic mall stores", "Tripp NYC wide-leg pants", "Slipknot and Marilyn Manson merch tees"],
    inf: ["nu-metal stage wear", "Halloween consumer goth iconography"], rel: ["Goth subculture", "Nu-metal visual culture", "Scene subculture"],
    par: "goth subculture retail offshoot", var: ["2000s deathrock-revival mall look", "2020s mall goth revival"], cf: ["Cybergoth"],
    src: [{ n: "Consumer Aesthetics Research Institute", u: "https://cari.institute/aesthetics/mall-goth", t: "A" }, { n: "Aesthetics Wiki — Mall Goth", u: "https://aesthetics.fandom.com/wiki/Mall_Goth", t: "B" }],
    tg: ["mall goth", "hot topic", "tripp nyc", "2000s goth", "skull motifs"], pop: 32, niche: true,
    vd: { shape: "wide stacked pant legs under fitted black tops", line: "straps, zips and chains criss-crossing", composition: "mall-storefront or bedroom mirror poses", texture: "screenprint crack and rubber matte", forms: "skulls, crosses, chains, flames, merch logos" },
    typ: { display: "horror-movie drip lettering", body: "plain web sans", notes: "MySpace-era profile text, song lyric captions" },
    fnt: { display: "Nosifer", body: "Open Sans", notes: "dripping horror display over plain teen-internet body" },
    lit: { quality: "fluorescent mall interior", direction: "overhead flat", temperature: "cold fluorescent", shadow: "weak, washed" },
    pho: { approach: "webcam and mirror-phone selfies, flash", grade: "low-fidelity grey cast with black blowout" },
    fash: { silhouettes: "baggy wide-leg over band tee", garments: "Tripp pants, fishnet sleeves, hoodies", acc: "rubber bracelets, spiked collars, platform sneakers" },
    env: { places: "food courts, Hot Topic aisles, suburban bedrooms", weather: "interior climate control" },
    gd: { layout: "MySpace profile: tiled background, layered boxes", icon: "skull with crossbones" },
    ui: { background: "#101013", surface: "dark tiled boxes", components: "glitter-bordered buttons", motion: "cursor sparkles" },
    rec: { materials: "nylon, cotton, rubber", lighting: "fluorescent retail glow", objects: "bracelet stacks, band pins, CD jewel cases", music: "nu-metal and industrial pop", scent: "incense sticks, new plastic, pretzel stands" },
    snd: ["mall ambience", "low-fi webcam static", "drop-tuned guitar chug"],
    dna: { mi: 45, og: 40, wc: 45, ns: 75, ad: 55, hf: 35, rr: 65, ps: 50, sh: 55, ql: 55, oc: 50, ds: 55, rs: 55, eu: 55, np: 85 },
    emo: { warm: 30, cold: 60, playful: 45, serious: 40, chaotic: 45, ordered: 45, nostalgic: 80, futuristic: 25, peaceful: 30, ominous: 55 },
  },
  {
    n: "Scene subculture", a: ["scene kids", "2000s MySpace scene"],
    cat: "Subculture Style", c: "MySpace-era neon youth style", e: "community_subculture",
    o: "MySpace-era US youth, early 2000s", g: "US first; global via MySpace and YouTube",
    p: "c. 2002–2012", era: "MySpace, Warped Tour and early YouTube era",
    sum: "Teased neon-and-black hair, bows and band tees: the MySpace scene-kid look built for the webcam.",
    desc: "Scene grew out of emo's MySpace orbit but turned up the volume: hair teased into enormous backcombed volumes with extensions, clips and bows; neon-on-black colour clashes; heavy eyeliner; skinny jeans, band tees and hoodies; jewellery piled on. It was a camera-first subculture — profile pictures, comment wars and top-friends politics were the social fabric — and its stars, like Kiki Kannibal, Audree Kitching and Hannie Dropkick, became influencers before the word existed, some selling their own merchandise lines. The music mapped to crunkcore and neon-tinted pop acts; photographers in the live-music circuit canonised the look. Scene was widely mocked as it faded in the early 2010s, then rediscovered with nostalgia on TikTok, where its styling language returned as deliberate camp.",
    col: [{ h: "#141216", n: "ink black" }, { h: "#ff4fd8", n: "neon pink" }, { h: "#ffe93d", n: "neon yellow" }, { h: "#3dd6ff", n: "cyan shock" }, { h: "#ff7a3d", n: "tangerine" }],
    m: ["hair extensions and bows", "screen-print band tees", "skinny denim", "plastic jewellery"],
    tx: ["backcombed fuzz halo", "glitter overlay", "neon-on-black contrast", "webcam pixelation"],
    obj: ["teased side-swept hair with bows", "hello-kitty-adjacent toys", "studded belts", "diamond-print hoodies", "webcam self-portraits"],
    ex: ["MySpace scene queen profiles", "Kiki Kannibal's Kikikouture jewellery line", "Crunkcore acts like Brokencyde and Millionaires"],
    inf: ["emo MySpace culture", "Harajuku street colour styling"], rel: ["Mall goth", "Punk fashion", "Cybergoth"],
    par: "emo and MySpace youth culture", var: ["plur-adjacent neon scene", "2010s Tumblr scene revival"], cf: ["emo (moodier, less neon)"],
    src: [{ n: "Wikipedia — Scene (subculture)", u: "https://en.wikipedia.org/wiki/Scene_(subculture)", t: "B" }, { n: "Aesthetics Wiki — Scene", u: "https://aesthetics.fandom.com/wiki/Scene", t: "B" }],
    tg: ["scene kids", "myspace", "scene queen", "2000s scene", "neon hair"], pop: 34, niche: true,
    vd: { shape: "huge asymmetrical hair volumes over skinny frames", line: "sticker-diamond outlines and starbursts", composition: "angled webcam self-portrait, one shoulder up", texture: "glitter, fuzz, screenprint", forms: "bows, hearts, diamonds, band logos, stars" },
    typ: { display: "bubble display with heart dotting", body: "rounded casual sans", notes: "lyric captions, tYpInG quirks, glitter fills" },
    fnt: { display: "Bowlby One SC", body: "Comic Neue", notes: "puffy poster display with cartoon-casual body" },
    lit: { quality: "direct webcam or on-camera flash", direction: "frontal, hot", temperature: "cool with neon blowouts", shadow: "hard flash behind subject" },
    pho: { approach: "webcam self-portraits, angled, airbrushed", grade: "high saturation, neon channel clipping" },
    fash: { silhouettes: "ultra-skinny jeans, shrunken tops, big hair up top", garments: "band tees, diamond-print hoodies, mini skirts", acc: "bows, studded belts, layered bracelets" },
    env: { places: "bedrooms with poster walls, malls, venue pit", weather: "interior always" },
    gd: { layout: "MySpace layout: tiled neon background, comment tables", icon: "hair bow or diamond" },
    ui: { background: "#141216", surface: "neon-bordered boxes", components: "glitter gradient buttons", motion: "sparkle cursor trails" },
    rec: { materials: "synthetic hair, glitter plastic, denim", lighting: "webcam key light", objects: "hair extensions, bracelet stacks, flip phones", music: "crunkcore, electropop crossovers", scent: "hair spray, bubblegum body spray" },
    snd: ["crunkcore synths", "camera shutter", "MySpace new-comment ping"],
    dna: { mi: 25, og: 35, wc: 30, ns: 85, ad: 90, hf: 45, rr: 60, ps: 80, sh: 40, ql: 85, oc: 60, ds: 50, rs: 50, eu: 35, np: 80 },
    emo: { warm: 60, cold: 35, playful: 85, serious: 20, chaotic: 65, ordered: 40, nostalgic: 85, futuristic: 30, peaceful: 40, ominous: 25 },
  },
  {
    n: "Nu-metal visual culture", a: ["nu metal style", "baggy metal era look"],
    cat: "Subculture Style", c: "late-90s metal crossover style", e: "community_subculture",
    o: "late 1990s United States", g: "US; global radio and MTV spread",
    p: "c. 1997–2005; revival since c. 2020", era: "post-grunge CD and MTV era",
    sum: "Baggy pants, jerseys, masks and dreadlocks: the streetwear-metal hybrid look of Korn, Slipknot and their era.",
    desc: "Nu-metal merged metal with hip-hop sportswear and skate culture, and its visual culture followed: enormous JNCO and Kikwear jeans, sports jerseys and Adidas tracksuits (Korn famously wore them), dreadlock extensions, gauges, wristbands and pained goatee-beards. Stage identity pushed theatrical: Slipknot's matching coveralls and self-designed masks turned the band into a horror troupe, while Fred Durst's backwards red cap made a meme of mall-metal casual. Album and merchandise art — Todd McFarlane's work for Korn's Follow the Leader among it — favoured grungy textures, tribal marks, broken type and disquieting mascots rather than NWOBHM's chrome fantasy. The style crashed out of fashion in the mid-2000s, then returned strongly in the 2020s as Y2K nostalgia, with the baggy silhouette again on runways and festival stages.",
    col: [{ h: "#16161a", n: "jersey black" }, { h: "#b32025", n: "tracksuit red" }, { h: "#d8d8dc", n: "baggy grey" }, { h: "#6b4a2f", n: "dread brown" }, { h: "#2b3a4a", n: "ink navy" }],
    m: ["oversized denim", "polyester jerseys", "rubber mask latex", "grunge print texture"],
    tx: ["stone-washed baggy fade", "stencil paint drip", "latex mask sheen", "distressed print grain"],
    obj: ["JNCO wide-leg jeans", "backwards baseball caps", "Slipknot-style masks", "dreadlock extensions", "tribal band motifs"],
    ex: ["Slipknot's masked coveralls stage image", "Korn's Follow the Leader artwork by Todd McFarlane", "JNCO wide-leg jeans"],
    inf: ["hip-hop sportswear styling", "skate and surf apparel graphics"], rel: ["Mall goth", "Skateboard graphics culture", "Hip-hop streetwear"],
    par: "metal and hip-hop crossover youth style", var: ["industrial nu-metal stage wear", "2020s nu-metal revival"], cf: ["mall goth"],
    src: [{ n: "Wikipedia — Nu metal", u: "https://en.wikipedia.org/wiki/Nu_metal", t: "B" }, { n: "Wikipedia — JNCO", u: "https://en.wikipedia.org/wiki/JNCO", t: "B" }],
    tg: ["nu metal", "jncos", "slipknot", "baggy jeans", "y2k metal"], pop: 44, niche: false,
    vd: { shape: "enormous low-hanging pant volumes", line: "rough stencil and scratch linework", composition: "band as characters, dark mascot theatre", texture: "grunge distress, latex shine", forms: "masks, chains, caps, dreads, broken glass" },
    typ: { display: "grungy stencil with scan-line distortion", body: "plain sturdy sans", notes: "lyric-book distress, roughened edges everywhere" },
    fnt: { display: "Saira Stencil One", body: "Inter", notes: "military-stencil display over neutral workhorse body" },
    lit: { quality: "harsh stage wash and strobes", direction: "low-angle uplight", temperature: "cold with red heat accents", shadow: "deep, sweaty darkness" },
    pho: { approach: "press and pit photography, fisheye closeness", grade: "desaturated with red-black push" },
    fash: { silhouettes: "top-heavy small shirts over massive pant legs", garments: "jerseys, Adidas tracksuits, cargo shorts", acc: "gauges, dreadfalls, wristbands, chains" },
    env: { places: "skate plazas, MTV studios, festival second stages", weather: "interior smoky" },
    gd: { layout: "distorted logo over collage of textures", icon: "tribal mark or broken mask" },
    ui: { background: "#16161a", surface: "concrete grey cards", components: "scratch-edged buttons", motion: "stuttering cut transitions" },
    rec: { materials: "denim, latex, steel", lighting: "sickly red practicals", objects: "seven-string guitars, skate decks, masks", music: "drop-tuned riffs and scratch samples", scent: "sweat, weed smoke, new denim" },
    snd: ["seven-string chug", "turntable scratch", "baggy denim shuffle"],
    dna: { mi: 45, og: 45, wc: 40, ns: 80, ad: 45, hf: 35, rr: 75, ps: 45, sh: 70, ql: 70, oc: 55, ds: 45, rs: 55, eu: 60, np: 70 },
    emo: { warm: 40, cold: 50, playful: 40, serious: 50, chaotic: 60, ordered: 40, nostalgic: 80, futuristic: 30, peaceful: 25, ominous: 55 },
  },
  {
    n: "Lowrider culture", a: ["lowriding", "Chicano custom car culture"],
    cat: "Subculture Style", c: "custom car and Chicano visual culture", e: "community_subculture",
    o: "Mexican-American communities of 1940s–50s Los Angeles", g: "Southwest US; Mexico, Japan and Brazil scenes",
    p: "c. 1945–present", era: "post-war Chicano Los Angeles to global scenes",
    sum: "Hydraulics, candy paint and pinstriping: lowered cars as rolling Chicano art and community pride.",
    desc: "Lowriding began in Mexican-American Los Angeles, descending from pachuco style: post-war Chevrolets customized lower than fashion, later rigged with hydraulic lifts adapted from aircraft pumps, famously airborne from 1959, so cars could cruise slowly, nose up or bounce. The aesthetic is total: metalflake and candy paint, hand-painted pinstriping and murals,Chain steering wheels, plush interiors, and depicted iconography of family, faith and Aztec and Mexican heritage. Lowrider magazine, founded in 1977 in San Jose, codified and globalized the culture; cruising on Whittier Boulevard became a civil-liberties battleground when cities banned it, with successful court challenges and California's 2022 repeal of its cruising ban. Today lowriding is celebrated institutionally — examples like the Gypsy Rose sit in the Petersen Automotive Museum — and scenes flourish from New Mexico to Japan.",
    col: [{ h: "#5c1020", n: "candy apple" }, { h: "#f2e8c9", n: "flake cream" }, { h: "#c9971f", n: "gold flake" }, { h: "#24408e", n: "pearl blue" }, { h: "#141414", n: "black plate" }],
    m: ["candy lacquer over flake", "pinstripe enamel", "chrome plating", "hydraulic cylinder steel"],
    tx: ["deep metallic flake sparkle", "hand-painted line confidence", "mirror chrome depth", "velour interior plush"],
    obj: ["hydraulic-rigged 1960s Chevys", "pinstriped murals", "candy metalflake paint", "chain steering wheels", "plush interiors"],
    ex: ["Lowrider magazine (founded 1977)", "The Gypsy Rose lowrider at the Petersen Automotive Museum", "1959 hydraulic conversions on 1950s Chevys"],
    inf: ["pachuco zoot suit tailoring", "Mexican-American muralism"], rel: ["Kustom kulture", "Rockabilly", "Chicano muralism"],
    par: "Chicano expressive culture", var: ["bomb-class cruisers", "competition hop shows"], cf: ["hot rod culture (speed versus slow cruise)"],
    src: [{ n: "Wikipedia — Lowrider", u: "https://en.wikipedia.org/wiki/Lowrider", t: "B" }, { n: "Wikipedia — Chicano", u: "https://en.wikipedia.org/wiki/Chicano", t: "B" }],
    tg: ["lowrider", "chicano", "hydraulics", "candy paint", "cruising"], pop: 42, niche: false,
    vd: { shape: "long lowered body lines, nose-high stance", line: "scrolling pinstripe flourishes", composition: "car front and centre, family and mural behind", texture: "metalflake lacquer depth", forms: "cruisers, saints, roses, lettering, hydraulics" },
    typ: { display: "sign-painter script with pinstripe swashes", body: "condensed block sans", notes: "airbrushed name lettering, magazine masthead style" },
    fnt: { display: "Pacifico", body: "Barlow Condensed", notes: "warm brush script over tight condensed sans" },
    lit: { quality: "golden-hour boulevard sun", direction: "low warm side light", temperature: "warm", shadow: "long and glossy" },
    pho: { approach: "magazine hero photography, low angles", grade: "saturated candy-warm with chrome pop" },
    fash: { silhouettes: "crisp pressed work or dress wear", garments: "zoot-adjacent suits, khakis and pendletons", acc: "gold chains, bandanas, saint imagery" },
    env: { places: "Whittier Boulevard cruises, show lawns, garage barrios", weather: "warm dry southern California evening" },
    gd: { layout: "masthead over hero car, editorial columns", icon: "pinstripe scroll or hydraulic cylinder" },
    ui: { background: "#141414", surface: "flake-cream panels", components: "chrome-bevel buttons", motion: "slow hydraulic lift" },
    rec: { materials: "lacquer, chrome, velour", lighting: "golden hour, chrome glare", objects: "model cars, airbrush kits, prayer candles", music: "oldies and brown-eyed soul", scent: "lacquer, lowtide leather, street food" },
    snd: ["hydraulic pump whine", "cruising oldies radio", "low-and-slow engine lope"],
    dna: { mi: 55, og: 55, wc: 65, ns: 50, ad: 75, hf: 25, rr: 55, ps: 60, sh: 40, ql: 60, oc: 45, ds: 50, rs: 60, eu: 50, np: 80 },
    emo: { warm: 70, cold: 25, playful: 55, serious: 45, chaotic: 40, ordered: 55, nostalgic: 85, futuristic: 20, peaceful: 50, ominous: 30 },
  },
  {
    n: "Normcore", a: ["basic style", "deliberate sameness dressing"],
    cat: "Fashion & Dress", c: "anti-fashion everyday basics", e: "commercial_style",
    o: "coined by trend group K-HOLE (2013); mainstreamed 2014", g: "US and UK fashion media; global",
    p: "c. 2013–2016; lasting influence", era: "post-ironic fashion media era",
    sum: "Deliberate blandness as a style: unbranded basics, mom jeans and sensible sneakers worn as a knowing reaction to logo fashion.",
    desc: "Normcore was coined by New York trend agency K-HOLE in its 2013 report 'Youth Mode', describing adaptation through flexible sameness rather than distinctiveness, and mainstreamed by New York magazine's February 2014 coverage. What fashion media then re-described as 'dressing deliberately normal' became a full look: plain tees, mom and straight jeans, light-wash denim, zip fleeces, trainers like New Balance 990s, and zero visible branding — famously worn by figures like Jerry Seinfeld and echoed in tech-world dress codes. The irony was structural: clothing chosen to avoid signalling became a recognisable signal itself. Normcore's lineage runs through 1990s unisex basics and forward into gorpcore, dadcore and quiet-luxury stealth wealth, and the Consumer Aesthetics Research Institute documents it as a foundational 2010s aesthetic of anti-assertion.",
    col: [{ h: "#e8e6e1", n: "oat white" }, { h: "#9aa3ad", n: "heather grey" }, { h: "#3f4a5c", n: "washed navy" }, { h: "#c9b89a", n: "khaki" }, { h: "#ffffff", n: "sneaker white" }],
    m: ["cotton jersey", "fleece", "light-wash denim", "suede-mesh trainers"],
    tx: ["washed-out cotton softness", "pilled fleece nap", "flat denim mid-blue", "matte rubber sole"],
    obj: ["plain white tees", "New Balance-style trainers", "zip fleece jackets", "mom jeans", "baseball caps without logos"],
    ex: ["K-HOLE's Youth Mode report (2013)", "New York magazine's normcore feature (February 2014)", "New Balance 990s as normcore staple"],
    inf: ["1990s unisex basics", "tech-industry dress codes"], rel: ["Avant basic", "Quiet luxury interiors", "Gorpcore"],
    par: "fashion anti-statement", var: ["dadcore", "sensible-chic"], cf: ["minimalism (visually quiet, conceptually loud)"],
    src: [{ n: "Wikipedia — Normcore", u: "https://en.wikipedia.org/wiki/Normcore", t: "B" }, { n: "Consumer Aesthetics Research Institute", u: "https://cari.institute/aesthetics/normcore", t: "A" }],
    tg: ["normcore", "basic", "anti fashion", "new balance", "2014 fashion"], pop: 52, niche: false,
    vd: { shape: "boxy, relaxed, unstressed fits", line: "straight seams, no decoration", composition: "flat lay or street casual group shots", texture: "cotton and fleece matte", forms: "tees, fleeces, trainers, denim, caps" },
    typ: { display: "plain grotesque with no styling", body: "neutral UI sans", notes: "typography deliberately unremarkable" },
    fnt: { display: "Libre Franklin", body: "Inter", notes: "transparent everyday sans, zero display effects" },
    lit: { quality: "flat available daylight", direction: "even frontal", temperature: "neutral", shadow: "soft, unremarkable" },
    pho: { approach: "candid street documentation, no styling cues", grade: "true-to-life neutral" },
    fash: { silhouettes: "relaxed straight cuts, nothing tailored tight", garments: "plain tees, fleeces, mom jeans, trainers", acc: "none — maybe a plain cap or tote" },
    env: { places: "suburbs, airports, coffee-shop patios", weather: "overcast ordinary" },
    gd: { layout: "grid of undifferentiated product shots", icon: "plain tote bag" },
    ui: { background: "#f5f5f4", surface: "flat white cards", components: "grey default buttons", motion: "subtle, barely-there" },
    rec: { materials: "cotton, fleece, rubber", lighting: "even ambient daylight", objects: "thermos, paperback, crossword", music: "easy 90s radio", scent: "clean laundry, coffee" },
    snd: ["quiet room tone", "sneaker scuff", "distant lawnmower"],
    dna: { mi: 25, og: 50, wc: 45, ns: 55, ad: 50, hf: 40, rr: 45, ps: 50, sh: 35, ql: 30, oc: 40, ds: 45, rs: 65, eu: 65, np: 55 },
    emo: { warm: 55, cold: 40, playful: 45, serious: 50, chaotic: 25, ordered: 70, nostalgic: 60, futuristic: 35, peaceful: 70, ominous: 15 },
  },
  {
    n: "Avant basic", a: ["avant basics", "print-heavy retail trend wave"],
    cat: "Fashion & Dress", c: "mass-print trend fashion", e: "commercial_style",
    o: "term coined by the Consumer Aesthetics Research Institute; retail wave c. 2018–2022", g: "English-language e-commerce; global",
    p: "c. 2018–2022", era: "Instagram and TikTok retail trend cycle",
    sum: "Smiley flowers, checkerboards and wavy pastel prints: the mass-produced arty-surface fashion CARI named 'avant basics'.",
    desc: "Avant basic is the Consumer Aesthetics Research Institute's name for the 2018–2022 wave of fast fashion that dressed basic silhouettes in loud, playful surface design: pink smiley faces, daisies, checkerboards that warp and drip, flame prints and clashing pastels. Retailers from Urban Outfitters and Zara to online-native labels like Lisa Says Gah churned the prints; House of Sunny's green checkerboard cardigan became the wave's breakout product around 2020, circulated endlessly on Instagram and TikTok. The aesthetic reads as trend cycle speed itself — surfaces recycled from 1960s-70s psychedelia and Memphis-era geometry, produced at fast-fashion velocity, mocked as 'SHEIN psychedelic' even as it sold. It waned around 2022 into coquette and indie-sleaze revivals, remaining a textbook case of a design institute naming a trend after the fact.",
    col: [{ h: "#f7b5d9", n: "pink smile" }, { h: "#7ee081", n: "grass green" }, { h: "#ffec6e", n: "daisy yellow" }, { h: "#ffffff", n: "checker white" }, { h: "#2a2a2a", n: "contrast black" }],
    m: ["printed cotton jersey", "knit jacquard", "clay-charm resin", "organic-canvas tote cloth"],
    tx: ["flat gouache print", "warped checker ripple", "soft knit texture", "glossy resin charm"],
    obj: ["smiley faces", "warped checkerboard knits", "daisy motifs", "flame prints", "clay smiley earrings"],
    ex: ["House of Sunny's Hockney checkerboard cardigan", "CARI's Avant Basics documentation", "Lisa Says Gah's print-heavy retail drops"],
    inf: ["1960s–70s psychedelic graphics", "Memphis Milano patterns"], rel: ["Normcore", "McBling", "Y2K fashion"],
    par: "internet-era retail fashion", var: ["checkerboard knit wave", "smiley print subset"], cf: ["Y2K fashion (period-specific versus trend-cycle)"],
    src: [{ n: "Consumer Aesthetics Research Institute", u: "https://cari.institute/aesthetics/avant-basics", t: "A" }, { n: "Aesthetics Wiki — Avant Basic", u: "https://aesthetics.fandom.com/wiki/Avant_Basic", t: "B" }],
    tg: ["avant basic", "smiley print", "checkerboard", "house of sunny", "trend core"], pop: 40, niche: false,
    vd: { shape: "wavy distorted geometric repeats", line: "blobby hand-drawn outlines", composition: "flat-lay grids of printed garments", texture: "flat print on matte knit", forms: "smileys, daisies, checkers, flames, lips" },
    typ: { display: "blobby retro serif or bubble caps", body: "quirky grotesque", notes: "playful curves, wobbly baselines" },
    fnt: { display: "Bungee", body: "Space Grotesk", notes: "chunky display shapes over slightly odd neutral body" },
    lit: { quality: "bright even product light", direction: "frontal flat", temperature: "warm", shadow: "none — shadowless e-commerce" },
    pho: { approach: "shadowless e-commerce and styled flat lays", grade: "lifted pastel brightness" },
    fash: { silhouettes: "basic boxy knits and simple slip cuts", garments: "checker cardigans, printed slips, baby tees", acc: "clay smiley earrings, beaded bags" },
    env: { places: "bedroom fitting mirrors, pastel cafes", weather: "permanent golden hour filter" },
    gd: { layout: "masonry grid of prints and haul shots", icon: "wavy smiley face" },
    ui: { background: "#fdf1f7", surface: "white cards with wavy borders", components: "blob-shaped buttons", motion: "squishy bounces" },
    rec: { materials: "soft knit, resin, canvas", lighting: "ring-light evenness", objects: "tote bags, charm bracelets, Polaroids", music: "bedroom pop", scent: "vanilla candle, new cotton" },
    snd: ["bedroom pop bounce", "camera shutter burst", "package unboxing rustle"],
    dna: { mi: 70, og: 35, wc: 60, ns: 85, ad: 70, hf: 45, rr: 55, ps: 80, sh: 30, ql: 70, oc: 50, ds: 50, rs: 45, eu: 45, np: 60 },
    emo: { warm: 65, cold: 30, playful: 85, serious: 15, chaotic: 50, ordered: 45, nostalgic: 70, futuristic: 35, peaceful: 50, ominous: 10 },
  },
  {
    n: "Balletcore", a: ["ballerina core", "dancewear street styling"],
    cat: "Fashion & Dress", c: "ballet-dresswear fashion trend", e: "commercial_style",
    o: "TikTok and Instagram trend consolidation, 2022", g: "global social fashion",
    p: "c. 2021–2024", era: "post-pandemic TikTok trend cycle",
    sum: "Ballet flats, wrap cardigans, ribbons and blush pink: dancewear worn as everyday fashion.",
    desc: "Balletcore brought the dance studio into street dressing: ballet flats (Miu Miu's viral 2022 version among them), wrap knit cardigans tied at the waist, ribbed tights and legwarmers, satin ribbons in hair, bun hairstyles and a palette of blush, pointe-shoe pink and cream. The look descends from ballet's long fashion afterlife — Repetto flats since the 1950s, dance-costume echoes in 1980s Flashdance-era wear — but consolidated as a tagged trend in 2021–22 lookbook culture alongside coquette and tenniscore. Dancewear brands like Capezio and Bloch found street customers; red carpets echoed the mood. Commentary also noted the trend's ambivalence: an aesthetic built on ballet's grace while romanticizing a discipline known for punishing bodily standards, a tension fashion writers flagged during its peak.",
    col: [{ h: "#f5d3dc", n: "blush pink" }, { h: "#fff7f0", n: "pointe cream" }, { h: "#e8a0b4", n: "ribbon rose" }, { h: "#c9a9b8", n: "mauve" }, { h: "#b0b3b8", n: "soft grey" }],
    m: ["satin ribbon", "fine rib knit", "powder-pink leather", "sheer ribbed tulle"],
    tx: ["soft satin sheen", "rib knit stretch", "suede sole nap", "tulle gauze"],
    obj: ["ballet flats with ribbons", "wrap cardigans", "legwarmers", "hair buns with bows", "pointe-shoe pink palette"],
    ex: ["Miu Miu's viral 2022 ballet flats", "CARI's Balletcore documentation", "Capezio and Repetto dancewear in street styling"],
    inf: ["ballet performance costume", "Ballets Russes design history"], rel: ["Mermaidcore", "Coquette", "Mob wife"],
    par: "activity-core fashion trend", var: ["studio-to-street layering", "ballerina-slipper-only styling"], cf: ["coquette (ribbon-adjacent)"],
    src: [{ n: "Consumer Aesthetics Research Institute", u: "https://cari.institute/aesthetics/balletcore", t: "A" }, { n: "Aesthetics Wiki — Balletcore", u: "https://aesthetics.fandom.com/wiki/Balletcore", t: "B" }],
    tg: ["balletcore", "ballet flats", "dancewear", "leg warmers", "soft pink"], pop: 44, niche: false,
    vd: { shape: "light, lifted, ribbon-bound silhouettes", line: "delicate hairline curves", composition: "airborne poses, wrap-tied middles", texture: "satin, rib, gauze", forms: "slippers, ribbons, buns, legwarmers, mirrors" },
    typ: { display: "high-contrast graceful serif", body: "light geometric sans", notes: "generous letterspacing, script accents sparingly" },
    fnt: { display: "Cormorant Garamond", body: "Jost", notes: "elegant serif display over airy light body" },
    lit: { quality: "soft window light with barre-side warmth", direction: "high side light", temperature: "warm neutral", shadow: "gentle, elongated" },
    pho: { approach: "editorial studio poise and studio-class candid", grade: "airy low-contrast pastel" },
    fash: { silhouettes: "fitted torso, light leg, tied waist", garments: "wrap tops, ribbed units, ballet flats", acc: "ribbons, bun cuffs, delicate charms" },
    env: { places: "dance studios, barre mirrors, marble lobbies", weather: "soft morning light" },
    gd: { layout: "centered figure with ribbon-line dividers", icon: "ribbon bow" },
    ui: { background: "#fff7f0", surface: "blush cards with hairline borders", components: "pill buttons, thin rules", motion: "pirouette ease-outs" },
    rec: { materials: "satin, knit, rosin dust", lighting: "window light on mirrors", objects: "slippers, rosin box, scrunchies", music: "piano variations and solo cello", scent: "rosin, powder, clean wool" },
    snd: ["pointe shoes on marley floor", "piano rehearsal", "soft teacher counts"],
    dna: { mi: 35, og: 60, wc: 55, ns: 60, ad: 50, hf: 35, rr: 55, ps: 50, sh: 25, ql: 35, oc: 40, ds: 45, rs: 60, eu: 75, np: 55 },
    emo: { warm: 70, cold: 25, playful: 55, serious: 40, chaotic: 25, ordered: 65, nostalgic: 60, futuristic: 30, peaceful: 75, ominous: 10 },
  },
  {
    n: "Mob wife", a: ["mob wife aesthetic", "mafiosa glamour"],
    cat: "Fashion & Dress", c: "maximalist cinematic fashion trend", e: "commercial_style",
    o: "TikTok trend, January 2024", g: "global social fashion",
    p: "2024 (with continued cycling)", era: "TikTok maximalist trend cycle",
    sum: "Fur coats, leopard print, gold hoops and dark lipstick: mafia-film glamour as a maximalist backlash to quiet dressing.",
    desc: "The mob wife aesthetic erupted on TikTok in January 2024 as a deliberate rebuttal to quiet luxury's bare minimalism: maximal faux and vintage fur, leopard print, leather, gold hoop jewellery, slicked dark hair and statement lips. Its costume sources are screen matriarchs — Sharon Stone's Ginger McKenna in Casino (1995), Edie Falco's Carmela Soprano in The Sopranos — filtered through decades of mafia-cinema wardrobe. Fashion press from Vogue to The Guardian documented the trend cycle in real time, including its ethical wrinkle: a rush toward vintage fur framed as acceptable precisely because secondhand. Retail moved quickly with faux-fur leopard coats and gold jewellery; the trend burned through its winter cycle, but it anchored a broader return of cinched, loud, darkly glamorous dressing and reframed vintage fur as the acceptable route back to maximalism.",
    col: [{ h: "#3d1f14", n: "mahogany fur" }, { h: "#c98a3d", n: "leopard amber" }, { h: "#8f1620", n: "wine red" }, { h: "#d4af37", n: "gold hoop" }, { h: "#1a1214", n: "espresso black" }],
    m: ["long-pile faux fur", "leopard-print calf hair", "polished gold", "structured leather"],
    tx: ["fur pile depth", "print rosette patterning", "mirror-polished metal", "leather grain"],
    obj: ["leopard fur coats", "gold hoop earrings", "red-brown lipstick", "gold-chain belts", "long cigarette holders as props"],
    ex: ["Casino's Ginger McKenna wardrobe (1995)", "The Sopranos' Carmela Soprano styling", "TikTok #mobwifeaesthetic trend wave"],
    inf: ["mafia film costume design", "1980s power dressing"], rel: ["Quiet luxury interiors", "Balletcore", "Avant basic"],
    par: "cinematic fashion trend", var: ["vintage fur maximalism", "mafiosa evening look"], cf: ["1980s power dressing"],
    src: [{ n: "Consumer Aesthetics Research Institute", u: "https://cari.institute/aesthetics/mob-wife", t: "A" }, { n: "Aesthetics Wiki — Mob Wife Aesthetic", u: "https://aesthetics.fandom.com/wiki/Mob_Wife_Aesthetic", t: "B" }],
    tg: ["mob wife", "fur coat", "leopard print", "quiet luxury backlash", "2024 trend"], pop: 42, niche: false,
    vd: { shape: "big fur volumes over cinched waists", line: "bold gold contours", composition: "low-angle glamour portrait, smoke optional", texture: "fur depth and print rhythm", forms: "coats, hoops, lips, sunglasses, martinis" },
    typ: { display: "high-contrast art-deco-adjacent serif", body: "refined transitional serif", notes: "old-Hollywood title-card swagger" },
    fnt: { display: "Fraunces", body: "Marcellus", notes: "smoky display serif with elegant inscriptional body" },
    lit: { quality: "dim restaurant glamour", direction: "low key side light", temperature: "warm", shadow: "long noir shadows" },
    pho: { approach: "editorial glamour portrait, controlled smoke", grade: "warm dark with amber highlights" },
    fash: { silhouettes: "voluminous outerwear over body-conscious base", garments: "fur and leopard coats, leather, slip dresses", acc: "gold hoops, chain belts, sunglasses at night" },
    env: { places: "steakhouse booths, vintage car backseats, fur closets", weather: "cold city night" },
    gd: { layout: "centered portrait with deco frame lines", icon: "leopard rosette" },
    ui: { background: "#1a1214", surface: "espresso cards with gold rules", components: "gold-trimmed buttons", motion: "slow curtain drapes" },
    rec: { materials: "fur, leather, gold", lighting: "candle-dim with gold bounce", objects: "jewellery trays, vintage furs, martini glasses", music: "mid-century croon and strings", scent: "perfume, leather, espresso" },
    snd: ["vinyl crooner strings", "ice in a glass", "clicking heels on parquet"],
    dna: { mi: 75, og: 55, wc: 60, ns: 65, ad: 45, hf: 30, rr: 40, ps: 40, sh: 50, ql: 55, oc: 45, ds: 50, rs: 60, eu: 30, np: 75 },
    emo: { warm: 60, cold: 40, playful: 40, serious: 60, chaotic: 40, ordered: 50, nostalgic: 70, futuristic: 25, peaceful: 30, ominous: 55 },
  },
  {
    n: "Mermaidcore", a: ["mermaid aesthetic", "sea siren fashion"],
    cat: "Fashion & Dress", c: "sea-creature fashion trend", e: "commercial_style",
    o: "TikTok and press trend, 2023", g: "global social fashion",
    p: "c. 2023 (peaking around the summer film season)", era: "TikTok trend cycle",
    sum: "Iridescent scale prints, wet-look fabrics and pearls: sea-maiden dressing timed to a mermaid-heavy pop season.",
    desc: "Mermaidcore peaked in 2023, coinciding with Disney's live-action The Little Mermaid (May 2023), as TikTok and retail converged on sea-maiden dressing: sequined scale prints, iridescent and wet-look slip fabrics, shell and pearl jewellery, aqua-to-teal gradients and coral accents. Mermaid imagery has older fashion lineages — from 1930s bias-cut 'mermaid gown' silhouettes through art-nouveau siren illustration and 1990s iridescent clubwear — which the trend re-cut into beach-adjacent, festival-ready styling. Lookbooks paired scale-print minis with pearl layers and wet-look slicked hair; press coverage framed it alongside coquette and mermaid-adjacent 'siren' editorial. As with other TikTok cores, its lifecycle was short and retail-driven, but the iridescent-mesh look stayed resident in clubwear and swim collections.",
    col: [{ h: "#7fe3d4", n: "aqua foam" }, { h: "#3aa8c9", n: "lagoon blue" }, { h: "#c9b8e8", n: "pearl lilac" }, { h: "#f4f9f8", n: "seafoam white" }, { h: "#1f6f8f", n: "deep teal" }],
    m: ["sequin scale mesh", "iridescent organza", "pearl strand", "wet-look jersey"],
    tx: ["scale sequin sparkle", "oil-slick iridescence", "pearl nacre glow", "sheer water ripple"],
    obj: ["scale-print mini dresses", "shell and pearl jewellery", "wet-look slip dresses", "coral accents", "oyster-pink gradients"],
    ex: ["Disney's The Little Mermaid (2023) tie-in styling", "Sequin scale-print retail waves", "CARI's Mermaidcore documentation"],
    inf: ["art nouveau mermaid illustration", "1990s iridescent clubwear"], rel: ["Balletcore", "Coquette", "Y2K fashion"],
    par: "creature-core fashion trend", var: ["siren editorial", "pearl-core subset"], cf: ["coquette"],
    src: [{ n: "Consumer Aesthetics Research Institute", u: "https://cari.institute/aesthetics/mermaidcore", t: "A" }, { n: "Aesthetics Wiki — Mermaidcore", u: "https://aesthetics.fandom.com/wiki/Mermaidcore", t: "B" }],
    tg: ["mermaidcore", "siren", "scale print", "pearl", "sea theme"], pop: 40, niche: false,
    vd: { shape: "fluid bias-cut and wave-hem silhouettes", line: "scale scallops and wave repeats", composition: "sunlit surf or poolside shimmer shots", texture: "sequin sparkle over liquid sheen", forms: "scales, shells, pearls, waves, tails" },
    typ: { display: "elegant thin serif with deco arcs", body: "rounded light sans", notes: "pearl-grey text, airy spacing" },
    fnt: { display: "Italiana", body: "Quicksand", notes: "sleek inscriptional display with soft rounded body" },
    lit: { quality: "sun-dappled water reflections", direction: "rippling caustic light", temperature: "cool with warm glints", shadow: "shifting, watery" },
    pho: { approach: "editorial pool and shoreline fantasy", grade: "aqua-teal grade with nacre highlights" },
    fash: { silhouettes: "bias-cut, body-skimming, wave hems", garments: "scale minis, wet-look slips, sheer layers", acc: "pearl strands, shell earrings, anklets" },
    env: { places: "tidepools, resort pools, grotto sets", weather: "sun glitter on water" },
    gd: { layout: "wave-divided panels with pearl dots", icon: "scallop shell" },
    ui: { background: "#3aa8c9", surface: "seafoam translucent cards", components: "nacre-gradient buttons", motion: "gentle tide drift" },
    rec: { materials: "sequins, organza, pearl", lighting: "caustic pool light", objects: "pearl dishes, sea glass, combs", music: "dreamy synth-pop", scent: "salt air, coconut, vanilla musk" },
    snd: ["underwater bubble hush", "dream pop shimmer", "lapping tide"],
    dna: { mi: 50, og: 65, wc: 45, ns: 70, ad: 55, hf: 45, rr: 45, ps: 60, sh: 30, ql: 45, oc: 45, ds: 45, rs: 50, eu: 65, np: 50 },
    emo: { warm: 55, cold: 45, playful: 60, serious: 30, chaotic: 30, ordered: 50, nostalgic: 55, futuristic: 45, peaceful: 70, ominous: 20 },
  },
  {
    n: "Boho chic", a: ["boho", "2000s festival bohemian"],
    cat: "Fashion & Dress", c: "commercialized bohemian revival", e: "commercial_style",
    o: "mid-2000s UK and US celebrity street style", g: "UK and US; global retail",
    p: "c. 2004–2011", era: "celebrity-street-style and festival era",
    sum: "Fringed vests, floaty maxis and layered jewellery: the Sienna Miller-era bohemian revival that turned hippie dress into mall fashion.",
    desc: "Boho chic revived hippie and prairie dress through a celebrity street-style lens: Sienna Miller's 2004 Glastonbury appearance — ugg boots, fringed waistcoat, messy braids — and Kate Moss's mid-2000s looks became the templates, and Topshop-era retail industrialised the formula of floaty peasant skirts, suede waistcoats, floppy hats, layered necklaces and flats. The Wikipedia article on boho-chic documents the trend's reach and its critics, who charged that romanticized 'bohemian' poverty was sold at luxury prices to festival crowds. Its elements recycle genuinely: 1960s hippie dress, 1970s prairie revivals and older gypsy-romantic clichés flattened into one palette of sun-washed neutrals and terracotta embroidery. By the early 2010s the wave crested, but festival fashion kept the silhouette alive, and 'boho' remains a standing retail category.",
    col: [{ h: "#c9a86a", n: "sun-washed tan" }, { h: "#8d6e4e", n: "suede brown" }, { h: "#e8ddc8", n: "cream gauze" }, { h: "#a4553e", n: "terracotta embroidery" }, { h: "#6d7b5a", n: "sage fringe" }],
    m: ["washed gauze cotton", "suede", "crochet lace", "beaded fringe"],
    tx: ["crinkled gauze softness", "suede nap", "crochet openwork", "sun-faded tone"],
    obj: ["fringed suede waistcoats", "layered long necklaces", "floppy hats", "peasant maxi skirts", "messy braids"],
    ex: ["Sienna Miller's 2004 Glastonbury look", "Topshop's mid-2000s boho ranges", "Coachella festival styling of the late 2000s"],
    inf: ["1960s hippie dress", "1970s prairie and peasant revival fashion"], rel: ["Hippie dress", "Normcore", "Rockabilly"],
    par: "romanticized vintage revival", var: ["festival boho", "prairie-romantic subset"], cf: ["hippie dress ( lived practice versus commercial revival)"],
    src: [{ n: "Wikipedia — Boho-chic", u: "https://en.wikipedia.org/wiki/Boho-chic", t: "B" }, { n: "Wikipedia — Bohemianism", u: "https://en.wikipedia.org/wiki/Bohemianism", t: "B" }],
    tg: ["boho chic", "festival fashion", "sienna miller", "2000s fashion", "prairie"], pop: 46, niche: false,
    vd: { shape: "flowing layered volumes with fringe movement", line: "hand-stitched floral curves", composition: "sunlit field portraits, hair loose", texture: "gauze, suede, crochet", forms: "fringe, feathers, flowers, braids, beads" },
    typ: { display: "romantic serif with swash alternates", body: "warm humanist serif", notes: "wedding-invitation softness, artisan craft cues" },
    fnt: { display: "Yeseva One", body: "Lora", notes: "decorative display serif over warm readable serif" },
    lit: { quality: "hazy golden backlit sun", direction: "backlight with flare", temperature: "warm", shadow: "soft and diffuse" },
    pho: { approach: "backlit festival and lookbook photography", grade: "washed warm with lifted blacks" },
    fash: { silhouettes: "loose layered flow over slim base", garments: "peasant skirts, waistcoats, kimonos, flat boots", acc: "layered necklaces, headscarves, slouchy bags" },
    env: { places: "festival fields, thrift markets, sun-bleached patios", weather: "dry golden summer" },
    gd: { layout: "collaged scrapbook with torn edges", icon: "feather or dreamcatcher ring" },
    ui: { background: "#e8ddc8", surface: "gauze-textured cream cards", components: "hand-drawn icon buttons", motion: "slow parallax drift" },
    rec: { materials: "gauze, suede, turquoise beads", lighting: "late afternoon string lights", objects: "dreamcatchers, layered rings, worn boots", music: "acid folk and indie folk", scent: "patchouli, leather, hay" },
    snd: ["acoustic strumming", "festival crowd murmur", "wind chimes"],
    dna: { mi: 60, og: 75, wc: 70, ns: 35, ad: 25, hf: 20, rr: 55, ps: 50, sh: 30, ql: 40, oc: 45, ds: 50, rs: 60, eu: 50, np: 80 },
    emo: { warm: 75, cold: 20, playful: 50, serious: 35, chaotic: 35, ordered: 45, nostalgic: 85, futuristic: 15, peaceful: 70, ominous: 15 },
  },
  {
    n: "Raygun Gothic", a: ["atomic-age pulp futurism", "retro rocket sci-fi style"],
    cat: "Technology & Retrofuturism", c: "pulp-era retrofuturist design language", e: "historical",
    o: "imagery of 1930s–50s pulp science fiction; term coined by William Gibson in 1981", g: "US pulp culture; worldwide influence",
    p: "c. 1938–1960s (the imagery); named in the 1980s", era: "pulp magazine and atomic age era",
    sum: "Curvy chrome rockets, bubble domes and ray guns: the optimistic space future imagined by golden-age pulp science fiction.",
    desc: "Raygun Gothic names the streamlined space-age imagery of Gernsback-era science fiction — William Gibson coined the term in his 1981 story The Gernsback Continuum to describe it. The vocabulary: teardrop rockets with tail fins, bubble helmets, skyroads, chrome robots, ray guns, and utopian white cities, drawn by artists like Frank R. Paul for Amazing Stories and industrialized by streamline designers such as Raymond Loewy and Norman Bel Geddes, whose futurist essays and worlds'-fair visions gave the look engineering credibility. The style spilled into toys, comic strips, film serials and cartoons (The Jetsons, 1962), then became a deliberate retro reference for later science fiction, comics and games, most influentially Fallout's retro-atomic America. It remains the anchor image of 'the future as imagined in 1950' — optimistic, aerodynamic and chrome-bright.",
    col: [{ h: "#c8ccd0", n: "polished chrome" }, { h: "#3a6ea5", n: "porthole blue" }, { h: "#e0b13c", n: "fin gold" }, { h: "#8c1f28", n: "rocket red" }, { h: "#0e1116", n: "space black" }],
    m: ["polished chrome and aluminium", "molded bakelite", "airbrushed gouache", "rubberized gasket"],
    tx: ["mirror chrome sweep", "smooth airbrush gradient", "riveted seam rhythm", "vinyl toy gloss"],
    obj: ["finned rockets", "bubble helmets", "ray guns", "flying cars", "saucer control panels"],
    ex: ["Frank R. Paul's Amazing Stories cover art", "William Gibson's The Gernsback Continuum (1981)", "The Jetsons (1962) futurism"],
    inf: ["streamline moderne industrial design", "science fiction pulp cover painting"], rel: ["Space Age design", "Googie architecture", "Dieselpunk"],
    par: "retrofuturism", var: ["atompunk", "googie futurism"], cf: ["Dieselpunk (heavier interwar machinery)"],
    src: [{ n: "Wikipedia — Raygun Gothic", u: "https://en.wikipedia.org/wiki/Raygun_Gothic", t: "B" }, { n: "Wikipedia — Retrofuturism", u: "https://en.wikipedia.org/wiki/Retrofuturism", t: "B" }],
    tg: ["raygun gothic", "retrofuturism", "atomic age", "pulp scifi", "streamline"], pop: 34, niche: true,
    vd: { shape: "teardrop curves, fins, domes and portholes", line: "swooping streamline speed lines", composition: "hero vehicle ascending diagonal light rays", texture: "chrome gloss on matte starfield", forms: "rockets, robots, saucers, gears, planets" },
    typ: { display: "geometric deco sans with atomic orbit motifs", body: "rounded modernist sans", notes: "letter-spaced caps, orbit-ring O's" },
    fnt: { display: "Monoton", body: "Questrial", notes: "neon-line deco display with clean geometric body" },
    lit: { quality: "hard studio key with star-field rim", direction: "heroic underlight and speed-line highlights", temperature: "cool with warm chrome glints", shadow: "long theatrical ray shadows" },
    pho: { approach: "airbrushed illustration logic applied to photography", grade: "cyan shadows, warm chrome highlights" },
    fash: { silhouettes: "sculpted shoulder, cinched flight suit", garments: "silver flight suits, bubble visors, capes", acc: "antenna headpieces, ray gun props" },
    env: { places: "spaceports, worlds'-fair domes, lunar launchpads", weather: "clear atomic-test sunrise" },
    gd: { layout: "diagonal ascent composition with orbit rings", icon: "finned rocket or atom symbol" },
    ui: { background: "#0e1116", surface: "chrome-edged panels", components: "dial-and-toggle instrument controls", motion: "smooth rocket-swoosh easing" },
    rec: { materials: "chrome, bakelite, rubber gaskets", lighting: "spotlight plus starfield backdrop", objects: "ray gun replicas, robot toys, skyline models", music: "theremin and early electronic oddities", scent: "ozone, hot metal, machine oil" },
    snd: ["theremin wail", "retro rocket thrust", "atomic-age fanfare brass"],
    dna: { mi: 55, og: 30, wc: 50, ns: 80, ad: 60, hf: 80, rr: 40, ps: 55, sh: 30, ql: 50, oc: 40, ds: 45, rs: 50, eu: 45, np: 90 },
    emo: { warm: 55, cold: 45, playful: 60, serious: 35, chaotic: 25, ordered: 65, nostalgic: 90, futuristic: 75, peaceful: 55, ominous: 25 },
  },
  {
    n: "Dieselpunk", a: ["interwar retrofuturism", "diesel-era punk aesthetic"],
    cat: "Technology & Retrofuturism", c: "interwar retrofuture genre aesthetic", e: "experimental_hybrid",
    o: "term credited to game designer Lewis Pollak c. 2001; communities through the 2000s", g: "online fandoms and cosplay scenes; global",
    p: "c. 2001–present", era: "steampunk's interwar offshoot",
    sum: "Interwar diesel futurism: riveted iron, prop fighters and art deco machines in alternate histories of the 1920s–40s.",
    desc: "Dieselpunk is retrofuturism built on the interwar period — roughly 1920s to 1940s — when diesel engines, riveted steel and art deco defined the machine imagination. The name, credited to game designer Lewis Pollak around 2001, positions it as steampunk's grittier successor: instead of brass and clockwork, towering engines, prop-driven aircraft, artillery and deco skyscraper ornament, usually shadowed by war and depression rather than utopia. Canon visual anchors include Fritz Lang's Metropolis (1927), Sky Captain and the World of Tomorrow (2004) and BioShock's decaying deco Rapture. Communities sustain it through cosplay, model-making, graphic design and alternate-history fiction, often split between 'ottensian' deco elegance and military grime. It shares DNA with raygun gothic but trades chrome optimism for soot and brass.",
    col: [{ h: "#8f8f94", n: "gunmetal" }, { h: "#b08d3f", n: "deco brass" }, { h: "#3c2f2f", n: "coal brown" }, { h: "#c9c2b2", n: "newsprint cream" }, { h: "#1c1e22", n: "engine black" }],
    m: ["riveted steel plate", "cast brass trim", "leather aviator gear", "aged newsprint"],
    tx: ["riveted panel rhythm", "brass tarnish", "oil-slick grime", "halftone pulp print"],
    obj: ["riveted airships", "art deco radios", "aviator goggles", "prop engines", "deco skyscraper grilles"],
    ex: ["Metropolis (Fritz Lang, 1927) imagery", "Sky Captain and the World of Tomorrow (2004)", "BioShock's decaying deco Rapture"],
    inf: ["art deco industrial design", "1930s pulp magazine art"], rel: ["Raygun Gothic", "Steampunk", "Art deco"],
    par: "retrofuturism", var: ["decopunk (glossier deco subset)", "military dieselpunk"], cf: ["Steampunk", "Raygun Gothic"],
    src: [{ n: "Wikipedia — Dieselpunk", u: "https://en.wikipedia.org/wiki/Dieselpunk", t: "B" }, { n: "Wikipedia — Cyberpunk derivatives", u: "https://en.wikipedia.org/wiki/Cyberpunk_derivatives", t: "B" }],
    tg: ["dieselpunk", "decopunk", "retrofuture", "interwar", "airship"], pop: 38, niche: false,
    vd: { shape: "monumental deco blocks and riveted curves", line: "sunburst deco ornament over hard seams", composition: "massive machinery dwarfing figures", texture: "soot, tarnish, plate shadow", forms: "airships, engines, goggles, radios, pistons" },
    typ: { display: "tall condensed deco caps", body: "sturdy book serif", notes: "poster-era lockups, engraved rules" },
    fnt: { display: "Bebas Neue", body: "Spectral", notes: "propaganda-poster display with print-serif body" },
    lit: { quality: "industrial haze with hard shafts", direction: "backlit factory windows", temperature: "cold smoke with warm brass", shadow: "heavy volumetric gloom" },
    pho: { approach: "wartime-photo realism staged as fiction", grade: "desaturated sepia-steel" },
    fash: { silhouettes: "military-cut tailoring with aviator function", garments: "flight jackets, wool greatcoats, jodhpurs", acc: "goggles, side caps, service medals" },
    env: { places: "hangars, boiler decks, deco metropolis streets", weather: "coal smog and drizzle" },
    gd: { layout: "deco sunburst masthead over photo block", icon: "gear within sunburst" },
    ui: { background: "#1c1e22", surface: "riveted steel panels", components: "brass toggle switches, analog dials", motion: "mechanical clunk transitions" },
    rec: { materials: "rivet steel, brass, oiled leather", lighting: "furnace orange against smoke", objects: "pocket watches, field radios, prop blades", music: "electro-swing and brass covers", scent: "diesel, leather, gun oil" },
    snd: ["piston chug", "propeller drone", "crackling radio wire"],
    dna: { mi: 55, og: 40, wc: 40, ns: 75, ad: 35, hf: 55, rr: 55, ps: 45, sh: 60, ql: 55, oc: 45, ds: 50, rs: 50, eu: 50, np: 65 },
    emo: { warm: 40, cold: 60, playful: 35, serious: 65, chaotic: 45, ordered: 60, nostalgic: 75, futuristic: 55, peaceful: 25, ominous: 60 },
  },
  {
    n: "Biopunk", a: ["biopunk aesthetic", "wet bio-future look"],
    cat: "Technology & Retrofuturism", c: "biotech dystopia genre aesthetic", e: "experimental_hybrid",
    o: "coined in early-1990s critical discourse around cyberpunk", g: "literary and screen culture; global",
    p: "c. 1990–present", era: "post-cyberpunk biotech anxiety era",
    sum: "Body-horror biotech futures: flesh machines, wet labs and engineered organisms as cyberpunk's organic dark mirror.",
    desc: "Biopunk takes cyberpunk's corporate-dystopia frame and swaps silicon for wet biology: genetic engineering, engineered plagues, vat-grown organisms and body modification under amoral corporations. The term circulated in early-1990s genre criticism (Paul Di Filippo's Ribofunk, 1996, wears it on the cover), with precursors from Greg Bear's Blood Music (1985) onward, and a screen lineage running through David Cronenberg's body horror — The Fly (1986), eXistenZ (1999) — to Jeff VanderMeer's Annihilation (2014) and its bloom of refracted biology. Visually the aesthetic means membranes, spore clouds, surgical steel, amber specimen jars and coral-like growths over clean lab light: the future as organism rather than machine. Games and concept-art communities (Bloodborne's blood-minister horror among them) keep the vocabulary productive, usually at one remove from cyberpunk's neon.",
    col: [{ h: "#5c1a2e", n: "meat maroon" }, { h: "#c9c2a8", n: "specimen amber" }, { h: "#7fae8f", n: "culture green" }, { h: "#d8d3c8", n: "bone porcelain" }, { h: "#23161c", n: "organ black" }],
    m: ["translucent membrane film", "resin specimen blocks", "surgical steel", "gel culture medium"],
    tx: ["wet glistening surface", "membrane translucency", "spore fuzz", "resin amber depth"],
    obj: ["specimen jars", "cultured tissue vats", "surgical steel instruments", "spore clouds", "grafted symbiote growths"],
    ex: ["David Cronenberg's The Fly (1986)", "Jeff VanderMeer's Annihilation (2014)", "Paul Di Filippo's Ribofunk (1996)"],
    inf: ["body horror cinema", "laboratory specimen photography"], rel: ["Cyberpunk", "Cosmic horror", "Post-apocalyptic wasteland aesthetic"],
    par: "cyberpunk derivatives", var: ["ribofunk", "bio-horror editorial"], cf: ["body horror (film genre versus aesthetic stance)"],
    src: [{ n: "Wikipedia — Biopunk", u: "https://en.wikipedia.org/wiki/Biopunk", t: "B" }, { n: "Wikipedia — Cyberpunk derivatives", u: "https://en.wikipedia.org/wiki/Cyberpunk_derivatives", t: "B" }],
    tg: ["biopunk", "body horror", "genetic engineering", "wet lab", "ribofunk"], pop: 34, niche: true,
    vd: { shape: "amoebic curves and vein networks", line: "organic tendrils, no straight edges", composition: "specimen-in-frame, viewer as examiner", texture: "wet gloss over matte flesh", forms: "membranes, veins, spores, grafts, vats" },
    typ: { display: "corroded experimental lettering", body: "monospaced lab record", notes: "specimen labels, batch codes, clinical caps" },
    fnt: { display: "Rubik Glitch", body: "Space Mono", notes: "corrupted display over clinical monospace" },
    lit: { quality: "cold clinical with bioluminescent pockets", direction: "overhead surgical", temperature: "cold green-amber", shadow: "wet, clinging" },
    pho: { approach: "macro specimen photography, clinical staging", grade: "sickly green-amber, milky highlights" },
    fash: { silhouettes: "asymmetric bio-grown overlays over fitted base", garments: "translucent membrane layers, harness strapping", acc: "sample vials, prosthetic accents, glass" },
    env: { places: "vat rooms, quarantine corridors, overgrown labs", weather: "humid greenhouse stale air" },
    gd: { layout: "clinical grid broken by growths crossing gutters", icon: "cell dividing or biohazard trefoil" },
    ui: { background: "#23161c", surface: "amber translucent panels", components: "specimen-tag chips, barcode labels", motion: "slow pulse and drip" },
    rec: { materials: "resin, glass, surgical steel", lighting: "specimen-tank glow", objects: "pipettes, petri dishes, bone models", music: "wet granular ambient, dental-drill drones", scent: "antiseptic, iron, pond warmth" },
    snd: ["viscous drip", "humid equipment hum", "slow heartbeat pulse"],
    dna: { mi: 55, og: 80, wc: 45, ns: 60, ad: 55, hf: 80, rr: 80, ps: 70, sh: 80, ql: 45, oc: 60, ds: 45, rs: 60, eu: 60, np: 40 },
    emo: { warm: 25, cold: 70, playful: 20, serious: 75, chaotic: 65, ordered: 40, nostalgic: 30, futuristic: 80, peaceful: 15, ominous: 85 },
  },
  {
    n: "Post-apocalyptic wasteland aesthetic", a: ["wasteland style", "desert raider look"],
    cat: "Science Fiction & Fantasy", c: "aftermath genre visual language", e: "historical",
    o: "nuclear-age fiction and film; codified by Mad Max 2 (1981)", g: "US and Australian genre film; global fandom",
    p: "c. 1950s–present; peak visual identity in the 1980s", era: "atomic anxiety to oil-crisis cinema",
    sum: "Scavenged armour, rusted vehicles and desert settlements: the visual grammar of civilization's aftermath.",
    desc: "The wasteland aesthetic grew from nuclear-age fiction — On the Beach (1957) set the genre's dread — but its look was codified by George Miller's Mad Max films, above all The Road Warrior (1981): road-leather armour, mohawks, shoulder pads, spiked and supercharged vehicles, gasoline as treasure, tribal gangs across Australian desert. The formula spread through The Terminator's future flashbacks, Judge Dredd's Cursed Earth, countless Italian derivatives, and later games (Fallout's retro-atomic ruin, Rage) and festivals like Wasteland Weekend (since 2010), where fans build full costume-and-vehicle camps. The palette is rust, dust and scavenged military surplus; the grammar is salvage — every object repaired, re-purposed, re-fought over. It remains the default image of 'the world after', flexible enough to carry ecological, nuclear or plague anxieties in turn.",
    col: [{ h: "#b0873f", n: "rust ochre" }, { h: "#8a5a33", n: "oxidized brown" }, { h: "#d9c49a", n: "dust cream" }, { h: "#4a3a2f", n: "scorched umber" }, { h: "#6f7570", n: "salvage grey" }],
    m: ["scrap mild steel", "road-weathered leather", "military canvas", "rusted vehicle plate"],
    tx: ["rust bloom and pitting", "cracked leather grain", "dust film on everything", "weld bead roughness"],
    obj: ["armoured vehicles with spikes", "road-leather shoulder pads", "scavenged gas masks", "windmill-punk water stills", "bartered fuel cans"],
    ex: ["The Road Warrior (George Miller, 1981)", "Wasteland Weekend festival, California", "Fallout series' retro-ruined America"],
    inf: ["biker kustom kulture", "military surplus desert styling"], rel: ["Dieselpunk", "Cyberpunk", "Kustom kulture"],
    par: "apocalyptic genre imagery", var: ["nuclear winter palette", "desert raider styling"], cf: ["dieselpunk (machines before the collapse)"],
    src: [{ n: "Wikipedia — Apocalyptic and post-apocalyptic fiction", u: "https://en.wikipedia.org/wiki/Apocalyptic_and_post-apocalyptic_fiction", t: "B" }, { n: "Wikipedia — Mad Max", u: "https://en.wikipedia.org/wiki/Mad_Max", t: "B" }],
    tg: ["wasteland", "post apocalyptic", "mad max", "salvage", "desert raiders"], pop: 46, niche: false,
    vd: { shape: "layered asymmetric salvage silhouettes", line: "scavenged seams and welded joins", composition: "lone figure against vast empty horizon", texture: "rust, dust, cracked rubber", forms: "vehicles, goggles, canisters, bones, ruins" },
    typ: { display: "sandblasted stencil caps", body: "plain industrial sans", notes: "spray-stencil distress, ration-stamp labels" },
    fnt: { display: "Rubik Distressed", body: "Barlow", notes: "eroded display over plain utilitarian body" },
    lit: { quality: "blinding desert glare through dust", direction: "overhead furnace light", temperature: "hot neutral", shadow: "hard, short, resource-saving" },
    pho: { approach: "heat-shimmer desert photography, telephoto compression", grade: "amber dust wash, crushed shadows" },
    fash: { silhouettes: "layered asymmetric armour over wraps", garments: "road leather, moto pads, repurposed tires", acc: "goggles, respirators, spike studs" },
    env: { places: "dry lakebeds, wrecked interchanges, water-barter towns", weather: "dust storms and white heat" },
    gd: { layout: "stamped ration-card grid with warning stripes", icon: "radiation trefoil or skull stamp" },
    ui: { background: "#4a3a2f", surface: "corrugated salvage panels", components: "welded-plate buttons, analog meters", motion: "gritty shake and settle" },
    rec: { materials: "rust, leather, canvas", lighting: "single work lamp and firelight", objects: "jerry cans, gas masks, blowtorches", music: "percussive scrap-metal industrial", scent: "gasoline, hot dust, cooked metal" },
    snd: ["v8 engine growl", "wind across wreck fields", "chain-link clank"],
    dna: { mi: 55, og: 60, wc: 55, ns: 45, ad: 30, hf: 50, rr: 85, ps: 55, sh: 75, ql: 55, oc: 60, ds: 45, rs: 60, eu: 60, np: 50 },
    emo: { warm: 55, cold: 45, playful: 35, serious: 60, chaotic: 70, ordered: 30, nostalgic: 45, futuristic: 50, peaceful: 20, ominous: 70 },
  },
  {
    n: "Cosmic horror", a: ["lovecraftian look", "eldritch visual culture"],
    cat: "Science Fiction & Fantasy", c: "weird-fiction dread imagery", e: "historical",
    o: "Lovecraft's Cosmicism in 1920s pulp weird fiction", g: "US weird fiction; global",
    p: "c. 1919–present", era: "weird tales to contemporary horror",
    sum: "Insignificance before unknowable entities: tentacles, impossible geometry and dread beyond human scale.",
    desc: "Cosmic horror is the weird-fiction tradition H. P. Lovecraft articulated as Cosmicism: humanity's utter unimportance in an indifferent cosmos, with horror arising from knowledge rather than violence. Its imagery — tentacled things, deep-sea and deep-time forms, non-Euclidean architecture, forbidden books and degenerating rituals across decaying New England towns — was fixed in stories like The Call of Cthulhu (1928) and spread by August Derleth's Arkham House publishing. The visual language has proven highly migratory: John Carpenter's The Thing (1982) pushed it through practical effects, games like Bloodborne (2015) built whole cities from its dread, and True Detective's first season carried it into prestige television. Contemporary illustration stresses scale and geometry — things too large, too old or too alien to parse — keeping the aesthetic defined by what cannot be fully depicted.",
    col: [{ h: "#101720", n: "abyssal navy" }, { h: "#3f6e63", n: "deep-sea green" }, { h: "#c7c2b4", n: "bone ivory" }, { h: "#6b2b45", n: "elder violet" }, { h: "#0a0a0c", n: "void black" }],
    m: ["wet stone", "inks and dry-brush wash", "aged manuscript paper", "bioluminescent gel accents"],
    tx: ["abyssal depth gradient", "slimy wet sheen", "cyclopean stone roughness", "ink bleed bloom"],
    obj: ["tentacles", "cyclopean ruins", "forbidden tomes", "ritual sigils", "bioluminescent deep-sea forms"],
    ex: ["H.P. Lovecraft's The Call of Cthulhu (1928)", "John Carpenter's The Thing (1982)", "Bloodborne (FromSoftware, 2015)"],
    inf: ["gothic literature", "deep-sea natural history illustration"], rel: ["Biopunk", "Post-apocalyptic wasteland aesthetic", "Sword & sorcery"],
    par: "weird fiction tradition", var: ["deep-sea eldritch", "folk-cosmic horror"], cf: ["splatter horror (visceral versus cosmic dread)"],
    src: [{ n: "Wikipedia — Cosmicism", u: "https://en.wikipedia.org/wiki/Cosmicism", t: "B" }, { n: "Wikipedia — H. P. Lovecraft", u: "https://en.wikipedia.org/wiki/H._P._Lovecraft", t: "B" }],
    tg: ["cosmic horror", "lovecraftian", "eldritch", "cthulhu", "weird fiction"], pop: 42, niche: false,
    vd: { shape: "vast asymmetrical masses beyond frame", line: "writhing tentacle curves against rigid geometry", composition: "tiny human figures dwarfed by unknowable scale", texture: "wet stone, slime, ink wash", forms: "tentacles, eyes, ruins, stars, sigils" },
    typ: { display: "decaying victorian serif with corrupted alternates", body: "scholarly old-style serif", notes: "manuscript-style footnotes, corrupted glyph moments" },
    fnt: { display: "Eater", body: "Crimson Pro", notes: "contorted horror display over antiquarian serif body" },
    lit: { quality: "moonless fog with single distant glow", direction: "unlocated, sourceless dread light", temperature: "cold", shadow: "absolute, taking the frame" },
    pho: { approach: "scale-dwarfing compositions, obscured subjects", grade: "desaturated cold with sickly green cast" },
    fash: { silhouettes: "heavy draping scholarly layering", garments: "antique coats, cassock lines, coats too big", acc: "signet rings, talismans, pocket watches" },
    env: { places: "fog-bound ports, decaying mansions, polar ice fields", weather: "sea fog and unnatural stillness" },
    gd: { layout: "unstable text blocks sliding into void margins", icon: "eye within spiral sigil" },
    ui: { background: "#0a0a0c", surface: "bone-ivory manuscript panels", components: "inked sigil buttons, broken grids", motion: "slow impossible warping" },
    rec: { materials: "sea-wet stone, old paper, salt", lighting: "lantern in infinite fog", objects: "codex books, astrolabes, whale-oil lamps", music: "dissonant strings and sub-bass drones", scent: "brine, old paper, rain on stone" },
    snd: ["sub-bass ocean drone", "impossible choir whispers", "foghorn at distance"],
    dna: { mi: 55, og: 75, wc: 85, ns: 45, ad: 40, hf: 35, rr: 65, ps: 75, sh: 75, ql: 45, oc: 55, ds: 45, rs: 60, eu: 60, np: 45 },
    emo: { warm: 15, cold: 85, playful: 15, serious: 85, chaotic: 60, ordered: 40, nostalgic: 35, futuristic: 45, peaceful: 10, ominous: 95 },
  },
  {
    n: "Sword & sorcery", a: ["S&S fantasy", "Conan-style heroic fantasy"],
    cat: "Science Fiction & Fantasy", c: "pulp heroic fantasy imagery", e: "historical",
    o: "pulp magazines, 1930s (Robert E. Howard)", g: "US pulp tradition; global",
    p: "c. 1932–present", era: "weird tales to modern fantasy",
    sum: "Muscular barbarians, decaying ruins and dark sorcery: the gritty, episodic branch of fantasy Robert E. Howard founded.",
    desc: "Sword and sorcery is the pulpy, personal-stakes branch of fantasy named by Fritz Leiber in 1961 and founded in Robert E. Howard's Conan stories (Weird Tales, from 1932's 'The Phoenix on the Sword'): lone adventurers, decaying pre-modern civilizations, thieving, fighting and dark magic, rather than epic quests to save worlds. Its visual identity was fixed by cover artists — above all Frank Frazetta, whose 1960s-70s Conan paintings defined the oiled-muscle, brooding-ruin, serpent-cult look, with Roy Krenkel and Boris Vallejo alongside — and carried into John Milius's Conan the Barbarian (1982) and heavy-metal album art. The mode's contrast with Tolkien-style high fantasy is structural: episodic, morally grey, sensual and violent. Grimdark fantasy descends from its grittier end, while its decadent-ruin imagery remains the default look of barbarian fantasy everywhere.",
    col: [{ h: "#a5552a", n: "sun-scorched bronze" }, { h: "#3f2a1d", n: "ruin brown" }, { h: "#c9a44a", n: "gold idol" }, { h: "#5e1f2b", n: "sorcery wine" }, { h: "#15100c", n: "cavern black" }],
    m: ["oil paint on board", "burnished bronze props", "weathered stone", "tool-dyed leather"],
    tx: ["broad painterly brushwork", "bronze muscle sheen", "stone decay texture", "leather strap wear"],
    obj: ["broadswords and axes", "decaying temples", "serpent idols", "fur-and-strap armour", "smoking braziers"],
    ex: ["Frank Frazetta's Conan cover paintings", "Robert E. Howard's The Phoenix on the Sword (1932)", "Conan the Barbarian (John Milius, 1982)"],
    inf: ["pulp magazine cover painting", "historical adventure illustration"], rel: ["Grimdark", "High fantasy", "Cosmic horror"],
    par: "fantasy genre imagery", var: ["grimdark (grittier descendant)", "dark sword & sorcery"], cf: ["high fantasy (epic scope versus episodic grit)"],
    src: [{ n: "Wikipedia — Sword and sorcery", u: "https://en.wikipedia.org/wiki/Sword_and_sorcery", t: "B" }, { n: "Wikipedia — Robert E. Howard", u: "https://en.wikipedia.org/wiki/Robert_E._Howard", t: "B" }],
    tg: ["sword and sorcery", "conan", "frazetta", "pulp fantasy", "barbarian"], pop: 38, niche: false,
    vd: { shape: "twisted heroic torsos and looming ruins", line: "energetic brush contour over musculature", composition: "warrior atop dead civilization, torch-lit", texture: "thick oil strokes, smoke haze", forms: "swords, idols, thrones, serpents, flames" },
    typ: { display: "runic-flavoured uncial and carved caps", body: "sturdy old-style serif", notes: "parchment stains, chapter-drop capitals" },
    fnt: { display: "Uncial Antiqua", body: "EB Garamond", notes: "carved uncial display over bookish serif body" },
    lit: { quality: "torch and braziers against night ruins", direction: "warm underlight from fires", temperature: "hot amber with cold voids", shadow: "deep romantic gloom" },
    pho: { approach: "painted-cover logic: staged heroic tableaux", grade: "bronze-warm with wine-dark shadows" },
    fash: { silhouettes: "minimal leather armour, fur mantles, bare-armed power", garments: "strap harnesses, loincloths, cloaks, chainmail hints", acc: "torques, sword belts, gem-encrusted hilts" },
    env: { places: "ruined temples, tavern tables, mountain passes", weather: "storm-breaking dusk" },
    gd: { layout: "central figure with arc title, torch flare borders", icon: "crossed sword and serpent" },
    ui: { background: "#15100c", surface: "parchment and bronze panels", components: "forged-metal buttons", motion: "heavy blade-draw reveals" },
    rec: { materials: "bronze, fur, stained oak", lighting: "brazier uplight", objects: "idols, maps, wine horns", music: "war drums and low male chorales", scent: "woodsmoke, leather, spilled mead" },
    snd: ["forging hammer ring", "distant war drums", "tavern roar"],
    dna: { mi: 70, og: 65, wc: 60, ns: 35, ad: 20, hf: 15, rr: 60, ps: 50, sh: 70, ql: 60, oc: 50, ds: 55, rs: 55, eu: 50, np: 60 },
    emo: { warm: 55, cold: 45, playful: 30, serious: 70, chaotic: 55, ordered: 40, nostalgic: 55, futuristic: 10, peaceful: 20, ominous: 70 },
  },
];
