/**
 * Completeness patch r2e — Architecture + Art Movement batch (20 entries).
 * Hand-authored from live manifest slugs; no LLM involvement.
 */
export const PATCHES: any[] = [
  {
    slug: 'lingnan-gardens',
    ctx: 'Lingnan gardens — Cantonese landscape architecture of Guangdong\'s subtropics — evolved Jiangnan garden logic for humid heat: smaller courtyards, water everywhere (pools, mist, lily ponds), open pavilions with cool draft design, Qing-style gray-brick and porcelain-work (Shiwan), and imported elements from overseas Chinese trade. Key sites: Shunde\'s Qinghui Garden, Panyu\'s Yuyin Shanfang, Dongguan\'s Keyuan. Lingnan\'s "four famous gardens" anchor the south\'s merchant-scholar identity distinct from Suzhou\'s reserved elegance.',
    vd: { shape: 'compact courtyard water gardens with winding corridors', composition: 'pavilion-view framing around pools and mist rocks', line: 'gray brick arcades, openwork window lattices', texture: 'porcelain-cut panel glaze, lotus leaf sheen, bamboo and banyan shade' },
    typ: { display: 'horizontal board (bian e) calligraphy at pavilions', notes: 'poetic couplets on column pairs' },
    lit: { quality: 'humid subtropical filtered glare', temperature: 'cool-toned', shadow: 'banyan canopies dapple water courts' },
    ui: { background: 'lotus-pond green', surface: 'porcelain-panel cards', components: 'lattice-window frames', motion: 'mist-over-pool drift loops' },
  },
  {
    slug: 'lanna-thai-architecture',
    ctx: 'Lanna architecture — the northern Thai (Chiang Mai, Chiang Rai) kingdom\'s building tradition — elevates teak temples (wat) on sling-stone bases: huge carved ho trai scripture libraries on high stilted platforms, multi-tiered thatch-and-teak roofs, chofa-less finials of naga serpents, and viharn halls whose carved gables (phan fa) blaze gold. Burmese and Shan craft enriched 19th-century rebuilds (Wat Phra That Doi Suthep, Wat Chedi Luang); Lanna\'s warm timber glow now defines "northern Thai" resort architecture worldwide.',
    vd: { shape: 'multi-tier sweeping roofs over timber temple halls', composition: 'stilted ho trai libraries as ornamental focal points', line: 'naga bargeboard curves, carved gable flames', texture: 'teak carving, gold leaf on gables, thatch tiers, stone chedi bases' },
    typ: { display: 'gold-on-teak Lanna Tham script panels', notes: 'donor names carved in gable beams' },
    lit: { quality: 'teak-shade warm temple dusk', temperature: 'warm-toned', shadow: 'tier roofs shade open viharn halls' },
    ui: { background: 'teak golden brown', surface: 'carved-gable cards', components: 'naga-finial dividers', motion: 'lantern-lit procession pans' },
  },
  {
    slug: 'great-zimbabwe-architecture',
    ctx: 'Great Zimbabwe (11th-15th c., UNESCO) — the medieval Shona capital — built Africa\'s largest ancient stone complex without mortar: the Great Enclosure\'s 11m-high walls of hand-fitted granite blocks, the conical tower, and hill-complex enclosures aligned to sacred astronomy. The name gave the modern nation its identity; colonial denial (crediting Phoenicians) was overturned by archaeological consensus, and the soapstone Zimbabwe Birds from the site are the national emblem.',
    vd: { shape: 'curved granite dry-stone walls in enclosures and cones', composition: 'hill acropolis above valley enclosures', line: 'regular course banding, patterned wall courses', texture: 'granite block warmth, lichen patina, grass thatch cone accents' },
    typ: { display: 'none', body: 'soapstone bird icons as emblem script', notes: 'ritual text spoken in stone geometry' },
    lit: { quality: 'highveld granite-noon glare', temperature: 'warm-toned', shadow: 'curved walls track deep circular shade' },
    ui: { background: 'granite grey-brown', surface: 'dry-stone cards', components: 'course-band dividers', motion: 'conical-tower reveal ascent' },
  },
  {
    slug: 'papuan-longhouse',
    ctx: 'The Papuan and Melanesian longhouse — communal ceremonial architecture of Papua New Guinea\'s Highlands, Sepik and Asmat regions — houses clans under one sweeping thatch: carved spirit poles and gable masks (korogo, bai tambaran), central fire lanes, men\'s-house sanctums holding ancestors, and painted facade emblems of lineage. Cultures (Asmat, Chambri, Dani) vary the form; longhouse ceremonies remain the Pacific\'s great social architectures of performance and memory.',
    vd: { shape: 'vaulted thatch profiles with upswept gable horns', composition: 'spirit-pole axes through central fire halls', line: 'painted facemotif bands on gable screens', texture: 'sago-thatch shag, carved hardwood, ochre-and-white pigment' },
    typ: { display: 'carved and painted spirit-gable figures', notes: 'clan story told in facade emblems' },
    lit: { quality: 'fire-glow under dark thatch vault', temperature: 'warm-toned', shadow: 'pole shadows dance with firelight' },
    ui: { background: 'thatch dark brown', surface: 'carved-pole cards', components: 'gable-mask icons', motion: 'fire-flicker ambient loops' },
  },
  {
    slug: 'soviet-mosaics-in-architecture',
    ctx: 'Soviet architectural mosaics (1960s-1980s) — Kyiv\'s "golden mile" murals, Tashkent\'s ceramic facades, Palanga\'s sanatorium panels — fused Smalti smalt glass and tile into socialist optimism: astronauts, workers, sunbursts and folk-motif patterns covering airport, hotel and institute walls. Artists (Ada Rybachuk, Vladimir Melnichenko, Uzbek workshops) made the USSR\'s largest public-art program; post-Soviet demolition debates (Kyiv\'s "protect the mosaics" campaigns) now treat them as endangered modern heritage.',
    vd: { shape: 'facade-scale image fields in smalti and ceramic relief', composition: 'heroic figures and sunburst motifs spanning elevations', line: 'mosaic pixel contours, glazed relief bands', texture: 'glass smalti glitter, glazed ceramic sheen, concrete setting beds' },
    typ: { display: 'block-letter Soviet slogans in mosaic', notes: 'building names as mural captions' },
    lit: { quality: 'streetlight-energized night glitter', temperature: 'cool-toned', shadow: 'relief tiles modulate facade shade' },
    ui: { background: 'smalti blue-gold', surface: 'mosaic-panel cards', components: 'tile-pixel dividers', motion: 'panel-glitter shimmer loops' },
  },
  {
    slug: 'kura-dozou',
    ctx: 'The kura (dozou) — Japanese fireproof storehouses — protected merchant wealth through Edo-period fires: thick mud-and-plaster walls over timber frames (dozozukuri), tiny barred windows, double-plate metal doors, whitewashed or blackened plaster surfaces, and stepped gables (shireba) whose heights signaled the owner\'s fortune. Kurashiki\'s canal-side kura quarter and Hakodate\'s warehouses preserve the type; storehouse aesthetics (compactness, dark shutters, plaster patina) remain the image of Japanese mercantile prudence.',
    vd: { shape: 'stubby fortress-like boxes with stepped gable walls', composition: 'storehouse rows along canal and street faces', line: 'heavy door plates, barred slit windows', texture: 'smooth ochre or black plaster, metal door sheen, roof tile ridges' },
    typ: { display: 'family crests (mon) on door plates', notes: 'merchant marks as brand identity' },
    lit: { quality: 'canal-morning cool light', temperature: 'cool-toned', shadow: 'stepped gables shade canal walks' },
    ui: { background: 'plaster white-black', surface: 'storehouse-wall cards', components: 'door-plate icons', motion: 'double-door slow seal' },
  },
  {
    slug: 'hakka-walled-villages',
    ctx: 'Hakka walled villages — beyond Fujian\'s round tulou, the Guangdong rectangular walled compounds (weilongwu, "dragon-ring houses") of Meizhou and Shenzhen — enclosed clan life in fortress geometry: square perimeter walls with corner watchtowers, half-moon ponds, ancestral halls on axis, and layered defensive courtyards. Distinct from tulou\'s rammed-earth rings, the Guangdong weilong built brick-and-stone; sites like Shenzhen\'s Dapeng Fortress and Ganxi\'s Hakka villages anchor the migration-history tourism of the Hakka diaspora.',
    vd: { shape: 'square perimeter walls with corner towers and moon ponds', composition: 'ancestral hall axis facing half-moon water', line: 'watchtower crenels, layered courtyard thresholds', texture: 'grey brick and stone base, timber galleries, tile shadow on lanes' },
    typ: { display: 'clan-name stone plaques at gates', notes: 'ancestor tablets as hall text' },
    lit: { quality: 'subtropical courtyard glare', temperature: 'warm-toned', shadow: 'watchtowers shade wall lanes' },
    ui: { background: 'brick grey', surface: 'courtyard-axial cards', components: 'moon-pond frames', motion: 'gate-threshold procession pan' },
  },
  {
    slug: 'ganch-plasterwork',
    ctx: 'Ganch — Central Asia\'s carved gypsum plaster — made Bukhara, Khiva and Samarkand interiors glow: ganch-dastakali deep-carved geometric and botanical reliefs (suzani-like mesh), painted-and-gilded crusts on madrasah niches, and complete room programs in muqarnas-linked panels. Masters (ustokoron) transmitted pattern families; the craft survives in restoration ateliers under UNESCO intangible-heritage programs. Ganch\'s whiteness turns any shaft of light into lace.',
    vd: { shape: 'deep-carved mesh reliefs filling niche and wall fields', composition: 'muqarnas-linked panels framing doors and windows', line: 'girih star and botanical scroll contours', texture: 'matte gypsum whiteness, painted-and-gilt accent crusts' },
    typ: { display: 'carved thuluth calligraphy medallions', notes: 'poetry panels in relief frames' },
    lit: { quality: 'courtyard-shaft light on white relief', temperature: 'warm-toned', shadow: 'deep cuts print lace shadows' },
    ui: { background: 'gypsum white', surface: 'carved-relief cards', components: 'girih-star dividers', motion: 'light-sweep lace reveals' },
  },
  {
    slug: 'dhow-boat-decoration',
    ctx: 'Dhow decoration — the Indian Ocean sailing vessel\'s ornamental culture (Oman, Zanzibar, Gujarat, Kuwait) — carved prows (qarqab), painted eyes (nakhoda "compass eyes"), stitched-seam patterns, raked mast garlands and cargo-hold geometricains into working ships: the sea as canvas. Dhows carried the Swahili, Arabian and Indian coasts\' trade for two millennia; surviving yards (Sur, Oman) and regattas (Al Gaffal) keep the craft, while museum dhows preserve the eye-and-carving grammar.',
    vd: { shape: 'swept lateen profiles with carved prow tiers', composition: 'eye motif at bows, cargo bands midship', line: 'stitch-seam rows, carved rail courses', texture: 'teak grain, painted hull bands, brass tacks, sail canvas patchwork' },
    typ: { display: 'painted vessel names in Arabic script', notes: 'owner marks carved on prow blocks' },
    lit: { quality: 'sea-glare tropical noon', temperature: 'warm-toned', shadow: 'lateen sail shades the deck sweep' },
    ui: { background: 'ocean deep blue', surface: 'hull-band cards', components: 'compass-eye icons', motion: 'lateen-sail billow loops' },
  },
  {
    slug: 'halsingland-farmhouse-interiors',
    ctx: 'Hälsingland\'s decorated farmhouse interiors (UNESCO, seven farms) — 19th-century Swedish timber wealth — painted whole rooms for weddings and identity: stencil-and-stencil marbling (imitating wallpaper and stone), biblical and pastoral scenes by itinerant painters (dalkullor painters), ten+ decorated rooms per farm including unused "status chambers". The farms\' stenciled profiles (Bortom Åa, Gästgivars) are Sweden\'s most complete vernacular interiors, and painted-farm restoration supports a living craft school.',
    vd: { shape: 'full-room stenciled walls, ceilings and door linings', composition: 'stencil marbling framing painted landscape panels', line: 'stencil-register repeats, faux-molding borders', texture: 'distemper matte, stencil edge fuzz, tobacco-stained patina' },
    typ: { display: 'biblical and farm-name wall lettering panels', notes: 'wedding dates and psalm verses painted' },
    lit: { quality: 'tall window northern summer light', temperature: 'warm-toned', shadow: 'stencil depth shadows under stenciling' },
    ui: { background: 'stencil cream-blue', surface: 'faux-marble cards', components: 'stencil-border frames', motion: 'wedding-procession room pans' },
  },
  {
    slug: 'finnish-church-villages',
    ctx: 'Finnish church villages (kirkonkylä) — UNESCO-listed Petäjävesi Old Church, Sonkajärvi, the Sastamala clusters — organized rural Finland around timber churches: not-gated freeholds (erämaaluvat) where farmers built cabins for feast-weekends, bell towers as village gateposts, and wooden vernacular (log-and-craft) united by church roads. The pattern — church, bell tower, rectory, stable-cabins — structures Finland\'s rural landscape and Protestant-vernacular identity; Petäjävesi\'s 1765 log church is the movement\'s masterpiece.',
    vd: { shape: 'log church with layered crossed-rod roof geometry', composition: 'village clusters radiating from church and bell tower', line: 'log-course rhythm, shingle roof bands', texture: 'unpainted log silver, tarred shingle, ironwork gates, church-green surrounds' },
    typ: { display: 'carved alms-box and pew-end inscriptions', notes: 'confirmation dates scratched in doorposts' },
    lit: { quality: 'midnight-summer whitened daylight', temperature: 'cool-toned', shadow: 'bell towers cast village sundial shade' },
    ui: { background: 'log silver grey', surface: 'shingle-band cards', components: 'bell-tower icons', motion: 'feast-week procession pans' },
  },
  {
    slug: 'sognefjord-stave-churches',
    ctx: 'The stave churches of Sognefjord — Urnes (UNESCO, c. 1130, oldest surviving), Borgund, Hopperstad — are Norway\'s medieval wooden cathedrals: stave-frame construction with carved portals in Urnes-style dragon interlace, tiered roofs with dragon-head finials, and dark tar-black timber against fjord green. Once 1,000+, twenty-eight survive; the Urnes portal\'s wandering animal carving is Viking-Romanesque transition\'s masterpiece, and the churches anchor "fjord Norway" cultural tourism.',
    vd: { shape: 'tiered steep roofs with dragon finials over stave frames', composition: 'carved west portals as narrative gates', line: 'Urnes dragon interlace contours', texture: 'tar-blackened pine, carved wood depth, ironwork hinges, fjord-mist damp' },
    typ: { display: 'runic and carved portal inscriptions', notes: 'stave crosses scratched by pilgrims' },
    lit: { quality: 'fjord-gorge filtered daylight', temperature: 'cool-toned', shadow: 'tier roofs shade dark timber walls' },
    ui: { background: 'tar black-brown', surface: 'carved-portal cards', components: 'dragon-finial dividers', motion: 'mist-drift fjord loops' },
  },
  {
    slug: 'dogon-architecture',
    ctx: 'Dogon architecture — Bandiagara Escarpment, Mali (UNESCO) — climbs cliffs in granary-and-gnawa compounds: toguna men\'s meeting shelters on thick millet-stalk columns, granaries with pottery-sealed lids, hogon chief\'s houses, and cliff-cave burials connecting to Tellem predecessor structures. The plan encodes cosmology (Nommo twins, Nummo spiral), and the granary facades — doors, ladders, coffered lids — became the most collected African sculptural architecture, with Amahyé masks and dama ceremonies animating the compounds.',
    vd: { shape: 'stacked cliff granaries with pointed thatch caps', composition: 'toguna columns shading elder councils', line: 'coffered granary lids, carved door reliefs', texture: 'millet stalk and mud plaster, carved hardwood doors, ironwood ladders' },
    typ: { display: 'carved granary door figures as narrative text', notes: 'cosmogram patterns in facade relief' },
    lit: { quality: 'Sahel-escarpment golden glare', temperature: 'warm-toned', shadow: 'toguna roofs shade council circles' },
    ui: { background: 'escarpment ochre', surface: 'granary-relief cards', components: 'ladder-rung dividers', motion: 'mask-dance procession loops' },
  },
  {
    slug: 'khorezmian-conical-minarets',
    ctx: 'Khorezm\'s conical minarets — Urgench\'s Kutlug Timur (60m, 12th-14th c.), Uzbekistan\'s tallest, with Turkmenistan\'s Köneürgenç siblings — are the Central Asian brick tower\'s other branch: not Samarkand\'s cylindrical taper but stepped conical profiles with turquoise glazed bands and muqarnas lantern crowns, built by Khwarazmian masters along the Amu Darya. Earthquake-scarred but standing, they anchor the UNESCO-listed "monumental bricks" of the Khwarezm oasis and the Ghaznavid-to-Timurid tower lineage.',
    vd: { shape: 'tall stepped-cone brick shafts with glazed band rings', composition: 'lone-tower skylines over oasis fields', line: 'band-course taper rhythm, muqarnas crowns', texture: 'rose fired brick, turquoise glaze accents, wind-polished mortar' },
    typ: { display: 'Kufic band inscriptions at mid-shaft', notes: 'date-and-ruler formulae in glaze bands' },
    lit: { quality: 'oasis-haze desert sunset', temperature: 'warm-toned', shadow: 'cones cast long oasis shadows' },
    ui: { background: 'desert rose-brick', surface: 'band-course cards', components: 'cone-taper dividers', motion: 'caravan-distance pan' },
  },
  {
    slug: 'tata-somba-architecture',
    ctx: 'Tata Somba — Benin and Togo\'s fortified house-towers (UNESCO-listed Koutammakou landscape for the Batammariba) — stack defense and domesticity in clay: two-to-three story turrets with granary ears, granary-and-living floors, spiked battle-proof walls, and rooftop sleeping platforms reached by interior ladders. Each tata is a family castle; the landscape of 100+ towers against the Atakora hills is West Africa\'s most striking vernacular skyline, still built by tabarma masons with ceremonial foundations.',
    vd: { shape: 'towered clay compounds with granary turret ears', composition: 'family fortresses on hill saddle terraces', line: 'spiked wall crowns, tower-step profiles', texture: 'hand-molded clay plaster, straw-tempered walls, thatch caps' },
    typ: { display: 'none', body: 'ritual marks molded at entry walls', notes: 'clan history spoken in tower additions' },
    lit: { quality: 'Atakora-plateau dry-season glare', temperature: 'warm-toned', shadow: 'turrets shade roof platforms by noon' },
    ui: { background: 'clay terracotta', surface: 'tower-turret cards', components: 'granary-ear icons', motion: 'ladder-climb ascent loops' },
  },
  {
    slug: 'sienese-mannerism',
    ctx: 'Sienese Mannerism — the Sienese school\'s late flourish after Baldassare Peruzzi and Perino del Vaga — ran Renaissance Siena\'s marble-and-brick craft into ornamental extremes: candelabra-flat facades, fanciful loggias (Loggia del Papa), terracotta-and-marble porticoes, and Peruzzi\'s stage-set spatial illusions. Peruzzi\'s drawings influenced Serlio and the general Mannerist grammar; Siena\'s bank palaces (Spannocchi, Tolomei) show the style\'s merchant-craft elegance against Florence\'s Tuscan bravura.',
    vd: { shape: 'flat candelabra facades with fanciful portal framing', composition: 'loggia and courtyard stage-set spatial play', line: 'finely carved terra and marble bands', texture: 'polychrome marble intarsia, terracotta relief, pietra serena frames' },
    typ: { display: 'engraved cartouche plaques over portals', notes: 'bank-family crests in spandrel roundels' },
    lit: { quality: 'Tuscan-courtyard filtered glow', temperature: 'warm-toned', shadow: 'loggia arches shade street benches' },
    ui: { background: 'terracotta warm', surface: 'marble-intarsia cards', components: 'cartouche-plaque frames', motion: 'stage-set courtyard pans' },
  },
  {
    slug: 'dong-drum-towers-and-wind-rain-bridges',
    ctx: 'The Dong people\'s drum towers and wind-rain bridges — Guizhou, Guangxi, Hunan (Chengyang\'s Yongji Bridge is the icon) — build mortise-and-tenon timber cities without nails: multi-tier drum towers (drum court, fire hearth, up to 17 stacked eaves), covered bridges whose corridors shelter markets and rest, and canal-set village plans linking water, paddy and clan squares. Dong carpenters (bigsu) transmit the craft orally; the structures are UNESCO intangible-heritage celebrated and China\'s most photographed wooden vernacular.',
    vd: { shape: 'pagoda-eave drum towers and long covered bridge spines', composition: 'village square clustering around tower and bridge axes', line: 'stacked eave tiers, corbel bracket rhythm', texture: 'fir timber grain, grey tile layers, fresh-cut shingle bright edges' },
    typ: { display: 'carved donor boards and village-name plaques', notes: 'drum-tower inscriptions as clan records' },
    lit: { quality: 'misty valley morning light', temperature: 'cool-toned', shadow: 'tier eaves shade bridge benches' },
    ui: { background: 'timber fir grey', surface: 'eave-tier cards', components: 'bridge-span dividers', motion: 'drumbeat-pulse rhythm loops' },
  },
  {
    slug: 'bukhara-wooden-doors',
    ctx: 'Bukhara\'s carved wooden doors — the Central Asian craft at its zenith (14th-19th c.) — made every mosque, madrasah and merchant house a threshold statement: deep-relief geometric star panels, linked kufic cartouches, dua-hand handles, and pine-and-elm carving so dense it reads as textile. Masters (khoja nurlon) signed lintels; the Ark citadel\'s doors and Bolo Hauz portals are canons, and Bukhara\'s workshop quarter (UNESCO intangible listing) still carves for trade and export.',
    vd: { shape: 'double-leaf doors as carved geometric image fields', composition: 'threshold framing with flanking carved columns', line: 'girih star lattice, kufic border cartouches', texture: 'deep-relief elm grain, walnut oil patina, iron strap-and-stud accents' },
    typ: { display: 'kufic cartouche calligraphy on lintels', notes: 'master-craftsman signatures under handles' },
    lit: { quality: 'threshold shaft-light on deep relief', temperature: 'warm-toned', shadow: 'carving depth prints door shadows' },
    ui: { background: 'elm walnut brown', surface: 'carved-star cards', components: 'door-handle icons', motion: 'threshold-swing reveal pans' },
  },
  {
    slug: 'musgum-earth-architecture',
    ctx: 'Musgum earth architecture — Cameroon and Chad\'s beehive shell huts (teleuk) — solve climate with pure geometry: clay-and-grass domes with ribbed surface ridges (drainage+structure+climbing scaffold), tiny crowned ventilation, and compound clusters of paired domes around grain courts. The ridged profile (musgum "herringbone") has been cited by Gaudí scholars and gridshell engineers alike; the huts build in days and last decades, renewed by women masons in family transmission.',
    vd: { shape: 'ribbed hemispherical clay domes in compound clusters', composition: 'paired shells around granary courts', line: 'structural rib ridges spiraling to crown vents', texture: 'smooth clay coat, rib shadow rhythm, straw fiber flecks' },
    typ: { display: 'none', body: 'pattern ribs as decorative structure', notes: 'form itself is the ornament' },
    lit: { quality: 'Sahel-savanna white glare', temperature: 'warm-toned', shadow: 'ribs stripe dome shade in spirals' },
    ui: { background: 'clay blush beige', surface: 'rib-dome cards', components: 'crown-vent icons', motion: 'rain-runoff rib shimmer' },
  },
  {
    slug: 'manierismo-lombardo',
    ctx: 'Lombard Mannerism — Galeazzo Alessi, Pellegrino Tibaldi, Martino Bassi — ran Milan\'s Counter-Reformation building into spatial experiments: Alessi\'s Marino and Anguissola palaces, Tibaldi\'s Piacenza Farnese and Milan Cathedral refits, perspective ambiguity, rusticated order-stacking and court-stage lobbies. The school carried Tuscan Mannerist grammar northward into church-and-court commissions and seeded the transition to Milan\'s Baroque; its cortili remain the city\'s hidden-room architecture.',
    vd: { shape: 'order-stacked courtyards with tensioned pediments', composition: 'perspective court-stages and staircase theaters', line: 'rusticated quoins against smooth giant orders', texture: 'bossed stone, stucco-framed fresco fields, marble portal frames' },
    typ: { display: 'Latin dedications in portal pediments', notes: 'patron crests in courtyard spandrels' },
    lit: { quality: 'cortile-filtered Milanese grey light', temperature: 'cool-toned', shadow: 'order-stacking shades the court stage' },
    ui: { background: 'bossed stone grey', surface: 'court-perspective cards', components: 'pediment-frames', motion: 'staircase-theater pans' },
  },
]
