/**
 * Completeness patch r2d — Architecture batch from live manifest slugs (20).
 * Hand-authored; no LLM involvement.
 */
export const PATCHES: any[] = [
  {
    slug: 'critical-regionalism',
    ctx: 'Critical Regionalism — theorized by Kenneth Frampton (1983) — asks modern architecture to answer place without kitsch: Tadao Ando\'s concrete engaging Japanese light and weather, Jørn Utzon\'s Battlemented Danish-to-Sydney crossbreeds, Geoffrey Bawa\'s Sri Lankan verandas. Against both universal International Style and nostalgic vernacular, it extracts local climate, craft and tectonic wisdom into contemporary form — the dominant serious position for regional architecture since.',
    vd: { shape: 'modern geometry tuned to local light, wind and rain logic', composition: 'veranda transitions mediating climate thresholds', line: 'material honesty with local craft joins', texture: 'local stone, brick, timber weaving through global modernism' },
    typ: { display: 'quiet architectural sans', notes: 'place names as design argument' },
    lit: { quality: 'region-specific daylight harvesting', temperature: 'varies by climate response', shadow: 'deep shading devices make climate legible' },
    ui: { background: 'site-specific neutrals', surface: 'veranda-threshold cards', components: 'brise-soleil dividers', motion: 'climate-response drift' },
  },
  {
    slug: 'vernacular-revival',
    ctx: 'Vernacular Revival — C.F.A. Voysey\'s English cottage school through most 20th-century nationalisms — reinterpreted local building (thatch, stone, half-timber, veranda) with modern comfort, becoming the default "tasteful traditional" architecture for suburbs, resorts and government housing. In Britain it anchored Arts-and-Crafts Domestic Revival; in Scandinavia and the alps it produced national-romantic housing; its grammar (steep roofs, small panes, honest materials) remains the marketing image of "countryside" living worldwide.',
    vd: { shape: 'steep roofs, deep eaves, locally-proportioned openings', composition: 'informal groupings around gardens and courts', line: 'hand-crafted joinery rhythms, swept valley lines', texture: 'local stone, clay render, thatch, sawn timber, ironwork' },
    typ: { display: 'carved village-sign lettering', notes: 'heritage-plaque serif' },
    lit: { quality: 'garden-window soft daylight', temperature: 'warm-toned', shadow: 'deep eaves shelter shaded porches' },
    ui: { background: 'limestone cream', surface: 'cottage-material cards', components: 'garden-path dividers', motion: 'gate-latch swing transitions' },
  },
  {
    slug: 'tulou-hakka-roundhouses',
    ctx: 'Fujian\'s Hakka tulou — UNESCO-listed rammed-earth roundhouses holding up to 800 people — are China\'s most communal vernacular: 3-5 story earthen rings around ancestral-hall courtyards, one gate, no exterior windows at ground level, bedrooms radiating outward with kitchens below. Built over centuries by Hakka migrants for clan defense and collective living, they astounded Cold-War satellites (mistaken for missile silos); Chengqi Lou and Tianluokeng cluster anchor Fujian\'s "earthen castle" tourism.',
    vd: { shape: 'giant earthen donuts with concentric timber rings', composition: 'ancestral hall at bullseye, kitchens ring first', line: 'rammed-earth strata, roof-tile concentric bands', texture: 'lime-tempered earth walls, dark timber galleries, grey tile rings' },
    typ: { display: 'clan-hall tablet calligraphy', notes: 'gate name boards in stone carving' },
    lit: { quality: 'ring-shadow courtyard diffusion', temperature: 'warm-toned', shadow: 'inner galleries shade in concentric bands' },
    ui: { background: 'rammed-earth tan', surface: 'courtyard-ring cards', components: 'gate-arch frames', motion: 'ring-pan slow orbit' },
  },
  {
    slug: 'kerala-architecture',
    ctx: 'Kerala architecture — Thachu-shastra timber tradition under monsoon climate — builds pitched-copper-roofed temples and nalukettu courtyard homes: steep gables shedding the southwest monsoon, carved timber columns and kathirmukham brackets, murals, and naalukettu\'s four-winged courtyard (nadumuttam) open to rain and light. The style\'s teak-and-laterite craft survives in Padmanabhapuram Palace and village temples; its low, hipped profile is Kerala\'s instant identity.',
    vd: { shape: 'steeply hipped copper roofs over low timber walls', composition: 'four-wing courtyard plans open to sky', line: 'carved timber bracket and cornice rhythm', texture: 'teak oil-dark columns, laterite block, copper roof patina' },
    typ: { display: 'carved Vatteluttu-style temple inscriptions', notes: 'nakshatra motifs on beam ends' },
    lit: { quality: 'monsoon-diffused courtyard light', temperature: 'warm-toned', shadow: 'deep eaves keep interiors cool-shaded' },
    ui: { background: 'laterite red-brown', surface: 'carved-timber cards', components: 'monsoon-gable dividers', motion: 'rain-fall courtyard loop' },
  },
  {
    slug: 'javanese-joglo',
    ctx: 'The joglo — Java\'s noble house form — centers on the saka guru four main columns and interlocking tumpang sari roof tiers, symbolizing the owner\'s rank while making an earthquake-resilient timber assembly. The pendopo pavilion (open-sided, tiered roof) hosts ceremonies; the dalem inner rooms encode Javanese cosmology (north-south sacred axis, mountains-to-sea orientation). Joglo carpentry (wet-rice economy\'s craft apex) remains the template for Javanese weddings, government halls and cultural revival architecture.',
    vd: { shape: 'pyramid-tumpang roof tiers on four carved columns', composition: 'open pendopo forecourt with enclosed dalem behind', line: 'stacked beam-ring geometry at roof core', texture: 'teak column polish, thatch or tile tiers, carved column capitals' },
    typ: { display: 'none', body: 'wayang motifs carved into column panels', notes: 'rank spoken through tier count' },
    lit: { quality: 'pendopo diffused tropical shade', temperature: 'warm-toned', shadow: 'tiered roof casts concentric shade rings' },
    ui: { background: 'teak golden brown', surface: 'tier-roof cards', components: 'column-cap dividers', motion: 'gamelan-syncopated pulses' },
  },
  {
    slug: 'scottish-baronial',
    ctx: 'Scottish Baronial (16th-18th c., revived 19th) mixed medieval tower-house defense with Renaissance turrets: crow-stepped gables, corbelled round turrets at corners (bartizans), conical caps and massive walling — Craigievar, Castle Fraser, Glamis — then revived by Edinburgh\'s New Town fringes and Balmoral for Victorian royal romanticism. The style\'s "fairytale fortress" profile became Scotland\'s exported image (highland hotels, Whisky-box baronial), engineered comfort beneath martial costume.',
    vd: { shape: 'tall L-plan towers with corbelled turrets and crow-stepped skylines', composition: 'clan-entrance towers over courtyard ranges', line: 'corbel course angles stepping to conical caps', texture: 'granite rubble, slate crow-steps, iron yett gatework' },
    typ: { display: 'carved family-crest panels over doors', notes: ' Gaelic motto ribbons under turrets' },
    lit: { quality: 'highland mist-and-sun breaking', temperature: 'cool-toned', shadow: 'turrets cast combed shadow fans' },
    ui: { background: 'granite silver-grey', surface: 'turret-bartizan cards', components: 'crow-step dividers', motion: 'mist-drift reveal loops' },
  },
  {
    slug: 'swahili-coastal-architecture',
    ctx: 'Swahili coastal architecture — Lamu, Zanzibar\'s Stone Town, Kilwa\'s ruins — blends African, Arab, Persian and Indian craft into coral-stone mercantile towns: massive 18th-century houses with inward courtyards, carved Zanzibar doors (pinwheel brass spikes against elephants, fish-motif date-code), baraza benches, mangrove-pole ceilings and rooftop rain terraces. The Indian Ocean trade (Frankincense to porcelain) wrote itself into the walls; UNESCO-listed Stone Town and Lamu Old Town preserve the dhow-port urbanism.',
    vd: { shape: 'coral-rag block houses with deep-windowed facades', composition: 'carved doors as the street\'s public face', line: 'lintel-carved arabesque and lotus bands', texture: 'coral lime render, carved mangarole hardwood, brass stud glint' },
    typ: { display: 'carved door lintel calligraphy and date formulae', notes: 'Quranic verses over house entries' },
    lit: { quality: 'monsoon-season filtered glare', temperature: 'warm-toned', shadow: 'baraza benches hold deep street shade' },
    ui: { background: 'coral-stone white', surface: 'carved-door cards', components: 'door-stud accents', motion: 'dhow-sail breeze drift' },
  },
  {
    slug: 'ancestral-puebloan-great-houses',
    ctx: 'Ancestral Puebloan Great Houses — Chaco Canyon\'s Pueblo Bonito (800-1150 CE, UNESCO) — are the American Southwest\'s monumental architecture: multi-story planned complexes of 600+ rooms, D-shaped cores, ceremonial kivas (round sunken chambers), aligned to solar-lunar cycles, connected by 400+ km of engineered Chacoan roads. Masonry styles (Type I-II-III) date construction; descendent Pueblo nations (Hopi, Zuni, Taos) keep the cultural lineage, and archaeoastronomy (Supernova pictograph, sun dagger) made Chaco World Heritage.',
    vd: { shape: 'D-shaped core-and-veneer masonry terraces', composition: 'plaza-centered complexes with kiva circles', line: 'banded stone courses, T-shaped doorways', texture: 'sandstone block, mud mortar, timber viga beam ends, adobe plaster' },
    typ: { display: 'none', body: 'petroglyph and pictograph panels', notes: 'astronomy read in stone alignments' },
    lit: { quality: 'desert-plateau dawn alignment', temperature: 'warm-toned', shadow: 'kiva shadow reaches by solar calendar' },
    ui: { background: 'canyon sandstone', surface: 'masonry-band cards', components: 'kiva-circle icons', motion: 'solstice-shadow tracking' },
  },
  {
    slug: 'fijian-bure',
    ctx: 'The Fijian bure — traditional thatched dwellings of the village compound — rise from coral-lime or earth floors with hardwood posts, woven (voi) bamboo walls, and a tall thatched (soga) hipped roof ridge-lined like a hull: chiefly bure kalou bore taller roof spikes and sacred thresholds. Modern resort "bures" quote the form in luxury villas; chiefly villages (Navesau, Navala) preserve authentic construction, and bure-building ceremonies remain fealty events in Fijian chiefly culture.',
    vd: { shape: 'ridge-hull thatch roofs over woven wall drums', composition: 'chiefly bure centered in village green ring', line: 'thatch course lines converging at ridge', texture: 'woven bamboo skin, soga grass thatch, coral-lime floor polish' },
    typ: { display: 'none', body: 'masi (barkcloth) pattern borders inside', notes: 'kava bowls mark the social center' },
    lit: { quality: 'lagoon-bright tropical noon', temperature: 'warm-toned', shadow: 'deep eaves shade the veranda (vale) edge' },
    ui: { background: 'thatch honey-gold', surface: 'woven-bamboo cards', components: 'ridge-line dividers', motion: 'palm-sway breeze loops' },
  },
  {
    slug: 'goan-portuguese-architecture',
    ctx: 'Goan Portuguese architecture (1510-1961) — a Luso-Indian hybrid unmatched in Asia: lime-plastered mansions of Fontainhas (Panjim), azulejo-tiled facades, oyster-shell window shells (jaali), Balcão sitting verandas, and baroque-gilded churches (Bom Jesus, UNESCO) against Indo-Portuguese furniture and rose windows. Old Goa\'s basilicas and convents were called "Rome of the East"; the susegad domestic style — chandeliers over red-oxide floors — survives in heritage homes and hoteliers\' revival.',
    vd: { shape: 'deep-hipped roofs, balcão verandas, tall shuttered windows', composition: 'azulejo-panel facades around courtyard chapels', line: 'shell-lime arch curves, oyster-window grids', texture: 'lime-wash ochre, blue tile glaze, teak shutters, red-oxide floors' },
    typ: { display: 'azulejo-framed house name tiles', notes: 'hand-painted saint niches at gates' },
    lit: { quality: 'monsoon-softened tropical light', temperature: 'warm-toned', shadow: 'balcão shades in afternoon heat' },
    ui: { background: 'ochre-and-blue tile', surface: 'shell-window cards', components: 'azulejo-frame dividers', motion: 'monsoon-shutter sway' },
  },
  {
    slug: 'brezhnevka',
    ctx: 'The brezhnevka — Leonid Brezhnev era housing (1964-1982) — succeeded the khrushchyovka with nine-to-sixteen story panels, elevators, garbage chutes, balconies, and modestly bigger rooms: the Soviet "comfort generation" block. Standard series (II-68, 121, P-44) built entire microrayons across the USSR; mocked as "ship of the desert" sameness, they are now nostalgic retro subjects (Instagram brezhnevka beauty pages) and still house vast populations — the era\'s ambiguous promise of socialist comfort made concrete.',
    vd: { shape: 'taller panel slabs with balcony grids and elevator cores', composition: 'microrayon superblocks with school-and-shop plinths', line: 'vertical balcony rhythm over horizontal seams', texture: 'painted panel wash, tile-ended lobbies, balcony cage iron' },
    typ: { display: 'block-number and street stencils', notes: 'local-service neon at ground plinths' },
    lit: { quality: 'courtyard sodium evening', temperature: 'cool-toned', shadow: 'balcony boxes stripe facades with shade' },
    ui: { background: 'panel beige-grey', surface: 'balcony-grid cards', components: 'elevator-core dividers', motion: 'intercom-buzz flickers' },
  },
  {
    slug: 'gopuram-temple-gate',
    ctx: 'The gopuram — Dravidian temple\'s monumental entrance tower — grew from Chola modesty to Nayak-era giants: Madurai\'s Meenakshi southern tower (51m, 1,500+ stucco figures), Srirangam\'s 13-tier Rajagopuram (72m). Built as stepped pyramids of divine population — deities, guardians, mythic processions — the gopuram anchors temple-city axial planning, is re-carved and repainted in cycles, and defines the skyline grammar of Tamil Nadu, Kerala and the diaspora (Singapore, London) alike.',
    vd: { shape: 'stepped trapezoidal pyramid towers rising in tiers', composition: 'sculpture-tiered bands descending to carved doorway', line: 'horizontal cornice tiers punctuated by stucco figures', texture: 'granite base, brick-and-stucco tier statues, bright mineral repainting' },
    typ: { display: 'donor and consecration inscriptions on plinths', notes: 'Tamil calligraphy on flagstaff bases' },
    lit: { quality: 'Dravidian dawn processional light', temperature: 'warm-toned', shadow: 'tiers cut sharp sunrise shadow ladders' },
    ui: { background: 'temple gopuram colors', surface: 'sculpture-tier cards', components: 'tier-band dividers', motion: 'procession-figure parallax' },
  },
  {
    slug: 'shanxi-courtyard-compounds',
    ctx: 'Shanxi merchant compounds — the Qiao Family Courtyard, Wang Family Compound, Rishengchang\'s Pingyao bank headquarters — housed the Qing "Jin merchants" whose remittance banks (piaohao) financed imperial China: multi-generation fortress-courtyards of grey brick, carved brick-and-wood ornament, defensive watchtowers, and axial family hierarchy ("three cardinal guides and five constant virtues" in architecture). Pingyao\'s walled city is UNESCO-listed; the compounds anchor Chinese merchant-heritage tourism.',
    vd: { shape: 'grey-brick axial courtyards in fortress clusters', composition: 'elder-to-younger hall sequences along central spine', line: 'brick-carved lattice screens, watchtower crowns', texture: 'grey brick, carved wood grilles, stone drum bases, slate tile shadow' },
    typ: { display: 'clan-hall hanging tablet calligraphy', notes: 'merchant mottos carved in screen panels' },
    lit: { quality: 'north-China courtyard clear noon', temperature: 'neutral-toned', shadow: 'eave shadows sharpen the axis' },
    ui: { background: 'grey brick', surface: 'courtyard-axial cards', components: 'lattice-screen dividers', motion: 'gate-sequence procession pan' },
  },
  {
    slug: 'kalyan-minaret-style',
    ctx: 'The Kalyan Minaret (Bukhara, 1127, "Death Tower" for its judicial throws) founded Central Asia\'s minaret typology: a 46m tapering brick shaft on octagonal base, ornamental bands of glazed brick (narrow-gauge formulas), and top muqarnas cornice that survived Genghis Khan\'s demolition of the rest of Bukhara. Prototypes: Vabkent and the Timurid towers; its silhouette is Uzbekistan\'s most reproduced architectural image, and UNESCO-listed Bukhara organizes tourism around it.',
    vd: { shape: 'slender tapering brick shaft over octagonal base', composition: 'ornament bands reading as tower scripts', line: 'glazed-brick ring courses, muqarnas cornice crown', texture: 'baked brick warm-rose, turquoise glazed bands, rope-course borders' },
    typ: { display: 'Kufic foundation inscription band', notes: 'master-builder name in ornament band' },
    lit: { quality: 'desert-city golden hour', temperature: 'warm-toned', shadow: 'taper casts moving ribbon shade' },
    ui: { background: 'brick rose', surface: 'ornament-band cards', components: 'muqarnas-crown dividers', motion: 'spiral-band ascent loop' },
  },
  {
    slug: 'kerala-timber-roof-temples',
    ctx: 'Kerala\'s timber-roof temples — Vadakkumnathan, Tali, Koodalmanikyam — are the Dravidian South\'s exception: not stone gopurams but sloped copper-and-timber roofs (two-tiered sreekovil sanctums, namaskara mandapa porches) against monsoon, with laterite plinths and murals inside. Craft rules (thachu shastra) govern roof pitches and joinery; the temples\' circular (vatta) and square (chathura) sanctum plans, ringed by outer walls and kshetrapala shrines, make Kerala\'s sacred skyline uniquely tiered and steep.',
    vd: { shape: 'steep copper roofs stacked over circular and square sanctums', composition: 'temple compound rings within stone walls', line: 'roof-hip curves and eave brackets', texture: 'copper patina, laterite base, carved wood door frames, mural pigments' },
    typ: { display: 'carved Sanskrit and Malayalam vatteluttu panels', notes: 'oil-lamp pillars as votive inscriptions' },
    lit: { quality: 'oil-lamp warmth inside monsoon shade', temperature: 'warm-toned', shadow: 'tiered roofs shade deep compound lanes' },
    ui: { background: 'laterite red', surface: 'copper-roof cards', components: 'tier-gable dividers', motion: 'monsoon-drip eave loops' },
  },
  {
    slug: 'turf-roofed-farmhouse',
    ctx: 'Turf-roofed farmhouses — Iceland\'s torfbær (UNESCO-listed Glaumbær, Laufás), Norwegian grass roofs, Faroese ì Føroyum settlements — built with what the North Atlantic offered: stone walls, birch frames, and turf layers providing insulation (R-value) against brutal winters. The soft green-roof silhouette — windows peeking under grass banks — became national-icon material (Icelandic turf houses on stamps, Norway\'s reconstructed villages) and a modern green-roof movement\'s ancestral precedent.',
    vd: { shape: 'low stone walls swallowed by grassed turf banks and roof', composition: 'gabled clusters around turf-walled farm courts', line: 'turf layers stepping like contour lines', texture: 'living grass roof, stone footing, driftwood door frames' },
    typ: { display: 'none', body: 'runic date marks on lintels', notes: 'weather told by roof flower species' },
    lit: { quality: 'north-Atlantic low silver light', temperature: 'cool-toned', shadow: 'turf banks soften all shadow edges' },
    ui: { background: 'turf green', surface: 'grass-roof cards', components: 'stone-base dividers', motion: 'wind-grass ripple loops' },
  },
  {
    slug: 'lombard-romanesque',
    ctx: 'Lombard Romanesque (11th-12th c.) — the Po Valley\'s brick-and-stone style — spread the "Lombard band" (hanging dwarf-gallery arcading), corbel tables and paired pilasters across Italy, Spain\'s Camino de Santiago and the Rhineland: Modena\'s cathedral, Sant\'Ambrogio Milan, Pavia\'s San Michele. Wiligelmo\'s Modena sculpture revived monumental figural carving in Italy; the style\'s brick craft and gallery skyline defined northern-Italian civic-religious identity for two centuries.',
    vd: { shape: 'gabled brick facades banded by hanging arcading', composition: 'porch-and-sculpture portals with rose windows rising', line: 'corbel-table and pilaster rhythm', texture: 'terracotta brick, sandstone sculpture, alternating stone courses' },
    typ: { display: 'Romanesque capitals with inscription rolls', notes: 'master-mason signatures on lintels' },
    lit: { quality: 'Po-valley haze-softened sun', temperature: 'warm-toned', shadow: 'arcading throws lace shadow bands' },
    ui: { background: 'brick terracotta', surface: 'gallery-arcade cards', components: 'corbel-row dividers', motion: 'pilgrim-road procession pan' },
  },
  {
    slug: 'byzantine-revival',
    ctx: 'Byzantine Revival — 19th-20th century architecture re-adopting the dome-and-gold program — built national-identity landmarks: London\'s Westminster Cathedral (1895-1903, red-brick Byzantine stripes), Neuschwanstein-era Germany\'s evangelical "Byzantine" churches, Greece\'s Athens Cathedral, and America\'s Greek Orthodox cathedrals. Alexandrian-Palace and Serbian Morava school revivals tied the style to Orthodox nationhood; the Masonic and ecclesiastical domes still anchor city skylines from Marseille to Melbourne.',
    vd: { shape: 'central Greek-cross domes on drum clerestories', composition: 'mosaic-filled apse and vault programs', line: 'arcuated pendentive curves, blind arcade bands', texture: 'polychrome brick courses, gold mosaic fields, polished marble veneers' },
    typ: { display: 'Greek monogram and dedication mosaics', notes: 'Latin and Greek bilingual inscriptions' },
    lit: { quality: 'drum-clerestory shafts onto gold', temperature: 'warm-toned', shadow: 'pendentives hold glowing dome shade' },
    ui: { background: 'mosaic gold field', surface: 'brick-dome cards', components: 'pendentive icons', motion: 'dome-light cycle shifts' },
  },
  {
    slug: 'napier-nz-deco',
    ctx: 'Napier, New Zealand — flattened by the 1931 Hawke\'s Bay earthquake — rebuilt itself in three years as the world\'s most complete Art Deco city: Louis Hay\'s residential Deco, local interpretations of Miami Beach and Zigzag Moderne, Maori motifs in friezes, all limestone-white against the Pacific. The 1930s rebuild (2,000 buildings, £21m) made "Napier Deco" a tourism brand (annual Art Deco Weekend), with the ASB Bank (1933) and Daily Telegraph as photographed icons.',
    vd: { shape: 'stepped parapets, fountain-splash corners, zigzag bands', composition: 'uniform street-wall height with Deco competition in detail', line: 'speed-line chevrons and sunburst gables', texture: 'smooth stucco, terrazzo lobbies, leadlight glass, cast iron fretwork' },
    typ: { display: 'streamlined Deco sign lettering', notes: 'Maori-motif name panels over shops' },
    lit: { quality: 'Hawke Bay bright afternoon', temperature: 'warm-toned', shadow: 'parapet steps cast crisp Deco shade' },
    ui: { background: 'stucco white', surface: 'chevron-band cards', components: 'sunburst-gable frames', motion: 'jazz-age shutter flicks' },
  },
  {
    slug: 'tectonics',
    ctx: 'Tectonics in architecture — from Greek tekton (carpenter) through Semper and Frampton\'s theorizing — privileges the visible, honest join: the structural poetry of load meeting support, material meeting material, as against scenographic surface. Swiss "tectonic school" (Pascal Flammer, Valerio Olgiati), Japanese joinery (Kuma\'s kizukuri), and the "construction as expression" teaching tradition keep it central; critics read tectonic legibility as architecture\'s ethical baseline.',
    vd: { shape: 'structural members displayed as spatial order', composition: 'load paths readable at a glance', line: 'joint lines as ornament', texture: 'timber dovetails, steel knife-plate connectors, concrete board-marking' },
    typ: { display: 'none', body: 'fabricator stamps on members', notes: 'craft documented in the joint itself' },
    lit: { quality: 'raking light across structural depth', temperature: 'neutral-toned', shadow: 'members cast honest structural shade' },
    ui: { background: 'material-neutral grey', surface: 'join-detail cards', components: 'joint-diagram toggles', motion: 'load-path stress animations' },
  },
]
