/**
 * Completeness patch r4e — Mexico, Guatemala, Central America & Baltic traditions (18).
 * Hand-authored (Task 4-e); names/dates/places Wikipedia-API-verified (en+lt+lv); no LLM involvement.
 * Fills ctx + visualDNA + typography + lighting + uiTranslation.
 */
export const PATCHES: any[] = [
  {
    slug: 'wixarika-yarn-painting',
    ctx: 'Wixarika (Huichol) yarn painting grew from the nierika, a small ceremonial tablet of pressed yarn and beeswax that stood in for visions. In the twentieth century artisans began pressing commercial wool yarn into wax-and-resin coated boards, and the votive tablet became a picture plane: peyote visions, deer, corn, fire and the mara\'akame shaman\'s spirit journeys rendered in radiant color and symbol.',
    vd: { shape: 'picture-plane rectangles packed with circular medallions', line: 'dense parallel yarn coils spiraling into god-eyes and suns', composition: 'central spirit figure ringed by concentric bands of symbols', texture: 'tight fuzzy ridges of pressed yarn in saturated color' },
    typ: { display: 'rounded geometric caps echoing yarn medallions', body: 'clean humanist sans set wide over wax-cream panels' },
    lit: { quality: 'high plateau sun flattening saturated yarn color', temperature: 'vivid warm-toned', shadow: 'soft ridge shadows between coiled yarn rows' },
    ui: { background: 'wax-cream board tan', surface: 'yarn-ridged panels in saturated rainbow fields', components: 'god-eye medallion chips and spiral buttons', motion: 'coils of color spiraling outward on load' },
  },
  {
    slug: 'otomi-tenango-embroidery',
    ctx: 'Tenango embroidery comes from Tenango de Doria, Hidalgo — Otomí country — where a 1960s economic crisis pushed traditional embroidery into a market craft now worked by more than a thousand artisans across Tenango de Doria and San Bartolo Tutotepec. Flora, fauna and everyday scenes are filled with dense running and satin stitches in bright threads over off-white cotton, making it one of Mexico\'s most recognizable textiles.',
    vd: { shape: 'whole-cloth panels alive with bird, rabbit and flower silhouettes', line: 'fine satin and running stitches filling each form edge to edge', composition: 'motifs scattered evenly with no horizon or ground line', texture: 'dense multicolor thread pile on plain off-white cotton' },
    typ: { display: 'stitched-outline caps like embroidered figure borders', body: 'light airy serif over unbleached cotton tones' },
    lit: { quality: 'even daylight flat-laying the embroidery field', temperature: 'bright warm-toned', shadow: 'tiny thread shadows giving each motif relief' },
    ui: { background: 'unbleached cotton cream', surface: 'embroidered panels with multicolor fauna rows', components: 'stitch-outline chips and running-stitch dividers', motion: 'motifs stitching themselves in row by row' },
  },
  {
    slug: 'oaxacan-alebrijes',
    ctx: 'Alebrijes began in 1936, when Mexico City cartonero Pedro Linares López, feverish and dreaming, shaped impossible beasts — part lizard, part butterfly, part dog — and named them from his dream. His papier-mâché creatures became a Mexican folk icon, and Oaxaca\'s woodcarvers reworked the idea in copal wood: densely carved, bright-painted animal chimeras with spiral horns and coiled tongues that now define the state\'s craft exports.',
    vd: { shape: 'chimeric beasts stacked of wings, horns and coiled tongues', line: 'sharply carved contours wrapped in stripes and scrolls', composition: 'one creature per plinth, pattern running over every limb', texture: 'glossy acrylic skin over pale copal wood grain' },
    typ: { display: 'playful hand-painted caps with creature-curl terminals', body: 'rounded friendly sans on zocalo-warm grounds' },
    lit: { quality: 'market-tent daylight bouncing off glossy paint', temperature: 'fiery warm-toned', shadow: 'crisp short shadows under carved hooves and plinths' },
    ui: { background: 'hot market orange', surface: 'painted-copal cards with stripe-and-scroll skins', components: 'spiral-horn toggles and totem creature icons', motion: 'beasts blooming wing and horn on hover' },
  },
  {
    slug: 'barro-negro',
    ctx: 'Barro negro is the burnished black pottery of San Bartolo Coyotepec, Oaxaca, with roots reaching back to the Monte Albán period. For centuries the clay dried to a matte gray; in the 1950s Doña Rosa found that polishing the semi-dried piece before firing turns it jet black with a metallic sheen. Her family and village workshops still shape cantaros, comales and flutes by hand, burnishing each piece into the shine that made the ware famous.',
    vd: { shape: 'rounded ollas, cantaros and flutes in true black', line: 'carved florid bands circling neck and shoulder', composition: 'single centered vessel, gloss fading toward the base', texture: 'mirror burnish over a fine gray clay body' },
    typ: { display: 'high-gloss carved-ceramic caps with fluted edges', body: 'elegant charcoal serif on smoke-dark grounds' },
    lit: { quality: 'single strong lamp giving the sheen a streak', temperature: 'smoky warm-toned', shadow: 'black-on-black shadow, depth read by reflection' },
    ui: { background: 'jet black clay', surface: 'burnished barro negro panels with carved bands', components: 'vessel-silhouette buttons and sheen-swept dividers', motion: 'a light streak gliding across the burnished black' },
  },
  {
    slug: 'san-antonio-aguas-calientes-huipil',
    ctx: 'San Antonio Aguas Calientes, a Sacatepéquez town in the Guatemalan highlands, is celebrated for one of Guatemala\'s finest huipils. Maya women weave on backstrap looms, brocading dense figurative bands — birds, flowers, the town\'s signature two-sided patterns — so finely the design reads identically front and back. Looms stand in doorways and the market square, where weavers demonstrate the technique for visitors and traders alike.',
    vd: { shape: 'tunic rectangles with deep brocaded yoke bands', line: 'double-faced weft floats tracing birds and blossoms', composition: 'heavy shoulder-to-chest ornament around a plain field', texture: 'silk-bright brocade over fine handwoven cotton ground' },
    typ: { display: 'brocade-set caps framed like woven yoke bands', body: 'warm humanist serif with highland-earth tones' },
    lit: { quality: 'patio light lifting both brocade faces', temperature: 'soft warm-toned', shadow: 'weave shadows pooling in the float-work bands' },
    ui: { background: 'eggshell cotton white', surface: 'two-sided brocade cards with bird-and-bloom bands', components: 'yoke-band headers and shuttle-shaped chips', motion: 'weft threads shuttling across the band' },
  },
  {
    slug: 'chichicastenango-textile',
    ctx: 'Chichicastenango\'s textiles come from a 1,965-meter K\'iche\' Maya town in El Quiché, the highland market center where the Popol Vuh manuscript was transcribed in the early 1700s. Its Thursday and Sunday markets fill with weavings: huipils brocaded in red, black and white, headwraps and carry-cloths worked with dense animal and flower figures. Weaving here is daily dress and ceremony together, not souvenir craft alone.',
    vd: { shape: 'long woven panels and tunic sleeves banded with figures', line: 'fine brocade outlines repeating animal and flower rows', composition: 'stripe-ruled layout in red-black-white register bands', texture: 'matte cotton wefts with raised brocade knots' },
    typ: { display: 'geometric banded caps in red-black register stripes', body: 'sturdy low-contrast serif on woven cream' },
    lit: { quality: 'highland sun slicing cold air onto woven color', temperature: 'cool air, warm cloth', shadow: 'market awning stripes darkening the fabric rows' },
    ui: { background: 'highland slate with red accents', surface: 'banded textile panels with brocade figure rows', components: 'stripe-ruled dividers and animal-figure chips', motion: 'bands scrolling like market cloth on display' },
  },
  {
    slug: 'guatemalan-corte-skirt',
    ctx: 'The corte is the wrap skirt of Guatemala\'s Maya women: ankle-length yardage wrapped around the body and belted with a faja, worn daily from highland villages to city markets. Cortes are woven as continuous panels on treadle looms or cut from glossy commercial cloth, then seamed and hemmed at home. A good corte is costly, distinctive to its community, and often passed down from mother to daughter.',
    vd: { shape: 'long wrapped cylinder of dense woven yardage', line: 'vertical ikat-warp patterns and pinstripe repeats', composition: 'one continuous panel folded, pleated and belted', texture: 'heavy polished-look wefts with crisp fold lines' },
    typ: { display: 'ikat-blurred display caps in warp-stripe colors', body: 'clean bookish serif suited to long cloth names' },
    lit: { quality: 'even plaza light sheening the wrapped folds', temperature: 'warm-toned', shadow: 'deep pleat shadows stacked at the hem' },
    ui: { background: 'indigo corte blue', surface: 'wrap-skirt panels with ikat stripe fields', components: 'faja-belt rules and pleat-folded cards', motion: 'panels wrapping and pleating into place' },
  },
  {
    slug: 'zinacantan-huipil',
    ctx: 'Zinacantán, a Tzotzil Maya municipality in the Chiapas highlands, dresses its women in huipils still woven at home on backstrap looms. The classic zinacanteca huipil is white cotton scattered with embroidered and brocaded flowers — wildflowers of the village lands — trimmed in ribbon at neck and seams. Local identity is read straight from the cloth: village, status and occasion all show in the flowers\' density and placement.',
    vd: { shape: 'loose white tunic panels dotted with flower sprigs', line: 'petal-and-vine embroidery radiating from neck and hem', composition: 'open white field, ornament clustered at collar and cuffs', texture: 'smooth cotton ground with satin-stitch bloom relief' },
    typ: { display: 'flower-sprigged caps with ribbon-trim strokes', body: 'soft rounded serif on snowy cotton white' },
    lit: { quality: 'bright mountain light on white cotton ground', temperature: 'crisp cool with warm blooms', shadow: 'stitch shadows lifting each flower off the cloth' },
    ui: { background: 'cotton white', surface: 'flower-scattered panels with ribbon edging', components: 'bloom badges and ribbon-stroke dividers', motion: 'flower sprigs blooming along the neck seam' },
  },
  {
    slug: 'san-juan-chamula-textile',
    ctx: 'San Juan Chamula, a Tzotzil municipality just north of San Cristóbal de las Casas, keeps one of Chiapas\'s most self-contained textile cultures. Men wear white sheep-wool tunics and sashes; women\'s huipils and skirts carry dense black-and-white or brocaded bands. Wool from household flocks is carded, spun and woven at home, and the municipality remains overwhelmingly Tzotzil-speaking — dress is the visible marker of that autonomy.',
    vd: { shape: 'wool tunic and huipil panels in heavy plain weave', line: 'black-and-white banding and striped sash repeats', composition: 'broad plain fields framed by dense woven borders', texture: 'homespun wool nap over tight handwoven cotton' },
    typ: { display: 'wool-plain display caps with banded rules', body: 'quiet neutral serif in graphite and bone tones' },
    lit: { quality: 'cool highland light absorbed by dark wool', temperature: 'cool-toned with warm skin notes', shadow: 'wool nap shadowing every band edge' },
    ui: { background: 'charcoal wool grey', surface: 'homespun panels with black-and-white banding', components: 'sash-stripe chips and woven-border frames', motion: 'bands knitting across loading states' },
  },
  {
    slug: 'guna-mola-reverse-applique',
    ctx: 'The mola is the blouse panel of Guna (Dule) women of Panama\'s San Blas Islands and Guna Yala; in Dulegaya, mola simply means shirt. Descended from geometric body painting and later woven cotton, molas are sewn from layered trade cloth — commonly two to seven layers — cut away in reverse appliqué to reveal each color, then overstitched in fine running seams. Panels pair on the dulemor blouse with sea, myth and political subjects.',
    vd: { shape: 'rectangular blouse panels of nested layered color', line: 'fine sawtooth reverse-appliqué edges stepping inward', composition: 'central motif echoed by stacked channel outlines', texture: 'flat cotton layers separated by tiny seam ridges' },
    typ: { display: 'zigzag appliqué caps in stacked outline colors', body: 'crisp small sans on flat sea-bright panels' },
    lit: { quality: 'island daylight flattening layered color bands', temperature: 'bright warm-toned', shadow: 'micro shadows along each appliqué channel' },
    ui: { background: 'caribbean reef red', surface: 'layered panel cards with stepped outline motifs', components: 'sawtooth-edged chips and channel-lined dividers', motion: 'top layers cutting away to reveal the next color' },
  },
  {
    slug: 'lenca-pottery-tradition',
    ctx: 'Lenca pottery is the household ceramic tradition of the Lenca people of western Honduras and El Salvador, kept alive by women potters in family workshops. Comales, water jars, candlesticks and animal figures are coil-built, finished with slip in black, honey and rust red, burnished smooth and fired over bark and wood. The pre-Columbian lineage is ancient, but the ware on market stalls today is living domestic craft, not reproduction.',
    vd: { shape: 'coil-built ollas and comales with wide stable bases', line: 'simple incised spirals and double-line rims', composition: 'vessel-first design, ornament following the profile', texture: 'stone-burnished slip shifting matte to soft gloss' },
    typ: { display: 'earth-burnished caps with incised line accents', body: 'sturdy unadorned serif in terracotta tones' },
    lit: { quality: 'kiln-warm light on burnished slip', temperature: 'earthy warm-toned', shadow: 'soft amber shadows inside vessel mouths' },
    ui: { background: 'burnished terracotta', surface: 'clay-toned cards with incised spiral corners', components: 'olla-shaped buttons and comal rules', motion: 'coil lines rising to form each vessel' },
  },
  {
    slug: 'lielvarde-belt',
    ctx: 'The Lielvārde belt is Latvia\'s mythic woven sash: up to three meters of red-and-white linen and wool, its length set with twenty-nine geometric signs, historically woven along the old Daugava waterway around Lielvārde. The symbols are read as a script of Latvian myth, and the belt entered national memory through the epic hero Lāčplēsis. It now belongs to Latvia\'s Culture Canon and every full national costume.',
    vd: { shape: 'long narrow sash of repeated pickup-woven signs', line: 'crisp red-on-white geometric strokes, pixel-true', composition: 'sign sequence read left to right along the band', texture: 'flat wool-and-linen weave with raised pickup rows' },
    typ: { display: 'runelike geometric caps drawn from belt signs', body: 'clean engineering sans in red on bone white' },
    lit: { quality: 'crisp northern daylight paling the linen', temperature: 'cool-toned with red accents', shadow: 'weave shadow tracing each raised sign row' },
    ui: { background: 'bone linen white', surface: 'belt-band cards with red sign sequences', components: 'sign-glyph chips and woven-band dividers', motion: 'signs weaving in sequence along the band' },
  },
  {
    slug: 'baltic-mitten-patterns',
    ctx: 'Knitted mittens are a signature craft of Latvia, Lithuania and Estonia: every district kept its own repertoire of geometric stranded-colorwork bands — stars, rams\' horns, S-hooks — knitted in counted patterns on fine wool. Mittens marked life\'s passages, given as betrothal and wedding gifts and worn with national costume; a bride\'s trousseau could hold dozens of pairs. Charted regional pattern archives still drive Baltic mitten design today.',
    vd: { shape: 'mitten-shaped panels banded in dense colorwork', line: 'counted geometric stars, hooks and horn figures', composition: 'cuff, hand and finger zones each with its band', texture: 'fine stranded wool with slight relief trapping air' },
    typ: { display: 'chart-knit caps in two-color starwork', body: 'compact wool-warm sans with even spacing' },
    lit: { quality: 'window-side winter light on fine knitting', temperature: 'cool-toned with warm wool notes', shadow: 'stitch shadow giving the colorwork depth' },
    ui: { background: 'deep winter navy', surface: 'colorwork-band cards with charted star motifs', components: 'mitten toggles and chart-grid dividers', motion: 'patterns counting across the cuff on load' },
  },
  {
    slug: 'lithuanian-sodai-straw-gardens',
    ctx: 'Sodai — Lithuanian straw gardens — are hanging mobiles built from rye and wheat straw: interlocking frames of strung quills opening into rings, diamonds and spires, all balanced on a single thread. Made for Christmas (Kūčios), weddings and new homes, they hung over cradles and dinner tables as charms of fertility and cosmic order, a folk image of the world tree. Vilnius-region makers bind the same straw craft into Palm Sunday verba bouquets.',
    vd: { shape: 'floating cage-like spheres and spires of straw', line: 'hair-thin straw quills running ring into ring', composition: 'tiered mobile balanced around a center axis', texture: 'dry golden straw catching light at every joint' },
    typ: { display: 'delicate filigree caps in straw gold', body: 'light airy serif with generous winter-white space' },
    lit: { quality: 'candle-warm glow filtering through straw rings', temperature: 'golden warm-toned', shadow: 'lace-fine mobile shadows turning on the wall' },
    ui: { background: 'straw gold on winter white', surface: 'openwork geometric cards like straw lattice', components: 'ring-and-diamond chips suspended in space', motion: 'the whole garden slowly turning on its thread' },
  },
  {
    slug: 'marguciai-egg-decorating',
    ctx: 'Margučiai are Lithuania\'s decorated Easter eggs, an art the region mastered in wax resist and etching. In Lithuania eggs are dropped, drawn or written on in hot wax, dyed in successively darker baths and scratched or carved to reach the shell\'s pale ground — multicolored margučiai, distinct from plain onion-dyed riciai. Symbols of spring and resurrection older than the calendar they now mark, they still fill Easter baskets and folk-art displays.',
    vd: { shape: 'eggshell ovals divided into dyed and waxed zones', line: 'wax pin-dots and scratch-carved lines through color', composition: 'banded egg layout with sun stars at crown and base', texture: 'glossy dyed shell with fine relief wax lines' },
    typ: { display: 'wax-resist caps with scratch-line stroke ends', body: 'gentle rounded serif on dyed pastel grounds' },
    lit: { quality: 'spring window light brightening the shell dyes', temperature: 'fresh cool-warm mix', shadow: 'tiny wax-line shadows across the curved shell' },
    ui: { background: 'dyed-shell amber', surface: 'egg-oval cards with wax-band motifs', components: 'pin-dot toggles and carved-line dividers', motion: 'wax dots patterning the shell as it loads' },
  },
  {
    slug: 'baltic-national-costume-ornament-bands',
    ctx: 'Baltic national costume lives and dies by its woven bands: the Latvian josta and Lithuanian juosta sashes, plus collars, cuffs and hem stripes, all patterned with regional sign systems. Woven narrow on inkle and pickup looms or brocaded wide, the sashes cinch skirts and cap the shoulders of festival dress. Their geometric repertoire — stars, crosses, barley-ear and fire-cross signs — ties costume directly to the region\'s older sign language.',
    vd: { shape: 'narrow woven bands laid into costume edges', line: 'pickup-woven star, cross and barley-ear figures', composition: 'bands framing skirt, shoulder and hem as borders', texture: 'firm wool weave with raised pattern floats' },
    typ: { display: 'band-pattern caps in festival reds and greens', body: 'clear regional serif with folklore-archive warmth' },
    lit: { quality: 'even museum light across woven floats', temperature: 'neutral-cool with warm wool', shadow: 'float shadows reading as fine relief' },
    ui: { background: 'archive linen grey', surface: 'band-swatch cards with woven sign rows', components: 'sash-belt rules and sign-glyph chips', motion: 'band patterns advancing like a loom in use' },
  },
  {
    slug: 'jurmala-wooden-architecture',
    ctx: 'Jūrmala\'s wooden architecture is the residue of its birth as a seaside resort: from the late 1800s, Riga families built summer villas along some thirty kilometers of white-sand Gulf of Riga beach, many in flamboyant Art Nouveau wood. Carved gables, lace-sawn verandas, towers and colored boarding survive along streets like Jomas iela, alongside Soviet-era sanatoriums from the resort\'s favored status among top Soviet officials.',
    vd: { shape: 'tall gabled villas with towers and open verandas', line: 'lace-sawn board edges and carved ornament runs', composition: 'villas rowed along pine-lined beach streets', texture: 'weathered painted boarding over grained timber' },
    typ: { display: 'art-nouveau wooden-sign caps with carved curves', body: 'retro summer sans in faded resort pastels' },
    lit: { quality: 'sea glare and pine shade across facade boards', temperature: 'sunny warm-toned', shadow: 'veranda-lace shadows striping the walls' },
    ui: { background: 'faded seafoam villa pastel', surface: 'painted-board panels with sawn-lace trims', components: 'veranda-arc headers and plank-stripe rules', motion: 'sawn-lace trims easing into view like shutters' },
  },
  {
    slug: 'hill-of-crosses',
    ctx: 'The Hill of Crosses, some 12 kilometers north of Šiauliai, Lithuania, is a pilgrimage site where crosses, crucifixes, Virgin statues and rosaries have crowded a former hill fort since the nineteenth century — tradition ties the first crosses to the 1831 Uprising. Estimates counted some 55,000 crosses by 1990 and around 100,000 by 2006. Through decades of Soviet bans it kept growing, and now stands as an emblem of Lithuanian Catholic endurance.',
    vd: { shape: 'a hill mass of thousands of layered crosses', line: 'slender cross arms and folk-carved sunbeam halos', composition: 'crosses packed every direction, sky at the crown', texture: 'weathered wood, silvered metal and paper rosaries' },
    typ: { display: 'carved crossbeam caps with sun-ray terminals', body: 'reverent humanist serif on pale sky grounds' },
    lit: { quality: 'low northern sun raking across the cross forest', temperature: 'cold-toned with golden breaks', shadow: 'tangled cross shadows crossing everywhere' },
    ui: { background: 'pale sky over hill grey', surface: 'cross-etched cards with rosary-bead rules', components: 'cross-glyph chips and pilgrimage-path breadcrumbs', motion: 'crosses accumulating into the hillside on scroll' },
  },
]
