/**
 * Completeness patch r3i — Nordic rosemaling, Sámi duodji & Eastern European (20).
 * Hand-authored (Task 3-i); names/eras Wikipedia-API-verified; no LLM involvement.
 * Fills ctx + visualDNA + typography + lighting + uiTranslation.
 */
export const PATCHES: any[] = [
  {
    slug: 'estancia-silver-tack',
    ctx: 'Estancia silver tack is the platería of the Argentine and Uruguayan pampas: the gaucho\'s horse gear — headstall mounts, stirrups, reins, buttons and the hilt of the facón, the pampas\' principal knife — dressed in chased and engraved silver. On estancias where livestock was wealth, rural silversmiths turned working tack into worn status; parade gear still rides in full silver, and old platería ranks among the emblematic arts of the plains.',
    vd: { shape: 'saddle and headstall gear sheathed in cast silver mounts', line: 'chased scroll engraving running along rein chains', composition: 'silver concentrated at buckles, conchos and hilt', texture: 'polished silver glare over tooled dark leather' },
    typ: { display: 'engraved-plate serif caps with tooled silver filigree', body: 'warm colonial-era roman serif with wide tracking' },
    lit: { quality: 'hard pampas sun glinting off engraved silver', temperature: 'warm-toned', shadow: 'deep leather shadow pooled under silver mounts' },
    ui: { background: 'pampas leather brown', surface: 'tooled-leather panels with silver mount frames', components: 'chased-silver buttons and saddle-stitch dividers', motion: 'silver glint sweeping along rein chains' },
  },
  {
    slug: 'tango-era-poster-and-sheet-cover-art',
    ctx: 'After tango\'s 1880s birth along the Río de la Plata, Buenos Aires and Montevideo lived by printed paper: lithographed sheet-music covers selling each new tango from the piano bench, and posters announcing café, cabaret and theater seasons. Together the two trades formed one graphic wave — bandoneón silhouettes, street-corner couples, dramatic display lettering — that carried the dance to world fame and fixed tango\'s UNESCO-listed identity.',
    vd: { shape: 'portrait-format covers and posters built around dancers', line: 'lithographic outlines mixing lettering and silhouette', composition: 'title block above, couple and skyline filling the sheet', texture: 'flat spot-color ink with stone-litho grain and foxing' },
    typ: { display: 'bold condensed wood-type caps with fanfare swashes', body: 'compact grotesque sans with tight dramatic leading' },
    lit: { quality: 'smoky café spotlight on printed covers', temperature: 'warm-toned with shadowed edges', shadow: 'ink-heavy litho depth darkening the café room' },
    ui: { background: 'noir café umber', surface: 'aged sheet-music covers with foxed edges', components: 'poster-frame cards with marquee-style titles', motion: 'couple silhouettes drifting in slow tango sway' },
  },
  {
    slug: 'tango-era-poster-art',
    ctx: 'Tango-era poster art sold the dance and its nightlife: from the tango\'s 1880s Río de la Plata origins through the interwar export craze, lithographic posters announced café, cabaret and theater programs in Buenos Aires and Montevideo, and later for the European tango boom. Bold condensed lettering, spotlighted couples and smoke-dark palettes made the poster a mirror of the port-city image tango projected — glamour with a shadowed edge.',
    vd: { shape: 'tall poster sheets dominated by lettering and figures', line: 'high-contrast litho strokes and spotlight beams', composition: 'diagonal couples under oversized marquee titles', texture: 'matte poster stock, misregistered ink edges, smoke haze' },
    typ: { display: 'condensed poster caps with spotlight gradient fills', body: 'utilitarian grotesque listing program details' },
    lit: { quality: 'stage-light glare raking poster paper', temperature: 'warm-toned, dusk-shadowed', shadow: 'silhouetted dancers casting long café shadows' },
    ui: { background: 'spotlit midnight red-black', surface: 'matte poster stock with visible litho grain', components: 'marquee titles and ticket-stub buttons', motion: 'spotlight sweep crossing tilted dancers' },
  },
  {
    slug: 'telemark-rosemaling',
    ctx: 'Telemark rosemaling is the most flamboyant of Norway\'s three main rose-painting styles (with Hallingdal and Rogaland), flourishing 1700s–mid-1800s as rural painters, freed from guild rules, translated Baroque/Rococo acanthus carving into paint. Telemark work is asymmetric: C- and S-scrolls, teardrop acanthus leaves and fantasy flowers swing about a central axis in glazed, shaded color — the style most prized by collectors and revival painters.',
    vd: { shape: 'swinging scroll bouquets on bowls, trunks and walls', line: 'flowing C- and S-curves ending in teardrop acanthus', composition: 'asymmetric balance around a central axis', texture: 'glazed layered color with dark edge-shading on petals' },
    typ: { display: 'hand-painted scroll serifs with acanthus-curl terminals', body: 'warm humanist serif on cream wooden tones' },
    lit: { quality: 'soft window light across painted scrolls', temperature: 'warm-toned', shadow: 'gentle shade pooling in glazed scroll recesses' },
    ui: { background: 'rosemaling cream', surface: 'scroll-painted panels with teardrop acanthus', components: 'C-scroll borders framing cards and chips', motion: 'scrolls unfurling into place' },
  },
  {
    slug: 'hallingdal-rosemaling',
    ctx: 'Hallingdal rosemaling comes from the valley of Hallingdal, one of the style\'s 1700s birthplaces in eastern Norway. It is the symmetric counterpart to Telemark\'s drama: centrally symmetric roundels, concentric wreaths of stylized tulips and roses around a central medallion, painted in strong opaque colors on dark grounds. Hallingdal work covers ale bowls, cupboards, trunks and church interiors in dense, orderly splendor.',
    vd: { shape: 'roundel medallions on flat chest fronts and bowls', line: 'bold even strokes in concentric wreath rings', composition: 'strict central symmetry, mirrored left to right', texture: 'opaque bright pigments, crisp flat color over dark ground' },
    typ: { display: 'symmetric rosette-framed caps in bright enamel colors', body: 'sturdy country serif with generous leading' },
    lit: { quality: 'even bright daylight on flat pigments', temperature: 'warm-toned', shadow: 'minimal — pigment reads bright and opaque' },
    ui: { background: 'deep hallingdal red-brown', surface: 'symmetric roundel medallion cards', components: 'wreath badges and medallion toggles', motion: 'roundel petals rotating into symmetry' },
  },
  {
    slug: 'rogaland-rosemaling',
    ctx: 'Rogaland rosemaling, named for the southwest-coast region, is the third main Norwegian style: finer and more delicate than Telemark\'s drama, with soft pastel glazes, tulip clusters and more naturalistic flowers set in balanced oval and rectangular panels framed by fine scrollwork. The region also kept the art alive in print — during the occupation of Norway a Stavanger firm in Rogaland issued rosemaling-motif cards as coded patriotic statements.',
    vd: { shape: 'oval and rectangular framed floral panels', line: 'fine delicate scrollwork bordering tulip clusters', composition: 'balanced symmetric framing with airy centers', texture: 'soft pastel glazes, thin translucent washes over light ground' },
    typ: { display: 'delicate pastel initials framed in scrollwork borders', body: 'light humanist serif with airy spacing' },
    lit: { quality: 'airy diffuse light on pastel glazes', temperature: 'cool-warm balanced', shadow: 'feathered shade under thin scroll borders' },
    ui: { background: 'pale pastel blue-grey', surface: 'oval scroll-framed panels', components: 'delicate border frames and ribbon chips', motion: 'tulip clusters easing into balanced panels' },
  },
  {
    slug: 'swedish-dalmalning',
    ctx: 'Dalmålning — Sweden\'s Dalarna painting — is the Swedish branch of rose-painting: from the late 1700s through the 1800s, traveling Dalarna painters (dalmålare) painted narrative "wallpaper" on cloth and paper panels hung in farmhouses across Dalarna and neighboring provinces. Motifs came from figure Bibles and cheap woodcuts — religious scenes, local folk dress, landscapes — rendered in clear strong colors with kurbits foliage between scenes.',
    vd: { shape: 'long cloth-and-paper frieze panels of grouped figures', line: 'woodcut-derived outlines with brushed folk color', composition: 'story scenes sequenced across the wall, foliage fillers', texture: 'matte distemper color on worn woven cloth' },
    typ: { display: 'figure-panel caps brushed like woodcut headings', body: 'rustic antique serif with storybook warmth' },
    lit: { quality: 'farmhouse daylight on cloth wall panels', temperature: 'warm-toned', shadow: 'soft folds shadowing the painted figures' },
    ui: { background: 'painted-linen cream', surface: 'narrative frieze panels with folk-costume figures', components: 'story-panel dividers with woodcut frames', motion: 'scenes scrolling past like a farmhouse frieze' },
  },
  {
    slug: 'kurbits',
    ctx: 'Kurbits — from Latin cucurbita, the long-bodied gourd — names the fantasy foliage of Dalarna painting: great bundles of blooming, curling plants that stand alone as decoration or fill the gaps of dalmålning scenes, older examples tied to religious motifs on walls and furniture. The poet Erik Axel Karlfeldt popularized the name in the 1920s ("Kurbitsmålning," 1927), and kurbits brushwork now runs across Swedish craft, most famously on Dala horses.',
    vd: { shape: 'oversized gourd-vine bundles with tulip blooms', line: 'confident one-stroke leaves and curling tendril wisps', composition: 'foliage clumps anchoring scenes or filling gaps', texture: 'flat vivid folk pigments, quick loaded-brush edges' },
    typ: { display: 'swashbrush caps blooming with leafy flourishes', body: 'friendly round serif with kurbits-red accents' },
    lit: { quality: 'bright even light like a painted cottage wall', temperature: 'warm-toned', shadow: 'light shading only, inside foliage bundles' },
    ui: { background: 'warm cottage ochre', surface: 'foliage-bundle cards with curling vines', components: 'kurbits-leaf dividers and bloom badges', motion: 'vines growing and blooming across layouts' },
  },
  {
    slug: 'dalahast',
    ctx: 'The dalahäst — Dala horse — is Dalarna\'s carved and painted wooden horse, first a whittled children\'s toy, now a symbol of Dalarna and of Sweden itself. Local styles differ, but the classic form is stoutly carved, traditionally iron-oxide red (today brighter orange-red) with harness and details in white, green, yellow and blue and a kurbits saddle flourish; workshops around Lake Siljan still carve and paint each horse by hand.',
    vd: { shape: 'stout rounded horse silhouette on flat wooden base', line: 'simple carved contour with painted harness straps', composition: 'single centered figure with saddle as focal ornament', texture: 'glossy oxide-red paint, visible knife facets beneath' },
    typ: { display: 'rounded toy-like caps in oxide red with cream outline', body: 'simple warm sans-serif with hand-cut corners' },
    lit: { quality: 'shop-window clarity on glossy toy paint', temperature: 'warm-toned', shadow: 'short crisp shadows under carved hooves' },
    ui: { background: 'iron-oxide red', surface: 'glossy toy-paint cards with cream edging', components: 'horse silhouette icons and harness-strap rules', motion: 'little horses trotting through loading states' },
  },
  {
    slug: 'finnish-ryijy',
    ctx: 'Ryijy — the Finnish rya — is a knotted long-pile textile of Nordic origin: a Viking-era cloak and blanket, then for centuries the bedcover of Finnish and Swedish homes, pile turned toward the body. Wedding and keepsake ryijys carried dates and initials; in modern times it became one of Finland\'s best-known textile arts, a wall hanging through which folklore motifs and successive art movements have been woven.',
    vd: { shape: 'rectangular tufted field with fringed ends', line: 'knotted row structure building images from pile', composition: 'bold central motifs reading at room distance', texture: 'shaggy long-pile wool, dense directional nap' },
    typ: { display: 'woven-wool block letters with fringed terminals', body: 'soft national-romantic serif with roomy leading' },
    lit: { quality: 'soft raking light lifting the pile', temperature: 'neutral-warm', shadow: 'tuft shadows deepening the woven relief' },
    ui: { background: 'wool ivory', surface: 'long-pile rya texture panels', components: 'tufted gradient chips and fringe borders', motion: 'pile rippling like fabric in slow wind' },
  },
  {
    slug: 'gakti-dress-tradition',
    ctx: 'Gákti is the Northern Sámi word for the traditional dress of Sámi communities across northern Norway, Sweden, Finland and Russia\'s Kola Peninsula, worn for ceremony and while working, particularly reindeer herding. Each region reads differently: a dominant color banded with contrasting trims, plaits, pewter and tin embroidery, often a high collar. Cut and ornament signal home district, family and life stage — a walking register of Sámi belonging.',
    vd: { shape: 'tunic-and-skirt silhouettes with structured high collars', line: 'horizontal contrast bands running collar to hem', composition: 'bands and plaits zoning the body by region', texture: 'dense wool felt with tin-thread shine and silver fittings' },
    typ: { display: 'band-bordered caps in tin-thread outlines', body: 'clean humanist sans with contrasting trim rules' },
    lit: { quality: 'outdoor herding light on wool and tin', temperature: 'cool-toned with silver glints', shadow: 'band trims throwing fine thread shadows' },
    ui: { background: 'gákti blue-black', surface: 'wool panels with contrast band trims', components: 'tin-thread border rules and collar tabs', motion: 'band trims stitching themselves across screens' },
  },
  {
    slug: 'sami-silver-belt-ornamentation',
    ctx: 'Sámi belt silver is a dowry-and-status economy as much as ornament: over a lifetime — especially at weddings — women accumulated stamped and cast silver fittings loading the gákti belt, the greatest sets handed down generations. Region-styled plaques, pendants and studs announced home valley and wealth, and silver carried protective, heirloom meaning that pastoral life made portable — wealth kept where it could travel.',
    vd: { shape: 'belt straps loaded with stacked stamped plaques', line: 'stamped geometric punchwork edging every fitting', composition: 'silver massed densely down the belt line', texture: 'cast silver patina against dark oiled reindeer hide' },
    typ: { display: 'stamped silver medallion caps on leather bands', body: 'quiet humanist sans with silver-foil accents' },
    lit: { quality: 'jewelry-case light on stacked silver', temperature: 'cool-toned', shadow: 'cast plaques shadowing one another down the belt' },
    ui: { background: 'reindeer-brown leather', surface: 'belt-strap rows of stamped silver', components: 'pendant toggles and plaque badges', motion: 'silver pieces clicking onto the belt line' },
  },
  {
    slug: 'tenntradsbrodering',
    ctx: 'Tenntrådsbrodering — tin-thread embroidery — is the Sámi craft of couching fine tin thread, usually alloyed with a little silver and wound around a cotton core, onto reindeer leather: collar and cuff bands of the gákti, knife sheaths, bags and shoes stitched in close parallel coils, S-curves and star motifs. The metal thread catches the low northern light, so bands of embroidered tin read as jewelry worked into leather rather than mere trimming.',
    vd: { shape: 'narrow band registers across collars, cuffs and sheaths', line: 'close parallel coils forming S-curves and stars', composition: 'stitched bands framing garment openings symmetrically', texture: 'bright spiraled tin ridges on dark grained hide' },
    typ: { display: 'coiled tin-thread script with spiraled terminals', body: 'small neat sans set on reindeer-brown panels' },
    lit: { quality: 'low raking northern light catching tin coils', temperature: 'cool-toned', shadow: 'coils casting fine parallel shadows on hide' },
    ui: { background: 'smoked reindeer leather', surface: 'collar-band panels of parallel tin coils', components: 'coiled-thread dividers and star studs', motion: 'tin spirals sewing lines into place' },
  },
  {
    slug: 'sami-reindeer-leather-work',
    ctx: 'Reindeer leather work sits at the center of duodji, Sámi craft: hides became winter footwear, sledge and ski gear, knife sheaths, bags and lines, chosen because reindeer skin is warm, light and hard-wearing in deep cold. Working it — smoke- or bark-tanned hide cut and sinew-sewn, edges clipped in rhythmic patterns — is among the defining skills of Sámi material life and the base layer of most duodji objects.',
    vd: { shape: 'soft volumes — boots, bags, sheaths — from square hides', line: 'sinew seam lines and clipped decorative edges', composition: 'seams and edges carrying all the ornament', texture: 'porous tanned hide grain with hair-follicle freckling' },
    typ: { display: 'tooled-leather caps with clipped-edge patterning', body: 'durable humanist sans with sinew-stitch underlines' },
    lit: { quality: 'overcast even light on tanned hide', temperature: 'neutral-cool', shadow: 'hair-follicle texture breaking up the shadow' },
    ui: { background: 'tan reindeer hide', surface: 'grained hide panels with clipped edges', components: 'sinew-stitch underlines and hide tabs', motion: 'hide panels lacing together with stitch lines' },
  },
  {
    slug: 'duodji-knife-ornamentation',
    ctx: 'The knife is the signature object of duodji, the Sámi craft tradition whose items are made to be used daily yet carry artistry: Sámi knives pair carved birch handles with reindeer-antler fittings and leather sheaths ornamented with tin-thread embroidery, tooled leather and carved patterns. Ornament follows function — grips shaped for use, sheaths built for belt wear — and each maker\'s region and hand show in the handle profile and decoration.',
    vd: { shape: 'stacked handle blocks of birch and antler over blades', line: 'incised S-motifs and tooled borders on sheaths', composition: 'ornament concentrated at handle stack and sheath mouth', texture: 'sanded antler gloss, birch grain, stitched leather' },
    typ: { display: 'antler-carved caps with incised S-motifs', body: 'functional humanist sans with knife-edge rules' },
    lit: { quality: 'workbench side-light on handle and sheath', temperature: 'warm-toned', shadow: 'blade shadow inside the open leather sheath' },
    ui: { background: 'birch and antler ivory-brown', surface: 'handle-grain cards with antler-tip caps', components: 'knife-profile dividers and sheath buttons', motion: 'blade sliding home into a stitched sheath' },
  },
  {
    slug: 'guksi-kuksa-birch-cup-tradition',
    ctx: 'The guksi — Finnish kuksa, Swedish kåsa — is the Sámi drinking cup carved from a birch burl, the rounded grain growth whose curved wood resists splitting. A herding and travel cup, it hangs from the belt, holds anything from coffee to berries, and traditionally carries a thumb rest, often patched or footed with reindeer antler; well-used cups darken into personal heirlooms, and hand-carved guksi remain classic duodji.',
    vd: { shape: 'round-bellied carved cups with wide thumb rests', line: 'knife-facet curves following the burl grain', composition: 'single vessel, handle loop and antler patches balanced', texture: 'dense swirl-grained burl, darkened by use at the rim' },
    typ: { display: 'burl-turned rounded caps with antler inlay dots', body: 'warm plain sans with birch-tan body text' },
    lit: { quality: 'campfire-warm light on carved burl', temperature: 'warm-toned', shadow: 'cup interior falling into soft round shade' },
    ui: { background: 'birch burl tan', surface: 'turned-burl cup forms with antler patches', components: 'cup-shaped chips and hanging-loop icons', motion: 'cups filling with steaming coffee swirls' },
  },
  {
    slug: 'sami-belt-ornaments',
    ctx: 'Sámi belt ornaments are a typology of metalwork worn across the belt line of the gákti: stamped or cast plaques and mounts, suspended pendants and chains, rings and hooks, and solid silver clasps — a repertoire whose forms and densities vary by region. As a set the ornaments punctuate the dress with rhythm and flash, anchor pouches, knife and awl cases at the waist, and mark the belts of festive dress as distinct from everyday working kit.',
    vd: { shape: 'rows of plaques, pendants, rings and clasps at the waist', line: 'stamped punch patterns repeated fixture to fixture', composition: 'evenly spaced ornament rhythm along the strap', texture: 'hammered silver surfaces with dark hide showing between' },
    typ: { display: 'pendant-hung caps with stamped silver fringe', body: 'spaced small-caps sans on gákti-red grounds' },
    lit: { quality: 'flat daylight for typological display', temperature: 'neutral', shadow: 'each pendant casting its own small shadow' },
    ui: { background: 'gákti red wool', surface: 'ornament-row belts across card headers', components: 'stamped plaques, rings and hook icons', motion: 'pendants swinging gently from the belt row' },
  },
  {
    slug: 'gallo-sami-ornamentation',
    ctx: 'Catalogued here as "gallo" Sami, this is the tradition of the Eastern Sámi known as Skolt Sámi (own name sää\'mi), of the Petsamo–Kola borderlands, today centered on Sevettijärvi, Finland. Skolt dress and goods are densely ornamented: heavy silver collar fittings, chains on women\'s dress, embroidered panels, metal-decorated hides. Much heirloom silver scattered in mid-20th-century resettlements; survivors are treasured as rare Eastern Sámi work.',
    vd: { shape: 'closed collar forms and chest panels hung with silver', line: 'chain links and pendant drops swinging below collars', composition: 'ornament massed at the bodice collar zone', texture: 'pleated bright wool against polished coin silver' },
    typ: { display: 'collar-frame caps hung with silver chain details', body: 'warm serif set on pleated red grounds' },
    lit: { quality: 'museum case light on collar silver', temperature: 'cool-toned with warm red reflections', shadow: 'chains shading the pleated wool beneath' },
    ui: { background: 'pleated kolt red', surface: 'collar panels hung with silver chains', components: 'chain-link dividers and coin-pendant chips', motion: 'chains settling with a soft silver sway' },
  },
  {
    slug: 'petrykivka-painting',
    ctx: 'Petrykivka painting comes from the village of Petrykivka in Ukraine\'s Dnipropetrovsk region, where it decorated house walls and household objects from the 18th century onward. Its language is flowers and berries, laid down with distinctive brush techniques on a traditionally white ground (contemporary painters also use black, red and blue). Ukraine recognized it in 2012 and UNESCO inscribed it in 2013; it thrives today as a modern art form.',
    vd: { shape: 'flower sprays and berry clusters on flat surfaces', line: 'single-stroke petals pressed by distinctive brushwork', composition: 'blooms fanning from stems across borders and panels', texture: 'gouache-flat color, wet-on-wet transitions, fine tip lines' },
    typ: { display: 'brushstroke florals curling into letterforms', body: 'lively humanist serif with berry-red accents' },
    lit: { quality: 'bright even studio light on a white ground', temperature: 'warm-toned', shadow: 'almost none — petals stay flat and vivid' },
    ui: { background: 'petrykivka white', surface: 'flower-spray cards with berry clusters', components: 'petal borders and leafy spray icons', motion: 'blooms brushing open with petal strokes' },
  },
  {
    slug: 'pysanka-writing',
    ctx: 'Pysanka — from Ukrainian for "to write" — names the wax-resist egg of Slavic tradition: pagan in origin, transformed by syncretism into the Christian Easter egg; the oldest decorated examples were found in Ukraine. Designs are "written" in beeswax that preserves each color through successive dye baths; sun, bird, plant and geometric symbols make each egg a talisman, exchanged at Easter and now collected worldwide as a signature of Ukrainian art.',
    vd: { shape: 'egg-shaped fields divided into banded symbol zones', line: 'wax-preserved contours around stars, suns and rakes', composition: 'symmetric division of the shell into symbol medallions', texture: 'layered dye baths under glossy wax-resist sheen' },
    typ: { display: 'wax-resist caps built from egg-shaped band motifs', body: 'crisp humanist serif with dyed drop caps' },
    lit: { quality: 'luminous backlight through dyed shell', temperature: 'warm-toned', shadow: 'wax lines shadowing faintly under the dye' },
    ui: { background: 'dyed-egg ochre', surface: 'wax-resist egg panels with band motifs', components: 'egg-shaped chips and wax-line dividers', motion: 'dye baths flooding between wax lines' },
  },
]
