/**
 * Completeness patch r2c — Architecture tail + Art Movement batch (20 entries).
 * Hand-authored from verified entry identities; no LLM involvement.
 */
export const PATCHES: any[] = [
  {
    slug: 'nieuwe-bouwen',
    ctx: 'Nieuwe Bouwen — Dutch functionalism (Nieuwe Bouwen = "New Building") — was the Netherlands\' De Stijl-to-Dudok modernism: J.J.P. Oud\'s Rotterdam housing estates, Johannes Duiker\'s Zonnestraal sanatorium and Open Air School, Willem Marinus Dudok\'s Hilversum town hall, brise-soleil, roof terraces and social-housing idealism. Dutch rationalism (H.P. Berlage\'s brick groundwork) made its modernism humane and communal; the 2010s restoration of Zonnestraal canonized it as a UNESCO-tourism-grade monument of socially ambitious light.',
    vd: { shape: 'pinwheel plans, cantilevered slabs, glazed stair drums', composition: 'light-and-air blocks arranged for sun rights', line: 'steel window grids, brick piers against white slabs', texture: 'clinker brick, glass-and-steel skin, cork floors, steel handrails' },
    typ: { display: 'functional sans block lettering', notes: 'estate name plaques at entries' },
    lit: { quality: 'sanatorium-grade sunlight', temperature: 'cool-toned', shadow: 'brise-soleil shades striped by slabs' },
    ui: { background: 'sanatorium white', surface: 'brick-slab cards', components: 'terrace-rail dividers', motion: 'sun-path shadow tracking' },
  },
  {
    slug: 'metabolism',
    ctx: 'Metabolism (1960-1973) — Kiyonori Kikutake, Kisho Kurokawa, Fumihiko Maki and Kenzo Tange\'s Japanese avant-garde — imagined cities as living organisms: capsules swapping into megastructure trunks (Nakagin Capsule Tower, 1972), marine cities floating on rings, Tange\'s Tokyo Bay Plan. Launched at Tokyo World Design Conference 1960 with the manifesto-like "Ocean City", it made Japan the pole of future-city imagination until oil shocks stalled construction; the capsule tower\'s 2022 demolition intensified global preservation debate over the movement\'s remaining ideals.',
    vd: { shape: 'capsule modules plugged into trunk cores', composition: 'stacked megastructure nodes over city scale', line: 'unit-grid repetition with service spines', texture: 'prefab capsule shells, exposed steel joints, weathering steel tone' },
    typ: { display: 'module-number stencil plates', notes: 'manifesto-era diagram typography' },
    lit: { quality: 'night-megastructure sodium glow', temperature: 'cool-toned', shadow: 'capsule grids cast modular shade' },
    ui: { background: 'megastructure grey', surface: 'capsule-cell cards', components: 'plug-in module toggles', motion: 'capsule-swap cycle animation' },
  },
  {
    slug: 'ashcan-school',
    ctx: 'The Ashcan School — Robert Henri\'s circle (John Sloan, George Bellows, George Luks, Everett Shinn) — painted New York\'s democratic everyday around 1900-1920: tenement rooftops, saloons, boxing rings, girls on fire escapes, snow-slicked streets. Nicknamed "Ashcan" for their grime subjects, they rejected Academy polish for Henri\'s "art for life\'s sake" realism; their dark tonal canvases (charcoal, umber, bravura brushwork) bridged pictorialism to social documentary and set American urban painting\'s voice for a generation.',
    vd: { shape: 'figures anchored in geometric street architecture', composition: 'genre scenes with deep stage-space depth', line: 'decisive contour over tonal masses', texture: 'loaded brush drag, umber-and-slate tonal range, scumble darkness' },
    typ: { display: 'saloon signage lettering painted in-scene', notes: 'newspaper headlines as props' },
    lit: { quality: 'gaslit tenement interior pools', temperature: 'warm-toned', shadow: 'velvet shadows with edges of light' },
    ui: { background: 'tenement umber', surface: 'canvas-grain cards', components: 'etching-line dividers', motion: 'street-life vignette pans' },
  },
  {
    slug: 'regionalism',
    ctx: 'American Regionalism — Grant Wood, Thomas Hart Benton, John Steuart Curry (1930s) — painted the Midwest as America\'s moral backbone through the Depression: Wood\'s "American Gothic" and rolling Iowa hills, Benton\'s twisting mural narratives of Tom Sawyer-Arcadia, Curry\'s Kansas baptisms and tornado skies. Positioned against European modernism and East Coast abstraction, it became WPA-era national imagery; its stylized musculature and luminous farms remain the visual shorthand for "heartland America".',
    vd: { shape: 'rolling land curves with sculpted figure volumes', composition: 'narrative friezes folding time into single panels', line: 'Bentonian sinuous contour ribbons', texture: 'egg-tempera-like smoothness, glazed earth palettes, furrow patterning' },
    typ: { display: 'serif Americana poster caps', notes: 'mural title panels in stone-carved style' },
    lit: { quality: 'prairie wheat-gold afternoon', temperature: 'warm-toned', shadow: 'hill curves shade like relief sculpture' },
    ui: { background: 'harvest gold', surface: 'mural-frieze cards', components: 'wheat-stalk dividers', motion: 'panoramic mural scroll' },
  },
  {
    slug: 'suprematism',
    ctx: 'Suprematism — Kazimir Malevich\'s 1915 invention, announced with the Black Square at 0.10 exhibition — reduced painting to "the supremacy of pure feeling": floating geometric primitives in weightless white space, no horizon, no object, no metaphor. The Black Square (1915), White on White (1918), and the "vkus" (taste) polemics made it the most radical zero-point of modern art; it fed UNOVIS (with El Lissitzky\'s Prouns), influenced constructivist graphics and Bauhaus abstraction, and was suppressed under Stalin as formalism.',
    vd: { shape: 'pure geometric primitives suspended in white voids', composition: 'dynamic diagonal drift, no ground plane', line: 'hard flat edges, no modeling', texture: 'matte oil body, hairline craquelure on black square' },
    typ: { display: 'constructivist sans exhibition labels', notes: 'manifesto typography in geometric blocks' },
    lit: { quality: 'gallery-neutral flat wash', temperature: 'cool-toned', shadow: 'none — shapes float beyond shadow' },
    ui: { background: 'infinite white', surface: 'primitive-shape cards', components: 'floating-square toggles', motion: 'weightless drift easing' },
  },
  {
    slug: 'fauvism',
    ctx: 'Fauvism (1904-1908) — Matisse, Derain, Vlaminck at Collioure — detonated color from description: green stripes on faces ("don\'t put nature in your pictures"), vermilion skies, complementary explosions at full tube strength. Named "wild beasts" (fauves) by critic Louis Vauxcelles at the 1905 Salon d\'Automne, the movement lasted barely four years but permanently freed Western painting from naturalistic color, feeding Matisse\'s lifelong decorative mastery, German Expressionism, and every poster-colored style since.',
    vd: { shape: 'flat color planes bound by dark contours', composition: 'poster-like planes compressed in shallow space', line: 'thick arabesque contour, often in cobalt', texture: 'canvas weave through pure pigment, unblended stroke slabs' },
    typ: { display: 'hand-brushed poster lettering', notes: 'salon-catalogue serif as counterpoint' },
    lit: { quality: 'Mediterranean glare intensified', temperature: 'warm-toned', shadow: 'shadows painted violet, never black' },
    ui: { background: 'vermilion field', surface: 'color-plane cards', components: 'arabesque-line dividers', motion: 'complementary-flash transitions' },
  },
  {
    slug: 'supa-dupa-fly-era',
    ctx: 'The 1997 "Supa Dupa Fly" era — Missy Elliott and Timbaland\'s debut run — fused futuristic R&B with Hype Williams\' fisheye-lens videos: inflatable suits, Harcourt-crystal "The Rain" bubble, Y2K chrome and Africa Bambaataa lineage. As an aesthetic moment it defined late-90s "space-age soul": glossy black-and-silver wardrobe, distorted lens bodies, and video as fashion-film. It shaped 2010s-20s Y2K revival styling (and Missy\'s own MTV Video Vanguard moment) as an era-defining visual grammar.',
    vd: { shape: 'fisheye-distorted bodies in inflated volumes', composition: 'single-dancer frame-filling choreography', line: 'chrome trim and PVC shine edges', texture: 'wet-look vinyl, iridescent lamé, raindrop bubble glare' },
    typ: { display: 'stretched chrome logotypes with vowel gimmicks', notes: 'fisheye-warped title cards' },
    lit: { quality: 'hard video-clip strobe wash', temperature: 'cool-toned', shadow: 'lens distortion bends shadows' },
    ui: { background: 'chrome-silver field', surface: 'vinyl-inflated cards', components: 'bubble-icon buttons', motion: 'fisheye warp on hover' },
  },
  {
    slug: 'harlem-renaissance',
    ctx: 'The Harlem Renaissance (1918-1937) — the New Negro movement — built Black America\'s first full visual-aesthetic self-assertion: Aaron Douglas\'s silhouette murals fusing Art Deco with African mask geometry, Augusta Savage\'s sculpture, James Van Der Zee\'s parlor photography, cover design for The Crisis and Opportunity, and the Cabaret Calloway chitlin glamour. Patronage (Charlotte Mason, Alain Locke\'s The New Negro anthology) framed it as race advancement; its poster-deco-meets-Ancestry style remains the foundation of Black American graphic identity.',
    vd: { shape: 'radiating concentric silhouettes and mask-derived profiles', composition: 'mural friezes of rising figures and music ripples', line: 'geometric Deco contour with African-inspired angularity', texture: 'flat gouache silhouettes, silver gelatin sheen, letterpress covers' },
    typ: { display: 'Deco display caps for Crisis covers', notes: 'van der Zee studio-stamp lettering' },
    lit: { quality: 'cabaret spotlight warmth', temperature: 'warm-toned', shadow: 'silhouette shadows merge with figures' },
    ui: { background: 'velvet cabaret plum', surface: 'deco-panel cards', components: 'banjo-motif dividers', motion: 'jazz-syncopation pulses' },
  },
  {
    slug: 'precisionism',
    ctx: 'Precisionism (1920s-30s) — Charles Sheeler, Charles Demuth, Georgia O\'Keeffe\'s city years, Louis Lozowick — rendered America\'s machines, factories and skyscrapers as crystalline planar geometry: Sheeler\'s Ford photographs and "American Landscape", Demuth\'s "I Saw the Figure 5 in Gold", grain elevators as cathedrals. The first fully American modernist movement, it worshipped industrial form without European angst, and its clean Cubist-Calisthenics still frames corporate American "efficiency" aesthetics.',
    vd: { shape: 'planar geometric architecture, clean edge abstraction', composition: 'stepped skyscraper views and factory stillness', line: 'ruled crisp contours, airbrushed gradients', texture: 'smooth oil surface, photographic clarity, steel-and-concrete sheen' },
    typ: { display: 'stencil-industrial caps in posters', notes: 'Demuth\'s numerals as subject and type' },
    lit: { quality: 'hard industrial morning light', temperature: 'neutral-toned', shadow: 'architecture casts precision shadow planes' },
    ui: { background: 'concrete silver', surface: 'planar-cut cards', components: 'gear-silhouette icons', motion: 'assembly-line stepped pans' },
  },
  {
    slug: 'barbizon-school',
    ctx: 'The Barbizon School (1830-1870) — Rousseau, Corot, Millet, Daubigny — abandoned Paris for the Forest of Fontainebleau village to paint nature directly: oak interiors, peasant sowers, dusky cattle, paysage intime. Rebelling against Neoclassical landscape formulas, they made plein-air observation respectable a generation before Impressionism; Corot\'s silvery mornings and Millet\'s monumentality of peasants seeded both Impressionism and Van Gogh. The Barbizon aesthetic — muted gold-green tonalism, pastoral dignity — still defines "forest mood" painting.',
    vd: { shape: 'organic tree masses framing pastoral stage depths', composition: 'low horizons with big atmospheric skies or forest canopies', line: 'soft lost-and-found contours', texture: 'tonal glazes, silvery greens, canvas-toned warmth' },
    typ: { display: 'salon-catalogue serif etchings titles', notes: 'Millet pastoral prints as popular text' },
    lit: { quality: 'dusk golden hour interiors of forest', temperature: 'warm-toned', shadow: 'tree masses dissolve edges into shade' },
    ui: { background: 'fontainebleau moss', surface: 'canvas-toned cards', components: 'leaf-frond dividers', motion: 'wind-stir canopy shimmers' },
  },
  {
    slug: 'hudson-river-school',
    ctx: 'The Hudson River School (1825-1875) — Thomas Cole, Asher Durand, Frederic Church, Albert Bierstadt — was America\'s first native art movement: panoramic wilderness as providential revelation, luminist sunsets over the Catskills, Andes, and Yosemite. Cole\'s "Course of Empire" moralized; Church\'s "Heart of the Andes" (1859) drew 3,000 paying viewers under opera-house lighting; Bierstadt\'s western canvases advertised Manifest Destiny. Its luminism — glowing atmospheres, God-in-nature — defined 19th-century American landscape taste.',
    vd: { shape: 'panoramic vistas with theatrical light entry', composition: 'dark framing trees opening to infinite distance', line: 'minute detail subordinated to atmosphere', texture: 'luminist glazes, almost invisible brushwork, varnish glow' },
    typ: { display: 'engraved exhibition title scripts', notes: 'Bible verses in picture titles' },
    lit: { quality: 'providential sunset radiance', temperature: 'warm-toned', shadow: 'holy glow dissolves shadow edges' },
    ui: { background: 'luminist gold-rose', surface: 'vignette-framed cards', components: 'vista-view dividers', motion: 'sublime slow-zoom revelations' },
  },
  {
    slug: 'ukiyo-e',
    ctx: 'Ukiyo-e — "pictures of the floating world" — was Edo Japan\'s mass visual culture (1670s-1860s): woodblock prints of actors (Sharaku), courtesans, landmarks (Hokusai\'s 36 Views, Hiroshige\'s Tokaido), and chonin town pleasure quarters, sold for the price of a bowl of noodles. Its prussian-blue breakthrough (1820s), flat planes, cropping and line confidence rewired Western art through Japonisme (Whistler, Van Gogh, Degas); today it remains the world\'s most recognized Japanese graphic tradition.',
    vd: { shape: 'flat color planes with bold contour lines', composition: 'cropped asymmetry, diagonal weather and wave diagonals', line: 'singe-hair keyblock confidence', texture: 'bare-faced woodgrain, bokashi gradient wipes, mica dust sparkle' },
    typ: { display: 'vertical cartouche kanji title blocks', body: 'poem-pillar calligraphy beside prints', notes: 'censor seals as credit marks' },
    lit: { quality: 'flat daylight, printed light', temperature: 'warm-toned', shadow: 'shadow as flat tone steps' },
    ui: { background: 'prussian blue gradient', surface: 'woodblock-texture cards', components: 'cartouche-frame headers', motion: 'wave-curl parallax loop' },
  },
  {
    slug: 'ashcan-photography',
    ctx: 'The social documentary photography tradition descending from Jacob Riis\'s flash-lit tenement exposé (How the Other Half Lives, 1890) and Lewis Hine\'s child-labor evidence — the photo as social document — established American urban photography\'s moral voice: unposed labor, immigrant life, working streets. Through the Photo League (Sid Grossman, Aaron Siskind\'s Harlem Document) it carried into postwar street photography, and its flash-and-honesty grammar still grounds documentary practice.',
    vd: { shape: 'narrow-frame urban vignettes, faces in work', composition: 'corner-compressed interiors and alley depths', line: 'flash-shadow hard edges', texture: 'press-camera grain, glossy print blacks, scratched negatives' },
    typ: { display: 'headline slide captions', notes: 'photo-essay typewriter introductions' },
    lit: { quality: 'flash bulb harsh honesty', temperature: 'neutral-toned', shadow: 'flash throws hard social light' },
    ui: { background: 'darkroom grey', surface: 'contact-sheet cards', components: 'frame-number strips', motion: 'slide-projector clack advance' },
  },
  {
    slug: 'pictorialism',
    ctx: 'Pictorialism (1885-1915) — Alfred Stieglitz\'s Photo-Secession, Gertrude Käsebier, Edward Steichen, Clarence White — fought for photography as fine art by making pictures look like paintings: soft-focus lenses, gum-bichromate brushwork, platinum prints, allegorical titles, and salon jury aesthetics. Camera Work magazine (1903-17) was its manifesto organ; its end (Straight Photography, Paul Strand 1917) proved the argument won photography\'s museum status while leaving a haze-golden aesthetic still quoted in romantic portraiture.',
    vd: { shape: 'soft-edged tonal masses, atmospheric veils', composition: 'symbolist poses, mirror and window motifs', line: ' contours dissolved into light', texture: 'gum-bichromate brush texture, platinum matte, tissue-guard softness' },
    typ: { display: 'art-nouveau Camera Work mastheads', body: 'essay small-caps salon prose', notes: 'titles as poem captions' },
    lit: { quality: 'north-light pictorial glow', temperature: 'warm-toned', shadow: 'diffused, never stark' },
    ui: { background: 'platinum warm grey', surface: 'tissue-veil cards', components: 'soft-focus blur toggles', motion: 'gauze-fade transitions' },
  },
  {
    slug: 'vaudeville-poster-art',
    ctx: 'Vaudeville and circus poster art (1880s-1920s) — Strobridge, Courier, theRingling Brothers printers — built American billboard culture: stone-lithograph multi-sheet spectacles with ten-color process, star portraits at opera-house scale, and type as fireworks (wood type faces still named for circuses). Working-class America read them as everyday wallpaper; collectors now prize "Circus posters" as the apex of pre-cinema commercial lithography, and their grammar (the stacking bill, the star burst) lives in concert posters and drag-show flyers.',
    vd: { shape: 'stacked billboard compositions with portrait medallions', composition: 'bill-of-show hierarchy, eight-sheet monsters', line: 'chromolitho registration and burst ray-lines', texture: 'stone-litho ink density, sheet-seam overlaps, paste-weathered corners' },
    typ: { display: 'wood-type pyramids with catchword bullets', body: 'small-print show-bill blocks', notes: 'typefaces as circus performers' },
    lit: { quality: 'marquee daylight-and-gas mixture', temperature: 'warm-toned', shadow: 'portrait vignettes shaded litho-style' },
    ui: { background: 'paste-bill tan', surface: 'stone-litho cards', components: 'bill-stack headers', motion: 'marquee-bulb chase lights' },
  },
  {
    slug: 'wpa-poster-art',
    ctx: 'The Works Progress Administration poster division (1936-1943) — under Richard Dhuwne and Anthony Veloz — produced some 35,000 designs: silkscreened public-health, national-park, theater and literacy posters in flat, bold, modernist colors. Drawing on Bauhaus and constructivist émigré lessons, the posters made New Deal graphic style a civic vernacular; the Library of Congress collection (2,000+ surviving) is the canon, and its two-ink silkscreen grammar anchors today\'s "national park poster" revival industry.',
    vd: { shape: 'flat poster geometry with simplified landscape icons', composition: 'message-first stacking with pictorial header', line: 'silkscreen block edges, minimal linework', texture: 'flat ink coverage, slight screen-mesh tooth, poster-board matte' },
    typ: { display: 'heavy geometric sans stacked messages', body: 'small-caps details blocks', notes: 'WPA credit line as seal' },
    lit: { quality: 'flat print studio evenness', temperature: 'varies by palette, always poster-true', shadow: 'only where the design says so' },
    ui: { background: 'posterpaint cream', surface: 'silkscreen cards', components: 'message-stack headers', motion: 'ink-roller pass reveals' },
  },
  {
    slug: 'picasso-blue-period',
    ctx: 'Picasso\'s Blue Period (1901-1904) — triggered by friend Carlos Casagemas\'s suicide — painted Barcelona and Paris\'s dispossessed in monochrome blues: beggars, blind men, la vie\'s lovers, The Old Guitarist. Critically cool then, now the most famous monochrome phase in art history, the period established Picasso\'s melancholic humanism before Rose Period and Demoiselles. Its blue-tonalism is quoted everywhere a single color carries grief.',
    vd: { shape: 'elongated figure masses in shallow stage spaces', composition: 'café and streetside tableau intimacy', line: 'thin contour accenting tonal washes', texture: 'thin matte oil, canvas showing through blue glaze layers' },
    typ: { display: 'none', body: 'gallery label neutrality', notes: 'the blue is the caption' },
    lit: { quality: 'blue-lit interior dusk', temperature: 'cold-toned', shadow: 'shadows deepen into Prussian depths' },
    ui: { background: 'cobalt blue wash', surface: 'canvas-toned cards', components: 'guitar-figure icons', motion: 'blue-fade cross transitions' },
  },
  {
    slug: 'dutch-golden-age-still-life',
    ctx: 'Dutch Golden Age still life (1600s) — Heda and Claesz\'s breakfast pieces (banketjes), vanitas skull-and-bubble warnings, Pronk luxury displays, flower pieces by Heem and Ruysch — made table painting a moral theater: abundance and mortality, Calvinist economy and colonial spice, insect life-cycle vignettes in tulip petals. Scientific optics (lenses) sharpened dew and lemon peel; the genre\'s symbolic reading tradition continues to structure every "flat lay" and luxury advertising composition today.',
    vd: { shape: 'foreshortened table planes with stacked object pyramids', composition: 'monochrome tonal breakfasts or full-color pronk chaos', line: 'implied edges through value only', texture: 'glass sheen, pewter dullness, lemon-peel spiral highlight, insect shell glint' },
    typ: { display: 'none', body: 'vanitas Latin mottos occasionally inscribed', notes: 'objects carry the moral sentence' },
    lit: { quality: 'single north-window keystoning', temperature: 'neutral-toned', shadow: 'deep table-edge shadow anchoring pyramids' },
    ui: { background: 'cellar-workshop brown', surface: 'tonal-still cards', components: 'vanitas-icon badges', motion: 'fruit-soft spoiling shifts' },
  },
  {
    slug: 'byzantine-mosaic',
    ctx: 'Byzantine mosaic (330-1453) — Ravenna\'s San Vitale, Constantinople\'s Hagia Sophia, Palermo\'s Cappella Palatina — made walls into fields of heavenly gold: glass tesserae set at angles to catch candlelight, frontal saints in hieratic order, imperial processions meeting angels. The mosaics were theology as surface — light itself divine — and their gold-ground logic later structured Duccio, Giotto\'s roots and every icon screen. Ravenna\'s UNESCO monuments remain the most complete imperial ensemble.',
    vd: { shape: 'frontal hieratic figures on flat gold fields', composition: 'dome ascension and apse theophany programs', line: 'tessera-set contour and highlight steps', texture: 'angled gold glass glitter, colored enamel smalti, mortar-set irregularity' },
    typ: { display: 'Greek titlos and monogram panels', body: 'psalm inscriptions wrapping vaults', notes: 'letters set in stone as scripture surface' },
    lit: { quality: 'candlelight multiplied by gold', temperature: 'warm-toned', shadow: 'tessera angles turn shadow into shimmer' },
    ui: { background: 'gold-ground field', surface: 'tessera-texture cards', components: 'halo-medallion frames', motion: 'candle-flicker shimmer loops' },
  },
  {
    slug: 'gothic-stained-glass',
    ctx: 'Gothic stained glass (1140s-1500s) — Abbot Suger\'s Saint-Denis choir, Chartres\' blue, Sainte-Chapelle\'s wall-of-light — made windows into theology: grisaille-and-gold panels, blue-virgin ensembles, rose windows as cosmic diagrams. Painters fired detail onto colored glass; lead lines drew the contour language; UNESCO-listed Chartres and Sainte-Chapelle remain the canon. The glass\'s color-in-motion inspired every subsequent "light as material" art from Expressionist windows to Liggett-colored skylights.',
    vd: { shape: 'lancet and rose geometries with leaded panel stories', composition: 'light-wall programs rising to rose oculus', line: 'lead came as drawing, painted grisaille detail', texture: 'pot-metal glass depth, silver-stain golds, jewel-tone luminosity' },
    typ: { display: 'donor and saint name bands', body: 'Latin texts as window "pages"', notes: 'windows read as illuminated books' },
    lit: { quality: 'sun-through-glass color light', temperature: 'cool-toned', shadow: 'the glass itself is colored light' },
    ui: { background: 'cathedral blue', surface: 'leaded-glass cards', components: 'rose-window loaders', motion: 'sun-cycle color shift' },
  },
]
