/**
 * Completeness patch r5b — global art movements batch (20 entries). [retry]
 * Hand-authored; facts verified via Wikipedia API (Pattachitra, Nsukka group,
 * Ottoman miniature + Levni, Persian miniature, Mughal painting, Joaquín
 * Torres-García + América Invertida, Manifesto Antropófago, Outsider art incl.
 * its Neuve Invention taxonomy, Visionary environment, Naïve art, Tā moko,
 * Makonde art, Taller de Gráfica Popular, Polish School of Posters, Kamala
 * Ibrahim Ishaq / the Crystalist group). Sudanese Kriatalism, Prague Group,
 * Sunday Painters, PichiAvo and Indigenism-in-Mexico have no standalone
 * enwiki articles — those entries stay general-confident, no invented dates
 * or names.
 */
export const PATCHES: any[] = [
  {
    slug: 'pattachitra',
    ctx: 'Pattachitra — Sanskrit patta, "cloth", and chitra, "picture" — is the cloth-scroll painting of eastern India, centered on Odisha\'s Jagannath temple at Puri and continued by Bengali patua painters. Chitrakar painters grind natural pigments onto treated cloth or palm leaf, building Vaishnava and mythological narratives; Bengali scrolls were unrolled scene by scene as a singer performed their story. The tradition is over a thousand years old.',
    vd: { shape: 'long cloth scrolls and palm-leaf pothi strips', line: 'bold black outlines enclosing bulbous figures', composition: 'register-like narrative bands framed by decorative borders', texture: 'matte earth pigment over tamarind-gum prepared cloth' },
    typ: { display: 'devanagari-flavored display with scroll-panel weight', body: 'clean humanist sans for captions' },
    lit: { quality: 'even temple-courtyard daylight across flat color', temperature: 'warm-toned', shadow: 'no modeling; outlines carry all depth' },
    ui: { background: 'deep red ochre cloth ground', surface: 'border-patterned card frames', components: 'scroll-panel section dividers', motion: 'unrolling-scroll sequential reveals' },
  },
  {
    slug: 'nsukka-school',
    ctx: 'The Nsukka group formed in the art department of the University of Nigeria, Nsukka, under Uche Okeke, whose "natural synthesis" theory made him seminal to Nigerian modernism. The artists revived uli, the ephemeral body and wall painting traditionally Igbo women\'s art, carrying its flowing curves into acrylic, gouache, watercolor and ink. The Smithsonian\'s National Museum of African Art showed them in 1997 as "The Poetics of the Line."',
    vd: { shape: 'lyrical linear compositions on paper and canvas', line: 'thin uli curves, herringbone motifs and tapering strokes', composition: 'line-first spacing where drawing breathes around emptiness', texture: 'dry ink washes and gouache over open paper' },
    typ: { display: 'drawn-line display serif with uli curvature', body: 'light geometric sans' },
    lit: { quality: 'soft diffuse studio light over pale paper', temperature: 'warm-toned', shadow: 'faint wash pooling where lines gather' },
    ui: { background: 'soft paper ivory', surface: 'line-drawn card outlines', components: 'uli-motif divider strokes', motion: 'hand-drawn stroke-draw transitions' },
  },
  {
    slug: 'sudanese-kriatalism',
    ctx: 'Sudanese Kriatalism is an obscure modernist tendency recorded in Sudanese art history, adjacent to the Khartoum School that carried Sudan into modern art by fusing Arabic calligraphy with African expression. It belongs to the decades when painters debated what a Sudanese modernity should look like — a debate the conceptual Crystalist group around Kamala Ibrahim Ishaq renewed against the conventions of 1960s Sudanese modern painting.',
    vd: { shape: 'flat panel compositions between painting and script', line: 'calligraphic contours and rhythmic angular breaks', composition: 'centralized emblems balanced against open ground', texture: 'matte gouache and ink with woven-pattern fills' },
    typ: { display: 'kufic-modern Arabic display lettering', body: 'quiet neutral sans with Arabic support' },
    lit: { quality: 'harsh Nile-valley sun diffused through dust', temperature: 'warm-toned', shadow: 'flattened shadows locked to pattern edges' },
    ui: { background: 'Nile mud ochre', surface: 'letterform-cut panel headers', components: 'calligraphic-knot icon accents', motion: 'script-unfurl reveal transitions' },
  },
  {
    slug: 'ottoman-miniature',
    ctx: 'Ottoman miniature (Osmanlı minyatürü) illustrated imperial manuscripts, within a book-arts ensemble of illumination (tezhip), calligraphy (hat), marbling and binding. Grown from Persian, Byzantine and Mongol influences, it bent toward documentation: precise accounts of campaigns, chronicles and festivals rather than lyric fantasy. Court painters like Levni (died 1732) filled pages with lively anecdotal figures, flat color and factual detail.',
    vd: { shape: 'album and manuscript pages banded with text panels', line: 'fine uniform contour lines around stylized figures', composition: 'tiered scenes and grid courts seen in tilted elevation', texture: 'smooth burnished paper with gold-leaf accents' },
    typ: { display: 'divani-style calligraphic display script', body: 'compact scholarly serif' },
    lit: { quality: 'even palace light across open folios', temperature: 'warm-toned', shadow: 'flat; depth given by gold and border layers' },
    ui: { background: 'deep maroon with gold illumination frame', surface: 'folio-page cards with ruled bands', components: 'tughra-style corner flourishes', motion: 'folio-turn page transitions' },
  },
  {
    slug: 'safavid-miniature',
    ctx: 'Safavid miniature crowned the Persian tradition of negargari — small paintings on paper for manuscripts and muraqqa albums — at its peak in the fifteenth and sixteenth centuries. Under Shahs Ismail and Tahmasp the royal ateliers of Tabriz and Herat, led for a time by the master Bihzad, produced luxurious Shahnameh commissions. Fine drawing, jewel color and stacked compositions became the dominant influence on Ottoman and Mughal painting alike.',
    vd: { shape: 'single-folio paintings with ruled text cartouches', line: 'gold-finished fine brush contour over vibrant color', composition: 'tilted stacked planes packed edge to edge with incident', texture: 'polished pigment with tooled gold and lapis flecks' },
    typ: { display: 'shimmering nastaliq display calligraphy', body: 'small literary serif for album notes' },
    lit: { quality: 'jewel-box evenness, light caught in gold leaf', temperature: 'warm-toned', shadow: 'minimal; color rhythm replaces shading' },
    ui: { background: 'lapis ultramarine field', surface: 'gold-rule framed cards', components: 'rosette medallion buttons', motion: 'illumination-gild fade-in reveals' },
  },
  {
    slug: 'mughal-painting',
    ctx: 'Mughal painting flourished from the sixteenth century onward, from the atelier organized under Akbar to the intense naturalism of Jahangir. Descended from Persian miniature, it absorbed Indian color, Islamic ornament and European shading brought by Jesuit prints at court, with a far stronger taste for realistic portraiture. Animal and plant studies filled imperial muraqqa albums alongside court scenes and book illustration.',
    vd: { shape: 'album folios with wide decorated margins', line: 'precise fine brush drawing with European-modeled volumes', composition: 'dense centered court scenes framed by illuminated borders', texture: 'burnished gouache with incised detail and gold hatching' },
    typ: { display: 'nastaliq display script with gold accent rules', body: 'elegant muted serif' },
    lit: { quality: 'soft north-lamp studio light on miniature scale', temperature: 'warm-toned', shadow: 'subtle modeled shading on faces and drapery' },
    ui: { background: 'album cream with painted margin blooms', surface: 'bordered-folio cards', components: 'margin-floriate nav trims', motion: 'album-leaf slide transitions' },
  },
  {
    slug: 'indigenism',
    ctx: 'Indigenism in Mexican art is the post-Revolutionary current, backed by indigenismo ideology, that made Indigenous Mexico the center of national identity. Muralists led by Diego Rivera filled walls with Aztec laborers and conquest scenes, while Frida Kahlo grounded self-portraiture in Tehuana dress and pre-Hispanic symbols. The movement reversed colonial hierarchy, turning once-despised Indigenous heritage into the signature of modern Mexico.',
    vd: { shape: 'monumental mural walls and shallow-picture portraits', line: 'sculptural rounded contours drawn from pre-Columbian relief', composition: 'processional friezes stacking history across the wall', texture: 'fresco matte, broad pigment planes with dry edges' },
    typ: { display: 'bold mural-poster sans capitals', body: 'warm humanist sans' },
    lit: { quality: 'high Mexican sun raking across plaster', temperature: 'warm-toned', shadow: 'hard-edged simplified shadows like cut stone' },
    ui: { background: 'terracotta red earth', surface: 'fresco-plaster section panels', components: 'stepped-pyramid corner motifs', motion: 'wall-painting scaffold-reveal scroll' },
  },
  {
    slug: 'constructive-universalism',
    ctx: 'Constructive Universalism is the theory and school of Uruguayan Joaquín Torres-García, who reached Montevideo in 1934 after co-founding Cercle et Carré in Paris and Madrid\'s Grupo de Arte Constructivo. His 1943 América Invertida drawing turned South America upside down; his paintings set pictograms of sun, fish and anchor inside architecture-proportioned grids of universal signs. His Montevideo Taller carried the style to a generation.',
    vd: { shape: 'gridded rectangular fields subdivided into sign cells', line: 'even dark rule lines locking pictogram to frame', composition: 'modular grid architecture with signs stacked like masonry', texture: 'flat matte oil with visible panel joins' },
    typ: { display: 'modular geometric grid sans capitals', body: 'neutral modernist sans' },
    lit: { quality: 'even rational studio light', temperature: 'neutral-warm', shadow: 'flat; grid lines do all structural work' },
    ui: { background: 'unbleached canvas bone', surface: 'ruled-grid layout skeleton', components: 'pictogram icon set', motion: 'grid-cell cascade reveals' },
  },
  {
    slug: 'anthropophagy',
    ctx: 'Anthropophagy was the second wave of Brazilian modernism launched by Oswald de Andrade\'s Manifesto Antropófago of 1928, inspired by Tarsila do Amaral\'s Abaporu. Its program — "Tupi, or not Tupi" — recast cannibalism as cultural strategy: Brazil should devour European influence, digest it and make it authentically its own. Circulated through the Revista de Antropofagia, it became one of Latin America\'s most influential cultural metaphors.',
    vd: { shape: 'swollen organic figures and hybrid biomorphic forms', line: 'inflated cartoon contour with elastic distortion', composition: 'single totemic figure against chemically pure skies', texture: 'smooth enamel-like paint with saturated flushes' },
    typ: { display: 'rough-cut Brazilian modernist display type', body: 'warm humanist sans' },
    lit: { quality: 'blistering tropical noon, color at full bleed', temperature: 'warm-toned', shadow: 'minimal; heat flattens shadow into color' },
    ui: { background: 'acid green with hot coral blocks', surface: 'devoured-collage card edges', components: 'fanged-mouth toggle shapes', motion: 'bite-and-swallow wipe transitions' },
  },
  {
    slug: 'prague-group',
    ctx: 'The Prague Group — the Czechoslovak Surrealist Group founded 1934 in Prague by Vítězslav Nezval with Karel Teige, Toyen and Jindřich Štyrský — became surrealism\'s most durable cell, surviving occupation and socialism. Its art braided dream, eroticism and political unease into precise oniric paintings, reaching film through Jan Švankmajer (joined 1970) and Eva Švankmajerová. Toyen\'s gender-neutral persona remains its celebrated face.',
    vd: { shape: 'void-scattered dream stages with isolated objects', line: 'smooth academic contour tracing impossible scenes', composition: 'deep oneiric emptiness with small sharp motifs', texture: 'polished oil glaze over eerie gradient skies' },
    typ: { display: 'surrealist collage display lettering', body: 'refined central-european serif' },
    lit: { quality: 'stage-lit dusk, objects lit against black', temperature: 'cool-toned', shadow: 'long theatrical shadows leaking from objects' },
    ui: { background: 'faded Prague ochre with coal shadows', surface: 'collage-tear panel edges', components: 'eye-and-lock motif icons', motion: 'melting-object morph transitions' },
  },
  {
    slug: 'outsider-art',
    ctx: 'Outsider art is the term Roger Cardinal coined in 1972 as the English equivalent of Jean Dubuffet\'s art brut, the "raw art" Dubuffet named in the 1940s for work made outside official culture by psychiatric patients, hermits, spiritualists and other self-taught creators. Dubuffet\'s Collection de l\'Art Brut in Lausanne fixed the canon, and since 1993 the New York Outsider Art Fair has made the category a market fixture.',
    vd: { shape: 'obsessive accumulated surfaces, books and buildings filled', line: 'unstable self-invented contours and compulsive hatching', composition: 'all-over density without academic hierarchy', texture: 'raw mixed materials, ballpoint, crayon, soot, thread' },
    typ: { display: 'raw hand-drawn display type', body: 'plain utilitarian sans' },
    lit: { quality: 'bare bulb light in attic and asylum rooms', temperature: 'cool-toned', shadow: 'uneven shadows deepening obsessive detail' },
    ui: { background: 'workshop gray with paper scraps', surface: 'pinned-and-taped document cards', components: 'stitch and staple fasteners', motion: 'compulsive line-draw loops' },
  },
  {
    slug: 'visionary-environments',
    ctx: 'Visionary environments are the building-scale installations and sculpture parks that self-taught creators labor over for decades — decorated houses, grottoes, gardens of towers — built to express an intensely personal vision. The type sits close to outsider art, its makers usually marginal to the art world. Canonical examples include Simon Rodia\'s Watts Towers in Los Angeles, the Buddha Park in Laos and its Thai companion Sala Keoku.',
    vd: { shape: 'towering spires, mosaic domes and encrusted walls', line: 'frenzied ornament wrapping every structural surface', composition: 'total environments where nothing escapes decoration', texture: 'embedded glass, shell, pebble and found-object encrustation' },
    typ: { display: 'assembled folk-object display lettering', body: 'plain legible sans' },
    lit: { quality: 'open-sky sun flashing off embedded glass', temperature: 'warm-toned', shadow: 'spire shadows sweeping across packed courtyards' },
    ui: { background: 'concrete gray with mosaic sparkle', surface: 'encrusted-tile card faces', components: 'spire-and-flower ornament chips', motion: 'slow construction-accumulation build-ins' },
  },
  {
    slug: 'naive-painting',
    ctx: 'Naïve painting is the work of artists without formal training who know the conventions of fine art but cannot, or choose not to, use them. The result is a childlike directness and frankness, collected and imitated since Henri Rousseau, the self-taught customs officer whose jungle scenes hung beside the avant-garde. Flat space, sharp detail, off scale and bright unmodulated color give naïve canvases their peculiar force.',
    vd: { shape: 'frontal flat scenes with every element outlined', line: 'careful deliberate contour, stiff and literal', composition: 'stacked shallow depth, objects sized by importance', texture: 'smooth enamel-finish oil, little brush expression' },
    typ: { display: 'cheerful folk-painted display type', body: 'simple rounded sans' },
    lit: { quality: 'uniform storybook daylight', temperature: 'warm-toned', shadow: 'literal small shadows repeated under each object' },
    ui: { background: 'garden green with flower-dot pattern', surface: 'hand-tilted storybook cards', components: 'button-daisy icons', motion: 'bouncing toy-box entrance animations' },
  },
  {
    slug: 'sunday-painters',
    ctx: 'Sunday painters are the great army of amateur artists — the French "peintres du dimanche" — who paint evenings and weekends around their day jobs, filling kitchens and attics with landscapes, still lifes and portraits of houses and family. Most pursue the craft for love, but the category shades into naïve art where a self-taught weekend painter achieves a personal vision; amateur salons have long given their work a modest public stage.',
    vd: { shape: 'small framed landscapes and still lifes at tabletop scale', line: 'copybook contour borrowed from prints and postcards', composition: 'textbook one-point views, horizon politely centered', texture: 'moderately loaded oil brush, patient hobbyist finish' },
    typ: { display: 'hand-painted hobbyist lettering', body: 'friendly rounded sans' },
    lit: { quality: 'soft afternoon light through kitchen windows', temperature: 'warm-toned', shadow: 'gently generalized shadows, softly blended' },
    ui: { background: 'faded armchair sage', surface: 'small-easel framed cards', components: 'gilt-frame corner brackets', motion: 'shelf-hanging settle-in animations' },
  },
  {
    slug: 'neuve-invention',
    ctx: 'Neuve Invention — "new invention" — is Jean Dubuffet\'s companion category to art brut, for marginal artists who retain some interaction with mainstream culture, perhaps painting part-time or exhibiting occasionally. Strictly speaking it covers a special section of the Collection de l\'Art Brut; French circles also use "marginal art" and "art singulier" for the same middle territory.',
    vd: { shape: 'framed independent sheets closer to studio practice', line: 'assured personal contour with schooled echoes', composition: 'planned formats betraying awareness of exhibitions', texture: 'standard artist materials, applied with idiosyncratic touch' },
    typ: { display: 'delicate marginal-lettering display type', body: 'quiet gallery sans' },
    lit: { quality: 'gallery-spaced even light on modest works', temperature: 'neutral-cool', shadow: 'thin drop shadows from simple framing' },
    ui: { background: 'white-wall gallery off-white', surface: 'thin-plate mounted cards', components: 'caption-label chips', motion: 'gentle drift-in hover states' },
  },
  {
    slug: 'maori-ta-moko',
    ctx: 'Tā moko is the permanent body marking practiced by Māori, one of the five great Polynesian tattoo styles. Worked by tohunga-tā-moko, tattooists considered tapu and sacred, traditional moko cut grooves into the skin with chisels rather than puncturing it, carving spirals across face and body that recorded lineage, rank and achievement. Women\'s moko kauae, the chin marking, has seen a powerful modern revival as an assertion of Māori selfhood.',
    vd: { shape: 'face-centered spiraling fields following skull planes', line: 'koru spirals and grooved parallel chisel channels', composition: 'symmetric facial architecture keyed to bone structure', texture: 'incised groove ridges against skin, dense black infill' },
    typ: { display: 'angular carved koru display lettering', body: 'sturdy humanist sans' },
    lit: { quality: 'clear southern daylight on carved skin relief', temperature: 'cool-toned', shadow: 'grooves cast hard micro-shadows like woodcut' },
    ui: { background: 'pounamu deep green-black', surface: 'groove-carved panel headers', components: 'koru-spiral icons and dividers', motion: 'chisel-carve stroke reveals' },
  },
  {
    slug: 'pichiavo',
    ctx: 'PichiAvo is a Spanish street-art duo known for setting the gods of Greek myth directly onto contemporary walls: Apollo, Athena and their kin painted like polished marble statuary, then broken across by raw graffiti tags, drips and chrome lettering. From murals to canvas they have carried the pairing of classical sculpture and urban writing to festivals, museums and exhibitions worldwide, making antiquity and graffiti argue on the same wall.',
    vd: { shape: 'life-scale god figures rooted on graffiti walls', line: 'classical marble-fine modeling crashed into fat tag outlines', composition: 'sculptural center figure against layered writing field', texture: 'polished airbrush flesh over spray-cracked aerosol' },
    typ: { display: 'graffiti-tag display lettering with marble-serif accents', body: 'clean contemporary sans' },
    lit: { quality: 'museum key-light on painted stone, street glare behind', temperature: 'neutral-cool', shadow: 'statue-strong core shadows against flat spray color' },
    ui: { background: 'atmospheric spray gray', surface: 'marble-finish hero cards', components: 'tag-style underline strokes', motion: 'spray-fade over statue-slow parallax' },
  },
  {
    slug: 'makonde-art',
    ctx: 'Makonde art is the sculpture of the Makonde people of northern Mozambique and southern Tanzania, divided by the Ruvuma River. Traditionally they carved masks and ritual objects from soft njala wood; masks remain the art\'s heart, above all the famed mapiko masks danced at initiations. First exhibited in Mozambique in the 1930s, the genre later divided into traditional and modern carving, including shetani spirit figures prized by collectors.',
    vd: { shape: 'full-round helmet masks and tall stacked human figures', line: 'sleek head crests and flowing carved contours', composition: 'vertical figure-on-figure totems rising from one trunk', texture: 'oiled dark ebony-like wood, burnished scarification marks' },
    typ: { display: 'bold carved-wood display capitals', body: 'earthy humanist sans' },
    lit: { quality: 'filtered village-shade light on oiled wood', temperature: 'warm-toned', shadow: 'deep hollows carving black ridges in relief' },
    ui: { background: 'charred ebony brown', surface: 'wood-carved section plaques', components: 'mask-silhouette icons', motion: 'lathe-turn rotation reveals' },
  },
  {
    slug: 'taller-de-grafica-popular',
    ctx: 'The Taller de Gráfica Popular (People\'s Graphic Workshop) was founded in Mexico City in 1937 by Leopoldo Méndez, Pablo O\'Higgins and Luis Arenal as a print collective for political action. Its shop produced linocut leaflets and broadsides for revolutionary and anti-fascist causes, sold cheaply for workers, and drew foreign artists as collaborators. Its stark black-and-white graphics set the standard for committed printmaking in the Americas.',
    vd: { shape: 'sheet-sized leaflets and portfolio prints in stark relief', line: 'knife-cut white lines gouged from black linoleum', composition: 'high-contrast diagonal energy built from hatched blacks', texture: 'inking grain, chatter marks and bitten paper texture' },
    typ: { display: 'woodcut poster sans with protest weight', body: 'compact grotesque for leaflets' },
    lit: { quality: 'hard workshop light flattening relief blocks', temperature: 'neutral-cool', shadow: 'pure black cut shapes, no gradient' },
    ui: { background: 'newsprint off-white', surface: 'ink-pressed flat cards', components: 'stamp-and-inked edge trims', motion: 'block-print stamp-down reveals' },
  },
  {
    slug: 'polish-poster-school',
    ctx: 'The Polish School of Posters, active from the early 1950s to the late 1980s, turned state-commissioned posters for films and cultural events into an internationally admired art under communist censorship. After the 1956 thaw its Warsaw and Kraków artists — Henryk Tomaszewski, Jan Lenica and Waldemar Świerzy among them — blurred designer and artist, distilling each commission into a succinct painterly metaphor with hand-lettered type.',
    vd: { shape: 'B1-format sheets read as single painted ideas', line: 'loose brushwork, torn collage edges and gestural smear', composition: 'one succinct metaphor dominating empty paper', texture: 'poster paint, crayon and print grain left visible' },
    typ: { display: 'painterly hand-lettered poster display', body: 'loose brush-caption sans' },
    lit: { quality: 'overcast Baltic light suiting matte gouache', temperature: 'cool-toned', shadow: 'paper-flat; painted shadows are graphic shapes' },
    ui: { background: 'gallery white with poster red accents', surface: 'full-bleed art-sheet cards', components: 'hand-lettered label scribbles', motion: 'paste-up slap transitions' },
  },
]
