/**
 * Completeness patch r3c — Indian, Sri Lankan, Indonesian & Thai traditions (20).
 * Hand-authored from live manifest slugs; Wikipedia-verified titles; no LLM involvement.
 */
export const PATCHES: any[] = [
  {
    slug: 'ink-cake-molding',
    ctx: 'Ink cake molding is the Chinese craft of pressing soot-and-glue dough into carved wood molds to form decorated ink cakes: pine-soot or lampblack bodies kneaded with animal glue, released with reliefs of dragons, landscapes, verses and maker names. Huizhou workshops in Anhui produced the finest cakes from the Ming dynasty onward, and master makers\' signed cakes became collector\'s objects — tools for grinding on the inkstone and miniature sculptures of the literati studio at once.',
    vd: { shape: 'pillow-like molded cakes with raised relief scenes and inscriptions', line: 'crisp negative-cut mold edges defining dragons and verses', composition: 'central medallion imagery framed by band inscriptions', texture: 'matte carbon black, faint glue sheen, crisp cast relief' },
    typ: { display: 'mold-carved brush lettering naming makers and formulas', body: 'kaishu colophon scripts on collector boxes' },
    lit: { quality: 'raking studio light lifting low relief', temperature: 'neutral-dark', shadow: 'shallow relief shadows pooling in the black' },
    ui: { background: 'inkstone charcoal', surface: 'cake-relief cards', components: 'mold-frame borders', motion: 'grinding-circular ripples' },
  },
  {
    slug: 'gongshi-scholars-rocks',
    ctx: 'Gongshi — Chinese scholar\'s rocks — are natural stones selected for likeness to mountains and cosmic landscape, displayed on carved hardwood stands in the study. Lake Tai\'s perforated limestone (taihu) and Lingbi\'s dark resonant stones were prized for the qualities of thin, open, pierced and wrinkled texture. Since Song dynasty times literati have treated them as portable wilderness — daoist micro-mountains to contemplate, ranked with painting and bonsai in the scholar\'s studio grammar.',
    vd: { shape: 'upright pierced stone bodies balanced on fitted stands', line: 'wind- and water-eroded channels and flutes', composition: 'single sculptural object in studied negative space', texture: 'honeycombed limestone voids, matte grey-green patina' },
    typ: { display: 'vertical calligraphic colophons naming the stone', body: 'small regular-script studio inscriptions' },
    lit: { quality: 'single-window directional daylight', temperature: 'cool-toned', shadow: 'deep piercings pool black shadow' },
    ui: { background: 'rice-paper grey', surface: 'stand-like plinth cards', components: 'void-pierced dividers', motion: 'slow orbit reveals' },
  },
  {
    slug: 'zhuanshi-seal-carving',
    ctx: 'Zhuanshi seal carving (zhuàn kè) turns seal-script characters into cut stone: literati since the Ming-Qing era carve zhuanshu designs into soapstone — Shoushan, Qingtian and Changhua stones are classic — with knife techniques valued like brushwork, printing the results in cinnabar paste on paintings, letters and books. Characters read red-on-white or white-on-red; the impressed seal is both signature and compositional accent, and carving one\'s own seal became a canonical literati art beside calligraphy.',
    vd: { shape: 'squarish stone blocks crowned with sculpted knob finials', line: 'knife-cut zhuanshu strokes, square-ended and springy', composition: 'few-character fields balanced red against white', texture: 'stone grain, cinnabar paste bleed on absorbent paper' },
    typ: { display: 'zhuanshu seal-script impressions, red-on-white and white-on-red', body: 'regular-script colophons and title slips' },
    lit: { quality: 'flat copying-table light', temperature: 'neutral', shadow: 'minimal — stamps lie flush on paper' },
    ui: { background: 'cinnabar red on paper white', surface: 'seal-impression chips', components: 'stamp-pad buttons', motion: 'press-and-lift impression stamps' },
  },
  {
    slug: 'handscroll-mounting',
    ctx: 'Handscroll mounting (zhuangbiao) is the Chinese craft that turns painting and calligraphy into portable architecture: the work is faced and backed with paper, framed in silk brocade bands, and finished with a wooden roller and stiletto ends, so the scroll unrolls right to left, an arm\'s length at a time. Mounters match silk colors and damask patterns to the painting\'s age and tone; the layered structure of face, protection strips and backing has conserved masterworks through centuries of re-mounting.',
    vd: { shape: 'long horizontal bands stepped in silk and paper layers', composition: 'centered painting field inside graded brocade borders', line: 'straight mitered seams and parallel damask rails', texture: 'figured silk damask, aged paper warmth, roller gloss' },
    typ: { display: 'frontispiece title slips in formal brush script', body: 'colophon columns of literati script inside the scroll' },
    lit: { quality: 'gallery-wide even wash', temperature: 'neutral', shadow: 'slight roller-end shadow on the wall' },
    ui: { background: 'silk-damask beige', surface: 'scroll-band panels', components: 'bordered strip rails', motion: 'unroll-right-to-left pans' },
  },
  {
    slug: 'kishangarh-painting',
    ctx: 'Kishangarh painting is the 18th-century Rajput court school of Kishangarh in Rajasthan, crystallized around the prince-devotee Raja Sawant Singh (Nagari Das) and the revered ideal Bani-Thani: women with pointed profiles, arched lotus eyes and serpentine locks set into Radha-Krishna devotional scenes of refined elegance. Painters such as Nihal Chand perfected the elongated profile, brilliant greens and gold, mixing Mughal finish with local Bhakti intensity; the school remains Rajasthan\'s most recognizable miniature idiom.',
    vd: { shape: 'tall narrow folios with figure groups under pale horizons', line: 'sweeping profile outlines, eyelid and brow arcs', composition: 'flanking attendants framing a central courtly couple', texture: 'polished pigment, burnished gold, fine paper tooth' },
    typ: { display: 'nastaliq title bands naming Radha-Krishna episodes', body: 'Devanagari couplet captions in small panels' },
    lit: { quality: 'moonlit terrace luminescence', temperature: 'cool greens with warm gold', shadow: 'flat miniatures, hairline shading only' },
    ui: { background: 'pale jade night green', surface: 'folio-frame cards', components: 'gold-border buttons', motion: 'profile-turn reveals' },
  },
  {
    slug: 'kangra-painting',
    ctx: 'Kangra painting is the Pahari school that flourished in the Kangra valley of Himachal Pradesh from the mid-18th century, notably under the patronage of Raja Sansar Chand: Gita Govinda and Bhagavata romances of Radha and Krishna drawn with fine squirrel-hair line, tender natural detail of flowering trees, reed beds and rain, and soft greens, teals and rose skin tones. Its lyrical, slim-waisted figures and delicate hatching became the classical image of the Pahari miniature across India.',
    vd: { shape: 'portrait folios with layered tree and river settings', line: 'hair-fine continuous contour, leaf-by-leaf drawing', composition: 'diagonal grove-and-stream staging of figure groups', texture: 'matte mineral washes, stippled grass, silk-smooth ground' },
    typ: { display: 'Devanagari couplet panels floating above scenes', body: 'fine marginal script of couplet continuations' },
    lit: { quality: 'soft Himalayan valley daylight', temperature: 'cool-toned', shadow: 'leaf-shade dappling, painted not cast' },
    ui: { background: 'rain-washed teal', surface: 'folio panels with gilt edges', components: 'vine-scroll dividers', motion: 'page-turn feather reveals' },
  },
  {
    slug: 'deccani-painting',
    ctx: 'Deccan painting is the court art of the 16th-17th century Deccan sultanates — Ahmadnagar, Bijapur and Golconda — where Persianate drawing met local idiom: tall sinuous figures, huge radiant halos, gold-flecked skies, African courtiers and Sufi subjects under patrons such as Bijapur\'s Ibrahim Adil Shah II. Golconda\'s diamond wealth funded dreamlike blues and greens; the school\'s strange intensity and color brilliance set it apart from both Mughal and Persian art.',
    vd: { shape: 'elongated figures in tall folios under wide skies', line: 'languid calligraphic contours, spiral trees', composition: 'single figures or small groups in vast decorated fields', texture: 'velvety ultramarine, gold-flecked skies, burnished halos' },
    typ: { display: 'Persian nastaliq captions in gilded cartouches', body: 'Deccani Urdu marginal notes and verse' },
    lit: { quality: 'night-garden radiance with halo glow', temperature: 'warm gold on cool indigo', shadow: 'flat fields, luminous rather than cast' },
    ui: { background: 'gold-flecked indigo', surface: 'tall-folio cards', components: 'cartouche-frame headers', motion: 'halo-pulse glows' },
  },
  {
    slug: 'company-painting',
    ctx: 'Company painting is the hybrid Indian art made for East India Company patrons from the late 18th century: Mughal-trained workshop artists in Murshidabad, Patna, Lucknow, Delhi and Tanjore adapted precise miniature drawing to European watercolor shading, perspective and paper formats, producing natural-history albums of birds and botany for patrons of the Impey circle, caste and trade occupation series, and monument views for British collectors — the bridge that carried Indian technique into colonial and museum taste.',
    vd: { shape: 'album leaves of single specimens or full-length figures', line: 'miniature-fine outlines reinforced by European wash', composition: 'centered subjects on uncluttered white album grounds', texture: 'flat local color under graded graphite-and-gum shading' },
    typ: { display: 'engraved colonial serif titles on album mounts', body: 'Devanagari, Telugu or Persian artist inscriptions' },
    lit: { quality: 'specimen-plate even light', temperature: 'neutral', shadow: 'soft cast shadows after European models' },
    ui: { background: 'album white', surface: 'plate-mount cards', components: 'ruled collection labels', motion: 'folio-lift page reveals' },
  },
  {
    slug: 'kelaniya-temple-murals',
    ctx: 'The murals of Kelaniya Raja Maha Vihara, the great Buddhist temple near Colombo where the Buddha is held to have preached on his third visit to Sri Lanka, were repainted in the 1930s by artist Solias Mendis, who revived an older Sinhalese temple manner — deep reds, blues and golds, band-eyed Buddha figures and Jataka story walls — inside a shrine rebuilt in the 18th century under Kandyan royal patronage. Kelaniya\'s Duruthu poya pilgrimage each January fills its image walls with worshippers.',
    vd: { shape: 'wall-wide narrative registers of Jataka and Buddha scenes', line: 'soft flowing outlines, lotus-petal eye curves', composition: 'tiered registers around seated and reclining Buddhas', texture: 'flat mineral color, gilt halo outlines, polished plaster' },
    typ: { display: 'Sinhala script scene titles with rounded curves', body: 'pilgrim notice boards in bold Sinhala' },
    lit: { quality: 'lamp-and-daylight temple glow', temperature: 'warm-toned', shadow: 'flat painted shade with gilt outline light' },
    ui: { background: 'temple deep red', surface: 'register-band cards', components: 'lotus-petal buttons', motion: 'pilgrim-procession scrolls' },
  },
  {
    slug: 'dambulla-cave-temple-murals',
    ctx: 'Dambulla\'s rock cave temple — five shrine caves under a vast granite overhang in Sri Lanka\'s Cultural Triangle — holds over 2,000 square meters of murals and more than 150 Buddha images, the island\'s largest painted cycle. Painting from earlier monastic layers was re-covered in the 18th century under Kandyan patronage: red-and-gold reclining Buddhas, floral ceilings and standing figures, all sheltered by the natural rock. The UNESCO World Heritage site remains a working pilgrimage temple.',
    vd: { shape: 'cave-ceiling floral canopies over image-lined walls', line: 'buoyant Kandyan outline with petal-rich borders', composition: 'rows of seated Buddhas behind a giant reclining figure', texture: 'flat red-gold fields, crackled repaint layers, rock grain' },
    typ: { display: 'Kandyan rock-inscription panel lettering', body: 'round Sinhala donor captions' },
    lit: { quality: 'oil-lamp amber against cave darkness', temperature: 'warm-toned', shadow: 'natural rock recesses swallow edges' },
    ui: { background: 'cave ochre red', surface: 'cavern-panel cards', components: 'gold-fleck accents', motion: 'lamp-flicker ambience' },
  },
  {
    slug: 'ambalangoda-mask-carving',
    ctx: 'Ambalangoda, on Sri Lanka\'s southern coast, is the island\'s mask-carving town: family workshops shape kaduru (milkwood) heads for the masked dances of the low country — kolam comic folk drama, exorcism sanni demon sets and protective raksha masks — then paint them in swirling bright colors with bulging eyes, fangs and serpent crowns. Mask museums and dance troupes keep the repertoire alive, and carved masks now travel worldwide as icons of Sinhalese folk art.',
    vd: { shape: 'goggle-eyed mask heads with flared serpent crowns', line: 'curling paint outlines around fangs and brows', composition: 'symmetrical demon faces split by central nose ridges', texture: 'glossy paint on pale wood, deep carved hollows' },
    typ: { display: 'hand-painted Sinhala workshop signboards', body: 'kolam verse song-sheet lettering' },
    lit: { quality: 'bright coastal workshop light', temperature: 'warm-toned', shadow: 'mask cavities cast strong eye-hole shade' },
    ui: { background: 'demon-face vermillion', surface: 'mask-plaque cards', components: 'serpent-crown badges', motion: 'mask-wiggle reveals' },
  },
  {
    slug: 'sri-lankan-drum-decoration',
    ctx: 'Sri Lankan drum decoration dresses the island\'s ritual instruments: the geta bera played for Kandyan dance, the yak bera of low-country exorcism ritual and the cylindrical dawula of temple and village processions all carry painted and lacquered bands — vine scrolls, lotus medallions, dotted rims — around barrel bodies whose heads meet in a waist bound by cord webbing. The decoration signals the rank of dance and rite, echoing temple-painting palettes across the island.',
    vd: { shape: 'hourglass and barrel drum bodies with waisted cord webbing', line: 'circulating bands of vine scroll and dot rims', composition: 'end-to-end symmetry around the two playing heads', texture: 'taut rawhide heads, glossy lacquer bands, cord cross-weave' },
    typ: { display: 'festival banner Sinhala display script', body: 'dance-school ruled practice sheets' },
    lit: { quality: 'outdoor procession glare', temperature: 'warm-toned', shadow: 'lacquer bands throw ring shadows' },
    ui: { background: 'ceremonial lacquer red-gold', surface: 'drum-waist roundels', components: 'cord-weave dividers', motion: 'rhythm-pulse ring pulses' },
  },
  {
    slug: 'sri-lankan-batik-workshop-culture',
    ctx: 'Sri Lankan batik grew from Javanese teaching into a cottage-industry culture of family compounds and cooperative workshops after independence: hot-wax drawing with canting and brushes, stepped dye baths, crackle effects and sun-dried yards of cloth became sarongs, shirts, wall hangings and tourist gifts. Motifs mix Kandyan flora, Buddhist lotus and elephant imagery with abstract crackle; small studios around Kandy and the southern coast keep the wax-and-dye rhythm of drying lines and communal dye vats alive.',
    vd: { shape: 'yardage panels of motif repeats inside wax outlines', line: 'canting-drawn bead lines with hairline crackle webs', composition: 'bordered panels around central Buddhist and floral motifs', texture: 'waxy matte resist, layered dye blooms, cotton tooth' },
    typ: { display: 'studio nameboard lettering in bold Sinhala', body: 'order-book cursive and price tags' },
    lit: { quality: 'open-air drying-yard brightness', temperature: 'warm-toned', shadow: 'folded cloth shadows on the lines' },
    ui: { background: 'dyed indigo ground', surface: 'cloth-swatch cards', components: 'wax-crackle borders', motion: 'dye-bloom diffusion fills' },
  },
  {
    slug: 'matale-lacquer-turning',
    ctx: 'Matale, in central Sri Lanka, anchors the island\'s laksha lacquer craft: village workshops turn bowls, vases, walking sticks, candle stands and ornamental pieces on hand lathes while sticks of molten lac resin are pressed against the spinning wood, building vivid banded surfaces of red, yellow, green and black that are polished to a deep gloss. Patterned by combed waves and nail-head banding, turned lacquer ware is a staple of Sri Lankan craft societies and gift traditions.',
    vd: { shape: 'spindle-turned silhouettes ringed in bright lac bands', line: 'horizontal banding with combed wave interruptions', composition: 'concentric color rings following the turned profiles', texture: 'molten-lac gloss, lathe-fine ridges, polished depth' },
    typ: { display: 'craft-society wood-burned labels', body: 'sales-ledger upright script' },
    lit: { quality: 'workshop-side shafts of sunlight', temperature: 'warm-toned', shadow: 'lacquer gloss mirrors window light' },
    ui: { background: 'polished lac red', surface: 'turned-profile cards', components: 'banded-ring sliders', motion: 'lathe-spin rotations' },
  },
  {
    slug: 'kris-pamor-patterns',
    ctx: 'The pamor of the Malay-Javanese kris is pattern-welded poetry: smiths (empu) layer iron with nickel-bearing metal — traditionally including meteoritic iron — fold and forge the blade, then etch it so contrasting lamellae rise as watered patterns named for scattered rice (beras wutah) or golden rain (udan mas). Guided by ritual and numerology, the asymmetric double-edged dagger carries spiritual power for its owner; UNESCO proclaimed the Indonesian kris a Masterpiece of the Oral and Intangible Heritage of Humanity in 2005.',
    vd: { shape: 'wavy asymmetric blades with flared pistol-grip hilts', line: 'watered lamellae streams along the blade ridge', composition: 'pattern flow converging on the base and tip', texture: 'etched nickel silvery-watering on dark iron, matte wood scabbard' },
    typ: { display: 'Javanese aksara maker\'s marks on blade tangs', body: 'palm-leaf manuscript captions on kris lore' },
    lit: { quality: 'edge-lighting on etched steel', temperature: 'cool-toned', shadow: 'blade waves ripple shifting highlights' },
    ui: { background: 'dark forge iron', surface: 'pamor-stream panels', components: 'watered-steel accents', motion: 'lamellae shimmer sweeps' },
  },
  {
    slug: 'wayang-kulit',
    ctx: 'Wayang kulit, the shadow theatre of Java and Bali, stages Ramayana and Mahabharata epics with perforated, gilded and painted buffalo-hide puppets pressed flat against a white cotton kelir screen, lit by an oil lamp and voiced entirely by the dalang puppeteer over gamelan. The craft encodes Javanese cosmology — refined elongated figures for noble knights, coarse bulky forms for ogres — and UNESCO proclaimed the Indonesian wayang tradition a Masterpiece of the Oral and Intangible Heritage of Humanity in 2003.',
    vd: { shape: 'flat articulated hide figures with lance-like arms', line: 'pierced tracery of vines and openwork detail', composition: 'dalang-orchestrated figures across the lit screen', texture: 'translucent hide glow, gilt edge paint, leather spring' },
    typ: { display: 'episode titles from Javanese-script manuscripts', body: 'dalang prompt-books and verse notes' },
    lit: { quality: 'single oil-lamp backlight halo', temperature: 'warm amber', shadow: 'giant sharp-edged shadows through pierced hide' },
    ui: { background: 'kelir screen cream', surface: 'puppet-silhouette cards', components: 'pierced-tracery dividers', motion: 'shadow-arm gesture toggles' },
  },
  {
    slug: 'balinese-carving',
    ctx: 'Balinese carving orders wood and stone into an unbroken ornament: temple gates (the split candi bentar and roofed kori agung), shrine thrones, barong and rangda masks, rafters and beams covered in patra foliage, flame tongues and demon faces, each relief finished with paint and gold leaf. Carving villages such as Mas near Ubud trained family workshops whose motifs double as offerings — every surface mediates between human and spirit worlds in the island\'s Hindu-Balinese cosmology.',
    vd: { shape: 'stepped gate silhouettes crowned by flame-finned roofs', line: 'tightly coiled patra vines and fanged grimaces', composition: 'symmetric relief fields ascending in tiers', texture: 'deep-cut relief shadow, gilt and polychrome paint, grain polish' },
    typ: { display: 'Balinese script inscriptions on gate lintels', body: 'lontar palm-leaf manuscript lettering' },
    lit: { quality: 'tropical temple-day brightness', temperature: 'warm-toned', shadow: 'relief depth doubles shadow detail' },
    ui: { background: 'carved sandstone cream', surface: 'gate-tier cards', components: 'flame-tongue badges', motion: 'vine-unfurl ornaments' },
  },
  {
    slug: 'joglo-architecture',
    ctx: 'The joglo is the classic Javanese house type: a steep hipped-pyramid roof raised on four central saka guru posts, its ceiling built of the tiered tumpang sari interlock that signals rank, fronted by an open pendhapa pavilion for guests and ceremonies and backed by enclosed family rooms. Timber framing, carved gebyok doors and a metaphysics of orientation made the joglo the grammar of Javanese aristocratic and village architecture alike, still echoed in modern Indonesian design.',
    vd: { shape: 'steep pyramidal roofs over square columned cores', line: 'stepped tumpang sari ceiling tiers stacking inward', composition: 'pendhapa porch field before enclosed interior blocks', texture: 'aged teak grain, soot-darkened rafters, carved panel relief' },
    typ: { display: 'carved gebyok door panel inscriptions', body: 'Javanese family chronicle script' },
    lit: { quality: 'pendhapa-filtered daylight from four sides', temperature: 'neutral-warm', shadow: 'deep eaves shade under the bright roof ridge' },
    ui: { background: 'teak brown ground', surface: 'post-and-beam cards', components: 'tiered-ceiling headers', motion: 'roof-rise expand transitions' },
  },
  {
    slug: 'gamelan-gong-smithing',
    ctx: 'Gamelan gong smithing forges the tuned bronze core of Javanese and Balinese orchestras: copper-tin bronze is cast into discs, hammered into gong bosses and keyed bars, then tuned by cold-hammering and grinding until each instrument\'s pitch locks into the ensemble\'s slendro or pelog tuning. Central Javanese workshops supply ensembles whose gongs mark musical cycles, and whose forging is itself ritual — a new gamelan is ceremonially brought to life before it sounds.',
    vd: { shape: 'boss-centered gong discs and slab key rows', line: 'hammered concentric facets around each boss', composition: 'ensemble rows from great gong to small kettle racks', texture: 'bronze patina greens, hammer facets, carved frame wood' },
    typ: { display: 'kepatihan cipher notation charts', body: 'hand-ruled practice grids in workshop ink' },
    lit: { quality: 'forge-dark workshop with fire glow', temperature: 'warm-toned', shadow: 'boss craters ring firelight shadow' },
    ui: { background: 'aged bronze green', surface: 'gong-boss round cards', components: 'hammer-facet chips', motion: 'resonant ripple pulses' },
  },
  {
    slug: 'khon-masked-dance-costume',
    ctx: 'Khon, Thailand\'s classical masked dance drama of the Ramakien epic, dresses demons, monkey warriors and celestials in hua khon masks — built over frames, gilded, lacquered and glass-set per character lineage — plus brocade tunics dense with gold-thread embroidery, jeweled belts and towering spired headdresses. Once a royal court performance, khon was inscribed by UNESCO on its intangible cultural heritage lists in 2018 and remains the summit of Thai costume art.',
    vd: { shape: 'towering masked heads with flared spires and fangs', line: 'gilded scrollwork framing glass-jeweled eyes', composition: 'frontal masked figures against gold-threaded brocade fields', texture: 'lacquer gilt, mirror-glass glints, stiff metallic brocade' },
    typ: { display: 'Thai script scene titles in court calligraphy', body: 'choreography manual notes in Thai print' },
    lit: { quality: 'stage spotlight on gilt surfaces', temperature: 'warm gold', shadow: 'mask depth carves cheek shadow' },
    ui: { background: 'royal gold-on-black', surface: 'mask-portrait cards', components: 'gem-eye accents', motion: 'dance-pose transitions' },
  },
]
