/**
 * Completeness patch r4a — Chinese minority textiles / Korean crafts / Indian & Sindhi textile traditions (20).
 * Hand-authored (Task 4-a); facts Wikipedia-API-verified (en/zh); no LLM involvement.
 * Fills ctx + visualDNA + typography + lighting + uiTranslation.
 */
export const PATCHES: any[] = [
  {
    slug: 'miao-silver-embroidery',
    ctx: 'The Miao of the mountains of southern China — above all Guizhou, the largest of China\'s ethnic minorities — dress festivals in two signature arts: silver and embroidery. Silversmiths forge horn-shaped headdresses, neckrings and lock pendants, while women embroider festival jackets with butterfly-mother, dragon and bird motifs recounting migration legend. Glittering metal and dense silk stitching mark wealth, clan memory and rites of passage.',
    vd: { shape: 'horned silver headdresses and festival jacket panels', line: 'fine satin-stitch silk over cast scrollwork outlines', composition: 'metal crowning the head, embroidery ringing cuffs and hems', texture: 'polished silver glitter against dense silk-thread relief' },
    typ: { display: 'angular ethnic display caps with silver-bright outlines', body: 'warm humanist serif for legend panels' },
    lit: { quality: 'festival-court daylight glinting off silver', temperature: 'cool-toned', shadow: 'sharp jewelry shadows over embroidered ground' },
    ui: { background: 'indigo midnight', surface: 'silver-stamped cards with thread-relief borders', components: 'headdress badges and butterfly-mother icons', motion: 'pendant glints swaying like worn silver' },
  },
  {
    slug: 'dong-indigo-baby-carriers',
    ctx: 'The Dong (Kam) people of eastern Guizhou, western Hunan and northern Guangxi — famed for wind-and-rain bridges and drum towers — dye cotton deep indigo in vats, beating it glossy, then sew and embroider it into baby carriers: stiff square panels that bundle an infant to a mother\'s or grandmother\'s back. Ribbon-edged embroidered fronts pair protective motifs with the sheen of beaten indigo, a color held to shield a child\'s skin and spirit.',
    vd: { shape: 'stiff rectangular carrier panels with shoulder ties', line: 'grid-ruled stitching bands and ribbon borders', composition: 'central protective emblem framed by counted bands', texture: 'lacquered indigo sheen, raised silk embroidery, folded cloth weight' },
    typ: { display: 'folk stencil caps with dyed-resist edges', body: 'plain sturdy sans on undyed cotton' },
    lit: { quality: 'shaded courtyard light under drum towers', temperature: 'cool-toned', shadow: 'fold shadows pooling in glossy indigo pleats' },
    ui: { background: 'deep vat indigo', surface: 'ribbon-framed carrier cards', components: 'protective-emblem chips and stitch-band dividers', motion: 'carrier panel rocking to a walker\'s step' },
  },
  {
    slug: 'liangshan-yi-cloaks',
    ctx: 'In Liangshan, the great Yi (Nuosu) homeland of southern Sichuan, herders and elders wrap themselves in wool capes — the fringed cha\'erwa and pleated felt mantles — spun, felted and plaited at home through high cold seasons. Shelter, blanket and status in one, the cloak keeps an ink-black ground banded with red and yellow appliqué echoing the Yi lacquer palette, its dense lower fringe swinging as wearers stride mountain paths.',
    vd: { shape: 'shoulder-draped capes ending in swinging fringe', line: 'vertical pleat ridges and horizontal color bands', composition: 'dark field carrying red-and-yellow banded trim', texture: 'dense felted wool, plaited fringe, waxy lanolin hand' },
    typ: { display: 'angular script-inspired caps with lacquer-bright inlays', body: 'sturdy serif for mountain-epic captions' },
    lit: { quality: 'thin high-altitude sun through cloak wool', temperature: 'warm-toned', shadow: 'fringe shadows striping the felt shoulders' },
    ui: { background: 'charcoal felt black', surface: 'banded cape cards with fringe edges', components: 'pleat-fold toggles and lacquer-palette chips', motion: 'fringe swaying as panels stride' },
  },
  {
    slug: 'sipsongpanna-dai-brocade',
    ctx: 'Sipsongpanna — the Tai name for Xishuangbanna, the Dai prefecture on Yunnan\'s Myanmar and Laos border — weaves brocade on small body-tension looms: weft-faced bands of silk and cotton raised over dark grounds in peacocks, pagoda roofs, lotus blooms and elephants. Woven for festival dress, temple offering cloths and dowry pieces, its gold-and-jewel palette carries the Dai affinity for gilded temple spires and tropical gardens.',
    vd: { shape: 'narrow woven bands and shoulder-bag panels', line: 'stepped diamond lattices with bird-and-pagoda inserts', composition: 'banded repeats alternating figures with geometric fill', texture: 'raised weft floats, crisp silk relief, dense cotton ground' },
    typ: { display: 'rounded Tai-inspired display caps with gold edging', body: 'clean humanist sans for warm-toned panels' },
    lit: { quality: 'humid canopy-filtered daylight', temperature: 'warm-toned', shadow: 'weft floats casting fine woven shadows' },
    ui: { background: 'banana-leaf green', surface: 'brocade-banded cards with gold picks', components: 'peacock medallions and lotus toggles', motion: 'bands advancing loom-weft by loom-weft' },
  },
  {
    slug: 'shui-horsetail-embroidery',
    ctx: 'Among the Shui (Sui) people of Guizhou, embroidery rides on horsehair: strands of horsetail wrapped in colored silk floss are couched into springy, raised outlines that hold curves no thread alone could keep. Prized on baby carriers, shoes and festival aprons, the technique lifts butterfly, dragon and flower motifs off indigo cloth in glossy relief, and the densest pieces are treasured as proof of a woman\'s patience and household standing.',
    vd: { shape: 'curved medallion motifs on apron and carrier panels', line: 'raised horsehair outlines in glossy silk wraps', composition: 'symmetric coil-and-bloom motifs over dark grounds', texture: 'springy corded relief, floss sheen, indigo ground' },
    typ: { display: 'curled display caps echoing coiled floss', body: 'soft rounded sans on deep blue panels' },
    lit: { quality: 'even window light picking out raised coils', temperature: 'cool-toned', shadow: 'hairline coil shadows above the cloth' },
    ui: { background: 'indigo dyebath blue', surface: 'cord-outlined cards with floss-gloss borders', components: 'coil-line icons and medallion badges', motion: 'coiled outlines drawing in like stitched curves' },
  },
  {
    slug: 'gejia-batik',
    ctx: 'The Gejia, a small Guizhou people of Huangping and Kaili officially grouped with the Miao, are celebrated for wax-resist batik worn on festival dress. Women draw melted wax from a metal blade in fine spirals and sunburst centers, dip the cloth in indigo vats, then stitch the crackled blue-and-white lengths into pleated skirts and baby carriers. Sun-radius rosettes, fish and bird motifs tie the costume to Gejia origin stories and lineage markings.',
    vd: { shape: 'pleated skirt panels radiating circular rosettes', line: 'fine knife-drawn spirals with hairline wax crackle', composition: 'sun-radius medallions marching in ordered rows', texture: 'crackled wax veins, indigo bleed, matte cotton' },
    typ: { display: 'dyed stencil caps with spiral terminals', body: 'light airy sans on bleached cotton white' },
    lit: { quality: 'bright highland daylight over drying cloth', temperature: 'cool-toned', shadow: 'wax crackle throwing net-thin shadows' },
    ui: { background: 'batik indigo white', surface: 'rosette-bloomed cards with crackle texture', components: 'sunburst badges and spiral dividers', motion: 'indigo blooming outward like a dipped cloth' },
  },
  {
    slug: 'zhuang-brocade',
    ctx: 'Zhuang brocade — man in the Zhuang language — is the signature handwoven cloth of China\'s largest minority, the Tai-speaking Zhuang of Guangxi. Local records praise a people who "love color", weaving garments, sashes and quilts from five-colored threads: bold diamonds, braided zigzags and stylized birds and flowers in fierce reds, oranges and greens, raised in weft floats on cotton warps for dowry boxes, shoulder bags and festival dress.',
    vd: { shape: 'thick woven panels and sash bands', line: 'stepped diamonds and hooked zigzag frets', composition: 'allover geometric repeats with figure medallions', texture: 'raised weft relief, chunky silk over cotton warp' },
    typ: { display: 'blocky display caps with woven-band frames', body: 'compact grotesque for bold panels' },
    lit: { quality: 'bright loom-room daylight', temperature: 'warm-toned', shadow: 'weft ridges striping fine woven shadows' },
    ui: { background: 'five-thread crimson', surface: 'diamond-lattice cards with woven borders', components: 'medallion chips and zigzag dividers', motion: 'diamond rows shuffling like a pattern repeat' },
  },
  {
    slug: 'najeonchilgi',
    ctx: 'Najeonchilgi is Korean mother-of-pearl lacquerware: thin slices cut from abalone and other shells are inlaid into lacquered wood, their iridescence shifting blue, green and rose as light moves. Long applied to chests, game boards, comb boxes and temple fittings, the craft lays shoreline-glint patterns — cranes, clouds, vines, geometric keyfrets — into near-black lacquer grounds, pairing the sea\'s shimmer with the clean line of Korean furniture.',
    vd: { shape: 'low chests, flat boxes and board surfaces', line: 'hair-thin shell strands in vine and keyfret outlines', composition: 'central medallion with corner-cartouche balance', texture: 'glassy lacquer depth, abalone iridescence, mirror-smooth finish' },
    typ: { display: 'brush-drawn hangul caps with pearl highlights', body: 'refined serif for dark lacquer grounds' },
    lit: { quality: 'cool directional light that stirs the shell shimmer', temperature: 'cool-toned', shadow: 'lacquer depths swallowing all but glints' },
    ui: { background: 'black lacquer', surface: 'pearl-inlaid cards with keyfret trims', components: 'shell-glint icons and cloud-corner frames', motion: 'iridescence drifting as panels tilt' },
  },
  {
    slug: 'buncheong-ware',
    ctx: 'Buncheong ware is Korean stoneware born in the fifteenth century between Goryeo celadon and Joseon white porcelain: blue-green bodies coated in white slip and decorated by a roster of free techniques — slip stamped in dense florals, incised, sgraffito-cut to the dark clay, brushed or iron-painted. Made in great quantities for daily use and tea, its unforced hand was prized by Japanese tea masters, and studio potters revive the style today.',
    vd: { shape: 'broad-shouldered jars, bowls and tea cups', line: 'stamped floral fields and swift sgraffito cuts', composition: 'all-over slip patterning honoring the thrown form', texture: 'white slip on blue-green stoneware, glazed unevenness' },
    typ: { display: 'stamped seal-script caps with slip texture', body: 'quiet sans with soft grey ink' },
    lit: { quality: 'north-lit studio light on glazed clay', temperature: 'cool-toned', shadow: 'soft pooling shadows in thrown footrings' },
    ui: { background: 'celadon grey-green', surface: 'slip-stamped cards with sgraffito marks', components: 'stamp-repeat borders and brush-dash toggles', motion: 'slip strokes dragging across like a loaded brush' },
  },
  {
    slug: 'dancheong',
    ctx: 'Dancheong — "cinnabar and blue-green" — is Korea\'s decorative painting system for wooden temples and palaces, adapted from Chinese danqing. Built from repeating pattern units called danchu, it runs in banded courses along eaves, beams and brackets, keyed to five directions and elements: blue east, white west, red south, black north, yellow center. Beyond ornament it shields timber and marks sacred rank, lifting plain wood into jeweled ceremony.',
    vd: { shape: 'banded courses following beam and bracket geometry', line: 'scrolling floral curls framing lozenge danchu units', composition: 'repeating units stepping along eave lines', texture: 'matte mineral pigment, gilded accents, layered paint ridges' },
    typ: { display: 'brush-weighted hangul caps with vermilion warmth', body: 'dignified serif on temple-paper cream' },
    lit: { quality: 'sun-washed temple-eave brightness', temperature: 'warm-toned', shadow: 'bracket shadows deepening the color bands' },
    ui: { background: 'temple cream', surface: 'danchu-banded headers with lotus corners', components: 'pattern-unit badges and eave-line dividers', motion: 'color bands unfurling along eave lines' },
  },
  {
    slug: 'pochampally-ikat',
    ctx: 'Pochampally, a weaving town in Telangana\'s Yadadri Bhuvanagiri district, is an icon of Indian double ikat: warp and weft yarns are tied and resist-dyed section by section before weaving, so pattern emerges only as threads cross on the loom. Its thousands of looms weave diamonds, elephants, lamps and flowers into hand-woven silk and cotton sarees — honored with a geographical indication tag in 2004 and a UNWTO best-tourism-village nomination.',
    vd: { shape: 'sari lengths with blurred diamond grids', line: 'feathered resist edges where dye meets undyed yarn', composition: 'chequerboard of diamonds alternating with figure panels', texture: 'silk sheen, dye-bleed halo, crisp loom beat' },
    typ: { display: 'tie-dyed display caps with haloed edges', body: 'neutral grotesque on handloom ivory' },
    lit: { quality: 'weaver-shed shafts of sun on dyed warp', temperature: 'warm-toned', shadow: 'warp threads striping thin moving shadows' },
    ui: { background: 'handloom ivory', surface: 'diamond-grid cards with haloed glyphs', components: 'motif swatches and GI-seal badges', motion: 'patterns resolving as threads cross, ikat-style' },
  },
  {
    slug: 'sambalpuri-ikat',
    ctx: 'Sambalpuri bandha is Odisha\'s handwoven double ikat, warp and weft tie-dyed before weaving in the districts around Sambalpur, Bargarh, Balangir, Boudh and Sonepur. Its saris bear motifs of deep Odia meaning — shankha conch, chakra wheel, phula flower — in the red, black and white linked to Lord Jagannath. Famous across India since the 1980s through Indira Gandhi\'s fondness for the cloth, bandha weaving remains a household handloom economy.',
    vd: { shape: 'sari borders and body fields of banded motifs', line: 'dotted resist outlines in conch and wheel forms', composition: 'wide bordered bands framing motif-scattered grounds', texture: 'soft cotton-silk hand, speckled dye halos, fine warp grain' },
    typ: { display: 'handloom display caps with resist-dye edges', body: 'warm text serif for Odia motifs' },
    lit: { quality: 'tropical window light across stretched warp', temperature: 'warm-toned', shadow: 'tie-knot shadows dotting the dyed yarn' },
    ui: { background: 'sari crimson', surface: 'banded-border cards with motif rows', components: 'conch-and-wheel icons and border swatches', motion: 'border bands sliding like a woven pallu' },
  },
  {
    slug: 'chikankari',
    ctx: 'Chikankari is Lucknow\'s white-on-white embroidery, long worked in and around the Nawabi city — the Chowk bazaar remains its main market. A dozen named stitches — murri knots, bakhiya shadow work, phanda, open jaali lattice — build tone-on-tone flowers and openwork on fine muslin, white thread catching white cloth in faint relief. The chikan kurta endures as North India\'s summer uniform, cool fabric carrying quiet ornament.',
    vd: { shape: 'flowing kurta and dupatta panels of airy muslin', line: 'whisper-fine white stitches in vine and bud outlines', composition: 'scattered butis drifting over open grounds', texture: 'embossed thread relief, sheer fabric glow, matte white-on-white' },
    typ: { display: 'nawabi flourish script caps in pearl white', body: 'airy light serif on unbleached muslin' },
    lit: { quality: 'soft high-key light with minimal contrast', temperature: 'cool-toned', shadow: 'stitch relief casting the faintest tone shifts' },
    ui: { background: 'muslin white', surface: 'embroidered cards with tone-on-tone relief', components: 'buti dot icons and jaali-lattice dividers', motion: 'stitch vines threading across the panel' },
  },
  {
    slug: 'phulkari',
    ctx: 'Phulkari — "flower work" — is the folk embroidery of Punjabi women, worked in darn stitch on the wrong side of coarse khaddar with floss silk so the long satin surface glows. Sparse stitching leaves a phulkari shawl with cloth showing; when the stitch covers every thread it becomes a bagh, a garden. Wedding and birth heirlooms in types such as chope, tilpatr and neelak, the shawls once moved with a bride from her mother\'s house to her new home.',
    vd: { shape: 'large draped shawls and headcloths', line: 'darning-stitch rays in strict diagonal counts', composition: 'hollyhock and chevron fields radiating over the drape', texture: 'floss-silk sheen, crisp khaddar tooth, stitch-direction shimmer' },
    typ: { display: 'Gurmukhi display caps in bright floss colors', body: 'warm humanist serif for Punjabi captions' },
    lit: { quality: 'golden winter sun on spread cloth', temperature: 'warm-toned', shadow: 'thread sheen shifting light across the drape' },
    ui: { background: 'khaddar ochre', surface: 'bagh-garden cards with floss-silk bloom', components: 'motif chips and darning-count borders', motion: 'stitch rows filling in like a garden growing' },
  },
  {
    slug: 'kashmiri-kashida',
    ctx: 'Kashida is the fine embroidery of the Kashmir valley, worked with needle and hooked aari on shawls, pashmina and crewel furnishings. Stitch by stitch, artisans build flowing vines, chinar leaves, almond buds and the boteh paisley that made Kashmir shawls coveted far beyond the Himalaya. Often a single stitch carried through a whole field, the dense-but-quiet ornament gives Kashmiri cloth its soft, painterly surface.',
    vd: { shape: 'shawl fields and long flowing border bands', line: 'sinuous vine curves with fine leaf-and-bud fills', composition: 'asymmetric sprays climbing toward dense borders', texture: 'flat fine stitches, wool-and-silk bloom, soft pashmina ground' },
    typ: { display: 'flowing nastaliq-inspired display caps', body: 'delicate serif with hand-drawn grace notes' },
    lit: { quality: 'diffused valley light through chinar leaves', temperature: 'cool-toned', shadow: 'stitch shadows barely denting the wool nap' },
    ui: { background: 'pashmina ivory', surface: 'vine-scroll cards with boteh corners', components: 'leaf-spray icons and border-band dividers', motion: 'vines growing across the panel like embroidery' },
  },
  {
    slug: 'kutch-mirror-work',
    ctx: 'Kutch mirror work — shisha — sets tiny mirror discs into the embroidery of Gujarat\'s pastoral and farming communities, from Kutch out to Rajasthan and Haryana. Tacked down with a buttonhole cage of stitched squares and triangles, each mirror throws back a pinpoint of desert light; crowded among flowers, peacocks and geometry on toran door hangings, chakla wall squares and bridal cloth, the glinting work turns garment and household into talisman.',
    vd: { shape: 'disc-set medallions on hangings and bodices', line: 'stitched cage frames of triangles and squares', composition: 'mirrors scattered like stars among dense motifs', texture: 'glass glint, raised satin stitching, coarse cotton ground' },
    typ: { display: 'hand-stitched display caps with mirror dots', body: 'cheerful rounded sans on bright grounds' },
    lit: { quality: 'fierce desert sun flashing off glass', temperature: 'warm-toned', shadow: 'mirror points scattering hard little sparks' },
    ui: { background: 'desert ivory', surface: 'mirror-set cards with stitch-cage frames', components: 'glint-dot badges and toran-border headers', motion: 'sparkle points winking as cards tilt' },
  },
  {
    slug: 'bengal-kantha',
    ctx: 'Kantha is Bengal\'s quilting art: worn-out saris stacked in layers and bound with thousands of running stitches until the cloth ripples softly and motifs bloom across the surface. Rural women stitched nakshi kantha quilts for dowries and cradles, filling borders with lotus ponds, fish, birds, trees and scenes of daily life, turning thrift into narrative. The same quilting now rides silk scarves and saris loved far beyond Bengal.',
    vd: { shape: 'quilted throws and drape-soft sari panels', line: 'dense running-stitch ripples and outlined figures', composition: 'central lotus or figure field ringed by story borders', texture: 'wavy quilted relief, soft washed cotton, thread shimmer' },
    typ: { display: 'hand-painted Bengali display caps', body: 'easy literary serif for story captions' },
    lit: { quality: 'soft overcast courtyard light', temperature: 'warm-toned', shadow: 'quilt ripples casting gentle wavy shadows' },
    ui: { background: 'washed cotton white', surface: 'quilt-rippled cards with stitched borders', components: 'lotus medallions and story-border headers', motion: 'running stitch rippling across as panels load' },
  },
  {
    slug: 'kasuti',
    ctx: 'Kasuti is Karnataka\'s counted-thread embroidery, worked without frame or traced pattern: counting the weave, women place up to five thousand tiny stitches to raise temple gopurams, palanquins, elephants, birds and lamps in crisp double-sided geometry. Traditionally worked on dark Ilkal saree and blouse cloth, its motifs read like a stitched village skyline, and the craft now carries a state-handicraft geographical indication.',
    vd: { shape: 'border bands and hem fields of counted motifs', line: 'stair-stepped stitch diagonals forming squared figures', composition: 'motifs marching along hems like a town skyline', texture: 'bead-tight cross-stitch relief, matte silk ground' },
    typ: { display: 'squared display caps echoing counted stitches', body: 'compact serif for pattern notes' },
    lit: { quality: 'even veranda daylight on stretched cloth', temperature: 'neutral with warm cast', shadow: 'stitch bumps rippling hair-thin shadows' },
    ui: { background: 'ilkal deep maroon', surface: 'hem-border cards with counted motifs', components: 'gopuram badges and stitch-count meters', motion: 'motifs placing one counted stitch at a time' },
  },
  {
    slug: 'sindhi-ajrak',
    ctx: 'Ajrak is Sindh\'s block-printed cloth and a flag of Sindhi identity, printed in deep crimson and indigo with white star-and-vine geometry. The resist method — successive mordant and resist blocks with dye vats and washes between stampings — builds mirror-symmetric fields finished in a spray of dots and cut across with bordered grids. Worn as turbans, shoulder cloths and gifts of honor in Sindh and Kutch, each ajrak reads as respect made visible.',
    vd: { shape: 'large symmetric shawl fields with bordered bands', line: 'crisp block-print outlines in star and vine repeats', composition: 'mirror-symmetric grids around a central medallion', texture: 'indigo-crimson depth, hand-stamp texture, dot-spattered finish' },
    typ: { display: 'block-stamped display caps in crimson and white', body: 'sturdy serif on indigo grounds' },
    lit: { quality: 'high-contrast sun on drying indigo cloth', temperature: 'cool-toned', shadow: 'printed dots casting minute relief shadows' },
    ui: { background: 'ajrak indigo', surface: 'crimson-star cards with block-print borders', components: 'star medallions and border-grid dividers', motion: 'block stamps pressing in sequence across the field' },
  },
  {
    slug: 'ralli-quilts',
    ctx: 'Ralli quilts are the layered textile art of Sindh and its borderlands — Kutch, Rajasthan, Bahawalpur — made by women from cloth saved and traded between households. Three known types — appliqué, patchwork and embroidered — stack bright cotton diamonds, stars and peacocks over laid quilting; motifs echo the region\'s ancient painted pottery, and mothers pass distinctive designs to daughters as inheritance, marking every rite of passage.',
    vd: { shape: 'bed-size quilts of layered local cotton', line: 'scissor-cut appliqué curves and pieced diamond edges', composition: 'bold medallion grids with border-on-border frames', texture: 'hand-quilted ripples, raw-edge appliqué, sun-faded brights' },
    typ: { display: 'folk appliqué display caps with cut edges', body: 'warm humanist sans on faded cotton' },
    lit: { quality: 'flat desert daylight on spread quilts', temperature: 'warm-toned', shadow: 'quilting lines dimpling soft shadows' },
    ui: { background: 'sun-faded cotton cream', surface: 'patchwork cards with quilted borders', components: 'diamond-patch chips and appliqué medallions', motion: 'patches assembling tile by tile like a quilt top' },
  },
]
