/**
 * Completeness patch r3k — Celtic/Iberian + Chinese textile and craft
 * traditions (20 entries). Hand-authored; facts spot-checked via Wikipedia
 * API (Celtic Revival, Harry Clarke, Aran jumper, Lovespoon, Filigree,
 * Portuguese pavement, Minho, Manila shawl, Peineta, Talavera de la Reina
 * pottery, Shibori, Persian carpet, Zellij, Boro, Suzhou/Xiang/Yue/Shu
 * embroidery, Yunjin).
 */
export const PATCHES: any[] = [
  {
    slug: 'celtic-revival-design',
    ctx: 'The Celtic Revival rekindled 19th- and 20th-century interest in Gaelic and Welsh literature and in insular art, the early medieval style of Ireland and Britain. Interlace, knotwork, spirals and the reintroduced Celtic cross carried from manuscripts into Arts and Crafts studios, stained glass and type; beside the Irish Literary Revival of Yeats and Lady Gregory, ornament became a language of national identity.',
    vd: { shape: 'circular high-cross heads and manuscript-page frames', line: 'endless interlace knotwork and triple spirals', composition: 'dense border panels around a central cross or initial', texture: 'carved stone and inked vellum line over flat color' },
    typ: { display: 'uncial-inspired display lettering with knotwork terminals', body: 'bookish serif for revival texts' },
    lit: { quality: 'clear manuscript-room daylight', temperature: 'cool-toned', shadow: 'deep relief shadow inside carved interlace' },
    ui: { background: 'aged vellum parchment', surface: 'interlace-border section frames', components: 'high-cross icon markers', motion: 'knotwork line-draw reveals' },
  },
  {
    slug: 'harry-clarke-stained-glass',
    ctx: 'Harry Clarke (1889–1931) was Dublin\'s stained-glass virtuoso and a leading figure of the Irish Arts and Crafts movement, his art informed by Art Nouveau, Art Deco and French Symbolism. His small panels blaze with jewel tones framing pale, elongated figures with tapering hands under ornamental canopies; his Poe book illustrations carry the same macabre elegance. Clarke\'s windows stand among the great achievements of the Celtic Revival.',
    vd: { shape: 'tall narrow window panels with slender robed figures', line: 'fine leadlines tracing elongated hands and tapering faces', composition: 'jewel-toned figure beneath a dense ornamental canopy', texture: 'acid-etched glass detail over flashed deep-hued panes' },
    typ: { display: 'art-nouveau lettering with elongated capitals', body: 'refined literary serif' },
    lit: { quality: 'backlit glass glow at full saturation', temperature: 'cool-toned', shadow: 'leadlines web dark across glowing color' },
    ui: { background: 'midnight cobalt glass wash', surface: 'stained-glass panel cards', components: 'canopy-arch tab tops', motion: 'light-through-glass color shifts' },
  },
  {
    slug: 'aran-knitting-tradition',
    ctx: 'The Aran jumper — geansaí Árann, the fisherman\'s gansey — takes its name from the Aran Islands off Ireland\'s west coast: an off-white báinín sweater knitted with cable panels down body and sleeves, originally in unscoured wool whose lanolin kept it water-resistant and wearable when wet. The idea that each cable spells a clan code is largely a 20th-century invention, but the dense patterned texture remains the emblem of Atlantic knitting.',
    vd: { shape: 'sweater body and sleeves built of vertical cable panels', line: 'twisted cables, honeycombs and zigzag ladders', composition: 'five to seven pattern panels running shoulder to hem', texture: 'bumpy unscoured wool with lanolin weight' },
    typ: { display: 'hearty roundhand knitspun caps', body: 'easy humanist sans' },
    lit: { quality: 'grey Atlantic daylight', temperature: 'cool-toned', shadow: 'cable ribs shade their own twists' },
    ui: { background: 'báinín off-white', surface: 'stitch-swatch cards', components: 'cable-ladder dividers', motion: 'knit-row tension ripples' },
  },
  {
    slug: 'welsh-lovespoon-carving',
    ctx: 'The Welsh lovespoon — llwy garu — is a wooden spoon decoratively carved and traditionally presented as a gift of romantic intent, its bowl, handle and linked decorations displaying symbols of love and the carver\'s skill. Intricate designs long retired it from the table, and it survives as a craft of courtship tokens: hearts, bells, keys, wheels and caged balls carved from a single piece of wood, hanging on Welsh walls as pledges of affection.',
    vd: { shape: 'spoon silhouette with carved bowl, handle and cage', line: 'deep pierced scrollwork and linked chain cuts', composition: 'love symbols stacked along the carved handle', texture: 'polished pale wood with knife-edged relief' },
    typ: { display: 'carved woodcut lettering with swash terminals', body: 'warm cottage serif' },
    lit: { quality: 'soft parlor lamplight', temperature: 'warm-toned', shadow: 'pierced cuts shadow the wall behind' },
    ui: { background: 'pale sycamore cream', surface: 'lovespoon plaque cards', components: 'heart-and-bell icon set', motion: 'spoon-turn hanging reveals' },
  },
  {
    slug: 'viana-heart-filigree',
    ctx: 'Viana do Castelo in Portugal\'s Minho is home of the coração de Viana — the heart-shaped gold and silver filigree jewel that crowns the region\'s festival dress. Portuguese filigree solders tiny beads and twisted threads into lace-like openwork, a metal art that flourished from the 17th century into the late 1800s; worn in showers over the lavradeira costume at romarias, the Viana heart is now a national shorthand for Portuguese jewellery.',
    vd: { shape: 'sacred-heart pendants crowned and rayed in openwork', line: 'twisted gold threads beaded into lace-like curls', composition: 'small hearts worn in showers of pins across the chest', texture: 'glinting filigree granulation on dark festival wool' },
    typ: { display: 'gold filigree-script display capitals', body: 'elegant Portuguese serif' },
    lit: { quality: 'festival sun flashing on gold', temperature: 'warm-toned', shadow: 'openwork casts lace shadows on cloth' },
    ui: { background: 'festival-red wool ground', surface: 'filigree-heart badge cards', components: 'gold-bead border ticks', motion: 'jewel-glint hover sheens' },
  },
  {
    slug: 'calcada-portuguesa',
    ctx: 'Calçada portuguesa is Portugal\'s hand-laid stone pavement: small white limestone and black basalt blocks set like mosaic into waves, rosettes, ships and saints across the sidewalks, squares and atriums of Portugal, Brazil and the former colonies, laid by specialist pavers called calceteiros, whose skill is even hired to Gibraltar. In town squares the art is at its deepest, Lisbon\'s wave grounds turning the street into monochrome graphic design.',
    vd: { shape: 'ground-plane fields of black and white stone figures', line: 'wave swirls and compass rosettes in hand-cut curves', composition: 'pictorial carpets stretched along sidewalks and squares', texture: 'worn limestone sheen against dark basalt contrast' },
    typ: { display: 'stone-set monochrome poster capitals', body: 'clean grotesque sans for signage' },
    lit: { quality: 'hard high-noon glare on pale stone', temperature: 'cool-toned', shadow: 'wet stone deepens every joint shadow' },
    ui: { background: 'limestone white with basalt black', surface: 'pavement-pattern banner strips', components: 'wave-border progress rails', motion: 'stone-tile step-in placements' },
  },
  {
    slug: 'traje-minhoto',
    ctx: 'The traje minhoto dresses Portugal\'s Minho, the green north that borders Galicia and shares its culture: the lavradeira costume of Viana do Castelo layers a richly embroidered skirt and apron over starched white petticoats, a silk headscarf and gold filigree earrings. Bright linen shawls served work days while gilded splendour belongs to festivals and romarias; its flowered embroidery bands make it Portugal\'s most exuberant regional dress.',
    vd: { shape: 'full skirt, starched petticoats and crossed shawl', line: 'brilliant flowered embroidery on skirt bands and aprons', composition: 'gold filigree at throat and ears over red-and-gold ground', texture: 'crisp linen, silk scarf sheen, dense gold weight' },
    typ: { display: 'festive script with banner ribbons', body: 'friendly rounded serif' },
    lit: { quality: 'procession afternoon sun', temperature: 'warm-toned', shadow: 'pleated skirts shade their own embroidery' },
    ui: { background: 'lavradeira red with gold accents', surface: 'embroidery-band header cards', components: 'scarf-knot corner accents', motion: 'skirt-swirl ribbon sweeps' },
  },
  {
    slug: 'manton-de-manila',
    ctx: 'The mantón de Manila is an embroidered silk shawl derived from the Philippine alampay, which travelled the colonial Manila trade to Spain and Latin America and became a 19th-century European fashion sensation. Its silk ground carries dense Chinese-style embroidery of peonies and blossoms in multicolored silk with long knotted fringe; knotted at the breast it dresses flamenco dancers, and hung on walls it becomes Spanish drawing-room tapestry.',
    vd: { shape: 'large square silk shawl gathered to a center point', line: 'satin-stitch peony sprays radiating from corners', composition: 'dense blossoms framing an open center, knotted fringe below', texture: 'liquid silk ground under raised multicolor embroidery' },
    typ: { display: 'flamenco poster lettering with fan flourishes', body: 'elegant fashion serif' },
    lit: { quality: 'stage spotlight through silk', temperature: 'warm-toned', shadow: 'fringe throws fine moving shadow lines' },
    ui: { background: 'ivory silk with blossom reds', surface: 'shawl-corner drape cards', components: 'fringe-knot tick details', motion: 'silk-swirl unfold transitions' },
  },
  {
    slug: 'peineta-comb',
    ctx: 'The peineta is Spain\'s great decorative comb: a convex body on a fan of long teeth that anchors it into a bun, worn to hold the mantilla lace veil at weddings, Holy Week processions, bullfights and flamenco. Once cut from tortoise shell, with Iberian evidence as early as the 5th century BCE, it flowered in 19th-century Spain and spread across the Hispanic world — from Buenos Aires\' giant peinetones to the Philippine payneta.',
    vd: { shape: 'high convex crest crowning a fan of long teeth', line: 'pierced shell and scroll openwork along the crown', composition: 'comb rising from the bun beneath sheer mantilla lace', texture: 'glossy shell-dark sheen with lace overlap' },
    typ: { display: 'graceful rococo script capitals', body: 'delicate didone serif' },
    lit: { quality: 'chapel candle glow through lace', temperature: 'warm-toned', shadow: 'comb crest shadows the lace above' },
    ui: { background: 'mantilla ivory lace field', surface: 'comb-silhouette profile cards', components: 'tooth-comb divider rules', motion: 'lace-drape settle transitions' },
  },
  {
    slug: 'talavera-de-la-reina-ceramics',
    ctx: 'Talavera de la Reina pottery is the tin-glazed faience of the Toledo town of Talavera de la Reina, a ceramics center reaching back to Roman-era finds that blossomed in the Renaissance into blue-and-white and polychrome majolica. Arcaded plates, apothecary jars and ewers carry birds, mythological scenes and florals in a lively Spanish-Mudéjar idiom; carried to New Spain, the style founded Puebla\'s celebrated Mexican talavera tradition.',
    vd: { shape: 'arcaded plates, apothecary jars and bulbous ewers', line: 'cobalt brush outlines around birds and mythic figures', composition: 'central medallion scene between calligraphic border bands', texture: 'glassy tin glaze with pooled blue brushwork' },
    typ: { display: 'cobalt majolica brush capitals', body: 'old-world workshop serif' },
    lit: { quality: 'bright kiln-room daylight', temperature: 'warm-toned', shadow: 'glaze highlights sharpen rim shading' },
    ui: { background: 'cream tin-glaze white', surface: 'blue-on-white tile cards', components: 'arcade-border frame rails', motion: 'glaze-brush stroke draw-ons' },
  },
  {
    slug: 'shibori',
    ctx: 'Shibori — from the Japanese verb shiboru, to wring, squeeze or press — is Japan\'s family of manual resist-dye techniques: cloth is bound, folded, stitched, clamped or plucked before dyeing, so the resist itself draws the pattern. Worked chiefly with indigo by regional schools from Arimatsu to Kyushu, its tiny puckered circles, kumo webs, folded grids and stitched landscapes made shibori the textured memory of Japanese rural dress.',
    vd: { shape: 'cloth worked into bound peaks, folds and pinch points', line: 'resist edges feathering between indigo and white', composition: 'allover small-pattern repeats across garment panels', texture: 'puckered dyed cotton with crackle and stitched ridges' },
    typ: { display: 'indigo brush-stroke display type', body: 'quiet minimal sans' },
    lit: { quality: 'dye-yard filtered daylight', temperature: 'cool-toned', shadow: 'fold creases keep pale resist shadows' },
    ui: { background: 'indigo vat blue', surface: 'shibori-swatch texture cards', components: 'stitch-bound accent chips', motion: 'dip-dye gradient reveals' },
  },
  {
    slug: 'persian-carpet',
    ctx: 'The Persian carpet is Iran\'s essential textile art, woven in parallel by nomadic tribes, village workshops and royal manufactories; the 16th-century Safavid ateliers of Isfahan set the artistic standard. Garden, medallion and hunting fields flow in arabesque over dense pile, with centers from Tabriz to Kashan keeping distinct repertoires; in 2010 the weaving skills of Fars and Kashan joined UNESCO\'s intangible heritage lists.',
    vd: { shape: 'rectangular field framed by wide ornamental borders', line: 'arabesque vines curling around a central medallion', composition: 'garden, medallion or hunting scenes in endless repeat', texture: 'dense clipped pile in madder red and lapis blue' },
    typ: { display: 'ornamental kufic-inspired display capitals', body: 'classic book serif for attribution text' },
    lit: { quality: 'warm bazaar lamp pools', temperature: 'warm-toned', shadow: 'pile direction shifts sheen and shade' },
    ui: { background: 'madder red ground', surface: 'carpet-border frame panels', components: 'medallion-rose nav markers', motion: 'vine-scroll parallax drifts' },
  },
  {
    slug: 'zellige',
    ctx: 'Zellige — also zellij or zillij — is the mosaic tilework of the western Islamic world, Morocco and al-Andalus: individually hand-chiseled pieces of glazed tile fitted into tessellations of radiating stars and interlacing polygons. Craftsmen cut enamel squares into many shapes and assemble them face-down into infinite geometric order, giving fountains, mihrabs, courtyards and palace walls their shimmering, perfectly fitted colour.',
    vd: { shape: 'hand-chiseled tile fragments of stars and polygons', line: 'crisp mosaic joints locking interlacing geometry', composition: 'radiating star tessellations across walls and fountains', texture: 'glazed enamel shimmer with chisel-matte edges' },
    typ: { display: 'angular geometric display type built from tile forms', body: 'simple modern sans for wayfinding' },
    lit: { quality: 'courtyard glare off glazed tiles', temperature: 'cool-toned', shadow: 'tile steps catch fine relief shadows' },
    ui: { background: 'glazed enamel green-blue', surface: 'tessellation-pattern section tiles', components: 'star-polygon icon badges', motion: 'tile-flip assembly transitions' },
  },
  {
    slug: 'boro',
    ctx: 'Boro — literally rags — is the mending culture of rural Japan: farming and fishing households, above all in snowy Tohoku, stitched layer upon layer of indigo-dyed scraps over worn garments and futons until the cloth became a map of generations of repair. Coarse white running stitches, square patches and graded fading blues turn humble patched fabric into an aesthetic of thrift and endurance, now collected worldwide as textile wabi-sabi.',
    vd: { shape: 'layered rectangles patching jacket and futon grounds', line: 'rows of coarse white running stitches in grid ranks', composition: 'indigo scrap mosaic densest at points of wear', texture: 'sanded indigo cotton with frayed edges and quilt ridges' },
    typ: { display: 'stencil-dyed workwear lettering', body: 'plain utilitarian sans' },
    lit: { quality: 'low winter lamplight in farmhouse dark', temperature: 'cool-toned', shadow: 'patch layers shadow like sediment strata' },
    ui: { background: 'faded indigo navy', surface: 'patchwork stitch cards', components: 'sashiko-dash progress marks', motion: 'patch-stitch layer builds' },
  },
  {
    slug: 'su-embroidery',
    ctx: 'Su embroidery — Su xiu, of Suzhou in Jiangsu — is the most representative of China\'s four great embroideries, with a history of more than 2,000 years. Famous for its variety of stitches, elegant colours and beautiful patterns, its signature is double-sided embroidery: gossamer silk floss, split into fine filaments, renders cats, goldfish and lotus with painterly shading that reads identically on both faces of translucent silk.',
    vd: { shape: 'framed silk panels of cats, goldfish and lotus', line: 'hair-fine split-silk strokes following fur and vein', composition: 'one image reading on both faces of sheer silk', texture: 'satin-sheen floss with painterly colour gradation' },
    typ: { display: 'refined brush-script display type', body: 'graceful old-style serif' },
    lit: { quality: 'soft north-window studio light', temperature: 'warm-toned', shadow: 'thread angles shade like brush washes' },
    ui: { background: 'silk-ivory ground', surface: 'double-sided panel cards', components: 'thread-split hover accents', motion: 'stitch-fill painting reveals' },
  },
  {
    slug: 'xiang-embroidery',
    ctx: 'Xiang embroidery, from Changsha in Hunan, is the most dramatic of China\'s four great embroidery styles — a folk art rooted in Chu culture and included in the country\'s first national intangible cultural heritage list in 2006. Working silk thread in layered realistic shading with a high sense of reality, it favours lions and tigers whose fur bristles stitch by stitch alongside bold birds and flowers, needlework so alive it seems to roar.',
    vd: { shape: 'large-panel beasts — lions, tigers, eagles — mid-stride', line: 'bristle-true fur strokes built hair by hair', composition: 'one powerful animal centred on open ground', texture: 'dense silk-thread pile with realistic shading' },
    typ: { display: 'bold brush display capitals', body: 'strong humanist serif' },
    lit: { quality: 'dramatic side light on thread pile', temperature: 'warm-toned', shadow: 'fur strokes throw their own micro-shadows' },
    ui: { background: 'ochre silk field', surface: 'beast-portrait hero cards', components: 'claw-stroke divider marks', motion: 'fur-bristle stagger reveals' },
  },
  {
    slug: 'yue-embroidery',
    ctx: 'Yue embroidery — Guangdong embroidery of the Pearl River Delta and Chaozhou — is the brightest of China\'s four great embroideries, full in composition and vivid in colour. Its subtropical world of abundant flora and fauna supplies the motifs: the beloved Hundred Birds with flowers, fruits, dragons and phoenixes, worked in satin floss, gold and silver thread, bead embroidery and woolen needlepoint on screens, dress and shoes.',
    vd: { shape: 'hanging screens crowded with birds over flowers', line: 'bright satin fills with gold-couched busy outlines', composition: 'hundred-bird profusion filling every corner', texture: 'lustrous floss with metallic thread glints' },
    typ: { display: 'gilded festival display lettering', body: 'bright friendly serif' },
    lit: { quality: 'subtropical bright daylight', temperature: 'warm-toned', shadow: 'gold couching casts crisp glint shadows' },
    ui: { background: 'canton vermillion', surface: 'bird-and-flower motif chips', components: 'gold-thread border rules', motion: 'bird-flit stagger animations' },
  },
  {
    slug: 'shu-embroidery',
    ctx: 'Shu embroidery — from Sichuan and Chongqing — is the fourth of China\'s great embroidery traditions, from a region long famous for silk: Chengdu\'s Shu brocade reaches back to the ancient kingdom of Shu, and Western Han tombs at Chengdu yielded looms proving early mastery of figured weaving. Worked in fine, even stitches on soft satin grounds, it renders lotus, carp, pandas and cranes with a smooth satin-stitch sheen prized for screens and dress.',
    vd: { shape: 'satin-ground panels of lotus, carp and cranes', line: 'fine even satin stitches smoothing each petal', composition: 'single emblem worked large on soft plain silk', texture: 'slick satin sheen with razor-neat stitch faces' },
    typ: { display: 'slender brush-stroke display lettering', body: 'clean scholarly serif' },
    lit: { quality: 'even studio light on satin', temperature: 'cool-toned', shadow: 'stitch direction shades petals subtly' },
    ui: { background: 'pale satin blush', surface: 'emblem-panel cards', components: 'stitch-gradient hover fills', motion: 'satin-sheen sweep transitions' },
  },
  {
    slug: 'nanjing-yunjin-brocade',
    ctx: 'Nanjing yunjin — cloud brocade — is China\'s most luxurious silk, shuttle-woven in Nanjing since the end of the Song dynasty on weft-weaving techniques inherited from Tang and Song, with gold and silver thread worked among coloured silks. Ming weavers added swivel methods for figured colour on satin, and the brocade that clothed emperors rises like relief on its ground; in 2009 UNESCO inscribed the craft as intangible heritage of humanity.',
    vd: { shape: 'broad brocade lengths of dragon medallions and cloud bands', line: 'weft gold threads couched into raised relief contours', composition: 'clouds spiralling beneath five-clawed imperial dragons', texture: 'heavy silk with raised gold-weft shimmer' },
    typ: { display: 'imperial seal-script inspired display type', body: 'dignified classical serif' },
    lit: { quality: 'treasury lamplight on gilt thread', temperature: 'warm-toned', shadow: 'gold wefts shadow into raised relief' },
    ui: { background: 'imperial cloud-blue', surface: 'brocade-band header strips', components: 'cloud-scroll divider motifs', motion: 'gold-weft shimmer sweeps' },
  },
  {
    slug: 'song-brocade',
    ctx: 'Song brocade is Suzhou\'s classic silk weave, named for the Song-dynasty taste it revived: fine compact patterns of small florals, lattices and auspicious symbols in muted, harmonious colours. Supple rather than splendid, it was woven for court garments and, above all, for mounting paintings and covering books, where its quiet elegance frames brushwork — one of the trio of historic Chinese brocades beside yunjin and Shu brocade.',
    vd: { shape: 'compact woven panels of small florals and lattices', line: 'fine warp-faced geometry framing tiny emblem repeats', composition: 'muted border bands designed to frame paintings and books', texture: 'supple silk with a quiet low-sheen surface' },
    typ: { display: 'scholarly song-typeface display headers', body: 'refined bookish serif' },
    lit: { quality: 'soft scroll-mounting table light', temperature: 'warm-toned', shadow: 'flat weave keeps shadows minimal' },
    ui: { background: 'aged rice-paper cream', surface: 'brocade-mount frame rails', components: 'lattice-corner accents', motion: 'scroll-mount slide reveals' },
  },
]
