/**
 * Completeness patch r2b — Architectural Style batch (20 entries).
 * Hand-authored from verified entry identities; no LLM involvement.
 */
export const PATCHES: any[] = [
  {
    slug: 'blobitecture',
    ctx: 'Blobitecture ("blob architecture") names the curvilinear buildings of the late 1990s-2000s made possible by CAD software and CATIA-era structural engineering — Greg Lynn\'s "blob wall" theory, Frank Gehry\'s Guggenheim Bilbao (1997), Future Systems\' Selfridges Birmingham (2003) — where amorphous, biomorphic skins replaced plan-driven geometry. Critics debated whether blobs were the end of architecture or its computational dawn; the term (from Warren Chalk\'s 1960s "blob" sketch, revived by Lynn) stuck as shorthand for software-born form.',
    vd: { shape: 'amorphous continuous skins without corner logic', composition: 'building as single sculptural gesture', line: 'seamless panel jointing tracking curves', texture: 'titanium panel ripple, sprayed insulation, glass double curvature' },
    typ: { display: 'none', body: 'minimal wayfinding strips on glass', notes: 'form replaces ornament entirely' },
    lit: { quality: 'rippling reflected sky', temperature: 'cool-toned', shadow: 'curves smear shadow into gradients' },
    ui: { background: 'sky-reflection gradient', surface: 'curved-panel cards', components: 'seam-flow dividers', motion: 'blob-morph easing loops' },
  },
  {
    slug: 'biophilic-design',
    ctx: 'Biophilic design — E.O. Wilson\'s "biophilia" (1984) turned architectural doctrine — integrates nature into buildings for measurable wellbeing: Singapore\'s Parkroyal and Oasia hotels with planted sky terraces, Milan\'s Bosco Verticale, Amazon Spheres, plus the 14-pattern framework (Browning/Ryan/Clancy, 2014) codifying views of nature, natural materials, light rhythms and airflow. Green-building economics (productivity, recovery speed) made it policy; the aesthetic reads as architecture surrendering its edges to living systems.',
    vd: { shape: 'terraced planting planes dissolving building edges', composition: 'green ramps weaving through structural grids', line: 'organic vine trails over rational frames', texture: 'living foliage, warm timber, moss-flecked stone, water sheen' },
    typ: { display: 'soft humanist sans wayfinding', notes: 'species-name labels like botanical plates' },
    lit: { quality: 'canopy-dappled interior daylight', temperature: 'warm-toned', shadow: 'leaf shade flickers over finishes' },
    ui: { background: 'foliage green gradient', surface: 'planted-terrace cards', components: 'leaf-motif toggles', motion: 'breeze-sway ambient loops' },
  },
  {
    slug: 'mamluk-architecture',
    ctx: 'Mamluk architecture (1250-1517) — Cairo\'s Golden Age — built the densest concentration of medieval Islamic monuments anywhere: Sultan Hasan\'s four-iwan madrasa-mosque, Qalawun\'s hospital complex, and the domed-and-minareted funerary khanqahs lining Qarafa\'s "City of the Dead". Signature elements: ablaq striped masonry, octagonal minarets with carved balconies, red-and-cream stone joggling, crested dome profiles and blue mosaic marquetry. It expressed a military-caste patronage competitive in piety and scale until the Ottoman conquest annexed the style.',
    vd: { shape: 'towering pishtaq portals, crested stone domes, tiered minarets', composition: 'street-corner mausoleum complexes on curved urban sites', line: 'ablaq black-white banding, joggled voussoirs', texture: 'carved stone arabesque, gold mosaic lunettes, marble marquetry dados' },
    typ: { display: 'monumental thuluth foundation inscriptions', notes: 'waqf deeds carved in full on facades' },
    lit: { quality: 'Nile-dust golden hour', temperature: 'warm-toned', shadow: 'portal recesses cut hard urban shade' },
    ui: { background: 'ablaq stripe field', surface: 'carved-stone cards', components: 'minaret-balcony dividers', motion: 'muqarnas cascade reveals' },
  },
  {
    slug: 'huizhou-merchant-houses',
    ctx: 'Huizhou merchant houses (Ming-Qing Anhui province) — white-washed horse-head walls over dark timber frames — were the homes of the salt-and-pawn bankers whose Hui merchants guild financed them: multi-story courtyard houses (tian jing skywells) that funnelled light and rain ("four waters return to the hall" = wealth retained), carved brick gate facades (menlou), and family hierarchy encoded in hall placement. Xidi and Hongcun villages are UNESCO-listed; the white-wall/black-tile image became "Anhui style" and China\'s ink-painting architecture.',
    vd: { shape: 'two-story courtyard boxes crowned by stepped horse-head gables', composition: 'skywell center stacking light down into halls', line: ' stepped gable walls above tiled slopes', texture: 'limewashed brick, dark carved wood, slate tile shadow' },
    typ: { display: 'brick-carved menlou gate inscriptions', notes: 'calligraphy couplets on hall columns' },
    lit: { quality: 'skywell-square overhead light', temperature: 'cool-toned', shadow: 'courtyard walls shade with drawn blind lines' },
    ui: { background: 'limewash white', surface: 'carved-brick cards', components: 'gable-step dividers', motion: 'rain-curtain skywell loop' },
  },
  {
    slug: 'tibetan-monastery-architecture',
    ctx: 'Tibetan monastery architecture — Potala\'s white-and-red mass over Lhasa, Labrang\'s prayer-wheel lanes, Ganden\'s ridge-line colleges — fused Chinese, Indian and Nepali craft into fortress-spiritual complexes: thick sloping stone walls with black trapezoidal trapezoid trapez window trims, flat roofs with timber parapets, chörtens (stupas), and prayer halls lit by butter lamps. Monasteries were city-states of learning and politics until 1959; rebuilding since preserves the trapezoid-shadow aesthetic now global through Himalayan diaspora temples.',
    vd: { shape: 'trapezoid-windowed sloping wall masses in stacked terraces', composition: 'white abbot wings, red chapel cores, gold roof shrines', line: 'black window trims repeating as pattern band', texture: 'whitewashed granite, red ochre walls, hammered gold roofs' },
    typ: { display: 'gold-on-red Tibetan u-chen fascia lettering', notes: 'prayer flags as moving text' },
    lit: { quality: 'high-altitude glare, butter-lamp interiors', temperature: 'warm-toned', shadow: 'trapezoid trims cast deep window shade' },
    ui: { background: 'monastery white', surface: 'red-ochre cards', components: 'chörten-bump dividers', motion: 'prayer-wheel spin loops' },
  },
  {
    slug: 'vietnamese-nguyen-architecture',
    ctx: 'Nguyễn Dynasty architecture (1802-1945) — Hue\'s imperial citadel, royal tombs (Tu Duc, Khai Dinh) and the Forbidden Purple City — fused Vietnamese timber carpentry with Qing Chinese axial planning and French colonial touches: purple-glazed tile roofs, dragon-cornice ironwood frames, inlaid mother-of-pearl interiors and Khai Dinh\'s mosaic-frenzied concrete-vented tomb. UNESCO-listed Complex of Hue Monuments survives war and typhoon as Vietnam\'s imperial memory palace.',
    vd: { shape: 'stacked courtyard temples along dragon-axis routes', composition: 'harmonious hall-typology rows within citadel walls', line: 'upturned dragon-ridge eaves', texture: 'purple glazed tiles, lacquered ironwood, mother-of-pearl inlay shimmer' },
    typ: { display: 'Sino-Vietnamese chữ Hán plaque boards', notes: 'poem panels lacquered over hall doors' },
    lit: { quality: 'Perfume River humid glow', temperature: 'warm-toned', shadow: 'eave curves shade veranda edges' },
    ui: { background: 'imperial purple', surface: 'tile-ridge cards', components: 'dragon-rail dividers', motion: 'boat-procession slow pan' },
  },
  {
    slug: 'trullo',
    ctx: 'The trulli of Alberobello (Puglia, UNESCO 1996) — dry-stone cone-roofed huts built without mortar — served tax avoidance (demountable structures evaded building levies) and practical climate, whitewashed cylinders capped by stacked limestone courses topped with whitewash-and-symbol pinnacles: sun wheels, heart piercings, primitive crosses painted by roof-masons. Thousands survive as dwellings, shops and Masseria stays; the conical skyline is Italy\'s most distinctive vernacular landscape.',
    vd: { shape: 'cylindrical whitewashed drums under corbelled cones', composition: 'clustered hive groups on terraced lanes', line: 'cone-course spiral rhythm, whitewashed symbols at tips', texture: 'chiseled limestone, limewash brush, moss between stones' },
    typ: { display: 'household initials painted on cone tips', notes: 'mason symbols as protective marks' },
    lit: { quality: 'Mediterranean high noon', temperature: 'warm-toned', shadow: 'cones cast circular noon shadows' },
    ui: { background: 'limewash white', surface: 'cone-course cards', components: 'symbol-paint badges', motion: 'stone-corbel assembly build' },
  },
  {
    slug: 'ethiopian-rock-hewn-churches',
    ctx: 'Ethiopia\'s rock-hewn churches — Lalibela\'s eleven (12th-13th c., UNESCO), carved down into living rock as a "New Jerusalem", plus Tigray\'s cliff churches (Debre Damo, Abuna Yemata reachable only by cliff climb) — are monolithic sacred architecture unmatched anywhere: Bete Giyorgis cut as a Greek cross pit-church, columns, windows and drainage carved in one act of subtraction. Priests still serve;pilgrims fill the trenches at Genna and Timkat. The architecture proves Ethiopian Christianity\'s 1,600-year continuity.',
    vd: { shape: 'cross-shaped voids cut downward into red tuff', composition: 'trench-labyrinth linking church courts', line: 'Axumite-style window and cornice carving', texture: 'raw tuff grain, soot-darkened interiors, brass cross glints' },
    typ: { display: 'Ge\'ez inscriptions cut in jambs', notes: 'parchment manuscripts as liturgical interior text' },
    lit: { quality: 'trench shadow to sunken interior glow', temperature: 'warm-toned', shadow: 'the rock itself is the shadow' },
    ui: { background: 'tuff red-brown', surface: 'carved-cross cards', components: 'trench-path dividers', motion: 'descend-into-rock scroll' },
  },
  {
    slug: 'mississippian-platform-mound',
    ctx: 'The Mississippian platform mound (900-1600 CE) — Cahokia\'s Monks Mound (largest earthen structure in the Americas: 30m high, 290m long), Moundville, Etowah — staged Mississippian cosmology: flat-topped earthen pyramids bearing temples and elite residences above plazas, aligning solstice sunrises and ranking society vertically. Built basket-load by basket-load, they anchored the Southeastern Ceremonial Complex\'s "Southern Cult" iconography; surviving mounds are tribal nations\' heritage landmarks and archaeological climate records.',
    vd: { shape: 'stepped earthen pyramids with ramp approaches', composition: 'mound-around-plaza sacred precinct plans', line: 'sod-layer stratigraphy exposed in profiles', texture: 'grassy earth, clay pan surface, palisade post shadows' },
    typ: { display: 'none', body: 'shell gorgets and copper plates as iconographic text', notes: 'cosmology spoken in mound geometry' },
    lit: { quality: 'solstice-aligned dawn glare', temperature: 'warm-toned', shadow: 'mound faces shade toward plaza at sunrise' },
    ui: { background: 'prairie green', surface: 'earth-step cards', components: 'sun-alignment markers', motion: 'processional ramp ascent' },
  },
  {
    slug: 'dutch-colonial-architecture',
    ctx: 'Dutch Colonial architecture — from the Hudson Valley\'s gambrel-roofed farmhouses (1730s) to Batavia\'s canals, Cape Town\'s warehouses and Curaçao\'s Willemstad gables — carried Dutch practicality worldwide: brick walls, stepped or neck gables, deep eaves, and the American gambrel that gave "Dutch Colonial Revival" (1890s-1930) its barn-like suburban coziness. New Amsterdam street plans survive in lower Manhattan; Willemstad\'s Handelskade is UNESCO-listed Caribbean Dutch.',
    vd: { shape: 'wide gambrel roofs over brick rectangles', composition: 'stoop-fronted facades on short street frontages', line: 'stepped gable courses, curved gambrel eaves', texture: 'ironspot brick, lime mortar, painted shutters, deep-swing doors' },
    typ: { display: 'date-stone numerals set in gables', notes: 'family initials in anchor-plate ironwork' },
    lit: { quality: 'low canal-reflected light', temperature: 'cool-toned', shadow: 'gambrel eaves shade long stoops' },
    ui: { background: 'brick red-brown', surface: 'gambrel-roof cards', components: 'gable-step dividers', motion: 'stoop-door swing open' },
  },
  {
    slug: 'khrushchyovka',
    ctx: 'The khrushchyovka — Nikita Khrushchev\'s prefab five-story concrete apartment blocks (1957-1964) — housed millions moving into Soviet cities, ending communal flats with standardized one-room-to-three-room units at socialist cost: low ceilings, tiny kitchens ("Khrushchev was determined to cook on two burners"), walk-up stairs, and panel joints that whistled in wind. Maligned then, they are now heritage-adjacent — photogenic in golden-hour panels, studied as the largest housing experiment ever, and still home to tens of millions across the former USSR.',
    vd: { shape: 'repeating five-story panel slabs, window-grid regular', composition: 'courtyard blocks with breathing strips between', line: 'panel-seam horizontals and window rhythm', texture: 'prefab concrete wash, painted-over panel streaks, balcony cage lattice' },
    typ: { display: 'street-number plaques and address stencils', notes: 'shopfront signs at block bases' },
    lit: { quality: 'low winter-panel sun', temperature: 'cool-toned', shadow: 'projecting panel frames stripe facades' },
    ui: { background: 'panel grey-beige', surface: 'window-grid cards', components: 'stair-block dividers', motion: 'elevator-cage vertical scroll' },
  },
  {
    slug: 'central-asian-muqarnas',
    ctx: 'The muqarnas — honeycomb vaulting of stacked niche cells — reached sculptural perfection in Central Asian masterworks: Samarkand\'s Gur-e Amir and Bibi-Khanym portals, Bukhara\'s Balyand Mosque, the Shah-i-Zinda necropolis. Reading from below as dripping stalactites or frozen crystal, muqarnas dissolve the corner between square room and dome (squinch evolution), while gilded terracotta versions (Bukhara) made entire portal half-domes into suspended gardens of light. The geometry is modular craft: unit cells (kitab) assembled by master builders from pattern books.',
    vd: { shape: 'tiered stalactite cells cascading in 3D tiers', composition: 'portal squinches and dome drums as showcase fields', line: 'cell-edge rhombic grids radiating', texture: 'gilded terracotta, glazed turquoise cells, shadow depth between tiers' },
    typ: { display: 'calligraphic bands wrapping muqarnas tiers', notes: 'inscriptions flow around the honeycomb' },
    lit: { quality: 'portal-shaded glitter, gilded cell catch', temperature: 'warm-toned', shadow: 'each cell casts onto the tier below' },
    ui: { background: 'ultramarine field', surface: 'gold-cell cards', components: 'niche-stack loaders', motion: 'honeycomb cascade build-up' },
  },
  {
    slug: 'vesara-hoysala-style',
    ctx: 'The Hoysala style (1026-1343) — Vesara hybrid of Dravida and Nagara — built Karnataka\'s most intricate temples: Belur\'s Chennakesava, Halebidu\'s Hoysaleswara, Somnathpura\'s Keshava — on star-shaped (16-24 point) platforms, with chloritic schist so fine it carves like wood: friezes of elephants, horses and myth literally wrapping bases, lathe-turned pillars, and scalloped towers. soapstone allowed hundreds of deities in single registers; UNESCO-listed in 2023, the style is medieval Karnataka\'s signature.',
    vd: { shape: 'star-platform plans multiplied into stellate towers', composition: 'frieze-band registers wrapping the star perimeter', line: 'horizon friezes under scalloped moldings', texture: 'soapstone polish, lathe pillar flutes, mini-figure density' },
    typ: { display: 'Old Kannada donative inscriptions on slabs', notes: 'mason signatures carved beneath friezes' },
    lit: { quality: 'Deccan plateau hard light', temperature: 'warm-toned', shadow: 'star-point shadows rotate through day' },
    ui: { background: 'soapstone grey-green', surface: 'frieze-band cards', components: 'star-plan badges', motion: 'frieze-figure procession slide' },
  },
  {
    slug: 'kashan-merchant-houses',
    ctx: 'Kashan\'s merchant houses (Tabatabaei, Borujerdi, Ameri — 1800s carpet-trade fortunes) are Iran\'s desert domestic showpieces: sunken courtyards (howz) with reflecting pools, windcatcher-cooled summer and winter wings, badgir-topped rooflines, and mirror-work, fresco and carved stucco interiors where merchants displayed silk-road wealth within Islamic privacy. The houses\' reception rooms (panj-dari, golestan) hosted trade negotiations; today they operate as boutique hotels — the grand Persian house as living heritage.',
    vd: { shape: 'courtyard-centered wings, sunken garden floors', composition: 'badgir skylines over inward-facing privacy', line: 'arch-and-mihrab niche rhythm in iwans', texture: 'fresco pastel, mirror-mosaic glitter, carved stucco lace' },
    typ: { display: 'stucco calligraphy panels over summer iwans', notes: 'poetry quatrains framing doorways' },
    lit: { quality: 'courtyard-filtered desert glare', temperature: 'warm-toned', shadow: 'iwan depth cools shade into blue' },
    ui: { background: 'rose-desert cream', surface: 'mirror-work cards', components: 'howz-pool dividers', motion: 'windcatcher-breeze ripple' },
  },
  {
    slug: 'ksar-architecture',
    ctx: 'The ksour (plural ksar) — fortified mudbrick villages of Morocco\'s Drâa and Ziz valleys and southern Algeria — stack family towers (igherman) within defensive walls around palm-oasis economy: Aït Benhaddou (UNESCO, film-starred in Gladiator and Game of Thrones), Tinghir, Ghardaïa\'s M\'zab pentad. Collective granaries (agadir), sumptuous gates and earthen repair cycles made ksar life communitarian; rural exodus emptied many, and earthen-architecture conservation programs now train artisans in the original mud-lime craft.',
    vd: { shape: 'tower-clusters within circuit walls on hill spurs', composition: 'narrow medina lanes radiating from gates', line: 'crowned wall walks, pointed tower crenels', texture: 'rammed earth and pisé, straw-flecked render, palm-lintel ends' },
    typ: { display: 'none', body: 'carved door lintel blessings', notes: 'lineage spoken through tower heights' },
    lit: { quality: 'Sahara-edge incandescent noon', temperature: 'warm-toned', shadow: 'towers shade the lanes by half day' },
    ui: { background: 'pisé ochre', surface: 'tower-cluster cards', components: 'gate-arch frames', motion: 'palm-shade dapple drift' },
  },
  {
    slug: 'brick-gothic',
    ctx: 'Brick Gothic (Backsteingotik) — the North German and Baltic adaptation of Gothic where stone was absent — built Lübeck\'s Holstentor, Gdańsk\'s St. Mary\'s (largest brick church on earth), Stralsund and Rostock townscapes from the Hanseatic trade\'s clay: glazed brick color fields, stepped gables, tiered towers, and tracery translated into molded brick. The style defined the "Hanseatic" look across Germany, Poland and the Baltics; UNESCO cities (Lübeck, Stralsund-Wismar, Toruń) preserve its austere skyline.',
    vd: { shape: 'massive hall-church volumes with stepped gables and tower ladders', composition: 'market-square frontages balancing civic and sacred', line: 'molded-brick tracery, glazed diamond patterning', texture: 'clinker brick skin, black-glazed accents, lime mortar courses' },
    typ: { display: 'glazed-brick heraldic shields and donor marks', notes: 'Latin inscriptions in molded-brick bands' },
    lit: { quality: 'Baltic overcast silver', temperature: 'cool-toned', shadow: 'stepped gables stair-shadow down facades' },
    ui: { background: 'clinker red-brown', surface: 'brick-tracery cards', components: 'gable-step dividers', motion: 'galleon-trade sail drift' },
  },
  {
    slug: 'manierismo-toscano',
    ctx: 'Tuscan Mannerism — the anti-classical riposte of Michelangelo\'s followers — stretched Renaissance rules into virtuoso discomfort: Ammannati\'s courtyard at Palazzo Pitti, Buontalenti\'s grottoes and Boboli garden facades, Vasari\'s Uffizi corridor, rustic-stone rustication gone wild, splayed keystones, dropping swag pediments and broken cornices. Giorgio Vasari theorized it as grazia and difficultia; the style\'s engineered weirdness became the ground-plan of Baroque drama while remaining recognizably Florentine in its stone craft.',
    vd: { shape: 'deliberately destabilized classical elements', composition: 'theatrical garden-courtyard stagings', line: 'broken pediments, splayed keys, telescoped orders', texture: 'rough rusticated stone against polished portico, grotto shell-encrustation' },
    typ: { display: 'engraved motto panels in cartouche frames', notes: 'grotesque-mask spouts as punctuation' },
    lit: { quality: 'gallery-courtyard raking light', temperature: 'warm-toned', shadow: 'rustication throws deep stone shadow' },
    ui: { background: 'pietra serena grey', surface: 'grotto-texture cards', components: 'broken-pediment dividers', motion: 'grotesque-mask reveal winks' },
  },
  {
    slug: 'moorish-revival',
    ctx: 'Moorish Revival — 19th-century Europe and America rebuilding the Alhambra — produced synagogues (Berlin\'s Oranienburger Straße, Budapest\'s Dohány, Cincinnati\'s Plum Street), railway stations, casinos and pleasure gardens in horseshoe arches, honeycomb vaults, azulejo fields and minaret towers. For Jewish congregations the style evoked Golden-Age Sephardic Spain; for entertainers it packaged exotic leisure. The style\'s most photographed survivors (Granada\'s cafés, Sarajevo\'s Vijećnica) tie Victorian exoticism to 21st-century memory politics.',
    vd: { shape: 'horseshoe and multifoil arches under ribbed domes', composition: 'courtyard facades with paired minaret flanks', line: 'stalactite corbels and alfiz frames', texture: 'polychrome zellige tiles, carved stucco lace, walnut mashrabiya' },
    typ: { display: 'kufic-style decorative bands over entrances', notes: 'Hebrew and Arabic letterforms sharing ornament logic' },
    lit: { quality: 'lantern-filtered courtyard glow', temperature: 'warm-toned', shadow: 'multifoil arches print lace shadow' },
    ui: { background: 'zellige blue-green', surface: 'stucco-lace cards', components: 'horseshoe-arch frames', motion: 'fountain-ripple reflections' },
  },
  {
    slug: 'stick-style',
    ctx: 'Stick Style (1860-1890) — Vincent Scully\'s named "transitional" American style — exposed the building\'s skeleton as ornament: diagonal stickwork trusses, angle brackets, king posts and trusses patterned across sheathing, as if to declare the timber frame through the wall. Represented by Woodward\'s First Methodist (Salem), the Emlen House and hundreds of Queen Anne cousins, it linked Gothic Revival honesty to Shingle Style simplification, and remains the American suburb\'s most carpenter-legible historic style.',
    vd: { shape: 'steep gables with applied stickwork trusses and brackets', composition: 'facade as exploded frame diagram', line: 'diagonal and vertical stick grids, corner boards', texture: 'flat siding sheathing, sawn trim, jig-sawn ornament' },
    typ: { display: 'carved house-name boards at porches', notes: 'date-and-initial brackets at gable peaks' },
    lit: { quality: 'crisp northern daylight', temperature: 'warm-toned', shadow: 'stickwork throws fretted shadow on sheathing' },
    ui: { background: 'sheathing tan', surface: 'stick-grid cards', components: 'truss-diagonal accents', motion: 'frame-exposure toggle reveal' },
  },
]
