/**
 * Completeness patch r5c — 20th-century movements + painting schools (20).
 * Hand-authored (Task 5-c); facts Wikipedia-API-verified; no LLM involvement.
 * Fills ctx + visualDNA + typography + lighting + uiTranslation.
 */
export const PATCHES: any[] = [
  {
    slug: 'wpa-printmaking',
    ctx: 'WPA printmaking is the poster and print output of the Federal Art Project (1935–1943), the New Deal program under the Works Progress Administration led by Holger Cahill. The largest Federal Project Number One effort, it sustained some 10,000 artists during the Depression, established more than 100 community art centers, and ran poster and graphic-arts divisions turning silkscreen and lithography into cheap, boldly communicative images.',
    vd: { shape: 'poster sheets, mural studies and portfolio prints in flat public formats', line: 'bold stencil contours cut for silkscreen and linoleum blocks', composition: 'stacked slogan bands over simplified worker, farm and city figures', texture: 'flat screenprint ink with visible drag and registration grit' },
    typ: { display: 'condensed poster sans in thick slab weights, WPA placard style', body: 'utilitarian grotesque in high-contrast black on newsprint cream' },
    lit: { quality: 'flat poster light across silk-screened sheets', temperature: 'workshop-warm reds and ochers', shadow: 'ink solids sitting printed-flat, casting no relief' },
    ui: { background: 'newsprint cream with poster ink black', surface: 'silkscreen-flat panels in federal blue and poster red', components: 'stencil badge buttons and slogan banner rules', motion: 'poster sheets flipping like a community-center display rack' },
  },
  {
    slug: 'direct-carving',
    ctx: 'Direct carving — taille directe — is the early twentieth-century approach in which the sculptor cuts the finished work straight from the block, with no intermediate model or maquette, often working from memory. Prominent from the early 1900s and read as a return to the directness of primitive art, it demands truth to materials: veining, color changes and flaws revealed while cutting are kept and honored as features of the piece.',
    vd: { shape: 'block-born volumes keeping the mass of the parent stone or trunk', line: 'tool paths left honest — chisel flats, adze gouges, claw marks', composition: 'single figures discovered within the block, not imposed on it', texture: 'raw quarried and weathered surfaces breathing beside polished passes' },
    typ: { display: 'chiseled capitals with lapidary, stone-cut proportions', body: 'quiet humanist serif like museum sculpture labels' },
    lit: { quality: 'north-light studio sun raking across the block', temperature: 'cool stone neutral', shadow: 'chisel recesses holding crisp dark edges' },
    ui: { background: 'limestone block grey', surface: 'rough-chiseled cards beside polished marble panels', components: 'chisel-tip cursors and truth-to-materials toggles', motion: 'block mass revealing a form as chips fly' },
  },
  {
    slug: 'constructivist-sculpture',
    ctx: 'Constructivist sculpture grows from Constructivism, founded in Russia in 1915 by Vladimir Tatlin and Alexander Rodchenko. Abstract and austere, it rejected decorative stylization for the industrial assemblage of real materials, aiming to reflect modern industrial society and urban space. Aligned with the Soviet avant-garde and art for social purposes, it helped shape the Bauhaus, De Stijl and much of twentieth-century sculpture and design.',
    vd: { shape: 'cantilevered frames, towers and open reliefs of real materials', line: 'diagonal struts and taut wires shooting through empty space', composition: 'engineered intersections of beam, rod and plane like a factory model', texture: 'bare sheet metal, wood and wire — industrial, unadorned, matte' },
    typ: { display: 'bold geometric sans set on diagonals, constructivist placard style', body: 'clean functional grotesque in black and industrial red' },
    lit: { quality: 'hard industrial hall light from high clerestories', temperature: 'neutral steel-cool', shadow: 'open frameworks throwing lattice shadows' },
    ui: { background: 'industrial red on black steel', surface: 'open-frame panels of rods, planes and wires', components: 'diagonal strut dividers and gimbal-style controls', motion: 'towers assembling themselves beam by beam' },
  },
  {
    slug: 'kinetic-sculpture',
    ctx: 'Kinetic sculpture makes movement — real or apparent — part of the work. Early milestones include Duchamp\'s Bicycle Wheel (1913), Naum Gabo\'s motor-driven Kinetic Construction (1920) and Moholy-Nagy\'s Light-Space Modulator (1930); Calder moved from motors to air currents. The 1955 exhibition Le Mouvement at Galerie Denise René in Paris — with Calder, Tinguely, Soto, Vasarely and Agam — made kinetics international, Tinguely its machine-builder.',
    vd: { shape: 'mobiles, spinning vanes and motor-driven machine assemblages', line: 'wire arms and blades sweeping arcs through the air', composition: 'balanced pivots staging movement, shadow and reflected light', texture: 'painted sheet metal and wire gleaming as blades rotate' },
    typ: { display: 'geometric sans with optical-motion letterforms like Vasarely prints', body: 'neutral modernist sans for gallery wall texts' },
    lit: { quality: 'gallery spots tracking moving blades', temperature: 'warm metal mixed with cool air', shadow: 'rotating shadows sweeping the wall' },
    ui: { background: 'gallery white under moving shadow', surface: 'rotor-dial cards and pivot-hinged panels', components: 'spin sliders and mobile menus balancing like Calder arms', motion: 'blades orbiting continuously at idle' },
  },
  {
    slug: 'assemblage',
    ctx: 'Assemblage is the three-dimensional cousin of collage: three-dimensional elements — found objects prominent among them — project from a defined substrate, and the term also covers free-standing works assembled from real things. Twentieth-century artists raised it into a full artistic form and medium, letting the street and scrapheap enter art as material, with meaning accumulating from the objects themselves and their histories.',
    vd: { shape: 'found-object reliefs and freestanding stacks of real castoffs', line: 'edges and silhouettes determined by the scavenged things themselves', composition: 'accumulated clusters where each object keeps its identity', texture: 'rusted tin, worn wood, frayed cord — surfaces with former lives' },
    typ: { display: 'salvage-yard stencil caps mixed with commercial serif scraps', body: 'workmanlike slab serif like object inventory sheets' },
    lit: { quality: 'uneven studio light pooled over relief shelves', temperature: 'scrapyard rust-warm', shadow: 'projecting objects casting hard cutout shadows' },
    ui: { background: 'workbench plywood tan', surface: 'collage-relief cards of layered scraps', components: 'pinned-object chips and salvage-bin palettes', motion: 'found pieces snapping together into place' },
  },
  {
    slug: 'driftwood-sculpture',
    ctx: 'Driftwood sculpture builds art from wood washed ashore by winds, tides and waves — branches, roots and timbers softened by salt, sun and the chewing of gribbles and shipworms. No two pieces arrive alike, so the maker reads each find\'s curl, grain and silvered surface, then assembles and joins them into figures, birds and abstractions — beachcombing turned studio practice, deferring to the shoreline\'s patient weathering.',
    vd: { shape: 'branch and root figures built from curled, tide-worn timbers', line: 'grain lines and erosion ridges following the wood\'s own growth', composition: 'beachcombed finds balanced into beasts, birds and abstractions', texture: 'silvered, salt-bleached wood softened by sand and brine' },
    typ: { display: 'weathered driftwood-silver caps with tide-rounded terminals', body: 'soft organic serif in beach-stone neutrals' },
    lit: { quality: 'open beach daylight, salt-hazed and even', temperature: 'bleached silver over warm driftwood heart', shadow: 'eroded hollows shading soft grey' },
    ui: { background: 'sea-washed bone white', surface: 'silvered driftwood-grain cards', components: 'tide-line tags and branch-node connectors', motion: 'waves of grain drifting through panels' },
  },
  {
    slug: 'trompe-l-il-revival',
    ctx: 'The trompe-l\'œil revival renewed the old French art of "deceiving the eye" — painting so convincing that viewers take painted objects and spaces for real — as a late twentieth-century public art. American muralist Richard Haas (born 1936), its leading figure, wrapped blank building walls in architectural illusion, while painted windows, arcades and ceilings returned to lobbies as witty, popular realism.',
    vd: { shape: 'flat walls opened into fake windows, doors, arcades and skylines', line: 'architectural edges ruled to a single site-correct viewpoint', composition: 'illusion anchored to real cornices, sills and street sightlines', texture: 'smooth enamel-fine paint denying any trace of the brush' },
    typ: { display: 'classical incised romans pretending to be carved in stone', body: 'refined old-style serif like a painted sign panel' },
    lit: { quality: 'site daylight matched exactly to the painted scene', temperature: 'matched to the street or interior being faked', shadow: 'painted shadows angled to the wall\'s real sun' },
    ui: { background: 'plaster wall pretending to be stone', surface: 'painted-niche frames and false-door panels', components: 'windows opening onto painted rooms', motion: 'curtains of the illusion settling at load' },
  },
  {
    slug: 'chinese-social-realism',
    ctx: 'Chinese social realism is the heroic figurative style adapted from Soviet socialist realism — official doctrine of the USSR from 1932 and later of other socialist countries — made China\'s dominant art language after 1949. Organized around "depicting reality in its revolutionary development," it presents workers, peasants and soldiers in idealized, clearly narrated scenes of collective purpose, in robust academic drawing and warm legible color.',
    vd: { shape: 'heroic full figures and grouped tableaux at monument scale', line: 'firm academic contour and modeled drawing with no ambiguity', composition: 'low-horizon hero placements under clear revolutionary light', texture: 'smooth blended oil handling with poster-bright saturation' },
    typ: { display: 'sturdy brush-derived songti display heads, upright and square', body: 'clear readable sans with printed-poster evenness' },
    lit: { quality: 'bright ideological spotlight from upper left', temperature: 'healthy warm sun over rose cheeks', shadow: 'minimal and softened so no face falls dark' },
    ui: { background: 'poster red field under a morning-gold sky', surface: 'monumental hero panels in healthy warm tones', components: 'banner headlines and badge-star buttons', motion: 'figures marching forward in a parade scroll' },
  },
  {
    slug: 'wiener-werkstatte',
    ctx: 'The Wiener Werkstätte — "Vienna Workshop" — was founded in 1903 by Koloman Moser, Josef Hoffmann and patron Fritz Waerndorfer, uniting architects, artists, designers and artisans in one association. Dedicated to artistic utilitarian objects in the spirit of the Gesamtkunstwerk, it worked in silver, metalwork, ceramics, fashion, furniture, bookbinding, jewelry and graphic art, pioneering modern design with influence reaching the Bauhaus.',
    vd: { shape: 'square-sectioned metalwork, boxy furniture and geometric textiles', line: 'right-angle grids, dense small repeats and thin axial rules', composition: 'total-work-of-art ensembles where every object shares the grid', texture: 'polished silver, hand-hammered facets, printed silk and leather' },
    typ: { display: 'geometric display capitals on strict square grids, WW workshop style', body: 'sachplakat-plain sans with crafted letter spacing' },
    lit: { quality: 'even vitrine light on polished metalwork', temperature: 'warm silver over black and gold', shadow: 'faceted squares stepping light across the surface' },
    ui: { background: 'black, white and gold workshop grid', surface: 'square-panel cards with fine axial rules', components: 'grid-locked buttons and monogram tags', motion: 'pattern tiles rotating on the workshop grid' },
  },
  {
    slug: 'showa-modern',
    ctx: 'Shōwa modern names the design culture of Japan\'s Shōwa era (1926–1989), above all its interwar and early postwar decades, when cosmopolitan urban life, jazz-age café interiors, cinema, advertising and imported European modernism fused with Japanese craft. After wartime devastation, occupation-era exchange and rapid rebuilding carried the modern idiom into homes, print and product design — sleek geometry meeting tactile tradition.',
    vd: { shape: 'streamlined containers, café fittings and slim print formats', line: 'clean modernist geometry softened by hand-drawn brush accents', composition: 'asymmetric layouts pairing kanji display with Roman captions', texture: 'rough matte papers, lacquer sheen, tin and bentwood surfaces' },
    typ: { display: 'mincho-modern display with deco contrast and short descenders', body: 'gothic humanist sans pairing kanji and romaji cleanly' },
    lit: { quality: 'café lamp glow over tin and lacquer', temperature: 'mocha-warm with neon accents', shadow: 'soft interior pooling like a cinema lobby' },
    ui: { background: 'warm cream paper with deco rules', surface: 'lacquer and tin cards in muted café tones', components: 'vertical kanji labels beside roman captions', motion: 'neon-sign flicker greeting at open' },
  },
  {
    slug: 'hague-school',
    ctx: 'The Hague School is the group of artists who lived and worked in The Hague between 1860 and 1890, heavily influenced by the realist painters of the French Barbizon school. Working largely before the motif around town, polder and the Scheveningen fishing shore, they favored relatively sombre colors — muted greys, greens and browns beneath heavy Dutch skies — an outlook so consistent that the group is sometimes called the Grey School.',
    vd: { shape: 'low-horizon polder and shore panels under towering Dutch skies', line: 'soft wet-into-wet contours dissolving into humid atmosphere', composition: 'small figures and cattle dwarfed by cloud and water space', texture: 'silvery grey-green paint dragged over warm umber grounds' },
    typ: { display: 'bookish old-style serif caps with silvered ink weathering', body: 'calm text serif in umber-grey on soft paper' },
    lit: { quality: 'heavy overcast Dutch daylight through damp air', temperature: 'silver-grey with umber warmth', shadow: 'soft wet reflections dissolving the horizon' },
    ui: { background: 'silvery umber-grey like wet sand', surface: 'low-horizon cards under broad painted skies', components: 'cloud-heavy headers and moored-boat chips', motion: 'tide creeping slowly across the footer' },
  },
  {
    slug: 'dusseldorf-school-of-painting',
    ctx: 'The Düsseldorf School of painting refers to painters who taught or studied at the Düsseldorf Academy (today the Staatliche Kunstakademie Düsseldorf) roughly between 1819 and 1918, first directed by Wilhelm von Schadow. The academy became one of nineteenth-century Europe\'s major art schools, drawing international students and sending closely finished, story-rich landscape and genre painting across Germany, America and beyond.',
    vd: { shape: 'cabinet-scale landscapes and genre scenes with deep receding space', line: 'crisp academic drawing threading narrative through the scene', composition: 'theatrical vistas with storyteller figures staged mid-episode', texture: 'fine enamelled oil surfaces with glazes in the shadows' },
    typ: { display: 'nineteenth-century German textura display caps with engraved flourish', body: 'roman text serif like academy exhibition catalogs' },
    lit: { quality: 'clear academic daylight in the academy studio', temperature: 'golden romantic evening tones', shadow: 'deep glazed browns inside ruined architecture' },
    ui: { background: 'academy oxblood and parchment', surface: 'catalogue cards with engraved plate frames', components: 'chapter numerals and story-caption plates', motion: 'pages of a leather album turning' },
  },
  {
    slug: 'norwich-school',
    ctx: 'The Norwich school of painters was the first provincial art movement established in Britain, active in the early nineteenth century. Inspired by the natural environment of the Norfolk landscape and owing some influence to Dutch Golden Age landscapists such as Hobbema and Ruisdael, its members painted local rivers, marshes and big skies with direct observation, making the region itself the serious subject of art.',
    vd: { shape: 'broad Norfolk river, marsh and heath canvases in tidal light', line: 'gentle tonal contours traced around reeds, dykes and cattle', composition: 'big sky over low fen horizons, river bends leading the eye', texture: 'luminous thin oil washes over warm-toned grounds' },
    typ: { display: 'regency-era serif caps with fine hairline serifs like exhibition catalogs', body: 'gentle georgian serif in warm sepia ink' },
    lit: { quality: 'broad fenland sky light over tidal flats', temperature: 'pale gold against cooler grey greens', shadow: 'tree masses shading cool against wet marsh' },
    ui: { background: 'broad-sky pale blue over marsh green', surface: 'riverbend cards with tidal-flat margins', components: 'reed-rule dividers and skylight headers', motion: 'clouds crossing slowly over the page' },
  },
  {
    slug: 'multi-layer-glazing-depth',
    ctx: 'Multi-layer glazing depth is the oil painter\'s method of building color and space from thin transparent veils. A glaze is a thin transparent or semi-transparent layer that modifies the paint beneath it — shifting chroma, value, hue and texture while carrying little pigment in rich medium such as linseed oil. Layer over dried layer, translucent shadow and luminous color deepen into interior light opaque paint cannot reach.',
    vd: { shape: 'deep panel and canvas space built in stacked translucent veils', line: 'edges that glow where successive glazes lap over one another', composition: 'underpainted shadow cores radiating through colored glaze layers', texture: 'glassy oil film with almost no visible trace of brushwork' },
    typ: { display: 'luminous serif caps with layered jewel-toned fill and thin outline', body: 'classic old-style serif on translucent tinted panels' },
    lit: { quality: 'light entering the paint film and glowing back out', temperature: 'warm luminous depths under cool glazes', shadow: 'transparent shadow you can see color through' },
    ui: { background: 'deep translucent crimson over warm umber', surface: 'glass-panel cards layered like dried glazes', components: 'luminous gradient buttons with shadow cores', motion: 'color deepening as layers settle in' },
  },
  {
    slug: 'scumbling-broken-color',
    ctx: 'Scumbling is glazing\'s opaque twin: a light, opaque coat brushed on very thinly so bits of the paint below shine through, mixing colors optically by the same principle the pointillists used. Where painters most often glaze with dark colors, scumbling favors lighter ones — especially atmospheric effects like fog and clouds — and the broken, half-hiding film lets forms breathe out of the ground with air and shimmer.',
    vd: { shape: 'atmospheric passages where forms emerge half-veiled from the ground', line: 'dry-brushed broken edges letting underlayers flicker through', composition: 'light caught in mist, cloud and bloom over darker foundations', texture: 'rough speckled film dragging across the tooth of the canvas' },
    typ: { display: 'dry-brushed display serif with broken, feathered stroke edges', body: 'soft humanist serif on misted pale grounds' },
    lit: { quality: 'diffused atmospheric light caught in a dry film', temperature: 'pale chalky coolness', shadow: 'half-lights where the underlayer mutes the shadow' },
    ui: { background: 'misty chalk white with faint underlayer glow', surface: 'dry-brushed cards with broken pigment film', components: 'feathered-edge toggles and soft cloud headers', motion: 'fog lifting to reveal content beneath' },
  },
  {
    slug: 'alla-prima-directness',
    ctx: 'Alla prima — Italian for "at first attempt," also called wet-on-wet, direct painting or au premier coup — is painting finished at one sitting, wet layers applied into wet layers beneath. Used mostly in oils, it demands speed and decision: the work must be complete before the first strokes dry. Every touch stays fresh, edges stay lively, and the canvas records one continuous, direct encounter with the subject.',
    vd: { shape: 'single-session canvases with forms stated in one decisive pass', line: 'wet strokes laid into wet, edges fused while the paint moves', composition: 'spontaneous arrangement preserved exactly as first blocked in', texture: 'buttery wet-into-wet ridges with color mixed right on the canvas' },
    typ: { display: 'single-stroke brush caps with wet, confident endings', body: 'spontaneous humanist sans with quick, open forms' },
    lit: { quality: 'one sustained sitting of natural studio light', temperature: 'true to the hour the painting was made', shadow: 'wet reflections keeping shadows alive and transparent' },
    ui: { background: 'primed canvas warm white', surface: 'single-session sketch cards with wet-edge highlights', components: 'one-stroke buttons and fresh-palette swatches', motion: 'strokes completing in a single confident pass' },
  },
  {
    slug: 'grisaille-underpainting',
    ctx: 'Grisaille is painting executed entirely in shades of black and grey, or of another neutral greyish color. It serves many ends: decorative schemes in imitation of sculpture, models for engravers — Rubens and his school sketched compositions in monochrome for engravers — and, above all, underpainting: a monochrome foundation laid in preparation for glazes of color over it, grey bones beneath centuries of luminous flesh.',
    vd: { shape: 'monochrome figures and shadow fields in stone-grey oil', line: 'modeled light-to-dark folds reading as carved relief', composition: 'grey bones of a composition awaiting colored glazes above', texture: 'smooth neutral passages calibrated to receive translucency' },
    typ: { display: 'engraved stone-grey capitals modeled in light and shade', body: 'neutral book serif ready to receive color glazes' },
    lit: { quality: 'monochrome daylight like a marble court', temperature: 'strictly neutral greys', shadow: 'shadow carrying all the form, no color to hide in' },
    ui: { background: 'stone-grey value scale', surface: 'monochrome panels awaiting a color pass', components: 'value-step sliders and glaze-ready frames', motion: 'color washing over grey like a revealed glaze' },
  },
  {
    slug: 'palette-knife-impasto-courtauld-era',
    ctx: 'Palette-knife impasto belongs to the nineteenth-century European lineage — the French Impressionist and Post-Impressionist works the Courtauld Gallery is known for — in which paint is laid on thickly enough that the brush or painting-knife strokes stay visible, mixed right on the canvas. When dry, impasto provides real texture: paint appears to come out of the canvas, each loaded stroke catching actual light.',
    vd: { shape: 'thick paint masses standing proud of the canvas surface', line: 'loaded knife strokes with sharp leading edges and dragged tails', composition: 'form built stroke by stroke, each mark a color decision', texture: 'ridged impasto catching real light like low relief' },
    typ: { display: 'impasto-smeared display caps with palette-knife pulled edges', body: 'nineteenth-century bookman serif on gallery cream' },
    lit: { quality: 'side light raking across paint ridges', temperature: 'vivid impressionist warmth', shadow: 'each impasto ledge casting a tiny real shadow' },
    ui: { background: 'gallery cream with paint-ridge texture', surface: 'impasto cards with knife-pulled edges', components: 'loaded-stroke buttons and pigment-swatch chips', motion: 'paint dragging thickly as panels arrive' },
  },
  {
    slug: 'egg-tempera',
    ctx: 'Egg tempera is the permanent, fast-drying panel medium of the Renaissance: pigment mixed with a water-soluble binder, usually glutinous egg yolk. Thin translucent passes are hatched and layered over gesso, building crisp, luminous color that dries almost at once — a patience art far removed from soft "poster tempera." Fine hatching and long-setting glazes give it the jewel-like, famously durable surfaces of old panels.',
    vd: { shape: 'gesso panels with mirror-fine ground and incised setting lines', line: 'fine crossed hatch builds replacing any broad blending', composition: 'gold-leafed halos and architectural grounds framing the figures', texture: 'chalky gesso under crisp yolk glaze, satin and age-cracked' },
    typ: { display: 'gilded roman capitals with fine hatched highlights', body: 'delicate renaissance-era serif on gesso white' },
    lit: { quality: 'candle-and-daylight evenness of a panel altarpiece', temperature: 'gold-ground warmth over cool flesh', shadow: 'hatched shadow lines cross-accumulating into tone' },
    ui: { background: 'gesso white with faint warm undertone', surface: 'panel cards with gold-leaf headers', components: 'hatched dividers and incised-line frames', motion: 'fine hatch lines building tone stroke by stroke' },
  },
  {
    slug: 'acrylic-pouring',
    ctx: 'Acrylic pouring is the fluid-art side of pouring — the artistic technique of paint pouring noted alongside kitchen and trade uses of the act — using fast-drying acrylic paint: pigment suspended in acrylic polymer emulsion, thinned with water, gels and mediums until it flows. Tilted and layered across a surface, colors marble, ribbon and cell into one another, trading the brushstroke for pools and lacing gravity draws.',
    vd: { shape: 'edge-to-edge pools and cells flowing past the canvas rim', line: 'ribboned veins and lacing where differing densities push apart', composition: 'marbled color fields with no center, horizon or focal point', texture: 'glossy resin-smooth film with cell rims and skin wrinkles' },
    typ: { display: 'fluid rounded display letters that drip and pool at the baseline', body: 'airy geometric sans on bright pour-white grounds' },
    lit: { quality: 'even studio light trapped under a glassy film', temperature: 'saturated neon-to-deep-sea range', shadow: 'cell rims darkening like tidepool edges' },
    ui: { background: 'pour-white with neon ribbon veins', surface: 'cell-pattern cards with glossy resin finish', components: 'drip-edge buttons and marbled chips', motion: 'colors oozing and blooming at load' },
  },
]
