/**
 * Completeness patch r5a — Art movements (20): Western/Japanese avant-garde, contemporary
 * social/digital currents, and Japanese/Chinese/Indian classical painting & craft traditions.
 * Hand-authored (Task 5-a); facts Wikipedia-API-verified; no LLM involvement.
 * Fills ctx + visualDNA + typography + lighting + uiTranslation.
 */
export const PATCHES: any[] = [
  {
    slug: 'de-stijl',
    ctx: 'De Stijl — \'The Style\' — was a Dutch art movement founded in 1917 in Leiden, where Theo van Doesburg began the journal that spread its theories. With Mondrian, van der Leck, Rietveld and Oud, its theory — Neoplasticism — reduced painting and architecture to orthogonal lines, right angles and three primaries balanced by black, white and grey, seeking universal harmony after World War I. Rietveld\'s Red and Blue Chair took the idiom into furniture.',
    vd: { shape: 'flat rectangular planes, grids and right-angled open frames', line: 'strictly horizontal and vertical orthogonal rules, never diagonal', composition: 'asymmetric balance of large and small primary color blocks', texture: 'flat matte paint on machine-smooth planes, no brushwork' },
    typ: { display: 'geometric square-cut lettering in the spirit of Theo van Doesburg\'s block alphabet', body: 'clean neutral grotesque sans with generous white space' },
    lit: { quality: 'even studio daylight flattening color to pure hue', temperature: 'neutral', shadow: 'hard orthogonal shadows aligned to the grid' },
    ui: { background: 'chalk white canvas', surface: 'blocks of primary red, yellow and blue with black rules', components: 'rectangle tiles and right-angle dividers', motion: 'crisp snap transitions locking elements into the grid' },
  },
  {
    slug: 'magic-realism',
    ctx: 'Magic realism presents the world with dense, matter-of-fact realism while magical elements slip in as ordinary fact. As the critic Luis Leal explained, its aim is not to evoke wonder but to express emotion, using the impossible to make a point about reality — distinct from fantasy. Born in interwar European painting criticism, it found its fullest home in Latin American letters, the marvelous reported with a documentarian\'s flat voice.',
    vd: { shape: 'ordinary rooms and figures occupied by quiet impossible details', line: 'painstaking realist contour drawing around uncanny subjects', composition: 'documentary stillness with one marvel centered in plain view', texture: 'smooth enamel finish, minute detail, dreamlike evenness' },
    typ: { display: 'bookish literary serif with ornate initials for chapters', body: 'classic text serif set for long, enveloping prose' },
    lit: { quality: 'luminescent twilight brushing against the prosaic', temperature: 'warm-toned', shadow: 'soft edges where the impossible melts into the real' },
    ui: { background: 'aged parchment with faint narrative grain', surface: 'illustrated panels framed like novel plates', components: 'chapter markers and marginalia notes', motion: 'slow reveals, wonders arriving with deadpan calm' },
  },
  {
    slug: 'tachisme',
    ctx: 'Tachisme, from the French tache, stain, is the French school of abstract painting popular in the 1940s and 1950s, first used in this sense around 1951. Europe\'s counterpart to abstract expressionism within the wider Art Informel current, it abandoned geometry for intuitive stains and flung color — also called Abstraction lyrique — and after World War II often stood for the School of Paris. Wols, Dubuffet, Soulages and Hartung led the field.',
    vd: { shape: 'clouded fields of pigment punctured by sudden blot accents', line: 'splashed, scratched and trailed marks with no fixed outline', composition: 'all-over drift of stains, dense center breathing to the edges', texture: 'wet-on-wet bleeding, impasto ridges, ragged paint skins' },
    typ: { display: 'gestural script-like display with brushed, spattered terminals', body: 'quiet neutral sans giving the stains room' },
    lit: { quality: 'raking gallery light over uneven impasto', temperature: 'warm-toned', shadow: 'cracks and ridges casting painterly micro-shadows' },
    ui: { background: 'raw off-white canvas ground', surface: 'stain-washed cards with torn pigment edges', components: 'ink-blot buttons and drag-stroke dividers', motion: 'paint blooming and pooling like a dropped tache' },
  },
  {
    slug: 'gutai',
    ctx: 'The Gutai Art Association, founded in Ashiya in 1954 under Jirō Yoshihara, took gutai — concrete — against abstract and figurative art, fusing painting, performance and raw matter: Kazuo Shiraga wrestled pigment with his feet, Atsuko Tanaka wore blinking electric dresses. Yoshihara urged members to \'create what has never been done before\'; exchanging with Michel Tapié and Europe\'s Zero and Nul, the group ran until soon after his death in 1972.',
    vd: { shape: 'flung pigment fields, slashed paper and body-scale surfaces', line: 'violent gesture trails, foot-dragged arcs, burst-open seams', composition: 'action-centered formats staging raw matter in open space', texture: 'caked impasto, sprayed paint, industrial raw-material grit' },
    typ: { display: 'rough marker or brush display with urgent hand-stroke terminals', body: 'plain industrial gothic for manifesto texts' },
    lit: { quality: 'raw outdoor daylight on unrehearsed action', temperature: 'warm-toned', shadow: 'bodily shadows thrown across wet, gleaming pigment' },
    ui: { background: 'tarp grey of open-air venues', surface: 'punch-through cards with burst edges', components: 'gestural badges and body-trail cursors', motion: 'splashes, bursts and feet-drawn arcs animating on tap' },
  },
  {
    slug: 'nouveau-realisme',
    ctx: 'Nouveau Réalisme was founded in 1960 by Pierre Restany and Yves Klein at a first show in Milan\'s Apollinaire gallery; that October nine signed the constitutive declaration in Klein\'s workshop — Arman, Spoerri, Tinguely and the torn-poster affichistes Dufrêne, Hains and Villeglé among them. César, Rotella and Niki de Saint Phalle soon joined, pressing urban castoffs — torn posters, compressed metal, junk — into art; the group dissolved in 1970.',
    vd: { shape: 'accumulated real objects: poster shreds, blocks, compressed slabs', line: 'torn, rent edges of street posters stretched over structure', composition: 'collage fields built from ready-made urban fragments', texture: 'layered paper tear, rusted metal, industrial found surfaces' },
    typ: { display: 'decollaged display lettering pieced from torn poster strips', body: 'workmanlike grotesque sans like trade signage' },
    lit: { quality: 'hard Parisian street light, flat and factual', temperature: 'neutral', shadow: 'crisp paper-lift shadows under torn layers' },
    ui: { background: 'pasted-over hoarding grey', surface: 'torn-paper cards with lifted, sun-bleached edges', components: 'fragment chips and compression-block buttons', motion: 'posters ripping away to reveal the layer beneath' },
  },
  {
    slug: 'mono-ha',
    ctx: 'Mono-ha — usually translated \'School of Things\' — names a late-1960s movement of Japanese and Korean artists, theorized in Lee Ufan\'s writing and crystallized in Nobuo Sekine\'s Phase—Mother Earth (1968). Practitioners set natural and industrial materials — stone, steel, glass, light bulbs, wood, earth, water — mostly unaltered and ephemeral, caring less for objects than for the interdependency of things and their surrounding space.',
    vd: { shape: 'raw blocks, slabs and poles balanced in measured constellations', line: 'gravity-plumb lines, edges left unworked and unaligned', composition: 'few elements placed so each measures the space around it', texture: 'unpolished stone, oxidizing steel, damp earth, cordage fiber' },
    typ: { display: 'sparse mono-weight display with wide, unornamented letterforms', body: 'quiet neo-grotesque with airy line spacing' },
    lit: { quality: 'dim gallery light treating materials just as they are', temperature: 'cool-toned', shadow: 'material shadows pooled where things meet the floor' },
    ui: { background: 'bare concrete grey', surface: 'stone-and-steel cards with raw edges', components: 'weight-indexed blocks and taut rope dividers', motion: 'elements settling slowly as if finding balance' },
  },
  {
    slug: 'transavantgarde',
    ctx: 'Transavantgarde — literally beyond the avant-garde — is the Italian face of neo-expressionism, named by Achille Bonito Oliva at Aperto \'80, Venice Biennale. Against conceptual art\'s dematerialization, Chia, Clemente, Cucchi and Paladino revived painting itself: large figurative images alive with mythic symbols, hot color and rediscovered emotion — joy above all. Through the 1980s their canvases carried drawing, fable and craft back to the center.',
    vd: { shape: 'sturdy monumental figures and emblem-like beasts', line: 'confident expressive contour with thick, reworked edges', composition: 'theater-stage arrangements of mythic symbols in shallow space', texture: 'raw canvas showing through oily, layered expressive strokes' },
    typ: { display: 'painterly display serif with irregular, hand-retooled letterforms', body: 'warm humanist serif for essayistic wall texts' },
    lit: { quality: 'stagey warm spotlight like an opera set', temperature: 'warm-toned', shadow: 'dramatic figural shadows at the picture edge' },
    ui: { background: 'fresco-plaster terracotta', surface: 'canvas-textured cards with drawn borders', components: 'mythic emblem icons and brush-stroke toggles', motion: 'figures striding in with bold painted ease' },
  },
  {
    slug: 'glitch-art',
    ctx: 'Glitch art makes beauty from digital or analog error, corrupting data or manipulating electronic devices so failure becomes image. The lineage runs from Len Lye\'s A Colour Box (1935) and Nam June Paik\'s TV Magnet (1965) through Digital TV Dinner (1978) to the net.art of JODI, who crashed their own site to expose raw code. Databending and datamoshing spread through new media circles; the GLI.TC/H conference convened in Chicago in 2010.',
    vd: { shape: 'smeared scanlines, split pixel blocks and torn image bands', line: 'stair-stepped datamosh trails and jagged compression seams', composition: 'familiar imagery broken by abrupt horizontal displacement', texture: 'pixel noise, banding, phosphor smear, chunky macroblocking' },
    typ: { display: 'corrupted display type with sliced, offset glyphs and dead-pixel gaps', body: 'monospaced terminal sans exposing raw code' },
    lit: { quality: 'CRT glow with sudden channel-skip flashes', temperature: 'cool-toned', shadow: 'afterimage ghosting instead of true shadow' },
    ui: { background: 'black screen with faint scanline texture', surface: 'misregistered cards with RGB channel splits', components: 'databent buttons and checksum error badges', motion: 'stutter, datamosh smears and sudden frame drops' },
  },
  {
    slug: 'bio-art',
    ctx: 'Bioart works at the seam of art and the life sciences: artists use live tissues, bacteria and living organisms with microscopy, tissue culture, genetic engineering and cloning, in labs, galleries or studios. Peter Weibel\'s 1981 essay \'Biotechnology and Art\' introduced the term, and as the practice matured at the turn of the millennium each experiment became an ethical and social question too — what counts as alive, and who may engineer it.',
    vd: { shape: 'vessel forms: petri dishes, flasks, growth-scaffold grids', line: 'fine filament and capillary lines branching like specimens', composition: 'specimen-slide framing of living matter under inspection', texture: 'translucent membranes, colony bloom, wet glass and agar sheen' },
    typ: { display: 'soft rounded display with bio-lab plate numerals', body: 'clinical grotesque sans for protocol and caption text' },
    lit: { quality: 'cold lab illumination glowing through living matter', temperature: 'cool-toned', shadow: 'specimen shadows cast inside lit vessels' },
    ui: { background: 'sterile white with faint agar tint', surface: 'slide-frame cards with culture-bloom edges', components: 'specimen chips and sterile-field toggles', motion: 'colonies slowly blooming and drifting across panels' },
  },
  {
    slug: 'social-practice-art',
    ctx: 'Social practice — socially engaged art — treats human interaction itself as the medium: artists co-create with communities through dialogue, pedagogy and activism. Kin to relational aesthetics and participatory art, it values process over product — people and their relationships form the work, social engagement an aesthetic in itself. The discourse matured through the 2000s, codified in anthologies like Claire Bishop\'s Artificial Hells (2012).',
    vd: { shape: 'gathering formats: circles, tables, long shared benches', line: 'handwritten charts, banners and conversational diagram lines', composition: 'people arranged in dialogue, documentation at the margins', texture: 'photocopy grain, tape, chalk dust, fabric banner weave' },
    typ: { display: 'open civic sans display with banner-letter warmth', body: 'accessible humanist sans for community-facing text' },
    lit: { quality: 'plain available light of halls, lots and kitchens', temperature: 'warm-toned', shadow: 'soft shared shadows of people in conversation' },
    ui: { background: 'welcome-mat warm off-white', surface: 'workshop-poster cards with tape corners', components: 'sign-up sheets, map pins and discussion threads', motion: 'threads growing as more hands join the circle' },
  },
  {
    slug: 'metamodernism',
    ctx: 'Metamodernism names the cultural mood after postmodernism: an oscillation between modern idealism and postmodern skepticism, between sincerity and irony, integrating both rather than choosing. The term surfaced in 1975 with Mas\'ud Zavarzadeh and gained its present sense from Vermeulen and van den Akker\'s 2010 essay \'Notes on Metamodernism\': earnest longing worn with knowing humor, a new structure of feeling rather than a midpoint.',
    vd: { shape: 'paired motifs: geometric order leaning toward romantic horizons', line: 'clean modern contours dissolving into misty, drawn atmosphere', composition: 'sincere center framed by self-aware, ironic margins', texture: 'glossy synthetic surfaces brushed with handmade paint' },
    typ: { display: 'earnest serif display with a knowing sans alternate', body: 'literary serif carrying both wonder and deadpan asides' },
    lit: { quality: 'dawn light — hopeful yet sharply observed', temperature: 'warm-toned', shadow: 'long romantic shadows checked by flat modern shade' },
    ui: { background: 'horizon gradient from concrete grey to open sky', surface: 'cards alternating bare geometry with hand-tinted warmth', components: 'sincere pledge buttons with winking hover states', motion: 'pendulum easing that never quite settles' },
  },
  {
    slug: 'digital-folk-art',
    ctx: 'Digital folk art is the vernacular maker\'s instinct reborn in consumer software: untrained hands using pixel editors, emoji, memes and phone cameras much as rural sign-painters once used brush and barn board. It keeps folk art\'s loves — bold outline, flat celebratory color, naive perspective, hand-lettered words — while circulating through chats and feeds at platform speed, made by proud amateurs who value community usefulness over polish.',
    vd: { shape: 'chunky icons, framed greetings and square pixel tiles', line: 'wobbly freehand contours and hard one-bit outlines', composition: 'centered greeting-card layout with corner ornaments', texture: 'pixel staircases, jpeg softness, glitter and drop-shadow clichés' },
    typ: { display: 'hand-lettered pixel display with folk-border flourishes', body: 'rounded friendly sans like community newsletter text' },
    lit: { quality: 'screen-glow warmth, evenly front-lit', temperature: 'warm-toned', shadow: 'drop shadows applied by hand, one pixel too thick' },
    ui: { background: 'clip-art sky blue', surface: 'framed greeting cards with glitter borders', components: 'sticker badges, emoji reactions and heart toggles', motion: 'sparkle loops and bouncy sticker pops' },
  },
  {
    slug: 'yoga',
    ctx: 'Yōga, literally Western-style painting, is Japan\'s tradition of painting Japanese subjects with European means — oil on canvas, perspective, cast shadow, modelled flesh — coined in the Meiji period to stand opposite indigenous Nihonga. The 1855 Bansho Shirabesho institute trained Kawakami Tōgai and Takahashi Yuichi, reckoned the first true Yōga painter; from 1876 the Kobu Bijutsu Gakkō school brought Italian advisors such as Antonio Fontanesi.',
    vd: { shape: 'full-depth canvas images with plinth-still portrait busts', line: 'academy drawing contours softened by oil handling', composition: 'single-point perspective interiors and posed sitters', texture: 'varnished oil sheen, crisp canvas weave, glazed shadows' },
    typ: { display: 'Meiji roman display serif with engraved headline flourish', body: 'bookish transitional serif pairing Latin and Japanese' },
    lit: { quality: 'north-window studio light studied and rendered', temperature: 'warm-toned', shadow: 'graded chiaroscuro turning form in oil' },
    ui: { background: 'aged oil-tint ivory', surface: 'canvas-texture cards with gilt frame rules', components: 'portrait medallions and brush-glide sliders', motion: 'paint loading onto the brush, stroke by stroke' },
  },
  {
    slug: 'mingei',
    ctx: 'Mingei, the folk-craft ideal developed from the mid-1920s by philosopher Yanagi Sōetsu with potters Hamada Shōji and Kawai Kanjirō, locates beauty in ordinary utilitarian objects made by nameless craftsmen — pots, lacquer, textiles, baskets. Proclaimed a movement in 1926 amid Japan\'s rapid modernisation, it held that daily use keeps objects honest; Yanagi\'s Japan Folk Crafts Museum opened in 1936, a byword for the beauty of common things.',
    vd: { shape: 'wheel-turned pots, ladles, trays and cloth showing working wear', line: 'unselfconscious kiln drips, tool marks and brush-ringed rims', composition: 'useful objects grouped by function, never by display', texture: 'raw clay tooth, ash glaze pooling, woven and patched fiber' },
    typ: { display: 'hand-cut woodblock display like mingei print labels', body: 'warm sturdy sans on paper grain' },
    lit: { quality: 'low morning light across a working kitchen shelf', temperature: 'warm-toned', shadow: 'soft use-shadows under handles and rims' },
    ui: { background: 'rice-paper warm cream', surface: 'unglazed clay-toned cards with paper labels', components: 'tool-shaped icons and stitched dividers', motion: 'objects rocking gently as if lifted for use' },
  },
  {
    slug: 'sosaku-hanga',
    ctx: 'Sōsaku-hanga, the creative-prints movement of early twentieth-century Japan, insisted the artist be sole creator — self-drawn, self-carved, self-printed (jiga, jikoku, jizuri) — against the ukiyo-e division of labor kept by shin-hanga. It was born with Yamamoto Kanae\'s print Fisherman (1904); led between the wars by Onchi Kōshirō\'s abstractions, it struggled prewar and flourished after World War II as the woodblock tradition\'s genuine heir.',
    vd: { shape: 'kentō-registered image blocks within generous paper margins', line: 'carved chisel contour, angular gouges left visible', composition: 'bold single motifs, often abstracted, on open ground', texture: 'woodgrain pickup, baren burnish, uneven handmade paper' },
    typ: { display: 'carved-in-wood display lettering with chisel notches', body: 'clean small sans respecting wide print margins' },
    lit: { quality: 'even printing-studio daylight over damp paper', temperature: 'neutral', shadow: 'kentō ridge shadows inside stamped color fields' },
    ui: { background: 'washi paper cream', surface: 'block-print cards with deckled edges', components: 'stamp seals and ink-gradient chips', motion: 'baren pressing color across the sheet in passes' },
  },
  {
    slug: 'new-ink-art',
    ctx: 'New ink art is the contemporary turn of China\'s oldest painting tradition: since the late twentieth century artists take up shuimo — brush, ink and washes on xuan paper — turning from literati landscape toward abstraction, the city and conceptual play. Keeping calligraphic brush vitality and the tonal scale from black to faint grey, they push the medium through collage, resin and installation — ink at once a heritage and a live argument today.',
    vd: { shape: 'scroll-format panels and squared sheets of floating wash', line: 'brush center-line strokes flicking into dry-bone splays', composition: 'breathing emptiness broken by dense ink concentrations', texture: 'bleeding wet ink, granulated pigment, fibrous xuan paper' },
    typ: { display: 'bravura brush-script display with dry-brush flying white', body: 'minimal light sans letting ink strokes breathe' },
    lit: { quality: 'soft diffused light, washes glowing wetly', temperature: 'neutral', shadow: 'ink-dark pools acting as their own shadow' },
    ui: { background: 'xuan paper white', surface: 'wash-bleed cards with deckled corners', components: 'brush-stroke icons and ink-drop sliders', motion: 'ink blooming outward through paper fibers' },
  },
  {
    slug: 'guangdong-style-ceramics-painting',
    ctx: 'Guangdong\'s ceramic painting grew up in Guangzhou — until 1842 China\'s sole legal port for the European export trade. Canton porcelain, exportware of the eighteenth to twentieth centuries, was decorated there with overglaze enamel figure and flower scenes in famille-rose panels. Nearby Foshan\'s Shiwan kilns modeled boldly glazed figurines from the Qing onward, the Nanfeng dragon kiln firing some five hundred years.',
    vd: { shape: 'medallion panels framing figure scenes on vase and tureen', line: 'fine enamel contour work inside gilt-edged cartouches', composition: 'alternating figure and flower panels around a gilded border', texture: 'glassy overglaze enamel, raised gold rimming, figural glaze' },
    typ: { display: 'enamel-medallion display with gilt cartouche frames', body: 'trade-ledger serif with export-catalog clarity' },
    lit: { quality: 'shop-light glinting on glazed enamel and gold', temperature: 'warm-toned', shadow: 'tight reflections pooled inside glossy panels' },
    ui: { background: 'celadon-tinted porcelain white', surface: 'panel-framed cards with gilt borders', components: 'medallion emblems and gold-ribbon dividers', motion: 'panels rotating like wares on a turntable' },
  },
  {
    slug: 'madhubani-painting',
    ctx: 'Madhubani, or Mithila, art comes from the Mithila region of India and Nepal, named for Bihar\'s Madhubani district. Legend begins it with Rama and Sita\'s wedding, when King Janak ordered paintings to mark it; generations of women painted freshly plastered mud walls with fingers, twigs and matchsticks. Its five styles — Bharni, Kachni, Tantrik, Godna and Kohbar — leave no space empty, filled with flowers, birds, fish and geometry for festivals.',
    vd: { shape: 'dense bordered rectangles with twin-line frames', line: 'double-outline figures with fine cross-hatch fill', composition: 'central deity or bridal motif ringed by tight decorative bands', texture: 'matte mud-wall or paper ground with flat natural pigment' },
    typ: { display: 'double-outlined display lettering with hatched fill', body: 'rounded earthy sans on cream paper' },
    lit: { quality: 'warm courtyard daylight on fresh plaster', temperature: 'warm-toned', shadow: 'minimal — flat color holding its own shade' },
    ui: { background: 'mud-plaster ochre cream', surface: 'twin-bordered cards with hatched margins', components: 'lotus-and-fish icons and kohbar medallions', motion: 'borders growing line by line like ritual drawing' },
  },
  {
    slug: 'kalighat-painting',
    ctx: 'Kalighat painting — Kalighat Pat — arose around the Kalighat Kali Temple in 19th-century Kolkata, where scroll painters called patuas sold quick images to pilgrims. On cheap paper they drew gods, myths and satirical takes on colonial society with bold outlines, flat color and minimal background, sheets finished in sweeping strokes. Its record is a Bengal in transition; the Victoria and Albert Museum holds the largest collection, 645 works.',
    vd: { shape: 'single-sheet upright images with one or two figures', line: 'bold sweeping contour drawn in one confident brush load', composition: 'figures isolated on bare paper, background omitted', texture: 'watery flat color pooling inside decisive outline' },
    typ: { display: 'sweeping brush display with pat-painting swells', body: 'plain serif legible for Bengali and Latin captions' },
    lit: { quality: 'temple-court daylight on paper sheets', temperature: 'warm-toned', shadow: 'none but the outline — color stays front-lit and flat' },
    ui: { background: 'unbleached paper buff', surface: 'sheet cards with bare painted figures', components: 'outline icons and story-strip panels', motion: 'single-stroke reveals, one bold line at a time' },
  },
  {
    slug: 'tanjore-painting',
    ctx: 'Thanjavur (Tanjore) painting is the classical South Indian style born in the Maratha court of Thanjavur on Nayaka foundations of about 1600 under Vijayanagara suzerainty. Its icons of gods and saints carry rich flat color and the signature — gesso relief on halos and jewels overlaid with glittering gold foil, set with glass beads, the deity framed in a niche. Geographical Indication status followed in 2007–08.',
    vd: { shape: 'rectangular icon panels with arched niche and prabhavali arch', line: 'crisp embossed contours tracing gesso ornament', composition: 'deity centered in an architecturally framed throne niche', texture: 'raised gesso relief under beaten gold foil, glass-bead inlay' },
    typ: { display: 'gilded display lettering embossed like foil relief', body: 'dignified serif pairing Tamil and Latin scripts' },
    lit: { quality: 'lamp-light making gold foil blaze over gesso', temperature: 'warm-toned', shadow: 'deep relief shadows under halos and jewelry' },
    ui: { background: 'maroon banner cloth', surface: 'gold-foiled cards with embossed borders', components: 'halo medallions and bead-inlay buttons', motion: 'foil shimmering as panels tilt to the light' },
  },
]
