/**
 * Completeness patch r5f — illustration and line-work traditions (20).
 * Hand-authored (Task 5-f); facts Wikipedia-API-verified; no LLM involvement.
 * Fills ctx + visualDNA + typography + lighting + uiTranslation.
 */
export const PATCHES: any[] = [
  {
    slug: 'vesalian-anatomical-illustration',
    ctx: 'Anatomy\'s first great image tradition: Andreas Vesalius\' De Humani Corporis Fabrica Libri Septem ("On the Fabric of the Human Body in Seven Books"), published in 1543, broke with Galen by teaching from his own Paduan dissections. Its woodcut plates — carved in relief and printed — pose flayed muscle figures gesturing theatrically before Italian landscapes, making the dissected body both scientific record and Renaissance monument.',
    vd: { shape: 'flayed muscle figures posed like living statuary', line: 'incised woodcut contour with dense parallel hatching', composition: 'anatomized body front and center, sited in a landscape', texture: 'cut-block grain, tendon striation, crisp printed ink' },
    typ: { display: 'roman incised display caps like Renaissance plate titling', body: 'classical serif with generous margins for captions' },
    lit: { quality: 'bright studio daylight over the dissecting table', temperature: 'neutral-cool', shadow: 'modeled in hatching rather than cast black shadow' },
    ui: { background: 'aged rag-paper cream', surface: 'plate cards with letterpress caption rules', components: 'muscle-layer tabs and figure-index chips', motion: 'anatomical layers peeling away like turning pages' },
  },
  {
    slug: 'entomological-plates',
    ctx: 'Entomological plates made insects stars of scientific illustration. Maria Sibylla Merian (1647–1717), German-Dutch entomologist and illustrator, documented insects directly — establishing that they metamorphose rather than arise by spontaneous generation — and published her first book of natural illustrations in 1675. Hand-colored plates stage butterflies, moths and beetles through every life stage among host plants in lush baroque color.',
    vd: { shape: 'life-cycle clusters: eggs, larvae, pupae, winged adults', line: 'fine engraved outlines with stippled wing veining', composition: 'specimens arranged around a central host-plant stem', texture: 'hand-tinted watercolor bloom over engraved paper' },
    typ: { display: 'engraved-style caps with fine hairline serifs', body: 'small scholarly serif for Latin binomial captions' },
    lit: { quality: 'diffuse naturalist daylight on pinned specimens', temperature: 'neutral-cool', shadow: 'minimal, delicate drop shadows beneath wings' },
    ui: { background: 'moth-wing parchment ivory', surface: 'plate cards with specimen-number corners', components: 'life-stage filter chips and magnifier toggles', motion: 'wing stages unfolding as each plate settles' },
  },
  {
    slug: 'architectural-section-poche',
    ctx: 'Poché — French for "pocket" — is architecture\'s convention of filling everything cut through by a plan or section: walls, columns, hearths, vaults. Rendered in solid black or dense hatch, poché gives structure graphic weight, so rooms read as figure against the white ground of space. Refined by the Beaux-Arts ateliers, disciplined poché still tells a reader which lines are cut matter and which are seen beyond the section plane.',
    vd: { shape: 'solid-filled wall masses slicing through white rooms', line: 'hairline rules against heavy black cut fills', composition: 'figure-ground flip: voids white, cut structure black', texture: 'flat india-ink black, 45-degree hatch, printed tone' },
    typ: { display: 'engraved plate caps with drafting-lettering rigor', body: 'slender technical serif for section labels' },
    lit: { quality: 'even drafting-table light with no falloff', temperature: 'neutral-cool', shadow: 'shadow lives only inside the ink of the cut' },
    ui: { background: 'paper-white with faint graphite grid', surface: 'plan cards whose borders thicken to cut-line black', components: 'section-cut toggles and fill-hatch swatches', motion: 'walls flooding solid black as the cut plane sweeps' },
  },
  {
    slug: 'blueprint-cyanotype-drafting',
    ctx: 'In 1842 Sir John Herschel introduced the blueprint: a contact print process on light-sensitive sheets, using cyanotype chemistry — ferric ammonium citrate and potassium ferricyanide — developed and fixed with water alone. Printing as a negative, drafting linework emerges white on Prussian-blue ground, and construction and industry specification drawings could be copied quickly and accurately for over a century — drafting\'s defining look.',
    vd: { shape: 'sheet-wide plans, elevations and section grids', line: 'white linework luminous on saturated blue ground', composition: 'border frame, title block and scale rule framing the sheet', texture: 'slightly mottled wash-blue field, crisp bleached strokes' },
    typ: { display: 'reverse-out engineer caps stenciled in white', body: 'condensed technical gothic for dimension strings' },
    lit: { quality: 'flat ultraviolet exposure light', temperature: 'cool-toned', shadow: 'none — light prints only where lines block it' },
    ui: { background: 'deep Prussian cyanotype blue', surface: 'reversed white-line cards on blue stock', components: 'revision-cloud badges and scale-rule sliders', motion: 'new lines developing pale-to-white like a fresh print' },
  },
  {
    slug: 'japanese-technical-illustration',
    ctx: 'Japan sustains one of the world\'s most disciplined illustration cultures, from Edo-period woodblock-illustrated craft manuals to contemporary manga and anime production design. Whether explaining sword fittings, machine assemblies or mecha, the idiom prizes clean, confident contour, economical flat fills and exploded or cutaway logic, with calligraphic line weight carrying both material and motion for a broad general audience.',
    vd: { shape: 'crisp cutaway diagrams and exploded assemblies', line: 'uniform confident contour with weighted accents', composition: 'labeled callouts orbiting the subject on open ground', texture: 'flat vector-clean fills, screentone dots, smooth paper' },
    typ: { display: 'square gothic display caps with technical clarity', body: 'compact gothic balancing kana and latin captions' },
    lit: { quality: 'shadowless presentation light', temperature: 'neutral-cool', shadow: 'flat cel-style shading only where it clarifies form' },
    ui: { background: 'cool off-white layout-bond paper', surface: 'diagram cards with thin frames and leader lines', components: 'exploded-view sliders and part-number chips', motion: 'assemblies drifting apart into labeled layers' },
  },
  {
    slug: 'gesture-drawing',
    ctx: 'Gesture drawing is the laying in of a figure\'s action, form and pose in seconds — typically between ten-second flashes and five-minute poses — most often as the warm-up of a life-drawing session, though it is cultivated as an art in its own right, capturing people in the street, performers, athletes, animals at the zoo. Instead of contour or detail it chases movement: a few searching strokes registering weight, balance and thrust.',
    vd: { shape: 'elongated thrust lines finding the pose\'s spine', line: 'fast light strokes, continuous, rarely closed', composition: 'a single figure centered on generous empty page', texture: 'gritty charcoal or soft pencil dragged over tooth' },
    typ: { display: 'loose hand-drawn caps with darting terminals', body: 'light humanist sans for timing and pose notes' },
    lit: { quality: 'a single soft studio lamp on the model stand', temperature: 'warm-toned', shadow: 'broad soft shading implied in one tonal pass' },
    ui: { background: 'warm newsprint gray', surface: 'sketch cards with quick pencil edge shadows', components: 'timers running ten seconds to five minutes', motion: 'strokes replaying in their original drawing order' },
  },
  {
    slug: 'prison-tattoo-line-grammar',
    ctx: 'Prison tattooing builds an improvised visual language: without studios or sterile equipment, incarcerated people work with homemade machines and improvised needles and inks, and the tattoos may convey gang membership, codes, origins or hidden meanings of deeds. Denied color and correction, the line grammar turns elemental — hand-poked black outlines, repeated symbols and motto text reduced to what survives rough skin and scarce ink.',
    vd: { shape: 'bold symbols and lettering sized to skin panels', line: 'single-needle hand-poked black outline, committed', composition: 'symbol and text stacked in tight body-map layouts', texture: 'solid soot black, no shading, aged skin grain' },
    typ: { display: 'heavy block caps in tattoo gothic patterns', body: 'simple small-caps script for motto lines' },
    lit: { quality: 'harsh overhead institutional light', temperature: 'neutral-cool', shadow: 'minimal — the ink alone carries all depth' },
    ui: { background: 'asphalt charcoal gray', surface: 'skin-panel cards with scarred edge texture', components: 'symbol badges with hand-poked dotted borders', motion: 'marks completing line by line, as if poked' },
  },
  {
    slug: 'girih-patterns',
    ctx: 'Girih — Persian for "knot" — are decorative Islamic geometric patterns of angled lines forming interlaced strapwork, used across architecture and handicraft. Descended from Syrian Roman knotwork and shaped by Islamic mathematics after the ninth century, the earliest date from around 1000 CE and the art flourished until the fifteenth century, laid out with straightedge and compass. The Darb-i Imam shrine in Isfahan carries celebrated examples.',
    vd: { shape: 'interlaced polygonal strapwork filling surface fields', line: 'equal-width ribbon bands weaving over and under', composition: 'radially symmetric star polygons tiled edge to edge', texture: 'glazed tile gloss, carved stucco crispness, wood inlay' },
    typ: { display: 'slender geometric kufic-inspired display caps', body: 'quiet humanist sans for provenance notes' },
    lit: { quality: 'warm courtyard sun raking across tilework', temperature: 'warm golden', shadow: 'thin relief shadows along every raised strap' },
    ui: { background: 'lapis and turquoise tile field', surface: 'strapwork cards with woven-border rules', components: 'pattern-unfold toggles and star-node chips', motion: 'straps weaving over and under as patterns tile in' },
  },
  {
    slug: 'norse-ribbon-ornament',
    ctx: 'Norse ribbon ornament is the interlaced animal style of Viking art (8th–11th centuries), kin to Celtic and Germanic knotwork and culminating in the Urnes style, named for Norway\'s twelfth-century Urnes stave church. Slim quadrupeds and biting serpents loop in figure-eight interlace across carved wood, cast metal and rune stones, their ribbon-thin bodies, gripping claws and almond eyes giving hard-edged carving an unexpected linear elegance.',
    vd: { shape: 'slim looping quadrupeds woven into figure-eight knots', line: 'single-width ribbon contour with tapering tendrils', composition: 'a gripping beast centered in circular rhythm', texture: 'low-relief carved wood, cast bronze grain, runestone polish' },
    typ: { display: 'angular rune-cut display caps with carved terminals', body: 'sturdy humanist sans for saga captions' },
    lit: { quality: 'north light through a high stave-church window', temperature: 'cool-toned', shadow: 'crisp side shadows inside carved relief channels' },
    ui: { background: 'weathered runestone gray-green', surface: 'carved-panel cards with knotwork corner pieces', components: 'interlace toggles and rune-stone dividers', motion: 'serpents uncoiling along card edges as sections load' },
  },
  {
    slug: 'greek-key-meander',
    ctx: 'The meander or meandros is a decorative border built from one continuous line shaped into a repeated motif — the "Greek key" or "Greek fret" of modern naming, though it appears far earlier and far from Greece, in Near and Far Eastern cultures. Classic straight-line versions meet at right angles in a running fret; rounded variants read as running scrolls or water waves. Endless and self-contained, it frames Greek pottery to neoclassical floors.',
    vd: { shape: 'one continuous line folded into squared right-angle cells', line: 'uniform band that turns and turns, never crossing', composition: 'border friezes repeating the key around a field', texture: 'flat black-on-terracotta slip, incised stone channel' },
    typ: { display: 'lapidary Greek-inscription caps with wide tracking', body: 'classical serif for gallery captions' },
    lit: { quality: 'bright Aegean museum daylight', temperature: 'warm-toned', shadow: 'flat — only incised lines hold thin darks' },
    ui: { background: 'terracotta and slip black', surface: 'frieze cards framed by running-key rules', components: 'key-pattern dividers and fret-corner chips', motion: 'the line drawing itself endlessly around borders' },
  },
  {
    slug: 'rosemaling-strokes',
    ctx: 'Rosemaling — "rose painting" — is Scandinavian decorative folk painting that flourished from the 1700s to the mid-1800s, particularly in Norway; Sweden\'s branch became dalmålning and kurbits. It decorated church walls before spreading to everyday woodenware: ale bowls, stools, chairs, cupboards, boxes and trunks. Its fantasy flowers, scrollwork and fine line work are built from C- and S-strokes, one loaded brush carrying dark and light at once.',
    vd: { shape: 'C- and S-stroke scrolls bursting into teardrop flowers', line: 'double-loaded one-stroke leaves, petals and tendrils', composition: 'symmetrical bouquets banded around a central crest', texture: 'glossy oil glaze over turned wood and flat panels' },
    typ: { display: 'folk display caps with brush-tapered swashes', body: 'warm rounded serif for valley-style captions' },
    lit: { quality: 'candle-warm farmhouse window light', temperature: 'warm golden', shadow: 'the soft dark side of every two-tone stroke' },
    ui: { background: 'warm cream with aged varnish tint', surface: 'trunk-lid cards with painted border bands', components: 'kurbits blossom badges and scroll dividers', motion: 'petals unfurling stroke by stroke around crests' },
  },
  {
    slug: 'isometric-technical-vector',
    ctx: 'Isometric projection is the axonometric method for representing three-dimensional objects in two dimensions: the three coordinate axes appear equally foreshortened, set 120 degrees apart, so a cube\'s edges rise at thirty degrees and no vanishing point distorts measure. That kept-true scale made it the workhorse of engineering and technical drawing, and recast as clean vector geometry it is now an aesthetic — tidy, explorable diagram-space.',
    vd: { shape: 'cubes and prisms sheared to thirty-degree axis geometry', line: 'uniform vector strokes locked to three fixed axes', composition: 'subject corner-forward on an isometric floor grid', texture: 'flat vector fills, hairline rules, matte planes' },
    typ: { display: 'technical sans display caps with tabular numerals', body: 'compact grotesque for part callouts' },
    lit: { quality: 'flat shadowless vector light', temperature: 'neutral-cool', shadow: 'optional flat-toned drop shadows, never gradients' },
    ui: { background: 'pale blueprint-paper blue-gray', surface: 'grid-lined cards with axis-marker corners', components: 'axis-rotate dials and layer-explode sliders', motion: 'objects snapping between isometric facet states' },
  },
  {
    slug: 'svg-stroke-minimalism',
    ctx: 'SVG stroke minimalism is the contemporary interface idiom of drawing everything — icons, illustrations, logotype — as unfilled outlines: paths carry a stroke weight, round caps and joins, and nothing else. Born of the web\'s scalable vector format, its hairline geometry scales from sixteen-pixel glyphs to full-page murals, and its restraint — one or two line weights, generous white space — is now the lingua franca of product illustration.',
    vd: { shape: 'geometric icons and scenes built from open paths', line: 'a single uniform stroke weight, round caps and joins', composition: 'centered figures floating in generous white space', texture: 'pure vector edge — no fills, no grain, no noise' },
    typ: { display: 'matching geometric sans caps, stroke-weighted', body: 'airy geometric sans with wide leading' },
    lit: { quality: 'shadowless screen light', temperature: 'neutral', shadow: 'none — depth is dashed lines, not shade' },
    ui: { background: 'pure white with pale tint accents', surface: 'hairline-outlined cards on white', components: 'stroke icons that animate draw-on at two pixels', motion: 'paths tracing themselves as each view appears' },
  },
  {
    slug: 'painterly-digital-line',
    ctx: 'Painterly digital line is the contemporary hybrid where drawn strokes keep the hand\'s life in digital tools: pressure-sensitive stylus lines with tapered ends, grainy brush texture and gouache-or-ink edges, all endlessly editable. Storyboards, editorial illustration and animation design exploit the fusion — sketch energy with production polish — so one brush pass can act like graphite, sumi or oil while the file stays clean and revisable.',
    vd: { shape: 'organic drawn figures with breathing tapered contours', line: 'pressure-tapered strokes with grainy brush edges', composition: 'loose vignettes anchored by confident focal lines', texture: 'brush-grain fills, paper-tooth overlay, dry-edge breaks' },
    typ: { display: 'hand-lettered display caps with brush terminals', body: 'humanist sans at home in sketchbook context' },
    lit: { quality: 'warm drawing-desk lamp wash', temperature: 'warm-toned', shadow: 'soft painterly shadow massed in one brush pass' },
    ui: { background: 'textured digital-paper off-white', surface: 'sketchbook cards with deckle-edge shadows', components: 'brush-picker chips and pressure-curve sliders', motion: 'strokes painting in with velocity-based taper' },
  },
  {
    slug: 'fashion-flats-spec-drawing',
    ctx: 'Fashion flats are the working language of apparel production: garments drawn flat — front and back, symmetrical, in true cloth proportions — with seams, stitching, closures and trims called out as clean line work and spec measurements beside them. Where fashion illustration sells a mood, the flat specifies a thing to be cut and sewn, so its line is exact, its fills minimal, and every stitch rendered as deliberate, production-ready shorthand.',
    vd: { shape: 'symmetrical garment silhouettes laid perfectly flat', line: 'even-weight outlines with dashed stitch lines', composition: 'front and back views paired with spec callouts', texture: 'flat white ground, hairline grid, no fabric rendering' },
    typ: { display: 'precise tech-pack caps with measured tracking', body: 'tiny tabular sans for measurement tables' },
    lit: { quality: 'flat scanner-even light', temperature: 'neutral-cool', shadow: 'none — a document casts no shadow' },
    ui: { background: 'spec-sheet white', surface: 'tech-pack cards with stitch-dashed borders', components: 'seam-detail zoom chips and size-grid tables', motion: 'flats flipping crisply between front and back' },
  },
  {
    slug: 'vogue-era-gouache-fashion-plates',
    ctx: 'The fashion plate — an illustration showing the highlights of fashionable dress, historically etched, engraved or lithographed and colored by hand — entered the magazine age through Condé Nast\'s Vogue. Artists such as Erté, the Russian-born designer who worked across fashion, costume and graphic arts, defined the era: elongated figures in gouache, flat stencil-fresh color and Deco contour turning couture into idealized portraits of chic.',
    vd: { shape: 'impossibly elongated figures swathed in draped couture', line: 'sinuous Deco contour over flat gouache shapes', composition: 'one model on an empty stage-like ground, props minimal', texture: 'matte gouache veils, stenciled flat color, sheen accents' },
    typ: { display: 'elegant Deco display caps with high-waisted curves', body: 'refined italic-leaning serif for couture captions' },
    lit: { quality: 'footlight glow on satin and velvet', temperature: 'warm-toned', shadow: 'long theatrical shadows beneath sweeping gowns' },
    ui: { background: 'powdered champagne rose', surface: 'plate cards with art-deco corner lines', components: 'season-tag chips and couture-house crests', motion: 'gown hems sweeping across as plates turn' },
  },
  {
    slug: 'costume-design-rendering',
    ctx: 'Costume design — creating clothing for performers in theater, cinema and performance — communicates through the rendering: a painted drawing of each costume as worn, posed to show how the garment moves and what it declares, since costumes denote status, age and personality in a production\'s visual world. Watercolor or gouache on a figure template, fabric swatches at the margin, turns wardrobe decisions into a picture a director can approve.',
    vd: { shape: 'posed figure templates clothed in full character dress', line: 'quick confident outline weighted by fabric thickness', composition: 'one character per sheet, fabric swatches at the margin', texture: 'watery gouache washes, ink accents, taped swatch scraps' },
    typ: { display: 'theatrical hand-inked caps with playbill flourish', body: 'practical sans for scene and act numbers' },
    lit: { quality: 'backstage mirror-bulb brightness', temperature: 'warm-toned', shadow: 'cast shadows hinting at the stage floor' },
    ui: { background: 'watercolor buff on cold-press texture', surface: 'rendering cards pinned with tape-corner shadows', components: 'scene-number tabs and fabric-swatch chips', motion: 'costumes flipping like a lookbook on approval' },
  },
  {
    slug: 'daumier-lithographic-line',
    ctx: 'Honoré-Victorin Daumier (1808–1879) earned his living as a printmaker, filling Paris caricature journals La Caricature and Le Charivari with lithographs lampooning the monarchy, judiciary, lawyers and the wealthy from the Revolution of 1830 to the fall of the Second Empire. His lithographic crayon line is the tradition\'s high point: broad greasy blacks modeling theatrical bulk, caricature carried by gesture and contour, not detail.',
    vd: { shape: 'bulky theatrical figures massed in courtroom and street', line: 'greasy crayon stroke: broad black, scraped highlights', composition: 'stage-lit group scenes with caricature focal heads', texture: 'toned lithographic wash, stippled crayon grain, paper bite' },
    typ: { display: 'bold journal headline caps of the Parisian press', body: 'narrow news serif for satirical captions' },
    lit: { quality: 'footlight chiaroscuro on stage-set rooms', temperature: 'warm-toned', shadow: 'heavy crayon blacks massing into shadow' },
    ui: { background: 'aged newsprint gray-cream', surface: 'journal-page cards with caption-rule frames', components: 'satire-series tabs and issue-date stamps', motion: 'crayon strokes pressing in like stone to paper' },
  },
  {
    slug: 'grosz-satirical-ink',
    ctx: 'George Grosz (1893–1959) drew Weimar Berlin\'s ruling class with a savage pen: caricatural drawings and paintings of 1920s Berlin life, as a prominent member of Berlin Dada and New Objectivity, indicting profiteers, militarists and a decadent bourgeoisie in razor-ruled pen-and-ink and acid washes. Emigrating to the United States in 1933 and later teaching at the Art Students League of New York, he made moral rage into crisp, jagged drawing.',
    vd: { shape: 'jagged merchant figures, top hats and knife-edge rooms', line: 'nervous ruled pen lines, blade-thin, deliberately bent', composition: 'crowded urban cross-sections of greed and ruin', texture: 'acid wash pools, hard pen cross-hatch, smeared ink' },
    typ: { display: 'condensed poster-gothic caps with cut edges', body: 'tense grotesque for indictment captions' },
    lit: { quality: 'harsh streetlamp and neon glare', temperature: 'cool-toned', shadow: 'ink-wash darks swallowing building corners' },
    ui: { background: 'bile-tinted paper yellow-green', surface: 'torn-edge cards with hard ink borders', components: 'satire-series chips and dagger divider marks', motion: 'lines slashing in like pen strikes on load' },
  },
  {
    slug: 'new-yorker-mid-century-refined-line',
    ctx: 'The New Yorker, founded February 21, 1925, by Harold Ross and Jane Grant, made the single-panel cartoon a house art form, and its mid-century refined line — urbane, literate, sparing — is epitomized by Saul Steinberg, the Romanian-born artist best known for the magazine — notably View of the World from 9th Avenue — who called himself "a writer who draws." Thin pen strokes, a caption rule beneath, wit through restraint, not caricature\'s excess.',
    vd: { shape: 'small-figure vignettes in wide-margin white panels', line: 'thin even pen line, sparingly accented with wash', composition: 'one gag, one panel, a caption rule beneath', texture: 'smooth bristol paper, dry pen skip, faint gray wash' },
    typ: { display: 'understated literary caps with urbane restraint', body: 'graceful old-style serif for cartoon captions' },
    lit: { quality: 'even drawing-table daylight', temperature: 'neutral-cool', shadow: 'light gray washes, never heavy black' },
    ui: { background: 'warm editorial white', surface: 'cartoon-panel cards with thin double rules', components: 'issue-archive chips and caption-style toggles', motion: 'panels sliding in like magazine pages turning' },
  },
]
