/**
 * Completeness patch r3a — Japanese craft & aesthetic traditions (20).
 * Hand-authored (Task 3-a); names/eras Wikipedia-API-verified; no LLM involvement.
 * Fills ctx + visualDNA + typography + lighting + uiTranslation.
 */
export const PATCHES: any[] = [
  {
    slug: 'kintsugi',
    ctx: 'Kintsugi — mending broken ceramics with urushi lacquer dusted in gold, silver or platinum — grew from Muromachi-to-Edo tea culture, where prized Chinese bowls were too valuable to discard. Tradition traces its origin to a shattered bowl of the Ashikaga shogun; maki-e workshops supplied the gold dusting. The seam is honored, not hidden: the crack becomes the vessel\'s biography — visible repair as object history, a philosophy cited worldwide.',
    vd: { shape: 'vessels reassembled along jagged crack paths', line: 'gilded seams tracing each fracture like calligraphy', composition: 'crack networks as focal ornament on asymmetric mends', texture: 'dark urushi lacquer gloss against raised gold-sprinkled veins' },
    typ: { display: 'organic brush serifs with irregular gilded baselines', body: 'quiet Mincho with generous leading and restrained gold accents' },
    lit: { quality: 'low raking light catching gold seams', temperature: 'warm-toned', shadow: 'deep vessel shade making gold seams glow' },
    ui: { background: 'near-black lacquer brown', surface: 'seam-veined cards with gold crack lines', components: 'kintsugi-repair borders for broken-element states', motion: 'cracks knitting shut in gold-dust shimmer' },
  },
  {
    slug: 'shippo-cloisonne',
    ctx: 'Japanese shippō-yaki — "seven treasures" enamel — fuses copper bodies, silver wire cells and glass-glaze color, the name borrowed from Buddhist treasure lists. Meiji-era workshops made Japan the world\'s cloisonné power: Nagoya\'s Ando lineage and Kyoto\'s Namikawa Yasuyuki won exposition fame with mirror-black grounds, hair-fine wirework and translucent windows, running from temple ritual objects to export parlor vases.',
    vd: { shape: 'copper vase and plaque forms under pooled glass color', line: 'hair-fine silver wire cells outlining every motif', composition: 'symmetric medallions on mirror-black enamel fields', texture: 'glassy fused enamel gloss, raised wire edges, translucent windows' },
    typ: { display: 'enamel-wire lettering, fine silver outline strokes', body: 'small-scale Mincho serif against dark glaze grounds' },
    lit: { quality: 'jewel-case spotlight on glass glaze', temperature: 'cool-toned with warm metal accents', shadow: 'wire cells cast hairline shade into enamel pools' },
    ui: { background: 'mirror-black enamel', surface: 'wire-cell medallion cards', components: 'silver-outline chips and toggles', motion: 'glass-pool color fills flooding cells' },
  },
  {
    slug: 'edo-kiriko-cut-glass',
    ctx: 'Edo kiriko — Tokyo\'s cut-glass craft — took shape in 19th-century Edo, where glasshouses began wheel-cutting facets into blown glass; after the Meiji opening, Western brilliant-cutting merged with Japanese motifs like nanako fish-roe dots, asanoha hemp leaf and kagome basket lattices. Deep facet bands wrap tumblers in crisp registers; the lineage survives in Tokyo workshops as a designated traditional craft.',
    vd: { shape: 'tumbler and rock-glass bowls wrapped in facet bands', line: 'wheel-cut geometric lattices and fish-roe dot rows', composition: 'horizontal registers of stacked cut patterns', texture: 'transparent glass sparkle, cold polished facet planes, wheel sheen' },
    typ: { display: 'engraved-line lettering with crisp faceted strokes', body: 'clean grotesque sans paired with kana captions' },
    lit: { quality: 'hard specular sparkle and refraction', temperature: 'cool-toned', shadow: 'cut facets throw prismatic edge shadows' },
    ui: { background: 'pale glass blue-white', surface: 'facet-banded panels', components: 'cut-lattice dividers and frames', motion: 'light glints sweeping across facet rows' },
  },
  {
    slug: 'netsuke-carving',
    ctx: 'Netsuke — the carved toggles that anchored sagemono (inrō, purses, pipes) against a kimono sash — became Japan\'s miniature sculpture industry under Edo prosperity. Carvers shaped boxwood, ivory, stag antler and lacquer into katabori figures, manjū discs and mask forms, packed with artisan wit, zodiac jokes and foreign curiosities; the himotoshi cord-holes alone show engineering genius. Western collections prized them as the Edo world in an inch.',
    vd: { shape: 'palm-size rounded figures, discs and mask forms', line: 'soft carved contours with incised fine detail', composition: 'one compact subject composed from every viewing side', texture: 'polished boxwood and ivory patina, hand-wear gloss, tiny drill openings' },
    typ: { display: 'incised signature calligraphy on hidden undersides', body: 'small engraved caption marks for attribution' },
    lit: { quality: 'intimate directional side light', temperature: 'warm-toned', shadow: 'palm-shadow pockets pooled in carved folds' },
    ui: { background: 'boxwood cream', surface: 'rounded toggle-like buttons and chips', components: 'carved-figure icons with cord-hole details', motion: 'objects swinging gently on cord pivots' },
  },
  {
    slug: 'wajima-lacquer',
    ctx: 'Wajima-nuri, from Wajima on the Noto Peninsula of Ishikawa, is Japan\'s most durable urushi ware: layers of lacquer reinforced with powdered diatomaceous earth (ji-no-ko) over zelkova grounds, finished with maki-e gold dusting and chinkin — gold leaf pressed into finely carved lines. A town-wide division of labor, turners to decorators, sustained it from Edo prosperity to today; its gloss signs chopsticks, trays and tea utensils worldwide.',
    vd: { shape: 'turned bowl, tray and chopstick forms over zelkova cores', line: 'chinkin engraving channels filled with gold leaf', composition: 'border maki-e programs on plain deep-black fields', texture: 'deep urushi black gloss, gold-powder sparkle, layered undercoat ridges' },
    typ: { display: 'maki-e gold lettering on lacquer grounds', body: 'warm-ivory Mincho serif set on black' },
    lit: { quality: 'candle-warm depth light on black gloss', temperature: 'warm-toned', shadow: 'reflections floating in mirror-dark lacquer' },
    ui: { background: 'urushi near-black brown', surface: 'gloss-lacquer cards with gold trim', components: 'gold-engraved line icons', motion: 'gold dust settling into place' },
  },
  {
    slug: 'ise-katagami-patterns',
    ctx: 'Ise katagami — the paper stencils of Suzuka, Mie Prefecture — cut layered mulberry paper stiffened with persimmon tannin into the repeat patterns behind Japan\'s komon and yūzen textiles. Carving families passed down four techniques — drill, push-knife, tool and slash work; hairline bridges held the fine mats together, making the stencils museum-grade graphic design. The craft is a designated Important Intangible Cultural Property.',
    vd: { shape: 'rectangular stencil sheets of repeated medallion motifs', line: 'drilled dot rows joined by hairline paper bridges', composition: 'all-over repeats engineered for seamless dyeing', texture: 'tobacco-brown kakishibu paper, cut-edge fuzz, lacquer-stiffened sheen' },
    typ: { display: 'stencil-cut logotypes with visible bridge hairlines', body: 'cut-paper Mincho captions on stencil grids' },
    lit: { quality: 'flat even light on paper relief', temperature: 'warm-toned', shadow: 'cut edges cast fine knife-line shadow' },
    ui: { background: 'kakishibu tan', surface: 'stencil-repeat pattern cards', components: 'cut-grid dividers with hairline bridges', motion: 'stencil drop revealing pattern beneath' },
  },
  {
    slug: 'mon-family-crests',
    ctx: 'Mon — Japanese family crests — reduce identity to one circular emblem: paulownia for the Toyotomi, hollyhock for the Tokugawa, the sixteen-petal chrysanthemum for the imperial house. A 2004 compilation counted 241 general categories and 5,116 distinct designs; Edo-period codification fixed the rules, and crests still mark formal black kimono, lacquer boxes, temple gates and corporate logos — Japan\'s oldest continuously used logo system.',
    vd: { shape: 'circular medallions enclosing stylized plants, birds, tools', line: 'bold simplified contours with exact petal counts', composition: 'a single central emblem, symmetric and reversible', texture: 'flat ink stamp or resist-white on formal black cloth' },
    typ: { display: 'circular mon deployed as logotype seals', body: 'Mincho body text punctuated by crest stamps' },
    lit: { quality: 'flat even museum light', temperature: 'neutral', shadow: 'none — the emblem reads dead flat' },
    ui: { background: 'formal black', surface: 'crest-badge cards', components: 'round mon-style icon buttons', motion: 'seal-stamp press-in on select' },
  },
  {
    slug: 'hinagata-bon-pattern-books',
    ctx: 'Hinagata-bon — Edo-period woodblock kimono pattern books — turned fashion into a publishing genre, selling kosode design to urban consumers from the seventeenth century onward. Kyoto illustrator Nishikawa Sukenobu (1671-1750) set the standard: his Hyakunin joro shinasadame (1723) showed women of every rank dressed in the current pattern vocabulary, the plates serving as tailoring reference, style magazine and merchant reading copy alike.',
    vd: { shape: 'bound volumes of full-page kimono plates', line: 'woodblock contour line with pattern-filled garments', composition: 'standing figures staged to display sleeve and hem designs', texture: 'hand-pressed sumi on mulberry paper, woodgrain fleck, safflower-red accents' },
    typ: { display: 'title slips in bold woodblock Edo-moji letters', body: 'kana-and-kanji captions beside each plate' },
    lit: { quality: 'soft daylight on laid paper', temperature: 'warm-toned', shadow: 'page gutter and block-impression shading' },
    ui: { background: 'mulberry cream', surface: 'book-plate cards with figure crops', components: 'pattern-swatch selectors', motion: 'page-turn plate reveals' },
  },
  {
    slug: 'edo-nishiki-e-advertising',
    ctx: 'After Suzuki Harunobu\'s full-color nishiki-e arrived in the 1760s, Edo\'s woodblock publishers discovered the advertising print: beauties and kabuki stars fronted plugs for hair oils, medicines, cosmetics and restaurants, blurring art and commerce. Kuniyoshi, Kunisada and their contemporaries made product endorsement a star vehicle; theatre bills and publisher seals completed the first mass-media graphic economy of urban Japan.',
    vd: { shape: 'oblong single-sheet posters with product vignettes', line: 'keyblock contours over flat color fields', composition: 'celebrity figure fronting a brand-text cartouche', texture: 'woodgrain overprint, mica-dust grounds, bokashi gradient edges' },
    typ: { display: 'brush-style Edo-moji display lettering in cartouches', body: 'Mincho-style serif captions with mixed kana' },
    lit: { quality: 'print-shop evenness with theatrical spotlight', temperature: 'warm-toned', shadow: 'flat color blocks, minimal cast shadow' },
    ui: { background: 'indigo with mica dusting', surface: 'poster-sheet cards', components: 'cartouche badges and brand stamps', motion: 'bokashi gradient wipe-ins' },
  },
  {
    slug: 'showa-hyakkaten-matchbox-labels',
    ctx: 'Shōwa department stores (hyakkaten) gave away branded matches at every counter, and the labels became a golden age of Japanese commercial design: houses like Mitsukoshi and Takashimaya commissioned bold mixed-script typography, modernist geometric motifs and seasonal imagery on small cream boards. Produced from the 1930s through the 1960s, the labels are collected today as a time capsule of mid-century urban Japan\'s daily graphic language.',
    vd: { shape: 'small rectangular card labels with framed layouts', line: 'ruled frames cut by diagonal dynamic accents', composition: 'store name dominant, service claims stacked beneath', texture: 'flat letterpress ink on cream board, slight misregistration, strike-edge wear' },
    typ: { display: 'bold mixed kanji-katakana display lockups', body: 'compact gothic captions for services and addresses' },
    lit: { quality: 'flat print-shop light', temperature: 'warm-toned', shadow: 'none — flat ink on board' },
    ui: { background: 'aged cream board', surface: 'label-framed cards', components: 'stamp-like store badges', motion: 'match-strike flash transitions' },
  },
  {
    slug: 'kamishibai-story-cards',
    ctx: 'Kamishibai — "paper play" — carried illustrated cards on bicycles to street corners, where narrators clacked hyōshigi sticks and sold candy to children through the Depression-era 1930s and the postwar years until television arrived in the mid-1950s. Its lineage reaches back to 8th-century picture-scroll preaching, but its flat, vivid, action-cut card style fed directly into the visual grammar of manga and anime.',
    vd: { shape: 'large landscape boards slid into a box stage', line: 'thick cartoon outline contours', composition: 'one scene per card, action cropped for drama', texture: 'flat poster-color fills, gouache brush grain, sun-faded wear' },
    typ: { display: 'hand-lettered onomatopoeia bursts on the boards', body: 'performative narration lines in legible kana script' },
    lit: { quality: 'open-air afternoon street light', temperature: 'warm-toned', shadow: 'gathered children shading the stage bottom' },
    ui: { background: 'street-corner dust tones', surface: 'card-slide story panels', components: 'stage-framed story steppers', motion: 'cards push-swapping left to right' },
  },
  {
    slug: 'japanese-matchbook-and-ticket-design',
    ctx: 'Mid-century Japan printed daily life on tiny cardstock: ryokan matchbooks, restaurant book matches and cardboard train tickets each carried a compressed graphic identity — bold kanji and katakana, vermilion-and-cream palettes, punched marks, serial numbers and gate symbols. Discarded by the millions, this transit-and-hospitality ephemera is now collected as Shōwa-era modernism\'s humblest and most telling graphic layer.',
    vd: { shape: 'palm-size book covers and stub rectangles', line: 'rule-box borders with tab notches and perforations', composition: 'name block top, class and number strips below', texture: 'soft card tooth, letterpress ink bite, edge wear and punch holes' },
    typ: { display: 'heavy gothic kanji lockups with katakana subheads', body: 'tiny numeric, routing and serial captions' },
    lit: { quality: 'even archival flat light', temperature: 'neutral-warm', shadow: 'perforation and staple micro-shadows' },
    ui: { background: 'ticket cream', surface: 'stub cards with punched corners', components: 'stamp-serial chips and gate tokens', motion: 'tear-off perforation snaps' },
  },
  {
    slug: 'karesansui',
    ctx: 'Karesansui — the dry landscape garden — distills landscape into raked gravel water and grouped stone islands, composed for seated viewing from a temple veranda. Muromachi-period Zen temples in Kyoto perfected the form: Ryōan-ji\'s late-15th-century fifteen-stone field remains its canonical enigma, and Daisen-in\'s compact courtyard extends the grammar. Gravel is re-raked daily as contemplative practice — emptiness as image.',
    vd: { shape: 'rectangular walled fields of raked gravel and stone groups', line: 'parallel rake furrows circling stone islands', composition: 'asymmetric stone placement read from one seated viewpoint', texture: 'fine pale gravel grain, moss softness, weathered wall patina' },
    typ: { display: 'spare brush kanji with wide open counters', body: 'quiet Mincho with generous space and no ornament' },
    lit: { quality: 'flat overcast morning light', temperature: 'neutral', shadow: 'stone groups casting soft moss-side shade' },
    ui: { background: 'raked-gravel off-white', surface: 'stone-group cards on furrow grounds', components: 'hairline rule dividers', motion: 'rake-line slow redraw loops' },
  },
  {
    slug: 'wabi-cha',
    ctx: 'Wabi-cha — the rustic tea aesthetic — crystallized across three masters: Murata Jukō, Takeno Jōō and above all Sen no Rikyū (1522-1591), who moved tea from gilded shoin display to a thatched two-mat hut. Korean Ido bowls, Karatsu and raku ware, bamboo scoops and wildflowers replaced Chinese masterpiece perfection; imperfection, poverty of means and seasonal presence became the highest taste, founding chanoyu\'s philosophy.',
    vd: { shape: 'irregular two-mat hut geometry and asymmetric utensils', line: 'hand-formed, never-quite-straight contours', composition: 'deliberate imbalance around the tokonoma focal point', texture: 'rough clay, splint bamboo, thatch fiber, soft use patina' },
    typ: { display: 'rustic brush kana with wobbled baselines', body: 'small Mincho with wide word spacing and air' },
    lit: { quality: 'paper-filtered low afternoon light', temperature: 'warm-toned', shadow: 'deep quiet corner shadow, tokonoma half-light' },
    ui: { background: 'earthen clay grey-brown', surface: 'rough matte paper cards', components: 'understated ink-line buttons', motion: 'slow kettle-steam fades' },
  },
  {
    slug: 'raku-ware',
    ctx: 'Raku ware began when the tile-maker Chōjirō, working to Sen no Rikyū\'s wabi-cha direction in late-16th-century Kyoto, hand-shaped tea bowls without a wheel and pulled them glowing from a small kiln — raku meaning ease or pleasure. The family\'s raku seal was traditionally bestowed under Hideyoshi\'s regime; sixteen generations of the household in Kyoto keep the soot-black kuro-raku and iron-red aka-raku modes alive as tea\'s most direct vessels.',
    vd: { shape: 'hand-pinched low bowls with soft shoulder dents', line: 'finger-drawn rim waves, tool-scraped foot', composition: 'a single gestalt vessel with no applied decoration', texture: 'matte soot-black glaze, fine crackle web, raw foot clay' },
    typ: { display: 'single-stroke brush kanji with seal-stamp accents', body: 'hushed Mincho with uneven ink density' },
    lit: { quality: 'kettle-side warm glow', temperature: 'warm-toned', shadow: 'bowl interior swallowing light into soft black' },
    ui: { background: 'char soot black', surface: 'matte crackle-glaze cards', components: 'seal-red accent buttons', motion: 'kiln-glow pulse on hover' },
  },
  {
    slug: 'chashaku-aesthetics',
    ctx: 'The chashaku — bamboo tea scoop — is tea ceremony\'s smallest artwork and among its most personal: carved from a single strip of bamboo, often by the tea masters themselves, given a poetic name (mei) and sometimes a lacquer inscription on the reverse. Rikyū\'s plain bent scoops set the ideal; scoops by successive grandmasters are stored in bamboo tubes, mounted, and displayed in the tokonoma, studied like calligraphy.',
    vd: { shape: 'slim bent bamboo strip with a scooped tip', line: 'one continuous node-to-tip curve', composition: 'the calligraphic presence of a single object in space', texture: 'satin bamboo skin, node-ring relief, dark age patina' },
    typ: { display: 'inscribed mei names in grass-script brush kana', body: 'catalog captions in small Mincho' },
    lit: { quality: 'tokonoma side-window soft light', temperature: 'warm-toned', shadow: 'a thin object casting one fine bamboo shadow' },
    ui: { background: 'plain washi white', surface: 'scroll-mounted object cards', components: 'slender dividers like bamboo nodes', motion: 'gentle rotation revealing the curve' },
  },
  {
    slug: 'bokuseki-aesthetics',
    ctx: 'Bokuseki — "ink traces" — are the calligraphy of Zen monks, valued precisely for their bold, unpolished force: each character brushed in a single breath, the whole mind visible in the stroke. Ikkyū Sōjun (1394-1481) and Hakuin Ekaku (1686-1769) are the classic hands; Daitoku-ji in Kyoto preserves the troves that tea masters enshrine in the tokonoma, where one hanging word can govern an entire gathering.',
    vd: { shape: 'hanging scroll fields carrying few large characters', line: 'wet-loaded bold strokes with dry-brush breaks and splashes', composition: 'vast blank paper around a dense calligraphic mass', texture: 'matte sumi blacks from wet sheen to crumble, absorbency halos' },
    typ: { display: 'monumental brush kanji as pure display type', body: 'small cartouche captions and colophon lines' },
    lit: { quality: 'reverent indirect alcove light', temperature: 'neutral', shadow: 'scroll cloth and roller casting soft edge shade' },
    ui: { background: 'aged paper white', surface: 'scroll-panel cards', components: 'ink-stroke icon marks', motion: 'single-breath stroke draw-on' },
  },
  {
    slug: 'chabana-aesthetics',
    ctx: 'Chabana — tea flowers — reject ikebana\'s structure for the nageire "thrown-in" gesture: one or two seasonal blooms stood in a bamboo tube or rough ceramic vase in the tokonoma, arranged as if they had simply grown there. Developed alongside wabi-cha under Rikyū\'s taste, the practice admits only what the season offers — no doubled varieties, no contrived form. Wildness itself is the art.',
    vd: { shape: 'one or two stems in a tall tube or rough vase', line: 'natural stem curves with an unforced lean', composition: 'a single point of interest against blank alcove wall', texture: 'petal translucency, dew sheen, split bamboo fiber' },
    typ: { display: 'season names in delicate brush kana', body: 'minimal captions with much white space' },
    lit: { quality: 'faint morning tokonoma light', temperature: 'neutral-warm', shadow: 'flower shadow on alcove plaster like a second bloom' },
    ui: { background: 'alcove plaster off-white', surface: 'bloom-on-blank cards', components: 'single-accent floral icons', motion: 'soft stem-sway loops' },
  },
  {
    slug: 'mizusashi-aesthetics',
    ctx: 'The mizusashi — the fresh-water jar of the tea ceremony — stands among chanoyu\'s three great utensils beside the kettle and the tea bowl, and its lid is lifted as a ritual beat that briefly bares the water. Potters of Bizen, Shigaraki and Karatsu supplied fire-marked stoneware jars, while lacquer and metal lids set off the rough kiln character; the host\'s choice signals season and depth of taste.',
    vd: { shape: 'shouldered jar bodies with wide fitted lids', line: 'wheel-thrown swell with natural kiln pinch', composition: 'a weighty single object anchoring the tatami diagonal', texture: 'unglazed fire-cloud stoneware, ash-splash glaze, polished lid rims' },
    typ: { display: 'utensil names in brushed kanji labels', body: 'ledger-style Mincho catalogue lines' },
    lit: { quality: 'low mat-level evening light', temperature: 'warm-toned', shadow: 'jar mass casting broad tatami shade' },
    ui: { background: 'tatami straw grey-green', surface: 'stoneware-textured cards', components: 'lid-lift toggles', motion: 'heavy settle-in transitions' },
  },
  {
    slug: 'natsume-aesthetics',
    ctx: 'The natsume — the small tea caddy for thin (usucha) powdered tea — takes its name from the round-shouldered jujube fruit it resembles, and is most often lacquered wood, from plain black to seasonal maki-e imagery. Rotated to match the month, presented and admired with formal turns of the hands, it carries the quiet glamour of Edo-period lacquer craft into every tea gathering.',
    vd: { shape: 'round-shouldered squat cylinder with a snug lid', line: 'clean turning ridges and lacquer edge fillets', composition: 'a single centered object over folded silk', texture: 'mirror urushi depth, maki-e gold dust imagery, cool rim light' },
    typ: { display: 'maki-e seasonal motifs doubling as lettering', body: 'small Mincho captions on deep black' },
    lit: { quality: 'candle-and-daylight tea room glow', temperature: 'warm-toned', shadow: 'lid rim shading a soft highlight band' },
    ui: { background: 'deep lacquer brown-black', surface: 'round-shouldered pill cards', components: 'seasonal gold-accent chips', motion: 'lid-lift slide reveals' },
  },
]
