/**
 * Completeness patch r3f — Australian Aboriginal, Northwest Coast & Arctic entries (20).
 * Hand-authored (Task 3-f); facts spot-checked via Wikipedia API (Papunya Tula, Bark
 * painting, Wandjina, Gwion Gwion, Tiwi Islands, Kinngait, Chilkat weaving, Qulliq, Amauti).
 */
export const PATCHES: any[] = [
  {
    slug: 'papunya-tula-dot-painting',
    ctx: "Papunya Tula launched the Western Desert acrylic movement at Papunya, Northern Territory, after teacher Geoffrey Bardon encouraged Pintupi, Luritja, Warlpiri, Arrernte and Anmatyerre men to paint ceremonial body and sand designs in 1971; the cooperative followed in 1972. When sacred content was criticized for exposing ritual heritage, painters veiled it under dot fields — concealment became the signature shimmer carrying Aboriginal art worldwide.",
    vd: { shape: 'circular journey paths and ancestral sites made of ringed dot clusters', line: 'stippled dot rows bending around hidden sacred under-designs', composition: 'hidden icon at center swamped by concentric dot fields', texture: 'matt acrylic pigment in raised pointillist crusts over flat ground' },
    typ: { display: 'rounded geometric caps with dotted counters and halos', body: 'clean humanist sans set wide with ochre-dot bullets' },
    lit: { quality: 'hard desert sun bleaching flat color fields', temperature: 'warm-toned', shadow: 'raised dots bead tiny shadows into the grooves' },
    ui: { background: 'burnt-ochre sand orange', surface: 'dot-field cards with ring motifs', components: 'circular site-marker chips', motion: 'dots cascading to unveil hidden designs' },
  },
  {
    slug: 'arnhem-land-x-ray-painting',
    ctx: "In western Arnhem Land, rock painters perfected the x-ray style: fish, fauna and spirit figures with backbone, organs and skeleton visible inside the contour. Fish anchor the regional diet and dominate the imagery, and Australian x-ray painting counts among the world's oldest continuous art traditions, with early specimens millennia old. Painters refreshed the shelter walls across generations, keeping the sites living, layered galleries.",
    vd: { shape: 'slender elongated fish and spirits with organ shapes inset', line: 'single flowing contour enclosing radiating spine and rib strokes', composition: 'lateral side-view figures stacked on flat ochre grounds', texture: 'dry earth-pigment matte, hatched infill, weathered rock grain' },
    typ: { display: 'condensed lattice serif with inner crossbars showing through', body: 'open workhorse sans with skeletal diagram captions' },
    lit: { quality: 'filtered torchlight raking shelter walls', temperature: 'cool-toned with warm ochre accents', shadow: 'rock relief shadows under thin painted contours' },
    ui: { background: 'red-ochre cave wash', surface: 'translucent anatomical panels', components: 'bone-line iconography', motion: 'organs fading in beneath contour lines' },
  },
  {
    slug: 'rarrk-crosshatch',
    ctx: "Rarrk is the fine cross-hatching of Arnhem Land bark painting: over ochre grounds of red or white, artists fill clan designs with hair-thin parallel strokes that shift color at intersections and shimmer from within. Inherited designs make the rarrk field itself the owner's signature — geometry read as radiance and ancestral presence — carried by Yolngu painters at Yirrkala and West Arnhem masters like John Mawurndjul.",
    vd: { shape: 'flat figurative blocks dissolved into fine diagonal weave', line: 'millimetre-spaced parallel strokes crossing into moire shimmer', composition: 'feature blocks framed by yellow clan-design borders', texture: 'crisp dry stroke over toothed bark, pigment ridges catching light' },
    typ: { display: 'hairline cross-hatched display face with shimmering joints', body: 'quiet small sans on deep ochre fields' },
    lit: { quality: 'angled gallery light igniting the moire', temperature: 'warm-toned', shadow: 'stroke ridges shade alternately as light moves' },
    ui: { background: 'white pipeclay ground', surface: 'rarrk-weave dividers and rules', components: 'clan-band header strips', motion: 'crosshatch shimmering on scroll' },
  },
  {
    slug: 'wandjina-rock-faces',
    ctx: "Wandjina are cloud and rain spirits of the Wanjina Wunggurr cultural bloc of the Kimberley, painted in rock shelters for perhaps 4,000 years and still renewed by custodians such as the Mowanjum community. The faces are mouthless, ringed by halo-like headdresses, eyes without pupils, bodies dissolving into concentric lines — rain-bearing ancestors whose force never left the country, repainted as an act of care that keeps them alive.",
    vd: { shape: 'mask-like faces floating over caped halo-ringed bodies', line: 'thick powdery outlines with radial mouthless tassels', composition: 'ranked figures gathered in shelter ceilings like clouds', texture: 'chalky white and red pigment blooming on rough stone' },
    typ: { display: 'rounded halo-headed letterforms with eye-dot counters', body: 'soft rounded sans like pigment-saturated strokes' },
    lit: { quality: 'dim diffuse shelter light, no hard cast', temperature: 'cool-toned', shadow: 'stone hollows deepen around the glowing white bodies' },
    ui: { background: 'storm-cloud grey-white', surface: 'halo-ringed avatar frames', components: 'rain-band progress strips', motion: 'mouthless faces slowly regathering color' },
  },
  {
    slug: 'gwion-gwion-figures',
    ctx: "Gwion Gwion — long called the Bradshaws, after pastoralist Joseph Bradshaw who recorded them in 1891 — is the elegant rock-figure tradition of the north-west Kimberley. Slender human figures stride with tassels, bags and headdresses in mulberry, ochre and white, contours barely disturbed by centuries; dating stays contested, though a 2020 study placed most figures near 12,000 years old. Traditional owners today name and interpret the paintings.",
    vd: { shape: 'tall linear silhouettes in dynamic stride, waist-length accoutrements', line: 'thin unwavering contours with fringed tassel strokes', composition: 'single-file processions across shelter wall registers', texture: 'flat matte mulberry and white pigment on abrasive stone' },
    typ: { display: 'tall slender elongated serif caps like striding figures', body: 'light elegant serif captions with tassel accents' },
    lit: { quality: 'low-angle sun grazing rock galleries', temperature: 'warm-toned', shadow: 'figures ghost pale against shadowed overhangs' },
    ui: { background: 'mulberry oxide maroon', surface: 'procession-strip banner cards', components: 'tassel-fringed list markers', motion: 'figures marching across the viewport' },
  },
  {
    slug: 'tiwi-tutini-grave-poles',
    ctx: "On the Tiwi Islands, the pukamani burial rite culminates in tutini: up to a dozen ironwood grave posts, commissioned from carvers and raised around the grave months after burial. Carved and painted with white clay, black charcoal and yellow or red ochre, the poles condense the deceased's story into bold abstract fields; dancers move among them, painted tunga baskets crown the posts, before the assemblage is left to weather back into the scrub.",
    vd: { shape: 'tall tapering ironwood posts crowned by carved finials', line: 'bold banding and zigzag ochre fields between carved ridges', composition: 'ring of standing poles around one grave mound', texture: 'white clay, black charcoal and red-yellow ochre on rough grain' },
    typ: { display: 'chunky post-carved capitals with ochre banding', body: 'rounded sans with charcoal-and-clay tonal weight' },
    lit: { quality: 'open monsoon-sky daylight on bare ground', temperature: 'warm-toned', shadow: 'pole clusters throw long crossing shadows at dusk' },
    ui: { background: 'ironwood grey-brown', surface: 'banded-post section dividers', components: 'ochre-band progress columns', motion: 'baskets settling onto pole tops' },
  },
  {
    slug: 'utopia-batik',
    ctx: "Batik reached Utopia (Urapuntja), an Alyawarre and Anmatyerre homeland north-east of Alice Springs, in the late 1970s: women's workshops translated body-paint and Dreaming design into wax-resist dyeing on silk in communal outstations. Emily Kame Kngwarreye began in it in 1977 before turning to canvas, and the community's silk batiks — layered yam, seed and awelye motifs — toured internationally and sustained the community for over a decade.",
    vd: { shape: 'allover fields of circular body-paint motifs and yam tendrils', line: 'wax-drawn crackle lines separating dye-wash pools', composition: 'repeating vegetal rhythm with no fixed horizon', texture: 'cracked wax resist, saturated dye blooms, silk sheen' },
    typ: { display: 'wax-resist display letters with crackle texture', body: 'soft rounded sans echoing dye-wash gradients' },
    lit: { quality: 'bright diffuse studio light through silk', temperature: 'warm-toned', shadow: 'dye pools shade where wax blocks the color' },
    ui: { background: 'dyed indigo-plum silk wash', surface: 'crackle-texture panels', components: 'motif-repeat tile chips', motion: 'dye bleeding across waxed resists' },
  },
  {
    slug: 'sand-stories',
    ctx: "Across Central Australia, sand is a storytelling surface: in Pitjantjatjara country the practice is milpatjunanyi, the art of telling stories in the sand. Tellers, often women, first press the drawing stick to the body to make the connection, then sketch lines, circles and tracks while tapping out rhythm; symbols stand for camps, ancestors and animals, the drawing erased by wind as the story ends. It now also lives on in classroom teaching.",
    vd: { shape: 'shallow fingertip-drawn maps of camp, water and journey', line: 'single-stick incisions, dotted track lines, open circles', composition: 'episodic panels wiped and redrawn beside the speaker', texture: 'loose granular sand, crisp line edges crumbling inward' },
    typ: { display: 'stick-drawn informal caps like finger-traced lines', body: 'light monoline sans mimicking sand scratch' },
    lit: { quality: 'overhead desert light flattening the ground', temperature: 'warm-toned', shadow: 'tiny line shadows give the drawing depth' },
    ui: { background: 'pale red-sand ground', surface: 'sketchable sand-drawing canvas', components: 'track-and-circle legend chips', motion: 'lines drawing on, then wind-erasing' },
  },
  {
    slug: 'haida-formline-art',
    ctx: "Haida formline is the Northwest Coast design system: swelling black formlines bent around red secondary fields define ovoids, U-forms and S-forms, splitting and filling into eagle, bear, raven and whale crests. From cedar house fronts, boxes and masks on Haida Gwaii to Charles Edenshaw's (c. 1839–1920) 19th-century brilliance in wood, argillite and jewelry, its rules are strict enough to read as language and fluid enough for endless invention.",
    vd: { shape: 'crests built of swelling ovoids, U-forms and S-forms', line: 'thick tapering black formlines wrapping red secondary units', composition: 'split-body symmetry folded into chest and panel planes', texture: 'flat pigment on cedar grain, crisp carved ridge edges' },
    typ: { display: 'bold formline face with ovoid counters and U-form bowls', body: 'sturdy low-contrast sans beneath red-and-black panels' },
    lit: { quality: 'north-light clarity on carved relief', temperature: 'cool-toned', shadow: 'formline ridges cast hard internal shadows' },
    ui: { background: 'deep cedar brown-black', surface: 'ovoid-panel headers', components: 'crest badges and toggles', motion: 'formlines swelling to assemble crests' },
  },
  {
    slug: 'tlingit-chilkat-weaving',
    ctx: "Chilkat weaving (Tlingit naaxein) is the ceremonial robe art of Tlingit, Haida and Tsimshian weavers. On a simple frame loom, cedar-bark and wool warps are twined around to build curving formline crests — ravens, whales, bears — in the near-universal palette of black, white, yellow and blue. High-ranking owners wear them at dances and potlatches; the fringe-swinging dancing blankets remain among the coast's most coveted regalia.",
    vd: { shape: 'curved crest motifs hemmed by long swinging fringe', line: 'tapered curving outlines advancing line by line in twine', composition: 'central crest field between banded borders and side panels', texture: 'wool weft loft over corded cedar-bark warp, silken sheen' },
    typ: { display: 'weft-fiber display serif with fringe descenders', body: 'warm yarn-toned sans with woven-rule dividers' },
    lit: { quality: 'soft hall light lifting wool pile', temperature: 'warm-toned', shadow: 'fringe strands shade in moving layers' },
    ui: { background: 'midnight blue-black wool', surface: 'fringed-edge cards', components: 'weave-pattern progress bars', motion: 'fringe swaying on hover' },
  },
  {
    slug: 'kwakwaka-wakw-transformation-masks',
    ctx: "Kwakwaka'wakw transformation masks are mechanical marvels of the potlatch: a hinged outer animal face — raven, hawk, sun — opens on a pulled cord to reveal an inner human face, staging the move between natural and supernatural worlds. Cedar-carved and painted black, red and yellow, they snap open with flapping parts amid dance, song and drumming as chiefs enact ancestor myths at winter ceremonies on northern Vancouver Island and the mainland.",
    vd: { shape: 'rounded hinged animal head splitting to a nested human face', line: 'bold black-red formline banding across beak, eye and brow', composition: 'closed-to-open choreography, mask face as moving stage', texture: 'glossy paint over adzed cedar, movable flaps and feather shine' },
    typ: { display: 'split-hinged display letters that open like a mask', body: 'cedar-toned sans with ceremonial red drop caps' },
    lit: { quality: 'firelit big-house drama with flashing reveal', temperature: 'warm-toned', shadow: 'hinged flaps throw sudden dark when snapped wide' },
    ui: { background: 'big-house smoke black', surface: 'hinged reveal panels', components: 'string-pull disclosure toggles', motion: 'mask snapping open on interaction' },
  },
  {
    slug: 'northwest-coast-bentwood-boxes',
    ctx: "Bentwood boxes are the Northwest Coast's signature container: a single cedar plank is kerfed and steam-bent into a squared chest whose only seam runs up one corner, then painted or carved with formline crests. Haida, Tlingit, Tsimshian, Gitxsan and other nations made them to hold food, regalia and treasure — stacked on feast-house floors — their clean bent corners, tight joinery and crisp painted panels turning storage into ceremony-grade art.",
    vd: { shape: 'squared chest volumes bent from one continuous plank', line: 'crisp kerfed corner folds and formline panel borders', composition: 'stacked and ranked boxes, each face a designed panel', texture: 'adzed cedar sheen, oiled patina, pigment sitting proud of grain' },
    typ: { display: 'chamfered plank-serif caps like bent-corner edges', body: 'sturdy workhorse sans with corner-brace details' },
    lit: { quality: 'warm interior lamplight on oiled cedar', temperature: 'warm-toned', shadow: 'bent corners shade in clean vertical seams' },
    ui: { background: 'oiled cedar amber-brown', surface: 'bent-corner container cards', components: 'stackable box modules', motion: 'panels folding shut like kerfed planks' },
  },
  {
    slug: 'coast-salish-spindle-whorls',
    ctx: "Coast Salish weavers spun wool for their famous mountain-goat robes on hand spindles weighted with whorls of carved wood — large discs whose animal and human designs turned with the spin. Beyond the workroom, notable whorls circulated as display objects in ritual and prestige contexts and as heirlooms; their concentric ring compositions and sweeping crescent figures make them among the most distinctive carved artworks of the Salish world.",
    vd: { shape: 'broad carved discs with raised rim and centered hub', line: 'concentric rings of sweeping crescents and eye figures', composition: 'radial symmetry spinning around the central spindle hole', texture: 'smooth-turned wood, low carved relief, hand-polished wear' },
    typ: { display: 'concentric ring letterforms circling a central dot', body: 'even-spun monoline sans with crescent finials' },
    lit: { quality: 'even display-case lighting on turned wood', temperature: 'warm-toned', shadow: 'shallow relief rings shade as the disc turns' },
    ui: { background: 'pale straw maple tan', surface: 'spinning-whorl loader rings', components: 'radial dial selectors', motion: 'whorl spinning up on page load' },
  },
  {
    slug: 'edenshaw-era-silver-engraving',
    ctx: "In the late 19th century, Haida and Tlingit smiths engraved Northwest Coast crests into trade silver bracelets and pendants, serving both regalia and the curio trade. Charles Edenshaw (c. 1839–1920) of Haida Gwaii — celebrated in 1902 as the best carver in wood and stone then living — set the era's standard, adapting formline design to fine chasing and engraving that made silver a modern channel for ancient crests.",
    vd: { shape: 'flat bracelet and pendant planes wrapped around the wrist', line: 'fine engraved formlines chasing ovoids across polished metal', composition: 'crest scenes banded around continuous cuff circumference', texture: 'burnished silver sheen, crisp incised grooves, dark oxidized lines' },
    typ: { display: 'engraved-line serif caps with chased formline flourishes', body: 'cool metallic-toned sans with thin engraved rules' },
    lit: { quality: 'jeweler-lamp specular gleam on silver', temperature: 'cool-toned', shadow: 'engraved lines darken into sharp hairline shadows' },
    ui: { background: 'cool coin-silver grey', surface: 'engraved cuff-band headers', components: 'chased-line dividers', motion: 'crest designs etching themselves in' },
  },
  {
    slug: 'lakota-floral-beadwork',
    ctx: "Floral beadwork spread across the Plains from Great Lakes mission-era teaching, where Ursuline nuns introduced flower patterns that Indigenous women made their own; Lakota women developed it into a prized regional style. Glass seed beads, line-and-fill sewn, cover dresses, moccasins, vests and cradleboards with roses, leaves and vines against dark hides — a flowering of the prairie that turns clothing into regalia for powwows and giveaways.",
    vd: { shape: 'rounded blossom and vine clusters covering garment planes', line: 'bead-row outlines with smooth line-and-fill shading', composition: 'symmetric floral bouquet across yokes, moccasin insteps, cradles', texture: 'glass seed-bead gloss, tight sinew rows, dark hide ground' },
    typ: { display: 'flourished floral display script with leaf terminals', body: 'friendly rounded sans over dark hide grounds' },
    lit: { quality: 'bright dance-ground sun on bead gloss', temperature: 'warm-toned', shadow: 'bead domes shade into tiny highlight-and-shadow sparkle' },
    ui: { background: 'dark smoked-hide brown', surface: 'beaded-yoke header cards', components: 'flower-cluster badges', motion: 'vines stitching across on scroll' },
  },
  {
    slug: 'kinngait-printmaking',
    ctx: "Kinngait (Cape Dorset until 2020) calls itself the Capital of Inuit Art. James Houston set up a graphic arts workshop there in 1957, teaching carvers to cut stone-block prints; the West Baffin Eskimo Cooperative, co-founded by Houston and Kananginak Pootoogook in 1959, has issued an annual print collection ever since — tens of thousands of prints between 1959 and 1974 alone. Kenojuak Ashevak's bold owls became among Canada's most beloved images.",
    vd: { shape: 'flat rounded creatures and birds filling the sheet', line: 'cut stoneblock edges leaving crisp gouged contours', composition: 'single emblematic animal centered on open paper field', texture: 'stonecut grain and stencil color flats on paper tooth' },
    typ: { display: 'bold stonecut block caps with rough gouged edges', body: 'clear utilitarian sans with Inuktitut syllabics alongside' },
    lit: { quality: 'arctic studio daylight over paper flats', temperature: 'cool-toned', shadow: 'inked blocks print shadows as flat graphic fields' },
    ui: { background: 'print-paper warm white', surface: 'edition-sheet gallery cards', components: 'numbered-edition chips', motion: 'block-print press-stamp reveals' },
  },
  {
    slug: 'inuit-soapstone-carving',
    ctx: "Carving is Inuit art's oldest impulse: walrus ivory once fed the engraver's tools; from the mid-20th century, southern markets drew figurative sculpture in soft stone — soapstone, serpentinite, argillite. Carvers across the Arctic reduce bears, birds, mothers and hunters to smooth rounded masses, leaving tool marks and stone veins visible; the work moved from community cooperatives to global galleries, anchored by major collections in Winnipeg.",
    vd: { shape: 'compact rounded animal and figure masses, heads turned to viewer', line: 'few economy contours where mass speaks over line', composition: 'single subject on its own plinth, negative space generous', texture: 'matte to satin stone with veins, scratches and adzen polish' },
    typ: { display: 'smooth rounded display forms like polished stone', body: 'soft grey-toned sans with generous whitespace' },
    lit: { quality: 'single gallery spot sculpting the mass', temperature: 'cool-toned', shadow: 'round bellies shade into deep soft cores' },
    ui: { background: 'soapstone charcoal green-grey', surface: 'plinth-style specimen cards', components: 'stone-swatch chips', motion: 'forms rotating slowly on pedestals' },
  },
  {
    slug: 'amauti-parkas',
    ctx: "The amauti is the Inuit mother's parka of the eastern Canadian Arctic: a woman's outer garment with the amaut, a built-in pouch below the hood where a baby rides against the back until about two years old. Mothers swing the child forward to nurse or tend without exposure to wind and frost, so the parka is at once clothing, cradle and carrier — traditionally sewn from caribou hide with decorative trim, today an emblem of Inuit design ingenuity.",
    vd: { shape: 'voluminous hooded parka with pouch bulge at the back', line: 'piped trim seams framing hood, pouch and hem', composition: 'front view reads plain; profile reveals the carried child', texture: 'soft caribou hide nap, wolverine or ruff trim, embroidered panels' },
    typ: { display: 'hooded display caps with pouch curves under baseline', body: 'warm utilitarian sans with trim-stitch accents' },
    lit: { quality: 'low arctic sun through sea-mist', temperature: 'cool-toned with warm hide accents', shadow: 'hood shade hides the child until profile view' },
    ui: { background: 'caribou tan against snow white', surface: 'profile-toggle garment cards', components: 'mother-and-child paired chips', motion: 'child swinging pouch-to-front' },
  },
  {
    slug: 'yupik-masks',
    ctx: "Yup'ik masks of southwestern Alaska are shamanic sculpture: carved wood faces assembled with appendages, feathers and articulated parts, painted in few strong colors, guided by the angalkuq (shaman) who instructed the carvers. They ranged from small finger masks and maskettes to ten-kilogram pieces hung from the ceiling or carried by several dancers, embodying story-spirits for winter ceremonies, then often destroyed or traded once used.",
    vd: { shape: 'concave face discs ringed by appendage hoops and feathers', line: 'painted contour bands dividing few bold color zones', composition: 'outer ring satellites orbiting the central spirit face', texture: 'adzed wood grain, flaking pigment, feather and fur attachments' },
    typ: { display: 'totemic mask letterforms with appendage flourishes', body: 'simple painted-wood sans in few colors' },
    lit: { quality: 'qasgiq firelight flickering on hung masks', temperature: 'warm-toned', shadow: 'appendages spin slow shadows on smoke-dark walls' },
    ui: { background: 'smoke-dim qasgiq brown', surface: 'ring-haloed mask frames', components: 'spirit-orbit icon sets', motion: 'masks rocking gently on their hangers' },
  },
  {
    slug: 'qulliq-lamp-aesthetics',
    ctx: "The qulliq is the Arctic's hearth: a shallow soapstone lamp filled with seal oil or blubber, its moss wick lit with a taqqut stick to give light and warmth in a treeless land. The single most important article of furniture in the traditional Inuit dwelling, tended and trimmed by women, it glows inside the dim snow-house dome — soft low amber light, soot-blackened stone rim — the whole visual world of the ice house set around one living flame.",
    vd: { shape: 'long shallow crescent bowl carved from grey soapstone', line: 'rim rising to a lip where the moss wick curls', composition: 'single flame pooling light across the snow dome', texture: 'greasy stone sheen, soot-black rim, molten oil gleam' },
    typ: { display: 'warm glowing display letterforms with flame-lick terminals', body: 'quiet dark-room sans with amber highlights' },
    lit: { quality: 'single low flame as sole light source', temperature: 'warm amber against arctic blue', shadow: 'dome walls shade to black beyond the glow' },
    ui: { background: 'night-snowhouse indigo black', surface: 'hearth-glow gradient panels', components: 'flame-status indicators', motion: 'wick flickering as ambient presence' },
  },
]
