/**
 * Completeness patches r1 — 20 Architectural Style records missing
 * culturalContext + visualDNA + typography. Authored directly (no LLM).
 * Applied via apply-patches.ts; draft entries reaching full depth are
 * promoted to researched.
 */
export const PATCHES: any[] = [
  { slug: 'sudano-sahelian-architecture',
    ctx: 'Sudano-Sahelian building grew from the Sahel corridor between desert and savanna, where West African mason families — notably the Mande guilds credited with Djenné and Timbuktu — fused local banco technique with the demands of trans-Saharan trade towns and Islamic worship. Mali\'s Djenné and Timbuktu, Niger\'s Agadez and northern Nigeria\'s cities kept the style alive; the 1907 Djenné mosque rebuild fixed its canonical look, and annual communal replastering keeps the tradition a living social institution.',
    vd: { shape: 'stepped pyramidal masses with tapering minaret towers', line: 'horizontal toron beam stubs in dense rhythm', composition: 'prayer-wall symmetry buttressed by rounded pylon corners', texture: 'smooth hand-plastered earth over sun-dried brick' },
    typ: { display: 'calligraphic whitewash bands over entry portals', body: 'painted Qur\'anic school slates inside', notes: 'inscriptions refreshed at replastering festivals' },
    lit: { quality: 'hard equatorial glare softened by deep eaves', temperature: 'warm-toned', shadow: 'toron beams stripe every wall daily' },
    ui: { background: 'banco tan with dust gradient', surface: 'plaster-rounded cards', components: 'beam-stub dividers and pylon buttons', motion: 'plaster-spread slow wipes' } },
  { slug: 'indo-saracenic',
    ctx: 'Indo-Saracenic was the British Raj\'s official hybrid: engineered by colonial architects such as Robert Fellowes Chisholm and Vincent Esch for Bombay, Madras and princely states from the 1870s, it married Mughal domes, chhatri kiosks and cusped arches to Victorian steel structure and Gothic massing. Princes commissioned it to broadcast modernity with native legitimacy — Bombay\'s Prince of Wales Museum and Mysore Palace remain textbook cases — and post-independence India kept many as civic landmarks.',
    vd: { shape: 'onion domes over eclectic Gothic-to-Renaissance masses', line: 'cusped arcades on load-bearing masonry', composition: 'symmetric fronts dotted with chhatri kiosks', texture: 'stucco and polychrome stone with iron structure hidden' },
    typ: { display: 'roman capitals paired with Nastaliq cartouches', body: 'Victorian panel lettering', notes: 'bilingual civic inscriptions codified the hybrid' },
    lit: { quality: 'tropical arcade shade', temperature: 'warm-toned', shadow: 'deep jali screens scatter lace light' },
    ui: { background: 'sandstone cream', surface: 'cusped-arch frames', components: 'chhatri-badge icons', motion: 'processional reveals' } },
  { slug: 'naqsh-e-jahan-ensemble',
    ctx: 'Naqsh-e Jahan (Imam) Square was laid out under Shah Abbas I between 1598 and 1629 as the heart of his new Isfahan — a royal promenade linking the Shah Mosque, Sheikh Lotfollah Mosque, Ali Qapu palace and the bazaar portal. Measuring 160 by 560 metres, it staged polo, processions and commerce at Safavid scale, and UNESCO inscribed it in 1979 as the paramount ensemble of Persian urban planning, its architecture still defining Iranian civic space.',
    vd: { shape: 'long rectangular square framed by two-storey arcades', line: 'tiled portal arches towering at each pole', composition: 'four monuments anchored to one plan', texture: 'polychrome haft-rangi tilework over brick' },
    typ: { display: 'monumental thuluth mosaic inscriptions on portal spandrels', body: 'calligraphic tile bands inside domes', notes: 'poet chronograms date each portal' },
    lit: { quality: 'desert noon above arcaded shade', temperature: 'warm-toned', shadow: 'arcade depth frames the turquoise domes' },
    ui: { background: 'tile-blue gradient', surface: 'arcade-arch cards', components: 'portal-frame buttons', motion: 'procession-scroll pans' } },
  { slug: 'sidi-bou-said-style',
    ctx: 'Sidi Bou Said standardized its blue-and-white look in the 1920s when artist and preservationist Rodolphe d\'Erlanger had the Tunisian cliff village painted in the now-canonical white lime wash and cobalt blue trim, codifying a Tunisian-Andalusi tradition of door studs, mashrabiya and arched loggias. Tunisian law protects the palette, and the village became North Africa\'s postcard — an authored vernacular that resorts worldwide imitate.',
    vd: { shape: 'cubic white houses stepping down the cliff', line: 'cobalt outlines tracing arches and lintels', composition: 'door and window as decorated focal points', texture: 'lime-wash chalk over stucco, black iron accent' },
    typ: { display: 'black-lettered shop and café signs', body: 'Arabic street inscriptions', notes: 'blue-on-white lettering follows the architecture' },
    lit: { quality: 'Mediterranean glare off white walls', temperature: 'cool-toned', shadow: 'cobalt frames read as permanent shadow' },
    ui: { background: 'lime white', surface: 'blue-trimmed cards', components: 'stud-dot buttons', motion: 'sea-breeze gentle sways' } },
  { slug: 'banco-masonry',
    ctx: 'Banco masonry — sun-dried mud brick set in earth mortar and finished in smooth plaster — is the load-bearing technology of the West African Sahel, maintained by mason lineages for centuries and refreshed seasonally by whole communities. From Djenné houses to mosque walls across Mali, Burkina Faso and northern Nigeria, banco answers the Sahel\'s extremes: thermal mass against heat, materials from the field itself, and repair built into yearly ritual.',
    vd: { shape: 'rounded masses with soft bull-nosed edges', line: 'few — mass carries the design', composition: 'thick walls with small punched openings', texture: 'hand-smoothed clay, straw temper flecks' },
    typ: { display: 'whitewash calligraphy at thresholds', body: 'none — oral building knowledge', notes: 'mason guilds transmit by apprenticeship' },
    lit: { quality: 'dawn and dusk long raking light', temperature: 'warm-toned', shadow: 'every hand-smoothing ripple shows' },
    ui: { background: 'wet-clay brown drying to tan', surface: 'rounded-corner cards', components: 'brick-bond icons', motion: 'monsoon-cycle color shifts' } },
  { slug: 'ise-shrine-shinden',
    ctx: 'Ise Jingu\'s shinden architecture preserves Japan\'s oldest shrine form through the Shikinen Sengu: every twenty years since 690 CE the entire shrine — inner sanctum, treasure houses, bridges — is rebuilt on adjacent plots in unhewn cypress with gold-tipped chigi and katsuogi ridge logs. The ritual rebuild copies the 7th-century state, making Ise a machine for transmitting pre-Buddhist architecture; carpenters train their careers against one rebuild.',
    vd: { shape: 'rectangular honden raised on stilted piles', line: 'chigi crossed finials and katsuogi ridge weights', composition: 'single gable entrance axis, veranda ring', texture: 'unpainted hinoki bark and plank surfaces' },
    typ: { display: 'shrine name plaques in lacquer and gold', body: 'none — ritual space keeps text minimal', notes: 'shimenawa rope and paper streamers carry meaning' },
    lit: { quality: 'filtered forest canopy light', temperature: 'neutral-toned', shadow: 'veranda shadows measure the day' },
    ui: { background: 'cypress cream', surface: 'bark-texture cards', components: 'chigi-cross icons', motion: 'rebuild-cycle crossfades' } },
  { slug: 'majlis-reception',
    ctx: 'The majlis — literally "place of sitting" — is the reception heart of Arab and wider Islamic social life, from Bedouin tents to Ottoman-era Damascene houses to Gulf palaces, where a ruler or elder receives petitioners, hosts poets and settles disputes. UNESCO inscribed the majlis as living heritage in 2015; contemporary Gulf majlises still stage weekly audiences beside qahwa service, keeping governance, hospitality and architecture fused.',
    vd: { shape: 'long narrow rooms of wall-to-wall floor seating', line: 'arched niches and wall recesses', composition: 'host seat at head, guests in ranked U', texture: 'carpet depth, cushion rows, low tables' },
    typ: { display: 'calligraphic panels above the host seat', body: 'poetry recited rather than posted', notes: 'nabati verse is the majlis currency' },
    lit: { quality: 'evening lantern and chandelier warmth', temperature: 'warm-toned', shadow: 'mashrabiya lace at dusk' },
    ui: { background: 'deep carpet red-brown', surface: 'cushion-tone cards', components: 'dallah-coffee icons', motion: 'welcome-sweep arcs' } },
  { slug: 'falu-red-farmstead',
    ctx: 'Falu red — copper-mine sludge pigment cooked into linseed paint — turned Sweden\'s farmhouses, barns and manors a single crimson from the 1700s, when Falun\'s Stora Kopparberg mine supplied a national economy of timber buildings needing preservation. 19th-century National Romantic writers made the red cottage an emblem of Swedish identity, and heritage practice now guards the hue on farmsteads across the country.',
    vd: { shape: 'long timber gable houses under pitched roofs', line: 'white window frames as counterline', composition: 'clustered yard: dwelling, barn, storehouse', texture: 'matte iron-oxide paint over sawn plank' },
    typ: { display: 'painted farm name boards at gates', body: 'dates and owner initials carved over doors', notes: 'vernacular lettering for farm signs' },
    lit: { quality: 'low Nordic sun through mist', temperature: 'cool-toned', shadow: 'snow doubles every red wall\'s glow' },
    ui: { background: 'falu red field', surface: 'white-trim cards', components: 'gable icons', motion: 'season-swap crossfades' } },
  { slug: 'chichen-itza-puuc-style',
    ctx: 'Chichén Itzá fused Puuc hills masonry with Toltec-influenced forms in the Terminal Classic era (roughly 800-1100 CE), when the city dominated Yucatán trade and pilgrimage. Elite buildings — El Castillo pyramid-temple, the Warriors\' temple with its Chacmool altar, the largest ballcourt in Mesoamerica — carried Maya calendar symbolism and feathered-serpent cults at imperial scale; the site anchored Maya-Toltec interaction and remains Mexico\'s most visited monument.',
    vd: { shape: 'nine-tiered radial pyramid platforms', line: 'serpent balustrades running down stairways', composition: 'cardinal-aligned temple crowns over colonnaded courts', texture: 'drystone veneer mosaic over rubble core' },
    typ: { display: 'Maya glyph blocks carved on lintels and benches', body: 'inscribed dates of dedication', notes: 'glyphic texts name rulers and K\'atun endings' },
    lit: { quality: 'tropical zenith sun', temperature: 'warm-toned', shadow: 'equinox serpent-shadow plays down El Castillo' },
    ui: { background: 'limestone cream', surface: 'mosaic-panel cards', components: 'glyph-block icons', motion: 'calendar-wheel rotations' } },
  { slug: 'wharenui',
    ctx: 'The wharenui — Māori meeting house — crystallized in the 1840s-70s as Ngāpuhi and other iwi responded to land loss and mission schooling with monumental carved houses serving as tribal parliament, chapel and genealogy. Its ridgepole is an ancestor\'s spine, the porch face an ancestor\'s body; inside, poupou carvings name descent lines. Princess Te Puea Herangi\'s Tūrangawaewae revival and marae building nationwide keep the form central to Māori life.',
    vd: { shape: 'ridgepole body with spread-armed bargeboards', line: 'koru spiral carving over every surface', composition: 'ancestor front, genealogy ranks inside', texture: 'carved totara dark wood, woven tukutuku panels' },
    typ: { display: 'house name in carved lintel (pare) or painted mahau', body: 'whaikorero oratory inside', notes: 'names and genealogies spoken, not written' },
    lit: { quality: 'low lamplight of night meetings', temperature: 'warm-toned', shadow: 'koru relief pools deep shadow' },
    ui: { background: 'carved-brown gradient', surface: 'tukutuku-weave cards', components: 'koru-spiral icons', motion: 'whakairo-carve reveals' } },
  { slug: 'brazilian-colonial-architecture',
    ctx: 'Portuguese colonial building in Brazil — from 16th-century Olinda through the 18th-century Minas Gerais gold towns — adapted Lisbon\'s baroque and convent plainness to tropical scale, with thick whitewashed walls, azulejo tile facades, and wood ceilings against humidity. Aleijadinho\'s Ouro Preto churches crown the tradition; UNESCO-listed Ouro Preto, Olinda and Paraty preserve whole urban fabrics of the style.',
    vd: { shape: 'steep-roofed white blocks around church-heavy squares', line: 'cartouche pediments over doors', composition: 'terrace-and-hill stacking, churches at crest', texture: 'limewash, blue azulejo panels, carved soapstone frames' },
    typ: { display: 'painted cartouche name panels over portals', body: 'tile-picture narratives on facades', notes: 'azulejo scenes substitute for signage' },
    lit: { quality: 'high tropic glare', temperature: 'warm-toned', shadow: 'deep window reveals cool interiors' },
    ui: { background: 'limewash white', surface: 'azulejo-frame cards', components: 'pediment-scroll icons', motion: 'procession-climb verticals' } },
  { slug: 'french-colonial-architecture',
    ctx: 'French colonial building — from Caribbean plantation houses through Pondicherry\'s quarters to Hanoi\'s Indochinese villas — adapted French Beaux-Arts and Provençal habits to colonial climates with arcaded ground floors, louvered verandas and later tropical modernist experiments. Hanoi\'s French Quarter, Saigon\'s Opera and Dakar\'s plateau districts show the range; decolonization turned many administrative ensembles into national landmarks and conservation battlegrounds.',
    vd: { shape: 'two-storey blocks with continuous veranda bands', line: 'arched colonnades and tall shutter bays', composition: 'courtyard cores, garden fronts', texture: 'plaster render, iron balcony work, louver wood' },
    typ: { display: 'engraved administration plaques in roman caps', body: 'street-name enamel plates', notes: 'bilingual signage marked colonial order' },
    lit: { quality: 'veranda-filtered afternoon', temperature: 'warm-toned', shadow: 'shutter slats stripe the rooms' },
    ui: { background: 'colonial cream', surface: 'louver-texture cards', components: 'arch-column icons', motion: 'shutter-fold transitions' } },
  { slug: 'centrally-planned-church',
    ctx: 'The centrally-planned church — round, octagonal or cross-in-square — descends from Roman mausolea and Byzantine practice, matured in the Greek-cross churches of Constantinople and the Balkans, and reached its Renaissance apotheosis in Brunelleschi\'s Pazzi Chapel and da Vinci\'s ideal-church drawings. Its geometry argued theology: the dome as heaven over a unified congregation, versus the processional Latin cross.',
    vd: { shape: 'dome over drum on square or octagon base', line: 'radial pendentive geometry', composition: 'altar at center or east of a unified volume', texture: 'brick and stone courses, mosaic fields' },
    typ: { display: 'mosaic and fresco inscriptions ringing the dome', body: 'liturgical texts in apse medallions', notes: 'Christ Pantocrator gazes from the center' },
    lit: { quality: 'dome-ring window shafts', temperature: 'neutral-toned', shadow: 'golden mosaic darkness beneath' },
    ui: { background: 'gold-mosaic depth', surface: 'medallion cards', components: 'cross-in-square icons', motion: 'dome-orbit slow spins' } },
  { slug: 'fujian-tulou',
    ctx: 'Fujian tulou — rammed-earth compounds of the Hakka and other communities — grew between the 15th and 20th centuries in southwest Fujian\'s hill country, housing whole clans behind walls up to five storeys thick for defense against banditry. One courtyard, one gate, concentric rings of rooms around ancestral halls; UNESCO listed 46 tulou in 2008, and village clusters like Yongding and Nanjing keep them in daily use.',
    vd: { shape: 'circular or square mega-rings, inward-facing', line: 'eave rings stepping concentrically', composition: 'ancestral hall at core, rooms stacked outward', texture: 'rammed earth bands, timber galleries, grey tile roofs' },
    typ: { display: 'calligraphic hall names over shrine doors', body: 'couplet boards on room columns', notes: 'clan mottos carved at the gate' },
    lit: { quality: 'courtyard-well daylight from above', temperature: 'warm-toned', shadow: 'ring shadows circle with the sun' },
    ui: { background: 'earth-ring brown', surface: 'tile-grey cards', components: 'ring-radial icons', motion: 'gate-entry zooms' } },
  { slug: 'kalinga-deul-style',
    ctx: 'The Kalinga deul — the towering rekha shikhara of Odisha\'s temples, from Parasurameswara (7th c.) to Lingaraja and Konark\'s Sun Temple (13th c.) — developed a Nagara idiom of its own: curvilinear towers rising in horizontal pagas, carved chaitya windows, and jagamohana porches in front. Temple-building under the Eastern Ganga kings made Bhubaneswar a city of shrines; Konark\'s stone wheel-dials remain its signature.',
    vd: { shape: 'curvilinear deul towers over porch boxes', line: 'vertical paga ribs and chaitya-window rows', composition: 'axis from aruna pillar to sanctum', texture: 'khondalite sandstone deep relief' },
    typ: { display: 'Sanskrit donative inscriptions on temple walls', body: 'pilgrim graffiti across centuries', notes: 'epigraphs name patrons and dates' },
    lit: { quality: 'morning monsoon gold', temperature: 'warm-toned', shadow: 'paga ribs stripe the tower' },
    ui: { background: 'sandstone gold-brown', surface: 'chaitya-window frames', components: 'wheel-dial icons', motion: 'nagara-curve ascents' } },
  { slug: 'riad-architecture',
    ctx: 'The riad — Moroccan courtyard house with an inner garden — matured in Marrakesh and Fez\'s medinas as Islamic family law and climate demanded inward privacy: blind walls outside, orange trees and fountains inside under high ceilings, with zellij tile, carved cedar and tadelakt plaster. Restoration booms from the 1990s turned hundreds into guest houses, exporting the riad as a global hospitality template.',
    vd: { shape: 'inward-facing ring of rooms around square court', line: 'horseshoe arcades on cedar columns', composition: 'garden core, symmetric gallery, roof terrace above', texture: 'zellij mosaic, tadelakt sheen, carved stucco' },
    typ: { display: 'painted calligraphic medallions at entry', body: 'proverb inscriptions over fountain basins', notes: 'bismillah panels guard thresholds' },
    lit: { quality: 'courtyard well of light, rooms dim behind', temperature: 'warm-toned', shadow: 'stucco lace casts moving lace' },
    ui: { background: 'tadelakt wax green-blue', surface: 'zellij-pattern cards', components: 'fountain-tile icons', motion: 'courtyard-well zooms' } },
  { slug: 'lafte-log-construction',
    ctx: 'Lafté — Norwegian laftebygg — is Scandinavia\'s medieval log-building tradition: round logs scribed into saddled notches so walls settle tight without nails, from stave-church precursors to 18th-century seter cabins and storehouses. Migrants carried it across the American frontier Midwest, and today Norwegian conservation carpenters still teach scribe-fit notching as living heritage.',
    vd: { shape: 'stacked round-log walls under heavy sod or shingle roofs', line: 'horizontal log courses with protruding notch ends', composition: 'single-room cores with loft cross-sections', texture: 'adzed log faces, tar-black chinking lines' },
    typ: { display: 'runes and owner marks on door lintels', body: 'carved year dates on gables', notes: 'build-date carving is a strong custom' },
    lit: { quality: 'low through small windows', temperature: 'warm-toned', shadow: 'log courses stripe interiors' },
    ui: { background: 'tar-brown gradient', surface: 'log-grain cards', components: 'notch-joint icons', motion: 'settle-stack easing' } },
  { slug: 'rayonnant',
    ctx: 'Rayonnant Gothic — the court style of Louis IX\'s Paris from the 1230s to mid-1300s — thinned structure toward glass: Sainte-Chapelle\'s walls nearly vanished into windows, Notre-Dame\'s transept facades opened into rose lattices, and radiating tracery gave the style its name. Architect Pierre de Montreuil led the key works; the style spread to León and Cologne before Flamboyant superseded it.',
    vd: { shape: 'skeletal stone frames over vast glass fields', line: 'bar tracery in radiating rose patterns', composition: 'wall reduced to buttress pier and window', texture: 'polychrome glass over slender masonry' },
    typ: { display: 'inscribed donor bands under rose windows', body: 'scholarly marginalia of cathedral schools', notes: 'glass cycles read as books for the illiterate' },
    lit: { quality: 'stained-glass saturation', temperature: 'cool-toned', shadow: 'structure nearly immaterial in color' },
    ui: { background: 'glass-blue wash', surface: 'tracery-lace frames', components: 'rose-window icons', motion: 'light-wheel rotations' } },
  { slug: 'prodigy-house',
    ctx: 'Prodigy houses — the enormous show-palaces of Elizabethan and Jacobean England (Longleat, Burghley, Hardwick Hall, Hatfield) — were built by courtier-competitors between the 1550s and 1620s to lodge the monarch\'s progress and broadcast new money. Symmetric E-plans, enormous glass walls ("Hardwick Hall, more glass than wall"), and Renaissance detail by master masons like Robert Smythson made them England\'s first architect-led country houses.',
    vd: { shape: 'towered symmetric blocks with huge mullioned fronts', line: 'strapwork parapets and bay-window stacks', composition: 'state rooms ranged around courtyards and long galleries', texture: 'cut stone, glass grids, plaster strapwork inside' },
    typ: { display: 'family mottos in carved strapwork cartouches', body: 'inventory and progress documents', notes: 'ES initials crowned Hardwick by Bess of Hardwick' },
    lit: { quality: 'long-gallery window light', temperature: 'neutral-toned', shadow: 'mullion grids pattern every floor' },
    ui: { background: 'stone grey-green', surface: 'mullion-grid cards', components: 'strapwork-knot icons', motion: 'progress-arrival reveals' } },
  { slug: 'churrigueresque',
    ctx: 'Churrigueresque — Spanish and Mexican Ultra-Baroque named for the Churriguera family of Salamanca sculptors — piled estípite pilasters, inverted obelisks, saints and vines over retablos and church facades from the 1680s to mid-1700s. Mexico City\'s Sagrario Metropolitano, Oaxaca\'s La Soledad and Taxco\'s Santa Prisca show its colonial apex; the style signaled Counter-Reformation triumph and silver-rich patronage.',
    vd: { shape: 'facade fields overgrown with pilaster tabernacles', line: 'estípite inverted-obelisk shafts', composition: 'frames devour the walls behind them', texture: 'polychrome stone, gilt wood retablos' },
    typ: { display: 'Latin dedications across broken pediments', body: 'indulgence inscriptions beside doors', notes: 'icon programs read devotionally upward' },
    lit: { quality: 'gold altarpiece candle blaze', temperature: 'warm-toned', shadow: 'every volute hooks its own shade' },
    ui: { background: 'gilded baroque depth', surface: 'volute-frame cards', components: 'estipite-shaft icons', motion: 'cascade-scroll flourishes' } },
]
