/**
 * Completeness patch r4d — Oceania (barkcloth, quilting, pandanus) + Native American Southwest (20).
 * Hand-authored (Task 4-d); facts Wikipedia-API-verified; no LLM involvement.
 * Fills ctx + visualDNA + typography + lighting + uiTranslation.
 */
export const PATCHES: any[] = [
  {
    slug: 'toghu',
    ctx: 'Toghu (atoghu) is the royal beadwork of the Cameroon Grassfields, the Bamileke and Bamum courts. Coiled raffia and cloth forms are wrapped in thousands of glass beads — red dominant on black, with white accents — worked into medallions, horns, birds and leopards. Crowns, capes, pipes and staffs belong to the fon and honored notables, worn at annual dances and inherited as titles pass; beading density signals rank within the kingdom.',
    vd: { shape: 'crowned, caped forms massed in raised bead relief', line: 'two-color geometric banding across black grounds', composition: 'central medallions ringing with horn and leopard motifs', texture: 'glass-bead convexity over coiled raffia and cloth' },
    typ: { display: 'regal beaded serif caps with medallion terminals', body: 'warm text serif on deep black grounds' },
    lit: { quality: 'ceremonial courtyard light on beadwork', temperature: 'hot red undertones', shadow: 'bead rows throwing tight dark grout lines' },
    ui: { background: 'near-black cloth ground', surface: 'beaded medallion panels in crimson and white', components: 'medallion badges and rank-band accents', motion: 'bead shimmer rippling across panels' },
  },
  {
    slug: 'hollandais-wax',
    ctx: 'Hollandais wax is the premium grade of the Dutch wax print, the resin-resist cotton the Netherlands has shipped to West Africa since the nineteenth century — Vlisco of Helmond, founded 1846, remains its standard-bearer. Molten wax is stamped on both faces, dyes crack through in marbled veins, and every bolt carries a named design with a story. Identical pattern on both faces and deep saturated color suit full wrappers and made-to-match ensembles.',
    vd: { shape: 'six-yard bolts and wrapper ensembles, pattern edge to edge', line: 'wax-resin crackle veins threading the motif', composition: 'named repeat designs centered on shoulders and hips', texture: 'dense cotton hand with marbled dye breakthrough' },
    typ: { display: 'bold trade lettering with wax-crackled edges', body: 'rounded humanist sans on saturated prints' },
    lit: { quality: 'crisp market daylight on taut cotton', temperature: 'saturated warm', shadow: 'soft folds shadowing the crackle veins' },
    ui: { background: 'wax-print primary hue', surface: 'crackle-veined pattern cards', components: 'named-design tags and selvedge badges', motion: 'pattern unrolling like a bolt at auction' },
  },
  {
    slug: 'obroni-wawu',
    ctx: 'Obroni wawu — Akan for \'dead white man\'s cloth\' — is what Ghanaians call the bales of secondhand clothing arriving from Europe and North America. Bales are opened and auctioned at Accra\'s Kantamanto, West Africa\'s largest secondhand market, where traders sort and restyle cast-offs into a busy resale economy. The name carries wit and unease: thrifted fashion feeds Ghanaian style while burying local mills under imported cloth.',
    vd: { shape: 'plastic-wrapped bales split into tall sorted stacks', line: 'hanging rails and folded towers in long aisles', composition: 'stall grids where auctions fan garments overhead', texture: 'pre-worn cottons, pressed wax prints, sun-faded corduroy' },
    typ: { display: 'market-chalk stencil caps, repurposed', body: 'utilitarian sans like bale labels' },
    lit: { quality: 'high tropical noon over open stalls', temperature: 'warm-toned', shadow: 'tarp shade striping the sorted stacks' },
    ui: { background: 'bale-paper kraft tan', surface: 'sorted stacks of thrifted prints', components: 'bale tags and size-chip tickets', motion: 'bales splitting open, garments fanned out' },
  },
  {
    slug: 'commemorative-wax-prints',
    ctx: 'Commemorative wax prints turn cloth into a public monument across West Africa. Mills and traders issue named designs marking independence days, state visits, elections and beloved figures, printing slogans along the selvedge so the message travels with the cloth. Bought as gifts and stored like heirlooms, these repeats circulate portraits, flags and crests through dress, letting wearers carry a milestone on their shoulders.',
    vd: { shape: 'wrapper lengths banded with emblem medallions', line: 'flag ribbons, crest shields and portrait roundels', composition: 'hero motif repeated in strict print-grid alignment', texture: 'crisp factory cotton with dense color fills' },
    typ: { display: 'selvedge banner caps with ribbon rules', body: 'clear grotesque for dedication lines' },
    lit: { quality: 'even cloth-hall light', temperature: 'flag-bright warmth', shadow: 'crisp folds over the emblem medallions' },
    ui: { background: 'cloth-of-gold festive ground', surface: 'emblem repeat panels', components: 'selvedge slogan strips and crest chips', motion: 'emblem repeats scrolling like a parade' },
  },
  {
    slug: 'tongan-ngatu',
    ctx: 'Ngatu is Tonga\'s barkcloth: sheets of paper-mulberry bast felted into great continuous panels and decorated by rubbing red-brown and black dyes over kupesi, tablets carrying raised family patterns. Women beat, join and paint the cloth communally, layering stencilled diamonds, wheels and leaves. Ngatu is the supreme gift at weddings, funerals and investitures, presented in rolled bundles that display lineage and chiefly honor.',
    vd: { shape: 'very long joined panels, rolled and shouldered', line: 'kupesi rubbings in rows of diamonds and wheels', composition: 'pattern grid marching the full length of the cloth', texture: 'beaten bark felt with stencilled dye uptake' },
    typ: { display: 'bark-brown caps with kupesi-block edges', body: 'gentle serif on cream barkcloth' },
    lit: { quality: 'diffused fale daylight on spread cloth', temperature: 'warm ocher', shadow: 'long panel shadows over the beaten bark' },
    ui: { background: 'barkcloth cream', surface: 'kupesi grid panels in umber and black', components: 'pattern-block dividers and gift-band ribbons', motion: 'dye rub developing across kupesi rows' },
  },
  {
    slug: 'samoan-siapo',
    ctx: 'Siapo is Samoa\'s barkcloth, made from the bast of the paper mulberry and finished two ways: printed with upeti, carved pattern boards rubbed with dye, or hand-painted as siapo mamanu. Bark and root dyes give browns, blacks and rusts; designs set family motifs, plants and ocean forms into grids of diamonds and leaves. Beaten, printed and squared by women, siapo dresses the body in ceremony and marks births, marriages and chiefly gifting.',
    vd: { shape: 'squared barkcloth sheets, edges clipped true', line: 'diamond and leaf grids inked from upeti boards', composition: 'central field quartered by crossing pattern bands', texture: 'soft beaten bast drinking up rust-brown dye' },
    typ: { display: 'hand-painted caps with diamond joins', body: 'soft island serif on ocher grounds' },
    lit: { quality: 'bright lagoon-side daylight', temperature: 'rust-warm', shadow: 'soft wrinkle shadows across the printed bark' },
    ui: { background: 'rust-brown dye wash', surface: 'diamond-grid siapo panels', components: 'upeti-block chips and family-motif markers', motion: 'patterns printing across the sheet' },
  },
  {
    slug: 'hawaiian-kapa',
    ctx: 'Kapa is Hawaiian barkcloth, beaten from the bast of the wauke plant with grooved ʻiʻe kūkū beaters until thin, soft and scented, then dyed and patterned. Makers stamp geometric repeats with carved bamboo tools and paint freehand, using dyes of kukui soot, ocher clays and plant juices. Once the islands\' clothing, bedding and ceremony cloth, kapa nearly vanished after imports arrived and now lives on through revival makers.',
    vd: { shape: 'felted sheet lengths, loincloth and bedcover forms', line: 'stamped geometric rows from carved bamboo tools', composition: 'banded repeats framing freehand dyed fields', texture: 'groove-felted surface, watermark ridges, matte dye' },
    typ: { display: 'stamped repeat caps from bamboo stamp tools', body: 'organic humanist serif in kapa-dyed tones' },
    lit: { quality: 'soft trade-wind daylight', temperature: 'plant-dye warmth', shadow: 'felted ridges shading faintly' },
    ui: { background: 'undyed kapa buff', surface: 'geometric stamp rows in kukui browns', components: 'bamboo-stamp toggles and cord ties', motion: 'stamp rows pressing in rhythm' },
  },
  {
    slug: 'cook-islands-tivaevae-quilting',
    ctx: 'Tivaevae — the word means \'patches\' — is the Cook Islands\' cherished quilting art, learned from missionary-era sewing and made local by Polynesian women. Vainetini, women\'s sewing circles, gather to stitch, sing and trade village news while turning imported cotton into bold patchwork and appliqué of island flowers, leaves and birds. Quilts are given at weddings and funerals and displayed on walls, serving as visible wealth and tokens of love.',
    vd: { shape: 'full-bed quilts and hung wall pieces', line: 'appliqué edges traced in rows of tiny stitches', composition: 'great bloom motifs filling white grounds', texture: 'soft imported cotton, trapunto puff, dense hand-quilting' },
    typ: { display: 'friendly script caps like sewing-circle notes', body: 'light serif on quilted white' },
    lit: { quality: 'veranda daylight through pandanus shade', temperature: 'island-warm', shadow: 'quilt-stitch shadows stippling the field' },
    ui: { background: 'quilted white ground', surface: 'appliqué flower cards in vivid cottons', components: 'stitch-dash borders and vainetini badges', motion: 'stitches tracing echo outlines outward' },
  },
  {
    slug: 'hawaiian-snowflake-quilts',
    ctx: 'Hawaiian snowflake quilting fuses New England needlework taught by nineteenth-century missionaries with the islands\' own kapa tradition. A single design is cut from cloth folded like a paper snowflake — usually native leaves, breadfruit or taro — and appliquéd in two bold colors on a white ground, then quilted with fine echo contours that ripple outward like waves. Each quilt is one maker\'s design, rarely repeated, treated as an heirloom.',
    vd: { shape: 'radial snowflake medallions filling the quilt top', line: 'echo quilting following every appliqué contour', composition: 'single central motif mirrored eight ways from a fold', texture: 'smooth two-color cotton with ridged stitch waves' },
    typ: { display: 'elegant caps with appliqué-point terminals', body: 'quiet serif like museum quilt labels' },
    lit: { quality: 'even gallery light on cotton', temperature: 'cool greens over warm woods', shadow: 'echo quilting casting soft ridged shadows' },
    ui: { background: 'white quilt ground', surface: 'two-color snowflake medallion cards', components: 'leaf-cut badges and echo-stitch dividers', motion: 'medallion unfolding like opened folded cloth' },
  },
  {
    slug: 'lauhala-pandanus-weaving',
    ctx: 'Lauhala weaving works the leaves of the hala tree (Pandanus tectorius) — lau, leaf — into the everyday matting of Pacific island life. Leaves are stripped, dried, rolled and split into ribbons, then plaited into checkerboard weaves for floor mats, pillows, baskets, hats and once sails. The craft remains a living household art across Hawaii and Polynesia, with sleeping mats rolled each morning and hats worn against the sun.',
    vd: { shape: 'flat mats, hats and basket forms of plaited strips', line: 'diagonal and checkerboard interlace edges', composition: 'weave grid carrying tone bands across the sheet', texture: 'stiff dried leaf ribbons, glossy tops, rolled seams' },
    typ: { display: 'woven-strip caps interlaced like lauhala', body: 'sturdy humanist sans in dried-leaf tones' },
    lit: { quality: 'bright shade under a hala grove', temperature: 'golden straw warmth', shadow: 'weave ridges striping the mat' },
    ui: { background: 'dried-leaf gold', surface: 'checkerboard plait panels', components: 'plait dividers and basket-chip buttons', motion: 'strips interlacing one weaver at a time' },
  },
  {
    slug: 'two-grey-hills-rugs',
    ctx: 'Two Grey Hills rugs are the connoisseur\'s Navajo weaving, named for the trading-post district where traders George Bloomfield and Ed Davies encouraged the style in the early twentieth century. Woven flat like tapestry, they use only naturally colored wool — blacks, whites, greys, browns — in intricate four-fold symmetric geometry around a central diamond. Fine, tight weft-faced work taking many months, with no dyed yarn in the field.',
    vd: { shape: 'flat rectangular rugs with guarded central diamonds', line: 'stepped terraces and serrated borders in four-fold symmetry', composition: 'intricate medallion geometry inside concentric borders', texture: 'tight weft-faced wool in undyed natural tones' },
    typ: { display: 'engraved serif caps, trading-post ledger style', body: 'bookish serif on natural wool tones' },
    lit: { quality: 'clean high-desert daylight', temperature: 'neutral with wool warmth', shadow: 'weft ridges shading each diamond edge' },
    ui: { background: 'undyed cream wool', surface: 'four-fold diamond panels in grey and brown', components: 'stepped-border trims and post-label chips', motion: 'geometries resolving fold by fold' },
  },
  {
    slug: 'rio-grande-serapes',
    ctx: 'The Rio Grande serape is the long striped wearing-blanket of Hispanic New Mexico and southern Colorado, woven on Spanish-colonial treadle looms in the Rio Grande valley. Valley wool in browns, blacks, creams and vegetal reds is worked into bold horizontal bands, later elaborated with Saltillo-style central diamonds. The Chimayó district, home to the Ortega and Trujillo weaving families, carried the banded-and-medallion style into the tourist era.',
    vd: { shape: 'long rectangular blankets with worn shoulder openings', line: 'bold transverse stripes with sawtooth band edges', composition: 'banded field centered by Saltillo-style diamonds', texture: 'dense wool twill, vegetable-red depth, fringe-true ends' },
    typ: { display: 'band-lettered caps between stripe rules', body: 'old-style serif with dye-lot warmth' },
    lit: { quality: 'adobe-bright Southwest sun', temperature: 'red-warm', shadow: 'long stripe shadows across the wool' },
    ui: { background: 'wool cream with red banding', surface: 'serape stripe cards', components: 'band dividers and Saltillo diamond chips', motion: 'bands scrolling off the loom' },
  },
  {
    slug: 'hopi-overlay-silverwork',
    ctx: 'Hopi overlay is the signature silver of the Hopi mesas. Silversmithing reached Hopi from Zuni teachers by 1890; the style matured in mid-century programs taught by Fred Kabotie and Paul Saufkie, with Victor Coochwytewa among the innovators. Two silver sheets are joined: the upper is sawn into designs — cloud bars, rain, corn — and soldered over a lower sheet whose background is oxidized and matted so the polished figure floats in shadow.',
    vd: { shape: 'buckles, bracelets and pins as flat silver plaques', line: 'sawn symbolic outlines over rain and cloud bars', composition: 'figure silhouette hovering in a darkened field', texture: 'stamped matte texture against mirror-polished tops' },
    typ: { display: 'clean geometric caps cut like overlay silhouettes', body: 'even modernist sans, silver-on-black' },
    lit: { quality: 'hard mesa sun on polished silver', temperature: 'cool metallic', shadow: 'oxidized matte backgrounds deepening each cutout' },
    ui: { background: 'oxidized silver black', surface: 'polished silver overlay panels', components: 'clan-symbol buttons and rain-cloud dividers', motion: 'designs lifting from matte ground on hover' },
  },
  {
    slug: 'maria-martinez-black-on-black-pottery',
    ctx: 'Maria Martinez of San Ildefonso Pueblo, with her husband Julian and son Popovi Da, created the black-on-black ware that made Pueblo pottery world-famous in the early twentieth century. Her gunmetal vessels — turned black in firings smothered to exclude oxygen — carry Julian\'s matte avanyu serpent and feather designs on the gleaming ground. Signed \'Marie\' and later with family names, they entered museums and made blackware the pueblo\'s signature.',
    vd: { shape: 'wide-shouldered storage jars, plates and wedding vases', line: 'matte avanyu arcs and feather trails circling the belly', composition: 'painted figure band set on the mirror-black shoulder', texture: 'stone-polished gloss ground against sooty matte design' },
    typ: { display: 'matte glyph caps on polished black bands', body: 'fine serif in gunmetal grey' },
    lit: { quality: 'single-source light sweeping the gloss', temperature: 'neutral-cool', shadow: 'matte paint absorbing light beside mirror slip' },
    ui: { background: 'gunmetal black', surface: 'polished-bowl cards with matte motifs', components: 'avanyu dividers and signature chips', motion: 'motif surfacing matte as light pans across' },
  },
  {
    slug: 'jicarilla-micaceous-clay-pottery',
    ctx: 'Jicarilla Apache potters of northern New Mexico build cooking and serving vessels from micaceous clay dug near Taos and Picuris — sparkle-flecked earth the region\'s Pueblos prized for centuries. Fired without a kiln, the thin-walled ollas hold heat and flavor, mica glinting gold against buff to rust clay. The Jicarilla\'s Ollero band were known as potters by name; micaceous ware fed families through trade and now carries a strong revival.',
    vd: { shape: 'thin-walled ollas and bean pots, coil-built by hand', line: 'smooth unglazed profiles with scraped coil seams', composition: 'plain sparkle fields left to the clay and fire', texture: 'mica flecks glittering through buff to rust body' },
    typ: { display: 'earthy caps with mica-fleck sparkle', body: 'warm slab serif like hand-built walls' },
    lit: { quality: 'low kitchen firelight plus window daylight', temperature: 'golden rust', shadow: 'mica flecks glinting through soft shade' },
    ui: { background: 'buff mica clay', surface: 'sparkle-flecked olla cards', components: 'coil-line dividers and pot-shape chips', motion: 'glint shimmering as panels tilt' },
  },
  {
    slug: 'sandpainting-imagery',
    ctx: 'In Diné (Navajo) healing ceremonies the hataałii singer casts dry paintings from colored sands, crushed stone, charcoal and pollen, drawing sacred figures, rainbows and guardian plants on the hogan floor. The patient sits within the image; at the ceremony\'s close it is destroyed. Carefully altered versions entered the weaving trade as sandpainting rugs, their guardian figures framed by rainbow bars becoming Southwest icons.',
    vd: { shape: 'square sand fields quartered by guardian figures', line: 'rainbow-bar frames and straight ceremonial rays', composition: 'four-fold sacred figures around a patient\'s center', texture: 'grain-fed color, mineral blues, pollen gold, charcoal black' },
    typ: { display: 'pictogram caps echoing guardian figures', body: 'plain sans on sand-neutral grounds' },
    lit: { quality: 'hogan firelight over the sand floor', temperature: 'mineral-warm', shadow: 'raised sand casting crisp grain shadows' },
    ui: { background: 'sand-panel tan', surface: 'guarded figure cards within rainbow bars', components: 'rainbow-bar frames and plant-symbol chips', motion: 'figures dissolving grain by grain at close' },
  },
  {
    slug: 'ganado-red',
    ctx: 'Ganado Red names the deep red style of Navajo rug woven around Ganado, Arizona, where John Lorenzo Hubbell\'s trading post — now Hubbell Trading Post National Historic Site — supplied weavers and shaped the market from the late nineteenth century. The classic Ganado rug blazes red with black, white and grey accents — a central stepped diamond over terraced borders, woven weft-faced in fine wool that made it the benchmark trading-post rug.',
    vd: { shape: 'rectangular rug anchored by one great diamond', line: 'stepped terraces and hooked cross motifs', composition: 'central red diamond over concentric banded borders', texture: 'weft-faced wool with madder-red saturation' },
    typ: { display: 'bold terraced caps over stepped borders', body: 'sturdy serif in trade-ledger black' },
    lit: { quality: 'bright trading-post daylight', temperature: 'madder-red warmth', shadow: 'deep red dye pooling in weft valleys' },
    ui: { background: 'deep madder red', surface: 'stepped-diamond rug cards in black and white', components: 'cross-motif chips and post seals', motion: 'diamonds stepping outward from center' },
  },
  {
    slug: 'zuni-needlepoint',
    ctx: 'Zuni needlepoint strings hundreds of tiny turquoise stones, set point-up in silver bezels, into row-upon-row bracelets and earrings of pure glitter. The style grew in the mid-twentieth century, encouraged by trader C. G. Wallace, who pushed needlepoint and petit point to satisfy demand for light jewelry and keep Zuni smiths ahead of machine-made copies. It extends a Zuni lapidary lineage reaching back to Ancestral Pueblo turquoise work.',
    vd: { shape: 'multi-strand rows of teardrop stones in bezels', line: 'stone rows curving with collar and cuff', composition: 'repeating stone grid climbing the silver frame', texture: 'polished turquoise points in bright bezel channels' },
    typ: { display: 'petite-point caps set in bezel-like frames', body: 'fine sans with turquoise-blue accents' },
    lit: { quality: 'jewel-case spotlight clarity', temperature: 'cool sky-blue over warm silver', shadow: 'bezels ringed with dark reflections' },
    ui: { background: 'deep jet display ground', surface: 'turquoise-row cluster cards', components: 'stone-toggle buttons and row dividers', motion: 'stone rows lighting up strand by strand' },
  },
  {
    slug: 'santa-clara-carved-ware',
    ctx: 'Santa Clara Pueblo is famous for polished blackware and redware with deep carving, a Tewa pottery lineage carried to fame by matriarch Margaret Tafoya (1904–2001), a 1984 National Heritage Fellow. Jars are stone-polished to a mirror, then carved with bear-paw, water-serpent and cloud motifs before firing, so cut areas emerge matte against the shine. Large storage jars with deep carving remain the pueblo\'s hallmark, passed through families.',
    vd: { shape: 'tall storage jars and bowls with swelling shoulders', line: 'deep-cut bear paws, water serpents and cloud bands', composition: 'carved emblem centered below a mirror-polished neck', texture: 'high-gloss slip against matte incised channels' },
    typ: { display: 'deep-carved serif caps with polished ridges', body: 'warm serif on blackware grounds' },
    lit: { quality: 'raking light proving the polish', temperature: 'smoke-warm neutral', shadow: 'carved channels holding matte shadow' },
    ui: { background: 'blackware jet black', surface: 'mirror-polished cards with carved channels', components: 'bear-paw badges and water-serpent dividers', motion: 'carve lines catching light as panels turn' },
  },
  {
    slug: 'mata-ortiz-pottery',
    ctx: 'Mata Ortiz pottery revives the ceramic art of Casas Grandes (Paquimé) in Chihuahua, Mexico, recreated from the 1970s by Juan Quezada and spread through his village to hundreds of potters. Thin-walled ollas are built without a wheel, painted with mineral slips in fine-line geometry, and fired in open runs. Championed early by Spencer MacCallum and Walt Parks, the ware reached fine galleries by the 1990s and sustains the valley today.',
    vd: { shape: 'symmetrical thin-walled ollas and lidded forms', line: 'hair-fine slip lines in broken geometry', composition: 'fine-line registers circling the pot above beast motifs', texture: 'buff clay burnished satin with crisp mineral paint' },
    typ: { display: 'fine-line painted caps on olla curves', body: 'light serif with mineral-ink restraint' },
    lit: { quality: 'patio daylight over open firing', temperature: 'warm clay tones', shadow: 'painted lines sitting flat in soft shadow' },
    ui: { background: 'clay-buff white slip', surface: 'fine-line geometric olla cards', components: 'motif chips and maker-signature tags', motion: 'brush lines finishing stroke by stroke' },
  },
]
