/**
 * Aesthetic Atlas — WORLD CULTURAL TRADITIONS expansion matrix.
 *
 * Purpose: guarantee comprehensive coverage of every world culture's documented
 * aesthetic traditions — crafts, textiles, dress, vernacular architecture,
 * ornament systems, ritual/sacred visual culture, performance dress, folk arts,
 * print/signage cultures, diaspora and modern fusion styles.
 *
 * Every focus names real, documented traditions as anchors for discovery.
 * The LLM documents actual named aesthetics within each cluster — never invented.
 * Format: [category, domain, focus]
 */

export const CULTURAL_BATCHES: Array<[string, string, string]> = [
  // ===================== EAST ASIA =====================
  ['Textile & Craft', 'Japanese Textile & Dyeing Traditions', 'Boro patched cloth, sashiko stitching, aizome indigo dyeing, katazome stencilling, tsutsugaki paste-resist, yuzen dyeing (Kaga and Kyoto), Ryukyu bingata, kogin counted stitch, kurume kasuri ikat, Oshima tsumugi mud-dyed silk, Nishijin brocade'],
  ['Regional & Cultural Tradition', 'Japanese Craft & Mingei Traditions', 'Mingei folk craft movement (Yanagi Soetsu), kintsugi repair, shippo cloisonne, Edo kiriko cut glass, netsuke carving, Wajima and Tsugaru urushi lacquer, kamakura-bori, Suruga bamboo craft, Bizen, Shino, Oribe and Karatsu pottery schools, Kutani overglaze ware'],
  ['Architectural Style', 'Japanese Vernacular & Classical Architecture', 'Sukiya-zukuri teahouse aesthetics, shoin-zukuri, gassho-zukuri minka of Shirakawa-go, Kyoto machiya townhouses, kura dozou storehouses, Ise Shrine shinden form, pagoda architecture, Ryukyu gusuku castles, onsen ryokan bathing architecture'],
  ['Fashion & Dress', 'Japanese Dress & Adornment Traditions', 'Kimono code system (furisode, tomesode, homongi, komon), obi tying styles, yukata, hakama, samurai kacchu armor, maiko and geiko dress, Satsuma buttons, Taisho roman modern dress, Showa kasuri workwear, jabara and haori culture'],
  ['Regional & Cultural Tradition', 'Japanese Graphic & Paper Arts', 'Ise katagami stencil patterns, mon family crests, hinagata-bon pattern books, Edo nishiki-e advertising, matchbox label culture (showa hyakkaten), kamishibai story cards, Japanese matchbook and ticket design, kawaii stationery culture, depachika food display, perfume? omit — stick to listed anchors'],
  ['Music & Sonic Culture', 'Japanese Stage & Festival Visual Culture', 'Kabuki kumadori makeup and stage design, Noh masks and costume (shozoku), bunraku puppet staging, matsuri dashi and Yamaboko float decoration, Awa Odori dance costume, taiko ensemble visual identity, Takarazuka revue feathers and spangles, Showa enka stage styling'],
  ['Regional & Cultural Tradition', 'Japanese Garden & Spatial Aesthetics', 'Karesansui dry gardens, chaniwa tea gardens, kaiyu-shiki stroll gardens, tsubo-niwa courtyard gardens, shakkei borrowed scenery, ikebana schools (Rikka, Chabana, Sogetsu, Ikenobo), bonsai and kokedama, roji path design, engawa transitional space'],
  ['Regional & Cultural Tradition', 'Japanese Tea Ceremony Aesthetics', 'Chanoyu and wabi-cha, raku tea bowls, chashaku bamboo scoops, bokuseki hanging scrolls, chabana simple flowers, mizusashi and kama kettle bronzeware, natsume tea caddies, Kuroda? omit — stick to utensil aesthetics and toriawase combining'],
  ['Regional & Cultural Tradition', 'Ainu Material Culture', 'Attush elm-bark robes, ikarkar embroidery bands, makiri carved sheaths, tamasay shell-and-metal necklaces, morew and aiush pattern motifs, iyomante bear ceremony regalia, kaparamip applique robes, Ainu pattern continuity in modern craft'],
  ['Regional & Cultural Tradition', 'Ryukyuan Visual Culture', 'Bingata resist dyeing, yachimun pottery (Tsuboya, Yomitan), Ryukyu glass, bashofu banana-fiber cloth, hana-ori flower weave, gusuku castle stone architecture, Shuri castle vermilion lacquer, Ryukyuan dance and minyo stage visuals, utaki sacred groves'],
  ['Subculture Style', 'Tokyo Street Style Tribes', 'Harajuku deco, lolita variants (sweet, gothic, classic, ouji), gyaru lineages (kogyaru, ganguro, hime gyaru), mori kei, dolly kei, otome kei, visual kei band dress, boso-zoku tokko-fuku regalia, yankee pompadour culture, forest girl? use mori kei anchors only'],
  ['Textile & Craft', 'Chinese Silk, Brocade & Embroidery Traditions', 'Four embroideries: Su (Suzhou), Xiang (Hunan), Yue (Canton), Shu (Sichuan); Nanjing yunjin gold brocade, Song brocade, Zhuang brocade, Guizhou Miao embroidery, horsetail embroidery of the Shui, Dali Bai tie-dye, kesi silk tapestry cut'],
  ['Regional & Cultural Tradition', 'Chinese Porcelain & Ceramic Traditions', 'Ru, Guan, Ge, Ding and Jun kiln wares, Jingdezhen blue-and-white, doucai and wucai enamels, famille verte and famille rose, Tang sancai lead glazes, Longquan celadon, Cizhou slipware, Dehua blanc de chine, Yixing zisha teapots, Jian ware hare-fur bowls'],
  ['Architectural Style', 'Chinese Vernacular & Regional Architecture', 'Beijing siheyuan courtyards, Huizhou merchant houses with horse-head gables, Fujian tulou rammed-earth rings, Shanxi courtyard compounds, Hakka walled villages, Lingnan arcade qilou, Dong drum towers and wind-rain bridges, Suzhou classical gardens, Shanxi? use Pingyao as anchor'],
  ['Regional & Cultural Tradition', 'Chinese Folk & Paper Arts', 'Jianzhi papercuts, nianhua New Year prints (Yangliuqing, Taohuawu, Mianzhu), piyingxi shadow puppets, Chinese knotting, Weifang kites, Zigong lantern festival craft, dough figurines, Tianjin clay figurine Niren Zhang, tiger-head shoes, cloth tigers'],
  ['Religious & Sacred Art', 'Chinese Sacred & Temple Visual Culture', 'Dunhuang Mogao murals, Yungang and Longmen grotto sculpture, Yongle Gong Daoist murals, ancestral hall ornament, spirit-way statuary (shendao), roof guardian figures, pagoda relic chambers, temple scented? use joss stick and altar codes, silk banner sutra painting'],
  ['Fashion & Dress', 'Chinese Dress & Adornment Traditions', 'Hanfu system (ruqun, shenyi, beizi, aoqun), Qing dragon robes (longpao), Shanghai-tailored qipao cheongsam, dudou bodices, mamianqun horse-face skirts, Miao silver headdresses, Yi jiaxi felt cloaks, chaozhu court bead rows, horseman? use bijia oversleeves anchors only'],
  ['Music & Sonic Culture', 'Chinese Opera & Performance Aesthetics', 'Peking opera lianpu face patterns and mang costumes, Kunqu refined staging, Sichuan bianlian face-changing, Yue opera soft staging, Cantonese opera sequin costumes, Shaanxi shadow puppet carving, yangbanxi model-opera aesthetics, Nuoxi exorcism masks'],
  ['Regional & Cultural Tradition', "Chinese Scholar's Studio Aesthetics", 'Wenfang four treasures (brush, ink, paper, inkstone), Duan and She inkstones, ink cake molding, gongshi scholars rocks, zhuanshi seal carving, huaji? omit — study furniture (jiaoyi, scholar tables), handscroll and album mounting (zhuangbiao), Hongxian? omit — keep listed anchors'],
  ['Textile & Craft', 'Chinese Ethnic Minority Textiles', 'Miao silver and festival embroidery (Leishan, Taijiang), Dong indigo and baby carriers, Liangshan Yi cloaks, Sipsongpanna Dai brocade, Shui horsetail embroidery, Gejia batik, Zhuang brocade, Bouyei tie-and-batik of Guizhou, Maonan? omit — keep listed anchors'],
  ['Textile & Craft', 'Korean Craft & Textile Traditions', 'Bojagi wrapping cloths and jogakbo patchwork, Hansan mosi ramie weaving, maedeup knotwork, najeonchilgi mother-of-pearl lacquer, onggi earthenware, buncheong ware, Goryeo celadon with sanggam inlay, dancheong temple painting, minhwa folk painting, hanji paper and jiseung paper weaving'],
  ['Architectural Style', 'Korean Vernacular Architecture', 'Hanok houses with giwa tile roofs, ondol underfloor heating, sarangchae and anchae gendered courtyards, seowon Confucian academies, Hahoe and Yangdong villages, Bulguksa temple stonework, Hwaseong fortress engineering, choga thatched farmhouse'],
  ['Fashion & Dress', 'Korean Dress & Adornment Traditions', 'Hanbok (jeogori, chima, baji), saekdongot striped childrens dress, norigae pendants, gat horsehair hats, wonsam and hwarot ceremonial wedding robes, gwanbok court dress, binyeo hairpins, dallye hair accessories, noble? use geumbak gold-leaf stamping anchors'],
  ['Music & Sonic Culture', 'Korean Performance & Mask Traditions', 'Talchum mask dances, Hahoe byeolsingut talnori, pansori stage aesthetics, samulnori percussion dress, ganggangsullae circle dance, jongmyo jeryeak court pageantry, namsadang itinerant troupe costume, gwangdae clown patchwork'],
  ['Textile & Craft', 'Tibetan & Himalayan Craft Traditions', 'Thangka painting styles (Menri, Karma Gadri), butter sculpture, Tibetan brocade chuba trim, yak-wool khullu weaving, Bhutanese kushutara kira weaving, Ladakhi perak headdress and pashmina, Sherpa dokhna, Newar paubha painting, Kullu shawls, Naga? use Northeast Indian batch instead'],
  ['Religious & Sacred Art', 'Tibetan Buddhist Visual Culture', 'Sand mandalas, monastery architecture (Potala, Tashilhunpo, Hemis), prayer wheels and lungta flag arrays, cham dance masks and brocade costumes, torma offering sculpture, gau amulets, dzong fortress-temple architecture, tsakli card paintings'],
  ['Architectural Style', 'Himalayan Vernacular Architecture', 'Ladakhi rammed-earth and mud-brick houses, Bhutanese dzongs, Newar pagoda temples and durbar squares, Sherpa stone houses, flat-roof monasteries of Spiti and Zanskar (Key, Thiksey), Kashmiri dhajji dewari timber framing, Kumaon wooden temples, Mustargi? use Mustang sky-caves as anchor'],
  ['Textile & Craft', 'Central Asian Felt & Ikat Traditions', 'Kyrgyz shyrdak and ala-kiyiz felt carpets, Kazakh syrmak and tekemet, Turkmen carpet gul motifs (Tekke, Yomut, Ersari), Uzbek suzani embroidery, Bukhara abrbandi silk ikat, Margilan atlas and adras ikat, Karakalpak weaving, Tajik chakan embroidery'],
  ['Architectural Style', 'Silk Road Monumental Architecture', 'Samarkand Registan ensembles, Bukhara madrasahs, Khiva Itchan Kala walls, Timurid ribbed domes and pishtaq portals, Central Asian muqarnas, carved wooden doors of Bukhara, ganch carved plasterwork, Kalyan minaret, Khorezm conical minarets'],
  ['Regional & Cultural Tradition', 'Mongolian Nomadic Material Culture', 'Ger (yurt) felt, khana lattice and uni roof-pole decoration, deel dress and khadag ceremonial scarves, morin khuur ornament, ovoo cairns, Mongolian vertical-script calligraphy, saddle and tack silverwork, archery equipment ornament, tanka? use devter lacquered cabinets as anchor'],

  // ===================== SOUTH ASIA =====================
  ['Textile & Craft', 'Indian Resist-Dye & Print Traditions', 'Bandhani tie-dye (Kutch, Saurashtra), leheriya and mothra waves of Rajasthan, Patola double ikat of Patan, Pochampally ikat, Sambalpuri ikat, Ajrakh mud-resist printing, Bagru and Sanganer block prints, Srikalahasti and Machilipatnam kalamkari, Chand? use Bhairavi? omit — keep listed anchors'],
  ['Textile & Craft', 'Indian Embroidery & Weave Traditions', 'Chikankari shadow work of Lucknow, phulkari of Punjab, Kashmiri kashida and sozni, Kutch mirror work (abhla), Bengal kantha, Karnataka kasuti, Toda embroidery, zardozi gold work, Banarasi brocade, Baluchari, Kanjeevaram, Paithani, Chanderi and Maheshwari weaves'],
  ['Regional & Cultural Tradition', 'Indian Folk & Tribal Painting Traditions', 'Madhubani/Mithila painting, Warli ritual wall art, Gond tattoo painting, Bhil dot painting, Pithora of the Rathwa, Bengal and Odisha patachitra, phad scrolls of Rajasthan, Cheriyal scroll painting, Kalighat pat, Sanjhi paper stencils, Saura wall drawing'],
  ['Regional & Cultural Tradition', 'Indian Miniature Painting Schools', 'Mughal atelier painting, Rajasthani courts (Mewar, Kishangarh, Bundi, Kota, Bikaner), Pahari schools (Basohli, Kangra, Guler, Garhwal), Deccani sultanates (Golconda, Bijapur), Company painting, Kalighat bazaar art, Tanjore glass-and-gold painting, Odisha palm-leaf etching'],
  ['Architectural Style', 'Temple Architecture of India', 'Nagara shikhara style (Khajuraho, Lingaraja), Dravida gopuram gateways (Meenakshi, Srirangam), Vesara Hoysala star-platform temples (Belur, Halebidu), Kalinga deul, Kerala timber-roof temples, Chettinad mansions, stepwells (Rani ki Vav, Chand Baori), Shekhawati painted havelis'],
  ['Architectural Style', 'Indo-Islamic & Colonial Indian Architecture', 'Mughal masterworks (Taj Mahal, Fatehpur Sikri, Red Fort), Gujarat Sultanate, Deccani (Gol Gumbaz, Charminar), Awadhi imambara and baradari of Lucknow, Indo-Saracenic (Victoria Memorial, Madras High Court), Portuguese Goa baroque churches, colonial bungalow, Mumbai Art Deco Ovalmaidan? use Oval Maidan anchors'],
  ['Fashion & Dress', 'Indian Dress & Adornment Traditions', 'Regional sari drapes, lehenga-choli and ghagra, salwar-kameez with phulkari dupatta, Rajasthani poshak, temple jewelry of Nagercoil, Jaipur kundan-meenakari, navaratna nine-gem codes, ghungroo anklets, Rajputi aad chokers, Nizam Hyderabadi jewels, mehndi henna patterning'],
  ['Religious & Sacred Art', 'Indian Sacred & Ritual Visual Culture', 'Rangoli and kolam floor geometry, pichwai of Nathdwara, Kerala murals (Guruvayur), Chola bronze icons (Nataraja), ratha temple chariot carving, Kathakali makeup and costume codes, Theyyam face transformation, Bharatanatyam temple dress, Kumartuli Durga idol craft, pandal temporary architecture'],
  ['Music & Sonic Culture', 'South Asian Performance Visual Culture', 'Kathakali and Mohiniyattam costume, Odissi and Bharatanatyam stage aesthetics, qawwali shrine visuals, Manganiar and Langa court-musician dress, Baul wandering-minstrel patchwork, bhangra costume and dhol decoration, nautanki portable staging, Parsi theatre, hand-painted Bollywood hoardings'],
  ['Textile & Craft', 'Pakistani & Bangladeshi Craft Traditions', 'Sindhi ajrak and ralli quilts, Hunza and Chitral embroidery, Balochi doch needlework, Phool Patti truck art, Multan blue pottery, camel-skin lamp craft, Bangladeshi nakshi kantha, jamdani supplementary weft, dhaka muslin legacy, rickshaw painting of Dhaka and Chittagong'],
  ['Regional & Cultural Tradition', 'Sri Lankan & Maldivian Visual Traditions', 'Kandyan dancers dress, temple murals (Kelaniya, Dambulla, Subodharama), Ambalangoda mask carving, Sri Lankan drum decoration, batik workshop culture, Matale lacquer turning, Maldivian liyelaa lacquerwork, feyli? use libaas? omit — keep listed anchors'],
  ['Textile & Craft', 'Northeast Indian Textile Traditions', 'Naga shawl traditions (Ao, Chang, Yimkhiung) and their rank codes, Manipuri phanek and Moirangphee, Mizo puanchei, Tripuri riha, Khasi jainsem cloth, Monpa painting of Tawang, Apatani? use Galo? omit — keep listed anchors plus backstrap loom culture'],

  // ===================== SOUTHEAST ASIA =====================
  ['Textile & Craft', 'Indonesian Textile & Batik Traditions', 'Court batik of Solo and Yogyakarta (parang, kawung, truntum), Pekalongan north-coast batik, Sumba hinggi ikat, Toraja ikat, Balinese endek and perada gold-leaf cloth, Sumatran and Balinese songket brocade, Batak ulos, Mandar Lipa saqbe silk, jumputan tie-dye'],
  ['Regional & Cultural Tradition', 'Indonesian Wood, Metal & Performance Craft', 'Kris dagger pamor damascene patterning, wayang kulit shadow puppet carving, Balinese stone and wood carving, joglo and pendopo Javanese architecture, candi bentar split gates and kori agung, gamelan gong smithing, Barong and Rangda masks, lontar palm-leaf manuscript illustration'],
  ['Textile & Craft', 'Mainland Southeast Asian Textile Traditions', 'Thai pha sin and Isan mat mi ikat, Lao sin weaving with naga motifs, khit supplementary weaving, Burmese acheik wave-pattern warp, Shan longyi, Chin State back-strap weaving, Karen weaving, Hmong batik and paj ntaub applique, Lisu stitching, Kachin manau? use naga? omit — keep listed anchors'],
  ['Regional & Cultural Tradition', 'Thai & Lao Temple and Court Visual Culture', 'Lai thai gilded lacquer and mirror inlay, wat architecture schools (Lanna, Ayutthaya, Rattanakosin), Buddha image styles (Sukhothai walking Buddha, Ayutthaya bronzes), khon masked dance costume, nang yai grand shadow play, Luang Prabang wat murals, golden chedi forms, khrueang su khon ornament sets'],
  ['Regional & Cultural Tradition', 'Vietnamese Craft & Visual Traditions', 'Dong Ho folk woodblock prints, Hang Trong prints, mua roi nuoc water puppet stagecraft, Hue imperial citadel ornament and Nhat Binh robes, ao dai tailoring eras, Bat Trang ceramics, Vietnamese silk painting, non la conical hat regional variants, tru? use cheo? omit — keep listed anchors'],
  ['Textile & Craft', 'Philippine & Malaysian Textile Craft', "T'nalak abaca ikat of the T'boli, inabel Ilocano weaving, pina pineapple fiber with calado openwork, Maranao okir carving and malong tubes, Ifugao ikat and basketry, Yakan seputangan weaving, Malaysian songket and tekat gold embroidery, labu sayong gourd pottery, Kelantan wau kites and wayang kulit, nyonya beadwork"],
  ['Fashion & Dress', 'Peranakan & Straits Chinese Visual Culture', 'Nonya kebaya and sarong, kasut manek beaded slippers, Straits famille-rose nyonya porcelain, kamcheng covered jars, Peranakan shophouse facades (Joo Chiat, Penang), kerongsang brooch triplets, hairpin cukil? use chignon pins anchors, altar and wedding-chamber regalia, beaded table mats culture'],

  // ===================== MIDDLE EAST / WEST ASIA =====================
  ['Textile & Craft', 'Persian Textile & Carpet Traditions', 'Carpet schools of Tabriz, Isfahan, Qom, Kashan, Heriz and Bakhtiari, termeh woven silk, pateh embroidery of Kerman, qalamkar block-printed cotton, Yazd silk brocade, kilim flatweaves, nomadic gabbeh pile, harir? use moreh? omit — keep listed anchors'],
  ['Regional & Cultural Tradition', 'Persian Decorative & Miniature Arts', 'Persian miniature painting (Tabriz, Shiraz, Herat schools), kashi-kari tile mosaic, qalamzani metal engraving, khatam marquetry, firoozeh turquoise inlay, reverse-glass painting, qahveh-khaneh coffee-house painting, Qajar oil portrait conventions, lacquered pen cases (qalamdan)'],
  ['Architectural Style', 'Persian Garden & Court Architecture', 'Chahar bagh quadripartite gardens (Fin Garden, Shazdeh), iwan portals, muqarnas vaulting, Naqsh-e Jahan ensemble of Isfahan, Kashan merchant houses (Borujerdi, Tabatabaei), badgir windcatchers of Yazd, yakhchal ice houses, ab anbar cisterns, caravanserai courtyards, Seljuk brick ornament'],
  ['Textile & Craft', 'Anatolian & Ottoman Craft Traditions', 'Iznik cini ceramics, ebru marbling, tezhip gold illumination, hüsn-i hat calligraphy (thuluth, diwani, ta liq), Hereke silk carpets, Anatolian kilims (Bergama, Konya, Aydin), Canakkale ceramics, cintemani cloud-band motifs, Ottoman goldwork embroidery (Mara? use sarma and tel sirma anchors)'],
  ['Fashion & Dress', 'Ottoman & Turkish Dress Traditions', 'Court kaftans in Bursa silk, entari layering, yemeni embroidered slippers, bindalli goldwork wedding dresses, ferace outerwear codes, Anatolian village costume (Tokat, Maras), Zeybek and Horon dance dress, kebe felt shepherd cloaks, po? use bindalli? covered — add üçetek entari anchors'],
  ['Regional & Cultural Tradition', 'Levantine & Mesopotamian Craft Traditions', 'Palestinian tatreez embroidery regional codes, Bedouin sadu weaving, Damascene silver and wood inlay, Aleppo laurel soap pressing, Iraqi Marsh Arab reed architecture, Kurdish kilims and jajim, Jerusalem Armenian ceramics (Karakashian, Balian), Hebron glassblowing, Levantine? use mashrabiya screen carpentry anchors'],
  ['Architectural Style', 'Arabian Peninsula & Gulf Vernacular Architecture', 'Coral-stone merchant houses of Jeddah Al-Balad, Hijazi rawshan lattice bay windows, Hadhrami tower houses of Shibam and Sanaa, barjeel wind towers of the Gulf, pearling architecture of Muharraq, Al-Ain mud-brick oases, dhow boat decoration, majlis reception interiors, sadu tent dividers'],
  ['Religious & Sacred Art', 'Islamic Sacred Geometry & Calligraphic Arts', 'Girih strapwork geometry, islimi arabesque systems, muqarnas honeycomb vaults, Quran illumination (Mamluk, Timurid, Safavid), mihrab and minbar ornament, bannai square-kufic brickwork, mosque lamp glass (mishkat), prayer-rug design typologies, dome and squinch decoration'],

  // ===================== NORTH AFRICA =====================
  ['Textile & Craft', 'Moroccan Craft & Textile Traditions', 'Zellige tile mosaic, tadelakt burnished plaster, Amazigh carpets (Beni Ourain, Azilal, Boucherouite, Hanbel), Fez embroidery and gold aqad braid, Chouara leather tanning, Safi pottery, Tamegroute green glaze, pierced-brass lanterns, carved Atlas cedar, Rabat kilim'],
  ['Architectural Style', 'Moroccan & Maghrebi Architecture', 'Riad courtyard houses, Saharan ksour (Ait Ben Haddou), kasbah earthen towers, Almoravid, Almohad, Marinid and Saadian arch schools, Sidi Bou Said blue-and-white medina, Nubian vault revival (Hassan Fathy), Ghadames old town oasis housing, Djerba island mosques'],
  ['Textile & Craft', 'Amazigh & Bedouin Adornment Traditions', 'Amazigh silver of Tiznit (fibula tabzimt, enamel and coral), khamsa hand iconography, henna body art sessions, Tuareg cross of Agadez and leatherwork, Siwan embroidery and basketry, Egyptian Bedouin dress codes, guembri and krakeb instrument ornament, Gnaoua? use listed anchors'],
  ['Regional & Cultural Tradition', 'Egyptian Folk & Urban Visual Culture', 'Khayamiya tentmaker applique panels, Coptic iconography and tapestry weaving, Wissa Wassef tapestries, Nubian painted house facades, camel blankets (shamla), Golden-Age cinema poster painting, baladi cafe signage, Shah? use Ramadan khayamiya streetscapes anchors, painted trucks of Upper Egypt'],

  // ===================== SUB-SAHARAN AFRICA =====================
  ['Textile & Craft', 'West African Indigo & Resist Traditions', 'Adire eleko and oniko of the Yoruba, bogolanfini mudcloth of the Bamana, adinkra stamping of the Asante, kente strip weaving (Asante and Ewe), aso oke of the Yoruba, ndop cameroon? use Ndop resist of the Bamum, Korhogo cloth of the Senufo, Baule indigo, Faso dan fani of Burkina Faso'],
  ['Textile & Craft', 'Central, East & Southern African Textiles', 'Kuba shoowa cut-pile raffia cloth, toghu/atogu? use Toghu/Atoghu Cameroon chief embroidery, barkcloth of Uganda, shweshwe printed cotton, Basotho blankets, capulana of Mozambique and Angola, kanga and kitenge of East Africa, samakaka of Angola, sisal? use listed anchors'],
  ['Regional & Cultural Tradition', 'Ndebele & Southern African Wall & Bead Arts', 'Ndebele geometric house painting, Zulu beadwork love-letter codes and isicholo hats, Basotho litema murals, Xhosa umbhaco dress and face paint, Sotho mokorotlo hats, Himba otjize ochre and shell jewelry, Herero ohorokova Victorian dresses, Tsonga xibelani skirts'],
  ['Regional & Cultural Tradition', 'Maasai, Samburu & East African Adornment', 'Maasai shuka and beadwork color semantics, Samburu layered collars, Turkana? use Mursi lip plates and Surma body painting, Ethiopian habesha kemis tibeb borders, Oromo? use Gada? omit — Swahili carved doors of Zanzibar and Lamu, Lamu stone town interiors, kanga inscription culture, kikoy wraps'],
  ['Regional & Cultural Tradition', 'Ethiopian & Eritrean Sacred Visual Culture', 'Rock-hewn churches of Lalibela, Garima Gospels manuscript illumination, processional crosses and tabot tablets, Ethiopian icon panels, Lake Tana monastery murals (Ura Kidane Mehret), Axum stelae, mesob basketry, Harar Jugol walled houses and container decoration, Qene? use listed anchors'],
  ['Religious & Sacred Art', 'West African Sacred Sculpture & Shrine Arts', 'Yoruba orisha shrines and beaded crowns, Benin bronze plaques and commemorative heads, Ife terracotta and copper heads, Asante goldweights, Fon bocio power objects, Bamana chi wara antelope headdresses, Dogon granary doors and dama masks, Senufo firespitter helmets, Kongo nkisi, Fang and Kota reliquary figures'],
  ['Architectural Style', 'Sudano-Sahelian & African Vernacular Architecture', 'Great Mosque of Djenne banco masonry, Timbuktu madrasahs (Djinguereber, Sankore), Agadez and Kano mud mosques, Larabanga mosque, Asante shrine houses, Musgum domed earth huts, Tata Somba fortified houses, Zulu beehive dome huts, Ndebele homestead painting (see wall-art batch), Venda? use listed anchors'],
  ['Music & Sonic Culture', 'African Popular Music Visual Culture', 'Highlife album cover art, Congolese rumba sapeur dandyism (La Sape), Fela Kuti afrobeat stage dress and Lemi Ghariokwu album covers, soukous stage fashion, mbalax concert visuals, Addis groove-era Ethiopian jazz vinyl, township jive and isicathamiya imagery, kwaito and amapiano streetwear, griot dress'],
  ['Textile & Craft', 'African Wax Print & Fabric Economies', 'Fancy/real wax print history from Javanese batik, VLISCO design culture, super-wax and Hollandais grades, commemorative and political wax designs, kitenge adaptations, market fashion economies of Accra, Lagos and Dar es Salaam, obroni wawu second-hand trade'],
  ['Regional & Cultural Tradition', 'African Hair & Body Adornment Culture', 'Cornrow and braid pattern histories, Yoruba hair naming traditions, gele sculptural headties, agbada embroidery economies, barbershop signage painting of Ghana and Nigeria, threading hair-texturing techniques, Wodaabe gerewol face painting, Surma body painting, Zulu? use listed anchors'],

  // ===================== OCEANIA =====================
  ['Regional & Cultural Tradition', 'Maori Visual & Material Culture', 'Whakairo meeting-house carving (maihi, amo, poutokomanawa), kowhaiwhai painted rafters, tukutuku lattice panels, ta moko and kirituhi tattoo, pounamu hei matau and hei tiki, koru spiral forms, waka carving, kahu huruhuru feather cloaks and korowai, marae display protocols'],
  ['Textile & Craft', 'Polynesian Barkcloth & Quilting Traditions', 'Tongan ngatu, Samoan siapo, Fijian masi, Hawaiian kapa beating and watermarking, Cook Islands tivaevae quilting circles, Hawaiian snowflake quilts, lauhala pandanus weaving, Tuvaluan fans and mats, Niue hiapo barkcloth, Tokelau? use listed anchors'],
  ['Regional & Cultural Tradition', 'Melanesian Ritual & Material Culture', 'Malagan carvings of New Ireland, Asmat poles and shields, Sepik Haus tambaran spirit houses and Iatmul orators stools, Abelam yam masks, kula valuables (mwali armshells, bagi necklaces), Vanuatu sand drawing grades, Fijian tabua whale teeth, Solomon Islands feather money (tevau), Lapita dentate stamping'],
  ['Regional & Cultural Tradition', 'Aboriginal Australian Art & Country', 'Papunya Tula dot painting and the Western Desert movement, Arnhem Land x-ray painting and rarrk crosshatch, Wandjina rock faces, Gwion Gwion (Bradshaw) figures, Tiwi tutini grave poles and ochre, Utopia and Ernabella batik movements, sand stories, pandanus weaving of Maningrida'],
  ['Fashion & Dress', 'Pacific Islander Dress & Adornment', 'Samoan pea and malu tattoo, puletasi and elei printed cloth, Tongan ta ovala mats and kiekie, Fijian sulu, ei flower crowns of the Cooks, Hawaiian lei and aloha wear, Pasifika festival dress, mermaid? omit — keep listed anchors plus pandanus waist mats'],

  // ===================== NORTH AMERICA INDIGENOUS =====================
  ['Textile & Craft', 'Navajo & Southwest Textile & Silver Traditions', 'Navajo rug periods (chief blankets, Germantown, Two Grey Hills, Ganado red), Pueblo weaving, Rio Grande and Saltillo serapes, Zuni inlay and needlepoint, Hopi overlay silverwork, Maria Martinez black-on-black pottery, Santa Clara carved ware, Jicarilla micaceous clay, sandpainting imagery'],
  ['Regional & Cultural Tradition', 'Northwest Coast Formline Art', 'Haida formline (ovoid and U-form) composition, Tlingit chilkat weaving and button blankets, Kwakwakawakw transformation masks and Hamatsa regalia, bentwood boxes, totem poles of Haida, Tsimshian and Coast Salish, Salish spindle whorls, Edenshaw-era silver engraving, coppers shields'],
  ['Regional & Cultural Tradition', 'Plains & Woodlands Beadwork & Regalia', 'Plains porcupine quillwork, Lakota and Crow beaded regalia, cornhusk bags, Iroquois raised beadwork whimsies, Seminole patchwork clothing and dolls, Cherokee double-weave baskets, Ojibwe birchbark biting and floral beadwork, Metis flower-beadwork tradition, wampum belt diplomacy'],
  ['Regional & Cultural Tradition', 'Arctic & Subarctic Visual Culture', 'Kinngait (Cape Dorset) printmaking, Inuit soapstone and antler carving, amauti parkas and kamiks, Yupik masks and ceremony objects, Unangan bentwood hats, Alaska Native ivory scoring? use scrimshaw? omit — birchbark canoe ornament, beadwork? use listed anchors plus qulliq lamp aesthetics'],
  ['Regional & Cultural Tradition', 'Ancient Mesoamerican & Andean Visual Systems', 'Maya codices and glyphic stelae, Mexica featherwork and codices, Mixtec gold and turquoise mosaics, Moche fineline pottery, Nazca textiles and geoglyphs, Paracas mantles, Inca tocapu square motifs and khipu cords, Chimu? use Chancay? keep listed anchors, Marajoara and Tapajonic pottery'],
  ['Textile & Craft', 'Mexican Folk Art & Craft Traditions', 'Talavera Poblana, Mata Ortiz pottery, Wixarika (Huichol) yarn painting and beadwork, Otomi tenango embroidery, Oaxacan alebrijes, barro negro of San Bartolo Coyotepec, papel picado banners, hojalata tin art, Catrina figures, Chiapas amber and huipiles, Eisen? use Tonala burnished ware anchors'],
  ['Textile & Craft', 'Maya & Central American Textile Traditions', 'Guatemalan huipiles (San Antonio Aguas Calientes, Chichicastenango), corte skirts and tzutes, jaspe ikat, Chiapas huipiles of Zinacantan and San Juan Chamula, Guna mola reverse applique, Lenca pottery, Maya backstrap loom culture, cinta headbands, quexquemetl? keep as anchor'],

  // ===================== LATIN AMERICA & CARIBBEAN =====================
  ['Regional & Cultural Tradition', 'Mexican Popular & Festival Visual Culture', 'Dia de Muertos ofrendas and cempasuchil decoration, La Catrina iconography, lucha libre masks and poster lettering, charreria traje charro, mariachi dress codes, exvoto retablo paintings, pulqueria and cantina murals, Mexican calendar art, papel picado (see craft batch), rotulista hand lettering'],
  ['Regional & Cultural Tradition', 'Andean Textile & Festival Material Culture', 'Shipibo kene design system, Taquile and Cusco pallay weaving, Bolivian aguayo and chuspa, regional ponchos, Paucartambo and Diablada festival masks, retablo ayacuchano boxes, mate burilado carving, toritos de Pucara, Qero textile codes, aymara? use listed anchors'],
  ['Regional & Cultural Tradition', 'Brazilian Popular & Folk Visual Culture', 'Literatura de cordel and xilogravura woodcuts, frevo umbrellas and masks, maracatu crowns and capes, capoeira visual culture, congado regalia, Folia de Reis banners, bumba meu boi embroidered skins, samba-school allegorical craft, fitas do Bonfim wish ribbons, northeastern clay figurative craft'],
  ['Regional & Cultural Tradition', 'Caribbean Sacred & Festival Visual Culture', 'Haitian Vodou drapo sequin flags, veve cornmeal drawings, Saint Soleil and Cap-Haitien painting schools, Croix-des-Bouquets iron-cut sculpture, Trinidad carnival wire-bending and fancy sailor mas, Cuban rumba and cabaret imagery, Lucumi bead collars (ileke), santos de palo carving and vejigante masks, diablos cojuelos'],
  ['Regional & Cultural Tradition', 'Rioplatense & Southern Cone Visual Culture', 'Fileteado porteno sign painting, mate gourd and bombilla silversmithing, facon and boleadoras ornament, gaucho poncho and chiripa dress, estancia silver tack, tango-era poster and sheet-cover art, Chilean arpilleras, cueca dress, Mapuche silver (trapelakucha) and nimin textile borders, pais? use listed anchors'],

  // ===================== EUROPE =====================
  ['Regional & Cultural Tradition', 'Scandinavian Folk Painting & Craft', 'Rosemaling styles (Telemark, Hallingdal, Rogaland), Swedish dalmalning and kurbits, Dalahäst carving, Finnish ryijy rugs, Halsingland painted farmhouses, mangle boards, flattsnideri chip carving, lusekofte and Marius sweaters, bunad silver brooches, painted? use listed anchors'],
  ['Regional & Cultural Tradition', 'Sami Duodji Craft Culture', 'Gakti dress and silver belts (solae? use belt hooks and silver buttons), pewter-thread embroidery (tenntradsbrodering), guksi/kuksa birch cups, reindeer-leather work, duodji knife ornament, lavvu tent form, noaidi drum iconography (historical), Sami? use listed anchors plus gallo? omit'],
  ['Architectural Style', 'Nordic Vernacular Architecture', 'Stave churches (Urnes, Borgund), turf-roofed farmhouses of Sogn and the Faroes, lafte log construction, Icelandic and Faroese turf houses, Falu red farmsteads, Halsingland farmhouse interiors, Finnish church villages (Petajavesi), Finnish? use listed anchors'],
  ['Textile & Craft', 'Baltic Textile & Ornament Traditions', 'Latvian Lielvarde belt symbolism, Baltic mitten pattern traditions, Lithuanian sodai straw gardens, marguciai egg decorating, national costume ornament bands, Jurmala wooden architecture, Vilnius Baroque, Lithuanian cross crafting and Hill of Crosses, Seto? use listed anchors'],
  ['Regional & Cultural Tradition', 'Russian Folk Lacquer, Wood & Ceramic Arts', 'Khokhloma painting, Gzhel blue ceramics, Palekh, Mstera and Kholuy lacquer miniatures, lubok broadside prints, matryoshka painting schools, Vologda lace, Orenburg downy shawls, Pavlovo Posad printed shawls, Rostov finift enamel, Dymkovo clay toys, Bogorodskaya carved toys'],
  ['Regional & Cultural Tradition', 'Ukrainian Folk Visual Culture', 'Vyshyvanka embroidery regional codes, pysanka egg writing, vinok floral crowns, Petrykivka decorative painting, Kosiv painted ceramics, Hutsul wood and metal inlay, rushnyk ritual cloth, vytyanka papercuts, opinka? use listed anchors plus lizhnykar? use Hutsul wool blankets'],
  ['Regional & Cultural Tradition', 'Polish, Czech & Slovak Folk Arts', 'Wycinanki papercuts (Lowicz, Kurpie), Lowicz stripes, Podhale parzenica embroidery, Krakow szopki nativity scenes, Detva and Slovacko kroj embroidery, Moravian painted furniture, Slovak ceramics (Modra), Czech? use Hanakia? keep listed anchors, cepelia era craft'],
  ['Regional & Cultural Tradition', 'Balkan & Southeast European Folk Arts', 'Bulgarian shevitsa embroidery and kukeri fur-mask costume, Pirot kilims, Serbian opanci and sajkaca, Croatian Konavle embroidery, Bosnian zlatovez goldwork, Albanian xhubleta bell skirt and qeleshe caps, Galichnik wedding dress of Macedonia, Vlach? use listed anchors'],
  ['Regional & Cultural Tradition', 'Romanian Folk Visual Culture', 'Bucovina painted monasteries (Voronet blue), Maramures wooden churches and carved gates, Romanian ia blouse embroidery, Horezu ceramics, Cucuteni motif revival, Transylvanian Saxon walled churches, Moldavian scoarte wall carpets, capra and mascati mask costume, ie? covered — add broboade? keep listed anchors'],
  ['Regional & Cultural Tradition', 'Celtic Insular & Revival Visual Culture', 'Insular manuscripts (Book of Kells, Lindisfarne Gospels), Celtic interlace and knotwork, high crosses (Muiredach, Ahenny), Pictish symbol stones, Tara brooch and Ardagh chalice metalwork, Celtic Revival design, Harry Clarke stained glass, Claddagh ring, Aran stitch culture, Fair Isle and Shetland lace, Welsh carthen tapestry and lovespoons, tartan dress codes'],
  ['Regional & Cultural Tradition', 'Iberian Tile & Folk Traditions', 'Azulejos of Seville, Lisbon and Porto, Portuguese filigree (Viana hearts), calcada portuguesa paving, traje minhoto, manton de Manila shawls and flamenco dress, peineta combs, Talavera de la Reina and Puente del Arzobispo ceramics, Fajalauza Granada ware, Minho? use listed anchors'],
  ['Regional & Cultural Tradition', 'Italian Regional Folk & Craft Traditions', 'Sicilian carretto carts and pupi marionettes, maiolica schools (Deruta, Faenza, Gubbio, Montelupo), Venetian masks and forcole oarlocks, Florentine pietra dura commesso, Neapolitan presepe nativity craft, trulli of Alberobello, sassi of Matera, Sardinian Mamuthones masks and Samugheo carpets, Palio banner craft'],
  ['Regional & Cultural Tradition', 'French Regional Folk Traditions', 'Provencal santons, indiennes printed cottons (Souleiado tradition), Quimper faience, bigouden headdresses, Aubusson tapestry, Limoges enamel, Alsatian costume and Soufflenheim pottery, Basque makhila walking sticks, Breton? use listed anchors plus toile de Jouy as anchor'],
  ['Regional & Cultural Tradition', 'Alpine & German Folk Craft', 'Luftlmalerei facade painting, Tracht costume codes (dirndl, lederhosen), Black Forest cuckoo clocks and wood carving, Erzgebirge toys and Schwibbogen arches, Maibaum maypole decoration, Basel Fasnacht and Krampus/Perchten masks, Appenzell folk painting, Bavarian? use listed anchors'],
  ['Regional & Cultural Tradition', 'Dutch & Low Countries Decorative Traditions', 'Delftware blue-and-white, polychrome and biblical tile series, Hindeloopen painting and costume, Frisian silver and skip? use Frisian clock? keep Hindeloopen and Delft anchors, Brussels and Mechelen bobbin laces, Zeeland? use costume caps anchors, Maastricht? use listed anchors plus tulipware'],
  ['Regional & Cultural Tradition', 'Greek & Aegean Visual Traditions', 'Cycladic marble figurines, Cycladic whitewashed island architecture, Karagiozis shadow theatre, Amalia dress and evzone foustanela codes, Greek folk embroidery, Chios pebble-mosaic courtyards, Skyrian frescoed house interiors, Hydra naval mansions, Dodecanese? use listed anchors'],
  ['Regional & Cultural Tradition', 'Jewish Material & Ritual Visual Culture', 'Hebrew illuminated manuscripts (Birds Head Haggadah), ketubah illumination, Jewish papercut traditions, Hanukkah lamp typologies, Bezalel school craft, wooden synagogues of the Polish-Lithuanian Commonwealth, Moorish Revival synagogues, parokhet ark curtains, Havdalah spice boxes and Kiddush cups, Yiddish theater posters'],
  ['Architectural Style', 'Russian & Slavic Vernacular Architecture', 'Wooden architecture of the Russian North (Kizhi pogost), onion domes and kokoshnik gables, izba houses with carved nalichniki window frames, terem upper chambers, Dacha? use dacha ornament anchors, Cossack? use listed anchors'],
  ['Architectural Style', 'Mediterranean Island & Coastal Vernacular', 'Maltese limestone architecture and luzzu eye prows, Dalmatian stone towns (Dubrovnik, Korcula), Cypriot Lefkara lace and folk architecture, Aegean? covered — Balearic finca courtyards, Corfu Venetian wellheads? use listed anchors plus Sardinian? use nuraghe as anchor'],
  ['Furniture & Product Design', 'Nordic Modern Design Traditions', 'Danish modern masters (Wegner, Finn Juhl, Panton), Finnish bentwood and glass (Aalto, Wirkkala, Sarpaneva, Aarnio), Swedish grace and Bruno Mathsson, Marimekko print culture, Iittala and Arabia tableware, teak? use listed anchors plus Fjord? omit'],
  ['Furniture & Product Design', 'Mid-Century National Design Schools', 'Olivetti studio aesthetics, Italian mid-century industry (Artemide, Kartell), Sori Yanagi and Japanese modern craft-design, MUJI anonymous design, Oscar Niemeyer furniture, Pierre Jeanneret Chandigarh chairs, Eames-era American modern, Czech? use listed anchors'],

  // ===================== GRAPHIC / TYPOGRAPHIC CULTURES =====================
  ['Graphic Design', 'National Typographic Traditions', 'Fraktur and blackletter print culture, Didot and French classical typography, Bodoni and Italian rationalism, wood-type poster lettering of the Americas, Japanese vertical composition (tate-gaki) and Edo typesetting, Ming/Song Chinese typefaces, Hangul typography design, Dutch book typography, American gothics and sign-painting caps'],
  ['Graphic Design', 'National Poster Traditions', 'Polish poster school (Cieslewicz, Lenica, Swierzy), Cuban ICAIC film posters, Japanese poster design (Ikko Tanaka, Kazumasa Nagai), Czech film poster school, Finnish transit posters (Erik Bruun), Swiss? covered by international style — use Polish, Cuban, Japanese, Czech, Finnish, and Addis? omit'],
  ['Graphic Design', 'Hand-Painted Signage & Vernacular Lettering', 'Indian film-banner painting, Ghanaian barbershop and evangelical signage, Pakistani truck lettering (see craft batch), gilded-glass and circus lettering of US/UK sign painters, Mexican rotulismo, lambe-lambe poster paste-up culture of Brazil, market? use listed anchors'],
  ['Graphic Design', 'Stamp, Currency & Engraved Print Cultures', 'Engraved postage-stamp traditions (Czeslaw Slania, Czech art stamps), commemorative stamp design waves, banknote guilloche and vignette engraving, first-day-cover design, revenue? use listed anchors plus airline? omit'],

  // ===================== MODERN / DIASPORA / FUSION =====================
  ['Regional & Cultural Tradition', 'Chinatown & Diaspora Visual Culture', 'Paifang gateways, bilingual neon and hand-lettered signage, Chinatown lantern strings, pagoda-roof commercial architecture, Hong Kong neon streetscapes, dim sum trolley and banquet aesthetics, Chinese-Chilean? omit — use listed anchors plus Chinatown pharmacy and butcher signage codes'],
  ['Regional & Cultural Tradition', 'Italian-American & Feast Visual Culture', 'Giglio feast towers, San Gennaro street festa decoration, red-sauce restaurant interiors, Italian market signage, bocce club aesthetics, Catholic street altars and luminaria, feast-light? use listed anchors'],
  ['Subculture Style', 'Global South Urban Street Aesthetics', 'Kenyan matatu graffiti and airbrush culture, Philippine jeepney chrome and decal art, Colombian chiva buses, Haitian tap-tap painting, Senegalese cars rapides, Havana vintage-car culture, Lagos danfo placard language, Accra? use listed anchors'],
  ['Subculture Style', 'Diaspora & Contemporary Urban Fashion Waves', 'Accra-Lagos-Dakar street style scene, desi diaspora streetwear fusion, Nollywood poster painting, khaleeji abaya fashion economies, Seoul street fashion tribes, Harajuku? covered in Tokyo batch — use listed anchors plus Caribbean? use dancehall fashion as anchor'],
  ['Regional & Cultural Tradition', 'Roma & Traveller Material Culture', 'Vardo wagon carving and decoration, Romani dress traditions of Central Europe, Roma market floral textile economies of Hungary and Slovakia, horse-fair culture (Appleby), atsingani? omit — keep listed anchors with respectful documentation focus'],
  ['Regional & Cultural Tradition', 'Pilgrimage Visual Cultures', 'Camino de Santiago scallop iconography and yellow arrows, Kumbh Mela flags and sadhu regalia, Hajj ihram plainness and kiswa calligraphy, Shikoku henro white robes and stamp books, processional? use listed anchors plus Saint? use Lourdes candle imagery as anchor'],
  ['Regional & Cultural Tradition', 'Culinary Presentation Aesthetics', 'Washoku and kaiseki plating codes, dim sum craft presentation, Indian thali arrangement geometry, Korean banchan layout, mezze spread composition, New Nordic plating, Moroccan tagine service, Oaxacan market presentation, bento composition principles, high-tea? use listed anchors'],
]
